### ISSUE TITLE
Links in Comment or descriptions to open on a new tab/page

### ISSUE THREAD

**Issue by deliciousbob** [kanboard/kanboard#1003]
Hallo Frederice,

is it possible to open links that are converted in the markdown language to open in an external page or tab.
```
<a href="http://www.primagaz.at/">external link</a>//
```
Is it possible to add **target="_blank"** automaticly on every link ? Which file could i edit to test this on my local installation?

Thank you and beste regards from Austria
Robert

**Comment by sparkles645** [comment]
Click the link with scroll-wheel = opens in new tab?

**Comment by deliciousbob** [comment]
:) thanks for the info, i've never used the scroll wheel to click a link.
But is there a way to get markdown to ad target="blank" on every link ? 
I found some jquery scripts but there must be an way to do it in the markdown code ?
Best regards Robert

**Comment by fguillot** [comment]
You have to create a new extension to Parsedown (Markdown parser used by Kanboard).

You will probably need to touch this file: https://github.com/fguillot/kanboard/blob/master/app/Core/Markdown.php
