### ISSUE TITLE
Provide time-based events for automatic actions 

### ISSUE THREAD

**Issue by jakoubek** [kanboard/kanboard#1017]
I use automatic actions very much. What I miss are event types that are triggered in combination with the period of time gone since another event in the past (such as a specific transition).

One example:

Event: If a task has been in the column "Customer approval" for >= 7 days, then
Action: Move it to column "Done"

I know that a PHP app only *lives* while a request triggered by a browser or another kind of client. These events would an ideal candidate for cron jobs.

**Comment by BlueTeck** [comment]
Regarding the cron job, there is already a command line interface https://github.com/fguillot/kanboard/blob/master/docs/cli.markdown 
to collect daily information for analytics,

(link #463)

**Comment by fguillot** [comment]
This automatic action is now available in the development branch.
