### ISSUE TITLE
Import single tasks from Github

### ISSUE THREAD

**Issue by oparoz** [kanboard/kanboard#1018]
I would find it useful to be able to add tasks coming from different Github repositories, even if I'm not an admin in all of them.

I wouldn't expect my changes in Kanboard to be sent back since I wouldn't have write access, but it would help manage all these tasks with one board instead of 10.

Ideally, I should be able to pick tasks from the list of issues I participate in, but for starters, I think just being able to paste an issue URL and have it automatically added, with comments, would be great.

**Comment by fguillot** [comment]
This plugin allows you to import any Github Issues: https://kanboard.net/plugin/github-frontend
