### ISSUE TITLE
Attachments not copied when project duplicated

### ISSUE THREAD

**Issue by uhcttam** [kanboard/kanboard#1030]
First off, I love this tool. Thanks for creating such an intuitive piece of software. One thing I noticed is that when I copy a project and select for everything to be duplicated, all task attachments that were present in the original project are missing in duplicate copy.  Is there anyway to make the duplicate copy a true clone of the original (attachments and all)?

Thanks

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
