### ISSUE TITLE
Creating tasks by email: attach email attachments as documents to the newly created task

### ISSUE THREAD

**Issue by jakoubek** [kanboard/kanboard#1033]
At least Mailgun's API delivers the attachments of the incoming email in its JSON data structure:

```
"attachments": [
  {
    "size": 79892,
    "content-type": "image/jpeg",
    "filename": "test.jpg"
  }
]
```

The Mailgun handler (in [app/Integration/Mailgun.php](https://github.com/fguillot/kanboard/blob/master/app/Integration/Mailgun.php)) only uses the email subject and body to create a new task.

How about attaching the email attachments to the newly created task? Maybe the user wants to configure the allowed file types somewhere in the settings.

**Comment by thob** [comment]
:+1:  I second that. Attached screenshots help a lot for ticketing in support and it's cumbersome to add then after the fact

**Comment by fguillot** [comment]
Email attachements are now supported for all email plugins (Mailgun, Sendgrid and Postmark). You have to use the latest version of each plugin, and at least Kanboard v1.0.39.
