### ISSUE TITLE
[FR] iCalendar VTODO

### ISSUE THREAD

**Issue by BlueTeck** [kanboard/kanboard#1045]
Hi all,

at the moment there is a ics feed with events. It is very nice to include them into my calendar.

To see my Kanboard Tasks in todo-apps it would be nice if the tasks are exportet as VTODO object too. Unfortunately the current used libary does not support this feature.

https://en.wikipedia.org/wiki/ICalendar -> VTODO

Thanks,
Timo

**Comment by fguillot** [comment]
I don't really have time to develop this feature. If you really need that, the best way is to contribute.
