### ISSUE TITLE
Add Assignee to a task when Gitlab's issue was created

### ISSUE THREAD

**Issue by nlevchuk** [kanboard/kanboard#1047]
Hi everyone!

I have the following configuration at automatic actions page:
Gitlab issue opened  ->  Create a task from an external provider

Is there way to use username from Gitlab and assign it to a created task (if gitlab's username and project's username are equal) ?

**Comment by arufanov** [comment]
Dear support,

Thanks you for production. I use it and happy, but have the same problem as @nlevchuk . It would be great to have this feature.

Artem.

**Comment by fguillot** [comment]
Issues related to Gitlab should be posted here: https://github.com/kanboard/plugin-gitlab-webhook/issues
