### ISSUE TITLE
Please add the task moving with keyboard

### ISSUE THREAD

**Issue by TheIndifferent** [kanboard/kanboard#1058]
Hey,

First of all, Kanboard is the best, thank you very much for doing it! Soon the big part of our team will use it, if not entire team. No idea why everyone likes trello, it does not even has swimlanes.

But dragging tasks with the mouse gets tricky sometimes. Could you please add the following feature:
- arrows are moving focus between tasks
- shift+left/right arrow moves the task to next or previous column.
- had no need to do it yet, but maybe also moving one swimlate up or down with shift+up/down will not be much trouble as well?...

Thanx again!

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
