### ISSUE TITLE
Some improvement requests

### ISSUE THREAD

**Issue by PhilJung** [kanboard/kanboard#1059]
Hi \* and thanks for this product.
I would like to submit some requests:

Maybe it could be good to allow disabling of some features (budget management for example). Goal is to keep the user interface as simple as possible ;

About the workflow between gitlab (or other) and kanboard: gitlab will receive lot of issues. One solution is to consider that the triage of each issue is a task to manage in the kanban. But I think it will be overkill. So I would like kanboard to be able to synchronise issue <-> tasks only when a given criterion is met. For exemple, if I put a tag Kanban or Backlog in gitlab, then it means synchronisation is useful.

I would like a reverse integration: If I manage my product from the backlog, adding kanban tasks, then I could be able to push them to gitlab as feature requests issue. So from a "manager" point of view, kanboard is the only thing to watch and from a dev point of view, gitlab is the only thing to watch

I would review gitlab integration samples : the order of 'What to do' / 'What trigger' is different in user interface and in sample.

About the automatic actions (need to better check if it already exists, but just in case): could be good to have a "when these gitlab fields are at this value" then "set kanboard these fields to these values".

About the automatic actions, I know I have gitlab so many possible actions could be disabled because they have no "When xxxxxxx happens in Gitlab". So it could be good to get a filter where I select "Gitlab" and only "What to do" that can be trigger by gitlab stays.

Philippe

**Comment by fguillot** [comment]
Closing this ticket due to inactivity.
