### ISSUE TITLE
Telegram Bot integration

### ISSUE THREAD

**Issue by antonioseric** [kanboard/kanboard#1062]
It will be great to have telegram integration in kanboard. To receive notifications on project changes.

**Comment by fguillot** [comment]
What is telegram? https://telegram.org/ right?

**Comment by antonioseric** [comment]
Yes. And here is documentation about telegram bot https://core.telegram.org/bots
There are also many open source implementations for telegram bot api..

**Comment by vlebo** [comment]
+1 for integration with telegram

**Comment by thob** [comment]
+1

**Comment by sah-anshu** [comment]
+1

**Comment by valessiobrito** [comment]
+1

**Comment by cmmata** [comment]
+1

**Comment by valessiobrito** [comment]
Using PaqueBOT[1]  it's possibile alerts from feed RSS and create alternative integrations with 

[1] https://telegram.me/paquebot - "Create your own community bots for Telegram, without server, without code, from a simple interface: a Telegram chat."

**Comment by thob** [comment]
with the RSS feed you'd get everything (not only those assigned to you)

**Comment by thob** [comment]
there's a Tg bot that might help to get notifications https://trafficrobot.tk/

**Comment by thob** [comment]
I think having the same notifications as in email is a start.

**Comment by vstrava** [comment]
+1

**Comment by leandrodb** [comment]
I think it would be easy to adapt/fork on of the chat plugins (slack, hipchat, rocketchat) to integrate Telegram

**Comment by magnific0** [comment]
A very crude solution is to use Slack plugin and https://github.com/Eleirbag89/TelegramBotPHP. The Slack plugin uses webhooks, so it is simple to call an external script which sends a message using the Telegram bot. Below is the example script that I use, make sure to set a channel / user name under "Integrations" for each user and board.

```
<?php

// Array that matches "channel" (user / board) to user / group chat ids. 
$chat_id_arr = array("USER1" => 100000000, "USER2" => 90000000, "BOARD1" => -10000000, "BOARD2" => -200000000);

// Token as given by @botfather
$bot_id = "300000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

// Get the message from Kanboard Webhook call
$msg = json_decode(file_get_contents('php://input'), true);

// If the specified channel exists in our simple lookup array, send the message.
if (array_key_exists($msg["channel"], $chat_id_arr)) {

    $chat_id = $chat_id_arr[$msg["channel"]];

    include("Telegram.php");
    $telegram = new Telegram($bot_id);
    $content = array('chat_id' => $chat_id, 'text' => $msg["text"]);
    $telegram->sendMessage($content);
} else {
    // Otherwise store the message for debug purposes.
    file_put_contents("msg/" . uniqid() . ".json", json_encode($msg));
}

?>
```

**Comment by DaBlitzStein** [comment]
+1

**Comment by filhocf** [comment]
@magnific0 , I'm not sure what you have. Do you already have this integration using this lack of code? If yes, can you give more info about?

**Comment by fguillot** [comment]
I'm closing this ticket. I let the community develop a Telegram plugin.

**Comment by manuvarkey** [comment]
I have written a telegram integration for receiving individual/project notifications similar to slack/jabber integration. Check it out from here.

https://github.com/manuvarkey/kanboard-plugin-telegram
