### ISSUE TITLE
add subtasks using automation when task moved to a specific column

### ISSUE THREAD

**Issue by trustserve** [kanboard/kanboard#1072]
Would like to have a set of subtasks autoassigned when task is put in a column. I find that certain projects have a whole set of subtasks. Would like to move project through a flow and add subtasks at each step to do.

**Comment by trustserve** [comment]
might there be away to trigger a webhook when moving a task to a category that then adds a subtask to that task?

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
