### ISSUE TITLE
Multiple LDAP sources

### ISSUE THREAD

**Issue by whitealsonerdy** [kanboard/kanboard#1073]
Hi, everything is working great with a single LDAP source (using AD in my case).  Are multiple LDAP sources supported?  My company has two separate domains and two separate AD servers.  I tried to add another set of config lines in config.php and also adding mutliple values to the same line, but it seems to only pick up the first reference.  For example:  

define('LDAP_SERVER', 'ldaps://ldap.domain1.com', 'ldaps://ldap.domain2.com');

define('LDAP_USERNAME', 'account@domain1.com', 'account@domain2.com');

and so on.  

I was hoping it would do a lookup in the first server and if it failed move on to the second server.  

Is this supported?  Or am I just not configuring it correctly?  Thanks!

**Comment by fguillot** [comment]
It's not implemented.

**Comment by whitealsonerdy** [comment]
Thanks for verifying.  I can workaround by using local accounts until we merge our AD domains.

**Comment by owenmica** [comment]
Is it possible to use LDAP on AD with 2 paths in the same forest? Ex. OU=Users OU=Admins

**Comment by Pecadis** [comment]
Hi  @fguillot i have the same problem on my Company like @whitealsonerdy .
It would be great if you could implement something like that into your awesome Tool.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding

**Comment by Cheatha** [comment]
I've got the same problem. Would be great to see such a plugin. Multiple LDAP Sources are fairly common in corporate environments.

**Comment by ElucGeek** [comment]
Hello, just to add that we are stuck for the same issue in my company. How hard would be to build such plugins ?
