### ISSUE TITLE
edit right away with 1 click on description or (sub)task etc

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#1074]
feature request

**Comment by elfalem** [comment]
+1 This would be more efficient.

**Comment by shimza** [comment]
+1 seems current normal practice everywhere now.

**Comment by DoumeDuSud** [comment]
they are a risk that to have a to complicated interface with to much posibility

if you clic on the number of a task you already have some direct editing link

**Comment by oparoz** [comment]
> if you clic on the number of a task you already have some direct editing link

Yes, but when viewing the task itself, it's slowing us down to have to use the menu all the time, when we have a bunch of edits to perform.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
