### ISSUE TITLE
New value needed for portfolio management: value in EUR or USD

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#1100]
If you create sales pipelines you need values. Later on stats too. The base is the deal value, of course

**Comment by fguillot** [comment]
Please provide details, examples/use cases... you speak Chinese for me.

**Comment by thob** [comment]
If I use a task as a deal (project) I'd need an extra value field. This way I can have a board for lead (deal)  management. Of course I need values for each project (deal)  -  see http://pipedrive.com

**Comment by fguillot** [comment]
Some people use the complexity field for that.

**Comment by fguillot** [comment]
Closing this ticket due to inactivity and lack of interest by the community.
