### ISSUE TITLE
[Inprovement] export on a pdf file to send report

### ISSUE THREAD

**Issue by DoumeDuSud** [kanboard/kanboard#1107]
_first thanks to @fguillot and all over contributor for the great job, I use kanboard since 1 year & half and I see the great evolution of this great tool_

I will be very intresting for 1 feature : **export a task, a swinglane even a project to a PDF file**
And if it possible to go further :
- to have the possibility of changing the template of the PDF file
- in the export a swinglane or a project to export the task regarding a ditermine people or team
- to select witch part of a task will be export (comment yes/no; attachment yes/no; ...)

The reason is that I help on a association and we done manual job with no computer around, so it will be usefull to be able to export and print.
It could be also usefull for those want to send/store a repport at a dedicat moment for archive.

Thanks a lot

**Comment by fguillot** [comment]
Merged with #2650
