### ISSUE TITLE
Change columns - display current number of tasks

### ISSUE THREAD

**Issue by eurodrew555** [kanboard/kanboard#1112]
When changing columns, it would be useful to see the current number of tasks next to the task limit. This would also help prevent removing a column that contains tasks.

Also, when you actually do go to remove a column, it would be great if Kanboard could confirm that this column contains X number of tasks. Again, this would help prevent accidentally removing a column that contains tasks (and therefore deleting them).

Thanks!

**Comment by fguillot** [comment]
This features are available.

**Comment by radimoto** [comment]
Thank you! Much appreciated.

**Comment by eurodrew555** [comment]
Thank you! Much appreciated.
