### ISSUE TITLE
Use link meanings in Calendar and Gantt views

### ISSUE THREAD

**Issue by oliviermaridat** [kanboard/kanboard#1114]
The link "Task #A blocks Task #B" implies that task #A shall be done before task #B. Therefore, even if task #B does not have a "Start date", it can be displayed after task #A in the calendar or the Gantt views.

The link "Task #A targets milestone Task #B" implies that task #A shall start after the beginning of task #B and shall be finished after the end of task #B. Therefore, even if task #A does not have any "Start date" or "Due date", it can be displayed between task #B start and due dates in the calendar and the Gantt views.

Do you think it is a good idea. It may be quite tricky to perform.

**Comment by Marc083** [comment]
this is a basic requirement for managing tasks in a project IMO.
a must have feature indeed.

**Comment by oliviermaridat** [comment]
I have an example of implementation here: @e4a94a7db12728cb0e4648df551720425f82f7ae

It works well but depends on the milestone feature #1009 (not necessarily though), and maybe quite hacky. One or two SQL additional queries per task in the Gantt diagram is maybe not ideal.

**Comment by oliviermaridat** [comment]
The main issue of my implementation proposal in terms of usability, is the miss of "inheritance". Here is an example:
If task #A is blocked by task #B which targets task #C which starts on December (2015-12-25), then task #B will be displayed on the Gantt chart to start also the 2015-12-25, but task #A will still start today and not in December, because task #B does not really have a start date.

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
