### ISSUE TITLE
notification not all changes

### ISSUE THREAD

**Issue by Vladimir-Kartashov** [kanboard/kanboard#1126]
How to configure notifications? For example, to not send notifications when change color.

**Comment by fguillot** [comment]
This feature is not available, you can only configure what is described on this page: http://kanboard.net/documentation/notifications

**Comment by Vladimir-Kartashov** [comment]
Perhaps turn off unnecessary notifications directly in php files ?

**Comment by Vladimir-Kartashov** [comment]
Perhaps turn off unnecessary notifications directly in php files?
When configured automatic actions on the mail comes 3 notifications per action.
