### ISSUE TITLE
Required Start Date (Gantt chart-related)

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#1135]
Just thinking - would it be possible to have a 'required start date' type thing? This would only be relevant when a due date and time estimate had been completed for a task, however ...

If we had a task "check naughty/nice list twice" which has been estimated as taking 2 days to complete, and is due for 23/12/2015, we could say that this task _must_ be started by 21/12/2015 for it to be completed.

In an ideal world, we could even say something like
"Deliver presents" - 1d, due 25/12/2015
is blocked by ...
"Check naughty/nice list twice" - 2d

then we could say that "Deliver presents" must start on 24/12/2015, and so therefore "check naughty/nice list" will need to start on (or before) 22/12/2015 for that to happen.  It'd make the Gantt charts nice, because you could be able to add critical path (etc) data, if it was correctly filled in, making the Gantt chart mega-useful :)

_BUT_: Is this out of the scope of Kanboard?  I think @fguillot would probably be best to answer that, really. I'm in two minds as to whether it'd be the right path (it is certainly heavily linked in terms of usefulness) or not (it's not a kanban board, so should be a separate component)

**Comment by AlgyTaylor** [comment]
Looking at it, this is linked quite heavily to #1114 ....

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
