### ISSUE TITLE
TACACS+ as external authentication provider

### ISSUE THREAD

**Issue by donpatzone** [kanboard/kanboard#1154]
Hi,

I wanted to ask, if it is possible to add TACACS+ as an external authentication provider?
There is already a [project up here on GitHub](https://github.com/jeroennijhof/pam_tacplus) if that is of any use.

Thanks!

**Comment by fguillot** [comment]
Unfortunately, the number of features is voluntary limited to keep the software simple and that doesn't seems to be used by a lot of people.

I don't even know how to setup a development environment to implement such feature. If anyone feel confortable to develop a plugin, contributions are welcome.
