### ISSUE TITLE
Create and Update Tasks via pop3/imaps

### ISSUE THREAD

**Issue by divansantana** [kanboard/kanboard#1158]
Similar task to #222 which is marked as resolved now.
Would be nice to have support to create/update tasks via pop3s/imaps.
Currently AFAIK email task integration is only supported with external/public email provided.

This is not ideal for many corporations which have policies which prevent use of their company data being stored in the cloud or on systems of which they don't have full control.

**Comment by fguillot** [comment]
In the meantime, you can always write a simple script that poll regularly emails from your imap server and then call the api of Kanboard.

**Comment by Minyun** [comment]
I second this. I am not authorised to use external providers.

Any news?

**Comment by aljawaid** [comment]
IMAP would be very useful

**Comment by EstebanMonge** [comment]
Hello!

Please stop crying about this feature!

I made a little plugin to fetch mail from IMAP account, it's a first attempt.

You can configure the parameters in Settings
You need to run a cron script to get all working.

I tried to get all from web front end.

At the moment I only tested with gmail and IMAPS... never can get a select with yes no option =$

If you want test it and give feedback this is the URL: https://github.com/EstebanMonge/kanboard_imap_tasks

**Comment by EstebanMonge** [comment]
Hello I updated the plugin to get the project ID from subject of mail, for example the subject can be:

<PROJECTID> Meter tres goles!

The plugin will remove <PROJECTID> and creates the task with the correct name

https://github.com/EstebanMonge/kanboard_imap_tasks

**Comment by mainboarder** [comment]
Unfortunally @EstebanMonge plugin just supports php7 or higher. Debian Jessie just supports 5.6.

Thanks @EstebanMonge for your plugin, but this does not help everyone who uses kanboard.

**Comment by EstebanMonge** [comment]
Hello:

Jessie can be installed with dotdeb packages and have good support.

You can follow this instructions:
https://www.dotdeb.org/instructions/

PHP 7 have better performance than PHP 5.6

If you have a setup with php 5.6 can made test with your environment and give me your feed back.

**Comment by mainboarder** [comment]
this is right, i just want to have as few entries in the sources list as possible.

at least debian stretch with php7 is on its way

**Comment by EstebanMonge** [comment]
Hello I tested with PHP 5.6 on Debian 8 and works fine!

**Comment by EstebanMonge** [comment]
I have a separated project, please open a ticket in that project: https://github.com/EstebanMonge/kanboard_imap_tasks

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
