### ISSUE TITLE
center gant chart on current date when viewing projects

### ISSUE THREAD

**Issue by lbtw** [kanboard/kanboard#1160]
gantt chart is showing the oldest date as the default, can it be set to (or be updated to be configurable) for today's date?

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
