### ISSUE TITLE
Enhancement: Sort Gantt chart by time per default or make it changeable

### ISSUE THREAD

**Issue by nodomain** [kanboard/kanboard#1184]
Every time I open the gantt view it is sorted by position. I'd like to have it sorted by time per default to make it look nicer.

Thanks.

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
