### ISSUE TITLE
Gantt chart for tasks: add more info (work progress)

### ISSUE THREAD

**Issue by mykytavoronkov** [kanboard/kanboard#1186]
Please add more info for Gantt chart for tasks: add more info: 
- work progress based on Time estimated and Time spent (as blocks inside task's colored block as it is here https://teamgantt.com/gantt-chart-software/ )

Thanks a lot for Gantt chart! :)

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
