### ISSUE TITLE
Gantt chart for tasks: add more info (tasks restrictions)

### ISSUE THREAD

**Issue by mykytavoronkov** [kanboard/kanboard#1188]
Please add more info for Gantt chart for tasks: add more info: 
- tasks restrictions

http://www.gantt.com/creating-gantt-charts.htm

Start No Earlier Than (SNET): This means that the task, whether linked or not, may not start before the given date. However, the Gantt application still has the flexibility to start the task later than the given date.
Start No Later Than (SNLT): This means that the task, whether linked or not, may not start later than the given date. However, the Gantt application still has the flexibility to start the task earlier than the given date.
Finish No Earlier Than (FNET): This means that the task, whether linked or not, may not end before the given date. However, the Gantt application still has the flexibility to end the task later than the given date.
Finish No Later Than (FNLT): This means that the task, whether linked or not, may not end later than the given date. However, the Gantt application still has the flexibility to end the task earlier than the given date.
Must Start On (MSO): This rigid constraint means that the task, whether linked or not, must start on the given date. Even if the preceding task is completed earlier, the Gantt application cannot pull in the constrained task to take advantage of the time gained.
Must Finish On (MFO): This rigid constraint means that the task, whether linked or not, must end on the given date. As above, even if the preceding task is completed earlier, the Gantt application cannot pull in the constrained task to take advantage of the time gained.

Thanks a lot for Gantt chart! :)

**Comment by Joan-Andreu** [comment]
It would be great !

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
