### ISSUE TITLE
Gantt chart for tasks: add more things (milestones, deadlines, redlines, priorities, critical path)

### ISSUE THREAD

**Issue by mykytavoronkov** [kanboard/kanboard#1190]
Please add more info for Gantt chart for tasks: add more info:
- milestones, 
- deadlines, 
- redlines, 
- priorities, 
- critical path

http://www.gantt.com/creating-gantt-charts.htm

Thanks a lot for Gantt chart! :)

**Comment by juanluisbaptiste** [comment]
The critical path feature would be very interesting !

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
