### ISSUE TITLE
Gantt chart for tasks: add it to embedded view + add 3 views switcher

### ISSUE THREAD

**Issue by mykytavoronkov** [kanboard/kanboard#1193]
Please add view switcher to public board view, having 3 views: kanban, tasks list details and gantt chart. We use kanboard for non-profits and volunteer orgs - so many times transparency of project plan is required to be published. 

Example of embedded usage is here http://it.vegan.in.ua/taskboards/vegan-wiki-v-1-0

BTW, Gantt chart is used (week scale) via google spreadsheet, see it embedded here http://it.vegan.in.ua/home 

But kanboard new gantt feature is great! )

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
