### ISSUE TITLE
Problem with the Calender view

### ISSUE THREAD

**Issue by dirktoennes** [kanboard/kanboard#1199]
Hi Guys,
i've got some Problems with my Calender view.
 At the moment it looks like this.
![unbenannt](https://cloud.githubusercontent.com/assets/14159085/9712432/dc6d65d8-554a-11e5-860c-77191d7f3ca5.JPG)
What I want it do to?

Here you can see a "Testing"-Task which should start at the 2th. and end at the 4th. Day of the month. In the Discription of the task it starts at 2th and ends at 4th. 

In the Gant view it looks like this ...
![unbenannt](https://cloud.githubusercontent.com/assets/14159085/9712516/75f8498e-554b-11e5-8b3d-0754f09eddf0.JPG)
But as you can see above in Calenderview it looks quiet different. 
At the moment it looks like a Task never stops.

What I want to create is a Task that starts at a certain day and stops at a certain day, esspecially for useing the Calender export Function.

Does Someone have any Ideas how to fix my Problem?

Thx for Help.

**Comment by fguillot** [comment]
In the task details, what are the defined start date and the due date? that should be 2th and 4th. Which settings did you use in calendar settings?

**Comment by dirktoennes** [comment]
Hi

so this is what it looks like.

![unbenannt1](https://cloud.githubusercontent.com/assets/14159085/9870897/3f4b561a-5b90-11e5-9d02-7a07130def51.JPG)

And here are the settings 

![unbenannt2](https://cloud.githubusercontent.com/assets/14159085/9870910/4ade154e-5b90-11e5-8401-26732f303772.JPG)
![unbenannt3](https://cloud.githubusercontent.com/assets/14159085/9870912/4d68bdf0-5b90-11e5-8327-40e8935796a1.JPG)

**Comment by PeGa** [comment]
Happens to me too, but it also happens when not start nor due date are defined.

Application version: 1.0.27
PHP version: 5.5.33-pl0-gentoo
PHP SAPI: fpm-fcgi
OS version: Linux 4.1.12-gentoo
Database driver: sqlite
Database version: 3.11.1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36

**Comment by fguillot** [comment]
Tickets related to the calendar should be posted to the calendar plugin bug tracker: https://github.com/kanboard/plugin-calendar/issues

Thank you
