### ISSUE TITLE
"Change the assignee based on external username" for Gitlab

### ISSUE THREAD

**Issue by nlevchuk** [kanboard/kanboard#1207]
Hi!

This feature works for Github. It would be great to have it for Gitlab too.

**Comment by brammeleman** [comment]
When GitLab triggers the webhook, it sends the assignee_id but the associated assignee data (name, username, avater_url).
Looks like this should be fixed in GitLab first.

**Comment by brammeleman** [comment]
I've created an issue for GitLab: [Issue assignee data should be posted to webhook](https://gitlab.com/gitlab-org/gitlab-ce/issues/3047)

**Comment by nlevchuk** [comment]
@brammeleman 

> When GitLab triggers the webhook, it sends the assignee_id but the associated assignee data (name, username, avater_url).
Looks like this should be fixed in GitLab first.

Yes. you're right and that's why i've created this issue https://gitlab.com/gitlab-org/gitlab-ce/issues/2475. But anyway thanks for your interest.

I've created this issue a month ago but still don't have an answer.

**Comment by brammeleman** [comment]
Looks like there's progress being made on the GitLab side of this issue. See https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1633

**Comment by nlevchuk** [comment]
@brammeleman yep, but actually this MR https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2724/diffs.

**Comment by nlevchuk** [comment]
Could someone realize this feature? I'm not familiar with PHP :(

**Comment by fguillot** [comment]
Issues related to Gitlab should be posted here: https://github.com/kanboard/plugin-gitlab-webhook/issues
