### ISSUE TITLE
Filter for "My Tasks"

### ISSUE THREAD

**Issue by crsaracco** [kanboard/kanboard#1217]
I'd like to be able to use filters for the "My Tasks" page just like you can on Kanban board pages.

You can search if you click on the "Search" link, but it doesn't really act the same as the filter on the board page.

**Comment by fguillot** [comment]
What to you mean by "doesn't really act the same as the filter on the board"?

**Comment by crsaracco** [comment]
The filter functionality does not show up directly on the `?controller=app&action=tasks` "My Tasks" page like it does on the taskboard. On the task board you could apply a filter right there and it would remember your filter on subsequent page visits.
