### ISSUE TITLE
Add date_creation and date_moved to updateTask and createTask API calls

### ISSUE THREAD

**Issue by diamondq** [kanboard/kanboard#1219]
I'm building an integration between Rational Team Concert / Jazz and Kanboard so that the stories and tasks are automatically sync'd between them. I'd like to be able to set the date_creation / date_moved from the equivalent fields in RTC. While those fields are exposed in getTask, they're not settable with createTask or updateTask. 

It seems to me that, as long as they were optional, it should not break any backwards compatibility.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
