### ISSUE TITLE
Automatic task color per swimlane

### ISSUE THREAD

**Issue by otterz** [kanboard/kanboard#1225]
Automatic or predefined task color per swimlane would be a nice feature. Perhaps you can implement it via those automation rules like "Change task color based on swimlane".

Thank you in advance,
Benne

**Comment by 85pando** [comment]
Is this really needed? The tasks in one column are already grouped together as they are in one column. Adding the same color to all of them seems redundant.

**Comment by BlueTeck** [comment]
:-1: 

I agree with @85pando 

The Task are already grouped by swimlane.

**Comment by 85pando** [comment]
Also, you can already do this via automatic actions:

* move task to column
* change color of task
* do this with one color for every task

**Comment by weizenspreu** [comment]
I started using Kanboard quite recently and would vote for this feature. Swimlanes may e.g. present different criticalities of bugs in a bug tracker and assigning them different colours would be really helpful. As an addition it would also be really helpful to set the swimlane level of a task by its category (e.g. a bug might be automatically assigned the colour yellow in the swimlane "medium", while a security vulnerability might be automatically assigned the colour red in the swimlane "critical").

**Comment by ukanalyst** [comment]
I actually just added this feature to submitted a pull request. You can find the request here: https://github.com/kanboard/kanboard/pull/2587

**Comment by fguillot** [comment]
PR #2587 have been merged.
