### ISSUE TITLE
Watch function

### ISSUE THREAD

**Issue by noktork** [kanboard/kanboard#1230]
Hi!
Thanks for a explendid work with kanboard!

I'm lacking the possibility to mark a task as a "watched" task by me or other user.
Today i can't get mail notifications on a particular task, that I nither are creator or owner to.
Creating the role watcher into kanboard an include default notify to both owner and watchers will improve process management of tasks.

Best regards
Walter Cruz

**Comment by varod** [comment]
it should be very nice to have this feature implemented :)

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
