### ISSUE TITLE
lock system for user access

### ISSUE THREAD

**Issue by walter03** [kanboard/kanboard#1244]
I suggest a new feature to help the application operations guys:
There should be way to lock/unlock web access for users to kanboard (e.g. for database backup or other operations tasks) which can be activated via web GUI or the json/rpc interface.
If locked, the users should get a notification that the system is in maintenance mode.

+1) The lock should persist during updates so that a release update can be made in a controlled way.

**Comment by kiney** [comment]
I usually just temporarily change the frontend server configuration in this case. For e.g. nginx you can have a second conf-file in sites-available. To lock just link it to site-enabled, and reload conf.

**Comment by walter03** [comment]
I see. In an environment where you have no access to the web server this is not possible.

**Comment by kiney** [comment]
Add something like:
print("Message");
exit();

at the top of config.php
I just tested that, seems to work.

**Comment by walter03** [comment]
true, but if the kanboard admin has no access to the webserver on commandline (because it is administrated by some other team), this is not possible.

**Comment by fguillot** [comment]
The best way is probably to put the web server in maintenance mode. It can be done easily with Nginx or Apache.

Usually, people that are managing the server are the same people who performs updates, backups or any administrative tasks.

Unfortunately, this is out of the scope for Kanboard at the moment.
