### ISSUE TITLE
Do not show item until start date in board view

### ISSUE THREAD

**Issue by julesverhaeren** [kanboard/kanboard#1253]
I think not showing cards that have a start date in the future can help keep the board organised while enabling planning far in the future with the gantt chart. Since this behaviour might not be wanted I think this should be an option per project that can be enabled (disabled by default to keep experience consistent). I'm not sure if this should be a setting per board or per column, or if this idea conflicts with anything?

**Comment by fguillot** [comment]
It would be better to add a new search filter by example `start:>=date` similar to the filter `due:today`...

**Comment by julesverhaeren** [comment]
Yeah that seems much better indeed! I'll try to implement that.

**Comment by julesverhaeren** [comment]
Okay I've got it working partially but I've ran into two problems:
 * (this might deserve a seperate bug/feature request issue:) The `<=`,`>=`,`>` and `<` operators do not seem to function in combination with `tommorow`,`today` and `yesterday` 
 * if the `start:` filter would work exactly like `due:` then dates that have not yet been assigned a start date would not be displayed. This is really annoying if you want to have this filter on continuously since all tasks will disappear on creation. Would it be better to also display tasks that have no start date with this filter on, or is there another filter technique so that you can still see these tasks? Or perhaps a start date field on the creation forms should be added?

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
