### ISSUE TITLE
Importing existing issues (gitlab)

### ISSUE THREAD

**Issue by stefanoco** [kanboard/kanboard#1259]
This applies to other integrations I guess: we're about to start using this beatiful application in our team of 12, integrated with an exiting gitlab self hosted server.

But we already have an established workflow based on issues and plenty of projects with open issues. Any trick for creating kanboard tasks from all existing gitlab issues at once?

**Comment by Bzzz** [comment]
Get feature request #1795 done and you're good to go ;)
I have the same problem right now, so I'd like to bump these two issues.

**Comment by michaeltlombardi** [comment]
This'd be really useful, we're investigating kanboard as a solution to our 'we need a way to see all of what we're doing' problem.

We only have about 200 issues to date, so scripting the load wouldn't be _terrible_, but still - this would be a killer feature for us.

**Comment by fguillot** [comment]
Issues related to Gitlab should be posted here: https://github.com/kanboard/plugin-gitlab-webhook/issues
