### ISSUE TITLE
how to calculate 'time spent'

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#1260]
is there a way to count the time spent (per project) in a given time span - say a month

**Additionally:** the cards display only _estimates_ but not the actual _time spent_

**Comment by thob** [comment]
or maybe better > connect to [Toggl](https://github.com/toggl/toggl-button/issues/329)

**Comment by phillc73** [comment]
+1 

I'm also using Toggl and would also appreciate integration to automatically log time against specific Tasks.

**Comment by bretweinraub** [comment]
+1 Toggl integ

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
