### ISSUE TITLE
Enhancement to 'duplicate' function

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#1264]
Would it be possible to allow (optionally?) the comments for a task to also be reproduced when the task is duplicated?

Just to give it a bit of context, we use Kanboard to track the processing of genetic data, so it would be nice to be able to keep a 'history' of comments from previous tasks, so that they can be referred back to at a later point.

Keep up the awesome work, by the way - it's transformed the way that a lot of the bioinformatic work is done here! (http://www.mangen.org.uk if you're interested)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
