### ISSUE TITLE
Additional visualizations

### ISSUE THREAD

**Issue by mtruijen** [kanboard/kanboard#1266]
The current cards have a couple ways of categorization:
- card color
- single category
  It would be beneficial if there was a few more:
- card border color. It would be cool if we could put a red frame around a card to make it stand-out.
- additional (second) category. Maybe allow for a secondary category. Or somehow segment the category. E.g. 3 segments that make up the actual category on the card.
- card size? Not sure how feasible that would be and if it makes a lot of sense. Just thinking more from visual management perspective.

All our work is for customers and it would be nice if we somehow could have the "Requestor/Customer" on the card. I know space is limited and you need to carefully consider what fits a card and keeps it clear and visual. But I thought I just put it out as something to think of.

Thanks a lot! Great software!
-Martien

**Comment by sparkles645** [comment]
@mtruijen - suggestion: write the name of "Requestor / Customer" as the first word in the name of the task? - hence visible on the card? 

If not according to wishes, and if treated as a feature request - this perhaps brings us back to the discussions/suggestion of a custom field / tags  - ref #262, #646, #998

**Comment by TimHandy** [comment]
That's exactly how we do it. We use 3-letter customer codes and have these as the first word in the title. E.g. "TRS - This is the task" and then we use the search to filter on only 'trs'.

**Comment by fguillot** [comment]
@mtruijen Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
