### ISSUE TITLE
Enhance analysis - split by swimlane

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#1267]
Would it be possible to split some of the analysis charts by swimlane?

The most useful would be the "average time spent in each column" graph; here we have two swimlanes that cover data coming off two separate types of machine. Let's say machine A takes around 3 days and produces 1gb of data, and machine B takes 5 days and produces 2gb of data - they both go through the same process afterwards, but it would be handy to report something like:
- data off machine A spends X hours waiting in column D
- data off machine B spends Y hours waiting in column D

Thanks again for the great work, by the way :)

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
