### ISSUE TITLE
Convert SVG logo to path-type

### ISSUE THREAD

**Issue by vikbez** [kanboard/kanboard#1270]
Current SVG logo depends on required font "Sans" and "Sans bold"
Not having this font renders badly the logo:

![logo](http://new.tinygrab.com/6fc1ddb35754ae9ab9713f2f2c487b7de9aadf1344.png)
Could you set the logo to path-type instead of requiring the font ?
Thanks !

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
