### ISSUE TITLE
Analytics / Reportings don't behave the same way according to the closed tasks

### ISSUE THREAD

**Issue by crile** [kanboard/kanboard#1275]
Hi,

For example, in "Task distribution" the closed tasks don't appear. So my "done" is alway equal to zero.
In "Cumulative flow diagram", the closed tasks are take into account.

So according to the report, the closed tasks are counted or not. Is it possible to fix this behavior ?
Or add some sort of check box ("hide closed tasks") ?

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
