### ISSUE TITLE
dragged/resized tasks are moved/resized one day too far in gantt view

### ISSUE THREAD

**Issue by julesverhaeren** [kanboard/kanboard#1282]
Tasks that get resized or moved in gantt view will jump one day too far/soon. I cannot seem to find a pattern in the direction of the jump, which I find quite confusing.
This seems too glaring to be a bug, so I've tested this on two different systems but both seem to be operating incorrectly. Anyone else also experiencing this problem?

**Comment by fguillot** [comment]
Hum, maybe a date issue, do you have the same timezone configured in Kanboard settings and in your browser/local machine?

**Comment by julesverhaeren** [comment]
I've installed KB on my local machine and the same issue is appearing, php date() gives me the same date as the clock on my OS so that isn't the problem I think? I've also done a clean install from the kanboard-latest.zip from the website (environment is XAMPP on win8.1), but the issue persists.

**Comment by julesverhaeren** [comment]
My bad the timezone in Kanboard was still at UTC. However I do think that the gantt view (or better: kanboard as a whole) should behave reliably regardless of the timezone of the client. (which is not the case right now). I think everything displayed and edited should be based on the timezone set in kanboard, but this might be very difficult to realise?

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
