### ISSUE TITLE
Import external ical feed into calender view?

### ISSUE THREAD

**Issue by poVoq** [kanboard/kanboard#1290]
Would be a 'nice to have' feature to be able to import an external ical feed (for example the planned holidays from of all colleagues from a shared google calendar or something like that) as an overlay to the calender view.

Thanks and awesome improvements lately!

**Comment by fguillot** [comment]
I see more people doing the opposite, they import the Kanboard iCal feed in their preferred calendar software.

**Comment by fguillot** [comment]
Closing this ticket due to inactivity and lack of interest by the community.
