### ISSUE TITLE
Hiding Default Swimlane also Hides Entire Kanban Board

### ISSUE THREAD

**Issue by phillc73** [kanboard/kanboard#1300]
Attempting to hide the default swimlane, specifically because I did not want it showing in the List view, ends up making the entire Board disappear.

Steps to Reproduce:
1. From an individual project board Actions drop down, select Settings
2. From the left menu select Swimlanes
3. Uncheck "Show Default Swimlane" check box and Save.
4. From the breadcrumb navigation, select "Back to the board"

Board has disappeared. Reversing the above process, and the board re-appears.

Also, in the List view, the Swimlane column still appears. The expectation was that unchecking the box in Step 3 above would result in this column no longer appearing.

Kanboard Version: 1.0.18
Browser: Chrome Version 45.0.2454.101 m

**Comment by fguillot** [comment]
It's not a bug, if you have a project with no swimlanes other than the default, and if you choose to hide the default swimlane there is nothing to show on the board anymore. That will not hide the column from the list view.

However, the checkbox to disable the default swimlane should not be shown when there is no other swimlanes created to avoid confusion.

**Comment by phillc73** [comment]
As I wasn't using any swimlanes on this specific project, what I was really trying to achieve was to hide the swimlane column in the List view. 

Unchecking "Show Default Swimlane" seemed like the logical way to achieve this.

**Comment by fguillot** [comment]
The concept of default swimlane has been removed in Kanboard 1.0.40. The layout of the list view has been changed as well.
