### ISSUE TITLE
Display Another Project Always Defaults to Board View

### ISSUE THREAD

**Issue by phillc73** [kanboard/kanboard#1304]
When viewing a project in Calendar, List or Gantt view, if the header drop down to "Display Another Project" is used, and another project chosen, the new project is always loaded in Board view.

Steps to Reproduce:
1. Ensure there are two or more available projects.
2. View a project in Calendar, List or Gantt view.
3. Use Display Another Project drop down to select another project.
4. Newly selected project loads that project's Board page.

Expectation was that the new project would be loaded in the same consistent view. e.g If new project selected from Calendar page of existing project, then new project would also load Calendar page.

Kanboard Version: 1.0.18
Browser: Chrome Version 45.0.2454.101 m

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
