### ISSUE TITLE
Link from a task to another pinboard

### ISSUE THREAD

**Issue by Andiministrator** [kanboard/kanboard#1311]
Is it possible to have a connection from a task to another project pinboard?
We have one "overview" pinboard where we created task to see the status of other pinnboards (that we don't need to click through all pinboards. The connection should be a kind of button or link which you direct to the connected pinboard.

**Comment by fguillot** [comment]
You can link tasks together across projects, all links are displayed in a tooltip on the board, maybe that can fit your need? or I misunderstand your request...

**Comment by Andiministrator** [comment]
Yes, and this is a great feature.
But I don't want to link from task to task. I want to link from a task to a board.

**Comment by donpatzone** [comment]
It is (currently) not directly possible. You can however do it via a workaround.
Copy the link of the board and put it as a description in the task on the main board. 
You may then hover over the description icon (bottom right of the task) and click on it.

**Comment by Andiministrator** [comment]
Yes, this is exactly what I do at the moment. But to navigate with the mouse to the description (tooltip) link is sometimes a bit exhausting ;)

**Comment by mhoennig** [comment]
Hi Frédéric, First thanks for this great piece of software. You mentioned "You can link tasks together across projects". But how?  I could not find any information about that and neither figure it out by myself.

**Comment by oliviermaridat** [comment]
Hi @mhoennig, this is possible using the [task link](https://github.com/fguillot/kanboard/blob/master/doc/task-links.markdown) feature. On the sidebar of a task click on "Add a link".

**Comment by mhoennig** [comment]
@oliviermaridat I had found that, but there I can only insert links to tasks of the same project, not to task of other projects, as Frédéric ahd mentiones above. What's the trick?

**Comment by oliviermaridat** [comment]
Hum...
If I start typing the name of a task there, a list of matching task appears. And this list also contains tasks from other projects.

**Comment by mhoennig** [comment]
@oliviermaridat that's what I though, but it only contains tasks from the same project :-(

**Comment by mhoennig** [comment]
@oliviermaridat very strange. I just moved my installation from sqlite to Postgres and suddenlly it works as you described. Thank you very much.

**Comment by oliviermaridat** [comment]
I am using Kanboard with sqlite. I have no idea of what is the issue.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
