### ISSUE TITLE
Cant move cards between columns on some touchscreen devices

### ISSUE THREAD

**Issue by kiney** [kanboard/kanboard#1313]
Drag & Drop does not work with some browsers on touchscreen devices. It appears there is no other way of moving cards between columns?

I have this problem with:
-android (5.1) running Fennec (Firefox) 40.0
-convertible notebook (touchscreen) with ubuntu running firefox 41

Fixing drag&drop for these browsers would be nice.
But anyway I think there should be a "fallback" way of moving cards without drag&drop.

**Comment by sparkles645** [comment]
#1382 - Android comment from me, recognice the description

**Comment by fguillot** [comment]
With recent versions of Kanboard, you can move task without drag and drop (accessible in the task view).
