### ISSUE TITLE
Enhancement Request: Closed Tasks Included in Analytics

### ISSUE THREAD

**Issue by phillc73** [kanboard/kanboard#1315]
I'd like to view, in the analytics section of each project, some data on how many closed vs open tasks the project has.

One idea is that the Task Distribution donut could also show Closed Tasks, but this is perhaps not very satisfactory.

Maybe then something else to show simply Closed vs Open Tasks might be enough to begin with. 

Essentially, when a Task is completed in the project, I'm closing it. This then causes it to pretty much disappear from view. I'd like an easy way to see how much work has been completed/closed.

Similar to https://github.com/fguillot/kanboard/issues/1275

**Comment by AgatonSax** [comment]
Also, it would be nice to be able to se User repartition on closed tasks (simply by changing the filter)
![image](https://cloud.githubusercontent.com/assets/5526928/15743136/94bf1aea-28c3-11e6-917a-64e871a27ee7.png)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
