### ISSUE TITLE
Enhancement Request: Categorise Closed Tasks

### ISSUE THREAD

**Issue by phillc73** [kanboard/kanboard#1316]
I can think of a number of different reasons one might want to close a Task. These could all revolve around the task either being completed or canceled (due to relevance, time, budget, requirements).

I'd like a way to categorise the reason for closing a Task. Either a couple of hard presets - Completed and Canceled. Or the ability to customise the fields however we choose, the same as Columns, Categories and Swimlanes.

These different categories should then also be available in the analytics section. See https://github.com/fguillot/kanboard/issues/1315

**Comment by sparkles645** [comment]
:fist: Recognize the use case, as "real life" in our use changes dynamically, but in our use - we close it and use **"Comments"** to explain/tell why it was closed. There may be 1 000 000+ different variety of reasones why it was closed, hence a static set of options would not be insufficient.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
