### ISSUE TITLE
Sort order: "no date" should be after filled dates

### ISSUE THREAD

**Issue by gregfr** [kanboard/kanboard#1320]
Kanboard is great :+1: 

When I sort tasks by date, in order to see the most urgent tasks, I can either have descending order, that is the last ones first, or ascending order with... the "no dates" first...

Don't you think tasks with no date could be considered as less urgent than tasks with dates?

**Comment by phillc73** [comment]
I agree this is an annoyance, and I would like to see "no dates" ordered to the end for ascending order. However, I temporarily work around this by picking some too far in the future date (1/1/2020 usually). It's an added extra step which ideally wouldn't need to occur.

**Comment by sparkles645** [comment]
:+1:  in terms of sorting from "closest due date" to "last due date"

**Comment by tamielbr** [comment]
+1

**Comment by sudoman** [comment]
I took a look into this issue. A schema change may be required to resolve this issue, as tasks without a due date have a `date_due` value of `0` and thus sort before the list of earlier due dates:

````
sqlite> select id,date_due from tasks where project_id = 6 and is_active = 1 order by date_due asc;

...
290|0
291|0
292|0
261|1526529600
263|1527825600
````

**Comment by neiaberau** [comment]
in pure sql you can always add addtional sort criterias to get what you want without data model changes, here first a sort that ensures all values > 0 are first: 
```
         select id,date_due from tasks where project_id = 4 and is_active = 1 
         order by case when date_due >0 then 1 else 0 end desc, date_due asc;
```
however 
- most of the time this does not work well with tools that map tables to objects
- you have to be careful to select a logic that works in all databases
- and there are probably more reasons ....

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
