### ISSUE TITLE
Setting option: Default Filter query

### ISSUE THREAD

**Issue by starjack1** [kanboard/kanboard#1323]
The default Filter query in the Project view is: status:open

Maybe there could be a Setting option, to choose his own default query. (in my case an empty query, want to see the closed tasks by default.)

Simple Kanboard with excellent connectivity options. Love your work.

**Comment by BlueTeck** [comment]
related #1295

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
