### ISSUE TITLE
[API] getBoard -> tasks -> add urls

### ISSUE THREAD

**Issue by BlueTeck** [kanboard/kanboard#1330]
Hi all,

the API Method getBoard, return also task details, this details should include the task url.

![image](https://cloud.githubusercontent.com/assets/1961634/10309680/2b1c492e-6c3e-11e5-8916-32b48b005e0d.png)

Reason, new function for the kanboard chrome extension, to jump from the chrome extension into the kanboard task page.

**Comment by fguillot** [comment]
If you really need that, the best way is to send a PR.
