### ISSUE TITLE
Column limit in hour

### ISSUE THREAD

**Issue by alevarotto** [kanboard/kanboard#1332]
Hello, i'm trying your project and it is very nice. I have a question: is it possible to setup the column limit in hour instead number of ticket ? So the column become red only if the sum of the time estimated exceed the column time limit ?
thank you

**Comment by sparkles645** [comment]
@alevarotto 
In current version, no - not possible to set limit in hour instead of number of tasks.
* This would be a feature request

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
