### ISSUE TITLE
cron type triggering of new tasks via task-template

### ISSUE THREAD

**Issue by walter03** [kanboard/kanboard#1334]
feature request
My suggestion is an extension to the command line tool, e.g. with the argument "projects:cron-trigger" which should process project specific crontab with the format "<hour> <day of month> <month> <day of week> <template-taskid> <dest-projectid> <dest-columnid> <dest-swimlaneid> <hours-before>" and copy, if matching, a task template info an existing project, a defined number of hours before the given time.

The usecase is to reschedule recurring operational tasks automatically without having to move tasks manually between columns, on the day before the task needs to be done.

+1 if configurable per project
+1 if also all subtasks and linked information is copied, too

**Comment by fguillot** [comment]
Unfortunately, the number of feature in Kanboard is voluntary limited. You could develop a plugin for your own needs.
