### ISSUE TITLE
Disable scrolling when dragging element

### ISSUE THREAD

**Issue by oparoz** [kanboard/kanboard#1339]
It's painful to move tasks from one swimlane to another as the whole list from the starting swimlane scrolls like crazy before reaching the next one.

**Comment by BlueTeck** [comment]
But how should the board know if you want to move between swimlanes or if you want to move the task position in a swimlane?

**Comment by oparoz** [comment]
When you hover over the end of the swimlane, then it should scroll until you move away from that point. There would still be a bit of scrolling, but if you time it right (don't wait too long before activating the scroll, but don't start immediately either), then it should be pretty usable.

**Comment by fguillot** [comment]
There is no column scrolling anymore.
