### ISSUE TITLE
Gantt chart for projects: Zoom

### ISSUE THREAD

**Issue by segfaultxavi** [kanboard/kanboard#1345]
I would like to be able to zoom out so I can see projects spanning multiple years in one screenfull.

One "cell" per month would be great, instead of one "cell" per day

**Comment by sparkles645** [comment]
:+1:

**Comment by robvoi** [comment]
This would indeed be great.

**Comment by robvoi** [comment]
Did some organizing work in Kanboard half the day again. Really missed this functionality.
Is there a way to see which feature request made it on the list or is there a public road map?

**Comment by sparkles645** [comment]
@segfaultxavi - this Github issues list is the current list / only list  - sometimes when a version is released, it's commented with the news on Kanboard.net what will be focused on for next version. Except from that, FGuillot makes the priorities on what features to include and not. The up-side with one dedicated owner / main developer for the main version is that nothing radical happens and  things are kept close and on track. Downside is that the user-base has to show a little patience with certain features.

**Comment by segfaultxavi** [comment]
I guess you meant @robvoi :)

**Comment by robvoi** [comment]
Think so :-)
Thanks for the explanation.

I hope this feature request makes it to the list.

**Comment by sparkles645** [comment]
**Suggestion - perhaps something like this?**
D = Days
W = Weeks
M = Months
Q = Quarters
Y = Years

* Defauls (D, W, M, Q, Y) for the Gantt view for the project can be chosen under "Project settings"
* By default, the date range is shown based on the configured start and end date of the project, but can be manually enteres by inputting dates and clicking "zoom"?

![2015-10-24_11-29-49](https://cloud.githubusercontent.com/assets/10092252/10710005/e6b94fd4-7a43-11e5-868d-599d72dd753e.png)

**Comment by robvoi** [comment]
Look good. I don't see anthing I would miss.

**Comment by tenwalls** [comment]
The above suggestions by sparkles645 looks good. Would the intention be that you also have a consolidated view of all projects/kanboards in a single gantt chart? This can then be filtered by user to assess if there is overlap on tasks across different projects. This would be the silver bullet for us from a project mgt perspective. Anyhow, amazing work - great job.

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
