### ISSUE TITLE
mail notification default sender not project specific 

### ISSUE THREAD

**Issue by sebastiantiede** [kanboard/kanboard#1357]
Hello,

i've connected mailgun with kanboard successfully.

If I add a comment to a project, associated users receive a email notification. 
The sender of this the one that is defined in config.php MAIL_FROM. 
Unfortunately I can’t answer to this sender, because there is no relation to the project and task.

Is there a possibility to change the default sender to a dynamically generated sender?

thanks a lot in advance
Sebastian

**Comment by fguillot** [comment]
It's not implemented at the moment.

To whom would you like to reply?

**Comment by sebastiantiede** [comment]
You've already implemented a way to send comments or commands via mail to projects. So far, it works very fine. But there should be an option to change the default system email address to a dynamic address like e.g. reply-[project identifier]@example.com.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
