### ISSUE TITLE
trac integration

### ISSUE THREAD

**Issue by frague59** [kanboard/kanboard#1362]
Hi, 

I'm using trac (http://trac.edgewall.org/) as bugtracker / source browser. Is there a way to integrate kanboard tasks into trac ?

Thanks !

**Comment by mwaeckerlin** [comment]
+1

For me it would be a good solution to be able to import a selection of trac tickets into kanboard.
Is there any import / export functionality in kanboard?

**Comment by fguillot** [comment]
Not yet, but anyone can develop a plugin fo that. Depends on what kind of integration you would like.

**Comment by fguillot** [comment]
Closing this ticket due to inactivity and lack of interest by the community.
