### ISSUE TITLE
display time spent instead of estimate on card

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#1363]
our use case should ideally indicate how much time has been used already on an entire board. Is there an easy way to **replace the estimate with time spent** on a card?

**Comment by pyg77** [comment]
+1

**Comment by armonyaltinier** [comment]
+1

**Comment by JoeScuba** [comment]
Or both?

**Comment by oxydron** [comment]
Or both? [2]

**Comment by fguillot** [comment]
This is now available in the dev version, time spent and estimated are visible.
