### ISSUE TITLE
Actions not applied to cards moved between columns in different swimlanes

### ISSUE THREAD

**Issue by nmarus** [kanboard/kanboard#1365]
I searched through the issue log, so my apologies if this is a dupe. 

Moving cards to another column in another swim lane of the same board does not apply the actions. The actions are only applied within the swimlane. 

Board Setup:
- 4 swim lines (S1,S2,S3,S4)
- 4 columns (C1,C2,C3,C4)

Actions (8):
- change color when moving card to a specific column (1 for each col)
- change color when creating card in specific column (1 for each col)

Scenario:
- Card1 in S1C1 -> S1C2 -> S1C3, etc (actions work)
- Card1 in S1C1 -> S2C2 (actions do not work)

**Comment by sparkles645** [comment]
@nmarus 
Tested, with the same results.

Automatic action -> "Assign a color when the task is moved to a specific column"

When moving task within the same swimlane, works fine.
When moving task directly to a different swim lane, **does not work**.

**Comment by fguillot** [comment]
It doesn't work because that trigger the event `task.move.swimlane`. That need to be improved or new action may be created to handle that.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
