### ISSUE TITLE
[Feature Request] Multiple selection to end/delete multiple tasks

### ISSUE THREAD

**Issue by oxydron** [kanboard/kanboard#1369]
Every end of month, we need to finalize tasks that are in the **ended** column, and to do it we need to enter every task and finalize it. As you can assume, is a very tedious task.

If multiple selection was possible, this would be done in 10 seconds.

Best regards,
Ben Hur

**Comment by sparkles645** [comment]
@oxydron 
* Why not create a column all the way to the right ("End of the month" that has an Automatic action to it that closes the task? 
* At the end of each month, you just drag-and-drop tasks that are to be closed to this column.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
