### ISSUE TITLE
Gantt moving task - moves one day after reloading page

### ISSUE THREAD

**Issue by Povezi** [kanboard/kanboard#1397]
Hi, great project...

just noticed if I make a task from e.g. 2015-10-12 to 2015-10-23 
screenshot: http://www.screencast.com/t/vJh2Sfws

and move it one day back to 10-11 to 10-22... 
screenshot: http://www.screencast.com/t/E6w5UR951xy2

after reloading page it is moved additional day by mistake
screnshot: http://www.screencast.com/t/TxTQKhR5OI

Any idea?

**Comment by tzwingm** [comment]
Tested with Stable version 1.0.32 -> Bug actual present -> The mentioned behaviour can still be observed. 

Addition Information:
If a task is moved to another date via Gantt, then the task is still moved one day before the entered date after "reload". It can be observed thatthe start time is set to 22:00 [10 PM].

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
