### ISSUE TITLE
Force adding comment when moving from a column to an other

### ISSUE THREAD

**Issue by bdrayer** [kanboard/kanboard#1402]
It will be great if, using automation, there will be a way to force user to add a comment when moving a task from a column to an other

**Comment by Cyrille37** [comment]
:-1: 
I think this feature is too specific.
Perhaps for a plugin.

**Comment by bdrayer** [comment]
It's to prevent users laziness, ... When you close a ticket, it's too easy to move it to the right column and don't give an explanation for the others users.

**Comment by Cyrille37** [comment]
Yes, I understand the need for some "usages" but it's not generic, in my mind ;-)

**Comment by oxydron** [comment]
I think too that is too specific.
Maybe a change of philosophy in the team is required. For example, anyone that moves a finalized task without commenting on it needs to buy a chocolate for the team.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
