### ISSUE TITLE
[FR][Plugins] Filter for Task Metadata / Filter hook

### ISSUE THREAD

**Issue by BlueTeck** [kanboard/kanboard#1411]
Hi all,

with the great new [metadata feature](https://github.com/fguillot/kanboard/commit/9283fb88d80cb355ff98364a9a57b657fc511d98), you could easily add new fields and information. It would be nice, if the board/calandar/list filter could be enhanced by metadata fields (by core or add filter hook for plugin devs) too.

Regards,
Timo

**Comment by fguillot** [comment]
Can you give an example of what you want?

**Comment by BlueTeck** [comment]
Simple example:

I want to add a metadata field named country. 
With a new page in the task menu this field could be changed. In the board I want to Filter all task for Germany. 

This could be done by this two ideas:

- generic filter for metadata like this: meta:"country":"Germany"

- or a way/hook to add custom filter like country:"Germany"

Regards,
Timo

**Comment by fguillot** [comment]
You can add custom filters with plugins (see class FilterProvider).
