### ISSUE TITLE
Search feature in user management

### ISSUE THREAD

**Issue by oazabir** [kanboard/kanboard#1426]
Easy way to search a user from user list and edit the user.

**Comment by Chaosmeister** [comment]
You could sort the Names or use the search feature of your browser.

**Comment by oazabir** [comment]
I am afraid I have 20+ pages of user on the user management view.

**Comment by szawadski** [comment]
Hello, I confirm my interest for such a feature. I have 1000+ users (although only 50 active ones) and it is quite complicated to browse through the pages to find a specific user account (created in batch thanks to the useful import function).
Regards,
Sébastien

**Comment by fguillot** [comment]
This is now available in the development branch.
