### ISSUE TITLE
Question: How can I get user_id and override layout array in plugin

### ISSUE THREAD

**Issue by Kolesar** [kanboard/kanboard#1430]
Dear,

I want to override app/overview with my plugin (add more details) but I do not know how to call exists methods getProjectPaginator, getTaskPaginator, ..., because these methods are private. OK, I copy/paste these methods in my plugin, but now I have another problem. How can I get user_id, because action $this->userSession->getId() return zero (0) and error in logs:
`Undefined variable: _SESSION in /var/www/html/kanboard/app/Helper/User.php`

**Comment by Kolesar** [comment]
And I attach something new with hook, how can I send array of data, like for hook->render?

**Comment by Kolesar** [comment]
Thanks for read my question. In middle time I tried something.

Can I use this in plugin?

``

**Comment by fguillot** [comment]
- Overriding a template will only replace a default template by a another one, variables passed to a template are not changed.
- Can you describe what you are trying to accomplish exactly? as you said you would like to add more details in the template `app/overview` but what kind of information do you want to add? where/how did you fetch this data?

I can probably improve the plugin api, but I need to understand your use case before.

**Comment by Kolesar** [comment]
- *First plugin:*
I want to create one new type of task with relation (Parent-Child). Child task is not subtask it is real task with relation to parent task with new column in database parent_id.
I made it, but now I want to show that information in task/show view.

- *Second plugin:*
Multiple user per task

- *Third plugin:*
Watchers on task

- *Fourth plugin:*
Group of users (for multiple user per task)

As you can see I have idea to make a lot of plugins. I do not want to change your original code because these plugins change a basic logic of your app. Please add necessaries in core for managing a lot of from plugin. If I can help you about it, I'm ready :)
