### ISSUE TITLE
Gantt chart: Group by swimlane

### ISSUE THREAD

**Issue by peredin** [kanboard/kanboard#1433]
I would like to be able to group entries in the gantt chart by swimlane.

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
