### ISSUE TITLE
Question on Filtering tasks based on User

### ISSUE THREAD

**Issue by Karthika19** [kanboard/kanboard#1438]
We are using the KANBOARD tool for our project tracking. The application version is 1.0.19.

In the Filter as per the User option, the user names chosen one after the other are getting appended in the Filter field box.

 assignee:"User1" --> Displays tasks assigned to User1
Then I choose User2, to see the tasks assigned only to User2, but the tasks of both User1 and User2 are displayed.
 assignee:"User1" assignee:"User2" --> Text in the filter field.

Just wanted to clarify if this is as per design or is it an issue?
Looks like an issue, since the field is to be over-written with the new filter and not appended.
Kindly clarify.

Thanks.

**Comment by BlueTeck** [comment]
This is the correct behaviour, but you could change it by editing https://github.com/fguillot/kanboard/blob/master/app/Template/project/filters.php#L83
change data-append-filter to data-filter

**Comment by middeke** [comment]
If you want both behavior, append and overwrite, you could do something like:

<li><a href="#" class="filter-helper" data-filter='assignee:"<?= $this->e($user) ?>"'><?= $this->e($user) ?></a>&nbsp;|&nbsp;<a href="#" class="filter-helper" data-append-filter='assignee:"<?= $this->e($user) ?>"'>append</li>

in line 83
