### ISSUE TITLE
FEATURE: Add automatic action for category change based on swimlane

### ISSUE THREAD

**Issue by Rtzq0** [kanboard/kanboard#1442]
It would be nice to be able to define category automagically by swimlane. That way for pipelining everything that you drop in to "bugfix" pipeline would be in the "bugfix" category.

**Comment by Biniou180** [comment]
Maybe it could be possible to not limit the feature to a category?
For example: When a task is dropped into a swimlane, it assigns the task to a specific user.

**Comment by jasonritzke** [comment]
@Biniou180 I don't disagree with a more general implementation approach. Since I wrote this issue automatic actions have been expanded quite a lot.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
