### ISSUE TITLE
Hide description or other fields on public boards

### ISSUE THREAD

**Issue by csuno** [kanboard/kanboard#1443]
I want to share (nearly)all my board activities to a wide range of public attendees. BUT for some Points we Need a Option to hide fields like description of a task or some new fields.

Goal is, to share the topics and all the activites, but not some private Infos (these should be just for boardmembers).

Is this possible?

**Comment by fguillot** [comment]
At the moment, it's not possible that some changes in the code. Probably a good idea for a plugin.

**Comment by DoumeDuSud** [comment]
And also is it possible to see almost every thing in the public view 

Specially the description of column swing-lane ... and even the empty swing-lane

thanks for all :+1:

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
