### ISSUE TITLE
[FR]edit (sub)tasks time spent (date stamp) freely

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#1445]
use case: I have to add **time spent** at the beginning of a month for the month that just ended. This is currently not possible I believe.

**Comment by fguillot** [comment]
Edit the subtask then change the time spent value?

**Comment by thob** [comment]
I meant editing the date stamp

**Comment by fguillot** [comment]
Can you provide an example because I don't get it, what do you call a "date stamp"? which date?

**Comment by thob** [comment]
my troubles are with collaborators who use an external time logging tool and close their KB tasks on – _say_ – November 3. My problem is that then the (sub)task reaches into November although it has been finished in October.

Does that make sense?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
