### ISSUE TITLE
[FR] Play/Pause button on the general screen.

### ISSUE THREAD

**Issue by oxydron** [kanboard/kanboard#1448]
The play/pause counter feature is very good but obvious only in subtasks.
I think some tasks are so straight forward described on the header, that don't need subtasks.

Would be nice to play/pause a task from the general perspective.

![teste](https://cloud.githubusercontent.com/assets/331134/10915578/921a5da8-823e-11e5-9d5f-55ad268a084e.png)

Some programming behind the subtasks would be interesting, like play/pause from the main screen play/pause the current subtask.

Good work guys :jack_o_lantern:

**Comment by NinjaPewPew** [comment]
:+1:

**Comment by iLucasBernardes** [comment]
@fguillot  👍

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
