### ISSUE TITLE
Question: link kanboard and cucumber

### ISSUE THREAD

**Issue by romu70** [kanboard/kanboard#1451]
Hi,
I begin to work on some projects with Kanban, and I plan to setup Kanboard. On another side, I've discovered Cucumber which we plan to use as a specification tool to describe our user stories.

So, I wonder if someone has already made a link between those tools? For instance, each Cucumber user story would be a Kanboard card. Then, we'll keep the Kanban visual aspects provided by Kanboard linked to the testable specification with Cucumber.

Thanks.

**Comment by fguillot** [comment]
Short answer, there is nothing related to Cucumber at the moment.

Just to have a better understanding, are your talking about https://cucumber.io right?

If I understand correctly, you want to use Kanboard to write the spec and then generate/export somehow the Cucumber spec and maintain a sync between the two systems?

**Comment by romu70** [comment]
Yes, something like what you described. Sounds great. I guess a Kanboard plugin could be perfect for such a feature.

**Comment by fguillot** [comment]
If anyone would like to develop a plugin for this, do not hesitate to contribute. There are already too many features requests and I prefer to focus on essential features.
