### ISSUE TITLE
[FR] Jours ouvrés / Actions automatisées

### ISSUE THREAD

**Issue by papyBrossar** [kanboard/kanboard#1454]
Bonjour, 

Serait-il possible de configurer la possibilité d'enlever les jours non ouvrés (le weekend) ? Les jours fériés ?

Sur le même sujet, est-il possible d'ajouter l'action automatisée "Déplacer un ticket dans une autre colonne dès que la date de début de la tâche est atteinte" ?

Cordialement, 

A.T

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding

**Comment by papyBrossar** [comment]
Okay, i understand.

Thank's for the reply
