### ISSUE TITLE
Bulk actions on tasks

### ISSUE THREAD

**Issue by facciocose** [kanboard/kanboard#1456]
It would be a very useful feature.

Something like: select multiple tasks and close all of them.

**Comment by iaanus** [comment]
A sort of "bulk" Close Tasks action has already been implemented. See #1056

**Comment by esclkm** [comment]
add bulk date_due, date_start, add tags

**Comment by anklaa** [comment]
Additional idea: Fast editing of tasks in list view.
Use case: project manager wants to change meta-data information like  Swimlane, Column, Category, Title, Assignee, Due date, Status) with less than 3 clicks.

**Comment by godspeedyou** [comment]
@iaanus That might be correct. A bulk action feature would be nice for other attributes nonetheless. Like changing the assignee of multiple tasks to one assignee.

**Comment by RRRRoger** [comment]
I have a Kanboard with hundreds of tasks. Sometimes, i want to change color for let's say, 20 of them. 
Do i need to change them one by one? Same for adding tags/deleting/moving/change priority/change assignee etc.?

**Comment by rautamiekka** [comment]
@RRRRoger Make your own ticket.

**Comment by RRRRoger** [comment]
My bad.. Can you link me where it's explained how to do a ticket?

**Comment by johanneskonst** [comment]
@RRRRoger to create a new ticket use the green button that says [New issue](https://github.com/kanboard/kanboard/issues/new) and fill in the form. Read [the guidelines](https://kanboard.net/documentation/contributing) beforehand.

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
