### ISSUE TITLE
Enable Gantt Chart View

### ISSUE THREAD

**Issue by darkocobe** [kanboard/kanboard#1465]
Do I need to do something special to enable Gantt chart view in the application. We are using the application and our tasks are shown in Board and Calendar but we can't see them in Gantt View.

**Comment by fguillot** [comment]
Your user need to be administrator or project administrator.

**Comment by darkocobe** [comment]
My user is both global Administrator and Project Administrator and Also manager of the project. But still can't see the tasks into Gantt Chart. I can see them on board or calendar.

**Comment by darkocobe** [comment]
Hi,
Just to notify you that we migrated our db from SQLite to PostgreSQL and now Gantt charts are working. I think this problem was related to DB. Maybe some bug because we didn't modify anything except the db.
Cheers

**Comment by rseabra** [comment]
Why not be able to allow members to view the gantt chart? It would be very useful for small team management and cooperation.

**Comment by 85pando** [comment]
@rseabra See #1667 … Oh, you already did find that as well (This link is for everyone else).

**Comment by rseabra** [comment]
Yeah, thanks. ☺

On 16 February 2016 08:29:31 WET, 85pando <notifications@github.com> wrote:
>@rseabra See #1667 … Oh, you already did find that as well (This link
>is for everyone else).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/fguillot/kanboard/issues/1465#issuecomment-184572755

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by asmwarrior** [comment]
I found a workaround about this issue, you can only change one line of PHP code, see the solution here: https://github.com/kanboard/kanboard/issues/1667
