### ISSUE TITLE
NOT operator in filters

### ISSUE THREAD

**Issue by facciocose** [kanboard/kanboard#1472]
It would be nice to have **not** operators in filters. To be able to do something like: `status:open color:red NOT column:done`

**Comment by oliviermaridat** [comment]
I agree, this can be really useful. An other possible syntax could be: "!column:done".

**Comment by eurodrew555** [comment]
This would be super useful !

**Comment by jtourt** [comment]
+1

**Comment by StanSiska** [comment]
Such feature would be really helpful, will it get implemented in future releases?

**Comment by godspeedyou** [comment]
I am also missing an AND-operator:

`status:open color:red AND column:done`
alternative:
`status:open color:red && column:done`

Groupings with brackets "()" could be necessary as well then.

**Comment by Paul-Hume** [comment]
Another one to add to this would be an or operator. 

status:open subtask:assignee:me or status:open  assignee:me

**Comment by lcmsrl** [comment]
+1

**Comment by dhornford** [comment]
+1

**Comment by ksciana** [comment]
+1

**Comment by regenduft** [comment]
+1

**Comment by dwm66** [comment]
+1

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
