### ISSUE TITLE
Assign user from comment form

### ISSUE THREAD

**Issue by skobeo** [kanboard/kanboard#1473]
it would be nice to have possibility to re-assign task from comment form in the same time comment publication.
Actually need to post the comment and then have to edit task to assign user.

thanks

**Comment by skobeo** [comment]
Hi, do you plan this feature request in a next version ? Thanks.

**Comment by fguillot** [comment]
Unfortunately, the number of features is voluntary limited to keep the software simple and that doesn't seems to be used by a lot of people.
