### ISSUE TITLE
time tracking export to csv

### ISSUE THREAD

**Issue by reiner** [kanboard/kanboard#1476]
Since I imagine that many of us need to invoice by time, It would be wonderful if it was possible to export tracked times by project and date in a csv. Are there any plans to offer such a function? Otherwise time tracking is just nice to have. In the meantime, do you recommend any workarounds for this? Thank you very much, Reiner

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
