### ISSUE TITLE
Make kanboard tickets exportable to PDF

### ISSUE THREAD

**Issue by noktork** [kanboard/kanboard#1492]
Hello!
Once again I want to congratulate you on a explendid work with Kanboard!

The function I was thinking of is to download a ticket as PDF for external presentation and reporting.
My thought was to segment the ticket, at the top you should be able to see the creator/owner, opened date and other statistics. Next below that you should be presented with relation to other tickets. And the final section will have all comments done in the ticket.

**Comment by NinjaPewPew** [comment]
:+1:

**Comment by fguillot** [comment]
Duplicate of #2650
