### ISSUE TITLE
BUG? Export dont work

### ISSUE THREAD

**Issue by csuno** [kanboard/kanboard#1494]
Is there a problem with export function?
I always get an "file not found".

link: http://xxx/kanboard/?controller=export&action=tasks&project_id=1&from=2015-11-01&to=2015-11-24
Hint: projectname has an german "ü" and an "#".

**Comment by fguillot** [comment]
Can you describe your environment (server and browser) to try to understand why it's not working?

**Comment by csuno** [comment]
Sure...
>TZ 	MET
>SCRIPT_URL 	/phpinfo.php
>HTTP_USER_AGENT 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 >Firefox/42.0
>HTTP_ACCEPT 	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
>HTTP_ACCEPT_LANGUAGE 	de,en-US;q=0.7,en;q=0.3
>HTTP_ACCEPT_ENCODING 	gzip, deflate
>PATH 	/usr/bin:/bin
>SERVER_SOFTWARE 	Apache/2.2.31 (Unix)

SQLite
>PECL Module version 	2.0-dev $Id$
>SQLite Library 	2.8.17
>SQLite Encoding 	iso8859

>Directive	Local Value	Master Value
>sqlite.assoc_case	0	0

sqlite3
>SQLite3 support	enabled
>SQLite3 module version 	0.7-dev
>SQLite Library 	3.7.7.1
