### ISSUE TITLE
Split/Merge Tasks

### ISSUE THREAD

**Issue by frederikheld** [kanboard/kanboard#1496]
As my team's board has grown we discovered a lot of tasks that were duplicates of each other. We started to link them but this doesn't reduce the number of tasks and therefore does not lead to a clearer board. If we delete the duplicates we have to copy the comments manually or we loose important information.

What I miss is the support for merging tasks. This should also include some clear way to show how discussion, subtasks etc. are merged from the involved tasks and a way to select which subtasks and comments shall be kept.

It would be great to have the same support for splitting a existing task as well.

**Comment by BlueTeck** [comment]
Other issue regarding split #873

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
