### ISSUE TITLE
owncloud integration / feature request

### ISSUE THREAD

**Issue by SebCanet** [kanboard/kanboard#1499]
Hi,
is it possible to add it inside owncloud, like a module ? using the user list from own cloud ?
Thanks a lot for your work !

**Comment by BlueTeck** [comment]
-> https://github.com/fguillot/kanboard/issues/466

**Comment by SebCanet** [comment]
Thanks, but it's not just 'view in iFrame' but integration with user's list.

**Comment by poVoq** [comment]
Yes with the new authentication system this should be possible no? Would be awesome if someone could write such a plugin and release a combined version on the owncloud app store.

**Comment by fguillot** [comment]
Already look at it in the past but their API doesn't make it easily to integrate KB.
