### ISSUE TITLE
Default application language for new user not applied

### ISSUE THREAD

**Issue by anayrat** [kanboard/kanboard#1500]
Hi,
I have just installed Kanboard  1.0.21 : 
Database postgres 9.3
Apache/2.2.22 (Debian)
PHP 5.4.45-0+deb7u2 (fpm-fcgi)
When I create a new user (ie brice) his default language is english instead of french (application setting is french)

```
select username,language from users;
 username | language
----------+----------
 brice    |
 admin    |


select * from settings where option = 'application_language';
        option        | value
----------------------+-------
 application_language | fr_FR
```

When I change the language for the user in his profile the language is ok.

**Comment by fguillot** [comment]
You should try again with the latest version of Kanboard (1.0.38). I'm not really able to reproduce your issue. Open a new ticket if the problem still there. Thank you.
