### ISSUE TITLE
Naming your Plugin

### ISSUE THREAD

**Issue by wozsoft** [kanboard/kanboard#1505]
Avoid problems loading your Plugin by using Proper Case (uppercase first letter) **only** when naming your Plugin.

The plugin template loader uses ucfirst() when creating the path to your templates in the getTemplateFile() function.

```
$path .= DIRECTORY_SEPARATOR.ucfirst($plugin).DIRECTORY_SEPARATOR.'Template'.DIRECTORY_SEPARATOR.$template.'.php';
```

So if you name your plugin and directory "MyPlugin" the loader will convert it to "Myplugin" and won't be able to find your template files to load. "myPlugin" & "myplugin" will also convert to "Myplugin".

The documentation and example file for "AutomaticAction" does not have any templates to load, but probably needs to be modified to avoid confusion.

**Comment by fguillot** [comment]
Filesystems on Linux are case-sensitive, so yes the way you define your plugins is important. However, `ucfirst('myPlugin');` will returns `MyPlugin` not `Myplugin`.
