### ISSUE TITLE
Kanboard as an Issue Tracking/Helpdesk System

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#1506]
Hello,

Thank you for making such a robust Visual Project Management System.   I have a request though.  Is it possible to add the following features so Kanboard could be used as an Support Desk System.  
1. Inbound Email creates an Task in a particular board. I know it does it now for registered users but it would be a great feature if it could create tasks from non-registered users as well. A possible example of this is a program I found called SmartQ.  Here is a link to their post on how they create tickets from non registered users.  http://blog.getsmartq.com/2012/06/submit-tickets-by-email-through-external-form-and-even-from-non-registered-users/
2. Add Requester Field to Task and Subtask Structure (Maybe just tasks)
3. Set Default Filters on Requester so they can only see tasks they requested.  This could be integrated into a role or maybe through some sort of custom text field defined per users in user management.  

Once again thanks to you and the kanboard community for a great platform.  

SC

**Comment by bdrayer** [comment]
Would also be interested

**Comment by seancarson** [comment]
So, After using Kanboard for some time I have been able to use kanboard a basic ticketing system.  

1.  All user that will submit tickets/tasks to your support board must be added to it.  Once this is done if you implement on of the plugins Sendgrid or PostMark user will be able to send emails to an plugin defined addreess and task will be created on your board under that user.  (Please see plugin documentation) 

2.  It would be good if this could be added to the tasks objects but it not entirely necessary with creator and assignee already existing. Just depends on how you want to use both.  I think assignee is the most rebust option right now in kanboard, and could be used as the requestor filed if it came down to it.  Analytics would be a bit throwed off though.  


3. The default filter is currently status:open.   In essence all users will be able to see all requests that have been added to the board.  For my use case thats ok, but this is different per each use case.  I have put in a feature request that would all board admin to set the default filter per board.   This would allow each users to see the tickets/tasks they created or requested depending on the filter you set.  creator:me or requester:me.  

Just my observations.  

Thanks

**Comment by MaximOrlovsky** [comment]
I'd like to use kanboard as help desk also.

**Comment by fguillot** [comment]
I'm closing this ticket. I let people from the community to contribute to project to implement such feature. That might be also possible to create a custom plugin.
