### ISSUE TITLE
More options for filtering and sorting of open tasks

### ISSUE THREAD

**Issue by eurodrew555** [kanboard/kanboard#1507]
I am currently using Kanboard personally to track multiple projects. Within these projects I am using columns to track many different things such as work at specific locations, timelines of work, specific issues, etc. I am not using it in the traditional sense of moving tasks across columns from left to right. To track the progress of tasks I am changing the colour e.g. yellow = normal priority, amber = medium, red = high priority/overdue, green = completed. I'm not really using the due date all that much as these are personal projects and not shared with team members. This system is working really well for me and I can see at a glance the status of specific items within projects.

To view all my open tasks I am using the query /kanboard/?controller=projectuser&action=opens&user_id=-1&page=1&order=tasks.date_due&direction=DESC

This gives me a list of all my open tasks, ordered by the due date.

It would be really great if I could simply order by colour, so that all red tasks are listed first, followed by amber, etc. I can then run as many projects as I want, assign colours to all the tasks and then use a single view to look at what needs to be actioned next, in order of priority.

It would also be really useful if there was an option to further filter this by projects. For example, there may be both work and personal projects and it would be useful to be able to show all open tasks in order of priority, only for a group of projects (e.g. work or personal).

**Comment by eurodrew555** [comment]
Another approach - it would be great if there was a filter field for open tasks, so for example if I just wanted to see all open, red tasks across all projects I could use the filter "color:red"

**Comment by Busfreak** [comment]
I created a simple plugin for naming colors and appending a filter-dropdown in board view:
https://github.com/Busfreak/kanboard-color_filter
Maybe this helps?

**Comment by eurodrew555** [comment]
Looks interesting @Busfreak however I'm looking for more ways to filter and sort the open tasks list view. Basically the problem I'm running into is I'm using Kanboard to manage multiple projects, and would like a quick way to see all the high priority tasks across all projects in one view, rather than having to go and check each project one by one.

**Comment by Busfreak** [comment]
Hi @eurodrew555,
I have added the filter to the search-controller, overwriting app/filters_helper.
Maybe we should insert it with a hook sometimes.
Now you can filter for your colors in the dashboard and search-controller. No sorting but filtering over all the tasks, you have access to.

**Comment by eurodrew555** [comment]
Sounds good @Busfreak 

Do you know if this works with the open tasks list view?
Does it add a filter field to that list view?

**Comment by Busfreak** [comment]
Hi @eurodrew555 

The plugin adds the color-filter to the dashboard (Farbkodierung, naming is done in the translation file of the plugin):
![color-filter1](https://cloud.githubusercontent.com/assets/12938119/11810236/ea27a29e-a32c-11e5-80c2-75b2e7c4ea4c.jpg)

When you choose a color, the filter is set showing all tasks you have access to with the selected color assigned to, no matter which project they belong to:
![color-filter2](https://cloud.githubusercontent.com/assets/12938119/11810332/7d68628c-a32d-11e5-86e8-2f88af281357.jpg)

This ist done in the search-controller. There you can combine all kinds of filter, e.g. 
```status:open assignee:me color:"cyan" color:"green" color:"yellow"```

**Comment by eurodrew555** [comment]
This sounds like it should solve my issue, however when I install the plugin on the latest version of kanboard 1.0.22 the UI now has two "Color Coding" filters. When I select color:"red" in either of the drop down lists it still only shows tasks from within the current project. Also, how does this filter then work within the current project? Ideally I would like to be able to filter either within the current project, or across all projects.

![kanboard color-filter 2015-12-15](https://cloud.githubusercontent.com/assets/13842996/11811233/56880194-a36f-11e5-820e-10f6077dc1e3.png)

**Comment by Busfreak** [comment]
Adding the filter to the dashboard was a quick and dirty test, if that would help you with your issue. Sure, now we have it twice in the board/project view. Here the filter only works within the current board. For filtering over all tasks, you have to do it in the dashboard or search view.
If you and maybe other users like the way of filtering colors, then I would refine the plugin, so the filter appears in different views (and only once :smile:)

**Comment by eurodrew555** [comment]
Looks good to me! Thanks!

**Comment by Busfreak** [comment]
Hi @eurodrew555,
try the update. Filter will appear once only :smile:

**Comment by eurodrew555** [comment]
This is perfect. Thanks!

**Comment by varod** [comment]
I am looking for a filter on task priority ; maybe something similar @Busfreak 's color filter can be applied ?

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
