### ISSUE TITLE
Easy way to remove name constraint in SQLite database

### ISSUE THREAD

**Issue by donpatzone** [kanboard/kanboard#1508]
Just an information for people who also like the addition of the feature having multiple projects with the same name introduced with 1.0.21, but are running on an SQLite database and want a quick and easy way to keep the existing database
The program [SQLite Browser](http://sqlitebrowser.org/) allows by the click on a checkmark to remove the UNIQUE constraint. 

I would advice to do an offline change, so that no Kanboard operations are made during editing. 

__DISCLAIMER__: As always, do a backup of the existing database. I am also not held responsible, if any problem arises with your database. As such, use at _your own_ risk!

First step is to open the db.sqlite file in the program and navigate to the `projects` table. Right click it and select _Modify Table_   

![step_1](https://cloud.githubusercontent.com/assets/4871330/11495840/8ed77f1e-980e-11e5-9623-b0d1211e8d72.png)

Remove the checkmark under the `U` column in the `name` row as shown by the arrow. You will also notice that in the live preview of the table below the keyword `UNIQUE` will disappear.  

![step_2](https://cloud.githubusercontent.com/assets/4871330/11495842/8efcee66-980e-11e5-8ed0-ed818fc6ea73.png)

Last step is to commit the changes by clicking on the _Write Changes_ button.
![step_3](https://cloud.githubusercontent.com/assets/4871330/11495841/8efbb992-980e-11e5-8b62-9c9af6d416df.png)

You should now be able to create a new project with the same name.

**Comment by BlueTeck** [comment]
Thanks for sharing, maybe @fguillot could add this workaround to the release notes.

**Comment by fguillot** [comment]
Link added to the FAQ.
