### ISSUE TITLE
Issue with Gantt chart view and different timezones

### ISSUE THREAD

**Issue by donpatzone** [kanboard/kanboard#1519]
Hi,

I think there is an issue with the Gantt chart view. When you move or resize a tasks timeframe via this view and afterwards open the task the time of the task will differ. Here are example screenshots

For reference: the server Kanboard runs on on uses CET timezone. My test user was running America/Los_Angeles

Here I resized the timeframe of the task via the Gantt View
![gantt_chart](https://cloud.githubusercontent.com/assets/4871330/11558958/dcea9878-99b5-11e5-98dc-c3efae8b232d.png)

This is how the task looks in detail (Start date). It shows 03:00PM the day before, a 9 hour difference, which coincides with the PST to CET timezone difference
![task_view](https://cloud.githubusercontent.com/assets/4871330/11558978/fb235d3e-99b5-11e5-9322-9389cbebc395.png)

What's curious though is the end date of the task.
![edit_task](https://cloud.githubusercontent.com/assets/4871330/11558980/05335a68-99b6-11e5-839b-e6ddb4ea442d.png)

When I now take a look back at the Gantt view I see this
![gantt_chart_after](https://cloud.githubusercontent.com/assets/4871330/11559154/00b6ba24-99b7-11e5-9df2-aef2b483236d.png)

I also tried and did a page refresh after I resized the timeframe in the Gantt view. It is the same result as shown in the last screenshot

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
