### ISSUE TITLE
Allow order of tasks to be changed for closed tasks

### ISSUE THREAD

**Issue by eurodrew555** [kanboard/kanboard#1534]
I am using some columns in my Kanboard for a timeline of tasks to complete. If I close the tasks I then cannot reorder them, or drag new tasks around these closed tasks.

This request is to allow drag/drag reordering of both open and closed tasks.

Thanks!

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited.

Thank you for your understanding
