### ISSUE TITLE
Calendar and export task issue

### ISSUE THREAD

**Issue by JMetai** [kanboard/kanboard#1535]
Back or forward arrows in calendar do not work if I want to back date or forward date. Also if I enter dates manually in start and end date for exporting task and when I try to export I get web page is not available error.
Does anybody had this issue before ? if so how you resolved this issue? or what could be the issue?

I am using stable version of kanboard and google chrome.

Thanks for your help.

**Comment by fguillot** [comment]
I cannot reproduce your issue on my local machine. Can you tell me if you can reproduce the issue on demo.kanboard.net ?

**Comment by JMetai** [comment]
Thanks for checking. Calendar is working on demo.kanboard.net. I am not sure why it's not working in my environment. Do you have any idea why it's not working?
