### ISSUE TITLE
How to adds fields (string, memo, checkbox, select) to tasks using a Plugin

### ISSUE THREAD

**Issue by bdrayer** [kanboard/kanboard#1536]
Hi,

Is there an example how to add different type of fields to tasks using a Plugin? I am also interested to add some fields to comments (for example add the type of source (Phone, email, ...) and the source of the comment).

I need to add some fields and I would be interested to do it using a Plugin to allow me to add them for me only because it's not needed by other people.

Thanks in advance for your answer

Best regards

Blaise Drayer

**Comment by fguillot** [comment]
You can attach metadata to tasks, you have an example here: http://kanboard.net/documentation/plugin-metadata

But your plugin will have to expose these data to the user interface. This part can be done with template hooks: http://kanboard.net/documentation/plugin-hooks By example, you can add a new section in the sidebar that link to another form.

At the moment, there is no metadata for comments but it's something that can be improved easily.

If you really need to create new columns in sql tables or create a new tables, you can use the schema migrations: http://kanboard.net/documentation/plugin-schema-migrations
