### ISSUE TITLE
Option to start Calendar Weeks on Monday

### ISSUE THREAD

**Issue by jclwilson** [kanboard/kanboard#1537]
I note that languages other than English change the first day of the week to Monday. Could an option be added for starting the week on Monday while language is set to English?
## Week start on Sunday (English)

Month view
![screenshot from 2015-12-11 14-00-45](https://cloud.githubusercontent.com/assets/3199935/11745425/ed31deca-a00f-11e5-8dfe-10646f96c8db.png)
Week view
![screenshot from 2015-12-11 14-01-05](https://cloud.githubusercontent.com/assets/3199935/11745432/f3d11480-a00f-11e5-8e21-a53d6e9892b5.png)
## Week start on Monday (German)

Month view
![screenshot from 2015-12-11 14-01-45](https://cloud.githubusercontent.com/assets/3199935/11745440/140d969c-a010-11e5-9974-482ecc18dc35.png)
Week view
![screenshot from 2015-12-11 14-01-57](https://cloud.githubusercontent.com/assets/3199935/11745446/1b2919ec-a010-11e5-8f40-46106baaee38.png)

**Comment by xavividal** [comment]
+1

**Comment by dezsijanos** [comment]
+1

**Comment by BlueTeck** [comment]
Workaround:

Edit this file: https://github.com/fguillot/kanboard/blob/master/assets/js/src/Calendar.js
and change the firstDay: http://fullcalendar.io/docs/display/firstDay/

regenerate assets: https://github.com/fguillot/kanboard/blob/master/doc/assets.markdown

**Comment by dezsijanos** [comment]
thanks a lot. we'll check it

**Comment by milankni** [comment]
+1
ownCloud's Calendar webapp uses

* English: American style. 
* English (UK): European style.

Affects date & time and start of week.
Although the possibility of manual override would definitely be better.

**Comment by jgeert1** [comment]
I don't have the development version. Is there a way to implement the workaround on the production version. I've updated the Calendar.js file. But that didn't help (firstday is still sunday). I could not find any reference in app.js, So stuck here, any help would be appreciated.
Thanks.

**Comment by SergiArias** [comment]
I would like to implement the workaround on the production version, but don't know how. It's very confusing the Sunday Week Start.

**Comment by nickian** [comment]
This was bothering me too. This should definitely be a setting in the UI. I didn't bother regenerating assets. Just went to `/assets/js/app.min.js` and search for "fullCalendar". Add `firstDay:1` into the options. For example, right after `editable:!0,`.

**Comment by fguillot** [comment]
Tickets related to the calendar should be posted to the calendar plugin bug tracker: https://github.com/kanboard/plugin-calendar/issues

Thank you

**Comment by SergiArias** [comment]
@fguillot But if the calendar is the one to select the day, within the core of Kanboard, should I report a new ticket?

![image](https://user-images.githubusercontent.com/13618783/28358639-e6cb8a80-6c6f-11e7-9f90-71b3779e1200.png)
