### ISSUE TITLE
Strikethrough text in Done column

### ISSUE THREAD

**Issue by jtourt** [kanboard/kanboard#1540]
Here is a tip on how to change the text to strikethrough in the Done column. I prefer to have done tasks as strikethrough so that the text is less likely to catch my eye when glancing at the board. 

##### Step 1: Determine the column ID.
* While in a board, click on Actions --> Settings.
* Click on Columns.
  * Click Edit for the column that you would to add strikethrough (i.e. the Done column)
* Look at the URL for the page and make note of the column_id:

For example:
  `http://example.com/kanboard/?controller=column&action=edit&project_id=1&column_id=4`
Column ID is 4.

##### Step 2: Apply CSS
* Go to the Kanboard Dashboard (top left KB logo link).
  * Click Settings.
  * Click Application Settings.
Paste the following into Custom Stylesheet:

         `td.board-column-4 {text-decoration: line-through;}`

Note: Adjust the number 4 to the column ID that was noted in Step 1. Number 4 is only an example. Column ID numbers vary with each board.  If the column ID is 17, enter:
        `td.board-column-17 {text-decoration: line-through;}`

* Click Save.

Hopefully this tip was helpful.  Cheers.

![done-strikethrough](https://cloud.githubusercontent.com/assets/14179005/11767816/509ee75e-a188-11e5-81fb-abea8df822d1.PNG)

**Comment by BlueTeck** [comment]
:+1:

**Comment by Chaosmeister** [comment]
:+1:

**Comment by CoMPaTech** [comment]
Would this work? @jtourt @fguillot 
https://github.com/CoMPaTech/kanboard_plugin-done_column_highlight

Rough on the edges but might due the trick?
