### ISSUE TITLE
Auto create subtasks on new task

### ISSUE THREAD

**Issue by tkwells** [kanboard/kanboard#1550]
Unless I've missed it, there currently isn't a way to define automatic actions that will create a list of "default" subtasks for new cards on a particular project.

The workaround is to have a "Template task" that is then cloned but this is a pain to do as you can't just use the default new task buttons.

P.S. Thanks for the hard work, really useful tool so far!

**Comment by AlgyTaylor** [comment]
:+1:

**Comment by MorganGeek** [comment]
It would be great ! Currently at work we must create "template" projects containing "template" tasks...

**Comment by angystardust** [comment]
+1

**Comment by NinjaPewPew** [comment]
Creat idea. I love the timer on sub task. Thats why I think it would be nice to have a automatically created default sub task.

**Comment by rickarubio** [comment]
+1 for this feature

**Comment by kjantin** [comment]
+1 for this feature

**Comment by corrador** [comment]
+1 for this feature

**Comment by creecros** [comment]
Try this:
https://github.com/creecros/AutoSubtasks
might do what you want.

**Comment by fguillot** [comment]
Duplicate with #850
