### ISSUE TITLE
Sorting comments - Comment box to top when sort is DESC.

### ISSUE THREAD

**Issue by neurocis** [kanboard/kanboard#1552]
When sorting comments within a task by most recent first, it would seem more logical to me to have the "Add a comment" textbox at the top of the comments section as opposed to bottom.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited.

Thank you for your understanding
