### ISSUE TITLE
Moving Tasks - UI Bug

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#1558]
Hi,

First of all, thanks very much for all the hard work put in to Kanboard, it's a fantastic piece of software that has inspired me as a developer!

Anyway, on to the bad stuff ... system:

**Browser:**
- Google Chrome (v47) on Windows 8
- _or_ Firefox (v42)

**Server:**
- Windows Server 2008
- Apache 2.4
- PHP 5.6
- Postgres 9.4

Say I have a task board with a few tasks (say ~12) on ... when I move them between columns, sometimes it's OK, but after a while I can't move the tasks between columns any more. It's fixed by pressing F5. Apparently this has been the case for a few versions (according to the person who reported it to me).

Looking at Firebug, it seems that some requests are coming back as 304s, with an error message:
![firebug_kanboard](https://cloud.githubusercontent.com/assets/1220211/11839867/14fd08f8-a3e9-11e5-8f28-4a1a3e8eb589.png)

The location of those controllers is:
1 - http://myhost/?controller=board&action=check&project_id=1&timestamp=1450265566&_=1450265557255

2 - http://myhost/?controller=board&action=check&project_id=1&timestamp=1450265566&_=1450265557256

Let me know if you need any more information :)

All the best,
Algy

**Comment by pythagorean** [comment]
I cannot move tasks either.  Pressing F5 does not result in success.  Using Chrome.

**Comment by cmmata** [comment]
I have the same problem in Heroku deployed version of Kanboard. My pc is a Fedora and I think it happened both in Firefox and Chrome. Last version of each one I suppose.

**Comment by pythagorean** [comment]
These seems to have been a problem with my install of chrome.  The cards/UI works fine in both Firefox and IE.

**Comment by butcher211** [comment]
I have the same problem here. It is very randomly. It was working the last weeks. Since 3-4 days it starts not working sometimes. And i couldnt find a way to move the tasks through task setting or whatever.

Google Chrome v51
Ubuntu 14.10 x64
PHP 5.5

**Comment by fguillot** [comment]
Unfortunately, we are unable to reproduce the original issue after all this time. You should try with the latest version of Kanboard and reopen this ticket if necessary.

Thank you
