### ISSUE TITLE
Bulk move tasks

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#1568]
Would it be possible to add in some kind of feature to bulk-move tasks from one column to another (eg I can select 5 tasks in the first column and place them in the second)? :)

**Comment by jarod80** [comment]
I think that while allowing multiple select it would be nice to enable also bulk edit

- change color
- close
- remove
- change categories 
at least.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
