### ISSUE TITLE
Filtering using wildcard masks

### ISSUE THREAD

**Issue by eurodrew555** [kanboard/kanboard#1571]
It would be really useful if we could use wildcard masks with filers.

For example, if you named your projects CLIENT-projectname then you could easily use the filter project:CLIENT\* to filter to all projects for that client.

**Comment by eurodrew555** [comment]
I've looked at the new tags to see if I could use them in place of the wildcard filters but it doesn't look suitable in the current implementation.

To use tags in the same way I would need to add a client tag to each task using an automatic action. Then I would search using tag:CLIENT-NAME

Any comment on whether wildcard filters or automatic tags could be implemented would be really appreciated. I am really enjoying using Kanboard and being able to quickly search in this way would make it perfect! Thanks

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
