### ISSUE TITLE
[Improvement] Listing view max entries for pagination should be configurable

### ISSUE THREAD

**Issue by gregdcBe** [kanboard/kanboard#1575]
Listing view max entries for pagination should be configurable

For now it is hardcoded to 30 in Listing.php

``` PHP
$paginator = $this->paginator
            ->setUrl('listing', 'show', array('project_id' => $params['project']['id']))
            ->setMax(30)
```

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
