### ISSUE TITLE
Work In progress Limits not Assignee Specific per Column

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#1584]
When setting Work in Progress Limits they do not apply to Assignee but to each column count.   So for instance if the WIP for a column is 3 then this well apply to all cards assigned to that column and will not be applied to each user but to the column as as whole.   So to apply a WIP to each user you would have to set a WIP of 15 for 5 users.  If this is by design then disregard.  

Thanks

**Comment by fguillot** [comment]
The WIP limit is for all tasks of the column regardless of the assignee.

**Comment by NinjaPewPew** [comment]
It would be creat to be able to set a task limit based on assignees. I would also wish for a warning if you try to assign a task to someone at max capacity.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
