### ISSUE TITLE
Changing category does not work properly

### ISSUE THREAD

**Issue by fbaret** [kanboard/kanboard#1585]
Hi,

Something goes wrong when I want to change a category having a custom action.
I have two custom actions that change task color based on category, with the **same color**  : 
Category 1  turn task in   Red
Category 2  turn task in   Red

When I'm changing task category, C1 or C2, it's already the same that is saved.

**The problem occurs only when two categories trigger the same color**.

Thank you for your help,

Florent

**Comment by fguillot** [comment]
When you say "it's already the same that is saved.", what do you mean? what is the problem exactly?

**Comment by fbaret** [comment]
Thank for answering me.

I have two custom actions (ui is in french) :
[image: Images intégrées 1]
 AND

[image: Images intégrées 2]

They trig the same color (Couleur : Rouge).

-> But if I create a task with category "Communication" and I save it,
category is automatically set to "Gestion des risques".

Regards,

Florent

2016-02-24 3:12 GMT+01:00 Frédéric Guillot <notifications@github.com>:

**Comment by fguillot** [comment]
I cannot see your screenshots in Github issue.

**Comment by fbaret** [comment]
http://oi65.tinypic.com/2cpalpg.jpg

http://oi65.tinypic.com/2nhoveq.jpg

2016-02-25 2:43 GMT+01:00 Frédéric Guillot <notifications@github.com>:
