### ISSUE TITLE
Automatic Action: set due date for new tasks at creation

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#1591]
Create Automatic Action that sets an Due Date on a newly added task of some many days from the current date.  So for example Today is 12/25/2015  if the auto action was set with a default of 5 days then the Due Date for a newly added card on that board would be automatically set to 12/30/2015.

**Comment by angystardust** [comment]
+1

**Comment by AgatonSax** [comment]
+1

**Comment by fguillot** [comment]
This automatic action is now available in the development branch.
