### ISSUE TITLE
Set of functionalities and ergonomic improvements 

### ISSUE THREAD

**Issue by b274** [kanboard/kanboard#1593]
Dear Fréderic Guillot, 

I have created yeasterday a framaboard account and I did appreciate your software. I have several functionnalities proposals to make your tool more relevant from my user point of view. I am a business owner (we are 3 in the team including me), a member fo two self-managed non profit organisation (co-working space where Framasoft is based and a festival). I am aware that this improvements are not as easy to implement as written below. 

So, it would be great to have the opportunity to:  

GENERAL NAVIGATION and PARAMETERS
- Have a menu (column on left) with the name (only) of all projects to make the navigation easier and faster when managing several projects.
- Link a color to a person, a categorie or a project to optimise the useful of colors code.

TABLE VIEW
- Parameter by default  "replier"

MENU VIEW
- Chose the column to show and rank it.

PROJECT CREATION
- Create different layout with categories, participants (individual and members) that can be used in various cases.

CREATION OF A TASK 
-  Have a remind of the name of the concerned project. 
- To choose which first name/name/both to show when a task is allocated. In my organisation, we all call each other by our firstname. And the column only show Name for which we are not confortable to use. 
- have directly all taks actions possibilities directly, with a button "Advanced functions". Several options can be accessed only once the task has been created.
- Rather having drop-down menu, an already visible list to tick will enable to avoid on click for each option.
- Some tasks concerns two persons, because they are part of the same meeting, or they both have to make this action individually. In the current version, one taks could only be allocated to one person only.
- Create regular task based on date. Each 30th of month, I need to make my accounts.
- Several times, some tick blocks are not followed by a "return to lign". See options to integrate  frequency. 

TASK LIST
- Change directly the content in the cells of the table, rather entering in the properties that requires two unuseful clics
- Chose the ranking of the table and save it. For instance, I would need to have all the tasks listed by date. In this way, I can see all taks I have to do today. Ranking by number is out of interest for me, or secoundary.
- Chose which column to show.

For sure, if this functionnalities are developped, I will greatly appreciate to make a financial contribution.

**Comment by fguillot** [comment]
Closing this ticket due to inactivity.
