### ISSUE TITLE
User Import fails. Always import nothing. 

### ISSUE THREAD

**Issue by snow-orld** [kanboard/kanboard#1595]
When importing users from the csv file, the result is always "nothing imported". I have checked the file to upload is encoded in utf-8 and found the uploaded file in the /tmp folder is with permissions wr------- which means besides user www-data nobody can read the file. Also tried to change the permission in php but the same happens. Does this happen to any site too? Or is it some settings I have missed?

Update: Importing users under Linux is successful but fails under Windows.

**Comment by fguillot** [comment]
Can you provide an example of file you are trying to import?
