### ISSUE TITLE
Feature Request/Question:  Documentation for adding additional custom fields to a task

### ISSUE THREAD

**Issue by kgraven** [kanboard/kanboard#1598]
I believe that using the latest codebase this can be done through the creation of a plugin.  Is there an example of adding custom fields to a task or a document that walks one through this?

It may be documented somewhere and I may be just using the wrong search terms.

Thanks

--Ken

**Comment by BlueTeck** [comment]
you could find it here: https://github.com/fguillot/kanboard/blob/master/doc/plugin-metadata.markdown

**Comment by Busfreak** [comment]
An example dealing with metadata:
https://github.com/Busfreak/kanboard-color_filter
