### ISSUE TITLE
Edit the date a task is created

### ISSUE THREAD

**Issue by jeffshieldsdev** [kanboard/kanboard#1604]
I'm backfilling some old requests as tasks and would really like to be able to set the "date created" to when I originally received the request.  Could it be possible, maybe not through the default screen, to be able to edit the Date Created field?

Another use case that happens for me frequently: I receive a request on a Thursday but don't get around to adding it to Kanboard until Monday.  For tracking and prioritization, it'd be helpful for me to know it was requested Thursday and not the following Monday.  Thank you.

**Comment by jeffshieldsdev** [comment]
In the interim, I wrote a VBScript file to do this for me on Windows.  I thought I'd share it with others.

It requires:
- the [CLI for SQLite](https://www.sqlite.org/cli.html),
- `sqlite3.exe` to be in the `PATH`, 
- and expects Kanboard's `db.sqlite` file to be located at: `C:\xampp\htdocs\kanboard\data\db.sqlite`

Here's the code:

### Update Kanboard Task Creation Date.vbs
```vb
Option Explicit

Const cAPP_TITLE = "Update Kanboard Creation Date"

Run()


Function Run()
	Dim strCreationDate
	Dim strID
	Dim objShell
	Dim strReturn

	strCreationDate = InputBox("Enter creation date (ex. ""YYYY-MM-DD HH:MM""):", cAPP_TITLE)
	If Len(strCreationDate) = 0 Then
		Exit Function
	
	ElseIf Not IsDate(strCreationDate) Then
		MsgBox "Creation date entered is not a valid date in the format ""YYYY-MM-DD HH:MM"".", vbCritical, cAPP_TITLE
		Exit Function

	End If

	strID = InputBox("Enter Kanboard Task ID:", cAPP_TITLE)
	If Len(strID) = 0 Then
		Exit Function

	ElseIf Not IsNumeric(strID) Then 
		MsgBox "Kanboard Task ID entered is not numeric.", vbCritical, cAPP_TITLE
		Exit Function

	End If

	Set objShell = WScript.CreateObject("WScript.Shell")

	strReturn = objShell.Run("sqlite3 ""C:\xampp\htdocs\kanboard\data\db.sqlite"" ""update tasks set date_creation = CAST(strftime('%s', '" & strCreationDate & "') AS INT) + (6 * 60 * 60) where id = " & strID & ";""", 0, True)

	If strReturn <> "0" Then
		MsgBox "sqlite3.exe returned:" & Chr(13) & Chr(13) & """" & strReturn & """.", vbInformation, cAPP_TITLE
	Else
		MsgBox "Done.", vbInformation, cAPP_TITLE
	End If

	Set objShell = Nothing

	Run = True
	
End Function
```

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
