### ISSUE TITLE
Change sort order on Gantt chart default

### ISSUE THREAD

**Issue by Inawire** [kanboard/kanboard#1605]
By changing line number 65 (it was in v1.0.20)

from:
 $filter->getQuery()->asc('column_position')->asc(TaskModel::TABLE.'.position');
to 
 $filter->getQuery()->desc('column_position')->asc(TaskModel::TABLE.'.position');

I find this puts the default Gantt chart in a improved, logical order. Tasks in progress (in columns to the right, and therefore a higher completion percentage based on how this chart works) are listed at the top of the chart with the higher priority ones first. This puts your backlog tasks at the bottom of your chart, vs. the top.

**Comment by Inawire** [comment]
In file /Controller->Gantt.php

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
