### ISSUE TITLE
[FR]Export task csv for entire instance

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#1607]
I just missed an item in an invoice because I didn't check all boards properly. Would be helpful to have aggregate exports available. Thanks for the wonderful software anyway.

**Comment by Soily** [comment]
I just wanted to request the same feature and discovered that you've done so already. Thanks.
Sometimes my supervisor needs to have an overview off all tasks but in a minimalistic view. Therefore the export function would be very helpful.

Thanks Mr. Guillot.

**Comment by fguillot** [comment]
Merging with issue #2951
