### ISSUE TITLE
Color and Category legend

### ISSUE THREAD

**Issue by Sean-Donovan** [kanboard/kanboard#1612]
For organizations that create automatic actions to set a color based on a category (or vice versa) a legend that explains what color goes with which category would be nice.

It will help managers read the kanboard.

**Comment by Busfreak** [comment]
You could try the plugin color_filter:
https://github.com/Busfreak/kanboard-color_filter
With it you can assign system wide labels for colors and in each board you can change them individually.
In the related filters the labels are shaded with the associated color, like a legend.

**Comment by akien-mga** [comment]
I'd like a feature of this kind too, I try to assign colors based on categories to have a better visibility over the current tasks, but so far I did not find an easy way to do it.

Having a built-in way to setup color legends and/or to auto-assign a color to a category would be great :)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
