### ISSUE TITLE
EPIC, US, TASK auto-DONE when all child events are DONE.

### ISSUE THREAD

**Issue by iPublicis** [kanboard/kanboard#1613]
Sorry for my english :)

One thing that I see in almost all projects like this is a lack of automation on epic/us/task/sub-task conclusion automation.

When you have a US with Tasks and those Tasks have Sub-tasks you will/should only work on the Sub-tasks and all the other should never have any really work to do. So when all the Sub-tasks are DONE the related Task should be automatically moved to DONE too. The same related to when all Tasks are DONE, US should me automatically moved to DONE. And the same for Epics, of course.

Does this make sense to you?

And, by the way, thanks for doing something so great like this in PHP.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
