### ISSUE TITLE
Duplicate/Clone project with tasks failed 

### ISSUE THREAD

**Issue by mrfyx** [kanboard/kanboard#1614]
I try to duplicate a project with 39 tasks but the copy is incomplete.

See screenshot below (The new project `QA (clone)` doesn't contain all tasks)

![clipboard01](https://cloud.githubusercontent.com/assets/7872032/12166654/c190d83e-b527-11e5-9417-fab364fa155e.jpg)

There is no error in the browser, just a blank page.

Version 1.0.22

**Comment by fguillot** [comment]
Do you have any php errors in the log files?

**Comment by mrfyx** [comment]
I redo the test at 14:46, there is an error but there are lot of errors before that.

	2016/01/13 10:43:00 [error] 2380#2408: *49143 FastCGI sent in stderr: "PHP Notice:  Undefined variable: changes in C:\kanboard\app\Template\notification\task_update.php on line 3" while reading response header from upstream, client: 10.48.33.63, server: ws, request: "POST /?controller=taskmodification&action=update&task_id=256&project_id=17 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9123", host: "ws.local"
	2016/01/13 10:43:13 [error] 2380#2408: *49143 FastCGI sent in stderr: "PHP Notice:  Undefined variable: changes in C:\kanboard\app\Template\notification\task_update.php on line 3" while reading response header from upstream, client: 10.48.33.63, server: ws, request: "POST /?controller=taskmodification&action=update&task_id=257&project_id=17 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9123", host: "ws.local"
	2016/01/13 10:43:29 [error] 2380#2408: *49253 FastCGI sent in stderr: "PHP Notice:  Undefined variable: changes in C:\kanboard\app\Template\notification\task_update.php on line 3" while reading response header from upstream, client: 10.48.33.63, server: ws, request: "POST /?controller=taskmodification&action=update&task_id=258&project_id=17 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9123", host: "ws.local"
	2016/01/13 10:43:45 [error] 2380#2408: *49253 FastCGI sent in stderr: "PHP Notice:  Undefined variable: changes in C:\kanboard\app\Template\notification\task_update.php on line 3" while reading response header from upstream, client: 10.48.33.63, server: ws, request: "POST /?controller=taskmodification&action=update&task_id=259&project_id=17 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9123", host: "ws.local"
	2016/01/13 10:44:42 [error] 2380#2408: *48857 FastCGI sent in stderr: "PHP Notice:  Undefined variable: changes in C:\kanboard\app\Template\notification\task_update.php on line 3" while reading response header from upstream, client: 10.48.33.64, server: ws, request: "POST /?controller=board&action=save&project_id=17 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9123", host: "ws.local"
	2016/01/13 10:58:27 [error] 2380#2408: *49322 FastCGI sent in stderr: "PHP Notice:  Undefined variable: changes in C:\kanboard\app\Template\notification\task_update.php on line 3" while reading response header from upstream, client: 10.48.33.64, server: ws, request: "POST /?controller=board&action=save&project_id=17 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9123", host: "ws.local"
	2016/01/13 11:14:09 [crit] 2380#2408: *50088 SSL_write() failed (SSL:) (10053: An established connection was aborted by the software in your host machine) while sending to client, client: 10.48.33.63, server: ws, request: "GET /?controller=board&action=check&project_id=17&timestamp=1452679868&_=1452679088154 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9123", host: "ws.local"
	2016/01/13 11:58:03 [error] 2380#2408: *50803 FastCGI sent in stderr: "PHP Notice:  Undefined variable: changes in C:\kanboard\app\Template\notification\task_update.php on line 3" while reading response header from upstream, client: 10.48.33.63, server: ws, request: "POST /?controller=board&action=save&project_id=17 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9123", host: "ws.local"
	2016/01/13 13:54:20 [error] 2380#2408: *52877 FastCGI sent in stderr: "PHP Notice:  Undefined variable: changes in C:\kanboard\app\Template\notification\task_update.php on line 3" while reading response header from upstream, client: 10.48.33.65, server: ws, request: "POST /?controller=taskmodification&action=update&task_id=196&project_id=17 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9123", host: "ws.local"
	2016/01/13 14:46:38 [error] 2380#2408: *53318 FastCGI sent in stderr: "PHP Notice:  Undefined variable: changes in C:\kanboard\app\Template\notification\task_update.php on line 3" while reading response header from upstream, client: 10.48.33.65, server: ws, request: "POST /?controller=board&action=save&project_id=17 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9123", host: "ws.local"

**Comment by mrfyx** [comment]
oups wrong file, it's my nginx server log. My php logs are not enable. I will redo the test later

**Comment by mrfyx** [comment]
I don't think I have another file in this case, right ?

**Comment by mrfyx** [comment]
It seems that log and clone action are not linked.
Anyone else can do the test ?

**Comment by fguillot** [comment]
You can also enable the debug mode then duplicate the same projects and see if you have any error in the log files.

**Comment by CoMPaTech** [comment]
Trying to duplicate a project the debug log shows https://gist.github.com/CoMPaTech/33d50323b4347e82b9f7
