### ISSUE TITLE
403 error trying to access the subdirectory containing kanboard without the trailing slash

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#1622]
I have a kanboard instance here that I upgraded for the last time in May 2015. Today I tried bringing it up to the latest stable version, like so:

```
$ git remote update
From https://github.com/fguillot/kanboard
 * [new tag]         v1.0.15    -> v1.0.15
 * [new tag]         v1.0.16    -> v1.0.16
 * [new tag]         v1.0.17    -> v1.0.17
 * [new tag]         v1.0.18    -> v1.0.18
 * [new tag]         v1.0.19    -> v1.0.19
 * [new tag]         v1.0.20    -> v1.0.20
 * [new tag]         v1.0.21    -> v1.0.21
 * [new tag]         v1.0.22    -> v1.0.22

$ git checkout v1.0.22
Previous HEAD position was fa59a14...
HEAD is now at f8bb0b4...

$ php ~/composer.phar install
```

This worked fine, except that when I try to access that directory (at "my_domain/kanboard"), I get a 403 error. This is a shared hosting service, I do not have access to the httpd logs, so I just compared the permissions of the files between the old and new version, and they seem to be the same (and I don't see something obviously wrong with them).

But then, I made an interesting discovery:
* if I try to access my_domaine/kanboard/index.php  I get the login page, no 403
* if I try to access "my_domain/kanboard/", *with* the trailing slash, then it works.

```$ git blame .htaccess``` makes me suspect one of the changes you made during the past few months might be the cause?

Could you make it work without the need for a trailing slash (it used to work)?

**Comment by fguillot** [comment]
Did you try without the .htaccess?

**Comment by nekohayo** [comment]
I can confirm that if I rename the .htaccess to something else, it works without the trailing slash (but then you don't get pretty URLs).

**Comment by fguillot** [comment]
Try to proceed by elimination to find what is causing the problem in the .htaccess:

```
<IfModule mod_rewrite.c>
    Options -MultiViews

    SetEnv HTTP_MOD_REWRITE On

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [QSA,L]
</IfModule>

<FilesMatch "(kanboard|config.php|config.default.php)">
    <IfModule mod_version.c>
        <IfVersion >= 2.3>
            Require all denied
        </IfVersion>
        <IfVersion < 2.3>
            Order allow,deny
            Deny from all
        </IfVersion>
    </IfModule>

    <IfModule !mod_version.c>
        Order allow,deny
        Deny from all
    </IfModule>
</FilesMatch>
```

Try to remove to FilesMatch section, then test, etc... so you can isolate and report the problem.

**Comment by nekohayo** [comment]
So, I isolated the problem. The first ifmodule block/section is not a problem, but the second one (inside the filesmatch section) is the cause. Specifically, if any of those two (one, or another) is present, the 403 will occur:
```
        <IfVersion >= 2.3>
            Require all denied
        </IfVersion>
```
or:
```
        <IfVersion < 2.3>
            Order allow,deny
            Deny from all
        </IfVersion>
```

The last remaining IfModule doesn't trigger the issue.

**Comment by fguillot** [comment]
Do you know which Apache version is it?

**Comment by nekohayo** [comment]
This is Apache 2.2.29 with PHP 5.4.45 running on CentOS 6.7 (shared hosting by Hostgator).

**Comment by EmFl** [comment]
Hello,
I had kind of a similar problem so posting this here instead of creating a new issue. I had 403 if accessed without the trailing / and 404 if accessed with the /

I'm using mod_alias to get /kanboardnew to display from a directory outside my docroot (ie /data/www/kanboard-test)
I had to change the .htaccess file from 
    RewriteRule ^ index.php [QSA,L]
to
    RewriteRule ^ /kanboardnew/index.php [QSA,L]

and now it seems to work fine
Don't know if this can help

**Comment by xmnr0x23** [comment]
Had similar problems trying to get it to run on a One.com host. Renamed the htaccess file and was able to login. Using the latest build.

**Comment by SylvainMoingeon** [comment]
Same issue on the webserver of my Qnap TS-253A NAS : 403 error without the trailing slash.
Works fine with the trailing slash.

**Comment by preparationh67** [comment]
Also getting this issue. Apache 2.4.18, PHP 5.6.18. I think the file match rule for "kanboard" is causing the issue and is matching the kanboard directory without a slash instead of just the kanboard file. (Assuming this is the intention of the check) This would also explain why @EmFl was able to get it to work with "/kanboardnew" instead of just "/kanboardnew/" as it would not run into that conflict.

**Comment by preparationh67** [comment]
This modification seems to be working for me in that it is allowing the redirect from "/kanboard" as well as blocking access to "/kanboard/kanboard".
```
<Files "kanboard">
    <IfModule mod_version.c>
        <IfVersion >= 2.3>
            Require all denied
        </IfVersion>
        <IfVersion < 2.3>
            Order allow,deny
            Deny from all
        </IfVersion>
    </IfModule>

    <IfModule !mod_version.c>
        Order allow,deny
        Deny from all
    </IfModule>
</Files>

<FilesMatch "(config.php|config.default.php)">
    <IfModule mod_version.c>
        <IfVersion >= 2.3>
            Require all denied
        </IfVersion>
        <IfVersion < 2.3>
            Order allow,deny
            Deny from all
        </IfVersion>
    </IfModule>

    <IfModule !mod_version.c>
        Order allow,deny
        Deny from all
    </IfModule>
</FilesMatch>
```

**Comment by preparationh67** [comment]
I was wrong in that this solution is not working. From my understanding the files directive should have worked and not matched on the directory, so I am not sure what the best way to implement this is in the .htaccess file. I was able to get the correct behavior moving the FilesMatch directive inside of a Directory block, but this cannot be done in .htaccess, only the Apache configs.

**Comment by arysom** [comment]
@EmFl same here, my kanboard was installed in subdomain

` RewriteRule ^ /mykanboarddir/index.php [QSA,L]`

worked. Thanks.

**Comment by fguillot** [comment]
I'm not able to reproduce this issue, I tried with:

- Ubuntu Precise (Apache 2.2)
- Centos 6.7 (Apache 2.2)
- Ubuntu Xenial (Apache 2.4)

**Comment by tommiehansen** [comment]
Just did a default install on WAMP 3+.
Same problem (403). Only a modified version of the .htaccess works.

**Comment by rickarubio** [comment]
As suggested above, I was able to get this to work with /kanboard (no trailing slash) by changing this line in the .htaccess file:

```RewriteRule ^ index.php [QSA,L]```

to 

```RewriteRule ^ /kanboard/index.php [QSA,L]```

However, I can still access /kanboard/kanboard, so I think the .htaccess file as is has an issue with preventing access to that file.

**Comment by asmundstavdahl** [comment]
Adding a `/?` after `kanboard` in the FilesMatch directive worked for me.

My installation is also located in a subdirectory, at `/kanboard/`.
```
<FilesMatch "(kanboard/?|config.php|config.default.php)">
```

**Comment by asmundstavdahl** [comment]
I suggest wrapping the whole FilesMatch directive in an inverted IfModule directive to check if mod_rewrite is on.
If mod_rewrite is on, we don't need to deny access to the files; all URLs are already rewritten to index.php.

This is my .htaccess file now, works wonders for me.
```xml
<IfModule mod_rewrite.c>
    Options -MultiViews

    SetEnv HTTP_MOD_REWRITE On

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [QSA,L]
</IfModule>

<IfModule !mod_rewrite.c>
    <FilesMatch "(kanboard|config.php|config.default.php)">
        <IfModule mod_version.c>
            <IfVersion >= 2.3>
                Require all denied
            </IfVersion>
            <IfVersion < 2.3>
                Order allow,deny
                Deny from all
            </IfVersion>
        </IfModule>

        <IfModule !mod_version.c>
            Order allow,deny
            Deny from all
        </IfModule>
    </FilesMatch>
</IfModule>
```

**Comment by wintstar** [comment]
This works. Thanks
