### ISSUE TITLE
Extend task transitions table

### ISSUE THREAD

**Issue by i-alex-i** [kanboard/kanboard#1625]
Hello, first of all, great job & hapy new year! 

I would like to record new 'src_swimlane_name' and 'dst_swimlane_name' fields in the transition table for task. How i can do that? 

can it be done through a plugin? if so I need more help that existing documentation, especially how catch task transition events and how to put them in DB and how to retrieve them.

I confirm the bug on email notifications, only one project remains selected and notifies.
Reference: Unable to select more than one Project to receive notifications from #1453
This is on Xampp/win/Apache/sql-wind

Regards

**Comment by fguillot** [comment]
If you need to alter the table schema, the best way is to contribute upstream. You could do that with a plugin but you are going to override a lot of stuff.
