### ISSUE TITLE
Sorting "Column" column in Search tasks out of order

### ISSUE THREAD

**Issue by jeffshieldsdev** [kanboard/kanboard#1639]
![image](https://cloud.githubusercontent.com/assets/8429539/12232738/c153061a-b826-11e5-9159-367bf7b64cc7.png)

Thank you.

**Comment by fguillot** [comment]
Which database type are you using: sqlite, postgres or mysql?

**Comment by jeffshieldsdev** [comment]
sqlite.  My setup is pretty vanilla.

**Comment by fguillot** [comment]
Which sqlite version do you have? and which OS?

**Comment by jeffshieldsdev** [comment]
Windows 7 64-bit.  I'm using XAMPP 5.6.20 which has MariaDB 10.1.13.  Thanks.

**Comment by jeffshieldsdev** [comment]
Here's the URL:

`http://localhost/kanboard/?controller=search&action=index&search=color%3AYellow+status%3Aopen&page=1&order=tasks.column_id&direction=ASC`

Is it sorting on the column's numeric ID instead of its "title"?

**Comment by fguillot** [comment]
This issue should be fixed with the latest version of KB. The sorting is now using the column name instead of the id.
