### ISSUE TITLE
Use same task id as gitlab's issue id

### ISSUE THREAD

**Issue by SSDAM** [kanboard/kanboard#1655]
Hello.
I'm enjoying Kanboard so much. The reason of this issue is I'm not having the best user experience.
My Kanboard tasks have a different id compared to gitlab's issues. I would like to use Kanboard most of the time but when I'm going to close an issue with "Fix #34 issue" (as an example) I have to go to Gitlab to see the real issue ID because issue 2 in Gitlab, can be 54 in Kanboard. 
How can I use per project id's in Kanboard?

Thanks!

**Comment by fguillot** [comment]
I understand your point, but task IDs in Kanboard are the auto increment field value that come from the database.

If anyone have any suggestions to tackle this point, create issues to https://github.com/kanboard/plugin-gitlab-webhooks.
