### ISSUE TITLE
Throughput diagram support ..

### ISSUE THREAD

**Issue by JohnBat26** [kanboard/kanboard#1659]
Kanboard has many important kanban diagram:
- Lead time diagram;
- Cycle time diagram;
- Cumulative flow  diagram;
- ...

What about Throughput diagram support? 
It would be a great addition to kanboard!

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
