### ISSUE TITLE
Gant Chart only visible for Project Manager

### ISSUE THREAD

**Issue by 85pando** [kanboard/kanboard#1667]
This is probably a design decision, but I want to raise this as an issue.

I think it could be usefull for normal users to be able to see the gant chart also, for example when people need to choose new tasks the gant chart could be an invaluable help to decide which tasks need to be finished soon.

**Comment by rseabra** [comment]
It also improves engagement with the project by not treating members as mere "slaves".

**Comment by mauriziodidomenico** [comment]
due to this circumstances, i set all user as manager, it's really helpful to have a rough schedule overview. and some user need this visual effect, to understand that they can not work on 5 task at the same time!

**Comment by juanluisbaptiste** [comment]
I agree it would be useful to be able to see the gantt view as a project user. Could the author explain why he thinks only projects admins should be able to see the gantt view ?

**Comment by juanluisbaptiste** [comment]
Nevermind my question, I just saw the "Feature request" tag :-)

**Comment by asmwarrior** [comment]
I also need this feature, I think a project user need to see the whole progress of every tasks. Thanks.

**Comment by asmwarrior** [comment]
I'm not familiar with PHP language, but I just looked at the source code from this package https://kanboard.net/kanboard-1.0.41.zip, and in the file `kanboard\app\Template\project_header\views.php`, it has such content:

```
<ul class="views">
    <li <?= $this->app->checkMenuSelection('ProjectOverviewController') ?>>
        <?= $this->url->icon('eye', t('Overview'), 'ProjectOverviewController', 'show', array('project_id' => $project['id'], 'search' => $filters['search']), false, 'view-overview', t('Keyboard shortcut: "%s"', 'v o')) ?>
    </li>
    <li <?= $this->app->checkMenuSelection('BoardViewController') ?>>
        <?= $this->url->icon('th', t('Board'), 'BoardViewController', 'show', array('project_id' => $project['id'], 'search' => $filters['search']), false, 'view-board', t('Keyboard shortcut: "%s"', 'v b')) ?>
    </li>
    <li <?= $this->app->checkMenuSelection('CalendarController') ?>>
        <?= $this->url->icon('calendar', t('Calendar'), 'CalendarController', 'project', array('project_id' => $project['id'], 'search' => $filters['search']), false, 'view-calendar', t('Keyboard shortcut: "%s"', 'v c')) ?>
    </li>
    <li <?= $this->app->checkMenuSelection('TaskListController') ?>>
        <?= $this->url->icon('list', t('List'), 'TaskListController', 'show', array('project_id' => $project['id'], 'search' => $filters['search']), false, 'view-listing', t('Keyboard shortcut: "%s"', 'v l')) ?>
    </li>
    <?php if ($this->user->hasProjectAccess('TaskGanttController', 'show', $project['id'])): ?>
    <li <?= $this->app->checkMenuSelection('TaskGanttController') ?>>
        <?= $this->url->icon('sliders', t('Gantt'), 'TaskGanttController', 'show', array('project_id' => $project['id'], 'search' => $filters['search']), false, 'view-gantt', t('Keyboard shortcut: "%s"', 'v g')) ?>
    </li>
    <?php endif ?>
</ul>
```

So, there is a `if` condition check to decide whether we need to show the gantt char, so can we just remove this `if` condition check?

**Comment by asmwarrior** [comment]
Oh, for [https://kanboard.net/kanboard-1.0.41.zip](https://kanboard.net/kanboard-1.0.41.zip), it looks like this code is controlling whether the gnatt is shown or not:
`kanboard\app\ServiceProvider\AuthenticationProvider.php`, it's 92 line is:
`$acl->add('TaskGanttController', '*', Role::PROJECT_MANAGER);`, which means only project manager can access to the gantt controller. It is checked in the function below in file `\kanboard\app\Helper\ProjectRoleHelper.php`

```
    /**
     * Check project access
     *
     * @param  string  $controller
     * @param  string  $action
     * @param  integer $project_id
     * @return bool
     */
    public function checkProjectAccess($controller, $action, $project_id)
    {
        if (! $this->userSession->isLogged()) {
            return false;
        }

        if ($this->userSession->isAdmin()) {
            return true;
        }

        if (! $this->helper->user->hasAccess($controller, $action)) {
            return false;
        }

        $role = $this->getProjectUserRole($project_id);

        if ($this->role->isCustomProjectRole($role)) {
            $result = $this->projectAuthorization->isAllowed($controller, $action, Role::PROJECT_MEMBER);
        } else {
            $result = $this->projectAuthorization->isAllowed($controller, $action, $role);
        }

        return $result;
    }
```

BTW: for kanboard 1.0.42, the [plugin-gantt](https://github.com/kanboard/plugin-gantt) code, the access control is under the file `Gantt\Plugin.php` as below:

```
class Plugin extends Base
{
    public function initialize()
    {
        $this->projectAccessMap->add('TaskGanttController', '*', Role::PROJECT_MANAGER);
        $this->applicationAccessMap->add('ProjectGanttController', '*', Role::APP_MANAGER);

        $this->route->addRoute('gantt/:project_id', 'TaskGanttController', 'show', 'plugin');
        $this->route->addRoute('gantt/:project_id/sort/:sorting', 'TaskGanttController', 'show', 'plugin')
```

So, I need to change the `Role::PROJECT_MANAGER` to `Role::PROJECT_MEMBER`?

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
