### ISSUE TITLE
Who is using Kanboard?

### ISSUE THREAD

**Issue by phillc73** [kanboard/kanboard#1693]
Not sure if it's useful, but I always seem to notice many projects list on their website some prominent companies using the product. Would this be something helpful in promoting Kanboard?

In November 2015, I initiated use of Kanboard at the Research Centre for Pharmaceutical Engineering (RCPE - http://www.rcpe.at/) in Graz, Austria.

It is only being used from one project at the moment, but many people are interested and have asked for an overview. 

 I migrated people away from Excel and OneNote, although sometimes MS Project's enhanced Gantt presentation view is required (dependencies mostly).

**Comment by mauriziodidomenico** [comment]
I started this year with kanboard im my development group (mechanical engineering), the goal is to migrate away from onenote, excel and Post It. And of course to force a global rollout for the development teams.

At the moment a can't name my company, but i will ask for permission.

**Comment by sparkles645** [comment]
Public utilities, engineering, operations and maintenance.

**Comment by bdrayer** [comment]
We use it to manage tasks for our production/R&D/SAV/Software_dev and I personnaly use it for IT ticketing (there is still some features missing for having a good ticketing system but I am the only IT guy so it's OK).

**Comment by AlgyTaylor** [comment]
The Bioinformatics Group @ the Manchester Centre for Genomic Medicine (NHS / UK)

**Comment by nttict-nick-b** [comment]
I'm a project manager at NTT ICT and we're trying it out in our DevOps (automation) team

**Comment by lgibelli** [comment]
https://todo.kde.org

**Comment by giuntim** [comment]
We use it:
http://www.codeguru.it/

**Comment by pmcfernandes** [comment]
My team changed from tfs to kanboard because is more easy to use and more fast

**Comment by aljawaid** [comment]
I use it to manage my small business... admin jobs/tasks etc that are away from the products etc

**Comment by DominicBoisvert** [comment]
We are. We use Kanboard to manage our internal projects and our clients projects (external).

We are a team of five archivists, managing records and archives in roughly 100 small towns in Quebec, Canada.

URL : https://www.hbarchivistes.qc.ca (we are archivists, not website designers)

**Comment by fguillot** [comment]
Closing this thread to avoid cluttering the bug tracker. There is now a forum for open disussions: https://forum.kanboard.net/topic/2
