### ISSUE TITLE
Different columns per swim lane 

### ISSUE THREAD

**Issue by andrenth** [kanboard/kanboard#1695]
Hi

I'm using swim lanes for different types of work, but sometimes these require different columns, since what makes sense for one swim lane's workflow might not make sense for others.

Do you have plans to add this feature?

Thanks,
Andre

**Comment by fguillot** [comment]
Not yet, for now the focus is simplicity.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
