### ISSUE TITLE
Display Description onMy Task page

### ISSUE THREAD

**Issue by sandipsavani** [kanboard/kanboard#1696]
how to display description on my task page

**Comment by fguillot** [comment]
You have to modify the code.

**Comment by sandipsavani** [comment]
in which file
and which code

**Comment by Busfreak** [comment]
You have to edit different files:
new column to display the description in task page: Template/app/tasks.php
function for getting description from database: getUserQuery in Model/Taskfinder.php
and maybe a little CSS.

Hope that helps.

**Comment by sandipsavani** [comment]
Will u plz give me all file with code
