### ISSUE TITLE
Setting time besides a date in the task due field

### ISSUE THREAD

**Issue by lehrhardt** [kanboard/kanboard#1701]
Hi,

I'd like to set a specific time besides a date in the due field of a task. At the moment it seems that it is only possible to enter fixed dates like 2016-01-01 or 2016_01_01 in the edit section.

Where does kanboard store the time information if I drag a task in the calendar view to a specific time slot?

**Comment by patrickvanelk** [comment]
The time of a due date is also not used when the iCal-feed is generated, I think. All my due tasks are set to "All day".

**Comment by fguillot** [comment]
Duplicate with #919
