### ISSUE TITLE
Editing a task to move swimlanes

### ISSUE THREAD

**Issue by SchmilK** [kanboard/kanboard#1705]
I have a complaint from a user that has over a dozen swimlanes saying she can't easily move a task from say, swimlane 12 to swimlane 1 because it is off the screen, even when all swimlanes are minimized.

I noticed if you edit a task you can move it to a new project which has the ability to assign a swimlane, but simply editing a task does not have an entry to change swimlane.

**Comment by BlueTeck** [comment]
Did you mean the same as in #696 ?

**Comment by Busfreak** [comment]
I created a pull request resolving the missing field: https://github.com/fguillot/kanboard/pull/1707

**Comment by SchmilK** [comment]
Yes thank you!

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
