### ISSUE TITLE
Navigation confirmation with unsaved edits

### ISSUE THREAD

**Issue by jeffshieldsdev** [kanboard/kanboard#1727]
It would be nice for a confirmation message before navigating away from pages with unsaved edits.

For example, I was working on a lengthy Comment in a Task and noticed the Start Date was wrong, so I clicked on Edit the Task to update the start date and in doing so lost the comment I was drafting.  It would have been nice to get a message "you have unsaved edits. are you sure you want to continue?" or similar.

Thank you.

EDIT: another example: while adding a comment I entered a "Time estimated" and clicked the companion Save button.  This saved the Time estimated but cleared out the comments I was drafting.

**Comment by fguillot** [comment]
Duplicate with #1019
