### ISSUE TITLE
how to modify the column width of "Project" in the Dashboard?

### ISSUE THREAD

**Issue by lowabr** [kanboard/kanboard#1731]
In the Dashboard view, how can I increase the width of column "Project" under "My Projects"?

![image](https://cloud.githubusercontent.com/assets/12190682/12564081/5c0f88e0-c37b-11e5-887d-d477470ad470.png)

**Comment by fguillot** [comment]
You have to modify this file: https://github.com/kanboard/kanboard/blob/master/app/Template/dashboard/projects.php or override the CSS.
