### ISSUE TITLE
The user role is too simple

### ISSUE THREAD

**Issue by musahi0128** [kanboard/kanboard#1747]
the user with project member privilege can do too much about task assigned to other member, they can even delete the task. The project viewer can't event comment, literally can do nothing, just looking to the project. I hope there is improvement in this aspect. I really love the concept and the simplicity tho, love it :+1:

**Comment by fguillot** [comment]
What do you suggest about that?

Kanboard focus on simplicity, the role and permissions system is voluntary simple.

**Comment by musahi0128** [comment]
In my case i need that : a task can only deleted by the project manager; someone who assigned to a task can only add subtask and move the task around the board; everyone who allowed / involved in a project can comment however they like, and the project manager have the ability to manage those comments, or even better a comment have to be approved by project manager before show it to entire project member / viewer.

**Comment by cstott-se** [comment]
I agree with the comment about comments.

I have a scenario where I'd like the project viewer to be able to comment on a task. For example, if the developer is working on the task but it gets blocked (e.g., information not clear, etc.) I'd like the requester (the project viewer) to be able to check the status of the task and when they see it is blocked add the necessary information to complete the work. That would be helpful.

**Note:** I'm not a fan of having the PM "approve" comments. Too much extra work.

**Comment by fguillot** [comment]
There are custom roles now.
