### ISSUE TITLE
Filter on tasks that have not been modified since x days

### ISSUE THREAD

**Issue by fbartels** [kanboard/kanboard#1751]
Hi,

I'd like to filter on tasks that have not been modified since a certain time.

I have already found the filter "modified:recently" which shows only tickets that have been changed in the last two days. And I know that I can set specific days e.g. "modified:<2016-01-20".

But I'd like to have this dynamic so I can save this as a filter. So something like "modified:<-2 weeks" would be nice, but does not produce any results.

EDIT: adapted to search to "modified:<-2 weeks" , but this also returns no results

**Comment by fguillot** [comment]
I don't believe that this feature exists yet.
