### ISSUE TITLE
feature request: add a new project as another project's task

### ISSUE THREAD

**Issue by zhangyv163** [kanboard/kanboard#1770]
It will be great if a new project can be created as a task in its parent project(other tasks still can be added in the same level)  for managing some complex projects or tasks.

**Comment by mauriziodidomenico** [comment]
:+1:

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited.

Thank you for your understanding
