### ISSUE TITLE
Feature request: global custom filters

### ISSUE THREAD

**Issue by patrickvanelk** [kanboard/kanboard#1772]
Would be nice to have some sort of global custom filters, e.g. to add a custom filter like `assignee:me due:<=2016-02-03 status:open` so I can see all my (over-)due tasks for all projects.

**Comment by oliviermaridat** [comment]
+1

**Comment by anklaa** [comment]
+1

**Comment by dominicwa** [comment]
+1

**Comment by mapeze** [comment]
+1

**Comment by mapeze** [comment]
kanboard/app/Template/app/filters_helper.php can be easily edited to add custom global filters.

**Comment by wucherpfennig** [comment]
Is there a way to properly override this file?

**Comment by razron** [comment]
kanboard/app/Template/app/filters_helper.php  doesn't exist anymore.

Any other suggestions on how to do this?

Otherwise +1

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
