### ISSUE TITLE
Order in cumulative flow diagram should match columns

### ISSUE THREAD

**Issue by rodja** [kanboard/kanboard#1775]
The CFD visualizes progress as cards flow from first column to the last. To make it more readable the order of the columns should be kept in the diagram. Example:

![cfd](https://cloud.githubusercontent.com/assets/131391/12806851/e63885fe-cb09-11e5-90b5-1953c3a288f6.png)

It's hard to see how items flow from "backlog" through "ready" and then further to "work in progress" until they are "done". The current implementation totally mixes the stacking in the diagram.

**Comment by BlueTeck** [comment]
:+1:

**Comment by BlueTeck** [comment]
I think in this method the column position should be respected:

https://github.com/fguillot/kanboard/blob/1259e911e4316f9f1ae401f4f293da69d9ba9e78/app/Model/ProjectDailyColumnStats.php#L120

**Comment by tvriend** [comment]
:thumbsup:

**Comment by balatone** [comment]
This is important for visualizing WIP and lead time correctly. So definitely nice if this could be corrected. :+1:

**Comment by fguillot** [comment]
This issue should be fixed in v1.0.39.
