### ISSUE TITLE
Close Tasks should respect the current filter

### ISSUE THREAD

**Issue by iaanus** [kanboard/kanboard#1776]
Use case:
- While displaying a board, select any filter
- On the dropdown menu of a column that contains filtered tasks, select the "Close all tasks of this column"

Actual result: all tasks in the column (both visible and hidden) are closed
Expected result: all visible tasks are closed, while all other (hidden) tasks should be unaffected

**Comment by NinjaPewPew** [comment]
:+1:

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
