### ISSUE TITLE
Cumulative flow diagram: filter by swimlane

### ISSUE THREAD

**Issue by rodja** [kanboard/kanboard#1780]
It would be nice to filter the CFD by swimlane to better analyze performance.

**Comment by Busfreak** [comment]
:+1: 
an even in all other reports!

**Comment by RageAgainstTheVM** [comment]
:+1:

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
