### ISSUE TITLE
Use fullname instead of username on assigned tasks

### ISSUE THREAD

**Issue by yurimpn** [kanboard/kanboard#179]
Hello

I am using LDAP authentication with MS-AD and my logins are all numeric codes. So, it is confusing when i need to assign a task to someone.

It is possible to use the full name instead of username on assigned tasks? if not i would like to request as a new feature.

Thanks for the attention and thanks for the great job on this software

**Comment by mkromka** [comment]
Sorry for asking, I have initial as a assigned user on task.
Where I can switch to display full name instead of initial?

**Comment by MaverickVG** [comment]
same here, after an major update (was 0.17) I just have initials on the tasks. Where can I set the full names?
