### ISSUE TITLE
Two way issue sync [feature request]

### ISSUE THREAD

**Issue by liladani** [kanboard/kanboard#1796]
Issues got via the webhook should notify gitlab if the issue changed or closed in kanboard.
This could be an opt-in feature that should be only applicable to issues imported / pushed in from Gitlab (or other provider).

**Comment by michaeltlombardi** [comment]
This would bring kanboard up to feature parity with the only competing software I like more: [waffle](https://waffle.io) - though waffle still only works with GitHub, so KanBoard is getting all of my love.

**Comment by fguillot** [comment]
Duplicate with https://github.com/kanboard/plugin-gitlab-webhook/issues/5
