### ISSUE TITLE
Add support for RTL language

### ISSUE THREAD

**Issue by myuser1234** [kanboard/kanboard#1799]
Hi,

I find kanboard very useful, so first of all thanks!

I'm using kanboard in hebrew which is right-to-left language.
I wonder if it's possible to add support for that.

In my kanboard I edited the app.css so that in the main locations I would see the hebrew text correct.

for example:
in class = task-board-title
i've added:
    direction: rtl;
    text-align: right;
(both necessary for correct hebrew and english visual correct)

you can see the example in the attached image:
![untitled](https://cloud.githubusercontent.com/assets/16746176/12879878/971a63de-ce42-11e5-9bdd-c56fa3d83134.jpg)

thanks!

**Comment by fguillot** [comment]
The best way to have RTL support is to contribute directly to the project.
