### ISSUE TITLE
Ability to edit / modify / change automatic actions

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#1804]
Currently the only way to change an automatic action is to delete it and recreate it from scratch, which is error-prone and very inefficient.

**Comment by RobHoffman** [comment]
I support this request to be able to edit an action.

**Comment by X3msnake** [comment]
+1

What is needed to be able to do this? where is this stored?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
