### ISSUE TITLE
Ability to duplicate automatic actions for fast creation

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#1805]
Currently, creating multiple variants of the same action (same events and rules, but with with different parameters) is a pain. Would be great if the board properties' "automatic actions" page allowed inheriting (duplicating + configuring) from an existing automatic action.

Also, when creating a new automatic action, there should be a checkbox at the end for "[x] Create another automated action with the same event and action rules?".

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
