### ISSUE TITLE
Simpler UX/design for the automated actions summary table

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#1806]
As seen in the screenshot below, there's two or three times more semantic and visual complexity than there needs to be, it's hard to filter out the noise:

![automated column-based colors](https://cloud.githubusercontent.com/assets/479401/12892717/6f442868-ce5b-11e5-806f-670ad6486b64.png)

I would suggest a simpler table, with no header row, using natural language and string substitutions. So for example, the first row would look like this:

```
When moving a task to column "Coincé/En attente",      ||  * Modify 
assign color "Grey".                                   ||  * Duplicate
                                                       ||  * Remove
```

(Notice the subtle `<br />` in the sentence to make it multi-line and easier to parse, visually separating the action from the trigger event)

Also related to issue #1804 and issue #1805.

**Comment by kwijk** [comment]
What about analogies in other software. Like Microsofts Outlook rules concept

**Comment by yannicka** [comment]
I think this can be implemented with a new method in `Kanboard\Action\Base` class, like `getDescription()`.

Maybe a method named `getNaturalLanguageDescription()` that returns a translatable string.

This method would be abstract and overrided in subclasses, for example in `TaskAssignColorColumn` with `When moving a task to column "%s", assign color "%s".`.

But for now, I don't know how to access to the column value and the color? It seems that `getParam()` returns an empty string.

@fguillot: How would you do that?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
