### ISSUE TITLE
"Attach an image" option in the "new task" menu

### ISSUE THREAD

**Issue by Giedrius173** [kanboard/kanboard#1809]
Hi,

When creating a new task, or editing a task; it would be great to have "attach an image" feature among the options. For example, instead  of "Write your text in Markdown" link.

![image](https://cloud.githubusercontent.com/assets/17138370/12911334/7dd16c00-cf1a-11e5-8651-e4557404fc4a.png)

Usually task requests are accompanied by a screenshot either from design or QA highlighting specific bug.  Currently there is no way to attach those in the new task window - you have to create the task, describe it, close it, find the task again, open & attach, and close again. Way too complicated.

Thanks,

**Comment by nttict-nick-b** [comment]
Yes, without first saving the task, there is no ID in the database to associate the uploaded file with. Perhaps a "save and keep open" checkbox as well as a "create another task" one?

**Comment by nttict-nick-b** [comment]
@fguillot - how do you want to deal with this one buddy? Do you have a preferred drag'n'drop JS library you want to use? I see in the Model that a File needs a Task ID, so we'll need to either force the user to save the record before the file is uploaded, or drop it somewhere temporary, assign a NULL task ID, then update task_id for the File after the task is saved. Or any other ideas?

**Comment by paddymac841** [comment]
@nttict-nick-b - Have you had any luck with this issue? Would like to try to develop this for my system.

**Comment by fguillot** [comment]
@nttict-nick-b There is already the possibility to drag and drop files for tasks and projects. That use the HTML5 File API (See `FileUpload.js`). To upload a file a task ID is necessary. So the UI or the flow to create a task probably need to be modified.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
