### ISSUE TITLE
Feature:  Batch actions up

### ISSUE THREAD

**Issue by ghost** [kanboard/kanboard#1821]
The current behavior of the app appears to be immediately sending an email upon any changes to an item.  Rather than immediately email upon any change it'd be a bit more user (and inbox) friendly if Kanboard waited a period of time (user configurable, say 5 minutes) before it emailed out changes.  Such that if an item gets changed from green to red, and a comment is added to that item, and it's task position is changed only one email is sent instead of 3.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
