### ISSUE TITLE
Help with Analytic

### ISSUE THREAD

**Issue by decost96** [kanboard/kanboard#1826]
Greetings, my concern is to know where the functions are used for Analytic function and how the query is made to the database for Analytic function is.

Also find out which tool was made Kanboard

Note:
If someone in the community could help me was the great maid ....

**Comment by BlueTeck** [comment]
Do you read this: https://github.com/fguillot/kanboard/blob/master/doc/analytics.markdown

**Comment by decost96** [comment]
That if I know what I need is to know where the function that is used to make these graphics and as obtained from the Database ....

**Comment by BlueTeck** [comment]
look into this folder: https://github.com/fguillot/kanboard/tree/master/app/Analytic
