### ISSUE TITLE
[Task] french record  "compte rendu"

### ISSUE THREAD

**Issue by tortue-geniale** [kanboard/kanboard#1828]
Me again,

Every week, i must to produce a record of activity.
So my team use comments' task to summarize the task treating.

And i scripted a .py to 
- connect database , 
- select tasks between two dates (for me : Monday 8h00, Friday 18h00)
- with specific project or not with specific swinlines or not ...
- format the result
- push me a mail which i can transform if necessary (mistake about a comment).

What do you think about a feature to send a similar record every weeks.... ?
I give mi idea :) if it doesn't already exist.

Bye.

**Comment by fguillot** [comment]
You can use the command line utility of Kanboard: http://kanboard.net/documentation/cli

Export tasks in CSV, pipe the output to the mail command and run that in a cronjob.
