### ISSUE TITLE
Is there a 'Move to column' somewhere 

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#1831]
Seems drag and drop doesn't work on my Nexus 7, how can I move a task? 
Thanks

**Comment by BlueTeck** [comment]
On mobile devices there should be this little icon for drag and drop:

![image](https://cloud.githubusercontent.com/assets/1961634/13005806/b14d44a2-d184-11e5-9574-4d01d03e3b62.png)

**Comment by thob** [comment]
It is, but not very usable unless you got very small fingers or a bigger screen, lower resolution. I think a command in the menu is helpful.

**Comment by fguillot** [comment]
Not yet, this feature is missing.

**Comment by fguillot** [comment]
This is now available in version 1.0.33
