### ISSUE TITLE
Feature request: simplify usage of swimlanes as iterations

### ISSUE THREAD

**Issue by huberv** [kanboard/kanboard#1843]
Hi,
In our current project we use kanboard to keep track of iterations. We use one swimlane per iteration (and some additional swimlanes which don't correspond to iterations). It would be very convenient for use, if we could
- define a start and end date for a swimlane (as new optional fields for a swimlane)
- choose a swimlane for all analytics charts instead of having to type in the start and end dates manually every time
- have the start and end dates filled automatically when one chooses a swimlane for e.g. the burndown chart
- have the analytics function restrict the evaluation to tasks contained in the chosen swimlane
- maybe have the swimlane defaulted to the top-most swimlane when one chooses an analytics function

**Comment by oparoz** [comment]
### Additional features

* Swimlanes would show up as milstones in the Gantt charts
* Swimlanes should probably be hidden from the calendar

### Steps to reproduce

1. PM decides to use swimlanes for milestones
1. PM sets start and end date for each swimlanes
1. PM can see milestones on the Gantt chart, above each group of tasks belonging to the swimlane

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
