### ISSUE TITLE
[FR] Subtask PreAssing

### ISSUE THREAD

**Issue by TabDambrine** [kanboard/kanboard#1854]
Hi, I've searched quickly trough the issues and I've not seen this feature request.

As for now when a user create a task the field assign to is set to the current user, that's great and the pre-assignation could be useful on subtasks too.

What i'm proposing is that when creating a new subtask the assignee dropdownlist to be pre-selected on the user assigned to the task if available and the current user (like task creation) otherwise.

**Comment by fguillot** [comment]
This is the case on latest version of KB.
