### ISSUE TITLE
Import from github issues

### ISSUE THREAD

**Issue by kamov** [kanboard/kanboard#1866]
Hi
is possible to import all issues already added from github?
thanks

**Comment by GDmac** [comment]
You could make an app (or plugin) to communicate between
https://developer.github.com/v3/issues/ <===> http://kanboard.net/documentation/api-json-rpc

**Comment by kamov** [comment]
thanks for your reply
I guess if exist something already.
I see that exist import via CSV, seem that I just need then to export issue to csv?

**Comment by fguillot** [comment]
You can use this plugin to import Github Issues into Kanboard: https://kanboard.net/plugin/github-frontend
