### ISSUE TITLE
Can't manually set the start and end date by typing into the text entry

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#1867]
With Kanboard 1.0.25, I tried editing a task to set the start and end date, and never managed to get it to work by typing it.

I tried these syntaxes:

* 2014-06-01 (as per issue #69)
* 2014-06-01 00:00
* 2014/06/01
* 2014/06/01 00:00

None of them worked. Kanboard always replaces them by "12/31/1969 19:33" (for the start date) and "1969/12/31" for the due date, and says "Invalid date". It's as if it would only work if using the calendar widget (which I don't want to use because using the mouse slows me down and you can't jump across years easily).

**Comment by fguillot** [comment]
The ISO8601 format should always work...

It's working for me, which version of Kanboard are you using?

Don't forget that the field "start date" must contains the time (2016-02-23 20:59) and the "due date" contains only the date (2016-02-23)

**Comment by fguillot** [comment]
Probably related to #2251
