### ISSUE TITLE
Public Access - Calendar and Gantt option?

### ISSUE THREAD

**Issue by nztebs** [kanboard/kanboard#1873]
### Requested behaviour

Currently, we can enable public access which gives us a readonly link to the project board, an RSS link and an iCal link.  

I have a board that would be best viewed as either the Calendar view or the Gantt view. If I use the public url provided, and change the 'controller' parameter to 'calendar', I get page not found. (I'm guessing because a public view is not enabled in the code?)

Is it possible presently, or by a new feature request, to provide a readonly link to the calendar and gantt view of a board please?
### Configuration
- Kanboard version: 1.0.18
- Database type and version: mysql

**Comment by badmojo76** [comment]
+1 for this. Ability to filter in public view would be nice too.

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
