### ISSUE TITLE
Edit behaviour

### ISSUE THREAD

**Issue by mterron** [kanboard/kanboard#1875]
Instead of of the edit menu for Edit Task, Edit description, etc can we get something like the little pencil in github on each part?

**Comment by nerdoc** [comment]
There is already the functionality for the comments. Links on the right side make it possible to edit, delete, permlink that comment.
This also should be possible for the task description as well. Should be easily implementable.

**Comment by fguillot** [comment]
This is a duplicate/similar to #2072
