### ISSUE TITLE
Project settings, columns ordering

### ISSUE THREAD

**Issue by baciugithub** [kanboard/kanboard#1877]
### Expected behaviour

In project settings, would like to order columns with drag and drop.

### Actual behaviour

You need to click on the right of column settings icon and then click on Move Up

### Steps to reproduce

1. Click on a project
2. Click on Actions
3. Click on Settings
4. Click on Columns
5. Reorder columns

### Configuration

- Kanboard version: 1.0.25
- Database type and version:  sqlite
- PHP version: 5.4.45
- OS: windows 7 64bits
- Browser: Firefox 44

**Comment by fguillot** [comment]
Drag and drop is available in the development version.
