### ISSUE TITLE
moving task without drag and drop

### ISSUE THREAD

**Issue by sstecker** [kanboard/kanboard#1879]
we are in a test phase so far we very happy with kanboard. I have around 34 columns going in a manufacturing facility with over 200 tasks active with 20 users.  problem I get is moving a task to columns off the page.  is there a way to move a task across columns without dragging?  similar action to changing assignee goes to pulldown menu but for columns?

**Comment by robjurd** [comment]
Please add "move to column" to the task view while you're at it.  cheers!

**Comment by sstecker** [comment]
nice. thank you. downloading and checking it out!
 
Date: Sun, 5 Jun 2016 20:06:36 -0700
