### ISSUE TITLE
Exact time tracking (not rounded) ?

### ISSUE THREAD

**Issue by tangelvy** [kanboard/kanboard#1883]
Hello, 
I would like to count the time spent on subtasks taking only a few minutes. But as it is specified in the documentation, "the calculated time spent is rounded to the nearest quarter", so I get only or 0 or 0.25 hours. Is they a way to have the exact result (or rounded to 0.01) please?
Thank you

**Comment by akaigotchi** [comment]
I'd second that :+1:

**Comment by hivemind** [comment]
Why to round hours to decimals at all? It's much better to store seconds.

**Comment by fguillot** [comment]
The time is not rounded anymore in version 1.0.33.

@hivemind yes, that need to be changed

**Comment by minthemiddle** [comment]
@fguillot Any updates on the storing of seconds instead of decimal hours?
