### ISSUE TITLE
Ability to use the stopwatch feature with toplevel tasks (cards)

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#1885]
There's a neat "stopwatch" feature for subtasks… but my cards/tasks rarely have subtasks, so it would be nice to be able to start and stop the chronograph/stopwatch for a task globally, instead of manually counting and entering the hours spent.

**Comment by Greendeviate** [comment]
I would actually love to see this feature added. I have seen it in other kanban boards and its incredibly useful. Hope this feature request has not been forgotten.

**Comment by dhornford** [comment]
As a work-around we create subtasks for this tracking. Accessing them from the dashboard is time-consuming

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
