### ISSUE TITLE
Suggestions =)

### ISSUE THREAD

**Issue by henriqueweiand** [kanboard/kanboard#1886]
I am impressed by the wealth that this code and documentation for this! Congratulations guys!
There goes some details for future implementations:
- Possibility to add more fields in the tables and the script will automatically recognize these new fields to also retornalos, updates them ...
-  Method for all tasks of a User;
-  Possibility to pass the filter function parameters of getAllTasks for example, retonar a filtered results or even possible to use the custom filters these functions.
  These sujestões are based on API integration course.

Thanks

**Comment by fguillot** [comment]
Thanks for your suggestions.
