### ISSUE TITLE
Cannot change order of default swimlane

### ISSUE THREAD

**Issue by nerdoc** [kanboard/kanboard#1894]
### Expected behaviour

At the swimlanes config page, the default swimlane is not in the list of other swimlanes, so you can't change the order of the default swimlane

What I want is:
- a "Priority" swimlane
- a default swimlane

When I add the priority swimlane, it is below the default one in the dashboard. workarounds ATM are: hide the default swim lane, and create two different ones: "priority" and "default" - which is duplication of work: 2 default swimlanes. Or I rename the "default swimlane" to "priority" and create another one. Which seems to be weird too.
### Actual behaviour

You cant change the vertical view order of the default swimlane
### Steps to reproduce
1. add another swimlane
2. try to get it above the default one.
3. cry.
### Configuration
- Kanboard version: 1.0.25
- Database type and version: MYSQL 5.1
- PHP version: 5.6
- OS: Linux
- Browser: Firefox

**Comment by tvriend** [comment]
We named the default swim lane to "Expedite" and created a swim lane for the default.
You can rename the default swim lane at the same place where you create new ones, just don't forget to press "save" once your done.

I don't think this is a bug or anything, just standard behaviour which can be bypassed by using the "extra" swim lanes.

**Comment by nerdoc** [comment]
I thought about that too.
But if you do that **after** you already had created some tasks, all these tasks remain in the "Expedit" swimlane, including the already closed ones, which you can't move any more...
So I would have to re-open each one of them, move them into the new "normal" swimlane and close them again. Much work for >100 tasks ;-)

*That's* why I created the bug. Your workaround works well when setting up a new project with no tasks in it. But later it is not really viable.

**Comment by tvriend** [comment]
Ah, yeah.. in that case i didn't say anything :)
I found this during my playtime with kanboard so i created the work around before i added our tasks.

**Comment by fguillot** [comment]
The concept of default swimlane has been removed in Kanboard 1.0.40. Now you can change the order of the first swimlane created.
