### ISSUE TITLE
"Start Date" not visible while creating a "New Task" only later in "Edit a task" mode

### ISSUE THREAD

**Issue by dezsijanos** [kanboard/kanboard#1896]
### Expected behaviour

When creating a new task for the first time the "Start Date" field should be visible there.
### Actual behaviour

"Start Date" is not available. Only if I "Edit a task"
### Steps to reproduce
1. Navigate to a Board
2. Add a new task
3. "Start Date" is not visible
### Configuration

It's officially documented that it's not there.
http://kanboard.net/documentation/creating-tasks
But the Gant using it: http://kanboard.net/documentation/gantt-chart-tasks
And it can be entered only in "Edit a task" screen for the first time:
![start_date_edit_task](https://cloud.githubusercontent.com/assets/17477191/13324267/3377a910-dbdd-11e5-99c0-552c20a1d8ba.jpg)

**Comment by fguillot** [comment]
it is now.
