### ISSUE TITLE
Datepicker unable to move around months 

### ISSUE THREAD

**Issue by diegoseso** [kanboard/kanboard#1899]
### Expected behaviour
Be able to navigate between months while  selecting dates (any kind of date) and having ES translation enabled.

### Actual behaviour
When clicking on the next or previous datePicker button the datePicker disappear. 

### Steps to reproduce
1. Enable translation to ES (Spanish)
2. Add a new task with a date , where the date is from a previous month (use nav buttons)
3. voila!

### Configuration

- Kanboard version: 1.0.20
- Database type and version: mysql 5.5
- PHP version: 5.6
- OS: Linux red hat
- Browser: Chrome 48.0.xxx

### Thoughts

I think translation has a bigger string length that is not supported by the datePicker component

**Comment by fguillot** [comment]
You should upgrade your Kanboard version. This issue have been already fixed in the past.
