### ISSUE TITLE
Checking subtask from board doesn't update percentage

### ISSUE THREAD

**Issue by GDmac** [kanboard/kanboard#1905]
### Expected behaviour

When checking one of two subtasks of a task, from the popover on the project board,
then the task percentage should go to 50%
### Actual behaviour

The Task-percentage is not updated
### Steps to reproduce
1. Project Board,
2. Hover task subtask icon
3. click subtask checkbox (becomes active / cogs)
4. click subtask check box again, checked
5. task percentage is not updated (reloading the whole page will show task at 50%)
### Suggestion

When clicking the checkbox, 
?controller=board&action=check&project_id=1&timestamp=1456653315&_=1456653316097
should (ideally) return changes to process immediately, 
or (less ideally) set timestamp client/server so that the next update call will actually get the changes
?controller=app&action=status&_=1456653316098

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
