### ISSUE TITLE
Apache 2.3+ Kanboard does not run in subdirectory kanboard

### ISSUE THREAD

**Issue by GDmac** [kanboard/kanboard#1909]
### Expected behaviour
Moved my install to other computer (apache 2.4.x)
subdir ``example.dev/kanboard`` (make data dir writeable)
expect to continue working 

### Actual behaviour
``example.dev/kanboard``
Get error: Acces Denied
``[authz_core:error] [pid xxx] [client 127.0.0.1:57018] AH01630: client denied by server configuration: /Users/GDmac/Sites/kanboard``

### What i think that happens
Because of the htaccess rule on 
``<FilesMatch "(kanboard|config.php|config.default.php)">``
the program does not work on server subdir kanboard
The filesmatch rule is probably there to deny access to
the ``kanboard`` shell script, but it does also deny access to the subdir itself.

**Comment by fguillot** [comment]
I'm not able to reproduce this issue, I tried with:

- Ubuntu Precise (Apache 2.2)
- Centos 6.7 (Apache 2.2)
- Ubuntu Xenial (Apache 2.4)

**Comment by GDmac** [comment]
``http://local.dev/kanboard`` 403 Forbidden (issue)
``http://local.dev/kanboard/`` Redirect to login (OK)

**Comment by mrks11** [comment]
I had the same issue on CentOS centos-release-6-5.el6.centos.11.2.x86_64 with  Apache/2.2.15.

**Comment by fguillot** [comment]
Provide your Apache configuration because I'm not able to reproduce the issue with the default configuration of Centos 6.7, Ubuntu...

**Comment by GDmac** [comment]
if you remove "kanboard" from the filesmatch in htaccess, 
then apache does an internal redirect from ``kanboard`` to ``kanboard/``.
But with the filesmatch present on kanboard, the forbidden somehow kicks in before the redirect.

**Comment by starthal** [comment]
I had the same issue on Debian (8.6/jessie) with Apache 2.4.10. This was right after a fresh install. I commented out the entire `FilesMatch` to make it work. Once it worked and I logged in for the first time, I reverted the `.htaccess`. Now it works whether I request `kanboard` or `kanboard/`, and I can't reproduce the issue.
