### ISSUE TITLE
Remove Administrator Application Role From Having Access to Projects by Default

### ISSUE THREAD

**Issue by jg-jhu-ds** [kanboard/kanboard#1912]
### Expected behavior

Do not give administrators access to all projects by default.  Give administrators the ability to add their accounts to each project explicitly.  Administrators can continue to access any project they want by adding their account to the project explicitly.  Benefits include:
- The administrator does not have default access to the project, so they cannot accidentally make changes to projects.
- The administrator's user account is listed in the Allowed Users list, so project managers know who has access to view and edit a project.
### Actual behavior

Currently, users with the application administrator role can access any projects.  However, the project managers of those projects cannot see the administrators that have access to the projects because they do not show up in the Allowed Users list under Settings > Permissions.
### Steps to reproduce
1. Login as a user with the User application role and the Project Manager project role.
2. Select Actions > Settings > Permissions.
3. In the Allowed Users list, no administrators are listed, so there is no visibility what administrator users have access to the project.  In addition, administrators can make changes without the project manager knowing.
### Configuration
- Kanboard version: 1.0.25
- Database type and version: sqlite
- PHP version: 5.4.16
- OS: Red Hat Linux
- Browser: Chrome

**Comment by Ksuh2111** [comment]
I added users to my project, then I checked the box at the bottom that said "Allow Everybody" and a screen popped up saying that I was a forbidden user. Everyone else I added to the project has also been forbidden. None of us can access the settings to fix this--including the admin. I want the admin to have the ability to delete or edit a board, but they cannot.

**Comment by jg-jhu-ds** [comment]
@Ksuh2111 ,
Can any user in the application edit the board?  If not, maybe there is a permissions issue with the web server accessing the database file.  One time when we upgraded, we encountered something similar.  We had to restore it from a backup and reset permissions in the operating system to the application folder and database.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
