### ISSUE TITLE
Question:  How can I change the cards to display the task description in board view?

### ISSUE THREAD

**Issue by Allvols82** [kanboard/kanboard#1915]
### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by Chaosmeister** [comment]
at the moment the only way would be to hover the mouse over the description icon

![image](https://cloud.githubusercontent.com/assets/13346344/13565703/132c0e44-e452-11e5-813c-ec74122e22fd.png)

**Comment by SeAlgoAsoma** [comment]
Yes, I need this too. Not being able to see at least a line or two of the description under the title in Board or List views (without having to click or hover to see them one by one) is a big problem, it would be much more productive if I could have details at a glance.

**Comment by fguillot** [comment]
Modify manually the template?
