### ISSUE TITLE
mentioned @user should be notified per mail even when his notifications are turned off.

### ISSUE THREAD

**Issue by nerdoc** [kanboard/kanboard#1916]
using Kanboard v 1.0.25.
If in a thread a user is mentioned manually like this: @fguillot - he should be notified by email. Maybe there should be a separate config option "Notify me if I am mentioned in a thread"

I think it is ok that some users don't want to get a mail for each and every little change that anyone does, but mentioning is worth notifying!

**Comment by thob** [comment]
@mention works for me. user get's an email

**Comment by nerdoc** [comment]
Oh I forgot to say - he should be mentioned even if he does not want to be contacted.
I know this is not really nice - and should not be done in the current setting.

I just don't get along with the current notification settings (I'll write that in [another issue](#1985)).
And I'll update the title here to make it clearer.

**Comment by nerdoc** [comment]
What about something like this:
![bildschirmfoto vom 2016-03-09 22-32-46](https://cloud.githubusercontent.com/assets/2955584/13651258/dcdfa07a-e646-11e5-9dae-c86d486ffa0f.png)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
