### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by jaiume** [kanboard/kanboard#1917]
Kanboard is great - It organised my life for me. So simple, so effective.

Some feature requests /suggestions
1. IMAP email to task (different account per kanboard)
2. Sub-tasks as a sub-kanboard (as an option, sometimes its just better to have the list)
3. Federated tasks/boards - same task/boards on multiple Kanboards on different servers
4. Create new user without password with welcome email directing them to set password

Thanks
Jamie

**Comment by EstebanMonge** [comment]
Hello!
I made a little plugin to fetch mail from IMAP account, it's a first attempt.

You can configure the parameters in Settings
You need to run a cron script to get all working.

I tried to get all from web front end.

At the moment I only tested with gmail and IMAPS... never can get a select with yes no option =$

If you want test it and give feedback this is the URL: https://github.com/EstebanMonge/kanboard_imap_tasks

**Comment by jaiume** [comment]
Thanks, I'll check it out.

PHP =>7.0 may be an issue for me though

Thanks
Jamie


------ Original Message ------

**Comment by EstebanMonge** [comment]
Please check it and tell me you... I don't have different environment to test.

I need to make more documentation... and only works with sqlite.

**Comment by EstebanMonge** [comment]
Hello I updated the plugin to get the project ID from subject of mail, for example the subject can be:

<PROJECTID> Meter tres goles!

The plugin will remove <PROJECTID> and creates the task with the correct name

https://github.com/EstebanMonge/kanboard_imap_tasks

You can configure a special user that can act as Guest User, if you send a reply to response mail, the reply will be added as a comment, if the email is not registered the plugin will create a new comment as guest user within the email as comment.

**Comment by EstebanMonge** [comment]
Hello I tested with PHP 5.6 on Debian 8 and works fine!

**Comment by fguillot** [comment]
@jaiume Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
