### ISSUE TITLE
Can´t see the options for tasks that refers to: Duplicate, Duplicate to another project, Move to another project and Delete

### ISSUE THREAD

**Issue by urribarrijn** [kanboard/kanboard#1919]
### Expected behaviour

I should see the options: Duplicate, Duplicate to another project, Move to another project and Delete in the task view
### Actual behaviour

I can´t see the options: Duplicate, Duplicate to another project, Move to another project and Delete in the task view, I can't execute non of the options already mentioned.
### Steps to reproduce

1.
2.
3.
### Configuration
- Kanboard version: v1.0.26
- Database type and version: sqlite
- PHP version: 
- OS: Debian
- Browser: Mozilla Firefox

**Comment by fguillot** [comment]
![task-menu](https://cloud.githubusercontent.com/assets/323546/13483364/a55e6922-e0c1-11e5-865d-6002dbc9a069.png)
