### ISSUE TITLE
Task distribution graph by categories (feature request)

### ISSUE THREAD

**Issue by bpetit** [kanboard/kanboard#1920]
Hi,

Is this in the roadmap to include task distribution graphic, by categories ? I mean like the one existing for task distribution by column ?

If not, I suggest the idea :)

Thank you for this great application and for your time

**Comment by tvriend** [comment]
+1
I would like this one as well to see average lead-time per category

**Comment by CoMPaTech** [comment]
First attempt at writing non-plugin contributions, but it reproduces the task distribution view for categories.

**Comment by CoMPaTech** [comment]
Re-applied to local branch ... off-topic but first commit included the generated js files, sorry

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
