### ISSUE TITLE
[FR] user should be able to export their task data

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#1931]
### Expected behaviour

any user should be able to export his data via csv _(maybe as an optional setting)_
use case: we do payments based on time spent and everyone should be on the same page.

**Comment by thob** [comment]
Any chance to get there without making everyone a project manager

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
