### ISSUE TITLE
Swimlane height causes lots of blank space

### ISSUE THREAD

**Issue by Cybergern** [kanboard/kanboard#1932]
### Expected behaviour

I expect swimlanes to only be as high as is necessary to display the tasks they have in them. This was the previous behaviour in version 1.0.11, which is the one we are currently using.

### Actual behaviour

Each swimlane height is as that of the highest swimlane or 500 px if the maximum column height is enabled. Because of this, we can now only fit 1-2 swimlanes (1 with maximum column height off, 2 with it on) where we could previously have 4-5.

### Steps to reproduce

1. Create a swimlane with 1 short description task in it.
2. Create another swimlane with 10 tasks or so in it.
3. The 1 task swimlane will have an equal height to that of the 10 task swimlane.

### Configuration

- Kanboard version:1.0.26 (stable)
- Database type and version: SQLite
- PHP version: 5.6.7
- OS: Windows 7 Enterprise
- Browser: Chrome

**Comment by fguillot** [comment]
From the actions menu, you can disable the "max height" to avoid blank space.

**Comment by Cybergern** [comment]
Yes, I am aware of this and as you can see in my description of the problem, my troubles are not with the max height but the min height. The min height will never go below 500px and never below the height of the highest swimlane, as far as I can tell.

**Comment by Chaosmeister** [comment]
:+1: I have a colleague who also complains about this.  
especially with "collapsed tasks".

**Comment by Cybergern** [comment]
Yes, I was hoping that it would get better with Collapsed tasks, but if anything, it makes the problem more obvious.

**Comment by Cybergern** [comment]
I think I've managed to solve this, actually, but I'm a little skeptical. I made my changes in assets/js/src/BoardColumnScrolling.js and removed the two lines that are setting min-height on taskList css and that was it. However, there's a comment that talks about a dropdown menu, but the only dropdown menu I can see is the one for the column that only has one item in it that easily fits. Maybe this is something old?

"$(this).css("min-height", 320); // Height of the dropdown menu"

**Comment by mkauzlar** [comment]
Having 3 or more swimlanes makes the page too long because of this issue. 
I vote for this to be fixed.

**Comment by Cybergern** [comment]
I was going to make a pull request for this, but unfortunately the harddrive in my laptop broke and I lost the virtual machine I had on there with my code changes. Luckily, they're not too complicated. I just removed the two settings of "min-height" on tasklist in assets/js/src/BoardColumnScrolling.js.

**Comment by Cybergern** [comment]
I created a pull request for this:

https://github.com/fguillot/kanboard/pull/2147

**Comment by Cybergern** [comment]
@fguillot Could you possibly take my pull request and run the yuicompressor on it to compile the app.js file and run the tests? I had a full virtual machine with all the changes, yuicompressed and everything but lost it in a harddrive crash before I could create the pull request, so then I only had the changes to BoardColumnScrolling.js, but not the compressed app.js-file.

**Comment by fguillot** [comment]
In the development version, individual column scrolling have been removed and the swimlane height is now the height necessary to display tasks.
