### ISSUE TITLE
Autocollapse swimlanes with 0 tasks

### ISSUE THREAD

**Issue by patrickvanelk** [kanboard/kanboard#1934]
It would be convenient if a swimlane with 0 tasks in it would automatically collapse.

**Comment by sandromario** [comment]
I was surprised this wasn't standard behaviour, yes.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
