### ISSUE TITLE
User's global Gantt Chart

### ISSUE THREAD

**Issue by Danoposada** [kanboard/kanboard#1935]
Great application. Really, a huge congrats to you guys because you've done an amazing job.

We're just missing one very useful feature that we either didn't seem to figure out, or it's not in the application at the moment:

We would like a gantt view where we can see (and move) ALL of a user's tasks, regardless of the project they come from. 

Right now we can (through "Users overview") view a users gantt chart by project, which is great to review schedule conflicts in one specific project. But we don't currently have a way to know if a particular user has any kind of schedule conflicts between projects.

This would make resources management exponentially easier for us: at the moment, the fastest way to review  and -more importantly- FIX schedule conflicts a user might have between projects, is by manually reviewing every single gantt chart per project the user has, compare schedules (again, manually), and fix the schedules in each project, one by one.

So, that was longer than I intended :disappointed_relieved: 
Anyway, thanks for the attention :smile: 
### Expected behaviour

A Gantt view that shows all of a users tasks at the same time, regardless of the project they come from.
### Actual behaviour

Gantt views that show a users tasks only per project, never globally.
### Steps to reproduce

None

**Comment by asmwarrior** [comment]
I also need such feature, thanks.

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
