### ISSUE TITLE
Import bulk subtasks from CSV

### ISSUE THREAD

**Issue by darkocobe** [kanboard/kanboard#1939]
### Expected behaviour

I want to be able to import sub-tasks from csv file for certain task. We often use lists of subtask for a certain task and it gives a pain to add one by one.
### Actual behaviour

At this moment you can only import bulk tasks not sub-tasks

**Comment by thob** [comment]
:+1:

**Comment by fguillot** [comment]
In version 1.0.48, you can create bulk subtasks.
