### ISSUE TITLE
Time tracking overwrites time spent information as entered

### ISSUE THREAD

**Issue by GDmac** [kanboard/kanboard#1947]
## Expected

I have entered values (2 hours each) into subtasks for time spent.
Expected to see those in the totals of time tracking
## Actual Behaviour
- The entered time spent for subtasks is calculated and changes the task time spent, overwriting any value entered in the task time spent itself
- Time spent that is entered in a subtask is not shown in the time tracking.
- You can only see entered values for time spent on task-summary, above subtask start timer button.

![kanboard-task-time](https://cloud.githubusercontent.com/assets/156334/13538779/bf756770-e24c-11e5-8c71-e57ba19a9f92.jpg)
## Suggestion
- On the board-view, there is no hint as to the time spent on a task (nor actual total of subtasks)
- In the list-view add a column of time-spent/estimate
- if the system overwrites task-time-spent from subtask time-spent, then it should not be editable

**Comment by neiaberau** [comment]
this still seems to be the case, 
after .64 hours, I entered .2 hours for time spent; then another .9 hours were recorded, 
the details still lists .64 and .09, but not the manally entered .2, 
the summary ignores all entries before the edit time and shows .29, there is no indicator of the .64 not beeing used in the summary or warning while entering .2
![screenshot 2018-02-24 10 14 14](https://user-images.githubusercontent.com/6450711/36628007-b56b4b40-194b-11e8-8cdb-00c692cbbce0.png)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
