### ISSUE TITLE
Forgot Password behaviour

### ISSUE THREAD

**Issue by tencrocs** [kanboard/kanboard#1951]
### Expected behaviour

Forgot Password module should notify users that a mail has been sent to their email address before going back to login screen.
### Actual behaviour

Forgot Password doesn't notify the user what to do after clicking "Change Password" button instead it goes back to login screen.
### Steps to reproduce
1. Before actually logging in, click the Forgot Password
2. Supply required information
3. Hit the "Change Password" button.
### Configuration
- Kanboard version: 1.0.26
- Database type and version: sqlite
- PHP version: PHP 5.4.45
- OS: Debian 7
- Browser: Gogle Chrome

**Comment by fguillot** [comment]
In Kanboard 1.0.39, there is now a message to inform the user.
