### ISSUE TITLE
Date range in reports

### ISSUE THREAD

**Issue by PatrickHonorez** [kanboard/kanboard#1975]
### Expected behaviour

When running Board Analytics reports, when user changes the date range and executes a report, then switches to another report, it would be nice to keep the same date range.
### Actual behaviour

In current version 1.0.26, one has to re-enter the dates for every report
### Steps to reproduce
1. go to analytics, Cumulative flow diagram. 
2. change the start date to a date 1 month ago, then run the report
3. switch to burndown chart: you need to re-enter the starting date
### Configuration
- Kanboard version: 1.0.26

**Comment by Busfreak** [comment]
:+1:

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
