### ISSUE TITLE
New Bug : General error: 1 ambiguous column name: name

### ISSUE THREAD

**Issue by matteosanguin** [kanboard/kanboard#1976]
### Expected behaviour

Show the list of projects

### Actual behaviour

the same as for bug #1910 

Internal Error: SQL error: SQLSTATE[HY000]: General error: 1 ambiguous column name: name

SELECT projects.*, users.username AS owner_username, users.name AS owner_name FROM "projects" LEFT JOIN "users" ON "users"."id"="projects"."owner_id"  WHERE projects.id IN (?, ?)   ORDER BY "name" ASC  LIMIT 20  OFFSET 0
[2016-03-08 15:56:06] [debug] SQLSTATE[HY000]: General error: 1 ambiguous column name: name

### Steps to reproduce

?controller=project&action=index

### Configuration

- Kanboard version: development latest
- Database type and version:sqlite 3.3.7
- PHP version: 5.4.45
- OS: centos 5.1
- Browser:  #any

**Comment by fguillot** [comment]
Do you still having the issue with the last master?

**Comment by matteosanguin** [comment]
Just updated to the last master ... Same error.
Il 28 apr 2016 02:26, "Frédéric Guillot" <notifications@github.com> ha
scritto:

**Comment by fguillot** [comment]
How did you install PHP 5.4 on a Centos 5.1? Did you use alternative RPM packages instead of the official ones? This operating system is so old that I can't even reproduce the problem.
