### ISSUE TITLE
Simple example of adding command line function

### ISSUE THREAD

**Issue by kgraven** [kanboard/kanboard#1977]
Would like to add a custom import function that is able to be run from the command line.  Is there a example that works with the latest version of Kanboard?

Let me add to this that optimally this should be extensible from a plugin.

Thanks
--Ken

**Comment by fguillot** [comment]
At the moment, there is nothing to add a new command line command from plugins.

**Comment by fguillot** [comment]
There is an example here to add new commands: https://kanboard.net/documentation/plugin-registration
