### ISSUE TITLE
Child task color change reflected in parent.

### ISSUE THREAD

**Issue by entwisi** [kanboard/kanboard#1980]
Feature request/Question

Is it possible to make any color changes e.g. RAG status reflect to parent tasks? i.e. parent with 4 sub tasks, parent task take high watermark from all child tasks ( Red if any are red, Amber if any are amber and no reds exist, green if all child tasks are green ). I'm guessing it would be via automated tasks but can't see one that will allow this. 

Thanks

Ian

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
