### ISSUE TITLE
Task Time Recording being overwritten when adding first subtask

### ISSUE THREAD

**Issue by bonbonGuy** [kanboard/kanboard#1981]
### Expected behaviour

-entered in time on a task ('estimated and spent') 
-add subtask
-add time to subtask
-sum current task time with additional subtask time.
### Actual behaviour

-entered in time on a task('estimated and spent')
-add subtask
-time on primary task is overwritten and set to the new subtask
### Steps to reproduce
1. create a new task
2. edit the task and add time to both estimated and spent values
3. add subtask
### Configuration
- Kanboard version: 1.0.26
- Database type and version: sqlite
- PHP version: 5.6.4
- OS: Windows 7
- Browser: Chrome Version 46.0.2490.71 m

**Comment by GDmac** [comment]
Similar to #1947

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
