### ISSUE TITLE
Report - Daily/Weekly  Project Details

### ISSUE THREAD

**Issue by anandvshah** [kanboard/kanboard#1982]
### Expected behaviour

Please provide a feature to download the detailed project report for Daily and Weekly basis
### Actual behaviour

Currently the report shows summary of tasks based on count. There is not feature for generating detailed project report
### Steps to reproduce
1. Navigate to a Project 
2. From Action menu select "Export"
### Configuration
- Kanboard version:1.0.26
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
