### ISSUE TITLE
Feature request: remove double email when user is mentioned

### ISSUE THREAD

**Issue by nerdoc** [kanboard/kanboard#1984]
When using @mentioning, people get an email if mentioned in a comment e.g.. If a user has enabled the setting that he gets notified for a comment as well, he gets a second email with nearly the same content.

To prevent spam, it would be cool to merge these two mails into one: _If @mentioned in a comment AND user would get an email anyway, drop that second email._
### Configuration
- Kanboard version: 1.0.26
- Database type and version: mysql
- PHP version: 5.6
- OS: Linux
- Browser: Firefox

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
