### ISSUE TITLE
[Feature Request] Comment window close confirmation

### ISSUE THREAD

**Issue by orlov0562** [kanboard/kanboard#1998]
Hi there,

I suggest to add some type of confirmation in case when you change some fields in new comment/task and click on shadowed area around window that leads to window close and loss of data entered.

For example, I just write a big comment and  accidentally clicked the mouse button that close my comment window, so I should write comment again
### Steps to reproduce
1. Open any task
2. Click Action > Add a comment
3. Type few words into text area
4. Click to shadowed area outside window 
### Actual behaviour

On click to shadowed area outside window:
1. Window closes
2. Entered data lost
### Expected behaviour

On click to shadowed area outside window:
1. Confirmation that suggest to save entered data if it modified
### Configuration
- Kanboard version: v1.0.25-134-ga3994b1
- Database type and version: sqlite
- PHP version: PHP 5.5.9-1ubuntu4.14 
- OS: Ubuntu 14.04.3 LTS
- Browser: Chromium 48.0.2564.116 Ubuntu 15.10 (64-bit)

**Comment by mtszsobczak** [comment]
I think that confirmation or form input save (like in trello) would be great.
I lost data multiple time, because of a need to open other task (I've been jumping a lot between tasks in trello in order to gather all needed data) or accidental click in grey area.

**Comment by lcmsrl** [comment]
This would be great: this missing feature cause time-wasting.
Thanks in advance

**Comment by fguillot** [comment]
This issue is fixed in more recent version of KB.
