### ISSUE TITLE
Setting for favicon (feature request)

### ISSUE THREAD

**Issue by 85pando** [kanboard/kanboard#2000]
### Expected behaviour

Option in settings to easily change the favicon to something custom.

This would be usefull for quickly being able to customize kanboard without having to create own css stylesheets.

Tried the following:
- Change `<kanboard>/favicon.ico` to another `ico`.
- Change `<kanboard>/asset/img/faivcon.png` to another `png`.
### Actual behaviour

No setting found in documentation.
### Steps to reproduce
1. Install Kanboard
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.20
- Database type and version: mysql
- PHP version: 5.5.10
- OS: Red Hat
- Browser: Firefox, Chrome

**Comment by NinjaPewPew** [comment]
Check out [this](https://github.com/phsteffen/kanboard-themeplus) KB plugin form @phsteffen. It allows you to replace the favicon with your own (amongst other things).

**Comment by fguillot** [comment]
If you still need this feature, the best way is to contribute to the project or to develop a plugin.
