### ISSUE TITLE
misleading error message 'Access Forbidden' if a task is moved to another board

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#2014]
### Expected behaviour

If I still have the permissions to access the issue I should be redirected, The task# didn't change after all, just the board
### Actual behaviour

your're left alone with 'Access Forbidden` 
### Steps to reproduce
1. Create an issue
2. Move it to another board (where you have permissions to access it)
3. You'll get `'Access Forbidden` 
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.26
- Database type and version: Mysql
- PHP version: 5.6
- OS: Debian
- Browser: Chrome

**Comment by fguillot** [comment]
Do you still having the issue with 1.0.27?

**Comment by thob** [comment]
yes, it's still there. Just tested it.
![image](https://cloud.githubusercontent.com/assets/755337/14878684/5d801fca-0d25-11e6-9770-108bfc485c0e.png)

**Comment by fguillot** [comment]
If you still have the issue, try with Kanboard 1.0.38. I was never able to reproduce the problem with the information provided. If the problem still there, reopen this ticket with absolutely all the relevant information to reproduce the problem.

Thank you
