### ISSUE TITLE
User management in public/private projects

### ISSUE THREAD

**Issue by iPublicis** [kanboard/kanboard#2016]
### Expected behaviour

Expected to add users to both private and public projects.
Can't understand why this is not the normal procedure.
### Actual behaviour

We can add users to private projects if we turn them public, add the users, turn them private again
### Steps to reproduce
1. Activate Public access
2. Add users
3. Deactivate Public access
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.26
- Database type and version: MySQL 5.6.28
- PHP version: 5.5.32
- OS: Linux 3.2.61 x64 SMP
- Browser: Firefox 45

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
