### ISSUE TITLE
Debian package for kanboard ?

### ISSUE THREAD

**Issue by fabrice-regnier** [kanboard/kanboard#2017]
Hi,

First, thank you so much for this piece of software that i've been used for 2 years ;)
I wonder: is there any debian package for it ? i guess no.

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790814
No news since ?

regards,

fabrice.

**Comment by waja** [comment]
> See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790814
> No news since ?

You should have asked in the Debian Bug.

**Comment by oliviermaridat** [comment]
A Debian package would be very nice.
I don't know the status of this Debian bug report, but if at least someone knows and can explain:
- how to create a Debian package for a Web project
- how to push it to the Debian repositories

it could be really helpful!

**Comment by Danoposada** [comment]
Second that :+1: 

Kanboard is not really that hard to install, but a Debian package would make things easier.

**Comment by oliviermaridat** [comment]
The main advantage, IMHO, is to automate updates.

**Comment by olberger** [comment]
@waja @fabrice-regnier ditto: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790814#10 

Let's see if he responds.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
