### ISSUE TITLE
Too many font sizes

### ISSUE THREAD

**Issue by mcorteel** [kanboard/kanboard#2024]
Hello!

Browsing through the CSS, I felt like everything had its own `font-size`, so I dug a little deeper to find out that it was nearly true. I found all these rules:
```
font-size: 2.5em;
font-size: 1.8em;
font-size: 1.5em;
font-size: 1.4em;
font-size: 1.3em;
font-size: 1.2em;
font-size: 1.1em;
font-size: 1.0em;
font-size: 0.95em;
font-size: 0.9em;
font-size: 0.85em;
font-size: 0.8em;
font-size: 0.75em;
font-size: 0.7em;
font-size: 0.6em;
font-size: 0.5em;
font-size: 150%;
font-size: 100%;
font-size: 80%;
```
I think that this is detrimental to the homogeneity of the application. I think that 5 font sizes would be OK, namely:
- App title `1.5em`
- Main title `1.6em`
- Section title `1.2em`
- Normal font `1em`
- Smaller font `0.8em`

EDIT: this does not count the font size for smaller screens (which only changes the main `font-size`).

What do you think?

**Comment by fguillot** [comment]
Agreed, what about using a css class for each font-size?

**Comment by mcorteel** [comment]
Well, there are HTML tags that will cover most of the use cases (`h1`, `h2`, `h3` and `small`). For other cases (like tables or the project overview where the numbers on top are displayed with a bigger font), we should have the rule directly in the CSS.
The problem is not to have to many `font-size` rules, but to have to many `font-size` values IMHO.

**Comment by fguillot** [comment]
In dev, the number of font-size values have been reduced to 6 and that can be changed easily since I converted all vanilla CSS to SASS.
