### ISSUE TITLE
[FR] Rename Screenshots

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#2027]
I would like to be able to rename my screenshots.

The upload-information are useful but a manual description would be even better.

![image](https://cloud.githubusercontent.com/assets/13346344/13885702/f8a4ba22-ed33-11e5-9c2c-f51381dd6810.png)

**Comment by facciocose** [comment]
+1

**Comment by WolfgangAndreas** [comment]
+1

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
