### ISSUE TITLE
Additional notiifcation functionality - send myself notifications

### ISSUE THREAD

**Issue by jgirouard** [kanboard/kanboard#2028]
Would it be possible to add functionality to the user notification settings to send myself notifications if I perform an action that would cause notifications to be sent out?

For example, let's say I have the following notification settings:
     Enable notifications:  Yes
     Notification methods:  Email
     I want to receive notifications for:  All tasks

Currently, if I make a change to a task, everyone with similar settings would receive an email, except for me.  I'd like a setting, such that if it is selected, I could receive notifications based on my actions.

This would allow me to save all emails for any actions within a project in one folder and allow for better traceability of actions taken within that project, whereas currently, I wouldn't have visibility to what I've done by looking at my emails.

Thanks!

**Comment by fguillot** [comment]
If you really need this feature, the best is to contribute to the project by sending a pull-request.
