### ISSUE TITLE
Discussion board/blog

### ISSUE THREAD

**Issue by paddymac841** [kanboard/kanboard#2035]
### Expected behaviour

Some sort of issue discussion form that lets all members of a project discuss a particular topic or just the whole projects progress. Would be a helpful/convenient add-on. A plugin for this would be great
### Actual behaviour

Have to just use comments on tasks.
### Configuration
- Kanboard version: Version 1.0.26
- Database type and version: Mysql 
- PHP version:
- OS: OSX
- Browser: Chrome

**Comment by Busfreak** [comment]
Have a look at the existing plugins:
https://github.com/kanboard/

Maybe there is something for you?
- Hipchat
- Slack
- Mattermost
- Rocketchat

**Comment by paddymac841** [comment]
Thanks for the response Busfreak. 
I searched through all the available plugins already (Some i found useful and straight forward to implement). Although there is not a massive selection.. I was thinking more of a forum based on Kanboard rather than using web hooks and a different system? or maybe that is a common solution?

**Comment by rvalente** [comment]
In my *humble* opinion, I would prefer that Kanboard remain very tight in its core. Stay away from scope creep and continue to provide a rock solid platform. Focus the efforts on improving UI/UX (which is already very good). Again, this is my humble opinion, but leveraging plugins to add features seems like a much better way to go to ensure a more rapid release timeline and easier to test code.

**Comment by paddymac841** [comment]
I agree on what you are saying rvalente. Have you tried developing your own plugins? Why are there so few plugins out there? Its a great system, which needs way more recognition.

**Comment by fguillot** [comment]
If anyone need this feature and would like to develop a plugin, do not hesitate to contribute. There are already too many feature requests and I prefer to keep the software simple.
