### ISSUE TITLE
Custom category of attached files

### ISSUE THREAD

**Issue by Folcky** [kanboard/kanboard#2039]
# FEATURE REQUEST

**### Expected behaviour**
We just need to define a custom category of attached files.

**Tell us what should happen**
After attaching file, user can change category file. For example, listbox with categories.

**### Actual behaviour**
There are no categories.

**### Configuration**
Configuration could be as an option inside board settings.

Thanks!

**Comment by fguillot** [comment]
Unfortunately, the number of features is voluntary limited to keep the software simple. There are already categories and tags for tasks and that cover most needs.
