### ISSUE TITLE
Moving tasks to another board - correct behaviour

### ISSUE THREAD

**Issue by Busfreak** [kanboard/kanboard#2041]
I've been using the function 'moving tasks to another board' and found some issues.
I want to discuss the correct behaviour of Kanboard.
### Actual behaviour
- Moving a closed task to an other board will reopen it
- Nothing will be documented in the activity stream, not the movement, not the reopening
- No notification is send
### Expected behaviour

To be discussed.
I think:
- tasks shouldn't be reopened, or in the moving dialog it has to be selected (reopen/keep closed)
- all activities have to be documented in the activity stream
- notifications should be send for all actions

What do you think?

**Comment by fguillot** [comment]
1) the task status is easy to fix
2) no event is fired at the moment, that need to be implemented
3) not sure about the notifications

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
