### ISSUE TITLE
Automatic action - moving column -> moving to another project - select swimlane

### ISSUE THREAD

**Issue by Busfreak** [kanboard/kanboard#2042]
### Expected behaviour

When creating the automatic action 'Move a task to another project' with the event 'Move a task to another column' there should be a selection of swimlanes, if multiple exist in destination project.
### Actual behaviour

Standard swimlane is the target, no swimlane selection.

**Comment by Beefaloaf** [comment]
Would like to second this request.  Could we get multiple ways to automate the swimlanes, just as there are already for columns?

In my case, I'm only working with one project, but have multiple swim lanes that represent departments.  When a department finishes a task by moving it into the last column ("Done"), we would like to automate it to move to the next swim lane, first column ("Queue").

http://i.imgur.com/BaOPkCl.jpg

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
