### ISSUE TITLE
Popup window doesn't  emerge when type: "@" in comment field 

### ISSUE THREAD

**Issue by JohnBat26** [kanboard/kanboard#2045]
### Expected behaviour

When I type "@" in task comment, I wait to open popup windows with list of project members
### Actual behaviour

When I type "@" in task comment, nothing happens :(
### Steps to reproduce
1. Open comment field
2. Type: @
3. Nothing happens
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: master (last commit 2425fd85c04e7ad6e571da1848bb8d4b54499394)
- Database type and version: PostreSQL 9.5.1
- PHP version: 5.6.19
- OS: CentOS Linux 7.2, kernel: 3.10.0-327.el7.x86_64
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by fguillot** [comment]
Yes, I know. It's due to the new Markdown editor, the autocomplete have to be rewritten.

**Comment by thob** [comment]
Will we see it working in .27?

**Comment by fguillot** [comment]
Probably next time, I need to find a better way to display the autocomplete with the new Markdown editor.

The user mention still there, only the autocomplete is missing.

**Comment by thob** [comment]
is it possible to deactivate the markdown editor and get autocomplete back?

**Comment by thob** [comment]
this is getting really annyoing. Too may users don't remember usernames and some write @mention: – tht doesn't work, of course. Any chance we can get autocomplete of usernames back?

**Comment by thob** [comment]
any news here. I'm getting in trouble with my fellow users :-(

**Comment by fguillot** [comment]
Yes, I'm working on it, there still some development todo to make it compatible with Internet Explorer.

**Comment by fguillot** [comment]
This is now available in v1.0.35, open a new ticket if you see any issue.

Thank you
