### ISSUE TITLE
Importing tasks from .csv file.  All tasks show in the boards etc but not in the Gantt chart

### ISSUE THREAD

**Issue by stevejtmc** [kanboard/kanboard#2047]
### Expected behaviour

expect imported tasks to show in Gantt chart

imported from .csv
### Actual behaviour

Not visible in Gantt chart
### Steps to reproduce
1. create a .csv
2. import tasks
3. view Gantt chart - empty?
4. Tasks can be seen in all other views
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Official website: http://kanboard.net/
Application version: 1.0.26
Author: Frédéric Guillot (contributors)
License: MIT
Database
Database driver: sqlite
Database size: 144k
Download the database  (Gzip compressed Sqlite file)
Optimize the database  (VACUUM command)
- Kanboard version:
- Database type and version:
- PHP version: 
- OS: windows 10
- Browser: chrome

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
