### ISSUE TITLE
No task match coming up in Task field of 'Add a new link'

### ISSUE THREAD

**Issue by rrockwell22** [kanboard/kanboard#2059]
### Expected behaviour

Have created 2 tasks. Have created a third and want to link to show blockage. Have clicked on add an internal link. I started typing in the Task field and expect some sort of menu to show matches.

### Actual behaviour

No choices show up, even when I explicitly copy and paste task title to ensure correctness

### Steps to reproduce

1. (As above)
2.
3.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.27
- Database type and version: sqlite 3.7.17
- PHP version: 5.4.16
- OS: (centos) Linux 3.10.0-327.el7.x86_64
- Browser: chrome

**Comment by fguillot** [comment]
Do you still having the issue because it's working for me?
