### ISSUE TITLE
Option to disable (or change?) avatars

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#2062]
### Actual behaviour

I want to identify who a given task belongs to. However, we have two people in the organisation with the initials "SB". Because we use LDAP authentication, it uses the system default of SURNAME FIRSTNAME, so both default avatars appear as "BS", which isn't either of their names (and even it if were, it would be impossible to tell which one was which!)
### Expected behaviour

It'd be nice to be able to customise what someone's initials are, so for the two SBs, they can be labeled "SB1" and "SB2". Or just disable them, so that it just shows the name. I don't mind - either/or. But as it is, the tasks are very difficult to identigy
### Configuration

Kanboard v1.0.27

**Comment by mcorteel** [comment]
I agree, #2066 fixes that by generating a color based on full name instead of initials. This way, people with the same initials still get a different background color.

**Comment by fguillot** [comment]
In the meantime, you can always upload a different image.

**Comment by AlgyTaylor** [comment]
Not sure it does fix it.

First, the initials are still the wrong way round ("BS" rather than "SB"), and my name on there is "TT" rather than "AT" (because I use my middle name rather than my first name). I know it sounds a minor point, but there will be other cases where people have prefered names ("Bob" rather than "Robert"), or like their initials in different orders (in some countries it's firstname-surname, in others surname-firstname).

The second problem is this. Take our theoretical company. It has 15 people with the initials 'MB' (Martha Blake, Martin Butler, Midred Baker, Matt Bullingdon, etc). First, there's a reasonable good chance that some people will **still** have the same colour background. Second, there will always be questions like "is Martha Blake blue or teal?", "Who's yellow?". Unless the person is that specific colour, or always wears that colour clothes (both unlikely), then the colour has no _actual_ link with the person, so it's very hard to tell who is who.

**Comment by mcorteel** [comment]
But like @fguillot said, if you find yourself in this situation, you'd probably be better off using actual avatar pictures. Color+initals is just a fallback for users that don't have an avatar.
But I agree that the option to disable avatars entirely could make sense.

**Comment by iaanus** [comment]
> First, the initials are still the wrong way round ("BS" rather than "SB")
I also hate the AD/LDAP default setting of having SURNAME FIRSTNAME. To overcome this, I made a minor tweak in function createLdapUser() that swaps SURNAME and FIRSTNAME. As such, it works for new users only, but it's easy to write an RPC API script to made the fix for existing users.

**Comment by fguillot** [comment]
Unfortunately, I don't want to add one billion of configuration options and I will never be able to satisfy everyone.

You still have the name of the person next to the avatar and the possibility to use custom images. If you don't agree with this behavior, you still have the possibility to create a plugin and do your own stuff.
