### ISSUE TITLE
Overlapping menubars

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#2071]
### Expected behaviour

In small width layouts the menubars should still be readable

### Actual behaviour

![image](https://cloud.githubusercontent.com/assets/13346344/14139879/1e26cd76-f676-11e5-849d-e92d16d7202b.png)

### Configuration

Application version: 1.0.27
PHP version: 5.3.28
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.2
Database driver: sqlite
Database version: 3.7.7.1
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by Chaosmeister** [comment]
I just tried a few things:

With a browser-width above 1031px everything looks fine.
Between 1025px and 1031px the div class "filter-box" overlaps with the ul class"views".
At 1024px the fontsize is reduced to 0.85em, which temporarily solves the overlapping until the width is below 972px. Then the overlapping starts again.

a "margin-bottom: 10px" in every element looks great on most widths.

below a width of 418px the ul class"views" starts wrapping itself. I'm unable to fix this through the css styles.
![image](https://cloud.githubusercontent.com/assets/13346344/17547751/11b0b918-5ee9-11e6-9719-def5f5b22ec3.png)

This does not happen with the filter box although the left Item of the wrapped filter-box is missing it's left border.

updated kanboardversion:

Application version: 1.0.32
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by fguillot** [comment]
I currently working on making Kanboard more responsive. It's in progress..
