### ISSUE TITLE
Quick edit in the list view

### ISSUE THREAD

**Issue by gene-pavlovsky** [kanboard/kanboard#2072]
It would be nice to have a feature to easily edit task names / descriptions in place when viewing them in list view.
E.g. double-click on task description, the field becomes an edit field, change the description, press enter, the description is saved. Or something like editing a table in Excel.

**Comment by oliviermaridat** [comment]
Did you see that a drop-down list appears if you click on the task id? It lets you quickly edit task fields.

**Comment by gene-pavlovsky** [comment]
Define *quickly*. Imagine I made 10 tasks, all titled "UI - ui task description". I talked to a coworker and we agreed "UI: ui task description" would be a better format. So I need to quickly edit 10 titles. Click on the task ids, then "edit task", then the title field, make the edit, click somewhere else to dismiss the pop-up. That's just too many clicks...

**Comment by Biniou180** [comment]
Some users of framaboard.org are also interested by this :-)
I would add also a special mention to the due date : it would be very convenient to modify it in place instead of opening each time the menu.
Also, why not think of adding this feature in cards in the board view too? (maybe would be useful for a lot of users?)

**Comment by khampf** [comment]
I would like two functions. To quick-edit (as in click ID, select edit) when clicking on the title and if possible either quick-edit date right away or open the quick-edit with date already open (as in click ID, select edit, click date).

**Comment by ramesh1024** [comment]
can any one please let me know how to add colums in listview of board

**Comment by krustymars** [comment]
Much asked feature in my team @fguillot ;) 
To bad non of us knows node.js, otherwise I would ask them to implement it or do it myself

**Comment by krustymars** [comment]
Pushed and pull request #3344

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
