### ISSUE TITLE
Feature request: mass changes of tasks

### ISSUE THREAD

**Issue by jniggemann** [kanboard/kanboard#2079]
Imagine you want to quickly set a category for multiple tasks.
I imagine this feature like this:
In list view, each task has a checkbox. I can select multiple tasks and then do an operation on all tasks at once, ex. set a category or add a comment.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
