### ISSUE TITLE
view cross-projects task list by priority

### ISSUE THREAD

**Issue by MarcoArdito** [kanboard/kanboard#2081]
I'm testing 1.0.27.

Is there any way to list tasks ordered by priority?

I need to assign tasks to users, and allow them to work on higher priorities first.
And I would also like to see (as manager or admin) the above list for other users too, in order to see what they should be working on, ant track work progress. Ideally, this should work either on a single project, or on multiple (all) projects.

I hope this is clear and, if there's no way, I would like to ask for a similar feature, if possible.

Thanks
Marco

**Comment by fguillot** [comment]
At the moment, this feature doesn't exists.

**Comment by abouquet** [comment]
+1 !

Not necessary cross project, but it should be good if it can be done inside a project :)
I'm using the "Tasks list" feature.

**Comment by fguillot** [comment]
You could perform a search from the dashboard and then sort the tasks by priority.
