### ISSUE TITLE
Feature Request: Set Project Status to 'Closed'

### ISSUE THREAD

**Issue by CaptainPackers** [kanboard/kanboard#2084]
I would like to be able to change a project status to 'Closed' instead of just 'Inactive' or removing it completely. Can this be added to a future release?

**Comment by fguillot** [comment]
You can already remove a project (project settings > remove) ?

**Comment by orware** [comment]
I can see his point regarding the Closed status (it gives a different meaning than Inactive in my mind...Inactive sounds more like the project died, whereas Closed indicates more that it was completed and done with).

**Comment by eskaryo** [comment]
This would be a great change. Having only Active and Inactive statuses is a little too two-dimensional for how this tool can be used. Statuses such as Closed, Template, On Hold, Cancelled could all be very useful. If user-creatable statuses were in play, that would only further improve the contextual value of a status assignment. I'm bringing this up for a team of 5 to help us focus and we've just today completed our first project tracked through the tool. We were sad when we realized our only option was to 'Disable' the project which sets it to inactive. We want a history of success and contextual value to the status assigned to the project.

**Comment by OschauLars** [comment]
We have the same issue.
Following the current principles, we close tasks once they are done. We do not delete them. This gives us the chance to review projects and tasks later.

The projects remain in the overview. They should closed and archived as well.

We set project to "inactive" in case we do not work on them. E.g. we set up upcoming projects to allow all co-workers to see what is coming down the road. In these case we might even have no tasks created in the projects. It is just a reminder.

So I think it would be helpful to sent accomplished projects to the archive be "closing" them.

**Comment by fguillot** [comment]
In Kanboard 1.0.39, the status has been changed to "closed" instead of "inactive".
