### ISSUE TITLE
Design-Improvements

### ISSUE THREAD

**Issue by phsteffen** [kanboard/kanboard#2087]
Hi folks,

I made some Design-Improvements and build an Theme-Plugin.
Perhaps there are some Changes you like and want to adopt.

https://github.com/phsteffen/kanboard-themeplus

These are the changes:
- Harmonize the font-size
- Remove round edges
- Harmonize font-family in jquery-ui
- Remove some gradients
- Add some more contrasts in some backgrounds
- Improve some margins and paddings
- Add an grey Background to the Header-Menu-Bar
- Add some grey Backgrounds to Page- and Projektheaders for better structure
- Add an Border-Bottom in Activity-Lists for better structure
- Add easily your own css-file
- Add easily a logo at login-page
- Replace the KB-Logo with your own logo
- Replace the KB-favicon with your own favicon
- Add some printer-friendly-css-improvements

Here some "before, afterwards"-Screenshots:

![board](https://cloud.githubusercontent.com/assets/18245229/14232984/919a6b26-f9bb-11e5-8b0e-191a5d0a79b7.png)
![dashboard](https://cloud.githubusercontent.com/assets/18245229/14232980/9196a586-f9bb-11e5-8070-2558b45cabf8.png)
![newtask](https://cloud.githubusercontent.com/assets/18245229/14232981/91974e00-f9bb-11e5-921b-0c62cc6c201a.png)
![overview](https://cloud.githubusercontent.com/assets/18245229/14232982/919814fc-f9bb-11e5-981d-8ee2f9114952.png)
![task](https://cloud.githubusercontent.com/assets/18245229/14232983/91991c1c-f9bb-11e5-8d22-f3f80daddf89.png)

**Comment by phsc** [comment]
I really like the improvements. They make Kanboard look more consistent and attractive.

Just one Detail:
In the first screenshot, there is to much whitespace between the kanban cards. This whitespace should be reduced, because it wastes space on the board, if you have a lot of cards.

**Comment by xavividal** [comment]
+1

**Comment by NinjaPewPew** [comment]
We are going to use that for sure. Great work.

**Comment by mcorteel** [comment]
@phsteffen this is a very good idea. I wanted to do a theme plugin but I didn't know where to begin...
Would you be open to the idea of a choice between different themes in the configuration?
I can try to implement that if you want!

**Comment by benoitjupille** [comment]
+1 It would be very interesting 😊

**Comment by phsteffen** [comment]
@mcorteel new ideas are great. ;-)

The same idea I have a couple days ago and I just upload a first version of a new theme-plugin.
If you want to have a look: https://github.com/phsteffen/kanboard-themeplus

Now you have a choise of two themes - but the dark-theme is in an very early stage. :-)
You can put your own css in a file to add your own theme or to change the themes.
You can add your logo on the login-Page.
You can replace the KB-Logo on all pages.
You can replace the favicon.
And some other thinks.

If you have improvement - this would be great.

**Comment by mcorteel** [comment]
I opened issue #2107 to change button layouts (include the icon in the anchor), which would greatly improve the possibilities for theming.
@phsteffen, could you please comment on this issue?

**Comment by AZimmerhofer** [comment]
I am using your "old" theme... Very good! Are you planning to introduce a mobile theme / responsive design for templates?

**Comment by phsteffen** [comment]
@phsc 
Thank you :-)
Have a look at this: https://github.com/phsteffen/kanboard-themeplus
I reduced the whitespace between the cards. Only the screenshots are not update to date.

@AZimmerhofer
Thx. 
Perhaps you should use my "new" theme. It has the same design-improvements and I will keep it update to date.
I dont planning a mobile theme. I think kanban should take place on a big screen (or on a whiteboard ;-). Perhaps I will optimize the theme for smaller screen a little bit - but not more.

**Comment by AZimmerhofer** [comment]
@phsteffen 

I have updated it. Thanks for the new one, too. I fully agree: Kanban needs a large screen normally. But it would be nice to check the projects and tasks (dashboard) mobile, too. For example: Now I can't use the dashboard screen on my iphone.

**Comment by wucherpfennig** [comment]
@phsteffen 
Do you plan to inlcude a printer friendly style too?

**Comment by phsteffen** [comment]
@wucherpfennig 
I improved the print-css (default-theme) in my theme-plugin just now.
So the dashboard, the board and the ticket-view is a bit more printer-friendly.
Not perfect - but a beginning ;-)

Here some screenshots:
![dashboard](https://cloud.githubusercontent.com/assets/18245229/14586464/182b68d8-0499-11e6-9c87-4660cac7497c.jpg)
![demo project](https://cloud.githubusercontent.com/assets/18245229/14586465/182cbd00-0499-11e6-9030-c5d2ddceebd5.jpg)
![demo project1](https://cloud.githubusercontent.com/assets/18245229/14586466/182dcf10-0499-11e6-88b7-0aee357c2ba3.jpg)
