### ISSUE TITLE
Add an option that forbid task creation if no categories is filled 

### ISSUE THREAD

**Issue by jbarotin** [kanboard/kanboard#2089]
Hi,

For some project, it would be very time effective if it was possible to avoid task creation if no category is filled.

Maybee, could-it be an automated action ?

**Comment by fguillot** [comment]
Automatic actions doesn't do any form of validation but a new automatic action may assign a default category.

**Comment by jbarotin** [comment]
It can work, because, my issue is that it need lot of clicks to change a category of a task. 

With an automated task that assign default category it should be ok : because I can change the categorie directly in the board.

Thanks a lot
