### ISSUE TITLE
[FR] comma as a seperator for time logging

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#2090]
### Expected behaviour

support `,` as a seperator for time logging and export like **1,5** instead of **1.5** - as part of the localization

**Comment by WolfgangAndreas** [comment]
+1 would be nice for the planned time and used time as well.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
