### ISSUE TITLE
Google auth stopped working on upgrade

### ISSUE THREAD

**Issue by ptman** [kanboard/kanboard#2091]
### Expected behaviour

Google Auth should work like it did
### Actual behaviour

"External authentication failed"
### Steps to reproduce
1. I installed kanboard (via docker) a couple of months ago. And added google auth. It worked.
2. Upgraded kanboard (and google auth, when it stopped working)
### Configuration

Application version: 1.0.27
PHP version: 5.6.17
PHP SAPI: fpm-fcgi
OS version: Linux 3.16.0-4-amd64
Database driver: postgres
Database version: 9.5.1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36

**Comment by fguillot** [comment]
You have the latest version of the GoogleAuth plugin, right?

**Comment by ptman** [comment]
Yes. I updated that when at first google login didn't work, but that didn't fix it either.

**Comment by fguillot** [comment]
Did you solve your issue after all this time?

**Comment by ptman** [comment]
Sorry, I forgot about it. At least it works now with latest
