### ISSUE TITLE
Default assignee when creating task

### ISSUE THREAD

**Issue by AgatonSax** [kanboard/kanboard#2092]
How can I change the default behavior for new tasks created, so that the assignee is set to "Unassigned" instead of the creators name (like prior to version 1.0.25)? I would find it very useful if I, per project, could set default assignee (Choose from "Unassigned" and "Task Creator", perhaps) from somewhere under Settings.

**Comment by NinjaPewPew** [comment]
I would like a option like that also very much. In our workflow the task creator is not always the one that will do this task later. I often forget to change it to "unassigned" before saving. Creating sub-task has "unassigned" as a default value. It's confusing that they not behave the same way.

**Comment by jbarotin** [comment]
Maybee, it would be possible thought automatic table. The problem is that we need to provide a specifi column name to each automatic tasks. 

I would be grateful to add an entry "all columns" in the automatic task at the column selection step.

**Comment by fguillot** [comment]
In Kanboard 1.0.39, the default assignee is now "unassigned" for team projects.

**Comment by felixkretschmer** [comment]
Is there a possibilty to edit the default behavior.
In some projects I prefer the default to be the creator. In others "unassigned" works much better.
