### ISSUE TITLE
Incorrect email address on notification email

### ISSUE THREAD

**Issue by masurti** [kanboard/kanboard#2095]
### Expected behaviour

When a new card is created on the Kanboard, a notification email is sent to the Assignee. The name AND the email address that is shown for the sender should be of the user that creates the card.
### Actual behaviour

When a new card is created on the Kanboard, a notification email is sent to the Assignee. The name that is shown for the sender is of the user that creates the card, which is correct.

However, the email address of the sender that is shown is for the Admin user - not of the person that has created the card.
### Steps to reproduce
1. Set up two users with respective email addresses as well as an admin account with its own email address.
2. Ensure all users are set to receive notifications "Only for tasks created by me and assigned to me".
3. User 1 creates a card on the board and assigns it to user 2.
4. User 2 gets notification via email stating the name of User 1 but the email address of Admin.
5. Any further activity on the card will send notification to User 2 and each time it will have the name of the user the performs the action but the email address will be of Admin account.
6.  This means that if User 2 replies to the email, Admin will get that email and not the User that performed the action.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.27
- Database type and version: MySQL 5.5.44-MariaDB
- PHP version: 5.4.16 
- OS: Linux 3.10.0-327.4.4.el7.x86_64
- Browser: IE 11

**Comment by fguillot** [comment]
- The sender name is the name of the person that does the action (the logged user, example: "John Doe via Kanboard")
- The sender email address is the one configured in the config file, defined by the parameter `MAIL_FROM`.

This is not the email of a user because that offer the possibility to implement new features in the future, for example: "reply to the notification and create a comment in Kanboard automatically".

**Comment by masurti** [comment]
Users receiving the email are reading the name and replying to the email expecting the user who's name they read to receive the reply and not the mailbox that was set-up in config.

IMHO both the name and the email address should be for the same person on the email to save the confusion.

**Comment by fguillot** [comment]
Kanboard 1.0.40 supports the Reply-To header that allows people to reply to the person that does the action.
