### ISSUE TITLE
Moving task in Gantt leads to errors in dates (3 bugs)

### ISSUE THREAD

**Issue by milankni** [kanboard/kanboard#2097]
1. Fresh installation
2. Login as admin/admin
3. From Dashboard: create New project "Test"
4. From Board: add new task "Test 10 Apr 2016" to Backlog column, with due date 10 Apr 2016.
5. View the new task, click Edit and set start date 8 Apr 2016.
   
   Now
   - the calendar shows two events: one on 8 Apr and another on 10 Apr. _These are not connected as lasting from - to._
   - the Gantt shows a project starting on 8 and finishing on 10 Apr. This seems okay to me.
6. From Gantt: click & drag the task so that it moves +3 days (i.e. 11 - 13 Apr).
   
   Now
   - the calendar shows two events: one on 10 Apr and another on 12 Apr
   - the Gantt shows the task lasts from 10 - 12 Apr.
   
   I.e. _it has moved itself one day backwards!_
7. From Gantt: click & drag the due date (only!) from the current 12 Apr to 15 Apr.
   
   Now
   - the calendar shows two events: one on 9 Apr and another on 14 Apr
   - the Gantt shows the task lasts from 9 - 14 Apr.
   
   Again, _both start and due dates moved one day backwards!_
8. From Gantt: click & drag the task so that it moves -3 days (i.e. 6 - 11 Apr).
   
   Now
   - the calendar shows two events: one as interval 5 - 6 Apr and another on 10 Apr
   - the Gantt shows the task lasts from 5 - 10 Apr.
   
   In addition to the "-1 day shift" bug described above, _the first calendar event shows a duration now, too._

![screen 01 calendar](https://cloud.githubusercontent.com/assets/937861/14342553/b430a11e-fc9a-11e5-9c5b-f32117f53b10.png)

![screen 02 task view](https://cloud.githubusercontent.com/assets/937861/14342567/ce17a654-fc9a-11e5-87af-42944a30c79e.png)

![screen 03 gantt](https://cloud.githubusercontent.com/assets/937861/14342570/d2a44ede-fc9a-11e5-9779-62e590149bb6.png)
### Configuration

Application version: 1.0.27
PHP version: 7.0.5
PHP SAPI: fpm-fcgi
OS version: Linux 4.1.20-3-ARCH
Database driver: sqlite
Database version: 3.11.1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36

**Comment by PhineasClick** [comment]
I can confirm this behaviour. In my case you only need to move a Task in Gantt, switch to another view and then back to Gantt, and the Task has moved back 1 day.

    Application version: 1.0.33
    PHP version: 5.6.23
    PHP SAPI: apache2handler
    OS version: Windows NT 6.1
    Database driver: sqlite
    Database version: 3.8.10.2
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
