### ISSUE TITLE
template hook for task listing

### ISSUE THREAD

**Issue by walter03** [kanboard/kanboard#2098]
### Expected behaviour

It should be possible to write a plugin for the task listing (Template/listing/show.php)
### Actual behaviour

Template/listing/show is not part of the documented template hooks.
### Steps to reproduce
1. listing of hooks in https://github.com/fguillot/kanboard/blob/45f21e1cd8e09e39d5f74d8826b27fc202428b3c/doc/plugin-hooks.markdown
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.23
- Database type and version: MySQL
- PHP version: 5.6
- OS: RHEL 7
- Browser: Chrome 49

**Comment by fguillot** [comment]
Well, if you still need template hooks, the best way is to send a pull-request.
