### ISSUE TITLE
Feature Request: Auto save while create / editing items

### ISSUE THREAD

**Issue by wucherpfennig** [kanboard/kanboard#2109]
### Expected behaviour

Auto Save Tasks / Description (or everthing in a modal) every XX seconds
### Actual behaviour

Eg. if you create a new task (modal) and accidentally click on the background all input is lost.

This is extremely stressfull if you take notes (description) during a meeting or similar occasions...
### Steps to reproduce
1. Create task
2. Click background
3. Cry
### Configuration

Version: 1.0.27
PHP version: 5.6.19
PHP SAPI: litespeed
OS version: Linux 2.6.18-448.16.1.el5.lve0.8.70
Datenbanktreiber mysql
Database version: 5.6.29-log
Browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36

**Comment by eurodrew555** [comment]
I keep getting caught out by this as well. Frustrating to lose all your updates when you accidentally click outside the popup edit page!

**Comment by fguillot** [comment]
Now, with the latest version of KB clicking on the background doesn't close the modal dialog.
