### ISSUE TITLE
Feature Request: Analyze by Swimlane

### ISSUE THREAD

**Issue by wucherpfennig** [kanboard/kanboard#2115]
### Expected behaviour

Show analysis for
- Project
- Swimlane A
- Swimlane B
- Swimlane N
### Actual behaviour

Show analysis for
- Project
### Steps to reproduce
1. Open Analysis
### Configuration

Version: 1.0.27
PHP version: 5.6.19
PHP SAPI: litespeed
OS version: Linux 2.6.18-448.16.1.el5.lve0.8.70
Datenbanktreiber mysql
Database version: 5.6.29-log
Browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
