### ISSUE TITLE
Feature Request: Consistency with start/end dates for project and tasks

### ISSUE THREAD

**Issue by ghost** [kanboard/kanboard#2116]
(Feature request)
### Expected behaviour

Adding start/end date for projects will avoid start/end dates for tasks outside project dates.
### Actual behaviour

It is still possible to assign a start/end date for a task outside the project dates.
By example, in a project that should ends on 2016-04-30, a task can be set to end on 2016-05-02, i.e. after the project deadline.
### Steps to reproduce
1. Define start/end dates for the project.
2. Define start/end dates for a task in this project, outside the project dates.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.27 (last stable release)

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
