### ISSUE TITLE
Gantt charts with short tasks (less than a day)

### ISSUE THREAD

**Issue by mehdid** [kanboard/kanboard#2119]
### Expected behaviour

We create tasks in a project, estimate their duration and complexity and then set links between those tasks. Often, we end-up creating tasks that will last less than a day. The Gantt view is very useless for that kind of tasks since it doesn't show what happens within a day.

Also, there is no reason one should not set a deadline as accurate as a specific hour in a day.
### Actual behaviour

All tasks are displayed the same way and links between tasks are not correctly drawn.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.27

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
