### ISSUE TITLE
New project, not possible after removing an old project

### ISSUE THREAD

**Issue by Dendek** [kanboard/kanboard#2122]
Adding a new project or private project from the dashboard. 
Its no longer possible after having an old project removed from the list

### Steps to reproduce
1. Remove an old project from the list
2. + New project or private project
3. Fill in a name
4. Press "Save" and it will not continue, only way are to "Cancel" and the message below are shown.

![project](https://cloud.githubusercontent.com/assets/18431412/14479654/2be0c34e-0121-11e6-905e-5e16495be1a5.JPG)

It seems to me, that the DB in someway crashes...
Does anyone have an idea ??

### Configuration
    Application version: 1.0.27
    PHP version: 5.5.29
    PHP SAPI: fpm-fcgi
    OS version: Linux 3.12.6
    Database driver: sqlite
    Database version: 3.4.1
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by fguillot** [comment]
- Did you create a new project with the same name as the old one?
- Since which version of Kanboard your database is created?

In the past, a unique constraint was defined on the project name. Sqlite doesn't fully support alter table. Maybe you have a old database.

Try to enable the debug mode and do the same operation, you will see the exact error message from the database.

**Comment by Dendek** [comment]
Hi fguillot

Since I experienced this behavior first time I have made 3 re-installations from scratch.
Everything is working fine, until I delete a project...
 
I tried to create new projects with a lot of different names, without any changes.
Function "New project" and "Private project" returns the message "Unable to create your project"
I have logged out and in as other users and privileges. No changes. 
Haven't tried the debug yet.
I just started to use Kanboard since this Monday and it's installed on my QNAB NAS with webserver and phpMyAdmin installed. See specifications below for QNAB, thus my Kanboard is still using the predefined sqlitedb in the folder ..\data\db.sqlite.
Maybe I should change db to use MariaDB instead ?

**Database-server QNAB**
    Server: Localhost via UNIX socket
    Servertype: MariaDB
    Serverversion: 5.5.44-MariaDB-log - MariaDB Server
    Protokolversion: 10

**Webserver QNAB**
    Apache
    Databaseklientversion: libmysql - mysqlnd 5.0.11-dev - 20120503

**phpMyAdmin QNAB**
    Versionsinformation: 4.1.13,

**Comment by Dendek** [comment]
Hi 
Just made a debug file.
- I logged in as admin
- Tried to create a new project
- Stranded at "save" project.

Maybe it make more sence to you ? :-)
Looking forward to your feedback.

[debug.txt](https://github.com/fguillot/kanboard/files/222122/debug.txt)

Regards

**Comment by Dendek** [comment]
Hi again

I change config.default.php to use mysql and mariaDB, located on my QNAB NAS (localhost)
It now seems to work perfect.

**Configuration**
    Application version: 1.0.27
    PHP version: 5.5.31
    PHP SAPI: fpm-fcgi
    OS version: Linux 3.12.6
    Database driver: mysql
    Database version: 5.5.44-MariaDB-log
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by fguillot** [comment]
According to your debug file, here is the SQL error:

```
2016-04-16 11:34:17] [debug] SQLSTATE[23000]: Integrity constraint violation: 19 columns title, project_id are not unique
```

I'm not able to reproduce the issue on my laptop. Maybe that come from your Sqlite version, need to be tested with another environment...
