### ISSUE TITLE
Feature request: Custom URL name for tasks

### ISSUE THREAD

**Issue by raphaelbastide** [kanboard/kanboard#2124]
### Expected behaviour

Each task could have a custom name displayed in the URL. For example, `/project/2/task/todo` or `/project/2/task/14-todo` Instead of `/project/2/task/14`

This would allow to quickly access to a specific task directly in the url bar of modern browsers. E.g. If a user type “todo” in the URL bar, `http://demo.kanboard.net/project/2/task/todo` will show up and considerably reduce the number of click to access it.
### Actual behaviour

The current tasks URL show only an ID and are not searchable in the smart address bar (Firefox or Chrome…)
### Comments
- A conflict check will be needed if the id is not appended to the custom name
- Custom names could be set for board as well: `http://demo.kanboard.net/project/customboard/task/todo`

**Comment by Chaosmeister** [comment]
:+1:

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
