### ISSUE TITLE
Make a value mandatory (automatic action)

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#2130]
### Expected behaviour

I should be able to make it compulsory that a specified column ('complexity' for me) is complete once a task reaches a certain column.
### Actual behaviour

We use 'complexity' to track the number of (genomic) samples associated with a task, which means we can pull out a load of statistics to track performance etc. However, sometimes the 'complexity' field doesn't get filled in ... maybe the person has forgotten to do it because they're in a rush.

Anyway, I'd like to be able to say that if a task gets to, say, column 3, that I expect a field to be complete. For us it's complexity, but it could also conceivably be 'priority', 'assignee', 'category', 'due date', or similar.

**Comment by alefaucheur** [comment]
I would appreciate the same improvement (or more example of automatic action)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
