### ISSUE TITLE
Use color picker in "assign color ..." automatic actions

### ISSUE THREAD

**Issue by gene-pavlovsky** [kanboard/kanboard#2133]
Would be nice to have a color picker rather than the dropdown when creating "assign color ..." automatic actions.

**Comment by 85pando** [comment]
Interestingly, I just wanted to add the same issue (-:

Could also be:
* Radio Buttons with colored fields.
* Coloring the fields in the dropdown menu (background color).
* Just have the block of colors there like it is in "edit task".

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
