### ISSUE TITLE
[FR] Automatic actions for subtasks

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#2134]
### Expected behaviour

It would great to have an automatic action that assigns the user who opens/closes a subtask automatically to it.
### Actual behaviour

I'm using a task with a lot of subtasks (for testing purposes) as a template and duplicate it. Unfortunately it doesn't keep the assignees this way.

_There are a few requests in this context that whish for templates. I think having automatic actions on that level would help_

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
