### ISSUE TITLE
Close task modal dialog and cache

### ISSUE THREAD

**Issue by Kolesar** [kanboard/kanboard#2137]
### Expected behavior

When I click on close task link I expect modal confirmation dialog
### Actual behavior

Nothing happened!!
### Steps to reproduce
1. Use the VPN connection with SSL/HTTPS and try to close task

Sometimes, works, but most of time does not work.
### Configuration

```
Application version: master
PHP version: 5.5.14
PHP SAPI: apache2handler
OS version: Linux 4.1.20-11-default
Database driver: mysql
Database version: 10.0.22-MariaDB
Browser: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```
### Note

If I comment  https://github.com/fguillot/kanboard/blob/master/app/Core/Http/Response.php#L161 works, but it is not solutions.

**Comment by fguillot** [comment]
Are your sure that is coming from Kanboard and not your connection that is too slow or have packet lost when your are using the VPN?
