### ISSUE TITLE
Error when creating Automatic Actions

### ISSUE THREAD

**Issue by justice777** [kanboard/kanboard#2141]
### Expected behaviour

When creating a new Automatic Action, clicking "Next Step" should move the user to the next part of action creation.

### Actual behaviour

An error message is displayed:

**Internal Error: Automatic Action Not Found: \\Kanboard\\Action\\CommentCreationMoveTaskColumn**

### Steps to reproduce

1. Navigate to a Project -> Settings -> Automatic Actions
2. Click "Add a new action"
3. Select any action from the dropdown
4. Click "Next Step"

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.28
- Database type and version: mysql\5.5.43-37.2-log
- PHP version: 5.3.24
- OS: Linux 2.6.32-604.30.3.lve1.3.63.el6.nfsfixes.x86_64
- Browser: Chrome\49.0.2623.112 m, Firefox\33.1.1

**Comment by fguillot** [comment]
I'm not able to reproduce the issue are you sure that everything is installed correctly?

**Comment by justice777** [comment]
I believe so.. The issue is only happening on one of my servers though. The
other is trouble free.
