### ISSUE TITLE
Auto-Update start date when moved from X

### ISSUE THREAD

**Issue by AgatonSax** [kanboard/kanboard#2142]
### Expected behaviour

I'd like to be able to choose "Move task from a column" under the Event-menu.
### Actual behaviour

Now it's "Move a task to another column" resulting in a problem if you have more columns (and perhaps a nonlinear workflow)
![image](https://cloud.githubusercontent.com/assets/5526928/14637616/c731751c-0632-11e6-879e-b21de05989ff.png)
### Configuration

Application version: 1.0.27
PHP version: 5.5.9-1ubuntu4.14
PHP SAPI: apache2handler
OS version: Linux 3.13.0-66-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
