### ISSUE TITLE
number of items in a list view

### ISSUE THREAD

**Issue by stlorenz** [kanboard/kanboard#2145]
I have a big number of projects, after 20 projects in the index, paginations kicks in. While I see that this is a nice behaviour in many use cases, on my 27" screens its a waste of screen real estate. 

If i would know how, I would try add a field myself, eg. "number of items, possible choices: 25, 50, 100, all. 

This should be a permanent choice. 

Thanks for reading 
### Expected behaviour

Feature Request:

Make it possible to adapt the the nummer of items in any list view, e.g. project index and so on. 
### Actual behaviour

automatic paginataion
### Steps to reproduce

does not apply
### Configuration

does not apply

**Comment by fguillot** [comment]
Duplicate with #1575
