### ISSUE TITLE
Automate change of swimlane and/or column based on dates

### ISSUE THREAD

**Issue by mkauzlar** [kanboard/kanboard#2148]
### Expected behaviour

Please add a feature to be able to automate changes in swimlanes and columns based on start date, end date etc.
For instance, if a task was under Doing column should be moved under Backlog column if the Due Date has already passed:

Backlog   To Do   Doing    Done
-----------+---------+--------+--------
### Configuration

```
Application version: 1.0.27
PHP version: 5.5.9-1ubuntu4.14
PHP SAPI: fpm-fcgi
OS version: Linux 3.13.0-66-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

**Comment by elfalem** [comment]
I second this. Also it would be great to trigger the change on date offsets. So, if a tasks due date is in 10 days from today, move to a different column today.

**Comment by fguillot** [comment]
You could send a pull-request or write a plugin if you need this feature.
