### ISSUE TITLE
Column widths fixed and too small when pressing back from task to board

### ISSUE THREAD

**Issue by nerdoc** [kanboard/kanboard#2150]
### Expected behaviour

The column width should always be filling 25% of the screen when having 4 columns.
### Actual behaviour

Sometimes, when clicking at a task, entering the task, and pressing the "back" browser button, you get back to the _board_, but the (here 4) columns are not spread all over the screen, but pressed together into the left side. Each column has a width of 240px (fixed!). The corresponding CSS element is in app.css:27:

```
#board th.board-column-header {
  width: 240px;
}
```
### Steps to reproduce
1. Go into a task
2. (edit it? I don't know, it is not always reproducible. Maybe in 1 of 10 times?)
3. go back to board with browser "Back" button
   ![bildschirmfoto von 2016-04-20 19-41-46](https://cloud.githubusercontent.com/assets/2955584/14684405/148f2aae-0730-11e6-84cd-4e0200bbc305.png)
4. pressing F5 "normalizes" the screen again:
   ![bildschirmfoto von 2016-04-20 19-45-01](https://cloud.githubusercontent.com/assets/2955584/14684503/886351da-0730-11e6-8b5a-a19471d6061f.png)
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.27
- Database type and version: MYSQL 5.5
- PHP version: 5.6, 7.0.5
- OS: Linux (Server/Client)
- Browser: Firefox 45

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
