### ISSUE TITLE
Dragging the mouse pointer out of a modal window when selecting text in the description closes the window without confirmation

### ISSUE THREAD

**Issue by PeGa** [kanboard/kanboard#2153]
### Expected behaviour

Modal window (e.g. new task) should remain open. 
### Actual behaviour

Dragging the mouse out of the screen (while pressing the primary mouse click while selecting text) closes the modal window. This happens only when selecting text in the description, and does not happen in the title.
### Steps to reproduce
1. Click a '+' in any column OR press 'n'
2. Write any text in the description
3. Select it, and without releasing the button, drag the pointer outside of the modal window.
### Configuration

Application version: 1.0.27
PHP version: 5.5.33-pl0-gentoo
PHP SAPI: fpm-fcgi
OS version: Linux 4.1.12-gentoo
Database driver: sqlite
Database version: 3.11.1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36

**Comment by fguillot** [comment]
This is fixed if you download the latest version of Kanboard.
