### ISSUE TITLE
[Feature Request] Possibility to change Rounding Timestamp

### ISSUE THREAD

**Issue by MatthiasKohlhoff** [kanboard/kanboard#2160]
### Expected behaviour

Would be grate, if one could change the rounding of timestamps in config.php
### Actual behaviour

Timestamps are rounded to the nearest quarter
### Reason

We often have Subtasks which take only 2 or 3 Minutes. In this case the Time is rounded to zero

**Comment by fguillot** [comment]
There are no rounding anymore.
