### ISSUE TITLE
public rss feed doesn't validate

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#2165]
### Expected behaviour

any rss reader should be able to read this feed. Seems Atom created the troubles for some of the feed readers. Like

https://github.com/jonbrett/cinnamon-feeds-applet
~~https://chrome.google.com/webstore/detail/rss-feed-reader/pnjaodmkngahhkoihejjehlcdlnohgmp~~ works

### Actual behaviour

```
This feed does not validate.

line 12, column 46: id must be a full and valid URL: 4208-comment.create-247-1461314076 (50 occurrences) [help]

        <id>4208-comment.create-247-1461314076</id>
                                              ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.

line 55, column 42: Two entries with the same value for atom:updated: 2016-04-22T10:14:38+02:00 (2 occurrences) [help]

        <updated>2016-04-22T10:14:38+02:00</updated>
```
                                          

### Configuration

Version: 1.0.27
PHP version: 5.6.20-1~he.0
PHP SAPI: apache2handler
OS version: Linux 2.6.18-prep-xenU-static-i686-he+12
Datenbanktreiber mysql
Database version: 5.5.47-37.7-log
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36

**Comment by fguillot** [comment]
Feeds are now valid (dev branch).
