### ISSUE TITLE
Kanboard is very slow to save tasks

### ISSUE THREAD

**Issue by Mammeri** [kanboard/kanboard#2166]
### Expected behaviour

Some weeks ago kanboard was still super fast : moving a task from a column to another was immediate.

### Actual behaviour

When we create a task or move one, it takes around 10 seconds to save the change.
Note that it doesn't seems to occurs on all projets, only certain where there are other users on the board.

At the end of the page you can check the debug.log file. It seems that somes queries took more than 7 seconds. FYI there are 42 projects and 64 users. But not everybody use kanboard

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.25
- Database type and version: SQLite provided by kanboard if I recall
- PHP version: 5.6
- OS: Debian 3.2.57-3
- Browser: Chrome and Firefox, latest versions

[debug.txt](https://github.com/fguillot/kanboard/files/231667/debug.txt)

**Comment by Kolesar** [comment]
I see similar on many actions and I think that problem is with mail notifications. Because as I can see, KB does not send mail to mail queue and PHP code waiting for mail server response. Sometimes communication with mail server (or mail relay) is slow or whatever and it is reflect to KB speed.

Yesterday, I was situation about uploading document (attachment to task) and after few hours I get list of many documents. All my tries are accepted. Very strange, ...

**Comment by langerhans** [comment]
I see the same slowness here. @Mammeri note that the queries you see as taking more than 7 seconds all have the suffix `E-5` at the duration. They didn't actually take that long, just an unfortunate number formatting issue in the log.

```
Version: 1.0.27
PHP version: 5.6.10
PHP SAPI: cgi-fcgi
OS version: Darwin 15.4.0
Datenbanktreiber sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17
```

**Comment by fguillot** [comment]
The latest version of Kanboard add the support of background workers to delegate slower operations to another process. This feature still experimental but greatly improve the performances.

Have a look to this page: https://kanboard.net/documentation/performances
