### ISSUE TITLE
[FR]The notifications list needs a column with the project name and id

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#2176]
### Expected behaviour

tell where the notification belongs to

### Actual behaviour

only a list of notifications with task id, no project name or ID

### Configuration

Version: 1.0.27
PHP version: 5.6.20-1~he.0
PHP SAPI: apache2handler
OS version: Linux 2.6.18-prep-xenU-static-i686-he+12
Datenbanktreiber mysql
Database version: 5.5.47-37.7-log
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36

**Comment by fguillot** [comment]
This is now available in the development version.
