### ISSUE TITLE
Comment input not saved when mouse cursor clicks outside of editor region before clicking Save button

### ISSUE THREAD

**Issue by jlchoike** [kanboard/kanboard#2177]
### Expected behaviour

Tell us what should happen

Kanboard should save the text input when editing a comment when my mouse cursor is clicked outside of the editor

### Actual behaviour

Tell us what happens instead

Kanboard exits from the editor; and my input is lost if I do not save.

### Steps to reproduce

1. Open comment editor
2. Add text to comment text input
3. Click outside of editor region

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.27
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by jlchoike** [comment]
If autosave is enabled in Markdown.js, then this would be sufficient for resolving issue 2177 (https://github.com/fguillot/kanboard/issues/2177). I cannot tell you how many times I have lost my changes to comments because I accidentally clicked away from the window before saving. I have been using Kanboard comments as a way of documenting user stories before creating actual tasks representing these stories; so losing my work has been frustrating.

Please let me know if this is possible. Thanks for your help!

**Comment by fguillot** [comment]
Everything is possible, it's just question of time and priority.

**Comment by jlchoike** [comment]
@fguillot Understood. Pardon the rant about losing work :)

**Comment by wucherpfennig** [comment]
See #2109

**Comment by AgatonSax** [comment]
+1 for autosave

**Comment by fguillot** [comment]
In the version 1.0.34, clicking on the background do not close anymore the form so it avoid to lost accidentally entered information.

**Comment by jlchoike** [comment]
I saw the release notes this morning - thanks for fixing this issue!
