### ISSUE TITLE
[FR] (Collapse/Expand) and (Hide/Show) all swimlanes/columns

### ISSUE THREAD

**Issue by didierm** [kanboard/kanboard#2179]
To keep an overview (see also issue #426), we are managing all our current projects (> 20, and growing) in one Kanboard project, divided in lots of swimlanes.

Even with _'Compact View', 'Collapsed tasks' and 'Maximum Height'_ applied, the kanboard display quickly grows very cluttered, with lots of up/down scrolling required for navigation.
- It might be beneficial to have a **[Collapse all/Expand all/Restore]** option for the swimlanes, which would allow you to quickly focus on or navigate to the swimlanes of interest.
- The same rationale could apply to the columns display (e.g. hide all columns except for the "Work in progress").

This might also largely benefit the search/filter function (when applying a filter, have an option to collapse all columns/swimlanes, except for those cards which result from the search).

_(apparently, this has been requested & applied for JIRA too : https://jira.atlassian.com/browse/JSW-5413)_

**Comment by wucherpfennig** [comment]
Any updates in this direction?

Another suggestion:
There is a search attribute "swimlane" it would be great if one could integrate the feature above with this specific search attribute. Means if there a matching swimlane was found only this one should be uncollapsed.

best regards

wucherpfennig

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
