### ISSUE TITLE
[Feature Request] Highlight today column in the gantt chart

### ISSUE THREAD

**Issue by eitzenbe** [kanboard/kanboard#2182]
### Expected behaviour

when visiting the gantt chart the column of today shopuld be highlighted using a different color as background (like e.g. light green)
### Actual behaviour

Its not visible which column is today

Code proposal based on jquery would be:

$(document).ready(function() {
  $('.ganttview-grid-row').each(function() {
    $(this).children('div').eq(XXXXX).css({ backgroundColor: "lightgreen"});//addClass('today');
  });
});

PLUS php code to calculate XXXXX being the number of column (starting from 1 for the first) that represents today

**Comment by eitzenbe** [comment]
improved client side script to highlight today. Just include it via script tag 

Assumes no scrolling in timeline so the first day of month matching is today...
Is agnostic to timezones ;) so better do not rely on it around mightnight

$(document).ready(function() {
  var today = 0;
  $('.ganttview-hzheader-day').each(function() {
    if ($(this).text() == new Date().getDate()) {
      return false;
    }
    today ++;
    return true;
  });
  $('.ganttview-grid-row').each(function() {
    $(this).children('div').eq(today).css({ backgroundColor: "lightgreen"});//addClass('today');
  });
});

**Comment by akien-mga** [comment]
I'd also like to have this feature, it always takes me some time to find out what column is today.

**Comment by juracy** [comment]
I believe this issue should be moved to https://github.com/kanboard/plugin-gantt

**Comment by fguillot** [comment]
This is in this PR https://github.com/kanboard/plugin-gantt/pull/7
