### ISSUE TITLE
Uploaded avatars should be stored in PNG (or in much higher quality)

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#2184]
Testing the avatar upload feature in 1.0.27, the uploaded avatars are extremely hard to recognize for two reasons:
- In the boards they are shown at extremely small size (twice smaller than most other websites, including Trello for example)
- They are JPEG compressed to the extreme. Ideally they should be stored as lossless PNG (it's not like they're going to weight much at resolutions <200x200). Worst case, if you really want to use JPEG, it should be at 95-99% quality instead.

You could also consider keeping only the "big size" version, in lossless PNG, and scale them down with CSS, letting browser handle it. This would also make it better for high-DPI (ex: retina) displays.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
