### ISSUE TITLE
Bug with priorities in determing which avatar to show

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#2185]
With kanboard 1.0.27, I've seen some cases where:
- The manually set/uploaded avatar gets overridden by the Google/Gravatar "default image" (as seen in the screenshot below, with a "Google Apps for your domain" account)
- The "default image" of Gravatar/Google/etc. gets used instead of the letter-based fallback avatar (ie: if you don't disable gravatar entirely in the global settings)

The order of priority I expect is:
1. Manually uploaded avatar
2. Google/LDAP/etc. private auth systems
3. Gravatar
4. Letter-based fallback

But cases 2 and 3 should avoid overriding 4 if they are using gravatar or google's "default" images:

![capture d ecran de 2016-04-28 14-20-58](https://cloud.githubusercontent.com/assets/479401/14896705/ec93b7ea-0d4c-11e6-8750-c892e812ffce.png)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
