### ISSUE TITLE
Auto-refresh after specified interval stops working

### ISSUE THREAD

**Issue by jgirouard** [kanboard/kanboard#2186]
We are running version 1.0.26.

If a user drags a task from one column to another or drags a task from one swimlane to another, the auto-refresh stops running.  The user has to manually refresh the page to start the auto-refresh again.

For example, we've set the refresh interval to 5 seconds.  Using Firebug in Firefox, I can see the "check" action executing every 5 seconds when I have the board open.  If I drag a task to another column or to another swimlane, the "save" action executes, but the "check" action no longer executes every 5 seconds.  So if someone on another computer makes a change, I don't automatically see the change on my computer.  If I manually refresh the page, the other user's change appears on my screen and the "check" action starts running again every 5 seconds.

It seems that the "check" action will execute every 5 seconds after editing a task, changing assignee, etc. since these actions essentially refresh the page.

Could you please look into this?

Thanks!

**Comment by fguillot** [comment]
You should try again with the latest version of Kanboard.
