### ISSUE TITLE
Redmine integration - either import from or sit atop....

### ISSUE THREAD

**Issue by PeterWhittaker** [kanboard/kanboard#219]
Our team of over 20 has been using self-hosted redmine for several years on a complex project. Moving away from redmine is extremely unlikely, but we would like to add kanban capabilities (and there are no actively maintained open source kanban plugins for redmine).

Some level of integration between kanboard and redmine could serve our purpose. Ideally, kanboard could use redmine as its issue source; second-best would be two-way sync between redmine and kanboard; third-best would be manual import from redmine, export back.

**Comment by joshuacox** [comment]
I've been using this one for over six months and am even on a redmine 3 branch http://www.redminebacklogs.net/  , I came across this post as I'm always looking redmine plugins that extend the experience

**Comment by jgarcin** [comment]
Hello, I use also much Kanboard, I find that this tool has a real added-value in our project management. However all our teams do not work with the kanboard, we use in parallel much Redmine.
I will like to be able to combine by a synchonisation the technicians who use Redmine, and the project managers who use Kanboard.
I can thus only consolidate the idea to have such a plugin for a management even nimbler between the various actors!

**Comment by joshuacox** [comment]
@jgarcin take a look at [redminebacklogs](http://www.redminebacklogs.net/) it is not a marriage between kanboard and redmine, but it does get most of the functionality such a marriage might provide.   That being said I'd still to see kanboard integration with redmine.

But any  such effort would do very well to look at the mentioned redminebacklogs, as you'd want much of the same functionality (ie dragging around issues in the kanboard needs to have corresponding status changes in redmine, etc).

**Comment by taladar** [comment]
Redmine Backlogs is very different because it only works on one Redmine project at a time. For Kanban it would be useful to have one board for tasks being worked on by one person or group in all projects though.

**Comment by jensaug** [comment]
+1 for @PeterWhittaker feature request. I'd love to switch our customers and projects from the SCRUM Backlogs stuff we use in Redmine to our newly installed sweet KB Kanboard, but it's just too much manual work today.

**Comment by Zayon** [comment]
Hi,

I'm trying create a Redmine integration plugin.

@fguillot I'm following instructions of this page : https://kanboard.net/documentation/plugin-external-tasks, but I need some help. 

Do you have an example plugin that use External Task Provider ? Maybe we can discuss this on IRC ?

Thanks.

**Comment by Zayon** [comment]
Hi,

https://github.com/Zayon/kanboard-redmine

It's really basic for now, feel free to ask more features.

**Comment by fguillot** [comment]
@Zayon This plugin is using the external task provider: https://github.com/kanboard/plugin-github-frontend

**Comment by Zayon** [comment]
Yeah thanks, I did find it and used it to create the plugin. You might want to try it, there's a dockerfile to test it easily. Maybe you can close this issue if you like it.

**Comment by fguillot** [comment]
I'm closing this ticket. I let the community develop plugins to implement such feature.
