### ISSUE TITLE
Dependent tasks should have their date changed based on parent task

### ISSUE THREAD

**Issue by oparoz** [kanboard/kanboard#2190]
### Steps to reproduce
1. Create 2 tasks 
2. Task 1 starts on the 1st
3. Task 2 starts on the 10th
4. Make task 2 a child of task 1
5. Change start date of task 1 to the 15th
### Expected behaviour

Task 2 should now start on the 25th
Ideally we should use the task's end date, but that can come later

It would be great to be able to see all tasks move at the same time from the gantt view.

Without this feature, if a project is postponed by 2 weeks per example, a PM has to change the dates of all the tasks instead of the date of a few key ones.
### Actual behaviour

The start date of task 2 doesn't change, which means it would start before its parent task is even started.

**Comment by AgatonSax** [comment]
+1

**Comment by magicvince** [comment]
+1

**Comment by mkauzlar** [comment]
+1

**Comment by jarod80** [comment]
+1

**Comment by j0xyz** [comment]
thats would be a great feature

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
