### ISSUE TITLE
CSV examples

### ISSUE THREAD

**Issue by AgatonSax** [kanboard/kanboard#2192]
On the import page there is a link to download CSV template. It would benefit from a few examples (generally).

Specifically, I am trying to import a closed task - what is the syntax for that?

Application version: 1.0.27
PHP version: 5.5.9-1ubuntu4.14
PHP SAPI: apache2handler
OS version: Linux 3.13.0-66-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by fguillot** [comment]
The last column is "Closed", put `1` or `t` or `y`.
