### ISSUE TITLE
Request to disable keyboard shortcuts

### ISSUE THREAD

**Issue by robjurd** [kanboard/kanboard#2194]
### Expected behaviour

Would like the option of turning them off as they interfere in entering text from mobile/tablet devices.
### Actual behaviour

When adding/editing comments, if an existing key shortcut is matched, the cursor jumps, often to the beginning of the previous word.
### Steps to reproduce
1. Use a mobile/tablet device
2. Start typing a comment on a task
3. Use key combinations such as "a " (no quotes)
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.27
PHP version: 5.5.9-1ubuntu4.16
PHP SAPI: apache2handler
OS version: Linux 3.13.0-85-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36

**Comment by robjurd** [comment]
Just to clarify, the goal here is to be able to add text from my mobile without the cursor jumping all over the place.  If you can do that and retain shortcuts and formatting then great :)

**Comment by fguillot** [comment]
What smartphone are you using?

**Comment by robjurd** [comment]
Currently Samsung galaxy s3 soon to be s5. Using chrome too.

I see this on my tablet too (Samsung galaxy note 2014)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
