### ISSUE TITLE
Email subject to show update in task status

### ISSUE THREAD

**Issue by foldedpaper** [kanboard/kanboard#220]
With the email feature enabled, when a user updates a task, kanboard generates an email with this subject:

"[Project name][Task updated] Name of task (# of task)"

It would be nice if the email reflected what sort of update was performed on the task. e.g. if the task is moved to a column on the board titled "Done", the subject line would say:

"[Project name][Task Done] Name of task (# of task)"

This would help make email updates more informative as an update feed.

**Comment by jesuslokoo** [comment]
Please, I need help with this subject.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
