### ISSUE TITLE
See "My Tasks" first in  overview view rather than "My Projects"

### ISSUE THREAD

**Issue by GaspardZeBear** [kanboard/kanboard#2204]

**Comment by levlaz** [comment]
@fguillot should this be the new default, or should it be configurable?

**Comment by GaspardZeBear** [comment]
Hi,

Sorry for late answer (holidays !).


My use case is as follow :

- I manage a team with many small parallel projects : I act as a task planner

- Everyone in the team can see all the projects, because he potentially can have things to do (specialist, backup ...)

- With "Projects view" first, people just see a long list of projects : see their tasks first is more comfortable for they daily job


I suggest this  to be configurable, because I guess other people don't use kanboard this way.


In fact, I had a look at the code, and did it (simple, but hard-coded : not good enough to be given)


Regards



________________________________
De : Lev Lazinskiy <notifications@github.com>
Envoyé : mardi 7 juin 2016 05:18
À : fguillot/kanboard
Cc : GaspardZeBear; Author
Objet : Re: [fguillot/kanboard] See "My Tasks" first in overview view rather than "My Projects" (#2204)


@fguillot<https://github.com/fguillot> should this be the new default, or should it be configurable?

-

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
