### ISSUE TITLE
Request: Show task column in my tasks table on dasboard

### ISSUE THREAD

**Issue by danielraknes** [kanboard/kanboard#2206]
On dasboard there is a table showing my tasks.

Existing columns:
| ID | Project | Task | Time | Deadline |

Can you also make a column that shows column for the task?

In that case we can see if the task is "Done" or if it is "In progress".  

Regards
Daniel

**Comment by seancarson** [comment]
+1

**Comment by fguillot** [comment]
You can see the column on the dashboard now.
