### ISSUE TITLE
User session not being refreshed when updated by a different user

### ISSUE THREAD

**Issue by nhowell** [kanboard/kanboard#2208]
### Expected behaviour

When a user's profile is modified by another user, for example to change their role from Administrator to Manager, it should refresh the modified user's session so that it uses the updated role, etc.
### Actual behaviour

The modified user still has its old user session, and therefore its old roles, etc. That means even though the user may no longer be an Administrator, they still have access to Administrator stuff.
### Steps to reproduce
1. Log into two different users simultaneously (one browser each, or use Private/Incognito). At least one needs to be an Administrator.
2. With the Administrator user, change the role of the other user.
3. Switch to your browser that has the other user logged in.
4. Notice that the other user's access is still being determined by its old role instead of the new one. (Other stuff like the user's name in the top right is affected, too.) So now, until the other user logs off, they maintain their old role. This is especially dangerous when the Administrator wanted to downgrade the other user's role.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: v1.0.28
- Database type and version: n/a
- PHP version: 5.6.21
- OS: n/a
- Browser: n/a

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
