### ISSUE TITLE
Tasks view and tasks access

### ISSUE THREAD

**Issue by diegospano** [kanboard/kanboard#2212]
Hi. I have very little experience using Kanboard and I have two questions:

1- Is there any way that a user can only see the tasks assigned to him in the board?
2- Is there any way that only the assigned user change a task?. I mean, user-A can only move his taks to another column or close the task.

Thanks a lot

Diego

**Comment by fguillot** [comment]
1. Yes, by using the filter in the search box, for example `assignee:me`
2. No, all project members can move tasks on the board

**Comment by erpnedir** [comment]
Hi, about question 1, can we set the project as the filter assigneee:me as default and cannot be deleted ?
BW.

**Comment by fguillot** [comment]
@erpnedir this feature doesn't exists at the moment.
