### ISSUE TITLE
Toolbar missing from comment entry

### ISSUE THREAD

**Issue by robjurd** [kanboard/kanboard#2214]
### Expected behaviour

Toolbar should be visible when adding a comment to a task.  Editing the comment, shows the toolbar
### Actual behaviour

No toolbar is visible
### Steps to reproduce
1. Open a task
2. Add a Comment
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.27
PHP version: 5.5.9-1ubuntu4.16
PHP SAPI: apache2handler
OS version: Linux 3.13.0-86-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36

**Comment by badmojo76** [comment]
Hey robjurd - 

Not sure if you noticed, but if you open the task then click "Add Comment" on the left side menu (in 1.0.28), you have the toolbar available.

**Comment by robjurd** [comment]
That's correct, it's the add comment box at the bottom of the task thread where it's missing.  I would rarely use the "Add Comment" link on the left side menu due to the length of some of the threads it would be a pain to scroll up just to add a formatted comment.

**Comment by fguillot** [comment]
The toolbar is everywhere now in v1.0.35
