### ISSUE TITLE
Calendar is not showing tasks if Due Date is not set.

### ISSUE THREAD

**Issue by badmojo76** [kanboard/kanboard#2215]
### Expected behaviour

After a task has been started, either manually via "Set Start Date" button, or via Automatic Actions, the task should appear in the Calendar view, with the end of the task showing as the current date/time if there is no Due Date set.  (or greater value of Due Date/Current Time).  
### Actual behaviour

If a task does NOT have a Due Date, and it is Started via Set Start Date or Automatic Action to update start date, the task does not appear in the calendar view at all, even after waiting for a period of time.  The only way that it seems to appear is if there is a Due Date explicitly set.  
### Steps to reproduce
1. Create Task - Do NOT set Due Date
2. Set Start Date
3.  View Calendar (status:*)
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

```
Application version: 1.0.28
PHP version: 5.4.16
PHP SAPI: apache2handler
OS version: Linux 3.10.0-327.10.1.el7.x86_64
Database driver: sqlite
Database version: 3.7.17
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0
```

**Comment by fguillot** [comment]
Tickets related to the calendar should be posted to the calendar plugin bug tracker: https://github.com/kanboard/plugin-calendar/issues

Thank you
