### ISSUE TITLE
Two markdown on one template

### ISSUE THREAD

**Issue by madibacsi** [kanboard/kanboard#2217]
### Expected behaviour

I created a new field on mysql table "task" and wanted to put another editor area for the new field (description is default, i have extended with solution)
Put (extend with) another markdown wysiwyg editor into template (for example: create task)
### Actual behaviour

Only the last editor is showed correctly
### Steps to reproduce
1. Edit template, copy-paste description markdown in(to) form
2. Save and check the result
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.28

Thx

**Comment by fguillot** [comment]
The Javascript code have to be modified to make it work.
