### ISSUE TITLE
Ability to choose language of tasks export.

### ISSUE THREAD

**Issue by crabnky** [kanboard/kanboard#2219]
### Expected behaviour

I want to be able to select the language of the tasks export, independent of the application settings.
My idea is to have a dropdown on the screen with date range selection.
### Actual behaviour

Tasks are exported in the language set in the application settings.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
