### ISSUE TITLE
task dependencies

### ISSUE THREAD

**Issue by hebertallan** [kanboard/kanboard#2220]
Hi. Is there a way to relate task and make dependencie between them? I found the Internal Links, but even if I relate one task to another it doent automatcally change the start date.

What I want to do is as below:

task#1 Start Date today - Time estimated  24h
task#2 Start Date today - Time estimated  24h. 
But task#2 is dependent to task#1 so in gannt view task#2 will be automatically moved to one day after.

Same as project softwares do.

Is there this feature in kanboard?

Tkanks!!!

**Comment by seancarson** [comment]
+1

**Comment by fguillot** [comment]
This feature is not yet available.

**Comment by hebertallan** [comment]
Ok. Thanks!

Em seg, 16 de mai de 2016 às 22:40, Frédéric Guillot <
notifications@github.com> escreveu:

**Comment by dedesite** [comment]
+1 It'll be really great to have this feature. At the moment, the gantt view is almost useless without task dependencies. I'm a fullstack developer, maybe I could help getting this feature quicker, can you give me some hint where to look and what to do. I don't have a lot of time but if this is an easy task I'm your men :).

**Comment by oliviermaridat** [comment]
@dedesite This is not perfect (yet ;-D), but there is a [Milestone plugin](https://kanboard.net/plugin/milestone), which does not change the start/due dates of tasks, but use internal links to display more properly the Gantt chart.

Help and comments are welcome!

**Comment by dedesite** [comment]
@oliviermaridat Thank you for pointing me the plugin. Unfortunately, I do not host my kanboard project for the moment so I can't use this plugin but it seems interesting.

**Comment by oliviermaridat** [comment]
I suppose you must use the great Framaboard service? Yep, unfortunately it does not support plugins... Is it a prerequisite for you or your company?

**Comment by dedesite** [comment]
Yes :). Honestly it is for a private home construction project where task dependency is really important because depending if some task take some time or not, the construction will be able or not this summer. It's not a big issue, I can update start and en time manually. But if would have been cool if it was automatic :).

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
