### ISSUE TITLE
Ability to Set Default Filters per Board

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#2222]
Create option under settings that allows the board admin to set the default filter in a board.  

It is currently defaulted to status:open.  

A more advance option down the road may be the ability to lock the board to the default filter. Basically grey out the filter option for non project manager users.   

These features would allow Kanboard to be more easily used in various use cases such as helpdesk, or even bug reporting.  **creator:me**  for instance is a very good one and if it was defaulted and locked would make kanboard an excellent helpdesk system.  Of course after you created all the user accounts as local or remote users  lol.  

Thank you for writing Kanboard.

**Comment by seancarson** [comment]
Also, if it makes more since to set it globally a good location to place this feature maybe Settings > Project settings.  this is where all the other global project settings exist.

Thanks

**Comment by LordFPL** [comment]
+1 :)

**Comment by erpnedir** [comment]
If the default filters can be defined **per board per user role**, and we have the option **to lock the filter** it would solve lots of my restriction and reporting purposes. 
+1 for this feature request

**Comment by ruihildt** [comment]
Also needed here. :)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
