### ISSUE TITLE
Ability to merge tasks

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#2223]
Create an option per task that allows project members and manages to merge a task with another.  

Phase 2 could be to allow 1 to many merging.  

This would be a good feature that would save users the time of having to copy add then remove tasks.  

Thanks

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
