### ISSUE TITLE
Ability to add checklists to an issue

### ISSUE THREAD

**Issue by rr40** [kanboard/kanboard#2225]
- Add a checklist to an issue
- Complete checklist
- Track checklist completion status (some kind of a percentage line)
- Save checklists for future use in other issues

**Comment by NinjaPewPew** [comment]
:+1:

**Comment by ptman** [comment]
This would be a very nice lightweight alternative to subtasks. Maybe even a simple syntax such as:

    [] foo
    [x] bar

**Comment by anayrat** [comment]
:+1: like https://help.github.com/articles/basic-writing-and-formatting-syntax/#task-lists

**Comment by fguillot** [comment]
Subtasks are pretty much the same as checklists.
