### ISSUE TITLE
Add ability to sort projects in Project Management -> Projects Gantt Chart 

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#2228]
Hello, 

If possible under Project Management -> Projects Gantt Chart could you add the ability to sort projects like in the other views such as Dashboard -> My Projects or Project Management -> Projects views.  In both of these views there is a projects column that when clicked on allows you to sort alphabetically.  This would be extremely useful in the Projects Gantt Chart because it would allow you to view all your relevant  projects together and show the sequence projects in a more gathered view.  

In my case my Kanboard includes both board names that represent projects(Project_CRM Upgrade, Project_Sharepoint Role Out, etc) and ongoing processes (procurement, support, sales, etc).  Based on how the Projects Gantt Chart currently works it is not entirely useful when wanting to show project  interdependency and flow over time via start and end dates.  The interdependency could by shown through renaming the projects/boards with numbers(1_Project_CRM Upgrade, 2_Project_Sharepoint Role Out, etc)  as long as sorting is available.  

The Project Gantt Chart is a good feature but is missing a feature which would make it more functional.  

Thank You

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
