### ISSUE TITLE
 Improve the main page (dashboard)

### ISSUE THREAD

**Issue by hozelock** [kanboard/kanboard#2229]
### Question

I just downloaded Kanboard to a friend. I find this interesting application, but there is one thing I have a problem.

In fact, when I go on the main page, I am redirected to the dashboard ... with the following information : My projects / My Tasks / My subtasks

However, it lacks one thing ... at the table My Tasks should specify the positioning of the task in question in the table ... for more details (see attachment). The best would be to have the ability to modify the table as needed, directly from the application.

![ka](https://cloud.githubusercontent.com/assets/16597592/15320283/f3c3bfd2-1c2f-11e6-937a-318186fc4411.jpg)

I also think it would be useful to review the display of this page ... now it appears as follows:
- My projects
- My tasks
- My subtasks

Each section being separated from each other. Why not split by projects and tasks and sub tasks ... you would have something like:

![capture d ecran 2016-05-17 a 12 52 43 2](https://cloud.githubusercontent.com/assets/16597592/15320302/0ddfd018-1c30-11e6-8699-d26d1eb33adb.png)
### Configuration
- Application version: 1.0.28
- PHP version: 5.6.10
- PHP SAPI: apache2handler
- OS version: Darwin 15.4.0
- Database driver: sqlite
- Database version: 3.8.10.2
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by Chaosmeister** [comment]
:+1:

**Comment by marcolefo** [comment]
I really would like to have this feature too. Thanks.

**Comment by fguillot** [comment]
Actually, the dashboard is already splited by projects in the latest versions of KB.
