### ISSUE TITLE
option "turn off avatars"

### ISSUE THREAD

**Issue by vova-deep** [kanboard/kanboard#2231]
Please add the option that allow to turn off avatars and show the user name like at version before 1.0.26

**Comment by BlueTeck** [comment]
see #2062

**Comment by fguillot** [comment]
Why? there are so many people who asked to have avatars... Making everything configurable increase the complexity of the software.

**Comment by vova-deep** [comment]
Avatars on with the tasks of the cards are very small, and many of those who actively use the KB say that without avatars was convenient.

**Comment by vova-deep** [comment]
If you make avatars included in the default plug-in , it will only add Kanboard elegance. 
Also, at least a few people who have long enjoyed Kanboard will be happy.

**Comment by erpnedir** [comment]
I vote up for a configuration for this feature. When there are lots of people using the boards, or managers do not recognize the members so good, names instead of initials or avatars would be better.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I cannot make everything configurable.

Thank you for your understanding
