### ISSUE TITLE
Force user to use two-factor authentication

### ISSUE THREAD

**Issue by Kolesar** [kanboard/kanboard#2232]
How can I as administrator push users to use two-factor authentication?

**Comment by Chaosmeister** [comment]
I don't think that is possible at the moment.
As admin you can only see if a use has activated t-f-auth in the UsersManagement table and notify them manually.
This may be realizeable through a plugin thoug.

**Comment by fguillot** [comment]
At the moment, there is nothing that enforce people to activate 2FA.

It's not very hard to develop especially with the new Middleware system in master. The check can be made at login time. If the user do not have 2FA, redirect the user to the 2FA config page.
