### ISSUE TITLE
Postmark 1.0.2 Plugin not working with Kanboard 1.0.28

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#2233]
Installing the postmark plugin in the Kanboard 1.0.28 renders kanborad unavailable.  All we requeust to the system yeild 500 error.  page isnt working error.  

### Steps to reproduce

1. cd /var/www/html/kanboard/plugins
2. sudo wget https://github.com/kanboard/plugin-postmark/releases/download/v1.0.2/Postmark-1.0.2.zip
3. sudo unzip Postmark-1.0.2.zip
4. sudo rm Postmark-1.0.2.zip

### Configuration

Application version: 1.0.28
PHP version: 5.5.9-1ubuntu4.16
PHP SAPI: apache2handler
OS version: Linux 3.13.0-86-generic
Database driver: postgres
Database version: 9.3.12
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by seancarson** [comment]
Installed Plugins.  

Name	Version
Sendgrid	1.0.3
Slack	1.0.3
Timetable	1.0.7
Subtask Forecast	1.0.1
Budget Planning	1.0.7

**Comment by fguillot** [comment]
Can you get the exact error message from your Apache logs? Thanks
