### ISSUE TITLE
[Improvements] Bulk sub-task creation

### ISSUE THREAD

**Issue by orlov0562** [kanboard/kanboard#2235]
Hi there,

It will be very cool if we can create more than one sub-task from "Add a sub-task" window at once.

**Problem:** 
I have 40 different tasks, but it should have similar sub-tasks. And this creation one-by-one is very painful now.

**I suggest next:**

1) In "Add a sub-task" window, right from "Title" input add [+] btn

2) When we press this btn, "Title" text **input** replaced with **textarea** input, with same name attribute. We also can change btn to [-] to have opportunity to return to standard input

3) Append to controller, next functionality: if **$title** variable contains new lines (\n) we explode titles by this character and do bulk append of sub-tasks that we get after explode. If we have not new lines (\n) we use old way single creation.

So, I think it should be not hard to implement, keep current functionality and get rid of pain.

I have found one more related task: [#1939 Import bulk subtasks from CSV](https://github.com/fguillot/kanboard/issues/1939) , but I decided not to mix them

**Comment by orlov0562** [comment]
Example:

![subtask-example](https://cloud.githubusercontent.com/assets/1763904/15359403/d1d5f876-1d11-11e6-9431-b5639ae5080d.png)

**Comment by eltonps** [comment]
I think this is a nice improvement too.

**Comment by SergiArias** [comment]
yeah, super useful if implemented :)

**Comment by fguillot** [comment]
Bulk subtask creation is now available in the development branch.
