### ISSUE TITLE
[Feature Request] Workload calculation on Gantt chart view

### ISSUE THREAD

**Issue by Sn-L** [kanboard/kanboard#2237]
### Expected behaviour

Is it possible to use the estimated time for a task for a workload management ?
It's possible to set-up the working time in a day, the working time in a week, the time a task costs, a start date, a due date, but there's not link bteween all these datas.

Multi-tasking doesn't exactly matches the kanban spirit, but a gantt chart per assignee with a load average on each day would be great to anticipate overload peaks.

As an example 
- user John work 8 hours a day, 5 days a week.
- 01/01 is a Monday
- Task A : time : 40h, start date : 01/01, end date : 10/01, average load : 40h/(8d*8h)=0.625h/d
- Task B : time : 48h, start date : 04/01, end date 17/01, average load : 48h/(10d*8h)=0.6h/d
- Task C : time : 12h, start time : 12/01, end date : 19/01, average load : 12h/(6d*8h)=0.25h/d
- worload : 
  - 01/01 to 03/01 : 62,5%
  - 04/04 to 10/01 : 122,5%
  - 11/01 to 11/01 : 60%
  - 12/01 to 17/01 : 85%
    -> 18/01 to 19/01 : 25%

This would be very usefull to manage a capacity planning, and prevent delay by adjusting start/due date or reassigning tasks a more balanced way between project contributors.

The same feature could be adapted on the project gantt chart to anticipate working capacity needs, especially when contributors are shared over multiple projects.

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding

**Comment by Sn-L** [comment]
Dear Frédéric Guillot,

The email sent to github@divers.tk with subject
"Re: [kanboard/kanboard] [Feature Request] Workload calculation on"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to github@divers.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
