### ISSUE TITLE
[Feature Request] Exports for a user activities

### ISSUE THREAD

**Issue by Sn-L** [kanboard/kanboard#2238]
I'd like to be able to export tasks/subtasks/etc (same data as the projects exports) including all projects a user belongs to.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding

**Comment by Sn-L** [comment]
Dear fguillot,

The email sent to github@divers.tk with subject
"Re: [kanboard/kanboard] [Feature Request] Exports for a user"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to github@divers.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
