### ISSUE TITLE
Two-way integration with Github?

### ISSUE THREAD

**Issue by brylie** [kanboard/kanboard#2241]
the website mentions that Kanboard can be integrated with Github. However, the Github webhooks module seems to be one-way, meaning Github only pushes wvents to Kanboard. Is it planned, or currently possible, for Kanboard to push events back to Github? 

E.g. when commenting on a Kanboard card, the comment would appear on the Github issue. We are practicing an open development methodology and would like to keep our kanboard issues open and synchronized.

**Comment by fguillot** [comment]
See https://github.com/kanboard/plugin-gitlab-webhook/issues/5

**Comment by brylie** [comment]
@fguillot in fairness, this is not strictly a duplicate. There may need to be separate code to integrate Gitlab and Github, as their API and data models might differ.

**Comment by fguillot** [comment]
Sorry by my bad, I read Gitlab instead of Github. This is the same scenario, the Github API have to be implemented in the plugin.

**Comment by brylie** [comment]
All good. :-)

**Comment by fguillot** [comment]
Please, move your ticket to the Github plugin bug tracker: https://github.com/kanboard/plugin-github-webhook/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
