### ISSUE TITLE
Clicking on Sign In button after entering User Name and Password leadind back to the Login Sceen

### ISSUE THREAD

**Issue by ragith** [kanboard/kanboard#2243]
### Expected behaviour

Clicking on Sign In button after entering User Name and Password should take to the home screen for Kanboard
### Actual behaviour

Clicking on Sign In button after entering User Name and Password leadind back to the Login Sceen again in Google Chrome and Internet Explorer 11. In Firefox it working perfect !!! .
### Steps to reproduce

1.
2.
3.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

```
Application version: 1.0.28
PHP version: 7.0.5
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.2
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
```

**Comment by jtourt** [comment]
I've seen the same thing.  The issue is not consistent though, occassionally it redirects fine, but many times it redirect back to login page after logging in.  I haven't spent any time trying to figure out the problem; I just manually enter in the board url after being redirected back to the login page and carry on with my day.

**Comment by fguillot** [comment]
Are you using IIS on Windows?

**Comment by jtourt** [comment]
Yes.

**Comment by NinjaPewPew** [comment]
We run our Kanboard preview version on the same server, just in a diffrent directory. If I'm logged in the production Kanboard (I use "remember me") and additionaly try to login to the preview Kanboard, I have the exact same issue. 

Using a wrong username/password shows the error like it should, but using the right credentilas just redirects back to the login screen (without any error).

I assumed that it has something to do with the remember me cookie and the session id that is stored in there.

**Comment by levlaz** [comment]
Just to confirm are you running on a subdom (Dev.kan.com and prod.kan.com) or a subdirectory? Kan.com/Dev and kan.com/prod

**Comment by VijayPNair** [comment]
I am also facing this issue, The same application works fine when I use it in intranet, however when I try to access the application from internet it just keeps redirecting to the home page. The debug log created in both scenarios are same, there is no specific error that you can see, the log shows that the user is authenticated .

PS: I have deployed the application to subdirectory.

**Comment by pduchene** [comment]
Same problem here.

Windows Server 2008 R2
IIS 7
PHP 5.3.28

Works fine with Firefox, but not with Google Chrome or Internet Explorer 11.

Pierre

**Comment by fguillot** [comment]
I was not able to reproduce your issue, so try again with the latest version of Kanboard (1.0.38). If the issue still there, reopen this ticket with all the relevant information to be able to found the problem. 

Thank you.
