### ISSUE TITLE
Allow edit the date of start / stop in subtasks.

### ISSUE THREAD

**Issue by menegrete** [kanboard/kanboard#2246]
### Expected behaviour

If by mistake an user does not Stop the subtask time tracking, the  total hours are wrong. Currently it is possible to edit the total time in the "Time spent" field but we realized that doing it does not modify the Start Date/Stop Date of each subtask.

It could be implemented something like this (maybe in the activity log):

![image](https://cloud.githubusercontent.com/assets/13860947/15393376/53ddbd7c-1da3-11e6-80f2-b520d0dc38a9.png)
### Configuration
- Kanboard version: 1.0.26

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
