### ISSUE TITLE
In automatic action "Move to task to another column" the Start date is overwritten when changing columns

### ISSUE THREAD

**Issue by menegrete** [kanboard/kanboard#2247]
### Expected behaviour

An automatic action to set the Start Date when moving the task to "WIP" was generated, but when moving the task to another column and then return it to "WIP" the Start Date gets modified again.

Would be nice to introduce an option (or another action) to set the start date only if it is not set.
### Configuration
- Kanboard version: 1.0.26

**Comment by menegrete** [comment]
I changed the title because it wasn't in concordance with the expected behaviour description

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
