### ISSUE TITLE
Filter by "My Tasks" or Filter by "User" No Longer Shows Tasks with Sub-tasks Assigned

### ISSUE THREAD

**Issue by jg-jhu-ds** [kanboard/kanboard#2248]
### Expected behaviour

When selecting the "My Tasks" filter or the "User" filter, the filters should return tasks for which the user is assigned **sub-tasks** in addition to tasks for which the user is the task owner.

### Actual behaviour

Bug: When selecting the "My Tasks" filter or the "User" filter, the filters do not return tasks for which the user is assigned sub-tasks.  It only returns tasks for which the user is the task owner.

### Steps to reproduce

1. Create a task and assign it to user A.
2. Create a sub-task and assign the sub-task to user B.
3. Select the User filter and select user B.  The newly created task does not show up.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Application version: 1.0.28
- PHP version: 5.4.16
- PHP SAPI: apache2handler
- OS version: Linux 3.10.0-327.4.4.el7.x86_64
- Database driver: sqlite
- Database version: 3.7.17
- Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36

**Comment by SchmilK** [comment]
Confirmed on 1.0.28 by a co-worker and myself. 
 
Also filtering 
**assignee:"User Name"** 
does not show subtasks.

Attempting to combine 
**subtask:assignee:"User Name" assignee:"User Name"** 
Returns no results.

**Comment by supportreq** [comment]
confirmed facing the same issue.. cannot list subtask in filter when the assignee is different..

please advice..

**Comment by supportreq** [comment]
@fguillot need any screenshot for the same? please advice..

**Comment by supportreq** [comment]
@fguillot any luck??

**Comment by fguillot** [comment]
- You have to use the attribute `subtask:assignee:`, for example: `subtask:assignee:"My user B"`
- This query `assignee:"My user B"` will return tasks assigned to User B
- This query `assignee:"My user B" subtask:assignee:"My user B"` will return only tasks assigned to User B **AND** tasks with subtasks assigned to User B

**Comment by mnstrmnch** [comment]
Is there no way to view tasks and subtasks assigned to a particular user simultaneously then?

**Comment by jg-jhu-ds** [comment]
It would be great to have an easy way to view tasks **AND** subtasks for a user.  Currently I do not believe there is a way to view a user's tasks and subtasks in one filter.  This functionality was available prior to 1.0.28.  This feature was incorporated by @Lesstat on Jul 11, 2015.  See: [#1012](https://github.com/kanboard/kanboard/pull/1012/commits/5101eaa8060ce3c75a81a26f6e47aae40e3d4ac3).  Can that code be reintroduced into the current build?
