### ISSUE TITLE
"Days in this column" value should not be changed when a task moved in the same column

### ISSUE THREAD

**Issue by hakanoo** [kanboard/kanboard#2262]
### Expected behaviour

"Days in this column" value should not be changed when a task moved to down or up in the same column.

### Actual behaviour

I have 2 tasks in WIP column. After I move first task under of second task, "days in this column" value becomes < 15m.

### Steps to reproduce

1. Create 2 tasks in WIP column
2. Wait 1 hour.
3. Change order of tasks. 

### Configuration

◾ Application version: 1.0.28 
◾ PHP version: 7.0.5 
◾ PHP SAPI: apache2handler 
◾ OS version: Windows NT 6.3 
◾ Database driver: postgres 
◾ Database version: 9.5.2 
◾ Browser: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; GWX:MANAGED)

**Comment by kerro** [comment]
In this case, not to update the _date_moved_ column in the tasks table is possible, but is it an accepted behavior ?

**Comment by fguillot** [comment]
In KB 1.0.34, the moved date doesn't change anymore if the task is moved in the same column.
