### ISSUE TITLE
Ability to Select Destination Column and Catagory in AutoAction - move the task to another project

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#2264]
Hello, 

If possible I would like to request a addition to the Automatic Action - Move the task to another project.  
1. Add Ability to Select Destination Project column (Project_Column)
2. Add Ability to Select Destination Project Category (Project_Category) 

Thank You  
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.27
PHP version: 5.5.9-1ubuntu4.16
PHP SAPI: apache2handler
OS version: Linux 3.13.0-71-generic
Database driver: postgres
Database version: 9.3.12
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by levlaz** [comment]
What type of event(s) would you like to see trigger this automatic action?

**Comment by seancarson** [comment]
You already have Move a task to another column and closing a task.  This is sufficent, but if possible category or color  triggers would be nice.  

My main ask though is the ability to place a event triggered task in a specific column and assign a specific category to it as well.  

Thanks

**Comment by jerrygacket** [comment]
Need the same: Ability to Select Destination Project column (Project_Column)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
