### ISSUE TITLE
Calender View in Project Management Module(Projects)

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#2265]
Hello, if possible I would like to request that Calendar View be added to Projects as an Option in addition to Projects Gantt Chart.  

Thanks
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.27
PHP version: 5.5.9-1ubuntu4.16
PHP SAPI: apache2handler
OS version: Linux 3.13.0-71-generic
Database driver: postgres
Database version: 9.3.12
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by fguillot** [comment]
Tickets related to the calendar should be posted to the calendar plugin bug tracker: https://github.com/kanboard/plugin-calendar/issues

Thank you
