### ISSUE TITLE
Cannot move a Task from a mobile application

### ISSUE THREAD

**Issue by faraj1978** [kanboard/kanboard#2269]
### Expected behaviour

Kanboard should provide normal way to move tickets from column to column

### Actual behaviour

I can only move by drag and drop currently throw normal browser

### Steps to reproduce

1.add the feature in edit Task
2.Field should be available for me to change the column.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.28
PHP version: 5.4.38
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-042stab112.15
Database driver: mysql
Database version: 5.5.42-cll
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by fguillot** [comment]
This is available now.
