### ISSUE TITLE
left right scroll

### ISSUE THREAD

**Issue by jquinn36** [kanboard/kanboard#2273]
### Expected behaviour

Scroll left and right without having to scroll to bottom of dashboard.
### Actual behaviour

Have to scroll to very bottom of dashboard to left right scroll.  Our Kanboard has 3 swimlanes and around 20 user stories .  We also have many columns in process (specification, specification done, WIP, WIP done, Testing, Testing done, Code check, Live date).  User are finding it hard to navigate especially in meetings.
### Steps to reproduce

Have to have board with larger process and many user stories in at least one.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.28
- Database type and version: SQLite
- PHP version: 5.6.15
- OS: windows 7
- Browser: Firefox, chrome and IE 11

**Comment by REJack** [comment]
I see also the UI Bug, 
but as workaround you can use the middle button (press scroll wheel) then you can scroll left/right with your mouse and you need not to see/use the scroll bar.

**Comment by jquinn36** [comment]
Thanks Jack - works on Chrome but not firefox and IE (most of our org is IE11).  That will be fine for me for now though cheers.  A lot of our desktops are locked down though.

**Comment by REJack** [comment]
No problem jquinn36,

did you tested Firefox and Chrome on the same PC? It should work everywhere its a windows feature ^^, I'm use FF and it work by me. 

Note: some mices with extra software changes the default keybinding of the middle button. 

Von meinem iPhone gesendet

**Comment by funfox1** [comment]
Get the same problem. Even if i can use left/right arrow to move inside the board, the lack of a left/right scrollbar makes it feel very weird in term of user experience.

Got a kanboard of 3 swimlanes too, with more or less 15 columns, and every of my users asked me once how to get to the last columns.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
