### ISSUE TITLE
Adding comments (keyboard shortcuts in Markdown editor)

### ISSUE THREAD

**Issue by adi76** [kanboard/kanboard#2274]
### Expected behaviour

When adding / editing comments when I press Alt+L, the editor start to create numbered list. I'm from Poland, and for me Alt+L should give a letter "ł".
### Steps to reproduce
1. 
   2.
   3.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

```
Wersja aplikacji: 1.0.28
Wersja PHP: 5.3.10
PHP SAPI: apache2handler
Wersja OS: Windows NT 5.2
Silnik bazy danych: mysql
Wersja bazy danych: 5.6.27-log
Przeglądarka Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0
```

**Comment by adi76** [comment]
As I can see, some change in configuration simplemde should make it work fine.

**Comment by adi76** [comment]
I just noticed that the same problem is with combination Alt+C. It should make letter "ć" instead of: ``

**Comment by adi76** [comment]
I downloaded Kanboard 1.0.32 and the bug I described still exists. Can you tell me when it could be modified.

**Comment by fguillot** [comment]
The Markdown editor have rewritten in the development branch. Those type of errors should not happen anymore.
