### ISSUE TITLE
Because i need date in time tracking

### ISSUE THREAD

**Issue by tornade69** [kanboard/kanboard#2282]
Hi,

I need to know when time tracking is log, so i improve database with 

> alter table subtask_time_tracking 
>   add column created datetime,
>  add column updated datetime;
> 
> delimiter //
> create trigger subtask_time_created before insert on subtask_time_tracking
>     for each row begin
>         SET new.created := now();
>         SET new.updated := now();
>     end;//
> 
> CREATE TRIGGER subtask_time_updated BEFORE UPDATE ON subtask_time_tracking
>     FOR EACH ROW BEGIN
>         SET new.updated := now();
>     END;//
> 
> delimiter ;

I prefer use this method because of mysql 5.6 or mysql 5.5 

Regards

**Comment by fguillot** [comment]
Closing this ticket due to inactivity and lack of interest by the community.
