### ISSUE TITLE
Analytics feature request: Custom periods for "average time spent into each column"

### ISSUE THREAD

**Issue by AgatonSax** [kanboard/kanboard#2286]
Present behavior (average for last 1000 tasks) is fine as default. Though It would be really nice to be able to set a custom period for average calculation.

Ultimately compare average for (i.e.) Q1 2015 and Q1 2016. Perhaps something like:
![image](https://cloud.githubusercontent.com/assets/5526928/15744809/7ceac90e-28ce-11e6-83b3-95900f1fb202.png)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
