### ISSUE TITLE
Unable to open the kanboard homepage

### ISSUE THREAD

**Issue by arun-16** [kanboard/kanboard#2287]
### Expected behaviour

I installed kanboard as per the instructions given on the website. But if I open the url "http://myurl/kanboard", it always says site unreachable

### Actual behaviour

 it always says site unreachable

### Steps to reproduce

1.
2.
3.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: Latest version as on today
- Database type and version:
- PHP version:
- OS: Centos 7.0
- Browser: Chrome

**Comment by NinjaPewPew** [comment]
Using `https://myurl/kanboard` always brings 403, but if I add a trailing backslash to it, the site is displayed right away. Not sure if you tried that already.

Can you post a screenshot from the error?
