### ISSUE TITLE
[FR]: change the creator

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#2293]
Sometimes I create a task in the name of someone else (a sponsor) and assign it to someone to work on it. This stops working communicationwise once an issue needs to be tested/approved by the sponsor. The reason is the strict notifications engine that only supports 2 parties (I know there's mention but it's pretty hidden for occasional users)
### Expected behaviour
- Change creator with pulldown like you change assignee.
- It still makes sense to keep the history (i.e. the creator of an issue therefore the label could change to 'sponsor' an still shows the creator)

**Comment by bdrayer** [comment]
It would be a great improvement, possibly as a plugin.

**Comment by boris-horner** [comment]
I use Kanboard myself, hosted on my own hardware, and advise my customers to use Kanboard for project management in the field of technical documentation. One difficulty in configuring Kanboard for such projects is that even though there seems to be an internal mechanism for handling custom metadata in key/value pairs for tasks, projects and IIRC users, it is not exposed, apart from a plugin that (sorry, no offense!) seems to be rather crude from a GUI integration point of view. 

There are several use cases where such a feature would be helpful in the type of projects in my environment, and one is the one described in this issue. That leads me to my point. I don't think it's a good idea to let users change the creator of a task, and if so, only with tight restrictions. Instead, a custom metadata GUI with typical data type fields (like text, dates, users), and the possibility to configure fields that always appear would solve this problem (and many, many others) in a cleaner and more flexible way.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
