### ISSUE TITLE
email address change when logging in via Google

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#2294]
### Expected behaviour

the set email address in the profile should persist even if you use a 3rd party login like Google

### Actual behaviour

after logging in via Google the set email address gets replaced with the Google email address

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Version: 1.0.28
PHP Version: 5.6.21-1~he.0
PHP SAPI: apache2handler
OS Version: Linux 2.6.18-prep-xenU-static-i686-he+12
Datenbanktreiber mysql
Datenbank Version: 5.5.47-37.7-log
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36

**Comment by fguillot** [comment]
This is the expected behaviour, see https://kanboard.net/plugin/google-auth section "Notes" at the bottom of the page.

**Comment by thob** [comment]
Ah, it doesn't happen with GH login though.
