### ISSUE TITLE
[FR] Kanbanflow.com has a pretty good user interface for task editing, something like that should be implemented

### ISSUE THREAD

**Issue by GeorgeFischhof** [kanboard/kanboard#2297]
Hi There,

[Feature request] Kanbanflow.com has a pretty good user interface for task editing, something like that should be implemented

movable windows, task elements are editable in the window (not by clicking on side menu)

BR,
George

**Comment by fguillot** [comment]
There are already a lot of requests to improve the user interface in this bug tracker. However, the goal of this software is not make a clone of Kanbanflow.
