### ISSUE TITLE
Scale time line in gantt view

### ISSUE THREAD

**Issue by mauriziodidomenico** [kanboard/kanboard#2310]
### Expected behaviour

To have the possibility to scale the time line (size of the day/month) in the GANTT View, to ensure the print out possibility.
### Actual behaviour

The view scale have a default value.
### Configuration

Application version: master
PHP version: 7.0.7
PHP SAPI: apache2handler
OS version: Linux 4.4.11-1-ARCH
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (X11; CrOS x86_64 
![bild 1](https://cloud.githubusercontent.com/assets/16655789/15862410/e20bcbee-2ccf-11e6-926a-39478fdf871c.png)

**Comment by adgu** [comment]
Maybe it could be implemented as a switch between daily view (current default view) and weekly view.
Something similar to instagantt:

WEEKLY:
![image](https://cloud.githubusercontent.com/assets/19857925/15965674/430f1628-2f17-11e6-9d35-3a711f853bc7.png)

DAILY:
![image](https://cloud.githubusercontent.com/assets/19857925/15965772/cf093032-2f17-11e6-9dc6-88924739867a.png)

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
