### ISSUE TITLE
Percentage Completed Of Task

### ISSUE THREAD

**Issue by aviadb** [kanboard/kanboard#2314]
It would be nice if an ongoing task can have a percentage progressbar or percentage of completeness label.

**Comment by levlaz** [comment]
This should already exist as long as a task has subtasks. 

![screenshot 2016-06-08 10 50 31](https://cloud.githubusercontent.com/assets/7981032/15904686/d8e4f440-2d66-11e6-9fd8-f67a4a68bd41.png)

Do you mean something else?

**Comment by aviadb** [comment]
I mean, changing percent competed per task, regardless to if task has subtasks or not.
percentage should be calculated according to assignee decision, not by remaining time to due date.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
