### ISSUE TITLE
Automatic action: Move To Another Column When Closed

### ISSUE THREAD

**Issue by aviadb** [kanboard/kanboard#2315]
It can be very useful if when closing a task, it would be automatically moved to another column.
As an example closing a task in column "Bugs" will move it to column "Fixed"

**Comment by skorvek** [comment]
This would be helpful- I have been training myself to instead move all completed items to the Done column, which has an associated automatic action to close the task.  However, it would be much easier to just close the task from the link on the task page. But that currently will keep it in my active task column, which is not ideal with some filters.

**Comment by fguillot** [comment]
This automatic action is now available in the development branch.
