### ISSUE TITLE
Mark certain items as "private" so they arent showed in a public link

### ISSUE THREAD

**Issue by Rydekull** [kanboard/kanboard#232]
It might be required for security sensitive issues. That shouldn't be seen by everyone.

**Comment by oparoz** [comment]
Now that we have groups, it would be a good feature to have

### Phase 1

* comment visibility -> select group
* changeable at any time
* different colour if visibility is not default

#### Impact

* none?

### Phase 2

* task visibility -> select group

#### Impact

* calendar
* Gantt chart
* sub-tasks
* internal links
* activity
* analytics
* exports

and probably more, so it's quite a large task...

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited.

Thank you for your understanding
