### ISSUE TITLE
docker image doesn't emails and doesn't return errors

### ISSUE THREAD

**Issue by lgibelli** [kanboard/kanboard#2326]
### Expected behaviour

When trying to 'recover the password', I should either receive an email with the reset link or an error
### Actual behaviour

No error is returned, no email is sent.
### Steps to reproduce
1. Start a kanboard container with "docker run -p 80:80 -d --name kanboard --restart=always -t kanboard/kanboard"
2. Login as admin, add a user
3. Reset the password for the new user
### Configuration

I'm running the official docker image from kanboard/kanboard with image id 4ec5fd421c32.

The easy way to fix this is to tell kanboard to call sendmail 'the busybox way', like this:

define('MAIL_TRANSPORT', 'sendmail');
define('MAIL_SENDMAIL_COMMAND', '/usr/sbin/sendmail -ti -S '. MAIL_SMTP_HOSTNAME);

The docker image comes with busybox and the sendmail shipped with busybox uses different options from the official sendmail.

A similar problem affects MAIL_TRANSPORT = mail.

Also I couldn't get kanboard to work with MAIL_TRANSPORT set to smtp, no idea why.

**Comment by Adaurg** [comment]
Same problem for me with emails. 
I tried to enable debug mode, like this :

// Enable/Disable debug
define('DEBUG', true);

// Available log drivers: syslog, stderr, stdout or file
define('LOG_DRIVER', 'file');

// Log filename if the log driver is "file"
define('LOG_FILE', __DIR__.DIRECTORY_SEPARATOR.'data'.DIRECTORY_SEPARATOR.'/data/debug.log');

But i can find the debug file...

Humm...
How we can relaod nginx config after a change in config.php ?

**Comment by lgibelli** [comment]
the brutal way: docker restart kanboard

**Comment by fguillot** [comment]
The easiest way to send emails with the docker image is to install a plugin like Mailgun/Sendgrid/Postmark or to configure the SMTP method by using a custom config file.

You can also extends the image to install ssmtp or or postfix to redirect mails to another smtp server.

**Comment by lgibelli** [comment]
@fguillot have you tested the SMTP method in the Docker image? It doesn't work for me.

Also the main issue here is that if emails fail to be sent, for whatever reason, there is no trace of that in the logs.

**Comment by Adaurg** [comment]
After using the brutal way to restart container ;) it's okey for me... Thanks for your help.

Here a part of my configure.php :

// E-mail address for the "From" header (notifications)
define('MAIL_FROM', 'kb.notification@blabla.fr');

// Mail transport available: "smtp", "sendmail", "mail" (PHP mail function), "postmark", "mailgun", "sendgrid"
define('MAIL_TRANSPORT', 'sendmail');

// SMTP configuration to use when the "smtp" transport is chosen
define('MAIL_SMTP_HOSTNAME', '192.168.100.07');
define('MAIL_SMTP_PORT', 25);
define('MAIL_SMTP_USERNAME', '');
define('MAIL_SMTP_PASSWORD', '');
define('MAIL_SMTP_ENCRYPTION', null); // Valid values are "null", "ssl" or "tls"

// Sendmail command to use when the transport is "sendmail"
define('MAIL_SENDMAIL_COMMAND', '/usr/sbin/sendmail -bs');

**Comment by mechanicjay** [comment]
I'm having similar issues.  No matter what I do, I cannot get emails to send from the docker container.

**Comment by fguillot** [comment]
You have to use the SMTP method, not sendmail.
