### ISSUE TITLE
Simplify CSS development process

### ISSUE THREAD

**Issue by megapctr** [kanboard/kanboard#2327]
Hi everyone! I noticed that kanboard does not use any tools that ease writing css, let's discuss that.

Writing vanilla css is perfectly fine, but it puts a lot of pressure on a developer:
> Is this class already in use?
> Do I need vendor prefixes?
> What is the value for 'error' color in this project?
> I'm afraid changing this class will break something

Luckily, there's more and more librares as well as guidelines which minimize those concerns

Let's take a look at
- sass
- sass-lint
- postcss and autoprefixer
### [Sass](http://sass-lang.com/guide)
:+1: Features like variables, imports, nesting and mixins make styling much easier, and in the same time your css is much more flexible. Need to increase font-size? :ballot_box_with_check:. Themes? :ballot_box_with_check: 

:+1: Sass syntax extends css syntax, so there's no need to modify source files at all.

:-1: The only migration cost is having to rename all css submodules to start with an underscore, so they can be imported in the root sass file.

### [sass-lint](https://github.com/sasstools/sass-lint)
:+1: Consistent code is always better. Even small things like properties kept in order or having property values normalized makes code easier to read, because there's less surprises to encounter. Sass-lint can also warn about duplicate and invalid properties or duplicate class names.

:-1: Applying it would be a long process, but not really intrusive. We can mark files to be ignored and enable rules one-by-one.

### [PostCSS](https://github.com/postcss/postcss) and [autoprefixer](https://github.com/postcss/autoprefixer)
:+1: Sass helps us write simpler code, postcss takes care of _shipping_ it, so to speak. Autoprefixer a plugin that adds vendor prefixes to your css so you don't have to. I didn't really explore other plugins, but there's many to choose from.

:-1: ¯\_(ツ)_/¯

All of these can be installed via npm and integrated into current gulp pipeline :tada:

**Comment by fguillot** [comment]
Why sass instead of less?

**Comment by megapctr** [comment]
Why less instead of sass? :smirk:

I suggested sass just beacuse it's what I've been using for few years now, and I didn't really have any problems. They're both pretty similar, although sass has a bigger community and is more popular. I haven't seen any css article/tutorial which uses less, but I've seen few that use sass.

**Comment by fguillot** [comment]
If you would like to contribute to the project and convert the existing vanilla CSS to SASS and integrate that into the gulp pipeline, I'm ok for it. Just try to not break stuff.

Thanks

**Comment by megapctr** [comment]
Cool. Any tips for preparing a development environment for kanboard?

**Comment by fguillot** [comment]
If you are using OSX, the only thing you need to install is probably nodejs/npm. PHP/Apache is already included with Mac OS. Otherwise nothing special, you just need php.
