### ISSUE TITLE
Permissions don't duplicate when creating new projects from another project.

### ISSUE THREAD

**Issue by hex45** [kanboard/kanboard#2329]
### Expected behaviour

Project permissions (for groups and users) should be duplicated when creating a new project and using "Create from another project" pull down.

### Actual behaviour

Only the project permissions for the user "me" are being duplicated.

### Steps to reproduce

1. Click on the link New project.
2. Name new project.
3. Select something from "Create from another project" list.
4. Select the Permissions, Tasks, etc. to duplicate.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

I need to check my work installation for these settings.

- Kanboard version: v1.0.29
- Database type and version: sqlite
- PHP version: 7.x
- OS: Lubuntu 16
- Browser: Firefox

**Comment by fguillot** [comment]
This issue is now fixed in the development branch. Thanks!
