### ISSUE TITLE
Feature request - changing trigger for task progress information in Gantt chart.

### ISSUE THREAD

**Issue by ghost** [kanboard/kanboard#2330]
I think it would be more beneficial to have the progress bar in gantt chart based on the number of completed subtasks instead of the position (column) in the keyboard.

Thanks.

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
