### ISSUE TITLE
Add global preference to remember Board settings

### ISSUE THREAD

**Issue by ngosang** [kanboard/kanboard#2332]
I have to select that option each time I log in:
![](https://i.imgur.com/OH3MjSt.png)
Please add an option to remember that for all boards:
![](https://i.imgur.com/rBZrTjM.png)

**Comment by Biniou180** [comment]
Some users of Framaboard are also interested by this feature.

An additional comment though: Is it better (easier?) to put this setting  in general preferences or in project preferences? (as it can be useful for a project with a lot of tasks, but painful with only a few tasks)

**Comment by ngosang** [comment]
@fguillot I think this is already implemented. Could you check and close?

**Comment by fguillot** [comment]
Yes, some of those settings are stored in the database now.
