### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by denisz1** [kanboard/kanboard#2335]
Similar apps have a functional demo with dummy data.

Does Kanboard have a demo site?

**Comment by BlueTeck** [comment]
There was a demo on http://demo.kanboard.net but I can't reach it at the moment.

**Comment by denisz1** [comment]
Me neither.

Also, I looked on the website but didn't find a prominent link anywhere (or maybe was not paying attention!)

**Comment by fguillot** [comment]
The demo have been removed and will be replaced later.

**Comment by denisz1** [comment]
Will be useful for new users.

I needed to install it to see if I like it... (I did!) :smile:

**Comment by ThomasFRW** [comment]
Hello, do you have any news of the demo ?
When will it be available again?
Your software is awesome :)
Best Regards

**Comment by Imbasaur** [comment]
Any update on this?

**Comment by fguillot** [comment]
You can signup for a free trial of kanboard hosting: https://kanboard.net/hosting there are also other providers that offer Kanboard...

**Comment by sergeevabc** [comment]
>> You can signup for a free trial of kanboard hosting: https://kanboard.net/hosting
> Sorry, the page you are looking for could not be found.

**Comment by grokky1** [comment]
Anywhere I can see this app in action?

**Comment by carlos22** [comment]
I found a demo: https://www.softaculous.com/demos/Kanboard

**Comment by sergeevabc** [comment]
@carlos22, it seems the developer wanted to make it flexible, but it turned to be cumbersome.
