### ISSUE TITLE
If a subtask is converted to a task the subtasktime_tracking record(s) are deleted 

### ISSUE THREAD

**Issue by aweisshh** [kanboard/kanboard#2338]
### foreword ;)

I discovered (in the actual head-version) the the very cool function for
converting a subtask to a task. 
I think this is very helpful especially if you work on subtask that becomes
more complex, you convert it to a task and can add comments/subtask and
the like to it. 
I (and different companies i work(ed) for) have to track their efforts on every issue people are working on, so i use a lot the 'Subtask timetracking'.

This is not a real bug (i would call it an incomplete feature).
Maybe i overlooked something or there are other ideas ...
### Expected behaviour

If a subtask is converted to a task, the subtasktime_tracking record(s) 
should not get deleted, instead the should get assigned to the (new created) task.

**This could be done by:**
  Adding a column 'task_id' to the 'subtask_timetracking' 
  table (which thereafter may be renamed to 'timetracking' or so.)
 and leave the records at their place but with a 'task_id' assigned instead a 'subtask_id'
**or**
  Adding a table 'task_timetracking' and writing the record there.

Maybe there could be another column added to either solutions indicating a the type of of record like:  
-   Type=Worklog => duration someone really worked on that issue (user_id, date ....)
-   Type=Estimation => place to keep the estimated effort(s)
-   Type=SumEntered => for the input-field ('Hours spend') entered by the Project manager.
-   ...=>...

There is a already a request for a Task_time tracking.. this could be a first step towards that feature.
### Actual behaviour

If a Subtask is converted, the individual subtasktime_tracking record(s) get deleted. 
These records are the base of my project accounting. The only place the effort is summed 
up to is the 'time_spent' field in the task-table. 
No data left to calculate accounting/bills of/for a individual project member. 
### Steps to reproduce
1. do some timetracking on a subtask
2. convert subtask to a task.
3. look under 'My Profile | time tracking' or look in the database
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: HEAD-Version

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
