### ISSUE TITLE
New template hook - Email

### ISSUE THREAD

**Issue by nitr8** [kanboard/kanboard#2339]
Hi,

It would be nice to be able to have custom plugins be able to modify the email templates.

Please could we have some hooks added for example Template/notification/footer.php so we can customize our mail templates.

https://kanboard.net/documentation/plugin-hooks does not refer to any mail templates.

Thanks.

**Comment by fguillot** [comment]
I do not plan to add such feature. If you really need that, the best way is to contribute.
