### ISSUE TITLE
Cuttlefish and/or office 365

### ISSUE THREAD

**Issue by lordvictor66** [kanboard/kanboard#2343]
### Expected behaviour

Is it possible to integrate Kanboard with Cuttlefish and Office 365?
### Actual behaviour

Integrates with sendgrid , mailgun , etc
### Steps to reproduce

1.
2.
3.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment]
There is no plugin for that at the moment. What is Cuttlefish?

**Comment by fguillot** [comment]
Unfortunately, I didn't plan to add such feature to avoid too much complexity in the software.
