### ISSUE TITLE
Backslash for escaped characters

### ISSUE THREAD

**Issue by robjurd** [kanboard/kanboard#2346]
### Expected behaviour

Backslashes should not show in the general flow of text

### Actual behaviour

Characters that are escaped and require a backslash for use in the database, are showing up and displayed on screen

e.g.

"Instead of seeing a user\'s comment, I\'m seeing backslashes"

### Steps to reproduce

1.  Post a comment that contains a quote character

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.30
PHP version: 5.3.29
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-431.20.3.el6.x86_64
Database driver: sqlite
Database version: 3.7.7.1
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36

**Comment by fguillot** [comment]
Since you are using a very old version of PHP, check if the magic quotes are enabled: http://php.net/security.magicquotes
