### ISSUE TITLE
Slow request -response of updating a task

### ISSUE THREAD

**Issue by margach** [kanboard/kanboard#2348]
### Expected behaviour

When updating  a task or description of a task, it should take a short time to update it, this was not the case but after i updated to the latest version.

### Actual behaviour

When you want to update a task or are creating a new task, the request takes too long to complete, this was not the case in the earlier version but have noticed it in the new version.

### Steps to reproduce

1.login
2.create a task
3. update the description or task name it self

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- 

    Application version: 1.0.30
    PHP version: 5.5.9-1ubuntu4.16
    PHP SAPI: apache2handler
    OS version: Linux 3.13.0-85-generic
    Database driver: mysql
    Database version: 5.5.49-0ubuntu0.14.04.1
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by fguillot** [comment]
Did you have a look to this page: https://kanboard.net/documentation/performances ?
