### ISSUE TITLE
Feature: possible restrictions?

### ISSUE THREAD

**Issue by marcelloh** [kanboard/kanboard#2350]
This is not an issue but unclear if the application can (already) work like this
### Expected behaviour

Have another kind of user, like Project member, with lesser rights.
(Let call that one: Project Filler)

A user that is a Project Filler can
- add/edit  tasks in Column X
- can't change the visible order 
- Write comments in every other column
- Can move a task from Column Y to another column
### Example

Eddy is that user
John is the one fixing stuff
Eddy can add tasks to the backlog, but can't move them out of that column.
John drags it into the Busy-column and has a question, so he puts in some comment.
Eddy answers it by adding some comment too.
John finishes the task and moves it to Check
Eddy checks the task (and since Eddy has just enough rights) he can move it to Done,
or to Busy (when there is an error)

**Comment by fguillot** [comment]
There are custom project roles now.
