### ISSUE TITLE
default text in task description

### ISSUE THREAD

**Issue by kwijk** [kanboard/kanboard#2352]
### Reproduce && Expected behaviour
1. For a project go to kanaban board
2. for a column press on + button to add new task

==> The task description is empty
==> I would rather be abled to add a predifined text, like when I add an issue in the kanboard issues (this text editor), so that I can guide users to fill in the correct info. Possible a different text per column. 
### Actual behaviour

The task description is empty
### Configuration

version 1.0.28

**Comment by fguillot** [comment]
Predefined texts are available in the development branch.
