### ISSUE TITLE
No check if automatic action already exists

### ISSUE THREAD

**Issue by Olliiee** [kanboard/kanboard#2356]
### Expected behaviour

Create a new automatic action and get an error message this action with the same parameters already exists.
### Actual behaviour

Add the same automatic action again.
### Steps to reproduce
1. Create an automatic action
2. Repeat step 1
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.30
PHP version: 5.5.9-1ubuntu4.17
PHP SAPI: apache2handler
OS version: Linux 3.13.0-32-generic
Database driver: mysql
Database version: 5.5.49-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
