### ISSUE TITLE
internal sql error auf upgrade to 1.0.30

### ISSUE THREAD

**Issue by mglaubitz** [kanboard/kanboard#2359]
### Expected behaviour

the docu says that the upgrade to another version work "automatically" without any manual work on the database structure
### Actual behaviour

I tried to update our kanboard 1.0.27 to 1.0.30 today an only got as far as the dashboard. When I tried to access a single project board I got a plain error page stating: internal sql error"

since we are running a really old database server (mysql 5.0) there might be problem, but 1.0.27 is running like a charm for us.
### Steps to reproduce
1. update to 1.0.30 from 1.0.27
2. log on as simple user or admin
3. access project board
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.27 --> 1.0.30
- Database type and version: mysql 5.0 (I know that this is rather old, but it is a central service at our university)
- PHP version: 5.5
- OS: openSUSE 13.2
- Browser: Firefox 47 + Chrome 51 (openSUSE Leap 42.1)

**Comment by fguillot** [comment]
What is the SQL error message exactly?

**Comment by rafael2813** [comment]
I have a similar problem in version 1.0.30 (Postgres 9.5.3): when I create a single task, board shows "Internal error: SQL error", but when I create tasks in bulk, this doesn't happen neither I save again a task created that way. In previous version, 1.0.27 (Postgres 9.4.7), it doesn't happen.

**Comment by fguillot** [comment]
You have to get the exact SQL error in your logs to be able to determine the root cause of the problem.
