### ISSUE TITLE
Group Mention that works like User Mention

### ISSUE THREAD

**Issue by OWENCRUZ** [kanboard/kanboard#2361]
Hi @fguillot , this piece of software works well for our needs. It would be nice though if you can add a Group mention feature that works the same way that user mention works. Say when I type @Accounting, notifications will be sent to all members of Accounting group.

Lastly, an option that says "I want to receive notifications:

> Whenever I am mentioned.
> Whenever my group is mentioned.

Because, right now, even if you're mentioned but you've set to receive only notifications from tasks assigned to you or created to you, user will not receive notification.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
