### ISSUE TITLE
Idea: attach comments to a task via email

### ISSUE THREAD

**Issue by skorvek** [kanboard/kanboard#2368]
The ability to add tasks to a project via email is great. 

I have an overflowing email box filled with discussions on many projects.  I am not a software developer, rather I am using kanboard for personal and professional project planning and organization (creating a kanboard to limit the amount of active tasks at once and attempt to retain my sanity). So an integration like slack or mattermost won't work, as none of my colleagues and collaborators would be using it to communicate with me. They're stuck on email.

It would be even better if I could forward/redirect messages to kanboard (I'm using Mailgun) and have it extract the body of the message to the comments of the task which matches the subject line.

So if I had an open project called "servers" with an open task called "Rebuild mail server" and I forwarded an email to kanboard+servers@mydomain.tld with a subject "Rebuild mail server", the body of the message would be added as the next comment on that task if found in the "servers" project.

Thanks for the project- love it so far and can't wait to see how it grows.

**Comment by OWENCRUZ** [comment]
+1 on this. I'm using WHMCS for our ticketing system ( Domain and Hosting Service ). 

WHMCS actually checks the email account via POP3 at a particular interval set by the administrator. WHMCS has the option to fetch only the user reply ( anything below the email line break will be disgcarded so as not to clutter the comment area ) or if for any reason the admin want to fetch the entire email content, it can also be done.

This is useful specially when you want to give a client access to the project management board and so the client can also easily reply via email without having to login to the board.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
