### ISSUE TITLE
Question: Subdir installation on Ubuntu 16.04 + nginx fails?

### ISSUE THREAD

**Issue by 0ip** [kanboard/kanboard#2369]
### Expected behaviour

Following https://kanboard.net/documentation/ubuntu-installation (Ubuntu 16.04), which assumes no further configuration changes, should lead to a working installation - even when deployed in a subdirectory.
### Actual behaviour

`PHP_SELF` is empty, thus when opening Kanboard in a browser, it references all resources to `/` and redirects the user to `/?controller=...` instead of `/my-subdir/?controller=...`.

Workaround:
Delete 

```
# Bypass the fact that try_files resets $fastcgi_path_info
# see: http://trac.nginx.org/nginx/ticket/321
set $path_info $fastcgi_path_info;
fastcgi_param PATH_INFO $path_info;
```

in `/etc/nginx/snippets/fastcgi-php.conf`. (`PATH_INFO` is empty then, however, `PHP_SELF` is not)

Alternatively, replace `PHP_SELF` with `SCRIPT_NAME` in https://github.com/fguillot/kanboard/blob/master/app/Helper/UrlHelper.php#L127.
### Steps to reproduce
1. (optional: `sudo add-apt-repository ppa:nginx/development` (shouldn't make a difference, hopefully))
2. `sudo apt-get install nginx php-fpm php-xyz-dependency...`
3. Default PHP-FastCGI config in a server block:
   
   ```
   server {
   ...
   location ~ \.php$ {
       include snippets/fastcgi-php.conf;
       fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
   }
   }
   ```
4. Install Kanboard as described here: https://kanboard.net/documentation/ubuntu-installation
5. Open `http(s)://host/subdir/kanboard/` - this will fail
6. Placing a file in `/subdir/kanboard/test.php` (`<?php var_export($_SERVER)?>`) reveals that `PHP_INFO` and `PATH_INFO` are both empty.
### Configuration
- Kanboard version: all affected
- Database type and version: default SQlite
- nginx version: 1.11.1
- PHP version: PHP 7.0.4-7ubuntu2.1
- OS: Ubuntu 16.04
- Browser: *

**Comment by volodymyr-kushnir** [comment]
Thanks, @0ip, removing `fastcgi_param PATH_INFO $fastcgi_path_info;` from my config helped.

**Comment by sensei412001** [comment]
i'm using windows 7 and IIS where can i remove the fastcgi_param ? thanks in advance

**Comment by volodymyr-kushnir** [comment]
@sensei412001, sorry, I'm not an expert in IIS, I thought that you're on nginx. Anyway, I still think that your issue is related to PATH_INFO, so you can refer to the **Install and Congifure PHP** section of [this](http://www.iis.net/learn/application-frameworks/install-and-configure-php-applications-on-iis/using-fastcgi-to-host-php-applications-on-iis#InstallPHP) document. Basically they recommend to set **cgi.fix_pathinfo=1** in *php.ini*.

**Comment by sensei412001** [comment]
thanks volodymyr-kushnir. appreciate it. hope someone could lend a hand

**Comment by fguillot** [comment]
You could use this example for a working example: https://github.com/kanboard/kanboard/issues/2080
