### ISSUE TITLE
Improvement: Sort Subtask by Task's priority

### ISSUE THREAD

**Issue by auguster** [kanboard/kanboard#2371]
I noticed that the only way to sort the subtask (ttbomk), in "My subtask" (name guessed from French) is through alphabetical sort on id, task name or subtask name. I don't see how those sort are relevant to anyone. I think I would be better to propose a sort based on the parent task's priority or deadline date.

The idea is to answer the question "what subtask should I do now ?" just by looking at the list of subtask.

I guess you can do that in two steps: "what task should I do now ?" and look for the associated subtask. But it isn't that convenient.

BTW: Great work on this project, it's one of the main tool of our organisation (right after the mail server).

**Comment by Jluisito** [comment]
+1 to auguster comment. The great question is "what subtask should I do now ?", what subtask has more priority or a nearest date?

**Comment by fguillot** [comment]
The layout of the dashboard has changed and this is now sorted by priority.
