### ISSUE TITLE
Kanboard 1.0.30 is locking

### ISSUE THREAD

**Issue by n0va1s** [kanboard/kanboard#2372]
### Expected behaviour
Tell us what should happen
As a user I would like to change the color, column, category or duplicate a card

### Actual behaviour
Tell us what happens instead
In a specific board(80 cards) when some people (20 people) move a card of column, change the color or duplicate it lock the application. An animated gif remain running. You must close the browser and open again to do the change.
When I create other board or duplicate it works, but I lose the statistics and the status of subtasks (running or completed)

### Steps to reproduce
1. Duplicate a card
2. Change the color of card
3. Save the change

### Configuration
Copy and paste the configuration section from the Kanboard settings page or fill these fields:
    Versão da aplicação: 1.0.30
    Versão do PHP: 5.5.21
    PHP SAPI: apache2handler
    Versão do sistema operacional: Linux 3.10.0-229.11.1.el7.x86_64
    Driver do banco de dados: postgres
    Versão do banco de dados: 9.3.0
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:38.0) Gecko/20100101 Firefox/38.0

![kanboard1_0_30](https://cloud.githubusercontent.com/assets/3171080/16210542/e848186c-3712-11e6-97f4-64cf3178686f.png)

**Comment by fguillot** [comment]
Did you have a look to this page: https://kanboard.net/documentation/performances ?

**Comment by n0va1s** [comment]
On ACCESS_SSL:

*This IP has problem

10.34.0.98 - - [07/Jul/2016:10:16:18 -0300] 208816 "GET /?controller=BoardViewController&action=show&project_id=678 HTTP/1.1" "KB_RM=0e6ea16bc0494df3e4805f8fc84aac3e45a4dc5c719fff78916409ded530afbc%7C67182577272e42fa3bbcd8d75316751d351aca451ffcbc849207ee891b09; KB_SID=BaZYB9KOqMBoV6yGBctl9uvZ3Df" 200 192022
10.34.0.98 - - [07/Jul/2016:10:16:18 -0300] 335 "GET /assets/css/vendor.min.css?1465608827 HTTP/1.1" "KB_RM=0e6ea16bc0494df3e4805f8fc84aac3e45a4dc5c719fff78916409ded530afbc%7C67182577272e42fa3bbcd8d75316751d351aca451ffcbc849207ee891b09; KB_SID=BaZYB9KOqMBoV6yGBctl9uvZ3Df" 304 0
10.34.0.98 - - [07/Jul/2016:10:16:18 -0300] 218 "GET /assets/css/app.min.css?1465608827 HTTP/1.1" "KB_RM=0e6ea16bc0494df3e4805f8fc84aac3e45a4dc5c719fff78916409ded530afbc%7C67182577272e42fa3bbcd8d75316751d351aca451ffcbc849207ee891b09; KB_SID=BaZYB9KOqMBoV6yGBctl9uvZ3Df" 304 0
10.34.0.98 - - [07/Jul/2016:10:16:18 -0300] 127 "GET /assets/css/print.min.css?1465608827 HTTP/1.1" "KB_RM=0e6ea16bc0494df3e4805f8fc84aac3e45a4dc5c719fff78916409ded530afbc%7C67182577272e42fa3bbcd8d75316751d351aca451ffcbc849207ee891b09; KB_SID=BaZYB9KOqMBoV6yGBctl9uvZ3Df" 304 0
10.34.0.98 - - [07/Jul/2016:10:16:18 -0300] 119 "GET /assets/js/app.min.js?1465608833 HTTP/1.1" "KB_RM=0e6ea16bc0494df3e4805f8fc84aac3e45a4dc5c719fff78916409ded530afbc%7C67182577272e42fa3bbcd8d75316751d351aca451ffcbc849207ee891b09; KB_SID=BaZYB9KOqMBoV6yGBctl9uvZ3Df" 304 0
10.34.0.98 - - [07/Jul/2016:10:16:18 -0300] 209 "GET /assets/js/vendor.min.js?1465608834 HTTP/1.1" "KB_RM=0e6ea16bc0494df3e4805f8fc84aac3e45a4dc5c719fff78916409ded530afbc%7C67182577272e42fa3bbcd8d75316751d351aca451ffcbc849207ee891b09; KB_SID=BaZYB9KOqMBoV6yGBctl9uvZ3Df" 304 0
10.32.128.56 - - [07/Jul/2016:10:16:18 -0300] 95471 "GET /?controller=UserAjaxController&action=status&_=1467894344524 HTTP/1.1" "KB_SID=RLKvaOSaopG8EJHZ3P7pUfSFhS7" 200 2
10.34.0.98 - - [07/Jul/2016:10:16:20 -0300] 199131 "GET /?controller=TaskViewController&action=show&task_id=9344&project_id=678 HTTP/1.1" "KB_RM=0e6ea16bc0494df3e4805f8fc84aac3e45a4dc5c719fff78916409ded530afbc%7C67182577272e42fa3bbcd8d75316751d351aca451ffcbc849207ee891b09; KB_SID=BaZYB9KOqMBoV6yGBctl9uvZ3Df" 200 105279
10.34.0.98 - - [07/Jul/2016:10:16:20 -0300] 334 "GET /assets/css/vendor.min.css?1465608827 HTTP/1.1" "KB_RM=0e6ea16bc0494df3e4805f8fc84aac3e45a4dc5c719fff78916409ded530afbc%7C67182577272e42fa3bbcd8d75316751d351aca451ffcbc849207ee891b09; KB_SID=BaZYB9KOqMBoV6yGBctl9uvZ3Df" 304 0
10.34.0.98 - - [07/Jul/2016:10:16:20 -0300] 164 "GET /assets/css/app.min.css?1465608827 HTTP/1.1" "KB_RM=0e6ea16bc0494df3e4805f8fc84aac3e45a4dc5c719fff78916409ded530afbc%7C67182577272e42fa3bbcd8d75316751d351aca451ffcbc849207ee891b09; KB_SID=BaZYB9KOqMBoV6yGBctl9uvZ3Df" 304 0
10.34.0.98 - - [07/Jul/2016:10:16:20 -0300] 243 "GET /assets/css/print.min.css?1465608827 HTTP/1.1" "KB_RM=0e6ea16bc0494df3e4805f8fc84aac3e45a4dc5c719fff78916409ded530afbc%7C67182577272e42fa3bbcd8d75316751d351aca451ffcbc849207ee891b09; KB_SID=BaZYB9KOqMBoV6yGBctl9uvZ3Df" 304 0
10.34.0.98 - - [07/Jul/2016:10:16:20 -0300] 118 "GET /assets/js/vendor.min.js?1465608834 HTTP/1.1" "KB_RM=0e6ea16bc0494df3e4805f8fc84aac3e45a4dc5c719fff78916409ded530afbc%7C67182577272e42fa3bbcd8d75316751d351aca451ffcbc849207ee891b09; KB_SID=BaZYB9KOqMBoV6yGBctl9uvZ3Df" 304 0
10.34.0.98 - - [07/Jul/2016:10:16:20 -0300] 142 "GET /assets/js/app.min.js?1465608833 HTTP/1.1" 

On the ERROR_SSL we haven't nothing on the same time.

**Comment by n0va1s** [comment]
The problem was in the mail configuration.

I had no interest in the e-mail configuration at this time, I chose not to do. So the application was slowly trying to send mail.

Thank's for help.
