### ISSUE TITLE
Add the weight of the column

### ISSUE THREAD

**Issue by hairetdin** [kanboard/kanboard#2376]
### Feature Request

To calculate bar percentage in the Gantt chart is used at the proportion of the number of columns. But, each column can have different levels of complexity of the task. As you look at something, to add the weight of the column to appear realistic percentage?

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
