### ISSUE TITLE
Nice to have feature: a place where ticket number and title are in the same line so we can easily copy them

### ISSUE THREAD

**Issue by giuntim** [kanboard/kanboard#2377]
In a previous version in ticket detail we had ticket number and ticket title on the same line, so it was very easy to copy/paste them.
We used it a lot to fill in SVN commit comments.
In the latest release ticket number and ticket description are on different columns, so we need to copy paste them separately.

I know it's not a big deal, but it would save us a lot of time :-)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
