### ISSUE TITLE
Cannot add attachments to tasks or projects

### ISSUE THREAD

**Issue by mjvolpe** [kanboard/kanboard#2381]
### Expected behaviour

Attachment should show in list of attachments after adding
### Actual behaviour

Add attachment to task or project by selecting file and clicking upload.  Receive message attachment successfully uploaded.   Click on link "View uploaded files", taken to project or task overview page.  Click on Attachments section, no attachments.   Checked in file system, attachments are not there.
### Steps to reproduce
1.  Add attachment to task or project
2.  Receive upload verification
3.  Try to view in list of attachments in task or project
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.2.28
PHP version: 5.5.9-1unbuntu4.16
PHP SAPI: apache2handler
OS version: Linux 3.19.0-59-generic
Database diver: MySQL
Database version: 5.5.19-0ubuntu0.14.04.1
Browser: IE11

**Comment by fguillot** [comment]
- You should upgrade to the latest version of Kanboard
- Is the data folder writeable by the web server user?
- Enable the debug mode, monitor the log file, then upload a file, if something is wrong you should see an error message that tell you you what is the problem.

**Comment by mjvolpe** [comment]
We upgraded to version 1.0.2.30, which did not help by itself. We also had to change the permissions on the data\files folder so that all users have create & delete access.   We tried with just the web server user, but this did not work.  Does this sound right?

**Comment by tzeumer** [comment]
I had some trouble too. It was related to open_basedir restrictions. I recognized it only by chance since the file upload does not produce any error. Somewhere else (don't remember where) an error message hinted to the missing access to /tmp. After including /tmp into open_basedir everything worked fine.
