### ISSUE TITLE
Last Modified and Last Comment Column and Export

### ISSUE THREAD

**Issue by OWENCRUZ** [kanboard/kanboard#2382]
Feature Enhancement:

I believe it'll be better for reporting purposes to included last modified date for tasks when searching for tasks.

Perhaps between the column Assignee and Due Date. See screenshot > http://prntscr.com/bkbwsi

I'm using WHMCS for support and accounting system and it's very useful to see immediately when a ticket was last modified and also be able to sort it so that administrators or project owner can identify tasks that are taking long to do.

It'll also be good to have a "Last  Comment" column with say only 30 character sniffet, then an underlined tripple dot "...." that when hovered shows the last comment and when clicked opens the task view.

Also, ability to export result in a CSV file would be neat.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
