### ISSUE TITLE
Feature Request: Automatic Actions: Change column if all blocked-by links are not active

### ISSUE THREAD

**Issue by GitHub-Lover** [kanboard/kanboard#2383]
An important feature request for automation:
- change column (e.g. from column 'waiting-for' to ready) of task A if
  - all related/linked tasks (e.g. task B, task C, ..) with relation blocked-by to task A are in a certain column (e.g. 'done') or
  - all related/linked tasks (e.g. task B, task C, ..) with relation blocked-by to task A have status 'closed' (or are deleted)

This would allow to bring tasks with are waiting for other tasked to the right column (in focus of the user).

(hope this is not a duplicate request).

Thank you for your effort.

**Comment by matteomazza** [comment]
I know this is a 1 years ago request, but is there any chance to have this feature implemented? I think it is really important for automation.

thank for your time

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
