### ISSUE TITLE
Markdown Toolbar in Comment area

### ISSUE THREAD

**Issue by OWENCRUZ** [kanboard/kanboard#2391]
### Expected behaviour

I'm expecting that there's a markdown toolbar in the comment box when adding a comment.
### Actual behaviour

No markdown toolbar ->   http://prntscr.com/bllhrb

But it's funny that it's available when editing a comment -> http://prntscr.com/blln2k 
### Steps to reproduce

Open an existing task and add new comment
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.27
PHP version: 5.5.35
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-431.29.2.el6.x86_64
Database driver: mysql
Database version: 5.5.50-cll
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by fguillot** [comment]
The toolbar is everywhere now if you download the v1.0.35.

Thank you
