### ISSUE TITLE
Improvement for Gantt view

### ISSUE THREAD

**Issue by Unictu** [kanboard/kanboard#2394]
### Expected behaviour

Overall, after half a year using Kanboard I have to say Kanban feature is one of the best of its kind. The speed of improvement is unbelievable too. 

If we can improve Gantt a bit more, you will have no competition. Most teams will need both Gantt and Kanban and this is not fully addressed by commercial application just yet. Imagine you have one board for task management and another for master (project/portfolio) management.

I would like to suggest a few features for Gantt view:
1. Pop up task view: this has been implemented in 1.0.29 so I am going to test it
2. Scaling schedule: ability to scale the timeline (Year->month->week>day) to show all your tasks timeline in one view
3. PDF export: together with scaling will make Gantt a great feature
4. Sorting task: current sorting option is not very useful when you have multiple Swimlanes. What about sorting by position but maintain Swimlane grouping?
5. Any other traditional Gantt features added eventually make it even better

Thanks for making and maintaining this awesome app.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.28
PHP version: 7.0.5
PHP SAPI: apache2handler
OS version: Windows NT 6.1
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by GeorgeFischhof** [comment]
Hi,

I was watching Gantt too. In my imagination Gantt shoukd work (semI) automatically:
- should be created from selectable columns (basically todo and work-in-progress should be taken into account, but maybe someone names these columns different, and for example we have plans on board as well, and maybe we would like to create a roadmap from the plans. This time we should calculate plans columns.)
- independent tasks should be calculated after each other according to the order in the column
- tasks assigned to different people can be executed parallelly, and here comes the calculation of  dependent tasks (this is the most valuable thing of Gantt: if someone has several tasks ad there is on at the end which blocks another guy then it will be shown on Gantt. The tasks must be reordered)

BR,
George

**Comment by Pawamoy** [comment]
Here is what I would like to see for Gantt tab:

- Sort by priority! (took me some time to understand "position")
- Ascending and descending order for all sorts

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
