### ISSUE TITLE
Suggestion: Kanboard as a ticketing system

### ISSUE THREAD

**Issue by fernandodiacenco** [kanboard/kanboard#2399]
Hello,

Kanboard has a great potential to overthrown the current ticketing system at our company (even tough it hasn't been explicitly designed for that)

but it can't to so without a few extra features, so i will leave them as suggestions for future development

Apologies if some of the features already exist, I didn't found them on my tests

1) Multiple boards with visibility options
This enables multiple teams from different departments to use the application and control wherever they are allowed to see each other boards

2) Email to card/task
This would be something like this: configure one "master" email to fetch emails and configure aliases to this email, so  for example every email send to tasks.dev@company.com (an alias of tasks@company.com)  would go to _boardhere_ on the first column as a new item/task

3) Scheduled or recurring cards/tasks
Possibility to schedule the opening of a card/task and daily/weekly/monthly scheduling for tasks that must be done everyday but can't be quite automated yet

4) LDAP integration
This is not critical, would just make things easier

I understand that many of those suggestions might not be feasible, but at least they serve as food for thought

Thanks.

**Comment by mlbarrow** [comment]
​Some responses:

1. Why would multiple projects not work for this purpose?

2. You could write a plug-in, or sponsor development of a plugin to allow a
more "flexible" email functionality. Right now, there is email support, but
it's intended for members of the project to email in information. It
doesn't allow arbitrary people to email into the system -- at least the
last time I looked into this.

3. This already exists. Click on the documentation link while logged in and
look for "recurring tasks."

4. This already exists. Click on the documentation link and look for "LDAP."
​

*michael at barrow dot me*
+1.541.600.2027

"Do not anticipate trouble, or
worry about what may never happen.
Keep in the sunlight." -- B. Franklin

**Comment by fernandodiacenco** [comment]
You are right, disregard #1 #3 and #4, LDAP is working flawlessly and it was WAY easier to setup the integration compared to OTRS

But it seems that there is no support yet to do what i need, about this i was thinking about email notifications as well, you send an email to contact@company, kanboard opens a task and the person who sent the email receives a notification that a Task/ticket has been opened and another notification when it is closed

Question: it is possible to schedule a task to be created only when another task is moved to a column or closed? I looked at the automatic actions configuration but may have missed that

Also it is possible to setup an default due date for created tasks?

**Comment by mlbarrow** [comment]
Yes -- the current email functionality of Kanboard is intended to support the project members, thus my comment about writing or sponsoring the development of a plug-in (or even extending the core functionality).

I currently use Kanboard as a ticketing system -- albeit one without end-users interacting with it. I thought about working on code mods to provide the functionality you describe, but alas there are too many other things in my queue just now. :-(

**Comment by seancarson** [comment]
Hello, take a look some of the request already made. 

Kanboard as an Issue Tracking/Helpdesk System #1506
Ability to Set Default Filters per Board #2222
Ability to merge tasks #2223
Ability to Select Destination Column and Catagory in AutoAction - move the task to another project #2264

As Both @mlbarrow and @fernandodiacenco stated you are not able to accept tickets from non project members.  It would be nice if users were autocreated as unregistered users or maybe even allow users by domain @doman.com.

**Comment by fguillot** [comment]
Kanboard is now capable of receiving and sending emails. This is pretty basic but the system could be extended with custom plugins.
