### ISSUE TITLE
Mail transports not being read correctly

### ISSUE THREAD

**Issue by PIMJIM** [kanboard/kanboard#2400]
### Expected behaviour

Tell us what should happen
The selected mail transport should be read from config.php
If I want to use SMTP, I should be able to set this:
// Mail transport available: "smtp", "sendmail", "mail" (PHP mail function), "postmark", "mailgun", "sendgrid"
define('MAIL_TRANSPORT', 'smtp');

// SMTP configuration to use when the "smtp" transport is chosen
define('MAIL_SMTP_HOSTNAME', 'xxx.xxx.xxx.xxx');
define('MAIL_SMTP_PORT', 25);
define('MAIL_SMTP_USERNAME', '');
define('MAIL_SMTP_PASSWORD', '');
define('MAIL_SMTP_ENCRYPTION', null); // Valid values are "null", "ssl" or "tls"
### Actual behaviour

Tell us what happens instead
No matter what the define('MAIL_TRANSPORT', 'smtp'); is set to, $this->helper->mail->getMailTransport() always returns "mail'
### Steps to reproduce
1. Install latest version on either Ubuntu 1404 or 16.04 (kanboard-1.0.30.zip)
2. try to use SMTP for notifications
3. It wont work

To fix I changed EmailJob.php to read like this:
public function execute($email, $name, $subject, $html, $author)
    {
        /_$transport = $this->helper->mail->getMailTransport();_/
        $transport = 'smtp';
        $this->logger->debug(**METHOD**.' Sending email to: '.$email.' using transport: '.$transport);
        $startTime = microtime(true);
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.30
- Database type and version: mysql 5.5.49-0ubuntu0.14.04.1
- PHP version: 5.5.9-1 ubuntu4.17
- OS: Linux 4.2.0-41 generic
- Browser:Mozilla/5.0

**Comment by fguillot** [comment]
Did you also set the mail transport in the user interface (Settings > Mail Settings) in addition to the config file? or only in the config file?
