### ISSUE TITLE
More Webhook actions (Gitlab)

### ISSUE THREAD

**Issue by PiMaker** [kanboard/kanboard#2401]
I began using the GitLab webhook integration today, it's great so far, but I noticed that because I don't use GitLabs issue system I can basically only close issues on commit. Which is nice, don't get me wrong, but I'd love to be able to do more.

My request: A simple command system using commits.
Explanation: Imagine having a Task "Do Smth" (#42) under the column "In development". Now you're ready for testing that feature, e.g. you want to move it to the "testing" column. You write a commit message like this: "Work ended, feature done #42 #testing"
What happens: Kanboard sees the testing command in the commit message and moves it to that column.

I don't think this would be too hard to implement, correct me if I'm wrong :)

Thank you!

**Comment by mjwwit** [comment]
I think this is bigger than GitLab, it should be a feature for all VCS integrations. I imagine an action syntax similar to the one used by Trac (https://trac.edgewall.org/wiki/CommitTicketUpdater#Usage), but extended to support more Kanboard features.

- "refs `#5`" creates a comment on task 5
- "closes `#26`" creates a comment on task 26 and closes it
- "moves `#26` to [testing]" creates a comment on task 26 and moves it to "testing"

We'll need to work out the exact syntax.

I also think you should be able to reference tasks by using the Reference field of a task, but maybe I need to create a different issue for this.

If you agree @fguillot, I can start working on a PR.

**Comment by fguillot** [comment]
Issues related to Gitlab should be posted here: https://github.com/kanboard/plugin-gitlab-webhook/issues
