### ISSUE TITLE
Nintex Workflow Integration, Sharepoint 2013

### ISSUE THREAD

**Issue by iM4rv** [kanboard/kanboard#2402]
### Expected behaviour

Hey Guys, I am trying to get and create some tasks using the the "Web request" functionality of Nintex (on a Sharepoint 2013). Did one of you guys have any success in establishing a connection and saving tasks to a Sharepoint List or creating them? I Only get some workflow errors "Error performing web request. Unable to connect to the remote server". I attached a screen of the config for a task creation.

![image](https://cloud.githubusercontent.com/assets/12135467/16478931/4a498e88-3e9d-11e6-96b5-aed5377c5efb.png)
### Actual behaviour

Tell us what happens instead
### Steps to reproduce

1.
2.
3.
### Configuration

Version: 1.0.30
PHP Version: 5.3.10-1ubuntu3.23
PHP SAPI: apache2handler
OS Version: Linux 2.6.32-45-pve
Datenbanktreiber: mysql
Datenbank Version: 5.5.49-0ubuntu0.12.04.1
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by fguillot** [comment]
If you have a problem "Unable to connect to the remote server" this a network problem. This is not related to Kanboard.
