### ISSUE TITLE
Unable to add tasks in backlog, ready, work in progress, and done.. The popup doesnt show

### ISSUE THREAD

**Issue by Stevonjugush** [kanboard/kanboard#2404]
### Expected behaviour

The Popup should show once I click the addition icon in the backlog, ready, work in progress and done.

### Actual behaviour

No popup shows. It works well in localhost but in the server, the popup doesn't show

### Steps to reproduce

1.
2.
3.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

    Application version: 1.0.30
    PHP version: 5.6.22
    PHP SAPI: litespeed
    OS version:
    Database driver: sqlite
    Database version: 3.8.5
    Browser: Mozilla/5.0 (Windows NT 6.1; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by fguillot** [comment]
Make sure everything is installed correctly.
