### ISSUE TITLE
Feature Request: Meta data for Swimlane

### ISSUE THREAD

**Issue by Vertumnus** [kanboard/kanboard#2407]
I need to add in an own developed Plugin some additional information about the Swimlane. To avoid the modification of the swimlane table at database level, I need a metadata table like for tasks. The implementation of the metadata content shall be the same like for the existing ones.
Also I need at least one event (like task.create_update) to react on change/create of a swimlane and store the additional information to the metadata table.

Is it possible to provide this in one of the next versions?

**Comment by Busfreak** [comment]
Hi Vertumnus,

you can create your own plugin-table for this:
https://kanboard.net/documentation/plugin-schema-migrations

**Comment by Vertumnus** [comment]
That's a good hint to do it myself. However I would be happy to have a solution in the core ;-).

**Comment by fguillot** [comment]
If you really need that, the best way is to contribute by sending a PR.
