### ISSUE TITLE
Feature Request: Make Color Model extendable for additional colors

### ISSUE THREAD

**Issue by Vertumnus** [kanboard/kanboard#2409]
### Background

We use the coloring of tasks to mark them, that they belong to one topic. Because of the amount of topics we work on at one swimlane the amount of standard colors is not enough. So we decided to extend them.
### Actual behaviour

I've overridden in a Plugin the ColorModel and provided two new methods to add colors.There is only one drop of bitterness. I had to modify the original ColorModel in the way that the attribute array $default_colors switched from private to protected. Cause: My Plugin ColorModel extends the original ColorModel to reuse all the existing functionality in a simple way.
### Expected behaviour

To avoid the modification on the original source file I need one of these changes:
1. The attribute $default_colors becomes protected in the original ColorModel
2. The original ColorModel gets methods to add new colors (my favored change)
### Additional stuff

Here my implementation to add colors preventing an overriding of already existing colors. Maybe it's better to provide methods, which set colors (overriding existing and adding new).

`
    public function addColor($id, $name, $background, $border)
    {
        // do not override existing color
        if(empty($this->default_colors[$id])) 
            $this->default_colors[$id] = array('name' => $name, 'background' => $background, 'border' => $border);

```
    return $this;
}

public function addColors(array $colors)
{
    $this->default_colors = array_merge($this->default_colors, $colors);

    return $this;
}
```

`

**Comment by aslmx** [comment]
+1 any chance this will be implemented soon? Or is there another workaround that i have not yet found?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
