### ISSUE TITLE
Feature Request: Configure the usage of a Plugin at project level

### ISSUE THREAD

**Issue by Vertumnus** [kanboard/kanboard#2410]
### Expected behaviour

I need the possibility to activate i.e. deactivate a Plugin for certain projects in Kanboard. The configuration should be available in the settings of a project. Deactivating a Plugin shall avoid the execution of the Plugin extensions for the affected project.

As a first draw, I see following two solution approaches
1. The core avoids to execute the Plugin coding
2. The Plugin has to check itself, if it has to execute its functionality depending on the project
- will need some kind of a method at the ProjectModel like isPluginActive() expecting the Plugin identifier and returning a boolean

### Actual behaviour

Plugins are executed independent of the project.

**Comment by fguillot** [comment]
Sorry but to keep the code base simple this feature request won't be developed.
