### ISSUE TITLE
Feature Request: Abillity to Add CC field to Tasks

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#2411]
Hello, 

If possible could you add an CC filed to tasks.  The CC filed would function as Carbon Copy does in email.  Any updates or changes to a tasks that matched a users notification level would be sent to them.  In the current iteration of Kanboard it is not possible to notify multiple users of task activity unless you create a distribution group in your email system and register it as a member of said KB Board.  

This feature would make the use of Kanboard more efficient and provide several different use cases for the project.    

Thank You

Sean Carosn

**Comment by ptman** [comment]
This sounds like something that could help with many of the intended usecases for #85

**Comment by seancarson** [comment]
Request from 2354.  

Hello,

If possible I would like to request that a CC or BCC like filed be added to tasks so that non creators and others not assigned to the task could be updated on task activity via email.

For Example. Tony Snow creates a task in kanboard. He assigns it to Jim Smith. Depending on how Jim and Tony have their notification settings they will both get notification on task activities. But say Tony wanted another person named Jill to be updated the tasks activities. This is currently not possible unless you create custom distro groups in your email server. and create users in kanboard with thoses custom groups as emails.

The CC function would allow Tony to Create the task, assign it to Jim and add Jill and or others as watchers/CCs of the task.

Thanks

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
