### ISSUE TITLE
Feature Request: Sort by Link Labels (is dependency of and dependent on) 

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#2412]
Hello, 

The Link Labels Kanboard incorporates provides and great framework for tasks dependencies.   If your create the Link Labels "is dependency of" and "dependent on"  you would then be able to add task relationships.  the only problem is how do you display that inter-dependency.   

A simple way would be to allow the displaying or sorting of task by Parent -> Child or "is dependency of " -> "dependent on" relationships.  

So say Task 1, Task 2, Task 3, Task 4, Task 5.  If task 1 to 4 are dependent on Task 5 then the sort would show as follows.

Task 5
Task 1
Task 2
Task 3
Task 4

Now I realize this does not cover every use (Multiple/Complex Dependencies) case but it would be a good start.  

Thanks

**Comment by seancarson** [comment]
As, I look at this further there is already a is a child of/is a parent of relationship already established.  This sort feature would be good to apply to this as well.  Which ever way your wanna go, I do not want to recreate the wheel.  

Thanks

SC

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
