### ISSUE TITLE
KANBOARD keeps stopping in Docker

### ISSUE THREAD

**Issue by rsliotta** [kanboard/kanboard#2413]
### Expected behaviour

The server should never stop unless we explicitly stop it
### Actual behaviour

It seems that KANBOARD just stops every few days.  Always seems to be when it is idle for a long time
### Steps to reproduce
1.  Start the server in docker
2. Wait a long time.  It will happen
   3.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.30  I was on the stable release prior and this was happening for that release to.  I upgraded to 1.0.30 in hope it was fixed...
- Database type and version:  Whatever was supplied in the image
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment]
Can you provide at least some logs or error messages? something to troubleshoot... I'm using myself Kanboard with Docker and I don't have any unexpected restarts.

**Comment by rsliotta** [comment]
If you can tell me where to find the logs, I will monitor them.

The issue so far is there seems to be no reason it is stopping.

**Comment by cweagans** [comment]
@rsliotta `docker logs [container id or name]`. You could also just set a restart policy on the container and it'll come back up again.

**Comment by rsliotta** [comment]
Hello!!!

Finally I got a log with something in it.  I am attaching both the logs and my docker config for the container.  It has always-restart, but it dies.  Hopefully the logs will help get a resolution
[kanboard_logs.txt](https://github.com/kanboard/kanboard/files/431541/kanboard_logs.txt)
[kanboard_docker.txt](https://github.com/kanboard/kanboard/files/431542/kanboard_docker.txt)

**Comment by fguillot** [comment]
Unfortunately, I don't know why your container is not working properly. I propose to try again with the last version of the Docker image and with the latest version of Docker. If the problem occurs again, reopen this ticket.

Thank you

**Comment by rsliotta** [comment]
Frederic,

I found out the issue is docker.  I forgot to update the issue

Best Regards,

Bob

[Sent from my iPhone]
