### ISSUE TITLE
@Mentions followed by punctuation cause mention to fail

### ISSUE THREAD

**Issue by george-viaud** [kanboard/kanboard#2418]
### Expected behaviour

When using mentions, adding punctuation characters at end of mention should not result in a failed mention.  Example:  

@Name, bla bla bla
### Actual behaviour

Adding punctuation after a mention causes it to not match the person's name

Example: 
@Name, bla bla bla (this fails)

@Name , bla bla bla (notice the space, this works)
### Steps to reproduce
1. Create a comment with a mention that has a comma after it (for example)
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.30
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment]
Thanks, this is now fixed in the development branch.
