### ISSUE TITLE
Recurrence settings

### ISSUE THREAD

**Issue by alefaucheur** [kanboard/kanboard#2422]
### Expected behaviour

Must be able to set recurrence against a day of week or month or quarter or semester or year
ex: Second Tuesday of every month
### Actual behaviour

Today recurrence is based on calendar day and not on business day
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
    Application version: 1.0.31
    PHP version: 5.6.15
    PHP SAPI: apache2handler
    OS version: Windows NT 6.1
    Database driver: mysql
    Database version: 10.1.9-MariaDB
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
