### ISSUE TITLE
Due date settings

### ISSUE THREAD

**Issue by alefaucheur** [kanboard/kanboard#2423]
### Expected behaviour

Be able to set a due date by default in project settings
So we can set automatically a start and end date
### Actual behaviour

Due-date field is never fulfilled
### Configuration

```
Application version: 1.0.31
PHP version: 5.6.15
PHP SAPI: apache2handler
OS version: Windows NT 6.1
Database driver: mysql
Database version: 10.1.9-MariaDB
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0
```

**Comment by fguillot** [comment]
I don't really understand your request, you want a new settings to set a due date by default for tasks? What is the use case for that, any example?

**Comment by alefaucheur** [comment]
Thank you,
actually my need is to be able to set this field (and maybe some others) mandatory according to a specific project.
This is the same when I close, some fields must be fulfilled prior to close.

By the way we cannot filter by task priority nor complexity?
Occurrence cannot be set on business day (instead of calendar day), ex: Every second Tuesday of each month

Best regards


De : Frédéric Guillot [mailto:notifications@github.com]
Envoyé : mardi 5 juillet 2016 04:24
À : fguillot/kanboard
Cc : Alexandre Le Faucheur; Author
Objet : Re: [fguillot/kanboard] Due date settings (#2423)


I don't really understand your request, you want a new settings to set a due date by default for tasks? What is the use case for that, any example?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/fguillot/kanboard/issues/2423#issuecomment-230375236>, or mute the thread<https://github.com/notifications/unsubscribe/APy6rhiot_ek2Ibgqf00bU3VmwvuTE8xks5qScBRgaJpZM4JEKdF>.

Alexandre Le Faucheur
QUALITY SYSTEM MANAGER
Telehouse Europe
D: +33 (0) 1 56 06 40 75

F: +33 (0) 1 56 06 40 49
Siège social : 137, Boulevard Voltaire 75011 Paris


[cid:imagec025f1.JPG@74520552.4b992d99]<http://www.telehouse.fr>


Ce message et ses pièces jointes éventuelles peuvent contenir des informations confidentielles ou légalement protégées à l’intention exclusive de ses destinataires. Toute modification, édition, utilisation ou diffusion non autorisée est interdite. Si vous avez reçu cet e-mail par erreur, nous vous remercions de bien vouloir le détruire immédiatement et de nous en informer par e-mail.

________________________________
This e-mail and any attachments may be confidential, proprietary or legally privileged and intended solely for the addressees. Any unauthorized modification, use, disclosure, distribution or copying of this e-mail is prohibited. If you received this message in error or are not the intended recipient, please delete or destroy the e-mail message and any attachments or copies and notify the sender of the erroneous delivery by return e-mail.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
