### ISSUE TITLE
Start Time not taken over when creating or changing tasks

### ISSUE THREAD

**Issue by Soily** [kanboard/kanboard#2425]
### Expected behaviour

When creating a new task or changing an existing task, the time for "Start Time" should be taken over flawlessly
### Actual behaviour

The start time box inside the task creation view will not take over the time and the task settings cannot be saved.
### Steps to reproduce
1. I'm on german time setting. 
2. Create or change existing tasks, where no start time has been set
3. Set Start Time for a task and set a misc. time.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.31
- Database type and version: SqlLite  Apache/2.4.12 (Win32) OpenSSL/1.0.1l 
- PHP version:PHP/5.6.8
- OS: Windows
- Browser: Firefox 47

**Comment by Soily** [comment]
I now set the date format and the date AND time format to the same definition (d, m, Y) and now everything works fine. So the issue seems only to be present when both formats don't allign?!

**Comment by fguillot** [comment]
What was the date/time settings initially?

**Comment by Soily** [comment]
Hi,
in my case the following settings were set while the error appeared to be present:

Dateformat:
Set to (d.m.Y)

Date- and Timeformat:
Set to (m/d/y H:i)

Timeformat:
14:16(H:i)

These settings will produce the error.

When changing the Date- and Timeformat to the following:
Date- and Timeformat:
Set to (d.m.Y H:i)

everthing runs fine.

Conclusion:
I think the Dateformat and therefore the Date-and Timeformat should be alligned to each other, or forced to be in sync somehow.

**Comment by fguillot** [comment]
You should try a more recent version of Kanboard because the date and time settings have been improved to avoid bad configuration/confusion.
