### ISSUE TITLE
FR: change filter behaviour if no attribute was matched.

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#2426]
I suggest changing the filter behaviour for the case:

---

**From the Documentation:**
Search by task title: _anything that doesn't match any search attributes_

---

This should instead **search over all available taskfields**.
After that you could **filter the result** more with the **advanced search syntax attributes**.

I think this would increase the efficiency of the filter - because I don't have to remember in which taskfield my searchstring was put in - while still providing the granularity of the current implementation, if a few attributes were added (title: & id:).

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
