### ISSUE TITLE
Internal Error: SQL error on order=title in dashboard

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#2428]
### Expected behaviour

Sort the tasks by title

### Actual behaviour

Internal Error: SQL error

### Steps to reproduce

1. Open the Dashboard.
2. Click on _Task_
![image](https://cloud.githubusercontent.com/assets/13346344/16565595/aa3ff40c-420e-11e6-953c-3400d52e6f7d.png)

### Configuration

Application version: 1.0.31
PHP version: 5.3.28
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.2
Database driver: sqlite
Database version: 3.7.7.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by Chaosmeister** [comment]
this also happens in
controller=DashboardController&action=tasks

Every other sorting works fine.

**Comment by fguillot** [comment]
Do you have the SQL error message from your debug logs?

Probably due to the very old version of Sqlite on your system.

**Comment by Chaosmeister** [comment]
with debug turned on the message changes to
**Internal Error: SQL error: SQLSTATE[HY000]: General error: 1 ambiguous column name: title**

**Comment by Chaosmeister** [comment]
One thing to add here maybe:
I updated from version 1.0.29 directly to 1.0.31.

**Comment by Chaosmeister** [comment]
I updated the php and sqlite version through the iis web-platform installer to

Application version: 1.0.31
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2

but this still happens.

I also tried to debug the query with var_dump() to see if I could find the error, but I'm unable to find the faulty query in the mass of the output: http://pastebin.com/gkqyyceb

**Comment by Chaosmeister** [comment]
so by var_dump-ing in the findall() method I was able to retrieve the query:

`SELECT tasks.id, tasks.title, tasks.date_due, tasks.date_creation, tasks.project_id, tasks.color_id, tasks.priority, tasks.time_spent, tasks.time_estimated, tasks.is_active, tasks.creator_id, projects.name AS project_name, columns.title AS column_title FROM "tasks" LEFT JOIN "projects" ON "projects"."id"="tasks"."project_id" LEFT JOIN "columns" ON "columns"."id"="tasks"."column_id" WHERE tasks.owner_id = ? AND tasks.is_active = ? AND projects.is_active = ? ORDER BY "title" ASC LIMIT 10 OFFSET 0`

**Comment by Chaosmeister** [comment]
without `ORDER BY "title"` the statement executes.

**Comment by fguillot** [comment]
The code have been modified in the development branch. It should work now.

**Comment by Chaosmeister** [comment]
works with 1.0.32
