### ISSUE TITLE
Beta reviews

### ISSUE THREAD

**Issue by Busfreak** [kanboard/kanboard#2430]
@fguillot 
Today I have seen accidentally, that a new beta is released 6 days ago. Today the new stable version is out. There was no mail alert, that a new beta has been released, so maybe no reviews / tests have been done before the final release. Is it possible to send an email, when a new beta ist out?

On the kanboard.net website there have been nightly builds with vendor folder in the past. Is it possible to generate them automatically? It would be helpful to get nightly builds for the beta for quick testing.

Kind regards!

**Comment by fguillot** [comment]
I don't want to spam people by sending too many emails. I should probably setup a separate mailing list for the beta announcements.

**Comment by toepi** [comment]
Why not use a more fixed schedule (beta release last monday in a month), see how gitlab do it. think it is a nice approach. Perfectly fit into Kanban - release finish features at a given date.

**Comment by fguillot** [comment]
I merged master into the branch beta.

The nightly build is back: https://kanboard.net/downloads

Otherwise you can use the Docker image for testing.
