### ISSUE TITLE
Feature Request: Completed Tasks to stay visible

### ISSUE THREAD

**Issue by Unictu** [kanboard/kanboard#2433]
Hi,

Tasks can be marked Done and will stay visible (on the DONE column) and stop showing red colour in due date until it is marked Closed/Archived.

Wondering if anyone else considering this is a useful feature? We want to keep current batch of works (i.e one sprint) visible until we finish them all.

Cheers

**Comment by NinjaPewPew** [comment]
I totally agree that that would be useful. We always want to have a start date and a completed date, but in the current version the only way to achieve that is to close the task. I would love a way to set a task to done. That way the completed date could be set, without having to immediately close the task.

**Comment by eurodrew555** [comment]
This would be really useful. I have tasks for reference/info that I just keep open which is good for quickly getting to important info for a project. The only problem with this is these tasks show up in searches, etc when I would prefer they are just closed but visible on the board.

Would be good if you could mark a task as completed which stays visible on the board but doesn't show up in open tasks, etc. Closing the task then removes it.

**Comment by lalato** [comment]
Agreed, being able to complete/resolve a task without closing it would work well with our process.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
