### ISSUE TITLE
Feature Request: automatic coloring for tags

### ISSUE THREAD

**Issue by hubutz** [kanboard/kanboard#2436]
Hi,

I've came across kanboard yesterday and I really like it. After fiddling with it I think the addition of tags makes perfectly sense. One thing that would make this complete would be the possibility to automatically color tasks per tag - like it's done via category already.

Best
hubutz

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
