### ISSUE TITLE
Feature Request: gray out tasks with a start date in the future

### ISSUE THREAD

**Issue by hubutz** [kanboard/kanboard#2437]
Hi,

another useful addition from my pov would be to show tasks that have a start date in the future grey with some transparency, so you don't focus too much on them. This would be nice too :)

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
