### ISSUE TITLE
Feature Request: add customer field to task

### ISSUE THREAD

**Issue by hairetdin** [kanboard/kanboard#2440]
I use Kanboard to execute task from customer (helpdesk in my organization). It would be convenient to have a separate field - customer.  This will immediately see who is the customer and then make reports. Other users will be able to use Kanboard with client field for task management of sales or purchases.
In my case , customers are users of LAN, and I look LDAP for user information.

**Comment by Vertumnus** [comment]
There is a table to store meta data for tasks in a key-value-format. If you implement a plug-in of your own you can use this meta data table to store this kind of information.

See [Documentation -> Integrations -> Plugins](https://kanboard.net/documentation/plugins) for more details.

**Comment by BlueTeck** [comment]
There is already a plugin: https://github.com/BlueTeck/kanboard_plugin_metadata

**Comment by fguillot** [comment]
You could use the plugin mentioned above. Otherwise seems to be the same feature request as #2892
