### ISSUE TITLE
Feature Request : User defaults

### ISSUE THREAD

**Issue by bluegroper** [kanboard/kanboard#2441]
**Feature Request : User defaults**

We use kanboard to manage shared work for a small team.
After login, each person must do the exact same sequence of clicks every time they commence using kanboard
- Click at the project (We have a single project, called "All Tasks")
- Click at Compact View
- Click at Remove maximum column height
  Would it be possible to have these login settings saved as "defaults" for each user, or "globally" for ALL users ?
  Perhaps there's other parameters that could also be usefully saved as user defaults ?
  TIA's

PS.  As we spend more time using the kanboard, we're learning to like it a lot.

**Configuration**

Application version: 1.0.30
PHP version: 5.4.16
PHP SAPI: apache2handler
OS version: Linux 3.10.0-327.22.2.el7.x86_64
Database driver: postgres
Database version: 9.2.15
Browser: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
