### ISSUE TITLE
Feature Request: Link Project dates to tasks start/end dates

### ISSUE THREAD

**Issue by Biniou180** [kanboard/kanboard#2442]
I open this ticket as a contributor of Framasoft projects, and particularly Framaboard which is based on Kanboard.

Currently in Kanboard, the user is able to set start/end dates for a task, and also for a project (used in the multi-project gantt). These data fields are independent: Changing a task date does not affect the project date.

Could it be possible to have an option to synchronize these dates? For example:
- if not already manually set, the project start date is taken from the earliest start date of all tasks
- if not already manually set, the project end date is taken from the latest end date of all tasks

As users may want to keep dates uncorrelated (because planned project dates may be deadlines to respect, independently from tasks), a checkbox to activate this behaviour for a project could be useful.

Do you think it is possible/interesting to add this feature?

Thanks! :-)

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding

**Comment by chaissac** [comment]
It may be possible to add this features via the Automatic Actions ? Something based on the link, for example : If a task is closed, all tasks that are blocked by this task have their start date set to the end date of the closed task.
