### ISSUE TITLE
Tag of user name in dashboard

### ISSUE THREAD

**Issue by Biniou180** [kanboard/kanboard#2443]
I open this ticket as a contributor of Framasoft projects, and particularly Framaboard which is based on Kanboard.

In the dashboard page, the user name appears above the dashboard menu to the left.
This user name is in a `h2` tag, which can have some downsides:
  * As a title, it can be very large depending on the applied theme (this is the case in the Framaboard theme - see screenshot below)
  * It can be semantically confusing for the user : It is not really the menu title, but a information indicating who is related to he dashboard menu items "my tasks", "my projects"...

![Framaboard screenshot](https://framapic.org/FKBQ8HXeb1sf/QN0DEkr9JKUZ)

Therefore, should it be possible to change the tag of this element? (a div with a specific class/style maybe?) This way we keep the reading simple, the semantic is improved, and themes can display it as an additional information instead of the menu title.

Thanks a lot! :-)

**Comment by Chaosmeister** [comment]
I think the user name at this position could be removed completely since the user menu is always available in the topleft corner.

**Comment by fguillot** [comment]
In the development branch, I removed most of the sidebar titles. Otherwise, the title is wrapped inside a div with the class "sidebar-title" that allows you to apply any style.
