### ISSUE TITLE
Feature request: case insensitive usernames on login

### ISSUE THREAD

**Issue by Biniou180** [kanboard/kanboard#2444]
I open this ticket as a contributor of Framasoft projects, and particularly Framaboard which is based on Kanboard.

Currently (1.0.25 on framaboard), usernames are case sensitive when logging in.
It can be great, but we have a lot of support requests concerning users unable to connect because they forgot they had uppercase characters in their usernames.
It could be great to ease the login process for our users :)
### Steps to reproduce
1. Create a user including at least one uppercase character
2. Log out
3. Forgot that the username has an uppercase character :)
4. Log in with lowercase username
### Suggested solutions
- To indicate at least that the username is case sensitive on the login page
- Best: Forbid uppercase in usernames (rather common for online services)
- Much better: Allow the user to login with his e-mail address too
- The best: Allow the user to reset his password by giving his e-mail address (the reply e-mail will contain the username)

Thanks a lot!

**Comment by Biniou180** [comment]
Hello, 
I just put a comment here to ask if this issue is planned in a future version by chance?
I have just discussed with one of our users about this ticket, particularly the ability to reset the password by giving e-mail, as final users often not remember their username but definitely remember their e-mail :)

Thanks again!

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
