### ISSUE TITLE
UI: Clarify difference between local/remote users

### ISSUE THREAD

**Issue by Biniou180** [kanboard/kanboard#2446]
I open this ticket as a contributor of Framasoft projects, and particularly Framaboard which is based on Kanboard.
### Actual behaviour

When creating a user, there is choice between "local user" and "remote user" ("utilisateur" and "utilisateur distant" in french).
The difference is not crystal clear when creating a user, because explanation is displayed only in remote user page, at the bottom of the page. (I was using a small screen the first time, i didn't see it)

![Screenshot utilisateur distant](https://framacolibri.org/uploads/default/optimized/1X/a82dbb8dbb2963ea73c42f4df2519ef55afc0177_1_601x500.jpg)
### Expected behaviour

It would be best if the explanation come sooner (or nearer the buttons).
Why not put a small icon (?) right next to the "create remote user", and when hovering/clicking on it, a small popup appears containing the explanation?
### Steps to reproduce
1. Go to "users management" page
2. Create a new user
### Configuration
- Kanboard version: 1.0.25 (but checked also with 1.0.31)

Thanks a lot for your work!

**Comment by fguillot** [comment]
The user creation form have been simplified in the master branch. I hope that is better than before:

![user_creation_form](https://cloud.githubusercontent.com/assets/323546/22187363/1869a0fa-e0d3-11e6-9db8-99a57540add0.png)

**Comment by fguillot** [comment]
This is now available in v1.0.38

**Comment by Biniou180** [comment]
Seems OK to me, i will check with our users. thanks :)
