### ISSUE TITLE
Task tags overlap when they overflow and break to the next line.

### ISSUE THREAD

**Issue by eknam** [kanboard/kanboard#2450]
### Expected behaviour
Task tags should not overlap when they overflow and break to the next line.

### Actual behaviour

Task tags overlap when they overflow and break to the next line.

### Steps to reproduce

1. Add multiple tags to a task
2. The column should be narrow enough for the multiple tags to break on to the next line

![image](https://cloud.githubusercontent.com/assets/11539450/16616795/522fc726-4388-11e6-8f32-b5c5abb33eba.png)

A possible fix is to make the .task-li a inline-block and adding some margin. Another solution would be to adjust the lineheight.

### Configuration
Application version: 1.0.31
PHP version: 7.0.7
PHP SAPI: fpm-fcgi
OS version: Linux 3.16.0-4-amd64
Database driver: postgres
Database version: 9.5.2
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by fguillot** [comment]
This now fixed in the development branch.

Thanks
