### ISSUE TITLE
Uploading works only for some file types

### ISSUE THREAD

**Issue by mcbejn** [kanboard/kanboard#2452]
### Expected behaviour

Hi there,

I could really use your help. I can attach PDF, SVG etc but cannot upload jpg files to tasks. Any idea on why / how I can overcome this?

Thanks so much!

(Running Ubuntu 14.04 LTS with Apache)
### Configuration

Application version: 1.0.31
PHP version: 5.5.9-1ubuntu4.9
PHP SAPI: apache2handler
OS version: Linux 3.13.0-43-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by fguillot** [comment]
There is no restriction on the file type, what happening exactly when you upload a jpeg file?

**Comment by NinjaPewPew** [comment]
I have the same issue, but with "png". It seems to be stuck at 0%.

![upload issue](https://cloud.githubusercontent.com/assets/16925901/16764374/04993358-482e-11e6-903e-76f503c31077.png)

**Comment by fguillot** [comment]
What's happening when you click on "Save", do you have any error in the Javascript console or in your application logs?

**Comment by mcbejn** [comment]
@fguillot sorry for the late answer.

For me there is nothing in the console at all. The file just doesn't upload, though I get the status is OK and "all files have been uploaded successfully". Other uploads work, that is very unusual :)

This is what happens once I click "upload"
![screen shot 2016-07-15 at 11 52 30 am](https://cloud.githubusercontent.com/assets/8762517/16870597/a26ab8e4-4a82-11e6-928c-00036644a5f0.png)

But then it's nowhere to be found
![screen shot 2016-07-15 at 11 53 36 am](https://cloud.githubusercontent.com/assets/8762517/16870629/d321b9b0-4a82-11e6-9573-dc8c46d4e0ca.png)

Works for SVG though

![screen shot 2016-07-15 at 11 54 28 am](https://cloud.githubusercontent.com/assets/8762517/16870644/e936fc06-4a82-11e6-932b-51b4156a1a57.png)

Any ideas on what else I could check?

**Comment by fguillot** [comment]
If you activate the debug mode, do you have any more information?

**Comment by fguillot** [comment]
I was never able to reproduce your issue, so try again with the version 1.0.38. If the issue still there, reopen this ticket.
