### ISSUE TITLE
New Feature request - Automatic action for blocking task

### ISSUE THREAD

**Issue by snarf77** [kanboard/kanboard#2453]
### Expected behaviour

Don't know if others users can be interested in this feature but I really would like to see the following feature in an upcoming version of Kanboard which already an excellent piece of software (congrats to dev):
- Adding automatic action that allows to move a task to another column when a related blocking tasks is over. Ex move from "To Do" to "Ready" when prerequisite task is done
- Adding automatic action that allows to change a task color when a related blocking tasks is over
### Actual behaviour

Nothing for the moment... lol
### Steps to reproduce

1.
2.
3.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
