### ISSUE TITLE
Error when saving email notification preferences for a user

### ISSUE THREAD

**Issue by esquawk** [kanboard/kanboard#2457]
**# Expected behaviour**

Expected to be able to change email notification preferences under user management to "All Tasks" instead of the default option "only for tasks created by me and assigned to me".

**# Actual behaviour**
when i select all tasks and hit save i get a 502.2 bad gateway error, 
HTTP Error 502.2 - Bad Gateway

**# Steps to reproduce**
1. Change email notifications under user management to anything other than the default option  "only for tasks created by me and assigned to me"
2. Press Save button and the error is generated

**# Configuration**
Application version: 1.0.31
PHP version: 5.4.45
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.2
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by fguillot** [comment]
Can you get the exact error message from your web server logs? Are you using IIS?

**Comment by esquawk** [comment]
Hi Yes I'm using IIS, i've checked the PHP error's folder and looked at the log. 

It seems like a permissions error with the common and config folders which i ran by web server host but they have enabled correct permissions and the error is still being generated. 

I've attached screen shots showing both the PHP error log and the error message displayed in the browser. Please let me know if you need anything else and many thanks for your support. 

Liam

![screen shot 2016-07-12 at 11 09 51](https://cloud.githubusercontent.com/assets/2700923/16764439/128f47a2-4826-11e6-96d1-2080f2e85d84.png)

![screen shot 2016-07-12 at 11 47 43](https://cloud.githubusercontent.com/assets/2700923/16764532/9803bf1c-4826-11e6-8453-86ad24e06fd0.png)

**Comment by chamunks** [comment]
@fguillot I'm using docker container version kanboard/kanboard:v1.0.37
getting 502 error timeouts after adding SMTP settings but I'm not certain where to pull the logs from by default.  I would gladly throw in some input on this matter.

**Comment by chamunks** [comment]
``` docker logs -f kanboard```

Results in the following output.

```
2017/01/25 00:44:58 [error] 11#0: *56 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant tls - assumed 'tls' in /var/www/app/config.php on line 16" while reading response header from upstream, client: REDACTEDIP, server: localhost, request: "GET /?controller=UserAjaxController&action=status HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "REDACTEDDOMAINNAME"
crond[9]: USER root pid  30 cmd run-parts /etc/periodic/15min
2017/01/25 00:45:26 [error] 11#0: *56 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant tls - assumed 'tls' in /var/www/app/config.php on line 16" while reading response header from upstream, client: REDACTEDIP, server: localhost, request: "GET /?controller=UserAjaxController&action=status HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "REDACTEDDOMAINNAME"
2017/01/25 00:45:58 [error] 11#0: *56 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant tls - assumed 'tls' in /var/www/app/config.php on line 16" while reading response header from upstream, client: REDACTEDIP, server: localhost, request: "GET /?controller=UserAjaxController&action=status HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "REDACTEDDOMAINNAME"
2017/01/25 00:46:26 [error] 11#0: *56 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant tls - assumed 'tls' in /var/www/app/config.php on line 16" while reading response header from upstream, client: REDACTEDIP, server: localhost, request: "GET /?controller=UserAjaxController&action=status HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "REDACTEDDOMAINNAME"
2017/01/25 00:46:26 [error] 11#0: *56 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant tls - assumed 'tls' in /var/www/app/config.php on line 16" while reading response header from upstream, client: REDACTEDIP, server: localhost, request: "GET /?controller=BoardAjaxController&action=check&project_id=1&timestamp=1485304879&_=1485304526382 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "REDACTEDDOMAINNAME"
2017/01/25 00:46:58 [error] 11#0: *56 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant tls - assumed 'tls' in /var/www/app/config.php on line 16" while reading response header from upstream, client: REDACTEDIP, server: localhost, request: "GET /?controller=UserAjaxController&action=status HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "REDACTEDDOMAINNAME"
```

**Comment by fguillot** [comment]
@esquawk Did you solve your issue after all this time?

**Comment by fguillot** [comment]
@chamunks Your issue is not the same as the original ticket, @esquawk has a problem regarding IIS on Windows.
