### ISSUE TITLE
Need to be able to create tasks via Mailgun from multiple email addresses

### ISSUE THREAD

**Issue by SeAlgoAsoma** [kanboard/kanboard#2458]
At the moment, I can only create tasks by email from the single email address in my user settings. I have several email addresses I use from different places, I need some way to create tasks via mailgun from more than 1 address. 

I tried setting up several users but then it's confusing, tasks get assigned to the different users, etc.

**Comment by skorvek** [comment]
My  workaround was to create users for each email address and then assign them to a group which in turn owns the projects.   That allows me to use any of those email addresses to email in tasks, but yes, then they are assigned to those "fake" users. I couple that with a automatic action which makes all tasks in my backlog columns unassigned so they don't end up on my ocerview pages to workaround thale issue of information overload on my projects. Certainly not ideal, and thus multiple email aliases would be a welcome feature. 
Another thing I do is have several projects, one for each major category of tasks (areas of responsibility) to hold and vet tasks and ideas. I use a column in each to move tasks I will be actively working on to my active projects project and limit what is moved to keep me focused. That project has a swimlane for each of the placeholder projects and I can only have one task in each that is in the active column. It helps with staging ideas, but is a bit complex to set up and explain.

**Comment by SeAlgoAsoma** [comment]
Yeah, that approach has its own drawbacks. I had wanted my clients' employees to be able to assign tasks to each other too, it's not just for my own use. 

As it turns out though, as I posted elsewhere, mailgun intentionally strips all useful information from the emails I'm forwarding, tasks can't be forwarded through Mailgun unless you retype them by hand anyway, making this entire app and all the months I've spent trying to get it working in a usable manner a total loss for me.

**Comment by skorvek** [comment]
Still a useful feature request- please re-open.

**Comment by SeAlgoAsoma** [comment]
Reopens per request.

**Comment by fguillot** [comment]
Tickets related to Mailgun should be posted to the plugin bug tracker: https://github.com/kanboard/plugin-mailgun/issues

Thank you
