### ISSUE TITLE
You should make it VERY CLEAR that Mailgun prohibits quoted text in emails

### ISSUE THREAD

**Issue by SeAlgoAsoma** [kanboard/kanboard#2459]
### Expected behaviour

Tell us what should happen
1. Client emails me. Subject reads "Reminder". Body of email reads: "Bob, please remember to hammistat the veeblefetzers"
2. I receive email, forward it to my email address "add+kanboard@projects.sealgoasoma.com", the email address I set up for creating new tasks via email. Subject now reads: "RE: Reminder". Body now reads:
"--Begin Forwarded Message
From: Client@blahblah.com
Date: 6/17/16
Subject: Reminder

Bob, please remember to hammistat the veeblefetzers"
1. I receive notification that new task has been created in kanboard.
2. Next time I'm at work, I open Kanboard to see what I need to do.
3. I see new task. Title is "RE: Reminder". Description is:
   "--Begin Forwarded Message
   From: Client@blahblah.com
   Date: 6/17/16
   Subject: Reminder

Bob, please remember to hammistat the veeblefetzers"

[EDIT: I haven't the foggiest idea why this website is reformatting and renumbering steps 3-5 above as a second 1-3. Thanks, github, I'm quite capable of typing the numbers I want, you don't have to "correct" me by replacing them with wrong ones.]
### Actual behaviour

Steps 1-4 same
5. I see new task. Title is "RE: Reminder". Description is completely blank. I have no idea what the reminder was or who it was from. 
6. I have 6-week back and forth with Mailgun support before I find out they are intentionally removing quoted text
7. Much weeping
8. Wonder why I wasn't told at the very beginning of this process about this incredibly important (for my purposes) limitation... I was told the body of the email would go into the description. The quoted text is part of the body.
### Steps to reproduce

As described above
NB. I also tried removing "--Begin forwarded text" before forwarding... Didn't help.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.28
PHP version: 5.6.17
PHP SAPI: cgi-fcgi
OS version: Linux 3.12.52-20160119.106.ELK6.x86_64
Database driver: sqlite
Database version: 3.6.20
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by fguillot** [comment]
Tickets related to Mailgun should be posted to the plugin bug tracker: https://github.com/kanboard/plugin-mailgun/issues

Thank you
