### ISSUE TITLE
Mechanism for updating plugins

### ISSUE THREAD

**Issue by gramakri** [kanboard/kanboard#2463]
Background:
The Cloudron.io app allows one to easily install Kanboard and get automatic updates. The code for the app is here https://git.cloudron.io/cloudron/kanboard-app.

Problem:
Updates to Kanboard breaks installation if we have an outdated plugin. Recently, I updated the Cloudron app to 1.0.31 and we hit https://github.com/fguillot/kanboard/issues/2387. This was because a Rocket.Chat plugin was being used and it was at 1.0.1. Updating the plugin to 1.0.2 fixed the problem.

I am thinking of updating the Cloudron app the following way:

a) The Kanboard app can simply list the plugins from the plugin/ directory. Is there a better way to get the plugin list?
b) Get the version of plugin. I can do a crude grep for getPluginVersion in Plugin.php if this is pseudo-standard. Is there a better way to get this?
c) A compatibility table of plugin and supported Kanboard version. This information is listed here https://kanboard.net/plugins but not in the "code". Maybe plugins can have a simple manifest file of some sort which codifies what is in the README (Requirements section)?
d) Updating the plugin might be tricky, so I might just disable the plugin. Is there a mechanism to disable plugins but keep them in plugins/ folder? Alternately, Kanboard can do this automatically based on the values it got in c). This way kanboard installation doesn't get hosed completely because of an outdated plugin.

**Comment by gramakri** [comment]
@fguillot did you have any thoughts on how you would do this? I assume you will face similar issues with your SaaS hosting (or how do you solve it there?) ?

**Comment by fguillot** [comment]
- Plugins can now use the method `getCompatibleVersion()` to indicate the compatibility with the application.
- Now, a plugin is not loaded if an exception is raised. However, due to PHP limitations this system cannot trap all errors.
- This API endpoint https://kanboard.net/plugins.json list the compatibility between the kanboard version and plugins versions.
- The hosted version of KB allows only a subset of the plugins and all plugins are updated automatically for each tenant.

**Comment by gramakri** [comment]
@fguillot Thanks for adding this! Let me test this out in the Cloudron and get back.

**Comment by gramakri** [comment]
@fguillot Thanks, this seems sufficient. I have to figure out a nice way to parse out the getCompatibleVersion from the plugin's php file though...

(Also, I just updated the cloudron app to 1.0.39)
