### ISSUE TITLE
Update task comment count on auto-refresh of board view

### ISSUE THREAD

**Issue by gene-pavlovsky** [kanboard/kanboard#2464]
My git commit hook can add comment to tasks, as well as close tasks (using the API access).
If it closes a task, a few seconds later I can see the board view updates automatically - the task disappears. However if the hook only posts a comment, the comment count doesn't update. Even if I hover the mouse over the comment icon, the just added comment is displayed, but even then the count doesn't change. I didn't test other stuff but I would also take a look at other properties of the task card if they auto-refresh or not. It would be good if every property would auto-refresh.

**Comment by fguillot** [comment]
Because the board is refreshed only if the project modification date is modified and comment events are not taken into consideration at the moment (See class ProjectModificationDateSubscriber).

**Comment by gene-pavlovsky** [comment]
Got it. I hope you will find a way to implement it in the future.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
