### ISSUE TITLE
Showing description in task board

### ISSUE THREAD

**Issue by eddyemmer** [kanboard/kanboard#2468]
### Expected behaviour

Show description in task board view
### Actual behaviour

Is it possible to show the description in the task on the Board view? Now I see only the title.
### Steps to reproduce

1.
2.
3.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: Latest
- Database type and version: Mysql latest version
- PHP version: PHP 5
- OS: Windows ( Wampserver)
- Browser:Firefox

**Comment by fguillot** [comment]
The description is visible in a tooltip (icon at the bottom).

**Comment by eddyemmer** [comment]
Yes I know but is it possible to show it under the Title of the task? Which php file can I open for see the code of tasks?

**Comment by fguillot** [comment]
In the folder app/Template/board

**Comment by Happyflore** [comment]
hello i need the same solution,which php file to edit in folder app/Template/board
thank you in advance
