### ISSUE TITLE
"Show Google Avatar" setting should be in the "Avatar" page

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#2470]
"[x] Show Google Avatar" is shown on the "Integration" page but it would make more sense for it to be shown on the "Avatar" page (or both pages) in users' profiles.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
