### ISSUE TITLE
Feature request: automatic tags

### ISSUE THREAD

**Issue by eurodrew555** [kanboard/kanboard#2473]
### Expected behaviour

I have submitted feature request #1571 which is for using wildcard masks in search. The primary reason for this is to be able to filter my view to client using a standard naming of projects "CLIENT-NAME project".

As I'm not sure if this is going to be implemented, I may be able to replicate this workflow that I want using tags instead. To do this I would need an automatic action to create a tag (for the client name) on each task within a project.
### Actual behaviour

As above, this is a feature request for automatically adding a tag to each task in a project. When a new task is added I would like a specific tag added for that project. Should be OK to just create this automatic action when I create a new project, although the wildcard mask searching would make the end result (just displaying all projects from that client) much easier to achieve by just using a standard naming convention.
### Steps to reproduce

N/A - feature request
### Configuration

Application version: master (I'm on 1.0.31)
PHP version: 5.6.23
PHP SAPI: fpm-fcgi
OS version: Linux 4.5.5-x86_64-linode69
Database driver: sqlite
Database version: 3.7.17
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by regenduft** [comment]
+1, I need to have tags (or subtasks) beeing present whenever a task is created.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
