### ISSUE TITLE
Copy/paste in text box.

### ISSUE THREAD

**Issue by bitozoid** [kanboard/kanboard#2477]
Hi, when I create a new task, I can't copy/paste into the editor. Feature or bug?
- Kanboard version: 1.0.30
- Database type and version: Sqlite 3.7.17
- PHP version: 5.4.16
- OS: CentOS 7.2.1511
- Browser: Firefox 38.8.0

**Comment by entwisi** [comment]
ditto in 1.0.31

you can paste in title box fine and can use CTRL V in description/tags but right click context menu doesn't offer paste option in the latter two.

**Comment by NinjaPewPew** [comment]
I might not show it in the context menu, but it works just fine with the keyboard shortcut CTRL+V.

**Comment by fguillot** [comment]
Right click seems to be disabled in the Markdown editor.

**Comment by SDTipps** [comment]
I haven't figured out what's causing this exactly. I do know that copy/paste works fine in the MDE website demo. The only observable difference is the additional tag "CodeMirror-Empty" at the start of the description element.

**Comment by fguillot** [comment]
The text editor have been rewritten in v1.0.35 and CodeMirror is not used anymore. So this is working now.
