### ISSUE TITLE
Feature Request: Tag Filter (like Category Filter)

### ISSUE THREAD

**Issue by NinjaPewPew** [kanboard/kanboard#2481]
I love the new tag system! Currently I can filter for specific tag by using "tag:Tagname". That works great, but is a litte time consuming (for example if you want to filter for 2 or 3 tags) and requires you to know all tags. For categories we have a quick filter, where I can see all available categories I can filter and apply them with one click.

For tags I would love to have the same kind of quick filter. 

And if you want to make me even more happy, you could try to implement something like github uses for issue filtering.

![image](https://cloud.githubusercontent.com/assets/16925901/16835018/ca5ee37e-49b6-11e6-8feb-fd70b15b9f8e.png)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
