### ISSUE TITLE
Swimlanes height in Board view

### ISSUE THREAD

**Issue by ilisepe1** [kanboard/kanboard#2482]
When adding swimlanes, the height of each one of them in Board view mode, is the same across all of them based on the swimlane with the most tasks. It would be better to either give the option to the user to control it (and resize it dynamically) or be as tall as the tasks within it.
See the attachment for better understanding. 

![img](https://cloud.githubusercontent.com/assets/7242472/16838035/ca43a456-49cf-11e6-8f16-883e05e65451.png)

**Comment by fguillot** [comment]
Duplicate with #1932
