### ISSUE TITLE
Feature Request: Evidence Based Scheduling

### ISSUE THREAD

**Issue by ForeverTangent** [kanboard/kanboard#2484]
### Expected behaviour

It would be great if Kanboard supported Evidence Based Scheduling, especially since it already recording actual and estimated time tracking.

[Wikipedia](https://en.wikipedia.org/wiki/Evidence-based_Scheduling)
[Joel of Software](http://www.joelonsoftware.com/items/2007/10/26.html)

Basically just three things:
- Reporting of individual task velocity ( Estimated Time / Actual Time )
- A chart display of velocity.
- Monte Carlo simulation to predict completion.
### Actual behaviour

If nothing else at least adding a column to the "Analytics(Reporting)>Estimated vs actual time page" which lists the velocity of a task completion ( Estimated Time / Actual Time ).
### Steps to reproduce

(No Steps, requested feature)
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
Application version: 1.0.31
PHP version: 5.5.33
PHP SAPI: cgi-fcgi
OS version: Linux 3.2.61-grsec-modsign
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17

**Comment by fguillot** [comment]
Unfortunately, I didn't plan to add such feature to avoid too much complexity in the software.

Any contribution, pull-request or plugin to implement this feature is welcome.
