### ISSUE TITLE
Task comments preview on hover displays scrollbar, messing up layout

### ISSUE THREAD

**Issue by gene-pavlovsky** [kanboard/kanboard#2486]
One of my tasks has a lot of comments. In the board view, hovering over the comments icon in the task card displays a preview of these comments, which is too tall to fit on screen - a vertical scrollbar appears. This causes the board columns to resize, moving the task comments icon away from under the mouse cursor - making the comments preview hide, bringing the task comments icon back under the mouse. It repeats jumping like that ad nauseam.
![](https://i.imgur.com/SrpiLnE.png)
![](https://i.imgur.com/kE2VS1F.png)

**Comment by fguillot** [comment]
In Kanboard 1.0.39, the list of comments are displayed in a modal box instead of a tooltip. You should not have this problem anymore.
