### ISSUE TITLE
Add automatic action "(Re-)open task when moved from a column"

### ISSUE THREAD

**Issue by gene-pavlovsky** [kanboard/kanboard#2487]
Sometimes I close a task by mistake. E.g. 
- I specified wrong task id in my git commit message
- My [git commit hook](https://github.com/gene-pavlovsky/kanboard-git-hooks/) moves the task to Done column
- Kanboard closes the task due to "Close task when moved to Done column" auto-action

I would like to be able to
- Drag the erroneously closed task from Done back to another column (Ready, Backlog, etc.) - for manual correction
- Setup automatic action which would (Re-)open a task if it's moved away from (the Done) column - usable for manual correction as well as for my commit hook - I would improve the amended commit handling to do that

**Comment by NinjaPewPew** [comment]
Automatic Action for re-opening a task would be pretty useful for us.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
