### ISSUE TITLE
Task limits counters when using a custom search filter

### ISSUE THREAD

**Issue by gene-pavlovsky** [kanboard/kanboard#2488]
I have set a task limit for my `Ready` column at 3 tasks, and currently there are 3 open tasks there, the counter displays `3/3`.
When I type some custom search filter query (other than the default `status:open`), which matches only some or none of the tasks in the `Ready` column, it will then display `0/3` or `1/3`, for example. Making it look like the column is not full with tasks yet, and allowing to drag tasks from `Backlog` to `Ready` without changing the background to the warning red. Clearing the filter box then shows that `Ready` is actually overfilled.
Not sure if this is intended behavior or not, but to me it seems counter-intuitive. Would it make more sense to apply the filter query only to columns that don't have task limits? E.g. it would search the backlog, but not the `Ready` and `Work in progress` columns. Or filter all columns but display total number of tasks in the column for columns with task limit, not the number of search results? Or display it as `1 out of (2/3)` - meaning task limit is 3, total of 2 tasks in there, 1 task matches the search query?

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
