### ISSUE TITLE
data filters not working currectly

### ISSUE THREAD

**Issue by esclkm** [kanboard/kanboard#2489]
date filters(creation, updated, due) not working with some filters like:
1/ status:open due:< next Friday (next also not working
2/ status:open due:+ 7 days
3/ status:open due:< + 7 days

**Comment by fguillot** [comment]
You have to use double quotes when there are spaces into the attribute value: `due:"+ 7days"`

**Comment by esclkm** [comment]
so - how i must send query

**Comment by godspeedyou** [comment]
1/ status:open due:< "next Friday"
2/ status:open due:"+ 7 days"
3/ status:open due:< "+ 7 days"

**Comment by godspeedyou** [comment]
I have a similar issue:

`tag:"simon says" assignee:"david"`

Expected:
All tasks with tag "simon says" and assignee david.

Actual:
"".
Nothing/Null.

When I execute both queries separately, they work.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
