### ISSUE TITLE
Settings > automatic actions - sort order

### ISSUE THREAD

**Issue by gene-pavlovsky** [kanboard/kanboard#2493]
I have several of automatic actions, many of them are about assigning a color based on task category. Then there are others. Recently I've added new categories and assign color automatic actions for them, these show up at the bottom of the list. I'd like to be able to take a better look at my automatic actions, that is have them grouped by type of action, sorted by name or something like that. 
The current ordering by automatic action creation date is not that helpful. It would also be nice if somehow the list could be displayed in more condensed. Currently each item takes up too much height, so all items can't fit on screen in my case.

**Comment by fguillot** [comment]
Duplicate with #304
