### ISSUE TITLE
Gantt page cannot be load when project have a lot of tasks

### ISSUE THREAD

**Issue by Kolesar** [kanboard/kanboard#2494]
### Expected behaviour

When click on Gantt expect Gantt chart
### Actual behaviour

Continuously loading in FF browser and browser frees, on Chrome get error: Page is unresponsive
### Steps to reproduce
1. Project have more than 20 opened tasks
2. Click on Gantt
### Configuration

Application version: master
PHP version: 5.6.23
PHP SAPI: apache2handler
OS version: Linux 3.10.0-327.22.2.el7.x86_64
Database driver: mysql
Database version: 5.6.31
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
