### ISSUE TITLE
Day view tasks revert back to All Day

### ISSUE THREAD

**Issue by lespaul4** [kanboard/kanboard#2495]
### Expected behaviour

Tell us what should happen
When tasks are dragged from all day (very top) to a particular time slow (eg. 3pm) the task details do not update. 

### Actual behaviour

Tell us what happens instead

Although you can drag the task to a particular time slot (day view), when you refresh the page it reverts back to All Day and goes to the very top. 

Only those tasks that have been "hard set" (ie. set in details view) are listed and persistent. Tasks dragged over will revert back.

### Steps to reproduce

1. Calendar > Day
2. Select any item from top (all day)
3. Move task to any time slot (item will move and stay properly, but...)
4. Refresh view (task will revert back)

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.31
PHP version: 5.6.23-0+deb8u1
PHP SAPI: apache2handler
OS version: Linux 4.4.13-v7+
Database driver: sqlite
Database version: 3.8.7.1
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by fguillot** [comment]
The due date do not contains the time. Actually the drag and drop into a time slot should not be allowed.

**Comment by lespaul4** [comment]
Thanks fguillot. Im new to Kanboard and I absolutely love it! Thank you so much for your creation.
