### ISSUE TITLE
work in progress limit = 0 -> to highlight non empty columns.

### ISSUE THREAD

**Issue by aslmx** [kanboard/kanboard#2497]
feature request:

i'd like to have a column with literally zero max WIP. Hence the column will be always red until all tasks are moved to other columns. If i set the WIP to 0 it means no-limit. 

Proposal: use -1 for no limit.

background: we use the kanboard not for real kanban like working, but we use the columns to represent coworkers and the swimlanes to represent weeks, so we can plan the weeks for our coworkers. I have one "backlog" column where the tasks are initially created in, i want to have a visual highlight if the column is not empty before the week starts.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
