### ISSUE TITLE
How to filter tasks due today and without due time?

### ISSUE THREAD

**Issue by artkpv** [kanboard/kanboard#2498]
### Expected behaviour

With filter 'status:open due:none due:<=today' I see tasks due today or overdue or without due time.
### Actual behaviour

With the filter I don't see tasks without due time.
### Steps
1. Set filter 'status:open due:none due:<=today'
### Configuration

Application version: 1.0.31
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2189.0 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
