### ISSUE TITLE
scrum sprint plugin

### ISSUE THREAD

**Issue by esclkm** [kanboard/kanboard#2502]
I fast crete little plugin for your kanboard:
do you intrestiong in it?
sorry.... i dont know how to write you personally
![image](https://cloud.githubusercontent.com/assets/780145/17013966/58307802-4f2a-11e6-97a7-aea56d4aa4c3.png)

**Comment by NinjaPewPew** [comment]
Is the source code available on github?

**Comment by esclkm** [comment]
not at this moment) if there will be people intresting in it I will

**Comment by fguillot** [comment]
You should publish the code of your plugin somewhere. If you would like to publish the plugin on the website follow this link: https://github.com/kanboard/website#how-to-add-a-new-plugin-to-the-list

**Comment by ucoding** [comment]
@esclkm Could you publish the Scrum sprint plugin to public? I like this. thx.

**Comment by esclkm** [comment]
thanks
https://github.com/esclkm/kanboard-sprints 
)))
