### ISSUE TITLE
Beanstalkd

### ISSUE THREAD

**Issue by mauriziodidomenico** [kanboard/kanboard#2503]
### Actual behaviour

after: ./kanboard worker

[fonzi@kanboard kanboard]$ ./kanboard worker
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Kanboard\Core\User\UserSession::initialize() must be of the type array, null given, called in /home/fonzi/git/kanboard/app/Core/Queue/JobHandler.php on line 75 and defined in /home/fonzi/git/kanboard/app/Core/User/UserSession.php:35
Stack trace:
#0 /home/fonzi/git/kanboard/app/Core/Queue/JobHandler.php(75): Kanboard\Core\User\UserSession->initialize(NULL)
#1 /home/fonzi/git/kanboard/app/Core/Queue/JobHandler.php(47): Kanboard\Core\Queue\JobHandler->prepareJobSession(6)
#2 /home/fonzi/git/kanboard/app/Core/Queue/QueueManager.php(71): Kanboard\Core\Queue\JobHandler->executeJob(Object(SimpleQueue\Job))
#3 /home/fonzi/git/kanboard/app/Console/WorkerCommand.php(26): Kanboard\Core\Queue\QueueManager->listen()
#4 /home/fonzi/git/kanboard/vendor/symfony/console/Command/Command.php(259): Kanboard\Console\WorkerCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/fonzi/git/kanboard/vendor/symfony/con in /home/fonzi/git/kanboard/app/Core/User/UserSession.php on line 35

### Configuration
Application version: master
PHP version: 7.0.7
PHP SAPI: apache2handler
OS version: Linux 4.4.11-1-ARCH
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (X11; CrOS x86_64 8172.62.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by fguillot** [comment]
You should try with a more recent version of Kanboard, the worker have been improved a lot since the time.

**Comment by easterwood** [comment]
Hi,

we have a similar problem with the kanbaord jsonrpc API:
```
error-kanboard-srv.log:[Mon Oct 30 09:00:51.206947 2017] [:error] [pid 15989] [client 192.168.129.33:42254] PHP Catchable fatal error:  Argument 1 passed to Kanboard\\Core\\User\\UserSession::initialize() must be of the type array, null given, called in /var/www/html/kanboard/app/Api/Middleware/AuthenticationMiddleware.php on line 34 and defined in /var/www/html/kanboard/app/Core/User/UserSession.php on line 35
error-kanboard-srv.log:192.168.129.33 - <username> [30/Oct/2017:09:00:51 +0100] "POST /jsonrpc.php HTTP/1.1" 500 - "-" "PostmanRuntime/6.2.5"
error-kanboard-srv.log:192.168.129.33 - - [30/Oct/2017:09:01:37 +0100] "GET /?controller=UserAjaxController&action=status HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
error-kanboard-srv.log:192.168.129.33 - - [30/Oct/2017:09:02:37 +0100] "GET /?controller=UserAjaxController&action=status HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
```

The request looks as follows:
```
Header:
Content-Type:application/json
Authorization:Basic dXNlcm5hbWU6cGFzc3dvcmQ=

Body:
{"jsonrpc": "2.0", "method": "getVersion", "id": 1}

Response: 500 Internal Server Error
```

**Configuration**

Application version: 1.0.48
PHP version: 5.4.16
PHP SAPI: apache2handler
OS version: Linux 3.10.0-514.26.2.el7.x86_64
Database driver: sqlite
Database version: 3.7.17
