### ISSUE TITLE
Task creation description editor turns on H button on entering one '-'

### ISSUE THREAD

**Issue by gene-pavlovsky** [kanboard/kanboard#2505]
### Expected behaviour

When creating a task and writing the description, when I enter a single `-` character, I'm intending to create a list. I expect nothing special to happen until it's clear whether this is a list or header underline. In my opinion, wait until there are two characters, if `--`, this is a header underline, or if `-`, this is a list. Personally, I think it's not necessary to display any indication or switch the font to big and bold for header - e.g. GitHub's Markdown editor's button are just for inserting something in the editor, but writing something in the editor doesn't change font or toggle the buttons.
### Actual behaviour

I enter a single `-` and the font becomes big and bold, while the `H` button becomes selected.
### Steps to reproduce

Enter a line of text, add newline, then type `-`. Or, enter a list item `- foo`, then press newline, the editor will auto-insert a `-` for next list item, but it will be in bold and big font.
### Configuration

1.0.31

**Comment by fguillot** [comment]
The text editor have been rewritten in v1.0.35 and CodeMirror is not used anymore. It should work now.

Thank you.
