### ISSUE TITLE
Heroku Redeploy Issue (Possibly Postgres Related)

### ISSUE THREAD

**Issue by mswbull** [kanboard/kanboard#2506]
### Expected behaviour

I'm expecting to be able to deploy Kanboard to Heroku and then redeploy if I need to add plugins, etc.
### Actual behaviour

I've deployed Kanboard to Heroku using the standard PHP Buildpack and Postgres (heroku-postgresql:standard-0).

The initial deployment works great, however if I re-deploy the code I start to get strange behaviour.

It would appear reading from the Postgres database becomes temperamental (can only occasionally login) and writing becomes impossible (can't add new users, tasks, etc.)
### Steps to reproduce
1. Deploy to Heroku.
2. Provision Postgres DB.
3. Redeploy to Heroku.
4. Attempt to login and create/update a record.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: v1.0.31
- Host: Heroku Default PHP Buildpack
- Database type and version: Postgres v9.5.3
- PHP version: php (7.0.8)
- OS: OS X 10.11.6
- Browser: Chrome / Safari

**Comment by fguillot** [comment]
You should contact Heroku's support because I have no idea what could be the problem.
