### ISSUE TITLE
Hook needed for dropdown at boards column

### ISSUE THREAD

**Issue by Vertumnus** [kanboard/kanboard#2507]
### Expected behaviour

We need a hook at the dropdown menu of columns in the board. It's needed to implement a column (and swimlane) specific feature inside a plugin.

Affected file: Template / board / table_column.php

Suggested implementation to call the new Hook:
<?= $this->hook->render('template:board:column:dropdown', array('swimlane' => $swimlane, 'column' => $column )) ?>

### Actual behaviour

There is no Hook at the place. It would be possible to replace the whole file by a plugin, but this is not satisfying.

### Workaround

We modified the file and added the requested Hook. But this has the disadvantage, we have to consider the modification at each update and reconstruct the modification.

**Comment by fguillot** [comment]
The new hook have been added into master.
