### ISSUE TITLE
Feature Request: Sort a column by Priority

### ISSUE THREAD

**Issue by Vertumnus** [kanboard/kanboard#2508]
### Background

Some columns in our project have to be sorted by the specified priority in the tasks to ensure the wanted progress order.
### Expected behaviour

We need a new function in the dropdown menu of the boarders column to sort the affected column by priority. The function shall take effect only on the tasks for the affected column and the affected swimlane. The ordering shall adjust the positions of these tasks. To support different business needs, there should be one ordering in ascending direction and one in descending. (In our case it must be ascending, because the tasks with lower priority number are more important.)
### Actual behaviour

There is no possibility to order tasks this way.

We implemented a Plugin to make the feature available in our project. On interest I can share the solution. To realize the functionality we had to add a hook, see #2507.

**Comment by Chaosmeister** [comment]
Hey! we just switched to using the priority value. Can you share your plugin?

**Comment by Chaosmeister** [comment]
At the moment I use a simple SQL Statement if requested:

```sql
update tasks
set position=3-priority
```

where 3 = `numbers of priorities - 1` 
(we use P0 for Low priority and P3 for critical tasks)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
