### ISSUE TITLE
Feature request: search on closed date

### ISSUE THREAD

**Issue by eurodrew555** [kanboard/kanboard#2509]
It would be really useful to be able to search based on when a task was closed.

For example, you can current search on when a task is due:

due:2015-07-01

It would be great if you could search to find tasks that have been recently closed:

closed:today
closed:yesterday
closed:2016-07-01 (show tasks closed on a specific date)

closed:Xdays (show tasks closed in the last X days)
e.g. closed:7days
e.g. closed:14days

EDIT - just going through all the search options and it looks like modified:today (etc) provides what I'm after.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
