### ISSUE TITLE
Under Windows Server 2008R2: How to schedule the required daily cron job

### ISSUE THREAD

**Issue by MikeHess16** [kanboard/kanboard#2512]
### Expected behaviour

How to configure the required daily cron job on a Windows Server?
### Actual behaviour

The required daily cron job is based on the Kanboard command line feature. I guess it's only working from Linux bash.
### Steps to reproduce

The existing documentation only explain how to configure the cronjob on Linux systems. 
https://kanboard.net/documentation/cronjob
How to configure a Windows Server "Scheduled Task" for that?
1. 
   2.
   3.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Application version: 1.0.31
- PHP version: 7.0.8
- PHP SAPI: apache2handler
- OS version: Windows NT 6.1
- Database driver: sqlite
- Database version: 3.8.10.2

**Comment by alexlewer** [comment]
I think you should be able to get this to run via a .bat file on Windows, using the command:

`php kanboard cronjob`

(This assumes the .bat file is in the root of the Kanboard install).

**Comment by fguillot** [comment]
I updated the documentation for Windows: https://github.com/kanboard/kanboard/blob/master/doc/cronjob.markdown#configuration-on-microsoft-windows-server

Basically, create a batch file and add a new task to the windows scheduler.

**Comment by mauricio-sonegatti** [comment]
I had a similar problem, as my website is on another drive, I had problems with the context that the cronjob was running.
For now I made put my .bat inside my kanboard folder with the code:

```
cd /D E:\WEBSITES\site1\Kanboard\
"C:\Program Files (x86)\PHP\v5.5\php.exe" -f "E:\WEBSITES\site1\Kanboard\kanboard" cronjob
```

Running with my AD user or local "Users" group was OK, running with the "IUSR_USRS" group didn`t work.
