### ISSUE TITLE
Debug not working

### ISSUE THREAD

**Issue by JPascalTaipei** [kanboard/kanboard#2513]
Hi, 

I am trying to set debug mode, but it does not seem to work. 

In my config file there is: 

// Enable/Disable debug
define('DEBUG', true);

// Available log drivers: syslog, stderr, stdout or file
define('LOG_DRIVER', 'file');

// Log filename if the log driver is "file"
define('LOG_FILE', __DIR__.DIRECTORY_SEPARATOR.'data'.DIRECTORY_SEPARATOR.'debug.log');

I set Kanboard inn /var/www/kanboard, so I expect to find debug.log file in /var/www/kanboard/data. 

Is there anything that I am doing wrong? 

Cheers!

**Comment by eSkiSo** [comment]
Put the directory before debug.log exactly like the FILES_DIR but replace 'files' by 'debug.log'

**Comment by JPascalTaipei** [comment]
I run Kanboard on Ubuntu 16.04. 

I know have the following in my config.default.php: 
===========================
// Enable/Disable debug
define('DEBUG', true);

// Available log drivers: syslog, stderr, stdout or file
define('LOG_DRIVER', 'file');

// Log filename if the log driver is "file"
define('LOG_FILE', 'data'.DIRECTORY_SEPARATOR.'debug.log');
===========================

But debug still does not seem to work:
- in /var/www/kanboard/data no debug.log
- if I manually create it (touch debug.log then chown www-data:www-data debug.log) it remains empty. 

I also tried to set it to 'syslog' and was expecting to see something in /var/log/syslog, but nothing appeared. 

If you have any hint you would like to share; you're more than welcome!

**Comment by fguillot** [comment]
Did you rename the file `config.default.php` to `config.php` (or create a new `config.php`)?

**Comment by JPascalTaipei** [comment]
Ah! Ha ha! Merci!
