### ISSUE TITLE
Project priority setting & note confusing or broke

### ISSUE THREAD

**Issue by danigrithos** [kanboard/kanboard#2516]
### Expected behaviour

Based on note: "If you put zero to the low and high priority, this feature will be disabled."
I should be able to set P0 as the High Priority and P(>0) as the Low Priority.
### Actual behaviour

If I set High Priority as P0 it disables priority despite Low Priority being set to non-zero. However according to the note mentioned above, the feature should not be disabled unless I also set the Low Priority to 0.
### Steps to reproduce

1.Set Low Priority to 5
2.Set High Priority to 0
3.Attempt to edit a task and the priority field is gone
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.31
PHP version: 5.4.16
PHP SAPI: apache2handler
OS version: Linux 3.10.0-327.22.2.el7.x86_64
Database driver: postgres
Database version: 9.3.13
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by NinjaPewPew** [comment]
More or less the same as #2517.

**Comment by varod** [comment]
+1 we are using inversed priority ; i've tested to change the order and priority field disappeared. it tooks me time to understand it was link to the setting : 
Low Priority = 4
High Priority = 0

**Comment by woosting** [comment]
> If I set High Priority as P0 it disables priority despite Low Priority being set to non-zero. However according to the note mentioned above, the feature should not be disabled unless I also set the Low Priority to 0.

I think this part is fixed? At leased I just checked on 1.034 with both:

> Low Priority=0
> High Priority=5

and

> Low Priority=5
> High Priority=0

and the settings the feature remained enabled (setting both to `0` indeed disabled the feature).

**Comment by fguillot** [comment]
The priority is now always displayed on latest version of KB.
