### ISSUE TITLE
Priority option disappears

### ISSUE THREAD

**Issue by Barnesy35** [kanboard/kanboard#2517]
### Expected behaviour

Tell us what should happen

I set the highest priority to P0 , the default to P1 and the lowest priority to P2. 
### Actual behaviour

Tell us what happens instead

For some reason it's removed the priority option from all of the tasks within that kanboard. 

It has also removed the Priority dialog box from the main task dialog box
### Steps to reproduce

1.Set highest priority to 0
2. Set default to 1 
3. Set lowest priority to 2 
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.30 
- Database type and version: 3.13.0
- PHP version: 7.0.7
- OS: Windows 8.1 Pro with Media Centre 64-bit (6.3, Build 9600)
- Browser: Google Chrome 52.0.2743.82 m

**Comment by NinjaPewPew** [comment]
In version 1.0.31 there is a warning telling you that setting the high or low priority to 0 will disable the feature.

![image](https://cloud.githubusercontent.com/assets/16925901/17128856/da32e798-530f-11e6-92e0-a3076bca5e7e.png)

**Comment by Barnesy35** [comment]
Thanks, NinjaPewPew.

Yeah I did get that warning but read it as having 0 for both the high and the low at the same time. 

Apparently a lot of big companies work in the way that P0 is the highest. All I am trying to do is invert the default P levels so 2 is low instead of high. 

Thanks, 

Mike

**Comment by woosting** [comment]
Isn't this resolved by now (see [my response / test results](https://github.com/kanboard/kanboard/issues/2516#issuecomment-275115150)).

**Comment by fguillot** [comment]
It should not happens anymore with the latest version of Kanboard.
