### ISSUE TITLE
How to override a model in a plugin?

### ISSUE THREAD

**Issue by stinnux** [kanboard/kanboard#2518]
I would like to enhance the existing subtask_time_tracking table with a field where you can enter a comment. 

I can change the schema (or introduce another table). I can override the template to show the necessary information. 

But how can i override the SubtaskTimeTrackingModel? 

As an alternative it would also be okay to completely disable to Time Tracking option within the tasks menu and add a menu item through the plugin. But i don't know how to disable a menu item.

Any suggestions?

As an alternative i could change kanboard directly and send in a PR.

**Comment by fguillot** [comment]
- Create a new class that inherit from the original one
- Use your own class instead of the original by changing the container, something like that: `$container['subtaskTimeTrackingModel'] = function($c) { return new YourClass($c); };`

**Comment by alefaucheur** [comment]
Hello,
would it be possible to have this example a bit more detailed please?
Thank you ahead of time.

**Comment by fguillot** [comment]
You have an example here for the formatters but the same concept can be used for models: https://github.com/kanboard/kanboard/blob/master/doc/plugin-overrides.markdown#formatter-overrides
