### ISSUE TITLE
Feature Request: Random colors for tasks

### ISSUE THREAD

**Issue by wucherpfennig** [kanboard/kanboard#2520]
### Expected behaviour

New Option to assign random colors to new tasks
### Actual behaviour

One default color
### Configuration
- Kanboard version: 1.31

**Comment by cdgeelen** [comment]
Hi,

I've took the liberty to write a plugin for this. See: https://github.com/cdgeelen/kanboard_plugin_randomColorSelector

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
