### ISSUE TITLE
Bug with attachments.

### ISSUE THREAD

**Issue by Kharalampidi** [kanboard/kanboard#2526]
### Expected behaviour

Attachments are  hidden, but exists.

And after uploading non image file (zip) everything was good :)

Before uploading Slack*.zip (image already exists)

![2016-07-27 18-40-51](https://cloud.githubusercontent.com/assets/11192488/17181710/b15edb0e-5429-11e6-80ee-7d0e6ebad6de.png)

and after uploading zip file

![2016-07-27 18-36-08](https://cloud.githubusercontent.com/assets/11192488/17181597/62bcac38-5429-11e6-8e2e-9b6c1186cebf.png)

### Steps to reproduce

1. Upload image (jpg/png) in new task
2. Now you see this bug :) (or not)

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.31 (latest master)
- Database type and version: Mysql 5.5.49-0ubuntu0.14.04.1
- PHP version: PHP 5.6.23-2+deb.sury.org~trusty+1
- OS: Ubuntu 14.04
- Browser: Chrome

Sorry for my english :)

**Comment by fguillot** [comment]
The regression introduced by PR #2439 is now fixed in master. Thanks!
