### ISSUE TITLE
disabled projects are not shown anymore

### ISSUE THREAD

**Issue by survietamine** [kanboard/kanboard#2527]
### Expected behaviour
When a user disable a project, he should be able to re-enable it.

### Actual behaviour
when a user that is not admin disables some project, he cannot re-enable it.
That's because the disabled project is not shown in projects list.

### Steps to reproduce

1. go to some project's preferences (as a user not admin)
2. disable the project
3. check projects list, the disabled project is no more listed.

Only admins can re-enable the project. The user can too, but he must know the project ID and provide it in the URL.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.31
- Database type and version: sqlite 3.8.2
- PHP version: 5.5.9
- OS: Ubuntu server 14.04.4 (openvz container in Proxmox)
- Browser: Chromium 51.0.2704.79 (64-bit)

**Comment by fguillot** [comment]
It's now fixed in the development branch. Thanks.
