### ISSUE TITLE
Closing a task

### ISSUE THREAD

**Issue by alefaucheur** [kanboard/kanboard#2528]
### Expected behaviour

When we close a task (not a subtask) we should evaluate its performance.
As we select fields when creating a task we should have same behavior at closing.
Why? How to remember we did something good or bad ? avoid reproducing same mistake ?
Make sure action / task contribute to the project.

We can plan well, we can make mistake, we are human.
How to improve your system/project/whatever for next time? By tracking what when wrong and finding the root cause.

When closing, Why not revalidate same parameters setup at Add new task time?
We open the same form,  complete it ; we add tags , time spent (may be also add a new cost field?)
### Actual behaviour

Yes/No close option

**Comment by schouinard** [comment]
You are describing a step in your personal process, not a feature. I wouldn't want that in my board. Done is done, if you need to do stuff before you close a task then it is another column in your process.

**Comment by alefaucheur** [comment]
Hello, 
I believe task fields value do really matter in the long run, this is why i am concerned about adjusting their values to make them as accurate as possible. If everything is just fine then it's another "Yes" click (2 sec) otherwise it allow user to modify value at the right time.

Example: 
New task creation -> fields could be blank
At closing time -> fields must be fulfilled ether manually or automatically.
Then a new feature would be to add a comment (or let's say a tag or drop-box) at closing time to specify something.

Thank you for your feedback, have a good day.

**Comment by fguillot** [comment]
Unfortunately, I didn't plan to add such feature to avoid too much complexity in the software.
