### ISSUE TITLE
EXport Tags (.csv)

### ISSUE THREAD

**Issue by alefaucheur** [kanboard/kanboard#2529]
### Expected behaviour

2°) Export Tags in excel/Csv format
Can you add tags value in export template?
or explain how to make a plugin by our own to do so.
### Actual behaviour

No way to get an extract of these values

**Comment by fourier** [comment]
I would vote for this, a problem for us is what tags are not exported together with tasks

**Comment by fguillot** [comment]
This is now available in the development branch.
