### ISSUE TITLE
[Enhancement] Customize columns order/presence and default sorting in list view

### ISSUE THREAD

**Issue by Biniou180** [kanboard/kanboard#2531]
I open this ticket as a contributor of Framasoft projects, and particularly Framaboard which is based on Kanboard.
### Actual behaviour

When displaying tasks in list views, there is one table with columns in this order: 
`Id     Swimlane    Column  Category    Title   Assignee    Due date    Status`

By default, the tasks are sorted by Id (descending).
### Expected behaviour
- Most of the time, the user is not interested by the task ID, but more often by the due date. Is it possible to sort by due date descending, by default ? (or best: let the user choose the default sorting)
- The most important information for a user to see quickly are the task name, assignee, due date and status. But these columns are at the end of the table, thus are less easy to read quickly. Could it be possible to rearrange the columns to show at least the due date more early in the table? (or again, let the user sort the columns as he prefers and memorize this choice)
- A lot of our users do not use all functionalities of kanboard (i.e. categories, swimlanes). Therefore these columns are often empty at the beginning of the table. Is it possible to let the user choose which columns he wants to see, or at least let them push these unused columns at the left end of the table as explained in the second bullet above?
- why not add the priority of the task, to let user sort tasks by priority?

Thanks again :)
### Configuration

Tested on Framaboard (=Kanboard 1.0.25) and Kanboard 1.0.31

**Comment by fguillot** [comment]
The layout has been changed since you posted this ticket. It should be better now, if not, then contribute :)

**Comment by Biniou180** [comment]
I've seen the modifications, it is indeed a lot better! :)
Thanks a lot! I will discuss with our users if they like the new list view (but from my point of view, it's ok like this)
Have a nice day :-)
