### ISSUE TITLE
Subtask timesheet "Time Spent" not being calculated

### ISSUE THREAD

**Issue by kgeil** [kanboard/kanboard#2532]
First off, thank you for the wonderful application.  I've been using it for a week now, and it's great so far.  I am having a bit of trouble getting the time tracking to work, and I'm hoping someone can help.  

Another issue which may be related, is that when I click on the calendar, sometimes I see my subtasks on the days for which I used the timer, and sometimes I don't.

Details are below: 
### Expected behaviour

When I click the "start timer" button, work for  a period of time, then click "stop timer", then go to the Time Tracking menu, the "Time Spent" column should show the differential between the "Start" column, and the "End" column
### Actual behaviour

"Time Spent" columns all show 0.00 hours, regardless of whether tasks are open or closed.
Example pasted from Kanboard Time tracking: 

User    Subtask ▼         Start   End Time spent
Kevin deploy server updates for 2015 and prior  07/29/2016 14:26    07/29/2016 16:03    0.00 hours
Kevin Review Collections, deploy updates        07/29/2016 11:16    07/29/2016 13:32    0.00 hours
### Steps to reproduce
1. Start timer
2. Stop timer
3. click time tracking menu.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.31
PHP version: 5.5.9-1ubuntu4.17
PHP SAPI: apache2handler
OS version: Linux 3.16.0-30-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

Thank you!!

Kevin

**Comment by kgeil** [comment]
So, I did a bit of debugging on this, and I found that the function SubtaskTimeTrackingModel.getTimeSpent($subtask_id, $user_id) has a variable called $hook, which has an assignment: $hook = 'model:subtask-time-tracking:calculate:time-spent';  This triggers the second (of 3) return statements in the function: 

`232      if ($this->hook->exists($hook)) {`
`233             return $this->hook->first($hook, array(`
`234                 'user_id' => $user_id,`
`235                 'start' => $start,`
`236                 'end' => $end,`
`237             ));`
`238         }`

If I comment out the assignment statement, subtask time tracking works as I expect it to: automatically calculating the value of time spent based on a calculation on  timer start and timer stop, which is performed by the getHours function called in the following return statement:

`240         return $this->dateParser->getHours($start, $end);`
`241     }`


At this point, I'm assuming that ` $hook = 'model:subtask-time-tracking:calculate:time-spent';` was a piece of debugging code that was left in?  I am definitely a rookie as far as oop, and hooks in PHP code, so if someone could offer some advice, it would be greatly appreciated. I'm not sure what the hook is supposed to do, and thus am not sure what I'm disabling.


Thanks again,

Kevin

**Comment by Imbasaur** [comment]
What i found out is Task's time_spent getting overwritted by sum of task's subtasks. This happens when you click 'stop' in timer, which triggers subtaskTimeTrackingModel.updateTaskTimeTracking. I think it should sum Task.time_spent and subtasks time_spent.

**Comment by kgeil** [comment]
Thanks Imbasaur, I'm going to upgrade to the new version soon, and will play with the code to the best of my ability.

Kevin

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
