### ISSUE TITLE
[FR] Re-Implementation "individual column scrolling" option

### ISSUE THREAD

**Issue by NinjaPewPew** [kanboard/kanboard#2536]
With 1.0.32 the option to enable/disable "individual column scrolling" was removed. I really think that is sad, because I liked the option very much. It's hard to explain, but I think the function had his advantages. I in fact always worked with "individual column scrolling" turned on.

A few reasons I believe it was useful:
- Scrolling in long task list, without losing the page header (navigation, project selection, etc)
- Easily compare task with task from other columns (in different list positions)

I hope that the option will be re-implemented in the future.

**Comment by NinjaPewPew** [comment]
I found the reason why it was removed #1932.

**Comment by antn89** [comment]
Yes, the same to @NinjaPewPew , so sad :))

**Comment by zoidy** [comment]
The fact the scrolling option was removed is a deal-breaker for me. If you have swimlanes with a lot of tasks, there is a lot of scrolling to do. I'd love to see the option to enable this come back. As of now, I've gone back to 1.0.31.

**Comment by garettmd** [comment]
+1 This is a big deal and something that will hinder adoption at my organization. At least have the option to re-enable max height, for those that want it

**Comment by anae211** [comment]
+1 This is a huge down fall to upgrading kanboard to 1.0.32. I love lots of the new features but really need the scrolling back. My team has an average of 15 tasks in each of their columns and is a huge nuisance to collapse tasks just to move one (also collapsing tasks means you cant tell what task is what). Please bring this back!

**Comment by fguillot** [comment]
Well, don't hesitate to contribute guys.

**Comment by anae211** [comment]
I do not see where this has been fixed
