### ISSUE TITLE
Default task assignee in board config

### ISSUE THREAD

**Issue by jbarotin** [kanboard/kanboard#2537]
Hi, 

Currently, when I create a new task, I am directly assigned to this task. 

I using Kanboard to follow work of different people on a very different domain. So I created one board by people. But, when I create a task in these board, I'd like to see dedicated people configured by default on the task (not me).

Do you know a way to change that comportment ?

**Comment by varod** [comment]
+1 in my case I would like to find a way a new task is without assignee by default. maybe I have not found the settings.

**Comment by mlbarrow** [comment]
The way that I have solved this issue is to create an automatic action for
the board:
[image: Inline image 1]

*michael at barrow dot me*
+1.541.600.2027

"Do not anticipate trouble, or
worry about what may never happen.
Keep in the sunlight." -- B. Franklin

**Comment by jbarotin** [comment]
Mmm @mlbarrow obviously it do the job... but I have to set a automatic action for each cols of my board.

**Comment by jbarotin** [comment]
Here it is, I upgraded Kanboard. I think a "all" options in column setting of the automatic action "assign task to a specific user" should be greatfull

**Comment by mlbarrow** [comment]
Do you not use a traditional kanban style workflow where tasks start in a
particular column and then move to other columns as they progress through
the workflow?

Note: I am not saying that your request is invalid; I'm merely trying to
understand how you're using the tool.

*michael at barrow dot me*
+1.541.600.2027

"Do not anticipate trouble, or
worry about what may never happen.
Keep in the sunlight." -- B. Franklin

**Comment by jbarotin** [comment]
Good question, no I'm not using as a strict Kanban workflow.

It's a kind a mix between scrum and kanban : typically my columns are "backlog", "next sprint backlog" and "current sprint backlog", "in progress", "in validation", "terminate".  So a task can be created in the 3 first columns (and if it is urgent, but that's exceptional in the "in progress" col).

**Comment by fguillot** [comment]
In Kanboard 1.0.39, the default assignee is not the creator anymore.
