### ISSUE TITLE
Plugin rocketchat doesn't show url of task in message notification. 

### ISSUE THREAD

**Issue by antn89** [kanboard/kanboard#2538]
### Expected behaviour

Message notification from Kanboard can include the ULR's task /project

### Actual behaviour
I use Roketchat plugin for notification when a task has new change (coment, new status... ).
I receive this message, but it not attach the URL . Both version of plugin 1.0.2 and 1.0.1 have same result.
I follow tutorial at https://kanboard.net/plugin/rocketchat. 
Thank all,

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.30
PHP version: 7.0.7
PHP SAPI: fpm-fcgi
OS version: Linux 3.10.0-327.18.2.el7.x86_64
Database driver: sqlite
Database version: 3.13.0

**Comment by fguillot** [comment]
What did you define in application url in global settings?

**Comment by antn89** [comment]
Hi there,
On project setting, i enabled notification via rocket plugin and integrated rocketchat's webhood url.
From rocket chat, i just receive info of task as my attached file.
![kb](https://cloud.githubusercontent.com/assets/19310978/17388218/e0513bea-5a24-11e6-96ad-6d1b1e53996e.jpg)

**Comment by antn89** [comment]
This issue has fixed on KB v 1.0.32,
Thanks all,
