### ISSUE TITLE
LDAP - indicate a LDAP group for manager remove manual rights

### ISSUE THREAD

**Issue by valvin1** [kanboard/kanboard#2540]
### Expected behaviour

After setting a LDAP DN group. All user in that group are manager. A user not in that group should be manually added as manager using Kanboard admin tool. 
### Actual behaviour

All users in the group are manager as expected. But if a user which is not in the group is setup manuelly as manager using admin tool. At the next login of this user it is "migrated" as a normal user. It seems that a manager has to be in the specified LDAP group. There is no way to fix rights an a LDAP user after using this parameter.

It is not a real issue but it is not very flexible. At least an information message should be indicated when setting role on a LDAP user when a group for manager is specified. This message should indicates dans role are not take in consideration with this configuration.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.31
- Database type and version: SQL Lite
- OS: Centos 7
- Browser: Firefox 47

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
