### ISSUE TITLE
cannot duplicate project

### ISSUE THREAD

**Issue by survietamine** [kanboard/kanboard#2543]
### Expected behaviour

I expected be able to create a project by duplicating another project with all checkboxes checked (permissions, categories, tags, actions, swimlanes, tasks).
### Actual behaviour

I'm stuck on the creation form, and after I clicked "Save" on the new project the Tasks checkbox become unchecked.
### Steps to reproduce

I did these steps to reproduce:
1. created a project (no duplication), mine is named template
2. gave permissions to 2 groups helpdesk-admin and infra
3. created a task named task01
4. added a tag to it
5. tried to clone the project with New Project> Create from another project (template) and checked the only unchecked box Tasks. So all checkboxes are checked
=> impossible to create the project, the form won't allow to save the project
After I clicked the Save button, the Tasks is unchecked like when I came to that form the 1st time.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: we observed that bug in 1.0.31. On 1.0.32 and dev versions, it is possible to duplicate the project if Tags is unchecked (and it copied the Tags anyway !)
- Database type and version: sqlite 3.8.2
- PHP version: 5.5.9
- OS: Ubuntu 14.04.4 LTS
- Browser: tested with 51.0.2704.79 (64-bit)

The weird thing is that sometimes "it works" and I don't see anything special in logs, even with DEBUG enabled in config.

**Comment by Trudill** [comment]
Hi,
I did some test on a brand new 1.0.41.

Duplicate works fine at first, but if you delete whatever project and try to duplicate after you have : 
=> Unable to clone this project. Sorry, I didn't find this information in my database!

And indeed if the "tasks checkbox" is unchecked when you duplicate it does work again. (and keeps the tasks even if unchecked)

**Comment by manchot37** [comment]
Hi,
I allow myself to relaunch this topic. 
Do you have ideas to resolve this problem ? Actually, we can clone a project just once. 
Thanks a lot and congrats for this software.

**Comment by Trudill** [comment]
Hi,
It didn't worked, then worked fine, then didn't and worked again ;) So no idea... I noticed that it ddn't work after deleting a previous project and seems to work back after creating a new one. But I am not that sure...

**Comment by manchot37** [comment]
Hi, 
okay ;) it's strange. I noted the same behavior like you...

**Comment by fguillot** [comment]
I'm not able to reproduce your problem.

You should try to check the logs for potential errors when the problem happens:

- Check the browser console
- Check the web server logs
- Check the application debug logs
- Uninstall incompatible plugins
- Make sure your environment is compatible with the [requirements](https://kanboard.net/documentation/requirements)
