### ISSUE TITLE
Quick-Edit via Task-ID: "Attach a document" action missing

### ISSUE THREAD

**Issue by tzeumer** [kanboard/kanboard#2545]
### Steps to reproduce
1. Click on any Task-ID (e.g. in Board View). 
2. Expected: The context menu should offer the same actions as are shown in the "single task view". 
3. Actual: Only "Attach a document" is missing.

![kanboard - missing action - attach a document](https://cloud.githubusercontent.com/assets/119825/17327307/549c7d12-58b7-11e6-9294-9397fc205f64.png)
### Configuration

Application version: 1.0.31
PHP version: 5.5.9-1ubuntu4.17
PHP SAPI: apache2handler
OS version: Linux 3.13.0-91-generic
Database driver: mysql
Database version: 5.5.49-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by fguillot** [comment]
The menu entry is now present v1.0.39
