### ISSUE TITLE
API PHP

### ISSUE THREAD

**Issue by vittimendes** [kanboard/kanboard#2547]
Im trying to integrate Kanboard with my helpdeslp portal. Kanboard it's working fine after installation , but I can't get it to work with PHP API.

For now im trying to execute a simple test, the getAllProjects one, and im alway caught in that error msg:

Warning: fopen(http://10.0.14.252:8000/site_solus_hml/kanboard/jsonrpc.php): failed to open stream: Connection refused in /var/www/html/sites/site_solus_hml/kanboard/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php on line 249 Fatal error: Uncaught exception 'JsonRPC\Exception\ConnectionFailureException' with message 'Unable to establish a connection' in /var/www/html/sites/site_solus_hml/kanboard/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php:252 Stack trace: #0 /var/www/html/sites/site_solus_hml/kanboard/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(191): JsonRPC\HttpClient->execute('{"jsonrpc":"2.0...') #1 /var/www/html/sites/site_solus_hml/kanboard/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(176): JsonRPC\Client->sendPayload('{"jsonrpc":"2.0...') #2 /var/www/html/sites/site_solus_hml/kanboard/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(126): JsonRPC\Client->execute('getAllProjects', Array) #3 /var/www/html/sites/site_solus_hml/kanboard/teste.php(13): JsonRPC\Client->__call('getAllProjects', Array) #4 /var/www/html/sites/site_solus_hml/kanboard/teste.php(13): JsonRPC\Client->getAllProjects() #5 {main} thrown in /var/www/html/sites/site_solus_hml/kanboard/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php on line 252

This is php im running into root kanboard site:

<?php

error_reporting(E_ALL);
ini_set('display_errors', 1);

include_once **DIR** . '/vendor/autoload.php'; 

$client = new JsonRPC\Client('http://10.0.14.252:8000/site_solus_hml/kanboard/jsonrpc.php');
$client->authentication('jsonrpc', '99717cddd1f046d60aa97d21fecf2eb8e73215cc5457463750a0792eadd6');
$client->getHttpClient()->withDebug();
print_r($client->getAllProjects());

?>

Can anyone help me out with this?

tks

**Comment by fguillot** [comment]
According to the error message, your script cannot access to `http://10.0.14.252:8000`. This is not really related to Kanboard but to your environment.
