### ISSUE TITLE
Avatar is returning an empty '200 OK' and should be '304 Not Modified'

### ISSUE THREAD

**Issue by willianwrm** [kanboard/kanboard#2548]
### Expected behaviour

Avatars should return code 304 if in cache (AvatarFileController.php)
### Actual behaviour

A 200 OK code is returned with empty data
### Steps to reproduce
1. Just reload page several times
2. OR try reload the picture it-self from link like /kanboard/?controller=AvatarFileController&action=image&user_id=1&size=20
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.32
- Database type and version: mysql 5.7.14-log
- PHP version: 7.0.9
- PHP SAPI: apache2handler
- OS: Windows NT 6.2
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0
### Solution

In the AvatarFileController.php, function image(), move the commands 'withCache' and 'withContentType' to inside to the If-None-Match:

```
public function image()
{
    $user_id = $this->request->getIntegerParam('user_id');
    $size = $this->request->getStringParam('size', 48);
    $filename = $this->avatarFileModel->getFilename($user_id);
    $etag = md5($filename.$size);

    if ($this->request->getHeader('If-None-Match') !== '"'.$etag.'"') {
        $this->response->withCache(365 * 86400, $etag);
        $this->response->withContentType('image/jpeg');
        $this->response->send();
        $this->render($filename, $size);
    } else {
        $this->response->status(304);
    }
}
```

**Comment by fguillot** [comment]
I'm not able to reproduce the issue, do you have the problem only with a specific browser?
