### ISSUE TITLE
Add an "All Tasks" filter

### ISSUE THREAD

**Issue by michael79bxl** [kanboard/kanboard#2550]
### Expected behaviour

Ability to display all tasks
### Actual behaviour

You can only show open or closed tasks
### Feature request

file app/Template/app/filters_helper.php line 13

```
<li><a href="#" class="filter-helper" data-filter="status:open status:closed"><?= t('All tasks') ?></a></li>
```

**Comment by fguillot** [comment]
You don't need to have both status open and closed in your query, you just need to remove all status filters.

**Comment by michael79bxl** [comment]
Maybe but there is no entry in the menu to clear filters.

Alternative code:
```
<li><a href="#" class="filter-helper" data-filter="status:open status:closed"><?= t('All tasks') ?></a></li>
```

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
