### ISSUE TITLE
Create a way to view all the relations between tasks

### ISSUE THREAD

**Issue by baldurmen** [kanboard/kanboard#2551]
I find the relation system between tasks (blocked by, blocks, etc.) to be very powerful.

I would like to get a way to easily see all the relations between the tasks, so that you could easily see what is blocking what and be able to prioritize blocking tasks first to be able to move on.

**Comment by BlueTeck** [comment]
https://github.com/xavividal/kanboard-plugin-relationgraph

**Comment by baldurmen** [comment]
wow, thanks
