### ISSUE TITLE
[UI enhancement] Dashboard: menu on left pane

### ISSUE THREAD

**Issue by Biniou180** [kanboard/kanboard#2553]
I open this ticket as a contributor of Framasoft projects, and particularly Framaboard which is based on Kanboard.
### Actual behaviour

When opening the dashboard, there is a menu with following buttons: new project, new private project, search, Project management.

![dashboard screenshot](https://framapic.org/LCO2ss7pC3iV/36ytVsj659iV)
### Expected behaviour
- Is the search button relevant as there is a search bar next to it?
- For UI consistency and to gain space in the window, why not put it to the left, under the dashboard menu? Like the actions menu for a task:

![task screenshot](https://framapic.org/F234Ws4Yxk0T/v3vTKEdNuRK7)
### Configuration

Tested on Kanboard 1.0.31

**Comment by fguillot** [comment]
What do you mean exactly? moving the top menu (new project, ... search) to the left sidebar?

**Comment by Biniou180** [comment]
Yes, it was my suggestion: Moving the top menu with "new project" [...] to the left, under the menu containing "My project/task/subtasks/.../notifications"; the same way the "actions" menu for a task has been moved under task menu since previous versions.
Just a suggestion, if you think there is a better way, i'm okay with it :)

**Comment by fguillot** [comment]
The dashboard has been simplified a lot in v1.0.41. The goal is to have a more responsive design, for now the sidebar is gone...

**Comment by ptman** [comment]
What's the ticket for the new dashboard? The old one had so much more functionality and showed more data

**Comment by Busfreak** [comment]
And all the hooks are gone...
