### ISSUE TITLE
[UI enhancement] "Display another project" dropdown limited in height

### ISSUE THREAD

**Issue by Biniou180** [kanboard/kanboard#2554]
I open this ticket as a contributor of Framasoft projects, and particularly Framaboard which is based on Kanboard.
### Actual behaviour

When having more than 8/9 projects, the dropdown list for displaying another project displays a scrollbar:

![dropdown screenshot](https://framapic.org/WV9uiHvmrSJE/QkzmxT3nSRDj)
### Expected behaviour

Should it be possible to have a dynamic height, in order to never show a scrollbar even in case of a lot of projects?
### Steps to reproduce
1. create 9+ more projects
2. display the dropdown list
### Configuration

Tested on Kanboard 1.0.31 (firefox 48)

**Comment by fguillot** [comment]
Why the scrollbar is annoying?

**Comment by Biniou180** [comment]
It's not that annoying, but some of our users have a lot of projects and are forced to scroll down to find them (I know they can use the search input, but I suppose they like using the mouse).
As there is no reason (?) to add a scrollbar as there is still a lot of space on screen, it was a suggestion to make the menu more accessible.

**Comment by Biniou180** [comment]
In addition to previous comments, further discussions with our users brought other remarks to enhance the project bar:

  * Why not enlarge the width of the bar? in case of long project names, it could be easier to read
  * Instead of displaying "Display another project", why not directly display the text search input (which is inside the drop-down today), and right next to it a button to open the drop-down list? It will spare some clicks for a user searching by text, and not change the behaviors for mouse users.

A mockup from one of our users to illustrate the suggestion:
![mockup project bar](https://framacolibri.org/uploads/default/original/1X/8be166dac0b2238a886eb7c1aa21d05d43a68ac0.png)

Thanks :)

**Comment by fguillot** [comment]
This element have been completely rewritten by using a custom ui component (in dev branch). jQuery chosen plugin have been removed too.

**Comment by Biniou180** [comment]
Seems perfect for me ! :-)
I will show a screenshot of the improvement to our users to see their reactions.
just for completion sake:
![screenshot](https://framapic.org/khzKh4SSYRKE/alEZGJ97DmXN)

Can't wait to see this in production, thanks a lot :-)

**Comment by fguillot** [comment]
Available in v1.0.36, other improvements are coming in next versions.
