### ISSUE TITLE
[UI enhancement] display project name when creating tasks

### ISSUE THREAD

**Issue by Biniou180** [kanboard/kanboard#2555]
I open this ticket as a contributor of Framasoft projects, and particularly Framaboard which is based on Kanboard.

When creating a task, the title is only "New Task". There is no visible clue to tell to the user which project will receive the task.
It's clearly no big deal as the user must go first to a project view to then create a task (so he should know which project he comes from), but some of our users asked if it could be possible to add the project name in the task creation panel to improve readability (for example: "New Task for Project XXX").

Do you think it is possible to add the project name ? I suppose it is not too hard to add it, and it will be clearer for users when creating a task.

### Configuration
Tested on Kanboard 1.0.31 (firefox 48)

Thanks a lot, again and again! :-)

**Comment by fguillot** [comment]
It's now available in the development branch.
