### ISSUE TITLE
What is the best way to move a locally hosted kanboard to the cloud hosted one? 

### ISSUE THREAD

**Issue by klaw1** [kanboard/kanboard#2557]
### Expected behaviour

Exporting the whole database off to the cloud hosted KB.  How can that be accomplished?
### Actual behaviour

Tell us what happens instead
### Steps to reproduce

1.
2.
3.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by krembo99** [comment]
You did not specify your system config ( as requested ) .
If you are running on SQLite for example, you just need to copy the whole install  folder ...

**Comment by fguillot** [comment]
If you are talking about Kanboard Managed hosting, you have to export your database (SQL dump) and send the copy to support@kanboard.net. But that will work only if you are using Postgresql.
