### ISSUE TITLE
Feature request: Add templates for typical tasks

### ISSUE THREAD

**Issue by laughtingman** [kanboard/kanboard#2562]
Some typical tasks involve a constant set of subtasks. It would be nice to set templates for applications such that they immediately created with subtasks.

For example. The task order equipment from us includes this subtasks:
1. request an invoice
2. to give an account in payment
3. accept delivery
4. recorded in the inventory database

I see it this way: when you create a task, there is a drop-down list (by default, nothing is selected). In this drop-down menu lists the patterns that exist in the current project. When you select a template automatically filled fields, tags, and the scheduled time. Then when you click save, a task is created and also creaded list subtasks predefined in the project settings to it.

Also, It would be great if the template could also specify a default performers.

Sorry for my bad English, it's google translate.

**Comment by bonbonGuy** [comment]
I second this as Templates would be great for individual tasks yes!

I've been playing with something similar for auto generation of multiple tasks based on a template. (mimicking repeated process flow and promoting better estimations) It's a bit of a hack, but i wanted to work within the limits of the "plugin" space without altering core code. 

 What i did was created a new project (called it Templates), each column specified a new set of tasks for each process. filled it with the tasks, and configured how i wanted them exactly.

 I then created an automatic action that can be triggered when a task is moved to a specified column doing the following:

1. Generate the set of tasks from the template project / column by duplication [ to a specified column or other project]
2. Assign them to the parents tasks assigned user
3. Link the newly generated tasks back to the initial task by a specified link (i use milestone)
4. (optional) move the parent task to another board for tracking. 

This action can also be trigger by an action in the task menu (Generate tasks from task)

If this is of interest i would be happy to package it up as a plugin once i finish vetting it out.

**Comment by regenduft** [comment]
+1, I need to have tags (or subtasks) beeing present whenever a task is created.

**Comment by Snajper88** [comment]
A KanBan-workflow often represents reoccuring tasks. So why is that not already implemented? It seems so basic. +1

**Comment by pirona** [comment]
Totally on board with a task template, if possible

**Comment by DaGLiMiOuX** [comment]
+1 Task templates are required for the project I'm working on with this amazing software.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
