### ISSUE TITLE
[Question] Add bar with remaining time on compare hours chart

### ISSUE THREAD

**Issue by avadadbz** [kanboard/kanboard#2563]
Hello everyone,
I would like to add a new bar on CompareHoursColumnChart with hours remaining (estimated - spent), somebody can say me how? (I am not a programmar, just a curious, but believe thats not hard to do).

Kanboard is very very usefull and good! thankyou for the excellent work!
Thanks in advanced.

**Comment by fguillot** [comment]
You have to create another series of datapoint based on the estimated and spent values and add it to the graph.

**Comment by avadadbz** [comment]
Ok. I will try do it. Thanks.
