### ISSUE TITLE
[Question] How to add custom chart js via plugin?

### ISSUE THREAD

**Issue by bonbonGuy** [kanboard/kanboard#2564]
I'm trying to create a custom analytic that's very specific to my project, I've tried editing the router.js to add my js to the route, but it looks like there is another reference in app.js (this is a jumbled mess that i'm having a hard time understanding) Is there perhaps an easier method to do this that i'm unaware of?

Thank you in advance

**Comment by BlueTeck** [comment]
Maybe this plugin helps: https://github.com/xavividal/kanboard-plugin-relationgraph

**Comment by bonbonGuy** [comment]
Thanks for the reply,  More specifically i'm trying to hook into the C3 chart code.

**Comment by fguillot** [comment]
- Add a new section in analytics
- At the end of your template, include a Javascript file that draw the chart with C3

You don't need to integrate your javascript code into the application js code. It can be loaded separately.

**Comment by bonbonGuy** [comment]
I believe I was trying to make this more complicated than it really was :) Thank you for bringing me back to earth. I have now been able to build my own custom chart, and boss is happy. Thank you
