### ISSUE TITLE
Analytics no longer available to "project manager" and "user" roles

### ISSUE THREAD

**Issue by rogerlipp** [kanboard/kanboard#2565]
### Expected behaviour

The "Analytics" menu item should be available to all users of a project.
### Actual behaviour

The menu from within a project no longer shows "Analytics" unless you are an administrator
### Steps to reproduce
1. Login as a non-administrator user
2. Goto a project
3. Select "Menu" -- the "Analytics" option is missing
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

```
Application version: 1.0.31
PHP version: 5.5.17
PHP SAPI: apache2handler
OS version: Linux 3.14.4-200.fc20.i686+PAE
Database driver: mysql
Database version: 5.5.37-MariaDB
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
```

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
