### ISSUE TITLE
Attach document functionality not working on Edge browser 

### ISSUE THREAD

**Issue by allanmacritchie** [kanboard/kanboard#2567]
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Steps to reproduce

1.
2.
3.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by allanmacritchie** [comment]
on Windows 10 version 1511 the console returns an access failure error on javascript

**Comment by fguillot** [comment]
You should try again with the latest Kanboard (1.0.38). This is working correctly for me with Edge. If the issue still there, open a bug with absolutely all the details to reproduce the problem.

Thank you
