### ISSUE TITLE
Notifications preferences are lost when upgrading trough 5 versions

### ISSUE THREAD

**Issue by letompouce** [kanboard/kanboard#2570]
Upgrading from 1.0.27 to 1.0.32 had the unexpected effect to reset the email sender address preference.
### Expected behaviour

Email sender address should be kept when upgrading
### Actual behaviour

Email sender address were lost and reset to `notification@kanboard.local` after the upgrade.
### Steps to reproduce
1. Use Kanboard 1.0.27 with a custom email sender address.
2. Upgrade to 1.0.32
3. Check your mailbox
### Configuration

This is the values after the upgrade. Sorry, we are using the tool in production, I cannot downgrade back to 1.0.27.
- Kanboard version: 1.0.32
- Database type and version:  sqlite 3.7.13
- PHP version: 5.4.45-0+deb7u2
- OS: Linux 3.10.23-xxxx-std-ipv6-64
- Browser: Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by fguillot** [comment]
Yes, sometimes the internal implementation is modified. Putting back the old value should solve your issue.
