### ISSUE TITLE
[Improvement] Usefulness of notification subjects  (RSS, mail, activities etc)

### ISSUE THREAD

**Issue by tzeumer** [kanboard/kanboard#2571]
I find it pretty hard getting a quick overview via RSS feeds, the notifications and the activity stream (plus the integration messages). All of these "views" use the task id in the subject. I wonder what genius could remembers the task description behind that. I think it is a pretty useless information. In other aspects the various "channel" subject formats differ slightly, but overall could be improved (I think).

Maybe something like this would improve the overview:
[In which Board] [to which task/aspect] [what action] [by whom]  

Maybe the task names could be cut if they are too long.

Or maybe I missed something, because I'm wondering about no other issue existing for this topic. Does everybody else use the dashboard only? :)
### Configuration
- Kanboard version: 1.0.31

**Comment by dustinliddick** [comment]
I would like to add my two cents:

I have notifications sent to me via Slack webhook. I or a team member was updated or comment on a task, the notification in Slack means next to nothing to me as its very vague. Could we get it to include the text heading/title in the notification?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
