### ISSUE TITLE
Browser-based spell check not working in CodeMirror fields

### ISSUE THREAD

**Issue by george-viaud** [kanboard/kanboard#2572]
### Expected behaviour

Spell check function should work when editing human-language text fields
### Actual behaviour

Spell check doesn't work in edit fields (Description, Comments, etc)
### Steps to reproduce
1. Enable common browser-based spell checking
2. Type incorrectly spelled text into edit field such as Description or Comments
3. Observe lack of spell-check
### Configuration

```
Application version: 1.0.30
PHP version: 5.5.9-1ubuntu4.19
PHP SAPI: apache2handler
OS version: Linux 3.13.0-92-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
```

**Comment by george-viaud** [comment]
I think this has to do with CodeMirror - I'm not sure it is intended for use as human-language text editor.  Of course I'm quite happy to be wrong :)

**Comment by acs-ferreira** [comment]
The option is there, but disabled.

https://github.com/kanboard/kanboard/blob/45f21e1cd8e09e39d5f74d8826b27fc202428b3c/assets/js/src/Markdown.js#L48

**Comment by PawnStar** [comment]
That's to enable SimpleMDE's spellchecker - turning that on still doesn't allow the browser's spellcheck to work like on normal text fields.

See SimpleMDE's [example](https://simplemde.com) - the third field in that page seems to have that spellcheck option enabled.

**Comment by fguillot** [comment]
The text editor have been rewritten in v1.0.35 and CodeMirror is not used anymore. So this is working now.

Thank you.
