### ISSUE TITLE
User blocked after 3 attempts

### ISSUE THREAD

**Issue by n0va1s** [kanboard/kanboard#2573]
A user after 6 attempts is blocking access and is not releasing after 15 minutes. What to do? I need to set up some task in crontab? Something like ./kanboard -XXX unlock.

The current solution is to delete the user and grant all access again. But it loses all tasks already   allocated.

#1524

**Comment by fguillot** [comment]
You don't have to remove the user.

1) You can wait 15min, check the user profile as admin:

![account-locked](https://cloud.githubusercontent.com/assets/323546/17538432/449f36b8-5e73-11e6-937f-372d2ab176da.png)

2) If you don't want to wait, you can unlock the user by reseting his password from the user interface

**Comment by n0va1s** [comment]
I understand. But my users are remote authenticating in LDAP. And I have not found in the user profile option to reset the password. I'm using version 1.0.30 and will not appear until when the lock is active.

Some users were more than 24 hours without access to the system because it was locked. So it seems that the lockout period is more than 15 minutes (this setting is not made in the configuration file, is that the lockout period is infinite?).

**Comment by fguillot** [comment]
I added in the development version the possibility of unlocking users from the user interface. That should solve your issue.

The locking duration should not be more 15min by default. However, if the user still trying a wrong password, he will be locked for another 15min. This option is configurable: https://kanboard.net/documentation/bruteforce-protection

**Comment by n0va1s** [comment]
Fantastic! Thanks!!!
