### ISSUE TITLE
New-Line in Description editor does not produce displayed new-line when viewing description in task

### ISSUE THREAD

**Issue by george-viaud** [kanboard/kanboard#2576]
### Expected behaviour

Creating a list of items with new-lines between each should result in a displayed list that reflects the new lines
### Actual behaviour

Creating a list of items with new lines places each item on the same line with a space between them in the displayed description
### Steps to reproduce
1. Create a task
2. In the description text, create a list similar to this one:
   ItemA
   ItemB
   ItemC
   Etc.
3. Save the task and observe the description which will appear as:
   ItemA ItemB ItemC

as opposed to the desired result:
ItemA
ItemB
ItemC
### Configuration

```
Application version: 1.0.30
PHP version: 5.5.9-1ubuntu4.19
PHP SAPI: apache2handler
OS version: Linux 3.13.0-92-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
```

**Comment by TheCloud** [comment]
edit: app/Template/task/description.php

Change line:
            <?= $this->text->markdown($task['description'], isset($is_public) && $is_public) ?>
To:
            <?= nl2br($this->text->markdown($task['description'], isset($is_public) && $is_public)) ?>

**Comment by fguillot** [comment]
The text editor have been rewritten in v1.0.35 and CodeMirror is not used anymore. It should work now.

Thank you.
