### ISSUE TITLE
Change assignee drop down menu option (and others) on board view disappeared

### ISSUE THREAD

**Issue by hjjohny** [kanboard/kanboard#2577]
### Expected behaviour

As in the previous versions i expect a change assignee button in the drop down menu of the tickets on the board view.
### Actual behaviour

But now it is gone, and that drop down menu became a bit luck luster in the newer version ( 1.0.29 and above) the 1.0.28 version works fine, with a good drop down menu. 
### Steps to reproduce
1. Install 1.0.28 and create a ticket and click onto the number of the ticket in the top left corner when in the board view, and see the nice and detailed drop down menu, with the "Change assignee" option. 
2. After that install a 1.0.29 or above and the drop down menu becames luck luster a lot of options disappeared. 
### Configuration

Application version: 1.0.28
PHP version: 5.4.45-0+deb7u3
PHP SAPI: fpm-fcgi
OS version: Linux 3.2.0-4-686-pae
Database driver: sqlite
Database version: 3.7.13
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by fguillot** [comment]
Yes, that trigger the "edit task" form now.
