### ISSUE TITLE
Cant Attach Document  

### ISSUE THREAD

**Issue by pinchasertb** [kanboard/kanboard#2580]
### Expected behaviour

Tell us what should happen
Document should be added (I tried, IE, Firefox and Chrome)
### Actual behaviour

Tell us what happens instead
The process completes as successful. However the document does not appear in attachments location.
### Steps to reproduce
1. Click on task
   2.. Click on Attach a Document
2. Drag/Drop Word Document, and use search for file function
3. See file in the window and click Upload Files
4. Click on See document
5. No file displays
6. Open attachments and nothing there.
7. Refresh screen and open attachments and no file attached
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

```
Application version: 1.0.31
PHP version: 7.0.8-0ubuntu0.16.04.2
PHP SAPI: apache2handler
OS version: Linux 4.4.0-34-generic
Database driver: mysql
Database version: 5.7.13-0ubuntu0.16.04.2
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
```

**Comment by fguillot** [comment]
Can you try with the version >=1.0.38? Did you set the right permissions to the folder data if you use the local files storage?
