### ISSUE TITLE
Config.default.php refers to undefined constants

### ISSUE THREAD

**Issue by turjotuohiniemi** [kanboard/kanboard#2584]
### Expected behaviour

When config.default.php is renamed to config.php, it should work out of the box.

### Actual behaviour

I'm getting errors like this:

`PHP message: PHP Notice:  Use of undefined constant DATA_DIR - assumed 'DATA_DIR' in /var/www/app/config.php on line 14
`

As a result, a lot of things break down. At least plugins don't work, possibly attachments too (because FILES_DIR gets defined incorrectly). Therefore, fixing this bug should fix #2580 and #2581 as well.

Some analysis: The reason for this is that config.php.default refers to ROOT_DIR, which is defined in app/constants.php. However, app/common.php reads in config.php first and only after that comes constants.php. On the other hand, the order of these files cannot be swapped for obvious reasons.

### Steps to reproduce

1. rename config.default.php to config.php

### Configuration

Latest version from github (as of August 15th, 2016)
https://github.com/kanboard/kanboard/tree/d8b60ca0fa8d2e1fb3fa711dd24be16e01097654

**Comment by fguillot** [comment]
Duplicate with https://github.com/kanboard/kanboard/issues/2544
