### ISSUE TITLE
Add or remove manually one hour

### ISSUE THREAD

**Issue by Louison42** [kanboard/kanboard#2589]
Hi,

For my company I'm looking to integrate a function to add or remove manually one hour, because sometimes forgetting to start the stopwatch

like:
kanboard/app/Template/subtask/table.php
on <ul class="no-bullet">
<i class="fa fa-plus fa-fw"> </i> <?= $this->url->link(t('1 heure'), 'Addtimesubtask', 'time', array('time' => 1, 'project_id' => $task['project_id'], 'task_id' => $subtask['task_id'], 'subtask_id' => $subtask['id']), false)  ?>

Thx for Kanboard

**Comment by fguillot** [comment]
Well, don't hesitate to contribute.
