### ISSUE TITLE
Open Project fails

### ISSUE THREAD

**Issue by mgott85** [kanboard/kanboard#2590]
### Expected behaviour
Project should open

### Actual behaviour
- php7.1-fpm segfaults resulting in HTML Error 502 Bad Gateway

### Steps to reproduce
1. Create a Project and add 40 Cards. Every Project under 40 Cards works perfectly

### Configuration
    Kanboard Version: 1.0.32
    PHP Version: 7.1.0beta2
    PHP SAPI: fpm-fcgi
    OS Version: Linux 4.2.0-42-generic
    Datenbanktreiber: postgres
    Datenbank Version: 9.5.3
    Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by stlorenz** [comment]
Maybe it helps to add some more information to this issue. (working on the same installation)

The server config worked perfectly before upgrading to 1.0.32 and upgrading php5 to php7. 

The debug log shows no queries made on the database when opening the card board, but the overview and other pages work,

/var/log/syslog says:

````
 php-fpm7.1[17509]: segfault at 18 ip 000055b9cf3d6731 sp 00007fffccf73e60 error 4 in php-fpm7.1[55b9cf190000+3b0000] 
````

and  

````
www[20802]: PHP Notice:  Undefined index: id in /var/www/kanboard/app/Formatter/BoardColumnFormatter.php on line 85
````

**Comment by mgott85** [comment]
The php update to version 7.1.0beta3-1 fixed this issue.
