### ISSUE TITLE
Feature request: Have a count of occurrences to the tag list page, so that we can clean up unused tags and know which tags need use 

### ISSUE THREAD

**Issue by bruceylin** [kanboard/kanboard#2592]
### Expected behaviour

When going to configure tags in a project settings page, it would be useful to have a column or a little extra text to indicate number of occurrences of that tag.  E.g. "MyCoolTag (8)".  That tag occurs 8 times.

This will be useful as a summary to see where emphasis is with task items, and which  tags may  not have enough attention by the team.  I.e. if a tag has a zero-count, that may trigger the team to groom more stories about that tag-topic. 
### Actual behaviour

It just shows the tag itself with edit/remove buttons.
### Steps to reproduce

N/A
### Configuration

N/A
- Kanboard version: 1.0.32
- Database type and version: SQLite default
- PHP version: 5
- OS: Ubuntu Linux
- Browser: Chrome

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
