### ISSUE TITLE
CLI command not available (cronjob)

### ISSUE THREAD

**Issue by TheCloud** [kanboard/kanboard#2593]
### Expected behaviour

Running  _./kanboard cronjob_ should process cronjob

### Actual behaviour

<b>Parse error</b>:  syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in <b>/homepages/9/d611919376/htdocs/red-oemr-it/kanboard/kanboard</b> on line <b>4</b><br />

### Suggestion

Implement a URL which can be requsted via wget/curl command such as
http://kanboard.domain.tld/kanboard/runcronjob

Would be useful to be crossplatform (aka Windows) 
Would be useful for people not having access to console

### Steps to reproduce

1. Run command from command line on **1&1 hosting environment**

### Configuration

Versione dell'applicazione: 1.0.32
Versione PHP: 5.6.24
PHP SAPI: cgi-fcgi
Versione OS: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Driver per Database sqlite
Versione database: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by TheCloud** [comment]
In this case the crontab would need a change into
0 8 * * * curl --silent http://domain.tld/kanboard/runcronjob >/dev/null 2>&1

**Comment by TheCloud** [comment]
SOLVED issue on error: I missed config.default.php in the kanboard folder
Should maybe return a different error in case configuration is not present

Anyway, launching the cronjob via URL is imho still a good way to simple installation for who has not console access

**Comment by Rocreex** [comment]
What about a solution which makes it posible to run the script without console access?
