### ISSUE TITLE
Feature Request: Add Filters to Analytics view (Tags, Categories etc.)

### ISSUE THREAD

**Issue by andreaslink-de** [kanboard/kanboard#2596]
### Expected behaviour

When selecting analysis view I'd like to have the chance to breakdown analytics to the set filters. So I'd like to filter on only one or more categories and or tags e.g. (or other conditions)
### Actual behaviour

Currently the view is always filtered on all tasks of the complete project.
### Steps to reproduce
1. Set a filter of your choice
2. Click on analytics
3. See no effect of filters beeing applied to the analysis charts
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.32
- Database type and version: sqllite 3.8.2
- PHP version: 5.5.9-1ubuntu4.17
- OS: Linux 3.13.0-85-generic
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited.

Thank you for your understanding
