### ISSUE TITLE
Plugins not detected

### ISSUE THREAD

**Issue by aljawaid** [kanboard/kanboard#2598]
### Expected behaviour

Plugins should load and be installable

### Actual behaviour

No plugins found. 

I have tried to copy (ftp) the plugin file and extract as-is but no success.
I even tried to put all the plugin files in the same plugin sub-folder:
![snip_20160822121157](https://cloud.githubusercontent.com/assets/10233708/17852945/c6cd4e52-6861-11e6-9482-40b989eae2e7.png)

### Config File

// Plugins directory
```
define('PLUGINS_DIR', ROOT_DIR.DIRECTORY_SEPARATOR.'plugins');

define('PLUGIN_INSTALLER', true);
```
**Does it matter that I installed Kanban as mydomain.com/planner instead of mydomain.com/kanban ?**

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

    Application version: 1.0.32
    PHP version: 5.5.38
    PHP SAPI: cgi-fcgi
    OS version: Linux 2.6.32-573.18.1.el6.x86_64
    Database driver: mysql
    Database version: 5.5.47
    Browser: Mozilla/5.0 (Windows NT 10.0; rv:48.0) Gecko/20100101 Firefox/48.0

![snip_20160822120541](https://cloud.githubusercontent.com/assets/10233708/17852775/c6efe7a6-6860-11e6-9bce-cee4d1d8f8d6.png)
![snip_20160822120916](https://cloud.githubusercontent.com/assets/10233708/17852848/495152c0-6861-11e6-8da1-ddae447eb9b0.png)

**Comment by stinnux** [comment]
Is that your own plugin? How does plugin.php look like?

**Comment by aljawaid** [comment]
Hello, thanks for the response.  No, this was the Automatic Actions plugin.... I tried the same with the Timetable plugin.

This is the **plugin.php** for Automatic Actions:
`<?php

namespace Kanboard\Plugin\AutomaticAction;

use Kanboard\Core\Plugin\Base;
use Kanboard\Plugin\AutomaticAction\Action\TaskRename;

class Plugin extends Base
{
    public function initialize()
    {
        $this->actionManager->register(new TaskRename($this->container));
    }
}
`

**Comment by pzabek** [comment]
I had the same problem. I have a message "Your Kanboard instance is not configured to install plugins from the user interface". After copying the module to the plugins folder, it shows "no plugins found", a change in the configuration helped
```
define('PLUGINS_DIR', 'plugins');
```

**Comment by aljawaid** [comment]
@pzabek Thank you very much, your suggestion solved the problem!

Much appreciated.

**Comment by fabiocampero** [comment]
Thank you very much!
