### ISSUE TITLE
[FR]add ACL system for kanboard

### ISSUE THREAD

**Issue by renothing** [kanboard/kanboard#2599]
current there is no really permission structure for kanboard, for example, a common workflow looks ike this: one step for one column in kanboard.

report issue(reporter)---->waiting confirm(qa/pm)---->working in progress(programer)---->waiting validation(qa/pm)--->finished/close

current now it's easy to do in jira because its good workflow system, only special  user/group can change status at every step. and it can't be change from first step to last step directly, but it's can't be stop in kanboard. every team/project member can change it to any status or any column.

I think it would be useful if there is an strong  permission/role system for kanboard based on role for every action.  for example: when I add column, add new field for permission setting 
![addpermissionforkanboard](https://cloud.githubusercontent.com/assets/261274/17856794/be29cf28-68b1-11e6-905d-6b83ede81be7.png)

**Comment by fguillot** [comment]
I prefer to keep this software simple. If you need these features, you are probably better to use Jira.
