### ISSUE TITLE
CSS Hook in Plugin not working

### ISSUE THREAD

**Issue by stinnux** [kanboard/kanboard#2601]
According to the documentation a CSS hook works the following way:

`$this->hook->on('template:layout:css', 'plugins/Css/skin.css');`

instead the right syntax is:

`$this->hook->on('template:layout:css',array('template' =>  'plugins/Css/skin.css'));`

This is caused by the following change: https://github.com/kanboard/kanboard/commit/2ebe8b32728c341ec16e1197fe2e12d32ddd5de5
### Expected behaviour

CSS should be loaded.
### Actual behaviour

you get an error message.

**Comment by fguillot** [comment]
If you use the latest master, this issue should not happens, can you confirm that?
