### ISSUE TITLE
Is there a chance to mail in tasks?

### ISSUE THREAD

**Issue by hubutz** [kanboard/kanboard#2602]
Hi there,

don't know if I can state me clear on that: would it be possible to send a mail to some mailadress and the mail get's a new card say in the inbox?

Best
hubutz

**Comment by TheCloud** [comment]
Kanboard allows to create tasks sending emails.
You need to install and configure a mail service (such as mailgun plugin) and follow instructions.

https://kanboard.net/plugin/mailgun
