### ISSUE TITLE
Bug report: Create tasks in bulk

### ISSUE THREAD

**Issue by ngosang** [kanboard/kanboard#2604]
### Expected behaviour

When I create tasks in bulk the "Automatic actions" should apply to all tasks.
### Actual behaviour

"Automatic actions" are applied only to the first task.
### Steps to reproduce
1. Set an "Automatic action",  Event name = Task creation or modification.  Action name = Assign automatically a color based on a category 
2. Create 2 tasks in bulk with the category that triggers the "Automatic action"
3. The "Automatic action" (color change) is applied only to the first task.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

```
Application version: master
PHP version: 7.0.8-0ubuntu0.16.04.2
PHP SAPI: apache2handler
OS version: Linux 4.4.0-31-generic
Database driver: sqlite
Database version: 3.11.0
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
```

**Comment by ngosang** [comment]
@fguillot this is a bug not an improvement. thank you.

**Comment by ngosang** [comment]
@fguillot This should be easy to fix, Could you take a look?

**Comment by fguillot** [comment]
This is now fixed in the development version (better late than never).
