### ISSUE TITLE
Create task via email: mandatory + in local part

### ISSUE THREAD

**Issue by TheCloud** [kanboard/kanboard#2608]
If you have your domain configured and using mailgun to create task (ie create task by sending emails), you have to use the sintax SOMETHING+project_identifier@domain.tld

That "SOMETHING" part is not used within kanboard, so I suggest to remove it or, at least, still accept both solutions:

I did it by changing app/Helper/MailHelper.php on line 20ish

```
public function getMailboxHash($email)
{
    if (! strpos($email, '@')) {
        return '';
    }

    list($localPart, ) = explode('@', $email);
    if (! strpos($email, '+')){
            $identifier=$localPart;
    } else {
            list(, $identifier) = explode('+', $localPart);
    }
    return $identifier;
}
```

**Comment by fguillot** [comment]
This system can also be improved by letting the end-user enter the email address he would like for the project in a text field. That simplify the process and this code can be removed.

**Comment by fguillot** [comment]
With the latest version of KB you could define a custom project email address.
