### ISSUE TITLE
notification:overdue-tasks fails (using generic mail notifications)

### ISSUE THREAD

**Issue by ndbrownlow** [kanboard/kanboard#2609]
### Expected behaviour

Send overdue notifications

### Actual behaviour

PHP Notice:  Undefined index: task in /var/www/kanboard/v1.0.32/app/Notification/MailNotification.php on line 83
[...]
Variables in local scope (#11):
  $eventData = array ('tasks' => array (0 => array (...), 1 => array (...), 2 => array (...)), 'project_name' => 'My Project')
  $eventName = 'task.overdue'

### Steps to reproduce

Noticed after configuring cron to run cronjob task; can reproduce minimally as follows:
1. open terminal on server
2. cd into kanboard directory
3. ./kanboard notification:overdue-tasks

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.32
PHP version: 5.3.10-1ubuntu3.24
PHP SAPI: apache2handler
OS version: Linux 3.2.0-107-generic
Database driver: mysql
Database version: 5.5.50-0ubuntu0.12.04.1
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by fguillot** [comment]
It's already fixed in the development branch.

**Comment by fguillot** [comment]
The fix is now available in Kanboard v1.0.33
