### ISSUE TITLE
Feature: Hybrid Project Permissions

### ISSUE THREAD

**Issue by lukasjuhrich** [kanboard/kanboard#2610]
### Expected behaviour

There should be a possibility to add everybody as a project member but still define managers over a list of groups or users.
### Actual behaviour

The “allow everybody” button adds everybody as a team member, but disables any other option graphically (and thus functionally, I presume).
### What needs to be done

What would have to be done here? Also, why has the decision been made that allowing everybody as a project member disables any other configuration?

I don't know a lot about the model of Kanboard, but it seems on the first glance that this is currently defined by setting one switch `project→is_everybody_allowed` overriding every other permission setting.
### Proposal

I could imagine the following solution: introduce “everybody” as a group, and be able to add this group to the permission settings. However, a distinction between classical groups which can be added is necessary, since this group shouldn't show up in the list of groups and shouldn't allow adding and removing members.

I propose creating an interface “AccountFilter” or “PrimitiveGroup” (I'm bad at naming) having a central function `is_member` telling whether a user is a member, and perhaps, but not necessarily, a function `list_members`. Also, it should have a `display_name` to be displayed to the user when selecting it.
A group in the classical sense would extend this interface/class by properties such as `add_member` etc.
When changing and checkiing permissions, Kanboard should thus use `AccountFilter`s instead of `Groups`, allowing a broader range of settings.

I hope this is helpful, unfortunately I don't know a lot of php and didn't have the time to dig too deep into kanboard's source code.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
