### ISSUE TITLE
JSON-RPC / PHP / IIS / Windows 2012 R2 - Unauthorised

### ISSUE THREAD

**Issue by vk8996** [kanboard/kanboard#2611]
### Expected behaviour
Trying json-rpc on php with the following example

<?php

include_once 'vendor/autoload.php';

$client = new JsonRPC\Client('http://myserver/kanboard/jsonrpc.php');
client->authentication('jsonrpc', 'MY_KEY');
$client->getHttpClient()->withDebug();
print_r($client->getAllProjects());
?>

Expected

Array with all project details

### Actual behaviour

Getting the following error

[26-Aug-2016 09:21:27 Australia/Canberra] ==> Request: 

{"jsonrpc":"2.0","method":"getAllProjects","id":1654848642}

[26-Aug-2016 09:21:27 Australia/Canberra] ==> Headers: 

array (
  0 => 'HTTP/1.1 401 Unauthorized',
  1 => 'Content-Type: application/json',
  2 => 'Server: Microsoft-IIS/8.5',
  3 => 'X-Powered-By: PHP/7.0.7',
  4 => 'WWW-Authenticate: Basic realm="JsonRPC"',
  5 => 'WWW-Authenticate: Basic realm="myserver"',
  6 => 'X-Powered-By: ASP.NET',
  7 => 'Date: Thu, 25 Aug 2016 23:21:27 GMT',
  8 => 'Connection: close',
  9 => 'Content-Length: 223',
)

[26-Aug-2016 09:21:27 Australia/Canberra] ==> Response: 

null

[26-Aug-2016 09:21:27 Australia/Canberra] PHP Fatal error:  Uncaught JsonRPC\Exception\AccessDeniedException: Response: HTTP/1.1 401 Unauthorized in C:\inetpub\wwwroot\kanboard\vendor\fguillot\json-rpc\src\JsonRPC\HttpClient.php:360
Stack trace:
#0 C:\inetpub\wwwroot\kanboard\vendor\fguillot\json-rpc\src\JsonRPC\HttpClient.php(265): JsonRPC\HttpClient->handleExceptions(Array)
#1 C:\inetpub\wwwroot\kanboard\vendor\fguillot\json-rpc\src\JsonRPC\Client.php(191): JsonRPC\HttpClient->execute('{"jsonrpc":"2.0...')
#2 C:\inetpub\wwwroot\kanboard\vendor\fguillot\json-rpc\src\JsonRPC\Client.php(176): JsonRPC\Client->sendPayload('{"jsonrpc":"2.0...')
#3 C:\inetpub\wwwroot\kanboard\vendor\fguillot\json-rpc\src\JsonRPC\Client.php(126): JsonRPC\Client->execute('getAllProjects', Array)
#4 C:\inetpub\wwwroot\kanboard\testapi.php(12): JsonRPC\Client->__call('getAllProjects', Array)
#5 {main}
  thrown in C:\inetpub\wwwroot\kanboard\vendor\fguillot\json-rpc\src\JsonRPC\HttpClient.php on line 360

### Comments

Hi, I am new to JsonRPC. I read few posts having similar issues and most of the workarounds are for apache servers. I am using IIS in Windows 2012 R2, anyone could shed some light on this please.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: Latest
- Database type and version: sqllite
- PHP version: 7.0
- OS: Windows Server 2012
- Browser: IE / Edge / Chrome

**Comment by fguillot** [comment]
Do you have anything configured in IIS that restrict the access (login or password)? The same HTTP header is repeated 2 times (WWW-Authenticate).

**Comment by vk8996** [comment]
Thanks guillot for your reply.

I configured IIS initially only with Anonymous Access. After reading some post, I enabled Basic Authentication as well, other than that I haven't made any configuration changes to IIS.

**Comment by vk8996** [comment]
Changed API_AUTHENTICATION_HEADER to X-API-Auth in httpclient.php, it worked.

Thanks for your help.
