### ISSUE TITLE
API user credentials don't work if two users have same email address

### ISSUE THREAD

**Issue by TheCloud** [kanboard/kanboard#2612]
### Expected behaviour

When using jsonrpc API with username and password, a user should be able to run getAllProjects method (and all other methods)
### Actual behaviour

If the user has two accounts, one as admin (for management) and one as user, and both users are created with same email address, API always return not permitted access.

Accesssing using "Application credentials" works.
### Steps to reproduce
1. create a user with same emailaddress as admin
2. run API using User credentials
   3.use cURL example provided in docs to get all projects
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
Versione dell'applicazione: 1.0.32
Versione PHP: 5.3.10
PHP SAPI: apache2handler
Versione OS: Linux 2.6.9-67.0.4.EL
Driver per Database sqlite
Versione database: 3.7.7.1

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
