### ISSUE TITLE
Deployment option...

### ISSUE THREAD

**Issue by huntx011** [kanboard/kanboard#2615]
A VirtualBox appliance would make it easy and predictable for users or evaluators to either deploy or use a fully functional version that could run across all environments supported by VirtualBox. 

I would be open to helping if you are interested in this option.

CLH

**Comment by fguillot** [comment]
I like the idea, however the process of creating the appliance should be automated to simplify releases. Software like packer might be a good choice: https://www.packer.io

**Comment by fguillot** [comment]
Closing this ticket due to inactivity and lack of interest by the community.
