### ISSUE TITLE
JavaScript not working in current master version

### ISSUE THREAD

**Issue by stinnux** [kanboard/kanboard#2618]
### Expected behaviour

Working kanboard application including JavaScript

### Actual behaviour

JavaScript error messages (in Chrome):

```
vendor.min.js?1472549447:7 Uncaught EvalError: Refused to evaluate a string as JavaScript because
 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'".
n @ vendor.min.js?1472549447:7Ai.i.extend 
@ vendor.min.js?1472549447:7i.(anonymous function) 
@ vendor.min.js?1472549447:7(anonymous function) 
@ app.min.js?1472549448:1

Failed to parse SourceMap: http://localhost:8888/assets/js/vue.min.js.map
```

The offending line in vendor.min.js:
```
  }
    function Ai(i) {
        function n(t) {
            return new Function("return function " + f(t) + " (options) { this._init(options) }")()
        }
```

### Steps to reproduce

1. clone the current repository and checkout the master branch
2. Run composer install
3. Run make static
4. Access kanboard via browser

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: a3819c33d222b61f2a008f23ff67c7a14797c946
- Database type and version: sqlite
- PHP version: 7.0.8
- OS: macOS sierre Public Beta 6
- Browser: Chrome 52.0.2743.116 (64-bit)

**Comment by stinnux** [comment]
I installed it again on my windows machine and here it is working. I will investigate further what is wrong on my mac.

**Comment by fguillot** [comment]
I fixed the issue yesterday, it should work everywhere now.

**Comment by fguillot** [comment]
Closing this because it was only for the dev version.
