### ISSUE TITLE
LDAP: Profile name resets when logging in.

### ISSUE THREAD

**Issue by seacowz** [kanboard/kanboard#2619]
### Expected behavior

When a user changes their name in the profile (Actions->Edit Profile), that change should be permanent.
### Actual behavior

When using LDAP for authentication, the default name that is read from the LDAP database replaces the name that the user changed.
### Steps to reproduce
1. Enable LDAP authentication
2. Have LDAP database provide name for user
3. Change the name of the user so that it is not the default.
4. Log in  with LDAP and see that the name has changed back to the LDAP default.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.32
PHP version: 5.5.9-1ubuntu4.19
PHP SAPI: apache2handler
OS version: Linux 3.16.0-40-generic
Database driver: mysql
Database version: 5.5.50-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by fguillot** [comment]
In this mode, the source of truth is LDAP not Kanboard.
