### ISSUE TITLE
Possibility to execute the "Background job operations" by calling a web page

### ISSUE THREAD

**Issue by jarod80** [kanboard/kanboard#2620]
This is a feature request not an Issue but I am not so usedto github hope i am not using wrong place or format to put this.

Hi I have installed kanboard on an Azure web site, I am having difficulty in scheduling a job running an executable. 
What I have found is that I can schedule on remote server some jobs but only to call some urls.
I remember that in websites like Magento there was a page such as something similar to www.webpage.com/cron.php that executed the operations as well.
### Actual behaviour

For what I have seen actually I need to schedule a cron job operation based on executable only.
### Configuration

Application version: 1.0.32 
◾ PHP version: 5.4.45 
◾ PHP SAPI: cgi-fcgi 
◾ OS version: Windows NT 6.2 
◾ Database driver: sqlite 
◾ Database version: 3.8.10.2 
◾ Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. If you need that, the best way is to contribute.
