### ISSUE TITLE
Some projects are showing 01/01/1970 as start and end date

### ISSUE THREAD

**Issue by ahummes** [kanboard/kanboard#2622]
### Expected behaviour

Start and Enddate in 'Information' and Gantt chould be shown as set in project settings.

### Actual behaviour

In some of our projects we see 01/01/1970 as start and end date instead of the date which is set in project settings

### Steps to reproduce

1. open a new project
2. set start and end date
3. see wrong date in information section of this project
![2016-08-31 10_03_24-start](https://cloud.githubusercontent.com/assets/21356907/18120918/61e203c2-6f62-11e6-824d-0946529954a1.png)
![2016-08-31 10_04_06-einfuhrung kanboard](https://cloud.githubusercontent.com/assets/21356907/18120917/61e1a490-6f62-11e6-984e-c0be2031d52d.png)
![2016-08-31 10_04_27-einfuhrung kanboard _ edit project](https://cloud.githubusercontent.com/assets/21356907/18120919/61e52142-6f62-11e6-892e-af8175b53058.png)

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Version: 1.0.32
PHP Version: 7.0.9
PHP SAPI: cgi-fcgi
OS Version: Windows NT 6.3
Datenbanktreiber: mysql
Datenbank Version: 5.7.14-log
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by fguillot** [comment]
The fix is now available in Kanboard v1.0.33.

If that doesn't works correctly enter the dates again and submit the form. Otherwise, if you still having problem, reopen this ticket.

Thank you
