### ISSUE TITLE
Task public link

### ISSUE THREAD

**Issue by Imbasaur** [kanboard/kanboard#2629]
Hi, is it possible to generate public link, valid only for one task? Right now you can only make public link which works for whole project, would be cool to share only specific task.

**Comment by hozelock** [comment]
Many solutions :

- From the table in public access, click on the task you want, you have access to the details of this task

- Since the backend (not from the table in public access), click on the task you want and above, in the color band, get a link to access this task only

**Comment by Imbasaur** [comment]
But then you can just change &task_id to any task number within shared project and access that task.
controller=TaskViewController&action=readonly&task_id=1&token=c7d8e32ba2df552c224aeffb9ec532031b00f52f84c2838768abdb92bcee

**Comment by hozelock** [comment]
In fact, it's a problem !

The best would be to generate a link with a security token by task, indeed !

**Comment by aljawaid** [comment]
There is still a link to go back to the main board so a task-specific public link would be better for privacy.

**Comment by fguillot** [comment]
@Imbasaur this feature doesn't exists yet, contributions are welcome :)
