### ISSUE TITLE
Date pickers return inconsistent formatting

### ISSUE THREAD

**Issue by rmkraus** [kanboard/kanboard#2630]
### Expected behaviour

Date pickers under Analytics, Cumulative flow diagram should both use the same date formatting. Dates of format 2016-09-01 appear to be the only accepted formats. The Start Date date picker uses the format 09/01/2016. The date pickers on the data export tool also appear to use the 09/01/2016 format which generates an empty report. Using the 2016-09-01 format in the data export tool generates the proper report. The comments in the data export tool also indicate that the 09/01/2016 format is acceptable, but it does not appear to work with that format.

### Actual behaviour

 - Dates of format 09/01/2016 do not seem to be parsed correctly. (not a huge issue for me)
 - Date pickers return inconsistent formats. Some of these formats are not parsed correctly. Specifically, the Cumulative flow diagram Start Date picker and the data export pickers seem inconsistent.

### Steps to reproduce

1. Go to a project -> Analytics -> Cumulative flow diagram
2. Pick a start date 
3. Report will not honor the start date
4. Repeat for exporting data

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

    Application version: 1.0.32
    PHP version: 5.4.16
    PHP SAPI: apache2handler
    OS version: Linux 3.10.0-327.el7.x86_64
    Database driver: sqlite
    Database version: 3.7.17
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by fguillot** [comment]
It should be fixed with Kanboard v1.0.33 otherwise reopen this ticket.
