### ISSUE TITLE
public view on latest releases shows all tasks, desired to only show open tasks

### ISSUE THREAD

**Issue by entwisi** [kanboard/kanboard#2631]
### Expected behaviour

In an older version of the software the public view only showed open tasks ( which is desirable to me), since migrating to 1.0.31 the public view retrieves all tasks including all closed tasks ( we close the tasks rather than remove to maintain history for analytical reasons )

I have identified it is using taskFinderModel->getExtendedQuery() as opposed to the older software that build the board in a different manner and didn't appear to call a specific query. 

I am happy to "fix" my install if it is as simple as adding something like 

->eq(TaskModel::TABLE.'.is_active', TaskModel::STATUS_OPEN)

to the getExtendedQuery function if this would produce the desired effect.

### Actual behaviour
Public view shows all 6K tasks that have been created over the last year
Tell us what happens instead
Board shows all tasks including closed

### Steps to reproduce

1. select public link
2.
3.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.31
PHP version: 5.6.14
PHP SAPI: apache2handler
OS version: Linux 3.10.0-229.20.1.el7.x86_64
Database driver: mysql
Database version: 10.0.17-MariaDB-log
Browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by fguillot** [comment]
Thank you for raising this issue, it's now fixed in dev.

**Comment by entwisi** [comment]
Can you share the fix with me so I can get it onto my prod instance?                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Frédéric GuillotSent: Friday, 2 September 2016 01:54To: kanboard/kanboardReply To: kanboard/kanboardCc: entwisi; AuthorSubject: Re: [kanboard/kanboard] public view on latest releases shows all tasks, desired to only show open tasks (#2631)Thank you for raising this issue, it's now fixed in dev.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kanboard/kanboard","title":"kanboard/kanboard","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kanboard/kanboard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fguillot in #2631: Thank you for raising this issue, it's now fixed in dev."}],"action":{"name":"View Issue","url":"https://github.com/kanboard/kanboard/issues/2631#issuecomment-244255248"}}}

**Comment by fguillot** [comment]
The fix is available here: https://github.com/kanboard/kanboard/commit/6bad0523e581c6af1ab06dce726e2af1a08d9017

**Comment by entwisi** [comment]
Many thanks, I'm not an experienced php developer(my forte is websphere/middleware) but its slowly starting to make sense how it's all built‎.Ian                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Frédéric GuillotSent: Friday, 2 September 2016 23:32To: kanboard/kanboardReply To: kanboard/kanboardCc: entwisi; AuthorSubject: Re: [kanboard/kanboard] public view on latest releases shows all tasks, desired to only show open tasks (#2631)The fix is available here: 6bad052

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kanboard/kanboard","title":"kanboard/kanboard","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kanboard/kanboard"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fguillot in #2631: The fix is available here: https://github.com/kanboard/kanboard/commit/6bad0523e581c6af1ab06dce726e2af1a08d9017"}],"action":{"name":"View Issue","url":"https://github.com/kanboard/kanboard/issues/2631#issuecomment-244502405"}}}

**Comment by fguillot** [comment]
The fix is now available in Kanboard v1.0.33
