### ISSUE TITLE
External Links

### ISSUE THREAD

**Issue by skorvek** [kanboard/kanboard#2634]
### Expected behaviour

Adding external links that point to local resources should work.   Similar to Issue #1852, but not necessarily with file:// links

I use iOS and have multiple programs with URL Actions, whereby clicking on a resource link should open the program and open the proper file:  notebooks://show/path/to/file owncloud:// etc...

### Actual behaviour

Kanboard "cannot fetch link information"

### Steps to reproduce

1. Click External Link
2. Paste in local url to another program (not an http link)
3. Click Next

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: Git Master
- Database type and version: Postgresql latest
- PHP version: 5.x
- OS: iOS/Mac
- Browser: Safari

**Comment by fguillot** [comment]
It should works with Kanboard 1.0.34. Everything that not starts with http or ftp is considered a local file (your browser should be configured to open the right application according to the link type).
