### ISSUE TITLE
Feature request: starred projects

### ISSUE THREAD

**Issue by Jluisito** [kanboard/kanboard#2636]
Hi,
I think it would be a good feature the option to mark a project as "Starred". 
So, you can filter in your personal dashboard the tasks and subtasks related to starred projects, and focus on working on that projects.
The feature is similar to the star project in Trello, and must be a personal option for every user, not a global option. I.e, that each user is who chooses their starred projects.

**Comment by aljawaid** [comment]
Excellent idea but will also be useful for tasks/subtasks and not just projects.

**Comment by Jluisito** [comment]
Totally agree

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
