### ISSUE TITLE
403 Error when deleting Custom filters from other user

### ISSUE THREAD

**Issue by eSkiSo** [kanboard/kanboard#2637]
### Scenario

2 Admins in 1 project, admin 1 creates a custom filter, admin 2 tries to delete it
### Expected behaviour

Filter is deleted.
### Actual behaviour

Nothing happens, on console shows:

_NetworkError: 403 Forbidden - http://localhost/kanboard/?controller=CustomFilterController&action=edit&project_id=46&filter_id=13_

With response:

``` html
{"message":"Access Forbidden"}<section id="main">
    <p class="alert alert-error">
        Acesso negado    </p>
</section>
```
### Steps to reproduce
1. Have 2 Admins/Project Managers
2. Admin 1 creates custom filter
3. Admin 2 tries to delete it
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.32
- Database type and version: mysql 5.5.49-0ubuntu0.14.04.1
- PHP version: 5.5.9-1ubuntu4.19
- OS: Linux 3.13.0-93-generic
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by fguillot** [comment]
This is now fixed in the development branch. Thanks.
