### ISSUE TITLE
Cannot login on new installation as admin/admin

### ISSUE THREAD

**Issue by mironomi** [kanboard/kanboard#2643]
### Expected behaviour

Should be able to login as admin/admin after installation.
### Actual behaviour

It redirects to the login screen but says that the username and password are required.  
### Steps to reproduce

Try to login on a new installation.

Error logs from my site might help you:

PHP Warning:  session_start(): open(/hermes/phpsessions/-/9/s/Q/sess_-9sQluu70JZ,lDOOBGhVce5C2a6, O_RDWR) failed: No such file or directory (2) in /hermes/bosnaweb23a/b185/<domain>/public_html/kanboard/app/Core/Session/SessionManager.php on line 48 
PHP Warning:  Unknown: open(/hermes/phpsessions/-/9/s/Q/sess_-9sQluu70JZ,lDOOBGhVce5C2a6, O_RDWR) failed: No such file or directory (2) in Unknown on line 0 
PHP Warning:  Unknown: Failed to write session data (files). Please verify that the current 

Note that I have tested separate scripts that open new sessions using session_start and they have no problem..  Perhaps the error occurs due to the configuration of the sessions.  
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version:  1.0.31 and 1.0.32
- Database type and version: SQLITE 3.7.7.1
- PHP version: 5.3.29
- OS: Client OS is Windows 7 (although it doesn't matter in this case, its replicable on all OS)
- Browser: Google Chrome (again doesn't matter in this case)

**Comment by wmedsantos** [comment]
Hi, I have the same error .

 Kanboard version: 1.0.35
Database type and version: mySQL
PHP version: 5.3
OS: Client OS is Windows 7 (although it doesn't matter in this case, its replicable on all OS)
Browser: Google Chrome (again doesn't matter in this case)

**Comment by fguillot** [comment]
This issue is related to the configuration of your server, not Kanboard. According to the error message, PHP is not even able to write session files.
