### ISSUE TITLE
Captcha image not display

### ISSUE THREAD

**Issue by Smilefounder** [kanboard/kanboard#2644]
![06-09-2016-11-30-29](https://cloud.githubusercontent.com/assets/3785721/18261695/520b90ae-7425-11e6-9200-1179020a1966.png)
### Expected behaviour

Captcha should be display
### Actual behaviour

Captcha image not display
### Steps to reproduce
1. Click on forget password
### Configuration

Application version: 1.0.33
PHP version: 5.3.26
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.2
Database driver: mysql
Database version: 5.6.24-log
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by fguillot** [comment]
Which web server do you use, IIS? do you have the php extension "gd" enabled?

**Comment by Smilefounder** [comment]
Yes, I use IIS. Could you help to tell me how to enable "gd" ext? As I'm using Arvixe hosting.
Thanks.

**Comment by fguillot** [comment]
Usually, you just need to uncomment one line in the php.ini. But, unfortunately, I don't know how your hosting provider is working. This is probably better to ask them.
