### ISSUE TITLE
JSON-RPC - createTaskFile - Capture user details uploading the file

### ISSUE THREAD

**Issue by vk8996** [kanboard/kanboard#2645]
is it possible to provide the user details who attach the document to a task using JSON-RPC, createTaskFile?

Documentation shows

createTaskFile

Purpose: Create and upload a new task attachment
Parameters:
project_id (integer, required)
task_id (integer, required)
filename (integer, required)
blob File content encoded in base64 (string, required)

There is no option to update user_id column of the task_has_files table...

Please help...

**Comment by vk8996** [comment]
fixed it by myself. Thanks...

**Comment by Busfreak** [comment]
and can you provide the solution to the community please?

**Comment by vk8996** [comment]
Thanks for your comment Busfreak...

I am not sure whether I have implemented the fix in the correct manner also I am still doing UAT. This is what I did...

> TaskFileProcedure.php

public function createTaskFile($project_id, $task_id, $filename, $blob**, $user_id**)
    {
        ProjectAuthorization::getInstance($this->container)->check($this->getClassName(), 'createTaskFile', $project_id);

        try {
            return $this->taskFileModel->uploadContent($task_id, $filename, $blob**, $user_id**);
        } catch (ObjectStorageException $e) {
            $this->logger->error(__METHOD__.': '.$e->getMessage());
            return false;
        }
    }

> Filemodel.php

public function create($foreign_key_id, $name, $path, $size**, $user_id=0**)
    {
        $values = array(
            $this->getForeignKey() => $foreign_key_id,
            'name' => substr($name, 0, 255),
            'path' => $path,
            'is_image' => $this->isImage($name) ? 1 : 0,
            'size' => $size,
            **'user_id' => $this->userSession->getId() ?: $user_id,**
            'date' => time(),
        );

        $result = $this->db->table($this->getTable())->insert($values);

        if ($result) {
            $file_id = (int) $this->db->getLastId();
            $this->fireCreationEvent($file_id);
            return $file_id;
        }

        return false;
    }

_My sincere apologies to the authors if my way of implementation is incorrect._
