### ISSUE TITLE
Missing project title in due task mail

### ISSUE THREAD

**Issue by mdawart** [kanboard/kanboard#2646]
### Expected behaviour

Since updating to 1.0.32 the project title is no longer in the mail subject _[] 2 überfällige Aufgaben_ - in the mail body it is shown correctly

Is this a configuration issue or a possible bug?
 
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Version: 1.0.32
PHP Version: 7.0.10-pl0-gentoo
PHP SAPI: fpm-fcgi
OS Version: Linux 4.4.2-grsec
Datenbanktreiber: mysql
Datenbank Version: 5.6.28-log
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by fguillot** [comment]
This issue has been already fixed, you just need to upgrade to Kanboard v1.0.33

Thank you
