### ISSUE TITLE
missing RewriteBase in .htaccess

### ISSUE THREAD

**Issue by dunkelgruen** [kanboard/kanboard#2647]
When "installing" kanboard in a subdir (that is a "pseudo webroot"), the RewriteRules don't work anymore, giving me a "500 Internal Server Error".

Please add the following line to the htaccess:

RewriteBase /

...that fixed it for me.

**Comment by fguillot** [comment]
Which version of Apache do you use and which operating system?

**Comment by dunkelgruen** [comment]
running apache 2.2.15 on a centos 6.8

**Comment by leeomara** [comment]
We had the same issue running  Apache 2.2.15 on CentOs 6.7

In our case we we did not have kanboard in a subdirectory, but we are using dynamic vhosts.

The issue for us presented the odd behaviour where requests that explicitly included `index.php` would render fine, but those without (the default) would fail with a 500.

**Comment by remyguillaume** [comment]
Hello,

Thanks for the tip !
I had exactly the same problem on a mutualized hosting (1&1).
This solved the problem.

**Comment by fguillot** [comment]
The RewriteBase is now part of the .htaccess.

**Comment by jasmeetdd** [comment]
Hi Everyone!
Sorry for being an extreme novice in htaccess.

But I have Kanboard in a subfolder named "projects". Can someone tell me what do I write in place of this default htaccess:-

`<IfModule mod_rewrite.c>
    Options -MultiViews

    SetEnv HTTP_MOD_REWRITE On

    # Uncomment this line depending of your Apache configuration
    # RewriteBase /

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [QSA,L]
    
    ############################
    ## Uncomment the two lines below to enable force HTTPS capabilities
    ############################
    
    # RewriteCond %{HTTPS} !=on 
    # RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
</IfModule>

<IfModule pagespeed_module>
    ModPagespeed Off
</IfModule>
`

I have tried this but it did not work:-
`RewriteRule ^ /projects/index.php [QSA,L]`
It gives a page not found error. Please, help.

**Comment by jasmeetdd** [comment]
The only problem I am facing is that URL rewriting is not working in subfolder. 
Merely removing:
`SetEnv HTTP_MOD_REWRITE On
`
makes the website work but without url rewrites. Can something be done.

**Comment by aljawaid** [comment]
Try `RewriteBase /projects`

**Comment by jasmeetdd** [comment]
Sorry!

But the reason in my case was that "mod_env" was not installed on the server.
So,
`SetEnv HTTP_MOD_REWRITE On`
Never actually worked.
And hence, PHP never got to know that URL rewriting was enabled.

**I installed "mod_env"** and guess what?
Even the raw .htaccess that comes with kanboard started working. Even inside a subfolder.
No changes in .htaccess needed and all the rewrites are working perfectly.
