### ISSUE TITLE
Improvement of filter navigation with keyboard

### ISSUE THREAD

**Issue by donpatzone** [kanboard/kanboard#2648]
### Expected behaviour

When pressing F the focus is set to the filter bar. By pressing TAB you can then navigate to the filter dropdown and by pressing ENTER open up a dropdown field with various predefined filters. It would be an improvement when pressing the TAB key that the focus would move to the respective dropdown field.
This behaviour was already present in a previous version of Kanboard. If memory serves right it was around 1.0.21
### Actual behaviour

Currently the focus moves on to the next page element.
### Steps to reproduce
1. Focus the filter dropdown via TAB key menu and press ENTER
2. Press TAB again.
3. Focus moves to next page element, instead of dropdown field
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.33
- Database type and version: SQLite
- PHP version: 5.3
- OS: Windows Server 2008
- Browser: Firefox 48, Chrome 52

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
