### ISSUE TITLE
Turn off markdown shortcuts

### ISSUE THREAD

**Issue by Imbasaur** [kanboard/kanboard#2651]
We have polish special characters on alt + l and alt + c, and instead writing that character, shortcut activates which makes it impossible to write using polish characters.
### Steps to reproduce
1. Open edit task window
2. Try to write alt+l or alt+c
- Kanboard version: 1.0.32
- Database type and version: mysql 5.7.13-0ubuntu0.16.04.2
- PHP version: 7.0.8-0ubuntu0.16.04.2
- OS: Linux 4.4.0-36-generic
- Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by lukaszbulzacki** [comment]
Yes, I have same problem.

Or if it's not possible (not appropriate), please write in comment where (in what file) I can turn it off.
Thanks.

**Comment by lukaszbulzacki** [comment]
I found temporary solution.
In file kanboard/assets/js/app.min.js in expresion 
`new SimpleMDE({` 
you need add 
```
new SimpleMDE({shortcuts: {
            toggleBlockquote: null,
            toggleBold: null,
            cleanBlock: null,
            toggleHeadingSmaller: null,
            toggleUnorderedList: null,
            toggleItalic: null,
            drawLink: null,
            togglePreview: null,
            toggleCodeBlock: null,
            drawImage: null,
            toggleOrderedList: null,
            toggleHeadingBigger: null,
            toggleSideBySide: null,
            toggleFullScreen: null
        },
```

**Comment by Imbasaur** [comment]
Thanks!

**Comment by fguillot** [comment]
The text editor have been rewritten in v1.0.35 and CodeMirror/SimpleMDE is not used anymore. There is no keyboard shortcuts, it should work now.

Thank you.
