### ISSUE TITLE
Feature Request: Ability to Add custom tags to columns

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#2652]
Hello, 

Im requesting a way for custom tags to be added/defined on Board Columns.  This would allow Dashboard  Numbers (My Tasks) to reflect work that is in ToDo, Doing or Done depending on what you labeled the columns in your board to represent.  

For example say you had a board with Five Columns Backlog, Triage, Inprogress, OnHold, Done.    I would like the ability to add a custom label to each column to repersent what phase the task was in.  Backlog=ToDo, Triage=ToDo, InProgress=Doing, OnHold=Doing, Done=Done.    this way the Dashboard could be a more unified representation across all your boards.  This would allow you to define a base Representation of work across all your boards.

Thanks  

Sean Carson

**Comment by fguillot** [comment]
Unfortunately, I didn't plan to add such feature to avoid too much complexity in the software.
