### ISSUE TITLE
Upgrade Docs Confusion

### ISSUE THREAD

**Issue by aljawaid** [kanboard/kanboard#2653]
Can somebody please clarify how to upgrade from 1.0.32 to 1.0.33?

Am I correct in saying that as long as config.php stays intact... I can upload (ftp) and overwrite new version without any issues?

The docs mention the data "folder" which I'm not sure if it means the 'data' directory (only two files in that) or the whole extracted zip file as the 'data folder'

Any guidance would be appreciated.

### Configuration
- Kanboard version: 1.0.32

**Comment by eSkiSo** [comment]
You need to backup the **DATA** folder and review the new **config** file (some stuff were added), what  you can do to expedite this is actually "move" the data folder to an outside location (**kanboard_static** for example) and then on the **Config.php** change the **DATA_DIR** to something like: 

*define('DATA_DIR', '..'.DIRECTORY_SEPARATOR.'kanboard_static'.DIRECTORY_SEPARATOR.'data');*

This way you only need to worry about the config.php, but to answer your question:
- 1 : Rename your kanboard folder to something like kanboad_2
- 2 : Extract the downloaded version, renamed config.default.php to config.php
- 3 : Review and edit the new config.php
- 4 : Enjoy

**Comment by aljawaid** [comment]
@eSkiSo Thanks very much, that clarified a lot and I successfully upgraded.

**Comment by aljawaid** [comment]
@eSkiSo @fguillot Is it possible to skip from 1.40 to 1.45 or should I do it in steps?
