### ISSUE TITLE
Expand / Collapse Task Subtask and Descritpion

### ISSUE THREAD

**Issue by mauriziodidomenico** [kanboard/kanboard#2654]
### Actual behaviour

At the moment there are to possibilities to check the task content.
- Open the Task ![image](https://cloud.githubusercontent.com/assets/16655789/18379052/b5aa2ccc-7670-11e6-97ba-e7dfd776bb11.png)
- move mouse pointer over icon and keep it in position ![neues bild](https://cloud.githubusercontent.com/assets/16655789/18379097/e9c77c6c-7670-11e6-9cb4-ef7db1a718b3.jpg)
### Wish

My proposal is to implement an expand/collapse icon per task. So you have the possibility to check the task description and subtask in the board view and the possibilty to keep it open.  
![new1](https://cloud.githubusercontent.com/assets/16655789/18379231/a91eca8e-7671-11e6-8433-85e89e6fe254.jpg)
![new33](https://cloud.githubusercontent.com/assets/16655789/18379230/a9111240-7671-11e6-941c-809837d494d5.jpg)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
