### ISSUE TITLE
Subtask Event not found?

### ISSUE THREAD

**Issue by eSkiSo** [kanboard/kanboard#2655]
### Problem

I am creating a plugin to add more actions to **Subtasks** (Notify assignee on assignment), i've done similar ones for **Tasks**, but on **Subtasks** the Event does not show when creating the Action

### Snippet

Tell us what happens instead

on the Action i've tryied by the **SubtaskModel::EVENT_CREATE** and manually typing the task name **subtask.create**:

```php
...
use Kanboard\Model\TaskModel;
use Kanboard\Model\SubtaskModel;
...
public function getCompatibleEvents()
    {
        return array(
            'subtask.create', // this one does not show
            'task.create', // this one shows
        );
    }


```
Is there anything missing on the Event handler for subtasks?

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.33
- Database type and version: mysql 5.5.49-0ubuntu0.14.04.1
-  PHP version: 5.5.9-1ubuntu4.19
-  OS: Linux 3.13.0-93-generic
-  Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by fguillot** [comment]
Events for automated actions have to be added to the list in EventManager class: https://github.com/kanboard/kanboard/blob/master/app/Core/Event/EventManager.php#L44

**Comment by eSkiSo** [comment]
Thank you, got it working, injected it on the Plugin.php
