### ISSUE TITLE
Feature Request: Add Contact Details for Tasks and Subtasks

### ISSUE THREAD

**Issue by aljawaid** [kanboard/kanboard#2657]
### Actual behaviour

There is currently no way to associate an external contact to a task to store their details.
### Feature Request

We use the kanboard for a small local business.  When I create a task, there is usually a customer/supplier contact name/number associated with that task.  It would be very convenient if we could have an option to "add" a task contact (just a simple form with name, number, email, contact type) so that it is 'linked' with the task or subtask.

Then ideally we could pull up a list of contacts with associated tasks/subtasks for better workflow.
### Configuration
- Kanboard version: 1.0.33

**Comment by fguillot** [comment]
Duplicate with #2892
