### ISSUE TITLE
Feature Request: Switch to Task View Keyboard Shortcut 

### ISSUE THREAD

**Issue by connorbode** [kanboard/kanboard#2660]
### Ideal Scenario
1. Visit any area of a project (e.g. Board View)
2. Type `v t 123 g`
3. Task page for `Task #123` loads

The final key `g` ("go") would be used so that `Task #12` and `Task #123` are both accessible.

**If you can point me in the right direction for (1) Tools used for capturing keyboard events (`Mousetrap`?); and (2) Where this functionality would ideally be implemented; then I would be happy to implement and submit a PR**

Thanks!

**Comment by snth** [comment]
I would also like this and went digging through the code a bit.

It looks like the "v ?" sequence shortcuts are implemented in [`assets/js/Search.js` from line 50 onwards](https://github.com/kanboard/kanboard/blob/master/assets/js/src/Search.js#L50) .

I looked if I could figure out how to add it but the difficulty for me was that we need to capture the task number which it looks like the Mousetrap library doesn't support. So you would have to create an input element and then pop that up. I don't know enough Javascript to do that efficiently.

**Comment by snth** [comment]
Also, the URLs for the task seem to have the PROJECT_ID in them, e.g:

http://<HOST>/project/<PROJECT_ID>/task/<TASK_ID>

Why is that? It doesn't seem necessary to me and without that one could just generate a URL with the desired TASK_ID but this way you have to look up the PROJECT_ID first.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
