### ISSUE TITLE
Color dropdown width doesn't fit to longest color name

### ISSUE THREAD

**Issue by Imbasaur** [kanboard/kanboard#2661]
### Expected behaviour

Color dropdown width in task/create should fit to longest color name.
### Actual behaviour

![color dropdown](https://cloud.githubusercontent.com/assets/7914198/18437233/37cb8114-78fc-11e6-9ba0-474862e41e63.png)

Longest color name is "ciemnopomarańczowy" in polish, as you can see on screenshot it is bugging dropdown
### Steps to reproduce
1. Change language to polish
2. Open create/modify task form
3. Click select color dropdown
### Configuration

Kanboard version: 1.0.32
Database type and version: mysql 5.7.13-0ubuntu0.16.04.2
PHP version: 7.0.8-0ubuntu0.16.04.2
OS: Linux 4.4.0-36-generic
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by creecros** [comment]
@fguillot .color-picker{width:230px} would fix, not seeing any issues anywhere by doing so
