### ISSUE TITLE
Infinity task/Complexity length

### ISSUE THREAD

**Issue by Imbasaur** [kanboard/kanboard#2662]
### Expected behaviour

Complexity length should have max value

### Actual behaviour

Complexity length is infinity. Entering long value is causing Out of range SQL error

![complexity 1](https://cloud.githubusercontent.com/assets/7914198/18437428/23858e6a-78fd-11e6-8488-99bdb793691a.png)

![complexity 2](https://cloud.githubusercontent.com/assets/7914198/18437434/25c1d04e-78fd-11e6-9216-441fe913132e.png)

### Steps to reproduce

1. Open create/modify task form
2. Enter long Complexity value and save

### Configuration

Kanboard version: 1.0.32
Database type and version: mysql 5.7.13-0ubuntu0.16.04.2
PHP version: 7.0.8-0ubuntu0.16.04.2
OS: Linux 4.4.0-36-generic
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by fguillot** [comment]
This fix is now available in Kanboard 1.0.34.
