### ISSUE TITLE
task/creation hook values aren't merged if 'Create another task' is checked

### ISSUE THREAD

**Issue by Imbasaur** [kanboard/kanboard#2664]
### Expected behaviour

Hook task/creation values (controller:task:form:default and controller:task-creation:form:default) should be merged when 'another task' checkbox is checked

### Actual behaviour

Those values are not merged, because hook->merge function is running only if $values array in show() function is empty, and it's not because function afterSave() is providing default values
### Configuration

Kanboard version: 1.0.32
Database type and version: mysql 5.7.13-0ubuntu0.16.04.2
PHP version: 7.0.8-0ubuntu0.16.04.2
OS: Linux 4.4.0-36-generic
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by fguillot** [comment]
It should work with KB 1.0.34 otherwise reopen this ticket.

Thanks
