### ISSUE TITLE
403 Forbidden when edit & remove columns

### ISSUE THREAD

**Issue by inuvalogic** [kanboard/kanboard#2667]
### Expected behaviour

when edit & remove columns it should be no problem, as it is working fine in my localhost
### Actual behaviour

when edit & remove columns it show 403 Forbidden error below
- have tried in 2 different domain & hosting with installed kanboard, and the result are same
- have mod_security disabled, and the result are same
- have remove all htaccess file, and the result are same

Request URL:http://www.mydomain.com/kanboard/?controller=ColumnController&action=update&project_id=6&column_id=69
Request Method:POST
Status Code:403 Forbidden

Request URL:http://www.mydomain.com/kanboard/?controller=ColumnController&action=remove&project_id=6&column_id=69&remove=yes&csrf_token=mytoken123here
Request Method:GET
Status Code:403 Forbidden

Forbidden
You don't have permission to access /kanboard/ on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
### Steps to reproduce
1. login to kanboard
2. select a project
3. select Settings from Menu dropdown
4. select Columns from sidebar
5. edit a column, and save / remove column
6. 403 forbidden show here
### Configuration

Application version: 1.0.33
PHP version: 5.5.38
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-673.8.1.lve1.4.3.el6.x86_64
Database driver: mysql
Database version: 5.5.34-cll-lve
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36

**Comment by fguillot** [comment]
This is issue is related to the configuration of your server, not Kanboard itself. You should open the error log of the web server and you will see the root cause of the problem.

**Comment by inuvalogic** [comment]
yup, already fixed this issue on the last october by setting the apache conf, forget to update here hehe 😄 

in case other user find issue like me in the future, I have done something in this part <Directory "/home/domain/www/kanboard"> to Order allow,deny

anyway thanks for replying and keep the good work in this amazing kanboard 👍
