### ISSUE TITLE
FEATURE REQUEST: Highlight Comment icon if new comments added by team members

### ISSUE THREAD

**Issue by apmcodes** [kanboard/kanboard#2670]
This is not a bug but a feature request. Not sure where to post feature/ improvment request

In the Board, highlight comment symbol (one with the comment numbers) if any new comments added, so that other members can be aware of new comments. may be highlighted just like Due date highlight.

**Comment by OschauLars** [comment]
Good idea.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
