### ISSUE TITLE
bug with Template : Task_internal_link * (and with RabbitMQ?!)

### ISSUE THREAD

**Issue by alefaucheur** [kanboard/kanboard#2671]
### Expected behaviour
this->url->link for notification email in files: task_internal_link*.php should allow user to go and open the task in board.

### Actual behaviour
Link is broken, root part of the domain is not added correctly (missing:  http://x.x.x.x)
It seems to have 2 problems:
One with RabbitMQ plugin (or php worker?) which erases a part of the domain
One with url->link function in files : task_internal_link*.php  which erases another part of the domain

### Steps to reproduce
1. updating/creating/deleting internal task
2. broken link in received email notificaiton

### Configuration
- Kanboard version: 1.0.33
    Application version: master.20c187880ce9b5b4b55d3027f5df07ce042ad7ec
    PHP version: 5.6.15
    PHP SAPI: apache2handler
    OS version: Windows NT 6.1
    Database driver: mysql
    Database version: 10.1.9-MariaDB
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0
- RabbitMQ plugin : 1.0.0

**Comment by fguillot** [comment]
This issue should be fixed in Kanboard 1.0.34. Generated links in the email message should be absolutes and not relatives (the application url in settings must be defined too). 

Thanks
