### ISSUE TITLE
Reverse Proxy Authentication conflicts with Local Authentication cookies

### ISSUE THREAD

**Issue by nathancheek** [kanboard/kanboard#2674]
### Expected behaviour

If a Kanboard instance is switched from using local authentication to using SSO with Reverse Proxy Authentication, the new account name retrieved via  REVERSE_PROXY_USER_HEADER should take precedence over any old cookies identifying the previously locally authenticated user.
### Actual behaviour

A user is logged into Kanboard using local authentication, and then the Kanboard instance is switched to use Reverse Proxy Authentication. When the user reloads the website and authenticates through the proxy with a different username than was already logged in with local authentication, they will either get a 'Access Denied' error, or Kanboard will show them logged in as the old user. Deleting site cookies gets rid of this behavior.
### Steps to reproduce
1. Log into Kanboard using local authentication
2. Reconfigure Kanboard to use Reverse Proxy Authentication
3. Reload the Kanboard webpage and authenticate through the remote SSO server
4. The browser is returned to Kanboard which either shows 'Access Denied' or stays logged in as the previous locally authenticated user
### Configuration
- Application version: 1.0.33
- PHP version: 5.6.25
- PHP SAPI: apache2handler
- OS version: Linux 3.10.0-327.22.2.el7.x86_64
- Database driver: mysql
- Database version: 5.5.50-MariaDB
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by lapineige** [comment]
Is this the reason why it's not possible to use both an SSO + Reverse Proxy to authenticate the users, and local accounts at the same time ?
(it seems that to use local accounts, without the 'Access Denied' issue, you need to disable reverse proxy)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.7/developer_guide/faq.html).
