### ISSUE TITLE
Can't login with chrome unless cookies removed.

### ISSUE THREAD

**Issue by haler21** [kanboard/kanboard#2677]
### Steps to reproduce
1. Login into kanboard with chrome
2. close browser
3.  launch chrome enter username/password click signin.  returns to login page
4. delete kanban cookies KB_RM and KB_SID
   5  signin - even though username and password in fields -> message username and password required
   6 clear username and password and reentered - click sign in -> signed in successfully

Firefox and IE11 don't have this problem. 
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.33
PHP version: 7.0.11
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36- Browser: Chrome
IIS 8.5

**Comment by fguillot** [comment]
Can you try with the latest version of Kanboard? Can you make sure the PHP sessions are correctly configured? There is no reason that does not work with Chrome.
