### ISSUE TITLE
Group and/or filter time tracking (improvement)

### ISSUE THREAD

**Issue by OschauLars** [kanboard/kanboard#2682]
### Expected behaviour

It should be possible to filter or group all time tracking records. E.g. show all times for a certain user within a given period.

This is usefull to allow managers to see all times spent by a certain user for a given month or week
### Actual behaviour

Times are listed per project without any filtering.
### Steps to reproduce
1. Open a task
2. Open time tracking
3. List with all users for a project is listed and there is no filter

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
