### ISSUE TITLE
Completion is calculated based on the column (improvement)

### ISSUE THREAD

**Issue by OschauLars** [kanboard/kanboard#2683]
### Expected behaviour

It should be possible to assign a percentage of completion to a certain column or it should be possible to configure the pinboard not to display any percentage of completion.
### Actual behaviour

The completion of task is calculated based on the column. Tasks is the left most column are the most incomplete. The ones in the right most are the most complete.

Task in Gantt are displayed sorted by the column by default.

We use the columns to sort out the completion of a task. Starting from the left column we have "work in progress", "ready to start", "not assigned", "postponed", "finished". By doing this the project manager sees immediately in Pinboard AND Gantt the current tasks in a very natural way: reading from left to right / top down the level of completion is decreasing. Finished but not closed tasks are on the very right / bottom.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
