### ISSUE TITLE
Allow a custom icon

### ISSUE THREAD

**Issue by OschauLars** [kanboard/kanboard#2684]
### Expected behaviour

The FAVICON should be used in the upper left corner instead of the "KB" text.

We would like to customize the kanboard in such a way that we can use one of our logos as FAVICON and as a logo in the upper left corner.
### Actual behaviour

Currently in the upper left corner there is bicolored KB. The KB is a text and not a picture. It just flips the color when hovering over it.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
Version: 1.0.33
PHP Version: 7.0.9
PHP SAPI: cgi-fcgi
OS Version: Windows NT 6.3
Database driver: mysql
Database  Version: 5.7.14-log
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by Shaxine** [comment]
Currently this plugin allows you to do that and much more: https://github.com/phsteffen/kanboard-themeplus

**Comment by aljawaid** [comment]
Sounds good but it does not look compatible with 1.033

**Comment by Shaxine** [comment]
It's working fine here running from last commit.

And I have been using it for a while without any problem.

**Comment by OschauLars** [comment]
Thanks. Will try this Plugin.
