### ISSUE TITLE
.htaccess produces an internal server error on some configurations

### ISSUE THREAD

**Issue by krembo99** [kanboard/kanboard#2685]
### Expected behaviour

Kanboard should load without server problems
### Actual behaviour

On some server configurations , an internal server error will be caused by the `.htaccess` file.
Additional 500 error  would be produced .
### Error

The error from the log was :

`[Wed Sep 21 10:15:04.351886 2016] [core:alert] [pid 1016494] [client 104.xxx.yyy.111:43853] /home/mydomain/public_html/mydomain.TLD/kanboard/.htaccess: Invalid command 'SetEnv', perhaps misspelled or defined by a module not included in the server configuration`
### Steps to reproduce

On some servers I had a clean, smooth install & deploy , But I also encountered one server where an error was produced . 
Not sure config and reproduce steps as this was a simple shared hosting .
### Configuration

Application version: 1.0.32
PHP version: 5.6.24
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-673.26.1.lve1.4.15.el6.x86_64
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
### What was ( is ) the problem

Not sure , 
might be that the module for `SetEnv` was not installed / configured well
### Solution

The solution that worked for me was to change the line on the `.htaccess` file from : 

`SetEnv HTTP_MOD_REWRITE On`

to:

`SetEnvIf HTTP_MOD_REWRITE On`

The `If` condition would make the installation work, for now without visible problems, 

I am not sure if it will cause any issues ( is the `HTTP_MOD_REWRITE` really on or skipped ? ) 

If no additional issues occur - might need to change the default `.httaccess`  ( pull request for 2 characters ? )

**Comment by fguillot** [comment]
To be able to reproduce this issue, can you provide the Apache version that your are using and linux distro version?

**Comment by krembo99** [comment]
Like said in original comment , it is a shared hosting, so not really sure about all , but :

using` Cpanel` server information :

`Server Information
Item	Detail
Hosting Package	M***
Server Name	web10***
cPanel Version	58.0 (build 31)
Apache Version	2.4.23
PHP Version	5.6.24
MySQL Version	5.6.33-cll-lve
Architecture	x86_64
Operating System	linux
Shared IP Address	***.44.***.***
Path to Sendmail	/usr/sbin/sendmail
Path to Perl	/usr/bin/perl
Perl Version	5.10.1
Kernel Version	2.6.32-673.26.1.lve1.4.15.el6.x86_64`

Using php `uname` function and interpertation :
`Array
(
    [os_name] => Linux
    [uname_version_info] => #1 SMP Sun Jul 17 09:01:31 EDT 2016
    [machine_type] => x86_64
    [kernel] => 2.6.32-673.26.1.lve1.4.15.el6.x86_64
    [php_uname] => Linux web10***.***.com 2.6.32-673.26.1.lve1.4.15.el6.x86_64 #1 SMP Sun Jul 17 09:01:31 EDT 2016 x86_64
    [ubuntu_distribution] => 10.04
    [ubuntu_distribution_name] => Lucid Lynx
)
`

**Comment by fguillot** [comment]
If your shared hosting do not support mod_env, you can remove the SetEnv line and set to true the constants `ENABLE_URL_REWRITE` in your config file. The result will be the same.
