### ISSUE TITLE
Clean uploaded files when deleting a project

### ISSUE THREAD

**Issue by spst** [kanboard/kanboard#2687]
Dear development/support team,

I have a question concerning the deletion on tasks and projects:
- when I delete a task: will it be completely and without residue removed form the database, and will all attached files be deleted on the server?
- similarly for deleting projexts: will all tasks of the projects and their attached files be deleted?

Thanks in advance for any help,
Best regards
Stefan

**Comment by szawadski** [comment]
Apparently, when a task is deleted, the entry is removed from the database. This seems to be normal in opposition to the task closure, where the task remains in the table but not in default filter view.
Nevertheless, it would be appreciated to have a trace of the deletion in the activity log of the project.
Would it be possible to include in a future release?

Thanks in advance,

Sébastien

**Comment by fguillot** [comment]
Yes, there is no soft delete, the record is removed from the database.

This is not possible to keep a log of a deletion at the moment. The table schema have to be improved because a reference to the project_id or the task_id is used. There is a delete on cascade between references, if a task is removed the log entries are also removed.

**Comment by spst** [comment]
this is what I just figured out:

when I delete (not close) a task, files (in folder ./files/task/??? ) attached to it seem to be deleted as well. The subfolder relating to the task id however is not deleted. For the sake of tidiness, that might be a potential improvement for future versions.

when I delete an entire project, the tasks seem to be removed from the database, BUT any files attached to the tasks remain in the corresponding subdirectories of ./files/task/.
With time, this could lead to considerable clutter on the server.

So, to put it as an item for the wish list: "when as task with files attached ist deleted, the corresponding subdirectory in /files/tasks/ should be deleted as well. When a projetc is deleted, any files attached to tasks in that project and their subdirectories in /files/tasks/ should be deleted as well"

Best regards
Stefan

**Comment by fguillot** [comment]
Attachments are now removed when you delete a project (in dev branch).
