### ISSUE TITLE
Menu items links is full of block

### ISSUE THREAD

**Issue by vistar** [kanboard/kanboard#2688]
### Expected behaviour

Now menu item link <a> does not occupy the entire block <li>
### Steps to reproduce
1. Move mouse and click on meni item block and not in item text.
### Configuration
- Kanboard version: 1.0.33
- Database type and version: mysql 5.6.29-1~dotdeb+7.1
- PHP version: 5.5.38-1~dotdeb+7.1
- OS: Linux 3.2.0-4-686-pae
- Browser: Chromium 53

**Comment by fguillot** [comment]
Can you provide a screenshot?

**Comment by vistar** [comment]
On dashboard left sidebar: Menu item hovered but can't clicked. And many others menu items. This is not usable.
I tried to fix it шт pullrequest.

Sorry for my bad French :)

**Comment by fguillot** [comment]
Icons in menu items are now clickable in version 1.0.37.

Thank you
