### ISSUE TITLE
Click in black everything is gone

### ISSUE THREAD

**Issue by DaniWani** [kanboard/kanboard#2692]
### Expected behaviour

Ask about whether it should be saved.

### Actual behaviour

Click in the black around, then the popover area is closed. My Job is in vain.

### Steps to reproduce

1. Click on "Pinnwand" (german)
2. Click on "Aufgabe bearbeiten" (german)
3. Do some thing in popover (especially write a long description with many entries in lists)
4. Click by mistake in the black around
5. cry!

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: newest version
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by acs-ferreira** [comment]
You should remove

`
$(document).on("click", "#popover-container", function(e) {
        self.close(e);
    });
`

from `assests/js/src/Popover.js` (and/or `assets/js/app.min.js`)

Maybe this should be included on the project @fguillot ?

**Comment by eurodrew555** [comment]
This catches me out from time to time as well. My preference would be to require the cancel button to cancel. Clicking outside the task form shouldn't close the form.

**Comment by fguillot** [comment]
With Kanboard 1.0.34, clicking on the black background will not close anymore the form.
