### ISSUE TITLE
Add button to send test email

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#2693]
### Expected behaviour

I'd like to be able to send a test email to an email address I specify from the admin control panel on Kanboard
### Actual behaviour

I've set up my SMTP details on Kanboard, but don't know whether they're working or not ...
### Configuration

Application version: 1.0.33
PHP version: 5.6.21
PHP SAPI: apache2handler
OS version: Windows NT 6.2
Database driver: postgres
Database version: 9.5.2
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.90 Safari/537.36 Vivaldi/1.4.589.11

**Comment by OschauLars** [comment]
Just create a new user with your email adress and assign a task to him. If SMTP is set up correct you will get an email.

No issue.

**Comment by AlgyTaylor** [comment]
Thanks for the reply :+1: 

I know you can do that, but you just have to look at me over the past 2 days.  I keep getting my SMTP settings wrong (which is why I want an email).  To check them at the moment, I have to create a new user, then for every time I get it wrong go through:

1. create task
2. assign task
3. wait for email (or lack of email!)
4. delete task
5. change details
6. go to step 1

It would be much more convenient to have a single button that just sends a simple email (just with the text "Test" or something) to my address.  I know it's not a big thing, and but it's quite a small feature I think (probably < 10 lines of code, including the HTML+CSS) and it would save some time ...

**Comment by OschauLars** [comment]
Habe you tried to add an Action? There is an action that notifies the task owner  once you move the task from One column to another.

**Comment by robjurd** [comment]
Of course there's multiple workarounds for this.  What we're after is the ability to officially test the email configuration.

**Comment by risturiz** [comment]
I have same problem... Maybe some cli option to test email should be great... I have postfix working but "mail" dont work in kanboard

**Comment by fguillot** [comment]
@AlgyTaylor With Kanboard 1.0.40, if you would like to test your config, the most simple way is to send a task by email from the dropdown menu.

**Comment by AlgyTaylor** [comment]
@fguillot - Just going back to @robjurd's answer, this seems a bit like a workaround rather than a solution to me.  What happens, say, if 'send a task by email' is broken but the mail otherwise works?

**Comment by fguillot** [comment]
@AlgyTaylor Sorry, I read too fast your 2nd post and I missed the point. Yes, having a button to send a test email could be a trivial feature to implement.

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
