### ISSUE TITLE
Google Authenticator blocks API when "Allow User Creation" is active

### ISSUE THREAD

**Issue by TheCloud** [kanboard/kanboard#2696]
### Expected behaviour

Google Authentication should not block Kanboard APIs even if "Allow User Creation" is active on the Google Plugin.
### Actual behaviour

Login via API return "Unauthorized" if you have enabled the Google Auth plugin to create users
### Steps to reproduce
1. install the Google Plugin
2. enable User Creation option
3. API cannot authenticate anymore.

I tried both auth via standard auth user/pass and auth via header

FIX:
edit: /plugins/GoogleAuth/User/GoogleUserProvider.php
change getExtraAttributes() function so that it always returns array();
### Configuration

Versione dell'applicazione: 1.0.33
Versione PHP: 5.3.10
PHP SAPI: apache2handler
Versione OS: Linux 2.6.9-67.0.4.EL
Driver per Database sqlite
Versione database: 3.7.7.1
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
