### ISSUE TITLE
No events

### ISSUE THREAD

**Issue by wjdp** [kanboard/kanboard#2697]
### Expected behaviour

Should see many events in "Automatic actions" section
### Actual behaviour

Get this

![image](https://cloud.githubusercontent.com/assets/1690934/18838257/c0381dc0-83fe-11e6-9171-3cc9e60c96fe.png)
### Steps to reproduce

Attempting to add 'close task' when moved to completed column.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: master
PHP version: 7.0.9
PHP SAPI: fpm-fcgi
OS version: Linux 4.4.0-34-generic
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36

**Comment by fguillot** [comment]
The dropdown will show only events compatible with the selected action this why you see only 2 events.
