### ISSUE TITLE
[Framaboard] API-related questions

### ISSUE THREAD

**Issue by marienfressinaud** [kanboard/kanboard#2698]
**Context**
I'm working on updating Framaboard instance (which still use version 1.0.25!). Framaboard creates accounts with full administrator access (e.g. https://demo.framaboard.org `demo/demodemo`). Accounts are created based on information from a small form and guessed information (i.e. prefered language). There is only one Kanboard's instance shared for all the accounts and we need to init a new database each time an account is created. Kanboard knows which instance should be run by extracting account's name from the URL (e.g. https://demo.framaboard.org is the `demo` account) and setting the correct `DB_FILENAME` in `config.php`.

**Problem**
Today, database is initialized by creating a `Pimple\Container` and then a `Kanboard\Model\Config` and a `Kanboard\Model\User` in order to save new settings in the database ([code](https://framagit.org/framasoft/Framaboard/blob/master/common.php#L72-96) and [code](https://framagit.org/framasoft/Framaboard/blob/master/framaboard/index.php#L159-191)). Even if it's working, it breaks at each Framaboard's upgrades since Kanboard's code evolve… not cool!

**Solution**
I plan to avoid creating Kanboard's specific-objects and use an API instead which should be more reliable. I see two potential solutions:
- CLI (https://kanboard.net/documentation/cli): actually, I can't use it for anything since it does not offer any solution to update application's settings or user's configuration. However, it is very easy to use and do not need any authentication
- Json-RPC API (https://kanboard.net/documentation/api-json-rpc): in the current state, it can update user's configuration (not the password however if I look at the documentation and if it is up-to-date). Application's settings are still not available for update.

I need to set the following settings:
- application: `application_url`, `application_language`, `application_timezone` and `application_currency`
- user: `username`, `name`, `password` and `email`

Also, I need to create a cookie by hand ([code](https://framagit.org/framasoft/Framaboard/blob/master/framaboard/index.php#L237-259)) in order to autologin the user which just created its account. It's a bit beyond my first needs so we can consider this problem later.

**Questions**

I'll work on a PR in order to make it possible to init the database as I need. But first I have few questions:
1. Is there any other simpler and/or working solution that could solve my problem and I could miss?
2. Is there any related "work-in-progress" tickets that I could look at?
3. Otherwise, do you have any preferences for the API? I'll probably improve CLI commands but if you think it is more useful for the Json-RPC API I can work on it instead.

**Comment by fguillot** [comment]
- Yes, your code is too coupled to the Kanboard code and any change will break your provisionning script
- As far as I know, there is no open ticket for that
- You can implement the missing feature in the CLI or the API or both, if you choose the API it would be nice to have an integration test

Do you really need to autologin feature with the cookie?

**Comment by marienfressinaud** [comment]
It is, otherwise users fill the registration form, are redirected to their Framaboard instance and must fill the login form with the same information. It's boring for them

**Comment by fguillot** [comment]
If you still need to have these features, the best way is to write your own plugin or send a PR. Adding new command line tools or new API calls is pretty straightforward.
