### ISSUE TITLE
Filtering by swim-lanes - question

### ISSUE THREAD

**Issue by mgrabow1** [kanboard/kanboard#2700]
I am trying to filter my task list using multiple swim-lanes. 
According to the documentation:
"Find tasks into several swim-lanes: swimlane:"Version 1.2" swimlane:"Version 1.3" "
Does this mean that there is an OR in between or an AND? (is it even possible to have one task in multiple swim-lanes at once?)
I thought it would combine tasks from 2 different swimlanes, but I get no results...

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
