### ISSUE TITLE
PHP Warnings with Thumbnail generation

### ISSUE THREAD

**Issue by acs-ferreira** [kanboard/kanboard#2704]
### Expected behaviour

No warnings
### Actual behaviour

```
imagecreatefromstring(): Empty string or invalid image in /app/Core/Thumbnail.php on line 77
Division by zero in /app/Core/Thumbnail.php on line 110
Division by zero in /app/Core/Thumbnail.php on line 118
imagecopyresampled() expects parameter 2 to be resource, boolean given in /app/Core/Thumbnail.php on line 126
imagedestroy() expects parameter 1 to be resource, boolean given in /app/Core/Thumbnail.php on line 170
```

I'm not sure but it seems that these Warnings were produced after enabling **Gravatar** service.

**Comment by peter58228** [comment]
In my server, only first image uploaded no thumbnail, but second is fine. Even delete first image and upload same image file.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
