### ISSUE TITLE
Java API

### ISSUE THREAD

**Issue by phoen1x** [kanboard/kanboard#2708]
The idea behind this "feature request" of a Java API is to give the Java community a common ground at the [Json-RPC API](https://kanboard.net/documentation/api-json-rpc). Either to use functionality other users have implemented or extend a existing code base rather than start from scratch.

My project [kanboard-api-java](https://github.com/phoen1x/kanboard-api-java) reads this [YAML file](https://github.com/phoen1x/kanboard-api-java/blob/master/project/kanboard-spring/src/test/resources/application.yml) and creates a kanban board layout from a blank Kanboard installation. 

Therefore some functionality of

* user
* project
* task
* swimlane
* column
* automatic action

are already implemented in

* Java "without" dependencies
* Java Spring
* Apache Camel
* JUnit test against Docker. To test against future versions of Kanboard

I won't claim that my "pre-alpha" is the silver bullet for all Java developers, but it can be an origin to exchange ideas and start a Java API.

Regards,
Thomas

**Comment by fguillot** [comment]
Nice work! I'm not a java guy but it would be nice to see people contribute to your project.

**Comment by phoen1x** [comment]
Thanks! But I don't think it should be considered "my project" if other people join in. I see it more in a transit state, able to join you project if it proves useful. It would therefore be nice if I can start a pull request and add a link in the [Kanboard documentation](https://kanboard.net/documentation/api-examples) to let other developers know that they don't have to reinvent the wheel.

I added a simple [contribution guideline](https://github.com/phoen1x/kanboard-api-java#authors-and-contribution) and removed my licence. Which makes it easy to contribute or cherry-pick source code from the incubator.

The rest should be maintaining the API functionality for future Kanboard versions. Which I see as "my project" because my intelligent software assistant somehow needs to know about my overdue tasks. ;-)
