### ISSUE TITLE
Multiple time tracker running simultanously

### ISSUE THREAD

**Issue by gerritious** [kanboard/kanboard#2711]
### Expected behaviour

I expect a running timer to be stopped when I start tracking time another subtask.
### Actual behaviour

Two or more timers running at the same time (see screenshot). This could be reproduced on two separate installations of kanboard.
### Steps to reproduce
1. add a subtask and start time tracking this subtask or resume time tracking an existing subtask
2. add another subtask and start time tracking this subtask or resume time tracking another existing subtask 
3. There will be two subtasks being time tracked simultanously
### Configuration

Version: 1.0.33
PHP Version: 7.0.8-0ubuntu0.16.04.2
PHP SAPI: apache2handler
OS Version: Linux 4.4.0-38-generic
Datenbanktreiber: mysql
Datenbank Version: 5.7.15-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/52.0.2743.116 Chrome/52.0.2743.116 Safari/537.36
#### Installed Plugins:
- Gitlab Webhook
- Bitbucket Webhook
- Budget Planning
#### Screenshot

![kanboard-multiple-timers](https://cloud.githubusercontent.com/assets/3090084/18928294/b71167c0-85bf-11e6-9e30-b468c513b60c.png)

Maybe this is a feature I just don't understand? Thanks a lot!
gerriT

**Comment by fguillot** [comment]
At the moment, this is the expected behaviour. However, you can restrict a user to work only on a subtask at the time by changing the global settings: https://kanboard.net/documentation/project-configuration
