### ISSUE TITLE
SASL AD atutentication

### ISSUE THREAD

**Issue by lintzvl** [kanboard/kanboard#2713]
### Expected behaviour

I need to config my LDAP MS AD with Kanboard. 
My AD server uses GSS-API and SASL. 
I can connect it with LDAP/Admin, how you can see:

![image](https://cloud.githubusercontent.com/assets/22526674/18962983/60a53f62-8649-11e6-9731-24c28184cf2c.png)

### Actual behaviour

Authentication is failing. The debug generates the following statement:

[2016-09-29 13:18:28] [error] LDAP authentication failure for "my user"

### Steps to reproduce

I set the config.php as follows:

//LDAP

define('LDAP_AUTH', true);

// By default, require certificate to be verified for ldaps:// style URL. Set to false to skip the verification
define('LDAP_SSL_VERIFY', false);

// Enable LDAP START_TLS
define('LDAP_START_TLS', false);

define('LDAP_SERVER', '172.23.212.100');
define('LDAP_PORT', 389);

define('LDAP_BIND_TYPE', 'user');
define('LDAP_USERNAME', 'user');
define('LDAP_PASSWORD', 'password');

define('LDAP_USER_BASE_DN', 'dc=fazenda,dc=mg');
define('LDAP_USER_FILTER', '(&(sAMAccountName=%u)(objectclass=user))');

define('LDAP_USER_ATTRIBUTE_USERNAME', 'samaccountname');
define('LDAP_USER_ATTRIBUTE_FULLNAME', 'displayname');
define('LDAP_USER_ATTRIBUTE_PHOTO', 'jpegPhoto');
define('LDAP_USER_ATTRIBUTE_LANGUAGE', 'preferredLanguage');

define('LDAP_GROUP_PROVIDER', true);
define('LDAP_GROUP_BASE_DN', 'CN=Users,DC=fazenda,DC=mg');
define('LDAP_GROUP_FILTER', '(&(objectClass=group)(sAMAccountName=%s*))');
define('LDAP_GROUP_ATTRIBUTE_NAME', 'cn');

define('LDAP_USER_CREATION', true);

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version:1.0.33
- Database type and version: 10.1.16-MariaDB
- PHP version:5.5.38
- OS: Windows 7
- Browser:Chrome

**Comment by eSkiSo** [comment]
The problem does not appear to be on the configuration, but on the user you are using to login into kanboard, the so called "my user"

**Comment by acs-ferreira** [comment]
When entering user credentials, waht kind of data do you enter ?

You should use either `%s@domain.tld` or `KANBOARD\\%s` depending how your AD is configured.

The `%s` should be uses as is.

See also https://kanboard.net/documentation/ldap-authentication

**Comment by lintzvl** [comment]
Thank you, i solved this yesterday.
This is my configuration:

// Enable LDAP authentication (false by default)
define('LDAP_AUTH', true);

// LDAP server hostname
define('LDAP_SERVER', '172.23.212.100');

// LDAP server port (389 by default)
define('LDAP_PORT', 389);

// By default, require certificate to be verified for ldaps:// style URL. Set to false to skip the verification
define('LDAP_SSL_VERIFY', false);

// Enable LDAP START_TLS
define('LDAP_START_TLS', false);

// By default Kanboard lowercase the ldap username to avoid duplicate users (the database is case sensitive)
// Set to true if you want to preserve the case
define('LDAP_USERNAME_CASE_SENSITIVE', false);

// LDAP bind type: "anonymous", "user" or "proxy"
define('LDAP_BIND_TYPE', 'proxy');

// LDAP username to use with proxy mode
// LDAP username pattern to use with user mode
define('LDAP_USERNAME', 'sefatendesistema@fazenda.mg');

// LDAP password to use for proxy mode
define('LDAP_PASSWORD', 'Sef@17032016');

// LDAP DN for users
// Example for ActiveDirectory: CN=Users,DC=kanboard,DC=local
// Example for OpenLDAP: ou=People,dc=example,dc=com
//define('LDAP_USER_BASE_DN', 'ou=SEF,dc=fazenda,dc=mg'); //weblogic
define('LDAP_USER_BASE_DN', 'ou=SEF,dc=fazenda,dc=mg');

// LDAP pattern to use when searching for a user account
// Example for ActiveDirectory: '(&(objectClass=user)(sAMAccountName=%s))'
// Example for OpenLDAP: 'uid=%s'
//define('LDAP_USER_FILTER', '(&(sAMAccountName=%u)(objectclass=person))');  //weblogic
//define('LDAP_USER_FILTER', '(&(objectClass=user)(sAMAccountName=%s))');
define('LDAP_USER_FILTER', '(&(sAMAccountName=%s)(objectclass=person))');


// LDAP attribute for username
// Example for ActiveDirectory: 'samaccountname'
// Example for OpenLDAP: 'uid'
define('LDAP_USER_ATTRIBUTE_USERNAME', 'sAMAccountName');

// LDAP attribute for user full name
// Example for ActiveDirectory: 'displayname'
// Example for OpenLDAP: 'cn'
define('LDAP_USER_ATTRIBUTE_FULLNAME', 'displayname');

// LDAP attribute for user email
define('LDAP_USER_ATTRIBUTE_EMAIL', 'mail');

// LDAP attribute to find groups in user profile
define('LDAP_USER_ATTRIBUTE_GROUPS', 'memberof');

// LDAP attribute for user avatar image: thumbnailPhoto or jpegPhoto
define('LDAP_USER_ATTRIBUTE_PHOTO', 'jpegPhoto');

// LDAP attribute for user language, example: 'preferredlanguage'
// Put an empty string to disable language sync
define('LDAP_USER_ATTRIBUTE_LANGUAGE', '');

// Allow automatic LDAP user creation
define('LDAP_USER_CREATION', true);

// LDAP DN for administrators
// Example: CN=Kanboard-Admins,CN=Users,DC=kanboard,DC=local
define('LDAP_GROUP_ADMIN_DN', '');

// LDAP DN for managers
// Example: CN=Kanboard Managers,CN=Users,DC=kanboard,DC=local
define('LDAP_GROUP_MANAGER_DN', '');

// Enable LDAP group provider for project permissions
// The end-user will be able to browse LDAP groups from the user interface and allow access to specified projects
define('LDAP_GROUP_PROVIDER', false);

// LDAP Base DN for groups
define('LDAP_GROUP_BASE_DN', 'ou=SEF,dc=fazenda,dc=mg');

// LDAP group filter
// Example for ActiveDirectory: (&(objectClass=group)(sAMAccountName=%s*))
define('LDAP_GROUP_FILTER', '');

// LDAP user group filter
// If this filter is configured, Kanboard will search user groups in LDAP_GROUP_BASE_DN with this filter
// Example for OpenLDAP: (&(objectClass=posixGroup)(memberUid=%s))
define('LDAP_GROUP_USER_FILTER', '(&(cn=%g)(objectclass=groupofuniquenames))');

// LDAP attribute for the group name
define('LDAP_GROUP_ATTRIBUTE_NAME', 'cn');
