### ISSUE TITLE
Calendar View: Display Due Date more clearly

### ISSUE THREAD

**Issue by Biniou180** [kanboard/kanboard#2715]
I open this ticket as a contributor of Framaboard.
### Actual behaviour

When setting a start date and due date to a task, this task appears in calendar view.

For example when start date set on September 30th and due date on October 1st:
![startDate_Sept30&dueDate_Oct1st.png](https://framapic.org/kTeMJIyVVz1I/yexyYoFoRYGn)

...and both start date and due date set on October 1st:
![start&dueDate_Oct1st.png](https://framapic.org/ZHl60ILZ4NS1/EuTlS8z2zkpO)

It is not very clear that the second item is the due date, and some of our users didn't understand why they have "two" items for a task in the calendar.
### Suggested solutions
- Why not display the end of the task in continuity of the task itself? (for example in the first screenshot, join the two items together to make one, and in the screenshot display only one)
- Another solution would be to make the due date clearer: adding a title or icon (?) to indicate this is a due date

As always, thanks for kanboard :-)
### Steps to reproduce
1. create an event with start and due dates
2. Display the calendar for this dates and check the task
### Configuration

Tested on framaboard 1.25 (updated soon!) and Kanboard 1.0.33

**Comment by NoodleBB** [comment]
Same problem with the Calendar view in Kanboard 1.0.40

Breaks in the displayed Taskbars. Doubled task bars. Some with a addition "**12a**" before the task number. It's confusing.

![bildschirmfoto 2017-03-23 um 12 47 30](https://cloud.githubusercontent.com/assets/11850083/24246900/b334c1c6-0fc9-11e7-9170-bd190afc8cd5.png)

**Comment by fguillot** [comment]
Tickets related to the calendar should be posted to the calendar plugin bug tracker: https://github.com/kanboard/plugin-calendar/issues

Thank you

**Comment by NoodleBB** [comment]
Linked to: https://github.com/kanboard/plugin-calendar/issues/3
