### ISSUE TITLE
Let users create tasks with start date older then today

### ISSUE THREAD

**Issue by Stepkaa** [kanboard/kanboard#2716]
How can I achieve this? I looked the /app/Core/DateParser.php file, but had no success. Thanks.

**Comment by acs-ferreira** [comment]
This is already possible, just choose the whished date.
See http://s18.postimg.org/jhyjp31cp/screenshot_131.png

**Comment by Stepkaa** [comment]
Yes, thanks. But I think, I was not clear about my question, sorry for that. What I want is to have task creation date == task start date. Now I can manually edit it in the db, but is there any way to change the task creation algorithm?

**Comment by acs-ferreira** [comment]
Go to `app/Model/TaskCreationModel.php` line 84

Replace
`$values['date_creation'] = time();`
with 
`$values['date_creation'] = $values['date_started'];`

This will affect all future created tasks, an they will allways have the created date == start date.

**Comment by Stepkaa** [comment]
Wow, thanks for quick reply! This is exactly what I need.
