### ISSUE TITLE
Does kanboard support issues from multiple gitlab projects?

### ISSUE THREAD

**Issue by kramer65** [kanboard/kanboard#2719]
I'm looking into moving our teams to gitlab, but the one and only thing I (and I think many other people) need, is to be able to have a kanban board where I can reference issues from multiple projects/repos.

Many projects, including ours, includes multiple repos, such as:
- ios app
- android app
- api backend

but unfortunately, gitlab currently doesn't support boards in which you can reference issues from multiple gitlab projects. Does your kanban board support this?

**Comment by fguillot** [comment]
With Kanboard you can have multiple projects and you can use internal links to reference tasks across projects. Example: https://kanboard.net/documentation/task-links

If you use Gitlab, you could use the webhook plugin to copy issues from Gitlab to Kanboard. But at the moment, this is a one-way synchronization.
