### ISSUE TITLE
Kanboard internal hook when moving a task to a different column

### ISSUE THREAD

**Issue by trajche** [kanboard/kanboard#2720]
I would like to create a warning prompt, for users, when moving tasks from one column to another (only if that task has "internal links" to another task). That way the users will know they are moving a task with a dependency instead of having to read the task details.

Are there any hooks/events we could use to do this and call a js function?
I saw the web hooks, but that's for external applications from what I understand.

**Comment by fguillot** [comment]
At the moment, it's a bit tricky to implement a feature like that.

The best way is probably to extend the custom project role available in the development branch. You can apply restrictions based on the columns, for example you can move tasks only between the column A and B.

You could implement a new restriction that force tasks to have internal links.

**Comment by kgeil** [comment]
On this note, Is it possible to require that a note is added when moving a task from column B to Column A?  For example, if a supervisor requests that a task be done, and it exceeds the wip limit, and the task owner moves another task from B to A, it would be great to require a note be added to the task.
Forgive me if this already exists...

Thanks,
Kevin

**Comment by trajche** [comment]
@kgeil @fguillot I think a new 'hook' feature would be required in order to be able to develop plugins that are able to have callback upon certain 'actions'.

Simple JS hooks example: http://www.velvetcache.org/2010/08/19/a-simple-javascript-hooks-system
Similar to the webhooks selection: https://kanboard.net/documentation/webhooks
except that it would be called right away on the frontend.

**Comment by fguillot** [comment]
If you really need this feature, the best way is to contribute to the project to implement the missing part.
