### ISSUE TITLE
Overdue task email notification only in weekdays

### ISSUE THREAD

**Issue by zijam** [kanboard/kanboard#2721]
### Expected behaviour

I would like to get overdue email notification from kanboard only in weekdays

### Actual behaviour

I get notification every day also in the weekend.

### Steps to reproduce

1. Setup a task
2. Set the end date for the task 

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: git - master
- Database type and version: sqlite 3.13.0
- PHP version: 7.0.8
- OS: Linux 3.10.0-327.22.2.el7.x86_64
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

**Comment by felicson** [comment]
Hi!
Try use "kanboard notification:overdue-tasks" on weekdays in your crontab, and "kanboard projects:daily-stats" everyday for generate statistics.

https://github.com/kanboard/kanboard/blob/master/doc/cli.markdown

**Comment by zijam** [comment]
Thx.
I changed the cronjob in  /var/spool/cron/crontabs/nginx to only run in weekdays ;)
