### ISSUE TITLE
AD User default Config - Notification

### ISSUE THREAD

**Issue by mauricio-sonegatti** [kanboard/kanboard#2722]
Using kanboard with AD user I can`t define the default notification methods.
For now, each remote AD user that login on kanboard have to manually set the notification methods.
### Configuration
- Kanboard version: 1.0.33
- Database type and version:  sqlite 3.8.3.1
- PHP version: 5.5.11
- OS: Windows Server 2012 - iis 8.5
- Browser: Firefox ESR 38.1.0

**Comment by fguillot** [comment]
What behaviour do you suggest? how would you like to configure that for your users?

**Comment by ptman** [comment]
By default I think new users should get all notifications and then they'd need to reduce them if that's too much.

**Comment by mauricio-sonegatti** [comment]
I concour that all notifications is the best approach with less coding needed.
Perhaps an entry to config.php like define('LDAP_USER_DEFAULT_NOTIFICATION', 'mail') or 'web' or 'all' could work too.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
