### ISSUE TITLE
search/filter with empty value or null

### ISSUE THREAD

**Issue by GitHub-Lover** [kanboard/kanboard#2727]
On the feature of searching (IMHO is more filtering) tasks on board or list, I did try this:

  `status:open due:none`
OR
  `status:open due:""`
OR
  `status:open due:NULL`

With this I want to see only the task which have no due date. 

---

I also get an empty list, when I search for this:

  `status:open tag:""`
OR
  `status:open tag:none`
OR
 `status:open tag:NULL`

I guess other fields are with this issue also.

---

**Am I doing something wrong, or is searching/filtering for NULL/empty-fields/blank-files not supported?**

If not supported, I would be happy to see this feature in future (for all fields?). Thank you so much.

Github-Lover

**Comment by cbrachem** [comment]
Filtering with `due:none` is now possible.

Can this issue be closed?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
