### ISSUE TITLE
search/filter: is there a OR operator?

### ISSUE THREAD

**Issue by GitHub-Lover** [kanboard/kanboard#2728]
I tried this on search/filter

  `status:open category:none | category:"abc"`
OR
  `status:open category:none OR category:"abc"`

Did not work for me so far... or am I doing something wrong?

If not, this would be a nice feature. Thank you.

GitHub-Lover

---

Version: 1.0.33
PHP Version: 5.4.16
PHP SAPI: apache2handler
OS Version: Linux 3.10.0-327.28.3.el7.x86_64
Datenbanktreiber: mysql
Datenbank Version: 10.1.16-MariaDB
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by NinjaPewPew** [comment]
The OR operator is not yet supported. Source #2519.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
