### ISSUE TITLE
How to get access when emailing is not configured? 

### ISSUE THREAD

**Issue by w1ld** [kanboard/kanboard#2729]
Thanks for the tool! 

This is not a bug. I just want to get access with 'admin'. The password was lost (my machine broke). Kanboard is not configured correctly to send email (Windows 2012, Azure, IIS). So I can not get email for admin. I have full access to the files. How can I reset the password manually? (Can I just open DB and clear some values? Which ones?) 
### Configuration
- Kanboard version: 1.0.33
- Database type and version: sqlite, 3.8.10.2
- PHP version: 7.0.9
- OS: Windows NT 6.3

**Comment by w1ld** [comment]
I've erased field Password for admin in the users table and got: "Internal Error: SQLSTATE[HY000] [14] unable to open database file"

**Comment by fguillot** [comment]
If you want to reset the admin password by changing directly the database, you can use the method described here: https://github.com/kanboard/kanboard/issues/853

However, if you do something wrong, it might be harmful for your installation.
