### ISSUE TITLE
LDAP thumbnail doesn`t load correctly

### ISSUE THREAD

**Issue by mauricio-sonegatti** [kanboard/kanboard#2732]
### Expected behaviour

The LDAP image is created when the user login the first time and it`s shown in the right places.
### Actual behaviour

The problem was noted by @mickusmaximus in august (Issue #2183), but I didn't saw any follow up.
The image is downloaded "correctly" to the avatars folder, but kanboard is unable to load the image.
The size of the image makes no sense (too big, bigger than TIF and PNG from the same image), but the imaging software can open it without a problem.
When I remove the automatic image and re-upload the same image through the avatar page the error persists (file appears corrupt because of this), if I use the original LDAP JPEG or PNG it works as intended.
I couldn't identify for now if some error response is being written to the thumbnail file, and it`s not shown anywhere in the log that an error occurred.
### Steps to reproduce
1. LDAP user login
2. Thumbnail is entirely black
   The problem was noted on IIS+PHP.
   ### Configuration
   Application version: 1.0.33
   PHP version: 5.5.11
   PHP SAPI: cgi-fcgi
   OS version: Windows NT 6.2
   Database driver: sqlite
   Database version: 3.8.3.1
   Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by fguillot** [comment]
What is the format of the source image?

**Comment by mauricio-sonegatti** [comment]
The AD image was uploaded from a JPG.
Attached the images that I uploaded and downloaded from AD through kanboard.

![downloaded_ad](https://cloud.githubusercontent.com/assets/22504353/19198342/0498f838-8c95-11e6-88e8-4257db1ee087.jpg)
![uploaded](https://cloud.githubusercontent.com/assets/22504353/19198343/04cb5a1c-8c95-11e6-98db-fe5b58e1fd36.jpg)

**Comment by mauricio-sonegatti** [comment]
After some time, it was working, now that I'm deploying again a new Kanboard, the error was there.
By the end, it was an malformed jpeg file on the AD server that was the culprit, I got to this solution because every other thumbnailPhoto was at ~4KB, mine was at 74KB at the server, after changing for other file, it converted beautifully and it's working now as intended.
Closing
