### ISSUE TITLE
Duplicate swimlane

### ISSUE THREAD

**Issue by jfrenard** [kanboard/kanboard#2735]
### Expected behaviour

Duplicate swimlane
### Actual behaviour

There is no possibility to duplicate a swimlane 
### Steps to reproduce

1.
2.
3.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.33
- Database type and version: mariadb 10.1
- PHP version: 5.6
- OS: debian stable jessie
- Browser: FF 49.0.1

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
