### ISSUE TITLE
Looking for tips on how to add new CLI Email Reports

### ISSUE THREAD

**Issue by orware** [kanboard/kanboard#2737]
This is more asking for reference information so I can work on this as a feature on my own and submit a pull request once I have it available.

Currently I have two report ideas I'd like to build out:
- A Recently "Done" Report showing items that were moved to the Done column in the last week.
- A Forward Looking Report showing the items due in the Upcoming Week.

I'd like to add some additional Console tasks to accomplish this, but I'm not sure what would be the best way to integrate into the Kanboard project in a way that would be acceptable for inclusion (following the other conventions used inside of the project already).

So mainly I'm looking for some tips on how I could approach this and some similar examples maybe within the codebase I could draw from and then I can take it from there and work on this.

Thanks!

Here are the two queries I've put together that should more or less accomplish what I'm looking for:

```
-- Recently Completed Tasks (Last 7 Days):
select *
from tasks
WHERE column_id IN (                    
                    SELECT id 
                    FROM `columns`
                    where title = 'Done'
                    AND project_id in (SELECT id 
                                        FROM `projects`
                                        WHERE name in ('Application Services', 'Enterprise Systems', 'CTO Office', 'Online Services')))
and date_modification > (UNIX_TIMESTAMP() - (7 * 24 * 3600))

-- Upcoming (Due) Tasks for Coming Week:
select *
from tasks
WHERE project_id IN (SELECT id 
                    FROM `projects`
                    WHERE name in ('Application Services', 'Enterprise Systems', 'CTO Office', 'Online Services'))
and date_due > UNIX_TIMESTAMP()
and date_due < (UNIX_TIMESTAMP() + (7 * 24 * 3600))
```

**Comment by fguillot** [comment]
To add a new command, you just need to create a new class into the app/Console folder and register this class in CommandProvider. You could do the same from a plugin.
