### ISSUE TITLE
Bug: Parallel editing/overwriting of Task

### ISSUE THREAD

**Issue by salomonderossi** [kanboard/kanboard#2741]
### Expected behaviour

I do not know what the best strategy is. Maybe warn or lock user, when another user is currently editing the task. Or merge like git (when possible)
### Actual behaviour

The user which first edits the task wins and the information gets saved. The information which the other user had entered is lost. 

To sum this up: One user is overwriting the information of the other user
### Steps to reproduce
1. Login with "user one"
2. Edit the description from "Task 1" from "Project 1"
3. Do not save the edits, yet
4. In another browser login with "user two"
5. Also edit the description from "Task 1" from "Project 1"
6. Save the edits from "user two"
7. Save the edits from "user one"
8. The edits from user two are lost
### Configuration
- Application version: 1.0.33
- PHP version: 7.0.11
- PHP SAPI: cgi-fcgi
- OS version: Linux 2.6.32-531.17.1.lve1.2.60.el6.x86_64
- Database driver: postgres
- Database version: 9.1.23
- Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by fguillot** [comment]
Duplicate with #944
