### ISSUE TITLE
Sending mail when creating a task

### ISSUE THREAD

**Issue by gregfr** [kanboard/kanboard#2746]
Greetings
I was wondering if there was a way to send an email to the team when a new task is added ; I was found out how to send when an existing task is modified, but not when a new one is created.

Thanks

**Comment by Trapulo** [comment]
Ops, I noticed this just now, so my #2793 duplicates it...

**Comment by gregfr** [comment]
I hope it won't stay unoticed by the devs ;)

**Comment by fguillot** [comment]
Actually, you can already receive notifications when a task is created. The project members have to change their settings to receive all notifications. However, receiving everything might be a little bit spammy.

**Comment by Trapulo** [comment]
I think that an administrative option to notify task assignments will fit better workgroup scenarios...

**Comment by gregfr** [comment]
Thanks for your answer. I'll test the "all notifications" method.
Is there a reason why it's not in the "automated actions"?
TIA

**Comment by fguillot** [comment]
There is now an automated action to send new tasks by email.

**Comment by gregfr** [comment]
Smiley icons are silly but thanks for adding this!
