### ISSUE TITLE
How to defer mail sending to send through a cron job 

### ISSUE THREAD

**Issue by marcosaccioly** [kanboard/kanboard#2748]
I know there are plugins for beanstalk or rabbit. But on a shared host environment there's no way to install them. I'd like to be able to defer mail sending to be done, say, once an hour, **using a cron job**. Is that even possible? I've seen that I can use cron jobs along with the CLI to schedule sending of overdue tasks. 

What about regular task emailing? Is it possible to do using the CLI or by making a plugin? 

Kanboard settings:

Versão da aplicação: 1.0.27
PHP version: 5.5.9-1ubuntu4.19
PHP SAPI: apache2handler
OS version: Linux 3.16.0-77-generic
Driver do banco de dados: mysql
Database version: 5.5.52-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by fguillot** [comment]
At the moment, this is not possible, the source code have to be modified. The best approach might be to stack notifications and send a digest email instead of sending individual emails.

**Comment by marcosaccioly** [comment]
Thanks, Frédéric. I'll try to implement the digest as a plugin for a test.

**Comment by gerhard-tinned** [comment]
How do you "stach notifications andsend a digest email"? I would love to do that as users complained about too many email notifications.

**Comment by fguillot** [comment]
@gerhard-tinned Instead of sending the notification right away, store it in the database...

**Comment by gerhard-tinned** [comment]
@fguillot Yes, I understood that. But how do you configure that in Kanboard? I could not find any setting for that.

**Comment by fguillot** [comment]
@gerhard-tinned This improvement is not developed yet.

**Comment by gerhard-tinned** [comment]
Is this feature on the roadmap?

**Comment by fguillot** [comment]
@gerhard-tinned Everything that is annoying is on the roadmap

Move discussion to #2742
