### ISSUE TITLE
"project_has_roles doesn't" exist

### ISSUE THREAD

**Issue by pfabri** [kanboard/kanboard#2749]
Many thanks for looking into this, Frederic.
### Expected behaviour

I click on 'overview' inside a project and see the overview page.
### Actual behaviour

Error is thrown:

`Internal Error: SQL error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'peteqvzr_kbrd.project_has_roles' doesn't exist`
### Steps to reproduce
1. Click on a project
2. Click on 'overview'
3. Enjoy error message.
### Additional info

This is a fresh install, and I imported the mysql dump that came with the zipped source.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

```
Application version: 1.0.34
PHP version: 5.6.25
PHP SAPI: cgi-fcgi
OS version: Linux 3.10.0-427.18.2.lve1.4.15.el7.x86_64
Database driver: mysql
Database version: 5.6.33
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
```

**Comment by pfabri** [comment]
I've just discovered, that the `project_has_roles` TABLE definition is missing for **mySQL** in the schema. It is defined for sqLite and PostgreSQL, though.

**Comment by fguillot** [comment]
Did you had any errors during the database migration process? The table should be created automatically.

**Comment by pfabri** [comment]
No, there were no errors at all. I imported `Mysql.sql` straight into the empty database using phpMyAdmin.

Things I've noticed:

- there's no definition for `project_has_roles` inside `Mysql.sql`, however
- the definition exists inside `Mysql.php`
- `schema_version` inside the database is `115`, which I can see is the newest function inside `Mysql.php`

So I'm guessing that if I were to run `Mysql.php` it would create the necessary missing tables. How can I do this, would you please be able to help? I've checked the documentation, but it is not clear how to run this updater script.

Many thanks in advance!

**Comment by pfabri** [comment]
Okay, I managed to solve the problem as follows
! Please note, that mine was a fresh install, so the database was empty.

1. emptied out the kanboard database (i.e. dropped all tables)
2. downloaded v1.0.33
3. imported the sql dump from v.1.0.33 into the database (located in `app/Schema/Sql/mysql.sql`
4. then  went back to V1.0.34 and opened up `app/Schema/Mysql.php` and executed each SQL query from within `function version_113(PDO $pdo)` to `function version_115(PDO $pdo)`  
**Note:** v1.0.33 corresponds to `function version_` **112**  
You need to start with 113, execute the queries in the same order php would do it: top --> down that is.   Then continue with 114, then 115.

That's all.
