### ISSUE TITLE
Import custom roles in creating the project

### ISSUE THREAD

**Issue by helfreire** [kanboard/kanboard#2750]
Good afternoon,

I wonder if you can develop the option to copy the custom permissions for another project.

![image](https://cloud.githubusercontent.com/assets/5896776/19363965/8c1fee34-9162-11e6-8367-e7080b2e48aa.png)

Thank you

**Comment by ManasN** [comment]
Please do this, this is very useful.

**Comment by lintzvl** [comment]
Do you have forecast for this improvement in the system?

**Comment by matteomazza91** [comment]
is there a plan for this feature request? 

Without this I cannot "clone/duplicate" any project because users in the custom role "developer" will become **Project Manager** breaking my permission setup

**Comment by matteomazza91** [comment]
I can start working on this

**Comment by matteomazza91** [comment]
@fguillot maybe this issue can be closed. I can't close, can you?
