### ISSUE TITLE
Feature: Change the column of a task from the task page

### ISSUE THREAD

**Issue by elfalem** [kanboard/kanboard#2751]
Please consider a feature to have a row of buttons on the task details page to move a task. For example, we have the columns New, In Progress, and Done and a task in the In Progress column. When viewing the details of this task, there would be buttons for "New" and "Done". Clicking on "Done" would move the task to that column.

Perhaps you can also configure the button names per column and also restrict which transitions are possible. For example, when an In Progress task is viewed, show a button called "Finish Task" (which transitions the task to "Done" column) and don't show a button for "New" (to prevent moving the task back). The transition restrictions would also require a corresponding implementation on the actual board to disallow dragging a task to a column if it would override the restrictions in place.

**Comment by fguillot** [comment]
Moving tasks between columns is already possible from the task view page. However, the feature is more generic to fit with the different workflow that people might use.
