### ISSUE TITLE
Feature: allow multiple boards per project

### ISSUE THREAD

**Issue by elfalem** [kanboard/kanboard#2752]
Please consider allowing creating additional boards for a project. These boards can be customized in different ways.

For this proposal, assume that we have redefined what we currently call columns to be "states". So when a project is created, it will have several states. There will also be a default board created as it's done now that has the same columns as the states. The user can then create additional boards that have a different set of columns. Which tickets a column shows in can be configured using a filter.

For example, a user can create a new project with the states: New, Backlog, Ready For Work, In Progress, In Review, Done. The default board will have six columns, one for each state. The user then creates a second board for a more condensed view. It has the columns Queue (showing tasks with states New and Backlog), Active (states of In Progress and In Review), and Completed (state of Done). More complex filters can also be used (e.g. tasks with certain tags or categories).

This would require setting a default state for a column when a task is moved into that column (on the second board in the example, moving a task to "Active" is ambiguous since it includes tasks from two states) or the plus icon next to the column title is used to create new task.

**Comment by fguillot** [comment]
Unfortunately, features like that won't be developed because that will require too much changes in the software.
