### ISSUE TITLE
Overlay dialogs don't actually close

### ISSUE THREAD

**Issue by rwimpers** [kanboard/kanboard#2754]
### Expected behaviour

When you close an overlay dialog, the screen behind should be visible again.
### Actual behaviour

When I close an overlay dialog by saving, a white bar stays on top of the page and the rest of the page behind this bar is nearly black.
The state remains until I actively reload the page. 

I see the same behaviour with varoius overlay dialogs:
- Edit the task
- Edit recurrence
- Add a sub-task
- Add internal link
- and surely more

I can reproduce this behavoir with Chrome, Firefox, Internet Explorer and Edge.
I use the default configuration and just made some minor changes to the ".htaccess" file in the root directory:

CHANGED: SetEnv HTTP_MOD_REWRITE Off
ADDED: RewriteBase /
### Steps to reproduce

From the Board
1. Click on the avatar of a task, so that the overlay dialog shows up
2. Click "save" (with or without editing)
3. The overlay dialog changes into a white bar at the top

From the task-summary
1. Click on "Edit the task", so that the overlay dialog shows up
2. Click "save" (with or without editing)
3. The overlay dialog changes into a white bar at the top
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.34
- Database type and version: sqlite 3.8.4.3
- PHP version: 5.5.14
- OS: Linux 2.6.32.53-grsec-pvops-xen-x64
- Browser: Chrome, Firefox, Internet Explorer, Edge

**Comment by fguillot** [comment]
Can you send a screenshot of your problem? Did you upgrade from a previous version of Kanboard to the last one? Did you try to flush the browser cache?

**Comment by rwimpers** [comment]
Hello!

Sorry for the late answer.
See attached a screenshot of the behaviour.

I upgraded from version 1.0.32 to 1.0.34. (I renamed the Kanboard-folder on my web server, then uploaded the new version to the server and then copied the content of the data folder and the .htaccess-file in the root folder from the old version to the new one.)

In version 1.0.32 klicking outside the white bar closed the bar. That was not nice, but I could live with it.

Flushing the browser-cache does not change the behaviour.

![screenshot_overlay_not_closing](https://cloud.githubusercontent.com/assets/15425559/19717004/e94384ee-9b5e-11e6-96a5-4db532d9125e.png)

I hope this helps.

**Comment by pingadi** [comment]
I'm also having this issue when saving data with dialog.
Could reproduce by creating board in project, etc.

The screenshot is just as above.

Kanboard 1.0.34
Ubuntu 14.04
PHP 5.5.9-1ubuntu4.20
Database PostgreSQL 9.2 and sqlite
Browser tested: Chrome, Firefox, Safari

**Comment by rwimpers** [comment]
This issue still appears in version 1.0.35.

**Comment by fguillot** [comment]
Well, I'm not really able to reproduce this issue. I tried with Chrome, Safari, Firefox, IE11 and Edge.

Do you have anything specific installed on your server that could prevent that to work properly? Do you have any security modules enabled? Do you use something like Cloudflare that could manipulate the Javascript code on the fly? Can you see any error message in the browser console? What about the network connections, is there anything blocked?

**Comment by pingadi** [comment]
Update: 
With using SQLite database is doing just fine.
But when using PostgreSQL database the problem is always coming while saving data from pop-up.
I'm attaching the console log from Chrome.

While opening page after clearing console log:
![screen shot 2016-12-07 at 10 14 08 am](https://cloud.githubusercontent.com/assets/2283672/20953431/2f13c088-bc66-11e6-970a-efa8b76532e6.png)

While opening network log:
![screen shot 2016-12-07 at 10 14 25 am](https://cloud.githubusercontent.com/assets/2283672/20953444/49b33ed2-bc66-11e6-975b-ba9c22c3b7eb.png)

Response after saving task:
![screen shot 2016-12-07 at 10 15 32 am](https://cloud.githubusercontent.com/assets/2283672/20953451/5f552994-bc66-11e6-9f75-b7ffaff76af2.png)

**Comment by fguillot** [comment]
Do you have pagespeed module enabled somewhere?

The Javascript and CSS files are altered by PageSpeed according to your screenshot.

https://developers.google.com/speed/pagespeed/module/

**Comment by pingadi** [comment]
Yes maybe I will check with the pagespeed..
But how come that there is no problem while using SQLite database?

**Comment by pingadi** [comment]
For PostgreSQL when disabling mod_pagespeed using ModPagespeed off from /etc/apache2/mods-available/pagespeed.conf do the trick.

Still confused why the SQLite still working with pagespeed though.

**Comment by rwimpers** [comment]
I am using SQLite. And I use the default server setting of my provider. I don't know if there are any security modules set up.

I updated to the lastest version by renaming the folder on my web-server, creating a new folder with the latest version, and copying the "data" folder from the renamed folder to the new one.
After that, I had to make a change to the ".htaccess" file in the root folder in order to prevent an internal server error.

I attached the .htaccess file (I renamed it here - on my web server the file is named ".htaccess")
[htaccess.txt](https://github.com/kanboard/kanboard/files/639291/htaccess.txt)

**Comment by rwimpers** [comment]
This issue still appears in version 1.0.36.

**Comment by fguillot** [comment]
@rwimpers Are you sure that you don't have the same problem as @pingadi? Do you have mod_pagespeed enabled?

**Comment by rwimpers** [comment]
@fguillot 
How do I check, if "mod_pagespeed" is enabled? I have a webspace at "domainfactory" and I have no access to the apache configuration.

In the forum of domainfactory, there is a thread where technicans of domainfactory say, that there are more problems than advantages with this mod. So as I understand, they don't have enabled this mod on the servers of their clients.

Nevertheless, after searching a bit, I found a hint, that "mod_pagespeed" can be disabled by inserting the following lines into the ".htaccess" file:

<IfModule pagespeed_module>
    ModPagespeed off
</IfModule>

I did that (in the .htaccess file in the kanboard root folder), but there is no change.

**Comment by pingadi** [comment]
@rwimpers just using ModPagespeed off is not enough. You must clear the cache data at /var/cache/mod_pagespeed. But actually this also not work for me until I disable mod_pagespeed from Apache using _sudo a2dismod pagespeed_.

Hope this will help.

**Comment by rwimpers** [comment]
This issue seems to be solved in version 1.0.37 :-)
Great work - thank you :-)
