### ISSUE TITLE
Feature request: edit field with completion to search for user to reassign task

### ISSUE THREAD

**Issue by fourier** [kanboard/kanboard#2758]
### Expected behaviour

When there are a lot of users in database, it would be easier to start typing the name in some edit field when reassigning the task with some completion popping up (or narrowing search).
### Actual behaviour

Right now the dropdown list is used in when reassigning the task, which is difficult when there are a lot of users.
### Steps to reproduce
1. Create the task
2. Edit task -> Assign to
   3.
### Configuration
- Kanboard version: 1.0.31
- Database type and version: sqlite
- PHP version:
- OS: Debian Linux 8.0
- Browser: various

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
