### ISSUE TITLE
Feature request: Move task between swimlanes in "Edit Task" dialog

### ISSUE THREAD

**Issue by fourier** [kanboard/kanboard#2759]
### Expected behaviour

Need to move task not only between columns but also between swimlanes in Edit task.
### Actual behaviour

It is possible to move task between columns but not between swimlanes when editing the task
### Steps to reproduce
1. Create the task
2. Edit task
3. <= Here we shall be able to select the swimlane for the task without necessity to go to the Board and manually drag the task.
### Configuration
- Kanboard version: 1.0.31
- Database type and version: sqlite
- PHP version:
- OS: Debian Linux 8.0
- Browser: various

**Comment by elsajan** [comment]
I have similar problem, when im trying to post by json-rpc method "moveTaskPosition" parameter swimlane_id it always get default value, can't pass my value

**Comment by fguillot** [comment]
Duplicate with #1705
