### ISSUE TITLE
Project Boards causing HTTP ERROR 500 

### ISSUE THREAD

**Issue by Danis42** [kanboard/kanboard#2760]
### Expected behaviour

Downloaded the zip and installed everything like the documentation says.
Edited the Config to get MySql working and done. 

Everything works all functions and options. 
I can make Projects and users and change settings.
If I want to access a Project that i created i get an ERROR 500.

The Controllers that urls that are inaccessible are:
kanboard/?controller=BoardViewController&action=show&project_id=1
kanboard/?controller=TaskGanttController&action=show&project_id=1
kanboard/?controller=ProjectOverviewController&action=show&project_id=1&search=status%3Aopen
kanboard/?controller=CalendarController&action=show&project_id=1&search=status%3Aopen
kanboard/?controller=TaskListController&action=show&project_id=1&search=status%3Aopen

the only link that works is:

kanboard/?controller=ProjectViewController&action=show&project_id=1

anything in the Project View i can change and edit.
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.34
PHP version: 7.0.8-0ubuntu0.16.04.3
PHP SAPI: apache2handler
OS version: Linux 4.4.0-42-generic
Database driver: mysql
Database version: 5.7.15-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

I changed the log file to syslog and this is the output:

```
Oct 16 22:09:19 <user> kanboard[6136]: Kanboard\Core\Controller\Runner::executeMiddleware
Oct 16 22:09:19 <user> kanboard[6136]: Subscriber executed: Kanboard\Subscriber\BootstrapSubscriber::execute
Oct 16 22:09:19 <user> kanboard[6136]: Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\AuthenticationMiddleware
Oct 16 22:09:19 <user> kanboard[6136]: Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\PostAuthenticationMiddleware
Oct 16 22:09:19 <user> kanboard[6136]: Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\ApplicationAuthorizationMiddleware
Oct 16 22:09:19 <user> kanboard[6136]: Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\ProjectAuthorizationMiddleware
Oct 16 22:09:19 <user> kanboard[6136]: Kanboard\Core\Controller\Runner::executeController => \Kanboard\Controller\BoardViewController::show
```

All files are owned by my Web-user and have the efficient efficient privileges (-rwx-rw-r--)

**Comment by fguillot** [comment]
What can you see in the Apache error logs?

**Comment by Danis42** [comment]
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 65536 bytes) in /var/www/html/kanboard/vendor/composer/ClassLoader.php on line 412

My php.ini has a memory_limit of 128M ..

**Comment by Danis42** [comment]
Sorry my bad,
Fixed it by changing the php.ini 
Php ignores 128MB when its not written like 128M
