### ISSUE TITLE
Activity stream not logging between 2 swimlines

### ISSUE THREAD

**Issue by switek** [kanboard/kanboard#2761]
### Expected behaviour

When dragging and dropping a Task from Swimline A having status open to another swimline B and changing in the same time the column status (for instance closed) the Activity stream task page must log the change of the swimline and the status too.
### Actual behaviour

Only swimline action is logged in Activity stream task page.
### Configuration
- Kanboard version: 1.0.25
- Database type and version:  sqlite
- OS: win 7
- Browser: Firefox 47.0.1

**Comment by fguillot** [comment]
You should upgrade to the last version of Kanboard.
