### ISSUE TITLE
Missing description/title when hovering mouse cursor over subtask change status icons

### ISSUE THREAD

**Issue by Imbasaur** [kanboard/kanboard#2762]
### Expected behaviour

When hovering mouse cursor over subtask icon, description/title should appear to recognize what will happen after changing status.
### Actual behaviour

Description/title isnt displaying because `$title` parameter is defaul (null) in `SubtaskHelper->toggleStatus`
`return $this->helper->url->link($this->getTitle($subtask), 'SubtaskStatusController', 'change', $params, false, $class);`

This need to be to be extended to add detailed title for each icon.

**Comment by fguillot** [comment]
There is now a title in the development branch.
