### ISSUE TITLE
create automatic action, "Internal Error: Automatic Action Not Found" occurred

### ISSUE THREAD

**Issue by foodboox** [kanboard/kanboard#2763]
### Expected behaviour

I can create automatic action for project
### Actual behaviour

after I select a action and click "next", I got a "Internal Error: Automatic Action Not Found......" alert
### Configuration

Kanboard: 1.0.32
PHP version: 5.3.3
PHP SAPI: apache2handler
OS version: Linux 2.6.32-642.1.1.el6.x86_64
Database driver： sqlite
Database version: 3.6.20
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36

**Comment by foodboox** [comment]
I see the error came from below method in ActionManager.php, seems array actions not set.
 /**
     * Get automatic action instance
     *
     * @access public
     * @param  string  $name  Absolute class name with namespace
     * @return ActionBase
     */
    public function getAction($name)
    {
        if (isset($this->actions[$name])) {
            return $this->actions[$name];
        }

        throw new RuntimeException('Automatic Action Not Found: '.$name);
    }

**Comment by fguillot** [comment]
I cannot reproduce your issue, are you sure that all files are files are there? Which automatic action did you try to add?

**Comment by foodboox** [comment]
Yes, all task php files locate at /var/www/html/kanboard/app/Action directory. No matter what  available action selected, I see the same error message when I click next button: "Internal Error: Automatic Action Not Found: \\Kanboard\\Action\\<task file name>"

**Comment by sthesing** [comment]
Same here for all automatic actions. The files in the kanboard/app/Action directory are present.

    Application version: 1.0.34
    PHP version: 5.3.28-nmm7
    PHP SAPI: fpm-fcgi
    OS version: Linux 3.2.0-115-generic
    Database driver: sqlite
    Database version: 3.7.9

**Comment by sthesing** [comment]
Oops, sorry, my mistake. I just saw that Kanboard actually requires PHP >= 5.3.9
I'm running it on 5.6 now and automatic actions work as expected. 

That should solve it for @foodboox, too, who is on 5.3.3.
