### ISSUE TITLE
English corrections

### ISSUE THREAD

**Issue by pfabri** [kanboard/kanboard#2765]
Dear Frédéric,
I don't mean to be a smarty at all, but your excellent software contains a few English errors. I would be happy to point these out to you and suggest corrections as and when I stumble upon them. Please let me know if this is of any interest to you.

Other than that, thank you for this great tool, which I'm test-driving at the moment, but it is likely that we'll end up using it with my small team of 3, in which case we'll make sure to support you with some donations.

**Comment by mlbarrow** [comment]
Just submit the PRs in Github! This is open source; contributions from
everyone are welcome!

*michael at barrow dot me*
+1.541.600.2027

"Do not anticipate trouble, or
worry about what may never happen.
Keep in the sunlight." -- B. Franklin

**Comment by fguillot** [comment]
Since I'm not a native english speaker, the software contains English errors for sure.

Don't hesitate to report any errors or mistakes.

Thanks

**Comment by pfabri** [comment]
@mlbarrow Okay, thanks for the tip. Could you please tell me how to do that? I'm not sure what 'PR' stands for.
@fguillot No worries. Strictly speaking I'm not a 'native' either, but I've lived in the UK for 10 years and taught English in Paris for 2 years. Seeing some typically French mistakes brings back fond memories :) Again, thanks for the great open source and your efforts!

**Comment by fguillot** [comment]
PR stands for pull-request, you can find more information about it in the Github documentation. If you don't feel confortable to deal with technical stuff, you can list the mistakes in this ticket and I will fix it manually in the source code.
