### ISSUE TITLE
Mentioning notification does not work

### ISSUE THREAD

**Issue by Kolesar** [kanboard/kanboard#2767]
### Expected behaviour

When add mention in description of task when creating. User get mail, but if add mention in comments user does not get email
### Actual behavior

Get mail mention from comments
### Steps to reproduce
1. Create a new task and make a mention for any project member with @username
2. Add comment with similar mention (@username)
### Configuration

Application version: master
PHP version: 5.6.26
PHP SAPI: apache2handler
OS version: Linux 3.10.0-327.36.1.el7.x86_64
Database driver: mysql
Database version: 5.6.34
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

**Comment by Kolesar** [comment]
I have found where is the bug.

In file: UserMentionModel:50

Instead:
`$event['project_id'] = $this->taskFinderModel->getProjectId($event['task_id']);`

add:
`$event['project_id'] = $this->taskFinderModel->getProjectId($event['task']['id']);`

@fguillot please fix this issue. It is fastest and easiest than I make a request from my source.

**Comment by Kolesar** [comment]
Any news here?

**Comment by fguillot** [comment]
This is now fixed in the development branch.

Thank you.

**Comment by Kolesar** [comment]
Unfortunately mentioned does not work again.

Now, I get suggested menu on typing, but I do not get any email and I cannot click on user in comments :/

**Comment by Kolesar** [comment]
I have found again where is the problem about showing link on mentioned user in comments or description.

In ``Markdown`` class is regular expression do not see usernames with dot (.), but all my users are with dot like firstname.lastname.
```
if (! $this->isPublicLink && preg_match('/^@([^\s,!.:?]+)/', $Excerpt['text'], $matches)) {
```

And I cannot find where is the problem about sending email, probably is the same problem with regular expression, because if i testing with user without dot in username everything works fine.

Can you see this please?

**Comment by fguillot** [comment]
Indeed, I will try to fix that in the next couple of days.

**Comment by fguillot** [comment]
It should work now.

**Comment by jesushgonzalez** [comment]
Please, could say me if problem was solved? What should I do?

**Comment by Kolesar** [comment]
As I know it is fixed and works for me.

**Comment by jesushgonzalez** [comment]
I have the version 1.0.35

Can I make these changes? because I don´t see UserMentionModel file.

Or have I  migrate to last version 1.0.42 ?

**Comment by Kolesar** [comment]
I do not understand why you do not want to update to latest version where is fixed :/
