### ISSUE TITLE
composer.json - Update (minor) versions?

### ISSUE THREAD

**Issue by acs-ferreira** [kanboard/kanboard#2768]
@fguillot not an issue but a simple question : is there a reason to not load **minor** version updates?

Like (ex.) `"fguillot/picofeed": "0.1.*"` in place of `"fguillot/picofeed": "0.1.24"` ?

I've made a test updating all packages to their minor version, everything runs smoothly.

Thanks.

**Comment by fguillot** [comment]
There are not breaking changes between minor versions of these libs, using `*` will install the latest version.

**Comment by acs-ferreira** [comment]
Ok but is there a reason to not use `*` on the master branch ?

**Comment by fguillot** [comment]
I'm updating the dependencies only when it's necessary. It simplify the tests of KB even if no breaking changes should happens.
