### ISSUE TITLE
Caps lock when accessing kanboard with iPad

### ISSUE THREAD

**Issue by spst** [kanboard/kanboard#2772]
I am using my iPad at times to access kanboard: 
In some dialogues, "shift" acts like caps lock instead, i.e. all letters are entered upper case, until I once more hit shift. This happens with
- Add comment to task
- Entering a description for a task

Konfiguration
 Version:  1.0.34
 PHP Version:  5.6.26
 PHP SAPI:  cgi-fcgi
 OS Version:  SunOS localhost 5.10 Generic_142901-13 i86pc SunOS localhost 5.10 Generic_142901-13 i86pc
 Datenbanktreiber:  mysql
 Datenbank Version:  5.5.52-log
 Browser:  Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1

**Comment by fguillot** [comment]
This should not happen anymore with a recent version of Kanboard.
