### ISSUE TITLE
Tasks created via email do not belong to anyone

### ISSUE THREAD

**Issue by TheCloud** [kanboard/kanboard#2773]
### Expected behaviour

If I create a task, it should be assigned to me unless changed.
This is not a software bug, but an improvement on the kanban philosophy because no tasks should be left unassigned.
### Actual behaviour

Only creator is set
### Suggest update

On line 68 Change:
            'creator_id' => $user['id'],
To:
            'creator_id' => $user['id'],
            'owner_id' => $user['id'],
in /plugins/Mailgun/EmailHandler.php

**Comment by fguillot** [comment]
Merged here: https://github.com/kanboard/plugin-mailgun/commit/7717a043a18894fd279da6e50041a1fa6238c1f4
