### ISSUE TITLE
updated german translation

### ISSUE THREAD

**Issue by spst** [kanboard/kanboard#2774]
I just took the liberty to update the german translation.

However, submitting a pull request seems to be beyond me. I ended up having created a fork, and seemingly a pull request inside that fork, or some such. But there is no pull request in the master branch. Sorry for that - I am no developer, obviously :( 

So in case that's of any use to anyone, I attach the file:

[translations.php_de-DE.zip](https://github.com/kanboard/kanboard/files/544675/translations.php_de-DE.zip)

**Comment by fguillot** [comment]
Thank you very much for your contribution. The translations have been integrated manually into the master branch: https://github.com/kanboard/kanboard/blob/master/app/Locale/de_DE/translations.php

**Comment by spst** [comment]
Hi Frédéric,

thanks for the reply and for taking the pain to integrate my efforts into your amazing project!

there seems to be one last line missing:
`'You are not allowed to move this task.' => 'Sie haben nicht die Berechtigung, diese Aufgabe zu verschieben'`

Best regards / cordialement
Stefan

**Comment by fguillot** [comment]
This is up to date. Thanks.
