### ISSUE TITLE
Add document directly from the board

### ISSUE THREAD

**Issue by pfabri** [kanboard/kanboard#2775]
### This is a feature request

It would be handy, if one could add a document to a task directly from the board, by clicking on the small arrow that brings up the task's contextual menu.

Currently, as far as I could tell, one has to click on the task first to be directed to its details page, and add a document from there.

It would also be nice if one could just supply a URL for the file to be added as opposed to uploading from the local machine.

Many-many thanks in advance!

**Comment by fguillot** [comment]
This is now possible in version 1.0.39
