### ISSUE TITLE
projects management or project list - internal error: sql error

### ISSUE THREAD

**Issue by dragontune** [kanboard/kanboard#2777]
### Expected behaviour

When clicking the 'project list' or from the admin menu: Projects management

I should think you get to that page. But i receive this error:

```
Users overview
Projects Gantt chart
```

Internal Error: SQL error
Id  Status  ▲ Project     Start date  End date    Owner   Users   Columns

If i then click on users overview or projects, everything works - but when i again click on 'project list' i get the same error again. 
### Actual behaviour

```
Users overview
Projects Gantt chart
```

Internal Error: SQL error
Id  Status  ▲ Project     Start date  End date    Owner   Users   Columns
### Steps to reproduce
1. Admin menu (right upper corner) => project management (=> error!)
2. On the projects page, when clicking on the link 'project list' when its available (=> error)
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

```
Application version: 1.0.34
PHP version: 5.5.36
PHP SAPI: fpm-fcgi
OS version: Linux 3.4.6
Database driver: sqlite
Database version: 3.4.1
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
```

**Comment by fguillot** [comment]
Can you provide the exact SQL error message? (this is visible in the debug logs when activated)

**Comment by dragontune** [comment]
The exact error:

Internal Error: SQL error: SQLSTATE[HY000]: General error: 1 ambiguous column name: name.

The same happens with collumn 'id', 'status' and 'project'.







If i pres the column (sort by start_date or end_date) the list shows up normally. 



When i want to add a new project. There is also an add error. Seems a problem with inserting or reading of table?


If i type test and click add, next message: 



In the debug log is only text, no sql messages




Raf Aendekerk

**Comment by dragontune** [comment]
If i test in the latest nightly build. This problem also exists (managing projects):
- no view of projects if you choose "manage projects", unless you sort them on start or enddate. 

The add a new project does work again in the latest nightly build , even after deleting other projects. 

Raf Aendekerk

**Comment by dragontune** [comment]
To fast: The add a new project does work again in the latest nightly build , even after deleting other projects. 

=> only works if you don't delete all testprojects untill you have none left, after all projects are deleted,  i cant create a new one anymore. (Nightly build)


Raf Aendekerk

**Comment by fguillot** [comment]
Do you still have the problem with the latest version of Kanboard (1.0.37)?

**Comment by dragontune** [comment]
Still exists. If i make only one testproject, then delete that same project, i cannot make another project anymore.

Just tested in 1.0.37 version.

Raf Aendekerk

**Comment by fguillot** [comment]
Unfortunately, we are unable to reproduce the original issue after all this time. You should try with the latest version of Kanboard and reopen this ticket if necessary.

Thank you
