### ISSUE TITLE
Time spent is doubled when converting a subtask to a task on its own 

### ISSUE THREAD

**Issue by aweisshh** [kanboard/kanboard#2785]
### Expected behaviour

When i convert a subtask to a task we should have a consistent amount of time_spent.
### Actual behaviour

When i convert a subtask to a task the new task receives the amount of time_spent from the
former subtask. But the original task still has the time_spent assigned resulting from its former subtask.
Before converting we have 1 Task and (inside) a subtask with time_spent like 0.08.
After converting we have 2 Task with each 0.08h assigned.

![bildschirmfoto vom 2016-10-25 21-42-50](https://cloud.githubusercontent.com/assets/18518128/19702466/1cedaeaa-9b00-11e6-879f-2acb3e71570f.png)
### Steps to reproduce
1. create a Task
2. create a subtask inside this Task
3. work on the Subtask it for some minutes
4. convert the subtask to an task by its own
5. both Tasks will have the 'time_spent' assigned (but we have worked only on 1 subtask)
### Configuration

```
Application version: 1.0.34
PHP version: 7.0.8-0ubuntu0.16.04.3
PHP SAPI: apache2handler
OS version: Linux 4.4.0-45-generic
Database driver: mysql
Database version: 5.7.16-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
```
### Suggestion how to fix:
- either remove the amount of time_spent from the originating Task/Subtask and
  'transport' it to the new task.
- a bit more complicated: allow time_log_entries for Tasks (i know it is much work)  

Thank you for your great Application.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
