### ISSUE TITLE
Custom roles and task assignee

### ISSUE THREAD

**Issue by WolfgangKluge** [kanboard/kanboard#2786]
### Expected behaviour

I want to define a custom role that acts like (inherits) from `Project Member`, so I can assign a task to a user that  is permitted by such a custom role.
### Actual behaviour

It seems that all custom roles inherit from `Project Viewer`. Thus I cannot assign a task to any custom role-user.
### Steps to reproduce
1. Create a custom role 
2. Permit a user or group to that custom role
3. Try to assign that user (or a user from that group) to a task

Do I miss something?
### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
- Kanboard version: 1.0.34
- Database type and version: MariaDB 5.5.52
- PHP version: 5.5.9
- OS: Ubuntu 14.04
- Browser: -

**Comment by Yazza182** [comment]
Likely the same behaviour for me if the custom role is assigned for a group in a project (users of the group are not shown in assign task view).
If the role is assigned for a single user the task could be assigned for that user.

**Comment by Alexandr93** [comment]
In  ProjectGroupRoleModel,  function: getAssignableUsers
 	
			this:    `->in(self::TABLE.'.role', array(Role::PROJECT_MANAGER, Role::PROJECT_MEMBER))`
            
			replace to
			
			`->neq(self::TABLE.'.role', Role::PROJECT_VIEWER)`

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
