### ISSUE TITLE
Problem in Automatic actions

### ISSUE THREAD

**Issue by piotrekt** [kanboard/kanboard#2787]
Hi,
when I want to add Automatic actions I received a message:
`Internal Error: Automatic Action Not Found: \\Kanboard\\Action\\CommentCreationMoveTaskColumn`

What do I need to change in a settings to not appeared `\\` ?

**Comment by foodboox** [comment]
same problem for me but no fix method till now...https://github.com/kanboard/kanboard/issues/2763

**Comment by fguillot** [comment]
Can you give more details about your environment (OS, PHP version, Browser, Kanboard version, etc.) ? Are you using PHP 5.3 with magic_quotes_gpc on?
