### ISSUE TITLE
Feature Request: Create a task with tags via API

### ISSUE THREAD

**Issue by PawnStar** [kanboard/kanboard#2789]
It would be really nice if the `createTask` procedure in the API had the option to create a task with tags.

The documentation doesn't mention whether this is possible or not, but if it were I would really appreciate it.

**Comment by odebeir** [comment]
+1 
@fguillot Great job btw ! thanks for the kanboard project !

**Comment by tonylea** [comment]
Another +1 for this feature

**Comment by GuidoM12** [comment]
+1 for this. Any timeline for it?

**Comment by fguillot** [comment]
This feature have been implemented in the development branch.
