### ISSUE TITLE
Updates to task lists

### ISSUE THREAD

**Issue by jeffka11** [kanboard/kanboard#2790]
This is a feature request. In views that give lists of tasks in table format, such as the templates search/results.php, dashboard/tasks.php, and others, can

1. The columns be the same? I understand that when inside a project and you view the tasks as a list instead of a board, the project name is redundant, but I'd rather consistency across the app than an extra column. I'm especially concerned with keeping the project, swimlane, column, and category available.
2. Add tags. I get sorting would be hard to define and implement so that isn't a request in this issue. A comma separated list of tags would be OK. Ellipses if the list of tags gets too long or just let it scroll horizontally.

I did make these changes minus the tags to my local instance although this is the first time I've used Github and my first attempt at modifying PHP, so I'm not sure you'd want me making pull requests (and I don't know how the test cases work, how to execute, etc..). To make it work, I only had to adjust the templates listed in the first paragraph and the appropriate models (ie: TaskFinderModel.php). I have no idea how to go about adding tags.

**Comment by fguillot** [comment]
Task list is the now the same everywhere and with tags.
