### ISSUE TITLE
Calendar across ALL projects or My calendar + search bar

### ISSUE THREAD

**Issue by pfabri** [kanboard/kanboard#2792]
### This is a feature request
**Current behaviour:**
 'My Calendar' only displays those tasks that are **assigned** to the logged in user.

**Feature Request**
I think it would be really useful if 'My Calendar' could display tasks across all projects for those tasks that the user has permission to view. If there was a search bar provided, one could just search for `status:open` for example.

**Alternative idea**
Calendars inside projects already have a search bar, but they can only search for tasks within the project. It would be really nice if a syntax along these lines existed: `status:open project:*`, which would search for all open tasks across all projects. 

I do think, however, that the most intuitive location for a 'global search' function would be inside 'My Calendar'.

Many-many thanks in advance!

**Comment by fguillot** [comment]
Tickets related to the calendar should be posted to the calendar plugin bug tracker: https://github.com/kanboard/plugin-calendar/issues

Thank you
