### ISSUE TITLE
Attaching DOCX documents crashes web host

### ISSUE THREAD

**Issue by tstafford** [kanboard/kanboard#2795]
When attaching a .docx document to a task, my web host appears to crash and the file is not attached to the task.  I am able to attach other file formats without issue.

### Expected behaviour

Site keeps running, document is attached to task.

### Actual behaviour

Site responds with error 500, then returns after a delay and the document is not attached to the task.

### Steps to reproduce

1. Open a task
2. Click "attach document"
3. Select a .docx file
4. Click upload
5. Click "view uploaded files"

### Configuration

Application version: 1.0.33
PHP version: 5.4.19
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-604.30.3.lve1.3.63.el6.nfsfixes.x86_64
Database driver: mysql
Database version: 5.5.43-37.2-log
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by fguillot** [comment]
Are you sure that the problem is coming from Kanboard and not your web server configuration? Did you watch the error log files of your web server?

**Comment by tstafford** [comment]
I tested this on a different server and did not experience the same problem.  So it appears to be a web server issue, but I don't know what configuration could be causing the problem.  I have attached a snipped from the error log on the affected server.

[log.txt](https://github.com/kanboard/kanboard/files/570234/log.txt)

**Comment by fguillot** [comment]
That seems to be related to your Apache configuration ("client denied by server configuration"). Not by Kanboard itself. Did you try with the latest version of Kanboard?

**Comment by tstafford** [comment]
That is correct, problem was with the web server running mod_security and blocking the transfer of certain file types.
