### ISSUE TITLE
jpegPhoto not working

### ISSUE THREAD

**Issue by rverchere** [kanboard/kanboard#2796]
### Expected behaviour

I've set up the jpegPhoto parameter to use avatar photo from our LDAP server.
At login time, the jpegPhoto is retrieved from the LDAP server and stored in the kanboard.
Then, we could see the LDAP avatar.

### Actual behaviour

The jpegPhoto is well updated, but cannot be displayed.
It was working with previous version (I guess v1.0.27).

Note that it fails only with new generated photos. I can see difference on photo files format:
- works -> JPEG image data, EXIF standard
- fails -> JPEG image data, JFIF standard 1.01

### Steps to reproduce

1. Configure jpegPhoto to retrieve LDAP photos
2. Connect with a remote user
3. Check avatar

### Configuration

- Kanboard version: v1.0.34
- Database type and version:  mysql 5.5.52-0+deb7u1
- PHP version: 5.4.45-0+deb7u5
- OS: Debian 7 (wheezy) -  Linux 3.2.0-4-amd64
- Browser:  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by mauricio-sonegatti** [comment]
I have this problem for a while now...
https://github.com/kanboard/kanboard/issues/2732

**Comment by peter58228** [comment]
There is no resolution define in JFIF format JEPG file.

**Comment by fguillot** [comment]
What kind of tool do you use to add a photo using JFIF standard in your LDAP server?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
