### ISSUE TITLE
email address refused when creating a new user with a space at the end

### ISSUE THREAD

**Issue by wixiw** [kanboard/kanboard#2800]
### Expected behaviour

kanboard should strip the space and accept the mail

### Actual behaviour

kanboard refuse the mail address considering its an illegal address. It's was very difficult to understand why the address was refused.

### Steps to reproduce

create a new user with a space at the end of the email address.

### Configuration

    Application version: 1.0.34
    PHP version: 5.6.27-0+deb8u1
    PHP SAPI: apache2handler
    OS version: Linux 3.16.0-4-amd64
    Database driver: sqlite
    Database version: 3.8.7.1
    Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by markjszy** [comment]
I was not able to reproduce this in latest development (master) branch

**Comment by fguillot** [comment]
Do you have this issue with the latest version of Kanboard? (1.0.39)

**Comment by wixiw** [comment]
Hi, sorry for the delay, the upgrade was difficult to plan?

I still have the issue. Note that after being refused once I pressed the save button, the address is corrected on the print-screen (the trailling space is stripped), and I can add the user without changing the address (just clicking on save)


Configuration

    Application version: 1.0.39
    PHP version: 5.6.27-0+deb8u1
    PHP SAPI: apache2handler
    OS version: Linux 3.16.0-4-amd64
    Database driver: sqlite
    Database version: 3.8.7.1
    Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

![capture](https://cloud.githubusercontent.com/assets/839873/22901097/e204d9a2-f230-11e6-9624-bab0cc9cc5b1.PNG)

**Comment by fguillot** [comment]
I have never been able to reproduce this issue after all this time. You seems to be the only one to have this problem. Unfortunately, you will have to investigate by yourself and potentially submit a patch.
