### ISSUE TITLE
display php errors in browser with docker

### ISSUE THREAD

**Issue by wmike** [kanboard/kanboard#2802]
Hey guys,

is there a way to set up the docker container for showing all php errors in browser?

Best,
mike

**Comment by fguillot** [comment]
You have to change the php config file. You can do that by creating a new Docker image that inherits from the official one.

**Comment by wmike** [comment]
Thanks, mate.

I modified the php.ini ([src](http://php.net/manual/de/errorfunc.configuration.php#ini.error-reporting)):
- display_errors = on
- error_reporting = E_ALL (for example)

Afterwards I commited the modified container ([src](https://docs.docker.com/engine/reference/commandline/commit/)):
`docker commit container_id my_repo/kanboard`
