### ISSUE TITLE
[Feature Request] mysql connection via Unix socket. 

### ISSUE THREAD

**Issue by sven76** [kanboard/kanboard#2803]
Hi, would be nice to add mysql connection support via Unix socket. I didn't find it in the documentation, in case it exists already.

**Comment by mylcon** [comment]
Hi Sven, Kanboard uses PDO. So you can use the following statement:
define('DB_HOSTNAME', '127.0.0.1;unix_socket=/var/run/mysqld/mysqld.sock');

To find MySQL socket, try:
netstat -ln | awk '/mysql(.*)?\.sock/ { print $9 }'

**Comment by sven76** [comment]
Thanks a lot, worked perfectly.

**Comment by fguillot** [comment]
This is now included in the documentation. Thanks.
