### ISSUE TITLE
Drag and Drop between boards (or bulk move)

### ISSUE THREAD

**Issue by jaiume** [kanboard/kanboard#2804]
It would be great if you could drag and drop a task between two boards if you had them open in separate windows. This would be a great (and fast) way to move tasks between projects.

**Comment by jaiume** [comment]
Bump....please?

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
