### ISSUE TITLE
Allow TAB key to move focus away from Description field when editing tasks

### ISSUE THREAD

**Issue by snth** [kanboard/kanboard#2805]
### Expected behaviour

In any input form I expect to be able to move from input field to input field by pressing the TAB key.

### Actual behaviour

When editing the description of a task, the TAB key adds spaces in the description field rather than moving the focus away from the field. I tried ALT+TAB and CTRL+TAB combinations but ALT+TAB switches the active application on Ubuntu and CTRL+TAB switches the Browser Tab in the Chrome browser.

### Steps to reproduce

1. Create a new task
2. Edit the task description
3. Press the TAB key

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: v1.0.34
- OS: Ubuntu 14.04 host
- Browser: Google Chrome

Application version: master
PHP version: 7.0.9
PHP SAPI: fpm-fcgi
OS version: Linux 4.4.0-45-generic
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by fguillot** [comment]
This is now working in version 1.0.37. Other improvements are coming to improve the usability. Some ui components have to be rewritten to be able to do everything with the keyboard.

Thank you

**Comment by snth** [comment]
Thanks for the fix. I looked around the code a bit but wasn't able to figure out how to do it myself.
