### ISSUE TITLE
Overdue Notification not being translated to the user language

### ISSUE THREAD

**Issue by glaubersp** [kanboard/kanboard#2807]
### Expected behaviour

The overdue notification email should be sent in the same language that is set in the user preferences or the system preferences.

### Actual behaviour

The email is being sent only in English.

### Steps to reproduce

1. Change the language in the System Preferences or the User Profile.
2. Set a task to be overdue.
3. Set cronjob to send the overdue email.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.34
- Database type and version: Mysql 5.7.15-2
- PHP version: Php 7.0.10
- OS: Centos 6.8
- Browser: not applicable

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
