### ISSUE TITLE
Screenshots popups haven't a close button

### ISSUE THREAD

**Issue by giuntim** [kanboard/kanboard#2809]
### Expected behaviour

There should be a way to close screenshots modals.

### Actual behaviour

There is no close button and from the latest version screenshots' modals do non disapper clicking on the background. 

### Steps to reproduce

1. Add a screenshot to a task
2. Go in task detail
3. Click on the screenshot

### Workaround

refresh page

**Comment by loonies** [comment]
"Workaround" is pressing `Esc` key

**Comment by fguillot** [comment]
In the development branch, a close button have been added to all inline popups in addition to the keyboard shortcut.

**Comment by fguillot** [comment]
This is available in v1.0.35 now.
