### ISSUE TITLE
[UI] Clarify difference between username and name in profile page

### ISSUE THREAD

**Issue by Biniou180** [kanboard/kanboard#2812]
I open this ticket as a contributor of Framasoft projects, and particularly Framaboard which is based on Kanboard.

### Actual behaviour

When going to "My profile" page, the user can see his username and name.
However, for most of our non-technical users, it is not very clear which one is used for what. (some of them thought it was first name and family name, etc).

### Expected behaviour

Is it possible to add some explanation next to the label of the field? It would reduce confusion for a lot of users.
For example add to the label: 

  * Username (will be used for login)
  * Name (will be displayed in the interface and on tasks)

### Steps to reproduce

1. Go to "My profile" page when logged in.

### Configuration
- Kanboard version: 1.0.34

Thanks :-)

**Comment by fguillot** [comment]
Instead of adding an explanation, the label of the fields could be renamed:

- Username -> Login
- Name -> Full Name
