### ISSUE TITLE
[UI] Enhance task creation page for more readability

### ISSUE THREAD

**Issue by Biniou180** [kanboard/kanboard#2813]
I open this ticket as a contributor of Framasoft projects, and particularly Framaboard which is based on Kanboard.

### Actual behaviour
Today, the task creation/edition page looks like this:
![Task creation screenshot](https://framapic.org/LbXWllB4OZua/8jAVzCcuAMT1)

It is fine, but we have received some suggestions from our users in order to enhance it, and as we discuss with them and found there were relevant, I submit them to the kanboard github :-)

### Expected behaviour
Here is a suggestion from one of our users (sorry for french comments, do not have the english version):
![Mockup task edition](https://framapic.org/cUpsm1gIfQlU/IfMLN0p1W58x)

In the relevant UI enhancement we thought about:

  * In each of the free columns, have consistent width (example: "Tags" textbox with same width than description and title)
  * Reduce margin between labels and corresponding input fields (example: Time spent, which is today in equal distance between input above and under: which one is good? => it is instantly readable if Time spent is nearer from the input under). 
  * Otherwise/also, regroup relevant fields in a common frame
  * Allow user to set frequency directly in this page (instead of save, then go to detail and edit). The checkboxes on the screenshot above are an idea to avoid too many clicks with dropdown lists (maybe not the best as it takes a lot of room: maybe hide it if "set frequency" is not selected?).
  * Put the "save/cancel" buttons to the right (reading direction of the user: first column, second, third, and validation: so the save button should be at the far right for readability)
  * Why not add a new button "save and create a new subtask" to go directly to subtask edition (?) - it could save a few clicks when having to create complex tasks often.

A said before, these are only suggestions and are submitted to debate and discuss. Feel free to say if something is not right for you or if you think of a better way :-)

### Configuration

- Kanboard version: 1.0.34
- OS / Browser: (tested for me on Linux/Firefox, but should not be limited to this configuration)

Thanks again!

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
