### ISSUE TITLE
Tags lost due to moving a task to another project

### ISSUE THREAD

**Issue by asegu** [kanboard/kanboard#2817]
### Expected behaviour

When moving a task from project A to project B, I expect the task to be copied including tags.

### Actual behaviour

The task is moved, but any tags assigned are lost.

### Steps to reproduce

1. Create a project A with swimlanes and columns (new project, "Create from another project" = "Do not duplicate anything", ...)
2. Create a project B as a copy of project A (new project, "Create from another project" = "A")
3. Create a task T in project A, add a description, add a tag "Tag"
4. Go back to the board of project A : it can be observed that the task T has a tag "Tag"
5. Move the task T from project A to project B
6. View the board of project B (task is visible, no tags)
7. View the task T in project B (task has no subtags)

Tags can then be added to task T, but they are once again lost if the task T is moved back to project A.

Same behavior is observed if the task is moved automatically due to predefined actions (ex: add the action that closing the task from a Done column will move the task to another project).

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.33
- Database type and version: mysql
- PHP version: 7.0.8-0ubuntu0.16.04.3
- OS: Ubuntu 16.04 / Linux 4.4.0-43-generic
- Browser: Chrome

**Comment by asegu** [comment]
Took a stab at a fix in my own environment.

Mainly, the function syncTaskTagsToAnotherProject in TagDuplicationModel.php works as commented, but not as I was expecting based on the method name. I changed the code to synchronize as I understand the term (make sure the tags exist in the destination project and associate to the task).

I don't expect side-effects to other operations as the method syncTaskTagsToAnotherProject seems to only be called by moveToProject (in TaskProjectMoveModel.php)

At the same time, I modified duplicateTaskTagsToAnotherProject - as my reading of the code was such that tags would only be copied if they already existed in the destination project. I changed getIdByName to be findOrCreateTag.

To do would be:
- Review / test other than manually
- Consider if this should be configurable behavior (should tags be automatically added to the other project if not previously existing)
- Make the change in the actual repo.

Code for the changed methods changed are here:

```
    /**
     * Was: Remove tags that are not available in destination project
     * Now: Create tags (if needed) in the destination project to fit the source project
     *
     * @access public
     * @param  integer $task_id
     * @param  integer $dst_project_id
     */
    public function syncTaskTagsToAnotherProject($task_id, $dst_project_id)
    {
        /* $tag_ids = $this->taskTagModel->getTagIdsByTaskNotAvailableInProject($task_id, $dst_project_id);

        foreach ($tag_ids as $tag_id) {
            $this->taskTagModel->dissociateTag($task_id, $tag_id);
        } */

        $tags = $this->taskTagModel->getTagsByTask($task_id);

        foreach ($tags as $tag) {
            $new_proj_tag_id = $this->tagModel->findOrCreateTag($dst_project_id, $tag['name']);

            $this->taskTagModel->dissociateTag($task_id, $tag['id']);
            if ($tag['id']) {
                $this->taskTagModel->associateTag($task_id, $new_proj_tag_id);
            }
        }
    }
}
```


```
    /**
     * Link tags to the new tasks
     *
     * @access public
     * @param  integer $src_task_id
     * @param  integer $dst_task_id
     * @param  integer $dst_project_id
     */
    public function duplicateTaskTagsToAnotherProject($src_task_id, $dst_task_id, $dst_project_id)
    {
        $tags = $this->taskTagModel->getTagsByTask($src_task_id);

        foreach ($tags as $tag) {
            //$tag_id = $this->tagModel->getIdByName($dst_project_id, $tag['name']);
            $tag_id = $this->tagModel->findOrCreateTag($dst_project_id, $tag['name']);

            if ($tag_id) {
                $this->taskTagModel->associateTag($dst_task_id, $tag_id);
            }
        }
    }
```

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
