### ISSUE TITLE
Task Manager / Bug with CLI (windows)

### ISSUE THREAD

**Issue by alefaucheur** [kanboard/kanboard#2818]
### Expected behaviour

Try to run these CLI under a windows task manager
c:\xampp\php\php.exe -f C:\xampp\htdocs\kanboard\kanboard.php cronjob
c:\xampp\php\php.exe -f C:\xampp\htdocs\kanboard\kanboard.php notification:overdue-tasks
c:\xampp\php\php.exe -f C:\xampp\htdocs\kanboard\kanboard.php projects:daily-stats
c:\xampp\php\php.exe -f C:\xampp\htdocs\kanboard\kanboard.php trigger:tasks

### Actual behaviour
Get error message:
Automatic Action Not Found: \Kanboard\Plugin\XXXAction\SetEndDateWithoutRewriting

I don't know why it fails on my plugins which works just like a charm.

This command line , ex:
php kanboard trigger:tasks
works just fine at the root of kanboard folder, ex:

### Steps to reproduce

1. create the bat
2. run the command : cmd /C start c:\xampp\htdocs\kanboard.bat
3. see result

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

    Application version: 1.0.34
    PHP version: 5.6.15
    PHP SAPI: apache2handler
    OS version: Windows NT 6.1
    Database driver: mysql
    Database version: 10.1.9-MariaDB
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by fguillot** [comment]
This issue is related to your server environment, not Kanboard itself. The command line scripts should be executed from the kanboard directory.
