### ISSUE TITLE
Task delete could able to be banned from users or roles

### ISSUE THREAD

**Issue by erpnedir** [kanboard/kanboard#2822]
A user with a project member role must not see the delete task menu. At least this permission could be removed from the role.
A good place for this restriction is project custom roles, but there is no restriction for task delete.
Can this be added or Is there a way to achieve this?

**Comment by erpnedir** [comment]
After a few more tests, I understand that only the creator can delete tasks, which makes sense. So this is a nice to have feature.

**Comment by asmwarrior** [comment]
I see such code in the file `AuthenticationProvider.php`
`$acl->add('TaskSuppressionController', '*', Role::PROJECT_MEMBER);`
So, the project manager can also delete a task created by a member.

**Comment by fguillot** [comment]
Custom roles can now prevent task suppression.
