### ISSUE TITLE
Need to add column in ListView on Kanboard is it possible..?can you help on this

### ISSUE THREAD

**Issue by ramesh1024** [kanboard/kanboard#2825]
### Expected behaviour

We need Extra columns in the listview of kanborad ,Now we have 4 columns
id   swimlane  column  category  ..  status

### Actual behaviour

need to add other columns taskbypriority taskdesc

id   swimlane  column  category  ..  status   **taskbypriority**   **taskdesc**

Tell us what happens instead

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: master.a1e2b0f1b88ed445a9dd960d9431fdbcf983fb33
PHP version: 5.6.21
PHP SAPI: fpm-fcgi
OS version: Linux 4.7.3-coreos-r2
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

**Comment by ramesh1024** [comment]
PHP version: 5.6.21
OS version: Linux 4.7.3-coreos-r2
Database driver: sqlite
Database version: 3.13.0

**Comment by fguillot** [comment]
The list view has changed a lot since your posted this message.
