### ISSUE TITLE
New user notification

### ISSUE THREAD

**Issue by gerhard-tinned** [kanboard/kanboard#2827]
### Expected behaviour

When a new user is created with name and email address (without password), the user should receive an email notification with a randomly generated password. 

### Actual behaviour

User must be generated with password. 
User is not informed by email at all. 

### Steps to reproduce

1. Create new user with user name and email address 
2. No email notification is sent to the new user.

**Comment by fguillot** [comment]
The invitation feature have been added to the development version of Kanboard.
