### ISSUE TITLE
GITLAB WEBHOOK ISSUE COLOR NEED IN KANBOARD

### ISSUE THREAD

**Issue by ramesh1024** [kanboard/kanboard#2830]
### Subject of the issue
I had a webhook of gilab connected in Kanboard. 
My question is There is NO option for Choose Color  (red,blue ..)ISSUE create or closed or commented in GITLAB WEB HOOK. then,I need to SHOW some Different COLOR as Same as we are showing task in Kanboard.
How can I easily identify particular story or issue  difference in Kanboard while to connect from gitlab...?want see differentiate story and issue first column of the kanboard.

### Expected behavior
Need to show differentiated story and issue in kanboard first column with Color..There is no option for choose color for an issue .

### Actual behavior
Showing all values in the first same color.issue or story

we need to something in GITLAB WEBHOOK while a create issue OR need to something in kanboard..?

Any help appreciated!!

**Comment by fguillot** [comment]
Issues related to Gitlab should be posted here: https://github.com/kanboard/plugin-gitlab-webhook/issues
