### ISSUE TITLE
Different columns across swimlanes

### ISSUE THREAD

**Issue by Buzut** [kanboard/kanboard#2831]
So far, it's only possible to have the exact same colomns between swimlanes. It would be great to have different columns so that it's possible to manage different things. There are great exemples of [possible use in this article](https://leankit.com/learn/kanban/kanban-board-examples-for-development-and-operations/).

For instance:
<img width="512" alt="2-largedevelopmentteamkanbanboardexample-37d24ae7-1024x601" src="https://cloud.githubusercontent.com/assets/6450536/20481419/4d8d299a-afe7-11e6-9547-265172a777b5.png">

**Comment by dustinliddick** [comment]
Ironically enough, I missed this when I just requested the same thing. I think this would be great feature to have. Just wanted to throw my .02 in!!

Thank you to all for such a great product.

**Comment by rdezavalia** [comment]
This would be great
+1

**Comment by MDKAOD** [comment]
+1 Here as well. The ability to have different workflows for different aspects of a project is invaluable. For example, in manufacturing, there's one project with different phases that go from artwork through to physical production. For teams of all sizes, this would be very helpful.

**Comment by KenD-OP5** [comment]
+1 For this.

**Comment by leifgen** [comment]
+1
As long as this isn't possible, we cannot use swimlanes effectively. Furthermore, we have to separate one project into multiple - which leads to less overview.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
