### ISSUE TITLE
Multi colonne déplacement horizontal

### ISSUE THREAD

**Issue by SUPRVISOR** [kanboard/kanboard#2832]
### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

bonsoir,
Soucis lors de plusieurs tache dans une colonne défaut pour accéder a la barre de progression qui se trouve tout en bas très très bas .... pas pratique on as du mal a voir la dernière colonne !
Merci :)

![presse-papiers-1](https://cloud.githubusercontent.com/assets/23641503/20497026/e1649794-b027-11e6-9cff-24268f0c3a73.png)

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.34
- Database type and version: mysql
- PHP version: 5.7
- OS: debian 8
- Browser: all

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
