### ISSUE TITLE
Ajax not working in debug = true and LOG_DRIVER = file

### ISSUE THREAD

**Issue by pmcfernandes** [kanboard/kanboard#2834]
When I set DEBUG =  'true' and LOG_DRIVER = 'file' in config.php then I enter in TaskViewController action Show using normal browsing to see task

.http://myurl/?controller=TaskViewController&action=show&task_id=1843&project_id=29

On buton Close this Task window (for confirm) not appear. Saying this in Chrome console: vendor.min.js?1476114552:4 GET http://myurl/?controller=UserAjaxController&action=status&_=1479919440929 500 (Internal Server Error)

I founded same problem in almost Ajax requests. Note: not file permissions because I wrote debug line inside TaskViewController  show action and works.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: v1.0.34
- Database type and version: Mysql 5.5
- PHP version: 5.6 + (Samething in 7)
- OS: Windows 2012
- Browser: All browsers.

**Comment by rakesh1084** [comment]
even I get this

**Comment by fguillot** [comment]
Can you copy and paste your config file here?

**Comment by pmcfernandes** [comment]
My problem is already fixed. I get lastest version from master and works.
