### ISSUE TITLE
withBeforeMethod undefined

### ISSUE THREAD

**Issue by pmcfernandes** [kanboard/kanboard#2835]
Fatal error: Call to undefined method JsonRPC\ProcedureHandler::withBeforeMethod() in \app\ServiceProvider\ApiProvider.php on line 77

On Windows 2012, PHP7 with php_curl enabled

**Comment by fguillot** [comment]
Are you sure that vendor folder is up to date?

**Comment by pmcfernandes** [comment]
Can't confirm anymore. But normally I delete all files except Data folder and config file and copy everything again. To fix this issues I copied from master and all works correctly.,
