### ISSUE TITLE
incorrect task search result

### ISSUE THREAD

**Issue by foodboox** [kanboard/kanboard#2836]
### Expected behaviour

Tell us what should happen
I can search tasks by specified category.

### Actual behaviour

I create category in project and assign to tasks. Then I select category name for search criteria but I find nothing list in the search result...the search criteria like category:\\"缺陷\\"
Search works as expected if remove \\"\\", how can I set this for default value?

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
Kanboard version: 1.0.32
PHP version: 5.3.3
PHP SAPI: apache2handler
OS version: Linux 2.6.32-642.1.1.el6.x86_64
Database type: sqlite
Database version: 3.6.20
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
