### ISSUE TITLE
Complexity / Score should follow Fibonacci serie

### ISSUE THREAD

**Issue by TheCloud** [kanboard/kanboard#2841]
### Expected behaviour

When setting task Complexity (aka Score), it's suggested to use a subset of Fibonacci.
Our way of doing it is using T-Shirt sizes and FIbobacci
XS=> 1, S => 2, M =>3, L => 5, XL => 13, XXL => 21

### Actual behaviour

Numer to be set

### Proposed solution

1. Edit /board/app/Helper/TaskHelper.php
2. Go to line _public function selectScore_
3. Add options and values
`$rangeOptions=array("XS","S","M","L","XL","XXL"); // Name of options`
`$rangeValues=array(1,2,3,5,13,21); // Value of options`
`if (!isset($values['score'])) $values['score']="3"; // default value`
`$options=array_combine($rangeValues,$rangeOptions);`

4. Comment out this line
`        // $html .= $this->helper->form->number('score', $values, $errors, $attributes);
`
5. Add this line
`        $html .= $this->helper->form->select('score', $options, $values, array(), $attributes);
`

### Configuration

Versione dell'applicazione: 1.0.33

**Comment by fguillot** [comment]
Many people are not using this field to define story points or T-shirt size. I prefer to not enforce the value of this field.

**Comment by TheCloud** [comment]
I agree on the fact that many could use this in different ways using different labels.

We could write a use case like:
As a project administrator I would like to be able to configure a list of name/values for complexity/score.

:-)

**Comment by fguillot** [comment]
Feel free to create a plugin :)

**Comment by TheCloud** [comment]
I'd love to, but the last attempt I tried to create one for automatic action, it didn't worked out :-(

Anyway I will try to code one and see :-)
