### ISSUE TITLE
worker says "No queue driver defined!" and exits.

### ISSUE THREAD

**Issue by mo-han** [kanboard/kanboard#2842]
### Expected behaviour

run `kanboard worker` as nginx (my web server's running user) and work with `beanstalkd`

### Actual behaviour

```
kanboard worker


  [LogicException]
  No queue driver defined!


worker
```

### Steps to reproduce

1. Start `beanstalkd` service

```
● beanstalkd.service - Beanstalkd Fast Workqueue Service
   Loaded: loaded (/usr/lib/systemd/system/beanstalkd.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-11-28 09:35:01 CST; 10min ago
 Main PID: 22752 (beanstalkd)
   CGroup: /system.slice/beanstalkd.service
           └─22752 /usr/bin/beanstalkd -l 0.0.0.0 -p 11300 -u beanstalkd

Nov 28 09:35:01 server.dev.local systemd[1]: Started Beanstalkd Fast Workqueue Service.
Nov 28 09:35:01 server.dev.local systemd[1]: Starting Beanstalkd Fast Workqueue Service...
```

2. Install Beanstalk plugin as the docs told me.

```
Beanstalk	Frédéric Guillot	1.0.0	 Uninstall
Use Beanstalk to process background jobs
```

3. run `kanboard worker` as my web server's user.

```
kanboard worker


  [LogicException]
  No queue driver defined!


worker
```

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.34
- Database type and version: postgres (PostgreSQL) 9.2.15
- PHP version: PHP 5.4.16 (cli) (built: Aug 11 2016 21:24:59
- OS: CentOS Linux release 7.2.1511
- Browser: 54.0.2840.99 m

**Comment by fguillot** [comment]
Did you solve your issue since the time?

If you get this error that means the worker was not able to connect to the beanstalkd server. By default, the plugin assume the deamon listen on 127.0.0.1: https://github.com/kanboard/plugin-beanstalk/blob/master/Plugin.php#L14
