### ISSUE TITLE
Show PDF attachments in browser

### ISSUE THREAD

**Issue by phsc** [kanboard/kanboard#2843]
Currently, there are the following actions available on attachments:
- Download
- Remove

It would be great if there was an additional action "Show", to open PDF attachments directly in the browser.

**Comment by skorvek** [comment]
Second that!

**Comment by fguillot** [comment]
This is now implemented in the development branch. PDF attachments are opened in a new tab and rendered by the browser. Seems to work with Chrome, Safari and Firefox.

Thanks

**Comment by phsc** [comment]
Yes, can confirm that this works great with Kanboard 1.0.36 in Chrome.
