### ISSUE TITLE
Form elements can't get focus after "Add a screenshot" layer-box was opened

### ISSUE THREAD

**Issue by nepomuc** [kanboard/kanboard#2846]
### Expected behaviour

The user should be able to click on form elements in order to use them

### Actual behaviour

After opening the "Add a screenshot" lay-box, focussing form elements doesn't work any more.
You have to completely reload the entire page in order to be able to use form elements again.

### Steps to reproduce

1. Create a new task or go into an existing one
2. Click on "Add a screenshot" and close the layer-box again
3. Now if you click on the filter input for example, as soon as you click on it it loses it's focus instantly.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.34
PHP version: 7.0.13
PHP SAPI: cgi-fcgi
OS version: Linux 3.16.0-4-amd64
Database driver: sqlite
Database version: 3.14.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

![kanboard-add-a-screenshot-input-focus-error](https://cloud.githubusercontent.com/assets/864660/20709297/c0c0d7ba-b634-11e6-84c2-b536149a5d98.gif)

**Comment by fguillot** [comment]
This is now fixed in version 1.0.37.

Thank you
