### ISSUE TITLE
Image preview can't be closed

### ISSUE THREAD

**Issue by nepomuc** [kanboard/kanboard#2847]
### Expected behaviour

Images added to a task can be opened in a preview layer-box. This layer-box can be closed by clicking on a &times; char at the top right of the box or by clicking on  the dark background.

### Actual behaviour

There's neither a &times;-char to click on nor is there listener set up for clicks on the dark background.
On desktop you can at least close the layer-box by pressing ESC, but on mobile you have to reload the entire page to use kanboard again.

### Steps to reproduce

1. click on a image's thumbnail inside a task
2. try to close the layer-box by using you mouse

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.34
PHP version: 7.0.13
PHP SAPI: cgi-fcgi
OS version: Linux 3.16.0-4-amd64
Database driver: sqlite
Database version: 3.14.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

**Comment by fguillot** [comment]
Actually, closing the modal box by clicking on the background was the default behaviour of previous previous of Kanboard. But people complains about that, because they could close a modal box with a form by mistake.

So, this feature have been removed, people can still close the modal box by using the keyboard shortcut "Esc" or the cancel link.

However, a closing button was effectively missing, this is why this feature have been added into the current development branch.

**Comment by nepomuc** [comment]
@fguillot Thanks for the explanation. Well in my experience users who don't like a feature complain more than users who don't even realise that it's there. Users just using your UI intuitively is basically the best result you can wish for, but those users usually don't give you any feedback at all. In this case we know it's very common for layer-boxes, modals, gallery-zoom-thingies etc. that you can close them by clicking on the background. So maybe it's worth thinking about it again, or maybe find an even better solution by implementing a recurity feature for layer-boxes which do contain a <form>. Maybe by showing a alert which asks you if you really want to close the layer-box.

**Comment by fguillot** [comment]
Yes, having a confirmation before closing a modal box with a form would be the best approach.

**Comment by nepomuc** [comment]
@fguillot I built a solution for that but I can't commit it yet, because I don't know how you deal with translating text in JavaScript. Can you tell me how I can make the text of the confirm available for translation?

`$(document).on("click", "#popover-container", function(e) {
        if($(this).find('form,input,textarea,select,option').length > 0) {
            var r = confirm("Are you sure you want to close this layer-box?");
            if (r == true) {
                self.close(e);
            }
        }
        else {
            self.close(e);
        }
    });`

**Comment by fguillot** [comment]
The modal/dialog/confirmation boxes have been completely rewritten for version 1.0.37.

- Images are displayed with a "slideshow" and can be closed by clicking anywhere or Esc key.
- Confirmation dialogs can be closed by clicking on the background, or use Esc, or the close button.
- Modal boxes with a form can be closed with the close button or Esc key, or cancel link.

Thank you
