### ISSUE TITLE
Ressource-based-view

### ISSUE THREAD

**Issue by mauriziodidomenico** [kanboard/kanboard#2849]
Hi Frederic,

this is a feature request. I work in the product development of hardware parts. We plan our task together, but don't have sprints, like scrum, due to the big time impact during manufacturing of prototypes. We have several project and several departments. As example a project team have 7 people (2 x Development, 1 x Application Engineering, 1 x Procurement, 1 x Production Engineering ....). As you could imagine from the organisation point of view we have dedicated Groups. 

Here an Example of two Projects as we work now.
Project X:
![image](https://cloud.githubusercontent.com/assets/16655789/20709611/ad80f584-b636-11e6-8341-572c0dd092cf.png)
Project Y:
![image](https://cloud.githubusercontent.com/assets/16655789/20709673/ffa0c0e2-b636-11e6-9349-07164ef05b7b.png)

Now my question is, is it possible to have a kind of ressourced based view, that means that i see an overview of all task over all projects just for a dedicated Group (for all memebers of this group)? I don't have a need for drag and drop this task, because this should happen in the projects, the goal is to see how many task as an example a production engineering have in total? What is already planned, what is ongoing ....

Ressource Based View
![bla](https://cloud.githubusercontent.com/assets/16655789/20710265/c5b313aa-b639-11e6-8714-336a311b4c74.png)

Project -> Ressource Based View
![asdfasf](https://cloud.githubusercontent.com/assets/16655789/20710295/ea2779e2-b639-11e6-86ca-d92aa88968d5.png)

**Comment by sstiene** [comment]
I'd also need this feature.

Perhaps it can be additionally realized as described here:
https://www.teamgantt.com/resource-management-software/

so that I have a tasks per day and hours per day overview over my team per project or for all projects.

I already computed this numbers using the python API but it would be great to have this in the web GUI!

**Comment by GlebPoljakov** [comment]
@sstiene, may be you can develop a plugin for Kanban?

I think, that such plugin will be popular.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
