### ISSUE TITLE
Translation Italian: Inzio Vs Inizio

### ISSUE THREAD

**Issue by TheCloud** [kanboard/kanboard#2852]
### Expected behaviour

"Start date" in Italian should be shown as "Data di inizio"

### Actual behaviour

"Start date" in Italian is shown as "Data di inzio"
(Missing an i)

## solution ##
Find the word "inzio" in the locale file for it_IT and replace all instances with "inizio"

**Comment by fguillot** [comment]
Thanks this fixed now
