### ISSUE TITLE
[FeatReq] Extend \ breakout swimlanes and coloums, multiple levels

### ISSUE THREAD

**Issue by dustinliddick** [kanboard/kanboard#2854]
### Expected behavior

I am using a 'backlog\TODO' column. I would like to have this as an independent column separate from the rest of my columns. I would also like to be able to have multiple levels of swimlanes with each their own columns.

Attaching example image
![devkanbanboard](https://cloud.githubusercontent.com/assets/8737875/20756933/7d5347ac-b6e2-11e6-8cf1-d1a5418e8952.png)

**Comment by BlueTeck** [comment]
see also #2831

**Comment by dustinliddick** [comment]
Damn.... totally missed that one, sorry. Thank you very much for pointing that out to me!!

Closing and referencing original request #2831
