### ISSUE TITLE
Feature Request - Integrating hours per week and workload percentage

### ISSUE THREAD

**Issue by sstiene** [kanboard/kanboard#2855]
Hi Kanboard Team,
this is a feature request and general question. 
I want a hours per week field in the personal settings and than a percent field in the new task dialog. So that I am for example able to say that this task takes 40% of my workload from start date until due date. This would simplify the integration of long tasks as otherwise you have to compute the hours yourself. Is this already possible somehow?

Background: We are a non profit research institute with computer scientists and want to give kanboard a try for multiproject resource planing and tracking in combination with a personal task dashboard. We are willing to contribute to the kanboard development but we are currently in the phase of analyzing to which degree kanboard already fits our needs. 
Kind Regards
Stefan

PS.: Is this the right place to ask this general questions? Or is there a kanboard forum somewhere?

**Comment by fguillot** [comment]
This is probably better to develop features like that as external plugin. The forum is there: https://forum.kanboard.net/
