### ISSUE TITLE
Close a task in a column doesn't work in specific project

### ISSUE THREAD

**Issue by EstebanMonge** [kanboard/kanboard#2856]
### Expected behaviour

We created a automatic action, if you move a task to column Finish must be Closed.
Event name = Move a task to another column
Action name = Close a task in a specific column
Column = Finish

### Actual behaviour

Actually the task isn't not closed when you move to Finish column.

The problem only occurs in one specific project, all projects can close automatically the task.

### Configuration

Application version: 1.0.34
PHP version: 7.0.13-1~dotdeb+8.1
PHP SAPI: apache2handler
OS version: Linux 3.16.0-4-amd64
Database driver: sqlite
Database version: 3.8.7.1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36

**Comment by fguillot** [comment]
You should provide more details about your issue because if you tell me that works everywhere except for one project, there is no way to guess the root cause of the problem.

**Comment by fguillot** [comment]
No answer
