### ISSUE TITLE
Manager Dashboard or a Report View (Feature Request)

### ISSUE THREAD

**Issue by rakesh1084** [kanboard/kanboard#2857]
### Expected behaviour

There should be a common report plugin (basic table view report) of all the projects with various metrics.

_Sample Report format:_ - 

1. Portfolio Project Summary (Report of all the projects as a report in a table format is also OK)
SrNo, ProjectName, Status

2. Project Summary with Assignee view 
SrNo, ProjectName, Assignee, Status
like wise category wise and so on and so forth.

so that a manager will have visibility where the Project is struck and under whose bucket and for how long and so on and so forth.

# common Gantt View in (read only mode) of all the projects for Manager Role.

**This is not related to #426, so kindly do not close as duplicate)**

### Configuration
Kanboard 1.0.34

**Comment by rakesh1084** [comment]
any luck on this..?

**Comment by rakesh1084** [comment]
Hi @fguillot , do you have this in the roadmap..?

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
