### ISSUE TITLE
Internal links lable is missleading

### ISSUE THREAD

**Issue by hjjohny** [kanboard/kanboard#2858]
### Expected behaviour

I create 2 tasks (A,B) in the board, and set A to be blocked by B with internal link on A. 
A should show the link as: "is blocked by B". ( This part is working)
B should show the link as: "is blocking A". (This part is not working)

### Actual behaviour

The link on A works as it should be, but in B it shows: "is blocked by A" instead of is "is blocking A"
(This behavior is present at the other labels to: "is child of" , "is "duplicated by")

### Steps to reproduce

1. Create two task A,B
2. Set the internal link on A to: is blocked by B  (or to "is child of" or "is "duplicated by")
3. Check the internal links label in both of the tasks

### Configuration

    Application version: 1.0.34
    PHP version: 5.4.45-0+deb7u3
    PHP SAPI: fpm-fcgi
    OS version: Linux 3.2.0-4-686-pae
    Database driver: sqlite
    Database version: 3.7.13
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by fguillot** [comment]
Unfortunately, we are unable to reproduce the original issue after all this time. You should try with the latest version of Kanboard and reopen this ticket if necessary.

Task A:

![image](https://user-images.githubusercontent.com/323546/31572142-dc2cf9e2-b053-11e7-8480-615c9f3fc412.png)

Taks B:

![image](https://user-images.githubusercontent.com/323546/31572145-e9501ea6-b053-11e7-8a4d-501ed06f5d6e.png)

Thank you
