### ISSUE TITLE
Project Templates - Feature Request

### ISSUE THREAD

**Issue by wiserweb** [kanboard/kanboard#2862]
### Summary

Make possible to define common project types as predefined project templates. These are either included as part of Kanboard default installation or can be imported/downloaded/added to an existing installation.

Perhaps this can be achieved by adding ability to export projects structure only to be able to share via website and community.

### Description

Templates consist of a default project name and columns.

Proposed Templates:
-Basic Template
-Time Driven Template
-Event Driven Template
-Product Development Template
-Sales Pipeline Template
-Online Marketing Template

See kanbantool.com for example templates.

**Comment by fguillot** [comment]
Project templates are already available.

When you create a new project you can choose to duplicate another project. The original project is your template.
