### ISSUE TITLE
PLUGIN_INSTALLER missing from default.config.php

### ISSUE THREAD

**Issue by wiserweb** [kanboard/kanboard#2863]
### Expected behaviour

A line like the following should exist in config.php

// Allow plugin installation
define('PLUGIN_INSTALLER', 'false');

So that the administrator may simply change the value to true if they wish to enable plugin installation.

i.e. 
// Allow plugin installation
define('PLUGIN_INSTALLER', 'true');

### Actual behaviour

No line with PLUGIN_INSTALLER in config.default.php

### Steps to reproduce

1. extract latest stable 1.0.34  .zip
2. Open config.default.php
3. Examine file to see no PLUGIN_INSTALLER configuration exists

**Comment by fguillot** [comment]
Thanks, this is done in the development branch.
