### ISSUE TITLE
Can't specify "creator_id" in createExternalTaskLink and createTaskFile API calls

### ISSUE THREAD

**Issue by mably** [kanboard/kanboard#2866]
So the related columns are shown as empty on Kanboard web site :

![image](https://cloud.githubusercontent.com/assets/385653/20838298/3c62c5f2-b8a8-11e6-92ff-fb8765cfd257.png)

**Comment by fguillot** [comment]
At the moment, the creator_id is the current session user, if you use the user "jsonrpc" you will get 0. You could use a specific user for this.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
