### ISSUE TITLE
jsonRPC API / removeProject

### ISSUE THREAD

**Issue by Hofi67** [kanboard/kanboard#2867]
I am heavily using the jsonRPC API with user "jsonrpc"  and global api token (Ubuntu/mySQL). 
So I create projects by "createProject" and many "createTasks".

If I delete such a project with "removeProject" everything is doing fine in the UI. No project no tasks anymore...

But if I create a new project again, the id counters for Projects and Tasks do not reset - so my new tasks have ids like "#10454"... 

Can I be sure that tasks are deleted from database even if there is no counter reset?

Not quite sure ... but in testing I did deletion by hand and ids never counted up. Is there a difference between creator "admin" and a normal Member as creator?

Thank you for the the great project!

Frank

**Comment by fguillot** [comment]
Task IDs do not "reset", this is a auto-increment field in your database.
