### ISSUE TITLE
not able to login using Chrome

### ISSUE THREAD

**Issue by rakesh1084** [kanboard/kanboard#2868]
### Expected behaviour
the website should work in google chrome smoothly.  so thought I will debug and see. 

**when the debug is true and the log mode is file, it should capture all the info including sql queries in debug.log**

### Actual behaviour
the debug.log just prints below lines instead of actual error messages or the sql statements.

> [2016-12-03 19:15:36] [debug] Kanboard\Core\Controller\Runner::executeMiddleware
> [2016-12-03 19:15:36] [debug] Subscriber executed: Kanboard\Subscriber\BootstrapSubscriber::execute
> 

### Steps to reproduce

1. renamed the config file to config.php
2. changed the debug true
3. mode to file

// Data folder (must be writeable by the web server user)
define('DATA_DIR', 'data');

// Enable/Disable debug
define('DEBUG', true);

// Available log drivers: syslog, stderr, stdout or file
define('LOG_DRIVER', 'file');

// Log filename if the log driver is "file"
define('LOG_FILE', DATA_DIR.DIRECTORY_SEPARATOR.'debug.log');

// Plugins directory
define('PLUGINS_DIR', 'plugins');

// Available cache drivers are "file" and "memory"
define('CACHE_DRIVER', 'memory');

// Cache folder to use if cache driver is "file" (must be writeable by the web server user)
define('CACHE_DIR', DATA_DIR.DIRECTORY_SEPARATOR.'cache');

// Folder for uploaded files (must be writeable by the web server user)
define('FILES_DIR', DATA_DIR.DIRECTORY_SEPARATOR.'files');

// E-mail address for the "From" header (notifications)
define('MAIL_FROM', 'replace-me@kanboard.local');

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Configuration

◾ Application version: 1.0.34 
◾ PHP version: 7.0.9 
◾ PHP SAPI: cgi-fcgi 
◾ OS version: Windows NT 10.0 
◾ Database driver: mysql 
◾ Database version: 5.5.45 
◾ **Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586** 
It works well.
when ◾ **Browser: Chrome* it does not 
Note:- Microsoft IIS 

**kindly help and Thanks for the cool project**

**Comment by rakesh1084** [comment]
**another unusual behavior**
when the debug is true none of the write is happening to database.

**Comment by fguillot** [comment]
You should try again with the v1.0.38, a bug has been fixed regarding the default value in the example config file.

See issue #2955 (reopen if necessary)
