### ISSUE TITLE
Filter error in project activity page

### ISSUE THREAD

**Issue by notrinos** [kanboard/kanboard#2871]
I got an error "Internal Error: Action not implemented" when used filter in project's activity page. Is this a bug?
_sorry for my bad English_

**Comment by notrinos** [comment]
The error disapear now, but the activity's filter does not work at any syntax, or maybe i wrong the syntaxs?

**Comment by fguillot** [comment]
This issue have been fixed in v1.0.36 with PR #2875 

Thank you
