### ISSUE TITLE
Help for a plugin on Gantt view

### ISSUE THREAD

**Issue by oliviermaridat** [kanboard/kanboard#2874]
Hi,

I need some help to create a plugin that uses "targets milestone" and "is blocked by" links to simulate start/due dates in the task Gantt view. In the example below, I have just set the start / due dates of the milestone and the due date of a blocking task, and the other tasks have been automatically displayed correctly.

![gantt-milestone-and-blocked](https://cloud.githubusercontent.com/assets/953989/20960699/f64a6daa-bc61-11e6-9383-9af822c5da8d.png)

I have [a simple patch for this on my fork](https://github.com/oliviermaridat/kanboard/commit/0126170f3e5ff3fed58cb4182b5b77c30019c968).

The question is: how can I adapt this patch to fit into a plugin? I do not know how to modify the behaviour of the GanttFormatter. Any help / ideas are welcome!

Thanks!

**Comment by fguillot** [comment]
The creation of the object GanttFormatter could be moved to a service provider and then you can create a new class that inherits from GanttFormatter. And finally, in your plugin, replace the formatter by your own object.

**Comment by oliviermaridat** [comment]
Thanks for your replu @fguillot!

I did not see yet how to move the GanttFormatter instantiation into a service provider. Anyway, I think an other solution may be to add a reference hook in TaskGanttFormatter::formatTask before to return the task data. Something like:

```
  private function formatTask(array $task)
    {
        if (! isset($this->columns[$task['project_id']])) {
            $this->columns[$task['project_id']] = $this->columnModel->getList($task['project_id']);
        }

        $start = $task['date_started'] ?: time();
        $end = $task['date_due'] ?: $start;

        $data = array(
            'type' => 'task',
            'id' => $task['id'],
            'title' => $task['title'],
            //...
        );

        $this->hook->reference('formatter:task:gantt:task', $data);
        return $data;
    }
```

Can you confirm? Do you have any preference in these 2 solutions?

Thanks!

**Comment by fguillot** [comment]
I made some changes in master, you can now override any formatter classes, there is an example here: https://github.com/kanboard/kanboard/blob/master/doc/plugin-overrides.markdown#formatter-overrides

Adding a plugin hook could work, but overriding the default class avoid to add hooks everywhere in the application, this approach is more "object-oriented".

**Comment by oliviermaridat** [comment]
Thank you @fguillot ! As you may have seen, I merged my patch in the Milestone plugin. I had to override completely the GanttTaskFormatter due to "private" methods, which may increase the risk of conflict between plugins, but at least, this is working.
