### ISSUE TITLE
Unprotected "db.sqlite" file

### ISSUE THREAD

**Issue by peugnezb** [kanboard/kanboard#2877]
Hello,

I have just seen that the file http://mywebsite.fr/kanboard/data/db.sqlite is accessible by everyone just after installation on Centos 7.

It's normal ?

Thanks

**Comment by fguillot** [comment]
This is up to you to configure your web server.

See: https://github.com/kanboard/kanboard/blob/master/doc/installation.markdown#security

**Comment by peugnezb** [comment]
Oh sorry, I had not seen this part of the wiki.

Thanks a lot
