### ISSUE TITLE
[Feature Request] Time since last modification

### ISSUE THREAD

**Issue by WolfgangAndreas** [kanboard/kanboard#2878]
It would be nice to (optionally) have a third column "Time since last modification" which is displayed right to "Task age in days" and "Days in this column" which gets updated when any change on the Task was done.

For example this gets updated, if anyone adds a comment or so on to the task.

So it would be possible to see directly, when the last time was a change has been done to the task. This would be very useful for tasks where anybody have to regulary check the status and do not want to note the last check time.

Additionally it would be nice, if the color of the task is able to automatically changed when the time is exceeding a specific limit.

Thanks for your great work!!!!

Kind regards,
Wolfgang

**Comment by loonies** [comment]
What about notifications? You have web and email notifications that will
notify you on any change.

**Comment by WolfgangAndreas** [comment]
That's right. But for my use case i often take comments to myself, to my own tasks, which does not send any notification.

I have many parallel tasks were i just want to see "ah okay, you didn't watch for this about ~4hrs. call the user again". For this it would be great to have colorizing and / or notification.

We are using kanboard mainly as a kind of ticketing system for one of our projects.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
