### ISSUE TITLE
I'm not able to login with Microsoft IIS on Windows 10

### ISSUE THREAD

**Issue by ssoorajrauth** [kanboard/kanboard#2880]
### Should able to see index page of this application

I must able to brows through kanban application

### 1) I downloaded kanboard-master folder and in IIS I created a website (http://kanban.com:60/) and physical path was outside inetpub . When I browse this website  I am getting  **"Make sure you’ve got the right web address"** error.

2) I copied  kanboard-master folder in inetpub\wwwroot folder. When I browse this website I am getting **"HTTP Error 500.19 - Internal Server Error"**. Please see attached screen-shot of error for more details.
![screenshot 388](https://cloud.githubusercontent.com/assets/24458848/21016813/089aa9f8-bd8d-11e6-9cb9-c62973a8b1c3.png). 

When I click on PHP Manager I am getting below screen-shot error
![screenshot 389](https://cloud.githubusercontent.com/assets/24458848/21017365/20dcf1ea-bd8f-11e6-8310-7d4356601203.png)

When I click on Handle Mapping below is screen-shot

![screenshot 390](https://cloud.githubusercontent.com/assets/24458848/21017410/40f5be80-bd8f-11e6-8d59-21523a395cb3.png)

I have deleted web.config file.

Please help me to resolve this.

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 
- Database type and version:
- PHP version: 5.6
- OS: windows10
- Browser: IE, Chrome

**Comment by fguillot** [comment]
Unfortunately, this issue is not related directly to Kanboard but to your server configuration. Maybe, you should take a look to the official documentation of PHP.
