### ISSUE TITLE
Local avatar images not visible in public view

### ISSUE THREAD

**Issue by brueggemann** [kanboard/kanboard#2881]
### Expected behaviour
The locally uploaded avatar images should be visible in public view

### Actual behaviour
The avatars can not be loaded. I tried to load the image URL directly and got a login screen.

### Steps to reproduce

1. Upload avatar
2. Take a task, so that your avatar is shown on it
3. Open the public view with some incognito mode browser

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.35
- Database type and version: MySQL (don't know the version)
- PHP version: 5.6
- OS: FreeBSD
- Browser: Midori / Chromium

**Comment by fguillot** [comment]
This issue have been fixed in 1.0.36 by PR #2887 

Thank you
