### ISSUE TITLE
Notifications for tasks when the start date is reached

### ISSUE THREAD

**Issue by sha-marsig** [kanboard/kanboard#2883]
### Expected behaviour
A Task has the possiblity to set a start date. If I create a task in the future then it would be nice to get a notification based on the start date. So I can ignore this task until the notification is received.

### Actual behaviour
feature request

### Configuration
    Version: 1.0.34
    PHP Version: 5.5.9-1ubuntu4.20
    PHP SAPI: apache2handler
    OS Version: Linux 3.13.0-101-generic
    Datenbanktreiber: postgres
    Datenbank Version: 9.3.15
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
