### ISSUE TITLE
How to run Kanboard inside an Symfony 3 application?

### ISSUE THREAD

**Issue by k00ni** [kanboard/kanboard#2884]
I would like to run Kanboard inside my Symfony 3 application[1]. 

With *run* i mean the following:
* central user login: user logs into my application and is also "logged-in" for Kanboard
* visual integration: inclusion of the UI inside twig/php/... 
  * is it possible to deactivate UI elements from the outside?

Can you please tell me, what would be a good approach to realize that? My current idea would be to write a plugin to realize the central user login and include Kanboard via iFrame (regarding visual integration).

[1] - http://symfony.com/what-is-symfony

**Comment by fguillot** [comment]
You can include KB in a iframe and do the authentication part with OAuth2 or whatever SSO system. But, I don't see the point of including KB in another Symfony app.

**Comment by k00ni** [comment]
KB is a good PM and organize tool and we want to use it extensively. Therefore we don't want to rewrite, but to include/integrate it for now.

Could you please explain the OAuth2/SSO part a little bit more?

**Comment by fguillot** [comment]
There is a generic OAuth2 plugin here: https://github.com/kanboard/plugin-oauth2 It could be a good starting point.

**Comment by k00ni** [comment]
Hi @fguillot, my current setup is my custom app and the Kanboard. Users login into my custom app and after they did, i want them to be logged in into Kanboard as well. Can i realize that using the OAuth2 plugin?
