### ISSUE TITLE
Question: Gather specific data about categories and their time spent in columns

### ISSUE THREAD

**Issue by Perrylicious** [kanboard/kanboard#2885]
Hi,

this is a question about functionality. Please delete if you don't allow that here.

Is there a way to extract information about how long tasks (open and closed) from a specific category (e.g. "Web" or "Doc") have spent in a specific column (e.g. "New", "In Progress", "Done")? This would tell my users how long certain categories wait until they're moved to "In Progress" and how long they're actually worked on (until moved to "Done").

Thank you.

Regards,
Perry

**Comment by sstiene** [comment]
look at the 
https://kanboard.net/documentation/analytics
-> Average time spent into each column

But I have a related question: I want to get the total amount of working hours spent on a project. The Idea was, that I sum up the spent hours of all tasks in the "Done" column but it seams that the API is not able to give me closed tasks and if all tasks have to remain open  the "Done" column will be overcrowded with tasks very soon.
