### ISSUE TITLE
Autoamtic assignment for subtasks

### ISSUE THREAD

**Issue by jmi-compador** [kanboard/kanboard#2888]
When I start working on a subtask which is not assigned yet, I expect the subtask is assigned to me a a registered user.

When I start working on a unassigned subtask this subtask stays unassigned and switches to assigned when I stop working on it. But the time tracking didn't work.

**Comment by fguillot** [comment]
Can you provide all the steps to be able to reproduce the problem?

**Comment by jmi-compador** [comment]
It's pretty simple to reproduce the point:
- create a task
- add a subtask to this task without assigning a user to it
- click the subtask's checkbox to start working on the subtask
You can see the subtask is not assigned by the user you're logged in. Also the time tracking is not working for this subtask for this user. 

When you click the check box again to finish the subtask, the subtask is assigned to the logged in user.

**Comment by fguillot** [comment]
Which version of Kanboard are you using?

**Comment by jmi-compador** [comment]
The installed version is 1.0.31

**Comment by rautamiekka** [comment]
^ That's your problem: old version, the newest is 1.0.40 and it works fine there, but **I don't use time tracking** (it's globally disabled on purpose) so it stays empty for me, and if I click either the main task or the subtask to go into the main task's page I see 'Start timer' instead.
