### ISSUE TITLE
Question: Is it possible to hide tasks and subtasks in Dashboard?

### ISSUE THREAD

**Issue by erpnedir** [kanboard/kanboard#2889]
Hi,
I want to remove / hide tasks and subtasks grid in Dashboard. Is it possible, how can I do that?
Thanks

**Comment by fguillot** [comment]
You can hide tasks on the dashboard based on the column. If you go to the project config > column > edit a column, there is a checkbox for that.

**Comment by erpnedir** [comment]
Thank you very much. This helped me simplify the dashboard.
