### ISSUE TITLE
Customer/Client information on project and tasks

### ISSUE THREAD

**Issue by mkysoft** [kanboard/kanboard#2892]
We need customer/client information on project. Also I can filter projects by customer/client on projects page. May be we can use tags for this. But we need making change on project listing for filtering.

I can work on this feature if you approve (Also I working this on own clone).

**Comment by erpnedir** [comment]
Hi Mustafa, I would like to keep in touch with you about KB modification.

**Comment by SergiArias** [comment]
I think this feature would be awesome. Every project I open I write "COMPANY - Name of project", to be able to see the clients/customers.
Kanboard could have the option to assign clients or customers, and then, be able to see a list of all clients with their related projects. Not necessary to be a CMS, though, just simple options to understand the full picture.

**Comment by rakesh1084** [comment]
Genuine Requirement and a cool feature request.
waiting to get it

**Comment by fguillot** [comment]
I'm closing this ticket. I let the community develop such plugin if anyone is interested.
