### ISSUE TITLE
Ubuntu 16.04 PHP7.0 => Database driver not supported

### ISSUE THREAD

**Issue by mtinfo** [kanboard/kanboard#2894]
### Expected behaviour

Tell us what should happen
Application need start

### Actual behaviour

Tell us what happens instead
After installation and config PHP7.0-Sqlite3 and install PHP7.0-mbstring I get this : 
Internal Error: Database driver not supported

PHP and Mysql run fine on the serveur

### Steps to reproduce

1. Install
2. Config MySQL connexion param
3. install module needed as it demand
Connect to URL

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: Change log : Version 1.0.35
- Database type and version: MySQL 5.7.16-0ubuntu0.16.04.1
- PHP version: 7.0.8-0ubuntu0.16.04.3
- OS: Ubuntu 16.04
- Browser: Chrome,  FF

**Comment by fguillot** [comment]
Can you show your config file?

**Comment by mtinfo** [comment]
Bonjour Frédéric, 


Voici le fichier de config. 


Cordialement, 
Marc 
----- Mail original -----

De: "Frédéric Guillot" <notifications@github.com> 
À: "kanboard/kanboard" <kanboard@noreply.github.com> 
Cc: "mtinfo" <mt.info@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 16 Décembre 2016 12:46:34 
Objet: Re: [kanboard/kanboard] Ubuntu 16.04 PHP7.0 => Database driver not supported (#2894) 


Can you show your config file?

**Comment by fguillot** [comment]
I didn't see any config file in your message.
