### ISSUE TITLE
Public or Read Only Board: Adding Information

### ISSUE THREAD

**Issue by Pindawen** [kanboard/kanboard#2898]
The kanboard board is really impressive!  I have a question, my boss would like me to put the 'public' kanboard board on our website so his boss(es) can easily see all of our projects at a glance without logging in. I have two questions: 

1) What file would I edit in php, to echo out the project name of the board at the top?  
2) If I wanted to add some custom php code, as a footer, to this read only page, where would I do that? 

I have a link of my public site below. The Project or 'board' name is "Technology Projects", but on the public page its not printed on the screen.

Link: 
https://techprojects.min201.org/?controller=BoardViewController&action=readonly&token=7094d41bf7356839be3b382090b1390c4086df857d6556bce5ca1ce986a5

**Comment by fguillot** [comment]
You could edit the file `app/Template/board/view_public.php`

**Comment by lucaspessoapereira** [comment]
@fguillot sorry, I'm trying to edit the `app/Template/board/view_public.php` you mentioned, but nothing works. I'm also trying to edit the `app/Controller/BoardViewController.php` file, changing `'no_layout' => true,` to `'no_layout' => false,` just below the `* Display the public version of a board` comment, but this is getting me some weird header when i'm not logged in. How could the public board get a center-aligned header just with the project title?
