### ISSUE TITLE
Question: How to link to a certain view in the calendar?

### ISSUE THREAD

**Issue by k00ni** [kanboard/kanboard#2902]
Is it possible to link to a certain view in the calendar, for instance to the week view? My current research shows that i only can go to the calendar and pick the view myself, but its implemented using JavaScript and not dereferenceable. In my case i want to call Kanboard's calendar via URL and open either month, week or day view.

![screenshot from 2016-12-21 17 45 39](https://cloud.githubusercontent.com/assets/381727/21397821/77c9c03a-c7a5-11e6-85b9-7aa25588d55d.png)

**Comment by fguillot** [comment]
Someone have to implement this feature.

**Comment by fguillot** [comment]
This is now possible in master. PR #3063 has been merged.

**Comment by k00ni** [comment]
Thanks @kvj and @fguillot for implementing and reporting this. Will look into it soon.

**Comment by fguillot** [comment]
This is now available in Kanboard 1.0.40
