### ISSUE TITLE
API: getAllSwimlanes returns position instead of id in 'id' field.

### ISSUE THREAD

**Issue by eskiou** [kanboard/kanboard#2903]
### Expected behaviour

When querying getAllSwimlanes, API should return id: swimlane_id and position: swimlane_position. getActiveSwimlane does it correctly.

### Actual behaviour

getAllSwimlanes returns id: swimlane_position and position: swimlane_position

### Steps to reproduce

No specific situation, just query getAllSwimlanes

### Configuration

Seen using framaboard version.
Application version: 1.0.34
PHP version: 5.6.29-0+deb8u1
PHP SAPI: cgi-fcgi
OS version: Linux 3.16.0-4-amd64
Database driver: sqlite
Database version: 3.8.7.1

**Comment by markjszy** [comment]
@eskiou , I was not able to reproduce this. Can you post results of a specific example of API queries that you have made?

**Comment by fguillot** [comment]
I cannot reproduce your issue either, here an example with the Python client:

```python
>>> pprint.pprint(kb.get_all_swimlanes(project_id=6))
[{u'description': None,
  u'id': 10,
  u'is_active': True,
  u'name': u'Default swimlane',
  u'position': 1,
  u'project_id': 6},
 {u'description': u'',
  u'id': 12,
  u'is_active': True,
  u'name': u'Another swimlane',
  u'position': 2,
  u'project_id': 6}]
>>> pprint.pprint(kb.get_active_swimlanes(project_id=6))
[{u'description': None,
  u'id': 10,
  u'is_active': True,
  u'name': u'Default swimlane',
  u'position': 1,
  u'project_id': 6},
 {u'description': u'',
  u'id': 12,
  u'is_active': True,
  u'name': u'Another swimlane',
  u'position': 2,
  u'project_id': 6}]
```
