### ISSUE TITLE
LDAP replace default username with given name.sn

### ISSUE THREAD

**Issue by mehdiyahyaoui** [kanboard/kanboard#2904]
Hello

Can you please help

I'm trying to use the LDAP authentication feature

How to use the string "given name.sn" as the kanboard username instead of the default saamacounr (hope I spelled it OK) ?

I tried the custom tag #{given name}.#{sn} but it didn't work

Thanks

**Comment by mehdiyahyaoui** [comment]
in other word what should I pu in the configfile

// LDAP attribute for username
// Example for ActiveDirectory: 'samaccountname'
// Example for OpenLDAP: 'uid'
**define('LDAP_USER_ATTRIBUTE_USERNAME', 'xxxxxxxxxxxx');**

**Comment by mehdiyahyaoui** [comment]
plz Help

**Comment by mehdiyahyaoui** [comment]
Plz can someone adress my request

**Comment by mehdiyahyaoui** [comment]
Would it be possible to use the same sync schema used in Rocket.CHAT

![image](https://cloud.githubusercontent.com/assets/23338414/24600566/2bda42e6-184d-11e7-8b6e-20343f4ba530.png)

**Comment by fguillot** [comment]
This feature doesn't exists yet. If you really need that, the best way is to contribute.
