### ISSUE TITLE
Bug: Private projects removed after deleting a user

### ISSUE THREAD

**Issue by marienfressinaud** [kanboard/kanboard#2905]
### Expected behaviour

After deleting a user which is not the owner of a private project, I expect project to not be deleted.

### Actual behaviour

After deleting a user associated to a private project, the project disappears. It makes sense if there is only one user associated to the project… but it was not the case (which may be the real bug).

### Steps to reproduce

1. Create a project and change to "private project"
2. Create a user and associate it to this project 
3. Delete the user

Or

1. Create a project
2. Associate some users to it
3. Change to "private project"
4. Delete a user

### Configuration

    Version de l'application : 1.0.34
    Version de PHP : 5.6
    Type de base de données : sqlite
    Version de la base de donnée : 3.8.7.1
    Navigateur web : Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
