### ISSUE TITLE
Documentation Improvements: OpenSuSE and mySQL

### ISSUE THREAD

**Issue by zorner** [kanboard/kanboard#2906]
### OpenSuSE

Instead of : sudo chmod -R 777 kanboard

sudo chown -R wwwrun /srv/www/htdocs/kanboard

### mySQL

mysql> CREATE DATABASE IF NOT EXISTS `kanboard`

mysql> CREATE USER 'kanboard'@'localhost' IDENTIFIED BY '$password';

mysql> GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, CREATE TEMPORARY TABLES, DROP, INDEX, ALTER, LOCK TABLES, REFERENCES ON `kanboard`.* TO 'kanboard'@'localhost';

With instruction to change '$password' to a password they want to use, and adjust the username as needed. 

Using the 'root' is not desirable. Even here the kanboard user has too much access normal operation, and if hacked could drop all the tables in the kanboard DB.

**Comment by levlaz** [comment]
Why not send a PR against the docs with these updates rather than making an issue?

**Comment by fguillot** [comment]
The doc have been updated.
