### ISSUE TITLE
Question: Can I run kanboard with an older PHP version (5.2) ?

### ISSUE THREAD

**Issue by fsilveir** [kanboard/kanboard#2907]
### Question

Hi all, I'm trying to put kanboard on one application server that I have, but unfortunately the PHP version there is 5.2, which according to the requirements wouldn't work. I've read some folks commenting that the requirement for greater version is just because of some password hash functions... So I was wondering if I could disable or work around this to try using the board with the existing version of php that I have.

- Kanboard version: 1.0.35
- Database type and version: sqlite
- PHP version:  PHP 5.2.14 with Suhosin-Patch 0.9.7 (cli) (built: Jul 17 2013 23:26:47) 
- OS: SUSE Linux Enterprise Server 11 SP4
- Browser: Chrome

**Comment by fguillot** [comment]
Kanboard will never work with 5.2, PHP Namespaces are required and are available since PHP 5.3.

**Comment by fsilveir** [comment]
Thank you Frédéric, just needed to be sure if I could work around it !!!
