### ISSUE TITLE
Ability to set due dates for subtasks through API

### ISSUE THREAD

**Issue by dhornford** [kanboard/kanboard#2910]
### Expected behaviour

When we use the API to create subtasks we would like to be able to create the due-date like we do with the addon in Plugins Directory

### Actual behaviour

No provision in API to create date_due

### Steps to reproduce

1. create subtask in browser, works
2. read https://kanboard.net/documentation/api-subtask-procedures, no parameter for date_due
3. Experiment with Task parameters in-case the documentation lagged and the plug-in added functionality (https://kanboard.net/documentation/api-task-procedures)

Similar to issue https://github.com/kanboard/kanboard/issues/2347 that was resolved by plugin (that issue probably should be resolved)

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.36
PHP version: 7.0.14
PHP SAPI: apache2handler
OS version: Linux 3.10.0-514.2.2.el7.x86_64
Database driver: mysql
Database version: 5.7.16-log

**Comment by fguillot** [comment]
At the moment, there is no due date for subtasks.
