### ISSUE TITLE
API Create tasks invisible if column_id is used

### ISSUE THREAD

**Issue by dhornford** [kanboard/kanboard#2911]
### Expected behaviour

Creating a task with API should allow it to be visible in the Board

### Actual behaviour

If the column_id parameter is used the task is invisible in the board until it is moved
The task appears in the assignee's dashboard and can be accessed through that link

### Steps to reproduce

1. Run the following script
#!/bin/sh

curl \
-u 'uname:token' \
-d '{"jsonrpc": "2.0",  "method": "createTask", "id": 1176509098,
    "params": {"title": "Invisible Column Title", "project_id": 3, "owner_id": 3, "creator_id": 3, "category_id": 6, "date_due": "2017-01-10", "column_id": 2 }
     }' \
https://kanboard.conexiam.com/jsonrpc.php

curl \
-u 'uname:token' \
-d '{"jsonrpc": "2.0", "method": "createTask", "id": 1176509098,
    "params": {"title": "Visible Title", "project_id": 3, "owner_id": 3, "creator_id": 3, "category_id": 6,
"date_due": "2017-01-10" }
}' \
https://kanboard.conexiam.com/jsonrpc.php

1st post is invisible, 2nd is visible.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.36
PHP version: 7.0.14
PHP SAPI: apache2handler
OS version: Linux 3.10.0-514.2.2.el7.x86_64
Database driver: mysql
Database version: 5.7.16-log
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by fguillot** [comment]
Did you check that the column_id 2 belongs to the project_id 3?

**Comment by dhornford** [comment]
I can see no way to identify “column_id” in the user interface.
Presumption was 2nd column

On January 4, 2017 at 7:54:42 PM, Frédéric Guillot (notifications@github.com)
wrote:

Did you check that the column_id 2 belongs to the project_id 3?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kanboard/kanboard/issues/2911#issuecomment-270550993>,
or mute the thread

**Comment by fguillot** [comment]
You could get the columnId with the API call "getColumns".
