### ISSUE TITLE
Cosmetic: first swimlane headers and column headers in the wrong order compared two other swimlanes

### ISSUE THREAD

**Issue by aslmx** [kanboard/kanboard#2912]
Only a small cosmetic problem but it bugs me. Maybe it can be fixed - or maybe it is even by design? ;)

### Expected behaviour

Board view shows always

SWIMLANE HEader
Column Headers
SWIMLANE Header
Column Headers
etc.

### Actual behaviour

regardless whether default swimlane is activated or not, the first Swimlane has the column headers above the swimlane title bar.
All the other Swimlanes will have the Swimlane title bar and then below there will be the column headers.

So the order is

Column Headers
SWIMLANE HEader

SWIMLANE Header
Column Headers
SWIMLANE Header
Column Headers
etc.

### Steps to reproduce

1. Have a project with 2+ Swimlanes
2. Go to Project, switch to Board view
3. Look at the first swimlane and check for the order of the Column headers and the swimlane title
4. Look at the second swimlane and check for the order of the column headers and the swimlane title
5. Notice that the first Swimlane differs from all the other Swim lanes

### Configuration

    Application version: 1.0.36
    PHP version: 5.6.19-0+deb8u1
    PHP SAPI: apache2handler
    OS version: Linux 4.1.19-v7+
    Database driver: sqlite
    Database version: 3.8.7.1
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by fguillot** [comment]
Duplicate, see #2575 for explanation
