### ISSUE TITLE
Feature Request: Edit Automatic Action and make the dialog more simple

### ISSUE THREAD

**Issue by aslmx** [kanboard/kanboard#2914]
Right now there is no possibility to change an automatic action. If i want to change the color that a task is assigned upon a certain event, i need to delete + re-recreate the automatic Action.

Also the dialog could be simplified by removing the necessity to click the "Next" Button once i choose something from the combo-boxes. Cant the dialog show all options directly to save some clicks?

Thanks!

**Comment by fguillot** [comment]
Duplicate with #1804
