### ISSUE TITLE
Allow LDAP and local authentication to work together

### ISSUE THREAD

**Issue by nicopace** [kanboard/kanboard#2916]
### Expected behaviour

When you have LDAP auth enabled, to be able to authenticate with a local account that does not belong to ldap.

### Actual behaviour

When you have ldap auth enabled, and you create a local user, the local user is rejected to login, saying "Invalidate session for user" in the logs and not letting the user log in.

### Steps to reproduce

1. enable LDAP
2. create a local user account
3. login with the local user account

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.31
- Database type and version: MySQL 5.5.53
- PHP version: 5.6.29-0+deb8u1
- OS: Debian
- Browser: Chrome/Firefox/Chromium

**Comment by rmkraus** [comment]
Just a suggestion: To get this behavior with Apache, you could use an .htaccess rule in combination with mod_authnz_external and pwauth. This should work if your system is also configured to authenticate with LDAP.

**Comment by fguillot** [comment]
Actually you can have both local and LDAP users. However, the local users must be not be present in your LDAP directory. Kanboard try first to contact LDAP then the local database.

**Comment by nicopace** [comment]
Well... I created a local user in Kanboard that was not present in LDAP, and when i tried to login with his credentials (And an incognito browser) it rejected me

**Comment by fguillot** [comment]
Try a recent version of KB, there is more logs. That will probably help you to find this issue.
