### ISSUE TITLE
Create from another project not working 1.0.36

### ISSUE THREAD

**Issue by jaiume** [kanboard/kanboard#2918]
### Expected behaviour

You should be allowed to create a new project, duplicating the aspects you select from another project

### Actual behaviour

Just hangs.
When you reload site, it says 'Unable to create project' in purple at the top

Worked in 1.0.34

### Steps to reproduce

1. Use 1.0.36
2. Create a new project
3. Select an existing project under 'Create from another project'

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.36
PHP version: 5.6.29
PHP SAPI: apache2handler
OS version: Linux 3.10.0-514.2.2.el7.x86_64
Database driver: sqlite
Database version: 3.7.17
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by fguillot** [comment]
Can you try with the latest version of Kanboard and watch the debug log file when the problem happens?

**Comment by fguillot** [comment]
No answer

**Comment by jaiume** [comment]
Sorry for no response.

You snooze you loose I guess.

I checked on version 1.0.38 and it seems to be working fine
