### ISSUE TITLE
Sorting for "Display another project"

### ISSUE THREAD

**Issue by eurodrew555** [kanboard/kanboard#2920]
### Expected behaviour

I have recently upgraded to 1.0.36.

When using "Display another project" I'm pretty sure this used to be sorted alphabetically, however it now appears to be in the order of when the projects were created.

I have a lot of projects and use a naming convention of "COMPANY - xxxxxx" in the project name. When the project list is sorted alphabetically it is very fast to select the project I'm looking for. 

It would be great if this could be sorted alphabetically or alternatively be available as an option in the settings page.

### Actual behaviour

"Display another project" is not sorted alphabetically and it is now slower to find the project you are looking for.

### Steps to reproduce

1. Use the "Display another project" dropdown

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: master
PHP version: 5.6.29
PHP SAPI: fpm-fcgi
OS version: Linux 4.8.6-x86_64-linode78
Database driver: sqlite
Database version: 3.7.17
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by SergiArias** [comment]
I was going to open this exact issue, as I am working exactly in the same manner. 
As a matter of fact, regarding this issue, there are other slightly related issues (I am opening a ticket for each one, I list them only to summarize):

- In the user dashboard, when searching for tasks in column (eg: work in progress), the project, and swimlane order follows the same pattern described here, when it would be desirable to be alphabetic.
- It would be desirable to have clients/customers assigned to each project, and have the possibility to list the clients with all their related projects.

**Comment by fguillot** [comment]
This element is now sorted alphabetically in version 1.0.37.

Thank you

**Comment by SergiArias** [comment]
Thank you very much Frédéric!!
