### ISSUE TITLE
Dashboard search doesn't sort alphabetically project and swimlane

### ISSUE THREAD

**Issue by SergiArias** [kanboard/kanboard#2922]
### Expected behaviour

When sorting the project or the swimlane it should sort alphabetically as the creation order is not quite practical.

### Actual behaviour

The ordering is by project or swimlane creation.

### Steps to reproduce

1. From my dashboard, search: column:"work in progress"
2. Click "project" or "swimlane"

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.36
PHP version: 7.0.2
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-604.30.3.lve1.3.63.el6.x86_64
Database driver: mysql
Database version: 5.6.33-cll-lve
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by fguillot** [comment]
In the latest version, the sorting is now by name and not id.
