### ISSUE TITLE
There's no option to search or order a search by priority, position, or complexity

### ISSUE THREAD

**Issue by SergiArias** [kanboard/kanboard#2923]
### Expected behaviour

It would be desirable an option to search priorities, position in a column or complexity, and/or order by them. Or at least, set this up in general settings. I would use it to decide which tasks to move to work in progress when in my dashboard.

### Actual behaviour

This option doesn't exist.

### Steps to reproduce

1. Search column:"work in progress" (there are no options to search by priority, complexity or position)
2. There is no priority, complexity or position in column in the results.
3.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.36
PHP version: 7.0.2
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-604.30.3.lve1.3.63.el6.x86_64
Database driver: mysql
Database version: 5.6.33-cll-lve
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by fguillot** [comment]
You can sort by priority and position in v1.0.43

**Comment by sargat** [comment]
@fguillot 
Why not order by complexity?

**Comment by SergiArias** [comment]
@fguillot and the option to filter by priority or complexity?

Thanks for the change, it's much better now!!
