### ISSUE TITLE
New option to search in "Display another project" only search by initial letters.

### ISSUE THREAD

**Issue by SergiArias** [kanboard/kanboard#2924]
### Expected behaviour

This is an awesome feature when we have many projects, but as I have customer and project type identifiers in the beginning of the name of the project it becomes unusable in my kanboard. I would expect to search any string contained in the projects. Eg: If I want to select the project "COMPANY website", I would search "website" and all the projects containing the word website would be filtered.

### Actual behaviour

I have to search from the first letter of the project. If the project I want is "COMPANY website" I have to search by typing "c", "o", "m",...

### Steps to reproduce

1. Search any string contained in a project in "Display another project"

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.36
PHP version: 7.0.2
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-604.30.3.lve1.3.63.el6.x86_64
Database driver: mysql
Database version: 5.6.33-cll-lve
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by eurodrew555** [comment]
I'm running into the exact same problem as all my projects are prefixed with "COMPANYNAME - "
This would be perfect if it just matched any position rather than from the start of the project name.

I have also submitted a separate request to sort the projects alphabetically.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
