### ISSUE TITLE
What is your workflow?

### ISSUE THREAD

**Issue by SergiArias** [kanboard/kanboard#2925]
Hi! 

I recently installed kanboard, and I am amazed by it. I was using the kanban system on paper before, but this is a huge improvement. 

So, I would like to know your workflow while working with kanboard as maybe there is a better way that the one I am using.

**My workflow:**
**Once a week:**
I go to my dashboard, search all "the pen", "ready" and "backlog" tasks to see if there should be a column change, thinking and defining my week goals.

**Daily:**
I go to my dashboard, search by column "Filter1" (which is a similar column to "Ready", with just one task, the next task in the project), and decide which ones I should work today. 
Then, I search by column "work in progress", and reduce the list to no more than 3 tasks (unless some of the tasks take less than one hour).

I'm sure there's a better workflow, so I would like to know how do you manage to not get overwhelmed by the increasing responsibilities you have in many projects that don't have a due date.

I also thought the software could show a "virtual" kanban board with all your assigned tasks in all the projects at once, kind of a "personal kanban" where you can move the tasks between columns. But I don't know if it's too idealistic and not practical (and maybe impossible to code maintaing all the columns in the projects), existing a simpler and still clear and focused solution.

Thanks!

**Comment by fguillot** [comment]
To avoid cluttering the bug tracker, there is now a forum for open discussions: https://forum.kanboard.net/
