### ISSUE TITLE
working time tracking

### ISSUE THREAD

**Issue by vpistis** [kanboard/kanboard#2926]
Hi,
maybe this is a Feature Request, I don't see this kind of report into this kanboard version.
### Expected behaviour
In the day X a user work 2 hours into task 1 and 6 hours into task 2.
The manager or the administrator want to see a calendar where for the day X there is an entry for the user where to see the working time per day: in the day X the user has worked 2 hours into task 1 and 6 hours into task 6.

Obviously this statistic should exist for all users and for all projects.

### Actual behaviour

I don't see this feature

### Configuration

- Application version: 1.0.36
- PHP version: 5.5.9-1ubuntu4.20
- PHP SAPI: apache2handler
- OS version: Linux 3.13.0-74-generic
- Database driver: mysql
- Database version: 5.6.33-0ubuntu0.14.04.1
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 OPR/42.0.2393.94

**Comment by vpistis** [comment]
Hi @fguillot ,

I look today that the plugin maybe exists and is your own Timetable :).
I have installed it from first days.
For some obscured reason I don't see the menu `Manage Timetable` from my UserProfile :)
Now I have the possibility to create my standard work week and my effective work week, if I'm not wrong.

At this moment the "desiderata" (Expected behaviour) is to have a report per Project, per User, per Task, etc...for all users in the project, where I can see the spent time by day, week, month, etc..for all users at same time (if my role is Manager of the project).

There is a report like this?

**Comment by fguillot** [comment]
There is no report like this.
