### ISSUE TITLE
A fork based on Kanboard

### ISSUE THREAD

**Issue by lianguan** [kanboard/kanboard#2927]
Hi all

I developed a system based on kanboard, named jitamin.

Everyone can visit the demo site to see if there are any interesting features, and if so, I can send PR to kanboard.

Very grateful to @fguillot developed such a great project management system.

## repository

[https://github.com/jitamin/jitamin](https://github.com/jitamin/jitamin)

## demo

[http://jitamin.com](http://jitamin.com):

1. User

- **username:** `test` or `test@test.com`
- **password:** `test123`

2. Manager

- **username:** `jitamin` or `jitamin@jitamin.com`
- **password:** `jitamin`

## License

Jitamin is licensed under the license of MIT.  See the LICENSE for more details.

Jitamin is a fork based on Kanboard. Kanboard is Copyright Frédéric Guillot and others.

**Comment by rakesh1084** [comment]
Impressive and bravo...!
Can you make it as a plugin and give it to the original kanboard..?

**Comment by lianguan** [comment]
@rakesh1084 
A little disappointed. Jitamin can not run as a plugin for kanboard. Jitamin changes made relatively large. And is not compatible with kanboard. That's why I made a standalone derivative.

**Comment by rakesh1084** [comment]
@lianguan 
**Ok Understood. Really cool and very responsive web design.** 

Anyways while I tried to install in my IIS Environment it is not working.
downloaded & unzipped and pasted in C:\inetpub\wwwroot\jitamin
Open browser and tried http://localhost/jitamin just like I did for http://localhost/kanboard.
Not working..  :-( .
jitamin will work only in Linux based...?
if you have time request you to help me or other folks just like me

**Comment by fguillot** [comment]
Nice, don't hesitate to submit improvements upstream on KB :)

**Comment by renothing** [comment]
@fguillot 
the author removed all copyright information in his fork, and just made one line comment  in readme.md. what a sham!

**Comment by lianguan** [comment]
@renothing 

Thank you for your feedback. please see the license file here : https://github.com/jitamin/jitamin/blob/master/LICENSE

**Comment by lianguan** [comment]
If @fguillot thinks this is a serious matter, I can delete this project.
