### ISSUE TITLE
Feature request: export complexity of the subtask when exporting subtasks

### ISSUE THREAD

**Issue by fourier** [kanboard/kanboard#2928]
### Expected behaviour

There should be a way to export subtasks complexity taken from the task. It allows users to calculate 
the team score points done.

### Actual behaviour

Complexity of exported subtasks is not exported

**Comment by fguillot** [comment]
There is no complexity for subtasks, only for tasks?

**Comment by fourier** [comment]
Actually it is related to issue #2929. The users (managers of projects) want export statistics on tasks. 
It is useful to generate reports on week ends to measure the progress.

But tasks includes subtasks. The subtasks exported separately. And in these exports manager want to see the complexity of subtasks to understand amount of real efforts team had to put during a week/other time frame.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
