### ISSUE TITLE
Feature request: Exported tasks should have % of the completed subtasks

### ISSUE THREAD

**Issue by fourier** [kanboard/kanboard#2929]
### Expected behaviour

Right now exported tasks have no information about its completion status.
For example if the task is 'Open' but have 4 subtasks with 3 of them complete, it should be a column indicating what it is 75% done in exported CSV file.

### Actual behaviour

The percents of task completion are not available in the exported CSV file

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
