### ISSUE TITLE
Question: colored category labels?

### ISSUE THREAD

**Issue by Hofi67** [kanboard/kanboard#2930]
Hi, 

is it possible to give category labels (shown as a 'tag' or 'button') in tasks a specific background color?
I know I can do it for the whole Task background ... but I like clean white tasks ...

Thanks,
Frank

**Comment by ThomasTJdev** [comment]
@Hofi67 - I'm coloring my tags with this code: [colorful_tags](https://github.com/ThomasTJdev/KanboardColorfulTags). You could maybe do some code modifications and use it for categories.

**Comment by fguillot** [comment]
To avoid cluttering the bug tracker, there is now a forum for open discussions: https://forum.kanboard.net/
