### ISSUE TITLE
its almost a request for support. creating sub tasks via actions

### ISSUE THREAD

**Issue by lalamax3d** [kanboard/kanboard#2931]
## Expected behaviour
i need an action, which can add sub task, on create task event, my understanding, its not doable. but if it is, lucky day. 
### Actual behaviour
I am unable to find action which can help me setup this.
### Ideal behaviour
if that action will let me pick or add multiple sub tasks at once

HISTORY: in last month, i have tested lot of applications (qdPM, projectPier,myCollab) mostly stuck at one point or other, finally i found this tool via google, and its satisfy all needs for small animation studio where work typically split between two categories ( asset / shot ) (preproduction / production & post)
Asset, typically go through phase of (modeling/texturing/unwrapping/rigging/shaders) etc
Shot, typically go through phase of (animation,lighting,rendering,compositing) etc...
so, once actions are setup (ideal level) as soon as manage will add a task (shot) relevant sub tasks will get created. huge thanks for support

**Comment by lalamax3d** [comment]
current solution, i add one task(Shot) with subtasks and one task(Asset) with subtasks. put in ready column. each time to add a new task, i open this, duplicate and tweak assignee's . thanks..

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
