### ISSUE TITLE
Close all tasks of this column does not work

### ISSUE THREAD

**Issue by Kolesar** [kanboard/kanboard#2932]
### Expected behaviour
When click on "Close all tasks of this column" confirmation modal dialog should be open

### Actual behaviour
Nothing happens

### Suggestion for solve issue
in file:
``app/Template/board_popover/close_all_tasks_column.php``

change:
```
<?= $this->modal->submitButtons(t('Yes'), 'red') ?>
```

to:
```
<?= $this->modal->submitButtons(array('submitLabel' => t('Yes'), 'color' => 'red')) ?>
```

**Comment by fguillot** [comment]
This is fixed in dev. thks
