### ISSUE TITLE
Hit Enter key in editor validate creation/edition task modal

### ISSUE THREAD

**Issue by Finrod927** [kanboard/kanboard#2933]
### Expected behaviour

When creating or editing a tasks, hitting the Enter key in editor create a new line.

### Actual behaviour

When creating or editing a tasks, hitting the Enter key in editor does not always create a new line, it sometimes validate the modal (like the ctrl+enter shortcut).

### Steps to reproduce

It's not 100% reproductible so I don't have steps to reproduce but it often happens when hitting enter after special characters (non letter/number characters)

### Configuration

- Kanboard version: 1.0.36
- Database type and version: MySQL (don't know the version)
- PHP version: 5.5.9
- OS: Ubuntu 14.04.5
- Browser: Firefox

**Comment by andr-d** [comment]
I can confirm this. If you use the Ctrl-Key for anything in any of the text fields, the next use of Enter is counted as Ctrl-Enter, saving and closing the dialog,  

**Steps tp reproduce:**
* open "Edit Task" dialog
* Click on title, type some text
* Press Control key
* Change to task description. Type some text.
* Press Enter
* Instead inserting of a newline, the dialog closes

**Configuration:**
* Kanboard Version: 1.0.36
* PHP Version: 7.0.11
* PHP SAPI: cgi-fcgi
* OS Version: Linux 2.6.32-642.6.2.el6.x86_64
* database driver: mysql
* database Version: 5.1.73-log
* Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

Same behavior can be seen on Firefox 50.1.0

**Comment by fourier** [comment]
I've experienced it as well, here the comment from one of users:
```Every time I write a comment and hit the enter key to make a line break, my comment gets submitted. The mitigation is to add a couple of white spaces at the end and add a few line break before them. But even then, it still gets submitted sometimes. ```

**Comment by fguillot** [comment]
This is now fixed in version 1.0.37.

Thank you

**Comment by tzeumer** [comment]
I think now there is a problem if I paste something (ctrl + v) into the editor. Afterwards I can't create another break.
