### ISSUE TITLE
Editing Comment Does Not Update Timestamp

### ISSUE THREAD

**Issue by asftAndrew** [kanboard/kanboard#2934]
When editing a comment, the timestamp does not update to the date and time that the edit occurred. This makes it appears that the comment was made months ago when it was just recently updated.

I would expect that the date and time on the comment would be updated, however perhaps this could be an option set in the configuration file as to the behavior when editing comments.

**Comment by levlaz** [comment]
Took a look at the schema, this would involve a DB change because the comments table does not track updated_date, only the `date_creation`. I think it would be useful to show both the created date and the updated date on the comment itself.
