### ISSUE TITLE
Admins can not Import automatic actions between projects not owned

### ISSUE THREAD

**Issue by piltraspn** [kanboard/kanboard#2939]
### Expected behaviour

As administrator one should be able to import automatic actions from one project to another even if the administrator is not the project owner.

### Actual behaviour

Only the project owner can import automatic actions among projects he/she owns. The Administrator role can not do that if he/she doesn't own project.

### Steps to reproduce

1. Try as Administrator to import automatic actions between two projects the Administrator doesn't own.

### Configuration

Application version: 1.0.35
PHP version: 5.6.29
PHP SAPI: cgi-fcgi
OS version: Linux 3.12.18-clouder0
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by fguillot** [comment]
The actual behaviour that you described is the expected one.
