### ISSUE TITLE
Feature request: move the hide/show Backlog option directly into the 

### ISSUE THREAD

**Issue by liar666** [kanboard/kanboard#2941]
Hi,

I'm using the version available online at:
https://framaboard.org/
Since I have not installed the software myself, I don't know if my "problem" is in the software in general or the particular configuration of the online version I'm using.

My feature request is: Instead of hidding the option to hide/show the BackLog column deep in the configuration menus (which makes it almost a definitive choice), why not add a button directly in the  Kaban-board view, so that wew can dynamically show/hide its content?

**Comment by fguillot** [comment]
At the moment, you can show or hide a column directly on the board by clicking on the title.
