### ISSUE TITLE
Feature Request: Click on a task in Kaban-board view results directly in editing the task

### ISSUE THREAD

**Issue by liar666** [kanboard/kanboard#2942]
Hi,

I'm using the version available online at:
https://framaboard.org/
Since I have not installed the software myself, I don't know if my "problem" is in the software in general or the particular configuration of the online version I'm using.

My 2nd feature request is: When in the Kaban-board view, when I click on a task, it opens up a summary view of the task. If I want to modify it, I have to click again (on "edit"). Why not redirect directly to the editing view when users click on a task in the Kaban-board view, in the same amnner as most Calendar WebApps (e.g. GoogleCalendar) do? This would spare *many* clicks to the user...

**Comment by fguillot** [comment]
There is a dropdown menu that allows you to edit the task (ok 2 clicks).

**Comment by fguillot** [comment]
When I click on a task I prefer to see the content, the subtasks, the comments, the links, not editing the task.
