### ISSUE TITLE
Show number of open/closed tasks on "Edit columns" page

### ISSUE THREAD

**Issue by eurodrew555** [kanboard/kanboard#2943]
### Expected behaviour

When you edit a board and go to the "edit columns" page it would be great if it also showed the current number of open/closed tasks for each column.

At present this information is not shown and when you go to delete the column you have no idea if you are deleting tasks or not.

### Actual behaviour

The risk is when you delete a column you may be unknowingly deleting tasks.

### Steps to reproduce

1. Edit Board
2. Edit Columns

The table showing the columns should also show the number of open/closed tasks.

### Configuration

Application version: master
PHP version: 5.6.29
PHP SAPI: fpm-fcgi
OS version: Linux 4.8.6-x86_64-linode78
Database driver: sqlite
Database version: 3.7.17
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by fguillot** [comment]
This is now available in the development branch.

**Comment by fguillot** [comment]
Available in v1.0.39

**Comment by radimoto** [comment]
This is great! Thank you.
