### ISSUE TITLE
Calendar view is to big

### ISSUE THREAD

**Issue by stuxxn** [kanboard/kanboard#2944]
### Expected behaviour

Show the calendar view on a single screen with no need to scroll

### Actual behaviour

Currently the calendar view is to big to show in on a single screen. So i have to scroll down.
Eg. the month view shows only the first three weeks: 1 - 21
### Steps to reproduce

Click on the calendar view on any project

### Configuration

    Application version: master
    PHP version: 7.0.13-0ubuntu0.16.04.1
    PHP SAPI: fpm-fcgi
    OS version: Linux 4.4.0-57-generic
    Database driver: mysql
    Database version: 5.6.33-0ubuntu0.14.04.1
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by fguillot** [comment]
Tickets related to the calendar should be posted to the calendar plugin bug tracker: https://github.com/kanboard/plugin-calendar/issues

Thank you
