### ISSUE TITLE
JSON RPC: Start date, task age, days in column 

### ISSUE THREAD

**Issue by Hofi67** [kanboard/kanboard#2945]
Hi,

I am importing and then syncing tasks from an other system (here crm server / sales pipeline).
That works pretty well. But I can not handle the past:

I have to set "start date" of a task to the past ... eg. 2016-12-1.
Same thing with "task age" and "days in column" ... e.g. visualize how long a task is in sales stage (column) "Quote" even right after my sync script execution.

I know to set due dates. That works well.

Any ideas how i can arrange this via json rpc?

Thank you again
Frank

**Comment by fguillot** [comment]
The start date is now available via the API.
