### ISSUE TITLE
Shift+Enter on Mac and probably Linux unpredictably saves comment when we want a New Line

### ISSUE THREAD

**Issue by chamunks** [kanboard/kanboard#2948]
### Expected behaviour
Shift+Enter to have some consistency between text entry boxes.

Tell us what should happen
We would love the ability to determine if the app should create a new line or submit a comment when pressing **Enter**

### Actual behaviour
When we press Shift+Enter some of the time it creates a new line others it submits your comment and sometimes it does both at the same time.

Tell us what happens instead
![image](https://cloud.githubusercontent.com/assets/1068374/21966533/1aac4f42-db43-11e6-8635-4366ca4c38f8.png)
This is the view that currently, both submit on Shift+Enter and also tries to create a new line.

### Steps to reproduce

1.
2.
3.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:
Mostly default configuration.

- Kanboard version:
Latest stable from Docker
- Database type and version:
SQLLite
- PHP version:
Latest stable from Docker
- OS:
Latest stable from Docker
- Browser:
Chrome & Firefox ( presumably )

**Comment by fguillot** [comment]
Which version of Kanboard do you have? (the version number on the settings page not the Docker tag)

**Comment by chamunks** [comment]
Application version: 1.0.36
PHP version: 7.0.9
PHP SAPI: fpm-fcgi
OS version: Linux 4.4.0-59-generic
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by fguillot** [comment]
Can you try with the version 1.0.37?

**Comment by chamunks** [comment]
@fguillot seems fixed tyvm!
