### ISSUE TITLE
can't pop window while editing a task

### ISSUE THREAD

**Issue by lanrenwo** [kanboard/kanboard#2949]
### Expected behaviour
Click avatar letter, Edit the task.

### Actual behaviour
![click](https://cloud.githubusercontent.com/assets/3632406/21968679/2a2df738-dbd2-11e6-9083-87c6fc030a17.png)

### Configuration
- Kanboard version: 1.0.37
- Database type and version: Sqlite
- PHP version: PHP 5.5.8
- OS: Windows
- Browser: Chrome 55.0.2883.87 m / Firefox 50.1.0

Thank you!

**Comment by fguillot** [comment]
This is now fixed in v1.0.38
