### ISSUE TITLE
Request: Static migration tools

### ISSUE THREAD

**Issue by gnubyte** [kanboard/kanboard#2951]
NOTE: This is meant to be a very brief request of the author and other contributors. I would like to support this project by writing python plugins, but it is hard to support a moving target.

### Expected behaviour
I would like to formally make a request to keep the import/export of kanboard data a static function and static format. This would be a continuity that is familiar in most application environments between versions.

Tell us what should happen
Using Kanboard's import/export tasks should work between separate versions

### Actual behaviour
Moving from one month's version to the next months, and going live in production with a full kanboard system, I found that I have to manually cut or upgrade the Kanboard.

Tell us what happens instead
The format has changed, meaning I now have to upgrade a previous installation or manually chop the data

### Steps to reproduce

1. Have October/December releases of Kanboard from 2016
2. Go to project thread
3. Navigate to the menu
4. Select export
5. Select export tasks
6. export as CSV
7. Move to new Kanboard
8. See steps 2 & 3
9. Select Import
10. Attempt to upload the CSV

### Configuration
SQlite, default installation on original host and new host.
Moved data file in config.php to a new directory and gave apache r/w access.

**Comment by gnubyte** [comment]
I will try to write a porting tool in python later this week and see if I can make something for specific versions. This will create a temporary fix in the meantime.

**Comment by khampf** [comment]
I just tried exporting a board as CSV from one instance of kanboard 1.0.37 and importing the tasks into another and I get errors that nothing got imported. I look at the CSV and it does not store ISO-dates but the restrictions are ISO-dates are to be used. The exported CSV looks nothing like the template you can download when trying to import. So for me exports/imports using CSV are broken and I will have to look into using data from MySQL/SQLite directly it seems :(

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
