### ISSUE TITLE
Move task changes to duplicate task when selecting another project

### ISSUE THREAD

**Issue by jitoot** [kanboard/kanboard#2957]
Hi there, I'm trying to move a task to another project, but when I select a different project in the popup window, it changes to duplicate task instead.

### Steps to reproduce

1. Click on a task
2. Click on Move to another project
3. In the Project dropdown, select another project. The action changes to Duplicate Task instead

### Configuration

Application version: 1.0.37
PHP version: 5.5.30
PHP SAPI: apache2handler
OS version: Windows NT 6.1
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by fguillot** [comment]
This is definitively a regression, this is now fixed in the development branch. The next release is coming at the end the week. Thanks!

**Comment by ngosang** [comment]
I'm having the same problem.

**Comment by fguillot** [comment]
This is now fixed in v1.0.38
