### ISSUE TITLE
TaskCompletionDateFilter don't work

### ISSUE THREAD

**Issue by pmcfernandes** [kanboard/kanboard#2958]
### Actual behaviour

Completed filter don't work (app\Filter\TaskCompletionDateFilter.php)
### Steps to reproduce

On search put text like completed: >= 2017-01-01 and nothing happens

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: Master
- Database type and version: mysql
- PHP version: 5.6
- OS: WIndows
- Browser: Chrome

**Comment by markjszy** [comment]
I was able to reproduce this in dev. I think it's just due to an absent configuration in the FilterProvider. Submitting PR shortly.

**Comment by fguillot** [comment]
This is fixed by PR #2970
