### ISSUE TITLE
Json-RPC getTaskTags

### ISSUE THREAD

**Issue by mtruijen** [kanboard/kanboard#2959]
### Expected behaviour

GetTaskTags should return a dictionary of tags regardless of how many tags have been assigned (0..n).

### Actual behaviour

GetTaskTags appears to return an empty list if no tags have been assigned and a dictionary when one or more tags have been assigned.

### Steps to reproduce

1. Create two tasks
2. Assign one or more tags to the first task
3. Do not assign any tags to the second task
4. View the results returned by the GetTaskTags routine.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.36
PHP version: 5.3.3
PHP SAPI: apache2handler
OS version: Linux 2.6.32-642.11.1.el6.x86_64
Database driver: sqlite
Database version: 3.6.20
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by fguillot** [comment]
This is now fixed in master, next release is coming at the end of the week.

**Comment by fguillot** [comment]
This is now available in v1.0.38
