### ISSUE TITLE
Error while Save

### ISSUE THREAD

**Issue by rakesh1084** [kanboard/kanboard#2960]
### Expected behaviour
- Allow to Save the Task with the Start Date and Due Date selected.
### Actual behaviour
- Error came while Clicking on the Save button in the Create New Task window
![save_error_jan_19_](https://cloud.githubusercontent.com/assets/20356619/22099728/84ed2612-de52-11e6-8275-f04153509fbd.png)

### Steps to reproduce
1.Goto any of the board.
2.Click on the Create New Task
3.Change the Start Date and Due date either using calendar control or manually.

### Configuration
Copy and paste the configuration section from the Kanboard settings page or fill these fields:
    Application version: 1.0.36
    PHP version: 5.3.28
    PHP SAPI: cgi-fcgi
    OS version: Windows NT 6.2
    Database driver: mysql
    Database version: 5.6.31
    Browser: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by rakesh1084** [comment]
Can you please help me on this....?

**Comment by fguillot** [comment]
Can you try the version 1.0.37 and tell me if the problem still there?

**Comment by j0xyz** [comment]
Is there any bug fix available. I have the same problem on version 1.0.37.

**Comment by fguillot** [comment]
It should be fixed in v1.0.38, let me know if there is any problem about that.

**Comment by j0xyz** [comment]
Thx

**Comment by rakesh1084** [comment]
This Issue is fixed.
Thanks  :-) 👍
