### ISSUE TITLE
Closing task from dropdown on board view - changed behaviour in 1.0.37?

### ISSUE THREAD

**Issue by mgrabow1** [kanboard/kanboard#2961]
### Expected behaviour

Task is closed, green info on the board, KB stays on board view.
(it worked just like that in 1.0.36)

### Actual behaviour

Task is closed, but the view switched to task edit view.
(new in 1.0.37 after modal dialog handling change)

### Configuration

- Kanboard version: 1.0.37
- Browser: Chrome and Firefox.

**Comment by fguillot** [comment]
This is a regression due to some refactoring, this is now fixed in the development branch. Thanks!

**Comment by fguillot** [comment]
This is now fixed in v1.0.38
