### ISSUE TITLE
Mentioning of the LDAP accounts is not working

### ISSUE THREAD

**Issue by fourier** [kanboard/kanboard#2962]
### Expected behaviour

When I type @ and start to type someone's name/username who is remote (LDAP) account, the completion of the name and mentioning should be working 

### Actual behaviour

Mentioning of LDAP accounts is not working.

### Steps to reproduce

1. Have a board LDAP users
2. Try to mention someone in the comments
3.

### Configuration

    Application version: 1.0.36
    PHP version: 5.6.29-0+deb8u1
    PHP SAPI: apache2handler
    OS version: Linux 3.16.0-4-amd64
    Database driver: sqlite
    Database version: 3.8.7.1
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by fguillot** [comment]
I'm not able to reproduce your issue. Try the version 1.0.38 and please provide more details to be able to troubleshoot something.

**Comment by fourier** [comment]
I'll try to install 1.0.38 next week and test. Maybe the reason is what we have ~200 users registered, and only first 10-15 are not LDAP?

**Comment by fguillot** [comment]
Did you try with a more recent version of Kanboard? LDAP should not make any difference here, the system read the users from the database.

**Comment by fourier** [comment]
Hi,

Still doesn't work in  1.0.39

**Comment by fguillot** [comment]
You didn't give me any details to be able to reproduce the issue. This is working for me with LDAP.

**Comment by fourier** [comment]
How can I test and provide any details for you? It looks like now it doesn't work with normal accounts as well. When I type @ no popup window shown.
I must mention I have rather huge amount of users ~200 people.

**Comment by rautamiekka** [comment]
@fourier You're still not on latest Kanboard, which is 1.0.40.

**Comment by fguillot** [comment]
I have never been able to reproduce this issue after all this time. You seems to be the only one to have this problem. Unfortunately, you will have to investigate by yourself and potentially submit a patch.
