### ISSUE TITLE
Color of weekend days in gantt view and calendar

### ISSUE THREAD

**Issue by chthal** [kanboard/kanboard#2964]
Currently the weekends in gantt view are barely visible (maybe due to our crappy monitors). The contrast between background-color of the gantt-view and the days on weekend is too minimal to be seen easily. The same is with saturday and sunday in the calendar.

If the definition of div.ganttview-grid-row-cell.ganttview-weekend would be:
background-color: #f8f8f8;

It could be seen even here ;-)

**Comment by Busfreak** [comment]
You can create your own CSS using this example plugin:
https://github.com/kanboard/plugin-example-css

**Comment by chthal** [comment]
Oh, thank you, I didn't know that.  But anyhow, for me the standard seems to be disadvantageous. But feel free to close this issue.
