### ISSUE TITLE
Swimlane, category or new project for grouping dependent projects

### ISSUE THREAD

**Issue by masoodmx** [kanboard/kanboard#2971]
We have just recently started to use Kanboard, but still not sure how to apply our projects in the Kanboard system. We have a couple of major software projects contains sub-projects such as Delphi components, Lazarus components, Windows version, Linux version, Innosetup maker, documentation, etc.
We would like to know how to initially create the structure of the projects/swimlanes/categories in the Kanboard to start using it.
Could you elaborate the usage of and difference between swimlane and categories in Kanboard? 
How should we fit the mentioned sub-projects in project, swimlane or category?

**Comment by fguillot** [comment]
You could find these answers in the documentation: https://kanboard.net/documentation. This is up to you to define how you structure your projects into Kanboard.

**Comment by BigGitWorld** [comment]
I think you can not define multi level projects (or sub projects) by kanboard.
you can only use swimlanes that provide ONE level below your main project.
