### ISSUE TITLE
Feature request: export of found tasks

### ISSUE THREAD

**Issue by fourier** [kanboard/kanboard#2972]
Currently if one searches for tasks using tags or any other criteria, it is possible to switch to list view and copy-paste tasks to the Excel.
But the software only shows 30 tasks per page.
It would be nice to have a possibility to show all tasks found in the list view or export them in CSV format.

**Comment by Deka-chan** [comment]
Hi, it will be great to have export button on search page (controller=SearchController&action=index&search=) like it realized in board view menu button.
I'm currently trying to do that. But i'm new in php and debuging it :) So it will take a time. But maybe it can be done with a couple of strings.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
