### ISSUE TITLE
Priority values are not included in task exports

### ISSUE THREAD

**Issue by woosting** [kanboard/kanboard#2973]
### Actual behavior

The **priority** "column" does _not_ end-up in the csv file when exporting tasks.

### Expected behavior

Have priority included in the export (as stated by the Kanboard's helptext at task export page: `This report contains all tasks information for the given date range.`).

### Steps to reproduce
1. make a task having a priority
2. export the task

### Nota bene
Closely related to issue [#2974](https://github.com/kanboard/kanboard/issues/2974)
(Filed individually to be able to process them separately if deemed necessary by @fguillot).

**Comment by fguillot** [comment]
This is now available in the development branch.
