### ISSUE TITLE
Feature request: Total number of score in this column across all swimlanes (like with tasks)

### ISSUE THREAD

**Issue by devBartek** [kanboard/kanboard#2975]
### Actual behaviour

In board view on top we have total number of tasks in column across all swimlanes. Label: "Total number of tasks in this column across all swimlanes"

### Expected behaviour

In board view on top we have sum of score in column across all swimlanes. Example: "Total number of score in this column across all swimlanes"

### Configuration
- Kanboard version: 1.0.37
- Database type and version: sqlite 3.8.10.2
- PHP version: 5.6.19
- OS: Windows NT 6.1
- Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by fguillot** [comment]
This is now implemented by PR #3068

**Comment by fguillot** [comment]
This is now available in Kanboard 1.0.40
