### ISSUE TITLE
File uploads twice when pressing "cancel"

### ISSUE THREAD

**Issue by jansch2015** [kanboard/kanboard#2976]
### Actual behaviour

When I choose a file for upload, then decide not to upload it, press cancel and choose another file, both files are being uploaded.
-> This does not happen when I refresh the page after pressing "cancel"

### Expected behaviour

When Canceling the upload, the file should not be uploaded :)

### Steps to reproduce

1. Enter a task
2. Press "Attach a document"
3. Choose any document
4. Press "cancel"
...
Then I choose to upload another document... Do not refresh the page!
...
5. Press "Attach a document" again
6. Choose any document
7. Press "Upload files"
8. Press "View uploaded files"
-> Both files are uploaded now, even though I canceled the first one.

### Configuration

I don't think this matters in this case. The uploading queue is not cleared correctly when pressing "cancel".

**Comment by fguillot** [comment]
It should be fixed in v1.0.38, let me know if there is any problem with that.

**Comment by jansch2015** [comment]
Fixed, thank you very much! :)
