### ISSUE TITLE
Adding a comment does not update change modified date on task

### ISSUE THREAD

**Issue by razron** [kanboard/kanboard#2978]
### Actual behavior

When adding a comment the task modification date does not change.

### Expected behavior

Adding a comment updates the modification date on a task

### Steps to reproduce

Add a comment to a task and save it.
Click on task to view last modified date.

### Configuration

    Application version: 1.0.34
    PHP version: 5.6.25
    PHP SAPI: fpm-fcgi
    OS version: Linux 3.10.0-514.el7.x86_64
    Database driver: sqlite
    Database version: 3.7.17
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by fguillot** [comment]
You should try the latest version of Kanboard (1.0.38). This PR #2950 adds the support for modification date in comments.

**Comment by razron** [comment]
So upgraded to 1.0.38. Took a task that showed last  modified in the web interface of 2017/01/09 11:14 and added a comment. It still shows 2017/01/09 11:14 as the modified time.

Since this had schema changes I manually ran ./cli  db:migrate and that showed:

Current version: 120
Last version: 120

From Settings:
    Application version: 1.0.38
    PHP version: 5.6.25
    PHP SAPI: fpm-fcgi
    OS version: Linux 3.10.0-514.el7.x86_64
    Database driver: mysql
    Database version: 10.1.19-MariaDB
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by fguillot** [comment]
All existing comments will have the same creation and modification date after the migration because the modification date field was not present before. If you modify a comment now, the modification will be updated.

**Comment by razron** [comment]
I created a new comment on an existing task after the upgrade. The modification time for the task didn't change. Or did PR #2950  just add modification date to tasks. My request originally was to have adding a comment to a task to update the modification on the task.

**Comment by fguillot** [comment]
Ah sorry, I misread your ticket. Can you explain why you need such feature?

**Comment by razron** [comment]
We were trying to find a way to show open tasks that hadn't been updated in anyway in more than a week.

i.e. a filter : status:open   modified:<-1week

But most of the users in our environment add comments to the task  for simple status updates. Instead of say creating subtasks or updating the task description.

**Comment by kvj** [comment]
I'd like to work on it.

Should we update `date_modification` also on comment/link/document/sub-task create/update/remove?

**Comment by razron** [comment]
To me it makes logical sense, all of these are modifications or updates 
to the task.

The comments were what we found was not updating the modification date 
when we tried to find tasks that no one had updated or work on for 2 
weeks.

All of these would be nice.

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
