### ISSUE TITLE
Estimated time board-filter-option unavailable

### ISSUE THREAD

**Issue by woosting** [kanboard/kanboard#2979]
### Actual behaviour

Filter option is simply not available (or not described in [the documentation](https://kanboard.net/documentation/search)).

### Expected behaviour

Having the option to filter the tasks based on a time estimate threshold.

*Use case:* one has an hour time to pick up a task, so he/she only wants to be presented with tasks equal or shorter than that hour.

### Workaround

Assign specific discrete estimation _labels_ (e.g. hour / evening / day), and make custom filters:
1. tag:hour
2. tag:hour tag:evening
3. tag:hour tag:evening tag:weekend

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
