### ISSUE TITLE
JSONRPC: The lists of Categories, Subtasks and Project Users need Manager rigths

### ISSUE THREAD

**Issue by andresth** [kanboard/kanboard#2982]
### Actual behaviour
The following functions return error 403 when called with a user account that is only a project member and not a manager
* getAllCategories
* getCategory
* getProjectUsers
* getAssignableUsers
* getProjectUserRole
* getDefaultSwimlane
* getActiveSwimlanes
* getAllSwimlanes
* getSwimlane
* getSwimlaneById
* getSwimlaneByName

This relates to #2776

### Expected behaviour
The functions should return the expected data even if the requesting user is only a project member.

### Steps to reproduce

Call any of this functions for a project where your user has the role member.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.37
- Database type and version: mysql 5.1.73-log
- PHP version: 7.0.8
- OS: Linux 2.6.32-642.6.2.el6.x86_64
- Browser:

**Comment by fguillot** [comment]
It should be fixed in v1.0.38, let me know if I forgot something.
