### ISSUE TITLE
Png are missing after Update (1.0.22 to 1.0.37)

### ISSUE THREAD

**Issue by vancleeff** [kanboard/kanboard#2983]
Hi everyone,
 
After updating Kanboard (from 1.0.22 to 1.0.37), all png images in tickets are missing. All jpeg are fine.
Any ideas?

Thanks in advance.

### Configuration

Software Version : 1.0.37
PHP Version : 5.4.45-0+deb7u3
PHP SAPI : apache2handler
OS : Linux 2.6.32-27-pve
DB type : mysql
DB Version : 5.5.49-0+deb7u1-log
Browsers : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

### Image

![2017-01-27 15_41_52-comptoirs d orta 4484 - image de fond sur du header home home](https://cloud.githubusercontent.com/assets/23222514/22374841/1827f9a6-e4a8-11e6-8a42-804967efb728.png)

**Comment by fguillot** [comment]
- Do you have any errors in log files (KB logs and web server logs)?
- Is the files are present in the data folder?
