### ISSUE TITLE
Improvement : Add a My Gantts for all tasks

### ISSUE THREAD

**Issue by melioratif** [kanboard/kanboard#2988]
Hi dears, 

I love Kanboard (that I use for my personal projects) but I was surprises not founding the following:
A gantt's graph that show every tasks and subtasks not only for one project but for all projects.

Should be named a 'My Gantt' under my notifications ( on page ?controller=DashboardController&action=show).

thanks.

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
