### ISSUE TITLE
doc/tr_TR/ files

### ISSUE THREAD

**Issue by desendijital** [kanboard/kanboard#2989]
https://github.com/desendijital/kanboard/tree/master/doc/tr_TR
created

### Actual behaviour

Tell us what happens

### Expected behaviour

Tell us what should actually happen

### Steps to reproduce

Please supply step-by-step instructions so that anyone with the same environment can reproduce the issue. Whenever you offer a description, imagine
yourself in the shoes of someone who has never encountered this problem before and would like to know exactly how to observe it under a given set of conditions.
Here is an example:

1. Log in to the application as the administrative user
2. Click on button X, then on the modal dialog that appears, click Y
3. Wait for 3 seconds, and note the appearance of an unexpected message

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.35 (now running - master.ba544882dea5e5bf18ca8cae1ee6c479d3ab0f76)
- Database type and version:  mysql -  mysql
- PHP version: 7.0.15
- OS: Linux 2.6.32-673.26.1.lve1.4.18.el6.x86_64
- Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by fguillot** [comment]
Thank you, I merged manually your translations.

If you have some difficulties to create a pull-request, there is guide here: https://help.github.com/articles/creating-a-pull-request/
