### ISSUE TITLE
Turkish translate update

### ISSUE THREAD

**Issue by desendijital** [kanboard/kanboard#2990]
app/Locale/tr_TR/translations.php

https://github.com/desendijital/kanboard/commit/27ff8ad01c8a03f53b91567220c2bed9b23742d7
https://github.com/desendijital/kanboard/commit/27ff8ad01c8a03f53b91567220c2bed9b23742d7#diff-c01db63f448c5d4a6a72711de986954a

**Please, do not create duplicate issues**

### Actual behaviour

Tell us what happens

### Expected behaviour

Tell us what should actually happen

### Steps to reproduce

Please supply step-by-step instructions so that anyone with the same environment can reproduce the issue. Whenever you offer a description, imagine
yourself in the shoes of someone who has never encountered this problem before and would like to know exactly how to observe it under a given set of conditions.
Here is an example:

1. Log in to the application as the administrative user
2. Click on button X, then on the modal dialog that appears, click Y
3. Wait for 3 seconds, and note the appearance of an unexpected message

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment]
Your translations have been merged manually into the development branch of Kanboard.

- When you send new translations, make sure that you use the latest version of Kanboard.
- Plugins translations are stored into the plugin code bases: https://github.com/kanboard (projects that starts with plugin-*)

Thank you!
