### ISSUE TITLE
Notification 

### ISSUE THREAD

**Issue by Kolesar** [kanboard/kanboard#2992]
### Actual behaviour

Notification "bell" is always black

### Expected behaviour

When exits notification notification "bell" should be blue

I have found that override does not work properly. Please see attached file 

![image](https://cloud.githubusercontent.com/assets/6159988/22414798/820bdefa-e6d3-11e6-9a7a-e73f9eb4a8db.png)

**Comment by fguillot** [comment]
It should be fixed in v1.0.39
