### ISSUE TITLE
Assignee "Me" link in "Add a sub-task" does not work

### ISSUE THREAD

**Issue by jsteel44** [kanboard/kanboard#2994]
### Actual behaviour

Click "Me" in "Add a sub-task" and it remains "Unassigned". The "Me" link in "New Task" works fine.

### Expected behaviour

It should change the drop-down to select your user.

### Steps to reproduce

Create a new task.
Add a sub-task and click "Me"; it says on Unassigned.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version:  1.0.38
- Database type and version: 5.5.52-MariaDB
- PHP version: 5.4.16
- OS: CentOS 7
- Browser: Any

**Comment by kvj** [comment]
Works for me in 1.0.39, Firefox 51

**Comment by jsteel44** [comment]
Just tried 1.0.39 and Firefox 51.0.1 and it still doesn't work for me. It's odd that it works in the task, just not sub task.

**Comment by fguillot** [comment]
I'm really able to reproduce your problem. Ca you provide more details? (potential errors in browser console, screenshots, browser version, something to troubleshoot, etc..)

**Comment by jsteel44** [comment]
I see no errors/warnings in my browser using Firefox 51.0.1. Comparing the code between the task and sub-task "Me" links, I can get the sub-task "Me" link working if I change user_id to owner_id (3 occurrences in app/Helper/SubtaskHelper.php). Now it works fine with those changes. Does that shed any light on the issue?

**Comment by fguillot** [comment]
You should try again with the latest version of KB.

**Comment by jsteel44** [comment]
@fguillot just tried 1.0.48 and I have the same issue. What info do you need from me to help debug this further?
