### ISSUE TITLE
Option to show the task name in the subject of emails

### ISSUE THREAD

**Issue by jsteel44** [kanboard/kanboard#2995]
Currently the subject of all emails refer to tasks only by "task #". It would be nice to have the option to display the task name instead of/as well as the task # in the subject of emails.

**Comment by HenLab** [comment]
Any news on this?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
