### ISSUE TITLE
Cumulative Flow Diagram

### ISSUE THREAD

**Issue by mauriziodidomenico** [kanboard/kanboard#2997]
Hi,

The sequence of the data series in the diagram should correspond to the columns (Backlog, Ready, Ongoing, Done). Otherwise it is not possible to recognize the cycle time and the work, directly in the diagramm. I know there is a dedicated grafical possibility.

This is how it looks now.
![cfd](https://cloud.githubusercontent.com/assets/16655789/22428223/87fe3aaa-e706-11e6-829b-1e968ddbe84c.PNG)

Below, how it should look like.
![cfd_leffington](https://cloud.githubusercontent.com/assets/16655789/22428284/bdf44820-e706-11e6-8624-08eaee6ab16b.PNG)
Source: Leffingwell (http://www.scaledagileframework.com/team-kanban/)

**Comment by fguillot** [comment]
This issue should be fixed in Kanboard 1.0.39.

C3js, the library that generate the chart was changing the order of the stack.

If that doesn't work as expected don't hesitate to reopen this ticket.

Thank you
