### ISSUE TITLE
Cmd/Ctrl+Enter removes CSS when creating task

### ISSUE THREAD

**Issue by garettmd** [kanboard/kanboard#2998]
### Actual behaviour

When creating a task, with the "create another task" option selected, if you use the Cmd+Enter (or Ctrl+Enter on Windows) hotkey, the new task form comes back up, but all the styling is gone, as if the CSS didn't load.

### Expected behaviour

The new task form should just come back up as normal, with styling

### Steps to reproduce

1. On a project page, click the plus icon on any column.
2. On the new task form, enter a task name, then check the "create another task" box.
3. On Mac, hit Cmd+Enter on your keyboard, or Ctrl+Enter on Windows.

### Configuration

Application version: 1.0.37
PHP version: 5.5.9-1ubuntu4.20
PHP SAPI: apache2handler
OS version: Linux 3.13.0-107-generic
Database driver: mysql
Database version: 5.5.54-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by garettmd** [comment]
Here's a screenshot of what the form looks like with no styling:

<img width="1360" alt="screenshot at jan 30 15-38-48" src="https://cloud.githubusercontent.com/assets/7316933/22440612/472f1fd4-e702-11e6-87c6-7ac21c8e03f1.png">

as opposed to how it should look:

![image](https://cloud.githubusercontent.com/assets/7316933/22440660/7ca16b36-e702-11e6-8a85-4e04568e23fc.png)

**Comment by fguillot** [comment]
Can you try the version 1.0.38 of Kanboard?

**Comment by garettmd** [comment]
Yep, I'll give that a try

**Comment by garettmd** [comment]
Ok, just confirmed that it's fixed in 1.0.38.

Thanks!
