### ISSUE TITLE
Snycing docker tags with Digest, please

### ISSUE THREAD

**Issue by zorner** [kanboard/kanboard#2999]
**Please, do not create duplicate issues**

### Actual behaviour

When pulling down a docker image, the 'stable' images digest does not match what looks to be the same image, 1.0.38. Below is the put from a script that runs the next two lines:

$ sudo docker pull kanboard/kanboard:stable
$ sudo docker pull kanboard/kanboard:v1.0.38 

stable: Pulling from kanboard/kanboard                                                                                                               
Digest: sha256:2d51455ef11e97a91a5b74b828003616b490b8bbf0d68ba501844f60be80f409                                                                      
Status: Image is up to date for kanboard/kanboard:stable                                                                                            
v1.0.38: Pulling from kanboard/kanboard                                                                                                              
e110a4a17941: Already exists                                                                                                                         
fac5265555a6: Already exists                                                                                                                         
5a8186ad8785: Already exists                                                                                                                         
04d7cedece00: Already exists                                                                                                                         
5811355619f8: Already exists                                                                                                                         
0f2bd2761cbc: Already exists                                                                                                                         
66b1c76f691d: Already exists                                                                                                                         
296d3c7c87e1: Already exists                                                                                                                         
3b92d7d23f22: Already exists                                                                                                                         
a5019007fd8a: Already exists                                                                                                                         
e55ba8f948eb: Pull complete                                                                                                                          
7310ba560a1c: Pull complete                                                                                                                          
3e6761c3e516: Pull complete                                                                                                                          
70cf05d1f7f8: Pull complete                                                                                                                          
c38a55f797e0: Pull complete                                                                                                                          
4ac29588fadc: Pull complete                                                                                                                          
68669accbf0c: Pull complete                                                                                                                          
Digest: sha256:3a1ca36c819abdd62ea7f8f4353a2ad2d5e76c21d2fd32292496abf62757f840                                                                      
Status: Downloaded newer image for kanboard/kanboard:v1.0.38                                                                                         

### Expected behaviour

Simlar to this where the digest match:
stable-alpine: Pulling from library/nginx                                                                                                            
Digest: sha256:ce50816e7216a66ff1e0d99e7d74891c4019952c9e38c690b3c5407f7af57555                                                                      
Status: Image is up to date for nginx:stable-alpine                                                                                                  
1.10.2-alpine: Pulling from library/nginx                                                                                                            
Digest: sha256:ce50816e7216a66ff1e0d99e7d74891c4019952c9e38c690b3c5407f7af57555                                                                      
Status: Image is up to date for nginx:1.10.2-alpine                                                                                                  

### Steps to reproduce

$ sudo docker pull kanboard/kanboard:stable
$ sudo docker pull kanboard/kanboard:v1.0.38 

### Configuration

N/A

**Comment by fguillot** [comment]
The docker image tagged as v1.0.38 is built automatically from this repository and the stable tag is build manually from the repo https://github.com/kanboard/docker

I will try to improve that for the next release.

**Comment by fguillot** [comment]
In the upcoming v1.1.1, the tag stable will be deprecated and only tagged versions will be available.
