### ISSUE TITLE
Version number not in code for docker tag 1.0.37 and 1.0.38

### ISSUE THREAD

**Issue by zorner** [kanboard/kanboard#3000]
**Please, do not create duplicate issues**

### Actual behaviour

No version number - docker tag 1.0.37 and 1.0.38
![image](https://cloud.githubusercontent.com/assets/5413793/22452090/c63f7122-e741-11e6-9171-5e50e89808e6.png)

### Expected behaviour

The actual version should be reported

### Steps to reproduce

Spin up the docker image
Goto setting
Look at Application version:

### Configuration

N/A

**Comment by fguillot** [comment]
As of now, the Docker image contains the version number or the commit hash if using latest docker tag. Will be available after releasing v1.1.1.
