### ISSUE TITLE
"Error: SQLSTATE[HY000] [14] unable to open database file" at just installed

### ISSUE THREAD

**Issue by w1ld** [kanboard/kanboard#3001]
Hello. Thank you for the great tool!
How can I fix this error? 

### Actual behaviour

Error at openning:

> Internal Error: SQLSTATE[HY000] [14] unable to open database file

### Expected behaviour

Log in page as successful loading.

### Steps to reproduce

1. I follow steps described at https://kanboard.net/documentation/windows-iis-installation . Installation at an empty directory. Data dir is empty, no 'db.sqlite' file.
2. Open in browser 'localhost/kanboard'
3. The error

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.38  
- Database type and version: 
- PHP version: 

```
> php --version
PHP 7.0.9 (cli) (built: Jul 20 2016 10:47:41) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```
![screenclip](https://cloud.githubusercontent.com/assets/3657998/22460158/ba0e1250-e7b4-11e6-93b2-c027ff3546bf.png)

- OS:
OS Name:                   Windows 10 Pro (Registered Trademark)
OS Version:                10.0.14393 N/A Build 14393
- Browser: Chromium Version 56.0.2921.0 (64-bit)

**Comment by fguillot** [comment]
This is probably a permission problem on the data folder. Can you check that the data folder is writeable by the IIS user?

**Comment by w1ld** [comment]
@fguillot It doesn't seem so. I give it: 

```
icacls 'kanboard' /grant IIS_IUSRS:RX /T
icacls 'kanboard' /grant IUSR:RX /T
icacls 'kanboard/data' /grant IUSR:F /T
```

And I've installed 1.0.35 with my data. Working. I'm going to check it again

**Comment by w1ld** [comment]
The same bug in the new version, 1.0.39. I just extract files to a folder, make the access as above and run the site. And it gets the error as in subj. But my current app, 1.0.35 works great. No idea why so. 
PHP updated to 7.1.1, db version: 3.15.1, PHP SAPI: cgi-fcgi, OS: Windows NT 10.0

**Comment by w1ld** [comment]
Solved by enabling php extension php_ldap.dll. So make sure all requirements as per https://kanboard.net/documentation/windows-iis-installation fulfilled. Also ensured that kanboard/data/db.sqlite file has all permissions.
