### ISSUE TITLE
The User return to the previous role after changed by admin

### ISSUE THREAD

**Issue by oandreazza** [kanboard/kanboard#3002]
### Actual behaviour

As a Admin I created some users with User role. After that I needed change some users to Manager Role. The system said me that was all right. But when the user accessed the system, automatically the role came back to previous role. 

### Expected behaviour

Keep the new role of the user.

### Steps to reproduce

1. Log in to the application as the administrative user
2. Create a new user with User role
3. Edit the previous user and change the role to Manager.
4. Log off
5. Log in with the new user
6. Log off
7. Log  in with Admin user
8. Go to user list
9. Check the role of the user

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Application version: 1.0.36
- PHP version: 5.5.30
- PHP SAPI: fpm-fcgi
- OS version: Linux 2.6.32-431.29.2.el6.x86_64
- Database driver: postgres
- Database version: 9.3.9
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by Busfreak** [comment]
I was not able to reproduce your issue (with MySQL).
You should try again with the latest version of Kanboard (1.0.38).

**Comment by fguillot** [comment]
Are you using LDAP or any kind of external authentication?

**Comment by oandreazza** [comment]
Yes, using ldap authentication

**Comment by fguillot** [comment]
Depending of your configuration it could be the expected behaviour. Each time, the user login his LDAP profile is synchronized to Kanboard database.

Did you enable LDAP group synchronization?

**Comment by psy-q** [comment]
We have the same issue, and we do use LDAP group synchronization. Maybe Kanboard could keep track of whether a user that originally came from LDAP has been changed manually, and then ignore certain attributes (such as role)?

**Comment by fguillot** [comment]
If you have enabled LDAP group sync, the source of truth is LDAP, each time the user will login, the data that come from LDAP will override the data in the local database.
