### ISSUE TITLE
Gant chart performance with large amount of items

### ISSUE THREAD

**Issue by Zimeon-** [kanboard/kanboard#3003]
### Actual behaviour

Gant chart performance slow when there are over 100 tasks. It seems that the browser spends a lot of time rendering the chart.

### Expected behaviour

A suggestion could be to remove by default those tasks that do not have a start or end date to reduce the amount of items displayed in the gant chart.

### Steps to reproduce

~100 tasks with over half having a start and due date with the total timespan of one year.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.37
- Database type and version: PostgreSQL 9.3
- PHP version: 5.6.x
- OS: CentOS 7
- Browser: Vivaldi/Firefox/Chrome

**Comment by fguillot** [comment]
Gantt chart issues should be moved to this bug tracker: https://github.com/kanboard/plugin-gantt/issues
