### ISSUE TITLE
LDAP authentication against AD does not work when using SSL

### ISSUE THREAD

**Issue by psy-q** [kanboard/kanboard#3005]
I've configured Kanboard to auth against our AD server, but it can't bind, neither in user nor in proxy mode.

### Actual behaviour

The debug.log shows:

    LDAP authentication failure for "kanboard-svc"

Kanboard says "Bad username or password".

### Expected behaviour

Users should be able to authenticate in Kanboard using their LDAP usernames.

### Steps to reproduce

1. Have a Microsoft AD setup somewhere
2. Set config file as given under "Configuration" below
3. Try to log in using valid AD user credentials

### Configuration

I've tried the following configurations, 'domain.com' being a stand-in for our domain.

```php
define('LDAP_AUTH', true);
define('LDAP_SERVER', 'ad.domain.com');
define('LDAP_PORT', 636);
define('LDAP_SSL_VERIFY', false);
define('LDAP_START_TLS', false);
define('LDAP_USERNAME_CASE_SENSITIVE', false);


// Attempt 1
define('LDAP_BIND_TYPE', 'proxy');
define('LDAP_USERNAME', 'kanboard-svc');
define('LDAP_PASSWORD', 'password-goes-here');

// Attempt 2
define('LDAP_BIND_TYPE', 'proxy');
define('LDAP_USERNAME', 'kanboard-svc@domain.com');
define('LDAP_PASSWORD', 'password-goes-here');

// Attempt 3
define('LDAP_BIND_TYPE', 'proxy');
define('LDAP_USERNAME', 'domain\kanboard-svc');
define('LDAP_PASSWORD', 'password-goes-here');
```

All three of these usernames work when used with e.g. ldapsearch or when binding with "raw" PHP `ldap_connect()` and `ldap_bind()`. I also tried user auth:

```php
// Attempt 4
define('LDAP_BIND_TYPE', 'user');
define('LDAP_USERNAME', 'domain\%s');
define('LDAP_PASSWORD', null);
```

With the same error in debug.log.

I've also tried to hardcode the username/password in app/Core/Ldap/Client.php line 134:

```php
           if (! @ldap_bind($this->ldap, 'kanboard-svc', 'password-goes-here')) {
```
Which produced the same error. However, this test code copied from the PHP manual:

```php
<?php

// using ldap bind
$ldaprdn  = 'kanboard-svc';     // ldap rdn or dn
$ldappass = 'password-goes-here';  // associated password

// connect to ldap server
$ldapconn = ldap_connect("ldaps://ad.domain.com:636")
    or die("Could not connect to LDAP server.");

if ($ldapconn) {
    // binding to ldap server
    $ldapbind = ldap_bind($ldapconn, $ldaprdn, $ldappass);
    // verify binding
    if ($ldapbind) {
        echo "LDAP bind successful...";
    } else {
        echo "LDAP bind failed...";
    }
}
```
Works and produces "LDAP bind successful..."

- Kanboard version: 1.0.38
- Database type and version: 10.0.29-MariaDB-0+deb8u1
- PHP version: 5.6.29-0+deb8u1
- OS: Linux 3.16.0-4-amd64

**Comment by fguillot** [comment]
I don't think the problem is coming from the ldap_bind() parameters but from the SSL connections.

- Is the Kanboard config working without SSL? (port 389 instead of 636)
- The code snippet above is executed on the same machine as Kanboard is installed?
- I would like to reproduce your issue, how can I setup a AD with SSL enabled? installing certificate service is enough?

**Comment by psy-q** [comment]
Thanks for the reply. It doesn't look so good, though:

  * I can't test without SSL because in our environment it's not allowed, but I'll try to scare up someone who could perhaps make an exception.
  * Yes, it was executed on the same machine. Once via Apache, once via command line. Both times it connected.
  * I'm not sure about that because I'm a Linux guy and the AD infrastructure is in the hands of other people. But I'll try to find out.

**Comment by psy-q** [comment]
I can meanwhile say that it works without SSL.

**Comment by jdkruzr** [comment]
It *does* work without SSL for you? Can you paste your configuration? It does not work without SSL for me.

**Comment by jdkruzr** [comment]
Also, can you tell me where you found these logs? I can't find where Kanboard puts its logs. They don't live in /var/log/apache2.

**Comment by psy-q** [comment]
Yes, **without** SSL it works. The only change to the configuration above is to use port 389. All four attempts then work. Manager and admin group matching works, as does group searching in the permission field.

**Comment by jdkruzr** [comment]
Do you know if any of this needs to be set?

// LDAP user group filter
// If this filter is configured, Kanboard will search user groups in LDAP_GROUP_BASE_DN with this filter
// Example for OpenLDAP: (&(objectClass=posixGroup)(memberUid=%s))
define('LDAP_GROUP_USER_FILTER', '');

// LDAP attribute for the group name
define('LDAP_GROUP_ATTRIBUTE_NAME', 'cn');

// Enable/disable the reverse proxy authentication
define('REVERSE_PROXY_AUTH', false);

// Header name to use for the username
define('REVERSE_PROXY_USER_HEADER', 'REMOTE_USER');

// Username of the admin, by default blank
define('REVERSE_PROXY_DEFAULT_ADMIN', '');

// Default domain to use for setting the email address
define('REVERSE_PROXY_DEFAULT_DOMAIN', '');

**Comment by psy-q** [comment]
I think you're asking about general LDAP configuration, but this ticket is about problems connecting with AD over SSL. You need the group filter string if you want to use groups, but not for authentication in general, that should work without. The reverse proxy settings should have nothing to do with LDAP as far as I know.

**Comment by keestux** [comment]
I have a similar (same?) problem with an OpenLDAP authentication. It works without TLS, and it does **not** work **with** TLS enabled.

In other words, this works:

    define('LDAP_PORT', 389);
    define('LDAP_START_TLS', false);

and this does not work:

    define('LDAP_PORT', 636);
    define('LDAP_START_TLS', true);
    define('LDAP_SSL_VERIFY', false);   // skip verification, just to be sure it does not interfere

The rest of the config is unchanged.

The not-working behaviour is that the login page in the browser hangs forever. Debug log gives no clue.

**Comment by keestux** [comment]
Enabling TLS via port 389, seems to be working though

**Comment by fguillot** [comment]
Do you guys try these settings: https://github.com/kanboard/kanboard/blob/master/doc/en_US/ldap-authentication.markdown#example-for-ldaps-ssl-encryption

**Comment by psy-q** [comment]
Thanks, adding the `ldaps://` schema before the FQDN worked for me. From the name `LDAP_SERVER` I thought that constant was only for the server name, not for a URI. But with a URI and using port 636, but `LDAP_START_TLS` set to false, it works.
