### ISSUE TITLE
Structured Task Description (Form or Template)

### ISSUE THREAD

**Issue by jaiume** [kanboard/kanboard#3007]
Feature Request

Ability to structure the description of a task to capture the same information.

Ideal implementation would be a form within the description. 
Could also be implemented as a template to be completed

Could define one or more forms per project.

E.g.

I am currently running a project, and using Kanboard to capture and track decisions. For each decision we want to capture some specific information, such as who needs the decision made, what should happen after the decision is made, and what supporting information is required for the decision. Currently we just use free form text, but it would be good to have the capability of a form within the description.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
