### ISSUE TITLE
Change file extensions for view file functionality

### ISSUE THREAD

**Issue by garettmd** [kanboard/kanboard#3008]
### Actual behaviour

With task attachments, it looks like certain file extensions give you the option to "view file" rather than just downloading it. I've noticed this works on files with the `.txt` extension, but it would be great to be able to add other file extensions as well, since many other files have different extensions but are still just plaintext files (.log, .py, etc.).

### Expected behaviour

It would be nice to have the ability to treat different extensions as .txt files, whether through the UI or through config.php. That way I would be able to view those files without downloading them.

### Configuration

Application version: 1.0.37
PHP version: 5.5.9-1ubuntu4.20
PHP SAPI: apache2handler
OS version: Linux 3.13.0-107-generic
Database driver: mysql
Database version: 5.5.54-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
