### ISSUE TITLE
Conflict due date

### ISSUE THREAD

**Issue by Kolesar** [kanboard/kanboard#3009]
### Actual behaviour
When make automatic action for adding due date on each task and make recurrence task with automatic due date. Kanboard adding both dates

### Expected behaviour
Recurrence task due date should be independent of automatic action due date

### Steps to reproduce
1. Make automatic action for adding due date
2. Make recurrence task with due date
3. Move task to another column
4. Check due date - it is sum of (period) due date from automatic action and recurrence task due date

### Configuration
Application version: master
PHP version: 5.6.30
PHP SAPI: apache2handler
OS version: Linux 3.10.0-514.6.1.el7.x86_64
Database driver: mysql
Database version: 5.6.35
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36

**Comment by fguillot** [comment]
In your scenario, the automatic actions and the recurrence will be executed, both system will modify the due date one after the other one. There is no mechanism to detect that you have configured both.
