### ISSUE TITLE
Request: Recurring based on week, weekday and other

### ISSUE THREAD

**Issue by Zimeon-** [kanboard/kanboard#3010]
### Actual behaviour

Recurring tasks would be great to set based on weekday or week for example every second tuesday. 3rd friday of the moth and so on.

### Expected behaviour

Based on actual behaviour. Mimic Outlook calendar feature for recurring tasks.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
