### ISSUE TITLE
Bug: "Move task" stopped to work

### ISSUE THREAD

**Issue by fourier** [kanboard/kanboard#3011]
![kb_move_task_bug](https://cloud.githubusercontent.com/assets/900250/22602797/044a472a-ea45-11e6-8ee0-ada6cebcab2e.png)
"Move position" button started to produce empty dialog after 2 weeks with 1.0.36

### Actual behaviour

1.Select the task
2. Click on "Move position" button
3. The dialog "Move position" is empty

### Expected behaviour
The dialog should never be empty.

### Configuration

    Application version: 1.0.36
    PHP version: 5.6.29-0+deb8u1
    PHP SAPI: apache2handler
    OS version: Linux 3.16.0-4-amd64
    Database driver: sqlite
    Database version: 3.8.7.1
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

Database

    Database size: 24.79M

**Comment by fourier** [comment]
It happens with several users I've been spoken to.

**Comment by fguillot** [comment]
You should try with the version 1.0.38 of Kanboard because the implementation is completely different. Before it was using VueJS.

If you get the same result with 1.0.38, check the browser console if there are any Javascript errors.

**Comment by fourier** [comment]
Ok I'll try to reinstall on next Friday's evening or earlier if I had a chance
