### ISSUE TITLE
Kanboard - Heroku documentation should mention limitations regarding plugins

### ISSUE THREAD

**Issue by connorbode** [kanboard/kanboard#3012]
### Actual behaviour

Plugins are erased because of Heroku's ephemeral storage.  In order to retain plugins, one should fork the Kanboard repo and manually maintain the plugins directory.

### Expected behaviour

Plugins installed via UI will remain after a Kanboard version upgrade / redeploy / restart of Heroku instance.

### Details

I've discovered this behaviour because:

1. I had installed and configured the S3 plugin via UI after deploying to Heroku.
2. After some time, I noticed some files I had uploaded were gone.
3. When I checked the Plugin configuration in the UI, there were no installed / configured plugins.
4. After some research, I realized that this is easily explained by the Plugins directory not being part of the code deployed to Heroku.

I'm suggesting that a point be added to the **Limitations** section in [this documentation on deploying Kanboard to Heroku](https://kanboard.net/documentation/heroku)

**Comment by fguillot** [comment]
The documentation has been updated. Thanks.
