### ISSUE TITLE
Issue 2681 is incorrectly labeled `unable to reproduce bug`

### ISSUE THREAD

**Issue by woosting** [kanboard/kanboard#3013]
I've reproduced [bug 2681](https://github.com/kanboard/kanboard/issues/2681) (showing the erroneous behavior in a moving gif), provided a step-by-step reproduction scenario, and explained what the expected behavior IMHO should be (also illustrated by a moving gif). However, I think it's not getting developmental attention as the original Issue-report was _erroneously_ labeled as `unable to reproduce bug` (probably being filtered as such from the developmental views by @fguillot a.o.) at some point. I therefore explicitly double-post here, to make sure that it's at least _noticed / acknowledged_ (by having [its label](https://github.com/kanboard/kanboard/issues/2681) changed), and _hopefully_ picked up in the (near?) future:

- Please change the [bug 2681](https://github.com/kanboard/kanboard/issues/2681) label to `bug`.
- Preferably provide some insights into whether (or not) it is to be expected to be picked-up.

_Apologies for double posting_ (I do not want to be pushy), but I am under the impression that the bug is critical for many and can easily go unnoticed until it is too late already having messed up people's production data, only because of an [unnoticed bug report](https://github.com/kanboard/kanboard/issues/2681) (which seems to be the case as its status is not updated).

**Comment by fguillot** [comment]
Thank you, I understand your concerns. But most of the time, duplicated tickets create more work in bug triage...
