### ISSUE TITLE
Bug: cannot remove attached images from task

### ISSUE THREAD

**Issue by Digital-punk** [kanboard/kanboard#3014]
### Actual behaviour

When trying to remove attachment from task, it redirects to new window, where is asking "Do you really want to remove this file", and there is now OK button or similar.

![bug-images-2](https://cloud.githubusercontent.com/assets/655257/22630146/7f9fae64-ebf4-11e6-9b44-0bf1c991659c.png)

### Expected behaviour

When trying to remove attachment from task, it should not to redirect, but show modal window with delete confirmation "Do you really want to remove this file" and OK button.

### Steps to reproduce

1. Open task with attachment (or add attachment).
2. Choose any attachment and select "remove":

![bug-images](https://cloud.githubusercontent.com/assets/655257/22630150/92b832a0-ebf4-11e6-9846-255245069e6a.png)

3. You will be redirected to new window without possibility to confirm delete.

### Configuration

Application version: 1.0.38
PHP version: 5.6.3
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-74-server
Database driver: mysql
Database version: 5.1.73-0ubuntu0.10.04.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by fguillot** [comment]
I'm not able to reproduce your issue with v1.0.38. Can you check if you have any Javascript errors in the browser console?

**Comment by Digital-punk** [comment]
There are no errors in the console. It's just opening not in modal window, but in the new window.

I could reproduce on the 3 different browsers.

**Comment by fguillot** [comment]
- Can you copy the HTML source code of the first screenshot to see what have been rendered?
- Do you have the same behaviour for files attached on the project (not tasks)?

**Comment by Digital-punk** [comment]
On the project it's working - I could successfully remove attached images.

Here is HTML source of the first screenshot:

[attachment-remove-bug-1.html.zip](https://github.com/kanboard/kanboard/files/753866/attachment-remove-bug-1.html.zip)

And here is HTML source of task page:

[attachment-remove-bug-2.html.zip](https://github.com/kanboard/kanboard/files/753867/attachment-remove-bug-2.html.zip)

**Comment by fguillot** [comment]
Ok, the 2nd HTML source tells me that you still have files from an old version of Kanboard. The remove link is rendered as:

```html
<a href="/?controller=TaskFileController&amp;action=confirm&amp;task_id=70&amp;project_id=4&amp;file_id=1" class="popover" title='' >Remove</a> 
```

The CSS class "popover" doesn't exists anymore.

This is probably due to the way you updated Kanboard.

**Comment by Digital-punk** [comment]
That's fine, but I actually downloaded Kanboard for the very first time 2 days ago, I didn't had any older version before. And I guess application version 1.0.38 is the latest one?

**Comment by Digital-punk** [comment]
Hi, I've found where is an issue with class "popover" - it's added by plugin "coverimage".
