### ISSUE TITLE
Unable to upload the file

### ISSUE THREAD

**Issue by SergiArias** [kanboard/kanboard#3016]
### Actual behaviour

The avatar file doesn't upload giving the error "Unable to upload the file."
I have kanboard installed on another server and the same feature works, so I guess it's a server requirement problem (maybe php version?).

### Configuration

SERVER THAT GIVES ERROR:

Application version: 1.0.38
PHP version: 5.6.30-1+deb.sury.org~trusty+1
PHP SAPI: apache2handler
OS version: Linux 4.8.6-x86_64-linode78
Database driver: mysql
Database version: 5.6.33-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

SERVER THAT WORKS

Application version: 1.0.38
PHP version: 7.0.2
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-604.30.3.lve1.3.63.el6.x86_64
Database driver: mysql
Database version: 5.6.33-cll-lve
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by fguillot** [comment]
Is the permissions of the data folder are corrects?

**Comment by SergiArias** [comment]
The permissions are 755 in both servers for data folder. The files inside are 644. In the case that doesn't work, the files folder with avatars and # inside aren't created. Even creating them by hand doesn't make it work.

Thanks!

**Comment by fguillot** [comment]
It should work regardless of the version of PHP.

- The owner/group of the data folder are correct? the web server user is able to write in this folder?
- Do you have a custom config file? if yes, what is the value for the data folder, is the path absolute?

**Comment by SergiArias** [comment]
Hi! In my config file I have the default value: `define('DATA_DIR', 'data');`

But I will ask the webmaster regarding this config. Maybe because of the server type the path has to be absolute. I will get back to you as soon as I have tried some things.

Merci!!

**Comment by SergiArias** [comment]
Hi!
It's solved now, the problem was the web server user, that wasn't able to write in this folder. I don't have access to the server setup so I didn't know beforehand.

Thank you so much and sorry for asking a minor problem!
