### ISSUE TITLE
Ldap Active directory authentication failed with complex password

### ISSUE THREAD

**Issue by tpimont** [kanboard/kanboard#3017]
Hello,

setup a new server with latest version 1.0.38 and ldap authentication against Active Directory.
log  a user with a password that doesnt contains special character is ok.
but not when the password contains special character.

in the log LDAP authentication failure

**Comment by tpimont** [comment]
Remove this line  $this->password = $password;  in \kanboard\app\auth\ldapauth.php

 public function setPassword($password)
    {
        //$this->password = $password;
    }

user with complex password can now login

**Comment by fguillot** [comment]
If you remove this line, the authentication will not use any password.

There is no reason that complex passwords should not work, how did you come to this conclusion?

**Comment by tpimont** [comment]
I try with a user in Active directory that dont have complexe password only letters and it's ok.
the user was create in kanboard and can login.
then i try with another one with complex password letters numbers an complexe sign , the user didnt login
and there is a authentication failure in logs

i try to html_entity_decode password or ut8 decode but noting change.

**Comment by tpimont** [comment]
Extract from logs 

This user is ok , standard password
[2017-02-15 15:21:19] [info] Authenticate this user: CN=Test,OU=Utilisateurs,OU=conto,OU=contoso,DC=contoso,DC=fr

This user is ko , complex password

[2017-02-15 15:26:21] [info] Authenticate this user: CN=Test2,OU=Utilisateurs,OU=conto,OU=contoso,DC=contoso,DC=fr
[2017-02-15 15:26:21] [error] LDAP authentication failure for "CN=Test2,OU=Utilisateurs,OU=conto,OU=contoso,DC=contoso,DC=fr"

**Comment by tpimont** [comment]
problem solved, it is not the complex password but a problem with OU in base DN.
i try in wrong OU .
Sorry

**Comment by fguillot** [comment]
Ok so I close this ticket.
