### ISSUE TITLE
Feature request/question: advanced search for tasks

### ISSUE THREAD

**Issue by fourier** [kanboard/kanboard#3018]
Right now there seems to be no way to perform the following search actions:
 - Search for issues with 2(or more) specified tags, i.e. "tag:Release1 tag:Showstopper"
 - Search for negative cases, i.e. "status:open not(tag:Showstopper)"

If there is a way to perform these searches, kindly please let me know! 

Configuration

    Application version: 1.0.36
    PHP version: 5.6.29-0+deb8u1
    PHP SAPI: apache2handler
    OS version: Linux 3.16.0-4-amd64
    Database driver: sqlite
    Database version: 3.8.7.1
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by fguillot** [comment]
There is no negation at the moment. Contributions are welcome.
