### ISSUE TITLE
Feature request : advanced filters to send mail on task creation

### ISSUE THREAD

**Issue by Finrod927** [kanboard/kanboard#3019]
Right now, we can create an automated action to send a task by email to one person when the tasks is created in a specific column.

It would be great to be able to send a task by email to **one or more** person when the tasks is created in a specific column **and/or a specific swimlane**.

We have an "issue" swimlane and it would be great that all team members receive an email when a task is created in that swilane.

Thanks :)

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
