### ISSUE TITLE
Set or update "started date" via the API

### ISSUE THREAD

**Issue by rmjstn** [kanboard/kanboard#3020]
Hello, 

It's not possible to set or update the "started date" via the API procedures createTask or updateTask (https://kanboard.net/documentation/api-task-procedures).
The getTask procedure return the "date_started" attribute.

Thanks,

Rémy

**Comment by rmjstn** [comment]
Hi, 

I create a Pull Request.

Rémy

**Comment by fguillot** [comment]
Your PR is merged now.

**Comment by andresth** [comment]
Hi,
it seems to me that the handling of dates in this two functions are inconsistent with the rest of the API.
All the other functions return dates as Unix timestamps, while create and updateTask now take two differently formatted strings for start and due date.
Is it possible to change this two functions to use Unix timestamps too?

Greetings
Thomas

**Comment by andresth** [comment]
Hi,

while trying to use the date_started parameter in my app I found that it only accepts the date format defined application configuration.

Greetings
Thomas

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
