### ISSUE TITLE
Adding dynamically (when enough room) sub-task % / comment icon / external link icon using Board with Collapse tasks

### ISSUE THREAD

**Issue by 2Belette** [kanboard/kanboard#3021]
### Actual behavior

Theses information are only displayed on Expand Task mode.
Using Expand Task mode with a high number of tasks is not so easy to navigate and get a global view of the tasks without scrolling a lot.
Collapse tasks mode is the perfect view but we are losing useful information...

### Expected behavior

Would be great to dynamically put the information on the right of the task name itself when the column width is more than X pixel (to defined) and disappear if the column width is too low.

### Example
Now - Collapse Task mode : 
![2017-02-08-20 37 22](https://cloud.githubusercontent.com/assets/2325706/22754197/fc44da74-ee3e-11e6-8e4b-92127a042d8d.png)

Now - Expand Task mode : 
![2017-02-08-20 39 36](https://cloud.githubusercontent.com/assets/2325706/22754191/f26e1402-ee3e-11e6-8cb8-d7ff7a1caba4.png)

Expected - Hybrid mode : 
![2017-02-08-20 42 11](https://cloud.githubusercontent.com/assets/2325706/22754282/5d927aca-ee3f-11e6-86d3-1e16f2b8896d.png)

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
