### ISSUE TITLE
Feature request: duplicate task to one or more swimlanes

### ISSUE THREAD

**Issue by szawadski** [kanboard/kanboard#3022]
### Actual behaviour

Today it is possible to duplicate a task to one or more projects (with one manipulation). It is also possible to duplicate a task within the same project but with no possibility to chose to which swimlane.

### Expected behaviour

Similarly as for the duplication to another project, it would be interesting to be able to duplicate to one or more swimlanes within the same projects.

### Configuration

- Kanboard version: 1.0.36
- Database type and version: MariaDB
- PHP version: 5.6
- OS: Synology DSM 6.0
- Browser: Chrome & Mozilla

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
