### ISSUE TITLE
Feature Request - Filter by both asignee or(inclusive) subtask assignee

### ISSUE THREAD

**Issue by george-viaud** [kanboard/kanboard#3025]
It would be very useful to be able to quickly see only tasks that are either assigned to me, or have a subtask that is assigned to me (at the same time), from the board view.

If this is possible I have not discovered the method of achieving the described result.

Many thanks!

**Comment by szawadski** [comment]
Hello, got the same request from users. Solved the issue by providing an external report, build using an SQL request on the database. But it would be SO cool to have it directly in Kanboard!

**Comment by szawadski** [comment]
Actually, maybe it would be more useful to propose to possibility to use the keyword OR in filters. Would solve the issue and would offer other possibilities.

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
