### ISSUE TITLE
LDAP working in anonymous, but not in proxy nor user

### ISSUE THREAD

**Issue by feydreva** [kanboard/kanboard#3027]
### Actual behaviour

When configured in anonymous, i can logg-in using the ldap without issue.

When it is configured in proxy mode or user mode, I get error message.
I tried with a end-user, that successfully log in when in anonymous, and with a proxy.. same result

=====logs=====
[2017-02-10 15:54:27] [debug] ###############################################
[2017-02-10 16:56:36] [debug] Kanboard\Core\Controller\Runner::executeMiddleware
[2017-02-10 16:56:36] [debug] Subscriber executed: Kanboard\Subscriber\BootstrapSubscriber::execute
[2017-02-10 15:56:36] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\AuthenticationMiddleware
[2017-02-10 15:56:36] [debug] Kanboard\Core\Controller\Runner::executeController => \Kanboard\Controller\AuthController::check
[2017-02-10 15:56:36] [error] LDAP authentication failure for "kanboardsystemuser"
[2017-02-10 15:56:36] [debug] Kanboard\Auth\ApiAccessTokenAuth::authenticate: Authentication provider skipped because invalid scope
[2017-02-10 15:56:36] [debug] Subscriber executed: Kanboard\Subscriber\AuthSubscriber::onLoginFailure

=====config======
// LDAP bind type: "anonymous", "user" or "proxy"
define('LDAP_BIND_TYPE', 'proxy');

// LDAP username to use with proxy mode
// LDAP username pattern to use with user mode
define('LDAP_USERNAME', 'kanboardsystemuser');

// LDAP password to use for proxy mode
define('LDAP_PASSWORD', 'dQA6CACom8EeGF');

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:
    Application version: 1.0.38
    PHP version: 5.6.30-0+deb8u1
    PHP SAPI: apache2handler
    OS version: Linux 3.16.0-4-amd64
    Database driver: mysql
    Database version: 5.5.54-0+deb8u1
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by feydreva** [comment]
Any idea ?? thank you :)

**Comment by jdkruzr** [comment]
I'm having the same problem with my Active Directory LDAP, but I don't know where you're seeing these logs. Where did you find this?

**Comment by fguillot** [comment]
Is the LDAP user working correctly independently of Kanboard:

> [error] LDAP authentication failure for "kanboardsystemuser"

The error reporting has been improved in v1.0.39, maybe that will help you to find the problem. I assume that you checked the examples provided in the documentation: https://kanboard.net/documentation/ldap-configuration-examples ?

For your information, you just open sourced your LDAP password:

> define('LDAP_PASSWORD', 'dQA6CACom8EeGF');

**Comment by rakesh1084** [comment]
proxy is working for me 
in the config.php

below won't work
```
define('LDAP_BIND_TYPE', 'proxy');
// LDAP username to use with proxy mode
#define('LDAP_USERNAME', '0075');

```

This below one worked for me:-

```
define('LDAP_BIND_TYPE', 'proxy');

// LDAP username to use with proxy mode
define('LDAP_USERNAME', 'CN=read_only_admin,OU=Users,OU=Corp,OU=ORG,DC=COM');
```


below is the debug.log snapshot
`[2017-04-25 15:26:01] [info] Authenticate this user: CN=Rakesh,OU=Users,OU=Corp,OU=ORG,DC=COM`

**Comment by fguillot** [comment]
Well, I cannot troubleshoot your LDAP configuration for you. Double check your config file according to the documentation.
