### ISSUE TITLE
New feature Dates

### ISSUE THREAD

**Issue by fabdelgado** [kanboard/kanboard#3028]
### Expected behaviour

Start date, planned date and end date are required in tasks and subtasks.

**Comment by razron** [comment]
I would agree if that is a setting at the project level. In our work flows we do have a "Wish List" or "Nice to have" tasks that just have estimated time associated with them. Mandatory "dates" really work for these.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
