### ISSUE TITLE
SQLite database upload

### ISSUE THREAD

**Issue by kvj** [kanboard/kanboard#3030]
When sqlite DB is used, there are two additional administrator options available: download gzipped DB and run VACUUM. It would be great to be able to upload gzipped (or not) DB in order to replace existing.

Use cases: migration, having multiple instances, restore from backup etc.

If community is OK, I can work on that

**Comment by fguillot** [comment]
You could make a prototype to validate that works correctly. I don't know what will be the behaviour if the file is replaced while in use.

**Comment by fguillot** [comment]
This is now merged into master.
