### ISSUE TITLE
Inconsistent "Add task" and "Add a sub-task" assign UI behaviour 

### ISSUE THREAD

**Issue by kvj** [kanboard/kanboard#3031]
**Here I mean only Private projects**

### Actual behaviour

* When new task is created, it's assigned to current user by default
* When new sub-task is created, current assignee is 'Undefined'

### Expected behaviour

* New sub-task should be assigned to project owner (or task assignee) by default

### Steps to reproduce

1. Make new private project
2. Add new task (by default assigned to project owner)
3. Add new sub-task (by default it's unassigned)

### Configuration

- Application version: 1.0.39
- PHP version: 7.0.15
- PHP SAPI: fpm-fcgi
- OS version: Linux 4.4.0-57-generic
- Database driver: sqlite
- Database version: 3.15.2
- Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

If expected behaviour is desired one, I can fix that

**Comment by NinjaPewPew** [comment]
To be fair, the sub task is automatically assigned, when you start a sub task. So it's not like you actually have to do anything.

**Comment by kvj** [comment]
@NinjaPewPew that's true, but the thing is un-assigned tasks are not shown in Dashboard

**Comment by fguillot** [comment]
This is now fixed by PR #3046. Thanks!

**Comment by fguillot** [comment]
Available in Kanboard 1.0.40
