### ISSUE TITLE
'Visible on dashboard' flag is ignored on copy

### ISSUE THREAD

**Issue by kvj** [kanboard/kanboard#3032]
### Actual behaviour

* When 'Create from another project' option is used in 'New project' dialog, Column visibility flag is not copied (column name is copied though)

### Expected behaviour

* All column properties should be copied on project duplicate

### Steps to reproduce

1. Make new project
2. In column settings, change column visibility flag from Yes to No
3. Create another project using 'New project' dialog and select previously created project from drop-down
4. Check new project column -> visibility flag is Yes

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version:  1.0.39
- Database type and version: sqlite 3.15.2
- PHP version: 7.0.15
- OS:  Linux 4.4.0-57-generic
- Browser:  Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

If it's bug I can fix that

**Comment by fguillot** [comment]
This is now fixed by PR #3047. Thanks!

**Comment by fguillot** [comment]
Available in Kanboard 1.0.40
