### ISSUE TITLE
Open task in new tab (board card)

### ISSUE THREAD

**Issue by lejean2000** [kanboard/kanboard#3033]
I just updated to version 1.0.39, having skipped 1.0.38. Before it was possible to middle-click on a task name in board view and the task will open in new tab. This worked both in collapsed and not-collapsed view. We used this feature all the time.

Now it is **not possible** to middle-click or even right-click a task in Board view. They always open in the same window. If I want to open in new window I have to go to List view.

**Comment by szawadski** [comment]
Hello, I confirm this new behaviour of the application is not appreciated by our users. Many of them where pre-opening multiple tasks in multiple tabs during the review of tasks. Would be appreciated to get this feature unlocked in the next version.

**Comment by fguillot** [comment]
This feature is back in v1.0.41
