### ISSUE TITLE
New keyboard shortcut for dashboard - v+d

### ISSUE THREAD

**Issue by cose385** [kanboard/kanboard#3036]
### Actual behaviour

Currently there's no such keyboard shortcut for quick accessing the dashboard.

### Expected behaviour

When pressing letter "v" and then "d" it should open the dashboard - in a similar way it now opens the board with v+b.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
