### ISSUE TITLE
Sub-tasks from the hidden columns still visible on the dashboard

### ISSUE THREAD

**Issue by cose385** [kanboard/kanboard#3037]
### Actual behaviour

When Column is checked with "Hide tasks in this column in the dashboard" - tasks are hidden, but sub-tasks are still displayed on the dashboard.

### Expected behaviour

Sub-tasks from the Column with checked option "Hide tasks in this column in the dashboard" should also be hidden.

Optionally add option "Hide sub-tasks in this column in the dashboard" to the Columns.

### Steps to reproduce

1. Edit Column and check option "Hide tasks in this column in the dashboard".
2. In that Column create Task "Test task - hidden".
3. In that Task create sub-task "Test sub-task - not hidden".
4. Go to dashboard - "Test task - hidden" is not visible and the sub-task "Test sub-task - not hidden" is visible.

### Configuration

- Kanboard version: 1.0.39
- Database type and version: SQlite
- PHP version: 5.6
- OS: Windows
- Browser: Chrome

**Comment by Busfreak** [comment]
well observed, thanks for the hint!

**Comment by fguillot** [comment]
The fix is available in Kanboard 1.0.40. Thanks!
