### ISSUE TITLE
Feature Request :: Notifications Alert

### ISSUE THREAD

**Issue by rakesh1084** [kanboard/kanboard#3039]
### Actual behaviour
Sends and email immediately on the task creation to users .

### Expected behaviour

It would be nice to have an option in the user Preferences menu:-
_Already Available_: Notification via Mail/Web
_Required Feature_: Meeting Invite / **Reminder on Task Due Date**
**_Notification Mechanism_**: -
Under **Notifications** Screen 
Give an option to Select the "**Send Reminder Alert Notifications**".
when user selects the option kanboard can send an alert mail as a calendar option.

some working sample below:-
```
	function reminderNotify() {
		$subject                  = "title_of_the_Task";
		$organizer              = task_Creator;
		$organizer_email    = task_creator_mail_id ;
		$participant_name_1 = 'task_Creator';
		$participant_email_1= 'task_creator_email_id';
		$participant_name_2 = 'manager_Name';
		$participant_email_2= 'manager_email_id';
		#$location           = "location";
		$task_due_date	= 'task_due_date';
		$dateObj			= DateTime::createFromFormat('d/m/Y', $task_due_date );
		$new_date_format	= $dateObj->format('Ymd');
		$date                       = $new_date_format;
		$startTime               = date("hi");
                $endTime                = date("hi",  strtotime(idate("h").idate("i") . "+30 minutes"));
		$desc                       = 'task_description';
		$headers = 'Content-Type:text/calendar; Content-Disposition: inline; charset=utf-8;\r\n';
		$headers .= "Content-Type: text/plain;charset=\"utf-8\"\r\n"; #EDIT: TYPO
		$message = "BEGIN:VCALENDAR\r\n
		VERSION:2.0\r\n
		PRODID:-//Deathstar-mailer//theforce/NONSGML v1.0//EN\r\n
		METHOD:REQUEST\r\n
		BEGIN:VEVENT\r\n
		UID:" . md5(uniqid(mt_rand(), true)) . "example.com\r\n
		DTSTAMP:" . gmdate('Ymd').'T'. gmdate('His') . "Z\r\n
		DTSTART:".$date."T".$startTime."00Z\r\n
		DTEND:".$date."T".$endTime."00Z\r\n
		SUMMARY:".$subject."\r\n
		ORGANIZER;CN=".$organizer.":mailto:".$organizer_email."\r\n
		LOCATION:".$location."\r\n
		DESCRIPTION:".$desc."\r\n
		ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN".$participant_name_1.";X-NUM-GUESTS=0:MAILTO:".$participant_email_1."\r\n
		END:VEVENT\r\n
		END:VCALENDAR\r\n";
		$headers .= $message;
		mail($to, $subject, $message, $headers);
	}
       reminderNotify(required_parameters_of_the_project);
```

### Steps to reproduce
1. Goto any of the Project --> Create a New Task --> Enter required details and SAVE.
2. Email will get triggered based on the preferences.

### Configuration

    Application version: 1.0.38
    PHP version: 5.3.28
    PHP SAPI: cgi-fcgi
    OS version: Windows NT 6.2
    Database driver: mysql
    Database version: 5.6.31
    Browser: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Thanks for the wonderful project again**

**Comment by rakesh1084** [comment]
Hi @fguillot , do you have this in the roadmap.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
