### ISSUE TITLE
Allow ordering actions

### ISSUE THREAD

**Issue by docwhat** [kanboard/kanboard#304]
When multiple action manipulate the same thing (e.g. color) then it isn't obvious what will happen.

It'd be nice if the actions could be reordered (via drag-and-drop?) so that the admin can make that explicit.

**Comment by gene-pavlovsky** [comment]
It would also be nice if somehow the list could be displayed in more condensed. Currently each item takes up too much height, so all items can't fit on screen in my case.

**Comment by ErZ101** [comment]
+1 this feature/improvement.
What order are they processed in right now? Bottom to Top?
