### ISSUE TITLE
Give feedback when creating subtasks with "create another subtask"

### ISSUE THREAD

**Issue by psy-q** [kanboard/kanboard#3043]
### Actual behaviour

When using the "Create another sub-task" feature, adding a sub-task will not show any feedback. I don't know whether the subtask was actually created. Closing the "add sub-task" dialog will not show any of the new sub-tasks. Reloading the task page will.

### Expected behaviour
 
When using the "Create another sub-task" feature, adding a sub-task will give some sort of feedback whether the task was created successfully. Closing the "add sub-task" dialog will make all the newly added tasks show on the task page. This could even be done by a brute reload of the page.

### Steps to reproduce

  1. Click "Add a sub-task" in a task
  2. Check "Create another sub-task" checkbox
  3. Enter a title for the subtask. Click "save"
  4. The sub-task title is blanked and you get no feedback that the sub-task was created.
  5. When closing the "Add sub-task" dialog, all the new sub-tasks are not displayed on the task page
  6. Reloading the page will show the newly added sub-tasks

Instead an improved behavior could be:

  1. Click "Add a sub-task" in a task
  2. Check "Create another sub-task" checkbox
  3. Enter a title for the sub-task. Click "save"
  4. A confirmation that the sub-task was created appears (if successful, otherwise error message)
  5. The sub-task title is blanked and the system is ready for the next task
  6. When closing the "Add sub-task" dialog, all the new sub-tasks are displayed on the task page
  6. Reloading the page will still show the same sub-tasks: any existing ones plus any new ones added in step 3

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

    Application version: 1.0.38
    PHP version: 5.6.29-0+deb8u1
    PHP SAPI: apache2handler
    OS version: Linux 3.16.0-4-amd64
    Database driver: mysql
    Database version: 10.0.29-MariaDB-0+deb8u1
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by fguillot** [comment]
This behavior has been improved in the development branch.
