### ISSUE TITLE
Feature request: setting for first day of week in pop-up calendar

### ISSUE THREAD

**Issue by cose385** [kanboard/kanboard#3044]
### Actual behaviour

While date and time format can be specified independently of the chosen language - first day of week is depending only on the chosen language and can't be overridden.

### Expected behaviour

In the Application settings (where Timezone and date settings are located) there should be a setting for "First day of week" with values "Language default, Sunday, Monday, Tuesday, ... Saturday".

**Comment by fguillot** [comment]
Tickets related to the calendar should be posted to the calendar plugin bug tracker: https://github.com/kanboard/plugin-calendar/issues

Thank you
