### ISSUE TITLE
Unable to complete subtask

### ISSUE THREAD

**Issue by garettmd** [kanboard/kanboard#3045]
### Actual behaviour

When clicking on a subtask to close it, instead of the subtask changing to "in-progress" or "complete" a new window comes up informing the user that "You already have one subtask in progress". This window seems to be in error especially because it is lacking any CSS styles like the rest of Kanboard, and the two options it gives - "Todo" and "Done" - don't respond.

![image](https://cloud.githubusercontent.com/assets/7316933/22994379/c2d8d898-f394-11e6-977a-5af68a08b10d.png)

### Expected behaviour

Clicking on the subtask should either move the task to an in-progress state or complete it.

### Steps to reproduce

So far, I've only seen one user with this issue. For this user, the error was occurring without fail until we changed his application role from Manager to Administrator. This fixed the error for the next click, but any subsequent clicks brought the error up again. Changing his role back to Manager from Administrator again fixed the error for one click, with every subsequent click showing the error again.

### Configuration

Application version: 1.0.37
PHP version: 5.5.9-1ubuntu4.20
PHP SAPI: apache2handler
OS version: Linux 3.13.0-107-generic
Database driver: mysql
Database version: 5.5.54-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by fguillot** [comment]
You should upgrade to Kanboard 1.0.39 because this issue has been fixed if I remember correctly.

**Comment by garettmd** [comment]
Turns out there was a setting preventing the user from being able to have more than one subtask running. We changed the setting.
