### ISSUE TITLE
Feature request: Create permalink to #id

### ISSUE THREAD

**Issue by jniggemann** [kanboard/kanboard#3048]
**Goal**: Link directly to a card so that it opens in the browser (if the user is authenticated). The link could be in all kinds of external systems, ex. in a spreadsheet or word processor.

### Actual behaviour

I did not find such a possibility.

### Configuration

- Version: 1.0.36
- PHP Version: 5.6.30-0+deb8u1
- PHP SAPI: apache2handler
- OS Version: Linux 3.16.0-4-686-pae
- Datenbanktreiber: sqlite
- Datenbank Version: 3.8.7.1
- Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3000.4 Safari/537.36

**Comment by fguillot** [comment]
Why not use the URL location when you are on the task view page?

**Comment by jniggemann** [comment]
I tried it, but always got redirected to the board view.
Will retry and report back next week.

**Comment by kvj** [comment]
In my case following works:
`/?controller=TaskViewController&action=show&task_id=62`
where `task_id` is persistent ID of task

**Comment by jniggemann** [comment]
Thank you @kvj, this worked.
