### ISSUE TITLE
Add voting to tasks - Enhancement Request

### ISSUE THREAD

**Issue by whinote** [kanboard/kanboard#3053]
**Please, do not create duplicate issues**
- I did search for a duplicate request but did not find one.

### Expected behaviour
- This would work similar to Trello's voting. A user can vote one time only. It would be nice if their could be a downvote and upvote option.

### Configuration
Application version: 1.0.38
PHP version: 5.6.30
PHP SAPI: apache2handler
OS version: Linux 2.6.32-642.el6.x86_64
Database driver: mysql
Database version: 5.6.35
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by whinote** [comment]
Is this best implemented in a plugin or in the base code? Is this something that a plugin developer could write for a fee?

Our team has been trying a few things in the base code but nothing has proven to be the same as what we saw in Trello. We like Kanboard and its features much more and the voting option would just extend our use of the application for other things in our office.

**Comment by Busfreak** [comment]
Hi @whinote 
A plugin would be best.
Use the hook "template:board:task:icons" to implement an icon in the right lower corner of the tasks and give it the action you need.
Something like this:
![image1](https://cloud.githubusercontent.com/assets/12938119/23455984/f8db394e-fe71-11e6-97fc-7196585cd85a.jpg)

**Comment by RRRRoger** [comment]
I upvote this!

**Comment by Busfreak** [comment]
So tell me what it should do in detail.
Maybe I think about it 😄

**Comment by RRRRoger** [comment]
I'm new to this community and i'm zero-technical so i can't technically explain in detail how it would work. I'm not even sure you are talking to me so if it isn't the case, i'll just delete this to keep the thread clean!

I don't want to hijack or spam whinote's thread.. Anyway, here's how i see it:


![kanboard_vote_002](https://cloud.githubusercontent.com/assets/26545297/24768935/7fe6e2cc-1ad2-11e7-8c03-9ffceb0ba9e2.jpg)

**- A bit like reddit does, each task could be upvoted/downvoted.** 

**- Each user could only put one upvote/downvote per task.**

**- The cumulative vote points could be used as a task sorting filter to affect it's display order in a column.**

I guess most upvoted tasks would be sorted top and the ones with the least votes would be sorted at the bottom.

**Here's some practical context:** 
Where i work we are many people per department and everyone has specific priorities.
Having meetings to decide on what order the task should be addressed can be chaotic, time consuming and inefficient.
On other hand, having the supervisor deciding the priorities has it's downside too. Sometimes he doesn't really know the details of each tasks, making it hard for him to decide of it's priority.
 
 
Now here's something that might be illegal/confusing...
I should probably put this in it's related thread ( https://github.com/kanboard/kanboard/issues/1507 ) ...
It's about having a sorting functionnality in Kanboard ( "By vote number" for this example) .
![screenshot_sorting_dropdown_001](https://cloud.githubusercontent.com/assets/26545297/24770014/7ee53f82-1ad6-11e7-8fca-189a711f6ba0.jpg)

Again, if this post is useless i'll either edit or delete it!

**Comment by whinote** [comment]
That is very close to how we intended this feature to work. We have developed our own work around but it exists mainly outside of the kanboard and is not as clean as it being natively developed inside the app. It would be really great to see something like this added into the application.

We were hoping to use it as an idea board of sorts. Users can vote on tasks and if there is enough interest and it is technically feasible it moves from the ideas column to planning and progresses through our development process. It is a way for users to see the devops lifecycle in action. They vote and give feedback with comments. Tasks are updated and statuses are changed by developers which notifies users of progress. It is an easy way to engage users without having to engage them at a specific time during conference calls and meetings. They can interact at times that are convenient to them.

By allowing them to down vote and provide comments we can also see why a particular idea or feature would be bad or impact other users even though one user may think it is beneficial.

RRRRoger is using this specifically for a team and we do that as well but we want to bridge a huge gap with our user community that is spread all over the country by providing a way for them to steer the development ship without having to attend every meeting and conference call but still provide much needed interaction and feedback. Plus, there are times outside of meetings when inspiration hits and they can update the board themselves without having to reach out to my team to update a board they never see.

We would like the votes to be one per user per task whether it is an up or down vote.

RRRRoger’s mockup looks really good as well and sorting by votes would be really nice feature to have.

Thanks for considering this and thank you RRRRoger for providing additional input and including a visual aid!

**Comment by Busfreak** [comment]
Hi @RRRRoger, you are welcome to express your wishes and comments here!

I have a plan how to do the up-/downvoting once for each user/task.
There is no sorting filter, this is done by moving tasks manualy. But I could implement sorting in the bord/column/dorpdown, but this has to be done manualy. I have to think about automatic sorting and do some tests.

Question:
Is it important to track who has voted? E.g. in the project activity?

Further discussion can be done here:
https://github.com/Busfreak/kanboard_TaskVote

@whinote you can close this issue to keep kanboard issues clean.

**Comment by Busfreak** [comment]
Hi!
give it a try:
https://github.com/Busfreak/kanboard_TaskVote/releases/tag/v.0.0.1
Sorting is in the dropdown at top of a column, but also automatically after voting.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin as discussed before.

Thank you for your understanding
