### ISSUE TITLE
Add comments to tasks - Enhancement Request

### ISSUE THREAD

**Issue by whinote** [kanboard/kanboard#3054]
**Please, do not create duplicate issues**
- I did search for a duplicate request but did not find one.

### Expected behaviour
- This would work similar to Trello's comments. A user can add a comment but not edit a task submitted by another user unless they are an admin. Supports multiple comments with the ability to notify the creator of the task as well as the person who adds a comment.

### Configuration
Application version: 1.0.38
PHP version: 5.6.30
PHP SAPI: apache2handler
OS version: Linux 2.6.32-642.el6.x86_64
Database driver: mysql
Database version: 5.6.35
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by fguillot** [comment]
Comments are already there and notifications too, what should be different?

**Comment by twburgett** [comment]
I didn't see the comments until after I sent the request.   I apologize for
not looking closer.   Thank you for the feedback.
I like the application very much.
