### ISSUE TITLE
Calendar: Business hours

### ISSUE THREAD

**Issue by chthal** [kanboard/kanboard#3055]
In calendar hours go from 00 to 23. But fortunately we only need from 8:30 to 16:00, on friday our business hours end at 14:00, the rest of the days we do not work.  ;-)

We would like to have the ability to define the range of hours per day in a project. So the calendar view for a day could be smaller.

**Comment by fguillot** [comment]
Tickets related to the calendar should be posted to the calendar plugin bug tracker: https://github.com/kanboard/plugin-calendar/issues

Thank you
