### ISSUE TITLE
Access Forbidden message after close a task version 1.0.39

### ISSUE THREAD

**Issue by spychoux** [kanboard/kanboard#3056]
**Please, do not create duplicate issues**
I don't find the same

### Actual behaviour

When I close a task I have the message Access Forbidden that will be appears.

### Expected behaviour

I'm prefered to return at the board view of the project.

### Steps to reproduce

1. Log in to the application as the administrative user
2. Create two differents project.
3. Use automatic Actions  
> **Event name** = Closing a task
> **Action name** = Move the task to another project
4. Go to the Board view and click on a task for view Summary.
5. And then close the task
```
For more information, no problem when close directly in Board view or task list
```
### Configuration
* Application version: 1.0.39
* PHP version: 7.0.8
* PHP SAPI: fpm-fcgi
* OS version: OpenBSD 6.0
* Database driver: postgres
* Database version: 9.5.3
* Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

English not my first choice in school best in French ;)

Thanks for read.

**Comment by fguillot** [comment]
1. You should upgrade to the latest version. 
2. Take a screenshot of what is happening exactly. 
3. Watch the logs while the problem occurs.
