### ISSUE TITLE
Kanboard getting firewalled

### ISSUE THREAD

**Issue by skreisel** [kanboard/kanboard#3057]
### Actual behaviour

Dragging a task from one column to another, or from one swimlane to the next causes that task to be placed in the goal slot, but it stays greyed out and the throbber spins to eternity. Alternatively, if one wants to change the column association by editing the task and via the "Move position" command - this then leads to a prompt on the pop-up stating "undefined".

This behaviour is behind our hospital's firewall only; (using the board outside this constrained environment is flawless). Note though: everything else works fine. So the problem must be Kanboard's calls to the outside world being intercepted. 

Question would be: how does Kanboard communicate so that it gets firewalled?

### Expected behaviour

Drag drop on the board working like a charm.

### Steps to reproduce

None outside the environment used...

### Configuration

Note: Kanboard is installed on a dedicated server outside the hospital's firewall. Bug is: using Kanboard "client" within the firewall, calling Kanboard installation outside of it.

- Application version: 1.0.39
- PHP version: 5.5.38
- PHP SAPI: cgi-fcgi
- OS version: Linux 2.6.32-504.12.2.el6.x86_64
- Database driver: sqlite
- Database version: 3.6.20
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by skreisel** [comment]
I'm not sure it's server configuration - that is if Kanboard's server is meant: Rather some (firewall) server inbetween...
Rather:
Should be: Browser request `->` Firewall lets request to switch column through `->`  Kanboard Server outside the firewall environment responds
Bug could be: Browser request `->` Firewall does not let request to switch column through `->`  Kanboard Server outside the firewall environment does not respond

Cheers!

**Comment by fguillot** [comment]
What kind of firewall do you use? if you are using a system (web application firewall) that modify/alter the Javascript code on the fly, there is unfortunately not much that can be done at the application level (Kanboard).

You will probably have the same problem with any kind of web application that go through your firewall.

Perhaps, you could disable some rules on your firewall or whitelist Kanboard.

**Comment by skreisel** [comment]
Thanks for your comment! And yes: it will probably be some configuration in the server environment I have no influence on...
There are some peculiarities however: If I edit a task and add a `#` to e.g. the title, it goes into the same deathspin. So am wondering if some part of the Information transmitted is interpreted as being malicious. Again: everything else works fine - just the drag-drop move on the board!

**Comment by fguillot** [comment]
I understand but unfortunately there is not much that can be done in the application itself.

The only thing that could done is to change the configuration of your Firewall. Or try to use HTTPS to avoid the content inspection of your Firewall.
