### ISSUE TITLE
Tasks in "Done" vanish"

### ISSUE THREAD

**Issue by skywalker89** [kanboard/kanboard#3064]
**Please, do not create duplicate issues**

### Actual behaviour

In Board view, I know there are more closed tasks, but I see only one, I still see the closed tasks in Activity view ... on the "Done (1)! Headline, on the far right is a bold "7", not sure if that is all taks

### Expected behaviour

I should see all closed taks

### Steps to reproduce

no idea

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

    Application version: 1.0.38
    PHP version: 7.0.16
    PHP SAPI: cgi-fcgi
    OS version: Linux 3.10.0-514.6.1.el7.x86_64
    Database driver: mysql
    Database version: 5.5.54-cll
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by fguillot** [comment]
The closed tasks are visible on the board only if you set the filter to `status: closed`.
