### ISSUE TITLE
Suggestion: Make external links open in new tab

### ISSUE THREAD

**Issue by skywalker89** [kanboard/kanboard#3066]
HI, not having to use right click to open links would save me a lot of time

thx

**Comment by fguillot** [comment]
Not everyone have the same usage as you. I can find requests where people are asking the opposite. Sometimes, you would like to open link in the same tab and sometimes not. Since it's pretty hard to guess the intention of people, I prefer to leave the default behaviour of the web browser.

**Comment by skywalker89** [comment]
HI and thx,

well, I would argue that loosing my kanboard in the process makes no real sense, but hey, thats my point of view

perhaps a setting in option is a solution

Thx

**Comment by kvj** [comment]
If I narrow down this issue to external links only, then usually such links are opened in new tab

**Comment by skywalker89** [comment]
HI Konstantin, not in my case

**Comment by fguillot** [comment]
External task links are now opened in a new tab.
