### ISSUE TITLE
Timer Start/Stop in Tasks

### ISSUE THREAD

**Issue by hauserulrich** [kanboard/kanboard#3067]
### Actual behaviour

In Subtasks I have a button for starting and stopping the timer which supports the time tracking.

### Expected behaviour

Such a button would be very helpful for tasks without subtasks as well.

### Configuration

Application version: 1.0.36
PHP version: 5.6.30
PHP SAPI: fpm-fcgi
OS version: Linux 4.4.0-45-generic
Database driver: sqlite
Database version: 3.11

###Plugins
TimeTrackingEditor
Coverimage
Subtaskdate
Relationgraph

**Comment by ianc125** [comment]
I second this request

**Comment by toepi** [comment]
same as: #2283, but with more details.

**Comment by fguillot** [comment]
Duplicate with #1885

**Comment by hauserulrich** [comment]
It's OK to close it, being a duplicate indeed. I had searhed for keywords like start, stop etc., but hadn't found #1885 or #2283, sorry for the inconvenience.
