### ISSUE TITLE
'Hide this column' feature doesn't resize the height of the column / 'Hide tasks in this column in the dashboard' doesn't work

### ISSUE THREAD

**Issue by 2Belette** [kanboard/kanboard#3069]
### Actual behaviour

'Hide tasks in this column in the dashboard' when editing a column worked in the past but doesn't seem to work anymore.

When manually 'Hide this column' on a specific column, the tasks are hidden but the size (height) of the column remains the same. 

***EDIT*** This is working in 'Collapse Tasks" mode but not in 'Expand Task' mode.
Switching from Collapse to Expand mode temporarly fix the issue but opening kanboard in another browser windows suffers from the same issue..

### Expected behaviour

For the first item, it should auto hide the column from the dashboard.

For the second item, it should resize the height of the column to fit on the column with the bigger number of task instead of putting huge blank hole.

### Steps to reproduce

First item:

1. Tick 'Hide tasks in this column in the dashboard' when editing a column
2. Refresh the page -> column is not hidden

Second item:

1. Tick the 'Hide this column' on the largest number of items column
2. Scroll down -> big hole

### Configuration

    Application version: master
    PHP version: 7.0.13
    PHP SAPI: apache2handler
    OS version: Linux 4.8.10-gnu-1
    Database driver: sqlite
    Database version: 3.15.1
    Browser: Mozilla/5.0 (Windows NT 6.1; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by fguillot** [comment]
Can your provide a screenshot?

**Comment by 2Belette** [comment]
I have added a comment in EDIT in Actual behavior btw..

Working : 

![2017-02-22-17 58 05](https://cloud.githubusercontent.com/assets/2325706/23222864/83b61d70-f929-11e6-85d1-0049fc88a8d9.png)



Not working : (as you can see I needed to unzoom a lot in my browser to be able to see this huge 'hole')

![2017-02-22-17 59 41](https://cloud.githubusercontent.com/assets/2325706/23222938/cdd5f182-f929-11e6-8541-8452d10e03b9.png)

**Comment by kvj** [comment]
I can reproduce that

**Comment by 2Belette** [comment]
Thanks it is like I got the same issue even after the push...

**Comment by 2Belette** [comment]
First item:

    Tick 'Hide tasks in this column in the dashboard' when editing a column
    Refresh the page -> column is not hidden

Second item:

    Tick the 'Hide this column' on the largest number of items column
    Scroll down -> big hole


Hi,
I confirm that the first item is solved :) now the column is hidden by default

For the second item, I got the issue when I tick to the + sign to show the column and then click on "Hide this column" : the column is hidden properly but I got a "hole" on the same size as the maximum height of my Closed column. (like the screenshot I sent before)

**Comment by 2Belette** [comment]
Edit : First item doesn't seem to work anymore...
Hide tasks in this column is checked on column properties but accessing my dashboard show the column... I have to manually hide the column, anyone with the same issue?

**Comment by fguillot** [comment]
You should try again with the latest version of KB and if the problem persist reopen this issue.

**Comment by 2Belette** [comment]
Thanks! I just upgraded and I tested it again, and it was working a a minute or so and not anymore!
It was easy to see it as even if it was very fast, I was able to see my "Closed" column closed by itself when I loaded the board.

Now, it keeps opened even if I ticked the option to hide it in column properties.
I tried to untick and tick again, but same effect
