### ISSUE TITLE
Preview image/pdf on the card

### ISSUE THREAD

**Issue by fguillot** [kanboard/kanboard#307]
Feature request from the Twitter account: https://twitter.com/gruenler/status/518108481036255232

**Comment by lawre** [comment]
+1 on the request for an image thumbnail on the kanban card.  This feature is the *only* reason why I haven't ditched Trello yet.

**Comment by BlueTeck** [comment]
What do you think about this?

![kb_img](https://cloud.githubusercontent.com/assets/1961634/6430242/a233ba2c-c001-11e4-955b-af5bc8e7da7a.PNG)

**Comment by ashbike** [comment]
:+1:

**Comment by oparoz** [comment]
Looks good. Which image formats does it support?


   FROM: Timo
SENT: Sunday, 1 March 2015 10:57
TO: kanboard@noreply.github.com
REPLY TO: fguillot/kanboard
CC: Olivier Paroz
SUBJECT: Re: [kanboard] Preview image/pdf on the card (#307)

> What do you think about this?
>
> [1]
>
> —
> Reply to this email directly or view it on GitHub[2].



Liens:
------
[1]  
https://cloud.githubusercontent.com/assets/1961634/6430242/a233ba2c-c001-11e4-955b-af5bc8e7da7a.PNG
[2] https://github.com/fguillot/kanboard/issues/307#issuecomment-76590221

**Comment by BlueTeck** [comment]
at the moment kanboard supports image types, that are supported from php getimagesize https://github.com/fguillot/kanboard/blob/master/app/Model/File.php#L122 http://php.net/manual/de/function.getimagesize.php

This php command supports:
[IMAGETYPE_GIF] 
[IMAGETYPE_JPEG] 
[IMAGETYPE_PNG] 
[IMAGETYPE_SWF] 
[IMAGETYPE_PSD] 
[IMAGETYPE_BMP]
[IMAGETYPE_TIFF_II] 
[IMAGETYPE_TIFF_MM] 
[IMAGETYPE_JPC] 
[IMAGETYPE_JP2] 
[IMAGETYPE_JPX]
[IMAGETYPE_JB2] 
[IMAGETYPE_SWC] 
[IMAGETYPE_IFF] 
[IMAGETYPE_WBMP] 
[IMAGETYPE_JPEG2000] 
[IMAGETYPE_XBM] 
[IMAGETYPE_ICO]

**Comment by BlueTeck** [comment]
I have changed the layout, i think it looks much clearer, but you could see the whole width of the picture, but not the full height.
![kb_img](https://cloud.githubusercontent.com/assets/1961634/6431457/9ebf300e-c030-11e4-9000-5bcef27e420a.PNG)

**Comment by lawre** [comment]
Hi BlueTeck: I believe the original Twitter message was asking for a thumbnail image to show up "on" the kanban card viewed within the overall board view.  The method Trello uses is to pick the "last uploaded image" as the representative thumbnail to go on the kanban card.

Here is a sample image taken from my Trello board: ![trello](http://i.imgur.com/EAjXiKj.png)

**Comment by BlueTeck** [comment]
I will look into that:
- better attachment handling in task view
- better popup in task on board
- optional display last image on card
- thumbnails for better performance

**Comment by lawre** [comment]
From a usability perspective, I think a general option to set the default behavior of displaying an image thumbnail on all cards would be useful, probably more useful that an option within each card for those of us who use hundreds of cards.

BTW, thank you so much for picking this up BlueTeck

**Comment by BlueTeck** [comment]
@lawre i thought about an this option per project

**Comment by BlueTeck** [comment]
I think the general option is a bad idea, i like this:
![cover1](https://cloud.githubusercontent.com/assets/1961634/6637374/d633ac48-c979-11e4-9ba6-0713057badf4.PNG)
![cover2](https://cloud.githubusercontent.com/assets/1961634/6637375/d633fa2c-c979-11e4-86ac-621856a06d22.PNG)

You could select one image from the attachments as cover. So not every task with images has a cover image.

**Comment by lawre** [comment]
Fair enough.  It might work out well that way

**Comment by lawre** [comment]
BlueTek, can you make sure #511 is incorporated in your new feature?  I saw you commenting on #511, so I have my fingers crossed :)

**Comment by fguillot** [comment]
@lawre thumbnails are also available with screenshots

**Comment by BlueTeck** [comment]
as @fguillot said, its wirking fine with screenshots.

regarding the cover image i am playing around with it, but it isnt finished. https://github.com/BlueTeck/kanboard/tree/cover_image

**Comment by crabnky** [comment]
Hi,
Can we have images smaller that thumbnali not get resized? I have small icons attached to task and thumbnails do not look good :)

**Comment by BlueTeck** [comment]
It is me again ;)

The coverimage is coming via plugin, first version is a little bit ugly but working via plugin:

https://github.com/BlueTeck/kanboard_plugin_coverimage

![image](https://cloud.githubusercontent.com/assets/1961634/13931027/b9cfb19c-efa1-11e5-9a70-980d50ff4fe9.png)
![image](https://cloud.githubusercontent.com/assets/1961634/13931074/f3628876-efa1-11e5-90c7-bfd161b9487e.png)

Only working with the kanboard dev version or the next release.

**Comment by BlueTeck** [comment]
First Version released:
https://github.com/BlueTeck/kanboard_plugin_coverimage/releases/tag/0.1.0
Needs Kanboard _v1.0.27_ or the latest master
