### ISSUE TITLE
Cronjob doesn't recognise running environment CentOS

### ISSUE THREAD

**Issue by pfabri** [kanboard/kanboard#3072]
**Please, do not create duplicate issues**

### Actual behaviour

When trying to manually run `php cli cronjob` the following error message is returned:

    This script run only from the command line

Nothing else happens, i.e. the job does NOT get executed

### Expected behaviour

The cronjob should run.

### Steps to reproduce

1. run `php cli cronjob` from inside your `kanboard` installation directory on CentOS

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.37
- Database type and version: MySQL 5.6.34
- PHP version: 7.0.16
- OS: CentOS
- Browser: irrelevant

**Comment by aljawaid** [comment]
* KB Version: 1.0.39
* Database type and version: MySQL 5.5.54
* PHP version: 7.0.16
* OS: CentOS 7.3 x86_64 hyper-v – server

I have the same problem, then my VPS host advised me to use the below command for my cron.  They said it executes correctly, but Kanboard (I have installed it as Planner) gives me no updates or e-mails etc.  I was hoping something would happen every 6am like a summary e-mail or expired tasks notification etc.

`* 6 * * * cd /home/pewsedofitsc/public_html/planner && ./cli cronjob >/dev/null 2>&1`

**Comment by pfabri** [comment]
## Solution ##
Remove this from `cli`:

    if (php_sapi_name() !== 'cli') {
        echo 'This script run only from the command line'.PHP_EOL;
        exit(255);
    }

**Comment by aljawaid** [comment]
@pfabri solution for you, me or both of us?

Where is that code?  Can it just be commented out?

**Comment by aljawaid** [comment]
Looking into my server emails, I noticed my errors were this:

`Backgroundjobs are using system cron!`

**Comment by aljawaid** [comment]
@pfabri 's solution above works for me with:
`* 6 * * * cd /home/pewsedofitsc/public_html/planner && ./cli cronjob >/dev/null 2>&1`
