### ISSUE TITLE
New language translation - Croatian

### ISSUE THREAD

**Issue by cose385** [kanboard/kanboard#3076]
I made a new translation - where can I send it to be included in Kanboard?

**Comment by fguillot** [comment]
You could send a pull-request or attach the translation file here if you don't feel confortable to send a pull-request on Github.

Thank you

**Comment by cose385** [comment]
Currently I can't contribute to Github, so I'll attache the file - this is for Croatian language (locale hr_HR):

[translations.zip](https://github.com/kanboard/kanboard/files/801298/translations.zip)

This is the first version which works, but there's still some work to do on missing translations for less used options.

**Comment by fguillot** [comment]
Thank you! Your work is now integrated into Kanboard.
