### ISSUE TITLE
Board is squeezed to the left 

### ISSUE THREAD

**Issue by 2Belette** [kanboard/kanboard#3079]
### Actual behaviour

When the board is loading the entire dashboard squeeze to the left even if my browser is full screen.
I already tested with multiple browsers and PC, same behavior. 

### Expected behaviour

It should use the entire screen.

### Steps to reproduce

1. Log in to the application
2. Click on the board

### Notice
Clicking on the arrow to collapse/expand the Swimlanes make it full screen again...

### Configuration

    Application version: master
    PHP version: 7.0.13
    PHP SAPI: apache2handler
    OS version: Linux 4.8.10
    Database driver: sqlite
    Database version: 3.15.1
    Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0 (also tested on linux host)

### Screenshot
![sans titre](https://cloud.githubusercontent.com/assets/2325706/23340940/4c2178a0-fc3f-11e6-9faf-b5c064f3ccd8.png)

**Comment by fguillot** [comment]
Which version of master do you have? (commit hash)

**Comment by 2Belette** [comment]
Hi 

This commit:
2f0f996c1d46a7cf388093b971f6c756c8cc3933

On Sun, Feb 26, 2017 at 10:25:09AM -0800, Richard Bayerle wrote:
>Which version of master do you have? (commit hash)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kanboard/kanboard/issues/3079#issuecomment-282575764

-- 
Benoit

**Comment by fguillot** [comment]
This is really weird, I cannot reproduce the issue and I tested with 3 different browsers.

- Did you use the compact mode or have any collapsed column?
- Do you have old cookies/local storage data? clear the browser cache?
- Did you try in incognito mode?
- Do you have a browser extension that could break the Javascript?
- Do you have any Kanboard plugin installed?

**Comment by 2Belette** [comment]
On Mon, Feb 27, 2017 at 04:11:01PM -0800, Richard Bayerle wrote:
>This is really weird, I cannot reproduce the issue and I tested with 3 different browsers.
>
>- Did you use the compact mode or have any collapsed column?

I tried both, same issue on both

>- Do you have old cookies/local storage data? clear the browser cache?

I cleared the cache

>- Did you try in incognito mode?

I tried as well same issue

>- Do you have a browser extension that could break the Javascript?

Nope

>- Do you have any Kanboard plugin installed?

I have ColumnGroup, I uninstalled it and same thing...

On another browser on Linux I only see this happen during the loading of 
task (I have more than 500 tasks) so on wireless it couuld take 10sec to 
load and during the loading I see litle by litle the column sqeezed to 
the left and after loading finished it goes straight to full screen (use 
of all space on the browser)...

Perhaps something related to Swimlanes as on the other Browser on MacOS 
this is working back when I collaspe/expand the first Swimlanes...

>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kanboard/kanboard/issues/3079#issuecomment-282899544

-- 
Benoit

**Comment by fguillot** [comment]
I have never been able to reproduce this issue after all this time. You seems to be the only one to have this problem. Unfortunately, you will have to investigate by yourself and potentially submit a patch.

**Comment by 2Belette** [comment]
Thanks for your reply, I still experiment this issue even with a brand new computer under a fresh iceweasel installation.. perhaps I would need to reinstall entirely kanboard..but I don't know if this would solve the issue. I also notice the hiding column not kept even if the option is ticked in the column property, just for information as I don't know if knowing theses two issues can ring a bell on your side
