### ISSUE TITLE
Cannot attach documents to tasks that have comments

### ISSUE THREAD

**Issue by Cinderos** [kanboard/kanboard#3083]
I apologize in advance if this is a duplicate, but I have tried searching and cannot find a solution to this problem.

### Actual Behavior

After adding a comment to a task I can no longer add file attachments. After I delete the comment from the task, I can again add attachments.

### Expected Behavior

I should be able to add attachments to a task when it has comments.

### Steps to Reproduce

1. Log into the application.
2. Create a new task.
3. Click _Attach Document_
4. Select a document
5. Click _Upload Files_
6. Note - the file is now attached to the task.
7. Click _Add a Comment_
8. Fill in the comment and click _Save_
9. Click _Attach Document_
10. Select a document
11. __*Upload Files* will be grayed out and you cannot click it__
12. Click _Remove_ on the comment that was added.
13. Click _Yes_ to delete the comment
14. Click _Attach Document_
15. Select the same document you tried to upload in step 10
16. Click _Attach Document_
17. The file is now attached to the Task

### Other Notes

Yes, the permissions on my data directory are correct. My web user is www-data and it is the owner with full access the /var/www/kanboard/data/

I have even tried chmod -R 777 to the directory, but it  still presents the same behavior.

### Configuration

Application version: __1.0.39__
PHP version: __7.0.15-0ubuntu0.16.04.2__
PHP SAPI: __apache2handler__
OS version: __Linux 4.4.0-62-generic__
Database driver: __sqlite__
Database version: __3.11.0__
Browser: __Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36__

**Comment by fguillot** [comment]
This issue has been already fixed in version 1.0.40

**Comment by Cinderos** [comment]
Cool sorry about that, I very recently deployed the board and figured I had the latest version. Again apologies for the duplicate.
