### ISSUE TITLE
Docket pull error

### ISSUE THREAD

**Issue by onedr0p** [kanboard/kanboard#3084]
```
root@mercury:~# docker pull kanboard/kanboard
Using default tag: latest
Error response from daemon: manifest for kanboard/kanboard:latest not found
```

I've tried on 3 other systems using docker version 1.13.1. I also tried tag stable but no go

**Comment by fguillot** [comment]
AWS S3 is down today and Docker hub use this service, that nothing to do with Kanboard.

See: http://status.docker.com/pages/history/533c6539221ae15e3f000031 and https://status.aws.amazon.com

**Comment by onedr0p** [comment]
Thanks I didn't know AWS killed half the internet today ;)
