### ISSUE TITLE
Move task position ignores "Insert after this task"

### ISSUE THREAD

**Issue by cose385** [kanboard/kanboard#3086]
### Actual behaviour

When in the task, clicking on the "Move position" opens "Move task to another position on the board" screen where you can choose destination Column, Swimlane, task list in that Column/Swimlane and option whether task is to be moved before or after chosen destination task.

Regardless of whether one chooses option "Insert before this task" or "Insert after this task", the task is always moved before the destination task.

### Expected behaviour

When option "Insert after this task" is chosen, task is supposed to be moved after chosen task.

### Steps to reproduce

1. Open some task in the project
2. Click "Move positions"
3. Choose some other column with tasks in it
4. Choose task from the list
5. Click "Insert after this task"
6. Click "Save"

The task is moved but instead of being after chosen task - it is moved before it.

### Configuration

Application version: 1.0.40
PHP version: 5.6.12
PHP SAPI: apache2handler
OS version: Windows NT 6.1
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
