### ISSUE TITLE
File size of assets/js/vendor.min.js is more than 1 MB

### ISSUE THREAD

**Issue by ngosang** [kanboard/kanboard#3087]
The file size of **assets/js/vendor.min.js** is more than 1 MB. This is too much for slow 3G connections. Could you check the file contents to see if all included libraries are necessary?
Maybe some libraries are necessary but only for advanced features like plugins, etc.. In this case you could have one .js file for core features (and less size) and other with advanced features when required.

### Configuration
    Application version: master
    PHP version: 7.0.15-0ubuntu0.16.04.2
    PHP SAPI: apache2handler
    OS version: Linux 4.4.0-64-generic
    Database driver: mysql
    Database version: 5.7.17-0ubuntu0.16.04.1
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by cose385** [comment]
If everything is properly set up - that file should be loaded only once and afterwards browser will use it from local cache and should be no problem in later usage.

**Comment by ngosang** [comment]
I know but smartphone browsers usually have very little cache space. It's highly probable next time you visit kanboard the cache is empty again.

**Comment by cose385** [comment]
Ideal solution would be to have completely separated .js for mobile browsers with minimal functionality - or maybe even different template set

**Comment by fguillot** [comment]
Did you configure your webserver to gzip the *.js files?

**Comment by ngosang** [comment]
> Did you configure your webserver to gzip the *.js files?

Yes I did, 317 KB gziped. Still too much.

**Comment by fguillot** [comment]
Since the calendar and the gantt chart have been moved to plugins, the size is down to 869KB.

The list of external dependencies are defined here: https://github.com/kanboard/kanboard/blob/master/gulpfile.js#L30-L51. Anyone can contribute to reduce that.
