### ISSUE TITLE
Remove file from task doesn't work

### ISSUE THREAD

**Issue by thob** [kanboard/kanboard#3088]
### Actual behaviour

After clicking **Remove** I get the following without any option to delete the file. _I'm using upload to AMZN S3_

![removefile](https://cloud.githubusercontent.com/assets/755337/23458197/74eb5eac-fe7b-11e6-8b9e-aba94c10c7b8.png)

### Expected behaviour

Dialougue for removing the file

### Configuration

Version: 1.0.40
PHP Version: 7.1.0
PHP SAPI: cgi-fcgi
OS Version: Linux 2.6.32-642.6.2.el6.x86_64
Datenbanktreiber: mysql
Datenbank Version: 5.1.73-log
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.88 Safari/537.36 Vivaldi/1.7.735.46

**Comment by jansch2015** [comment]
I have the same problem... I do see a dialogue though, but when I click "Yes", I just see the wheel spinning forever :)

**Comment by fguillot** [comment]
Do you use some old plugins that are not compatible with the latest version of Kanboard?

**Comment by thob** [comment]
You were right, after deactivating the [Milestone plugin](https://github.com/oliviermaridat/kanboard-milestone-plugin) I got the dialogue and was able to remove the file,

**Comment by fguillot** [comment]
Closing this since you reported the issue to the plugin creator.
