### ISSUE TITLE
Filter Concatenation not working correct

### ISSUE THREAD

**Issue by juergenniessen** [kanboard/kanboard#3089]
### Actual behaviour

Filter >assignee:"J N" completed:>="today-7 days"< is working,
Filter >completed:>="today-7 days" assignee:"J N"< is not working

### Expected behaviour

Both Filter should return the same resultset

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

    Version: 1.0.40
    PHP Version: 5.5.9-1ubuntu4.11
    PHP SAPI: apache2handler
    OS Version: Linux 3.2.0-70-generic
    Datenbanktreiber: mysql
    Datenbank Version: 5.5.44-0ubuntu0.14.04.1
    Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
