### ISSUE TITLE
iCal Feed: DTEND should be DTSTART + 1 Day

### ISSUE THREAD

**Issue by juergenniessen** [kanboard/kanboard#3090]
### Actual behaviour

Tasks disappear on Thunderbirds dayplan on the duedate.

### Expected behaviour

The Task mustn't disapear on the duedate

### Possible solution

Change the DTEND to DTSTART + 1 Day in the iCal Feed

### Steps to reproduce

- Start Thunderbird with Lighning Addon
- Add your iCal Feed as new Calendar
- Activate the Dayview on the first page of Thunderbird with F11 e.g.
- Notice, that tommorow's tasks are listet under "Tomorrow"
- Notice, that todays's task are not listet under "Today"

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

Version: 1.0.40
PHP Version: 5.5.9-1ubuntu4.11
PHP SAPI: apache2handler
OS Version: Linux 3.2.0-70-generic
Datenbanktreiber: mysql
Datenbank Version: 5.5.44-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by fguillot** [comment]
With the latest version of Kanboard (1.1.0), the iCal feed has been improved. This is working as expected for me with Apple Calendar. You should try again.
