### ISSUE TITLE
Analytics with custom filter

### ISSUE THREAD

**Issue by juergenniessen** [kanboard/kanboard#3091]
Feature request:

### Expected behaviour

It would be great, if analytics could use the actual used filter or if you could define a custom filter.

Without this, you can't analyse "User repartition" for closed task e.g.

### Configuration

Version: 1.0.40
PHP Version: 5.5.9-1ubuntu4.11
PHP SAPI: apache2handler
OS Version: Linux 3.2.0-70-generic
Datenbanktreiber: mysql
Datenbank Version: 5.5.44-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited.

Thank you for your understanding
