### ISSUE TITLE
"Time spent" calculation incorrect for Export (CSV)

### ISSUE THREAD

**Issue by mrkafk** [kanboard/kanboard#3093]
## Actual behaviour

The "Time spent in column" calculation in Transitions is correct (double-click a task, click Transitions):
![task_spent_in_column_correct](https://cloud.githubusercontent.com/assets/593219/23563846/c2394c4a-0048-11e7-821f-c05c974ac70a.png)

However, the time for the same task calculated in Export (board view, expand Menu, click Exports, select Transitions, select dates) is incorrect:

[test_task_bad_spent_time_calc.txt](https://github.com/kanboard/kanboard/files/817590/test_task_bad_spent_time_calc.txt)

### Expected behaviour

I get the same "time spent" data in exported CSV for particular task as the data in task/Transitions/Time spent in column view.

### Steps to reproduce

1. log into app
2. create a task 
3. drag the task between columns in order as seen on the screenshot, from bottom to top, giving each transition some time of course.
4. Export | Transitions as described above, compare with task | Transitions. 

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

Application version: 1.0.39
PHP version: 5.4.45-0+deb7u7
PHP SAPI: apache2handler
OS version: Linux 3.2.0-4-amd64
Database driver: postgres
Database version: 9.5.6
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.11 (KHTML, like Gecko) Ubuntu/11.10 Chromium/27.0.1453.93 Chrome/27.0.1453.93 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
