### ISSUE TITLE
Sum up estimated hours in column header

### ISSUE THREAD

**Issue by jniggemann** [kanboard/kanboard#3094]
Great tool, absolutely love it! We use KB for Scrum and realized that it would facilitate our Scrum sprint planning, if the estimated hours would be summed up in the column header.

**Comment by ericcswanson** [comment]
I use it similarly; estimated and consumed hours totals for columns would be fantastic.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
