### ISSUE TITLE
WIP Limit Enforcer

### ISSUE THREAD

**Issue by jregusci** [kanboard/kanboard#3095]
Hi Frederic. As allways, great work evolving kanboard!

This issue is a feture request that i think would be very useful and it's about the WIP Limit to the columns.

Right now when you set a WIP Limit, if that limit is broken the column gets highlighted in red. In order to help the users limit the work and not overcommit I propose the following:

1- Add a new flag in the column configuration (something like **force wip limit**)
2- If that flag is set to true, when the user tries to move a task to that column and that breaks the limit, the change is rolled back and the task remains where it was. Perhaps show a message to the user.
If that flag is set to false, the system behaves like it does now.

This way, you can enforce certain wip limit policies for some columns and perhaps be more flexible in others.

What do you think about it?

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited.

Thank you for your understanding
