### ISSUE TITLE
Docker Stop/Restart Command Locking up Docker Completely - Kill Command Works Though

### ISSUE THREAD

**Issue by ianc125** [kanboard/kanboard#3096]
### Actual behaviour

I have Kanboard running in a docker container. When I got to stop or restart the container it locks up my docker environment completely. When I run the kill container command this works no problem.

These commands lock it up:
docker stop "Container Name"
docker restart "Container Name"

This command works:
docker kill "Container Name"

I noticed when I run the stop/restart command most of the processes stop correctly, but it seems like the processes running with s6 process manager seem to be the ones getting stuck.

It may be the difference in the what happens when docker does a kill versus a stop command:
http://superuser.com/questions/756999/whats-the-difference-between-docker-stop-and-docker-kill

Docker stop command  never seems to hit the sigkill.

### Expected behaviour

Container should stop / restart after a graceful shutdown.

### Steps to reproduce

run kanboard on docker and run on the following commands:
docker stop "Container Name"
docker restart "Container Name"

### Configuration

Application version: 1.0.40
PHP version: 7.0.9
PHP SAPI: fpm-fcgi
OS version: Linux 3.10.102
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

Thanks for your help, and for kanboard awesome job with it.

Ian

**Comment by fguillot** [comment]
Unfortunately, I was never able to reproduce this issue after all this time, so I'm closing this ticket now.
