### ISSUE TITLE
[FR] More flexibility for defining 'overdue'

### ISSUE THREAD

**Issue by dave2** [kanboard/kanboard#3099]
Our kanban process has us put tasks into a "Done" column, but not close them until the retro is completed at the end of the sprint (so we have visibility of done as it progresses through the sprint). This means if we put a due date of anything other than the end of the sprint, we get email notifications about overdue tasks which have been placed in "Done".

We'd like a sort of soft-close option, or a "done" state, or some way of saying that tasks in a column are "done" for the purpose of overdue notification. 

Thanks!

**Comment by tmihob** [comment]
Hello, for me, I added an automatic action to close a task in a specific column. 
Is not that the right way to go?
Then, if you want to see the closed jobs, you just have to remove the filter to display all.

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
