### ISSUE TITLE
Gantt chart - chrome ram limit reached

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#3101]
### Actual behaviour

Our Kanboard has +400 open tasks scattered over a few swimlanes and columns.
When I open the Gantt chart view for all tasks, chrome reaches it's ram limit and won't load the chart.

### Expected behaviour

The Gantt chart should be displayed.

### Steps to reproduce

1. create lots of tasks
2. try to view the gantt chart.

### Configuration

Application version: 1.0.38
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

Thank you for your understanding
