### ISSUE TITLE
Copy project fails

### ISSUE THREAD

**Issue by jniggemann** [kanboard/kanboard#3102]
### Actual behaviour
New project is not created, instead, the form is re-displayed with all checkboxes enabled.

### Expected behaviour

New project is created and only the data selected via checkboxes is copied over to the new project.

### Steps to reproduce

* Click "add new project"
* click "duplicate settings from another project"
* unselect all checkboxes but "tags"
* click save

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version:KB v1.0.36 (as well as 1.0.40)
- Database type and version: sqlite 3.8.7.1
- PHP version: 5.6.30-0+deb8u1
- OS: Debian 8
- Browser: Chrome 58

**Comment by fguillot** [comment]
I'm not able to reproduce this problem. You should give more details when the problem occurs, for example the log files. Otherwise, it is not really possible to guess the origin of the problem.

**Comment by jniggemann** [comment]
Forgot about this one, else I had added more info sooner...
I'm no longer able to reproduce this, so I'm just closing this.
