### ISSUE TITLE
Autosave comment from task to avoid loss of data

### ISSUE THREAD

**Issue by joandre** [kanboard/kanboard#3103]
### Actual behaviour

When I right a comment in a task and I have connection troubles (or do F5), I lose my work if I try to save. 

### Expected behaviour

- I think the autosave idea from this issue [#2177](https://github.com/kanboard/kanboard/issues/2177) could be a good idea to avoid a lot of frustration. So no matter what happens (connection issues or inattention) , your work will be saved from the last real time backup point. 

- Another good feature would be a clearer indication that you have been disconnected.

### Steps to reproduce

1. Open a task
2. Start writing a comment
3. Disconnect from internet (or do F5)
4. Try to save your comment
5. Your comment is lost

Other behaviour: 

1. Click on add a comment for a task
2. Start writing a comment
3. Disconnect from internet
4. Try to save your comment
5. It tries to save indefinitely

### Configuration

- Kanboard version: 1.0.38
- Database type and version: 
- PHP version:
- OS:
- Browser: IE and Mozilla

**Comment by rautamiekka** [comment]
The 2177 you referred was fixed already.

And there's no such browser as Mozilla, not been for, what, 15 years without checking.

**Comment by fguillot** [comment]
Pretty much the same as #2109

**Comment by joandre** [comment]
Yes indeed. I did not see this one. But I think the main behavior reported was fixed in 1.0.34 (cf [#2177](https://github.com/kanboard/kanboard/issues/2177)). Do you want me to close this issue and add a comment in the one you referred to in order to add the connection issue in the reasons to implement this feature or should I keep it open ?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
