### ISSUE TITLE
Impossible to import Kanboard tasks on Outlook 2013

### ISSUE THREAD

**Issue by yannicka** [kanboard/kanboard#3106]
### Actual behaviour

When I try to import Kanboard calendar to Outlook with the given link, the tasks does not import: the calendar is created but empty.

I've the following errors:
```
La tâche « Abonnements à des calendriers Internet » a signalé une erreur (0x0004001A) :
« Le VEVENT « n°17 Task name » défini près de la ligne 7 contient une propriété qui fait
référence à un fuseau horaire non déclaré dont le TZID est « Europe/Paris ». Cependant,
Outlook a trouvé un substitut approximatif. Notez que certains de vos rendez-vous
peuvent présenter un décalage d'une heure. Double-cliquez pour ouvrir cet élément. »
```

```
La tâche « Abonnements à des calendriers Internet » a signalé une erreur (0x0004001A) :
« Le VEVENT « n°17 Task name » défini près de la ligne 7 contient une propriété qui fait
référence à un fuseau horaire non déclaré dont le TZID est « Europe/Paris ». Cependant,
Outlook a trouvé un substitut approximatif. Notez que certains de vos rendez-vous
peuvent présenter un décalage d'une heure. Double-cliquez pour ouvrir cet élément. »
```

### Expected behaviour

I want the Kanboard tasks to be visible on my Outlook calendar.

### Steps to reproduce

1. Create a project with a task with a "start date" and a "due date" assigned to you
2. Enable public access on the project
3. Enable public access on your account
4. Get the public access "iCal" of your account (URL like this: "site.com/?controller=ICalendarController&action=user&token=TOKEN")
5. On Outlook: "Open a calendar" then "From internet"
6. Input the URL
7. Confirm

#### Kanboard

- Kanboard version: 1.0.40
- Database type and version:  mysql 5.7.14-log
- PHP version:  7.0.15
- OS: Linux 3.14.79-grsec-hosting-web-3.14

#### My computer
- OS: Windows 8.1
- Browser: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
- Outlook 2013

If I missed some information, please tell me.

**Comment by hammer-of-thor** [comment]
I can confirm this issue

**Comment by hammer-of-thor** [comment]
Did some more research, this also happens with Outlook 2007 and gmail.

**Comment by fguillot** [comment]
Unfortunately, I do not have Outlook 2013 to be able to reproduce this issue. Someone else have to fix this problem.

**Comment by fguillot** [comment]
With the latest version of Kanboard (1.1.0). The iCal feed has been improved. Perhaps, that fix your issue with Outlook. Since I do not have Outlook, I cannot really troubleshoot this problem.

**Comment by yannicka** [comment]
It seems that now the first synchronization works, but it never resynchronize.
