### ISSUE TITLE
Unable to attach document in task if there is a task comment

### ISSUE THREAD

**Issue by freeblue** [kanboard/kanboard#3108]
### Actual behaviour

If we try to attach a document in a task that already has one comment, the upload button stay unclickable (greyed), so it's impossible to attach the document

### Expected behaviour

It should be possible to attach document inside a task even if there are comments in this task

### Steps to reproduce

1. Log in to the application as the administrative user
2. Click on an existing project
3. add a task (whatever column) : task title is enough
4. attach a document : this work
5. add a comment
6. attach a document : the upload button stay unclickable (greyed), so it's impossible to attach the document
7. delete the previous comment (5)
8. try to attach the previous document (6): the upload button is clickable and document is uploaded.

### Configuration

    Application version: 1.0.39
    PHP version: 5.6.30-0+deb8u1
    PHP SAPI: apache2handler
    OS version: Linux 3.16.0-4-amd64
    Database driver: postgres
    Database version: 9.4.10
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by fguillot** [comment]
This issue has been fixed in 1.0.40. Please, upgrade.

**Comment by freeblue** [comment]
Merci Frederic
