### ISSUE TITLE
API call moveTaskPosition does not update transitions table

### ISSUE THREAD

**Issue by KyleBrandon** [kanboard/kanboard#3111]
### Actual behaviour

I've created an integration with our case management system that uses the moveTaskPosition API call to move cases or tasks from one column to another.  I noticed that when viewing the tasks Transitions (http://localhost/project/6/task/714/transitions) the move action does not show up.  When looking in the sqlite database I've verified that an entry does not get created. 
When I manually move the task an entry in the transitions table is created and it shows in the UI.

### Expected behaviour
I would expect that API calls would create this history entry so that we could correctly integrate other systems.

### Steps to reproduce

from kanboard import Kanboard

KANBOARD_API_URL = 'http://localhost/jsonrpc.php'
KANBOARD_USERNAME = 'jsonrpc'
KANBOARD_API_TOKEN = 'xxx'

kb = Kanboard(KANBOARD_API_URL, KANBOARD_USERNAME, KANBOARD_API_TOKEN)
kb.move_task_position(project_id=6, task_id=714, column_id=40, position=1, swimlane_id=5)

Once you execute the Python script you'll see that the task was moved but on opening the task's transitions it won't have a record indicating it was moved.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

Application version: master
PHP version: 7.0.9
PHP SAPI: fpm-fcgi
OS version: Linux 4.9.12-moby
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by KyleBrandon** [comment]
OK looks like a problem with using the Application API.  If I use the User API (user account) then the transition table is updated.  I take it that the reason for this is that the user that moved the card is stored with the transition.  Seems like this should be an operation supported by the Application API.

**Comment by fguillot** [comment]
The user "jsonrpc" is not a real user, the transitions table requires a logged Kanboard user to create a record.
