### ISSUE TITLE
Price a task ?

### ISSUE THREAD

**Issue by TheCloud** [kanboard/kanboard#3112]
I was wondering if anyone is giving monetary values to tasks for customer budgeting.

I know there is a subtask plugin, but what I'm thinking is more related on using Kanboard in a sales process when you might need to manage the value of a prospect/lead/project/feature...

Anyone has manage it before ?

**Comment by fguillot** [comment]
To avoid cluttering the bug tracker, there is now a forum for open discussions: https://forum.kanboard.net/
