### ISSUE TITLE
"Move position" dialog should have default values set to current

### ISSUE THREAD

**Issue by fourier** [kanboard/kanboard#3114]
### Actual behavior

The dialog is always first swimlane and first column.

### Expected behaviour

 It is better to have them set to the current values for the task.

### Steps to reproduce

1. Have a board with several swimlanes.
2. Open any task which is *not* in the first swimlane and *not* in the first column.
3. Open 'Move task' dialog
4. Observe the values for Swimlane and columns are the 1st swimlane and 1st column

### Configuration

    Application version: 1.0.39
    PHP version: 5.6.29-0+deb8u1
    PHP SAPI: apache2handler
    OS version: Linux 3.16.0-4-amd64
    Database driver: sqlite
    Database version: 3.8.7.1
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by kousu** [comment]
I found this super inconvenient too, @fourier ! So many times did we accidentally bounce things back to Backlog when we were just trying to change their Swimlane (which we are using for our categorization), and so many other times did we bounce things back to our Default swimlane when we were just trying to advance their process.

I've fixed it. Hopefully it gets committed and pushed out to you soon; or you can just merge my patch manually.

**Comment by fguillot** [comment]
Fixed in PR #3680
