### ISSUE TITLE
Error migration to 122 

### ISSUE THREAD

**Issue by bdrayer** [kanboard/kanboard#3115]
Hi,

### Actual behaviour
I try to upgrade to the last version of kanboard but I get an error which I cannot fix.

Internal Error: Unable to run SQL migrations: Running migration \Schema\version_122, SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Default swimlane-40' for key 'name' (You may have to fix it manually)

### Expected behaviour

What do I need to check to correct this? I already check that there was no 'NULL' on default_swimlane on project

### Configuration

- Kanboard version: 1.040 (previously 1.0.32)
- Database type and version: Mysql 
- PHP version: Ver 14.14 Distrib 5.5.43
- OS: Debian
- Browser: CLI or firefox

**Comment by bdrayer** [comment]
I did a migration from SQLite to MySQL a long time ago. Perhaps there is errors in my SQL schema, ...

Any tools to check the SQL tables integrity?

**Comment by ibedon** [comment]
I have the same issue, I went through the same migration long before from SQLite to MySQL and now that I tried the latest version migration. it is giving me that error. Please help

**Comment by bdrayer** [comment]
someone has created a "Default Swimlane" on a Project, ... It's the reason of the upgrade problem.

Thanks a lot for your help

**Comment by ibedon** [comment]
Hi :
Does it mean have to check in all projects if some has created a Default swimlane wih the name "Default swimlane"



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by bdrayer** [comment]
You will have to check in the table Swimlanes that there is no Swimlane with the name "Default Swimlane"

**Comment by ibedon** [comment]
Thank you so much ! You guys are awesome



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by fguillot** [comment]
I assume that this problem is solved.

**Comment by ibedon** [comment]
Thanks Frederic.. i am running the 41 version now. Just as feedback i've been getting from users is that the new dashboard is not as easy to read and it looks busy as supposed to the previous version it is more clean and simple.

other than that the product is amazing. Thanks again

Sent from my Samsung Galaxy smartphone.

-------- Original message --------
