### ISSUE TITLE
Duplicate emails when mentioned in a comment of a task you own

### ISSUE THREAD

**Issue by jsteel44** [kanboard/kanboard#3118]
### Actual behaviour

User1 gets two emails when someone comments on his task and does an @User1 in the comment.

Subject of email 1: [Board] You were mentioned in a comment on the task #264
Subject of email 2: [Board] New comment on task #264

### Expected behaviour

User1 should get one email about the comment.

For eg just: [Board] New comment on task #264

### Steps to reproduce

User2 comments on User1's task and does an "@User1" in the comment.

### Configuration

    Application version: 1.0.40
    PHP version: 5.4.16
    PHP SAPI: apache2handler
    OS version: Linux 3.10.0-514.6.2.el7.x86_64
    Database driver: mysql
    Database version: 5.5.52-MariaDB
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:45.9) Gecko/20100101 Goanna/3.0 Firefox/45.9 PaleMoon/27.1.2

**Comment by jsteel44** [comment]
Just to confirm, this issue is still present in the latest version 1.2.0. Thanks

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
