### ISSUE TITLE
Add a notification option when assigned to a sub-task

### ISSUE THREAD

**Issue by jsteel44** [kanboard/kanboard#3120]
If I only have notifications on for tasks I create and own, then I do not get an email when someone assigns me to a sub-task of a task that I did not create or own.

Either the sub-task should be considered a task that I am assigned to and send me an email, or there should be another notification option to opt-in to emails when assigned to sub-tasks.

Thanks

**Comment by rautamiekka** [comment]
I think a separate option to be notified of subtasks would be better, as it serves environments where the assignee of a subtask can be expected to change but won't bother env where that likely wouldn't happen.

**Comment by jsteel44** [comment]
Sure, either way it would be nice to be able to choose to get notified.

**Comment by crisicon** [comment]
willing to sponsor this, if someone wants to work on it.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
