### ISSUE TITLE
Unable to load GDoc file name when import GDoc by "external link"

### ISSUE THREAD

**Issue by IcelmServices** [kanboard/kanboard#3122]
### Actual behaviour
When you import an "external link" thant consists of a Google drive file, does not appear the filename present in Google Drive, but just "Google Docs - create and edit documents online, for free."
If I link other urls, usually the correct webpage name appears.
No change if you select "auto" or "Link web"
We use kanboard with Google Authentication.

### Expected behaviour
When the wizard load the URL, the real file name should appear in the Kanboard database.
As new feature, would be interesting to use drap&drop to insert external link in projects and tasks.

### Configuration
- Versione dell'applicazione: 1.0.36
- Versione PHP: 5.4.34
- PHP SAPI: apache2handler
- Versione OS: Linux 2.6.32-042stab120.11
- Driver per Database sqlite
- Versione database: 3.6.20
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by fguillot** [comment]
You have to use the shareable link of your Google document to see the title.

This feature is not able to access to private Google documents.
