### ISSUE TITLE
ProjectRoleController: how to limit all task view to some users???

### ISSUE THREAD

**Issue by IcelmServices** [kanboard/kanboard#3123]
### Actual behaviour
Kanboard has 3 permissions roles for each project:
- manager
- member
- observer
Then, now it's possible, to create new roles by function "ProjectRoleController"
All roles view all tasks inside the related project.

### Expected behaviour
We'd like to have the chanche to assign users a news role, called "Limited user".
The "limited user" should:
- view and edit JUST the tasks assigned
- view and edit JUST the tasks created  by himself (optional)
We tried to get this step by using the function "ProjectRoleController" but even if you create a new role, the new role can view always all the project's tasks.
It should be possibile to achive this goal, adding a "view limitation" option in "ProjectRoleController"

We think it's important to have users with a limited view of the tasks to better manage sales: in fact, in these situation, it's not simply to share all tasks to all project members; and if you have to creat several project according to view's rights, it' very hard for sales manager/ project manager.

We don't want ti change kanban approach, but we think it's useful to have the chanche to restrict view to some users.

### Configuration
Versione dell'applicazione: 1.0.36
Versione PHP: 5.4.34
PHP SAPI: apache2handler
Versione OS: Linux 2.6.32-042stab120.11
Driver per Database sqlite
Versione database: 3.6.20
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by rautamiekka** [comment]
I think `Assigned Only` would be more clear. Other than that it's a good idea.

**Comment by IcelmServices** [comment]
Dear Frederic,
we could subsidize this feature's development.
how can we contact You for details?
Furthermore: in out country, companies as your can receive government founds to develop projects on cloud as Kanboard
We're waiting Your feedback

**Comment by IcelmServices** [comment]
Dear Frederic,
we could subsidize this feature's development.
how can we contact You for details?
Furthermore: in out country, companies as your can receive government founds to develop projects on cloud as Kanboard
We're waiting Your feedback

**Comment by IcelmServices** [comment]
Dear Frederic,
**we CAN subsidize this feature's development**.
how can we contact You for details?
Furthermore: in out country, companies as your can receive government founds to develop projects on cloud as Kanboard
We're waiting Your feedback
THANKS IN ADVANCE!

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
