### ISSUE TITLE
TaskListController: how to customize the table view

### ISSUE THREAD

**Issue by IcelmServices** [kanboard/kanboard#3124]
### Actual behaviour
Kanboard has 4 standard view
- BoardView
- CalendarController
- TaskListController
- TaskGanttController
There is no way to customize the views, especially TaskListController

### Expected behaviour
It's useful to have in the backened menù, the chance to select which columns appear, and the order.
In basic alternative, it's necessary to show the task field "riferimento" in TaskListController

THANKS!

### Configuration
Versione dell'applicazione: 1.0.36
Versione PHP: 5.4.34
PHP SAPI: apache2handler
Versione OS: Linux 2.6.32-042stab120.11
Driver per Database sqlite
Versione database: 3.6.20
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by fguillot** [comment]
You could write a plugin that override the templates. See https://kanboard.net/documentation/plugins
