### ISSUE TITLE
[Feature Request] date ranges on Activity Feed

### ISSUE THREAD

**Issue by Elfmagi** [kanboard/kanboard#3125]
Is it possible for us to get a toggle for date ranges on Activity Feed, and also on the Overview? Currently it only shows you the past 3 days on both.
We would like for this to be customizable up to 30 days at a time.

**Comment by Budpitchford** [comment]
I will pay for this to be added. Will payment expedite the process? I have a great need to be able to pull reports of the comments by users. i.e.
April 1- April 10
All comments by user Daniel
Thanks.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
