### ISSUE TITLE
@ mentions are case sensitive

### ISSUE THREAD

**Issue by george-viaud** [kanboard/kanboard#3126]
@ mentions are currently case-sensitive.

This has caused issues for us when people believe they are mentioning a person in a comment but are actually not due to incorrect case.

It would be great if mentions were case-neuter 

Note: I believe user-names are also case sensitive?  Not sure why, but if so there may be minor ramifications when creating new users so that user-names that are not allowed to duplicate independent of case variation.

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
