### ISSUE TITLE
SMTP email appears to be blocking

### ISSUE THREAD

**Issue by george-viaud** [kanboard/kanboard#3127]
When configured to send email via SMTP, the operation appears to be blocking and thereby slows down some operations that fire off one or more email messages.

This is more apparent when a fairly slow SMTP server is configured or when multiple parties are @ mentioned in a comment.

In my personal experience this can take upwards of 10 seconds which is detrimental to workflow.

Two possible solutions:
1) Move mail to CRON process or similar
2) Use some sort of pseudo multi-threading / forking.  (I have some ugly examples of this in PHP, PM me for details if desired)

**Comment by fguillot** [comment]
See https://kanboard.net/documentation/performances

**Comment by george-viaud** [comment]
Many thanks!  This worked great.

I am running Ubuntu server 14.04 and used beanstalk w/ the Kanboard plugin for the same.

I installed supervisord and ran it with crontab on @reboot which is flawed, would rather run it via init.d but am sadly not an expert in the same or have time to play with it at the moment, will likely correct this by using systemd after upgrading this box to 16.04 or higher.

A bit of a pain for me personally to configure but I've had worse.  It does the trick!  

Thank you

**Comment by rautamiekka** [comment]
@george-viaud Just noticed your at mention points to another user who has nothing to do with this.
