### ISSUE TITLE
The 2-factor authentication could use a correction

### ISSUE THREAD

**Issue by rautamiekka** [kanboard/kanboard#3128]
### Actual behaviour
Just now I were locked out of friend's Kanboard installation due to me falsely believing Google Authenticator used same code for both hers and my Kanboard installation, so I asked her to do something about my acc on hers, such as disable the 2-factor. She did, but refreshing and changing the address didn't make Kanboard stop asking for the imaginatory code.

Then it was when I figured I should be able to logoff without cookie clearance or touching the db, and I logged off from the top-right corner menu which offered other options I didn't test.

### Expected behaviour
The way this seems to work after Kanboard verifies my logins are good is Kanboard checks various other things, including the 2-factor, and when it's 2-factor's turn, it takes note it's 2-factor's turn and sticks to it until logoff-then-relogin. Instead of only relying to the note of it being 2-factor's turn,
1) check if it's 2-factor's turn
2) check if 2-factor is disabled
3.1) **if 2-factor is still enabled and it's 2-factor's turn, continue demanding the code as normal**
3.2) **if 2-factor is disabled, discard the note and proceed with whatever is next**

### Steps to reproduce
You need 2 separate Kanboard installations for this, and just having the software in 2 separate folders will do it since they'll have dedicated databases.

**I dunno if you need to have renamed any previous email entries in the Authenticator so you don't lose it !**

1) use same email to become any type of user on both installations
2) go enable 2-factor auth on both installations for your user
3) scan or enter the code of one installation and confirm it
4) now do step 3 on the another one, making sure it doesn't create 2 Kanboard entries in the Authenticator, only listing 1 Kanboard with your email. Scanning makes the process instant.
5) logoff from both installations
6) now, trying to login to the installation you confirmed the 2-factor on first will always deny your code, while the second will accept it

### Configuration
Apache, PHP and MySQL are shared on the computer, the Kanboard installations are separate, but identical version.

    Application version: 1.0.40
    PHP version: 7.0.16-4+deb.sury.org~xenial+1
    PHP SAPI: fpm-fcgi
    OS version: Linux 4.4.0-66-generic
    Database driver: mysql
    Database version: 5.7.17-0ubuntu0.16.04.1

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
