### ISSUE TITLE
organize tasks like github Issues page

### ISSUE THREAD

**Issue by sailfish009** [kanboard/kanboard#3129]
Hi, i am using  kanboard on local linux server. (ubuntu 14.04, nginx 1.11.3)

I want to organize kanboard task like github Issues page, just like below page:
https://github.com/kanboard/kanboard/issues

Current kanboard task page is not so attractive to me.
Can i do that?
Thank you.

**Comment by rautamiekka** [comment]
The collapsed tickets are similar to that, but I found it useless. I don't know other ways, someone else has to take this further.

**Comment by fguillot** [comment]
This is the main improvement of the version 1.0.41

**Comment by sailfish009** [comment]
Thank you! use it well!!!
