### ISSUE TITLE
kanboard LDAP issue

### ISSUE THREAD

**Issue by afeliciotto** [kanboard/kanboard#3136]
Hi, i have an issue with LDAP authentication.
My enviroment:

last kanboard
last ubuntu 16.04.02
last ldap module

My config.php stored in \data

<?php

// Enable LDAP authentication (false by default)
define('LDAP_AUTH', true);

define('LDAP_BIND_TYPE', 'user');
define('LDAP_USERNAME', 'openesse.local\\%s');
define('LDAP_PASSWORD',null);

// LDAP server hostname
define('LDAP_SERVER', 'SRV-DC-1.openesse.local');

define('LDAP_PORT', 389);
define('LDAP_SSL_VERIFY', false);
define('LDAP_START_TLS', false);
define('LDAP_USERNAME_CASE_SENSITIVE', false);
define('LDAP_USER_ATTRIBUTE_USERNAME', 'samaccountname');
define('LDAP_USER_ATTRIBUTE_USERNAME', 'samaccountname');
define('LDAP_USER_ATTRIBUTE_FULLNAME', 'displayname');
define('LDAP_USER_ATTRIBUTE_EMAIL', 'mail');
define('LDAP_USER_ATTRIBUTE_GROUPS', 'memberof');
define('LDAP_USER_CREATION', true);

// LDAP properties
define('LDAP_USER_BASE_DN', 'CN=Users,DC=openesse,DC=local');
define('LDAP_USER_FILTER', '(&(objectClass=user)(sAMAccountName=%s))');

the error is: wrong username or password

in my DC LDAP windows 2012 log,  i dont see my user activity.

Can you halp me?

thank you

**Comment by fguillot** [comment]
Please, can you make a proper bug report by using the provided template? (otherwise I will be forced to close your ticket)

**Comment by afeliciotto** [comment]
If i edit my post, a can see all writed. But in preview i can see only the first lines....
