### ISSUE TITLE
API not authenticating remote users

### ISSUE THREAD

**Issue by rmkraus** [kanboard/kanboard#3138]
### Actual behaviour
Unable to Authenticate via the API when using HTTP Basic Auth for authentication. 
The following is returned from the API:
```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": 401,
        "message": "Unauthorized"
    },
    "id": null
}
```

### Expected behaviour
We have Apache setup using pwauth to handle user authentication. In the logs, I can see that the user successfully authenticates with the system. Kanboard is rejecting the user [here](https://github.com/kanboard/kanboard/blob/master/app/Api/Middleware/AuthenticationMiddleware.php#L49). Because the user is a "Remote User", I would expect the API to accept that the user has been authenticated.

### Steps to reproduce

  1. Create a Remote user and setup Apache Authentication with a .htaccess file and pwauth.
  2. Using the Python API client, run the following code:
```python
kb = Kanboard(HOST, user, password)
print(kb.get_my_projects)
```
A 401 error is returned.

### Configuration

>     Application version: 1.0.40
>     PHP version: 5.4.16
>     PHP SAPI: apache2handler
>     OS version: Linux 3.10.0-514.10.2.el7.x86_64
>     Database driver: sqlite
>     Database version: 3.7.17
>     Browser: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by fguillot** [comment]
Which authentication backend do you use, reverse-proxy?

**Comment by rmkraus** [comment]
Yes, reverse-proxy.

**Comment by yann-soubeyrand** [comment]
I can confirm this issue.

**Comment by fguillot** [comment]
The API doesn't supports authentication in reverse proxy mode. Someone have to implement this feature.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
