### ISSUE TITLE
Issues go missing if not dropped inside a dotted box

### ISSUE THREAD

**Issue by ChangePlaces** [kanboard/kanboard#3139]
### Actual behaviour
When dragging tasks/issues around a board, unless you drop them inside a dotted box that denotes a drop area they go missing. It's possible, sometimes, when dragging, that a box doesn't appear where you want it, and if you "drop" the issue it doesn't appear elsewhere on the board.

### Expected behaviour

For the drop zone to appear to then drop the issue into.

### Steps to reproduce

I haven't been able to narrow this down to either dragging between swimlanes or just columns, but I find I can reproduce it more when dragging between cols. 

0. Firefox 52 / Windows
1. Create some tasks / take an existing board
2. drag a task around inbetween others
3. try dropping the task when there's no drop zone appear

### Configuration

    Application version: master
    PHP version: 7.0.15-0ubuntu0.16.04.4
    PHP SAPI: fpm-fcgi
    OS version: Linux 4.4.0-62-generic
    Database driver: sqlite
    Database version: 3.11.0
    Browser: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by fguillot** [comment]
Can you provide a screenshot/video/gif?

**Comment by ChangePlaces** [comment]
I will try to forcibly reproduce this

**Comment by ChangePlaces** [comment]
![no-dropzone](https://cloud.githubusercontent.com/assets/302031/24146224/b6c220c0-0e2c-11e7-99bc-130f8efd456b.png)

I've been able to successfully reproduce - the column to the left of the hidden column is affected, the column to the right is not. I can not drop from different swimlanes, nor the same swimlane. If I unhide the column, normal behaviour returns and drop zones are shown. 

In the picture, if I were to drop the selected task, it disappears  and a reload does not make it return

**Comment by fguillot** [comment]
After all this time, I'm still not able to reproduce this issue. Try again with the latest version of KB. If the problem persist, try to investigate by yourself and submit a patch.
