### ISSUE TITLE
Project overview screen

### ISSUE THREAD

**Issue by ChangePlaces** [kanboard/kanboard#3140]
Is there a reason why the columns, and amount of tasks per column has disappeared in the project list? I loved the old table. Having a full-width table is difficult to read and with no information in it other than the project title makes it seem a little useless!

**Comment by acs-ferreira** [comment]
Maybe related to #3144?

**Comment by acs-ferreira** [comment]
You can switch back to the latest release table based: https://github.com/kanboard/kanboard/releases/tag/v1.0.39

**Comment by felixkretschmer** [comment]
I can understand the issue. Kind of the same here. I loved the dashboard with it's overview to have projects, tasks in one view and easily select a project I'd like to see in detail what is going on with other users and their tasks.
I might stay at 1.0.40 for now, but as soon as other features or important updates come up I got kind of a dilemma. ;-)

**Comment by fguillot** [comment]
The old dashboard is back in latest version of KB.
