### ISSUE TITLE
kanboard written in go

### ISSUE THREAD

**Issue by sailfish009** [kanboard/kanboard#3141]
Hi, this is just a suggestion.

gitea/gogs is local git server which has wiki page. (written in go)

https://github.com/go-gitea/gitea

https://gogs.io/

go-wiki is Simple wiki server written in Go.

https://github.com/renstrom/go-wiki

it would be more productive to do implement kanboard with go than php.

just a thought.

**Comment by ChangePlaces** [comment]
FYI gitea is a (rather bad) fork of gogs. There's no reason why software has to be completely rewritten just because another piece is written in GO and the two work well together. There's a Gogs hook implementation in Kanboard - no idea whether this will work with gitea.

**Comment by sailfish009** [comment]
gogs or gitea don't care, only i see is golang is much better than php.
and gogs/gitea functionality cover up all of kanboard functions.

**Comment by fguillot** [comment]
Even if I like Golang, I don't really have the time right now to rewrite everything. Do not forget that there are dozen of plugins too (Gogs don't even have a plugin interface).

Switching to Go will simplify the installation (single binary) and probably leads to better performances. But I'm not sure that justify to put all the existing code to the trash.

**Comment by sailfish009** [comment]
there is some discussion about this:
https://www.reddit.com/r/golang/comments/3wfnru/switching_from_php_to_go/

**Comment by ChangePlaces** [comment]
@sailfish009 could always rewrite it in go. talk is cheap, action is golden.

**Comment by fguillot** [comment]
@sailfish009 I know very well what is Golang, I already write several software in Go, you don't need to give a sales pitch. There are so many factors that you didn't take into consideration.

**Comment by sailfish009** [comment]
i would like to listen the reason.
most of all, IMHO, you can get the many factors, but lost simplicity.

**Comment by sebastianmacias** [comment]
+1 golang implementation / single bin deployment

**Comment by DaBlitzStein** [comment]
+1 
Reasons: speed on low-budget environments

**Comment by DaBlitzStein** [comment]
+1
