### ISSUE TITLE
Add "attachment" to initial task creation window.

### ISSUE THREAD

**Issue by whyfrycek** [kanboard/kanboard#3143]
### Actual behaviour
When creating a task, I use the popup task creation window.

Very often, I would like to add attachment, so I manually have to edit the task after creation. For this (often), I need to scroll to the newly created task, then click on it, then click on "Attach a document" (Labeling could also be "Add attachment", because it is often not a document, but a previously taken screenshot.

This is quite a bit of scrolling and at least three clicks.

### Expected behaviour

Thanks to an icon to add an attachment, I can do this during initial task creation.

**Comment by kent1D** [comment]
Would love to see it also

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
