### ISSUE TITLE
Bug report: Gantt view not available to manager

### ISSUE THREAD

**Issue by NoodleBB** [kanboard/kanboard#3146]
### Actual behaviour

A user with **manager** role in a project is unable to switch to the Gantt chart. The button for the Gantt chart view is gone.

### Expected behaviour

A user with **manager** role, must be able to see the gantt chart. Because it's **the manager**. So there should be the Gantt button.

### Steps to reproduce

1. Create a new project.
2. Create some tasks with dates.
3. Create a new user with **manager** role in that a project. 
4. Long out and login as the created user
5. Open the project.
6. Try to switch to the gantt chart. - It's impossible, because the button is missing.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.40
- Database type and version: sqlite 3.8.10.2
- PHP version: 5.6.21
- OS: Linux 2.6.32-642.6.2.el6.x86_64
- Browser/s: Safari, Chrome, Firefox.

**Comment by n1trux** [comment]
for me it's not working either, I thought this was an issue with the Gantt plugin: https://github.com/kanboard/plugin-gantt/issues/5

Could be that I'm wrong, but I can't seem to get it to work with an earlier version either.

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_

**Comment by NoodleBB** [comment]
Moved to https://github.com/kanboard/plugin-gantt/issues/11
