### ISSUE TITLE
Feature request: Modernized UI [Interface] (1.0.40)

### ISSUE THREAD

**Issue by NoodleBB** [kanboard/kanboard#3147]
# Situation
The current UI is a bit "90's-Coder-Design". When clicking on a task, a bulk of texts actions appear left beside another endless text desert in vertical order. Longer than the screen. When editing a task it's cluttered with options on the other side of the text box. When opening a board on an tablet, it's not possible to move the tasks. Etc. 

# Suggestions
* The UI simply would need a clean up and reorganization. Grouping by functionality. Structuring by workflow. Reordering for mobile devices. etc. 
* The UI should be useable on "_modern devices_". Tablets and smartphones are normality today. Responsive UI/Design is the key. 
* The UI could be more appealing. May be it is possible to adapt parts of the [kanboard-presenter](https://github.com/davideberlein/kanboard-presenter) UI.

**Comment by NinjaPewPew** [comment]
The UI has been responsive for a while now. So using it on mobile devices is working just fine. I'm quite happy with it. Obviously there is a lot of personal preference involved, when talking about "appealing" UIs.

I would love to hear what you mean with reorganizing the UI. You especially mentioned "Grouping by functionality". Maybe you can give me (and other interested parties) an idea about what you have in mind :-)

**Comment by ChangePlaces** [comment]
you can use custom css in the admin settings

**Comment by NoodleBB** [comment]
@ChangePlaces: Do you have such a "_custom css_"?

**Comment by NoodleBB** [comment]
@NinjaPewPew 
On mobile devices custom UI-Widgets appear unreachable half outside the screen, or tasks are not dragable on the board. And also not in the calendar. The color-tag-popup sometimes scrolls, other times it moves out of the view. The behavior is unpredictable and there's no benefit. On the Desktop the widgets on create new task is not ergonomically ordered. The Board is very colorful, but total confusing, and partially badly readable (red text on purple ground, light grey on light blue, etc.). And making just little changes to 5 tasks take a lot of time and a lot of clicking an a marathon of mouse movements. Don't tell me about shortcut. The most of non-IT-users are using a mouse. The UI idol not asset what you're doing, it's a break. It is exhausting. - Btw. I found a css that reduced the massive color flash, that improved the readability and the confusion, but it can't recreate an elaborate UI/UX.

What can be done better for example: When creating custom-ui-elements these should make the user experience better (Faster, easier, readable, etc.). Not like the color-popup. That's counterproductive. Give the users a native popup, then they could have the full list of colors with just on one click. Without scrolling erratically around in an unsorted list. So what would be a better UI-Widget? When clicking on a color widget, it should bring up a palette (like the date selector) where you can see all color-samples at once, and select it with one click. Or other example: When there are these cool shortcuts - hovering in board view over attachment, sub-task- list-icon, brings up a preview-popup - why can't the date be modified, by just clicking on the date? It could bring up the date picker direct in the board view. - Result: 3 clicks reduced to 1.
 
And dialogs should have one naturally flow direction. Currently it is more like a triangle. That's not good.  So build group of them. Sample: The keywords are "tags". The color is also a tag. The should be to side-by-side next to each-other and represent a logical group. Same with the dates. A group below the tags-group. Startdate on the left. End Date on the right. The Assignee is the person (or group) that does that task. So put it on the top. Same line of the first field. This task has to be done by this guy. This is a group. They have a direct correlation.  Etc. When there's logical break use separator, to build different blocks. Build the dialog in a flow from the top to the bottom. 

I've made a quick sketch, just show the concept. The idea. 
![sketch](https://cloud.githubusercontent.com/assets/11850083/24472267/63312cb8-14c5-11e7-9e04-4d655303fa1d.JPG)

I'm sure, at the beginning there was a kind of ui concept. But when a project grows, and there's nobody responsible for the task, it dissolves. At this point three hint's are not enough. You need an UI professional, who can invest time to completely overhaul the current UI and UX.

**Comment by NoodleBB** [comment]
The date selector plays hide & seek.
![img_8221](https://cloud.githubusercontent.com/assets/11850083/24475616/b8503f44-14d0-11e7-8fec-c96c3b79d9e9.PNG)

But he doesn't move even if try to pull em.
![img_8222](https://cloud.githubusercontent.com/assets/11850083/24475633/d148410e-14d0-11e7-9164-15f6cb192adc.PNG)

When tapping the slider, there appears a text cursor. But the sliders can't be moved.
![img_8223](https://cloud.githubusercontent.com/assets/11850083/24475669/f8129438-14d0-11e7-815f-7a48498514d5.PNG)

When scrolling to fast, the popup moves away
![img_8224](https://cloud.githubusercontent.com/assets/11850083/24475696/16d351b4-14d1-11e7-9f2f-dd11a4802371.PNG)

When dragging a Task nothing happens. Etc. 

It seem, i has been never systematically testet. 

Device: iPhone 6S
OS: iOS 10.2.1

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
