### ISSUE TITLE
New Dashboard (v1.0.41) breaks JSONRPC

### ISSUE THREAD

**Issue by andresth** [kanboard/kanboard#3148]
### Actual behaviour
The RPC call of `getMyDashboard` returns a completely different data structure than the older Kanboard versions.

I think this should at least be mentioned in the changelog and the documentation.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.41
- Database type and version: mysql
- PHP version: 7
- OS: CentOS
- Browser:

**Comment by fguillot** [comment]
Sorry about that.
