### ISSUE TITLE
Feature request: Assign multiple users to a task

### ISSUE THREAD

**Issue by NoodleBB** [kanboard/kanboard#3149]
### Actual behaviour

I like to create a task and assign it to two users. But currently it is not possible. You can assign only one  user to a task.

### Expected behaviour

It would be useful if you could add more than one user to a task. When two people are work on one task. Or if responsibility for that task changes. Etc.

### Configuration

- Kanboard version: 1.0.40

**Comment by rautamiekka** [comment]
Agree. It's not just a matter of changing 1 or 2 lines with a few letters, though, it takes some redesigning of the database and changing of fair count of references to the old design.

**Comment by NinjaPewPew** [comment]
There is already a pretty long dissucsion going on for that feature since May 2014. You can find it in #85.

**Comment by NoodleBB** [comment]
@NinjaPewPew 
Thank you. I was pretty wondering, that i didn't found a request for such a elementary feature.

**Comment by fguillot** [comment]
Duplicate with #85
