### ISSUE TITLE
Ability to change default swimlane.

### ISSUE THREAD

**Issue by erixtekila** [kanboard/kanboard#3150]
It's impossible to define a named swimlane to be the default.
Default swimlane are choosen to push subtask to task, for example.
If you de-activate the default one, you won't se your migrated task

**Comment by rautamiekka** [comment]
Fill the template, need the step-by-step instructions.

**Comment by fguillot** [comment]
If you upgrade to the latest version of Kanboard, there is no concept of default swimlane anymore.

**Comment by heticeric** [comment]
Ah yes thanks @fguillot. 
Really better like this.
Keep up the good work !
