### ISSUE TITLE
Question: Zoom in Zoom out on Gantt timeline

### ISSUE THREAD

**Issue by NK74** [kanboard/kanboard#3152]
### Actual behaviour
How to zoom in zoom out on gannt timeline in a project, (view 3 months, 6months,12months)

### Configuration
- Kanboard version: 1.0.41
- Database type and version: sqlite 3.7.13
- PHP version: 7.0.7 (fpm-fcg)
- OS: Linux 3.16.0-0.bpo.4-amd64
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by NK74** [comment]
Hello, 

Up 👍

**Comment by fguillot** [comment]
This feature doesn't exists.

**Comment by NK74** [comment]
Can you add zoom in/out for gantt view?

To improve gantt visibilibility

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_
