### ISSUE TITLE
Swimlane table header inconsistency 

### ISSUE THREAD

**Issue by ChangePlaces** [kanboard/kanboard#3153]
### Actual behaviour
When you have more than one swimlane, the top one (maybe others) have the swimlane title below the column headers instead of above.

#### New swimlane moved to the top with title below col headers
![kanboard_2](https://cloud.githubusercontent.com/assets/302031/24279465/ee9d56d8-1041-11e7-8b86-12198a62216a.png)

#### Default swimlane with title above col headers
![kanboard_1](https://cloud.githubusercontent.com/assets/302031/24279466/eea15db4-1041-11e7-8486-19f828d979b8.png)

### Expected behaviour
The swimlane title should be above the column headers as it is with the default header

### Steps to reproduce
1. create a new swimlane, and title and description and move the lane to the top
2. notice the title is below the column headers

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

    Application version: master
    PHP version: 7.0.15-0ubuntu0.16.04.4
    PHP SAPI: fpm-fcgi
    OS version: Linux 4.4.0-62-generic
    Database driver: sqlite
    Database version: 3.11.0
    Browser: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by rautamiekka** [comment]
That's different from 1.0.40 where the first lane has them below the lane's name and the second has them above the lane's name. Could be changing the lanes did it, as I changed the lanes and columns in my software production project.

**Comment by fguillot** [comment]
Duplicate with #2575
