### ISSUE TITLE
new dashboard (v1.0.41) search feature group by

### ISSUE THREAD

**Issue by SergiArias** [kanboard/kanboard#3154]
Hi!

The new dashboard is very nice looking, thanks!
But my issue is: when searching in the new dashboard, if there are many results, the new design overwhelms easily. I think the results should be grouped by project as the dashboard without search or maybe give the option to choose the variable to group by.

### Actual behaviour

It just give endless results that cannot be ordered or grouped by project.

### Expected behaviour

When there are too many results, the appearance should be clearer.

### Steps to reproduce

Search assignee:me for example.

### Configuration

- Kanboard version: v1.0.41

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
