### ISSUE TITLE
Calendar View doesn't Save Task postition

### ISSUE THREAD

**Issue by juehv** [kanboard/kanboard#3155]
### Actual behaviour
I go to the calender view and drop a task from the "all day" part to an actual time.
When leave the view and go back to it, the Tasks are back in the all day part.

### Expected behaviour
Tasks should stay at the time slots.

### Steps to reproduce
Open a Project
Go to the calender view
Drag a task from the upper all day part and drop ist down to an actual time slot
Leave the view (maybe to the board view)
Go to the calender view again
--> Task went back to all day part :(

### Configuration
- Kanboard version: 1.0.41
- Database type and version: mysql 10.1.22-MariaDB-1~xenial
- PHP version: 7.1.1
- OS: Linux 4.4.26-20161020-1031-05fc878
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 (Actually it is the Google Chrome browser)

**Comment by fguillot** [comment]
Duplicate with #2495

**Comment by juehv** [comment]
So maybe you could consider it as feature request ;)
