### ISSUE TITLE
User Dashboard - does not display all projects

### ISSUE THREAD

**Issue by kappler0** [kanboard/kanboard#3156]
I have a fresh install and believe the application is not displaying the dashboard correctly. 

### Actual behaviour

User dashboard only displays a single project with task summary for that project only (DashboardController&action=show)

### Expected behaviour

Should display all projects with task summaries as the (ProjectListController&action=show)

### Steps to reproduce

1. Log in to the application 
2. Click on button My Dashboard
3. Only showing a single project. You must use "Display another Project" or "Project Management" links to view others.

### Configuration

Application version: 1.0.41
PHP version: 7.0.10
PHP SAPI: cgi-fcgi
OS version: Linux 3.10.0-327.36.3.el7.x86_64
Database driver: mysql
Database version: 5.5.52-MariaDB
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
- Browser:

**Comment by jeppetrost** [comment]
It looks like this has something to do with how the projects are counting their tasks. If a project has no tasks, it won't show up on the dashboard.
However, this is determined by the getTotal function of the paginator, which is not always correct. 
For example if I create a new project and 'move' a task to it from an old project, it still won't show up on the dashboard.

**Comment by fguillot** [comment]
The old dashboard is back in more recent version of KB.
