### ISSUE TITLE
Improvement: see the project info when the task view is loaded

### ISSUE THREAD

**Issue by SergiArias** [kanboard/kanboard#3159]
I usually fill the project info with shortcuts (users, sites, brief goals, etc...). And it's very useful when being in the project view. But when in the task view, it disappears. Would it be possible to show it also in the task view?

If it's something that isn't useful for everybody, is there a workaround I can make in the template?

In header/title.php:
```
    <?php if (! empty($description)): ?>
        <small class="tooltip" title="<?= $this->text->markdownAttribute($description) ?>">
            <i class="fa fa-info-circle"></i>
        </small>
    <?php endif ?>
```

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
