### ISSUE TITLE
 Scroll Browser Window when dragging task [Feature Request]

### ISSUE THREAD

**Issue by bonbonGuy** [kanboard/kanboard#3160]
As a user, when i drag a task in a project with multiple swimlanes and columns, would like for the browser window to scroll in the direction i am dragging, in order to drop the task in a distant swimlane/ column

**Comment by psy-q** [comment]
This seems to be a very hard thing to do for some reason. Even some dedicated drag & drop JavaScript libraries [have not managed to accomplish this](https://github.com/bevacqua/dragula/issues/327). I will research a little bit whether a solution that fits only Kanboard (not a general use case) would be doable.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
