### ISSUE TITLE
[BUG?] Description field disappeared when trying to edit task (1.0.3.5)

### ISSUE THREAD

**Issue by sparkles645** [kanboard/kanboard#3161]
**Haven't screened the issues list for a while - been busy enjoying KB - , so apologies to @fguillot  if this is duplicate. Did quick search without finding similar reported issue**

### Actual behaviour

1. Pasted a list of links in description of new task

2. When trying to edit task - field "Description" is missing

### Expected behaviour

1. Paste and establish Markdown < > for 5 links

2. Be able to edit task "Description" after doing so.

## SCREENSHOTS
![bilde](https://cloud.githubusercontent.com/assets/10092252/24422232/160489c0-13f9-11e7-96b1-60a5e71f00c2.png)

![bilde](https://cloud.githubusercontent.com/assets/10092252/24422248/24f19e3c-13f9-11e7-88bb-cfe2d8b13973.png)

![bilde](https://cloud.githubusercontent.com/assets/10092252/24422270/379507ea-13f9-11e7-81d3-03717f4c5cfc.png)

## END-OF-SCREENSHOTS
********************************************************

### Steps to reproduce

1. Create new task
2. Paste the following (without < > when pasted, added manually)

https://d3js.org/

https://github.com/d3/d3/wiki/Gallery
https://vida.io/explore https://bl.ocks.org/mbostock
http://christopheviau.com/d3list/gallery.html

http://prcweb.co.uk/lab/circularheat/

3. Add <> on the links

4. Save task

5. Edit task

********************************************************

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: **1.0.35**
- Database type and version: **Sqlite 3.7.13**
- PHP version:  **5.5.38-1~local.2**
- OS:  **Linux 3.2.0-4-amd64**
- Browser:  **Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0**

**Comment by Busfreak** [comment]
Hi,
you should try updating to a newer version. We are currently on 1.0.41. On this version I can't reproduce your issue.

**Comment by sparkles645** [comment]
@Busfreak 
* Tnx for the feedback.
* I tested on 1.0.4.1, but was not able to reproduce it there.
* Sticking with 1.0.3.5 for now - since I'm happy with it + it's the version running on our production server.

**Comment by sparkles645** [comment]
Closing this one since problem doesn't appear in later versions
