### ISSUE TITLE
[Feature request] Set notification rule per projet

### ISSUE THREAD

**Issue by auprobst** [kanboard/kanboard#3165]
### Actual behaviour

In Kanoboard 1.0.40, it is possible to set the 1 (and only 1) notification rule for several projects : https://kanboard.net/screenshots/documentation/en_US/screenshots/notifications.png
The unselected project won't generate Notifications

### Expected behaviour

It would be nice to be able to set 1 notification rule per project.
e.g.
* Project A -> Only for tasks created by me or assigned to me
* Project B -> All tasks
* Project C -> No notification
etc.

Furthermore, the #2411 feature request would be nice so that users can choose to "follow" a specific task without changing their notification settings.

Application version: 1.0.40
PHP version: 5.6.30-0+deb8u1
PHP SAPI: fpm-fcgi
OS version: Linux 3.16.0-4-amd64
Database driver: sqlite
Database version: 3.8.7.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited.

Thank you for your understanding
