### ISSUE TITLE
Import / sync User from windows active directory group

### ISSUE THREAD

**Issue by mehdiyahyaoui** [kanboard/kanboard#3169]
How to import / syncronise the users within an active directory group to Kanboard

I assume that the users should log in once to have there account created

but can I create / import the Users account on Kanboard from windows active directory

so far I was only able to import the group without the users using group syncronisation

**Comment by fguillot** [comment]
See: https://kanboard.net/documentation/ldap-authentication and https://kanboard.net/documentation/ldap-configuration-examples

**Comment by mehdiyahyaoui** [comment]
Still 

I need to ask users to login in order for them to be on the database 
is it possible to maintain a sync with an active directory group using 'memberof'

**Comment by fguillot** [comment]
Users have to login first. However, you can write a custom script the create the users in advance via the API.
