### ISSUE TITLE
Feature Request - Add tag updates to webhook supported events

### ISSUE THREAD

**Issue by garettmd** [kanboard/kanboard#3170]
Could tag modifications be added as a webhook event (`task_tags_modify` or similar) or just add the list of a task's tags to any task webhooks (`task.update` would include a tags list in `event_data`, for example)?

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
