### ISSUE TITLE
Comment tip

### ISSUE THREAD

**Issue by lcappello** [kanboard/kanboard#3171]
**Please, do not create duplicate issues**

### Actual behaviour

The previous behaviour to show comments in the kanboard task is changed. Now appears only a counter of how many comments are present. Was lost the possibility to show the comments list quickly

### Expected behaviour

Sow the comments list quickly

Tell us what should actually happen

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:
all

**Comment by fguillot** [comment]
Please, can you make a proper bug report?

**Comment by varod** [comment]
we have the same "issue" and we think it is related to v1.0.39 Improvments "Open comments on board view with a modal dialog instead of tooltip"
 
now in 1.0.42 when hover comments icons on a card, comments are not any more shown. we have to click to see it.

this feature was very helpful.

**Comment by lcappello** [comment]
It's possible to have, as option, both the behavior (tip and modal window)?

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited.  I cannot make everything configurable. The best approach is probably to write a custom plugin.

Thank you for your understanding

**Comment by lcappello** [comment]
Thank you very much. I will try to find a different solution.
I appreciate very much your work.

Thanks again
Luca
