### ISSUE TITLE
cronjow on windows

### ISSUE THREAD

**Issue by brillox** [kanboard/kanboard#3172]
**Please, do not create duplicate issues**

### Actual behaviour

Tell us what happens
bat file command ailed in task scheduler

### Expected behaviour

Tell us what should actually happen
the bat file must have run the cron job script

### Steps to reproduce
on windows server 2012 machine
create a task scheduler to run this bat file script (with my php and kanboard paths)
"C:\PHP\7.0.12\php.exe" -f "C:\inetpub\wwwroot\kanboard\" cronjob

Please supply step-by-step instructions so that anyone with the same environment can reproduce the issue. Whenever you offer a description, imagine
yourself in the shoes of someone who has never encountered this problem before and would like to know exactly how to observe it under a given set of conditions.
Here is an example:

1. create a scheduled task to run a bat file with the above command
2. run the task manually to test
3. task end with x01 error

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.41
- Database type and version: mysql 5.7.16-log
- PHP version: 7.0.12
- OS: Windows server 2012
- Browser: Chrome (latest version as typing this post)

**Comment by brillox** [comment]
I am not sure if CronjobCommand.php is teh cron php script or not

**Comment by mfreyer** [comment]
There is no file named "conjob" in the kanboard root directory, thus running
"C:\Program Files\PHP\v7.1\php.exe" -f "C:\inetpub\wwwroot\kanboard" cronjob
on my system produces the following output
Could not open input file: C:\inetpub\wwwroot\kanboard

**Comment by mfreyer** [comment]
After some more testing I found that running
"C:\Program Files\PHP\v7.1\php.exe" -f "C:\inetpub\wwwroot\kanboard\**cli**" cronjob
actually seems to work. At least it did not produce any error message. But I see no way to verify if it actually does something useful.

**Comment by fguillot** [comment]
Yes, there is a typo in the doc, you have to call the script `cli`, not `kanboard`.
