### ISSUE TITLE
Feature Request: Include Tags in Export

### ISSUE THREAD

**Issue by MaxITCorp** [kanboard/kanboard#3173]
Currently the Export feature does not include tags. 

I work with multiple clients and use the Reference Field for the statement of work but that's a unique number that my CMS/Billing system generates. I use the tags for the customer's name. This makes filtering easy, but no way to identify them when I export the data.

### Configuration
Application version: 1.0.40
PHP version: 7.0.16
PHP SAPI: cgi-fcgi
OS version: Linux 3.12.65-188.ELK6.x86_64
Database driver: sqlite
Database version: 3.14.2

**Comment by Biniou180** [comment]
Hello!
This feature is interesting indeed :)
Could it be possible (feasible?) to also add descriptions and perhaps comments to an export?

Thanks a lot!

**Comment by MarieIdille** [comment]
Hi!
I add my vote to the feature request! We use tags a lot along categories to label various tasks, and we would need these to be exported along with the other info. Export of descriptions would also be a big plus.
Thanks!

**Comment by fguillot** [comment]
This is now available in the development branch.

**Comment by peter58228** [comment]
Where is the export function ?
