### ISSUE TITLE
Feature Request: Saved Filters

### ISSUE THREAD

**Issue by KrisNick** [kanboard/kanboard#3174]
We work with a number of clients and use a number of different filters based on tags, status, etc. I would be really handy to have a way of saving this. Currently, we're hard-coding them into filters_helpers.php file. Ideally, we would simple be able to save/edit/delete filters.

By the way, saw some comments about the new look. Personally, I think it looks very nice and find the site easy to work with and navigate.

### Configuration

Application version: 1.0.40
PHP version: 7.0.16

**Comment by NinjaPewPew** [comment]
Couldn't you use the "Custom Filter" project setting for that?

**Comment by fguillot** [comment]
Yes, you can already save your filters by using custom filters.
