### ISSUE TITLE
Duplicate and keep tasks order [Feature Request]

### ISSUE THREAD

**Issue by Trudill** [kanboard/kanboard#3175]
## Actual behaviour

When you duplicate a project (or create a new one based on another one), if you modified the position of tasks in a column, the "clone" re-order the tasks depending on their numbers.

### Expected behaviour

When you duplicate a project, it would be nice to be able to have an "exact" copy of it, even the tasks re-ordered. (maybe has an option to check ?)

### Steps to reproduce

1. Create project with tasks
2. Re-order the tasks in a column
3. Clone or create a new project based on another one
4. The tasks are ordered by number and so is not a "clone" which keeps the re-ordered tasks.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.41
- Database type and version: sqlite 3.8.7.1
- PHP version: 5.6.22-0+deb8u1
- OS:Linux 3.14.53-grsec-paas-3117c5c
- Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

Thanks !

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
