### ISSUE TITLE
bug form validation  required field issue

### ISSUE THREAD

**Issue by brillox** [kanboard/kanboard#3176]
![screenshot](https://cloud.githubusercontent.com/assets/685626/24586037/17c33654-1790-11e7-8192-7119eb69b008.png)
### Actual behaviour
cannot add a new task
Tell us what happens
when trying to create a new task although I set a title I get a required field validation pop-up for missing title

### Expected behaviour
task created
Tell us what should actually happen
task cannot be created

### Steps to reproduce
1. login
2. add a task to an existing project
3. Fill in title and description
4. click save

### Configuration
Application version: 1.0.41
PHP version: 7.0.12
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: mysql
Database version: 5.7.16-log
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by brillox** [comment]
figure it out... the task title must be one word cannot have blank spaces; can you change this behaviour?

**Comment by brillox** [comment]
also the task description and the project description does not accept multiple words???  And the validation error message is always the same.. "title required" Man you have to review the form validation code.

**Comment by fguillot** [comment]
Are you sure that everything is installed correctly?

**Comment by brillox** [comment]
I have uninstalled and installed again twice; is on windows environment though

**Comment by rautamiekka** [comment]
I'm leaning towards Web browser doing it wrong. It seems you're using Google Chrome, so try extracting [Chrome Portable](https://sourceforge.net/projects/portableapps/files/Google%20Chrome%20Portable/GoogleChromePortable_57.0.2987.133_online.paf.exe/download) ([Firefox Portable](http://downloads.sourceforge.net/portableapps/FirefoxPortable_52.0.2_English.paf.exe) just in case) to some folder, make sure Chrome is completely closed, start the portable one and try the bug again. If it repeats all the same, it's not a browser issue.

**Comment by brillox** [comment]
Hirautamiekka,

I have already tried in firefox and chrome and IE11
![testnewtaskfirefox](https://cloud.githubusercontent.com/assets/685626/24829587/82fec65a-1c6c-11e7-8928-247f5a8692d9.png)

**Comment by brillox** [comment]
not sure if make any sense but by enabling debug in the config file seems that solved the issue; could this be something related to PHP 7.0.12 which is the version I am using on a windows machine?

**Comment by rautamiekka** [comment]
Just toggling Kanboard debug fixed that ? PHP7 is a possible culprit since some things were deleted altogether, so many PHP pages not specifically tested with PHP7 are unlikely to work.

**Comment by brillox** [comment]
I know, sound weird to me too... but so far it is working. Tomorrow I will switch off debug from kanboard config and see if it stop working again

**Comment by TravisNoles** [comment]
I had the same issue, am running PHP7 with nginx. The way I corrected it was by making sure /var/lib/php and sub-folders including /var/lib/php/session was owned by the nginx user/group. If you're running apache, it shouldn't be that much different using the apache user/group.


drwxr-xr-x  5 nginx nginx 4096 Sep 21 09:28 .
drwxr-xr-x 21 root  root  4096 Sep 21 09:48 ..
drwxrwx---  2 nginx nginx 4096 Aug 30 18:14 opcache
drwxrwx---  2 nginx nginx 4096 Sep 21 10:15 session
drwxrwx---  2 nginx nginx 4096 Aug 30 18:14 wsdlcache
