### ISSUE TITLE
RFE: Add a quick way to assign a task to a user

### ISSUE THREAD

**Issue by erickvd** [kanboard/kanboard#3177]
### Actual behaviour

When we create a task, we don't always want to assign it to someone.

### Expected behaviour

We are working with kanboard during scrums and it would be great if we can go quicker to assign a task to someone: item in the quick-menu or the list of the project members directly available,...

### Steps to reproduce

1. Create a task but but assign it.
2. Click on the quick menu
3. Edit the task
4. Assign the task.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Application version: 1.0.41
- PHP version: 7.0.11
- PHP SAPI: apache2handler
- OS version: Windows NT 6.2
- Database driver: mysql
- Database version: 5.5.40-log
- Browser: Firefox, Chrome, IE

**Comment by fguillot** [comment]
Same request as #3251
