### ISSUE TITLE
Gantt view trouble with an in/out zoom

### ISSUE THREAD

**Issue by emmanuelCNRS** [kanboard/kanboard#3180]
### Actual behaviour

When applying a IN or OUT zoom (ctrl + mouse) in the gantt view: 
- The colored weekend days are shifted.
- The last days of the view are placed on a new line (with OUT zoom), or are shifted (with IN zoom).

This trouble appears with Firefox, but doesn't appear with Internet Explorer.

Is it only due to Firefox ?

### Expected behaviour

If not due to Firefox, the use of the zoom should not affect the gantt view.

### Steps to reproduce

1. Open a gantt view.
2. Press "ctrl" key and zoom IN or OUT with the mouse.
3. Check the beginning and the end of the day numbers line.

### Configuration

- Kanboard version: 1.0.41
- Database type and version: postgres / 9.1.9 
- PHP version: 5.4.16
- OS: Seven
- Browser: Firefox 52.0.2 (32 bits)

![zoom_in](https://cloud.githubusercontent.com/assets/26926901/24707942/b1aaf306-1a15-11e7-9ca7-f732b11df6e2.JPG)

![zoom_out](https://cloud.githubusercontent.com/assets/26926901/24707949/b705a5d0-1a15-11e7-9346-2b2fa4f31d33.JPG)

**Comment by on-jz** [comment]
As a quick fix you could add this to Settings > Application settings > Custom Stylesheet
```
/* gantt chart browser zoom (partial) fix
 *****************************************/
div.ganttview-grid-row {
	float: left;
}
```
Hope that helps...

**Comment by fguillot** [comment]
Please, move your ticket to the Gantt plugin bug tracker: https://github.com/kanboard/plugin-gantt/issues

- This will facilitate the work of the maintainers (bug triage)
- Make sure your ticket still relevant with the latest version of the software
- If you are asking another feature request, do not hesitate to contribute, Kanboard is an open source project. Remember the famous quote from Linus Torvalds: _“Talk is cheap. Show me the code.”_
