### ISSUE TITLE
Email notification to all Kanboard users (when you are admin)

### ISSUE THREAD

**Issue by emmanuelCNRS** [kanboard/kanboard#3181]
### Actual behaviour
It seems that there is no way for a Kanboard administrator to send an email notification to all Kanboard users (thru the "Gestion des utilisateurs" menu).

### Expected behaviour
It could be nice to have it when a maintenance is planned (ex: Kanboard update, ...).

### Configuration
- Kanboard version: 1.0.41
- Database type and version: postgres / 9.1.9 
- PHP version: 5.4.16
- OS: Seven
- Browser: Firefox 52.0.2 (32 bits)

**Comment by fguillot** [comment]
Are you sure that Kanboard is the right tool for that?

**Comment by emmanuelCNRS** [comment]
Hello Frédéric,
I was thinking about this because Kanboard knows who is using Kanboard. 
It's a little bit long to take one by one each email to inform Kanboard users about an update :-)

**Comment by leandrodb** [comment]
Could it be an intermediate between the chat notification plugins and the
send mail plugins?

I think it is good to have redundancy between team chat notification and
project user's emails for notifications about interactions with the project
board, just like github, gitlab, trello allows user to subscribe.

Em 18 de abr de 2017 12:44 PM, "emmanuelCNRS" <notifications@github.com>
escreveu:

**Comment by emmanuelCNRS** [comment]
Hello Leandrodb, 
I have just check Kanboard plugin page and I have read this in the Chat plugin : "Notification on user mention".
With it, a Kanboard administrator have to type/select one by one each user name in the chat box...
The main goal of my idea is to save time, a little bit like the "Automatic Actions" feature of Kanboard :-)

**Comment by aslmx** [comment]
+1 - i wish there was an easy way to inform users about updates or possible outages.
right now i export the users to a text file and run a grep command to get the email addresses of the users and then manually put them into the TO box in outlook...

**Comment by Busfreak** [comment]
Why not using the hook 'template:auth:login-form:before' or 'template:auth:login-form:after'.
There you can display news or even links to where you want?
Simple way to inform users when logging in.

**Comment by aslmx** [comment]
Thanks for the hint. Apart from the fact that i do not know how to use these hooks yet, it would not be praticable for the way we use Kanboard in our Team. Not all users use the tool daily. Email notifications would be much easier for me.

Maybe i'll create some php script that selects all active users and just gives me their eMail addresses to solve this....

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
