### ISSUE TITLE
Remote user added to group only if group is used before first login of user

### ISSUE THREAD

**Issue by fernwerker** [kanboard/kanboard#3182]
### Actual behaviour
Using the LDAP Authenticator with the Active Directory (AD) does not add Remote Users to groups, if the user logged in to the KanBoard before a remote group was used in one of the projects.
Example:
User A is member of Group 1 in the Active Directory and logs into the Kanboard for the first time.
Group 1 is not used in any project before and therefore not visible in the Group Management.
User A assigns Group 1 as Member to his project.
Now Group 1 is visible in Group Management, but User A is not a member, although he is a member in AD
User B is member of Group 1 in AD and logs into Kanboard for the first time now.
He is member of Group 1 in the Group Management now and can access the project of User A.

Summary: Users, that logged in before a group is assigned to a project are not added to this group.
Assumption: Users that are added as remote users once are not synced again (e.g. during their next login)

### Expected behaviour
If new groups are assigned to projects and are used in Kanboard for the first time, existing Remote Users in the Kanboard, that are members of this group in AD will be joined to this group.

### Steps to reproduce
Install KanBoard with AD Authentication and replay the scenario mentioned-above.

### Configuration
Version: 1.0.40
PHP Version: 5.5.9-1ubuntu4.21
PHP SAPI: apache2handler
OS Version: Linux 3.13.0-108-generic
Datenbanktreiber: mysql
Datenbank Version: 5.5.54-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by felixkretschmer** [comment]
Isn't this considered a bug if #2173 was supposed to solve this?

**Comment by rajo** [comment]
Yes, I can confirm this behaviour:

we have a KanBoard instance running here, with ldap-auth against an AD. So far, so good. LDAP/AD-Users can login, and, once logged in, can be assigned to Projects etc. 

Also, we can get groups from LDAP/AD and they could be used for assigning group memberships in a Project. 

But: when changing the project permissions by granting permission to a ldap group, the (already existing-by-sync) users within this group will only be updated after their next login. So unless everyone logs in again, those people e.g. cannot be assigned to tasks etc.

This is especially a bit annoying, as one of the last releases removed the "grant access to everyone" and hence groups must be defined.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
