### ISSUE TITLE
FR - Notification be able to select type of notification

### ISSUE THREAD

**Issue by valvin1** [kanboard/kanboard#3186]
### Actual behaviour

When setting up notification rule I can select Mail / Web and Projects. When I've activated notifications (by mail for example) I receive all notifications of this project : column change, new tasks, new subtasks, task change (assignee, description, priority ...), subtask change (start / stop ...), comments ...
That leads to spamming quickly with non relevant information.

### Expected behaviour
It'll be great if we can select type of notification we want to receive. In my case, I'm interested in only new tasks, new subtasks and comments.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.41
- Database type and version: PostgreSQL
- PHP version: 7.0.x
- OS: Centos 7.x
- Browser: Firefox 52

**Comment by MichaelTunnell** [comment]
I think this would be a great feature. I really like Kanboard and the notification option is great. However, sending a message for new tasks, new subtasks, new comments, editing tasks, etc can get pretty spammy pretty quickly. A way to limit it for only new tasks would be great.

**Comment by netbomo** [comment]
Hello,
I'm using actually kanboard by the framaboard instance. As already said, notifications come sometime as a big rain.
An other proposition is to give the choice to have daily mail to group notifications in.
I'm working in different associations (with no "geek" people) and this possibility seems to be as a daily remember when notification appends. It's cool when you don't use a computer every day to have it.
Hope that can enjoy people.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
