### ISSUE TITLE
Error on setting start date

### ISSUE THREAD

**Issue by carlosatlantida** [kanboard/kanboard#3187]
### Actual behaviour

Error when clicked in "Set start date" button in tasks. There's no error in version 1.0.41 but when I update Kanboard to 1.0.42 error i can't set start date

![captura_de_pantalla_041017_040814_pm_041017_041001_pm](https://cloud.githubusercontent.com/assets/17640873/24865629/23f08890-1e08-11e7-8b1e-51301b94aa73.jpg)

![captura_de_pantalla_041017_114152_am](https://cloud.githubusercontent.com/assets/17640873/24856083/c5a4ad44-1de3-11e7-818d-354feb636c57.jpg)

### Expected behaviour

I'm trying to change start date.

### Steps to reproduce

1. Create a new task.
2. Click in "set start date" 

### Configuration

    Versión de la aplicación: 1.0.42
    Versión de PHP: 5.6.28
    PHP SAPI: apache2handler
    Versión del sistema operativo: Windows NT 6.1
    Driver de la base de datos sqlite
    Versión de base de datos: 3.8.10.2
    Navegador: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

In Chrome Browser it doesn't work too.

**Comment by juracy** [comment]
same problem here !

**Comment by freeblue** [comment]
same problem here

**Comment by PipC** [comment]
I temporary modified some codes in order to let it works again.

1. Edit app/Controller/CustomFilterController.php
   # private function checkPermission(array $project, array $filter)
   protected function checkPermission(array $project, array $filter)

2. Edit 
    # class TaskModificationController extends BaseController
    class TaskModificationController extends CustomFilterController

**Comment by liaoqinghai** [comment]
same problem here
apache error log:

 PHP Fatal error:  Uncaught Error: Call to undefined method Kanboard\\Controller\\TaskModificationController::checkPermission() in /www/kanboard/app/Controller/TaskModificationController.php:26\nStack trace:\n#0 /www/kanboard/app/Core/Controller/Runner.php(77): Kanboard\\Controller\\TaskModificationController->start()\n#1 /www/kanboard/app/Core/Controller/Runner.php(31): Kanboard\\Core\\Controller\\Runner->executeController()\n#2 /www/kanboard/index.php(9): Kanboard\\Core\\Controller\\Runner->execute()\n#3 {main}\n  thrown in /www/kanboard/app/Controller/TaskModificationController.php on line 26

**Comment by Busfreak** [comment]
see https://github.com/kanboard/kanboard/pull/3194

**Comment by liaoqinghai** [comment]
thx @Busfreak  
app/Controller/CustomFilterController.php  line 107,132 also call the discarded function

**Comment by edgram** [comment]
I have the same issue...

<img width="992" alt="captura de pantalla 2017-04-15 a la s 01 17 29" src="https://cloud.githubusercontent.com/assets/16267007/25061419/968799e0-217b-11e7-88ae-267e2f346cbf.png">

**Comment by joseluisbossio** [comment]
me too.

**Comment by fguillot** [comment]
The fix is available in v1.0.43

**Comment by fguillot** [comment]
Thanks @Busfreak for the PR!

**Comment by carlosatlantida** [comment]
Thanks Frédéric for the quick fix. Many thanks for share with us your BRILLIANT software.
