### ISSUE TITLE
Send comment by mail feature delete current comment

### ISSUE THREAD

**Issue by valvin1** [kanboard/kanboard#3189]
### Actual behaviour
In a task when I add a comment, I'm starting to write the comment and then decide to send it by email. When I click on send it by mail it delete the comment.

### Expected behaviour

Expected behaviour is it doesn't delete current comment in order to not loose current information.

### Steps to reproduce
1. In a task click on add a comment
2. Start writing the comment
3. Click on send by mail ==> delete comment written in 2.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.41
- Database type and version: Postgresql
- PHP version: 7.0
- OS: Centos 7
- Browser: Firefox 52 XUbuntu

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
