### ISSUE TITLE
Adding extra information in email notifications sent by Kanboard

### ISSUE THREAD

**Issue by Afedan** [kanboard/kanboard#3192]
This is the email notification that Kanboard sends via an SMTP server:

**### KPI preparation (#26)

Project: RECRUITMENT UNIT KANBAN
Created: 04/08/2017 11:51
Created by admin
Assigned to Danaf
Column on the board: Backlog
Task position: 1**

But I want to add the extra information below in the email notification:
Swimlane on the board: **Name of the swimlane**

Thanks in advance

**Comment by fguillot** [comment]
You could modify the templates here: https://github.com/kanboard/kanboard/tree/master/app/Template/notification

**Comment by izno** [comment]
Hi,
Possibly a related question: Is it possible to add additional info as part of the sender name "xxx via Kanbord + EXTRA Info." Can this be modified from a template? ...or that is a core thing?
If it's a core... can it be extended by a Plugin?

**Comment by fguillot** [comment]
@izno You could write a plugin for a different notification type and change the way that email are sent. See https://kanboard.net/documentation/plugin-notifications
