### ISSUE TITLE
Bulk remove columns from boards

### ISSUE THREAD

**Issue by eurodrew555** [kanboard/kanboard#3193]
### Actual behaviour

I duplicate a board as it has some columns that I wish to use for a new project. I then have to remove columns one by one.

### Expected behaviour

It would be nice to have a checkbox next to each column, so I can just check all the columns I want to delete and then remove them in one go.

### Steps to reproduce

Project > Settings > Columns

To delete more than one column at the moment it has to be done one by one.

### Configuration

Application version: master (1.0.42)
PHP version: 7.0.17
PHP SAPI: fpm-fcgi
OS version: Linux 4.9.7-x86_64-linode80
Database driver: sqlite
Database version: 3.7.17
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
