### ISSUE TITLE
Modal dialogs should adapt to viewport

### ISSUE THREAD

**Issue by alessandro-guido** [kanboard/kanboard#3196]
### Actual behaviour

When a modal dialog appears (i.e. edit task) its size is fixed and is not adapted to the available viewport.

### Expected behaviour

The modal dialog should adapt to the viewport, in particular, text areas should expand to use all available size.

![actual behaviour](https://cloud.githubusercontent.com/assets/1285126/25001340/6248bbf0-2045-11e7-918b-51a51402b93c.png)
![expected behaviour](https://cloud.githubusercontent.com/assets/1285126/25001341/62498cb0-2045-11e7-9185-19be2fd25b02.png)
### Configuration

- Kanboard version: 1.0.42
- Browser: Chromium 57

**Comment by ngosang** [comment]
I realized that this is also causing #2814

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
