### ISSUE TITLE
Docker volumes with host-path

### ISSUE THREAD

**Issue by Braintelligence** [kanboard/kanboard#3198]
I want to bind volumes to a host-path in docker. Due to permission problems this doesn't work. In the Dockerfile the chown with nginx:nginx propably fails when you try to do this on host-mounted volumes.

### Steps to reproduce

1. Instead of `- kanboard_data:/var/www/app/data` try `- /my/host/path:/var/www/app/data` in docker-compose.yml
2. See error in web browser that nginx was unable to reach the path due to permission problems

### Configuration

Current docker-compose.yml on Rancher with only difference in the docker-compose.yml being usage of host-path volumes.

**Comment by fguillot** [comment]
Adding a custom entry-point that chmod/chown the folder during startup could solve the issue or changing the permissions of the folder on the host could do the same.

**Comment by stratosgear** [comment]
Same here.

Adding `/backup/kanboard/data:/var/www/app/data` as a mounted volume in Rancher gives me:

    Internal Error: The directory "/var/www/app/app/../data" must be writeable by your web server user

I only solved it by doing `chmod 777 /backup/kanboard/data` (and /plugins) on my host machine, but I do not like it!!! :disappointed:

**Comment by obitech** [comment]
+1

**Comment by fguillot** [comment]
There is now an entrypoint that chown the folders when the container is started. That should solve your issue.

See https://github.com/kanboard/kanboard/blob/master/docker/usr/local/bin/entrypoint.sh#L3-L4
