### ISSUE TITLE
Activity stream showing only the last week activity.

### ISSUE THREAD

**Issue by Panosmit** [kanboard/kanboard#3202]
First of all thanks for this product and your efforts. It's amazing!!!

The Activity stream, seems to keep only the last week in database. I want to have Activity stream for at least 6 months history for each task. Is it feasible?
### Configuration

Application version: 1.0.40
PHP version: 7.0.13
PHP SAPI: apache2handler
OS version: Windows NT 6.3
Database driver: mysql
Database version: 10.1.19-MariaDB
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Best Regards
PM

**Comment by fguillot** [comment]
The number of events is hard-coded to 1000, you could bump the value if necessary: https://github.com/kanboard/kanboard/blob/master/app/Model/ProjectActivityModel.php#L28

**Comment by Panosmit** [comment]
Thank you!!!
