### ISSUE TITLE
Gantt plugin - search issues

### ISSUE THREAD

**Issue by tkadlecmichal** [kanboard/kanboard#3203]
**Please, do not create duplicate issues**

### Actual behaviour

I deployed Kanboard as Docker container. As a next step, installed Gantt plugin directly from application GUI. When I try to use any filtering/searching in the gantt view, I receive dollowing message:
`Internal Error: Controller not found`

### Expected behaviour

Ideally the filtering/searching would work in Gantt view the same way as in the Board or List view.

### Steps to reproduce

1. Log in to the application as the administrative user
2. Click on button "Gantt"
3. Enter a new string into filtering textbox and hit Enter
4. get `Internal Error: Controller not found`

### Configuration

Application version: 1.0.42
PHP version: 7.0.9
PHP SAPI: fpm-fcgi
OS version: Linux 4.4.0-72-generic
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by fguillot** [comment]
Duplicate with https://github.com/kanboard/plugin-gantt/issues/1

**Comment by fguillot** [comment]
It should be fixed in version 1.0.43 and Gantt plugin v1.0.1
