### ISSUE TITLE
Feature request : add options to custom dashboard overview

### ISSUE THREAD

**Issue by nqb** [kanboard/kanboard#3204]
### Actual behaviour

In 1.0.42, you can't customize dashboard overview.

### Expected behaviour

Options/Preferences to customize dashboard overview : 

- print/hide projects on the dashboard
- print/hide tasks (according to their columns)
- print/hide subtasks (according to their status)

### Steps to reproduce

I post this feature request because in my configuration, when you have ~40 projects with many task and subtasks, dashboard take time to be load. See attachment.
![time](https://cloud.githubusercontent.com/assets/10830260/25169346/012408d8-24e7-11e7-97c6-8845fdd26400.png)

### Configuration

Application version: 1.0.42
PHP version: 5.4.45-0+deb7u2
PHP SAPI: apache2handler
OS version: Linux 3.2.0-4-amd64
Database driver: sqlite
Database version: 3.7.13
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by rautamiekka** [comment]
You're on Window$ 7 yet you're using rather ancient Firefox.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. I cannot make everything configurable. The best approach is probably to write a custom plugin.

Thank you for your understanding
