### ISSUE TITLE
SQL error upgrading from 1.39 to 1.40 or 1.41

### ISSUE THREAD

**Issue by SchmilK** [kanboard/kanboard#3205]
**Please, do not create duplicate issues**

### Actual behaviour
Upon updating to Kanboard to version 1.41 I get the erorr
Unable to run SQL migrations: Running migration \Schema\version_112, SQLSTATE[23000]: Integrity constraint violation: 19 columns name, project_id are not unique (You may have to fix it manually)

Tell us what happens
I found one project_id that was close.  One was 1 on 1 - Michael S and the other was 1 on 1 - Michael S. (period at the end)  Changing both of those did not resolve the issue, not sure where else to look.

### Expected behaviour

Tell us what should actually happen
Server should just upgrade clean.

### Steps to reproduce

Please supply step-by-step instructions so that anyone with the same environment can reproduce the issue. Whenever you offer a description, imagine
yourself in the shoes of someone who has never encountered this problem before and would like to know exactly how to observe it under a given set of conditions.
Here is an example:

1. Log in to the application as the administrative user
2. Click on button X, then on the modal dialog that appears, click Y
3. Wait for 3 seconds, and note the appearance of an unexpected message

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

Application version: 1.0.39
PHP version: 5.4.16
PHP SAPI: apache2handler
OS version: Linux 3.10.0-514.10.2.el7.x86_64
Database driver: sqlite
Database version: 3.7.17
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by fguillot** [comment]
Can you check if you can solve this issue in the same way as this ticket: https://github.com/kanboard/kanboard/issues/3115 ?

**Comment by SchmilK** [comment]
I did look through that before I put the case in.  Unfortunately I cannot find what it thinks is a duplicate.

Can you clarify more what that message means so I can investigate more in SQL?
"19 columns name, project_id are not unique"

**Comment by fguillot** [comment]
This constraint fail because there are 2 swimlanes with the same name inside the same project. This might happens during the migration 122.

Before you upgrade, can you check if you have any swimlane that you explicitly named "Default swimlane": `SELECT name from swimlanes WHERE name='Default swimlane';`. If you have any, rename the swimlane name to something else and rerun the migration.

The goal of this migration is to remove the concept of default swimlanes. All "fake" default swimlanes are converted to real swimlanes.

**Comment by SchmilK** [comment]
There are no 'Default swimlane' in the swimlanes table, but in Table:projects I do see 63 projects that have default_swimlane='Default swimlane'

**Comment by fguillot** [comment]
Is it possible for you to send me a sanitized version of your database? If yes my email: fred@kanboard.net (it will be easier to troubleshoot this issue)

**Comment by aaron832** [comment]
Having this same issue.  Manually changed all swimlane names to be unique.  Still getting:
Internal Error: Unable to run SQL migrations: Running migration \Schema\version_112, SQLSTATE[23000]: Integrity constraint violation: 19 columns name, project_id are not unique (You may have to fix it manually)

What was the result from working with SchmilK?

**Comment by SchmilK** [comment]
I haven't had a moment to look into how to sanitize the database, and I haven't been able to resolve on my own.

Fred if you have a tip on DB sanitizing I'll get around uploading for you.

**Comment by fguillot** [comment]
@SchmilK What I mean by sanitizing your db is simply remove or override any sensitive information that you could have in your db (people names, emails, passwords...). Except for the tables that seems to cause the issue.

**Comment by SchmilK** [comment]
Email with attachment sent.  Thank you!

**Comment by SchmilK** [comment]
Totally just found the problem and fixed it!

I had to go page by page through each of the swimlane pages
i.e. 
https://servername.com/kanboard/?controller=SwimlaneController&action=index&project_id=_PROJECTIDNUMBER

In there I had found that some projects had an inactive default swimlane that matched and active swimlane.  I renamed the default to 'General' and made it active and then proceeded to upgrade the server.  Voila!  It worked!

Here is an example.

![image](https://user-images.githubusercontent.com/4335981/26994316-c2595e96-4d2c-11e7-9ef3-9fb79b9d198d.png)

**Comment by aaron832** [comment]
Thanks SchmilK.  Also important for anyone having issues.  You must rename "Default Swimlane" to "General" or something else for all of your projects.

**Comment by fguillot** [comment]
@SchmilK I'm closing this issue since you manage to make it works.

**Comment by fguillot** [comment]
By the way, the SQL migration has been improved to avoid this problem in the future.
