### ISSUE TITLE
Suite ticket 3184 - Groupes Synchronisation LDAP Kanboard Active Directory 2

### ISSUE THREAD

**Issue by Richard76000** [kanboard/kanboard#3206]
Bonjour, merci pour ces infos.

Maintenant j'ai réussi à voir les groupes. J'ai maintenant un nouveau soucis. Quand j'ajoute un groupe à un projet, je vois bien le groupe comme ci-dessous
![image](https://cloud.githubusercontent.com/assets/27015044/25220888/8360ab0e-25b3-11e7-8240-8e524cb6b995.png)

Mais si je me connecte avec une autre personne qui ne fait pas du tout partie de ce groupe ni membre du projet il est ajouter quand même

![image](https://cloud.githubusercontent.com/assets/27015044/25220969/c36f7ea0-25b3-11e7-9668-566d924dc5f9.png)

Nora.Azzaze fait partie du groupe LDAP > Groupe Urbanisme

Voici ma configuration sur la partie des groupes : 

// LDAP attribute to find groups in user profile
define('LDAP_USER_ATTRIBUTE_GROUPS', 'member');

// LDAP attribute for user avatar image: thumbnailPhoto or jpegPhoto
define('LDAP_USER_ATTRIBUTE_PHOTO', '');

// LDAP attribute for user language, example: 'preferredlanguage'
// Put an empty string to disable language sync
define('LDAP_USER_ATTRIBUTE_LANGUAGE', '');

// Allow automatic LDAP user creation
define('LDAP_USER_CREATION', true);

// LDAP DN for administrators
// Example: CN=Kanboard-Admins,CN=Users,DC=kanboard,DC=local
define('LDAP_GROUP_ADMIN_DN', '');

// LDAP DN for managers
// Example: CN=Kanboard Managers,CN=Users,DC=kanboard,DC=local
define('LDAP_GROUP_MANAGER_DN', 'CN=Kanboard,OU=xxxxxxx,DC=xxxxxx,DC=xxxxxxxxx');

// Enable LDAP group provider for project permissions
// The end-user will be able to browse LDAP groups from the user interface and allow access to specified projects
define('LDAP_GROUP_PROVIDER', true);

// LDAP Base DN for groups
define('LDAP_GROUP_BASE_DN', 'dc=xxxx,dc=xxxxxxxx');

// LDAP group filter
// Example for ActiveDirectory: (&(objectClass=group)(sAMAccountName=%s*))
 define('LDAP_GROUP_FILTER', '(&(objectClass=group)(sAMAccountName=%s*))');

// LDAP user group filter
// If this filter is configured, Kanboard will search user groups in LDAP_GROUP_BASE_DN with this filter
// Example for OpenLDAP: (&(objectClass=posixGroup)(memberUid=%s))
define('LDAP_GROUP_USER_FILTER','(objectClass=group)');

// LDAP attribute for the group name
define('LDAP_GROUP_ATTRIBUTE_NAME', 'cn');

Dans l'attente de votre retour. Merci par avance.

**Comment by Richard76000** [comment]
Avez-vous des nouvelles à mon sujet ?

**Comment by fguillot** [comment]
As far as I know, the LDAP attribute to fetch groups in user profile in `memberOf` for Active Directory, not `member` (take a look to the option `LDAP_USER_ATTRIBUTE_GROUPS`). 

There are a couple of example here: https://kanboard.net/documentation/ldap-configuration-examples
