### ISSUE TITLE
File Upload Link not working

### ISSUE THREAD

**Issue by ElLoko** [kanboard/kanboard#3207]
### Actual behaviour

File Upload Link not working / not executing

### Expected behaviour

I expect a file upload menu but nothing will happen

### Steps to reproduce

Clicking the link to add a document to a task will not open a screen for uploading the file. Screenshot is working.

### Configuration

- Kanboard version: 1.0.42
- Database type and version: sqlite
- PHP version: 7
- OS: Windows Server 2012 - IIS
- Browser: Crome

**Comment by fguillot** [comment]
I have never been able to reproduce this issue after all this time. You seems to be the only one to have this problem. Unfortunately, you will have to investigate by yourself and potentially submit a patch.
