### ISSUE TITLE
Delete all not checked subtasks / Delete all checked subtasks

### ISSUE THREAD

**Issue by jbarotin** [kanboard/kanboard#3208]
Feature proposition

### Actual behaviour
I'm using the "duplicate task" feature to split in two a task finished (with not checked sub task) and copy subtasks in a new task for my backlog. So, in this use case, after the duplication of a task with lot of subtaks, it's a bit painfull to : 
- delete checked subtask in the new created task. 
- delete uncheck task in the current finished task 

### Expected behaviour
An option in the task view that aim to delete all uncheck or all checked subtask will make my life easier (or any other options that help to manage subtask by group).

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
