### ISSUE TITLE
Feature: UML diagramms with PlantUML

### ISSUE THREAD

**Issue by phoen1x** [kanboard/kanboard#3210]
I wanted to ask if a PHP developer wants to team up to implement a [PlantUML](http://plantuml.com/) plugin. All that needs to be done by the developer is to write a **view-replace Plugin** for Kanboard which gets the Markdown before it is rendered in Kanboard and simply replace **TEXT-FOO** to **TEXT-BAR**.

Which will enable me to translate my [no-brainer business logic in Java](https://gitlab.com/phoen1x/livingfire-docbook/blob/master/book/src/main/java/de/livingfire/PlantumlConverter.java) and render for example a sequence diagramm like this

![Sequence Diagram](https://gitlab.com/phoen1x/livingfire-docbook/wikis/media/sequence2.png)

from this Markdown code

```
```plantuml
@startuml
Kanboard -> Plugin: send markdown
Plugin -> Plugin: preg_match plantuml content
    loop plantuml content
        Plugin -> Plugin: generate content hash 693d9a0698aff95c
        Plugin -> Plantuml: send text
        Plantuml -> Plugin: send image
        Plugin -> Plugin: save image to /images/693d9a0698aff95c.png
        Plugin -> Plugin: preg_replace ![uml](/images/693d9a0698aff95c.png)
    end
Plugin -> Kanboard: send markdown with images
@enduml
`` `
```

Hopefully it is as easy like this: 

1. check [PlantUML PHP capability](http://plantuml.com/code-php) 
2. create a **plugin-example-view-replace**
3. inject business logic
4. the PHP developer can take the credit
5. everybody can use UML diagrams in Kanboard

**Comment by fguillot** [comment]
I'm closing this ticket for inactivity. I let people from the community develop such plugin.
