### ISSUE TITLE
Restrict Email Updates

### ISSUE THREAD

**Issue by rakesh1084** [kanboard/kanboard#3211]
### Actual behaviour

Edit Profile Page allows end users to modify the Email.
![image](https://cloud.githubusercontent.com/assets/20356619/25324448/94969338-28e3-11e7-97d6-93bba9ac9576.png)

### Expected behaviour

Can we have a restriction not to change this, as in corporate environment we might not like to send the communications outside the corporate email...?
or in the User Management Screen an option to "Restrict edit Profile" can also be thought.

### Steps to reproduce

1. Log in to the application as the any user
2. Goto Profile --> Edit Profile
3. Try to change the Email Address. 

### Configuration
all latest.

**Comment by rautamiekka** [comment]
'all latest versions' is a really useless way of saying which versions you're running.

**Comment by rakesh1084** [comment]
**Agree** that 'all latest versions' is a really useless way of saying which versions you're running.

`Configuration`

    Application version: 1.0.41
    PHP version: 5.3.28
    PHP SAPI: cgi-fcgi
    OS version: Windows NT 6.2
    Database driver: mysql
    Database version: 5.6.31
    Browser: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by fguillot** [comment]
If you are using this software in a corporate environment you are better to use LDAP authentication.

If you really need this feature, the best way is to contribute to the project or create your own plugin. The goal of this software is to stay simple, we cannot add one billion features to satisfy all possible use cases.
