### ISSUE TITLE
Feature Request:: Add custom URL Links in the top right menu

### ISSUE THREAD

**Issue by rakesh1084** [kanboard/kanboard#3212]
### Actual behaviour

In the top right corner menu only kanboard links are available.

### Expected behaviour
We want users to stay within kanboard and navigate to other web pages, for e.g., from kanboard to another reporting system which has different URL.
I tried adding few lines in user_dropdown.php and it worked.
However if there could be any configurations from the Administrator mode that would be fine.
Like Add Custom URL / Links, preferrably kanboard variables can also be passed like userid, current project ID, and so on as per the configuration.

**Comment by Busfreak** [comment]
So create a plugin (https://kanboard.net/documentation/plugins) and use the hook 'template:header:dropdown' (https://kanboard.net/documentation/plugin-hooks).

**Comment by fguillot** [comment]
As mentioned, you could write a custom plugin for that.
