### ISSUE TITLE
Bug: Android app does not connect

### ISSUE THREAD

**Issue by natrius** [kanboard/kanboard#3214]
### Actual behaviour
Open the app, insert URL and the credentials to my kanboard on my webspace "Password incorrect". (User created manually via admin).

(With the last version there was all the time "You are using a version prior to 1.0.38" - but since the update that does not happen anymore)

### Expected behaviour
Login successful

### Steps to reproduce
1, Create user on KanBoard Admin
2, download app from f-droid store
3, insert credentials

### Configuration
    Application version: 1.0.41
    PHP version: 7.0.15
    PHP SAPI: cgi-fcgi
    OS version: Linux 3.14.79-grsec-hosting-web-3.14
    Database driver: sqlite
    Database version: 3.14.2
    Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

### Android app
   Downloaded via F-Droid (Kandroid)
   Version: 0.5.4

### Questions
Do i need something special with the user? I tried "remote" and "local" (i suppose its not meant for that as it states "for third-party-authentication").
I could not find any instructions where is stated that i need to do something special.
If the app is not from your side, sorry for this issue. Could not find something else.

**Comment by bttrx** [comment]
1. What URL do you enter exactly? Is is it in the format `http://...`?
2. Can you upgrade Kanboard to version 1.0.4**2**.

**Comment by natrius** [comment]
1. Yes, http://natrius...
2. Check, its done.

### Configuration
    Application version: 1.0.42
    PHP version: 7.0.15
    PHP SAPI: cgi-fcgi
    OS version: Linux 3.14.79-grsec-hosting-web-3.14
    Database driver: sqlite
    Database version: 3.14.2
    Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0

Still not working. "Das Passwort ist ungültig" - "Password not accepted"
I changed the password to something REALLY easy so i cannot mistype by mistake.

**Comment by fguillot** [comment]
There is no official Android application for Kanboard, you should contact the author of the application directly.

**Comment by bttrx** [comment]
I'm using Kanboard 1.0.42 and Kandroid 0.5.4 and don't have any login problems.

Can you login with admin/admin?

I also looked at the Kandroid source code. Passwords have to be longer than 4 characters. Is that the case?

**Comment by natrius** [comment]
Oh, my fault, i could not find the app and there is a folder "kanboard/app/" so i thought its here made too.
I found it now and will drop there the problem. Thanks anyway for your help :)

@bttrx 
Not possible. I changed the password, but still no.
And the easy password i set for the default user is longer than 4 characters.
