### ISSUE TITLE
Plugins not detected

### ISSUE THREAD

**Issue by ElucGeek** [kanboard/kanboard#3219]
### Actual behaviour

In the sub-folder "plugins" I got 3 plugins in their respective sub-folders:
/Kanboard/plugins/Calendar
/Kanboard/plugins/Gantt
/Kanboard/plugins/Subtaskdate

In config.php I got:

// Plugins directory
define('PLUGINS_DIR', 'plugins');

// Plugins directory URL
define('PLUGIN_API_URL', 'https://kanboard.net/plugins.json');

// Enable/Disable plugin installer
define('PLUGIN_INSTALLER', true);

BUT when I navigate:

On the plugins page http://IP_OF_SERVER/kanboard/?controller=PluginController I got:
"There is no plugin loaded."

On the plugins directory page http://IP_OF_SERVER/kanboard/?controller=PluginController&action=directory I got:
"Your Kanboard instance is not configured to install plugins from the user interface."

### Expected behaviour

I should see the plugins that are in the sub-folder plugins and be allowed to install plugins from the directory.

### Steps to reproduce

1. Fresh install of Kanboard on an Ubuntu VM
2. Unzip plugins in the plugins directory
3. Log as admin
4. Browse to the plugins page

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

    Application version: 1.0.42
    PHP version: 7.0.15-0ubuntu0.16.04.4
    PHP SAPI: apache2handler
    OS version: Linux 4.8.0-49-generic
    Database driver: mysql
    Database version: 5.7.17-0ubuntu0.16.04.2
    Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0

### Additional information

The issue seams similar as issue https://github.com/kanboard/kanboard/issues/2598 but I've got already the missing line in the configuration file.

By the way, do I need to restart Kanboard to apply a change in config.php ? I've seen nowhere how to restart it, so I've done a full reboot to be sure but it doesn't change the issue.

**Comment by fguillot** [comment]
- You should check the permissions of the plugins folder and subfolders. That must be writeable by the webserver user if you would like to install plugins from the user interface.
- Just in case, put the absolute path in to the plugins folder in `PLUGINS_DIR`

**Comment by ElucGeek** [comment]
Indeed, the plugins folder was www-data 777 but the subfolder were to another user 700. I've set owner of all sub folder and files to www-data and 777, it's OK now (thus I should set 755 maybe).

The other issue, were I get "Your Kanboard instance is not configured to install plugins from the user interface." while  // Enable/Disable plugin installer define('PLUGIN_INSTALLER', true); is set to true, is still open but I can work without it now.

Thanks

**Comment by fguillot** [comment]
Your should check that you have all requirements to install plugins from the user interface: https://kanboard.net/documentation/plugin-directory

**Comment by aljawaid** [comment]
@fguillot 
After setting the above folder/subfolder permissions correctly and checking the three config options on v1.40 I get this issue when I debug in Firefox>Inspect
``“https://domain.co.uk/kanboard/p?” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff)``

Which does not show the extensions directory but DOES show my installed plugins.

Is this related?
