### ISSUE TITLE
Sort by Start Date [Feature Request]

### ISSUE THREAD

**Issue by littlebunyip** [kanboard/kanboard#3223]
Hello,
This software is great. Thank you everyone!

### Context ###
We are a small farm in South Australia growing microgreens and mushrooms. We use this software to schedule our planting times for microgreens which requires the use of "Start Date" as critical to our growing and delivery times. "Start Date" changes throughout the year due to climactic factors. Our "Due Dates" are fixed, recurring every 14 days.

I have hacked the ability to sort by "Start Date" into the HTML of the list view on version 1.0.33 (see attached file Kanboard List View.png) so we can see what we need to plant on any given day. I cannot get my hack to work in the dashboard. On every update I have to hack this back into the list view which is one reason I have stopped updating at 1.0.33. I am not a programmer, just a farm hack.

![kanboard list view](https://cloud.githubusercontent.com/assets/17291869/25506820/b7d9a694-2be7-11e7-8148-56ed76867263.png)

### Actual behaviour

Currently, in all versions, the dashboard and the list view allow the sorting of tasks by "Due Date".

### Expected behaviour

Ability to sort tasks and sub-task by "Start Date" in the dashboard and the list view.
Ability to set the default sort order to "Start Date" for tasks in the dashboard and list view.

### Steps to reproduce

This is a feature request not really an "issue".

### Configuration

all versions.

**Comment by fguillot** [comment]
In version 1.0.43, you can now sort by start date.

**Comment by littlebunyip** [comment]
That's amazing! Thanks so much @fguillot
