### ISSUE TITLE
Feature Request: Add "Identificator" to Task Number

### ISSUE THREAD

**Issue by wucherpfennig** [kanboard/kanboard#3224]
It would help to add the project Identification Tag to the task number in order to "quick copy" this reference. 

eg. we are using those numbers to tag git commits.
instead of commiting just "#620" we would like to have "<Identificator>#620"

![image](https://cloud.githubusercontent.com/assets/3634653/25519471/3b6a5e30-2bf8-11e7-8534-723fbf27f3a8.png)

![image](https://cloud.githubusercontent.com/assets/3634653/25519490/4c418b0c-2bf8-11e7-837e-ea4d82b84dd7.png)

**Comment by AlgyTaylor** [comment]
Weirdly, I was thinking about something similar, although not quite the same.

I have been thinking about the Gogs plugin for Kanboard, although I guess the same could be said for github/gitlab.  We use Kanboard for both software development (ie will have an issue number) AND non-software development (ie will not have an issue number) tasks.  This would mean that potentially you could have a conflict where the Gogs/Github/.. issue number is the same as an existing task ID.

However, I also have a problem with commenting in the way @wucherpfennig mentioned.  Say if I comment my gogs commit "#620 my lovely commit", it will try to link to issue #620 on **Gogs** as well as in Kanboard (see image)

![gogs](https://cloud.githubusercontent.com/assets/1220211/25521171/7e0bc438-2bf6-11e7-8e53-5d1fe2d1a97e.png)

What would be useful, though, is to have **a separate field** where I could link an external issue tracker (whether it's gogs, github, or something else) to a task on kanboard.  This would allow me to keep both my Gogs issues clean, and link them nicely in to Kanboard ...

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
