### ISSUE TITLE
How do I Change Board/Project Default Filter

### ISSUE THREAD

**Issue by seancarson** [kanboard/kanboard#3225]
**Please, do not create duplicate issues**

### Actual behavior

When opening a new or existing board the filter defaults to Status:Open.  

### Expected behavior

In my kanboard instance I would like to change the default filter for all boards to Status:Open Status:Closed

### Steps to reproduce

1. Log into kanboard as administrator or regular users. 
2. Create or open and existing project.  
3. You will now see a text  area/filter with status:open

 I attempted to follow some of the example set in request https://github.com/kanboard/kanboard/issues/1295
but this does not apply to the version I am using.  

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.42
- Database type and version: postgres 9.3.16
- PHP version: 5.5.9-1ubuntu4.21
- OS:Linux 3.13.0-116-generic
- Browser: Chrome/57.0.2987.133

Thanks

SC

**Comment by fguillot** [comment]
See https://github.com/kanboard/kanboard/blob/master/app/Core/User/UserSession.php#L179

Note: It's more appropriate to post your questions on the forum instead of the bug tracker

**Comment by seancarson** [comment]
will do next time.  Thank You

On Apr 30, 2017, at 12:06 PM, Frédéric Guillot <notifications@github.com<mailto:notifications@github.com>> wrote:


See https://github.com/kanboard/kanboard/blob/master/app/Core/User/UserSession.php#L179

Note: It's more appropriate to post your questions on the forum instead of the bug tracker

**Comment by lohierf** [comment]
Thank you, I was also looking to change this default filter to "status:all" instead of "status:open".

For a better user experience, I also changed the default filter of the "Reset filters" button to "status:all" : https://github.com/kanboard/kanboard/blob/master/app/Template/project_header/search.php#L11
