### ISSUE TITLE
Please add the Danish Krone "DKK" to the Currency rates.

### ISSUE THREAD

**Issue by izno** [kanboard/kanboard#3228]
### Actual behaviour

Currency rates do not include Danish Krone

### Expected behaviour

DKK - Danish Krone

**Comment by NinjaPewPew** [comment]
Maybe that's an opportunity for you to contribute to the project! It seems to be a fairly easy change. Have a look at this [file here](https://github.com/kanboard/kanboard/blob/master/app/Model/CurrencyModel.php).

**Comment by izno** [comment]
@NinjaPewPew – Thanks! I'm new to this... still learning!

**Comment by fguillot** [comment]
The PR has been merged.
