### ISSUE TITLE
Can't access to my new task attribute everywhere

### ISSUE THREAD

**Issue by ptiyo** [kanboard/kanboard#3229]
### Actual behaviour

I create a new plugin which extends the Task table with a new attribute but I can't access to it in my overriden task_footer template.

I have the same behaviour with the TaskBoardDate plugin which adds the date_board attribute in the database but it's not accessible in the template.

### Expected behaviour

I would like to access to my new attribute in the template to display it.

### Steps to reproduce

We can reproduce it with the TaskBoardDate plugin.
1 - Just activate the TaskBoardDate plugin.
2 - In Template/board/task_footer.php, try to use/display "$task['date_board']"
3 - It doesn't work

The problem seems to come from the TaskFinderModel->getExtendedQuery() function which lists a subset of the attributes.
To get around, I've overriden the TaskFinderModel class and the getExtendedQuery function to include all the Task attributes (TaskModel::TABLE.'.*') instead of the specific list.
 
### Configuration

Application version: 1.0.42
PHP version: 7.0.18
PHP SAPI: apache2handler
OS version: Windows NT 10.0
Database driver: sqlite
Database version: 3.14.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by fguillot** [comment]
You will probably need to contribute upstream to implement what you need or use task metadata.
