### ISSUE TITLE
[LDAP] Hide "Forgotten password" link in login page

### ISSUE THREAD

**Issue by sulian** [kanboard/kanboard#3230]
### Actual behaviour

Actually, in the login page, an user can see the link "forgotten password".

### Expected behaviour

If kanboard use the LDAP authentification, can you add an option to hide the "forgotten password" link ?

### Configuration

- Kanboard version: 1.0.42 
- Database type and version: sqlite / 3.7.13
- PHP version: 5.4.45
- OS: Debian / Linux 3.2.0-4
- Browser: Mozilla Firefox

**Comment by Busfreak** [comment]
please have a look:
- log in as admin
- go to settings
- go to Application settings
- untick 'Enable "Forget Password"'
- have fun

**Comment by sulian** [comment]
My mistake, thanks a lot.
