### ISSUE TITLE
User should receive notifications when mentioned via an edit of a comment

### ISSUE THREAD

**Issue by asoete** [kanboard/kanboard#3232]
### Actual behaviour

User doesn't receive notifications when mentioned via an edit of a comment

### Expected behaviour

User should receive notifications when mentioned via an edit of a comment

### Steps to reproduce

1. Create a comment
2. Save comment
3. Edit comment and add a mention to a user (`@user`)
4. User should receive notification about mention but doesn't

### Configuration

    Application version: 1.0.42
    PHP version: 5.4.16
    PHP SAPI: apache2handler
    OS version: Linux 3.10.0-327.13.1.el7.x86_64
    Database driver: postgres
    Database version: 9.4.9
    Browser: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by rautamiekka** [comment]
First, update your ancient PHP.

**Comment by asoete** [comment]
@rautamiekka This shouldn't be an issue there PHP5.4.x is listed as supported: https://kanboard.net/documentation/requirements

![image](https://cloud.githubusercontent.com/assets/5277186/25700447/18c016b6-30c8-11e7-92a2-fc75c176b71f.png)

(Note: PHP 5.4.16 is the default PHP version available in CentOS7)

**Comment by rautamiekka** [comment]
@asoete Just cuz Kanboard supports it (and CentOS being retarded as usual) doesn't mean it won't be a problem.

**Comment by aljawaid** [comment]
I'm on PHP 7 and still wish for this feature to be implemented.  Mention+notification work hand in hand otherwise I don't see the point of a mention (would have to do separate comments).

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
