### ISSUE TITLE
Plugin question

### ISSUE THREAD

**Issue by izno** [kanboard/kanboard#3237]
How can I access this part of a core function in a plugin:

I'm new to PHP, so please be patient with me... I need to add additional information to the author part of the sender in

> [Kanboard\Core\Mail\Client](https://github.com/kanboard/kanboard/blob/master/app/Core/Mail/Client.php)

```
    /**
     * Get author name
     *
     * @access public
     * @return string
     */
    public function getAuthorName()
    {
        $author = 'Kanboard';

        if ($this->userSession->isLogged()) {
            $author = e('%s via Kanboard', $this->helper->user->getFullname());
        }

        return $author;
    }

```
I would appreciate some guidance.
Thank you in advanced.

**Comment by izno** [comment]
...anyone?

**Comment by NinjaPewPew** [comment]
I don't understand the question. You want more information from the author, so far so good. But what information are you looking for specifically? What are you trying to do?

**Comment by izno** [comment]
@NinjaPewPew Thanks for the reply. One information could be the project Identifier, but I also need/would like to add additional data/metadata which are Danish standards for tag/tracking documents in building industry. These codes must be added to all documents. This also helps the search for the documents/emails in the in-box/document folders...

example of the generated data: [ 3341_A_2_GEO_01]
3341 -> project ID/Nr.
A -> Provider type (A for Architect)
2 -> Place/Location/Level
GEO -> Content type (Geometry)
01 -> Version/Revision

I need to write a plugin to provide this type of identifiers eg. when sending a task by email... I know it's complicated and maybe not so practical.

I would appreciate any guidance...
Thank you in advanced

**Comment by izno** [comment]
I was trying (see below) – beginning with hand code the [DATA]. It's from the documentation example... but it's not working!

I need this format as in the mail:

**From: [3341_A_2_GEO_01] UserName via Kanboard <<notifications@kanboard.local>>**

```

<?php

namespace Kanboard\Plugin\MailData;

use Kanboard\Core\Mail\Client;
use Kanboard\Core\Plugin\Base;

class AuthorName extends Client
{
    public function getAuthorName()
    {
        $author = parent::getAuthorName();

        if ($this->userSession->isLogged()) {
            $author = e('[3341_A_2_GEO_01] %s via Kanboard', $this->helper->user->getFullname());
        }

        return $author;
    }
}

class Plugin extends Base
{
    public function initialize()
    {
        $this->container['send'] = $this->container->factory(function () {
            return new AuthorName();
        });
    }
    public function getPluginName() { return 'Mail Data'; }
    public function getPluginDescription() { return t('My plugin is awesome'); }
    public function getPluginAuthor() { return 'Name'; }
    public function getPluginVersion() { return '1.0.0'; }
    public function getPluginHomepage() { return 'https://github.com/plugin-myplugin'; }
}
```

**Comment by fguillot** [comment]
You will have to create a custom Mail client class the replace the method `getAuthorName()` and override the default one with yours in the container `emailClient` (take a look at `MailProvider` class).
