### ISSUE TITLE
Removed users in group management

### ISSUE THREAD

**Issue by robsonpiere** [kanboard/kanboard#3238]
### Actual behaviour

When you try to remove a user from a group, it is removed from the application.

### Expected behaviour

When trying to remove a user from the group as in previous versions the same should exit the group, but not be removed from the application.

### Steps to reproduce

1 - Go to Groups management -> access any group;
2 - Choose a user and click on the submenu to remove (The option to remove from group no longer appears);
3 - The user will be removed from the application as a whole and not only from the group.

### Configuration

I tested in two configurations:

Versão da aplicação: 1.0.41
Versão do PHP: 5.6.25
PHP SAPI: apache2handler
Versão do sistema operacional: Windows NT 6.1
Driver do banco de dados: mysql
Versão do banco de dados: 5.7.12-log
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36 OPR/44.0.2510.1449

Application version: 1.0.43
PHP version: 5.6.25
PHP SAPI: apache2handler
OS version: Windows NT 10.0
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36 OPR/44.0.2510.1449

**Comment by robsonpiere** [comment]
In earlier versions (1.0.37 for example), the loaded menu was in the "http: // host / kanboarad /? Controller = GroupListController & action = dissociate & group_id = '10' & user_id = 9" route.

![1 0 37](https://cloud.githubusercontent.com/assets/11904136/25901417/240a2fc6-356d-11e7-9ec9-f07a9ad09d78.png)

This driver and action still exist but have been removed from the user management menu

**Comment by fguillot** [comment]
The wrong contextual menu was displayed, this is now fixed in master.

**Comment by fguillot** [comment]
The fix is available in Kanboard v1.0.44. Thanks.
