### ISSUE TITLE
Generating User API access token throws error

### ISSUE THREAD

**Issue by dranft** [kanboard/kanboard#3239]
### Actual behaviour

When a user tries to generate an User API access token via button _Generate a new token_ on page _My profile/API_ an error is thrown:
<pre>
Undefined variable: user in /kanboard/app/Controller/UserApiAccessController.php on line 56
</pre>

### Expected behaviour

The access token should be generated and shown to the user.

### Steps to reproduce

1. Log in to the application
2. Choose the page _My profile_ in the navigation menu
3. Click on the link _API_ of section _Actions_ in the left sidemenu
4. Click on the button _Generate a new token_

### Configuration

* Application version: 1.0.42
* PHP version: 7.0.18-1~dotdeb+8.1
* PHP SAPI: fpm-fcgi
* OS version: Linux 4.8.3-pl1
* Database driver: mysql
* Database version: 10.0.30-MariaDB-1~jessie
* Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by fguillot** [comment]
The fix is available in Kanboard v1.0.44. Thanks.
