### ISSUE TITLE
API: createProject given nonexistent owner_id succeeds

### ISSUE THREAD

**Issue by inful** [kanboard/kanboard#3240]
### Actual behaviour

When calling the API createProject with the a non existing owner_id, the request succeeds

```
{
    "jsonrpc": "2.0",
    "method": "createProject",
    "id": 2134421211,
    "params": {
    	"name": "test",
    	"owner_id" : 9
    }
}
```

results in

```
{
  "jsonrpc": "2.0",
  "result": 6,
  "id": 2134421211
}
```

### Expected behaviour

I would expect this request to be rejected, or that the behavior is documented in the API docs.

### Steps to reproduce

See above

### Configuration

Application version: master
PHP version: 7.0.9
PHP SAPI: fpm-fcgi
OS version: Linux 4.9.21-moby
Database driver: sqlite
Database version: 3.13.0

**Comment by fguillot** [comment]
The fix is available in Kanboard v1.0.44. Thanks.
