### ISSUE TITLE
API: getProjectByName returns only one project

### ISSUE THREAD

**Issue by inful** [kanboard/kanboard#3241]
### Actual behaviour

When calling getProjectByName, only the first project with the given name is returned.

### Expected behaviour

As it is no requirement for the project name to be unique, I would expect all projects with the given name to be returned.

### Steps to reproduce

Call createProject with a single param `name`:`TEST` twice.
Call getProjectByName with param `name`:`TEST` - the returned project is the first created project with the given name.

### Configuration

Application version: master
PHP version: 7.0.9
PHP SAPI: fpm-fcgi
OS version: Linux 4.9.21-moby
Database driver: sqlite
Database version: 3.13.0

**Comment by be-ndee** [comment]
I think there should be another method called "getProjectsByName" which returns, like you expect, multiple projects based on the name. So there is no problem with people, who use the getProjectByName and expect a single project to be returned.

If you create 3 projects with the names `project 1`, `project 2` and `p 3` and you call `getProjectsByName` with the parameter `name: "project"` it should return `project 1` and `project 2`.

**Comment by inful** [comment]
@be-ndee I agree with the proposed name change (and also the extended functionality), but I still consider the current behavior of getProjectByName (because of the non-uniqueness of project names) to be nonsensical with regards to the name. The proper naming of the method as of today would be getFirstCreatedProjectByName or getEarliestCreatedProjectByName (or even getOneOfTheProjectsNamed.
Joking aside, I guess @fguillot is well aware of API stability issues, and will find a proper way of handling this. Documenting the actual behavior of the method would actually fix the issue, as the user would not draw incorrect conclusions based on the name of the method (you could at least tell people like me to rtfm when we open issues while bewildered:)).

**Comment by jpcanepa** [comment]
I agree with @inful that the current implementation does not make much sense. I think it was written with the assumption that projects normally don't repeat names. Today, the code just does a query for projects with the given name, and returns the first that the SQL engine returns, whatever that one may be (see `getByName` in `ProjectModel`, that is only used by this API, BTW).

I'd vote for removing the original method and replacing it by @be-ndee propopsal of `getProjectsByName` that performs a "like" search to return projects that have the supplied string as part of their names. At least that behavior can be documented more consistently, I think. The current API doc for the `getProjectByName` (see [here](https://github.com/kanboard/kanboard/blob/master/doc/en_US/api-project-procedures.markdown#getprojectbyname)) kind of implicitly suggest the assumption is there is only one project by the supplied name.

**Comment by samwaus** [comment]
I would like to work on this guys. I'm new to this project and might need some guidance. If you guys are happy to allow me to work on this issue, I will do my best to fix this.

**Comment by jpcanepa** [comment]
I mean, no one is stopping you from opening a pull request, @samwaus. Go ahead, give it a shot! It's up the the maintainer (@fguillot) to merge it in, but no harm done in proposing a solution.
https://github.com/notifications

**Comment by AI3Zakir** [comment]
I've added the [getProjectsByName API method](https://github.com/AI3Zakir/kanboard/commit/2a00ee80b07ff02b4db18a3ced3968f877e8d8ff). 
However, as I understand, from the code (may be i'm wrong :) ) there is no functionality to check permissions on list of the projects. 
An API method getAllProjects(app/Api/Procedure/ProjectProcedure.php:49) just ignores those checks. 
Can I open pull request already? Or firstly we should decide how to handle checks on list of Projects.

**Comment by fguillot** [comment]
@inful `getProjectByName` returns only the first project because this API call has been implemented when project names were unique. It's not the case anymore.

If you still need this feature, send a patch that implement a new API call, for example `getProjectsByName`.
