### ISSUE TITLE
Internal error with data/ directory

### ISSUE THREAD

**Issue by xifu77** [kanboard/kanboard#3244]
### Actual behaviour

Installing new version 1.0.43 to CentOS Server according to manual.
Message: "Internal Error: The directory "/var/www/html/kanboard/app/../data/" must be writeable by your web server user" appears on opening site

### Expected behaviour

Login window should be visible.

### Steps to reproduce

1. WGet fresh copy of kanboard
2. unzip kanboard
3. sudo chown -R apache:apache kanboard/data
4. Open page in browser
5. Message: "Internal Error: The directory "/var/www/html/kanboard/app/../data/" must be writeable by your web server user" appears

When renaming "config.default.php" to "config.php" the message changes to "Internal Error: The directory "/var/www/html/kanboard/data/" must be writeable by your web server user"

Version 1.0.40 is working perfectly

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.43
- Database type and version: SQLite
- PHP version: 5.4.16
- OS: CentOS 7.3.1611
- Browser: Firefox Nightley 64Bit

**Comment by SchmilK** [comment]
Here is what I have in my 'upgrade notes'
Looks like you are missing the first chcon command

//Fix DATA permissions
chcon -R -t httpd_sys_content_rw_t /var/www/html/kanboard/data
chown -R apache:apache /var/www/html/kanboard/data

**Comment by rautamiekka** [comment]
> chcon -R
> chown -R

You'd be wise to have `-v`/`--verbose` flag there.

**Comment by xifu77** [comment]
Hey SchmilK,
this did the trick, thank you very much, it's working now :)
