### ISSUE TITLE
Automated action "Move the task to another column when closed" does not work correctly with "Close all tasks of this coloumn"

### ISSUE THREAD

**Issue by znegva** [kanboard/kanboard#3248]
### Actual behaviour
"Close all tasks of this column" does close all tasks of the column.
Only __one__ task is moved to another column.

### Expected behaviour
"Close all tasks of this column" does close all tasks of the column.
__All__ closed tasks should be moved to another column.

### Steps to reproduce

1. Create automated Action like this:
> Move the task to another column when closed
> Event name = Closing a task
> Destination column = Archive

2. create some open tasks in any column that is not _Archive_

3. select "Close all task of this column" in dropdown of the column (Board-View)

4. see _Actual behaviour_ as described above 

### Configuration

Application version: 1.0.42
PHP version: 5.6.21
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-642.6.2.el6.x86_64
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
