### ISSUE TITLE
Fast assign card to user

### ISSUE THREAD

**Issue by filhocf** [kanboard/kanboard#3251]
### Actual behaviour

Today, to assign a card for a user, I need click in Edit the task -> in Assignee, choice the user, and click in save.

### Expected behaviour

Can change the card, to add assigned user in it, with a behavior of mouse over present 'Assign to' and when click, open a modal window with user list to select.

### Proposal
Before:
![image](https://cloud.githubusercontent.com/assets/952596/25850845/47e808ec-349a-11e7-984b-96429f1ad294.png)

After:
![proposal](https://cloud.githubusercontent.com/assets/952596/25852040/6a1eee04-349e-11e7-8753-55f707a7c98d.png)

**Comment by Chaosmeister** [comment]
👍

**Comment by rautamiekka** [comment]
A good idea. I imagine this'll be expandable from just the allowed users.

**Comment by on-jz** [comment]
I implemented a similar function lately. Dropdowns show all users involved into the project and provide a quick filter input for projects with many users.

### Expanded tasks view:
![grafik](https://cloud.githubusercontent.com/assets/5663097/26126831/617ba532-3a87-11e7-8ef2-52209eb18ca9.png)

### Collapsed tasks view:
![grafik](https://cloud.githubusercontent.com/assets/5663097/26127106/73514c52-3a88-11e7-9050-2d26833dcf6b.png)

@fguillot could you maybe quickly provide two new javascript events? I'd need the events described below to provide a proper solution for this idea and another one that might be of interest:

- 'dropdown.opened' (dropdown rendering complete)
- 'modal.opened' (modal rendering complete)

**Comment by fguillot** [comment]
@on-jz If you already implemented this feature, do not hesitate to send a pull-request :)

**Comment by Creanimo** [comment]
Not sure if this is a new issue, but wouldn't it be handy if all other visible attributes could also be changed like this? Like if you click on the label you get a list of recently used project labels, if you click the date you get a little calendar etc.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
