### ISSUE TITLE
Use environment variable API_AUTHENTICATION_TOKEN in docker

### ISSUE THREAD

**Issue by inful** [kanboard/kanboard#3253]
### Actual behaviour

Setting API_AUTHENTICATION_TOKEN environment variable in docker does not set the token in the running server

### Expected behaviour

Setting API_AUTHENTICATION_TOKEN environment variable in docker should set the variable in the running server

Running integration tests from a ci-server would be much easier if this was the case:)

**Comment by fguillot** [comment]
This is now possible in the current master.

**Comment by inful** [comment]
Thank you:)

**Comment by fguillot** [comment]
This is now available in Kanboard v1.0.44. Thanks!
