### ISSUE TITLE
Low-width Layout improvements [1]

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#3254]
### Actual behaviour

If the width of the browser is below 1903 px, the task is displayed below the sidebars:

![image](https://cloud.githubusercontent.com/assets/13346344/25856469/5cf270ba-34d6-11e7-8f00-0a39d3f16e51.png)

This leaves a lot of blank space that could be utilized better and always requires me to scroll down to see the tasks details.

### Expected behaviour

The sidebars could be displayed without width limitation and inline.

![image](https://cloud.githubusercontent.com/assets/13346344/25857018/11c6c134-34d8-11e7-829c-649b35e15978.png)

This works to a width of 560px from which the project header becomes positioned vertically.
The sidebars could also become dropdowns after 560px.

### Steps to reproduce

Reduce the width of the browser step by step to the given values.

### Configuration

Application version: 1.0.43
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
