### ISSUE TITLE
Low-width Layout improvements [2]

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#3255]
### Actual behaviour

At a width of 768 the "board-selector-container"s width becomes 100% and moved to the next line which is a little bit confusing, since the line would still have enough blank space for the box.

Also, the "title-container" is moved below the "board-selector-container"

Width above 786px:
![image](https://cloud.githubusercontent.com/assets/13346344/25858571/5b30d216-34dc-11e7-8f13-cc43e35ce892.png)

Width below 768px:
![image](https://cloud.githubusercontent.com/assets/13346344/25858541/486cc590-34dc-11e7-942e-6d35ef8859f5.png)

### Expected behaviour

Use a smaller limit for the switch and a minimum-width for the "board-selector-container" (maybe the approximated length of the longest project name?)

The "title-container" should stay on top of the page.

### Steps to reproduce

Reduce the width of the browser below 768px.

### Configuration

Application version: 1.0.43
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
