### ISSUE TITLE
Custom Roles : (Internal Error : SQL error) since update from 1.0.41 to 1.0.42 or 1.0.43.

### ISSUE THREAD

**Issue by spychoux** [kanboard/kanboard#3256]
**Please, do not create duplicate issues**
I don't find the same

### Actual behaviour

I have some trouble since I have past to kanboard version 1.0.42 and 1.0.43. I'm trouble with "Custom Roles". In fact, I can't access. Kanboard return error message : 
> Internal Error: SQL error

### Expected behaviour

Custom roles assigned to some user are now unusable and it's a trouble for us because they can't access to task. I need to change 

### Steps to reproduce

1. Log in to the application as the administrative user
2. With version of kanboard 1.0.41 go to project setting and click on Custom roles. No problem, I can change or create a custom roles.
3. With verison of kanboard 1.0.42 or 1.0.43 go to project setting and when I trying to access to "Custom Roles". KB return the SQL error.
```
Some people are the same issue since update ?
```
### Configuration
* Application version: 1.0.43
* PHP version: 7.0.8
* PHP SAPI: fpm-fcgi
* OS version: OpenBSD 6.0
* Database driver: postgres
* Database version: 9.5.3
* Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0

Thanks for read.

**Comment by fguillot** [comment]
Can you enable the debug mode and paste the complete SQL error here?

**Comment by spychoux** [comment]
Hi,

Here you can find what I see after activate debug mode. It's directly on the Browser : 

` 
Internal Error: SQL error: SQLSTATE[42703]: Undefined column: 7 ERROR: column column_has_move_restrictions.only_assigned does not exist LINE 1: ...n_id, column_has_move_restrictions.dst_column_id, column_has... ^
`

And here It's the debug.log file : 

`[2017-05-12 21:03:14] [debug] Kanboard\Core\Controller\Runner::executeMiddleware
[2017-05-12 21:03:14] [debug] Subscriber executed: Kanboard\Subscriber\BootstrapSubscriber::execute
[2017-05-12 21:03:14] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\AuthenticationMiddleware
[2017-05-12 21:03:14] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\PostAuthenticationMiddleware
[2017-05-12 21:03:14] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\ApplicationAuthorizationMiddleware
[2017-05-12 21:03:14] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\ProjectAuthorizationMiddleware
[2017-05-12 21:03:14] [debug] Kanboard\Core\Controller\Runner::executeController => \Kanboard\Controller\ProjectRoleController::show
`

Kind regards.

**Comment by fguillot** [comment]
Can you make sure that all SQL migrations are executed properly? You seems to not have the migration 102: https://github.com/kanboard/kanboard/blob/master/app/Schema/Postgres.php#L15

**Comment by spychoux** [comment]
Hello,

When I try the command : 

> \# ./cli db:version

Result are 

>Current version: 102
>Last version: 102

If it's: 
>\# ./cli db:migrate
>Current version: 102
>Last version: 102

I need to use an other command ? Or a script ?

Thanks for your time.

**Comment by spychoux** [comment]
OK,

I investigate myself and the command of Migration don't pass before : 
> kanboard=\# ALTER TABLE column_has_move_restrictions ADD COLUMN only_assigned BOOLEAN DEFAULT FALSE ;

Execute manually and now the problem disappear. I found that my config.php are not good. I add the line : 
> define('DB_RUN_MIGRATIONS', true);

Thanks you very much I close the issue.
