### ISSUE TITLE
Search tasks - add link to board

### ISSUE THREAD

**Issue by eurodrew555** [kanboard/kanboard#3257]
### Actual behaviour

When you search for tasks, the search results that are output only have the task and the user links active.

### Expected behaviour

I think it would be useful to have the board link active as well. This would make it quicker to jump straight to the board view if required (which I'm finding I want to do regularly)

### Steps to reproduce

From the dashboard, search for tasks
The search task results only have links enabled only for the task itself and the user

### Configuration

Application version: master (1.0.43)
PHP version: 7.0.18
PHP SAPI: fpm-fcgi
OS version: Linux 4.9.15-x86_64-linode81
Database driver: sqlite
Database version: 3.7.17
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by eskaryo** [comment]
This would be a very helpful feature

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
