### ISSUE TITLE
Completed Subtasks that are still assigned are still listed in dashboard

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#3258]
### Actual behaviour

Completed but assigned subtasks are still listed in the dashboard.

### Expected behaviour

I would like to [optionally] hide completed subtasks while preserving the assignment, to see who executed the task.  
So in a task with multiple subtasks with different states (new / in-progress / complete) I'm only want to see the new and in-progress subtasks.

### Steps to reproduce

Assign and complete a subtask.
Look for it in the dashboard.

### Configuration

Application version: 1.0.43
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

**Comment by rautamiekka** [comment]
This could be expanded with a checkbox or a button to toggle temporarily showing the completed tasks, but I see 2 problems with that:

1) The database query result could grow massive under right circumstances
2) The performance impact on the user could be orders of magnitude

**Comment by marcosaccioly** [comment]
A *task not assigned* to me for which I completed a subtask weeks ago is visible now on my dashboard and there's nothing for me to do with it.

So what would be the user scenario in which that behaviour is desirable?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
