### ISSUE TITLE
Inactive users can be added to project permissions

### ISSUE THREAD

**Issue by Sengorius** [kanboard/kanboard#3259]
### Actual behaviour
It may be possible to do so, but it is weird, if you can add inactive users to Project -> Settings -> Permissions -> Allowed Users.

### Expected behaviour
If this is a desired behaviour, im fine with it. But please mark inactive users in that list (e.g. cross out the names like in user management).

### Steps to reproduce
1. Log in as admin
2. Add multiple users to the application by its default user management form
3. Set at least one user to be inactive (click on the ID and choose "Disable")
4. Go to one of your Projects -> Settings -> Permissions -> Allowed Users
5. Try to add an inactive user with the text input ("Enter user name")

### Configuration
- Application version: 1.0.42
- PHP version: 5.6.4-4ubuntu6
- PHP SAPI: cgi-fcgi
- OS version: Linux 3.2.0-72-generic
- Database driver: mysql
- Database version: 5.6.33-0ubuntu0.14.04.1
- Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

**Comment by fguillot** [comment]
The fix is available in Kanboard v1.0.44. Thanks.
