### ISSUE TITLE
Conflict with ModSecurity Module

### ISSUE THREAD

**Issue by dannycolin** [kanboard/kanboard#3263]
### Actual behaviour

When I click on the "+" the modal won't open. It open if i use to link in the menu but the "save" button in the task model doesn't work. I have the same problem when I try to delete a column.

### Expected behaviour

Task modal window should open when clicking on the "+". 

### Steps to reproduce

1.Click on the "+" OR press "n" on keyboard, fill the form and click "save"

### Configuration

    Application version: 1.0.43
    PHP version: 7.0.18
    PHP SAPI: cgi-fcgi
    OS version: Linux 2.6.32-673.26.1.lve1.4.27.el6.x86_64
    Database driver: mysql
    Database version: 10.1.21-MariaDB-cll-lve
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0

### Other informations

I found out that Kanboard works perfectly whan ModSecurity is disabled (#1936).

**Comment by fguillot** [comment]
The best way to make Kanboard compatible with `mod_security` is to contribute.

**Comment by dannycolin** [comment]
No offense but if you respond like that to everyone maybe that's why no one is contributing. Plus, have you consider that it's not everyone who have the knowledge to contribute and that you can make your project more welcomeing to newcomers.

At least, you could have provide some hint and I would have be glad to investigate a bit further even if i've never done that kind of work.

**Comment by dannycolin** [comment]
You should read that https://opensource.guide/building-community/
