### ISSUE TITLE
getAllProjects returns erroneous url.calendar

### ISSUE THREAD

**Issue by inful** [kanboard/kanboard#3266]
### Actual behaviour
When calling getAllProjects, the following url is returned for `url.calendar`

```
http://localhost/?controller=CalendarController&action=show&project_id=5
```

which, when followed, returns: `Internal Error: Controller not found`

### Expected behaviour

I would expect the url to conform to the url provided by the calendar link in the user interface:

```
http://localhost/?controller=CalendarController&action=project&project_id=5&search=status%3Aopen&plugin=Calendar#month
```

### Steps to reproduce

see above

### Configuration

- Kanboard version: master
- Database type and version: postgres
- PHP version: 7.0.9
- OS: Linux 4.4.0-72-generic
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by fguillot** [comment]
The fix is available in Kanboard v1.0.44 and Calendar plugin v1.0.1. Thanks.
