### ISSUE TITLE
Locale PT_BT - revised translation - Kanboard version: 1.0.43

### ISSUE THREAD

**Issue by gideoni** [kanboard/kanboard#3267]
Here is my contribution to the Brazilian Portuguese translation.
[translations.php.txt](https://github.com/kanboard/kanboard/files/1004344/translations.php.txt)

### Configuration
- Kanboard version: 1.0.43
- Database type and version:  mysql /  5.7.11-log
- PHP version:  5.5.38
- OS:  Windows NT 6.1
- Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by fguillot** [comment]
Someone else also updated the pt_BR translations, you could check here if everything is correct: https://github.com/kanboard/kanboard/blob/master/app/Locale/pt_BR/translations.php

**Comment by gideoni** [comment]
I did a review on the translation.
Among others, the terms below have been revised throughout the language file:

drag and drop
Plugin
swimlane
project
dashboard
board
Open board switcher

Here is my translation suggestion. 
[translations.php.txt](https://github.com/kanboard/kanboard/files/1008113/translations.php.txt)

**Comment by fguillot** [comment]
Your translations are available in Kanboard v1.0.44. Thanks!
