### ISSUE TITLE
Assigned subtasks not always shown on dashboard

### ISSUE THREAD

**Issue by cose385** [kanboard/kanboard#3268]
### Actual behaviour

When subtask is assigned to you and the task is assigned to someone else - subtask is not shown on your dashboard.

### Expected behaviour

Subtasks assigned to you should be visible on your dashboard (even if the task is assigned to someone else)

### Steps to reproduce

1. Create task and assign it to another user
2. Under that task create subtask and assign it to you
3. Open dashboard - subtask is not visible

### Configuration

Application version: 1.0.43
PHP version: 5.6.29
PHP SAPI: cgi-fcgi
OS version: Linux 3.2.61-grsec-modsign
Database driver: mysql
Database version: 5.6.34-log
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36

**Comment by Chaosmeister** [comment]
duplicates #2552

**Comment by cose385** [comment]
Not quite - #2552 is referring to filtering to your tasks in the board view and this is about seeing subtasks in the Dashboard.

**Comment by Chaosmeister** [comment]
It is mentioned in the "expected" section
> #Expected behavior
When sub tasks are created and assigned to different project members they should be able to see them in dashboard, board, calendar ...

**Comment by cose385** [comment]
True that, but later discussion was focused primarily on filtering - dashboard was not mentioned afterwards.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
