### ISSUE TITLE
Moving the Kanboard Docker image to another server and now getting "Authentication provider skipped because invalid scope"

### ISSUE THREAD

**Issue by ccasares** [kanboard/kanboard#3269]
Hi all,

We're successfully running Kanboard (1.0.36) with its Docker Container distribution.

We need to copy the container to another machine and what I did was to "commit" the docker container, save the docker image, copy it to the new machine, load it to the new docker instance and run the image again.

However, when I try to login with any of the existing users, I always get a "logon denied" and a "Authentication provider skipped because invalid scope" error in the debug log.

How can I fix this? Or, as a Plan B, how can I fully export all data (including users) from the existing kanboard container and import it in a new kanboard installation?

Thanks

**Comment by fguillot** [comment]
You are not supposed to copy a Docker container from one machine to another one. A container is not a virtual machine.

You should have all your data in a volume or/and in an external database. Copy the data to the new machine and spawn a new container.
