### ISSUE TITLE
Precise in documentation that container must be restarted to take into account new config parameters

### ISSUE THREAD

**Issue by disanvparean** [kanboard/kanboard#3270]
### Actual behaviour

Docker container must be restarted to take into account new config parameters

### Expected behaviour

It should be precised in documentation.

### Steps to reproduce

1. Create a config.php file in volume data (user nginx:nginx)
2. Fill config.php file exemple (define('ENABLE_URL_REWRITE', false);)
3. Settings are ignored.
4. Restart container
5. Settings are took into account

### Configuration
Docker image

Thank you

**Comment by fguillot** [comment]
The documentation has been updated.
