### ISSUE TITLE
CAS authentification

### ISSUE THREAD

**Issue by dbourrion** [kanboard/kanboard#3271]
Hi
Any CAS authentification plugins somewhere ?
Can find one.
Best regards.
D;

**Comment by fguillot** [comment]
As far as I know, nobody developed a CAS plugin.

**Comment by dbourrion** [comment]
Any "howto make a plugin" somewhere ? (and hello @fguillot depuis angers ;) )

**Comment by fguillot** [comment]
The documentation to create plugins is available here: https://kanboard.net/documentation/plugins

**Comment by dbourrion** [comment]
Thx
