### ISSUE TITLE
Removing a user also removes any associations to the user in comments

### ISSUE THREAD

**Issue by izno** [kanboard/kanboard#3272]
I'm not sure to call this a bug or should be an improvement...

### Actual behaviour

Removing a user causes any associations to the user being removed in the "Comments". See image (the user name before the timestamp is gone)

![image](https://cloud.githubusercontent.com/assets/968204/26175631/8adc167e-3b53-11e7-9ce0-115443ea3ac5.png)

### Expected behaviour

Any comment associated to the user should at least have a reference to the username or being assigned to the admin. (maybe as a global setting parameter) Right now it is a big "?" in the avatar.

### Steps to reproduce

Just removing a user with activity stream...

OBS! It's not reestablishing the links even if I create the user again with exact same properties.

### Configuration

Application version: master
PHP version: 7.0.10
PHP SAPI: apache2handler
OS version: Darwin 14.5.0
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by izno** [comment]
...or it should be an option when deleting an user to choose "Who to assign the users activities to?"

PS. @fguillot Thank you for this fantastic tool...

**Comment by fguillot** [comment]
Instead of removing users, you could disable this user if you want to keep a trace.
