### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by ciroiriarte** [kanboard/kanboard#3274]
I've seen a similar issues with missing mbstring module, but it's not the case. This is SLES11SP4 x86_64 with PHP 5.6

ning:~ # php -r "print_r(get_loaded_extensions());"
Array
(
    [0] => Core
    [1] => date
    [2] => ereg
    [3] => libxml
    [4] => pcre
    [5] => **hash**
    [6] => SPL
    [7] => Reflection
    [8] => **session**
    [9] => standard
    [10] => SimpleXML
    [11] => **filter**
    [12] => xml
    [13] => mysqlnd
    [14] => bcmath
    [15] => **ctype**
    [16] => curl
    [17] => dom
    [18] => **gd**
    [19] => gettext
    [20] => iconv
    [21] => intl
    [22] => **json**
    [23] => **ldap**
    [24] => **mbstring**
    [25] => mcrypt
    [26] => mysql
    [27] => mysqli
    [28] => **openssl**
    [29] => PDO
    [30] => **pdo_mysql**
    [31] => pdo_sqlite
    [32] => snmp
    [33] => sockets
    [34] => sqlite3
    [35] => tokenizer
    [36] => xmlreader
    [37] => xmlwriter
    [38] => **zip**
    [39] => zlib
    [40] => mhash
)

Version 1.0.42 (April 8, 2017)

ning:/~ # rpm -qa |grep php56
apache2-mod_php56-5.6.27-357.1
php56-intl-5.6.27-357.1
php56-zlib-5.6.27-357.1
php56-xmlwriter-5.6.27-357.1
php56-curl-5.6.27-357.1
php56-ldap-5.6.27-357.1
php56-snmp-5.6.27-357.1
php56-ctype-5.6.27-357.1
php56-gettext-5.6.27-357.1
php56-openssl-5.6.27-357.1
php56-pdo-5.6.27-357.1
php56-pear-5.6.27-357.1
php56-tokenizer-5.6.27-357.1
php56-bcmath-5.6.27-357.1
php56-gd-5.6.27-357.1
php56-json-5.6.27-357.1
php56-mcrypt-5.6.27-357.1
php56-pear-Archive_Tar-5.6.27-357.1
php56-sqlite-5.6.27-357.1
php56-zip-5.6.27-357.1
php56-dom-5.6.27-357.1
php56-mbstring-5.6.27-357.1
php56-sockets-5.6.27-357.1
php56-5.6.27-357.1
php56-iconv-5.6.27-357.1
php56-mysql-5.6.27-357.1
php56-xmlreader-5.6.27-357.1

### Actual behaviour

Loading the initial page, we're redirected to /?controller=AuthController&action=login an have a blank page.

Page source as seen from the client:

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="robots" content="noindex,nofollow">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="referrer" content="no-referrer">

        
        <style>.task-board.color-yellow, .task-summary-container.color-yellow, .color-picker-square.color-yellow {background-color: rgb(245, 247, 196);border-color: rgb(223, 227, 45)}td.color-yellow { background-color: rgb(245, 247, 196)}.table-list-row.color-yellow {border-left: 5px solid rgb(223, 227, 45)}.task-board.color-blue, .task-summary-container.color-blue, .color-picker-square.color-blue {background-color: rgb(219, 235, 255);border-color: rgb(168, 207, 255)}td.color-blue { background-color: rgb(219, 235, 255)}.table-list-row.color-blue {border-left: 5px solid rgb(168, 207, 255)}.task-board.color-green, .task-summary-container.color-green, .color-picker-square.color-green {background-color: rgb(189, 244, 203);border-color: rgb(74, 227, 113)}td.color-green { background-color: rgb(189, 244, 203)}.table-list-row.color-green {border-left: 5px solid rgb(74, 227, 113)}.task-board.color-purple, .task-summary-container.color-purple, .color-picker-square.color-purple {background-color: rgb(223, 176, 255);border-color: rgb(205, 133, 254)}td.color-purple { background-color: rgb(223, 176, 255)}.table-list-row.color-purple {border-left: 5px solid rgb(205, 133, 254)}.task-board.color-red, .task-summary-container.color-red, .color-picker-square.color-red {background-color: rgb(255, 187, 187);border-color: rgb(255, 151, 151)}td.color-red { background-color: rgb(255, 187, 187)}.table-list-row.color-red {border-left: 5px solid rgb(255, 151, 151)}.task-board.color-orange, .task-summary-container.color-orange, .color-picker-square.color-orange {background-color: rgb(255, 215, 179);border-color: rgb(255, 172, 98)}td.color-orange { background-color: rgb(255, 215, 179)}.table-list-row.color-orange {border-left: 5px solid rgb(255, 172, 98)}.task-board.color-grey, .task-summary-container.color-grey, .color-picker-square.color-grey {background-color: rgb(238, 238, 238);border-color: rgb(204, 204, 204)}td.color-grey { background-color: rgb(238, 238, 238)}.table-list-row.color-grey {border-left: 5px solid rgb(204, 204, 204)}.task-board.color-brown, .task-summary-container.color-brown, .color-picker-square.color-brown {background-color: #d7ccc8;border-color: #4e342e}td.color-brown { background-color: #d7ccc8}.table-list-row.color-brown {border-left: 5px solid #4e342e}.task-board.color-deep_orange, .task-summary-container.color-deep_orange, .color-picker-square.color-deep_orange {background-color: #ffab91;border-color: #e64a19}td.color-deep_orange { background-color: #ffab91}.table-list-row.color-deep_orange {border-left: 5px solid #e64a19}.task-board.color-dark_grey, .task-summary-container.color-dark_grey, .color-picker-square.color-dark_grey {background-color: #cfd8dc;border-color: #455a64}td.color-dark_grey { background-color: #cfd8dc}.table-list-row.color-dark_grey {border-left: 5px solid #455a64}.task-board.color-pink, .task-summary-container.color-pink, .color-picker-square.color-pink {background-color: #f48fb1;border-color: #d81b60}td.color-pink { background-color: #f48fb1}.table-list-row.color-pink {border-left: 5px solid #d81b60}.task-board.color-teal, .task-summary-container.color-teal, .color-picker-square.color-teal {background-color: #80cbc4;border-color: #00695c}td.color-teal { background-color: #80cbc4}.table-list-row.color-teal {border-left: 5px solid #00695c}.task-board.color-cyan, .task-summary-container.color-cyan, .color-picker-square.color-cyan {background-color: #b2ebf2;border-color: #00bcd4}td.color-cyan { background-color: #b2ebf2}.table-list-row.color-cyan {border-left: 5px solid #00bcd4}.task-board.color-lime, .task-summary-container.color-lime, .color-picker-square.color-lime {background-color: #e6ee9c;border-color: #afb42b}td.color-lime { background-color: #e6ee9c}.table-list-row.color-lime {border-left: 5px solid #afb42b}.task-board.color-light_green, .task-summary-container.color-light_green, .color-picker-square.color-light_green {background-color: #dcedc8;border-color: #689f38}td.color-light_green { background-color: #dcedc8}.table-list-row.color-light_green {border-left: 5px solid #689f38}.task-board.color-amber, .task-summary-container.color-amber, .color-picker-square.color-amber {background-color: #ffe082;border-color: #ffa000}td.color-amber { background-color: #ffe082}.table-list-row.color-amber {border-left: 5px solid #ffa000}</style>        <link rel="stylesheet" href="/assets/css/vendor.min.css?1491691362" media="screen">        <link rel="stylesheet" href="/assets/css/app.min.css?1491691362" media="screen">        
                    <script  type="text/javascript" src="/assets/js/vendor.min.js?1491691362"></script>            <script  type="text/javascript" src="/assets/js/app.min.js?1491691362"></script>        
                
        <link rel="icon" type="image/png" href="/assets/img/favicon.png">
        <link rel="apple-touch-icon" href="/assets/img/touch-icon-iphone.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/assets/img/touch-icon-ipad.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/assets/img/touch-icon-iphone-retina.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/assets/img/touch-icon-ipad-retina.png">

        <title>
                            Iniciar sesión (Ingresar)                    </title>

            </head>
    <body data-status-url="/?controller=UserAjaxController&amp;action=status"
          data-login-url="/?controller=AuthController&amp;action=login"
          data-keyboard-shortcut-url="/?controller=DocumentationController&amp;action=shortcuts"
          data-timezone="America/Asuncion"
          data-js-lang="es"
          data-js-date-format="dd/mm/yy"
          data-js-time-format="HH:mm"
    >

                    <div class="form-login">

    
    
    
    </div>
        </body>
</html>

### Expected behaviour

We expect to load the page and login to the system.

### Steps to reproduce

Load de initial page site.

### Configuration

```
<?php

/*******************************************************************/
/* Rename this file to config.php if you want to change the values */
/*******************************************************************/

define('DEBUG', true);

define('DEBUG_FILE', __DIR__.DIRECTORY_SEPARATOR.'data'.DIRECTORY_SEPARATOR.'debug.log');

define('PLUGINS_DIR', 'plugins');

define('FILES_DIR', 'data'.DIRECTORY_SEPARATOR.'files');

define('MAIL_FROM', 'notifications@kanboard.local');

define('MAIL_TRANSPORT', 'mail');

define('MAIL_SMTP_HOSTNAME', '');
define('MAIL_SMTP_PORT', 25);
define('MAIL_SMTP_USERNAME', '');
define('MAIL_SMTP_PASSWORD', '');

define('MAIL_SENDMAIL_COMMAND', '/usr/sbin/sendmail -bs');

define('DB_DRIVER', 'mysql');

define('DB_USERNAME', 'kanboarduser');

define('DB_PASSWORD', 'pass');

define('DB_HOSTNAME', 'localhost');

define('DB_NAME', 'kanboard');

define('DB_PORT', null);

define('LDAP_AUTH', false);

define('LDAP_SERVER', 'svr-xxxxx');

define('LDAP_PORT', 389);

define('LDAP_SSL_VERIFY', false);

define('LDAP_START_TLS', false);

define('LDAP_USERNAME_CASE_SENSITIVE', false);

define('LDAP_BIND_TYPE', 'anonymous');

define('LDAP_USERNAME', null);

define('LDAP_PASSWORD', null);

define('LDAP_USER_BASE_DN', 'DC=xxxxx,DC=net,DC=py');

define('LDAP_USER_FILTER', '(&(objectClass=user)(sAMAccountName=%s))');

define('LDAP_USER_ATTRIBUTE_USERNAME', 'uid');

define('LDAP_USER_ATTRIBUTE_FULLNAME', 'cn');

define('LDAP_USER_ATTRIBUTE_EMAIL', 'mail');

define('LDAP_USER_ATTRIBUTE_GROUPS', 'memberof');

define('LDAP_USER_CREATION', true);

define('LDAP_GROUP_ADMIN_DN', '');

define('LDAP_GROUP_MANAGER_DN', '');

define('LDAP_GROUP_PROVIDER', false);

define('LDAP_GROUP_BASE_DN', '');

define('LDAP_GROUP_FILTER', '');

define('LDAP_GROUP_ATTRIBUTE_NAME', 'cn');

define('GOOGLE_AUTH', false);

define('GOOGLE_CLIENT_ID', '');

define('GOOGLE_CLIENT_SECRET', '');

define('GITHUB_AUTH', false);

define('GITHUB_CLIENT_ID', '');

define('GITHUB_CLIENT_SECRET', '');




define('GITLAB_AUTH', false);

define('GITLAB_CLIENT_ID', '');

define('GITLAB_CLIENT_SECRET', '');




define('REVERSE_PROXY_AUTH', true);

define('REVERSE_PROXY_USER_HEADER', 'REMOTE_USER');

define('REVERSE_PROXY_DEFAULT_ADMIN', '');

define('REVERSE_PROXY_DEFAULT_DOMAIN', '');

define('REMEMBER_ME_AUTH', true);

define('ENABLE_HSTS', true);

define('ENABLE_XFRAME', true);

define('ENABLE_SYSLOG', true);

define('MARKDOWN_ESCAPE_HTML', true);

define('API_AUTHENTICATION_HEADER', '');

define('ENABLE_URL_REWRITE', false);

define('HIDE_LOGIN_FORM', true);

define('BRUTEFORCE_CAPTCHA', 3);

define('BRUTEFORCE_LOCKDOWN', 6);

define('BRUTEFORCE_LOCKDOWN_DURATION', 15);

define('SESSION_DURATION', 0);

define('HTTP_PROXY_HOSTNAME', '');
define('HTTP_PROXY_PORT', '3128');
define('HTTP_PROXY_USERNAME', '');
define('HTTP_PROXY_PASSWORD', '');

```

**Comment by ciroiriarte** [comment]
vhost config:

  <Directory "/srv/www/vhosts/kanban.host.lan/">
    AllowOverride All
    Options FollowSymLinks MultiViews Includes
    Require all granted
  </Directory>

Default .htaccess:

<IfModule mod_rewrite.c>
    Options -MultiViews

    SetEnv HTTP_MOD_REWRITE On

    # Uncomment this line depending of your Apache configuration
    # RewriteBase /

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [QSA,L]

    ############################
    ## Uncomment the two lines below to enable force HTTPS capabilities
    ############################

    # RewriteCond %{HTTPS} !=on
    # RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
</IfModule>

<IfModule pagespeed_module>
    ModPagespeed Off
</IfModule>

**Comment by fguillot** [comment]
Before to install Kanboard, you should make sure that PHP is working correctly. The procedure on Centos is described here: https://kanboard.net/documentation/centos-installation and https://kanboard.net/documentation/installation

**Comment by ciroiriarte** [comment]
Thanks a lot for the suggestion. We have other PHP applications running on the same host. The only difference is that this application uses kerberos authentication (from apache), and the other one has native LDAP autentication.

**Comment by Snajper88** [comment]
@ciroiriarte: We also had issues to bring Kanboard to live.
Editing the .htaccess file in the kanboard folder helped us:
We had to comment this line out to make it work:
Options -MultiViews -> #Options -MultiViews

**Comment by fguillot** [comment]
If you check your Apache logs you will find the exact source of the problem.
