### ISSUE TITLE
Overdue task notification

### ISSUE THREAD

**Issue by mpolak83** [kanboard/kanboard#3277]
Hello,

How to disable overdue tasks notifications? I have added scheduled task to windows server to run every night and it's sending emails to everyone. How do I disable it?

Thank you
M

**Comment by fguillot** [comment]
Instead of using `./cli cronjob`, execute only the jobs that you would like, for example: `./cli projects:daily-stats` and `./cli trigger:tasks`.

More details here: https://github.com/kanboard/kanboard/blob/master/app/Console/CronjobCommand.php#L12-L16
