### ISSUE TITLE
New automatic action

### ISSUE THREAD

**Issue by mpolak83** [kanboard/kanboard#3278]
Hello,
Is it possible to add new automatic action that will assign the task to the creator when moved to specific column?

Thank you
M

**Comment by Chaosmeister** [comment]
This is already implemented:

![image](https://cloud.githubusercontent.com/assets/13346344/26549044/5c5777bc-4477-11e7-8c48-994a894d7c78.png)

**Comment by fguillot** [comment]
This is now implemented into the development branch.
