### ISSUE TITLE
reset the task id with a new project?

### ISSUE THREAD

**Issue by flpker64** [kanboard/kanboard#3279]
**Please, do not create duplicate issues**

### Actual behaviour
When we create a new task in a new project the id number of the task interact with the first project.

### Expected behaviour

Is there a way to reset this number? It will be easier to follow the number of task in a new project

Thank you for your great work!

**Comment by fguillot** [comment]
The task id is the auto-increment field of the tasks table which is common to all projects.

**Comment by Chaosmeister** [comment]
Use the list view for the numbers of tasks:

![image](https://cloud.githubusercontent.com/assets/13346344/26548938/c05936de-4476-11e7-9fef-f67a7c97ee5c.png)

The number of **all** tasks is displayed if the filter is cleared.
For the number of open tasks, set the filter to "status:open".

**Comment by gene-pavlovsky** [comment]
Personally I'd like to have a project-specific task IDs as well. Auto-increment `task_id` may stay as it is, how about adding another field, something like "display task id"? When creating a project, it's own display task id would start from 1, and be auto-incremented as well. Also I would add an option to specify a task ID prefix for a project. For example if I have WebApp and BackEnd projects, I'd like them to have task IDs WA-123 and BE-123. If no prefix is specified for a project, it's tasks ids would be just numbers, but independent of other projects.

**Comment by gdinit** [comment]
Hi Fred, amazing job with kanboard - thanks!

From a simple user perspective, I agree with the previous post - it would be great to see the first task added to a project with task ID 1 (rather than 548 or similar). I hope a workaround can be arranged to provide this visual illusion -even if it stays as 548 or similar in the db-.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
