### ISSUE TITLE
Local PC RAM Accumulation

### ISSUE THREAD

**Issue by KBDev07** [kanboard/kanboard#3281]
Hi 

I set up a kanboard, separating its DB from Web Application, however when I tried to move cards simultaneously and with multiple users the I experienced unacceptable lags and website freeze. The changes shows after reloads and are reflecting to the DB.

I checked the DB and Web Servers' utilization and the results were normal. What I observed weird is that every time there are movements on the board, it is eating up my local computer's RAM. PC specs are set enough to handle extensive and difficult websites. Have tested this to multiple PC's and results were the same.

Kindly assist on this one. Thank you in advanced.

**Comment by rautamiekka** [comment]
Just to be sure: the db ain't something like SQLite, but a dedicated system like MySQL ?

Fill the template, as well, your post doesn't tell much like this.

**Comment by KBDev07** [comment]
Hi rautamiekka,

No, it isn't, I am improving an existing kanboard, and replaced SQLite with MySQL. Please see below:

### Actual behaviour

I set up a kanboard, separating its DB from Web Application, however when I tried to move cards simultaneously and with multiple users the I experienced unacceptable lags and website freeze. The changes shows after reloads and are reflecting to the DB.

I checked the DB and Web Servers' utilization and the results were normal. What I observed weird is that every time there are movements on the board, it is eating up my local computer's RAM. PC specs are set enough to handle extensive and difficult websites. Have tested this to multiple PC's and results were the same.

### Expected behaviour

Movements should reflect to the board real time without extreme slowness and website's unresponsiveness.

### Steps to reproduce

Please create a project and at least a hundred cards in the board before proceeding with the execution of replication:

1. Log in to the application as any types of user (preferably multiple users in one shot )
2. Go to the created project board
3. Along with the other users logged in, try to move cards simultaneously all at once
4. Notice the extreme slowness and worse unresponsiveness of the application
5. While the other users are in the process of moving cards, Open the DB and Web Application servers see utilization, you'll notice that all are normal
6. Open task manager to users' local machines or computers notice that the web browser's .exe process is accumulating huge amounts of RAM

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.43
- Database type and version: MySQL || 5.6.35
- PHP version: 5.4.16
- OS: Linux 3.10.0-123.e67.x86_64
- Browser: Mozilla 5.0; AppleWebKit; Chroe/58.0.3029; Safari/537.36

Thank you

**Comment by rautamiekka** [comment]
> PHP version: 5.4.16

Try an up-to-date PHP for starters.

**Comment by KBDev07** [comment]
PHP Version: Updated to 7.1.5

Still receiving the same issues of slowness and unresponsiveness.

**Comment by fguillot** [comment]
Did you take a look to this page? https://kanboard.net/documentation/performances
