### ISSUE TITLE
Tracking 0 time from subtask in timesheet

### ISSUE THREAD

**Issue by izno** [kanboard/kanboard#3285]
### Actual behaviour

If I by misstake start a subtask and stop it, then it will make 0 record.

![image](https://cloud.githubusercontent.com/assets/968204/26378342/6b9fde6a-4014-11e7-9e77-f09070650005.png)

This action creates lots of unnecessary records in the timesheet.

### Expected behaviour

1. Would it be possible to manually delete 0 records in a timesheet?
2. What if 0 record not being tracked – if the start time and end time is the same?

This is also making mess in the budget plugin...

### Steps to reproduce

Create a subtask and start time tracking and stop it immediately.

### Configuration

Application version: 1.0.43
PHP version: 7.0.19
PHP SAPI: litespeed
OS version: Linux 2.6.32-673.26.1.lve1.4.27.el6.x86_64
Database driver: sqlite
Database version: 3.14.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
