### ISSUE TITLE
Estimated time in task being overwriten

### ISSUE THREAD

**Issue by izno** [kanboard/kanboard#3286]
### Actual behaviour

I'm not sure if this is a bug or feature request?

If I make a task and give it an estimated time of 4... then creating a subtask and estimate that to 2. This overwrites the original estimated time in the task.

### Expected behaviour

The task estimated time should have the overall priority over sub tasks and subtasks should complement the main task. Not to overwrite them.

### Steps to reproduce

- Create a task and estimate a time for it
- Create a subtask and estimate a time for it

The task estimated time is overwritten by the subtask estimation.

### Configuration

Application version: 1.0.43
PHP version: 7.0.19
PHP SAPI: litespeed
OS version: Linux 2.6.32-673.26.1.lve1.4.27.el6.x86_64
Database driver: sqlite
Database version: 3.14.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by fguillot** [comment]
This is the expected behavior. The estimated time in the task is the sum of all estimated time in subtasks if one the subtasks have a value defined.
