### ISSUE TITLE
Manually added time spent in subtask not showing up in the timesheet

### ISSUE THREAD

**Issue by izno** [kanboard/kanboard#3287]
### Actual behaviour

Manually adding time spent in a subtask is not registered any place... or do I miss some thing here?

This is also making it hard to use the budget plugin as the manually added time spent is not being registered any place and therefor not being included in any budget calculation.

### Expected behaviour

Manually added or adjusted time in a subtask should be registered. It should actually be placed as a separate line in the timesheet with a manually added flag. 

### Steps to reproduce

Create a subtask and start the timer... after you have tracked some time, stop it. Then edit the subtask and change the time spent and add 1h to it and save it. ex. It could be a case that you have ot been able to start the time tracker but you have to register some extra tracked time.

- In the time sheet overview it only states the original automated tracked time, and not the manually updated spent time.
- Also using the budget plugin, this extra time is not tracked and not registered.

**Comment by fguillot** [comment]
Manually added time doesn't appears on the timesheet. Only, the subtask timer write to this table.

**Comment by izno** [comment]
@fguillot Thanks for the info.

I can see the logic in it, that only time-tracker register the sub-task time – but then it's kind of misleading/confusing to have the opportunity to edit the sub-task time

![image](https://cloud.githubusercontent.com/assets/968204/26760731/23d77042-4920-11e7-8c1e-72853f980d93.png)

My question is though, if it could be possible to manually adjust or add to sub-task time and have it registered? ...and add a metadata of manually added.

- ex. could be that instead of "Time spent" input field, we can have "Manually add to time spent". Then we can register that in the time sheet what is tracked and manually added...

<hr>

Here it could be an example on real case scenario:


I have 0.15h spent time tracked from a sub-task and 2h original estimated time:

![image](https://cloud.githubusercontent.com/assets/968204/26760720/f8579c12-491f-11e7-8713-f4315c312a75.png)

Then I can adjust the time spent in the sub-task manually to 1.15... it's registered as total time spent in the overview:

![image](https://cloud.githubusercontent.com/assets/968204/26760738/7fe188aa-4920-11e7-8a57-e04750b3fda0.png)

But this adjustment is not registered under Timetracking? Which can be kind of confusing...

![image](https://cloud.githubusercontent.com/assets/968204/26760742/b0986040-4920-11e7-9c70-b812c9e3d90a.png)

In the yellow field overview it is 1.5h time spent – but then only 0.15h Timespent...
- It should have been 0.15 tracked & 1h manually added

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
