### ISSUE TITLE
Allow administrators to modify the login of users

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#3290]
I just enabled login with LDAP and wanted to merge/migrate the users already created in the database to the ldap logins.

Changing the account type to "remote" was simple.
However some accounts needed to have their login changed to their respective LDAP logins.

### Actual behaviour

This is not possible through the UserInterface. Neither for administrators, nor for my own account.
I had to change the logins in the database. However, this seems to work without a problem.

### Expected behaviour

The login might become subject to change in some situations,

### Configuration

Application version: 1.0.44
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by fguillot** [comment]
It should happen very rarely. In your case in was after a migration from local accounts to ldap. You could uncheck temporarily the checkbox "Remote User" to update the username.

**Comment by Chaosmeister** [comment]
> You could uncheck temporarily the checkbox "Remote User" to update the username.

How?  
I agree that the situations are rare but they do occur.  I did not see any drawbacks/sideeffects

**Comment by fguillot** [comment]
With the current development branch, you can now update the username of remote users if you are administrator.
