### ISSUE TITLE
External ressources [Feature Request]

### ISSUE THREAD

**Issue by globule** [kanboard/kanboard#3291]
A project is often linked to external ressources as support/accountable
That's why it could be usefull each user (responsible) can manage a contact list to assign tasks to his contacts.
Contact can be private or shared.
In addition, a mail could optionnaly be sent to a contact when assigng a task.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
