### ISSUE TITLE
Task comments "class" was renamed and now broken

### ISSUE THREAD

**Issue by jsteel44** [kanboard/kanboard#3292]
### Actual behaviour

It seems some versions ago the class name changed for the task comments from "accordion-content" to "accordion-content comments". There is no "accordion-content comments" class in the css file. This makes the comments box very small in the task view. Reverting this change with the following patch fixes the issue.

```
--- a/app/Template/task_comments/show.php
+++ b/app/Template/task_comments/show.php
@@ -2,7 +2,7 @@
     <div class="accordion-title">
         <h3><a href="#" class="fa accordion-toggle"></a> <?= t('Comments') ?></h3>
     </div>
-    <div class="accordion-content comments" id="comments">
+    <div class="accordion-content" id="comments">
         <?php if (!isset($is_public) || !$is_public): ?>
             <div class="comment-sorting">
                 <small>
```

Please review why the change was made and either provide an "accordion-content comments" class in the css file or revert this so the comments box is formatted correctly (as it was).

### Expected behaviour

Class name should match something in the CSS file.

### Steps to reproduce

Use latest version. Open a task and see the comments box is smaller than it was some versions ago. Apply patch above and see that it returns to the normal size.

### Configuration

- Kanboard version: 1.0.44
- Database type and version: 5.5.52-MariaDB
- PHP version:  5.4.16
- OS: Any
- Browser: Any

**Comment by fguillot** [comment]
Please, make a proper bug report by using the provided template.

**Comment by jsteel44** [comment]
I thought I explained the issue well and even included a fix. But as requested, I've updated my original post to be in template form.

**Comment by jsteel44** [comment]
I set this up on a new server and don't have this issue, so happy to close this.
