### ISSUE TITLE
"New Activity" counter in Board view

### ISSUE THREAD

**Issue by mrkafk** [kanboard/kanboard#3293]
Hello,

Feature Request:

The Overview provides activity log on the board. However, you have to switch back and forth between Overview and Board to see if something new and potentially relevant popped up. It would be nice to have a personal counter of activities that happened since last opening of Overview in the Board view, preferably colored. After visit to Overview the counter would obviously be reset to zero.

**Comment by fguillot** [comment]
Is it really important? Having too many features increase the complexity of the software.

**Comment by froschdesign** [comment]
@fguillot 
> Is it really important? Having too many features increase the complexity of the software.

If this question arises, then the answer is simple: Plugin! 😉 

(Suggestion: Change the label "feature request" with "plugin" and add a label "help wanted".)

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
