### ISSUE TITLE
Collapsed Swimlanes flashing as uncollapsed on page load

### ISSUE THREAD

**Issue by ghost** [kanboard/kanboard#3294]
Collapsed swimlanes appear in uncollapsed state on page load and are collapsed when the page has finished loading. This flashing and jumping is a little bit annoying.

Is it possible to send collapsed swimlanes in already collapsed state on page load?

Thanks

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
