### ISSUE TITLE
Custom role overwriting group rights.

### ISSUE THREAD

**Issue by Rocreex** [kanboard/kanboard#3295]
Assume we define a custom role with several restrictions and we have two groups of people. One being a subset of the other, e.g. members and officers (officers are also members).
Assume we want to grant Project Manager rights to the officers and the custom role to the members. It seems like the custom role is overwriting the Manager rights for the officers. Is this behaviour deliberate?
User rights, on the other hand, seem to overwrite group rights.

This is on Kanboard 1.0.44 but has probably always been.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
