### ISSUE TITLE
Problem to use API in kanboard, CURL error reponse, help me please

### ISSUE THREAD

**Issue by mewolfx23** [kanboard/kanboard#3296]
Hello, I have started to use kanboard and I think it is an excellent product, it has been very useful to me, but I have the following problem, you could help me please; I'm trying to use the kanboard curl but when using the documentation methods for example 'getAllprojects' I get no response. I would like to know what the correct syntax is for running the curl with the curl.php library or some example of how to implement it. Also, try to use the php client, but it gives me an error, the error is that it does not find the client class.

**Comment by rautamiekka** [comment]
I'm sure cURL has verbosity flags, even better if debugging flags, try putting those to highest (usually done by repeating the flag but it can differ; I don't use cURL). Since you mentioned cURL, it's quite safe to say you're on a Linux or another NIX system, so check `man curl` thoroughly.

Otherwise `curl --help` or `curl -h` or `curl -help`.

**Comment by mewolfx23** [comment]
Hello @raul, thank you very much for your answer, I am trying to call the api via curl from a php file using the curl.php library and it is there where I have the error the method I use is getAllprojects and I get the following answer:
"http://my_domain/kanboard/jsonrpc.php/webservice/rest/server.php?wstoken="X-API-Auth: anNvbnJwYzpjZWI0OWY3ZDQ4MGJjNjBlMzg2OTc1ZTNiMDVhM2JjYmU3ZGM5YjQzZTliNGJjMDY2Y2ZmODllYTRjZTI="&wsfunction=getAllProjects

{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}"

**Comment by rautamiekka** [comment]
^ You mentioned someone else than me.

**Comment by mewolfx23** [comment]
Oh, sorry @rautamiekka

**Comment by mewolfx23** [comment]
@rautamiekka  I've also tried a different approach, I'm using the library provided by @fguillot  called "Json-RPC PHP client/server" but the constructor crashes since php can't find the class "HttpClient", has anyone implemented this method?

**Comment by rautamiekka** [comment]
What versions are you on for the computer you use yourself and the Kanboard host ? OS, PHP, Web Server.

**Comment by mewolfx23** [comment]
@rautamiekka  I'm programming in windows 10 and The information do you ask me is the next:
kanboard  1.0.44
PHP in server 5.6.24
CentOS release 6.8

**Comment by fguillot** [comment]
You have an example with curl in the official documentation: https://kanboard.net/documentation/api-examples

Replace the token by the one of your Kanboard instance.
