### ISSUE TITLE
Sortable improvements?

### ISSUE THREAD

**Issue by Sengorius** [kanboard/kanboard#3297]
In a special project we try to fetch ressource management of our company into one project, which results into huge amount of tasks onto that board. The KanBoard has a lot of tools to support this and it is good to use.

### Actual behaviour

Despite of inactivating unused swimlanes, one drag&drop of a task takes at least 20 seconds. It seems to rely on the huge amount of tasks and swimlanes. We do not have to wait for an update to finish and can move multiple tasks instead, but sometimes the project view changed while dragging or did not result as expected.

### Expected behaviour

I took a look into the KanBoard core and found the `render` function inside the `BoardAjaxController`. If I get it right, this one constructs the whole table and sends it back as the response?

In my opinion, dropping a task in a project should send an ajax request to the server, write info into the database and only return with a success flag. JQuery already handled the movement and the board is up to date.

Is it possible to change the ajax calls that way? Or is this implementation needed for a function, I did not notice?

**Comment by fguillot** [comment]
This ajax call render the whole board because you still need to update column headers (number of tasks within the column, sum of complexity, turn the color to red, etc...). There are also some automatic actions that could change some properties of the task moved (color, assignee, etc).

A better way is probably to render the board client side in Javascript instead of server side in PHP. This could be done by using VueJS or ReactJS. But it's a huge change (don't forget that the software in multi-languages and plugins could alter templates).

**Comment by k9t9** [comment]
I agree that the ajax calls are not optimised. I also agree that implementing a full blown js framework is a major overhaull.. But there is a middle way of using jquery for example . there is no point in using ajax if the page reloads anyhow. IMHO it defeats the whole point of ajax...

**Comment by Sengorius** [comment]
Okay, passing only the success flag will be to few, to actually get all the things done. But what if you give the task itself back in the subrequest?

Automatic actions are only applied to the moved task itself, so can be updated in the subrequest? When the subrequest returned, just replace the old with the new task. Updating the number of tasks in the header can also be done with JavaScript.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
