### ISSUE TITLE
Notification box overlaps bottom navigation in user management

### ISSUE THREAD

**Issue by Rocreex** [kanboard/kanboard#3299]
When deleting a user in the user management interface, a popup appears at the bottom of the page overlapping the page navigation. Even though the popup disappears, it seems like the box stays in place as the navigation cannot be used anymore until you reload the page.

**Comment by rautamiekka** [comment]
First up:
- Your web browser version ?
- Your Kanboard version ?

**Comment by Rocreex** [comment]
I am using the latest Chrome version and the latest Kanboard version.

**Comment by rautamiekka** [comment]
^ 'Latest' ain't a valid version number/string.

**Comment by Rocreex** [comment]
Chrome: Version 58.0.3029.110 (64-bit)
Kanboard: 1.0.44

**Comment by Rocreex** [comment]
How is this labeled as "improvement". This is clearly a bug and still present in the latest version.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
