### ISSUE TITLE
task list not refreshed after cancelling adding sub-task

### ISSUE THREAD

**Issue by TriYop** [kanboard/kanboard#3300]
### Actual behaviour

When adding subtasks to an existing task, If I press the cancel button after adding a few subtasks (with "add another subtask" checked), the task page is not refreshed and the subtasks I created  are not displayed.

### Expected behaviour

I'm expecting the task page to be refreshed as far as at least one subtask is created, whatever button I actually click. 

### Steps to reproduce

1. Create a task
2. on the task details page click on add subtask menu
3. in the modal form, enter the subtask details, then check the box "add another subtask" and click on the validation button.
4. in the new modal form, click on the cancel button
5. modal is closed and task details page is not being refreshed.

### Configuration

- Kanboard version: 1.0.44
- Database type and version: embedded sqlite
- PHP version: 5.6 (xampp)
- OS: Windows 10
- Browser: Chrome, Edge, Firefox

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.3/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
