### ISSUE TITLE
Run several instances of (not dockerized) kanboard with simple nginx

### ISSUE THREAD

**Issue by rariteta** [kanboard/kanboard#3301]
As far as i can see, there is an option to run dockerized kanboard instances and reverse-proxy into them via either https://github.com/fguillot/proxy-hooker or https://github.com/jwilder/nginx-proxy. But i wonder if there could be an option to use not dockerized kanboard with simple nginx as a web-server servicing kanboard subdomains? This case, how shoud cron-jobs and queue workers run?

**Comment by fguillot** [comment]
You don't need to use Docker, you could create a virtual host for each Kanboard instance.
