### ISSUE TITLE
feature request : in board view individual items scale to estimated times

### ISSUE THREAD

**Issue by sstecker** [kanboard/kanboard#3303]
Hi 

great product! 

we have implemented kanboard across our organization (manufacturing company).  we use the board view.  new jobs are scripted to insert from our erp system. each job we are running has its estimated time inserted.  we have 300-400 tasks going that represents the next 6 weeks deliveries.   each job varies in estimated time from 1h to 40+ hours.  i have contemplated color change to show estimated time (0-4 hours green, 4-8 blue, etc)

FEATURE REQUEST: if the tasks height scaled vertically in board view to represent estimated time would make it very easy to schedule.  i do not see any other kanban system representing estimated times in a visual sense outside of gantt.  scaled display as an option on board view (regular view, collapsed view, scaled view).  like the collapsed view with scaling and horizontal lines signifying 40 hour marks from current viewing time.

thank you!

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
