### ISSUE TITLE
Project viewer can convert any subtask into a new task

### ISSUE THREAD

**Issue by fallcom** [kanboard/kanboard#3304]
### Actual behaviour

Project viewer can convert any subtask into a new task.

### Expected behaviour

Project viewer shouldn't can change the existing tasks.

### Steps to reproduce

The user with a project viewer role enters any card having subtasks, presses for any of them "Convert to task", and after confirmation his action is satisfied.

### Configuration

Application version: 1.0.44
PHP version: 5.4.3
PHP SAPI: apache2handler
OS version: Linux 4.8.17-tinycore
Database driver: mysql
Database version: 10.0.17-MariaDB
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.90 Safari/537.36 Vivaldi/1.91.867.38

**Comment by rautamiekka** [comment]
I'd update PHP to at least 5.6 to avoid and rule out problems.

**Comment by fallcom** [comment]
I tried versions of PHP 5.6.21 and 7.0.6 and it hasn't helped.

**Comment by fguillot** [comment]
This issue is now fixed in the development version of Kanboard. The PHP version has nothing to do with this problem.

**Comment by fguillot** [comment]
This issue should be fixed in version 1.0.45.
