### ISSUE TITLE
Create Task error 403

### ISSUE THREAD

**Issue by diego-betto** [kanboard/kanboard#3308]
### Actual behaviour

Cannot create new tasks, error 403 in console

` /?controller=TaskBulkController&action=show&project_id=1&column_id=2&swimlane_id=1 403 (Forbidden)`

Seems related to mod_security 

`ModSecurity: Access denied with code 403 (phase 2). Pattern match "(?i:\\\\b(?:t(?:able_name\\\\b|extpos[^a-zA-Z0-9_]{1,}\\\\()|(?:a(?:ll_objects|tt(?:rel|typ)id)|column_(?:id|name)|mb_users|object_(?:id|(?:nam|typ)e)|pg_(?:attribute|class)|rownum|s(?:ubstr(?:ing){0,1}|ys(?:c(?:at|o(?:lumn|nstraint)s)|dba|ibm|(?:filegroup|o ..." at ARGS_NAMES:column_id. [file "/etc/apache2/conf.d/modsec_vendor_configs/comodo_apache/24_SQL_SQLi.conf"] [line "18"] [id "211540"] [rev "11"] [msg "COMODO WAF: Blind SQL Injection Attack||sitedev.it|F|2"] [data "Matched Data: column_id found within ARGS_NAMES:column_id: column_id"] [severity "CRITICAL"] [tag "CWAF"] [tag "SQLi"] [hostname "******"] [uri "******"] `

It's related to url attribute "column_id" in 
https://github.com/kanboard/kanboard/blob/master/app/Template/board/table_column.php#L20
### Expected behaviour

Create task

### Steps to reproduce

Error is fired when I try to create a new task using '+' button.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

Versione dell'applicazione: 1.0.44
Versione PHP: 7.0.20
PHP SAPI: cgi-fcgi
Versione OS: Linux 3.10.0-514.21.1.el7.x86_64
Driver per Database sqlite
Versione database: 3.7.17
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36

**Comment by fguillot** [comment]
Unfortunately, Kanboard is not compatible with mod_security.
