### ISSUE TITLE
Calendar locale showing chinese instead of configured language

### ISSUE THREAD

**Issue by marcosaccioly** [kanboard/kanboard#3310]
This is somewhat a duplicate of two-year old closed issue #1458

### Actual behaviour

Application is configured to use pt_BR, but calendar shows chinese characters. 

### Expected behaviour

Calendar should display pt_BR characters or default to english.

### Steps to reproduce

1. Click on the Create Task 'plus' sign
2. Click in any date field

### Configuration

- Versão da aplicação: 1.0.44
- Versão do PHP: 5.6.30
- PHP SAPI: cgi-fcgi
- Versão do sistema operacional: Linux 3.12.72-202.ELK6.x86_64
- Driver do banco de dados: mysql
- Versão do banco de dados: 5.5.51-38.2
- Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36

![erro_kan_chinese](https://user-images.githubusercontent.com/1198117/27437128-acb5edba-5737-11e7-83c2-80615f914bca.jpg)

**Comment by fguillot** [comment]
It should be fixed in version 1.0.45. Thanks
