### ISSUE TITLE
Chat plugin does not work or show in installed plugins page

### ISSUE THREAD

**Issue by marcosaccioly** [kanboard/kanboard#3311]
### Actual behaviour

Chat plugin installation does not work and plugin does not show in installed plugins page, though folder is present in FTP. 

### Expected behaviour

Chat plugin should show under /?controller=PluginController&action=show and chat should work. The message is green after clicking "install" and we are redirected to "installed plugins" page, but chat is not there. Google authentication and Gantt chart plugins were correctly installed using the same procedure.

### Steps to reproduce

1. Access the plugin installation page 
2. Try to install chat plugin

### Configuration

Versão da aplicação: 1.0.45
Versão do PHP: 5.6.18
PHP SAPI: fpm-fcgi
Versão do sistema operacional: Linux 3.10.104-1.el6.elrepo.x86_64
Driver do banco de dados: mysql
Versão do banco de dados: 5.6.35-log
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

### Notes

I believe this is due to a database migration problem. I had trouble installing kanboard and had to manually run the sql for the database install (probably because of the host as I have used kanboard on other providers without any problem). Nonetheless, Kanboard cannot fool the user by saying the plugin was sucessfully installed if it wasn't able to generate tables and connect things. :)

**Comment by fguillot** [comment]
I have never been able to reproduce this issue after all this time. You seems to be the only one to have this problem. Make sure everything is installed correctly, the database schema must be consistent. Unfortunately, you will have to investigate by yourself and potentially submit a patch.
