### ISSUE TITLE
Feature Request - Enter task after creation

### ISSUE THREAD

**Issue by jansch2015** [kanboard/kanboard#3313]
I have a really useful feature request that would make it (at least for me) much easier and quicker:

Could you add a checkbox on the task creation form to enter the task after creation?

Alternative: Add a button "Save & Enter"

I often have to upload documents, which is only possible when I'm in the task.

What do you think?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
