### ISSUE TITLE
Feature Request : Add table prefix on mysql/postgres database schema objects

### ISSUE THREAD

**Issue by jerome42** [kanboard/kanboard#3316]
Hi,

If i choose a mysql/postgres database type at the kanboard install (in the config.php), i can't prefix the created objects 

It would be nice to have a new parameter like 

```
// Mysql/Postgres database objects prefix
define('DB_OBJECT_PREFIX', '');
```

PS : If you install the database schema of KanBoard in an existing database (for many reasons), it helps to separate from other projects

Thanks in advance to examine this request

**Comment by fguillot** [comment]
See https://github.com/kanboard/kanboard/issues/712
