### ISSUE TITLE
 Feature Request: Add a "Contacts" tab / option

### ISSUE THREAD

**Issue by sulian** [kanboard/kanboard#3317]
Hello

I usually use GLPI for project management but after testing Kanboard, I find it more interesting and pratical (the good point).

The bad point is that there is nothing to handle an external contact or a provider.

Can you add a new tab for contacts management ? 

Informations :

- Name / lastname,
- Kind of contact (provider, ...) <= list or free input ?
- Phone number,
- Fax (does anyone still use today ??),
- Email
- Comment

Perhaps create a new plugin like kanboard-contacts ?

Best regards

Sulian

**Comment by rautamiekka** [comment]
The precise implementation could be LDAP, MySQL/etc. ...

**Comment by sulian** [comment]
It must work with a database, all contacts are not in the company LDAP.

Suppose project is to add a ERP, GED or BPM software, you probably want the contact name of the company providing the service directly in the project not.

**Comment by Busfreak** [comment]
Very simple contacts plugin, beta stage:
https://github.com/Busfreak/plugin-contacts

It's for my private use, so no documentation etc. available.

- Individual list of items in system configuration
- List of Contacts in board configuration (but system wide available)
- Selection of contacts in task edit
- Symbol in task footer, if contact selected, with details in popover

**Comment by sulian** [comment]
Very interesting, I'll try to get some time in order to test it.

**Comment by ltajariolli** [comment]
Hi!
@sulian   do you tried  install the plugin?

I copied the files at /pluggin but don't work

Thank you very much!

**Comment by fguillot** [comment]
I'm closing this ticket because I don't plan to create a contacts plugin for now. I let people from the community to create such plugin.
