### ISSUE TITLE
Hidden columns always displayed

### ISSUE THREAD

**Issue by ErZ101** [kanboard/kanboard#3319]
### Actual behaviour
Putting a check mark in "Hide tasks in this column in the dashboard" has no effect.
Tasks and Column are still displayed for all users, no matter the Users Security Role or Project Permissions Role that is selected. 
Also when using Public Access Link, columns that are set to "Visible on dashboard" = No are also always displayed.

### Expected behaviour
"Hide tasks in this column in dashboard" should hide tasks and column on dashboard, especially for public access links.

### Steps to reproduce
1. Put check mark on "Hide tasks in this column in dashboard"
2. Login as different users
3. View projects dashboard.
4. Column is still visible.
5. Click Public Link.
6. Column is still visible.

### Configuration
- Kanboard version: 1.0.44
- Database type and version: sqlite 3.7.17
- PHP version: 5.4.16
- OS: Linux 3.10.0-327.3.1.el7.x86_64
- Browser: Chrome/51.0.2704

**Comment by Busfreak** [comment]
This feature works as it should do.
It means hiding tasks in the user dashboard, first page after log in (controller=DashboardController&action=show) not in the projects dashboard.

**Comment by ErZ101** [comment]
By "User Dashboard", you mean "My Tasks"? If the above isn't a bug and is as intended, it would make more sense to have that type of setting under Permissions. That way you could set individual Users or Groups to not see "THEIR" tasks in a certain column under "My Tasks".

If you want to hide a whole column from the Project Dashboard, that option would be under Project Settings, Columns.

**Comment by fguillot** [comment]
This is working as expected for me.

This feature doesn't hide the column on the board. This feature hide the tasks inside this column on the dashboard page.
