### ISSUE TITLE
Confirmation message hides link to next page in project overview

### ISSUE THREAD

**Issue by Busfreak** [kanboard/kanboard#3320]
### Actual behaviour

After deleting a project (controller=ProjectStatusController&action=confirmRemove&project_id=16) the user is redirected to the project overview (controller=ProjectListController&action=show).
The confirmation message at the bottom of the screen ("Project removed successfully.") covers the link to the next page (if there are more than 20 projects in the list), so the link isn't available.

### Expected behaviour

Link should be available.

### Steps to reproduce

1. be sure to have more than 20 projects
2. delete a project
3. try to click on "next"

### Configuration

    Version: 1.0.45
    PHP Version: 5.3.10-1ubuntu3.25
    PHP SAPI: apache2handler
    OS Version: Linux 3.2.0-113-generic-pae
    Datenbanktreiber: mysql
    Datenbank Version: 5.5.53-0ubuntu0.12.04.1
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by fguillot** [comment]
Seems to be the same as #3299
