### ISSUE TITLE
Feature Request: Allow swimlanes to be associated with user Groups

### ISSUE THREAD

**Issue by ErZ101** [kanboard/kanboard#3321]
**Feature request:**
Add the option to associate a projects swimlanes to user groups. When you assign a task to a user, it populates it in the proper swimlane on the Project Dashboard for that users group (department).

If this is also supported for Sub-Tasks, kanboard would need to support splitting the main task and sub-tasks. This would allow them to be displayed as their own item on the Project Dashboard if the main task is assigned to one group (swimlane) and a sub-task is assigned to a different group (swimlane).

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited.

Thank you for your understanding
