### ISSUE TITLE
Feature request: columns (number of columns & getByTitle)

### ISSUE THREAD

**Issue by michael79bxl** [kanboard/kanboard#3322]
That would be nice if the Project API returns the number of columns in a project.

Sample: getProjectByName (& other functions)
``{``
``    "jsonrpc": "2.0",``
``    "id": 1620253806,``
``    "result": {``
``        "id": "1",``
``        "name": "Test",``
``        "is_active": "1",``
**"columns": "5",**
``   "token": "",``
``        "last_modified": "1436119135",``
``        "is_public": "0",``
``        "is_private": "0",``
``        "is_everybody_allowed": "0",``
``        "default_swimlane": "Default swimlane",``
``        "show_default_swimlane": "1",``
``        "description": "test",``
``        "identifier": "",``
``        "url": {``
``            "board": "http:\/\/127.0.0.1:8000\/?controller=board&action=show&project_id=1",``
``            "calendar": "http:\/\/127.0.0.1:8000\/?controller=calendar&action=show&project_id=1",``
``            "list": "http:\/\/127.0.0.1:8000\/?controller=listing&action=show&project_id=1"``
``        }``
``    }``
``}``

That would be nice to able to find a column by its title (Column API)

Sample: function getColumnByTitle

```
{
    "jsonrpc": "2.0",
    "method": "getColumnByTitle",
    "id": 1242049935,
    "params": [
        "title": "Closed"
    ]
}
```

**Comment by fguillot** [comment]
If you need this feature, the best way is to contribute :)
