### ISSUE TITLE
Gravatar overwrites disables local Avatar

### ISSUE THREAD

**Issue by fernwerker** [kanboard/kanboard#3323]
### Actual behaviour

Local Avatar is not shown if gravatar plugin is installed

### Expected behaviour

Local Avatar is shown if gravatar plugin is installed but user is not found in gravatar

### Steps to reproduce

1. upload local avatar
2. install gravatar plugin
3. users without gravatar account will lose their avatar

### Configuration

- Kanboard version: 1.0.44

**Comment by SergiArias** [comment]
Yeah! It would be awesome to fix this :)

**Comment by esprit-libre** [comment]
Same in 1.0.48

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
