### ISSUE TITLE
GoogleAuth returns only "External authentication failed"

### ISSUE THREAD

**Issue by marcosaccioly** [kanboard/kanboard#3324]
### Actual behaviour

When trying to authenticate through Google the user is redirected to the login page with the message "**External authentication failed**".

I have enabled logs and tried stdout and file (folder with proper permissions) but nothing is displayed expect the aforementioned message. 

### Expected behaviour

Google Authentication should authenticate the user and log him in. 

### Steps to reproduce

I have had to manually install the plugin as the Plugin Directory Page (`/?controller=PluginController&action=directory`) shows a message "_There is no plugin available._". 

1. Install the plugin
2. Configure Google API Credentials at `/?controller=ConfigController&action=integrations`
3. Log out 
4. Try to log in via Google Authentication 

### Configuration

GoogleAuth plugin version: 1.0.4
Application version: 1.0.45
PHP version: 5.6.30
PHP SAPI: cgi-fcgi
OS version: Linux 4.4.54-grsec-1.lc.x86_64
Database driver: mysql
Database version: 5.6.34-log
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by marcosaccioly** [comment]
Is there anywhere where we can have more informative messages, like a log? We have 'debug' enabled and there's nothing in the logs.

**Comment by marcosaccioly** [comment]
I'm starting to see a pattern here... Requests to `https://kanboard.net/plugins.json` and `https://www.googleapis.com/oauth2/v1/userinfo` both fail. Seems like the server is having a hard time dealing with outbound `https://` requests.

**Comment by marcosaccioly** [comment]
I noticed `allow_url_fopen` is **OFF**. Does Kanboard need it on for these types of requests?

**Comment by marcosaccioly** [comment]
Well, we have enabled `allow_url_fopen` and `allow_url_include` but the error persists. Any clues from the logs, @fguillot ?

**Comment by marcosaccioly** [comment]
@fguillot you may close the issue, sorry for the inconvenience. 

The solution was setting `allow_url_fopen` to ON.

It is worth informing on the [requirements](https://kanboard.net/documentation/requirements) section that `allow_url_fopen` must be `ON` for the Kanboard's HttpClient to work.

**Comment by marcosaccioly** [comment]
@fguillot you may close the issue, sorry for the inconvenience. 

The solution was setting `allow_url_fopen` to ON.

It is worth informing on the [requirements](https://kanboard.net/documentation/requirements) section that `allow_url_fopen` must be `ON` for the Kanboard's HttpClient to work.

**Comment by AhmedFat7y** [comment]
I've added this but still it's not working for me and failing requests

```ini
; Whether to allow the treatment of URLs (like http:// or ftp://) as files.
; http://php.net/allow-url-fopen
allow_url_fopen = On
```
