### ISSUE TITLE
there is not Calendar and Gantt View at all

### ISSUE THREAD

**Issue by BigGitWorld** [kanboard/kanboard#3326]
Hi.
I have downloaded latest stable kanboard and set it in my vps
everything is good, but in the projectview, I dont have "Calendar" and "Gantt" views.
why?
![screenshot from 2017-06-30 23-06-00](https://user-images.githubusercontent.com/28644637/27749592-ae3255ba-5dc3-11e7-841f-20a524e84897.png)

**Comment by Busfreak** [comment]
https://github.com/kanboard/plugin-calendar

https://github.com/kanboard/plugin-gantt
