### ISSUE TITLE
what is t() function exactly?

### ISSUE THREAD

**Issue by BigGitWorld** [kanboard/kanboard#3328]
In the source code, t() function (in functions.php) does not has any input parameter,but in using, it has a string argument.
while it returns a string.
what does this function exactly?

**Comment by rautamiekka** [comment]
I think you didn't even try to read it. It clearly states what it does, in a nutshell:

```php
/**
 * Translate a string
 *
 * @return string
 */
function t()
{
    return call_user_func_array(array(Translator::getInstance(), 'translate'), func_get_args());
}
```

The `func_get_args()` is used to get whatever unpredictable arguments the function is given, which is why it's not initialized with defaults.
