### ISSUE TITLE
vendor.js instead of vendor.min.js?

### ISSUE THREAD

**Issue by BigGitWorld** [kanboard/kanboard#3331]
I want to change somethings in vendor.js file.
But there is the vendor.min.js (minified version) in source code.
is there anyone to provide me vendor.js file?
best regards

**Comment by BigGitWorld** [comment]
How can I use a different calendar from gregorian calendar?
I have a jquery-ui plugin for my local calendar and want to replace it instead of gregorian calendar.
I did a similar work in java already but I'm new in javascript.
I tried to re-produce vendor.js by gulpfile.js first, but I datepicker ui in task creation form has been disappeared.
please notify me.
best regards...

**Comment by fguillot** [comment]
You have to install nodejs and npm to get external libs, see https://kanboard.net/documentation/assets
