### ISSUE TITLE
Database not migrated after going from KB 1.0.31 to 1.0.45

### ISSUE THREAD

**Issue by Mammeri** [kanboard/kanboard#3332]
### Actual behaviour

Like everyone I guess I did several updates of kanboard, withtout any issues until now.
For that I just followed the procedure here : https://kanboard.net/documentation/update

- backup of my current kanboard instance (all the directory which contains of course the SQLlite database)
- uncompress the new kanboard, with the good rights
- copy of the old config.php into the new kanboard instance
- i test the new instance withtout any plugins before installing them one by one

### Expected behaviour

After doing that the new kanboard instance was working but no data was migrated !
My admin password was "admin" and all the users didn't have anymore their projects. The project list was totally empty.
I guess the database was not migrated at all.

### Configuration

- Kanboard version: from 1.0.31 to 1.0.45
- Database type and version: sqlite 3.7.3 (don't know the new version included with the 1.0.45)
- PHP version: 5.3.3-7+squeeze29 (the requirements seems to be now 5.3.9 but didn't see any "breaking changes towards that in the changes.log)

Note that i didn't found ANY log from the migration, where are they ? Also note the i don't have any "sqllite.sql" file (to perform the migration i guess) in the app/schema/... directory. Is it normal ?

Please let me know how I can investigate my issue. Thank you !

**Comment by Chaosmeister** [comment]
Kanboard only supports incremental updates.  
So you have to update from Version 1.0.31 to 1.0.32, then from 1.0.32 to 1.0.33 and so on.

@fguillot maybe add this bit of information to https://kanboard.net/documentation/update

**Comment by fguillot** [comment]
Did you copy your previous `db.sqlite` to the new install? if not, you will end-up with a empty db.

**Comment by fguillot** [comment]
Closing, no answer.
