### ISSUE TITLE
Using LDAP query with umlauts/special characters for the manager group does not work

### ISSUE THREAD

**Issue by psy-q** [kanboard/kanboard#3334]
### Actual behaviour

Using the query `CN=Domänen-Benutzer,CN=Users,DC=ad,DC=domain,DC=com` for LDAP_GROUP_MANAGER_DN, no user ever gets the manager role even though all users are in that group.

Trying to escape the ä as \E4 did not work.

When using the query `CN=Some_Other_Group,OU=_distributionlists,DC=ad,DC=domain,DC=com`, as LDAP_GROUP_MANAGER_DN, users that are in that group do get the manager role.

### Expected behaviour

Users in the group `CN=Domänen-Benutzer,CN=Users,DC=ad,DC=domain,DC=com` should have the manager role after logging into Kanboard.

### Steps to reproduce

1. Set up a German Active Directory server
2. Add some users, make sure they have the basic user group ("Domänen-Benutzer") as primary group
3. Configure Kanboard to use the matching DN: `CN=Domänen-Benutzer,CN=Users,DC=ad,DC=domain,DC=com` as LDAP_GROUP_MANAGER_DN.
4. Log into Kanboard as such a user.
5. Observe that they are missing the manager role (they are created as normal user).
6. Choose another group the user is member of, one without special characters, configure it as LDAP_GROUP_MANAGER_DN.
7. Log in as that user again.
8. Observe that they now receive the manager role.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

    Version: 1.0.38
    PHP Version: 5.6.30-0+deb8u1
    PHP SAPI: apache2handler
    OS Version: Linux 3.16.0-4-amd64
    Datenbanktreiber: mysql
    Datenbank Version: 10.0.30-MariaDB-0+deb8u2
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
