### ISSUE TITLE
Notification when new stable update is available

### ISSUE THREAD

**Issue by afranke** [kanboard/kanboard#3338]
It would be nice for admins to get a notification when a new version is available. A banner at the top mentionning that one is not running the latest stable version and should update would be nice too.

**Comment by fguillot** [comment]
I do not plan to add such feature. The best way to to be notified of a new release is to subscribe to the RSS feed or to follow the twitter account.

**Comment by afranke** [comment]
Rationale is that even if you are aware of the new version (and maybe even upgraded to it somewhere else), you may not realize that the current instance is not up to date. So it’s more about warning of an outdated version.
