### ISSUE TITLE
Images not loading after transfer

### ISSUE THREAD

**Issue by tabarjack** [kanboard/kanboard#3339]
**Please, do not create duplicate issues**

### Actual behaviour

The images are loading as blank images.

### Expected behaviour

I should see the image that was there before.

### Steps to reproduce

Migrated from another server, using ftp. Everything else works, uploading new images show up. However, all the old images (and the image ID like 735204bad47928e8b96ae28083b2d37437ef7a40 is there, in the right path) just show up as blank.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

Application version: 1.0.45 (was on 1.0.31 before, tried upgrading to see if it fixed the problem)
PHP version: 7.0.18-0ubuntu0.16.04.1
PHP SAPI: apache2handler
OS version: Linux 4.4.0-79-generic
Database driver: mysql
Database version: 5.7.18-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by fguillot** [comment]
- Watch log files for errors
- Check folder permissions
- Make sure that everything is installed correctly
