### ISSUE TITLE
Cant delete column

### ISSUE THREAD

**Issue by lespaul4** [kanboard/kanboard#3340]
**Please, do not create duplicate issues**

### Actual behaviour

Cannot delete columns when going to Project > Settings > Columns
The only option I have is 'Edit' - there is no delete/remove function.

### Expected behaviour

I would expect there to be a way to delete/remove any column when I enter the column settings. 
Even when I open 'Edit' the only option there is to 'hide' the column, which is not what I want. I want to delete/remove.

### Steps to reproduce

1. Go to Project > Settings > Columns
2. Once at Columns, select the column you would like to delete - but I cannot.

[Screenshot - 1](https://drive.google.com/file/d/0B6rjqLIGFg_wVEQ4bW1CRzdNSTg/view?usp=sharing)
[Screenshot - 2](https://drive.google.com/file/d/0B6rjqLIGFg_wbjltT24tS1poa2c/view?usp=sharing)

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.45
- Database type and version:  sqlite / 3.8.7.1
- PHP version: 5.6.30-0+deb8u1
- OS: Linux 4.9.35-v7+
- Browser: Chrome

**Comment by fguillot** [comment]
You cannot delete columns that contains tasks.

**Comment by lespaul4** [comment]
Thanks fguillot for answering.

**Comment by amff1704** [comment]
I do not have any tasks in any column and still can't delete the tasks...

**Comment by Chaosmeister** [comment]
This also happens to me.
I had an automatic action that moved tasks that were moved into this colum into another project. Now I can't delete the column.

**Comment by djixas** [comment]
Same issue.

Any update? Latest version

**Comment by dedeibel** [comment]
Please check that you don't have "closed" tasks in the column. It seems like they prevent a deletion too. You can see them in the projects, columns settings view.
