### ISSUE TITLE
Locale PT_BT - revised translation -  1.0.45

### ISSUE THREAD

**Issue by gideoni** [kanboard/kanboard#3341]
I did a review on the translation.
Among others, the terms below have been revised throughout the language file:

'Assign the task to its creator' => 'Atribuir a tarefa ao seu criador',
'This task was sent by email to "%s" with subject "%s".' => 'Esta tarefa foi enviada para "%s" com o assunto "$s".',
'Predefined Email Subjects' => 'Assuntos predefinidos de E-mail',
'Write one subject by line.' => 'Escreva um assunto por linha.',

[translations.php.txt](https://github.com/kanboard/kanboard/files/1136088/translations.php.txt)

    Versão da aplicação: 1.0.45
    Versão do PHP: 7.1.4
    PHP SAPI: apache2handler
    Versão do sistema operacional: Windows NT 6.1
    Driver do banco de dados: mysql
    Versão do banco de dados: 10.1.22-MariaDB
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by fguillot** [comment]
The Brazilian translation is up to date now: https://github.com/kanboard/kanboard/blob/master/app/Locale/pt_BR/translations.php
