### ISSUE TITLE
tooltip does not work correctly

### ISSUE THREAD

**Issue by BigGitWorld** [kanboard/kanboard#3342]
### Actual behaviour
when I hover mouse over an icon, hyper-text does not shown correctly.
![screenshot from 2017-07-10 20-16-09](https://user-images.githubusercontent.com/28644637/28028010-a451fd4c-658a-11e7-9f9b-129b3c0d42c6.png)

### Expected behaviour
When I hover mouse over an icon, real hyper-text appears.

**Comment by fguillot** [comment]
I forced to close this issue because you didn't even fill the provided template. Try to upgrade to the latest version...
