### ISSUE TITLE
Brazilian currency.

### ISSUE THREAD

**Issue by gideoni** [kanboard/kanboard#3346]
Please include the Brazilian currency in Kanboard.

**in CurrencyModel.php:**
`'BRL' => t('BRL - Brazilian Real'),`

**in translations.php:**
`'BRL - Brazilian Real' => 'BRL - Real Brasileiro', `

### Configuration

Versão da aplicação: 1.0.45
Versão do PHP: 5.5.38
PHP SAPI: apache2handler
Versão do sistema operacional: Windows NT 6.1
Driver do banco de dados: mysql
Versão do banco de dados: 5.7.11-log
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by fguillot** [comment]
It's there now: https://github.com/kanboard/kanboard/blob/master/app/Model/CurrencyModel.php#L51
