### ISSUE TITLE
Is "Plugin Directory" still working in 1.0.45?

### ISSUE THREAD

**Issue by oliviermaridat** [kanboard/kanboard#3347]
Is "Plugin Directory" still working in 1.0.45?

### Actual behaviour

On the "Plugin Directory" (/extensions/directory), I have now a "There is no plugin available." message, and no plugin is shown (this not the "configuration" error message, but the "no plugin available" warning).

It was working on v1.0.43. 
Does someone else have the same behaviour?

### Expected behaviour

Available plugin list shall be displayed

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

    Application version: master (git checkout v1.0.45)
    PHP version: 7.0.17
    PHP SAPI: fpm-fcgi
    OS version: Linux 4.4.67-ovh-vps-grsec-zfs-classid
    Database driver: mysql
    Database version: 5.5.55-0+deb7u1-log
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by marcosaccioly** [comment]
I have the same error. I believe it is due to the https:// request and your server configuration. I'm still trying to figure it out, but notice I've detailed it in this issue: https://github.com/kanboard/kanboard/issues/3324

**Comment by marcosaccioly** [comment]
@oliviermaridat 

The solution for me was setting `allow_url_fopen` to ON.

Cheers,

**Comment by oliviermaridat** [comment]
I checked with ini_get(allow_url_fopen) and it is set to "1" (i.e. ON) on my configuration. So this is not the same issue for me...

I manage to read some logs, and I have a "[error] HttpClient: request failed".
Nothing more yet...

**Comment by oliviermaridat** [comment]
By the way, I confirm that it also prevents from login using Google!

**Comment by fguillot** [comment]
Make sure your hosting provider is able to handle Cloudflare SSL certificate properly. Especially if you use OVH. If you have a shell, try `curl -v https://kanboard.net/plugins.json`
