### ISSUE TITLE
Public link - display options

### ISSUE THREAD

**Issue by valvin1** [kanboard/kanboard#3350]
### Actual behaviour

When I create a new public link for my project it displays with default view. I mean open tasks in not collapsed view and of course in read-only mode. 

### Expected behaviour

I am looking for an option to change the display of public view. For example put task in collapse view using a parameter in the url. The same to display a specific filter. I have not found any issue and documentation on this kind of feature. 
### Configuration

    Application version: 1.0.41
    PHP version: 7.0.19
    PHP SAPI: apache2handler
    OS version: Linux 3.10.0-514.21.1.el7.x86_64
    Database driver: postgres
    Database version: 9.5.7
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding

**Comment by Le1b1** [comment]
@valvin1 Did you write a custom plugin or found any other solution?

**Comment by valvin1** [comment]
@Le1b1 no, not yet I've not found time for this unfortunately.

**Comment by chriswep** [comment]
@fguillot would you accept a pull request that adds the possibility to manually add the search parameter to the public URL's query string (and default to the current behaviour if the parameter is not there)? As far as i could see there is no way to accomplish this via a plugin (?).

@valvin1 @Le1b1 It's a very simple change to the BoardViewController. However this only addresses the filter part of the issue not the layout.
