### ISSUE TITLE
# Feature Request: Add Reminders

### ISSUE THREAD

**Issue by jighem** [kanboard/kanboard#3351]
Can we have some option like to add reminders in the Task or subtask which shall pop-up on notification on time which is set to remind some task or sub task?

This will add stars to the current workings!!

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
