### ISSUE TITLE
Use icons/svg on project titles, descriptions, etc...

### ISSUE THREAD

**Issue by SergiArias** [kanboard/kanboard#3355]
This is an improvement proposal. Sometimes I use emoticons like this one to select quicker the information: 🔥 (or for example 🐞with a bug). 
If I use them on project title or tag it fails giving a database error.

But, I think even working, it would be awesome to be able to use fontawesome/emojis anywhere by the user, or even custom svg images using some kind of shortcode.

Wordpress converts emojis to it's own svg, so I guess it's not a big deal.

Would that be an interesting feature?

**Comment by SergiArias** [comment]
I tried to make it work by changing mysql encoding to utf8mb4, without success :(

![image](https://user-images.githubusercontent.com/13618783/28473591-925c0cae-6e45-11e7-9250-4310240952a0.png)

**Comment by fguillot** [comment]
Tracked on issue #3789
