### ISSUE TITLE
./cli worker doesn't return to prompt

### ISSUE THREAD

**Issue by lifeboy** [kanboard/kanboard#3356]
### Actual behaviour
When running "./cli worker" from the command line, it doesn't return to the command prompt. 

### Expected behaviour
Should the system return to a command prompt or is this the expected behaviour until the command it terminad with ctrl-c?

Moreso, how does one add this "./cli worker" to the system startup files.  I have beanstalk running as a service on Ubuntu.  Are these two related?  It may seem obvious to those that know how this works, but it's unclear in the documentation.

It seems that if cli worker is not running, then mail notifications are not sent.

Application version: 1.0.45
PHP version: 7.2.0alpha3
PHP SAPI: apache2handler
OS version: Linux 4.4.59-1-pve
Database driver: mysql
Database version: 10.0.31-MariaDB-1~trusty
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/59.0.3071.109 Chrome/59.0.3071.109 Safari/537.36

**Comment by rautamiekka** [comment]
Since it reads `-pve` in the kernel version string, is this an https://en.wikipedia.org/wiki/Proxmox_Virtual_Environment machine ?

**Comment by lifeboy** [comment]
Yes, it is.  What would the relevance of this be then?

**Comment by fguillot** [comment]
You have to run this command with a process manager like supervisord or systemd. That will not return to the prompt.

**Comment by lifeboy** [comment]
It would be nice to have a little more detailed installation / setup
instructions.  Of course this is probably obvious to those working with it
every day, but to me it's not.

How would I run this with supervisord then please?

​Thanks​


*Roland*

**Comment by fguillot** [comment]
The documentation of supervisord is there: http://supervisord.org/, just define a command for the Kanboard's worker: `/path/to/cli worker`
