### ISSUE TITLE
New feature: Assign default role for project

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#3362]
### Actual behaviour

On the settings, I can either have all -"Allow everybody to access to this project" - or nothing.  I cannot have a project where, say, all users have *some* level of permissions, but not the right to do anything they wish.

### Desired behaviour

I'd like to automatically assign everyone a default (custom) role for the project.  This will allow a project which is on everyone's Kanboard, and perhaps they can go in and add things to the "backlog" column or change items assigned to themselves - but not to have free reign to do what they please.

This is particularly important if I'm using LDAP authentication, and automatically create users.

**Comment by AlgyTaylor** [comment]
Actually, it might be better to add these as possible events.  For example, ``User::EVENT_CREATE``, ``User::EVENT_UPDATE`` and so on.  You could then hook them up to an automatic action for a board, so it'd be more flexible (although assigning a role is the only thing off the top of my head that I can think of doing!)

**Comment by fguillot** [comment]
If you use LDAP, enable the group sync, and assign a role to this group. People that belongs to this group will have access to this project with the specified role.
