### ISSUE TITLE
New automatic action: Email assigned person

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#3363]
### Actual behaviour

I go on to "Automatic actions", then "send a task by email to someone".  I click "move a task to another column" -- I want to send an email to the person **who the task is assigned to** when it reaches  "Priority".  However, I only have "unassigned" or a list of users -- no "user that this task is assigned to".

### Expected behaviour

Add a "user that task is assigned to" person for automatic actions!  It'd also be nice to have "Send a task by email to someone" and "when someone is assigned" added as a possibility. :)

**Comment by AlgyTaylor** [comment]
It'd also be handy to be able to email "person who created the task", to allow them to monitor things that they'd added easily

**Comment by creecros** [comment]
Try this:
https://github.com/creecros/SendTaskCreator

**Comment by AlgyTaylor** [comment]
@creecros - thanks :+1:

**Comment by fguillot** [comment]
@creecros You could publish your plugin on the website if you would like.

**Comment by creecros** [comment]
@fguillot how do i do that?

**Comment by mrozigor** [comment]
There is description in Kanboard website project: https://github.com/kanboard/website

**Comment by creecros** [comment]
thanks, yeah, I eventually found it and made a pr
