### ISSUE TITLE
#FeatureRequest - Automatic Action

### ISSUE THREAD

**Issue by Walfy21** [kanboard/kanboard#3365]
Would it be possible to get another action for "Duplicate Task To Another Project", if we move the item on one Board it duplicates the Action on another board and to specific Columns on duplication?

Example.
Task Created on Board 1, Duplicated to Board 2 in the first Column.
  - Can we get an option to select the relevant column when the task is duplicated?

If we later modify the task and move it to a completed Column can we have it move on both boards and apply the same Status and column if it exists?

Hope that my details above make sense.

**Comment by amff1704** [comment]
Thant makes a lot of sense, that would be like having shared columns between projects. It would be a great feature.

**Comment by Walfy21** [comment]
Agreed :). I would love to attempt to develop it my self but have no Skills in PHP yet ha ha, Maybe one day i'll get sometime to learn. 

How ever having a Shared column or set of columns would be amazing and any changes to the column are carried across both projects 💃

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin or to contribute to the project.

Thank you for your understanding
