### ISSUE TITLE
Feature request: projects clickable

### ISSUE THREAD

**Issue by SergiArias** [kanboard/kanboard#3366]
Sometimes it can be useful to open a project in a new tab in the browser while mantaining current view. But in the list, the links aren't clickable, but javascript, as seen in screenshot below. Would it be interesting to implement?

![image](https://user-images.githubusercontent.com/13618783/28528455-fdbe5836-708d-11e7-8690-12aa63515226.png)

**Comment by NinjaPewPew** [comment]
I usually open the board view in a new tab and than jump from there via list to the other project. It takes a bit more "effort", but works fine. Doesn't even take long if you get used to it.

**Comment by SergiArias** [comment]
Yeah, I do the same, it's nothing critical, but desired :)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
