### ISSUE TITLE
Gantt option not showing for regular users after plugin is installed

### ISSUE THREAD

**Issue by marcosaccioly** [kanboard/kanboard#3368]
### Actual behaviour

Gantt menu item does not show for regular user or manager.

### Expected behaviour

After Gantt plugin is installed, Gantt menu option should be immediately available to all users. 

### Steps to reproduce

1. Go to the plugins page and install Gantt plugin 
2. Go to a project page and check that Gantt option is normally shown 
3. Log out and log in as a regular user OR ask some regular user to check if they can see the Gantt option in the project page 

### Configuration

Versão da aplicação: 1.0.45
Versão do PHP: 5.6.30
PHP SAPI: fpm-fcgi
Versão do sistema operacional: Linux 4.4.54-grsec-1.lc.x86_64
Driver do banco de dados: mysql
Versão do banco de dados: 5.6.34-log
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by Phryxe** [comment]
Same problem here.

Application version: 1.0.45
PHP version: 5.3.28
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.1
Database driver: sqlite
Database version: 3.7.7.1

**Comment by Snajper88** [comment]
yes, this seems to be normal behaviour. I also wanted to make everyone see the Gantt plugin.

To let everyone see the Gantt tab at the top, simply go to the Plugin.php and change:
$this->projectAccessMap->add('TaskGanttController', '*', Role::PROJECT_MANAGER);
into
$this->projectAccessMap->add('TaskGanttController', '*', Role::PROJECT_MEMBER);

And thats it!

**Comment by Snajper88** [comment]
Actually I dont remember if there was _MANAGER or _OWNER before my edits...
Never the less, just change the Role:: - part into PROJECT_MEMBER
That should do the trick.

**Comment by marcosaccioly** [comment]
Man, that's gold. Thanks. I can say that I've successfully updated the `Plugin.php` file in `Gantt` folder and can see the expected results (regular users now have access to Gantt visualization feature). 

Have you made a pull request, @Snajper88 ?

**Comment by Snajper88** [comment]
Nope, because I guess its intension is, that only the project owner, or manager, can use that to keep an overview over the project.
A normal project member simply doesn't need that function, in general. 

The best solution would be a new option to simply set this "role" in the plugin settings on the web interface. Which I can't do, cause my skills are too low...

**Comment by marcosaccioly** [comment]
Got you. Good point. I'm closing this issue then. :)
