### ISSUE TITLE
QUESTION: More columns in board query

### ISSUE THREAD

**Issue by Imbasaur** [kanboard/kanboard#3369]
Hello,

Can i add new columns and tables to formatter:board:query hook? I Can't find any way to do it.

Thanks!

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
