### ISSUE TITLE
Feature requests: Custom roles extension and...

### ISSUE THREAD

**Issue by Abraka** [kanboard/kanboard#3370]
1. new column restriction -> hide tasks in this column
2. new column restriction -> lock out tasks in this column = specific user or group wont be able to read tasks in specific column(user wont see any text on task, but will know that some tasks are there)
3. new column restriction -> only selected color is allowed
4. new project restriction -> see only assigned tasks is permited
5. new project restriction -> use only allowed colors for tasks is permited

6. when creating new project, allow only speficic colors for tasks.
7. user group - allow only specific colors for use in tasks

**Comment by fguillot** [comment]
I prefer to keep the software simple. If you need these features, the best way is to contribute to the project.
