### ISSUE TITLE
Choose how to receive notification for each project

### ISSUE THREAD

**Issue by mytheine** [kanboard/kanboard#3371]
### Actual behaviour

My users can configure to receive a notification but this will be a global configuration.
If I choose to receive notification for "All tasks", that will be for all my projects that I have checked in the interface so I will receive a notification for all of them.

But I cannot say:
- For Project1 I want to receive a notification for **All tasks**
- For Project2 I want to receive a notification **only tasks assigned to me**

### Expected behaviour

I would like to be able to choose for **each project** if I want to receive a notification for :
- All tasks
- only tasks assigned to me
- only for tasks created by me
- only for tasks created by me and assigned to me

I would like to be able to say:
- For Project1 I want to receive a notification for **All tasks**
- For Project2 I want to receive a notification **only tasks assigned to me**

### Configuration

- Kanboard version: 1.0.45
- Database type and version: MySQL

**Comment by cjohnsonuk** [comment]
With notifications it would be nice to be able to choose 
notify on every change
or
notify me in bulk of changes in last XX days where you can choose the number of days and it won't send you emails more often than that.

We're seeing managers receiving 50+ emails when we reschedule our tasks as it sends an email for every drag and drop.  They're not happy... ;-)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
