### ISSUE TITLE
Hyperlinks in comments open in current tab/window

### ISSUE THREAD

**Issue by robotichead** [kanboard/kanboard#3373]
### Actual behaviour

When clicking on a hyperlink in the comment section, it will open it in the current tab/window

### Expected behaviour

The hyperlink will be opened in a new tab so user will not lose position on Kanboard

#### Prerequisite
An active project that contains a task. The task will need to contain a comment with a hyperlink in it

1. Log into Kanboard as any type of user
2. Navigate to a current project with current tasks
3. Click on a task with a comment in it
4. Wait for page to load, once loaded click on the hyperlink

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: kanboard-1.0.44
- Database type and version: mysql
- PHP version: php5
- OS: Debian 8
- Browser: Mozilla Firefox

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
