### ISSUE TITLE
Order of execution of plugins

### ISSUE THREAD

**Issue by bildsoe** [kanboard/kanboard#3374]
Hi,

I'm trying to extend the functionality of the standard email-client Core\Mail\Client. I'm accomplishing this using a plugin that modifies the Pimple container setup, by unsetting "emailClient", and creating a new (See below). However I'm also using the Mailgun plugin, and it gets an instance of "emailClient" before I change "emailClient", so my new methods are not used. Could this be solved by changing the order of execution of plugins? or am I hacking something, which could be solved more elegant?

$container = $this->container;
$container['emailClient'] = null;
$this->container['emailClient'] = $this->container->factory(function ($c) {
    return new MyMailClient($c);
});

BR
Thomas

**Comment by fguillot** [comment]
You can have only one email client. If you need mailgun and a custom one, you could inherit MyMailClient from the Mailgun client class.
