### ISSUE TITLE
Feature Request: Resource Management / Workload Reporting

### ISSUE THREAD

**Issue by robelgit** [kanboard/kanboard#3375]
**Hello friends. I did not find this feature in my test Kanboard installation with most plugins installed, the documentation or in this Issues list, so here goes**

### What I am trying to do (with Kanboard)

My team members are planned in onto multiple tasks in multiple projects, sometimes doing work for multiple departments.  I have not found out if/how Kanboard can show me where the planned-in tasks will cause a team member to be overloaded in the future.

### The features that would help 
I would like to be able to visualize the workload of each team member across all projects and tasks, set against time (e.g. planned tasks workload in hours per day).
Daily workload per task could be calculated from the 'Time Estimated' information in the task, divided equally across the period between the 'Start Date' and the 'Due Date'.  
If Kanboard could take into account the 'Time Spent' hours (as 'frozen') and only redistribute the remaining hours that would be even better.

Ideally, I would like to be able to resolve overloads dynamically by shifting team members' tasks in time or to another team member, while Kanboard recalculates the daily workload per team member automatically.  The GANTT view would be a natural place to do this, but it would need to be accessible across projects (rather than per project), enable sorting and grouping tasks on team members and projects (and on start / due dates of course :-) ) and calculating totals per group for the  (remaining) averaged workhours per task.

**If Kanboard can already do this, you'll let me know, won't you :-)** 

Many thanks,
Rob

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited.

Thank you for your understanding
