### ISSUE TITLE
Direct link to commenting the task in Board view

### ISSUE THREAD

**Issue by flowernert** [kanboard/kanboard#3377]
Feature request
User interface

### Actual behaviour

To comment a task, you have to dropdown the menu, then click add a comment
As commenting is an action often performed by users, it's boring for them to have a 2 clicks path to do it. Most UI of publication/comment system propose to comment in 1 click to encourage participation of users

### Expected behaviour

Have a direct link to commenting like this
(sorry, I already hacked to UI to have a direct link to editing the task and to have the feature I'm requesting :D )

Let me know if you would like me to commit it and ask a pull request

![image](https://user-images.githubusercontent.com/2923696/28960111-b0b3e4e8-78fd-11e7-8587-8166c7f97825.png)

**Comment by TriYop** [comment]
+1

**Comment by fguillot** [comment]
@krustymars You could send a PR like you did for the edit icon :)

**Comment by kent1D** [comment]
Why not show on every task the number of comments (0 if none) then this icon can be clicked. It’s already the case when there is at least one comment, isn’t it?

**Comment by aljawaid** [comment]
oh this would be a great time saving tool

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
