### ISSUE TITLE
Attach Documents not opening

### ISSUE THREAD

**Issue by dave8787** [kanboard/kanboard#3378]
### Actual behaviour

When I click on "Attach a Document" nothing happens (no popup, no window opens). I am correctly able to attach screenshots but not documents.
Same behavior with IE 11 and Firefox.

In Firefox, if I click on "Attach a Document" and "open in new tab" following error is returned in blank page:
"PHP Notice:  A non well formed numeric value encountered in C:\inetpub\wwwroot\kanboard\app\Helper\TextHelper.php on line 100"

Checking Firefox web console, I found following error when clicking on "Attach a Document" link (translated from Italian):
"XML interpretation error: syntax error
Address: http://localhost/kanboard/?controller=TaskFileController&action=create&task_id=1&project_id=1
Row number 1, column 1:"

### Expected behaviour

Opening of attachments management when I click "Attach a Document"

### Steps to reproduce

1. Log in to the application with a user account (admin, manager or user)
2. Enter a project
3. Create a task
4. Enter task and click on "Attach a Document" -> nothing happens

### Configuration

    Application version: 1.0.45
    PHP version: 7.1.0
    PHP SAPI: cgi-fcgi
    OS version: Windows NT 6.1
    Database driver: sqlite
    Database version: 3.15.1
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by fguillot** [comment]
Update to 1.0.46 to suppress the PHP notice, see: https://github.com/kanboard/kanboard/blob/master/ChangeLog#L28
