### ISSUE TITLE
attached JPG files NOT VISIBLES on dashboard.

### ISSUE THREAD

**Issue by tutle** [kanboard/kanboard#3379]
### Actual behaviour

When upload a picture, **impossible to delete it or to see it** in task view.

### Expected behaviour

I just see small "clickable" join logo in the board view
I had before miniatures of pictures in task view

### Steps to reproduce

just try to upload a picture file.

### Configuration

- Kanboard version : 1.0.46
- Database type and version:
- PHP version:
- OS:Win10
![bugjpg kanboard1](https://user-images.githubusercontent.com/23037149/29884575-373fe5d2-8db4-11e7-947d-2dfde3124251.PNG)
![bugjpg kanboard2](https://user-images.githubusercontent.com/23037149/29884577-37623204-8db4-11e7-9433-64ceeb041099.PNG)

- Browser: Firefox

Nobody else has this problem ?

**Comment by Snajper88** [comment]
same here, i think. It is gone now, and I dont know why.

Version: 1.0.46
PHP Version: 5.6.22
PHP SAPI: cgi-fcgi
OS Version: Linux 3.0.101-91-default
Datenbanktreiber: mysql
Datenbank Version: 5.7.18-log

![unbenannt2](https://user-images.githubusercontent.com/20987020/29277711-baec9eba-8112-11e7-98c2-77675dfb1333.PNG)

**Comment by Snajper88** [comment]
@tutle ok, I think I got it. After an update, my data folder wasn't in the apache-writable group "www" anymore. Now, after the correction of the owner group back to www, the jpg is readable, downloadable and shown in the taskboard.

**Comment by tutle** [comment]
Curiously I tried but still don't see any pictures even in task view, also impossible to delete it once uploaded.
Just possible to view or download in pop up board view, very embarassing for my team (movie making so I often use pictures...) Still searching...

**Comment by tutle** [comment]
![kanboard1](https://user-images.githubusercontent.com/23037149/29288875-c67969a2-813a-11e7-8f05-c2ddf68ce886.PNG)
![kanboard2](https://user-images.githubusercontent.com/23037149/29288874-c673a0da-813a-11e7-85a5-75fc159911d3.PNG)

**Comment by tutle** [comment]
Still try to see the attached jpg files without success, any ideas ? So embarrassed with that probably little bug.

**Comment by tutle** [comment]
Nobody else has this problem ?
Sad...

**Comment by tutle** [comment]
Youpee, I've desactivated extension coverimage and the pictures are back !!!!
