### ISSUE TITLE
Make "Due Date" a required field

### ISSUE THREAD

**Issue by 5live** [kanboard/kanboard#3380]
I was wondering if it is possible to make the Due Date field on the task creation & modification a required field?
Many thanks.

**Comment by rautamiekka** [comment]
That should be done on a project or installation basis, otherwise use cases which don't use a due date will have to switch away from Kanboard.

**Comment by 5live** [comment]
Could you please let me know how to do it on "a project or installation basis". I tried to add this line `new Validators\Required('date_due', t('Due date is required')),` to the code on TaskValidation.php but that did not work.  Any suggestions please?

**Comment by rautamiekka** [comment]
^ I mean an option in the global settings ("installation basis") and in the project settings instead of changing Kanboard to always require a due date.

Code-wise I can't help.

**Comment by jakern** [comment]
Would setting an automatic action to assign a due date be a workaround to the problem?

**Comment by 5live** [comment]
What I really trying to achieve here is when you create a new task and you forgot to select the "due date" you will get a warning message, the same as the title. Due date is crucial in our line of business so by making the due date field as a required field that will be the workaround but doing that in the code seems not work properly, I was hoping that someone will be able to guide me. Many thanks for your help.

**Comment by oliviermaridat** [comment]
Addind `new Validators\Required('date_due', t('The due date is required')),` in two functions of TaskValidator.php is working like a charm.

```php
public function validateCreation(array $values)
    {
        $rules = array(
            new Validators\Required('project_id', t('The project is required')),
            new Validators\Required('title', t('The title is required')),
            new Validators\Required('date_due', t('The due date is required')),
        );

        $v = new Validator($values, array_merge($rules, $this->commonValidationRules()));

        return array(
            $v->execute(),
            $v->getErrors()
        );
    }

   // ...
    public function validateModification(array $values)
    {
        $rules = array(
            new Validators\Required('id', t('The id is required')),
            new Validators\Required('title', t('The title is required')),
            new Validators\Required('date_due', t('The due date is required')),
        );

        $v = new Validator($values, array_merge($rules, $this->commonValidationRules()));

        return array(
            $v->execute(),
            $v->getErrors()
        );
    }
```

**Comment by rautamiekka** [comment]
^ Does that require due date regardless of whether you'll use one ? Not everyone uses one, thus requiring without an option to change it is unacceptable.

**Comment by 5live** [comment]
Thanks a million, that has worked, brilliant. I added the line only to the  function "validateCreation", I didn't think of the second function. This has solved the problem. Acceptable or not this is by far the quickest, the most reliable and the simplest way to do it. Very grateful to oliviermaridat.
