### ISSUE TITLE
Add a document (TextHelper Bug)

### ISSUE THREAD

**Issue by alefaucheur** [kanboard/kanboard#3381]
**Please, do not create duplicate issues**
### Actual behaviour
when click on attach a document i got warning message:
Notice: A non well formed numeric value encountered in C:\xampp\htdocs\kanboard\app\Helper\TextHelper.php on line 100

and i can attach the document so nothing very bad but recurring Notice message.

### Expected behaviour
Same without warning

### Steps to reproduce
click on attach a document in the task detail view

### Configuration
Application version: 1.0.45
PHP version: 7.1.1
PHP SAPI: apache2handler
OS version: Windows NT 6.1
Database driver: mysql
Database version: 10.1.21-MariaDB
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by fguillot** [comment]
Update to 1.0.46, see https://github.com/kanboard/kanboard/commit/3ba8b0462c682a66eda0120c0ebbc37ee740e39c#diff-cbda73c855698dadfdbc565785891f1c
