### ISSUE TITLE
Change "is_active" state via Web GUI

### ISSUE THREAD

**Issue by klokocka** [kanboard/kanboard#3382]
### Actual behavior

Not button/checkbox/dropdown changing the state "is_active" exists in the Web GUI. Possible to change this value only directly in DB or via API.

### Expected behavior

In the User Management should exist a feature that will allow an administrator to change the state "is_active" of a user to 0 or 1. Can be added to the "Edit profile" or any similar section.

### Steps to reproduce

Look at every page of User Management section

### Configuration

- Kanboard version: 1.0.45 
- Database type and version: MySQL
- PHP version: 5.6
- OS: Linux Debian 8
- Browser: Chrome 56

**Comment by fguillot** [comment]
Click on the dropdown menu and choose enable/disable.
