### ISSUE TITLE
Explanation on "notification:overdue-tasks"

### ISSUE THREAD

**Issue by diegospano** [kanboard/kanboard#3384]
Hi. I have a doubt about the notifications for overdue tasks. The email is sent only to the user that has the task assigned?.  I mean, Task-A is assigned to User-A and Task-B is assigned to User-B. Each user will receive only one email mentioning his task or both users will receive an email mentioning that two tasks reach the due date?.

Thanks
Diego

**Comment by diegospano** [comment]
Any help?.
Thanks

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
