### ISSUE TITLE
Cron Doesn't Recognise hyphen

### ISSUE THREAD

**Issue by aljawaid** [kanboard/kanboard#3385]
Cron entry in cPanel doesn't seem to work as:

`* 6 * * * cd /home/ofitsc/public_html/kanboard && ./cli projects:daily-stats >/dev/null 2>&1`

cPanel results as:

`Error
"-":15: bad command
errors in crontab file, can't install.
`

### Configuration

- Kanboard version: 1.0.45
- Database type and version: MySQL
- PHP version: 7
- OS: CentOS7
- Browser: cPanel on Firefox

**Comment by fguillot** [comment]
This issue is not related to Kanboard but to cPanel. Try to use quotes...
