### ISSUE TITLE
https://kanboard.net/documentation/nice-urls update url rewriting a

### ISSUE THREAD

**Issue by mfpg** [kanboard/kanboard#3386]
**Please, do not create duplicate issues**

### Actual behaviour

Requesting update to documentation to clarify the install steps for apache rewrite enabling. From users not familiar with apache it was not apparent that a2enmod was required at command line to allow url rewriting to function. Documentation for inexperienced users suggests configuration files are only necessary for change.

### Expected behaviour
Please add a line to the instruction for Url rewriting that suggests the command

`a2enmod rewrite
`
is required.

**Comment by fguillot** [comment]
`a2enmod` is only for Debian based Linux distros. This doc is only about the Kanboard configuration part. Configuring Apache is documented in your Linux distro documentation.

Of course, you can still send a PR to improve the doc.

**Comment by mfpg** [comment]
Understandable. How about a single line in the documentation with an asterisk that mentions Debian based distros, like Ubuntu, which I'm guessing has to be one of if not the most popular distros for modern web development, need to run a2enmod rewrite.
