### ISSUE TITLE
Design/theme question

### ISSUE THREAD

**Issue by Snajper88** [kanboard/kanboard#3387]
Why does my KanbanBoard (no matter if stable or nightly build) always look like this:
https://kanboard.net/screenshots/board.png

and not like this:
https://cloud.githubusercontent.com/assets/323546/5100037/708a0e2e-6f6e-11e4-9cc6-82a49c5b1cd1.png

Application version: master.7a6b1bc3da0af442e02b5a2dc430a4ded8e7c4ee
PHP version: 5.6.30
PHP SAPI: apache2handler
OS version: Windows NT 6.1
Database driver: sqlite
Database version: 3.8.10.2

Also: What themes are available? Havent found many...

**Comment by NinjaPewPew** [comment]
Both of these screenshots show different pages. The one is a "board" and the other the "Dashboard". That is the reason they do not look the same.

**Comment by Snajper88** [comment]
You cant be serious. Obviousyl I meant the design, the theme of the whole kanbanboard. Its different.
