### ISSUE TITLE
BUG in popup category descriptions, bullet/numbered lists do not render correctly

### ISSUE THREAD

**Issue by robelgit** [kanboard/kanboard#3388]
### Actual behaviour
When I enter markdown description text containing bulleted or numbered lists into category descriptions inside a project's settings, the numbers and bullets show correctly in the preview. 
However, when I hover over the (i) icon, the popup shows the description, but without the bullets or numbers.

### Expected behaviour

bullet and numbered lists should render correctly in popups (as they are shown in the preview) 

### Steps to reproduce

1. Go to project > settings > categories, 
2. add a category.  
3. add a bulleted list / numbered list in its description markdown.  
4. note that the list renders correctly in the preview mode of the markdown editor
5. save the category
6. hover over the (i) next to the newly created category name
7. note that the list item bullets / numbers are not rendered

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version:
    Application version: 1.0.45
    PHP version: 5.6.31
    PHP SAPI: apache2handler
    OS version: Windows NT 6.2
    Database driver: mysql
    Database version: 10.1.25-MariaDB
    Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

### Evidence

![popup_numbers_not_show](https://user-images.githubusercontent.com/28824930/29229706-23e8db3e-7ee0-11e7-8889-097808b84a5d.png)
![preview_shows_numbers](https://user-images.githubusercontent.com/28824930/29229705-23e6e126-7ee0-11e7-94cb-0452e2b59eef.png)

**Comment by fguillot** [comment]
This is now fixed in the development branch. Thanks
