### ISSUE TITLE
JSON-Rpc No API to authenticate user

### ISSUE THREAD

**Issue by HDBaggy** [kanboard/kanboard#3389]
I am developing a Mobile application that consumes API of Kanboard.

### Actual behaviour

There is Authentication API related documentation on https://kanboard.net/documentation/api-authentication   But it is not well documented to authenticate user. You can authenticate application but not user based on the guide lines it provides.

I am unable to find the API for following opeartions.

- Signup
- Forgot password
- Change password
- Logout

### Expected behaviour

There should be APIs for those operations. If they are already available, please add them in API documentation.

**Comment by fguillot** [comment]
You can create user by using these api calls: https://kanboard.net/documentation/api-user-procedures

There is no logout because the API is stateless.
