### ISSUE TITLE
Feat. Req.: Login to different default view. (i.e. 'Board View' of 'Project')

### ISSUE THREAD

**Issue by MDKAOD** [kanboard/kanboard#3391]
**Please, do not create duplicate issues**

### Actual behaviour

Upon login, user is send directly to the overview view.

### Expected behaviour

Would like to see a profile option to default directly to a desired view. For example, would like to log in directly to "Board View" of a specific project to simplify use for the less-tech savvy.

**Comment by Snajper88** [comment]
I would love that - and I tell you why.
I seperated our working places into "projects" - so it makes 100% sense to make the projects dashboard the startpage for us.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
