### ISSUE TITLE
PostgreSQL: permission denied for relation schema_version

### ISSUE THREAD

**Issue by weberjn** [kanboard/kanboard#3394]
When I followed the procedure from Postgresql configuration I got
SQLSTATE[42501]: Insufficient privilege: 7 ERROR: permission denied for relation schema_version

This was because I had run the postgres.sql script as postgres user as the procedure assumes and configured the app to use a different user.
For security reasons the app should always use a different user:

define('DB_USERNAME', 'kanboard');
define('DB_PASSWORD', 'sosecret');
define('DB_HOSTNAME', 'localhost');
define('DB_NAME', 'kanboard');

What worked for me was to run the sql as user kanboard:

postgres@host:~$ psql
psql (9.5.7)
Type "help" for help.

postgres=# CREATE DATABASE kanboard with owner kanboard;
CREATE DATABASE
postgres=# GRANT ALL PRIVILEGES  ON DATABASE kanboard TO kanboard;
GRANT

postgres@host:/var/www/kanboard$ psql -h localhost -U kanboard -d kanboard -a -f app/Schema/Sql/postgres.sql

**Comment by fguillot** [comment]
Looks like you solved your problem.
