### ISSUE TITLE
Translation: Texts with newlines after "e(" aren't found by "./cli locale:compare"

### ISSUE THREAD

**Issue by OHDMax** [kanboard/kanboard#3396]
### Actual behaviour

The command `./cli locale:compare` doesn't display the line `This task is now linked to the task %s with the relation "%s"` as `MISSING STRING` although it's not in the french translation. The line is from the file [task_internal_link_create_update.php](https://github.com/kanboard/kanboard/blob/dc7c7667ec2eb648ca097d00c25a00f7cc9a7d19/app/Template/notification/task_internal_link_create_update.php#L5).

### Expected behaviour

The line should be found when using `./cli locale:compare`.

### Steps to reproduce

1. Clone the project (tested with commit 066c9bf)
2. Switch to the directory containing the cloned project
3. Run `php composer update` to download dependencies
4. Execute `./cli locale:compare`

-> The line `This task is now linked to the task %s with the relation "%s"` doesn't appear in the output of the above command although it's not in the french translation

### Configuration

- Kanboard version: master (066c9bf)
- Database type and version: (not relevant)
- PHP version: 5.6.30 (from a xampp distribution)
- OS: Windows (using the commandline tools bundled with git-for-windows)
- Browser: (not relevant)

### Anaylsis

The culprit seems to be the newline after the the opening bracket from the `e` function. The regex `/\b[et]\((\'\K.*?\') *[\)\,]/` used in the [LocaleComparatorCommand.php](https://github.com/kanboard/kanboard/blob/066c9bf6e14cf2e6ec57d4bc7354aee38a08a944/app/Console/LocaleComparatorCommand.php#L66) doesn't expect one. 

A quick search with `grep -r -n -E '\b[et]/(&' app/` reveals other files where the translation could be missing because of this problem:
```
app/EventBuilder/TaskEventBuilder.php:154:                return e(
app/EventBuilder/TaskEventBuilder.php:161:                return e(
app/EventBuilder/TaskEventBuilder.php:173:                return e(
app/Template/event/task_internal_link_create_update.php:10:        <?= e(
app/Template/event/task_internal_link_delete.php:10:        <?= e(
app/Template/notification/task_internal_link_create_update.php:4:    <?= e(
app/Template/notification/task_internal_link_delete.php:4:    <?= e(
```

**Comment by fguillot** [comment]
This is now fixed in PR #3840.
