### ISSUE TITLE
[Question] Daily digest notifications plugin

### ISSUE THREAD

**Issue by krijnenr** [kanboard/kanboard#3397]
I like to send a daily digest email of new and modified tasks to the project manager. Similar to the overdue task notification.

I'm trying to figure out how to create a plugin to do this job.
Reading the documentation I think creating a custom console command would be the preferred way. With this custom command i can schedule the daily task using a cronjob.

However i did not figure out how to ad a custom command from within a plugin. 
Using "$this->cli->add(new MyCommand());" during initialization of a plugin does not seem to work.
I'm probably missing something. Does the plugin need to be based on a different class?

Any suggestion?

**Comment by fguillot** [comment]
- In the the method `initialize()` of `Plugin.php`, use something like `$this->cli->add(new MyCommand($this->container));`
- MyCommand class should extends from `Symfony\Component\Console\Command\Command`
- Take a look into other commands: https://github.com/kanboard/kanboard/tree/master/app/Console
