### ISSUE TITLE
Template question

### ISSUE THREAD

**Issue by izno** [kanboard/kanboard#3398]
Hi!

At the moment the header.php is used for all template pages!

What I want to achieve is to have a specific header only on the Dashboard page and use the template standard header.php for all other pages.

Question 1: Is it possible to render a specific header-tag ONLY for the dashboard?
Question 2: How can I check if the page is Dashboard page? ...and then load a specific template for that.

Thank you in advanced

**Comment by izno** [comment]
I've looked at the template hooks in the documentation:

```
$this->template->hook->attach('template:dashboard:layout', 'my_template:dashboard:layout', array(
    'my_dashboard_var' => 'my_val',
));

```
...but how can can I access the "my_val" in my template?

Any hint is very appreciated.

**Comment by Snajper88** [comment]
I'm pretty sure I got the same problem - I am working on a ticker, which should be working only on the dashboard, but instead its also working on the project-settings-page for example.

**Comment by fguillot** [comment]
You could override the default header template and check the name of the controller, take a look to the AppHelper class.
