### ISSUE TITLE
Display problem with selection box on popup window

### ISSUE THREAD

**Issue by alefaucheur** [kanboard/kanboard#3399]
### Actual behaviour
Tell us what happens
![image](https://user-images.githubusercontent.com/16562862/29513723-76a29c74-8666-11e7-81a1-4f92a86d6d71.png)

### Expected behaviour
Tell us what should actually happen
![image](https://user-images.githubusercontent.com/16562862/29513750-87529506-8666-11e7-99fe-e613f53fc925.png)

### Steps to reproduce
When I want to move a task to another project, at popup screen when i select the project name, the selection choice seems to be pushed at the top of the screen (see vertical scroll icon at the right) ... very annoying.

### Configuration
    Application version: 1.0.46
    PHP version: 7.1.1
    PHP SAPI: apache2handler
    OS version: Windows NT 6.1
    Database driver: mysql
    Database version: 10.1.21-MariaDB
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by fguillot** [comment]
This issue has been fixed in v1.1.0
