### ISSUE TITLE
Automatic action for start date

### ISSUE THREAD

**Issue by fkaag** [kanboard/kanboard#3400]
This application is great, but the behavior of the automatic action to set the start date when moving a task to a given column did not fit my need.

Since I wanted to track the actual time spent on a task, I shifted it from Pending to Ongoing, then possibly several times back and forth between Ongoing and Suspended. With the existing automatic action, the start date was reset each time I entered Ongoing again.

I made a slight modification to set the start date only if it was not set yet. The resulting plugin is attached for whoever might need it.

[InitStartTime.zip](https://github.com/kanboard/kanboard/files/1239590/InitStartTime.zip)

**Comment by fguillot** [comment]
You should put the source code of your plugin into a Github repository. That will allow people to improve what you did.
