### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by anandlinast** [kanboard/kanboard#3402]
Warning: require(C:\xampp\htdocs\kanboard-master\app/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\kanboard-master\app\common.php on line 3

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\kanboard-master\app/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\kanboard-master\app\common.php on line 3

**Comment by Snajper88** [comment]
Do not load the master at github.
Download here instead:
https://kanboard.net/downloads

**Comment by anandlinast** [comment]
thank you so much
