### ISSUE TITLE
Please add possibility to edit task directly on task view

### ISSUE THREAD

**Issue by simosuu** [kanboard/kanboard#3403]
Please make the fields editable as default. I do not see any reason why is needed to hit separate button to edit fields?

![image](https://user-images.githubusercontent.com/23297584/29563542-ba7b7a84-8746-11e7-974b-01be41b5f214.png)

Please.

**Comment by anandlinast** [comment]
hey can you help me about these 2 error what should i do for i have simply downloaded source file and running on the localhost and geeting this error please help me or send that autoload.php file and tell me where it to be placed 
thank you in advance .
 
Warning: require(C:\xampp\htdocs\kanboard-1.0.46\app/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\kanboard-1.0.46\app\common.php on line 3

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\kanboard-1.0.46\app/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\kanboard-1.0.46\app\common.php on line 3

**Comment by simppa69** [comment]
No I don't sorry.

---
Best regards,
Simo 

On 2017-08-22 15:48, anandlinast wrote:

> hey can you help me about these 2 error what should i do for i have simply downloaded source file and running on the localhost and geeting this error please help me or send that autoload.php file and tell me where it to be placed
> thank you in advance . 
> 
> Warning: require(C:\xampp\htdocs\kanboard-1.0.46\app/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\kanboard-1.0.46\app\common.php on line 3 
> 
> Fatal error: require(): Failed opening required 'C:\xampp\htdocs\kanboard-1.0.46\app/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\kanboard-1.0.46\app\common.php on line 3 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/kanboard/kanboard/issues/3403#issuecomment-324015468
[2]

**Comment by anandlinast** [comment]
Don't say sorry 
then how do you run the KB project on your system and asking for changes 
see the link:
![image](https://user-images.githubusercontent.com/31241271/29613266-e7bdf990-8822-11e7-8f91-b3c0d5ec9db7.png)

What i have did simply download the source code and running on localhost XAMPP server and getting error 
if you tell me how you run project of KB it will help me too.

so i will request you please let me know 

thank you
anand

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
