### ISSUE TITLE
Campsite CSS-only theme for Kanboard

### ISSUE THREAD

**Issue by synergico** [kanboard/kanboard#3405]
Hi,
I created a CSS-only theme that based on Basecamp theme. I was inspired by their simplistic and card-based design, not minimalism. 

Also, I was kind of frustrating with the UX and UI of the default theme. 
So here it is on Github, feel free to modify:[ Campsite Theme ](https://github.com/synergico/campsite-for-kanboard/)

Screenshot:
![synergico ss](https://github.com/synergico/campsite-for-kanboard/blob/master/1.png)

**Comment by fguillot** [comment]
nice
