### ISSUE TITLE
feature request - Auto Actions for adding Tags / Reference

### ISSUE THREAD

**Issue by mehdiyahyaoui** [kanboard/kanboard#3406]
Hi 

I would like to kindly request a new feature implementation which from my point of view would be very useful

- Is it possible to add automatic actions for adding a specific tag / Reference when an action is created/moved in specific column / swimlane

**Comment by regenduft** [comment]
+1, I need to have tags (or subtasks) beeing present whenever a task is created.

**Comment by fguillot** [comment]
You guys could easily create a plugin if you really need this feature.

This software should stay simple. The goal is not to add one billion of features to satisfy all possible use cases.
