### ISSUE TITLE
feature request - importing auto Actions (Replace all or add missing)

### ISSUE THREAD

**Issue by mehdiyahyaoui** [kanboard/kanboard#3407]
Hi

I would like to kindly request a new feature implementation which from my point of view would be very useful

- Is it possible when you import automated actions from another project to have a prompt choice for Adding missing (add all imported) or Replacing all (delete existants and replace with imported)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
