### ISSUE TITLE
New install, creating task shows my website index page

### ISSUE THREAD

**Issue by JolinM** [kanboard/kanboard#3408]
### Actual behaviour
Installation seams to be working all right
I’ve been able to change my account settings and create a new project.
But creating a new task shows my website (I’m running Kirby CMS 2).
[A screenshot](http://imgur.com/a/Ied1O)

### Expected behaviour
To be able to create a new task :)

### Steps to reproduce
Please supply step-by-step instructions so that anyone with the same environment can reproduce the issue. Whenever you offer a description, imagine
yourself in the shoes of someone who has never encountered this problem before and would like to know exactly how to observe it under a given set of conditions.
Here is an example:

1. go to [http://jolinmasson.com/kanboard/](http://jolinmasson.com/kanboard/)
2. use login **test** and password **testtest**
3. Go in Board view of project **test**
4. Try creating a new task

### Configuration
- Kanboard version: 1.0.45
- Database type and version: default one?
- PHP version: 5.5.57-MariaDB
- OS:Mac OS 10.12.6
- Browser: Safari 10.1.2

**Comment by fguillot** [comment]
Unfortunately this issue seems to be related to the configuration of your web server, not Kanboard.
