### ISSUE TITLE
Dies when opening subtasked task

### ISSUE THREAD

**Issue by tkteun** [kanboard/kanboard#3409]
### Actual behaviour

Whenever a task has subtasks, selecting it will make the page unresponsive. It will load up to the point where it should list the subtasks and stops. Can be seen in the screen shot below.

![screenshot from 2017-08-24 18-49-13](https://user-images.githubusercontent.com/720395/29678158-cf9d64d2-88fd-11e7-92c8-bf40600d60a2.png)

### Expected behaviour

It should show the page.

### Steps to reproduce

This probably came about when migrating from sqlite to mysql (which I had to do by hand because the tool kept dying). 

### Configuration

- Kanboard version: git
- Database type and version: 10.0.32-MariaDB-0+deb8u1 (Debian)
> Current version: 124
> Last version: 124
- PHP version: PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
- OS: Jessie with backports
- Browser: Vivaldi

There's no error message in either nginx or php-fpm, also in the debug log below, I don't see a sign that anything went wrong.

Can someone please clarify this?

> [2017-08-24 18:59:34] [debug] Kanboard\Core\Controller\Runner::executeMiddleware
> [2017-08-24 18:59:34] [debug] Subscriber executed: Kanboard\Subscriber\BootstrapSubscriber::execute
> [2017-08-24 18:59:34] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\AuthenticationMiddleware
> [2017-08-24 18:59:34] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\PostAuthenticationMiddleware
> [2017-08-24 18:59:34] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\ApplicationAuthorizationMiddleware
> [2017-08-24 18:59:34] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\ProjectAuthorizationMiddleware
> [2017-08-24 18:59:34] [debug] Kanboard\Core\Controller\Runner::executeController => \Kanboard\Controller\BoardAjaxController::check
> [2017-08-24 18:59:34] [debug] SQL: SELECT `version` FROM `plugin_schema_versions`   WHERE `plugin` = ?    LIMIT 1
> [2017-08-24 18:59:34] [debug] SQL: query_duration=0.00024199485778809
> [2017-08-24 18:59:34] [debug] SQL: total_execution_time=0.00024199485778809
> [2017-08-24 18:59:34] [debug] SQL: SELECT `version` FROM `plugin_schema_versions`   WHERE `plugin` = ?    LIMIT 1
> [2017-08-24 18:59:34] [debug] SQL: query_duration=0.00013613700866699
> [2017-08-24 18:59:34] [debug] SQL: total_execution_time=0.00037813186645508
> [2017-08-24 18:59:34] [debug] SQL: SELECT `version` FROM `plugin_schema_versions`   WHERE `plugin` = ?    LIMIT 1
> [2017-08-24 18:59:34] [debug] SQL: query_duration=0.00013589859008789
> [2017-08-24 18:59:34] [debug] SQL: total_execution_time=0.00051403045654297
> [2017-08-24 18:59:34] [debug] SQL: SELECT projects.id, projects.name FROM `projects` LEFT JOIN `project_has_users` ON `project_has_users`.`project_id`=`projects`.`id`  WHERE (project_has_users.user_id = ? OR projects.is_everybody_allowed = ?) AND projects.is_active IN (?)
> [2017-08-24 18:59:34] [debug] SQL: query_duration=5.9843063354492E-5
> [2017-08-24 18:59:34] [debug] SQL: total_execution_time=0.00057387351989746
> [2017-08-24 18:59:34] [debug] SQL: SELECT projects.id, projects.name FROM `projects` LEFT JOIN `project_has_groups` ON `project_has_groups`.`project_id`=`projects`.`id` LEFT JOIN `group_has_users` ON `group_has_users`.`group_id`=`project_has_groups`.`group_id`  WHERE group_has_users.user_id = ? AND projects.is_active IN (?)
> [2017-08-24 18:59:34] [debug] SQL: query_duration=5.4836273193359E-5
> [2017-08-24 18:59:34] [debug] SQL: total_execution_time=0.00062870979309082
> [2017-08-24 18:59:34] [debug] SQL: SELECT * FROM `actions`   WHERE `project_id` IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
> [2017-08-24 18:59:34] [debug] SQL: query_duration=6.6995620727539E-5
> [2017-08-24 18:59:34] [debug] SQL: total_execution_time=0.00069570541381836
> [2017-08-24 18:59:34] [debug] SQL: SELECT * FROM `action_has_params`
> [2017-08-24 18:59:34] [debug] SQL: query_duration=4.6014785766602E-5
> [2017-08-24 18:59:34] [debug] SQL: total_execution_time=0.00074172019958496
> [2017-08-24 18:59:34] [debug] SQL: SELECT `option`, `value` FROM `settings`
> [2017-08-24 18:59:34] [debug] SQL: query_duration=4.887580871582E-5
> [2017-08-24 18:59:34] [debug] SQL: total_execution_time=0.00079059600830078
> [2017-08-24 18:59:34] [debug] SQL: SELECT 1 FROM `users`  WHERE `id` = ? AND `is_active` = ?
> [2017-08-24 18:59:34] [debug] SQL: query_duration=5.1975250244141E-5
> [2017-08-24 18:59:34] [debug] SQL: total_execution_time=0.00084257125854492
> [2017-08-24 18:59:34] [debug] SQL: SELECT COUNT(*) FROM `projects`  WHERE `id` = ? AND `last_modified` > ?
> [2017-08-24 18:59:34] [debug] SQL: query_duration=5.1021575927734E-5
> [2017-08-24 18:59:34] [debug] SQL: total_execution_time=0.00089359283447266
> [2017-08-24 18:59:34] [debug] APP: nb_queries=10
> [2017-08-24 18:59:34] [debug] APP: rendering_time=0.034435987472534
> [2017-08-24 18:59:34] [debug] APP: memory_usage=3.1M
> [2017-08-24 18:59:34] [debug] APP: uri=/?controller=BoardAjaxController&action=check&project_id=26&timestamp=1503585404&_=1503585405422
> [2017-08-24 18:59:34] [debug] ###############################################

**Comment by fguillot** [comment]
You should check if you have a plugin that is not compatible with your kanboard version. Try to unable the error reporting of PHP and watch logs.

**Comment by fguillot** [comment]
Closing stale issue.
