### ISSUE TITLE
feature request - Tag user 

### ISSUE THREAD

**Issue by mehdiyahyaoui** [kanboard/kanboard#3410]
Hello

Is it possible to implement this

![image](https://user-images.githubusercontent.com/23338414/29706910-52758678-897b-11e7-8f47-e9d9bac16e3b.png)

When Tagging a user in a Comment / Message / Description - the typing should sherch for the user real name (full name) instead of the user login ID

This would be a useful feature when using Active directory to sync users

Regards

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
