### ISSUE TITLE
Broken Link – Mark all notifications modal

### ISSUE THREAD

**Issue by izno** [kanboard/kanboard#3411]
Hello all,

I've just tested a fresh install 1.0.46 and web notification checker for Unchecking all notifications "Mark all as read" opens a blank page.

### Actual behaviour

It opens a blank page with the notes:

> **My notifications**
> 
>  No notification.

(see attached image)

### Expected behaviour

Just uncheck the option.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/968204/29710148-74a8a388-898f-11e7-8acb-4e654d6bb7d8.png)

![image](https://user-images.githubusercontent.com/968204/29710185-93cf1756-898f-11e7-8059-208efec0e802.png)

### Configuration

- Application version: 1.0.46
- PHP version: 7.1.6
- PHP SAPI: apache2handler
- OS version: Darwin 14.5.0
- Database driver: sqlite
- Database version: 3.15.1
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**Comment by izno** [comment]
...just a clarification:

The link it selt is working fine to clear the "web-notifications", but trying to unchech the check-box will open the blank page and clear/markes everything on th list as read.

– The green part: OK
– The red part: Opens the blank page

![image](https://user-images.githubusercontent.com/968204/29870569-8862acdc-8d88-11e7-9854-376585a11c3c.png)

**Comment by fguillot** [comment]
This is now fixed in the development branch. Thanks.
