### ISSUE TITLE
Feature Request: Edit standard behaviour on task click

### ISSUE THREAD

**Issue by minthemiddle** [kanboard/kanboard#3412]
### Actual behaviour

When I click on a task title, I get to the "overview" screen where I can just see some details on the task and cannot edit anything.

### Expected behaviour

In 95% of cases, when I click on a task, I want to edit it in some way (change something, add a comment, etc.). Right now I need 2 clicks for that and the "overview" screen does not add any value to me.

Please make it possible to change the behaviour of clicking on a task and direct it to the "edit" screen, for example.

P.S. I know that I can click on the button on the top left and edit from there.

**Comment by jacekrszewczyk** [comment]
+1

**Comment by jacekrszewczyk** [comment]
https://github.com/kanboard/kanboard/pull/3344/files

**Comment by fguillot** [comment]
PR #3344 has been merged.
