### ISSUE TITLE
How to remove standard filter "status:open"?

### ISSUE THREAD

**Issue by minthemiddle** [kanboard/kanboard#3413]
### Actual behaviour

On all project views, the filter `status:open` is set automatically. I have to manually remove it to see my closed tasks.

### Expected behaviour

I would expect to set the default view filter somewhere instead having to manually remove a default one that does not suit my workflow. I prefer to see my closed tasks so I can visually get how much work I finished on a given day.

**Comment by El-Gavy** [comment]
I agree with that, i have the same need.
Working as a team, i want my coworkers to be able to see finished tasks without having to explain them how to manually remove the filter each time they connect.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
