### ISSUE TITLE
deactivate notification for tasks in a specific column

### ISSUE THREAD

**Issue by trendchiller** [kanboard/kanboard#3418]
I am wondering if it is possible to deactivate notifications for tasks in a specific column.
In this case it's possible to have completed tasks left in a column (not close the task).
So it's completed. Notifications are obsolete then.
Is there any possibility or it stis a new feature request ?

**Comment by wucherpfennig** [comment]
I support this! see #3429

**Comment by fguillot** [comment]
Closing duplicate.
