### ISSUE TITLE
Issue with PHP includes.

### ISSUE THREAD

**Issue by ankitp4** [kanboard/kanboard#3419]
I'm getting the error when navigating to the settings page:

Warning: include(C:\Inetpub\vhosts\sprint.example.com\httpdocs\app\Core\..\Template\config/layout.php): failed to open stream: No such file or directory in C:\Inetpub\vhosts\sprint.example.com\httpdocs\app\Core\Template.php on line 83

Warning: include(): Failed opening 'C:\Inetpub\vhosts\sprint.example.com\httpdocs\app\Core\..\Template\config/layout.php' for inclusion (include_path='.') in C:\Inetpub\vhosts\sprint.example.com\httpdocs\app\Core\Template.php on line 83

**Comment by fguillot** [comment]
You should make sure that all files are copied (follow the documentation on the website).
