### ISSUE TITLE
Guidance on troubleshooting LDAP and AD authentication in logs

### ISSUE THREAD

**Issue by the1poet** [kanboard/kanboard#3420]
### Actual behaviour
Lost where to find feedback in logs when LDAP and/or AD authentication is not working correctly.

### Expected behaviour
Would like to know where to look (i.e. logs) to see if my config file is set up correctly. 

### Steps to reproduce
N/A

### Configuration
Here's the relevant fields from the config file if it helps:
```
define('LDAP_AUTH', true);
define('LDAP_SERVER', 'authserver');
define('LDAP_PORT', 389);
define('LDAP_BIND_TYPE', 'proxy');
define('LDAP_USERNAME', 'CN=admin,CN=Users,DC=organisation,DC=com');
define('LDAP_PASSWORD', 'password');
define('LDAP_USER_BASE_DN', 'OU=Staff,OU=Users,DC=organisation,DC=com');
define('LDAP_USER_FILTER', '(&(objectClass=user)(sAMAccountName=%s)');
define('LDAP_GROUP_ADMIN_DN', 'CN=IT&C,OU=Security Groups,OU=Groups,DC=organisation,DC=com');
define('LDAP_GROUP_MANAGER_DN', '');
define('LDAP_GROUP_USER_FILTER', '(&(objectClass=groupOfNames)(sAMAccountName=%s,OU=Staff,OU=Users,DC=organisation,DC=com))');
define('LDAP_GROUP_PROVIDER', true);
define('LDAP_GROUP_BASE_DN', 'OU=Staff,OU=Users,DC=organisation,DC=com');
define('LDAP_GROUP_FILTER', '(&(objectClass=group)(sAMAccountName=%s*))');
define('LDAP_GROUP_ATTRIBUTE_NAME', 'cn');
```

the config file is located:
`C:\Apache24\htdocs`

I've tried checking the logs in:
`C:\Apache24\logs`
but have not found any useful information

- Kanboard version: 1.0.45
- Database type and version: sqlite, 3.15.1
- PHP version: 7.1.6
- OS: Windows NT 10.0
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
