### ISSUE TITLE
start_date starts after due_date

### ISSUE THREAD

**Issue by anleg** [kanboard/kanboard#3421]
Hello,

I've just notice that the start date can start after the due date.
I think an error must be throws because it makes no sense.

This bug has been tested on version 1.0.45 and 1.0.46.

Thank you all

![due_date_start_date](https://user-images.githubusercontent.com/6976793/29811742-ce502e48-8ca4-11e7-92a2-413eda045fbb.png)

**Comment by fguillot** [comment]
A check has been added into the form. But that could happen if someone click on the button "Set start date".
