### ISSUE TITLE
Unable to Login since PHP Version 5.6.31 update

### ISSUE THREAD

**Issue by peejaygee** [kanboard/kanboard#3422]
**Please, do not create duplicate issues**

Tried not too, but all solutions listed don't help me fix my issue. Been over the original install 'config' setup and made sure the php.ini hasn't changed after update/upgrade, wasn't able to login at first, so realized there was an Aug 13th update, so I downloaded and back'd up, copied data over to new folder, uploaded to my server, make sure all permissions were set correct, same error. These errors only happened since I updated PHP, but I don't know what else to look at? any other checks? I tried turning debug on, but I didn't get any additional output nor any files extra to examine, so I'm turning here now for guidance.

### Actual behaviour

Unable to Login, keeps asking me for username and password saying "The username is required" & "The password is required"

### Expected behavior

Able to Login

### Steps to reproduce
go to https://management.[myurlwithNOunderscoresinname].com/
try to login
get error, unable to pass it, and unable to login

### Configuration

- Kanboard version: Kanboard 1.0.46 (Aug 13th)
- Database type and version: mysql  Ver 14.14 Distrib 5.5.45, for Linux (x86_64) using readline 5.1
- PHP version:PHP Version 5.6.31
- OS Installed on : CentOS release 6.9 (Final)
- OS Using on: Windows 8 & Windows 10
- Browser: All I've tried, WaterFox, Edge, IE, Chrome, Firefox

**Comment by peejaygee** [comment]
So I've come home from work, my laptop still has a session cookie, so it still has me logged in, but I can't do anything with it, I can make any changes, I can't create a new user, etc

it's as if anything I put in any form box, once typed goes into a 'ghosted' format and then  the 'submit/save' button, doesn't knows it's there, and then Kanban is telling me I need to put something in the box?

**Comment by xevilstar** [comment]
no issues with php 7.1 fresh debian install

**Comment by peejaygee** [comment]
I fixed the issue, it was the permission issues in /var/lib/php, when PHP upgraded the owner changed, so the session was getting a 'denied', changed the owners back, and was able to login.
