### ISSUE TITLE
zimbra integration

### ISSUE THREAD

**Issue by xevilstar** [kanboard/kanboard#3424]
I'd like it to be possible to receive the zimbra chat messages in kanboard and vice versa. Also I'd like it to be possible to integrate zimbra mail in kanboard. Could you please add a form where I could for example insert my zimbra server data and have it done ? 

thanks

**Comment by fguillot** [comment]
Unfortunately, there is no plan to integrate Zimbra into Kanboard. If you need this feature, you could create your own plugin.
