### ISSUE TITLE
Feature request : when creating new task from subtask, have the possibility to set all task parameters.

### ISSUE THREAD

**Issue by Miroslav36** [kanboard/kanboard#3430]
### Actual behaviour

When creating a task from a subtask, the new task is automatically created without the possibility to assign the proper parameters : category, tag, swimlane, ...
It is currently necessary to search for the newly created task in order to update the parameters .

### Expected behaviour

Feature request : have the possibility to set all parameters (category, tag, swimlane, ...) immediatly.
Proposed workflow : 
when clicking on "create a task" (from the subtask) prompt the same window prompted when you click on the standard "create a new task" button (when you directly create a task, not from a subtask).
Ideally, the parameters prompted in this window could be inherited from the task it came from.

This feature can save some time and simplify the process of managing tasks created from subtasks.

### Configuration

I am currently on version 1.0.43

Thank you,
Miroslav

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
