### ISSUE TITLE
Relate the duplicate task to the original when creating the duplicate

### ISSUE THREAD

**Issue by gideoni** [kanboard/kanboard#3432]
**### Actual behaviour**
I can duplicate a task.

**### Expected behaviour**
I want to relate the duplicate task to the original task.
I suggest that a pop-up be opened for the choice of relationship.

**### Steps to reproduce**
1) Open the task.
2) Click the "Duplicate" link, then on the modal dialog that appears.
3) Choose relinking with the original task.
4) Confirm the action.
5) Ready, duplicate task.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
