### ISSUE TITLE
Feature Request : Calculated number in title and column

### ISSUE THREAD

**Issue by DocSmirc** [kanboard/kanboard#3433]
We looking for a way to 
a.) add a number in the task
b.) sum up this numbers from all tasks and show this in the column.

e.g. : The task show me a project and the number is the income of this project. Also I add the income 10.000€ to the first task and in the second task I have a income of 5.000€.
The column show me now 15.000€ as sum of both task.

e.g.: This plugin from Chrome can do this for Trello in a easy way, but I don't want use Trello. 
https://chrome.google.com/webstore/detail/scrum-for-trello/jdbcdblgjdpmfninkoogcfpnkjmndgje

We are ready to pay for the implementation.

**Comment by fguillot** [comment]
Some people use the complexity field for that.

**Comment by DocSmirc** [comment]
you are my hero!
thanx
