### ISSUE TITLE
Feature Request: Keep task sort order when creating a new project from existing one

### ISSUE THREAD

**Issue by wucherpfennig** [kanboard/kanboard#3434]
Hi everybody

We are heavily relying on the duplicate project function for standardized projects. Therefore we created several "template" projects an duplicate them for each new project.

Currently when you duplicate a project all tasks will be sorted by their task ID which is not an optimal solution since it happens quite often (especially with new project templates) that you add some new tasks to the template since you forgot something.  
In the template you are able to sort them according to your needs but after you duplicated it the sorting will be lost.

Is there a possibility to keep the task sort order according to the "parent" project?

Any feedback appreciated

Best regards 

wucherpfennig

**Comment by fguillot** [comment]
Duplicate with #3175
