### ISSUE TITLE
EXPORT PDF

### ISSUE THREAD

**Issue by Richard76000** [kanboard/kanboard#3435]
Hey,

It is very important to export PDF GANTT! When this feature will be present ??

Thanks !!

**Comment by wucherpfennig** [comment]
nobody understands this request? could you please be more specific?

**Comment by Richard76000** [comment]
EXPORT PDF GANTT --> function = WHEN ???

**Comment by Royalxm** [comment]
Hello,
Stop maj.
This is an open-source creator can't be everywhere. But as I said it's an open-source solution you can develop a solution and share it. Otherwise good point to study

**Comment by Richard76000** [comment]
it is really damaging that the updates are stopped. It really lacks this function of being able to export in pdf the diagram of GANTT

**Comment by Snajper88** [comment]
wrong place, dude. And stop being so ungrateful.
This is the right place to ask about a pdf export in the gantt plugin:
https://github.com/kanboard/plugin-gantt/issues

**Comment by cose385** [comment]
Dear @Richard76000,

like many others - Kanboard is open source project built by contribution of volunteers. You didn't pay for the privilege of using it and you can't demand everything from anyone here. Your suggestion is just that - a suggestion, nothing more.

You can, however, join in as a volunteer and add missing functionality. If you are not the programmer or don't have time "waste" on this project - than you can, at least, be fair enough and acknowledge others who contributed.

Or maybe the best thing of all both to fill your need and contribute to Kanboard - pay someone on Upwork (or similar site) who can program needed functionality and then donate result to this project.
