### ISSUE TITLE
sso login and user name creation issues.

### ISSUE THREAD

**Issue by marscoe** [kanboard/kanboard#3436]
### Actual behaviour

Our Service Provider has set up a kanboard instance with remote user auth using a saml sso login connected to our LDAP.

1) Login in works, but there is no button to log out in this configuration. 
In effect if you are once logged in, you can log out at the sso service and keep logged in at kanboard, even if an other user logs in via sso. You need to close the browser window to loose login.

2) kanboard creates internal accounts for each login, but the internal accounts are case sensitive whereas the logins are not. In our system user.name ist the same as User.Name. kanboard creates two accounts, which it should not.

### Expected behaviour

1) There should be a logout button which destroys the login session from remote user.

2) The User names created by kanboard should be case insensitive.

### Steps to reproduce

1) Login using the remote user service an logout directly thereafter. Try to make changes to kanboard tasks. It works where it should not.

2) Login via a remote user service which delivers the user names and use the same user name once with and once without capital letters. Two different users are created where there should be only one.

### Configuration

    Version: 1.0.43
    PHP Version: 7.0.19-1~dotdeb+8.1
    PHP SAPI: apache2handler
    OS Version: Linux 3.16.0-4-amd64
    Datenbanktreiber: sqlite
    Datenbank Version: 3.9.2
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

**Comment by fguillot** [comment]
1. There is already a logout button in Kanboard, perhaps it's disabled by your service provider.
2. There is feature request for case insensitive username: #2444
