### ISSUE TITLE
Upload file path value when migrating from Windows to Linux server.

### ISSUE THREAD

**Issue by devBartek** [kanboard/kanboard#3441]
### Actual behaviour

After migration from Windows to Linux server old avatars and old attachments doesn't work. 
There is no thumbnails and after download file it's size is 0 KB.
For new uploaded avatars and files everything is ok.

### Expected behaviour

I'd like to have easy and working migration from Windows to Linux server.

### Workaround

I notice that in db.sqlite on Windows server in table 'users' 'avatar_path' field look like:
avatars\2\c27880ah098ha98ha9h89ha08h
on Linux (after upload new avatar):
avatars/2/c27880ah098ha98ha9h89ha08h

I fix this problem for old files by query in db.sqlite:
BEGIN
    UPDATE task_has_files SET path = replace( path, '\\', '/' );
    UPDATE users SET avatar_path = replace( avatar_path, '\\', '/' );
COMMIT; 

### Configuration

Application version: 1.0.43
PHP version: 5.5.9-1ubuntu4.22
PHP SAPI: apache2handler
OS version: Linux 4.4.0-31-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by fguillot** [comment]
I don't plan to write any migration script from Windows to Linux. However, you could contribute to the documentation if you would like.
