### ISSUE TITLE
Feature Request : Action Send a task by email to task creator

### ISSUE THREAD

**Issue by lpequignot** [kanboard/kanboard#3442]
**Actual behaviour**
Action name = Send a task by email to someone
Event name = Move a task to another column
User that will receive the email = Unassigned/User

**Expected behaviour**
User that will receive the email = Task creator

**Comment by lpequignot** [comment]
Sorry, I just saw #3363 [https://github.com/kanboard/kanboard/issues/3363](url),
I am really interested in this improvement
Regards,

**Comment by creecros** [comment]
Try this:
https://github.com/creecros/SendTaskCreator

**Comment by lpequignot** [comment]
Hi, I'll try it, Thanks !
Cheers,

**Comment by creecros** [comment]
After seeing #3363, I also added an action to send to assignee as well. So, both features are included. Let me know though, haven't tested.

**Comment by lpequignot** [comment]
Hi, 
Works fine ! Thanks :)
louise

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
