### ISSUE TITLE
Images not showing after upgrading Kanboard into new folder 

### ISSUE THREAD

**Issue by thetrad9** [kanboard/kanboard#3443]
### Actual behaviour
Images attached to tasks are loading as blank images. 

### Expected behaviour
 I should see the image that was there before from my previous installation of Kanboard.  

### Steps to reproduce
Installed new instance of updated version of Kanboard into a folder called "v2" using ftp on the same server as my previous version. I then replaced the data folder of  version 1.0.46(new version) with data folder from my previous version of Kanboard v1.0.36.  

Everything else works fine.  Uploading new image previews show properly, the 'add a screenshot' & 'attach a document' functions work fine also.  
 
However, all the old images preview & just show up as blank when you click on them(image IDs like 735204bad47928e8b96ae28083b2d37437ef7a40 are there, in the right paths)

This is similar issue to "Images not loading after transfer #3339"
however there has been no response to that issue.  

Thanks for the help.

### Configuration
- Kanboard version:1.0.46
- Database driver: sqlite
- Database version: 3.6.20
- PHP version:5.6.31
- OS:Linux 3.10.0-614.10.2.lve1.4.50.el6h.x86_64
- Browser:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by tutle** [comment]
I have a very similar problem, impossible to see uploaded picture #3426 Very embarrassed and no response also...

**Comment by thetrad9** [comment]
Anyone had any luck yet?  Still no solution in sight here. 
Strange that so far only 3 users have reported this issue. 
Surely there must be more insidents?

**Comment by tutle** [comment]
Youpee, I've desactivated extension coverimage and the pictures are back !!!!

**Comment by thetrad9** [comment]
Hey tutle, 
Glad to hear ur problem is solved.  I've never had the 'coverimage' plugin installed before so I tried installing it and tested but no still the problem persists for me.  I also uninstalled the 'coverimage ' plugin & tested again but got the same result.  
:(

**Comment by devBartek** [comment]
Could you check how patch value looks in database? I have similar problem after migration. I descibed my problem in #3441.

**Comment by fguillot** [comment]
You should check that the path in the database is the same as the path on the disk.
