### ISSUE TITLE
Notifications for overdue tasks

### ISSUE THREAD

**Issue by diegospano** [kanboard/kanboard#3444]
Hi. I have a doubt about the notifications for overdue tasks. The email is sent only to the user that has the task assigned?. I mean, Task-A is assigned to User-A and Task-B is assigned to User-B. Each user will receive only one email mentioning his task or both users will receive an email mentioning that two tasks reach the due date?.

Thanks
Diego

**Comment by fguillot** [comment]
You already asked the same question here #3384
