### ISSUE TITLE
Requirements for 1.0.46 should mention Apache mod_version

### ISSUE THREAD

**Issue by olberger** [kanboard/kanboard#3445]
The .htaccess in app/ and data/ refer to IfVersion directive, which is provided by mod_version AFAIU.

Whenever the Apache server lacks mod_version, the following will be reported:
```
Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration
```
This doesn't seem to hinder security AFAIU, but is suboptimal. Maybe protecting this by an IfModule version could help, but that may have other drawbacks. It is likely that most Apache configs do have mod_version ?

In any case, the requirements docs should mention mod_version explicitely.

Hope this helps,

**Comment by fguillot** [comment]
The provided `.htaccess` doesn't require anymore mod_version since a long time. Are you sure that your `.htaccess` is not coming from an older installation of Kanboard?

See https://github.com/kanboard/kanboard/blob/master/.htaccess

**Comment by olberger** [comment]
I wasn't referring to the top-level .htaccess but the one in app/ or data/ (https://github.com/kanboard/kanboard/blob/master/app/.htaccess for instance).

Hth,

**Comment by fguillot** [comment]
Indeed `mod_version` is required. The documentation has been updated. Thanks
