### ISSUE TITLE
[Feature request] Batch create sub-tasks from list

### ISSUE THREAD

**Issue by hugopeek** [kanboard/kanboard#3446]
### Actual behaviour

Currently, every new sub-task needs to be created individually. There is a "Create another sub-task" checkbox available to speed things up, but it still takes a while to enter a long list of sub-tasks.

This is especially annoying if you have a list with the sub-tasks already as text (from an email, or markdown note for example), because you have to copy/paste them one by one or retype them.

### Expected behaviour

It would be nice to have the option to copy/paste a list of sub-tasks in a textarea. Every new line would be turned into a separate sub-task.

It would be extra nice if any markdown bullets at the start of each line would be removed, but that's nice to have. 

As a side note: I got the idea from Trello. Was using it there quite often and now I slightly miss this behavior in Kanboard.. Not criticizing btw; Kanboard is magnificent!

### Example

Below is a quick visual example of how this could work in the current Add sub-task modal. Ticking the "Add multiple tasks" checkbox would change the textfield for a single task into a textarea.

![screenshot from 2017-09-14 11-35-02](https://user-images.githubusercontent.com/5436121/30411082-76b188f4-9941-11e7-960a-c4a9fbddd359.png)

If anyone has any pointers as to which files contain the code that would need to be edited, please do share. Maybe I'll have a crack at it when wanting to flex my (scrawny) PHP muscles again some day..

**Comment by fguillot** [comment]
This feature is already requested here: #2235
