### ISSUE TITLE
Enhancement interface suggestion list of user and who's online.

### ISSUE THREAD

**Issue by tutle** [kanboard/kanboard#3447]
Does anybody knows how it could be possible to see users online for chat session an more.
Also, I don't feel very confortable to add members on a project, something like a list (with check boxes) could be easyer ?
I'm not compétent enough in programming but a plugin could do the job, no ?

- Kanboard version:1.0.46
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited.

Thank you for your understanding

**Comment by tutle** [comment]
Thanks for your answer, this software is just perfect but this small enhancement (especially who is online for chat session) for collaboration could maybe be a plugin ?
