### ISSUE TITLE
Please put the Matrix plugin into kanboard namespace

### ISSUE THREAD

**Issue by andrewshadura** [kanboard/kanboard#3448]
Hi,

I'm aware this isn't a bug in Kanboard itself, but I've written a [notification plugin](/andrewshadura/kanboard-plugin-matrix) to integrate Kanboard with [Matrix.org](/matrix-org). As I'd like it to be officially part of the project, could you please fork it into `kanboard/` namespace (and add me afterwards) so that users are more likely be able to easily find it?

Thanks!

**Comment by m8e** [comment]
Nice one!  Matrixing is the wave of the future, it's growing fast

**Comment by fguillot** [comment]
I cannot fork your project because you already forked from kanboard/plugin-mattermost and Github doesn't seems to allow that.

**Comment by andrewshadura** [comment]
How about now?

**Comment by fguillot** [comment]
Have fun: https://github.com/kanboard/plugin-matrix
