### ISSUE TITLE
[Solved] Raspberry PI > Internal Error: PHP extension required: "pdo_sqlite"

### ISSUE THREAD

**Issue by christi9n** [kanboard/kanboard#3449]
Hi,

I've got the following error through my browser when I tried to connect to Kanboard:
_Internal Error: PHP extension required: "pdo_sqlite"_

Following comments on few forum I can't get through this problem ?!

RASPBERRY PI 3
RasBian 8
Apache 2
PHP 5.6

Christi9n

**Comment by rautamiekka** [comment]
Show which ones cuz I'm confident you're not installing the SQLite PDO driver correctly.

**Comment by christi9n** [comment]
Yes definitely but what should I do ?

**Comment by rautamiekka** [comment]
^ Normally you'd install whichever package the `php#-pdo-sqlite` virtual package [reverse-]provides (`apt-cache showpkg php#-pdo-sqlite` or `aptitude show php#-pdo-sqlite`), where `#` is your PHP version, like `7.2` in PHP 7.2's case. On Ubuntu 16.04.x LTS that'd be `php#-sqlite3`, meaning `php7.2-sqlite3` for PHP 7.2. If Apache doesn't auto-reload/reboot, reboot it.

**Comment by christi9n** [comment]
when I run: `apt-cache showpkg php5.6-sqlite3`
I've got:
`N: Unable to locate package php5.6-sqlite3
N: Couldn't find any package by regex 'php5.6-sqlite3'
`
and
`apt-cache showpkg php5.6-pdo-sqlite`
returns
`N: Unable to locate package php5.6-pdo-sqlite
N: Couldn't find any package by regex 'php5.6-pdo-sqlite'
`

**Comment by christi9n** [comment]
for info, I also add the following lines to my php.ini

`register_globals=Off
extension=pdo.so
extension=pdo_sqlite.so
extension=sqlite.so
extension=pdo_mysql.so`

**Comment by rautamiekka** [comment]
Try `apt-cache search '.*php.*sqlite.*'`. `aptitude` would be easier ...

**Comment by christi9n** [comment]
`apt-cache search '.*php.*sqlite.*'`

returns

`php-db - PHP PEAR Database Abstraction Layer

php5-sqlite - SQLite module for php5

refdb-server - Reference database and bibliography tool - sql server
`

**Comment by rautamiekka** [comment]
^ Judging by a bit of googling, SQLite2 ain't available for Pi, so that `php5-sqlite` should do it.

**Comment by christi9n** [comment]
so you mean ...?

**Comment by rautamiekka** [comment]
^ Try installing the `php5-sqlite` package, and if Apache doesn't auto-reload/reboot after the package installation, reboot it yourself.

**Comment by christi9n** [comment]
and now .... it's work !
Thanks for your help ;o)
