### ISSUE TITLE
Display "project management"

### ISSUE THREAD

**Issue by trendchiller** [kanboard/kanboard#3452]
**Please, do not create duplicate issues**

### Actual behaviour

Tell us what happens

When calling URI
_/kanboard/?controller=ProjectListController&action=show_
the output is unformatted and on the bottom of the page
_Internal Error: SQL error_
is displayed

debug mode reveals:
_[2017-09-18 11:23:38] [debug] SQL: SELECT projects.*, users.username AS owner_username, users.name AS owner_name FROM "projects" LEFT JOIN "users" ON "users"."id"="projects"."owner_id"  WHERE projects.id IN (?)   ORDER BY "name" ASC  LIMIT 20  OFFSET 0
[2017-09-18 11:23:38] [debug] SQL: SQLSTATE[HY000]: General error: 1 ambiguous column name: name_

SQLite library 3.4.1 is in use

### Expected behaviour

Tell us what should actually happen

It should be properly displayed.

### Steps to reproduce

Please supply step-by-step instructions so that anyone with the same environment can reproduce the issue. Whenever you offer a description, imagine
yourself in the shoes of someone who has never encountered this problem before and would like to know exactly how to observe it under a given set of conditions.
Here is an example:

1. Log in to the application as the administrative user
2. Click on button X, then on the modal dialog that appears, click Y
3. Wait for 3 seconds, and note the appearance of an unexpected message

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.46
- Database type and version: SQLite 3.4.1
- PHP version: 5.6.31
- OS: QTS 4.3.3
- Browser: Chrome / Firefox

**Comment by fguillot** [comment]
Do you have to possibility to upgrade to a more recent version of Sqlite?

**Comment by trendchiller** [comment]
Not really - it's a QNAP (embedded system).
I'll try to open a ticket with them for this.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"unable to reproduce bug"**. If you think this is a mistake, open an issue with absolutely all the information required to reproduce the problem. You can also try to troublshoot the problem on your side and send a patch.
