### ISSUE TITLE
Automatic Actions not chaging color based on Category

### ISSUE THREAD

**Issue by dhornford** [kanboard/kanboard#3453]
### Actual behaviour

We have a set of Automatic actions that change a card's colour based on Category.
We have a template project that carries all these actions.
Creation or changing of Category doesn't change card colour

Previously this had happened when we used the API to create cards. Now it happens on hand created cards

We recently upgraded to 1.0.46. We were running whatever was current in Jan/Feb before the upgrade.

### Expected behaviour

Automatic Action functions and changes card color

### Steps to reproduce

Create Automatica Action
Assign automatically a color based on a category 
Select Colour
Select Category

Then create a card of this Category

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

    Application version: 1.0.46
    PHP version: 7.0.22
    PHP SAPI: apache2handler
    OS version: Linux 3.10.0-693.2.2.el7.x86_64
    Database driver: mysql
    Database version: 5.7.16-log
    Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0

**Comment by danielhrisca** [comment]
In our case for multiple tasks only the first task is colored.

**Comment by SchmilK** [comment]
I am experiencing the same thing on boards with and without swim lanes which previously had color changes working as recent as last week.

Production server is still al little behind on updates.

Application version: 1.0.46
PHP version: 5.4.16
PHP SAPI: apache2handler
OS version: Linux 3.10.0-514.26.1.el7.x86_64
Database driver: sqlite
Database version: 3.7.17
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36

**Comment by SchmilK** [comment]
**I believe I fixed my prod and dev.**
running this command
**sed 's/^\([^:]*\):.*$/crontab -u \1 -l 2>\&1/' /etc/passwd | grep -v "no crontab for" | sh**

The first line of return should be similar to this

Kanboard Management Tasks
0 8 * * * /var/www/html/kanboard/cron-tasks.sh 0

Take note there is a 0 at the end of the line.  Changing that to a 1, and refreshing my Kanboard page in browser, now my tasks change color in columns!

I don't know why that changed to a 0, we previously weren't using any scheduled tasks, but I got a request to send a weekly 'overdue tasks' email, which is when I found this.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"unable to reproduce bug"**. If you think this is a mistake, open an issue with absolutely all the information required to reproduce the problem. You can also try to troublshoot the problem on your side and send a patch.
