### ISSUE TITLE
Gantt & Calendar- page header displayed but no other information

### ISSUE THREAD

**Issue by chrisjhowe** [kanboard/kanboard#3454]
### Actual behaviour

I click on the Gantt chart link on the main board.
The Gantt page header displays but none of the tasks are visible

I click on the Calendar link.
The header is displayed but no dates or tasks.

### Expected behaviour

The pages should display bars showing dates and task durations.

### Steps to reproduce

The Gantt chart and Calendar worked OK up to Kanboard version 1.0.40, after this point they don't.
I have installed the Gantt and Calendar plugins.

The plugins I have are:
Incompatible Plugins
Milestone 	Olivier Maridat 	1.1.0 	1.0.43

Installed Plugins
Metadata 	BlueTeck + Daniele Lenares 	1.0.33.1
TimeTrackingEditor 	Thomas Stinner 	1.0.14
Budget Planning 	Frédéric Guillot 	1.0.9
Subtaskdate 	Manuel Raposo 	1.0.0
Calendar 	Frédéric Guillot 	1.0.1
TaskBoardDate 	Frédéric Guillot 	1.0.1
Gantt 	Frédéric Guillot 	1.0.2
Timetable 	Frédéric Guillot 	1.0.8
Subtask Forecast 	Frédéric Guillot 	1.0.2

### Configuration

    Application version: 1.0.46
    PHP version: 7.0.22-0ubuntu0.16.04.1
    PHP SAPI: apache2handler
    OS version: Linux 4.4.0-79-generic
    Database driver: sqlite
    Database version: 3.11.0
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

**Comment by chrisjhowe** [comment]
Further investigation:
Removed the db.sqlite file from the data directory and set the configuration to default.
Logged in as admin and it correctly created the database in the data directory.
Created two tasks neither show in the board view.
logged out of Kanboard
Added the Calendar and Gantt plugins.
Logged in again
Still no tasks in board view, both calendar and gantt views now work!

Tried using Internet explorer instead of Firefox.
The board, calendar and Gantt all work correctly.

Set the configuration back to what we normally use and the normal database file.
The board, the gantt and calendar plugins work in Firefox and IE.

Does letting Kanboard generate a db.sqlite file somehow change a setting within the software?

**Comment by fguillot** [comment]
I don't really understand what your are doing but start to remove incompatible plugins, watch logs on the server, the browser console and you will find out the source of the problem.

**Comment by chrisjhowe** [comment]
I eventually fixed the issue, not totally certain how but probably an incompatible plugin.
