### ISSUE TITLE
Add filter by score 

### ISSUE THREAD

**Issue by rafacamargo123** [kanboard/kanboard#3458]
**Please, do not create duplicate issues**

### Actual behaviour

Its not possible to search by score/complexity

### Expected behaviour

It would be very useful to search by score
score:<1 // score:>2 // score:0 // etc

### Steps to reproduce

N/A. It's a feature request

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.33
- Database type and version: mysql 5.7.9-log
- PHP version: 5.3.3
- OS: Linux 2.6.32-642.6.2.el6.x86_64
- Browser: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by fguillot** [comment]
This is now implemented in the development branch.
