### ISSUE TITLE
Background Job Scheduling on Synology

### ISSUE THREAD

**Issue by pcherkash** [kanboard/kanboard#3459]
on a synology NAS, where there is a graphical interface for this, what command should be entered in the "user defined script" ?

![1](https://user-images.githubusercontent.com/27211128/30662966-9f27f402-9e51-11e7-8afb-b5af3abd4df6.png)

cd /volume1/web/kanboard/ && ./cli cronjob >/dev/null 2>&1
don't work

Версия приложения: 1.0.46
Версия PHP: 7.0.16
PHP SAPI: fpm-fcgi
Версия ОС: Linux 3.10.102
Драйвер базы данных sqlite
Версия БД: 3.10.2
Браузер: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by szawadski** [comment]
See #3178 where I explain a similar problem with automatic tasks. @fguillot helped me to identify the rootcause but, unfortunately, I did not find the way to fix it on my Synology.
I remain interested if you find a fix in your case.

**Comment by bdouxx** [comment]
hi,

As explained in #3178 try :
> cd /volume1/web/kanboard/ && ph70 cli cronjob >/dev/null 2>&1
