### ISSUE TITLE
subtasks status not displayed 

### ISSUE THREAD

**Issue by juergenwinzer** [kanboard/kanboard#3462]
Hello,

I installed kanboard an our Server. Everything worked well.

But I have no chance to edit the status of a subtask. There is no icon displayed and when I do a mouseover there is only the option to move the subtask (here is also no Icon displayed).

When I click with the mouse close left to the name of the subtask a popup opens with "edit, Close, Change to Task".

What can I do to see the status of subtasks?

Jürgen

Version: 1.0.46 
◾ PHP Version: 5.6.31 
◾ PHP SAPI: cgi-fcgi 
◾ OS Version: Linux 4.9.44-040944-generic 
◾ Datenbanktreiber: sqlite 
◾ Datenbank Version: 3.8.10.2 
◾ Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

**Comment by fguillot** [comment]
You should take some screenshots because I don't really understand your problem.

**Comment by fguillot** [comment]
Closing stale issue.
