### ISSUE TITLE
Can not update existing Avatar

### ISSUE THREAD

**Issue by MontesaDave** [kanboard/kanboard#3463]
Hi all - hope this has not been reported already - I dont see anything similar to what Im seeing today. 
### Actual behavior

An avatar has been uploaded into our Kanboard and it is not appropriate for the business unit :(

Tell us what happens

The user has removed this avatar (with the "Remove my image" button) and Kanboard updates the board with the user initials (*as expected - so far so good). 

About 1 hr later - the user updates his avatar with a *completely different image* from the initial inappropriate image. He selects "Choose File" button and then selects the "Upload my avatar image".

The old inappropriate image shows up AGAIN ! (and the phone starts ringing AGAIN !)

### Expected behavior

The new avatar should replace the old avatar - and the original inappropriate image should be gone. 
*** Neither the user OR admin(myself) can update the avatar with a new image 

I have gone into the /var/www/html/kanboard/data/files/avatars/2 directory and removed the only file in there - this installation is fairly new and no one has setup avatars except for one person. I have also tried to remove the files directory structure - this has not helped.

### Steps to reproduce

try to update your avatar with a new picture. 

### Configuration

Application version: 1.0.46
PHP version: 7.0.22-0ubuntu0.16.04.1
PHP SAPI: apache2handler
OS version: Linux 4.4.0-96-generic
Database driver: sqlite
Database version: 3.11.0
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
Database
Database size: 225k

**Comment by MontesaDave** [comment]
update - i copied the data base into a new instance of kanboard on the same system (created a /var/www/html/Private ) directory and pointed my browser to it ... logged in as admin and restored the existing db into it... then I updated the users avatar with the new image ... that image is seen as expected.

I have then tried to update the avatar again ... and I can not do it (neither the user or admin can change the avatar).

although the process looks rather intuitive - - at this point im wondering if im doing something wrong

-Dave

**Comment by MontesaDave** [comment]
Admin cant not change two a 2nd avatar either - just tested this on another instance.  (created a /var/www/html/junk1)

**Comment by MontesaDave** [comment]
looks like my 2 image files for both admin and user #2 (I assume #1 is admin) ... are being populated correctly... the file sizes seem to look consistent between both accounts and the windows system which pushed them up to the kanboard server. 

root@kanboard:/var/www/html/junk1/data/files/avatars# ls -alF *
1:
total 28
drwxr-xr-x 2 www-data www-data  4096 Sep 21 13:03 ./
drwxr-xr-x 4 www-data www-data  4096 Sep 21 13:05 ../
-rw-r--r-- 1 www-data www-data  7459 Sep 21 13:02 5ee8d85a33965090023b4a9f29cbca9f3aa31ab0
-rw-r--r-- 1 www-data www-data 11084 Sep 21 13:03 9421ccf9433c024b51d9bec4aa3d3b0e8f97cb26

2:
total 28
drwxr-xr-x 2 www-data www-data  4096 Sep 21 13:06 ./
drwxr-xr-x 4 www-data www-data  4096 Sep 21 13:05 ../
-rw-r--r-- 1 www-data www-data 11084 Sep 21 13:05 19159d39308fc233f37c34b6a4b0b63c2939bd9e
-rw-r--r-- 1 www-data www-data  7459 Sep 21 13:06 954cfe2c6c316869d986826695636ce323c4ce8

**Comment by viki53** [comment]
From what I've experienced (I'm fairly new to this), the new avatar is uploaded with the same path and file name as the old one, so the browser cache is used.

There should be either batter cache control or a new file name.

**Comment by MontesaDave** [comment]
**RE: uploaded with the same path and file name as the old one...**
based on what I'm seeing (from the ls above) I see 2 very different avatar files in the same path (for every user that i experiment with).

I do agree - it seems that some type of cache refresh might be the issue. 
By the way - a reboot of the system does not seem to clear up the issue... 

Anyway I forgot to mention earlier - we really like the kanboard solution, keep up the great work.

-Dave

**Comment by esprit-libre** [comment]
Hello,
on fresh install, I also have the same problem. Any idea how to solve/workaround it?
More info needed to analyze?
Thx

**Comment by surebrec** [comment]
try to clear cache in Chrome, it helps to me

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
