### ISSUE TITLE
Date format should follow user language

### ISSUE THREAD

**Issue by viki53** [kanboard/kanboard#3464]
### Actual behaviour

The date format used is defined by the administrator, no matter the user's defined language

### Expected behaviour

The format should be defined accordingly to the user's wishes, not be the same for everyone and not defined by the admin (or, maybe, as a fallback).

### Steps to reproduce

Just look at any date with your personal language set to French (for example) and the date format set in the admin to the American format.

### Configuration

I'm not admin on our install, I don't have access to the config. Though it's pretty recent, so I guess it's up to date

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
