### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by sarvesh610** [kanboard/kanboard#3471]
### Actual behaviour

I have the latest version of Kanban and currently using SQLite. I have a lot of Backlog Tasks currently 900 and counting. 
The system is extremely slow to load all the tasks, and its take a very long time to move the tasks between columns. 

### Expected behaviour

System should perform much faster.

### Steps to reproduce

1. Login as admin user
2. Load 900 Backlog items 
3. Click on Board
4. Move the Tasks to Ready

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

Application version: 1.0.46
PHP version: 7.1.9
PHP SAPI: apache2handler
OS version: Windows NT 6.1
Database driver: sqlite
Database version: 3.15.1
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by eskaryo** [comment]
Would suggest you make sure you have the workers such as beanstalk configured and running as well as taking a look at converting to mysql- there is a script which will convert your sqlite db over to mysql and you should be on your way.

**Comment by tjharman** [comment]
You could also try (as a temporary fix, @eskaryo's is better) a SQLite vacuum

http://www.sqlitetutorial.net/sqlite-vacuum/

**Comment by fguillot** [comment]
- This software is not really made to have 900 tasks in a single column. I don't know how you can manage efficiently so many tasks...
- Did you read this page: https://kanboard.net/documentation/performances ?

**Comment by fguillot** [comment]
No answer, closing stale issue.
