### ISSUE TITLE
[FEATURE REQUEST] Make public access with edit rights, not only read-only

### ISSUE THREAD

**Issue by numapanuma** [kanboard/kanboard#3474]
### Actual behaviour
Currently public access is in read-only mode.

### Expected behaviour
Anyone with the link could be able to create a new task and move tasks between columns.
The goal is to avoid make people sign in and login to participate, since they might participate on a one time basis such as in the case of a neighbourhood assembly prioritizing topics for example.

Thanks!!

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited.

Thank you for your understanding
