### ISSUE TITLE
[Suggestion] Update favicon implementation (and icon?)

### ISSUE THREAD

**Issue by kramred** [kanboard/kanboard#3476]
### Update favicon implementation using [RealFaviconGenerator](https://realfavicongenerator.net)

Hello everyone,

for my own installation of kanboard I changed the code for the favicon (and the icon) and wanted to ask if this could be of interest to the project.

I used the online tool [RealFaviconGenerator](https://realfavicongenerator.net) to generate the icons.

I also made an updated version of the default icon with minor adjustments in size and positioning:

![Preview Kanboard favicon 2017-10-05](https://realfavicongenerator.net/featured_favicons/previews/p1brmbrpth1n5mb051sv11nf41a3k6.png)

- [preview here](https://realfavicongenerator.net/featured_favicons/p1brmbrpth1n5mb051sv11nf41a3k6)

- [download here](https://realfavicongenerator.net/files/5b40d76ca375727199f3e6f83db07e97d9a6fca5/favicons.zip)

The new code as suggested by [RealFaviconGenerator](https://realfavicongenerator.net) would be:

```html
        <link rel="apple-touch-icon" sizes="180x180" href="<?= $this->url->dir() ?>assets/img/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="<?= $this->url->dir() ?>assets/img/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="<?= $this->url->dir() ?>assets/img/favicon-16x16.png">
        <link rel="manifest" href="<?= $this->url->dir() ?>assets/img/manifest.json">
        <link rel="mask-icon" href="<?= $this->url->dir() ?>assets/img/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="shortcut icon" href="<?= $this->url->dir() ?>assets/img/favicon.ico">
        <meta name="msapplication-config" content="<?= $this->url->dir() ?>assets/img/browserconfig.xml">
        <meta name="theme-color" content="#f1f1f1">
```

However the files `browserconfig.xml` and `manifest.json` that come in the zip-package have hardcoded directories, which would have to be customized for each installation.

## Question 1

Is there a script that runs once after installation that could adjust the paths in these files?

##  Question 2

I used a derivative of the [commercial kanban app icon](http://fontawesome.io/icon/trello/) for my installation.

Is there any interest in having a different icon for Kanboard, maybe similar to a stylized kanban board?

**Comment by fguillot** [comment]
What is the difference with the existing icons?

**Comment by kramred** [comment]
Very minor differences in the KB icons themselves, new icon has:

- Same font-weight for both characters
- Same height for both characters (e.g. in pixels)
- More (and equal) padding on left and right side
- More padding on top (and thereby a bit smaller font size)
- Light grey instead of white as background color

![transition from old to new icon](https://raw.githubusercontent.com/kramred/kanboard/518f804feb7606abdfb74e0dd5c47bb3c8718867/assets/img/KB-new-vs-old.gif)

- This suggestion was more about the HTML code in the head and asking if the following could be (a starting point for) an alternative favicon:

![favicon-32x32](https://user-images.githubusercontent.com/16719551/31542121-be940e8e-b008-11e7-8057-00b0a993fbf6.png)

[fontawesome-kanban-commercial-app-icon](http://fontawesome.io/icon/trello/)

**Comment by fguillot** [comment]
I don't really want to have any legal issues with Trello, so I'm not going to use their favicon.
