### ISSUE TITLE
Can't connect to Kanboard self hosted with Android app

### ISSUE THREAD

**Issue by Gnaagounet** [kanboard/kanboard#3477]
Hi, when I try to connect my Kanboard app on Android : 

https://play.google.com/store/apps/details?id=eu.it_quality.kanboard&hl=fr

with : 

http://todo.nicolas-catillon.fr

and : 

user : demo
password : Test12345

I have an "error" message.

I emailed the dev of the app and he told me : 
_________
Hello Using PostMan I could not login to your KB

please contact Frédéric Guillot ( Owner of KB )

{"jsonrpc":"2.0","error":{"code":401,"message":"Unauthorized"},"id":null}
_________

Configuration of the hosting and Kanboard self hosted

- Kanboard version: 1.0.47
- Database type and version: sqlite 3.14.2
- PHP version: 7.0.17 
- OS: Linux 4.4.67-ovh-vps-grsec-zfs-classid 

And I use Android 7.0 with EMUI 5.0.1 (Honor 8)

Can you help me please?

**Comment by fguillot** [comment]
You should make sure your hosting provider pass the authentication header. Try this PR: https://github.com/kanboard/kanboard/pull/3456/files or try with another http header like described here: https://github.com/kanboard/kanboard/blob/master/doc/en_US/api-authentication.markdown#custom-http-header

This curl call should work:

```
curl -u demo:Test12345 -d '{"jsonrpc": "2.0", "method": "getMyProjects", "id": 1}' http://todo.nicolas-catillon.fr/jsonrpc.php
{"jsonrpc":"2.0","error":{"code":401,"message":"Unauthorized"},"id":null}
```

**Comment by Gnaagounet** [comment]
Thanks, it works with 

<IfModule mod_setenvif.c>
    SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0
</IfModule>

**Comment by fguillot** [comment]
The PR has been merged, that will be available in the next release.
