### ISSUE TITLE
[nested-projects] or [unlimited level sub-projects] in kanboard

### ISSUE THREAD

**Issue by BigGitWorld** [kanboard/kanboard#3478]
Hi.
I would like to create more than one sub-project in a main project.
for example:
main project : MyProject
sub-project(level-1) : MyProject > Sub-of-Main1
sub-project(level-1) : MyProject > Sub-of-Main2
sub-project(level-2) : MyProject >  Sub-of-Main1 > sub-of-(Sub-of-Main1)-1
sub-project(level-2) : MyProject >  Sub-of-Main1 > sub-of-(Sub-of-Main1)-2
...
sub-project(level-2) : MyProject >  Sub-of-Main2 > sub-of-(Sub-of-Main2)-1
sub-project(level-2) : MyProject >  Sub-of-Main2 > sub-of-(Sub-of-Main2)-2
...

currently I can create only one level of swimlane(s) in each project, but I need to create unlimited level (nested) swimlanes. 
how can I do this?

thanks alot

**Comment by fguillot** [comment]
Unfortunately, this feature doesn't exists. There is no plan to implement that.
