### ISSUE TITLE
swimlanes with different column names in one project

### ISSUE THREAD

**Issue by BigGitWorld** [kanboard/kanboard#3479]
### Actual behaviour
In kanboard we can change name of columns in project setting. it is very good but limited.
when we change name of columns, it apply to all swimlanes.

### Expected behaviour

I would like to have several swimlanes with different column names in one project.
for example : 
swimlane(1):
Column1 / Column 2 / Column 3 / ...
swimlane(2):
Column4 / Column 5 / Column 6 / ...

**Comment by amff1704** [comment]
Any news about this one? That would help a lot...

**Comment by fguillot** [comment]
See #1695
