### ISSUE TITLE
Remove Kanboard (change name) in From Email Address

### ISSUE THREAD

**Issue by sna8p** [kanboard/kanboard#3480]
I have notifications set up to email users.  My server name is 'Projects'.  When a notification is sent out if comes from 'Kanboard <ProjectNotice@Domain.com>'.  Oddly this confuses a few users.  Can I make it come from 'Projects <ProjectNotice@Domain.com>'? 

I have searched everywhere and just cant seem to find where it is set at.  Even tried putting the full email in config.php as 'Mail_From', 'Projects <ProjectNotice@Domain.com>' instead of just 'Mail_From', 'ProjectNotice@Domain.com'.  

Thanks in Advance!

 Application version: 1.0.34
PHP version: 5.4.16
PHP SAPI: apache2handler
OS version: Linux 3.10.0-514.26.2.el7.x86_64
Database driver: mysql
Database version: 5.5.52-MariaDB

**Comment by fguillot** [comment]
Unfortunately, there is no configuration parameters for that. If you really need this feature, the best way is to contribute to the project and send a PR.
