### ISSUE TITLE
The default issue category for kanboard or project

### ISSUE THREAD

**Issue by rammy1231** [kanboard/kanboard#3481]
The default category for kanboard.

This is the feature request:
It will be great to have a possibility to set default category for the entire kanboard (like it is with default colour of issues) or even every single project (e.x. in Category settings). The default category will be set for every new issue, analogically like default colour of the issue.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
