### ISSUE TITLE
Plugin request: connector with Microsoft Teams 365

### ISSUE THREAD

**Issue by szawadski** [kanboard/kanboard#3482]
I love the Mattermost plugin. Thank you @fguillot for developping this. But my employer decided to move to Teams 365, Microsoft's new collaboration tool. And I have to say it's pretty convincing even if some basic features of Mattermost are not present yet (like private channels, for instance).
Except the integrated MS-Planner light implementation that sucks compared to Kanboard... And Microsoft is still soooo far away of reaching the level of versatility of Kanboard, a real Swiss-Army knife in the world of the virtual kanban boards.
Is anybody planning to develop such a plugin? Thanks in advance!

**Comment by fguillot** [comment]
I don't really have plan to develop such plugin. If you need this feature, the best way is to create your own plugin. If Microsoft Team is a clone of Slack or Mattermost, then it should be easy to implement.
