### ISSUE TITLE
Clicking on a task created last year produces malformed html

### ISSUE THREAD

**Issue by chrisjhowe** [kanboard/kanboard#3484]
**Please, do not create duplicate issues**

### Actual behaviour

For tasks created last year when I click on the task title instead of getting the normal information about the task with the menu on the left I get this:
![image](https://user-images.githubusercontent.com/32091174/31393067-bc1bbce8-add2-11e7-8143-ca9d2c793c1c.png)

If I look at the page source it looks like this:
![image](https://user-images.githubusercontent.com/32091174/31393538-d8a39e70-add3-11e7-96c8-db68fb0f1bee.png)

There is no html, body, etc tags.

### Expected behaviour

I should get a nice page with all the menu items and information.

### Steps to reproduce

It appears that tasks created in earlier versions of Kanboard don't work correctly.  I haven't found a way to either fix a broken task or break a working one.  I have found that a task created in 2016 and then edited in 2017 seems to be OK.  But if I duplicate or edit a 'broken' task then that does not fix it.

### Configuration

    Application version: 1.0.46
    PHP version: 7.0.22-0ubuntu0.16.04.1
    PHP SAPI: apache2handler
    OS version: Linux 4.4.0-96-generic
    Database driver: sqlite
    Database version: 3.11.0
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by fguillot** [comment]
You should take a look into the web server log files to see if there are any potential PHP errors.

**Comment by chrisjhowe** [comment]
Checked log file.
Issue appears to be with time tracking editor as removing it fixes the problem:
Lines from the log file attached.
[apachelog.txt](https://github.com/kanboard/kanboard/files/1379404/apachelog.txt)

Thanks for the pointer.

**Comment by fguillot** [comment]
You should report this problem to the bug tracker of this plugin: https://github.com/stinnux/kanboard-Timetrackingeditor
