### ISSUE TITLE
Feature request: Advanced markdown

### ISSUE THREAD

**Issue by polymeer** [kanboard/kanboard#3487]
## At first. Excellent job Frederic. Same to the other contributors!
I wish the markdowd would have more options like GFM. Especially tables, notes, task lists, emojis
* https://help.github.com/articles/basic-writing-and-formatting-syntax/
* https://guides.github.com/features/mastering-markdown/#syntax
* https://github.github.com/gfm/

**Comment by polymeer** [comment]
After investigation (I would have done better times before) I've found /vendor/erusev/parsedown! It's mighty but some things not working:
* Syntax highlighting
* Emojis (not sure it's included)
* Foot notes  (not sure it's included)
* Notes  (not sure it's included)

https://guides.github.com/features/mastering-markdown/#examples > extras
Thanks a lot

**Comment by fguillot** [comment]
The best way to have this features is to contribute to the project. I don't really plan to add more complexity. Only advanced users really use the Markdown syntax...
