### ISSUE TITLE
Feature Request - Swimlanes in Analytics

### ISSUE THREAD

**Issue by eskaryo** [kanboard/kanboard#3490]
Expanding analytics to include swimlanes as a parameter would greatly improve their value for particular use-cases.  

If the CFD had an ability to display the flow divided through respective swimlanes, that could help identify a  specific swimlane with a flow issue. 

Swimlane visibility/toggling for Time Tracking would also be a great way to understand if you have a lane that is bad at estimation or is cycling through work so quickly that the phasing should be re-evaluated.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
