### ISSUE TITLE
Automatic due dates

### ISSUE THREAD

**Issue by Protarios** [kanboard/kanboard#3492]
Allow to have an automated task to set due day to current day (or current day + x days) if moved to a certain column (and no due date is set yet).
**I use a today/tomorrow column quite commonly to plan in the daily tasks. If due date is set automatically on moving there it would appear in the connected calendar.**

Also the other way round would be interesting. Have the background worker move the task to a (today) column, if the date is today.

**Comment by fguillot** [comment]
There is already an automatic action called "Automatically set the due date on task creation". You could easily improve this class and send a pull-request.
