### ISSUE TITLE
2FA verification is skipped when using the android client

### ISSUE THREAD

**Issue by dalai4git** [kanboard/kanboard#3496]
### Actual behaviour

- My account has 2FA active
- Tried to login using the Kanboard client for Android (from IT Quality LTD)
- After entering password the client has access to the server and second factor is not requested

### Expected behaviour

- Either there is a request to supply the second factor or the client fails to login because it doesn't support 2FA

### Steps to reproduce

- Setup 2FA for an account
- Login with the Android client mentioned above

### Configuration

Application version: master
PHP version: 7.1.5
PHP SAPI: fpm-fcgi
OS version: Linux 2.6.32-042stab113.21
Database driver: sqlite
Database version: 3.18.0

(Installed in a docker container using the latest image from about 10 days ago)

**Comment by fguillot** [comment]
As mentioned in the documentation, the 2FA feature is not yet available via the API.

Contributions are welcome.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
