### ISSUE TITLE
Please restore kanboard-1.0.41.zip

### ISSUE THREAD

**Issue by Jibec** [kanboard/kanboard#3497]
Hi there, our self-hosting project ([YunoHost](https://yunohost.org/#/)) is using this URL to get your application and install it:

`https://kanboard.net/kanboard-1.0.41.zip`

Unfortunately, this now returns a 404.

In the coming weeks, we'll fix our script to use: https://github.com/kanboard/kanboard/releases, but in the meanwhile, can you please restore this file?

Btw, here is our kanboard package: https://github.com/YunoHost-Apps/kanboard_ynh

thanks a lot for your help

**Comment by fguillot** [comment]
What about replacing that https://github.com/YunoHost-Apps/kanboard_ynh/blob/master/scripts/_common.sh#L9 by `https://github.com/kanboard/kanboard/releases/download/v${VERSION}/kanboard-${VERSION}.zip`?

**Comment by Jibec** [comment]
Well, you're right, we'll have to fix it anyway.
