### ISSUE TITLE
sometimes page drawn incorrectly

### ISSUE THREAD

**Issue by emanueledf** [kanboard/kanboard#3500]
hi there!  I really love kanboard and it is really part of my daily workflow.
here is the issue.

### Actual behavior
Sometimes page is not drawn correctly (please see screenshot)

### Expected behaviour
correct draw of the page

### Steps to reproduce
not reproducible. happen sometimes with refresh or press links

### Configuration

- Kanboard version: 1.0.47
- Database type and version: SQLite version 3.7.17 2013-05-20 00:56:22
- PHP version: PHP 5.4.16 (cli) (built: Nov  6 2016 00:29:02)
- OS: centos 7, Linux 3.10.0-693.2.2.el7.x86_64 (kanboard running inside a virtual box,  browser accessing from host)
- Browser: mainly Chrome   61.0.3163.100  (but I've got same issue with Explorer 11)

![image](https://user-images.githubusercontent.com/6025295/31778925-331d5ab0-b4f2-11e7-8143-4e7bfdb8e6b1.png)

**Comment by emanueledf** [comment]
can happen both on project page and in dashboard

**Comment by fguillot** [comment]
You should watch the different log files when the problem is happening. It's hard to guess the source of the problem without any details.

**Comment by emanueledf** [comment]
not sure. I don't find any error nor in HTTPD neither in php logfile. is it possible that the error is on client side?

**Comment by rautamiekka** [comment]
You guys sure you have high enough level of logging enabled ? For Apache [2.4.x](https://httpd.apache.org/docs/2.4/mod/core.html#loglevel) and for [2.2.x](https://httpd.apache.org/docs/2.2/mod/core.html#loglevel). 2.4.x is superior to 2.2 here as well.

**Comment by emanueledf** [comment]
Done. 
I don't know PHP and I'm not that good in apache. but to me logfiles seem quite ok.
[access_log.log](https://github.com/kanboard/kanboard/files/1402553/access_log.log)
[error_log.log](https://github.com/kanboard/kanboard/files/1402554/error_log.log)

**Comment by emanueledf** [comment]
issue is present since older version of Kanboard .(i would say around v1.0.30)
happened in 2 different virtual machines (centos 6 and centos 7)
Any suggestion on how to investigate is really welcome ;-)

**Comment by fguillot** [comment]
Do you have any errors in the browser console? All requests are loaded successfully?

**Comment by fguillot** [comment]
Closing stale issue.
