### ISSUE TITLE
Web Notification sorting ascending

### ISSUE THREAD

**Issue by blueforce** [kanboard/kanboard#3502]
**Please, do not create duplicate issues**

### Actual behaviour

the standard sorting for web notification is descending per default

### Expected behaviour

is it possible to turn this to ascending?

### Steps to reproduce

1. Log in to the application as user
2. Click on button notification, then see the list in the modal with all notifications sorted by date descending
3. how can I change this list sorting by date ascending?

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.47
- PHP version: 7.0.24

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
