### ISSUE TITLE
Individual Scrolling was said to be fixed

### ISSUE THREAD

**Issue by anae211** [kanboard/kanboard#3505]
With 1.0.32 the option to enable/disable "individual column scrolling" was removed.

It was removed because of [#1932](https://github.com/kanboard/kanboard/issues/1932) fix.

Issue [#2536](https://github.com/kanboard/kanboard/issues/2536) was closed stating that it was fixed. 

Recent new version 1.0.48 was released and so I installed, and the change log does not state this individual column scrolling was fixed.

Where is this fix and how do I implement it

Application version: 1.0.48
PHP version: 7.0.21
OS version: Linux 2.6.32-673.26.1.lve1.4.30.el6.x86_64
Database driver: sqlite
Database version: 3.8.5
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38

**Comment by fguillot** [comment]
This feature has been removed more than one year ago in v1.0.32. No body said it was fixed.
