### ISSUE TITLE
Create a repository for custom CSS files

### ISSUE THREAD

**Issue by mll0** [kanboard/kanboard#3506]
Kanboard allows us to make custom CSS files (https://kanboard.net/documentation/application-configuration).

I'm sure many people made great customisations. What would be nice would be an easy way to contribute them to a centralised repository.

One could easily browse this repository and download the CSS.

Nice stuff to have :
* screenshots in the repository
* number of downloads in the repository
* evaluation system in the repository
* info about Kanboard version compatibility in the repository
* quick way of submitting one's own CSS file to the repository
* ability to switch between different locally installed CSS files
* ...

(Yes, I pretty much have the Wordpresss Themes / Plugins system in mind)

What do you think ?

**Comment by matthew-mcallister** [comment]
If stylesheet authors are willing to distribute their themes as plugins (which they seem to do now), then this could be accomplished by just making a new plugin repo designated for themes. This would basically boil the implementation down to making Kanboard support multiple plugin repos at once.

**Comment by fguillot** [comment]
People already have the possibility to create custom themes by creating a plugin with few line of code (https://github.com/kanboard/plugin-example-css). It's up to them to submit (and maintain) their plugin to the website.
