### ISSUE TITLE
Add tag, reference and catégories in email

### ISSUE THREAD

**Issue by avermote** [kanboard/kanboard#3507]
### Actual behaviour
When we receive an email about new task creation or a reminder email of delayed task, the fields tag, reference and catégory don't appear

### Expected behaviour
Add these field in the email sent when a task is created or in a reminder

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.46
- Database type and version: postgres
- PHP version: 7.1.5
- OS: RedHat 7.2
- Browser: Firefox

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
