### ISSUE TITLE
Documentation Task by email question

### ISSUE THREAD

**Issue by izno** [kanboard/kanboard#3508]
Hello all,

I'm little confused by the documentation about the task by email. What confuses me is that in the documentation:

https://kanboard.net/documentation/create-tasks-by-email

...it say that a pattern of something+myproject@inbound.mydomain.tld should be used (see image)

![image](https://user-images.githubusercontent.com/968204/32041004-edea4426-ba32-11e7-90c0-55fe7c0658b7.png)

But in the mailgun documentation:

https://github.com/kanboard/plugin-mailgun

...it say that a specific email should be registered per project (see image)

![image](https://user-images.githubusercontent.com/968204/32040938-b27fdc52-ba32-11e7-8e03-fc629c75ed9d.png)

- Which one is the correct one?
- Now that we have the unique email field for each project, what is the project identifier being used for?
- Is it possible to use a generic pattern in mailgun for the incomming emails? ...If so, how should the local part of the email look like? ...or what is the best practice set up?

Thank you in advanced

Application version: 1.0.48
PHP version: 7.1.6
Database driver: sqlite

**Comment by izno** [comment]
I've found this documentation:

http://blog.mailgun.com/tips-tricks-guide-to-using-regular-expressions-to-filter-incoming-email/

...and used this expression: match_recipient("^project\+(.*)@example.com$") the email is being delivered and mailgun logs "Server response: 200 IGNORED"

The mail is delivered but Kanboard ignored it even though the sender is an user in the projekt with email...

Any help is appreciated!

**Comment by izno** [comment]
PS. I have to mention... if I put a static email in the project like the mailgun documentation... then it works like a charm!

The confusion and my question remains: How to make use of the "project identifier"?

**Comment by fguillot** [comment]
The documentation was not up to date. Project identifiers are not used anymore for incoming emails. Each project have its own email address.
