### ISSUE TITLE
missing avatar in UserView

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#3511]
### Actual behaviour

I added a custom avatar.
In the UserView and GroupMembersView, the avatar is not displayed.

![image](https://user-images.githubusercontent.com/13346344/32094676-ea838c24-bb00-11e7-8c18-e843b346acf6.png)

The name is displayed twice instead.

For users without a custom avatar, the avatar is displayed correctly `(TJ)` for example.

### Expected behaviour

The avatar should be displayed.

### Steps to reproduce

1. Add a custom avatar through the profile settings.
2. Check the UserView.

### Configuration

Application version: 1.0.48
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by fguillot** [comment]
I'm not able to reproduce your issue. You should try to check the logs for potential errors:

- Check the browser console
- Check the web server logs
- Check the application debug logs
- Uninstall incompatible plugins

**Comment by fguillot** [comment]
No answer.

**Comment by Chaosmeister** [comment]
Yeah sorry - it somehow fixed itself. Every avatar is displayed correctly by now.
