### ISSUE TITLE
cli worker issue / no email sent (with Sendgrid & RabbitMQ) [Monitoring]

### ISSUE THREAD

**Issue by alefaucheur** [kanboard/kanboard#3512]
**Please, do not create duplicate issues**
Warning: Error while sending QUERY packet. PID=xxx in C:\xampp\htdocs\kanboard\vendor\fguillot\picodb\lib\PicoDb\StatementHandler.php  on line 240
**i use RabbitMQ & Sendgrid plugins & cli worker**

### Actual behaviour
"php cli worker" command print out the error message and no email sent out using Sendgrid plugins (RabbitMQ services installed, when i start the "cli worker" email are sent like a charm but failed after a while i don't understand why and how)

Note: 
I use a very standard MySQL distribution, no configuration change made, i don't expect issue.

### Expected behaviour
when i run following commands:
php cli cronjob
php cli notification:overdue-tasks
php cli projects:daily-stats
php cli trigger:tasks

I expect late tasks to be emailed through the sendgrid plugin by RabbitMQ thanks to "cli worker".
After a couple of hours (12h maybe) when i run these php lines then "cli worker "will print out he error message and no email send.

### Steps to reproduce
run php cli worker over more than a day (to make sure)
run php cli notification:overdue-tasks
error message should occur

Note: when googled the error i hoped that the following would solve the problem but it ** did not **.
Change MySQL config (my.ini)  from max_allowed_packet=<your actual value> to max_allowed_packet=8M, 32M, event 64M did not solve the issue as well as the innodb_lock_wait_timeout = from 60 to 100

### Configuration
Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:
    Application version: 1.0.48
    PHP version: 7.1.1
    PHP SAPI: apache2handler
    OS version: Windows NT 6.1
    Database driver: mysql
    Database version: 10.1.21-MariaDB
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by alefaucheur** [comment]
I keep monitoring over a couple of week to figure out where is the problem
Thanks

**Comment by fguillot** [comment]
Seriously, stop creating duplicate, you already created this issue here #3498. Just reopen the closed issue?

**Comment by alefaucheur** [comment]
I am sorry, my bad (did not find the way to re-open)

This morning still get error message as above (Warning: Error while sending QUERY  ... StatementHandler.php ...) ,  mysql_error.log shows nothing, and debug.log shows = 
[2017-10-30 09:59:45] [error] Kanboard\Core\Queue\JobHandler::executeJob: Error during job execution: SQL error
[2017-10-30 09:59:45] [error] Kanboard\Core\Queue\JobHandler::executeJob => {"class":"Kanboard\\Job\\EmailJob","params": ...

turn all debug mode on, keep posted tomorrow

**Comment by alefaucheur** [comment]
Here is the mode detailed kanboard log
[2017-10-31 12:05:38] [debug] Subscriber executed: Kanboard\Subscriber\BootstrapSubscriber::execute
[2017-10-31 12:05:38] [error] Kanboard\Core\Queue\JobHandler::executeJob: Error during job execution: SQL error: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

May the "php cli worker" not developed to work on 24/7 and must be called on demand or once a day for instance

**Comment by alefaucheur** [comment]
Still occuring again.
Last change to my.ini (increased max_allowed_packet and innodb_log_file_size)
if not working then i will change wamp version, and reinstall everything

**Comment by alefaucheur** [comment]
Due to last changes in mysql config my.ini (increased max_allowed_packet and innodb_log_file_size)
now i got following errors (mySQLd crashed ... no good)

Apache error.log:
[Wed Nov 08 04:18:00.661907 2017] [php7:error] [pid 2568:tid 1608] [client ::1:50699] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in C:\\xampp\\htdocs\\kanboard\\plugins\\RabbitMQ\\vendor\\php-amqplib\\php-amqplib\\PhpAmqpLib\\Wire\\IO\\StreamIO.php on line 212

Apache access.log: 
::1 - - [08/Nov/2017:04:17:29 +0100] "GET /kanboard/?controller=UserAjaxController&action=status HTTP/1.1" 200 214 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0"

What "200 214" would ever mean?

mysql_error.log:
"15:58:25  [mysql] 	Error: MySQL shutdown unexpectedly.
15:58:25  [mysql] 	This may be due to a blocked port, missing dependencies, 
...
15:58:25  [mysql] 	entire log window on the forums"
mySQLd.exe crashed with nothing in the logs ... so i can not tell when.

I started over today, pretty sure this will occur again.
Keep posted

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as "server configuration". If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
