### ISSUE TITLE
Welcome message on login screen, or logged in screen

### ISSUE THREAD

**Issue by cjohnsonuk** [kanboard/kanboard#3513]
Feature request:
**Please, do not create duplicate issues**
Quick search of all issues didn't show anything

### Actual behaviour
No welcome message before logged in or MOTD functionality once logged in 
### Expected behaviour

It would be great if we could put some intro text on the login screen to let user know what the system is that they are about to log in to.  Eg Welcome, This Kanboard is for "Division X" projects only, please use this <a>link</a> for projects for "Division Y".

And a message once logged in eg "For more help on standards to use when creating projects please refer to this <a>linked document</a>" or "please note that this service will be down for maintenance between 23:00hrs and 25:30hrs on Feb 30th"

Not sure if this can be created as a plugin or if it needs a core change

### Steps to reproduce
n/a
### Configuration
n/a

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
