### ISSUE TITLE
Disable hashing as filenames for attachments.

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#3517]
We sometimes work with a lot of files per Task. Kanboard works well with few screenshots and some attachements, but we would not like packing these files for every task, and needing to unzip them for each process.
Because of that I moved the Data folder to a network share, so we can use the the kanboard generated folders for our filemanagement.

### Actual behaviour
All attachements are renamed to hashes and missing the file extension.

### Expected behaviour
Attached documents should keep their name. The extensions should be kept as well.
Attached screenshots should have the .png extension.

I quickly tried to change the behaviour, but was kind of unsuccessfull or the cache fought against me.

Something else:
Would it be possible to add a checkbox to create the folder? 

### Steps to reproduce
1. Attach a document to a task.
2. Inspect the task folder.

### Configuration

Application version: 1.0.48
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by fguillot** [comment]
This is not the attended usage of the files folder. It's a object storage. Sorry, I don't have any plan to change that.
