### ISSUE TITLE
Global categories

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#3519]
Our workflow is evolving with Kanboard.

So is our kanboard itself:  
We're incrementing the number of colums as we split our workflows into more & more granular processes. This causes the kanboard to become extremely compact (to the point where it's difficult to work with) or wide (depends on wether you use horizontal scrolling).

I'd like to split the Board into multiple smaller boards, where automatic actions will move tasks between the boards and every team just has to work with their own optimzied/simplified board.

For that I'd like to request a rework of the categories table:
At the moment, the `project_has_categories`-table stores the categories for each project separately.
This causes categories to be stored multiple times:  
![image](https://user-images.githubusercontent.com/13346344/32175211-88c4be6e-bd84-11e7-8fee-2191d99839d0.png)

If this table was split into 2 tables (one assigning the category-name to it's id, another one storing the category-id, with the project-id that uses it), the categories would become reusable in other projects, enabling the tasks to keep their categories when moving them between projects.

### Actual behaviour
The category of a task is set to none on moving, if the current category is not in the other project.
I need to make sure, the categories are available in the other project.

### Expected behaviour
Keep the category.

### Configuration

Application version: 1.0.48
PHP version: 7.0.7
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.3
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by fguillot** [comment]
Sorry, I don't plan to change this behavior, I have some use cases where I don't want the categories to be shared across projects. You still have the possibility to define a list of common categories in the application settings or use global tags instead of categories.
