### ISSUE TITLE
 PHP Fatal error - What's the best way to automate upgrade?

### ISSUE THREAD

**Issue by Jibec** [kanboard/kanboard#3520]
I rewrote the scripts to install Kanboard for the YunoHost self-hosting project.

Here is my code: https://github.com/Jibec/kanboard_ynh/tree/rework

I think the upgrade code should be quite easy to understand: https://github.com/Jibec/kanboard_ynh/blob/rework/scripts/upgrade

Unfortunately, I can't find a solution for obsolete plugins that triggers errors:
 https://github.com/YunoHost-Apps/kanboard_ynh/pull/52#issuecomment-340535086

Do you have any advice?
Thanks a lot for this great project!

Note, if you're look for one of the "helpers", here is the full list: https://github.com/YunoHost/yunohost/tree/unstable/data/helpers.d

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
