### ISSUE TITLE
Mention for a attachment/screen capture in a comment

### ISSUE THREAD

**Issue by eltonps** [kanboard/kanboard#3521]
I think a good improvement, is have the option to make a mention (generate a link or something) for specific a attachment/screen capture in a comment.

![image](https://user-images.githubusercontent.com/25574612/32197396-3714e36a-bdab-11e7-8b6d-b01b1782c9d1.png)

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding

**Comment by eltonps** [comment]
No problem. Thank you!
