### ISSUE TITLE
Tiddlywiki may a good idea for import/export task !

### ISSUE THREAD

**Issue by peter58228** [kanboard/kanboard#3524]
For long awaited tasks, archive tasks is a very important function. KB does not have it in current version.
The fist issues of the export a task should be "export to what", most people may say excel, but tasks include tags, attachments, links..., not Excel format can be include. **Tiddlywiki** use a single html file store everything of a wiki. It's may be a good solutions for task export. 
The reasons are:
1. Export task/tasks to a single file.
2. All element can be export and store in single readable html file.
3. Exported file can be read in browser instantly in a nice formatted page.
4. Exported file can email or share to other person.

I am not a programmer, hope somebody can make a plugin for this.

**Comment by fguillot** [comment]
The best way to make this happen is to create your own plugin.
