### ISSUE TITLE
not a bug but a wishlist: pushing delays for all tasks for all or a given project

### ISSUE THREAD

**Issue by zpartakov** [kanboard/kanboard#3526]
1st a **great thanks** for your **great** software! 

For me there is juste one important feature missing

excuse me if it already exists, I've really tried to find it but no way...

### Expected behaviour
ability of global pushing delays for tasks with a given delay, by project or for all project
example: a problem is found so all the tasks have to be task delayed +1 month

### Screenshots
sorry it's in french from my own made project management tool, much less efficient than your! but you'll understand the feature

![pushdelayskb](https://user-images.githubusercontent.com/2698011/32280371-e9db33b6-bf1b-11e7-9c42-96bcc3ce9aea.png)

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding

**Comment by zpartakov** [comment]
thanks for the answer, no problem!
I understand perfectly and it's a good idea if I try on my own
just 2 more questions:
- wouldn't it be easier to do it with the python-api-client instead of a plugin?
- if no, may you suggest me the "easiest" of your plugin to start studying it?

**Comment by zpartakov** [comment]
ok, forget about it, it was so easy using sql:
`
UPDATE tasks 
SET `date_due` = `date_due`+(7*24*3600) 
WHERE project_id=4;
`
