### ISSUE TITLE
Kanboard Federation

### ISSUE THREAD

**Issue by baldurmen** [kanboard/kanboard#3527]
Opening this since I can't find any mention of it anywhere.

I've started using Kanboard a lot more in the last year, and since I work at 2 difference places and contribute to multiple projects, I now have accounts on 3 different Kanboard instances.

It would be incredible if there was a way to federate those instances, a little bit like Nextcloud does.

The way I see it is that you would share a whole project with another Kanboard instance, so that you could keep track of that project on either of those.

Don't hesitate to close this one if it's a pipe dream :D

Thanks for the great project.

**Comment by k00ni** [comment]
I would need such tool too. It would help to maintain different instances, keep everything together on one place and allows high flexibility. 

There could be some "issues" with user handling (e.g. roles) and write/read access settings.

**Comment by oliviermaridat** [comment]
Nice idea!
A kind of "plugin-github-webhook" or "plugin-gitlab-webhook" but for Kanboard could be a solution for this.

**Comment by fguillot** [comment]
Sorry, but I don't really want to complexify this software.
