### ISSUE TITLE
In modal window: "Move task to other project"  select project doesn't work 

### ISSUE THREAD

**Issue by JohnBat26** [kanboard/kanboard#3528]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour

In modal window: "Move task to other project"  select project doesn't work 
### Expected behaviour
In modal window: "Move task to other project"  select project work 

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment]
It's working for me. Please, fill the Github template or close this issue.

**Comment by fguillot** [comment]
Closing invalid bug report.
