### ISSUE TITLE
PHP warning due to moving plugins to a different directory

### ISSUE THREAD

**Issue by chrisjhowe** [kanboard/kanboard#3531]
This doesn't stop my installation working but it might be worth looking at.

The apache error logs say:

> [Fri Nov 03 11:53:04.383196 2017] [:error] [pid 8342] [client xxx:53766] PHP Warning:  filemtime(): stat failed for plugins/Gantt/Assets/chart.js in /var/www/html/kanboard_48/app/Helper/AssetHelper.php on  line 24
> [Fri Nov 03 11:53:04.383226 2017] [:error] [pid 8342] [client xxx:53766] PHP Warning:  filemtime(): stat failed for plugins/Gantt/Assets/gantt.js in /var/www/html/kanboard_48/app/Helper/AssetHelper.php on line 24
etc.

My config.php file has the lines:

> // Plugins directory
> define('PLUGINS_DIR', '../kanboard_plugins');
> 
which is where the plugins are.

I can remove the errors by creating a symbolic link called plugins from within the kanboard directory
that points at ../kanboard_plugins, the config.php file was not changed so it is still setting PLUGINS_DIR as above.

### Configuration

    Application version: 1.0.48
    PHP version: 7.0.22-0ubuntu0.16.04.1
    PHP SAPI: apache2handler
    OS version: Linux 4.4.0-97-generic
    Database driver: sqlite
    Database version: 3.11.0
    Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by fguillot** [comment]
Well, if you read the error message, that says the application is not able to find the Javascript files. Probably because you defined a relative path.

Note that those JS files must be accessible by your web browser as well.

**Comment by esprit-libre** [comment]
Moving 'plugins' dir to other place, even if www-data has full access, cause problems (ie: [#21](https://github.com/kanboard/plugin-gantt/issues/21) ).

Apache logs are:
> [Mon Nov 20 10:00:08.708490 2017] [:error] [pid 5346] [client 109.190.199.43:64192] PHP Warning:  filemtime(): stat failed for plugins/Gantt/Assets/gantt.css in /data/www/kanboard/app/Helper/AssetHelper.php on line 37
> [Mon Nov 20 10:00:08.708503 2017] [:error] [pid 5346] [client 109.190.199.43:64192] PHP Warning:  filemtime(): stat failed for plugins/Calendar/Assets/fullcalendar.min.css in /data/www/kanboard/app/Helper/AssetHelper.php on line 37
> [Mon Nov 20 10:00:08.708517 2017] [:error] [pid 5346] [client 109.190.199.43:64192] PHP Warning:  filemtime(): stat failed for plugins/Gantt/Assets/chart.js in /data/www/kanboard/app/Helper/AssetHelper.php on line 24
> [Mon Nov 20 10:00:08.708527 2017] [:error] [pid 5346] [client 109.190.199.43:64192] PHP Warning:  filemtime(): stat failed for plugins/Gantt/Assets/gantt.js in /data/www/kanboard/app/Helper/AssetHelper.php on line 24
> [Mon Nov 20 10:00:08.708537 2017] [:error] [pid 5346] [client 109.190.199.43:64192] PHP Warning:  filemtime(): stat failed for plugins/Calendar/Assets/moment.min.js in /data/www/kanboard/app/Helper/AssetHelper.php on line 24
> [Mon Nov 20 10:00:08.708547 2017] [:error] [pid 5346] [client 109.190.199.43:64192] PHP Warning:  filemtime(): stat failed for plugins/Calendar/Assets/fullcalendar.min.js in /data/www/kanboard/app/Helper/AssetHelper.php on line 24
> [Mon Nov 20 10:00:08.708558 2017] [:error] [pid 5346] [client 109.190.199.43:64192] PHP Warning:  filemtime(): stat failed for plugins/Calendar/Assets/locale-all.js in /data/www/kanboard/app/Helper/AssetHelper.php on line 24
> [Mon Nov 20 10:00:08.708568 2017] [:error] [pid 5346] [client 109.190.199.43:64192] PHP Warning:  filemtime(): stat failed for plugins/Calendar/Assets/calendar.js in /data/www/kanboard/app/Helper/AssetHelper.php on line 24

```
# ls -l /data/kanboard/
total 8416
-rw-rw-r-- 1 www-data www-data 8598285 Nov 20 09:59 debug.log
drwxrwx--- 4 www-data www-data    4096 Nov 19 04:38 files
drwxrwx--- 9 www-data www-data    4096 Nov 20 09:59 plugins
-rw-rw---- 1 www-data www-data     160 Oct 24 03:04 web.config
```

Some plugins works well (ie: Milestone, Sel-registration...), but others not fully (Calendar, Gantt).
Installing some plugins also fails (ie: Subtask Due Date 1.0.0) whereas it works for others (ie: Milestone 1.1.1).

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as "server configuration". If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
