### ISSUE TITLE
Comment gets lost when Screenshot is uploaded

### ISSUE THREAD

**Issue by myrdd** [kanboard/kanboard#3533]
### Steps to reproduce

1. Open an existing task
2. Enter something in the Comment field. (Do *not* press "Save".)

**`[screenshot]`**

![](https://user-images.githubusercontent.com/4286829/32415919-8ded501a-c241-11e7-9309-0376060eb05e.png)

**`[/screenshot]`**

3. Follow the procedure to add a screenshot:

**`[screenshot]`**

![](https://user-images.githubusercontent.com/4286829/32415940-c17d6dfc-c241-11e7-92ae-80772361fe7e.png)

**`[/screenshot]`**
**`[screenshot]`**

![](https://user-images.githubusercontent.com/4286829/32415944-d0fb0686-c241-11e7-8da3-ebcb6227f18f.png)

**`[/screenshot]`**

### Actual behaviour

After pressing "Save" in the screenshot dialog, the screenshot is uploaded and saved. Now go to the bottom of the task. The field to add a comment is empty. The previously entered comment is lost, unless not saved elsewhere.

**`[screenshot]`**

![](https://user-images.githubusercontent.com/4286829/32415976-4f14f7d4-c242-11e7-8419-3832f0c2f0c5.png)

**`[/screenshot]`**

### Expected behaviour

I expect the comment not to be lost. Possible solutions:

a. back up the comment, i.e., perform some kind of autosave, see #3103
b. display a warning message when the comment field is non-empty and the user wants to add a comment / leave the task page / et cetera.

### Configuration

- Kanboard version: 1.0.48
- Database driver: sqlite
- Database version: 3.7.13
- PHP version: 5.4.45-0+deb7u11
- Server OS: Debian ~~Stretch~~ Wheezy
- Server OS version: Linux 3.2.0-4-amd64
- Browser: Firefox 56.0 (Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0)

**PS:** Thanks for this very nice piece of Software! :)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
