### ISSUE TITLE
URLs not working when behind nginx reverse proxy

### ISSUE THREAD

**Issue by XelaRellum** [kanboard/kanboard#3534]
We are using the docker image from https://hub.docker.com. On our docker server we have an nginx running that dispatches the URLs to the respective application (e.g. https://oursite.com/kanboard/ gets forwarded to http://localhost:4000). 

The login page shows up but all the assets link to an absolute path without /kanboard/ prefix, e.g. /assets/...

Our proxy rule for this site:
```
location /kanboard/ {
    proxy_pass http://127.0.0.1:8004/;
    proxy_redirect / /kanboard/;
  }
```

We have other applications running with the same set of rules (but different location). It seems as kanboard doesnt get the correct GET / LOCATION header.

- Kanboard version: current hub.docker.com image
- Database type and version: sqlite
- PHP version: 7
- OS: Linux
- Browser: Firefox

**Comment by fguillot** [comment]
Did you try to define the application URL in settings?

**Comment by XelaRellum** [comment]
Well was hard to get to the settings with the reverse proxy not working. Got around this by creating an SSH tunnel from my localhost to the docker port.
I changed the application url to the form "https://example.com/kanboard/" but the result was the same. For example the login screen still had links to the absolute "/assets" (without URL and without the application URL as prefix)

**Comment by nealey** [comment]
I just got bit by this. Currently trying various approaches to build a new docker image. Would very much appreciate a configuration setting that says "this is my base path". This is a pretty standard option for web-based apps that allows reverse proxying.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
