### ISSUE TITLE
Can't open menus

### ISSUE THREAD

**Issue by icnsoft** [kanboard/kanboard#3537]
Sorry I accidentally closed the topic so I recreate it now

### Actual behaviour
When I try to press either the + button or any other button, no menu appears while all regular links work. I can't work with it. Also no buttons for saving or anything else.
### Expected behaviour
Menus should appear and I should be able to use all the options including logging out

### Steps to reproduce
I do not know how, but I use Cloudflare (I can't run my website without)
When I did not use Cloudflare on a test subdomain through CNAME, I faced the same problem.

### Screenshots
I don't have any... yet. I'll do it only if really required.

### Configuration

- Kanboard version: 1.0.48
- Database type and version: MySQL
- PHP version: 7x (I think)
- OS: Windows 10
- Browser: Mozilla Firefox 57

**Comment by fguillot** [comment]
Open the browser console and look for errors. If you are using Cloudflare, try to disable the "Javascript optimization".

**Comment by icnsoft** [comment]
Ok I'll try to set up a new server for testing about this issue

**Comment by dhornford** [comment]
Thanks. We are having the same problem with Cloudflare.
Set a pagerule for the entire Kanboard site: Always Online: off, Cache level: bypass; Disable Apps; Disable Performance

With these pagerules the menus work & we can move the cards.
