### ISSUE TITLE
add check item list feature

### ISSUE THREAD

**Issue by xwinie** [kanboard/kanboard#3539]
看板按卡片的三要素里面，有一项重要的check list功能，希望在最近版本有添加这个计划

**Comment by fguillot** [comment]
Closing invalid bug report.

**Comment by xwinie** [comment]
不是报告，是这样的功能/Users/bobo/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/3a15979dd6b51b6aada209350cb3c0f6/Message/MessageTemp/c0d9dc739f6a161f44b30332b5a1d77c/Image/52101510124705_.pic.jpg

**Comment by xwinie** [comment]
@fguillot
