### ISSUE TITLE
Project list is hidden when moving/duplicating task to another project

### ISSUE THREAD

**Issue by hasop** [kanboard/kanboard#3541]
### Actual behaviour
Project list is hidden when moving/duplicating a task to another project.
You have to scroll up to view the list.

### Expected behaviour
Project list is available

### Steps to reproduce
Create many tasks (over 20) in the same column.
Scroll down to the last task.
Select "Move to another project" or "Duplicate to another project".
Unfold the project list => the list is not available.
scroll up => the list is in the top of the frame

### Configuration

- Kanboard version: 1.0.48
- Database type and version: Mysql 5.1.73
- PHP version: PHP 7.1.10
- OS: CentOS 6.0
- Browser: Chrome, IE

**Comment by fguillot** [comment]
It should be fixed now in the development version. Thanks.
