### ISSUE TITLE
Direct playback of mp3 files in task attachments

### ISSUE THREAD

**Issue by aquaneno** [kanboard/kanboard#3543]
This software focus on simplicity, the number of features is voluntary limited.

I would like to play mp3 files directly in the browser windows without downloading them. Therefore is it necessary to bring up a new button in the dropdown for attached files with a link to the data with the related mimetype or file extension. This would increase the mobile usability in a lot of situations.

THX!

### Actual behaviour
Attached MP3 files in a task are only available for a file download. There ist only a dropdown button available for "TaskViewerController" "Download" and "Remove". 

### Expected behaviour
Extend app/Template/task_file/file.php with a "FileViewerController" request for file tye audio.

### Configuration

- Kanboard version: 1.0.46
- Database type and version:  Kanboard default
- PHP version: 5.4.16
- OS: CentOS 7
- Browser: all

**Comment by FernandoBatels** [comment]
Hi, i added you feature request on my fork and send pull request on #3603. You can play yours mp3 files now on kanboard.

Best regards! :)

**Comment by aquaneno** [comment]
Thanks a lot! Works like a charme!
