### ISSUE TITLE
Cant delete column #3340

### ISSUE THREAD

**Issue by djixas** [kanboard/kanboard#3544]
I can;'t reopen ticket but please merge this under

https://github.com/kanboard/kanboard/issues/3340

Same issue, no tasks in column, had to delete via mysql

**Comment by igbanam** [comment]
Could you update this issue with proper reproduction steps? On the [most recent master today](https://github.com/kanboard/kanboard/commit/63dbab199c6709aafa77f409f87202443550badf), I created a new project and columns can either be edited or deleted from the gear icon drop-down.

**Comment by fguillot** [comment]
How do you expect people to solve a problem if you don't provide any information to reproduce the problem?

**Comment by djixas** [comment]
I have already solved mine by deleting mysql table, as i ahve no time to wait 5 days or months, and i have no idea now to reproduce it, it i knew, i would have told ya, it just stopped working like for other people, i guess run board for 4 months and see how that works?

**Comment by fguillot** [comment]
well, well...
