### ISSUE TITLE
Multilines in same swimline - Feature request.

### ISSUE THREAD

**Issue by Victor-IT** [kanboard/kanboard#3547]
Hello.
I apologize for my vision of the purpose of these lines (swimlines).
Do you planing to add this feature (multilines) in future?

### Actual behaviour
There are additional lines (swimlines) below. Each line is independent and goes through all the columns.

<table>
<tr><td colspan="4"> ^ Swimline 1 (for Dev_1)</td></tr>
<th>Backlog</th>
<th>In progress (0/3)</th>
<th>Testing</th>
<th>Done</th>
   <tr>
     <td>All tasks</td><td></td><td></td>
    <td>Done tasks</td>
  </tr>

<tr><td colspan="4"> ^ Swimline 2 (for Dev_2)</td></tr>
<th>Backlog</th>
<th>In progress (0/5)</th>
<th>Testing</th>
<th>Done</th>
   <tr>
     <td>All tasks</td><td></td><td></td>
    <td>Done tasks</td>
  </tr>
</table>

### Expected behaviour
Type of rows who can split only selected columns (multiline columns) in the same swimline. For better visualization.

<table>
<th>Backlog</th>
<th>In progress (0/10)</th>
<th>Testing</th>
<th>Done</th>

   <tr>
     <td rowspan="3">All tasks</td><td>Line for tasks of Dev_1 (0/2)</td><td></td>
    <td rowspan="3">Done tasks</td>
  </tr>
<tr><td>Line for tasks of Dev_2 (0/3)</td><td></td></tr>
<tr><td>Line for tasks of Dev_3 (0/5)</td><td></td></tr>
</table>

**Comment by vitkulov** [comment]
I'm using kanboard in my everyday work (not only for developing) with my helpers and give them new tasks.
*When there are many tasks in the column, it shifts down the bottom swimline.
*Looks like the backlogs is different for each swimlines.

I think the benefit - is just better process and interface visualisation of the board.
*In my case it will look like one backlog for everyone.

Of course it can be reached by adding more columns for each Person.
_*But there are no common headings in the current version._
<table>
<th rowspan="2">Backlog</th>
<th colspan="3">In progress (0/10)</th>
<th rowspan="2">Testing</th>
<th rowspan="2">Done</th>

<tr>
<th>Dev_1 (0/2)</th>
<th>Dev_2 (0/3)</th>
<th>Dev_3 (0/5)</th>
</tr>

<tr>
<td>All tasks</td><td></td><td></td><td></td><td></td>
<td>Done tasks</td>
</tr>
</table>

**Comment by vistree** [comment]
You find a first working approach in the referenced forum topic 106

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
