### ISSUE TITLE
Feature Request: Projects Draggable Sort Order

### ISSUE THREAD

**Issue by compumatter** [kanboard/kanboard#3548]
Just as the priority of tasks change, the priority of projects also change on a regular basis. 

At present there is no way to sort projects based on their priority which is actually among the most important sort criteria.  

Ideally I would like to see the ability to two things happen:

- Add a new Sort category called 'Priority' to the Sort List
- Add a draggable feature to the project list allowing us to drag / drop a project into a new position in project list which would also trigger the new Sort by in the list to be set to Priority.

![project-order](https://user-images.githubusercontent.com/121611/32742352-03796234-c85e-11e7-96fa-71ccd3a6119f.png)

Thank you.

Jay
CompuMatter

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
