### ISSUE TITLE
Identify users by their names and not by their SamAccountname when connected to LDAP

### ISSUE THREAD

**Issue by itsmedani** [kanboard/kanboard#3549]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
In my case Kanboard is connected to the  AD Domain
Users are identified by their samaccountname when you want to assign tasks to the user.

### Expected behaviour
Users are identified by their names for simplicity.
It's difficult to identify users by this way as you can see in the screenshot

### Steps to reproduce
Create a task and choose an user in the drop-down list

### Screenshots
![image](https://user-images.githubusercontent.com/26568167/32774659-52093eae-c92d-11e7-8d3d-77baab72b0f6.png)

### Configuration

- Kanboard version:  1.0.48
- Database type and version: sqlite 3.7.17
- PHP version: 5.4.16
- OS: Centos 7 64 bits
- Browser: Chrome

**Comment by itsmedani** [comment]
Hi, 

I found a solution. fortunately we have few users :). For each users, I changed the name as you can see below

![image](https://user-images.githubusercontent.com/26568167/32885067-b1b57986-cabc-11e7-9fed-66776a28fbfe.png)

Now, when i dentify the user in tasks, we are able to see users by their name

![image](https://user-images.githubusercontent.com/26568167/32885158-f208e48c-cabc-11e7-8595-11420756c843.png)


Thanks

**Comment by mauricio-sonegatti** [comment]
Using this configuration I have my users full name when assigning tasks:

define('LDAP_USER_FILTER', 'sAMAccountName=%s');
define('LDAP_USER_ATTRIBUTE_USERNAME', 'sAMAccountName');
define('LDAP_USER_ATTRIBUTE_FULLNAME', 'DisplayName');

You can always change these configs for achieving what you need, in my LDAP the DisplayName is the full name, check your LDAP and see what is registering on that field.

**Comment by itsmedani** [comment]
Hi Mauricio,

Thanks for the solution! 

I modified this parameter:
define('LDAP_USER_ATTRIBUTE_FULLNAME', 'DisplayName');

Regards

**Comment by mauricio-sonegatti** [comment]
Any problems still?

**Comment by itsmedani** [comment]
No it's resolved. 

Do I have to close this issue, right?

**Comment by mauricio-sonegatti** [comment]
Yes, just close it.
