### ISSUE TITLE
Automatic action "Close a task in a specific column" not doing anything

### ISSUE THREAD

**Issue by NimdaBE** [kanboard/kanboard#3550]
//Actual behaviour

nothing happening

//Expected behaviour

moving file to column "done" should close the task

//Steps to reproduce

I have a windows server 2016 machine.
The script for the daily cronjob is located in C:\scripts\kanboard.bat
the scripts containts following code:
"C:\Program Files\PHP\v7.0\php.exe" -f "D:\Applications\Kanboard\cli" cronjob

My site is located on "D:\Applications\Kanboard"
When I run the script manually (elevated command line) or with the task scheduler nothing happens (no errors or anything). The AD-user has rights on the server (local admin) and modify rights to all subfolders and files of the Kanboard-application folder. 

I created a automatic action with these settings:

Close a task in a specific column
--
Event name = Move a task to another column Column = Done

Moving tasks to the column "Done" does not close the tasks... I don't know what i can test or where to look for logs/errors/...

//Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

//Configuration
Application version: 1.0.48
PHP version: 7.0.21
PHP SAPI: cgi-fcgi
OS version: Windows NT 10.0
Database driver: sqlite
Database version: 3.14.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 OPR/48.0.2685.52

**Comment by fguillot** [comment]
The automatic action "Close a task in a specific column" is not triggered by the cronjob but when you move the task on the board to the specified column.
