### ISSUE TITLE
Add new colors as default colors from plugin

### ISSUE THREAD

**Issue by siryan2** [kanboard/kanboard#3551]
Hi, 

thank you so much for this software. I use it very often so that i got the need to add more colors.
I´ve created a plugin to override the default colors but wasn´t able to do that since the $default_colors Array in the ColorModel is set as private. How can I achieve this?

My initial try was this:
```
public function initialize() {

         $this->container['colorModel'] = $this->container->factory(function ($c) {
             return new MyColorModel($c);
        });
}
```
In MyColorModel i extend $default_colors but whitout luck.

**Comment by fguillot** [comment]
You could send a PR to make it protected instead of private.

**Comment by fguillot** [comment]
Your PR has been merged.
