### ISSUE TITLE
LDAP Config | self signed certificate in chain

### ISSUE THREAD

**Issue by wmike** [kanboard/kanboard#3553]
I want to setup Kanboard with the official docker container and it works fine until I want to use LDAP authentication. I setup the nginx with the internal certificate chain and the SSL connection to the server works fine. The chain looks good.
The ldap settings in the config.php works if I use a webserver on the host (not with docker)

### Actual behaviour
A user try to login with ldap authentication. Following error occures:
Internal Error: Unable to connect to LDAP server (Code="-1"; Error="Can't contact LDAP server"; ExtendedError="error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed (self signed certificate in certificate chain)")

### Expected behaviour
The login works (un)succesful.

### Steps to reproduce
1. Create a Dockerfile and the official docker image as the base image.
2. Copy the certificate chain in one file. The root certificate has to be the last one in the file. The server cert is the first one.
3. Change the server config of the nginx to: 
```       
server{
        listen       443 ssl;         
        server_name  localhost;        
        ssl_certificate chain.cer;        
        ssl_certificate_key server_cert.pem;     
        ...
}
```
4. Change the ownership of the certificate files to "nginx".
5. Use an external ldap server with self signed certificates

### Configuration

- Kanboard version: Version 1.0.48
- Database type and version: sqlite
- PHP version: 7
- OS: alpine
- Browser: firefox 52

**Comment by fguillot** [comment]
I don't really understand, according to the error message, the application is not able to establish a SSL connection to your LDAP server. But in the "Steps to reproduce" you are talking about Nginx config, this is unrelated?

**Comment by wmike** [comment]
I solved it. Your were right. The nginx config is not realted to this problem.  The certificates I used in the nginx config are not used for the ldap connection. I had to add `TLS_CACERTDIR path/to/ca/certs/dir` and `TLS_REQCERT allow` in `/etc/openldap/ldap.conf`. Afterwards it works like estimated.
