### ISSUE TITLE
cli : gives the current installed version

### ISSUE THREAD

**Issue by Dan33l** [kanboard/kanboard#3556]
### Actual behaviour

The current version is only available via webui. In an infrastructure as code way of life, all have to be done by cli.
 
### Expected behaviour
This should return the current installed version of kanboard : 
```
$> ./cli version
v1.0.48
$>
```

**Comment by fguillot** [comment]
I added the command in the development branch.

**Comment by Dan33l** [comment]
We can only access to production branch. Is it possible to know when the feature will be in the production branch ?
