### ISSUE TITLE
Can't create New task with the + sign (on column)

### ISSUE THREAD

**Issue by Dennis0001** [kanboard/kanboard#3559]
### Actual behaviour
Pressing the + (plus-sign) in the column header in a swimlane does notting.

### Expected behaviour
New task (modal window) by pressing the + (plus-sign) in the column header in a swimlane.

##work arround (but not a good one)
Press the N-key on my keyboard does show the New task (modal window). And i can create a new task.

##Same kind of problem 
Editing the board and change or delete a column does not work (no modal window).

### Steps to reproduce
Clean install on webserver.

### Configuration
Application version: 1.0.48
PHP version: 7.1.11
PHP SAPI: fpm-fcgi
OS version: Linux 2.6.32-042stab125.5
Database driver: mysql
Database version: 5.6.36
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by fguillot** [comment]
Did you take a look to issue #3537? Did you watch the logs and the browser console?

**Comment by Dennis0001** [comment]
Hi fguillot,

I've checkt out issue #3537.  I'm not using Cloudflare.

When i look al het logs in my browser console, when i press the +sign to add a task the bowser logging shows:
GET http://www.<<*removed*>>/kanboard/?controller=TaskCreationController&action=show&project_id=2&column_id=7&swimlane_id=2 403 (Forbidden)

I've installed this version of kanboard at my hostingprovider by unzipping and uploading the latested version of kanboard. Created a mysql db and created the config file. Notting more (verry basic ;) ) 

I've also installed it on my raspberry pi (with the same zip file and sqllite) and there it works perfect!! So, i know is must be a configuration issue. But i can't find it.

**Comment by Dennis0001** [comment]
found some logging

[Sat Nov 18 18:52:31.283393 2017] [:error] [pid 23353:tid 140056194733824] [client xx.xx.xx.xx:50199] 
[client xx.xx.xx.xx] ModSecurity: Access denied with code 403 (phase 2). 
Pattern match "(?i:\\\\b(?:t(?:able_name\\\\b|extpos[^a-zA-Z0-9_]{1,}\\\\()|
(?:a(?:ll_objects|tt(?:rel|typ)id)|column_(?:id|name)|mb_users|object_(?:id|(?:nam|typ)e)|pg_
(?:attribute|class)|rownum|s(?:ubstr(?:ing){0,1}|ys(?:c(?:at|o(?:lumn|nstraint)s)|dba|ibm|
(?:filegroup|o ..." at ARGS_NAMES:column_id. [file "/usr/local/cwaf/rules/24_SQL_SQLi.conf"] 
[line "18"] [id "211540"] [rev "12"] [msg "COMODO WAF: Blind SQL Injection Attack||www.ictkunde.nl|F|2"] 
[data "Matched Data: column_id found within ARGS_NAMES:column_id: column_id"] [severity "CRITICAL"] [tag "CWAF"] 
[tag "SQLi"] [hostname "www.<<domainname>>.nl"] [uri "/kanboard/"] [unique_id "WhBzX20w0EKU7QENe4CMFgAAAb4"]

**Comment by tjharman** [comment]
Your provider has enabled mod_security.
Kanboard states it's not compatible with mod_security here: https://kanboard.net/documentation/requirements

You need to ask them to disable mod_security or get a new hosting provider.

**Comment by Dennis0001** [comment]
I've checked my hosting provider and because it's a shared hosting they can't (or won't) disable it for me.

**Comment by tjharman** [comment]
Can't say I blame them, I have it myself on my webserver to protect against attacks on PHP code.

Not much you can do to get this to work then sadly, other than move provider.

**Comment by Dennis0001** [comment]
Well most hosting providers are using this kind of security. And if they don't they maybe do it tomorrow (when i've moved :) ) 

I can ony hope kanboard is being upgraded to support mod_security. I'm aware that this will be a lot of work but than again more people are going to (or can) use it when is does support mod_security. 

For now i'll run it from my raspberry at home "hidden" at a high numbered port.

**Comment by tjharman** [comment]
It is rather mod_security that should be flexible for Kanboard.
Their ruleset has rules to detect and not trigger on Wordpress and Drupal.

Plus there's nothing to stop Kanboard making lots of changes to try and "work around" mod_security, then new rules are released a week later that break Kanboard again.

The onus isn't on Kanboard to fix it, it's on the person who has deployed mod_security to know how to fix false positives.  In this case, your hosting provider.  If they're not willing to do this for you then you're not a great hosting provider.

**Comment by Dennis0001** [comment]
So true...

I looked at mod_security website and i can create a ticket there for a false positive.
That's the best thing i can do to help kanboard.

**Comment by Dennis0001** [comment]
Thanks for the support and explanation.

If more people have this problem, log a ticket at mod_security https://www.modsecurity.org/crs/
