### ISSUE TITLE
Can't get github inegration working

### ISSUE THREAD

**Issue by santiagoworkana** [kanboard/kanboard#3565]
Hello, can someone provide me some guidance on how to setup the github front en and webhook plugins?
I've tried creating the oath app and setting up the webhook bu can't get it to work.
Can someone share the steps?

Thanks

**Comment by fguillot** [comment]
Did you read the doc?

- https://github.com/kanboard/plugin-github-webhook#configuration-on-kanboard
- https://github.com/kanboard/plugin-github-frontend#documentation
- https://github.com/kanboard/plugin-github-auth#documentation
