### ISSUE TITLE
Return to original task when duplicating

### ISSUE THREAD

**Issue by LumpyNorman** [kanboard/kanboard#3567]
When duplicating a task is complete, the focus is left on the project to which the duplicate was posted.  Usually, when I make duplicates, I want to return to the source project rather than the target, and so have to navigate back manually.  Although not particularly difficult, this does get pretty tedious when administering.

### Actual behaviour
When a duplicate is made to a different project, the target project remains open in Kanboard when complete.

### Expected behaviour
When a duplication to a different project is completed, return to the source project.

### Steps to reproduce
1. From a task's drop-down menu, select "Duplicate to another project"
2. Select the project, Swimlane etc. and press "Save"
3. The duplicated task is opened
4. Press "Board" to return to the Kanboard view
5. The active Project/Kanboard is now the target project,

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
