### ISSUE TITLE
Not being redirected after login

### ISSUE THREAD

**Issue by Tunzyx** [kanboard/kanboard#3568]
I've installed kanboard on a windows 2016 server, along with PHP 7.0 and SQLite. When I log in, however, it just reloads the login page and doesn't send me anywhere. If i log in with a bad password it tells me that I used a bad password. On successful login nothing happens. Any ideas?

**Comment by fguillot** [comment]
You should try to check the logs for potential errors:

- Check the browser console
- Check the web server logs
- Check the application debug logs
- Uninstall incompatible plugins
- Make sure your environment is compatible with the [requirements](https://kanboard.net/documentation/requirements)

**Comment by Tunzyx** [comment]
Hi,

Thanks for the suggestions. I had to restart the web server for reasons other than Kanboard, and when it got back up the site worked :)

Thanks for the application and continued development and support. Good work!
