### ISSUE TITLE
New Task issue in version 1.1.0

### ISSUE THREAD

**Issue by Marketing-Inspop** [kanboard/kanboard#3569]
We are migrating to new version and i made a fresh installation. DB connectivity and everything is perfect and able to have the working system. 

However we see a issue in New task creation from board view. As soon as i click on + / New Task, URL in browser changes (which doesn't use to in previous versions) and it opens a broken page (CSS issues).

Screenshot is attached. It seems that an event listener is implemented and something conflicting which wasn't in earlier version.

![kanboardissue](https://user-images.githubusercontent.com/30594049/33180332-54ad07be-d092-11e7-8a48-41bdc539571d.png)

**Comment by fguillot** [comment]
You should try to check the logs for potential errors:

- Check the browser console
- Check the web server logs
- Check the application debug logs
- Uninstall incompatible plugins
- Make sure your environment is compatible with the [requirements](https://kanboard.net/documentation/requirements)

**Comment by Marketing-Inspop** [comment]
Thanks the issue was with ColumnGroup plugin and creating issue as mentioned with the new version.
