### ISSUE TITLE
Allow Everybody Access

### ISSUE THREAD

**Issue by kousu** [kanboard/kanboard#3570]
### Actual behaviour

In the most recent Kanboard, the "Allow Everybody Access" option shown (but not mentioned) [here](https://kanboard.net/documentation/project-permissions) was removed [here](https://github.com/kanboard/kanboard/commit/cc6618901bc927558dc159ac0dbec1159231c5f1).

### Expected behaviour

This has stomped on my use case, which is that I have a server integrated with [google](https://github.com/kanboard/plugin-google-auth/). I am not manually creating users; they are being made by plugin, so I have no way to add the users to a group. I would like all my hundreds of users to be able to access a few common boards by default without my intervention.

I think removing this is probably a good simplification, but in its place I need to have an "All Users" group, or maybe plugin-google-auth needs to grow an "Add User To Group At Creation" option; I prefer the former though.

### Steps to reproduce

0. Install/enable an external authenticator.
1. Create a board.
2. Sign in via the external authenticator
3. You cannot see the board and there is no way automated way for you to solve this; you must contact the admin, and you must somehow be informed that you need to contact the admin.

### Screenshots

![screenshot from 2017-11-24 11-20-24](https://user-images.githubusercontent.com/987487/33218184-9457343a-d109-11e7-8270-7b03ec006095.png)

![screenshot from 2017-11-24 11-19-26](https://user-images.githubusercontent.com/987487/33218189-9676bf92-d109-11e7-8894-a535aa90c860.png)

### Configuration

-    Application version: 1.1.0
-   PHP version: 5.6.30-0+deb8u1
-   PHP SAPI: fpm-fcgi
-   OS version: Linux 3.2.0-4-amd64
-   Database driver: mysql
-   Database version: 5.5.58-0+deb8u1-log
-   Browser: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by kousu** [comment]
I have hacked this functionality into my install by making a group named "Users" and adding this patch to kanboard/plugin-google-auth:Auth/GoogleAuthProvider.php

```
    public function authenticate()
    {
        $profile = $this->getProfile();

        if (! empty($profile)) {
            $this->userInfo = new GoogleUserProvider($profile, $this->isAccountCreationAllowed($profile));

+           $all_users_group = 2;
+           $userid = $this->userSync->synchronize($this->userInfo)["id"];
+           $this->groupMemberModel->addUser($all_users_group, $userid);

            return true;
        }

        return false;
    }
```

now everyone who successfully logs in is immediately added to the "Users" group.

I don't like my solution. I would much prefer to have something vetted and canonical. What do you think about the "Users" group being implicitly created as group 0 or group -1, and implicitly adding that group ID to to the return of `getGroups($userId)`

**Comment by finalbeta** [comment]
I have the same use case. Users are being logged in through the reverse proxy auth.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
