### ISSUE TITLE
Link to FreeOTP broken

### ISSUE THREAD

**Issue by bttrx** [kanboard/kanboard#3571]
[Two-Factor Authentication](https://kanboard.net/documentation/2fa) links to [https://fedorahosted.org/freeotp/](https://fedorahosted.org/freeotp/), which redirects to [fedorahosted.org retirement](https://fedoraproject.org/wiki/Infrastructure/Fedorahosted-retirement).

Suggested fix: Point to [https://freeotp.github.io/](https://freeotp.github.io/) instead.

**Comment by fguillot** [comment]
Thanks, the link has been updated.
