### ISSUE TITLE
Disallow reading ChangeLog

### ISSUE THREAD

**Issue by bttrx** [kanboard/kanboard#3572]
I'm no security expert, but I think it would be nice _not_ to reveal `ChangeLog`, because it shows the version number of my Kanboard installation.

Suggested fix: Add the following lines to the existing `.htaccess` file.
I've taken this from standard DokuWiki installation and adjusted it to Kanboard's needs.
```
## make sure nobody gets the htaccess, ChangeLog files
<Files ~ "^([\._]ht|ChangeLog$)">
    <IfModule mod_authz_host>
        Require all denied
    </IfModule>
    <IfModule !mod_authz_host>
        Order allow,deny
        Deny from all
    </IfModule>
</Files>
```

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
