### ISSUE TITLE
Is there some place to find customs CSS in an overview?

### ISSUE THREAD

**Issue by hubutz** [kanboard/kanboard#3573]
H,

I really think kanboard rocks but I don't like the standard interface that any more (it's kind of old fashioned) - maybe saw it too often.
I'm in no way an graphic addicted guy and will have a lot of struggels building an own theme/custom.css.

So my question is: is there some sort of place where i can find all themes/custom.css? Don't think so. What would it need to have that? I can even help with that (with maintaining the list, testing after updates and stuff).

Best
hubutz

**Comment by fguillot** [comment]
> Is there some place to find customs CSS in an overview?

Nope
