### ISSUE TITLE
Sort Order does not stick for My Tasks, My Projects, My Subtasks

### ISSUE THREAD

**Issue by compumatter** [kanboard/kanboard#3574]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
Selecting Sort dropdown reverts when selecting My Tasks, My Projects or My Subtasks

### Expected behaviour
Sort dropdown should by default stay to its last selection. This should ideally be recorded on the filesystem or database and not a cookie.

### Steps to reproduce
Click the Sort dropdown menu in My Tasks.   Now select My Tasks again.  You will notice it reverts to its default.

### Screenshots
Video Created For you:  https://www.youtube.com/watch?v=C7az-a-XZtQ

### Configuration

Application version: 1.0.48
PHP version: 7.0.22-0ubuntu0.16.04.1
PHP SAPI: apache2handler
OS version: Linux 4.4.0-98-generic
Database driver: mysql
Database version: 5.7.20-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
