### ISSUE TITLE
Allow for multiple recipients in Automatic Action: Send a task by email to someone

### ISSUE THREAD

**Issue by jsivak** [kanboard/kanboard#3576]
I see that in version 1.1.0 support for multiple email addresses has been added when sending tasks via the "Send by email" action when editing a task. (Thank you for this)

Would it be possible to add support for multiple email addresses in the Automatic Action: Send a taks by email to someone?

Thanks

**Comment by jsivak** [comment]
Howdy, I would like to try to add this feature; is there any guidance you can give me to start working on this?
I'm mainly a Python developer, so I'll have to familiarize myself with the PHP framework you're using; its Symphony right?

**Comment by sfahrenholz** [comment]
Hey @jsivak,
currently i didnt wrote any plugin in php, at [documentation](https://github.com/kanboard/kanboard/tree/master/doc ) you can finde some informations.

I using another plugin, [SendEmailCreator](https://github.com/creecros/SendEmailCreator), maybe this structur can help you.

**Comment by jsivak** [comment]
Thanks for the info: I'll look into it.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
