### ISSUE TITLE
Hide project(s) on dashboard

### ISSUE THREAD

**Issue by mrcorex** [kanboard/kanboard#3579]
When you have many projects and some of them are "sleeper" projects, on hold, etc, the dashboard get bloated. It would be nice to have an option to hide a specific project on dashboard.

**Comment by fguillot** [comment]
You can close these projects if you don't want to see them on the dashboard.

**Comment by mrcorex** [comment]
I dont want to close them? They are either sleeper projects, on hold, on planning stage etc. Close means "Done" ?

I sometime sits and building up a project before it is ready for "Open". I my mind it is wrong to work on a "Closed" project?

Am I missing something ?

**Comment by mrcorex** [comment]
I am writing a plugin that should help on this, but bumped into new issues #3586 

You can close this. The new hooks I requested should solve this.
