### ISSUE TITLE
RSS feed causes HTTP ERROR 500

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#3580]
### Actual behaviour
from httpd-log:
[Tue Nov 28 09:02:45.709288 2017] [:error] [pid] [client] PHP Fatal error:  Class 'DOMDocument' not found in /var/www/html/kanboard/vendor/miniflux/picofeed/lib/PicoFeed/Syndication/FeedBuilder.php on line 68

### Expected behaviour
I'd like to use the RSS feed.

### Steps to reproduce

This happens since I migrated the data from SQLite to MySQL.

### Configuration

Application version: 1.1.0
PHP version: 5.4.16
PHP SAPI: apache2handler
OS version: Linux 3.10.0-693.5.2.el7.x86_64
Database driver: mysql
Database version: 5.5.56-MariaDB
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by fguillot** [comment]
You have some missing PHP extensions. I updated the list here: https://github.com/kanboard/kanboard/blob/master/doc/en_US/requirements.markdown#php-extensions-required

**Comment by Chaosmeister** [comment]
PHP-xml was missing!
Thanks a lot!
