### ISSUE TITLE
Hiding tasks completed without using filters

### ISSUE THREAD

**Issue by cezaroliveira** [kanboard/kanboard#3581]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
Hiding tasks completed without using filters

### Expected behaviour
Hide tasks completed only when using filter "status:open"

### Steps to reproduce
Intermittent.
Stay in the "BoardViewController" for a moment and wait.

### Screenshots
Showing the problem:
![image](https://user-images.githubusercontent.com/34061128/33319014-0b482b4a-d424-11e7-977a-33f8fb989524.png)

Showing correctly:
![image](https://user-images.githubusercontent.com/34061128/33319045-25d720d8-d424-11e7-9dad-c56b7c47500d.png)

### Configuration

- Kanboard version: 1.0.46
- Database type and version: MySQL 5.7.11-log
- PHP version: 5.5.38
- OS: Windows 10 Enterprise 2015 LTSB
- Browser: Chrome 62.0.3202.94 (Versão oficial) 64 bits

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
