### ISSUE TITLE
Internal Error: SQL error: SQLSTATE[42S02]: Base table or view not found

### ISSUE THREAD

**Issue by bduplanty** [kanboard/kanboard#3582]
### Actual behaviour
When editing a task, the following error displays:
Internal Error: SQL error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx_kanboard.predefined_task_descriptions' doesn't exist

and full task edit screen does not display

### Expected behaviour
No error, display whole task editing screen.

### Steps to reproduce
Upgrade from prior version to 1.1.0 
using mysql database

Did not produce same error using sqlite on test system

### Screenshots
![screen_shot_2017-11-28_at_5_14_47_am](https://user-images.githubusercontent.com/33303709/33319304-4c8ab4b6-d3fb-11e7-8515-4fa5c68cb64e.jpg)

### Configuration

Application version: 1.1.0
PHP version: 5.5.38
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.18-420.el5xen
Database driver: mysql
Database version: 5.1.68-community-log
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by fguillot** [comment]
Look likes the SQL migrations didn't run properly for some reasons. When you run the migrations, make sure you have only one process that access to the database.

You could try to rerun the migrations from the command line: `./cli db:migrate` or execute the SQL manually, they are located here https://github.com/kanboard/kanboard/blob/master/app/Schema/Mysql.php. Find the one you are missing and apply them manually.

**Comment by bduplanty** [comment]
Thanks for the info.  Manually did the SQL, had to go back to "version_116".  The edit (and add) functionality has returned, and all appears to be well.

Thanks again.
