### ISSUE TITLE
Automatic action to change task color based on time left to due date

### ISSUE THREAD

**Issue by poinu** [kanboard/kanboard#3584]
### Actual behaviour
Currently we have an automatic action to assign a color to tasks whose due date has expired.

### Expected behaviour
It would be nice to 'generalize' this behaviour to assign a color to tasks when the time to their due date is less than a *parameter*.

ie.
- Assign 'yellow' color to tasks when there is less than a week left to their due date.
- Assign 'red' color to tasks when there is less than a day left to their due date.

### Screenshots
![screenshot-2017-11-30 automatic actions](https://user-images.githubusercontent.com/7153980/33426452-25d894aa-d5c2-11e7-8f7f-e45aea38a209.png)

### Configuration

- Kanboard version: from latest Docker image
- Database type and version: from latest Docker image
- PHP version: from latest Docker image
- OS: Linux
- Browser: Firefox 57

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
