### ISSUE TITLE
New hook (s).

### ISSUE THREAD

**Issue by mrcorex** [kanboard/kanboard#3586]
Since 2017-04-08 it has been possible to use 'pagination:dashboard:task:query'.

It would be nice to also have hooks for projects and subtasks i.e. 'pagination:dashboard:project:query'. :)

I have another request #3579 which you can close/throw away if this is made. I am writing a plugin that gives i.e. user defined status to control output of these lists. Then I bumped into this issue :)

Merry Christmas!!!!

**Comment by fguillot** [comment]
Sending a pull-request for this should be pretty straightforward.

**Comment by corex** [comment]
Of course. Added 2.

https://github.com/kanboard/kanboard/pull/3589
https://github.com/kanboard/kanboard/pull/3590

But I chose not to add for subtasks. I could add 'pagination:dashboard:subtask:query' but it will basically be a copy of 'pagination:dashboard:task:query'. If this is the case, please tell me and I will add it.

**Comment by corex** [comment]
I chose to make it anyway, so here it is.

https://github.com/kanboard/kanboard/pull/3592

**Comment by fguillot** [comment]
I merged your PRs. Thanks.
