### ISSUE TITLE
Ldap Groups member don't show up 

### ISSUE THREAD

**Issue by Zwordi** [kanboard/kanboard#3587]
Hello everyone,

I have an issue with ldap group that i'm gonna try to explain.

### Actual behaviour
I have my ldaps graps available through the search on Permissions tab. I can then select then whitout issue. The thing is that all my ldap groups show up like there don't have any user on it.
### Expected behaviour
I would like my users on my ldap group.

### Steps to reproduce
Go To groups> 0 Users
I have check my sladp logs and i seems to be ok on this side.
### Screenshots
![screenshot from 2017-12-01 11-08-23](https://user-images.githubusercontent.com/8830303/33478039-34d594fa-d688-11e7-8be0-5bea996f420a.png)

### Configuration
![screenshot from 2017-12-01 11-11-22](https://user-images.githubusercontent.com/8830303/33478084-65df3baa-d688-11e7-9799-269e46938901.png)

- Kanboard version: latest
- Database type and version: mariadb 10.1.26
- PHP version:  7.0.19
- OS: Linux
- Browser: Firefox and Chrmoe
- Authentication Backend : Openldap provide by Nethserver

Thanks for your nice project to have all this features out of the box.

Zwordi

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as "server configuration". If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
