### ISSUE TITLE
Synology DSM 6.2 cronjob

### ISSUE THREAD

**Issue by pcherkash** [kanboard/kanboard#3588]
In the scheduler use the script: "cd /volume1/web/kanboard && php70 cli cronjob"
DSM 6.1 everything worked, after the upgrade to DSM 6.2, I get this error: "PHP extension required: "pdo_sqlite"

Tell me how to solve it?

Версия приложения: 1.1.0
Версия PHP: 7.0.21
PHP SAPI: fpm-fcgi
Версия ОС: Linux 4.4.59+
Драйвер базы данных sqlite
Версия БД: 3.10.2

**Comment by fguillot** [comment]
You have to install/enable the extension pdo_sqlite.

**Comment by pcherkash** [comment]
Yes. without it, kanboard will not work
