### ISSUE TITLE
[Security] Cross-Site Scripting (XSS) Vulnerability

### ISSUE THREAD

**Issue by h4ckninja** [kanboard/kanboard#3591]
Hi,

You should be aware that Kanboard is vulnerable to XSS as it uses Parsedown, a library that allows attackers to inject arbitrary JavaScript. See https://github.com/erusev/parsedown/pull/495 for details.

**Comment by fguillot** [comment]
Do you know what is responsible disclosure? http://kanboard.org/#security

**Comment by h4ckninja** [comment]
Yes. Yes I do. However, this has been open for quite some time.

**Comment by fguillot** [comment]
Did you even try to reproduce the XSS mentioned on Parsedown thread?

Kanboard send CSP headers that prevent the execution of inline Javascript.

**Comment by h4ckninja** [comment]
Fair.

**Comment by SandroMiguel** [comment]
CSP is awesome

**Comment by aidantwoods** [comment]
If you'd like a patch so that CSP can go back to being defence-in-depth (instead of on the front-line), there's one available as a class-extension.

https://packagist.org/packages/aidantwoods/secureparsedown
