### ISSUE TITLE
Webhook url does not found

### ISSUE THREAD

**Issue by oteske** [kanboard/kanboard#3593]
I will send Tasks via csv to Kanboard, i have installes csv2kanboard. In the manual i can read to find out my webhook url to type "http://<kanboard_url>/?controller=config&action=webhook". I have replece <kanboard_url> with my url to the kanboard GUI. But i get only this message back "Internal Error: Controller not found"

Then i look under Settings=>Webhooks and the field "Webhook-url" is empty. I have only a webhook token. What is my mistaken????

Please help me!!!!

Many, many Thanks
Oli

### Configuration

- Kanboard version: master
- Database type and version: 3.7.13 sqlite
- PHP version: 5.4.45-0+deb7u11
- OS: Linux 4.1.19-v7+
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by fguillot** [comment]
You should ask your questions here: https://github.com/ashbike/csv2kanboard/issues
