### ISSUE TITLE
Safe to use Apache mpm_worker instead of mpm_prefork?

### ISSUE THREAD

**Issue by sadsfae** [kanboard/kanboard#3594]
### Question

I have been looking at using ```mpm_worker``` Apache MPM model over the default ```mpm_prefork``` and read differing reports around PHP and not being "thread safe".  Do you know offhand if I can start using kanboard with ```mpm_worker``` with no ill effect?

Thanks for working on such an awesome, lightweight project.

### Configuration

- Kanboard version: 1.0.47
- Database type and version: PostGresql  9.6.5
- PHP version: 5.4.16-43
- OS: CentOS 7
- Browser: N/A

```
# php -i|grep Thread
Thread Safety => disabled
```

**Comment by fguillot** [comment]
I didn't try but I assume it will work with PHP-fpm/fastcgi.

Some related information in the PHP documenttion: http://php.net/manual/en/faq.installation.php#faq.installation.apache2

**Comment by sadsfae** [comment]
@fguillot thanks, I considered using php-fpm / fastcgi to isolate the PHP processing but have read that some PHP apps are "safe" even if not "thread safe".  I was hoping some insight into how kanboard does (or doesn't do) threading it might just be ok without it.  I will look into implementing this to be safe if I move to ```mpm_worker``` as it's noticeably faster across the board for my other vhosts.

**Comment by fguillot** [comment]
Kanboard doesn't do anything specific regarding threading.

You could update this ticket to let people know if that work.
