### ISSUE TITLE
Increase maximum length for external links

### ISSUE THREAD

**Issue by poinu** [kanboard/kanboard#3595]
### Actual behaviour
When adding an external link to a task, its length may exceed the actual limit of 255 characters.

### Expected behaviour
Extend that maximum limit to something bigger.

### Screenshots
![screenshot-2017-12-5 miri 6 - simd project](https://user-images.githubusercontent.com/7153980/33623710-39c2a1fc-d9f2-11e7-8df3-6e1441ecb65d.png)

### Configuration

**Application version:** master
**PHP version:** 7.1.9
**PHP SAPI:** fpm-fcgi
**OS version:** Linux 4.9.65-1-ARCH
**Database driver:** sqlite
**Database version:** 3.20.1
**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by fguillot** [comment]
This limit has been removed in the development version.
