### ISSUE TITLE
Automatic action "Assign automatically a color based on a category"  is not executed on creation

### ISSUE THREAD

**Issue by jbarotin** [kanboard/kanboard#3597]
### Prerequisite
- I have in my dashboard actions with a category assigned let's say "foo"
- I set a new automatic action "Assign automatically a color based on a category" on the category "foo"

### Actual behaviour
- I go back to the dashboard, and I have to edit manuay all the existing tasks with the category "foo" to make the color change.

### Expected behaviour
- the color of the already existing tasks with the "foo" category change automaticaly

**Comment by fguillot** [comment]
Automatic actions are only triggered when the event occurs. It won't change the color of existing tasks.
