### ISSUE TITLE
Drag tasks in Calendar Views does not work correctly since last update

### ISSUE THREAD

**Issue by miradlo** [kanboard/kanboard#3598]
It would be great if dragging in calendar views could work again as it was before.

### Actual behaviour 
Some few tasks can still be dragged in the calendar views "my calendar" and project calendar but up to this version all tasks could be dragged without any problem

### Expected behaviour
Every task should be draggable in the calendar views.

### Steps to reproduce
Drag some tasks from a older date and try to drag them to a date in the future.

### Screenshots
none provided

### Configuration

- Kanboard version: 1.1.0
- Database type and version: Version: 5.5.56-MariaDB
- PHP version: 5.6.32
- OS: Linux 3.10.0-693.11.1.el7.x86_64
- Browser: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by fguillot** [comment]
The bug tracker for the calendar is here: https://github.com/kanboard/plugin-calendar/issues
