### ISSUE TITLE
time() or strtotime("now")

### ISSUE THREAD

**Issue by creecros** [kanboard/kanboard#3599]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
Action Stops

### Expected behaviour
Get the current time

### Steps to reproduce
use time() in an action: 
           ```$now = time();```
also tried:
          ```$now = strtotime("now");```

### Configuration

- Kanboard version: latest
- Database type and version: mysqllite
- PHP version: 7
- OS: linux
- Browser: all

**Comment by fguillot** [comment]
Same difference:

```
$ php -a
Interactive shell

php > var_dump(time() === strtotime('now'));
bool(true)
```

**Comment by creecros** [comment]
can you think of any reason why adding time() would kill the code.

tested with a simple action of sending an email with the date due as the subject. works fine. I then tried time() as the subject, and it won't even send the email. sorry, I'm clueless. not getting any error messeges in the logs.

**Comment by creecros** [comment]
nevermind, im a tard....to much coffee, typo.
