### ISSUE TITLE
Ease Access to latest version

### ISSUE THREAD

**Issue by ThomasMarkas** [kanboard/kanboard#3601]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
No easily located download link on website, kanboard.org, to latest version for installation. You have to know how git hub works to get to latest release. Not everyone uses GIT Hub and getting there from website is hit and miss.

### Expected behaviour
kanboard.org to have a hightly visible download  link to releases page in GitHub

- Kanboard version:
Latest for use

**Comment by ThomasMarkas** [comment]
This is to improve access to new users and those of us coming back to update our installation.

**Comment by ThomasMarkas** [comment]
Oh, my suggestion is to put (Download) after the latest version eg Latest Releases (Download) and put download links in other places.

**Comment by fguillot** [comment]
The installation instructions are here if you are lost: https://github.com/kanboard/kanboard/blob/master/doc/en_US/installation.markdown

By the way, there is a forum here: https://github.com/kanboard/forum/issues
