### ISSUE TITLE
Option to restore a deleted task

### ISSUE THREAD

**Issue by itsmedani** [kanboard/kanboard#3604]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
No option to restore a deleted task

### Expected behaviour
Possibility to restore a deleted card. I search on all menus but I didn't find this option

### Configuration

- Kanboard version: 1.1.0
- Database type and version: sqlite 3.7.17
- PHP version: 5.4.16
- OS: Centos
- Browser: Firefox

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
