### ISSUE TITLE
Assignee task to people

### ISSUE THREAD

**Issue by benbard** [kanboard/kanboard#3605]
This software focus on simplicity, the number of features is voluntary limited.
hello

I can not assign a task to another user. I can choose only me or Noboby

I have create many user, differents types.

**Comment by itsmedani** [comment]
Hi,

Do they have access to the project? I mean the good permissions.

**Comment by benbard** [comment]
yes i have created, user, manager and administrator to test.

**Comment by fguillot** [comment]
These users have to be member of the project.

If you have questions, the forum is here: https://github.com/kanboard/forum/issues
