### ISSUE TITLE
Unable to filter tasks and substask at the same time

### ISSUE THREAD

**Issue by itsmedani** [kanboard/kanboard#3606]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
When I filter by task and subtask for one user, the filter does not display any tasks

### Expected behaviour
Able to the see all activity for one user. Able to see his tasks and subtasks with only one filter

### Steps to reproduce
Filter like this status:open assignee:myuser  subtask:assignee:myuser

### Screenshots
It's alway filtered on the same user. As you can see, there is no cards shown

![image](https://user-images.githubusercontent.com/26568167/33773951-f106217e-dc39-11e7-9629-78c2d4530847.png)

In this one, he's the owner
 assignee:myuser
![image](https://user-images.githubusercontent.com/26568167/33773649-ea6650c4-dc38-11e7-94ac-8677953c4b71.png)

In this one, he have a subtask in this task but he's not the owner
status:open subtask:assignee:myuser
![image](https://user-images.githubusercontent.com/26568167/33773717-1a1084d4-dc39-11e7-94df-4aea41268f78.png)

### Configuration

- Kanboard version: 1.1.0
- Database type and version: Sqlite 3.7.17
- PHP version:5.4.16
- OS: Centos
- Browser: Chrome

**Comment by creecros** [comment]
I did this for someone else a while back:
- Added Filter to plugin: https://github.com/creecros/Creecros_Filter_Pack
- Added Plugin to kanboard/website#110
