### ISSUE TITLE
kanboard-v1.1.1.zip MIA

### ISSUE THREAD

**Issue by kratz00** [kanboard/kanboard#3611]
Did something change in the release process, I only see source code archives for version 1.1.1?

**Comment by vitkulov** [comment]
Someone stealed the release archive >_>

**Comment by fguillot** [comment]
Now, you can download directly the archive from GitHub on the release page:

https://github.com/kanboard/kanboard/archive/v1.1.1.zip
https://github.com/kanboard/kanboard/archive/v1.1.1.tar.gz

**Comment by vitkulov** [comment]
Thank you for direct link.
But can't view/find the release page.

**Comment by kratz00** [comment]
@fguillot I am not sure that is what I am looking for.
I know about the release page, in the past there were three files per release, the two source code archives you mentioned and third one (e.g. kanboard-v1.1.0.zip). I always used the third one to install kanboard.
So is the third one not needed anymore?

**Comment by SchmilK** [comment]
Confirming https://kanboard.net/kanboard-latest.zip downloads kanboard-1.1.0.zip

**Comment by fguillot** [comment]
The download links are there:

https://github.com/kanboard/kanboard/releases/tag/v1.1.1

<img width="825" alt="release" src="https://user-images.githubusercontent.com/323546/33901824-e9656ec0-df27-11e7-90ee-fd71be20f02b.png">

**Comment by kratz00** [comment]
I know, but like I said I am looking for the release archive (no idea  what the official name is).
![kanboard](https://user-images.githubusercontent.com/1938536/33906647-d07808fe-df82-11e7-85db-dbff282aec79.png)
If you diff the content of kanboard-v1.1.0.zip and v1.1.0.zip you will find differences, so there has to be a reason for releasing kanboard-v1.1.0.zip.
So the questions still stands what happened to kanboard-v1.1.1.zip, is it still needed or v1.1.1.zip all I need since version 1.1.1?

**Comment by olberger** [comment]
I guess what's more important is to have a signature file for the release files. Would that be automated somehow by github ?

**Comment by olberger** [comment]
Furthermore, tags up to 1.0.45 were signed, appearing as verified in https://github.com/kanboard/kanboard/tags, but that's no more the case... I'd assume that you transitioned to the new release@ key... but both aren't cross-signed... this is rather confusing IMHO.

Thanks in advance.

**Comment by kratz00** [comment]
I followed the updated installation instructions and I am successfully running Kanboard 1.2.0 now, thanks!
