### ISSUE TITLE
Filter on comments shows duplicated results when multiple comments match

### ISSUE THREAD

**Issue by cose385** [kanboard/kanboard#3612]
### Actual behaviour

If there are more comments in task that are matched with filter keyword - there will be shown multiple results of the same task.

### Expected behaviour

There should be only one same task in results.

### Steps to reproduce

Create task, add 3 comments containing same keyword, go to board view, enter filter term with that keyword in comments (comment:keyword) and you'll see duplicated results.

### Screenshots

![image](https://user-images.githubusercontent.com/25780896/33876476-f323cf6c-df25-11e7-8cf8-eb0590665ec0.png)

### Configuration

- Kanboard version: 1.0.48
- Database type and version: MySQL 5.6.26
- PHP version: 5.6.12
- OS: Windows
- Browser: Google Chrome

**Comment by phil-flex** [comment]
I also have this problem. Is it possible to add "distinct" keyword in the query SQL? it may be the duplicated taskId being selected, adding distinct may fix the problem. But I am not familiarize with PHP query so I don't know how to add distinct in the SQL statement.
