### ISSUE TITLE
LDAP User not working

### ISSUE THREAD

**Issue by jack1729** [kanboard/kanboard#3615]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
I have 14 users that are authenticating via LDAPS (AD) with no problem.  I have one user that fails, here is an except of the logs:
[2017-12-13 10:39:20] [debug] Filter=(&(objectCategory=person)(objectClass=user)(cn=XXXXXXX))
[2017-12-13 10:39:20] [info] Authenticate this user: CN=XXXXXXX=Users,DC=abcd,DC=com

it acts like it isn't even trying to authenticate.  If I create the account as local, he is working.

I have recreated kanboard account and what is working now is to create his kanboard account as local user with the same XXXXXXX.  I know see this:
[2017-12-13 11:50:42] [error] LDAP authentication failure for "CN=XXXXXXX,CN=Users,DC=abcd,DC=com" => Code="49"; Error="Invalid credentials"; ExtendedError="80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580"

which I think means it is trying to authenticate against LDAP and fails which causes it to use the local userid/password.

### Expected behaviour
I expect him to login with no issues using his AD account.

### Steps to reproduce
I can use ADSIEdit to reproduce the query that is being executed by kanboard and it works no problems.  I wonder if strange characters in the user's password is causing issue ')' and asked him to change it at his next password reset cycle.

I have verified he is using the correct userid/password.

### Screenshots
just Bad Username or Password on login screen.

### Configuration

◾ Application version: 1.1.0 
◾ PHP version: 7.0.21 
◾ PHP SAPI: cgi-fcgi 
◾ OS version: Windows NT 6.3 
◾ Database driver: sqlite 
◾ Database version: 3.14.2 
◾ Browser: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0; zoomrc 4.4.0)

**Comment by fguillot** [comment]
Looks like you have the same problem as #3354

Your LDAP server returns `Code="49"; Error="Invalid credentials"; ExtendedError="80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580`.

Do you have any specific security settings for ActiveDirectory?

**Comment by jack1729** [comment]
Not that I can think of.

On 2/22/2018 4:24 PM, fguillot wrote:

Looks like you have the same problem as #3354<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkanboard%2Fkanboard%2Fissues%2F3354&data=02%7C01%7C%7C3b457bc37fec4585208208d57a3aa235%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636549314593255442&sdata=IDnGVQ7NCMJp2VQZe3y1vRQpYEWZsZ4gz8RkNlzmnUY%3D&reserved=0>

Your LDAP server returns Code="49"; Error="Invalid credentials"; ExtendedError="80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580.

Do you have any specific security settings for ActiveDirectory?

**Comment by register99** [comment]
Hello, maybe the Issue in the other referenced Ticket #3354 is a simple typing error.
If the config.php is a real example there, then maybe ... the the **FASLE** instead of **FALSE** could be the problem.

The row out of the config.php:
// By default, require certificate to be verified for ldaps:// style URL. Set to false to skip the verification
define('LDAP_SSL_VERIFY', fasle);

**Comment by bkraul** [comment]
Actually, this error may be related to a problem with special characters being used in the password. The same authentication config settings work perfectly for accounts without the following characters in the password: !"#$%&'()*+,-./:;<=>?@[]^_`{|}~

Could there be an issue with needing to escape these characters?

**Comment by bkraul** [comment]
More info here:

https://stackoverflow.com/questions/12858493/php-ldap-bind-fails-when-password-contains-ampersand

**Comment by jack1729** [comment]
I have also found the user can be case sensitive.

On 8/2/2018 2:57 PM, bkraul wrote:

Actually, this error may be related to a problem with special characters being used in the password. The same authentication config settings work perfectly for accounts without the following characters in the password: !"#$%&'()*+,-./:;<=>?@[]^_`{|}~

Could there be an issue with needing to escape these characters?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.13/developer_guide/faq.html).
