### ISSUE TITLE
cannot make kanboard  v1.1.0 work with php7.0-fpm/nginx/sqlite: timeout error

### ISSUE THREAD

**Issue by benIT** [kanboard/kanboard#3617]
I just installed [Kanboard v1.1.0](https://github.com/kanboard/kanboard/releases/tag/v1.1.0) from the zip archive (already built) but when I tried to access kanboard in my browser I get a `504 gateway timeout` error.
Here is my `kanboard.conf` nginx vhost : 

```
server {
    listen 8080;
    root /vagrant/shared/kanboard;
    index index.php;
    autoindex on;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;

        # If Kanboard is under a subfolder
        # try_files $uri $uri/ /kanboard/index.php;
    }

    location ~ \.php$ {
        #If a file isn’t found, 404
        try_files $uri =404; 
        #Include Nginx’s fastcgi configuration
        include /etc/nginx/fastcgi.conf;
        #Look for the FastCGI Process Manager at this location 
        fastcgi_pass unix:/run/php/php7.0-fpm.sock; 
    }

    # Deny access to the directory data
    location ~* /data { 
        deny all;
        return 404;
    }

    # Deny access to .htaccess
    location ~ /\.ht { 
        deny all;
        return 404;
    }
}
```

For debugging purpose I add a `phpinfo.php` file at the root of kanboard, I get the phpinfo file page served normally.

Edit:
**After switching to a mysql database: the application is now running fine. The issue comes from sqlite.**

I changed db conf in `config.php`:
```
define('DB_DRIVER', 'sqlite');
define('DB_USERNAME', 'root');
define('DB_PASSWORD', '');
define('DB_HOSTNAME', 'localhost');
define('DB_NAME', 'kanboard');
```

to:
```
define('DB_DRIVER', 'mysql');
define('DB_USERNAME', 'kanboard');
define('DB_PASSWORD', 'kanboard');
define('DB_HOSTNAME', 'localhost');
define('DB_NAME', 'kanboard');
```

Database has been created as follow:
```
 sudo mysql -uroot -e "CREATE DATABASE kanboard;"
 sudo mysql -uroot -e "CREATE USER 'kanboard'@'localhost' IDENTIFIED BY 'kanboard';"
 sudo mysql -uroot -e "GRANT ALL ON kanboard.* TO 'kanboard'@'localhost'"

```
My configuration is:

- webserver:  nginx/1.10.3
- Kanboard version: v1.1.0
- Database type and version: sqlite
- PHP version: 7.0.19-1
- OS: linux ubuntu 17.10
- Browser: chromium, firefox

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as "server configuration". If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
