### ISSUE TITLE
LDAP groups and userdefined roles

### ISSUE THREAD

**Issue by rajo** [kanboard/kanboard#3619]
### Actual behaviour
We use LDAP to sync groups and assign project permissions. We use user-defined roles.
If a project has its permissions set to a ldap group as e.g. project member, we can select users from within that group and assign tasks to them. 
If a project has its permissions set to a ldap group as a user-defined role, even without any restrictions, we cannot select users from within that group and assign tasks to them.

### Expected behaviour
Be able to assign user-defined roles to ldap-groups and still assign the users of those groups to a task

### Steps to reproduce
- Set up LDAP with groups
- Create an user-defined role
- Grant permissions to a ldap-group with this role
- Try to assign a task to an user of this ldap group

### Configuration

- Kanboard version: 1.0.48
- Database type and version: mysql 5.5.58
- PHP version: 5.6.3
- OS: Debian Jessie
- Browser: Any

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
