### ISSUE TITLE
CLi cronjob not working

### ISSUE THREAD

**Issue by eleson2** [kanboard/kanboard#3620]
This software focus on simplicity, the number of features is voluntary limited.
crontab -l : 
`00 12 * * * cd /kanboard/var/www/html/kanboard-1.1.1 && ./cli cronjob >>/tmp/kanboard-cli.log 2>&1`
### Actual behaviour
/tmp/kanboard-cli.log: 

```
  [PicoDb\SQLException]
  SQL error


cronjob
```

### Expected behaviour
Atleast no errors.
any pointer as to where to look further is appreciated.

### Steps to reproduce
Don't know if there is one, problem may be in my setup.

### Configuration

> Application version: 1.1.1
> PHP version: 5.4.16
> PHP SAPI: apache2handler
> OS version: Linux 3.10.0-327.36.3.el7.s390x
> Database driver: mysql
> Database version: 5.5.52-MariaDB
> Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
>

**Comment by fguillot** [comment]
You should enable the debug mode to see the exact SQL error.

**Comment by eleson2** [comment]
Tnx.
I choosed to set up a script to run the command above and made sure setting up the env correctly ,
and now it works!
