### ISSUE TITLE
Bug: Moving task between columns behaves unexpectedly

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#3625]
### Actual behaviour

When I attempt to move a task in to a column, sometimes a dashed line **does not** appear around the task.  If I release the task at this point, it will move the task into a different column (often on a completely different swimlane)

![movetask](https://user-images.githubusercontent.com/1220211/34103909-389ecaaa-e3e6-11e7-8b14-33a43ff248e1.png)
(example of moving task with no dashed border)

Strangely, it does actually put "Moved task to [name of correct column]" in the comments (triggered by an automatic action), but moves it to the wrong column (and swimlane) :S

### Expected behaviour

That a task is moved to the column that it hovers over.

### Steps to reproduce

Try to move a task between columns.  It seems very inconsistent.  Sometimes this behaviour happens, sometimes it doesn't.  The board it affects is a relatively large one (~2000 tickets spread across 9 columns & 5 swimlanes ... it gets a bit laggy if you have no filters at all on it.  

### Configuration

Application version: 1.1.1
PHP version: 7.0.22-0ubuntu0.16.04.1
PHP SAPI: apache2handler
OS version: Linux 4.4.0-78-generic
Database driver: postgres
Database version: 9.5.2
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.97 Safari/537.36 Vivaldi/1.94.1008.36   (Vivaldi 1.13, but bug was initially found on the latest Google Chrome)

**Comment by neiaberau** [comment]
I notice the same or simlilar issue several times, no dash lines appearing the the task moved to some other area.  Found this when I wanted to report the behaviour.

**Comment by neiaberau** [comment]
demo MP4, rerpduced, with another browse and a small testinstallation

[Microsoft Edge 16.02.2018 16_22_20.mp4.zip](https://github.com/kanboard/kanboard/files/1731809/Microsoft.Edge.16.02.2018.16_22_20.mp4.zip)

**Comment by neiaberau** [comment]
I have to say, this is the an annoying issue for, me, having to search for task that got moved somewhere unexpected. Does nobody else have this issue regularly?

I tried looking at the code to find the issue, but it do no understand where in the Controller code this happens, but then again, I do not have any knowledge about php.

**Comment by fguillot** [comment]
Is it happening when someone else is moving the same task?

**Comment by sandromario** [comment]
No, I'm the only user of my board.

**Comment by neiaberau** [comment]
in may case it is a private board, so no other users involved

**Comment by fguillot** [comment]
Is it a large board with a lot of tasks (>100) as mentioned in the initial issue?

**Comment by sandromario** [comment]
It has more than 100 tasks, yes, but
a) I don't consider 100 tasks "a lot". 10000+ sounds like "a lot" to me personally, especially given that I'm using a mysql database.
b) I'm not 100% sure, but if I remember correctly this behaviour was unrelated to the number of tasks present. To reiterate, I'm not sure.

**Comment by sandromario** [comment]
Exactly, yes, plus, it's very erratic whether the dashed lines appear at all.

**Comment by neiaberau** [comment]
plain docker installation still has this issue, 
when bigboard plugin is installed, I cannot reproduce this anymore

**Comment by loonies** [comment]
We (at our organization) are also experiencing this behaviour. I believe it's a UI issue. At times it's hard to get the "selection" rectangle to target the desired spot. The board in question has over 200 cards.

**Comment by fguillot** [comment]
Well, I'm not able to reproduce the issue on my side.

I tested on Chrome, Firefox, and Safari. I created hundred of tasks into each columns. Moved tasks around without problem. No plugin installed.

Some troubleshooting on your side will be appreciated to tackle this issue. I'm wondering if this is related to jQuery-ui or a plugin that breaks something.

**Comment by neiaberau** [comment]
unable to reproduce, did you look at the video I attached?
(as said above it might be not relavant to all cases, however it is reproducable  on windows 10 on edge, Firefox and chrome)

**Comment by fguillot** [comment]
Yes, I saw your video. I do not have a Windows machine at the moment (I have to test with a virtual machine).

**Comment by neiaberau** [comment]
ok I see. I  just tested Chrome (67.0) on android (8.0) phone, there it is happening as well, therefore I think it is rather browser related not operating system related,

**Comment by neiaberau** [comment]
I setup a VM with ubuntu and Firefox, there it is happening as well

**Comment by stinnux** [comment]
I was able to reproduce it also. Using the latest master version without any plugins. Browser was chrome under Mac OS X.

If you try hard enough you will manage to move the task outside of the dropzone when dragging it out of the board. When dragged back it will not know where it is and when dropping it will be placed somewhere else. 

No JavaScript errors printed to the console, so i assume it is a jquery bug.

**Comment by fguillot** [comment]
I updated jQuery to the latest version in the master branch. Can someone test the development version to see if that fix the issue on your side?

**Comment by neiaberau** [comment]
with the latest docker image, it unfortunately still happens

Application version: master.0fc847f5723fb51b32a7141e8eb5017813b43687

**Comment by stinnux** [comment]
Still happens for me also.

https://www.amazon.de/clouddrive/share/7m767mzQhIiZHwxozRoVAnMIhXbT34uBAL7I8pYymmJ

**Comment by tuxayo** [comment]
Does anyone else knowing the code know what we should log/check with the inspector when we get the issue?

**Comment by tuxayo** [comment]
Something strange that might eventually hopefully help (or just add confusion)
- I cloned my problematic board
- The test board still had the issue
- I closed all the tasks in the finished column (more than 3/4 of all tasks)
- The issue was gone
- I removed the status:open filter
- the issue was still gone in the test board. Even though it's showing the same number of tasks as the "production" one
- the issue was still happening on the production board

**Comment by tuxayo** [comment]
Can someone try the test plan of #4011 and the [bonus](https://github.com/kanboard/kanboard/issues/4011#issuecomment-420950810) that might trigger this issue?

**Comment by rafacamargo123** [comment]
I'm also experiencing this issue in my company. 
Today I saw [this commit](https://github.com/kanboard/kanboard/commit/14d141130084b0c0a28b70f587af03b3cd124d32), applied this change (replaced `connectWith:".sortable-column"` with `connectWith:".sortable-column:visible"` on `assets/js/app.min.js`) and the problem disappeared!

**Comment by tuxayo** [comment]
This is a very very good news that #4011 might be related.

@fguillot Is this enough to be worth a release? (at least beta)

**Comment by tuxayo** [comment]
Thanks a lot! 14d141130084b0c0a28b70f587af03b3cd124d32 has been released in v1.2.6

We will see in the next week if anyone upgrading to v1.2.6 still gets this bug.

**Comment by tuxayo** [comment]
On my instance, this issue has been resolved in v1.2.6 :tada:

I have never triggered it again since upgrading to this version.

**Comment by neiaberau** [comment]
I also cannot reproduce anymore with a recent version of kanboard, so this looks ok now.

**Comment by tuxayo** [comment]
@AlgyTaylor Can this issue be closed?

**Comment by AlgyTaylor** [comment]
Yeah, it can :)
