### ISSUE TITLE
Alter role of all LDAP users

### ISSUE THREAD

**Issue by wiltonsr** [kanboard/kanboard#3626]
I have an OpenLDAP server where I cannot make any modification.
I configure the config.php with
LDAP_USER_BASE_DN = 'ou=users,dc=example,dc=com'
With this I can connect on Kanboard with LDAP users, but all my users have the role app-user. 

There is any way to define the role of all my LDAP users to Manager without add a group into my LDAP server?

Thanks for Kanboard.

### Actual behaviour

Manage roles from LDAP groups.

### Expected behaviour

Add a role to all LDAP users.

### Configuration

- Kanboard version: 1.1.0
- Database type and version: Postgres 9.4.15
- PHP version: 5.6.30
- OS: Debian 8 Linux 3.16.0-4-amd64
- Browser: Mozilla/5.0

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
