### ISSUE TITLE
Markdown parser fails

### ISSUE THREAD

**Issue by janHbre** [kanboard/kanboard#3627]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
At one time, http-links in markdown in comments and task description works and in the next moment it fails with the message "OK The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.".

### Expected behaviour
Markdown formatted Link entry saved without error.

### Steps to reproduce
Enter Markdown http Link with formatting [Link](http://link...) two times after another and the second time will fail.

### Configuration

- Kanboard version: 1.1.1
- Database type and version: MySQL 
- PHP version: 7.0
- Server: Apache / Strato hosted
- Client OS: Windows
- Browser: Firefox

**Comment by fguillot** [comment]
You should take a look to the logs to understand what is going on.

**Comment by janHbre** [comment]
Thank's very much for the fast reply!

This [debug.log](https://github.com/kanboard/kanboard/files/1578201/debug.log) was created when trying to add markdown http link to an existing comment. The same behavior occurs when simply adding a http link (without markdown). Do you have any ideas?

Cheers, Jan

**Comment by fguillot** [comment]
You should take a look to the Apache logs, perhaps your hosting provider is doing some weird shenanigans. Make sure mod_security is disabled.
