### ISSUE TITLE
error: missing dom-extension in installation instructions

### ISSUE THREAD

**Issue by ToxyLT** [kanboard/kanboard#3628]
### Error message after Installation
After following the installation instructions on https://github.com/kanboard/kanboard/blob/master/doc/en_US/ubuntu-installation.markdown I got the following error message when I try to open the website http://localhost/kanboard-1.1.1/ :
_Internal Error: This PHP extension is required: "dom"_.
Because I know absolutely nothing about things like php I had a long search before I found the 
### Solution:
After installing the missing extension with 
`sudo apt-get install php-xml`
everything works fine. I think you could spare many new users a few hours of frustration, if you add this command to the installation instructions

### Configuration

- Kanboard version: 1.1.1
- Database type and version:
- PHP version: 7.0
- OS: ubuntu 16.04 (Linux Mint 18.1)
- Browser: Firefox

**Comment by froschdesign** [comment]
@ToxyLT 
This is already included in the requirements: https://github.com/kanboard/kanboard/blob/master/doc/en_US/requirements.markdown#php-extensions-required

>  …if you add this command to the installation instructions.

The PHP-DOM extension is enabled by default and the command will not work on shared hosting.

**Comment by ToxyLT** [comment]
I understand that only computer professionals are living here on github. But I'm not and I only want to use Kanboard for my projects. So my only chance is to follow the installation instructions by the letter. The above mentioned instructions for Ubuntu didn't work. I had to install the php-xml additionally. As I searched for this solution a few hours, it is only fair to other new users that they find installation instructions that work right from the beginning.
I write this, because I find it worth, that more people (not only software programmers) can use this project management tool.

**Comment by froschdesign** [comment]
@ToxyLT 
> I understand that only computer professionals are living here on github.

No, I'm not a server administrator or the like. But if I want to install this or other applications myself, then I need some basics.

> …it is only fair to other new users that they find installation instructions that work right from the beginning.

And then we have the next problem: the install command will not work on a shared hosting server.

---

Please don't get me wrong, I like your intention, but not every topic can covered by the documentation. The documentation says you need PHP with some standard extensions, which are **enabled by default** in PHP! Why should the installation of these extensions be described then?
If something missing on your system, then look at the PHP documentation and you will find the install command: http://php.net/manual/en/book.dom.php

**Comment by fguillot** [comment]
I updated the documentation.

If something is not up to date or inaccurate, you could edit easily the documentation from GitHub user interface and send a pull-request.
