### ISSUE TITLE
Duplicate task to multiple projects, but as an optional link only between some projects

### ISSUE THREAD

**Issue by adrianovieira** [kanboard/kanboard#3629]
**I'm submitting a ..**
- [ ] Bug Report
- [x] Feature/Improvement Request

I've noticed that you already have *Duplicate to multiple projects* feature.

What if you have an option there where a task for multiple projects which can work as link only for some of those projects.

So, for that project which have a linked task it has it in read only mode, but could see all the updates done by/on the original project.

Thence, every project that needs follow up or infos about that task will have it syncronized accordinly to the updates done by the responsible to do it. Furthermore, you don't have to add users/members into a bunch of projects where they don't need to be added.

**Comment by kgeil** [comment]
This is a great idea!  I'm trying to build out kanboard usage to my whole team (instead of just a couple of individuals), and this would be very helpful for more visibility.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
