### ISSUE TITLE
Structure of swimlanes and the columns are different

### ISSUE THREAD

**Issue by sfahrenholz** [kanboard/kanboard#3630]
Hello,

i didnt found a similar issue for this "bug" so i opend a new one. If already a issue exists, so please close this.

im trying the kanboard an add to a project two swimlanes. The sorting or displaying of the colums of every swimlanes looks not correct. 
for the first swimlanes the columns titles are outside of the swimlane. For the seconds swimlane there are inside.

The installation is the default. no specify configs.

### Actual behaviour
![current](https://user-images.githubusercontent.com/6977657/34266759-b26f59f8-e67a-11e7-82db-08303845759b.PNG)

### Expected behaviour
![expected](https://user-images.githubusercontent.com/6977657/34266760-b28e2fd6-e67a-11e7-8ea3-01b58dce853e.PNG)

### Steps to reproduce
- Install Kanboard
- Add a second swimlane

### Configuration

Kanboard version: 1.1.0
PHP Version: 7.0.22-0ubuntu0.17.04.1
PHP SAPI: apache2handler
OS Version: Linux 4.10.0-42-generic
Datenbanktreiber: sqlite
Datenbank Version: 3.16.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by fguillot** [comment]
Duplicate with https://github.com/kanboard/kanboard/issues/2575
