### ISSUE TITLE
Add extra application role procedure

### ISSUE THREAD

**Issue by alexauser** [kanboard/kanboard#3636]
Hi,
First of all thanks for the software.

Last days i try to analyze the code structure because i want to extend for my personal needs and i have some questions.

1.) The kanboard is written on some php framework or use and combine composer packages?
2.) What is the request path in application?
3.) Is there a diagram showing the structure of the classes and functions?
4.) There are guidelines and examples for plugins development?

At an early stage, i want to add a custom application role or extend restrictions for the role inside project. Which parts of the application code are involved in this process?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
