### ISSUE TITLE
error: Export / import of tasks: different order of columns

### ISSUE THREAD

**Issue by ToxyLT** [kanboard/kanboard#3639]
### Actual behaviour
export of tasks creates a csv-file with the following columns:
"Task Id",Reference,Project,Status,Category,Swimlane,Column,Position,Color,"Due date",Creator,"Creator Name","Assignee Username","Assignee Name",Complexity,Title,"Creation date","Modification date","Completion date","Start date","Time estimated","Time spent",Priority,Tags

### Expected behaviour
The csv-template on the "import tasks" site inside the program has the following columns:
Reference,Title,Description,"Assignee Username","Creator Username","Color Name","Column Name","Category Name","Swimlane Name",Complexity,"Time Estimated","Time Spent","Start Date","Due Date",Priority,Status,Tags,"External Link"

Only this order of columns can be imported into Kanboard. So obviously the export-function works wrong

### Configuration

- Kanboard version: 1.1.1
- Database type and version: sqlite
- PHP version: 2.0
- OS: Linux Mint 18.1 (ubuntu 16.04)
- Browser: Firefox

**Comment by froschdesign** [comment]
@ToxyLT 
> So obviously the export-function works wrong.

I think "wrong" is not correct here, because the current behavior of import and export is not described and with the template for the import it works _obviously_ as intended.
It's not consistent, but it's not wrong. 😉 

@fguillot 
The documentation for import and export is missing or I did not find it.

Btw. why is this function in the core? Import and export are perfect candidates for plugins. This opens the door for more formats than CSV.

**Comment by ToxyLT** [comment]
o.k. inconsistent!
I used the export function as backup for my project. The import back into the data base (or a new data base) didn't work. So the export is obviously only usable for Excel or Calc and not for Kanboard. What a pity!
I think it is very easy to make the two functions compatible by modifying the order of the columns for the export. Most likely it is no disadvantage for other uses, if the order is modified.

**Comment by froschdesign** [comment]
@ToxyLT 
> What a pity!

First: I am not the programmer or volunteer on this project, but please pay attention to your tone. This is an open source project and if you miss something, then you can ask for that or make a suggestion. _(imo)_

> I used the export function as backup for my project.

Backup the database. The import and export function is the wrong way.

**Comment by ToxyLT** [comment]
@froschdesign 
Sorry, I didn't want to sound unfriendly (and don't know where I did). I'm not a native speaker of the English language, so please forgive me, if I used the wrong words.
I appreciate fguillot's work and your support very much and thank you for your altruistic engagement.
My intuition was to support the software with my experiences as an inexperienced user. I know from my own work that it is always good to have people look at your projects who are not involved, because they use things differently than you expected.
So, keep it up and best wishes for the new year!

**Comment by sfahrenholz** [comment]
I try to reproduce with the 1.2.0 but always i get the message "Nothing have been imported!". The project is the identical (same columns, swimlanes etc).
When i have time so i give 1.1 a next try.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
