### ISSUE TITLE
error: plugins not working / installation problems

### ISSUE THREAD

**Issue by ToxyLT** [kanboard/kanboard#3640]
### Actual behaviour

1. Installation of plugins inside of Kanboard does not work:
 "Your Kanboard instance is not configured to install plugins from the user interface."
2. Unpacking of zip files in the plugin directory does not work, because the directory of the plugin has the wrong name, e.g. "plugin-calendar-master" instead of "calendar"
3. renaming the directory lists the plugin in "installed Plugins" window inside Kanboard, but the functionality is not there (no calendar or gantt buttons in the project window).

I tested it with the calendar and the gantt plugins.

### Configuration

- Kanboard version: 1.1.1 (standalone on a single PC - local server)
- Database type and version: sqlite
- PHP version: 2.0
- OS: ubuntu 16.04
- Browser: Firefox

**Comment by fguillot** [comment]
Did you read the docs?

**Comment by ToxyLT** [comment]
yes, hours. But if you ask so, I obviously missed something?

**Comment by fguillot** [comment]
- To be able to install plugins from the user interface, you need to install the zip PHP extensions (https://github.com/kanboard/kanboard/blob/master/doc/en_US/requirements.markdown#optional-php-extensions) and make sure the `plugins` folder is writeable by the web server user (ie `www-data` if you use Ubuntu), and the config param `PLUGIN_INSTALLER` should be enabled (which is the case by default)
- If you want to install the plugins manually, do to not download the archive provided by GitHub but the one available on the releases page. For example, you can download the Calendar plugin here https://github.com/kanboard/plugin-calendar/releases/download/v1.1.0/Calendar-1.1.0.zip. The folder hierarchy should looks like: `your-kanboard-folder/plugins/Calendar`.

**Comment by ToxyLT** [comment]
@fguillot Thanks! After I added the zip extension and restarted the computer, the plugins work now:
`sudo apt-get install php-zip`
Sorry for the late answer -I was in holidays ;-)
