### ISSUE TITLE
admin should not be able to set himself to the role "manager"

### ISSUE THREAD

**Issue by ToxyLT** [kanboard/kanboard#3641]
### Actual behaviour
The admin can set himself to the role manager (or lower). It is not possible to become administrator again. 

### Expected behaviour
At least one admin should be fix. Only additional users should be allowed lesser roles.

### Configuration

- Kanboard version: 1.1.1 (on local server)
- Database type and version: sqlite
- PHP version: 2.0
- OS: ubuntu 16.04
- Browser: Firefox

**Comment by kousu** [comment]
Oh awkward. Did you manage to fix this? Probably you'd have to go in with sqllite and tweak settings at that level, I'd imagine.

I sort

**Comment by ToxyLT** [comment]
I'm only a simple user with no knowledge of data bases, so I took the easy way: I exported my only project to csv, emptied the "data" directory an began with kanboard from scratch. The import attempt led me to the next problem (see my other thread about import/export) as the no admin problem was the result of my problems with the plugins where I read in the forum that only managers can see the gantt view ...

**Comment by sfahrenholz** [comment]
Another way is the portable edition of "DB Browser for SQLite" and then following sql statement
`UPDATE users
SET is_admin = 1,
    role = 'app-admin' 
where users.id = {id}`
For the {id} value insert the number of the user. Alternative instead of _users.id = {id}_ can be used _users.username = "admin"_

**Comment by ToxyLT** [comment]
As the portable edition is an .exe-file I think it's only for Windows. But for Linux (Ubuntu / Linux Mint) sqlitebrowser is in the repositories and therefore easy to install.
When I see it right, the modifications can be done also without sql-code directly in the sqlite browser under the "browse data" tab in the table "users". You have to open the data base (db.sqlite in the data-directory) with administrator-rights to be able to modify the data. Otherwise it is opened read-only.

**Comment by sfahrenholz** [comment]
i try a little bit maybe a new validator can be help, to check if already a user with admin-rights exists. This is only an example.. @fguillot how can i add a new validator? All tries are failed, because kanboard can not found it...

```
<?php
namespace SimpleValidator\Validators;
use PDO;
class UserWithAdminRightsExists extends Base
{
    private $pdo;
    private $table;
    private $roleName;
 
    public function __construct($field, $error_message, PDO $pdo, $table)
    {
        parent::__construct($field, $error_message);
 
        $this->pdo = $pdo;
        $this->table = $table;
        $this->roleName = "app-admin";
    }
 
    public function execute(array $data)
    {
        if (! $this->isFieldNotEmpty($data)) {
            return true;
        }
 
        $rq = $this->pdo->prepare('SELECT 1 FROM '.$this->table.' WHERE '.$this->field.'= ?');
        $rq->execute(array($roleName));
 
        return $rq->fetchColumn() >= 1;
    }
}

```

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
