### ISSUE TITLE
Question about Swimlines and + buttons

### ISSUE THREAD

**Issue by emanueledf** [kanboard/kanboard#3643]
Ciao , a graphical question about swimlines and task buttons.
 In case of board with multiple swimlines, I see they behave differently between the default swimline and the new one

### Actual behaviour
+ buttons above defaultswimline name, but below newswimline name

### Expected behaviour
+ button in the same position in every  swimline 
on choice can be : + button  inside the swimline 

### Screenshots

![screen shot 2017-12-28 at 17 31 06](https://user-images.githubusercontent.com/6025295/34416999-7db1b7f2-ebf6-11e7-9beb-55d6a054106f.png)

Do you think it will make sense? graphically it would appear much cleaner.

Thanks for your work.
Happy holidays!
EM.

**Comment by sfahrenholz** [comment]
Hey @emanueledf,
thank you for using kanboard.

This issue is already known under the issue #2575.

**Comment by fguillot** [comment]
Closing duplicate
