### ISSUE TITLE
View or export transition history of active tasks in the board or in a certain column

### ISSUE THREAD

**Issue by Danoposada** [kanboard/kanboard#3644]
Hello.
So, some of the task we create begin life in "Project A", but through an auto-action are moved to "Project B" when they end their life-cycle.

Now, this tasks that end up in "Project B" have each an individual transition history, independent of the transitions of "Board B" Itself.

If I enter each task I can see their individual transitions, no problem. But If I try to export transitions in "Project B", it exports only the transitions made in "Project B", not the transitions of the task themselves.

Is there a way to make Kanboard export or show the transition history of the tasks themselves, in bulk?
Any info would help.

Thanks.

### Actual behaviour

Kanboard can export the transition history of a project, but not of the tasks themselves.
Transition history of each task is viewable individually, but not in bulk, and this info is not exportable.

### Expected behaviour

Some method to view or export the individual transition histories of tasks in a column or a project.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
