### ISSUE TITLE
Pass validation errors to API caller

### ISSUE THREAD

**Issue by cl0ne** [kanboard/kanboard#3651]
### Actual behaviour
When API caller submits an invalid value in request, all validation errors are simply ignored. The caller get's obscure value `false` and this makes API client debugging harder. I will use as an example [createTask](https://github.com/kanboard/kanboard/blob/0d20435f9e4c60a45d21819312a19401d628b72c/app/Api/Procedure/TaskProcedure.php#L130) procedure, but this issue is related to many other procedures.

### Expected behaviour
According to current documentation, this **is** an expected behaviour. My proposition is to let the caller know what's wrong with request. It can be done by passing validation errors in response.

### Steps to reproduce
1. Call API procedure `createTask` with argument `date_due` set to `'2017-12-10T10:00:00.000Z'`.

    According to [validation rules](https://github.com/kanboard/kanboard/blob/0d20435f9e4c60a45d21819312a19401d628b72c/app/Core/DateParser.php#L157) this is not a vaild date, request will fail.
2. Check JSON response - it has `result` field set to `false`, but doesn't contain `"Invalid date"` validation message.

### Configuration
- Kanboard version: 1.2.0

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
