### ISSUE TITLE
Limited ISO8601 support in combined date and time

### ISSUE THREAD

**Issue by cl0ne** [kanboard/kanboard#3652]
This issue is related to #1398 and #69, so this could be posted as a comment to any of that issues.
 
For example, according to ISO8601 `2017-12-10T10:00:00.000Z` **is** a valid date. But validators will reject it since it doesn't match any of [datetime formats](https://github.com/kanboard/kanboard/blob/0d20435f9e4c60a45d21819312a19401d628b72c/app/Core/DateParser.php#L157).

Also ISO 8601:2004(E) states: "4.3.2 NOTE: By mutual agreement of the partners in information interchange, the character [T] may be omitted in applications where there is no risk of confusing a date and time of day representation with others defined in this International Standard."

### Actual behaviour
API procedure calls (and anything that relies on validation) will reject valid ISO8601 datetime value, for example, `2017-12-10T10:00:00.000Z`.

### Expected behaviour
API procedure calls should not reject valid ISO8601 date and time values or documentation should be changed to reflect this behaviour.

### Steps to reproduce
1. Call API procedure `createTask` with argument `date_due` set to `"2017-12-10T10:00:00.000Z"`.
2. Check JSON response - `result` field contains `false`.

### Configuration
- Kanboard version: 1.20

**Comment by XBase-xOR** [comment]
As it is now the option to set a due date is mostly useless. Only a date can be specified but the time is then taken from the current time, resulting in a date time combination that doesn't make sense in any given situation.

I wanted to change this but I am not familiar with the Kanboard code. But as a small experiment I took **/app/Core/DateParser.php** from 1.2.6 and in the function getParserFormats() I added this item to the array:

`'Y-m-d\TH:i:s.u\Z',`

That's all I did. And now whereas before a call to createTask with "2017-12-10T10:00:00.000Z" would fail it now succeeds and creates a task with the correct due date and time.

Is it really that simple or am I missing something?

**Comment by levitte** [comment]
I've been wondering about the same kind of thing (along with the display options, which should really be tied to the used locale, but that's for a different issue).  Given time, I might be able to produce a PR.

**Comment by fguillot** [comment]
@cl0ne Only the date formats defined in `DateParser::getParserFormats()` are supported. If you need something else, send a patch.

**Comment by cl0ne** [comment]
> @cl0ne Only the date formats defined in `DateParser::getParserFormats()` are supported. If you need something else, send a patch.

API documentation, for example, for createTask procedure states that it accepts
> date_due: **ISO8601 format** (string, optional)

This issue emphasises actual date format support mismatch with declared in the documentation and proposed solution was to either make ISO8601 support more complete or make corrections to the documentation:
> API procedure calls should not reject valid ISO8601 date and time values
> or
> documentation should be changed to reflect this behaviour.

I found this incompatibility at least surprising, trying to import Trello board into KanBoard.
