### ISSUE TITLE
Timezone for datetime values supplied to API is not documented?

### ISSUE THREAD

**Issue by cl0ne** [kanboard/kanboard#3654]
It's not clearly stated in documentation what timezone should I use for datetime values in API procedure calls. Behaviour and steps to reproduce are described for User API, but the question is relevant to Application API as well.

### Actual behaviour
Displayed due date is `'2017-12-10 03:00'`. The difference is `-7` hours &ndash; server uses timezone set for application to convert received datetime values to UTC timestamp (and then displays it for timezone set in user profile).

### Expected behaviour
Displayed due date is `'2017-12-10 10:00'`. API should treat received datetime values either as UTC or as localtime (using timezone set for application (#3653?) or user profile).

Any chosen API behaviour should be documented, API should provide to caller reliable way to get timezone used for supplied datetime values (if needed).

### Steps to reproduce
1. Set timezones with differenet offsets for user profile and application (set in php.ini, I suppose).
    For example, set server's timezone to `Europe/Kiev` and profile timezone to `America/New_York`.
2. Create task using API with `date_due` set to `'2017-12-10 10:00'`
3. Open task details in web browser and look at the Due date displayed value

### Configuration
- Kanboard version: 1.2.0

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
