### ISSUE TITLE
Custom filters field is too short for complex filters

### ISSUE THREAD

**Issue by bmalynovytch** [kanboard/kanboard#3655]
### Actual behaviour
Filter definitions are limited to 100 chars

### Expected behaviour
Filter definitions should accept at least 256 chars for more complex situations

### Steps to reproduce
Try to add a longer filter, ex:
`status:open assignee:nobody assignee:me column:"To Do" column:Doing column:"Validate" started:<=today due:>=today `

### Configuration

- Kanboard version: 1.2.0
- Database type and version: MariaDB 5.5.52
- PHP version: 7.0.21
- OS: CentOS 7.3
- Browser: Google Chrome Mac OS X

**Comment by fguillot** [comment]
This limit has been removed in the development version.
