### ISSUE TITLE
FR - Expand/Collapse all swimlanes

### ISSUE THREAD

**Issue by Sn-L** [kanboard/kanboard#3658]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
In the Board View, the different swimlanes can be expanded/collapsed only one at a time.

### Expected behaviour
All swimlanes of a project can be expanded/collapsed in only one click.

### Configuration

- Kanboard version: 1.0.48
- Database type and version: sqlite 3.8.10.2
- PHP version: 5.6.18
- OS:Windows NT 6.1
- Browser: Firefox 52.5.3

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.7/developer_guide/faq.html).
