### ISSUE TITLE
Example project needed!

### ISSUE THREAD

**Issue by aleshins** [kanboard/kanboard#3659]
I've install kanboard and it is cool. But It would be much easier to switch other members of my team if You will provide some project with dummy data.

**Comment by lastlink** [comment]
Couldn't a plugin solve this issue? Just an example project plugin with only schema migrations or project model calls that insert a project. What would be a good name for this?

**Comment by fguillot** [comment]
Someone made a plugin: https://github.com/bdeshayes/Kanboard-plugin-DemoData
