### ISSUE TITLE
Kanboard text parser loses Cyrillic symbols

### ISSUE THREAD

**Issue by tallinn-code** [kanboard/kanboard#3661]
### Actual behaviour
Parser omits and loses some Cyrillic symbols in comments and task description when pasting from a UTF-8 text file.

### Steps to reproduce
Create a UTF-8 text file and paste Cyrillic text from it

### Screenshots
[Result](https://image.prntscr.com/image/mYirGSQuS3GwLWBy4HkSzQ.png)
[Rendered page code](https://image.prntscr.com/image/XndiwABnQ52cGrJNDvaS2g.png)

### Configuration

- Application version: 1.0.46
- PHP version: 7.0.22-0ubuntu0.16.04.1
- PHP SAPI: fpm-fcgi
- OS version: Linux 4.4.87-mainline-rev1
- Database driver: mysql
- Database version: 10.2.8-MariaDB-10.2.8+maria~xenial-log
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by cl0ne** [comment]
It would be nice to provide sample text for testing purposes. And pasting means Ctrl+C-Ctrl+V or import from CSV?

**Comment by tallinn-code** [comment]
[cyrillic-text-sample.txt](https://github.com/kanboard/kanboard/files/1622351/cyrillic-text-sample.txt)

Hello, I've attached a sample text which is not parsed properly by Kanboard. And I mean Ctrl+C-Ctrl+V, yes, simple copypasting.

**Comment by tallinn-code** [comment]
Is it possible to have a look at this issue? We're experiencing real problems while working with Cyrillic texts...

**Comment by cl0ne** [comment]
I don't have Mac OS X, so out of curiosity I tried to reproduce this issue on Linux - no luck.
Does preview show correct text?

**Comment by tallinn-code** [comment]
Unfortunately no, here's how it looks in preview.

<img width="642" alt="screen shot 2018-01-22 at 20 05 37" src="https://user-images.githubusercontent.com/26515805/35233619-af284df6-ffaf-11e7-8e87-da48e14011fa.png">

**Comment by tallinn-code** [comment]
More input to this problem.

When we're editing task description and not using any kind of lists formatting, the symbols are usually left unmodified, however, when we add numbered lists, the parser "eats" even latin symbols. 

I'm attaching 2 screenshots below, the first one shows text without list formatting, the second one uses simple list formatting.

<img width="1034" alt="screen shot 2018-01-23 at 16 21 11" src="https://user-images.githubusercontent.com/26515805/35278013-bb3ff314-0059-11e8-92c8-8d3fbefd68b7.png">
<img width="1046" alt="screen shot 2018-01-23 at 16 21 28" src="https://user-images.githubusercontent.com/26515805/35278023-c30c14b0-0059-11e8-875a-1e51866325cb.png">

**Comment by cl0ne** [comment]
yeah, markdown parser definitely has bug. couldn't reproduce exactly this bug, but recently ran into another one with links.

**Comment by tallinn-code** [comment]
@cl0ne 
I'm running OS X 10.11.6, my Kanboard installation is running with the following configuration

```
Application version: 1.0.46
PHP version: 7.0.22-0ubuntu0.16.04.1
PHP SAPI: fpm-fcgi
OS version: Linux 4.4.87-mainline-rev1
Database driver: mysql
Database version: 10.2.8-MariaDB-10.2.8+maria~xenial-log
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
```

I've tried to reproduce this bug on the latest stable Chrome

2 screenshots below reflect task editing modal window and task description... The same bug is here with Chrome. I'm going to install Windows 10 via Parallels virtual machine and try it in Windows.

<img width="1270" alt="screen shot 2018-01-24 at 11 26 03" src="https://user-images.githubusercontent.com/26515805/35321939-8d0c277e-00f9-11e8-85d2-d9ab6d2cf8af.png">
<img width="1046" alt="screen shot 2018-01-24 at 11 26 15" src="https://user-images.githubusercontent.com/26515805/35321947-93da7876-00f9-11e8-9758-2dbb522f30bc.png">
<img width="556" alt="screen shot 2018-01-24 at 11 27 57" src="https://user-images.githubusercontent.com/26515805/35321972-ac304ed2-00f9-11e8-8614-7d96976b23fd.png">

**Comment by tallinn-code** [comment]
I wonder if someone could look into this issue... It really IS loosing symbols when editing task description..

**Comment by linvinus** [comment]
@tallinn-code I can't reproduce bug with almost the same installation.
only one difference instead mysql i have sqlite.
may be problem with encoding when text saved to database?
![screenshot-2018-2-15 test_project 5 - mytask1](https://user-images.githubusercontent.com/1043873/36246815-8678d56a-1242-11e8-8e10-8502ce2b6053.png)

**Comment by fguillot** [comment]
I just tried with your text file, but I'm not able to reproduce the problem either. I tested with MariaDB/ PHP 7.
