### ISSUE TITLE
Unusual characters in project owners name

### ISSUE THREAD

**Issue by niall** [kanboard/kanboard#3668]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
Displays 
Project owner: Niall O&#039;Shea

### Expected behaviour
Project owner: Niall O'Shea

### Steps to reproduce
Create a project via a user with a name which includes an unusual character, e.g an apostrophe

### Screenshots

![image](https://user-images.githubusercontent.com/8472444/35033891-3082dd9e-fb64-11e7-8eb5-45bf1b6447d0.png)

### Configuration

- Kanboard version: 1.2.0
- Database type and version: sqlite
- PHP version: 7.2.1
- OS: Windows
- Browser: Chrome

**Comment by jonorozcoc** [comment]
Can you add a bigger screenshot to see the exactly place of your issue?

**Comment by jonorozcoc** [comment]
The issue is placed on project popunder info

![image](https://user-images.githubusercontent.com/8442497/36220075-652030ae-1187-11e8-87c0-ebcc554697d2.png)

**Comment by jonorozcoc** [comment]
The real issue seems to be the popunder doesn't escape the html entity

**Comment by lastlink** [comment]
probably need to encode the html entities using html_entity_decode();
https://www.w3schools.com/php/func_string_html_entity_decode.asp

**Comment by futzco** [comment]
I was just about to submit a similar issue, so I will piggyback here.

Sometimes the `Full Name` is not correctly escaped.

In my case, I noticed it's treated as markdown.

`My profile` page:
![image](https://user-images.githubusercontent.com/3706072/39027675-afc661bc-445b-11e8-9f20-e8fb67230358.png)

Project `i` hover:
![image](https://user-images.githubusercontent.com/3706072/39027676-b70f1fc2-445b-11e8-8b71-1480faacc1be.png)

**Comment by fguillot** [comment]
This is now fixed in PR #3837. Thanks to @sudoman

**Comment by sudoman** [comment]
@fguillot Thanks for merging my PR. : ) Did you intend to close this issue?

**Comment by fguillot** [comment]
This issue should be fixed in version 1.2.4.
