### ISSUE TITLE
Kanborad Very Slow with xampp 3.2.2 transactions delay 10 to 15 seconds or more

### ISSUE THREAD

**Issue by RalfProgrammer** [kanboard/kanboard#3669]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
Kanborad delay when i start session, the delay is 10 to 15 seconds or more,
when i do some transaction or operation(new projects, new tasks, new subtasks)
kandoard is slowly (10 to 15 seconds per operation)
can some help me in this situation?

### Expected behaviour
i need kanboard is faster

### Configuration

- Kanboard version: 1.1.1
- Database type and version:  SQLIte
- PHP version: 7.1.12
- OS: Windows 7
- Browser: Chrome

**Comment by tjharman** [comment]
Convert away from SQLite to mysql.

**Comment by RalfProgrammer** [comment]
Hi tjharman, thanks for the answer, i tried config kanboard for function together mysql, but i do not get success, i will tell you, the steps followed by me:

1 Create the database named kanboard in phpMyAdmin
2 Run the scrypt named mysql.sql, located in xampp/htdocs/kanboard/app/schema/sql (step right)
3 Activate the pdo extension in the file php.ini, in the line wich contains this text:  extension=php_pdo_mysql.dll
4 set up the text, indicates in the faqs about installation kanboard with mysql( https://github.com/kanboard/kanboard/blob/master/doc/en_US/mysql-configuration.markdown), the text is the next:
// We choose to use MySQL instead of Sqlite
define('DB_DRIVER', 'mysql');

// MySQL parameters
define('DB_USERNAME', 'REPLACE_ME');
define('DB_PASSWORD', 'REPLACE_ME');
define('DB_HOSTNAME', 'REPLACE_ME');
define('DB_NAME', 'kanboard');
the text was setted in the file "config.php", located in \xampp\htdocs\kanboard\vendor\miniflux\picofeed\lib\PicoFeed\Config
was right set this text in this file? or have i set the text in the file "config.php" located in: \xampp\phpMyAdmin\libraries?
it was right? or this text must be set up in another file? what is the file?
have i create a new file in some location?

i hope someone can help me

i am sorry for the bothers

Respectfully Regards

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as "server configuration". If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
