### ISSUE TITLE
May we have Yunohost in documentation?

### ISSUE THREAD

**Issue by Jibec** [kanboard/kanboard#3671]
Hi,

I worked for some time on the [Kanboard package](https://github.com/YunoHost-Apps/kanboard_ynh) for [YunoHost](https://github.com/YunoHost/). This is an official package, and your review is really welcome if you wish.

I did the same for [Weblate](https://github.com/YunoHost-Apps/weblate_ynh) and submit a patch to promote it in the documentation, here is how it looks now:
https://github.com/WeblateOrg/weblate/blob/b8250e893afbf136a2447867cc82e89bddae3c89/docs/admin/deployments.rst#weblate-in-yunohost

Would you agree to do the same in your documentation?
I'm unsure to understand which file I should edit to submit a PR. Should I create a new page?

Btw, how does your translation works? Is it really 100% manual? Why don't you use po4a?

Have a nice day,

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.

**Comment by fguillot** [comment]
You can update the documentation by sending a pull-request. See https://docs.kanboard.org/en/latest/developer_guide/faq.html#how-to-update-this-documentation
