### ISSUE TITLE
Incomplete Contributor Guidelines 

### ISSUE THREAD

**Issue by kousu** [kanboard/kanboard#3678]
The current contribution guidelines and install docs just say "clone the repo and run it" more or less. There are two oversights:

1) They don't suggest how to hook into PHP. Maybe leaving that as an exercise for the reader is on purpose, but it could be friendlier to have to cut-and-paste nginx and apache configs available.
2) They don't explain that when you're working from the source code, if you make any changes you **must** run

```
npm install
gulp
```

or else any of your frontend changes won't show up --- and a huge portion of Kanboard is implemented in javascript.

**Comment by fguillot** [comment]
There are some docs here: https://github.com/kanboard/kanboard/blob/master/doc/en_US/assets.markdown#how-to-build-assets-javascript-and-css-files

Feel free to update the doc if necessary
