### ISSUE TITLE
Don't checkin build products

### ISSUE THREAD

**Issue by kousu** [kanboard/kanboard#3679]
If I make a frontend change and re-run `gulp`, `git status` lists

```
	modified:   assets/css/vendor.min.css
	modified:   assets/js/app.min.js
	modified:   assets/js/vendor.min.js
```

and `git diff` is a huge mess because these files are huge single-line behemoths. It is impossible to read a sensible patch out of them, at least without a GUI like Github to help you.

They should be `git rm`ed and then added to `.gitignore` because they are not really a part of the source code, and the install guidelines (see #3678) should be updated to mention that part of installing from source is running `gulp`.

**Comment by fguillot** [comment]
These files are part of the source tree for the same reason as composer dependencies. This is to allow non-technical people to download Kanboard directly from GitHub.
