### ISSUE TITLE
Troubles Intallation Kanboard with Mysql

### ISSUE THREAD

**Issue by RalfProgrammer** [kanboard/kanboard#3681]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
Hi , thanks for the answer, i tried config kanboard for function together mysql, but i do not get success, i will tell you, the steps followed by me:

1 Create the database named kanboard in phpMyAdmin
2 Run the scrypt named mysql.sql, located in xampp/htdocs/kanboard/app/schema/sql (step right)
3 Activate the pdo extension in the file php.ini, in the line wich contains this text: extension=php_pdo_mysql.dll
4 set up the text, indicates in the faqs about installation kanboard with mysql( https://github.com/kanboard/kanboard/blob/master/doc/en_US/mysql-configuration.markdown), the text is the next:
// We choose to use MySQL instead of Sqlite
define('DB_DRIVER', 'mysql');

// MySQL parameters
define('DB_USERNAME', 'REPLACE_ME');
define('DB_PASSWORD', 'REPLACE_ME');
define('DB_HOSTNAME', 'REPLACE_ME');
define('DB_NAME', 'kanboard');
the text was setted in the file "config.php", located in \xampp\htdocs\kanboard\vendor\miniflux\picofeed\lib\PicoFeed\Config
was right set this text in this file? or have i set the text in the file "config.php" located in: \xampp\phpMyAdmin\libraries?
it was right? or this text must be set up in another file? what is the file?
have i create a new file in some location?

The localhost is configured on 8080 port

i hope someone can help me

i am sorry for the bothers

Respectfully Regards

### Expected behaviour
Get up the installation Kandoard with mysql succesfuly 

### Configuration

Kanboard version: 1.1.1
Database type and version: SQLIte
PHP version: 7.1.12
OS: Windows 7
Browser: Chrome

**Comment by cl0ne** [comment]
> the text was setted in the file "config.php", located in \xampp\htdocs\kanboard\vendor\miniflux\picofeed\lib\PicoFeed\Config was right set this text in this file?
yes

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as "server configuration". If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
