### ISSUE TITLE
Revised Translation PT_BR 1.2.0

### ISSUE THREAD

**Issue by gideoni** [kanboard/kanboard#3682]
I did a review on the translation Brasilian Portuguese .

'You don\'t have the permission to move this task' => 'Você não tem permissão para mover esta tarefa.',
'days' => 'dias',
'minutes' => 'minutos',
'seconds' => 'segundos',

---------------------------------------
- Kanboard version: Kanboard 1.2.0
- Database type and version: mysql
- PHP version: 
- OS: Windows NT 6.1
- Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0
---------------------------------------

[translations.php.txt](https://github.com/kanboard/kanboard/files/1656005/translations.php.txt)

**Comment by fguillot** [comment]
I updated these translations. There are new untranslated strings if you would like to translate them:

```
 'Assign automatically a color when preset start date is reached' => '',
 'Move the task to another column once a predefined start date is reached' => '',
```

**Comment by gideoni** [comment]
Yes, the translation follows.
Regards!

'Assign automatically a color when preset start date is reached' => 'Atribuir automaticamente uma cor quando a data de início for atingida',
'Move the task to another column once a predefined start date is reached' => 'Mover a tarefa para outra coluna quando a data de início for atingida',

**Comment by fguillot** [comment]
This is updated now.
