### ISSUE TITLE
No longer able to connect to postgres DB

### ISSUE THREAD

**Issue by krrutkow** [kanboard/kanboard#3686]
### Actual behaviour
After pulling a docker image today, the server now produces an error page:
```
Internal Error: SQLSTATE[08006] [7] missing "=" after "to" in connection info string
```

I believe this is related to passwords with spaces in them and the database connection changes (vendor/fguillot/picodb/lib/PicoDb/Driver/Postgres.php) from here https://github.com/kanboard/kanboard/commit/d35d5beee216ea0a092dac88e9b7556faa95372e#diff-5245718a3be5367e2357e7384f05be4d

Prior to that change the password was properly quoted to preserve spaces, but it seems that is no longer the case.

**Comment by fguillot** [comment]
Can you try again with the latest development version? I restored the old behavior.

**Comment by krrutkow** [comment]
Thanks, it is working again!
