### ISSUE TITLE
I can not access attached files in tasks

### ISSUE THREAD

**Issue by renatoaq** [kanboard/kanboard#3687]
After migrating the Kanboard to another server I can no longer access the files.

### Actual behaviour
The kanboard encrypts the files and I can not access them.

### Expected behaviour
Access the attached files in the tasks.

### Steps to reproduce
Attach files to a task. Then make a kanboard server change.

### Screenshots
No need.

### Configuration

- Kanboard version: 1.0.45
- Database type and version: 10.1.28-MariaDB
- PHP version: 5.6.32 
- OS: Windows
- Browser: All

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as "server configuration". If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
