### ISSUE TITLE
Bug: Documentation page image url

### ISSUE THREAD

**Issue by FJuette** [kanboard/kanboard#3689]
### Actual behaviour
On the documentation page (e.g. /documentation/project-views) the images are loaded from the wrong url if the language is set to 'Deutsch' in the user settings.

### Expected behaviour
The images are loaded from the correct url independent from the language settings.

### Steps to reproduce
  1. Swtich language to 'Deutsch'. No bug if language is 'English'
  2. Open the internal kanboard documentation page (e.g. /documentation/project-views)

In 'English' the src of the img tag is:
/doc/en_US/../screenshots/board-view.png

In 'Deutsch' the url is:
/doc/../screenshots/board-view.png

### Screenshots
<img width="725" alt="kb_error" src="https://user-images.githubusercontent.com/7962025/35429518-b1ca1f90-0274-11e8-8c4d-4b0a2b205443.png">

### Configuration

- Kanboard version: 1.2.0
- Database type and version: mysql 5.7.21
- PHP version: 7.0.22
- OS: ubuntu0.16.04
- Browser: all

**Comment by fguillot** [comment]
The documentation has been moved to a dedicated website now: https://docs.kanboard.org/
