### ISSUE TITLE
bug on User interface task page when i add a subtask

### ISSUE THREAD

**Issue by avermote** [kanboard/kanboard#3693]
### Actual behaviour
when i had a subtask on a task, the page task details don't be normal

### Expected behaviour
having a normal page task details like a tash without subtask + the table with subtask list

### Steps to reproduce
create a subtask.
clic on mother task in a project kanban to see or modify task

### Screenshots
![bug task with subtask](https://user-images.githubusercontent.com/32832982/35513883-bd8fc8f6-0504-11e8-81b8-b157e413d7cc.png)

### Configuration

- Kanboard version: 1.0.46
- Database type and version: postgresql 9.4
- PHP version: 5.5
- OS: redhat 7.2
- Browser: firefox 58.0

**Comment by fguillot** [comment]
No answer.
