### ISSUE TITLE
CLOSED task not showed

### ISSUE THREAD

**Issue by svratonzo** [kanboard/kanboard#3694]
Hi,
if a user closes a task it disappear from swimlanes.
I'm expecting to see it under a swimlanes.

How create a CLOSED swimlanes that will shows tasks?

Application version: 1.2.0
PHP version: 5.6.30
PHP SAPI: apache2handler
OS version: Windows NT 6.1
Database driver: sqlite
Database version: 3.8.10.2

**Comment by cl0ne** [comment]
I suppose that closed tasks are just hidden by default filter `status:open`

**Comment by svratonzo** [comment]
How to see both closed and open at same time?

**Comment by cl0ne** [comment]
@svratonzo just remove filter `status:open` from filter box
