### ISSUE TITLE
Being Member of a project vs. Being in a Group which is a member of a project

### ISSUE THREAD

**Issue by izno** [kanboard/kanboard#3696]
Hello everyone!

Can anyone explain this for me, I can't really get my head around it:

A user who is a member of a group, which is a member of a project doesn't show up in the users overview on project management page (see image bellow)

**I have a group called "TEST GROUP" with 3 members:**

<img width="519" alt="image" src="https://user-images.githubusercontent.com/968204/35644861-70814a22-06ca-11e8-8715-c8a8313cfc5f.png">

**...this is the setup in my project permission page:**

<img width="950" alt="image" src="https://user-images.githubusercontent.com/968204/35644997-ccddb706-06ca-11e8-9e0a-53b1129a1db4.png">

**...but under the project management / users overview page the only Member is the manager:**

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/968204/35645091-1cc5d46a-06cb-11e8-95d6-da06c5857dbc.png">

**...but under the OPEN tasks, the "Test User" profile is shown as a member of the project:**

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/968204/35645187-632a7744-06cb-11e8-8005-45d5e3c043ec.png">

Have I missed something?

The idea of a group is that a user is able to be in a group and part of different projects without being individually added to a project... right?

Otherwise I can't see any reason why the groups are interesting or relevant to have!

Scenario:
– "Test User" is part of a "Technical-support group"
– "Technical-support group" have permissions to be a member of "Project 1" and "Project 2"

Shouldn't "Test User" show up as a member of both projects on the project management / users overview page?

Thank you in advanced

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
