### ISSUE TITLE
Write log entry on file deletion

### ISSUE THREAD

**Issue by Dracer5** [kanboard/kanboard#3697]
### Actual behaviour
I can add new file to task and this action will be logged at Activity Stream.
Then I remove file from task using Attachments -> dropdown near file -> Remove , but no action is logged in Activity Stream.

### Expected behaviour
If someone removes attachment from task, this action will be logged in Activity stream.

### Steps to reproduce
1. Go inside task.
2. Click "Attach a document". Drag-n-drop or select file.
3. Click "Upload..."
4. Go to "Activity Stream" to make sure that log entry is created.
5. Go to "Summary"
6. Click on dropdown triangle near previously uploaded file.
7. Click "Remove".
8. Click "Yes" in opened window "Remove a file".
9. Go to "Activity Stream". See no log entry about deletion.

### Configuration

- Kanboard version: 1.2.0
- Database type and version: SQLite 3.20.1
- PHP version: 7.2.1
- OS: Windows Server 2016 - Windows NT 10.0
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 OPR/50.0.2762.67

**Comment by fguillot** [comment]
This is now implemented as PR #4043.
