### ISSUE TITLE
Hardcoded 'hours' in subtask time tracking

### ISSUE THREAD

**Issue by cl0ne** [kanboard/kanboard#3705]
Hi,
I'm currently translating Kanboard into Ukranian (uk_UA) and ran into couple hardcoded 'hours' string [here](https://github.com/kanboard/kanboard/blob/4aa1d6fd5bc4b54647a83a25271c4e486640d7eb/app/Template/subtask/timer.php#L3) and [here](https://github.com/kanboard/kanboard/blob/4aa1d6fd5bc4b54647a83a25271c4e486640d7eb/app/Template/subtask/timer.php#L7)

**Comment by sudoman** [comment]
@fguillot: Do you think that the code should use `%sh` for encoding the number of hours? It doesn't print trailing zeros for hours that don't contain a fractional part and might have other generic uses in the code base, but it doesn't support replacing periods with commas like `%.2f` does according to locale. The time tracking code seems to increment time by increments of `0.01`, so `%.2f` might be an okay option.

**Comment by fguillot** [comment]
@sudoman There is an existing function [to localize numbers](https://github.com/kanboard/kanboard/blob/4aa1d6fd5bc4b54647a83a25271c4e486640d7eb/app/Core/Translator.php#L104) which is also exposed as `n()`. Of course it could be improved. Doing something like that could work: `t('%s hours', n(5.25))`.

**Comment by cl0ne** [comment]
@fguillot Why don't you use something like `gettext` for localization?

**Comment by fguillot** [comment]
@cl0ne Because the gettext php extension is not always available and I'm too lazy to change everything now. If I had to start over, I will probably use gettext.

**Comment by cl0ne** [comment]
@fguillot So PR that add gettext support (if anyone implement it) are welcome?

**Comment by fguillot** [comment]
I did the modifications mentioned above in master.

@cl0ne Sure, if nothing breaks.

**Comment by cl0ne** [comment]
Thanks
