### ISSUE TITLE
Error docker-compose up -d

### ISSUE THREAD

**Issue by brunocfigueira** [kanboard/kanboard#3706]
Hi, after cloning the kanboard repository I tried to upload the docker but without success.
follows the error: - Kanboard version:1.2.0
PowerShell Windows 10

`> docker-compose up -d
Pulling kanboard (kanboard/kanboard:latest)...
latest: Pulling from kanboard/kanboard
ff3a5c916c92: Already exists
c31008fcdac9: Pull complete
b80aeb782d1e: Pull complete
3434ace811e9: Pull complete
Digest: sha256:364ce18abc0697a30aba06e7f07b079e7214448c154f5925ad3baed9d9e98f35
Status: Downloaded newer image for kanboard/kanboard:latest
Recreating a58b1bcb408a_a58b1bcb408a_a58b1bcb408a_a58b1bcb408a_a58b1bcb408a_a58b1bcb408a_a58b1bcb408a_a58b1bcb408a_kanboard_kanboard_1 ... error

ERROR: for a58b1bcb408a_a58b1bcb408a_a58b1bcb408a_a58b1bcb408a_a58b1bcb408a_a58b1bcb408a_a58b1bcb408a_a58b1bcb408a_kanboard_kanboard_1  no such image: sha256:5851a1ec04a45f60500506289655e218613bce
c53d7e8d9b1242ee2246f23134: No such image: sha256:5851a1ec04a45f60500506289655e218613bcec53d7e8d9b1242ee2246f23134

ERROR: for kanboard  no such image: sha256:5851a1ec04a45f60500506289655e218613bcec53d7e8d9b1242ee2246f23134: No such image: sha256:5851a1ec04a45f60500506289655e218613bcec53d7e8d9b1242ee2246f23134
ERROR: Encountered errors while bringing up the project.`

Is this a configuration error or did I do something wrong?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as "server configuration". If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
