### ISSUE TITLE
Integration with PHPStorm (JetBrains)

### ISSUE THREAD

**Issue by fatihalp** [kanboard/kanboard#3707]
Hi I really like kanboard. I was using PHPStorm jira extension and managing task in IDE. It's useful and able to do time management automatically. Is it possible with kanboard? 

![image](https://user-images.githubusercontent.com/219454/36029484-6b12c0ac-0db4-11e8-8d62-a4a81281c55b.png)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
