### ISSUE TITLE
Keep schema versions in sync between DB drivers

### ISSUE THREAD

**Issue by olberger** [kanboard/kanboard#3709]
AFAIU, in 1.1.1, the SQLite schema is 116 whereas MYSQL's is 126.

It's rather difficult to identify the needed bits to maintain a script like https://github.com/oliviermaridat/kanboard-sqlite2mysql

AFAIU, these 2 versions are in sync even though some changes weren't applied the same way between flavours : columns removed from MySQL and not in SQLIte, etc.

I think that having versions of the schema in sync (and corresponding schemas almost identical) would help.

Thanks in advance.

Best regards,

**Comment by fguillot** [comment]
This is not likely to happen because the changes required for each database type are not the same. Take a look in migration files: https://github.com/kanboard/kanboard/tree/master/app/Schema
