### ISSUE TITLE
Plugins is not installable with php 7.1.13

### ISSUE THREAD

**Issue by vistar** [kanboard/kanboard#3712]
### Actual behaviour
"Your Kanboard instance is not configured to install plugins from the user interface" with php 7.1.13

### Steps to reproduce
Setup php 7.1.13 for webroot

### Configuration

- Kanboard version: 1.2.0
- Database type and version: 
- PHP version: 7.1.13
- OS: debian 8
- Browser: chromium 62

**Comment by fguillot** [comment]
You have your answer in the documentation https://github.com/kanboard/kanboard/blob/master/doc/en_US/plugin-directory.markdown#plugin-directory-configuration

**Comment by vistar** [comment]
Hm. All working with php 7.0, but with 7.1 have an error.

**Comment by bugwatcher** [comment]
The version of PHP doesn't really make any difference in this context.

**Comment by vistar** [comment]
I do not know, but on version 7.0, 5.6 everything works fine.
I have been using kanboard for several years.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"server configuration"**. If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
