### ISSUE TITLE
Not receiving email notifications for drag and drop, but receive emails from automatic actions

### ISSUE THREAD

**Issue by adrianz2014** [kanboard/kanboard#3715]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
Not receiving emails for drag and drop of tasks. Notifications in user profile are set to receive emails for all tasks, for all projects, but not receiving any.

I have created an automatic action where I am notified that a task has been moved to a certain column, and I am receiving those emails.

### Expected behaviour
Receive emails for drag and drop of tasks for selected tasks(all, or created by me, or assigned to me, or only created by me and assigned to me)

### Steps to reproduce
Move task from one column to another. Receive no email.

### Configuration

- Kanboard version: 1.1.0
- Database type and version: mysql 5.5.46
- PHP version: 5.3.28
- OS: Windows NT 6.2
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

**Comment by fguillot** [comment]
FYI, you will not receive notifications for actions made by yourself. 

Make sure that you didn't miss anything from the doc: https://github.com/kanboard/kanboard/blob/master/doc/en_US/notifications.markdown#configuration

**Comment by adrianz2014** [comment]
Understood. I had another user move tasks and I received the emails. Thanks for letting me know.
