### ISSUE TITLE
php72 nginx centos7 no "pdo_mysql"

### ISSUE THREAD

**Issue by teksaport** [kanboard/kanboard#3718]
So when I try to run yum install to get the pdo_mysql, it says there isn't any.  Is anyone using this?
#yum install php72-pdo_mysql
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: pubmirrors.dal.corespace.com
 * epel: mirror.chpc.utah.edu
 * extras: mirrors.unifiedlayer.com
 * updates: centos.den.host-engine.com
No package php72-pdo_mysql available.
Error: Nothing to do

**Comment by fguillot** [comment]
Take a look to the documentation: https://github.com/kanboard/kanboard/blob/master/doc/en_US/centos-installation.markdown#centos-7

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"server configuration"**. If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
