### ISSUE TITLE
Couldn't open the main kanboard page

### ISSUE THREAD

**Issue by mechingineer** [kanboard/kanboard#3720]
Couldn't open the main login page after configuring Apache Server, PHP and MySQL Server.

Steps I followed
1. Configured Apache Server
2. Configure PHP
3. Configure MySQL Server
4. Created Database named as kanboard
5. Granted all permissions to root user for database kanboard
6. Made the MySQL related changes in config.php file
7. Browsed http://localhost/kanboard

All that is displayed is folder structure. Please see the image below

![image](https://user-images.githubusercontent.com/26077718/36297255-af9f41a6-1317-11e8-9d53-b206a2f13a3a.png)

Please help me in understanding the issue. I am totally new to this and probably I must be missing something. Please let me know how to fix this.

**Comment by dixon22ma** [comment]
Hi @mechingineer, apparently you do not have php5 installed. Or otherwise it indicates what version you have installed.

Regards..

**Comment by mechingineer** [comment]
Hi dixon22ma,

I have PHP v7 installed on my system. Please see below:

![image](https://user-images.githubusercontent.com/26077718/36306200-b91d165c-133c-11e8-86fa-049b6932ac77.png)

![image](https://user-images.githubusercontent.com/26077718/36306211-c8c43ea0-133c-11e8-9c45-bcedad4d9d0a.png)

**Comment by dixon22ma** [comment]
I downloaded the code again and it has been displayed without problems ... which version of Kanboard you are using

**Comment by mechingineer** [comment]
I am using latest kanboard version i.e. 1.2.0.

I followed the steps mentioned in the following link :
https://github.com/kanboard/kanboard/blob/master/doc/en_US/windows-apache-installation.markdown

**Comment by mechingineer** [comment]
Sorted, was missing this step:
DirectoryIndex index.php index.html

But now getting the below error:
![image](https://user-images.githubusercontent.com/26077718/36321019-60dfd010-136e-11e8-87c2-5b0b2ab6d83f.png)


FYI, I am using MySQL server for the configuration. I have create a DB named as kanboard in the MySQL server and provided the configurations in config.php file in Kanboard folder using the below link:
https://github.com/kanboard/kanboard/blob/master/doc/en_US/mysql-configuration.markdown

Please let me know how can I fix this.

**Comment by dixon22ma** [comment]
Remove the database
Re-create it
And add this line to your config.php file
// Set max_execution_time into php.ini
ini_set ('max_execution_time', 300); // 300 seconds = 5 minutes

This is a momentary solution, apparently the scripts exceed the allowed time limit.

**Comment by mechingineer** [comment]
Thanks a lot for your help. This resolved the issue. Closing the issue.

**Comment by dixon22ma** [comment]
@mechingineer to order ... I'm happy to help ...

@fguillot Will you commit these changes in the main branch? or is there a better solution?
