### ISSUE TITLE
Add wiki kanboard plugin to plugins.json

### ISSUE THREAD

**Issue by lastlink** [kanboard/kanboard#3721]
Please add this plugin https://github.com/funktechno/kanboard-plugin-wiki to the **plugins.json** list at https://kanboard.org/plugins.json.

Plugin is compatible w/ 5.6 of php as that's the version I'm running w/ my own kanboard.
I have basic wiki support per project. I save editions of wikipages that can be restored. I have an order attribute., but haven't build out the function to switch order yet. Full crud works on wikipages as well as edition restoring w/ the option as a global config to not save editions. File upload ui is working, but doesn't actually save files. Input/pull request would be great, maybe I'll figure it out. Unit tests also needs some tweaks to work w/ travis 5.6. I also noticed I don't know if this applies to all of kanboard, but the unit tests on travis don't run for php7. Only for php5.

This may be a duplicate of [issue 358](https://github.com/kanboard/kanboard/issues/358)

- Kanboard version:
1.0.37

- PHP version: 5.6 & 7.0

**Comment by fguillot** [comment]
The instructions are there: https://github.com/kanboard/website#how-to-add-a-new-plugin-to-the-list

**Comment by lastlink** [comment]
Ok I didn't know that the website repository existed. I created a pull request. https://github.com/kanboard/website/pull/13
