### ISSUE TITLE
Extend details on notification view

### ISSUE THREAD

**Issue by k00ni** [kanboard/kanboard#3722]
Is it currently possible to configure the notification view? (`?controller=DashboardController&action=notifications`) I would like to change the information that are displayed, because currently its very hard to determine, **who changed what in which way**.

The following changes would be helpful:
* instead of the task ID, the task title should be shown (or only the first 100 chars of it)
* added username of who made a change
* show what did change, e.g. show the new comment or show a diff of new added text

If these changes couldn't be part of kanboard, is it possible to implement them using a plugin?

What you think?

**Comment by fguillot** [comment]
This is not possible to configure the notification contents. However, you could contribute to this open source project to improve the messages.

**Comment by k00ni** [comment]
> This is not possible to configure the notification contents. However, you could contribute to this open source project to improve the messages.

Ok. Does that mean, that i can't extend/change the view's content with a plugin?

If so, can you please give me a short hint, in which internal file(s) the notification view is "generated"?

**Comment by fguillot** [comment]
You could modify these templates: https://github.com/kanboard/kanboard/tree/master/app/Template/notification and the subjects are here https://github.com/kanboard/kanboard/blob/master/app/EventBuilder/TaskEventBuilder.php#L134

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
