### ISSUE TITLE
extended plugin support

### ISSUE THREAD

**Issue by lastlink** [kanboard/kanboard#3724]
Right now our plugin list is maintained by https://kanboard.org/plugins.json. To add custom plugins we have to upload to the host in this websites plugins folder. 
Drupal allows you to upload plugins (called modules) from the website itself or give a url to the release in a .tar.gz format e.g. https://ftp.drupal.org/files/projects/smtp-8.x-1.0-beta3.tar.gz.
I propose that similar support be added. Maybe be able to upload plugins, give a url to the zip release, maybe have 2 json lists to pull dependencies from. Maybe even have an info.json for each plugin repository that allows the current version & download paths to be added when added in a certain way.
The other option is for each user to maintain their own plugins.json, but that would mean they would have to manually manage it, update the default config to point to their own as well.

Maybe each kanboard website could maintain its own plugins.json that when you go to the plugins install page it compared the local plugins w/ those in kanboard maintained plugins and only updates those in both this way a user could edit their own for nonstandard plugins, but pull updates from our maintained one.

### Actual behaviour
Have to upload zipped plugins onto host, then unzip in the plugins folder

### Expected behaviour
Be able to upload from website or give url to release.

### Screenshots
![image](https://user-images.githubusercontent.com/6679425/36343159-9959e062-13d6-11e8-81bb-43461e468881.png)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
