### ISSUE TITLE
Feature request: Return information about tags by getAllTasks

### ISSUE THREAD

**Issue by adnidor** [kanboard/kanboard#3726]
Currently the getAllTasks API method doesn't return any information about tags, it is necessary to call getTaskTags for every task.
It would be more efficient to return the applied tags in the task object returned by getAllTasks (and maybe getTask), or at least return information about the existance of tags so that getTaskTags doesn't need to be called if there aren't any.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
