### ISSUE TITLE
Fail to Access by jsonrpc to my own instance

### ISSUE THREAD

**Issue by blutux** [kanboard/kanboard#3728]
Hi,

I have installed kanboard on my synology yesterday. It works well with the web. Now 

### Actual behaviour
i try to connect it by an android application at kanboard but it doesn't work. When i'm investatigating, i have tried to connect by postman at http://myserver.com/kanboard/jsonrpc.php with basic auth but it doesn't work.

I have this response :

{ "jsonrpc": "2.0", "error": { "code": -32700, "message": "Parse error" }, "id": null }

### Expected behaviour
Connexion ok

### Configuration

- Kanboard version: 1.2.0
- Database type and version: sqlite
- PHP version: 5.6
- OS: linux

Could you tell me what i havent config correctly ?

Thanks in advance,

Blutux

**Comment by fguillot** [comment]
You get this API response because you sent a malformed request to the API endpoint.

Take a look to the documentation, there are some examples: https://github.com/kanboard/kanboard/blob/master/doc/en_US/api-examples.markdown#example-with-curl

**Comment by blutux** [comment]
I have tried the 1st example with curl : 

`curl \
-u "user:password" \
-d '{"jsonrpc": "2.0", "method": "getAllProjects", "id": 1}' \
http://192.168.0.5/kanboard/jsonrpc.php`

And i get this response : 
`{"jsonrpc":"2.0","error":{"code":403,"message":"Forbidden"},"id":null}`

**Comment by fguillot** [comment]
This API call is reserved for the special user "jsonrpc". This is why you get a forbidden access. If you use your user credentials, try another procedure, for example "getMe" instead of "getAllProjects"
 (https://github.com/kanboard/kanboard/blob/master/doc/en_US/api-me-procedures.markdown#getme).

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
