### ISSUE TITLE
picodb escape characters bug

### ISSUE THREAD

**Issue by lastlink** [kanboard/kanboard#3730]
Picodb needs additional escape characters. Maybe just missing for the ->asc() function especially for reserved words on a database. I placed this issue here b/c picodb doesn't allow us to submit issues.
This is in reference to an [issue](https://github.com/funktechno/kanboard-plugin-wiki/issues/1) I solved a different way for the wiki plugin. I tried to order by using the ->asc('order') function and the column named "order" which is a keyword and this through an error in sqlite. Doing ->asc('\'order\''). Solved this.

### Actual behaviour
```
->asc('order')
=
Internal Error: SQL error
```
on sqlite

### Expected behaviour
Properly order ascending by the database keyword.

Application version: 1.2.0
Database driver: sqlite
Database version: 3.22.0

**Comment by fguillot** [comment]
This is already escaped: https://github.com/fguillot/picoDb/blob/master/lib/PicoDb/Table.php#L536

**Comment by lastlink** [comment]
It didn't seem to work for sqlite.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.7/developer_guide/faq.html).
