### ISSUE TITLE
administrators can't see all projects

### ISSUE THREAD

**Issue by lastlink** [kanboard/kanboard#3733]
From what I understand an administrator should be able to access everything. This issue https://github.com/kanboard/kanboard/issues/1912 states that they should explicitly add themselves to a project before being able to make any changes. However, I've noticed that administrators if not in a project's permissions will not even be able to see the project when they list all projects. Is this the intended behavior. I've noticed this is because I have 2 administrator's in my kanboard instance. I also don't know if admin's should be able to see another user's private projects. If what is currently happening is the intended behavior please update the documentation or clarify here. Thanks!
https://github.com/kanboard/kanboard/blob/master/doc/en_US/project-permissions.markdown
https://github.com/kanboard/kanboard/blob/master/doc/en_US/roles.markdown
https://github.com/kanboard/kanboard/blob/master/doc/en_US/custom-project-roles.markdown

### Actual behaviour
Administrator's can't see projects that they haven't been added to.

### Expected behaviour
Administrator's should be able to see all projects, but not make any changes until added to their user list.

### Configuration

- Kanboard version: 1.2
- Database type and version: mysql 5.6
- PHP version: 7.1

**Comment by fguillot** [comment]
Administrators can see everything, however if they want to work on a project they should be members of this project to be visible in the assignee list.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
