### ISSUE TITLE
Feature Request: Allow zoom and pan of image attachments

### ISSUE THREAD

**Issue by manuvarkey** [kanboard/kanboard#3735]
It would be nice to pan and zoom image attachments. Currently full image is shown with no option to zoom/pan. This feature will be super useful for viewing scanned documents/illustrations from within Kanboard instead of downloading and using a separate image viewer.

Something like this can be implemented using http://ignitersworld.com/lab/imageViewer.html (Released under MIT license).

**Comment by manuvarkey** [comment]
I will give it a shot. Can I use the same plugin ?

**Comment by kent1D** [comment]
[Photoswipe](https://github.com/dimsemenov/photoswipe) may be better, with possibly less functionalities but better followed on Github ?

**Comment by kent1D** [comment]
One thing also is that it would be great if it would be framework independent, Vanilla JS.

In case we decide one day to switch off from jQuery

**Comment by fguillot** [comment]
Well, instead of adding more Javascript cruft, opening the image in a browser tab could be enough. Pretty much all browsers allows you to zoom in/out.

**Comment by fguillot** [comment]
I added a link to open the image in a new tab.
