### ISSUE TITLE
mismatch time tracking details sum and total sum when entering manuall subtask time spent 

### ISSUE THREAD

**Issue by neiaberau** [kanboard/kanboard#3737]
### Actual behaviour
entering a subtask time spent, "removes" all time tracked before this entry from the sum, but still shows them in the detailed list; the entered time itself is not shown in the detailed list, so
the total time then does not match the sum of the times  in the "time tracking" view

### Expected behaviour
- show the entered time in details as well, to be able to understand the overall sum of spent time
- remove (with a warning) or show an "ignored" flag on times not used for the sum of spent time

### Steps to reproduc
after .64 hours traced, I entered .2 hours for time spent; then another .9 hours were recorded,
the details still lists .64 and .09, but not the manally entered .2,
the summary ignores all entries before the edit time and shows .29, there is no indicator of the .64 not beeing used in the summary or warning while entering .2

### Screenshots

![screenshot 2018-02-24 10 14 14](https://user-images.githubusercontent.com/6450711/36628260-ced3f0cc-194c-11e8-8fd5-0d02eae4ebb2.png)

### Configuration

Application version: master.dd424e5a99c920434a8ea4402d764b46e69cd932 
PHP version: 7.1.14 
PHP SAPI: fpm-fcgi 
OS version: Linux 3.16.0-5-amd64 
Database driver: sqlite 
Database version: 3.21.0 
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.13/developer_guide/faq.html).
