### ISSUE TITLE
Show task link on notification after created

### ISSUE THREAD

**Issue by williamespindola** [kanboard/kanboard#3740]
### Actual behaviour
When a task is created a notification is launch, but only with info that one task was created and I can't go to this task direct or with some click, I need to find this on board.

### Expected behaviour
If this notification had the link of this task that was created, we can click on it. This will helpful when we need to create a task and define some others this like link this with other task for example.

**Comment by fguillot** [comment]
The task link will show up in notifications if you set the application url in application settings.

**Comment by williamespindola** [comment]
@fguillot is already set but don't show up.

**Comment by fguillot** [comment]
I cannot guess what is wrong on your side. You should give more details, take screenshots to make sure there is no misunderstanding, etc.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
