### ISSUE TITLE
Force redirect

### ISSUE THREAD

**Issue by sillyonthestreet** [kanboard/kanboard#3743]
I'm using cPanel, Apache, PHP 7.2, and the latest 1.2.1 version of Kanboard.

I use an SSL via AutoSSL from cPanel. I have the default .htaccess file and I configured my application URL to be https://my.kanboarddomain.com

I use kanboard on my subdomain.

But, there's no redirection from www to non-www. There's no redirection from http to https. How do I make a 301 redirect to force all traffic to https:// (non-www)?

Copied from the About page:

    Application version: 1.2.1
    PHP version: 7.2.2
    PHP SAPI: litespeed
    OS version: Linux 3.10.0-714.10.2.lve1.4.79.el7.x86_64
    Database driver: sqlite
    Database version: 3.8.5
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

Not sure why it says that the database driver is sqlite. I changed it to "mysql" in the config file and I'm using MySQL.

**Comment by fguillot** [comment]
Your issue is not related to Kanboard itself but to the configuration of your web server (cPanel).

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"server configuration"**. If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
