### ISSUE TITLE
Allow generating simpler iCal events

### ISSUE THREAD

**Issue by poinu** [kanboard/kanboard#3744]
### Actual behaviour

Currently, the events generated for iCal show the tasks full length, from the date of creation/start, and all the way through their 'due date'. This is useful, but sometimes floads the calendar with too much information when many tasks are active at the same time (plus displaying those days as completely busy from 00:00 to 23:59 everyday).

Closely related to plugin-calendar issue [#10](https://github.com/kanboard/plugin-calendar/issues/10).

### Expected behaviour

For some workflows, I think it would be better to generate simpler iCal events that display only the tasks' due date. That is, instead of showing the period when the task is being worked on, show only their 'due date' (as its currently done with tasks that a due date but no creation/start date). From my point of view, in this mode, if a task doesn't have a due date, it shouldn't be shown in the calendar.

If accepted, I have the intention of developing it myself, by adding a new setting that allows the user to choose between the two modes.

This proposal doesn't suppose many changes in the current structure: Given the calendar mode, all tasks should be handled as if they only had a due date but no start date, or handling those groups separately (as they are currently being handled now) otherwise.

As far as the setting is concerned, I've considered adding it either to the 'Public access' submenu in the user profile (see screenshot below), or directly to general user settings (it could make sense to put it there if the *plugin-calendar* is going to be using that setting to). 

### Screenshots
![screenshot from 2018-03-01 22-20-20](https://user-images.githubusercontent.com/7153980/36870252-c20ecc12-1d9e-11e8-8b1a-4537e0008448.png)

What do you think about the idea? Have I missed anything? Do you have any tip or suggestion?

Thanks!

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
