### ISSUE TITLE
Tooltip li margin

### ISSUE THREAD

**Issue by sillyonthestreet** [kanboard/kanboard#3745]
A minor "bug", but it's quite annoying to see. On a recurring task, when you hover over the recurrence icon, you get the tooltip. The list items (bullets) are too far left. Maybe the margin or max-width should be increased? Something here? https://github.com/kanboard/kanboard/blob/7399c3c59632712b0e9da778dd542fc681a5e0c3/assets/js/src/Tooltip.js

![recurring-task](https://user-images.githubusercontent.com/32963211/36874398-0b22bfbe-1dac-11e8-8bb3-3a31e8c890fd.png)

**Comment by fguillot** [comment]
This is now fixed in the development version.
