### ISSUE TITLE
Feature Request: Allow filtering for tasks with running subtask timers

### ISSUE THREAD

**Issue by neiaberau** [kanboard/kanboard#3747]
In order to have a quick overview of tasks currently activly worked on with timers, It would be beneficial to filter for all tasks with running subtask timers

**Comment by creecros** [comment]
- Added Filter to plugin: https://github.com/creecros/Creecros_Filter_Pack
- Added Plugin to kanboard/website#110

**Comment by neiaberau** [comment]
that's very good, thanks a lot, I will install  it next week

**Comment by neiaberau** [comment]
perfect, and with the new already implemented addition for RUNNING it covers all cases I have
