### ISSUE TITLE
Ubuntu Server 16.04, unable to log back in

### ISSUE THREAD

**Issue by lmwgv** [kanboard/kanboard#3748]
On a new install of kanboard, I was able to log in for the first time and use kanboard for several days. However, I am unable to log back in a second time.

I have tried upgrading kanboard to latest git version, changing logging method to syslog (an issue here mentioned it could help) and resetting the password with the cli command.

### Actual behaviour
After filling in username and password, I get: The username is required, The password is required.

### Expected behaviour
Logging in to Kanboard

### Steps to reproduce
On a new kanboard installation, log in, log out, attempt to log back in.

### Configuration

- Kanboard version: master git branch as of March, 5, 2018
- Database type and version:  mariadb 10.0.33
- PHP version: 7.0+35ubuntu6.1
- OS: Ubuntu Server 16.04 LTS
- Browser: Chrome, Edge

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"server configuration"**. If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
