### ISSUE TITLE
Better visibility and use of web notifications

### ISSUE THREAD

**Issue by kent1D** [kanboard/kanboard#3749]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour

* the standard sorting for web notification is descending per default (see #3502), better to sort it on the other side by default
* we can't change the sort of the unread notification
* we can't sort by type of notification
* there is no pagination in the user unread notification modal (with a lot, like more than 500 notifications, it would be better)
* lack of visibility of the icon, we also don't know how many notifications there are.

### Expected behaviour

* Invert the sort
* paginate the list inside the modal
* add a badge to show the number of unread notification
* add a sort menu (date asc/desc, type asc/desc)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
