### ISSUE TITLE
Feature Request: Filtering of tasks in period of time

### ISSUE THREAD

**Issue by starmagoo** [kanboard/kanboard#3750]
I wanted to ask if it is possible to filter for tasks that were processed within a certain period of time: for example, the last 14 days, the last 4 weeks, etc.

thanks in advance

**Comment by fguillot** [comment]
What do you mean by "processed" in this context?

**Comment by starmagoo** [comment]
I want to filter by modified / updated tasks of the last X days / weeks / months / periode

**Comment by gerald2545** [comment]
duplicate #3942 
merged in master
