### ISSUE TITLE
Migrated to latest version copying old DB file and errors coming

### ISSUE THREAD

**Issue by Inspop-Design** [kanboard/kanboard#3751]
We migrated to the latest version while keeping a back up and copying the old DB folder to the new installation. We keep on getting errors and not able to login inside. Issue logged in error log is  : 
```
[05-Mar-2018 20:20:00 Asia/Kolkata] PHP Fatal error:  Uncaught PicoDb\SQLException: SQL error in /home/missfilm/public_html/intranet/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php:351
Stack trace:
#0 /home/missfilm/public_html/intranet/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php(245): PicoDb\StatementHandler->handleSqlError(Object(PDOException))
#1 /home/missfilm/public_html/intranet/vendor/fguillot/picodb/lib/PicoDb/Table.php(237): PicoDb\StatementHandler->execute()
#2 /home/missfilm/public_html/intranet/app/Core/Session/SessionHandler.php(67): PicoDb\Table->insert(Array)
#3 [internal function]: Kanboard\Core\Session\SessionHandler->write('ef0f7b61047dd54...', 'hasRememberMe|b...')
#4 [internal function]: session_write_close()
#5 {main}
  thrown in /home/missfilm/public_html/intranet/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 351

```

You can see it on intranet.digimaximizer.com

**Comment by fguillot** [comment]
Enable the debug mode, and watch log files to see the exact sql error. Probably the sql migrations that didn't run properly.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"server configuration"**. If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
