### ISSUE TITLE
Feature Request: Change Weblink URL resolve to use client side JS in order to access protected links

### ISSUE THREAD

**Issue by wucherpfennig** [kanboard/kanboard#3752]
We use this feature a lot but unfortunately it works only with sites that have no authentication running.

Eg. If we want to link our helpdesk tickets to a task this usually does not work because the url resolving part of the weblink is run on our unauthenticated server which results in a "bad" link (you have just the start page linked). Same situation with other web applications.

Does anybody know how to implement another behaviour? If somebody could point me in the right direction I could provide you some code for this matter. I already checked the Weblink plugin but it seems no way to avoid the server limitation...

best regards

wucherpfennig

**Comment by fguillot** [comment]
I don't really understand what you are asking for (weblink?). But if the task URL is not correct, you must define the application URL in the application settings.

**Comment by wucherpfennig** [comment]
Dear @fguillot 

![image](https://user-images.githubusercontent.com/3634653/37082851-f400bf5c-21ed-11e8-9764-1fcaf2cf299e.png)

![image](https://user-images.githubusercontent.com/3634653/37082910-1b81d840-21ee-11e8-8c3d-f38ef02b1ddb.png)

the weblink class cannot resolve the url above because it needs authentication in order to access it. Usually only the USER (client) is authenticated on the external server / service and not the (kanboard) SERVER.

Therefore my suggestion to change the "url resolving and find page title" to a client side JS method in order to bypass this limitation

I hope this description made my suggestion / question clearer ;-)

Best regards

wucherpfennig

**Comment by fguillot** [comment]
Ok, I see. A picture is worth a thousand words.

**Comment by fguillot** [comment]
Doing this in JavaScript will probably no work because of [Cross-Origin/Same origin policy in browsers](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing).

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
