### ISSUE TITLE
Can't add a task with + column button

### ISSUE THREAD

**Issue by tutle** [kanboard/kanboard#3754]
I strangely can't add a task with the + button of column but I can with the manu add task.
Any idea ?
Sincerely
Yvan

### Configuration

- Kanboard version:1.2.0.
- Database type and version:3.6.20
- PHP version: 7.0.27
- OS:Linux 2.6.32-896.16.1.lve1.4.49.el6.x86_64
- Browser:Mozilla/5.0

**Comment by fguillot** [comment]
You should try to check the logs for potential errors:

- Check the browser console
- Check the web server logs
- Check the application debug logs
- Uninstall incompatible plugins

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"server configuration"**. If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
