### ISSUE TITLE
Feature Request : Categorie for project

### ISSUE THREAD

**Issue by tetsuosp** [kanboard/kanboard#3755]
It'll be great to view and filtering a list of project with categorie or tag (like "hardware", "network", "software", "political issue", ...). Don't you think so ?

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I understand your point but I prefer to keep the software simple, the number of features is voluntary limited. (duplicate of #790).

Thank you for your understanding
