### ISSUE TITLE
How to set "Category" for task as a required field ?

### ISSUE THREAD

**Issue by sringeard** [kanboard/kanboard#3756]
Hello,
Can we simply set the category as a required filed for all new task in a project ?

Thank you in advance
Regards

### Configuration

- Kanboard version: 1.2.1
- Database type and version:10.0.34-MariaDB
- PHP version: 7.0.28
- OS: Linux 3.10.0-714.10.2.lve1.5.12.el6h.x86_64
- Browser: Chrome

**Comment by fguillot** [comment]
This feature doesn't exists. Kanboard does not enforce that.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
