### ISSUE TITLE
issues less than 6 months old, get closed automatically by a bot

### ISSUE THREAD

**Issue by neiaberau** [kanboard/kanboard#3757]
feature request issues are auto closed with comment "inactivity for more than 1 year", although the
last activitiy/comment was less than  5 months ago.

what is the policy on this project? 

example issue 2473, see screen shot:
![kanboard_auto_closed_2473](https://user-images.githubusercontent.com/6450711/37239734-e9dd18ae-2440-11e8-8ecf-380319245954.png)

note:
this is an example I saw by accident, I personally do not specifically required the above mentioned FR, more 3625 and now I wonder when this gets closed

**Comment by fguillot** [comment]
Yeah I'm aware of that, don't worry. This is just a bad settings for the bot.

The policy is: feature requests are closed if nobody manifest any interest to develop the feature after a while or if this is against the philosophy of the software (focus on simplicity).
