### ISSUE TITLE
Increase length of "reference" field

### ISSUE THREAD

**Issue by C-Duv** [kanboard/kanboard#3760]
The `reference` field in a task creation/update form is currently limited to 50 characters.
By looking at the code, this cannot be configured via configuration file or administration interface.

Could the limit be increased? To say 150 characters?
Some issue-tracking system I use have long URLs (at least, longer than 50).

Here are the 3 files that need update:
* `/app/Validator/CommentValidator.php` (line 94)
* `/app/Validator/TaskValidator.php` (line 44)
* `/app/Import/TaskImport.php` (line 144)

And also the `tasks`.`reference` SQL column.

**Comment by fguillot** [comment]
The length has been increased in the development version to 255 characters.
