### ISSUE TITLE
Kanboard

### ISSUE THREAD

**Issue by mahdibugatti** [kanboard/kanboard#3761]
Hello my friends: I have an issue with a Kanboard here, I have deployed and configured Kanboard and it was working fine with config.php under /var/www/html/kanboard. 
Today I wanted to configure the OpenLDAP so I made a copy from config.php and started making changes on config.php file. It didn't work so I removed it and put back the original working one however when I restarted httpd services. I started to get an ERROR 500, I checked the logs and it shows:

[Mon Mar 12 13:46:34.947041 2018] [php7:warn] [pid 2485] [client 10.200.10.94:52109] PHP Warning:  require(/var/www/html/kanboard/app/../config.php): failed to open stream: Permission denied in /var/www/html/kanboard/app/common.php on line 21
[Mon Mar 12 13:46:34.947116 2018] [php7:error] [pid 2485] [client 10.200.10.94:52109] PHP Fatal error:  require(): Failed opening required '/var/www/html/kanboard/app/../config.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/kanboard/app/common.php on line 21
[Mon Mar 12 13:46:35.780015 2018] [php7:warn] [pid 2483] [client 10.4.7.129:52116] PHP Warning:  require(/var/www/html/kanboard/app/../config.php): failed to open stream: Permission denied in /var/www/html/kanboard/app/common.php on line 21
[Mon Mar 12 13:46:35.780097 2018] [php7:error] [pid 2483] [client 10.4.7.129:52116] PHP Fatal error:  require(): Failed opening required '/var/www/html/kanboard/app/../config.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/kanboard/app/common.php on line 21
[Mon Mar 12 13:46:36.216096 2018] [php7:warn] [pid 2482] [client 10.4.7.129:52120] PHP Warning:  require(/var/www/html/kanboard/app/../config.php): failed to open stream: Permission denied in /var/www/html/kanboard/app/common.php on line 21
[Mon Mar 12 13:46:36.216172 2018] [php7:error] [pid 2482] [client 10.4.7.129:52120] PHP Fatal error:  require(): Failed opening required '/var/www/html/kanboard/app/../config.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/kanboard/app/common.php on line 21

Any ideas?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"server configuration"**. If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding.
