### ISSUE TITLE
Automatic action for removing due date depending on column

### ISSUE THREAD

**Issue by rajo** [kanboard/kanboard#3765]
Just a minor feature request: if a task has a due date set and is overdue, this will be displayed on the task and notified. It would be useful, if one could define an action s.t. the placement of a task in e.g. the "Done" column will automatically remove due dates in order to avoid unneccessary Email notifications, when the due date is over but the task is for some reason still in the "Done" column. (Of course, one can manually remove the due date etc. but such a rule could be handy)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
