### ISSUE TITLE
Markdown toolbar - ordered list

### ISSUE THREAD

**Issue by meier-vbs** [kanboard/kanboard#3766]
When I first used the editor i didn't know about the automatic ordered list due to the fact that there wasn't an icon. Could it be possible to add an icon for the ordered list like it exists for the unordered list?
My main problem was that I entered a date "03. Mai 2018" that's how we write dates in Europe and in the first moments i didn't understand why it outputted "1. Mai 2018".

**Comment by fguillot** [comment]
The description field is using the Markdown syntax, you have a quick summary here: https://github.com/kanboard/kanboard/blob/master/doc/en_US/syntax-guide.markdown#syntax-guide

**Comment by aljawaid** [comment]
ordered lists should be done like this:
```
1. line 1
+ line 2
+ line 3 text
```
which **previews correctly** as:
1. line 1
2. line 2
3. line 3 text

but renders **incorrectly** when saving the comment.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
