### ISSUE TITLE
Expansive search

### ISSUE THREAD

**Issue by eltonps** [kanboard/kanboard#3768]
I think it's good if the search bar could be more expansive in the search.

### Actual behaviour
I can't search in mutiple fields. 

Eg: Search "term" in title OR description OR comment.
But no need to repeat the "term" in statement.

### Expected behaviour

Search a term in mutiple fields encapsulating the OR operand.
In this case the search will be more expansive.

**Comment by zpartakov** [comment]
totally agree with eltonps: a kind of "fulltext" searching everywhere (fields and all project) would be really appreciated, or at least some boolean operators combining fields - for me, it is the only feature really missing within this excellent software

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
