### ISSUE TITLE
"Access Forbidden" even when project published

### ISSUE THREAD

**Issue by binhsonnguyen** [kanboard/kanboard#3769]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour

I created a private project, after that i uncheck "private project" flag, but my friends still couldn't not access it (accesss by URL, or search)

### Expected behaviour

Accessible on "unprivated" projects

### Steps to reproduce

- Create a new private project
- Uncheck "Private project" in _Edit Project/Permissions and ownership_ menu.
- Update
- By another loged-in user, access project (by URL)

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment]
You have to add project members to your project in Project Settings > Permissions.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
