### ISSUE TITLE
CSS in input fields and texareas

### ISSUE THREAD

**Issue by rstockm** [kanboard/kanboard#3770]
You may consider to add this to your default CSS:

`input, textarea {
  padding-left: 5px;
}`

It's way more pleasing to the eyes. See the difference:

![image](https://user-images.githubusercontent.com/3195116/37407985-72496672-279b-11e8-91dc-fa3b47b94d1e.png)

It realy adds to a more polished look with no additional costs.

**Comment by rstockm** [comment]
(and yes, I am aware of the custom css field - but clean design should be a preset imho)

**Comment by fguillot** [comment]
What about sending a pull-request?

**Comment by rstockm** [comment]
Frankly speaking, I searched the repository but didn't find the .css

**Comment by DebianRoxx** [comment]
I have searched too and find sass file, updated it but what the next step ?
A contributor guide to install environment development will be nice.

**Comment by fguillot** [comment]
The contributor guide is part of the documentation:

https://github.com/kanboard/kanboard/blob/master/doc/en_US/index.markdown#contributors
https://github.com/kanboard/kanboard/blob/master/doc/en_US/assets.markdown#how-to-build-assets-javascript-and-css-files

**Comment by fguillot** [comment]
All right, I did it for you.
