### ISSUE TITLE
Request: Desktop notifications

### ISSUE THREAD

**Issue by juanjump** [kanboard/kanboard#3774]
Hello to all,
sorry but I speak bad English.

Is it possible to add Desktop Notifications (such as for example Trello)?
I need to use another program and at the same time a colleague assigns me a new task.

Thank you

**Comment by fguillot** [comment]
There is no desktop notifications.

**Comment by Qrizzz** [comment]
@juanjump you can use the Telegram plugin for Desktop and Mobile notifications.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
