### ISSUE TITLE
User Avataars Missing after migrating to new version

### ISSUE THREAD

**Issue by Inspop-Design** [kanboard/kanboard#3776]
We migrated to the latest version of kanboard and copied the data folder from previous set up.

Everything is working fine and no issues except that user Avatars aren't working. Issue is not only for existing uploaded avatars of existing users but even when we create new users and upload avatar, it doesn't works. Screenshots will explain.

Existing Users with Avatar Images Uploaded
http://take.ms/Dtlqi

DB files
http://take.ms/A8ZcH0
http://take.ms/kj4iL

New Users
http://take.ms/sFa1q

Image Reference in code
http://take.ms/LvtTi

Hope all explained well.

Also just to update, all migrations steps as documented were done as well (no other data issues).

**Comment by fguillot** [comment]
You should make sure the path in the database table match the path on the filesystem.

**Comment by Inspop-Design** [comment]
Thanks for the response.

However the path in the database table match the path on the filesystem. As we set a new avatar image, it gets uploaded to the desired path which is referred in DB as well. But images aren't rendered somehow.

**Comment by Qrizzz** [comment]
Clould be missing permissons. Is it a unix server?

**Comment by Inspop-Design** [comment]
Its IIS with MySql Installation. And on the folder everyone has the full rights (777).

**Comment by Qrizzz** [comment]
What about image Uploads in tasks? Do they work? Most of the time, either the path is wrong or the permissions are missing. What do you mean by everyone has full rights? PHP needs the permission to read the folder.

**Comment by fguillot** [comment]
- Check the log files for potential errors (web server and application)
- Open the image link directly in your browser (`?controller=AvatarController....`) and watch logs in your browser and your server
- Check the column `avatar_path` in the table `users` (same for other uploaded files)
- Compare with what you have on the filesystem
- Make sure the files and parent directories are accessible by the web server user

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"server configuration"**. If you need help to install Kanboard on your server, please, use the [forum](https://github.com/kanboard/forum/issues) to avoid polluting the bug tracker. Thank you for your understanding. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-did-you-close-my-question-on-the-bug-tracker).
