### ISSUE TITLE
Kanboard 1.2.1 Login Session Crashes with PHP Fatal error: Uncaught PicoDB\\SQLException

### ISSUE THREAD

**Issue by pcmc** [kanboard/kanboard#3777]
After the upgrade from Kanboard 1.0.48 to 1.2.0/1.2.1,
followed by the import the previous mysql data using the mysql source command,
I could then log on the Kanboard session using the admin account okay.
But soon later,  when I tried to a create user account, the session got crashed out,
prompting for the username and password again.
However subsequent login attempts using the same admin account and password will fail
as if the admin account/credential being invalid.

The kanboard/data/debug.log does not seem to show much details:
[2018-03-20 12:39:48] [debug] Kanboard\Core\Controller\Runner::executeMiddleware
[2018-03-20 12:39:48] [debug] Subscriber executed: Kanboard\Subscriber\BootstrapSubscriber::execute
[2018-03-20 12:39:48] [error] Kanboard\Core\Action\ActionManager::attachEvents: Automatic Action Not Found: KanboardActionTaskAssignSpecificUser
[2018-03-20 12:39:48] [error] Kanboard\Core\Action\ActionManager::attachEvents: Automatic Action Not Found: KanboardActionTaskEmail
[2018-03-20 12:39:48] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\AuthenticationMiddleware
[2018-03-20 12:39:48] [debug] Kanboard\Core\Controller\Runner::executeController => \Kanboard\Controller\AuthController::check

The /var/log/httpd/error_log reveals:
[Tue Mar 20 12:39:48.728280 2018] [php7:error] [pid 22455] [client 130.246.188.3:60530] PHP Fatal error:  Uncaught PicoDb\\SQLException: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'data' at row 1 in /var/www/html/kanboard-1.2.1/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php:351\nStack trace:\n#0 /var/www/html/kanboard-1.2.1/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php(245): PicoDb\\StatementHandler->handleSqlError(Object(PDOException))\n#1 /var/www/html/kanboard-1.2.1/vendor/fguillot/picodb/lib/PicoDb/Database.php(257): PicoDb\\StatementHandler->execute()\n#2 /var/www/html/kanboard-1.2.1/vendor/fguillot/picodb/lib/PicoDb/Table.php(218): PicoDb\\Database->execute('UPDATE `session...', Array)\n#3 /var/www/html/kanboard-1.2.1/app/Core/Session/SessionHandler.php(62): PicoDb\\Table->update(Array)\n#4 [internal function]: Kanboard\\Core\\Session\\SessionHandler->write('c8848ec2ebab14f...', 'redirectAfterLo...')\n#5 [internal function]: session_write_close()\n#6 {main}\n  thrown in /var/www/html/kanboard-1.2.1/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 351

Did try to have a look on StatementHandler.php but it is not that obvious which data row has exceeded its limit, and why it is affecting subsequent logins.

Much appreciated if anyone can advise how to identify where it has gone wrong.
Please kindly reply either to this thread, or directly to me at peter.chiu@stfc.ac.uk.

- PHP version: php71w  from mirror.webtatic.com/yum/el7/webtatic-release.rpm
- OS:   Centos 7.4.1708
- Browser:  Opera 51.0
- Maria DB 10.1 from http://yum.mariadb.org/10.1/centos7-amd64

Configuration: /var/www/html/kanboard/config.php

[config.php.txt](https://github.com/kanboard/kanboard/files/1829382/config.php.txt)

[screenshot 2018-03-20 12 59 02](https://user-images.githubusercontent.com/7513456/37656037-cf4cc024-2c3e-11e8-9b19-b36054ee556d.png)

**Comment by fguillot** [comment]
If you have installation issues, please use the forum https://kanboard.discourse.group/
