### ISSUE TITLE
Automatic Actions not changing color based on priority when creating multiple tasks

### ISSUE THREAD

**Issue by lionel-bijaoui** [kanboard/kanboard#3779]
### Actual behaviour
When multiple task are created, only the first one is colored from the automatic action

### Expected behaviour
When multiple task are created, all task should behave accordingly to the automatic action created

### Steps to reproduce
Create an automatic action that change the color (red for example) based on priority 0.
Go to any column in your project and click on the name of the column to display the menu then choose create multiple task at the same time ("Créer plusieurs tâches en même temps" in French).
Add at least 2 lines in the "Task" `textarea` and save.
The first task will be colored but the others will not be.

### Configuration

- Kanboard version: 1.2.1
- Database type and version: SQLite 3.21.0
- PHP version: 7.1.15
- OS: Windows
- Browser: Firefox/Chrome

**Comment by SladeP** [comment]
@lionel-bijaoui  I've tested this in every way I can think of, and automatic actions are applying to all tasks created in bulk. Will you let me know if the issue is persisting?

@fguillot I have reviewed this task and if they don't respond, it will be good to close.

**Comment by lionel-bijaoui** [comment]
@SladeP Thank you. I will test it tomorrow at work, sorry for the delay.

**Comment by lionel-bijaoui** [comment]
Not a problem anymore in 1.2.8, thank you
