### ISSUE TITLE
Feature Request: Editor replacement hook

### ISSUE THREAD

**Issue by J-Schuck** [kanboard/kanboard#3780]
The request is basically in the title.

We're using kanboard in our business, but we're always getting complains about the markdown syntax usage and how the editor handles the formatting. 

We're underway in trying to replace the editor and would like to do that in the least intrusive and easiest to maintain fashion of course, so a plugin, that we can simply drop in and exchange as we see fit would be optimal.

So if it's feasible i would like to request a hook  to plug our own editor in.

Thank you.

**Comment by creecros** [comment]
Everything exists to do what you want to do as a plugin. 
[Override the templates you need](https://github.com/kanboard/kanboard/blob/master/doc/en_US/plugin-overrides.markdown)
[And use your own helpers]
(https://github.com/kanboard/kanboard/blob/master/doc/en_US/plugin-helpers.markdown)

or use current hooks to Add the links to use the templates and helpers, maintaining the ability to use the markdown editor and adding the ability to use a different editor.

**Comment by J-Schuck** [comment]
All right i'll look deeper into it. Thanks.

**Comment by fguillot** [comment]
You should be able to replace the editor by overriding the method `textEditor()` of `FormHelper`. 

https://docs.kanboard.org/en/1.2.3/plugins/helpers.html
