### ISSUE TITLE
Web App Firewall (WAF) raises sql injection issue on filtering in Kanboard

### ISSUE THREAD

**Issue by freddrat** [kanboard/kanboard#3785]
This software focus on simplicity, the number of features is voluntary limited.

### Actual behaviour
When filtering for category a/o assignee, I get "403 forbidden" from WAF which is activated in Apache Web Server. The origin is a rule from OWASP Top 10 checking for possible SQL injections.

Reason is "double quotation marks"-usage directly in search query: e.g. &search=+category%3A"db"

### Expected behaviour
Filtering must not use quotation marks in search query to prevent errors from a WAF. For category this quotations can simply be removed. For assignee (if full name consists white space) quotations must be inserted later on.

### Steps to reproduce
Install kanboard on Apache WebServer with modsecurity activated.

### Configuration

- Kanboard version: 1.2.1
- Database type and version: MySQL 5.6
- PHP version: 5.6.34
- OS: Windows
- Browser: Firefox

**Comment by fguillot** [comment]
As mentioned in the documentation, Kanboard is not compatible with mod_security.
