### ISSUE TITLE
Make it easier to move an issue to a different column or swimlane

### ISSUE THREAD

**Issue by sandromario** [kanboard/kanboard#3786]
My task board has become quite large, with lots of tickets in different swimlanes. I therefore find it increasingly difficult to move tickets to the right position (i.e. to a different column or swimlane).

I think the expected behaviour would be to add options for "Column" and "Swimlane" in the little preview dialog which opens when the user clicks on the "board and pen" symbol. It's not very intuitive for the user (IMHO) to be able to change the name of a ticket so easily, but not its position (column and swimlane).

**Comment by sandromario** [comment]
I have implemented this myself. @fguillot, please could you give me permission to push a branch to your repo, such that I can create a pull request? Many thanks.

**Comment by sandromario** [comment]
@fguillot Did you see my question?

**Comment by gerald2545** [comment]
hi @sandromario,
why don't you fork kanboard, commit/push to your fork and then submit a pull request?
Gerald

**Comment by hoducha** [comment]
You can move a task to another position on the board (swimlane or column). Open the task page and you can see the Move Position menu on the left.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
