### ISSUE TITLE
Excessive visits to my webpage?

### ISSUE THREAD

**Issue by Silversunset01** [kanboard/kanboard#3788]
I am running into a TON of webpage hits after installing Kanboard, and it all seems to stem from:
`/kanboard/?controller=UserAjaxController&action=status`
whatever it is is logging hits every minute or so and causing my entire site to have I/O faults no matter what i do.

What is this, what does it do, and how do i keep it from spamming my host.

- Kanboard version: 1.2.1

**Comment by fguillot** [comment]
Kanboard needs to perform Ajax requests regularly. The request that you mentioned is made every 60 seconds. You could modify the source code if you want to change this behavior: https://github.com/kanboard/kanboard/blob/master/assets/js/components/session-check.js
