### ISSUE TITLE
Support Emojis for MySQL (use utf8mb4 instead of utf8)

### ISSUE THREAD

**Issue by indrisepos** [kanboard/kanboard#3789]
### Actual behaviour
Edit the task with "😊" -> Save -> "Internal Error: SQL error"

### Expected behaviour
Save the task without error message.

### Steps to reproduce
I can reproduce. Copy: "😊", paste, save...

### Screenshots
After save: "Internal Error: SQL error"

### Configuration

- Kanboard version: v1.1.0  e2eec8b7e75223cb4499de10e005cdb9e153868a
- Database type and version: MySQL 5.6.16-1~exp1 - (Ubuntu)
- PHP version: 7.0.28-1+ubuntu16.04.1+deb.sury.org+1 fpm-fcgi
- OS: Ubuntu 16.04
- Browser: Google Chrome 65.0.3325.181

Application version: master
PHP version: 7.0.28-1+ubuntu16.04.1+deb.sury.org+1
PHP SAPI: fpm-fcgi
OS version: Linux 4.4.0-116-generic
Database driver: mysql
Database version: 5.6.16-1~exp1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by creecros** [comment]
Which plug-ins do you have installed? If any.

**Comment by fguillot** [comment]
Emojis are not really supported with Mysql. The database have to be re-encoded in utf8mb4 instead of utf8.

**Comment by indrisepos** [comment]
Hi, This is my plugins list:




2018-03-28 01:15 keltezéssel, creecros írta:

**Comment by indrisepos** [comment]
Hi,

Thank you for your advice. I converted the 'tasks' table to utf8mb4. I 
could not save the emoji. Maybe this issue not urgent, but interest how 
to make a good workaround


2018-03-29 04:04 keltezéssel, Frédéric Guillot írta:

**Comment by fguillot** [comment]
This is now available in the development version but you should probably wait the next stable version. Some plugins needs to be updated as well.

Note: Do not make any changes manually in the database, otherwise the migrations will fail during the next upgrade (and you will be on your own to fix that).
