### ISSUE TITLE
Improvement: Easier closing of dialogs

### ISSUE THREAD

**Issue by felixdivo** [kanboard/kanboard#3791]
### Actual behaviour

When a window like seen below is opened, it cannot be closed by clicking on the grayed out area around it. 

### Expected behaviour

That the grayed out are is not clickable was unexpected for me and a better experience might be to let users click it in order to close the window. At least, when the user has not entered any text or other input, like when viewing comments. The behaviour in cases where the user has given some input could be discussed as well. Over all, this would make the service feel **way more** interactive, modern and effortless to use. (Obviously only from my point of view.)

### Steps to reproduce

There are many ways to to this:
- open a task and click "Add a sub-task"
- open a board and click on the comment icon of a task (lower right corner)
- click on "My activity stream" on the top
- click on the plus symbol in the upper right corner and then select "New private project" from the appearing drop-down menu
- ...

### Screenshots

The area marked red (the entire grayed out area) should be clickable: 

![image](https://user-images.githubusercontent.com/4403130/38046037-cea03012-32be-11e8-939a-5f1ea3b350c9.png)

### Configuration

- Kanboard version: unknown, although probably not too old (I was not able to find this out, since I am not hosting it)
- Database type and version: unknown (see above)
- PHP version: unknown (see above)
- OS: Kubuntu 16.04 / Windows 10 Version 1709
- Browser: Chromium Version 65 (on Kubuntu), Chrome Version 65.0.3325.181 (on Windows), MS Edge Version 41.16299.248.0/Engine Version 16.16299 (on Windows)

**Comment by fguillot** [comment]
Actually, it was like that before but people start to complaint because clicking inadvertently on the background was closing the modal dialog and they were losing data entered in forms. To prevent this, some kind of warning need to be implemented, for example a message box that say _"hey you filled the form, do you really want to close this?"_.

**Comment by felixdivo** [comment]
Yeah, and it should silently work for dialogs that do not allow any input.

**Comment by jamesrascal** [comment]
There is a jQuery plugin that may be able to handle this: http://plugins.jquery.com/are-you-sure/

**Comment by aljawaid** [comment]
The warning would be better than the new system.  Clicking elsewhere in the black area was a timesaver when viewing dialog popups.

**Comment by fguillot** [comment]
This is now implemented with the pull-request #4044.
