### ISSUE TITLE
Can't create task with setted date (german language)

### ISSUE THREAD

**Issue by BlackDark** [kanboard/kanboard#3793]
If the user configures the profile to use german language there are some problems with creating tasks.

### Actual behaviour
You want to create a tasks and set e.g. the due date to some value. If you try to save you get the error for invalid date: "Ungültiges Datum".

It could be a problem with the wordings in german. Instead of am/pm there are other translations.

### Expected behaviour
You can create the tasks without an error

### Steps to reproduce
Change the language to german and try to create a task with a date in a project.

### Screenshots
![image](https://user-images.githubusercontent.com/9947112/38083739-ca19f708-334a-11e8-84cf-a0a6dd02cd1d.png)

![image](https://user-images.githubusercontent.com/9947112/38083756-d9e38604-334a-11e8-9221-4a86c864c7e3.png)

### Configuration

- Kanboard version: 1.2.1 docker version
- Database type and version: -
- PHP version: -
- OS: Windows 7
- Browser: Chrome 65

**Comment by Qrizzz** [comment]
Can you try to change the date format in `Settings > Application settings` to `d.m.Y`?

**Comment by BlackDark** [comment]
Changed but still not working

**Comment by Qrizzz** [comment]
Sorry, I think the problem is the time format `g:i a`. `H:i` should work. The datepicker expects am/pm but it’s translated to vorm./nachm. – I think that is the issue

**Comment by BlackDark** [comment]
Yep, you're right. In `H:i` format it is working. Seems to be a problem with the datepicker expecting am/pm

**Comment by SladeP** [comment]
So, looking this over, in the file `assets/vendor/jqueryui-timepicker-addon/i18n/jquery-ui-timepicker-addon-i18n.min.js` you could change this part `amNames:["vorm.","AM","A"],pmNames:["nachm.","PM","P"]` to `amNames:["AM","A"],pmNames:["PM","P"]` and re-compile javascript. This would remove those options from the datepicker altogether and prevent this error from happening. 

I'll still dig more though and see if it's a setting with datepicker you can adjust so we don't have to edit vendor files and risk regression when updating datepicker.
