### ISSUE TITLE
Feature Request: Insert timestamp

### ISSUE THREAD

**Issue by gnubyte** [kanboard/kanboard#3794]
While Kanboard in existing format is FANTASTIC!, from an end user perspective there are times I do not want to rely on the timestamp of my post/comment/task itself, and am posting a timestamp for enrichment purposes... Is is possible to a insert timestamp feature next to the  bold/italic/underline/code buttons in the UI?

**Comment by fguillot** [comment]
I don't really understand what you are asking for. You should provide examples.

**Comment by gnubyte** [comment]
![kanboardidea](https://user-images.githubusercontent.com/16541000/38177533-cd597e64-35d1-11e8-9b0c-bd658037448d.png)
Sure, here is a screenshot of what I am thinking might be cool to have.

Essentially a button that takes the browser time and throws it to wherever your current cursor position is in the task editor.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
