### ISSUE TITLE
demo data plugin

### ISSUE THREAD

**Issue by bdeshayes** [kanboard/kanboard#3797]
I would like to write a new plugin to generate some sample demo data.
Is that all right with you?

NB Felicitations pour un projet phenomenal!

**Comment by fguillot** [comment]
You don't need the permission of anyone to create a plugin. Just do it :)

**Comment by bdeshayes** [comment]
Just released 
https://github.com/bdeshayes/Kanboard-plugin-DemoData

May it be listed at
https://kanboard.org/#plugins
