### ISSUE TITLE
new task saing error

### ISSUE THREAD

**Issue by creativeautomaton** [kanboard/kanboard#3799]
This issue is: 
 
[] Bug report 

### Actual behaviour
on click of save button on latest dev ver the save button just jumps and not saving loader shows up and nothing happens. just a buton jump every time you click the save task submit button.

### Expected behaviour

save the new task

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

[Frequently Asked Questions](https://docs.kanboard.org/en/latest/developer_guide/faq.html)

**Comment by fguillot** [comment]
You don't really provide any information to reproduce the issue.

See: https://docs.kanboard.org/en/latest/developer_guide/faq.html#how-to-make-a-bug-report
