### ISSUE TITLE
Text hardcoded

### ISSUE THREAD

**Issue by wintstar** [kanboard/kanboard#3804]
This issue is: Text not Translated

> this task is now linked to the task Nr 84 with the relation "relates to"

https://github.com/kanboard/kanboard/blob/dc7c7667ec2eb648ca097d00c25a00f7cc9a7d19/app/Template/notification/task_internal_link_create_update.php#L5

https://github.com/kanboard/kanboard/blob/7399c3c59632712b0e9da778dd542fc681a5e0c3/app/Template/event/task_internal_link_create_update.php#L11

[x] Bug report
[] Feature request
[] Improvement

### Screenshots
![text_not_translate](https://user-images.githubusercontent.com/2753863/38299166-94740de2-37f9-11e8-87c1-636ee83b6c4e.PNG)

### Configuration
- Kanboard version: 1.2.2
- Database type and version: mysql 5.6.37-log
- PHP version: 7.1.15
- OS: SunOS localhost 5.10 Generic_150401-49 i86pc SunOS localhost 5.10 Generic_150401-49 i86pc
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

[Frequently Asked Questions](https://docs.kanboard.org/en/latest/developer_guide/faq.html)

**Comment by fguillot** [comment]
The code has been updated but someone have to update the German translation now.

**Comment by wintstar** [comment]
Many Thanks 

```
    // 'Diese Aufgabe ist jetzt verknüpft mit der Aufgabe %s mit der Relation "%s"' => '',
    // 'Die Verknüpfung mit der Relation "%s" zur Aufgabe %s wurde entfernt' => '',
    // 'Custom Filter:' => 'Benutzerdefinierter Filter:',
```

**Comment by fguillot** [comment]
The German translation is now up to date. Thanks.
