### ISSUE TITLE
Webhook, back to nobody (owner_id=0) seems impossible

### ISSUE THREAD

**Issue by opitux** [kanboard/kanboard#3805]
This issue is:

[x] Bug report

### Actual behaviour
I am working on gogs webhook improvement and if I try to update the owner of a task from an assigned user back to nobody (owner_id=0), nothing happen. Updating a task to a different owner_id who works on the project succeeds however.

It look similar to https://github.com/kanboard/kanboard/issues/1700

```
/**
 * Handle unassigned issue
 *
 * @access public
 * @param  array    $issue   Issue data
 * @return boolean
 */
public function handleIssueUnassigned(array $issue)
{
    $task = $this->taskFinderModel->getByReference($this->project_id, $issue['issue']['number']);

    if (! empty($task)) {
        $event = array(
            'project_id' => $this->project_id,
            'task_id' => $task['id'],
            'owner_id' => 0,
            'reference' => $issue['issue']['number'],
        );

        $this->dispatcher->dispatch(
            self::EVENT_ISSUE_ASSIGNEE_CHANGE,
            new GenericEvent($event)
        );

        return true;
    }

    return false;
}
```

### Expected behaviour

Being able to assigned a task to nobody (owner_id = 0) with a webhook

### Configuration

- Kanboard version: 1.2.2
- Database type and version:sqlite 3.11.0
- PHP version:7
- OS:Ubuntu 16.04
- Browser:Firefox

Thanks a lot :)

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.13/developer_guide/faq.html).
