### ISSUE TITLE
Consistency between Search & API

### ISSUE THREAD

**Issue by dhornford** [kanboard/kanboard#3806]
This issue is:

[X] Bug report
[] Feature request
[X] Improvement

### Actual behaviour
Priority can be identified in the API, but cannot be filter for (advanced search syntax)
Complexity can be filtered for (*advanced search syntax), but not loaded through the API

We have several boards with a large number of well structured cards. We routinely use the API to update cards. As part of a performance improvement we wanted to focus more on priority. We cannot filter the display by priority, but can filter by complexity - so we decided fine we'll use complexity as a stand-in

However we cannot see in UpdateTask how to update Complexity

### Expected behaviour
Filtering by Priority (advanced search syntax)

### Steps to reproduce
Advanced search syntax

### Configuration

- Kanboard version: 1.2.1
- Database type and version: Mysql
- PHP version: 7
- OS: Server Centos client Windows & Mac
- Browser: Many

[Frequently Asked Questions](https://docs.kanboard.org/en/latest/developer_guide/faq.html)

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
