### ISSUE TITLE
Add a project logo/avatar

### ISSUE THREAD

**Issue by lohierf** [kanboard/kanboard#3808]
It would be very useful to be able to add a logo for each project in Kanboard, like the project avatar in Github/Gitlab. It helps users to quickly identify a project on their dashboard.

**Comment by creecros** [comment]
@fguillot Do you want a plugin or a PR?

**Comment by creecros** [comment]
Added functionality to @BlueTeck 's Coverimage Plugin.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
