### ISSUE TITLE
存在任务导出后没法在正常导入到的看板中去

### ISSUE THREAD

**Issue by MrLee91** [kanboard/kanboard#3809]
This issue is:

- [ ] Bug report
- [ ] Feature request
- [ ] Improvement

- Please, read the [Frequently Asked Questions](https://docs.kanboard.org/en/latest/developer_guide/faq.html).
- Ask questions on the [Forum](https://github.com/kanboard/forum/issues).

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment]
This is an invalid bug report, see https://docs.kanboard.org/en/latest/developer_guide/faq.html#how-to-make-a-bug-report
