### ISSUE TITLE
See the dates of the sub-tasks in the calendar (Plugin)

### ISSUE THREAD

**Issue by luciefz** [kanboard/kanboard#3812]
Hi,

I installed the calendar plugin (which is very good). however, it doesn't display the dates of the subtasks. I tried to modify the format() function of the TaskCalendarFormatter.php file to add a new events[] but it doesn't work. Does anyone have a solution? 

Thank you very much.

### Configuration
- Kanboard version: 1.2
- PHP version: 7
- OS: linux
- Browser: chrome

**Comment by creecros** [comment]
Tried how? Link code

**Comment by luciefz** [comment]
It probably wasn't correct, but I tried to get the date of a subtask with a foreach. 

foreach ($task['subtasks'] as $subtask){
     foreach ($subtasks as $subtask){
		$dateSubTask = $subtasks['due_date'];
     }
}

It doesn't work anyway and I don't know if it's in this function that I should modify.
I'm not an expert at all :/

**Comment by fguillot** [comment]
Please, do no duplicate issues everywhere. You already created the same here https://github.com/kanboard/plugin-calendar/issues/15
