### ISSUE TITLE
Role and permissions is unreasonable

### ISSUE THREAD

**Issue by Crandy** [kanboard/kanboard#3815]
This issue is:

- [ ] Bug report
- [ ] Feature request
- [*] Improvement

I find the role of "Project Member" can change the task assigned to him, I think this is unreasonable, the  task assigned to someone can change only by Project Manager, so, i hope this can be improved by next version.
Of course, i create a new custom role, but cannot deal with this problem.

### Configuration

Version： master.8c5b9925c49bc1a989cdc5e146ce79543fdf7f0a
PHP Version： 7.1.16
PHP SAPI： fpm-fcgi
OS： Linux 3.10.0-693.11.1.el7.x86_64
DB Driver： sqlite
DB Version： 3.21.0
Browser： Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by fguillot** [comment]
This feature won't be changed because this is the standard behavior since this software exists. Altering the permissions of this role will introduce a breaking change for all Kanboard users.

Since everyone manage projects differently, it's impossible to satisfy everyone. So, use custom roles.

**Comment by creecros** [comment]
Agree with @fguillot , custom role should achieve very close to what you want, but from what I can tell, I do believe it is currently not behaving as expected #3787 .

**Comment by lastlink** [comment]
Most projects I've worked on the project members assign the stories to themselves, so this is typically the most common behavior trying to take some of the micromanagement off of the project manager. Although the custom roles should allow for the changed behavior if they are working properly.

**Comment by creecros** [comment]
if you take a look at the projectAccessMap, I think you could limit a Project Member the way you want. 

Would be similar to this plugin: https://github.com/creecros/opencomment
But instead of adding abilities, you'd be taking them away.
