### ISSUE TITLE
improve text in notification options

### ISSUE THREAD

**Issue by RoelNoorman** [kanboard/kanboard#3817]
This issue is:

- [ ] Bug report
- [ ] Feature request
- [x] Improvement

- Please, read the [Frequently Asked Questions](https://docs.kanboard.org/en/latest/developer_guide/faq.html).
- Ask questions on the [Forum](https://github.com/kanboard/forum/issues).

### Actual behaviour
the options for notification says: "Only for tasks created by me and assigned to me"  
the meaning of "and" can be misunderstood. I read it as a logical 'and' while it appears to work as a logical 'or' 

### Expected behaviour
suggested text: Only for tasks created by me and **tasks** assigned to me

### Configuration

- Kanboard version: 1.2.0
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment]
PR #3851 has been merged.
