### ISSUE TITLE
Subtask notifications : translation of the status and presence of the time management

### ISSUE THREAD

**Issue by kent1D** [kanboard/kanboard#3818]
This issue is:

- [ ] Bug report
- [ ] Feature request
- [x] Improvement

- Please, read the [Frequently Asked Questions](https://docs.kanboard.org/en/latest/developer_guide/faq.html).
- Ask questions on the [Forum](https://github.com/kanboard/forum/issues).

### Actual behaviour

The statuses in the notification are not translated.

There is an empty value for time management if there is not time set. This shouldn't be in the notification if not set.

### Expected behaviour

Having the statuses translated.

Delete the time management li if not used.

### Configuration

- Kanboard version: 1.2.2

**Comment by fguillot** [comment]
Your PR has been merged.
