### ISSUE TITLE
Error 403 on task creation

### ISSUE THREAD

**Issue by CPUGPU** [kanboard/kanboard#382]
Completely stock install of Kanboard on Apache "compatible" LiteSpeed web server with PHP 5.3.28 and mbstring and pdo_sqlite installed and extensions enabled.

Except creating tasks, other functions work including creating projects and users.  Go to a board and click on any of the plus signs to create a task and get a 403 error.  Suggestions for troubleshooting?

**Comment by dantahoua** [comment]
Same problem here, I have access to the log but there is none generated!
-Apache, PHP 5.5, RedHat, cPanel...
Work perfectly on my local machine. If I could reproduce it local, maybe I could get a log!

**Comment by joeaston** [comment]
I encountered the same issue with LiteSpeed (unable to create tasks using board column heading links), but no errors showed in the log - only a 403 header was sent to the browser.

**Disabling mod_security has fixed the problem for now.**

**Comment by Stevonjugush** [comment]
Thanks joeston.. That fixed my problem too.. Am just wondering why its forbidden when the mod_security is on

**Comment by jcfrog** [comment]
Same problem here. Can't use it anymore. 
Was working perfectly and suddenly access right troubles.
`myboard/?controller=taskcreation&action=create&project_id=5&column_id=17&swimlane_id=0` => 403

**Comment by Stevonjugush** [comment]
test

**Comment by krembo99** [comment]
Same problem here ..

**Comment by jcfrog** [comment]
realizing this bug is closed. Sadly it is still alive :(
Hopefully keyboards shortcuts are still working, but that's just a workaround 
#stuck

**Comment by standardspace** [comment]
Disabling mod_security is not really a viable option. Has anyone found a better solution?

**Comment by davibertolini** [comment]
Hello, we are getting a 404 error on creating a Task. We disabled mod_security, uncommented RewriteBase /, moved .htaccess to root directory... 

When clicking on Menu > Create task:
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (kanboard, line 0)

https://www.mysite.com/kanboard/?controller=TaskCreationController&action=save&project_id=7

When clicking on the + of the column:
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (kanboard, line 0)

https://www.mysite.com/kanboard/?controller=TaskCreationController&action=show&project_id=7&column_id=30&swimlane_id=8

**Comment by CPUGPU** [comment]
Still appears to be a problem for users.  I'll leave it open, let Kanboard close it if they feel appropriate.

**Comment by fguillot** [comment]
Maybe you guys can contribute to make the software compatible with mod_security.
