### ISSUE TITLE
C'mon can someone please just give CLEAR instructions on how to use this with MySQL. 

### ISSUE THREAD

**Issue by OyeBenny** [kanboard/kanboard#3820]
I'm using Digital Ocean Ubuntu 16.

Error:
Internal Error: PHP extension required: "pdo_sqlite"

I've already changed the config.default.php file info to mysql from sqlite.

I've already created a mysql database table with the default name.

**Comment by rdnn** [comment]
config.default.php needs to be renamed to config.php

https://docs.kanboard.org/en/latest/admin_guide/config_file.html

**Comment by OyeBenny** [comment]
Thank you for reply.

But I did that as well and still doesn't work.

**Comment by fguillot** [comment]
https://docs.kanboard.org/en/1.2.2/admin_guide/mysql.html

**Comment by OyeBenny** [comment]
Thank you!
This worked!

Question, what is the default username and password?

**Comment by OyeBenny** [comment]
Its admin admin in case someone needs it.
