### ISSUE TITLE
Board color or image background plugin

### ISSUE THREAD

**Issue by ferslash** [kanboard/kanboard#3821]
This issue is:

- [ ] Bug report
- [x] Feature request
- [ ] Improvement

### Expected behaviour
I know this feature has been asked before, but, please, considere it, even with grate limitations it would be grate, even just a background color to chose or imput by text (exagesimal color) 

(grate software thanks a lot for sharing it)

**Comment by ChangePlaces** [comment]
Can't you use the CSS editor?

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html).
