### ISSUE TITLE
Make subtask title text field wider when editing subtasks

### ISSUE THREAD

**Issue by psy-q** [kanboard/kanboard#3824]
This issue is:

- [ ] Bug report
- [ ] Feature request
- [X] Improvement

### Actual behaviour

When editing a subtask, the field for the title is very narrow (300px) and only allows viewing 2 - 3 typical words in German and other languages with long compound words. The rest of the dialog's width goes unused and is blank.

### Expected behaviour

The subtask title input field should be wide enough to enter10, 15 words (or alternatively fill the whole available width).

### Steps to reproduce

Edit a subtask.

### Screenshots

![screenshot_20180418_162140](https://user-images.githubusercontent.com/87557/38937945-b43a4f7a-4324-11e8-9a3a-21eee774cae8.png)

### Configuration

 - Version: 1.2.0
 - PHP Version: 7.0.27-0+deb9u1
 - PHP SAPI: apache2handler
 - OS Version: Linux 4.9.0-6-amd64
 - Datenbanktreiber: mysql
 - Datenbank Version: 10.1.26-MariaDB-0+deb9u1
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by fguillot** [comment]
This change has been made is the development branch.
