### ISSUE TITLE
can not attach file in wiki plugin

### ISSUE THREAD

**Issue by ppierluigi** [kanboard/kanboard#3826]
This issue is:

 [ ] Bug report

### Actual behaviour
can not attach files in the wiki 

### Expected behaviour
normal attach

### Steps to reproduce
upgrade and try to attach

### Logs
[Thu Apr 19 12:29:12.358820 2018] [php7:error] [pid 23444] [client 172.21.200.51:61117] PHP Fatal error:  Class 'Kanboard\\Plugin\\Wiki\\Model\\FileModel' not found in /var/www/html/kanboard/plugins/Wiki/Model/WikiFile.php on line 11

namespace problems?

### Configuration

    Application version: 1.2.1
    PHP version: 7.1.14
    PHP SAPI: apache2handler
    OS version: Linux 3.10.0-327.el7.x86_64
    Database driver: mysql
    Database version: 10.1.31-MariaDB
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by fguillot** [comment]
Post your issue here: https://github.com/funktechno/kanboard-plugin-wiki/issues
