### ISSUE TITLE
Sidebar description to the left instead above the columns

### ISSUE THREAD

**Issue by TWConsult** [kanboard/kanboard#3828]
This issue is:

- [ ] Bug report
- [ ] Feature request
- [x] Improvement

### Actual behaviour
Swimline is a row above the columns.

### Expected behaviour
To clean up the UI following feature is asked for:
- switch the Swimline row to a column (by settings or plugin)

### Screenshots
![image](https://user-images.githubusercontent.com/13416945/39085764-d4bf5532-4587-11e8-9393-f7057c930662.png)

If there is an idea to do it by a plugin, feel free to advice and I will contribute to the project

**Comment by fguillot** [comment]
Actually, it was like that before but it was taking too much space.

**Comment by lastlink** [comment]
@fguillot I think this should be closed, this functionality doesn't need to be changed. Also @TWConsult  hasn't made any other comments. There should be a maximum amount of time before auto closing an issue if the submitter doesn't clarify what they need.
