### ISSUE TITLE
Task Sorting in Board View

### ISSUE THREAD

**Issue by futzco** [kanboard/kanboard#3831]
This issue is:

- [x] Feature request

I know some version of this has been discussed in the past many times, but please bear with me.

As projects grow in complexity and users, it becomes harder and harder to easily navigate the tasks.

Here's how I believe sorting in "Board" view should be implemented:
 - Next to each column's name (on each swimlane independently, not at the top across all swimlanes), a dropdown named "Sort by" should be displayed.
 - Clicking the dropwdown will review a list of sorting options. Selecting one option will replace the "Sort by" text with the name of that option.
 - By default, "Position" sorting is selected (current behaviour).
 - At a minimum, the following sorting options should be available: "Due Date", "Start Date", "Task ID", "Last Moved", "Last Activity", "Priority", "Complexity", with options for either "Ascending" and "Descending" for all of them.
 - In case more tasks have the same position (like 2 tasks with same priority when sorting by "Priority"), the Task ID should be used for deciding between them.
- A similar dropdown to apply the same sorting options should be enabled for the entire "Board"/Project, entire "Swimlane", and entire "Column" (across all swimlanes). This would provide an easy way to apply the same sorting to multiple columns at the same time, and also provide a way to reset the sorting to default in case it gets too confusing at some point.
 - The sorting would be on a per user basis, and all the options will be saved in the database and not in a cookie.
 - To solve the problem with moving tasks between columns when not in the "Default" ("Position") sorting order, a simplified version (no "Swimlane", no "Column") of the pop-up displayed when "Move position" is clicked can be used.

I believe this feature is highly necessary. The above guidlines should provide the necessary functionality for most users of the current project.

If @fguillot allows, I am willing to start a bounty for this feature request. Those interested in contributing, please pledge your support in the comments. I am pledging $100 PayPal. In order to claim the bounty, your implementation of this feature request should be approved by @fguillot and included in future releases.

**Comment by karakayasemi** [comment]
We have similar needs in my company. If @fguillot accept it as a valid request, I can work for creating a pull request to solve this issue.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
