### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '[' in /app/functions.php on line 37

### ISSUE THREAD

**Issue by Victor-IT** [kanboard/kanboard#3832]
This issue is:

- [x] Bug report
- [ ] Feature request
- [ ] Improvement

Hello. Can you help me, please?
I'm trying to run daily background job.
I wrote a sh script file. Cron executes it every day at 6 o'clock.
```
#!/bin/bash
date >> bgjob.LOG
cd ~/kanboard && ./cli cronjob >> bgjob.LOG 2>&1
```
### Actual behaviour
None of the **automatic actions** were triggered. (example: close task after 1 day)

### Logs
There are log records in my LOG file.
```
...
Fri Apr 20 06:00:01 MSK 2018
PHP Parse error:  syntax error, unexpected '[' in /kanboard/public_html/app/functions.php on line 37
Sat Apr 21 06:00:01 MSK 2018
PHP Parse error:  syntax error, unexpected '[' in /kanboard/public_html/app/functions.php on line 37
...
```
### Expected behaviour
Run of backgroun job every day by cron shedule.

---
- Kanboard version: 1.2.3
- Database type and version: MySQL 5.5.52-38.3
- PHP version: 5.6.30
- OS: Linux 4.9.79
- Browser: Chrome/66.0.3359.117

**Comment by Victor-IT** [comment]
same problem with PHP 7.1.9

**Comment by diego-betto** [comment]
Maybe your cli version is not the same as the web server version. 
Run a simple `php -v` anche check if it's >= 5.4

**Comment by Victor-IT** [comment]
yep it is PHP 5.3.29 (cli) (built: Aug 19 2016 17:49:16)
what package need to install?

**Comment by diego-betto** [comment]
It depends. The minimum required version is 5.4.
> As of PHP 5.4 you can also use the short array syntax, which replaces array() with [].
[http://php.net/manual/en/language.types.array.php](http://php.net/manual/en/language.types.array.php)

Personally I tend to keep same versions for cli and web server. 
Check your environment/project if this update can break something

**Comment by diego-betto** [comment]
@fguillot I think you can close this one

**Comment by fguillot** [comment]
You must have at least PHP 5.6 (for the web server and cli).

https://docs.kanboard.org/en/1.2.3/admin_guide/requirements.html#php-versions

**Comment by Victor-IT** [comment]
Oh, my webhoster tells that trough console I can use different php versions:
**/opt/php56/bin/php script_name.php**
can you help me adapt my sh script in this case?

**Comment by kent1D** [comment]
It seems you are using plesk or something similar. 

https://docs.plesk.com/en-US/onyx/administrator-guide/web-hosting/php-management/running-php-scripts-from-the-command-line.76345/

https://talk.plesk.com/threads/set-default-php-version-for-command-line.345940/

https://talk.plesk.com/threads/how-to-change-php-cli-version-from-5-4-to-highter.339906/
