### ISSUE TITLE
Do not allow edit/delete of sub-task for custom roles

### ISSUE THREAD

**Issue by limenleap** [kanboard/kanboard#3836]
This is a suggestion for Improvement

### Actual behaviour
Anyone can edit/delete a sub-task. This, in some situations, is not acceptable

### Expected behaviour
I wanted to create a custom for junior staff in an office so that they do not edit/delete a sub-task

### Steps to reproduce
Create any role and assign any permission to that role, but everyone is allowed to edit/delete a sub-task

### Recommendation

I changed line no 18 of  app/Template/subtask/table.php to the following

`<?php if ($editable && $this->projectRole->canRemoveTask($task)): ?>) `

Then only those who are allowed to remove the parent task can actually get the drop-down menu before the sub-task that is listed. Not sure if this is the right way to do it; but it seems good enough for me. Not sure if there are wrong side-effects

ONLY the project manager would get the aforementioned drop-down menu in the beginning of the sub-task 

None of the users with any other role, including any kind of custom role, would get the aforementioned drop-down menu before the sub-task.

A better refinement would have been to let the custom role have a specific restriction for removing the aforementioned side menu of the sub-task list

- Kanboard version:  1.2.3
- Database type and version: SQLite 3.11.0
- PHP version: 7.0.28-0ubuntu0.16.04.1
- OS: Ubuntu  16.04 Linux 4.4.0-1038-aws
- Browser:  Tested on Chrome and Opera

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
