### ISSUE TITLE
Cannot always click in bottom right hand corner of 'Save' button

### ISSUE THREAD

**Issue by sudoman** [kanboard/kanboard#3838]
This issue is:

- [✓] Bug report

### Actual behaviour

The user cannot always click on the bottom right hand corner of the 'Save' button located on the edit page for board settings.

### Expected behaviour

The user should be able to click anywhere on the save button for it to work.

### Steps to reproduce

Adjust your browser window so that it is about 1366 pixels wide.

View a board, go to settings, edit, then change some info. Scroll all the way down, then click 'Save' at the bottom of the page. Watch the green success message appear and cover the bottom right hand corner of the save button, then fade away. Then make more changes and try to click on the bottom right hand corner of the save button where the success message was. You cannot click on the save button in that location. If you click on the left side or upper part of the save button, then you can submit the form.

### Configuration

- Kanboard version: master
- Database type and version: SQLite
- PHP version: 7.1.16
- OS: GNU/Linux
- Browser: Firefox 59.0.2

**Comment by SladeP** [comment]
@sudoman this fix was merged into master so this issue should be good to close!

**Comment by sudoman** [comment]
Thanks! :smiley:
