### ISSUE TITLE
FreeBSD + Nginx don't accept admin / admin

### ISSUE THREAD

**Issue by Markus-** [kanboard/kanboard#384]
Hello,

I got a similar issue to issue 189. 
Fresh install and the default-combination is not accepted.
1. Download kanboard-latest.zip
2. unzip
3. make sure, that data-dir is writeable as webserver / php-fpm - user

Just got Username / Password required.

FreeBSD 10; Nginx 1.6.2; PHP 5.5

Any hints?
Regards
Markus

**Comment by therahulprasad** [comment]
In my case session was not getting started. 
I just added `session_start();` in line 2 of [index.php](https://github.com/kanboard/kanboard/blob/master/index.php). Now its working fine.
