### ISSUE TITLE
PHP Fatal error / database is locked

### ISSUE THREAD

**Issue by TmCTux** [kanboard/kanboard#3845]
I often have the following in my server log when someone is using kanboard (I didn't succeed to pinpoint to the action done at that time):

PHP Fatal error:  Uncaught exception 'PicoDb\\SQLException' with message 'SQL Error: SQLSTATE[HY000]: General error: 5 database is locked' in /var/www/html/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php:351\nStack trace:\n#0 /var/www/html/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php(245): PicoDb\\StatementHandler->handleSqlError(Object(PDOException))\n#1 /var/www/html/vendor/fguillot/picodb/lib/PicoDb/Database.php(257): PicoDb\\StatementHandler->execute()\n#2 /var/www/html/vendor/fguillot/picodb/lib/PicoDb/Table.php(218): PicoDb\\Database->execute('UPDATE "session...', Array)\n#3 /var/www/html/app/Core/Session/SessionHandler.php(63): PicoDb\\Table->update(Array)\n#4 [internal function]: Kanboard\\Core\\Session\\SessionHandler->write('ubIjbOJgi,TwCjl...', 'user|a:22:{s:2:...')\n#5 [internal function]: session_write_close()\n#6 {main}\n  thrown in /var/www/html/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 351

Nevertheless, no issue reported by user, so I don't really know if this "Fatal Error" is damaging anything.

thanks.

**Comment by fguillot** [comment]
Please, use the template to report bugs.
