### ISSUE TITLE
[ask] Mapping a swimlane into seperate project

### ISSUE THREAD

**Issue by veenone** [kanboard/kanboard#3850]
Hi,

Is it possible for us to set a swimlane of a board into a seperate project ?
In my case, my main kanban board has several swimlanes which represent projects. I want to have a single project which is linked to the swimlanes on the main kanban board which reflects all tasks inside the swimlane into its project board. 

if it is not possible on the current version, having this feature in the next version would be nice :)

**Comment by fguillot** [comment]
It's not possible in the current version and not planned (the data model is not adequate).

Please use the forum to ask questions.
