### ISSUE TITLE
Private Calendar does not show any assigned tasks

### ISSUE THREAD

**Issue by tobiasgraeber** [kanboard/kanboard#3852]
This issue is:

- [ x] Bug report
- [ ] Feature request
- [ ] Improvement

- Please, read the [Frequently Asked Questions](https://docs.kanboard.org/en/latest/developer_guide/faq.html).
- Ask questions on the [Forum](https://github.com/kanboard/forum/issues).

### Actual behaviour
Private Calendar does not show any assigned tasks

### Expected behaviour
Private Calendar should show any assigned tasks

### Steps to reproduce
Assign a Task to yourself, go to dashboard, click "my calendar"

### Configuration

- Kanboard version: 1.2.3
- Database type and version: mysql
- PHP version: 7.1
- OS: unix/apache
- Browser: mozilla ff

**Comment by fguillot** [comment]
Please, use this issue tracker for the calendar plugin: https://github.com/kanboard/plugin-calendar/issues
