### ISSUE TITLE
Make subtasks work as checklists

### ISSUE THREAD

**Issue by n1trux** [kanboard/kanboard#3855]
Hi, it would be a cool idea to make it possible to check subtasks with a single click, maybe in addition to a hotkey being pressed.

That'd make subtasks work like checklists (as described/wished for in #671, #1149, #2225).

Proposed features:
- option in project settings: "complete subtasks with single click"
- if set:
  - complete a subtask (make a checkmark appear in front of it) by simply clicking
  - start time tracking for subtask (cogwheels) by holding Shift + clicking
- if not set:
  - complete a subtask by holding Shift + clicking
  - start time tracking for subtask (cogwheels) by simply clicking

**Comment by fguillot** [comment]
Subtasks are already working as checklist, the only difference is you have 3 different states: todo, in progress and done. When you click on one subtask, it cycle to the next state.

I don't see how the end-users are going to guess they have to press on shift + click. This won't be possible on tablets or smartphones.

**Comment by n1trux** [comment]
>Subtasks are already working as checklist, the only difference is you have 3 different states: todo, in progress and done.

Correct. Then there could be an option to have only two states?

>This won't be possible on tablets or smartphones.

Tap-and-hold there?
