### ISSUE TITLE
Time formatting code in two additional templates may need updating

### ISSUE THREAD

**Issue by sudoman** [kanboard/kanboard#3857]
### Actual behaviour

In commit eafaa4b03770a73080520952112905eb8135a62f, hard-coded time format strings were updated, but it looks like these files were missed:

````
app/Template/notification/subtask_create.php
app/Template/notification/subtask_update.php
````

Grepping through the code didn't show me where those templates are in use, if at all.

### Expected behaviour

These templates should not have hard-coded time format strings.

### Configuration

- Kanboard version: master (eafaa4b03770a73080520952112905eb8135a62f)
- Database type and version: Sqlite3
- PHP version: 7
- OS: GNU/Linux
- Browser: Firefox

**Comment by sudoman** [comment]
Correction, only one Template was missed:

````
app/Template/notification/subtask_create.php
````

I'm working on a pull request for it.

**Comment by fguillot** [comment]
PR merged thanks
