### ISSUE TITLE
due:none doesn't work in Framaboard ?

### ISSUE THREAD

**Issue by pprel** [kanboard/kanboard#3859]
Hi,
I use Framaboard. I would be very interested in being able to filter tasks that doesn't have a due date. I have read forums and see that due:none should work.
It doesn't for me.
See, I have at least one task with no due date.
![image](https://user-images.githubusercontent.com/39195740/39932457-7cdcc232-5540-11e8-8600-bda03dcb8e30.png)
and when I look for due:none, it replies that I don't have any.
![image](https://user-images.githubusercontent.com/39195740/39932768-53a15530-5541-11e8-8116-3345ce04a825.png)

Thank you for your help.

**Comment by fguillot** [comment]
This bug tracker has nothing to do with Framaboard. The feature that you are looking for has been added in Kanboard 1.2.1: https://github.com/kanboard/kanboard/releases/tag/v1.2.1

You should ask Framasoft to upgrade the application. Their bug tracker seems to be there: https://framagit.org/framasoft/Framaboard

**Comment by pprel** [comment]
Thank you for the quick answer. Sorry I lost your time.
Thank you for your work.
