### ISSUE TITLE
Template hook request - template:search:task:footer and template:dashboard:task:footer

### ISSUE THREAD

**Issue by dmorlitz** [kanboard/kanboard#3863]
This issue is:

- [ ] Bug report
- [] Feature request
- [X ] Improvement

I was wondering if it would be possible to add the template hooks called template:search:task:footer template:dashboard:task:footer.

I have been working on a plugin that adds quick action buttons to each task card using the hook template:board:task:footer  While this works wonderfully, I would like to also expose these quick action buttons on the search results page and the dashboard.

If I understand correctly, there need to be 2 additional template hooks added to enable me to alter the contents rendered for each task on these screens.  Is it possible to get these hooks added?  (I guessed on what the proper names would be - please adjust as necessary to match current naming conventions)

Thank you.

     --David

**Comment by dmorlitz** [comment]
If this is going to be a difficult request, please feel free to let it pass.  I just realized that I can use the template:task:dropdown hook and the actions I am adding will appear everywhere, including the dashboard and search results.  It does require the extra click to pull the menu down versus just having an icon visible - but I can live with that.

**Comment by fguillot** [comment]
PR  #3895 has been merged.
