### ISSUE TITLE
Bug: Uninstall prompt for Incompatible Plugins not working

### ISSUE THREAD

**Issue by lastlink** [kanboard/kanboard#3871]
### Actual behaviour
On clicking on the **uninstall** button in the **Incompatible Plugins** row nothing happens.

### Expected behaviour
If an installed plugin appears in the **Incompatible Plugins** row then the **uninstall** button should work to prompt modal confirm dialog to uninstall the plugin.

### Steps to reproduce
Install the [Bigboard](https://github.com/stinnux/kanboard-bigboard) plugin and make sure that Kanboard is newer than 1.2.3. Then go to `plugins > installed plugins` & click the **uninstall** button.

### Screenshots
![incompatiblebigboard](https://user-images.githubusercontent.com/6679425/40214115-05387d66-5a27-11e8-8f9b-fc76707e45a3.png)

### Configuration

- Kanboard version: 1.2.4
- Database type and version: Mysql
- PHP version: 7.1
- OS: Linux
- Browser: Chrome

**Comment by Victor-IT** [comment]
Yup. I noticed this error of this plugin since 1.2.3 KB-version.
I had to remove the plugin from the plugins folder via FTP.

**Comment by SladeP** [comment]
@lastlink this fix was merged into master, so this issue should be good to close!
