### ISSUE TITLE
Plugin directory incorrectly identifying "Update" or "Up to date" for most(?) plugins

### ISSUE THREAD

**Issue by MDKAOD** [kanboard/kanboard#3873]
### Actual behaviour

Plugins that are either out of date or up to date aren't correctly identified.
AutoSubtasks for example had an update but was still listed as ver 0.0.1. I clicked "Install" which installed the updated version. I placed a ticket with @creecos and asked them to change modify the plugin to reflect the new version and it was updated to 0.0.2. The new version is correctly identified in Plugins.json as 0.0.2 and the plugin directory also shows 0.0.2 as the current version now. I can still click "Install" versus the directory showing "Up to date".

Similarly, plugin "Comment Tooltip" is listed as version 0.0.1 installed, and is showing "Up to date" even though the plugin's current version is 1.0.1.

### Expected behaviour

Plugins that have been updated and have correctly identified a new version number in Plugin.php should correctly show "Update now", "Up to date", or "Reinstall"

### Steps to reproduce
Browse to Plugin Directory, compare software versions

### Configuration

Application version: 1.2.3
PHP version: 7.0.30-0ubuntu0.16.04.1
PHP SAPI: apache2handler
OS version: Linux 4.4.0-116-generic
Database driver: mysql
Database version: 5.7.22-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

**Comment by lastlink** [comment]
My experience with these so far is that the plugin creator didn't properly update their compatible version. Usually using a >= will solve updates in software.

**Comment by MDKAOD** [comment]
I've tried that, but I'm not sure that would have the desired effect on my local version. What I can say is the implementation of getPluginVersion() function in third party plugins is the same (as far as I can tell) to official @fguillot 's plugins.

![image](https://user-images.githubusercontent.com/1223587/40242591-0667432e-5a8c-11e8-8057-fc1dca875d30.png)
![image](https://user-images.githubusercontent.com/1223587/40242611-13be96bc-5a8c-11e8-9039-2c2b9e89cc2d.png)

**Comment by lastlink** [comment]
`getPluginVersion` shouldn't have the >=, but the `getCompatibleVersion`

`getPluginVersion` needs to match the version on https://github.com/kanboard/website/blob/master/plugins.json otherwise it will keep ask to update.

**Comment by lastlink** [comment]
Could you provide screenshots of your install plugins & install plugins page?

**Comment by lastlink** [comment]
My getCompatibleVersion is this.
```
  public function getCompatibleVersion()
    {
        return '>=1.0.37';
    }
```

**Comment by MDKAOD** [comment]
![image](https://user-images.githubusercontent.com/1223587/40245314-4d0885ca-5a93-11e8-98a7-3a79555971c4.png)
![image](https://user-images.githubusercontent.com/1223587/40245342-5e95def0-5a93-11e8-8c87-b19b592e1723.png)

**Comment by lastlink** [comment]
It does look to be specifically an issue w/ AutoSubtasks.

**Comment by MDKAOD** [comment]
As I mentioned in my original ticket, "Similarly, plugin "Comment Tooltip" is listed as version 0.0.1 installed, and is showing "Up to date" even though the plugin's current version is 1.0.1."

I haven't investigated further, but I imagine there are others as well.

**Comment by lastlink** [comment]
Both plugins have their own issues, Comment Tooltip doesn't show a link to it's home page on the installed page.

Both of them also don't have the
```
public function getCompatibleVersion()
```
declared in Plugin.php
As for documentation, I remember it stating to just **look at the examples.** People are welcome to submit documentation updates.

**Comment by MDKAOD** [comment]
Thank you, I'll submit a bug fix and see how we do.

**Comment by MDKAOD** [comment]
Plugin was updated as suggested #https://github.com/creecros/AutoSubtasks/issues/12 and the behavior remains.

**Comment by creecros** [comment]
solved:
`title` in plugins.json has to match `name` in Plugins.php

**Comment by creecros** [comment]
as for Comment Tooltip, it will shoe "Update" vs "Up to date" because plugins.json `version` for it is 0.0.1, but it downloads and installs 1.0.1, so plugin.json needs to be updated.

**Comment by MDKAOD** [comment]
Thank you for your efforts!

**Comment by creecros** [comment]
kanboard/website#39
