### ISSUE TITLE
API adjustments to support offline clients

### ISSUE THREAD

**Issue by dvor** [kanboard/kanboard#3874]
*Sorry for the huge ticket, if you like I can break it into two.*

I'm working on the [iOS and macOS clients](https://github.com/dvor/SwiftyKanboard) for the Kanboard. Main feature I would like to implement is offline mode. In offline mode it should be possible to use all Kanboard functionality without internet connection and sync any changes to the server later.

However there are few API features missing that are required to have nice user experience:

## Lightweight status updates

I would like to ping server from time to time to check if there are any new updates for active project. It would be nice to make these updates as lightweight as possible. Saving bandwidth is critical for the mobile app, but it would be nice to improve bandwidth on desktop as well.

There is already an existing method `getProjectActivity`, however there are few issues with it:

- It is heavy. It always returns last 50 activities, despite the fact that these activities could be already processed by the app.
- Number of activities is limited to 50. This method becomes useless when there were more than 50 updates - there is no other way to know what updates happened on server except for fetching whole project with columns and all tasks (both opened and closed).

As a solution I propose to add a new request `getProjectUpdates`. Parameters for this request will be `project_id` and `updates_from` timestamp:

```
{
    "jsonrpc": "2.0",
    "method": "getProjectUpdates",
    "id": 942472945,
    "params": {
        "project_id": 1,
        "updates_from": "1436119135"
    }
}
```

Server will return ids of all objects that were modified from given date + date of last modification. This date can be used for the next `getProjectUpdates` request:

```
{
    "jsonrpc": "2.0",
    "id": 942472945,
    "result": {
        "last_modified": 1436119888",
        "project_id": 1,
        "column_ids": [1, 4],
        "task_ids": [37, 45, 54]
    }
}
```

In case there are no updates date passed in "updated_from" will be returned:

```
{
    "jsonrpc": "2.0",
    "id": 942472945,
    "result": {
        "last_modified": 1436119135"
    }
}
```

Alternative option for this request would be to return all modified objects instead of their ids. This will save one additional call to the server that app will make anyway:

```
# Alternative response
{
    "jsonrpc": "2.0",
    "id": 942472945,
    "result": {
        "last_modified": 1436119888",
        "project": { "id": "1", "name": "API test", ... }
        "columns": [
            { "id": "2", "title": "Ready", ...},
            { "id": "4", "title": "Done", ...}
        ],
        "tasks": [
            { "id": "37", "title": "Task #37", ...},
            { "id": "45", "title": "Some other task", ...},
        ],
    }
}
```

With this method it will be very convenient to get all board updates. In case of no updates response will be really small, making it easy to ping server from time to time even for mobile user.

## Task removal isn't tracked

Other issue I found is that there is no way to track task removal. No new activity event is being added when removing task. When removing last created task it's task_id even will be reused for the next task

For example, here is a list of actions I did in Kanboard:

- create task 386  <-- X
- create task 387
- remove task 386  <-- X
- create task 388  <-- X
- remote task 388  <-- X
- create task 388 (again!)

And here is an activity log:

- dvor created the task 387
- dvor created the task 388

Information about events marked with X is lost. For 388 even creation activity event was removed! Maybe there was a reason to implement it that way?

While it might be okay to lose information in case of 388, in case of 386 I would like to know that the removal was done. To accomplish that I propose to do the following:

- When removing task add an removal activity event. It would be nice to have a log of destructive operations.
- Add task removal information to the `getProjectUpdates` request that was proposed before. Some special status can be returned for the removed task, for example `"{ "id": "1", "status": "removed}` (or something similar).

I haven't checked removal activities for columns/projects, but I guess same can be done there.

----

What do you think about these features, would it be possible to add them? I'm open to other proposals and ideas that will help to solve API issues for offline app.

**Comment by lastlink** [comment]
How far along is your mobile app coming @dvor? Are you close to distribution? I created an issue for user testing distribution. You could compare it with taigios kanboard mobile app that is open sourced.

**Comment by dvor** [comment]
@lastlink thanks for you interest. I've started this project recently and I'm not sure yet when it will be ready. Hopefully some MVP with basic set of features will be implemented in a month or so.

If you have any other questions - please open new issue in [my repository](https://github.com/dvor/SwiftyKanboard/issues). Let's keep this ticket for questions about Kanboard API changes.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
