### ISSUE TITLE
[Feature Request] Activity Stream: Log Tag Changes

### ISSUE THREAD

**Issue by regenduft** [kanboard/kanboard#3876]
It would be nice to get Tag changes included into the activity stream of a task, like category changes are already.

Example:

We use tags as a marker for actions to be done for each task, like "Document!" or "Review!" or "Test!"

This is better than only columns because it can be done in whatever order.

New issues have all 3 tags, and when done, the tag is removed. So we can see if everything has been done, but it would be nice to have a log, when the tag was removed and by who, to see if, who and when the specific action item had been done.

(Yes - subtask would be the intended way to do this but the tags are visible in the board overview so we prefer them.)

This could be achieved by either including tag changes into the activity stream, or by implementing a automatic action based on tag remove (add comment ... doing the action).

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
