### ISSUE TITLE
Database migration 129 : 1170 BLOB/TEXT column 'name' used in key specification without a key length

### ISSUE THREAD

**Issue by anleg** [kanboard/kanboard#3880]
### Actual behaviour

I've upgraded kanboard from version 1.2.2 to 1.2.3. The database migration 129 failed.

### Expected behaviour

Successful kanboard update

### Logs
Unable to run SQL migrations: Running migration \Schema\version_129, SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'name' used in key specification without a key length (You may have to fix it manually)

# How i fix it
The specific database update that fail is 
```
$pdo->exec('ALTER TABLE `projects` MODIFY `name` TEXT NOT NULL');
```
from migrate n°129.

In fact, my projects tables had two UNIQUE KEY (name_3, name_4)
```
show create table projects;
| projects | CREATE TABLE `projects` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `is_active` tinyint(4) DEFAULT '1',
  `token` varchar(255) DEFAULT NULL,
  `last_modified` bigint(20) DEFAULT NULL,
  `is_public` tinyint(1) DEFAULT '0',
  `is_private` tinyint(1) DEFAULT '0',
  `description` text,
  `identifier` varchar(50) DEFAULT '',
  `start_date` varchar(10) DEFAULT '',
  `end_date` varchar(10) DEFAULT '',
  `owner_id` int(11) DEFAULT '0',
  `priority_default` int(11) DEFAULT '0',
  `priority_start` int(11) DEFAULT '0',
  `priority_end` int(11) DEFAULT '3',
  `email` varchar(255) DEFAULT NULL,
  `predefined_email_subjects` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_3` (`name`),
  UNIQUE KEY `name_4` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8 |
```

I found the database migration n°94 with two drop index (name, name_2)
```
function version_94(PDO $pdo)
{
    $pdo->exec('ALTER TABLE `projects` DROP INDEX `name`');
    $pdo->exec('ALTER TABLE `projects` DROP INDEX `name_2`');
}
```
Furthermore, I didn't found other INDEX created for projects table. My first thought was that the indexes name were wrong. So, i dropped the UNIQUE KEY name_3 and name_4 in test environment, the kanboard upgrade finally works. My production environment has the same indexes names.

Am I the only one to have this issue ?

### Configuration

- Kanboard version: From 1.2.2 To 1.2.3
- Database type and version: Percona Server 5.7
- PHP version: 5.6
- OS: Debian 8
- Browser: chromimum / Firefox

**Comment by fguillot** [comment]
These indexes where not named explicitly/properly the first time. MySQL generated a name automatically. I have different index names on my side.

The migration 94 should have generated an error. MySQL didn't complains about removing inexistent indexes.

The SQL migrations system is not really bullet-proof.

**Comment by amca01** [comment]
I have the same problem: in my case trying to migrate from 1.0.44 to 1.2.5.  According to 

   app/Schema/Migration.php

I should (in MySQL) enter

   repair tables projects;
   optimize table projects;

but this gives me an error that 

    The storage engine for the table doesn't support repair

I have set `mysql` as the database driver in my `config.php` file... beyond that I'm a bit stuck!

**Comment by bugwatcher** [comment]
Please, use the forum for questions or installation issues: https://kanboard.discourse.group/
