### ISSUE TITLE
Defineable Default text for new Tasks

### ISSUE THREAD

**Issue by wulfithewulf** [kanboard/kanboard#3883]
Hello,

I would appreciate it when you could implement the following:

When I open a new task, I will always have to fill in some basic information into the description field, that always are of same format. In my current workflow I first paste a template text into the field. It would fasten my workflow a lot, if I could define a default text in my project settings. So when I open a new task, the description field is prefilled with the defined text.  

In advance  a full template management would be even greater, so that I can choose between some template texts, for the description field on creating a new task.

I hope I described my Ideas well. 
Thank you for yor great work.

**Comment by Kolossi** [comment]
Have you tried

Board -> Menu -> Settings ->Predefined contents

Seems to do all you ask? - once you've set some, they are choose-able under the new task description.

**Comment by fguillot** [comment]
Not at the moment but feel free to send a pull-request :)
