### ISSUE TITLE
Ability to Filter on Bigboard View, by User

### ISSUE THREAD

**Issue by ElieNassif89** [kanboard/kanboard#3888]
Hello Kanboard Team,

Great job on the Bigboard extension. Just finished installing it and looks really good, however I would like to know if there is the possibility to filter that bigboard by User.

It would be very beneficial and efficient to have that view.
As you can see on the png I attached the selected filter would result only in showing the Tasks assigned to "EN" , Elie Nassif
Any comments, or is that functionality available and I have missed it.
Much Appreciate it

![bigboard](https://user-images.githubusercontent.com/39047916/40722681-3d7a75ee-641d-11e8-8ae9-b1413364bb99.PNG)

**Comment by fguillot** [comment]
This is the wrong bug tracker, the plugin bigboard is there: https://github.com/stinnux/kanboard-bigboard/issues
