### ISSUE TITLE
Line feed / newline are lost on some views

### ISSUE THREAD

**Issue by TheFax** [kanboard/kanboard#3891]
If you add a note containing line feeds / newline on a task, these are not well managed across the different views. 
See "Line 1", "Line 2" and "Line 3" on screenshots.
**Adding a note, with 3 lines:**
![correct](https://user-images.githubusercontent.com/19174767/40802349-a1e67dae-6515-11e8-90ee-3c3e53646de5.JPG)

**Wrong views: newlines are lost:**
![wrong 1](https://user-images.githubusercontent.com/19174767/40802624-6901dee2-6516-11e8-8e5a-9348a60acde6.JPG)
![wrong 2](https://user-images.githubusercontent.com/19174767/40802625-692e4702-6516-11e8-9043-b58e8832cd95.JPG)

### Configuration
    Versione dell'applicazione: 1.2.4
    Versione PHP: 5.6.34
    PHP SAPI: cgi-fcgi
    Versione OS: Windows 10
    Driver per Database sqlite
    Versione database: 3.8.10.2
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by froschdesign** [comment]
@TheFax 
Kanboard uses Markdown and for a line break you need two spaces or more at the end of a line.

Reference:

* https://daringfireball.net/projects/markdown/syntax#p
* https://en.wikipedia.org/wiki/Markdown#Example

**Comment by fguillot** [comment]
As mentioned above, this is not a bug. This is the way the Markdown syntax is defined.
