### ISSUE TITLE
Clarifying question on Automatic Actions behavior

### ISSUE THREAD

**Issue by MDKAOD** [kanboard/kanboard#3899]
This issue is:

- [ ] Bug report
- [ ] Feature request
- [x] Improvement
- [X] Question

- Please, read the [Frequently Asked Questions](https://docs.kanboard.org/en/latest/developer_guide/faq.html).
- Ask questions on the [Forum](https://github.com/kanboard/forum/issues).

### Actual behaviour
I have an automatic action to
![image](https://user-images.githubusercontent.com/1223587/40934781-ead45cd4-6803-11e8-81a6-4c4bf19c785a.png)

then later, another action to
![image](https://user-images.githubusercontent.com/1223587/40934825-0e08c2a8-6804-11e8-8aec-d8e3336ae239.png)

which results in: 

![image](https://user-images.githubusercontent.com/1223587/40934886-414d767c-6804-11e8-8168-378c2072fc82.png)

### **Desired** behaviour

What I'm curious about is whether the automatic action rules are processed in a linear manner, (i.e. Rule 1, then Rule 2, then rule 3)? Can I then avoid a flood of email by putting AutoSubtask rule before the email rule? If so, then can I Feature Request the ability to move the rules around similar to arranging Subtasks, columns, and swimlanes? 

### Steps to reproduce

Create a rule to send email to an assignee, then create a rule to automatically add subtasks, then create a new task that adds subtasks automatically, then delete all of the extra emails.

### Configuration

Application version: 1.2.3
PHP version: 7.0.30-0ubuntu0.16.04.1
PHP SAPI: apache2handler
OS version: Linux 4.4.0-127-generic
Database driver: mysql
Database version: 5.7.22-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by creecros** [comment]
Your "Which result in:" screenshot, those are not emails generated by the automatic action, but by the notifications system. I'd just turn the email portion of notifications off, that could get annoying, send those to rocket chat or something.

**Comment by creecros** [comment]
Check your notification settings at the user level, go to your user settings page

**Comment by creecros** [comment]
The clarifying answer to your question is, notifications and automatic actions are 2 separate things and your issue is not with the automatic actions, but with notifications. 

Anything that happens in a task, will trigger a notification, and if it is set to send by email, that's gonna make a lot of emails. I use rocket chat for those, keeps my inbox clear and delivers real time info in real time to a system that isn't my inbox. This is a user level setting, so it is set at each users end, as an admin, you would have to set each user up with "send by email" turned off, or let each of your users set it themselves.

**Comment by MDKAOD** [comment]
I've had a chance to circle back to this and I see what you're saying. I guess what I'm looking for is a more flexible option. I have users who are already having a hard time grasping this technology, to add another layer of "complexity" in the form of realtime chat isn't...desirable... to say the least lol

**Comment by creecros** [comment]
Then just use "Web"
