### ISSUE TITLE
Attachments are not visibile in public access

### ISSUE THREAD

**Issue by Bluewind** [kanboard/kanboard#390]
If you create a board (with public access enabled), create a task and then add an attachment to the task I would expect the attachment to show up when the task is viewed via the public link, but that doesn't seem to be the case.

**Comment by lazki** [comment]
:+1:

**Comment by DoumeDuSud** [comment]
:+1:

**Comment by golharam** [comment]
+1

**Comment by kwijk** [comment]
+1

**Comment by joeleaver** [comment]
+1

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
