### ISSUE TITLE
Removing swim lanes

### ISSUE THREAD

**Issue by cwolter** [kanboard/kanboard#3901]
This issue is:

- [ ] Bug report
- [ ] Feature request
- [X ] Improvement

- Please, read the [Frequently Asked Questions](https://docs.kanboard.org/en/latest/developer_guide/faq.html).
- Ask questions on the [Forum](https://github.com/kanboard/forum/issues).

### Actual behaviour
I see in #439 it was removed to delete swimlane as long as there are items in it. 
But it also seems this is the case even if all items are solved. 
Is this intended ? 
This means I can not delete the swimlane at all if I actually used it before right?

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by MDKAOD** [comment]
Have you checked that there are no closed tasks still living in the swimlane?

Use the filters and choose type "status:all" just to make sure that there is nothing in the swimlane hidden.

![image](https://user-images.githubusercontent.com/1223587/41042876-b8b4fad8-6970-11e8-94dc-d950bb0ec79e.png)

**Comment by fguillot** [comment]
If you want to remove a swimlane, you have to remove all tasks that belongs to this swimlane regardless of their status.
