### ISSUE TITLE
Logo for the project

### ISSUE THREAD

**Issue by ucodi** [kanboard/kanboard#3909]
I designed a logo and a styleguide for your project.

what do you think about it ?

![logo-text-bottom](https://user-images.githubusercontent.com/40141083/41202259-db1c76a8-6cb5-11e8-8cdc-cf6c3d560b3b.png)
![logo-text-inline](https://user-images.githubusercontent.com/40141083/41202260-db389144-6cb5-11e8-9fa6-fbb5938da489.png)
![styleguide](https://user-images.githubusercontent.com/40141083/41202261-db51a832-6cb5-11e8-8361-42004cbd1dc7.png)

**Comment by dvor** [comment]
@ucodi I'm working on the [iOS & macOS](https://github.com/dvor/SwiftyKanboard) app. Can I use your logo and icons as well? Can you please email them to d@dvor.me? Thanks!

**Comment by ucodi** [comment]
@dvor I will send you the assets this week-end :wink:

**Comment by ucodi** [comment]
@dvor here are the logo
[kanboard-logos.zip](https://github.com/kanboard/kanboard/files/2109205/kanboard-logos.zip)

icons  can be found here https://feathericons.com/

**Comment by dvor** [comment]
Cool, thanks!

**Comment by X3msnake** [comment]
@ucodi nice logo Master

**Comment by dvor** [comment]
Looks good on iOS:

![simulator screen shot - iphone 8 plus - 2018-06-24 at 23 05 19](https://user-images.githubusercontent.com/1132979/41823626-3754ff14-7803-11e8-9049-89a584fb159b.png)

**Comment by ucodi** [comment]
I'm not using iOS, but I see they didn't use shadow, do you prefer the same icon less shadow ?


![ios-kanboard](https://user-images.githubusercontent.com/40141083/41869607-0f82e2c0-78a9-11e8-9e53-0007139b21ed.png)

**Comment by dvor** [comment]
Yes, I think icon without shadow will fit more. Can you send it to me as well?

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
