### ISSUE TITLE
Filter Override

### ISSUE THREAD

**Issue by creecros** [kanboard/kanboard#3911]
@fguillot Is there a way to override a filter? For example:

Plugin A - Overrides TaskAssigneeFilter
Plugin B - `use Kanboard\Filter\TaskAssigneeFilter;`

Result: Plugin B uses the New TaskAssigneeFilter from Plugin A

Possible?

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
