### ISSUE TITLE
Notification Pick list in Public Projects limited

### ISSUE THREAD

**Issue by nztebs** [kanboard/kanboard#3913]
This issue is:

- [ X] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour
In a board where permissions are set to "Allow everybody to access to this project", dropdown lists for notifications (ie Send Comment by email, or use an @ inline in a comment or task description) are restricted to any named users that were added before marking the project as open to all.

### Expected behaviour
That ALL Kanboard users would be available in the notifications and @ context menus for Open Projects.  (This is the case for the "assignee" field, but not for notifications).

NB: I work around this by changing the project to NOT being open to everybody, add the names of all the users, save, then go back and mark it as open to everybody again.  

### Configuration

- Kanboard version: 1.0.48
- Database type and version: mysql, 5.5.56-MariaDB
- PHP version:  5.6.32
- OS: Linux 3.10.0-693.11.1.el7.x86_64
- Browser: Chrome

**Comment by loonies** [comment]
Did you try with the latest Kanboard version (1.2.5)?

**Comment by fguillot** [comment]
"Allow everybody to access to this project" doesn't exists anymore, this issue is not applicable with latest version.
