### ISSUE TITLE
Style of specific tags no longer working 

### ISSUE THREAD

**Issue by faspina** [kanboard/kanboard#3914]
I have style setup to color tags based on the tag name and after the 1.2.5 upgrade they are no longer working 

[class*="tag-Garden"] {
    background-color: rgb(92, 184, 92);
    border: none!important;
    box-shadow: 0 1px 1px rgba(186, 186, 186, 0.55);
    color: #392727;
}

This would color a tag name Garden

**Comment by fguillot** [comment]
Tags and categories now supports color without having to define a custom style. Give it a try.
