### ISSUE TITLE
JsonRPC createLdapUser not working - user role NULL not allowed.

### ISSUE THREAD

**Issue by ErrorFlexXx** [kanboard/kanboard#3921]
### Actual behaviour

If one want to register a user with an ldap username via the jsonrpc connector, the request fails and returns  'false', because of an unset role for the user registration. See the debug log below.

### Expected behaviour
The user should be registered with role `Role::APP_USER`
I guess, the role is empty because it is queried out of a user session -- There seems to be a difference, if one do a first login via the website and gets created via ldap or the registration comes from jsonrpc.

### Steps to reproduce
Setup kanboard with ldap connection in proxy mode and mysql database and fire a request to create an ldap user e.g.

```bash
curl  -u "jsonrpc:<fillInAKeyHere>" -d '{"jsonrpc": "2.0", "method": "createLdapUser", "id": <someId>, "params": { "username": "<aUserName>"}}' http://<kanboardURL>/jsonrpc.php
```

### Logs
```
[2018-06-19 15:51:21] [debug] SQL: INSERT INTO `users` (`username`, `name`, `email`, `role`, `is_ldap_user`) VALUES (:username, :name, :email, :role, :is_ldap_user)
[2018-06-19 15:51:21] [debug] SQL: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'role' cannot be null
```

### Configuration

- Kanboard version: 1.2.5
- Database type and version: MySQL 5.7.22-0ubuntu18.04.1
- PHP version: PHP 7.2.5-0ubuntu0.18.04.1 (cli) (built: May  9 2018 17:21:02)
- OS: Ubuntu 18.04
- Browser: none

### Dirty quick fix
With the following workaround the ldap user creation via jsonRPC works as expected. However, I guess there is a more correct way to fix this. That's the reason, why I didn't create a pull request with that fix.

File: kanboard/app/Api/Procedure/UserProcedure.php
```php
public function createLdapUser($username)
    {
       [...]
            $user = LdapUser::getUser($ldap, $username);

            if ($user === null) {
                $this->logger->info('User not found in LDAP server');
                return false;
            }

            if ($user->getUsername() === '') {
                throw new LogicException('Username not found in LDAP profile, check the parameter LDAP_USER_ATTRIBUTE_USERNAME');
            }

            $values = array(
                'username' => $user->getUsername(),
                'name' => $user->getName(),
                'email' => $user->getEmail(),
                'role' => $user->getRole(),
                'is_ldap_user' => 1,
            );

    +++        if($values['role'] == null)
    +++            $values['role'] = Role::APP_USER;

            return $this->userModel->create($values);
            [...]
```

**Comment by luanphan1996** [comment]
what do you using package???

**Comment by ErrorFlexXx** [comment]
I'm sorry, I don't get your question exactly. But json rpc is a kanboard core functionally and I'm using the official v 1.2.5 tar.gz release.

**Comment by ErrorFlexXx** [comment]
The jsonrpc connector itself is working. It's just the kanboard User Procedure thing, which doesn't setup the data structure properly to register a new user in the database. So if a jsonrpc request comes in, the database insertion fails.

**Comment by luanphan1996** [comment]
i'm run: composer require fguillot/json-rpc @stable   
errors:
Problem 1
    - The requested package fguillot/json-rpc could not be found in any version, there may be a typo in the package name.

why it's error??

**Comment by ErrorFlexXx** [comment]
Please discuss this in your issue, because you are dealing with another type of issue and your are using another software.

Note: The package you're using is marked [deprecated].
Additionally your opened issue #3990 doesn't follow the suggested template and is missing nearly all required informations, that would enable someone to help you.

**Comment by luanphan1996** [comment]
oke thank

**Comment by fguillot** [comment]
@ErrorFlexXx Looks like you need to configure LDAP groups, otherwise the role is null: https://github.com/kanboard/kanboard/blob/master/app/Core/Ldap/User.php#L119-L121
