### ISSUE TITLE
want a Custom Project Roles-move only assigned tasks is permitted 

### ISSUE THREAD

**Issue by kshke** [kanboard/kanboard#3936]
I see there is a default role that Update only assigned tasks is permitted .I set it for my project,  user can't edit other's task but they can move other people's task in board.
Can I let use just be able to move own task?

**Comment by Victor-IT** [comment]
#3930

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
