### ISSUE TITLE
Creating a subtask when writing a comment

### ISSUE THREAD

**Issue by emmanuelCNRS** [kanboard/kanboard#3943]
When writing a comment in a task during team tasks review, I frequently write a decision in the comment and then create a subtask to have a clear idea of what have to be done.

So it's a kind of double work.

To go in the sence of the automation, would it be possible to add a functionnality for creating a subtask from a comment ? 

For exemple, by adding some specific charactaires on each side of some words written in a comment : 

> I have to **[nst]** update the specification document **[/nst]** in next days.

In this exemple, [nst] means "New Sub Task beginning", and [/nst] means "New Sub Task ending".

When clicking on the SAVE button for adding the comment, the subtask "update the specification document" is automatically created and added after the existing ones. This new subtask could be not assigned in a first time.

**Comment by bugwatcher** [comment]
Sorry, no plan to implement this feature. If you really need this, send a pull-request or create a plugin.
