### ISSUE TITLE
Renumbering tasks? 

### ISSUE THREAD

**Issue by amca01** [kanboard/kanboard#3949]
Hello,

I'm just starting to use kanboard again after a time away from it; I've deleted all the old tasks and started afresh.  But this means that my new tasks are still numbered as from the old tasks - so how can I delete all the old tasks from the system completely so that my new tasks are numbered from 1?  Do I somehow need to wipe the database?

Thanks!

**Comment by bugwatcher** [comment]
This is an invalid bug report. See https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#how-to-make-a-bug-report

Use the forum to ask questions: https://github.com/kanboard/forum/issues
