### ISSUE TITLE
Automatic Aciont - Move task

### ISSUE THREAD

**Issue by leandroralmeida** [kanboard/kanboard#3951]
I create a automatic actions, like this in User´s Guide:
> When a task is moved to the last column, move the exact same task to another project
> Let’s say we have two projects: “Ideas” and “Development”. Once the idea is validated, swap it to the “Development” project.
> Choose action: Move the task to another project
> Choose the event: Move a task to another column
> Define action parameters: Column = Validated and Project = Developmen

But, I can´t choose the column destination  of the another project.
The task just move to last column of the other project.

### Screenshots
![image](https://user-images.githubusercontent.com/41297423/42765620-ced6f2ec-88ee-11e8-8ee1-765ef06d7b3a.png)

### Configuration

- Kanboard version:1.2.5
- Database type and version: sqlite 3.8.10.2
- PHP version: 5.6.30
- OS: Linux 3.10.0-693.17.1.2.ELK.el6.x86_64
- Browser: Chrome

**Comment by cmideal** [comment]
I think now ,you can reedit the source CODE to solve this .

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.13/developer_guide/faq.html).
