### ISSUE TITLE
want to add a register(log in) module by a email-address

### ISSUE THREAD

**Issue by Albert-cord** [kanboard/kanboard#3958]
include the above what I describe, for example, in the ### **login page**, I can use a _**email-address**_ instead of _**user name**_, please any good person give me **_some suggestions_**.

**Comment by bugwatcher** [comment]
This is an invalid bug report. See https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#how-to-make-a-bug-report

Use the forum to ask questions: https://github.com/kanboard/forum/issues
