### ISSUE TITLE
JS Issue : anonymous create a 403 error

### ISSUE THREAD

**Issue by gcharrier** [kanboard/kanboard#3960]
Hi everybody, i upgraded my Kanboard to version 1.2.5 and have some weird issue.

### Actual behaviour
When dragging a task to another column there is error in the JS control, here's the following ::

vendor.min.js?1529095995:2 POST http://www.oxygen-lab.com/kanboard/?controller=BoardAjaxController&action=save&project_id=1 403 (Forbidden)
send @ vendor.min.js?1529095995:2
ajax @ vendor.min.js?1529095995:2
Kanboard.BoardDragAndDrop.save @ app.min.js?1529095995:2
stop @ app.min.js?1529095995:2
_trigger @ vendor.min.js?1529095995:9
_trigger @ vendor.min.js?1529095995:16
(anonymous) @ vendor.min.js?1529095995:9
_clear @ vendor.min.js?1529095995:16
(anonymous) @ vendor.min.js?1529095995:9
_mouseStop @ vendor.min.js?1529095995:15
(anonymous) @ vendor.min.js?1529095995:9
_mouseUp @ vendor.min.js?1529095995:12
(anonymous) @ vendor.min.js?1529095995:9
n._mouseCapture._mouseDistanceMet._mouseDelayMet._mouseUpDelegate @ vendor.min.js?1529095995:12
dispatch @ vendor.min.js?1529095995:2
y.handle @ vendor.min.js?1529095995:2
app.min.js?1529095995:2 Uncaught TypeError: Cannot read property 'message' of undefined
    at Object.403 (app.min.js?1529095995:2)
    at u (vendor.min.js?1529095995:2)
    at Object.add [as fail] (vendor.min.js?1529095995:2)
    at Object.always (vendor.min.js?1529095995:2)
    at Object.statusCode (vendor.min.js?1529095995:2)
    at k (vendor.min.js?1529095995:2)
    at XMLHttpRequest.<anonymous> (vendor.min.js?1529095995:2)

Seems that there is a anonymous user in the stack execution. May be some of you had the same problem ? I attached a debug, where i didnt find anything "clear" for me. Thanks for your help.

Note that i dont have the problem to edit, modify and save a task. But if i edit the task and i use the "change position" function i have the same problem. 

### log here
[debug.log](https://github.com/kanboard/kanboard/files/2237984/debug.log)

### Configuration

- Kanboard version: 1.2.5
- Database type and version: SQlite
- PHP version:5.6
- OS:Linux/Apache
- Browser:CHrome

**Comment by alejandromorrison** [comment]
Hello @gcharrier are you running the project where? The error 403 is mostly giving in any occasion when you are having a lack of permission on the server to this project, could be folders or could be files permissions.

If you let me know in what OS, or where the server are you running to I could give you a hand.

Thanks you,
<h1>Nelson Morrison</h1>

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.7/developer_guide/faq.html).
