### ISSUE TITLE
Thumbnail size params

### ISSUE THREAD

**Issue by stefanKBL** [kanboard/kanboard#3961]
Hi,
would be nice if thumbnail size could be a parameter in config. As it seems that fixed size is 250px width (from generateThumbnailFromFile function in FileModel, possibly pass config.width as first parameter. I did hard coded modification in my instance and it's ok)
Why ? I use CoverImage for displaying img into cards, I also did some CSS modifications via CSS plugin and columns are max 320px, but could be larger for others users.
Thanks

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
