### ISSUE TITLE
Drag & Drop of attachment'sarea in open task

### ISSUE THREAD

**Issue by TheCloud** [kanboard/kanboard#3962]
I'm found in the need to attach files to tasks very often and not being able to drop a file directly into the file list.

Currently, when a task is open:
1) the "attachment" area is available only if an attachment has been already attached
2) there is no "active" drag and drop area in the open task, but you need to click on the vertical menu
<img width="724" alt="attach" src="https://user-images.githubusercontent.com/129162/43359227-4d589fe4-929f-11e8-90a6-809b6cb46db4.PNG">

Thank you for sharing your thoughts :-)
Julien

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
