### ISSUE TITLE
Fatal error on rendering comments with square brackets

### ISSUE THREAD

**Issue by d4rk5eed** [kanboard/kanboard#3964]
### Actual behaviour
Iterpretator crashes with fatal error on rendering task.
 

### Expected behaviour
Iterpretator renders requested task with comments.

### Steps to reproduce
1. Create new task
2. Add comment with square brackets (actually it should be sufficient one open bracket)

### Logs
```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 122683392 bytes) in /home/yz/Workspace/kanboard/app/Core/Markdown.php on line 158
[Mon Jul 30 16:25:07 2018] 127.0.0.1:39336 [200]: /?controller=TaskViewController&action=show&task_id=2&project_id=1 - Allowed memory size of 134217728 bytes exhausted (tried to allocate 122683392 bytes) in /home/yz/Workspace/kanboard/app/Core/Markdown.php on line 158
```

### Configuration

- Kanboard version: commit: efd64d84
- Database type and version: sqlite
- PHP version: 5.6.37
- OS:Linux calculate 4.14.39-calculate #1 SMP PREEMPT Fri May 4 09:24:36 UTC 2018 x86_64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz GenuineIntel GNU/Linux
- Browser: Google Chrome | 67.0.3396.99 (official) (64 бит)

**Comment by d4rk5eed** [comment]
```
c44880a5889ebaaec61001dddd6ba4e0b322d623 is the first bad commit
commit c44880a5889ebaaec61001dddd6ba4e0b322d623
Date:   Sat Jul 21 20:32:39 2018 +0300

```

**Comment by bugwatcher** [comment]
Can you check if this commit solve your issue: https://github.com/kanboard/kanboard/commit/1268c0023d7085fb4d960b869bf79ef0ade0d212
