### ISSUE TITLE
createTask api call does not work

### ISSUE THREAD

**Issue by aizaimenghuangu** [kanboard/kanboard#3966]
### Actual behaviour
use JSON-RPC to call createTask API  but  return null

```
$client = new JsonRPC\Client('http://localhost:8093/jsonrpc.php');
        $client->getHttpClient()->withDebug();
        $client->authentication('jsonrpc', '05d663e42d279af8851de6645b6237a5566d022bc995396bda77ee719961');

        $result = $client->createTask($title, 5);
```

```
[Tue Aug  7 16:02:54 2018] ==> Request: 
{"jsonrpc":"2.0","method":"createTask","id":1953840087,"params":["TEST TASK",5]}
[Tue Aug  7 16:02:54 2018] ==> Headers: 
array (
  0 => 'HTTP/1.1 200 OK',
  1 => 'Host: localhost:8093',
  2 => 'Connection: close',
  3 => 'X-Powered-By: PHP/5.6.30',
  4 => 'Content-Type: application/json',
)
[Tue Aug  7 16:02:54 2018] ==> Response: 
{
    "jsonrpc": "2.0",
    "result": null,
    "id": 1953840087
}
```

finally I found 
`$this->hook->reference('model:task:creation:prepare', $values);` return null

then Annotate the following code it works fine but i Don't know why
![image](https://user-images.githubusercontent.com/3993636/43763017-27e175dc-9a5c-11e8-8733-4a61e7530d3a.png)

### Expected behaviour
Annotate the following code I don't know what's going on
`$this->hook->reference('model:task:creation:prepare', $values);` 
### Configuration

应用程序版本： master
PHP 版本： 5.6.30
PHP SAPI： cli-server
系统： Darwin 16.6.0
数据库驱动： mysql
数据库版本： 5.6.24
浏览器： Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36

**Comment by cmideal** [comment]
yes i found this also

**Comment by fguillot** [comment]
This working fine for me. Please, use the forum if you still have issues: https://kanboard.discourse.group/

Here is an example:

```php
<?php

require __DIR__.'/vendor/autoload.php';

$client = new JsonRPC\Client('http://127.0.0.1/jsonrpc.php');
$client->authentication('jsonrpc', '9c086f276da572ef344362d904a234bfce6987c907b3bdf962b59d29781f');

$result = $client->createTask(['title' => 'This is a test', 'project_id' => 1]);

var_dump($result);
```
