### ISSUE TITLE
Moving my old database into docker container?

### ISSUE THREAD

**Issue by amca01** [kanboard/kanboard#3968]
I'm just exploring docker, and I've downloaded and installed the containerised version of kanboard.  It works fine!  But what I want to do is import my old database (which I dumped with `mysqldump`) into this new container.  I know this is a generic question, but as I am new to docker I don't know how to do it.  Can any docker mavens here point me in the right direction?  Thanks!

**Comment by bugwatcher** [comment]
This is an invalid bug report. See https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#how-to-make-a-bug-report

Use the forum to ask questions: https://github.com/kanboard/forum/issues
