### ISSUE TITLE
Copy of multiple tasks or the whole column

### ISSUE THREAD

**Issue by hansapils** [kanboard/kanboard#3975]
Hi board, hi Frédéric, 

first of all: thank you for this great Software. In the last two days I started from the nextcloud kanban and tried almost any other standalone kanban tools. In my opinion kanboard is the best and can  compete with commercial solutions.

For the management of my projects I need software, that I can host by myself. I have sensitive data and using SaaS would also mean, that I would become dependent.

I am dividing my projects in differenct columns, each column is for another customer. In this way I have a great overview. Since the projects are all the same (in the beginning), it would be great, if I could just copy one column to another. Another way would be to copy multiple tasks.

It would be great help, if you could realize this. 

Regards!
hansapils

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
