### ISSUE TITLE
Add support for (Universal 2nd Factor) U2F

### ISSUE THREAD

**Issue by baldurmen** [kanboard/kanboard#3976]
At the moment, Kanboard supports TOTP as a second factor authentication method. This is very nice, as 2FA is an important security measure, especially for admin accounts.

It would be nice if U2F support was also added, since these devices are becoming more and more frequent and provide a better user experience than TOTP.

Yubico (who works on the FIDO U2F standard) has a PHP library that could be used to implement U2F in Kanboard:

https://github.com/Yubico/php-u2flib-server

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
