### ISSUE TITLE
"Invalid DN syntax" error with openldap

### ISSUE THREAD

**Issue by gbwebdev** [kanboard/kanboard#3978]
This issue is:

- [X] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour

When trying to log in using LDAP, the ui shows an "invalid username or password" error, and the logs show an "Error="Invalid DN syntax"; ExtendedError="invalid DN"" error.

### Expected behaviour
A successful login.
Or at least a more precise error log.

### Steps to reproduce
-

### Logs
Kanboard Logs :
```

Kanboard\Core\Controller\Runner::executeMiddleware
Subscriber executed: Kanboard\Subscriber\BootstrapSubscriber::execute
Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\AuthenticationMiddleware
Kanboard\Core\Controller\Runner::executeController => \Kanboard\Controller\AuthController::check
LDAP authentication failure for "admin" => Code="34"; Error="Invalid DN syntax"; ExtendedError="invalid DN"
Subscriber executed: Kanboard\Subscriber\AuthSubscriber::onLoginFailure
```

### Configuration

- Kanboard version: 1.2.5
- Database type and version: MySQL (MariaDB) 10.1.34
- PHP version: 7.2 (fpm)
- OS: Ubuntu Server 18.04
- Browser: Google Chrome

**LDAP configuration :**
```
define('LDAP_AUTH', true);
define('LDAP_SERVER', '192.168.1.1');
define('LDAP_PORT', 389);
define('LDAP_SSL_VERIFY',false);
define('LDAP_START_TLS', false);
define('LDAP_USERNAME_CASE_SENSITIVE', false);
define('LDAP_BIND_TYPE', 'proxy');
define('LDAP_USERNAME', 'admin');
define('LDAP_PASSWORD', 'admin');
define('LDAP_USER_BASE_DN', 'cn=users,dc=192,dc=168,dc=1,dc=1');
define('LDAP_USER_FILTER', '(&(objectclass=*)(|(cn=%uid)))');
define('LDAP_USER_ATTRIBUTE_USERNAME', 'uid');
define('LDAP_USER_ATTRIBUTE_FULLNAME', 'uid');
define('LDAP_USER_ATTRIBUTE_EMAIL', 'mail');
define('LDAP_USER_ATTRIBUTE_GROUPS', 'memberof');
define('LDAP_USER_ATTRIBUTE_PHOTO', '');
define('LDAP_USER_ATTRIBUTE_LANGUAGE', '');
define('LDAP_USER_CREATION', false);
define('LDAP_GROUP_ADMIN_DN', 'cn=permanents,cn=groups,dc=192,dc=168,dc=1,dc=1');
define('LDAP_GROUP_MANAGER_DN', 'cn=permanents,cn=groups,dc=192,dc=168,dc=1,dc=1');
define('LDAP_GROUP_PROVIDER', false);
define('LDAP_GROUP_BASE_DN', '');
define('LDAP_GROUP_FILTER', '');
define('LDAP_GROUP_USER_FILTER', '');
define('LDAP_GROUP_ATTRIBUTE_NAME', 'cn');
```

**Important note :**
On the same server, using the same PHP, I have a "DokuWiki", "MantisBT" and "OwnCloud" all using LDAP successfully.

Thanks for all the great work BTW !

**Comment by stinnux** [comment]
instead of 
```define('LDAP_USER_FILTER', '(&(objectclass=*)(|(cn=%uid)))');```
try
```define('LDAP_USER_FILTER', '(&(objectclass=*)(|(cn=%s)))');```

**Comment by gbwebdev** [comment]
I will try on Monday and give you the results.
Thanks !

Le 17 août 2018 11:45:17 GMT+02:00, stinnux <notifications@github.com> a écrit :
>instead of 
>```define('LDAP_USER_FILTER', '(&(objectclass=*)(|(cn=%uid)))');```
>try
>```define('LDAP_USER_FILTER', '(&(objectclass=*)(|(cn=%s)))');```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kanboard/kanboard/issues/3978#issuecomment-413814836

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by bugwatcher** [comment]
Please, use the new forum for questions or installation issues: https://kanboard.discourse.group/
