### ISSUE TITLE
Separated swimlanes & columns

### ISSUE THREAD

**Issue by Skyrid3r** [kanboard/kanboard#3979]
I'm not sure if it was already suggested/or already implemented but couldn't find a way. 

Is there anyway that the Swimlanes & Columns can be separated? So that each Swimlane can have their own columns, rather than being duplicated.

**Comment by dasBuero** [comment]
Hello,
this could be a nice feature to separate the logic and define columns independently. Are there any efforts in this direction?

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
