### ISSUE TITLE
add global parameter to visualize entire activity flow of a task

### ISSUE THREAD

**Issue by avermote** [kanboard/kanboard#3980]
In the release 1.2.5 of kanboard, I note that I can't see the oldest part of activity flow, in the screen "activity flow for a task"
I don't find any documentation about the rules which are applyed to remove oldest activity flow item. For our need, we prefer have all history of activity flow. 

I suggest you to add a general parameter to describe if we want all history or not and a second one if the first parameter have the value "no" to set up the duration of visibility. Ex : the last 10 days

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
