### ISSUE TITLE
Freenode IRC #kanboard Spam

### ISSUE THREAD

**Issue by risturiz** [kanboard/kanboard#3986]
Hi,

Actually the channel is getting a lot of spam, but only @fguillot is admin... Its there any chance to promote someone that can help with administration of the channel?

Thanks.

**Comment by bugwatcher** [comment]
This is an invalid bug report. See https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#how-to-make-a-bug-report

Please, use the forum to ask questions: https://github.com/kanboard/forum/issues
