### ISSUE TITLE
Display project descriptions in public board display

### ISSUE THREAD

**Issue by seflerZ** [kanboard/kanboard#3987]
The public board is now displaying only the swimming lane cards and nothing else. I think it should display at least the project introduction and some basic concepts to help none project members to understand what is going on.

The project in Kanban indeed can be configured with descriptions but it's just not displayed in the public board. I think it is needed in public display.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
