### ISSUE TITLE
connexion AD 

### ISSUE THREAD

**Issue by kiterfoo** [kanboard/kanboard#399]
Bonjour,

je tente de connecter kanboard avec notre AD mais rien n'y fait, pas de message d'erreur pour m'aider.
voici ma config :

define('LDAP_AUTH', true);
define('LDAP_SERVER', 'ldap.abes.fr');
define('LDAP_PORT', 636);
define('LDAP_SSL_VERIFY', true);
define('LDAP_BIND_TYPE', 'proxy');
define('LDAP_USERNAME', 'ldap_cloud@levant.abes.fr');
define('LDAP_PASSWORD', 'xxxxxxxx'); #bien sur le mot de passe n'est pas le bon :)
define('LDAP_ACCOUNT_BASE', 'CN=ldap_cloud,OU=applicatif,OU=Utilisateurs,DC=levant,DC=abes,DC=fr');
define('LDAP_USER_PATTERN', '(&(objectClass=user)(sAMAccountName=%s))');
define('LDAP_ACCOUNT_FULLNAME', 'displayname');
define('LDAP_ACCOUNT_EMAIL', 'mail');

je post ma config pour Owncloud qui se trouve sur le même serveur et pour qui la connexion AD fonctionne.

ldaps://ldap.abes.fr
636
CN=ldap_cloud,OU=applicatif,OU=Utilisateurs,DC=levant,DC=abes,DC=fr
xxxxxxx
DC=levant,DC=abes,DC=fr

Voila, toute piste ou solution seraient la bienvenus

Fred

**Comment by majordom21** [comment]
Je me joins à cette conversation car je n'arrive pas à me connecter en ldap à l'appli. Je vois qu'il n'y a pas de log dans data/
Y'a t'il moyen de les avoir ?

merci
