### ISSUE TITLE
Json RPC not working with Laravel

### ISSUE THREAD

**Issue by luanphan1996** [kanboard/kanboard#3991]
### Logs
 Problem 1
    - The requested package fguillot/json-rpc could not be found in any version, there may be a typo in the package name.

### Configuration

- Kanboard version: 1.2.0
- Database type and version: mysql V15.1
- PHP version: 7.1.20
- OS:
- Browser:

**Comment by ErrorFlexXx** [comment]
Json-rpc is included in kanboard 1.2.0. You can find it in the following path: vendor/fguillot/json-rpc.

To use it, writing `use JsonRPC\Server` should work (like it is used in app/Api/Authorization/Middleware/AuthenticationMiddleware.php for example).

It would be interesting, what your actually goal is. What do you want to implement with JsonRPC ?

**Comment by luanphan1996** [comment]
i'm wan to using api kanboard

**Comment by fguillot** [comment]
You can found a copy of the JSON-RPC library here: https://github.com/kanboard/kanboard/tree/master/libs/jsonrpc This one is not available via composer anymore. There are plenty of other libs that can do the same things.

Please, use the forum for questions next time.
