### ISSUE TITLE
batch move tasks to other project

### ISSUE THREAD

**Issue by Hanskes** [kanboard/kanboard#3993]
It would be very useful to be able to copy multiple tasks at once to another project. We use the program for planning construction projects where a large part of the tasks (and subtasks) per project is the same. I know that it is possible to export the tasks of a project and import them again in the next project, but subtasks are not included.

**Comment by Hanskes** [comment]
I tried to achieve this with the current batch function in the list view. I stated in the automatic actions that when moving to another column the task is moved to another project, but apparently the automatic actions are not executed from the batch function.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
