### ISSUE TITLE
Odd error in console

### ISSUE THREAD

**Issue by adamprocter** [kanboard/kanboard#3995]
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src”). Source: call to eval() or related function blocked by CSP.

- Application version: 1.2.5
- PHP version: 7.2.9
- PHP SAPI: cgi-fcgi
- OS version: Linux 2.6.32-696.18.7.el6.x86_64
- Database driver: sqlite
- Database version: 3.6.20
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0

Not sure if this plugin related.

GitLab Webhook | Frédéric Guillot | 1.0.6 | 
Gantt | Frédéric Guillot | 1.0.4 | 
Task Interval Button | Igor Mroz | 0.9.0 | 
Calendar | Frédéric Guillot | 1.1.0 |
DueDate | David Morlitz | 1.0.2 |

**Comment by fguillot** [comment]
Your issue is probably related to one of the plugins. Remove all them, and install only one at the time.

By default, Kanboard doesn't allow the execution of inline Javascript.

If you have any installation issue, please use the forum instead: https://kanboard.discourse.group/
