### ISSUE TITLE
External Authentication 

### ISSUE THREAD

**Issue by Zeuh** [kanboard/kanboard#4]
Hi,

Possibility to use external authentication (ie LDAP) via module or extended class.

If you write a simple example or skeleton I can write complete code for LDAP.

Best Regards !

**Comment by poVoq** [comment]
Seems like embedding Kanboard into Owncloud is pretty popular, but not everyone wants to set up an external authentification service.
I think this gives some idea how kanboard could authentificate against Ownloud:
https://doc.owncloud.org/server/8.1/developer_manual/core/externalapi.html
(as it follows the OCS standard, it might work with other websites also in the future).
