### ISSUE TITLE
Can't login with chrome unless cookies removed. #2677 The error still exists

### ISSUE THREAD

**Issue by yuenshui** [kanboard/kanboard#4001]
POST /?controller=AuthController&action=check HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Cookie: KB_RM=6a20a1e955c834479c1af83fa07d5c0f1708777397ff46711fbd69f712d44ec8%7C1cce4dbaf253ee0db7520e42a236f997f32bae8ea46bb55235f055e0a2dc

chrome  68.0.3440.106
safari  11.1.2 (13605.3.8)
PHP 7.1.0
CentOS 7.5

**Comment by yuenshui** [comment]
kanboard version  1.2.5

**Comment by yuenshui** [comment]
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 04 Sep 2018 23:54:53 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: KB_SID=b2sqd5odgqditm8kghneclaorn; expires=Fri, 05-Nov-2021 09:41:32 GMT; Max-Age=99999999; path=/; secure; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src * data:;
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
P3P: CP="IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
X-Frame-Options: DENY
Strict-Transport-Security: max-age=31536000
Content-Encoding: gzip

**Comment by lastlink** [comment]
Maybe you have an extension in chrome causing a bug.

**Comment by bugwatcher** [comment]
This is an invalid bug report. See https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html#how-to-make-a-bug-report
