### ISSUE TITLE
Don't prohibit start date behind due date?

### ISSUE THREAD

**Issue by Kloppi313** [kanboard/kanboard#4004]
Hello,

is there any reason why it is not possible to have a start date behind a due date?
There are cases when you aren't able to start to work on a task and the end date (due date) reaches. I think a warning only would be enough, but please don't prohibit saving the task.
Also the editmode of a task has due date and start date in the interface, but saving it triggers the warning "The start date is greater than the end date" - I would say a due date (you are aiming for) is not the same as an end date (when you are actually finished).

So I would like to have the option to save tasks with a start date behind a due date and to standardize the phrasing (due vs. end).

**Comment by neiaberau** [comment]
actually this  works limited/partially, but is actually not consistent, 

steps to demonstrate, tested on the 08-09-2018:

   1) add a new task set the due date to 31-08-2018 (in the past), leave start date empty
   2) go to the task view and press start now
      => you get a task with "Due date: 08/31/2018 00:00"  and "Started: 09/08/2018 11:00"
 3) however, now try to modify the description of the task and save the task, 
    this is not possible anymore without change the started data

**Comment by Kloppi313** [comment]
Thanks for this information.
For me this is just one point more for being weird.
In some cases it is checked, in other cases not. But as I stated, I think it shouldn't be checked or at leased prevented.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
