### ISSUE TITLE
UI: Chrome rendering problem with width of project list dropdown

### ISSUE THREAD

**Issue by Kloppi313** [kanboard/kanboard#4005]
### Actual behaviour

In Chrome you see the change project field with to much width. (At least in the detailed view of a task, the overview of a project, own profile view, user- and groupmanagement, usersettings)

### Expected behaviour

The width should be the same on all pages. The dashboard looks fine and can be used as reference.

### Steps to reproduce

Navigate to one of the mentioned pages in chrome.
### Screenshots
not ok:
![image](https://user-images.githubusercontent.com/36038231/45206618-bb71ec00-b285-11e8-83da-01a6529a2c83.png)

ok:
![image](https://user-images.githubusercontent.com/36038231/45206894-916cf980-b286-11e8-894e-4c2ac16bbf75.png)

### Logs
not needed

### Configuration

- Kanboard version: 1.2.5
- Database type and version: mariadb 1:10.1.34-0ubuntu0.18.04.1
- PHP version: 7.2.7-0ubuntu0.18.04.2
- OS: Windows 10 (Client)
- Browser: Chrome 69

**Comment by jajm** [comment]
I have the same problem with Firefox 61. It can be fixed by refreshing the page.

A quick `git bisect` shows that this is caused by 7c0a1a5fbda41a1d9eb8af86546bd024275b7301 (Defer javascript files by default)

The problem is still in master.

**Comment by jajm** [comment]
It looks like removing this line https://github.com/kanboard/kanboard/blob/44cf75467c827f007ed2ca5962d3f864f6f10cd2/assets/js/components/select-dropdown-autocomplete.js#L268 fixes the problem.

**Comment by Kloppi313** [comment]
I also stumbled across this line. But in IE 11 everything looks fine.
Because I'm not firm with javascript my debugging possibilities are limited.

**Comment by Rustapo** [comment]
@jajm yes, this make help

**Comment by Markus-BE-X** [comment]
I also had this issue with the tarball of v1.2.5.

The issue was solved, removing the `.style("width",e.offsetWidth-30+"px")` part from the **assets/js/app.min.js** file.

```
y=KB.dom("input").attr("type","text").attr("placeholder",B()).addClass("select-dropdown-input").style("width",e.offsetWidth-30+"px").on("focus",c).on("input",r,!0).build(),w=KB.dom("div").addClass("select-dropdown-input-container").add(k).add(y).add(C).add(x).build()
```
_open it in vi and search for **.addClass("select-dropdown-input")**_

**Comment by Kloppi313** [comment]
Fixed. Thanks to @fguillot 
https://github.com/kanboard/kanboard/commit/1db83cddd019567cb0e059376fb59b89809025cf
