### ISSUE TITLE
if I save changes content in a project (configure project) it's not clear that the project has been saved

### ISSUE THREAD

**Issue by djonthenet** [kanboard/kanboard#4006]
it is not clear that the project has been saved

**Comment by creecros** [comment]
it's not clear what you are referring to

**Comment by creecros** [comment]
I just figured out what you are referring too, and after hitting "Save"
![image](https://user-images.githubusercontent.com/26339368/46222908-cfa68780-c31f-11e8-87a1-674184abd6dc.png)
It's pretty clear it saved.

**Comment by bugwatcher** [comment]
This is an invalid bug report. See https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#how-to-make-a-bug-report
