### ISSUE TITLE
A USER with role USER must not change his USERname! (and other profile settings)

### ISSUE THREAD

**Issue by erpnedir** [kanboard/kanboard#4007]
### Actual behaviour
A user with the role "User" can edit his profile, can change his username, name and email.

### Expected behaviour
Only users with role "Admin" must be able to change these information. Edit Profile menu must be disabled for this user role and Manager user role.

### Steps to reproduce
Create a user with role "User"
Login with that user
Go to user menu "My Profile"
Click "Edit Profile" menu
Change your username,name and email. Also preference settings.
Log out
Login with your new username

- Kanboard version: 1.2.5
- Database type and version: mysql 5.6.40
- PHP version: 5.6.37
- OS: Linux 3.10.0-427.36.1.lve1.4.47.el7.x86_64
- Browser:Chrome

**Comment by lastlink** [comment]
I don't think this is planned behavior maybe if you're using ldap. This probably could be changed via a plugin.

**Comment by creecros** [comment]
Agree with @lastlink , users like to edit their own info, what if someone gets married and changes their last name?

pretty sure it would be a very simple plugin. 

Hints: 
* [Example of changing default roles in the form of a plugin](https://github.com/creecros/opencomment)
* [This will help you understand the role you seek](https://github.com/kanboard/kanboard/blob/master/app/ServiceProvider/AuthenticationProvider.php)
* `getApplicationAccessMap()`
* `APP_USER`

I just did it for you, without doing it for you....sorta kinda.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
