### ISSUE TITLE
Command name "notification:overdue-tasks" is invalid.

### ISSUE THREAD

**Issue by renney** [kanboard/kanboard#4009]
### Actual behaviour

When I upgraded to v1.2.5 I get : 
Internal Error: Command name "notification:overdue-tasks" is invalid.
### Expected behaviour

I expected it to go to my board.

### Steps to reproduce
upgrade to v1.2.5 and type http://<your_url>/kanboard/.
move the sqllite data base to data directory from the old directory.

### Configuration

- Kanboard version: v1.2.5
- Database type and version: SQLite3
- PHP version: PHP 7.0.7 (cli) (built: Jun  4 2016 22:36:31) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
- OS: FreeBSD 10.4
- Browser: Chrome

**Comment by renney** [comment]
Same behavior when I upgraded to:
PHP 7.2.9 (cli) (built: Sep 12 2018 13:13:13) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
