### ISSUE TITLE
Feature Request: Add Top|Bottom Scroll on Page

### ISSUE THREAD

**Issue by aljawaid** [kanboard/kanboard#4010]
I've tried and tried to find a css-only solution to this but seem to be struggling.

Most of the tasks have **a lot** of comments by users going back and forth.

It would be nice if the side of the screen (right side in the middle) had an up/down arrow to jump to the top/bottom of the page respectively.

Or if anyone can suggest a css solution I could check it out.

**Comment by creecros** [comment]
here's how you would do it
https://github.com/creecros/Bak2topbotm

**Comment by creecros** [comment]
only thing i couldnt figure out was making the "bottom" button appear before scroll starts....leave that to you.

![image](https://github.com/creecros/Bak2topbotm/blob/master/screenshot/test_buttons.gif)

**Comment by aljawaid** [comment]
@creecros thanks!  I will check this out soon :)

**Comment by creecros** [comment]
ya, that solved it, works perfectly now. added you as a collab, do with it as you please.
