### ISSUE TITLE
Show description of task in public link

### ISSUE THREAD

**Issue by andjona** [kanboard/kanboard#4014]
Would be helpful to see the description of a task int the overview of a public share without having to click the task itself.

**Comment by andjona** [comment]
"Write a clear and concise description of your idea" - thought this is what i did - sorry, probably too short.
If I share a public link of a project, here is no info when i hover over the little document icon, compared to when i´m logged in. In my opinion it would be nicer to show that information (at least an excerpt of it) in the overview.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
