### ISSUE TITLE
kanbord 导出中文乱码

### ISSUE THREAD

**Issue by xwinie** [kanboard/kanboard#4019]
[任务.xlsx](https://github.com/kanboard/kanboard/files/2414545/default.xlsx)

项目设置中导出任务，是乱码

**Comment by creecros** [comment]
![image](https://user-images.githubusercontent.com/26339368/46221230-8b64b880-c31a-11e8-88e6-8d857329c8db.png)

Probably because it is a .csv?

There is really no information here to assist you.

**Comment by bugwatcher** [comment]
This is an invalid bug report. See https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#how-to-make-a-bug-report
