### ISSUE TITLE
Subtask to Task dialog improvement

### ISSUE THREAD

**Issue by itrv** [kanboard/kanboard#4020]
It would be nice to have an extended dialog for converting a subtask into a task.

Like the dialog when you open a task, but with name and assignee prefilled from the subtask.

thank you for kanboard and your invested time :)

**Comment by creecros** [comment]
I've thought about this before, and would even like to keep a "relates to" link to the task it came from. I might be inclined to make this a plugin.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
