### ISSUE TITLE
Sort Results in API Call searchtasks

### ISSUE THREAD

**Issue by mburamorde** [kanboard/kanboard#4021]
Hi, 

I totally love the api, but I'm missend the feature to get Results via https://docs.kanboard.org/en/latest/api/task_procedures.html#searchtasks and to limit the Number of results and decide how the results should be sorted.

Currently the results are sorted by ID ASC and I only need the last result ...

Thanks,
Michael

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
