### ISSUE TITLE
Tilt card to show card is in drag mode

### ISSUE THREAD

**Issue by emahuni** [kanboard/kanboard#4025]
To make dragging more intuitive, when the card is in drag mode it should tilt a little (just basic css stuff). This allows the user to feel that they have grabbed the card so that they begin their dragging quest.

**Comment by creecros** [comment]
are you on a mobile device? The card clearly is in drag mode with the dotted lines.

![image](https://raw.githubusercontent.com/creecros/Bak2topbotm/master/screenshot/test_drag.gif)

**Comment by emahuni** [comment]
True.

**Comment by fguillot** [comment]
Please, use the forum to suggest enhancements https://kanboard.discourse.group/
