### ISSUE TITLE
Action stream remains empty and table project_activities, too.

### ISSUE THREAD

**Issue by Shadow-crow** [kanboard/kanboard#4027]
### Actual behaviour

On the movement of a task, the activity stream doesn't mention it.
It suddenly stopped working. No systemupdate or versionupdate has been made or anything else.

### Expected behaviour

When moving a task the action stream logs it.

### Steps to reproduce

Move a task from "Ready" to "Work in progress"

### Screenshots
![grafik](https://user-images.githubusercontent.com/10142050/46295621-cf64f100-c598-11e8-834b-797e45ebccff.png)

![grafik](https://user-images.githubusercontent.com/10142050/46295579-b78d6d00-c598-11e8-9e13-69a6ebdeb7c0.png)

### Configuration

    Version: 1.2.5
    PHP Version: 7.1.15-1+ubuntu16.04.1+deb.sury.org+2
    PHP SAPI: fpm-fcgi
    OS Version: Linux 4.4.0-121-generic
    Datenbanktreiber: mysql
    Datenbank Version: 10.0.34-MariaDB-0ubuntu0.16.04.1
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by Shadow-crow** [comment]
No idea anyone?

**Comment by Shadow-crow** [comment]
I researched a little bit with the debug.log and there is no INSERT into the table project_activities. When I open:

[debug] APP: uri=/?controller=ActivityController&action=project&project_id=

the the SELECT query is called:

[debug] SQL: SELECT project_activities.*, uc.username AS author_username, uc.name AS author_name, uc.email, uc.avatar_path FROM `project_activities` LEFT JOIN `tasks` ON `tasks`.`id`=`project_activities`.`task_id` LEFT JOIN `projects` ON `projects`.`id`=`project_activities`.`project_id` LEFT JOIN `users` AS `uc` ON `uc`.`id`=`project_activities`.`creator_id`  WHERE project_activities.project_id = ?   ORDER BY project_activities.id DESC  LIMIT 50

but the table is empty...
Any ideas where to look?
No PHP or SQL-Errors appeared - the table is just not filling when doing an action with a task.

**Comment by bugwatcher** [comment]
Please, use the forum for questions or installation issues: https://kanboard.discourse.group/
