### ISSUE TITLE
API issue in live ubuntu server

### ISSUE THREAD

**Issue by SagarRaiyani** [kanboard/kanboard#4029]
### Actual behaviour

500 internal server error in postman

### Expected behaviour

i have s

### Screenshots

![image](https://user-images.githubusercontent.com/5584295/46332133-aac05600-c638-11e8-864e-e61d3c505f1d.png)

### Configuration

- Kanboard version:1.1.0
- Database type and version:mysql 5.7.23
- PHP version:7.0.32-0
- OS:ubuntu0.16.04.1
- Browser:chrome

**Comment by creecros** [comment]
Content-type?

**Comment by bugwatcher** [comment]
This is an invalid bug report. See https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#how-to-make-a-bug-report
