### ISSUE TITLE
Task Activity log with API JSON-RPC

### ISSUE THREAD

**Issue by niwang09** [kanboard/kanboard#4034]
Hi. ive been using KANBOARD JSON-RPC . it seems that movingTaskColumn or createTask does not include the activity log. ive also tried in the kanboard moving task column and creating task also create activity log.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
