### ISSUE TITLE
Update Template hooks docs

### ISSUE THREAD

**Issue by DaGLiMiOuX** [kanboard/kanboard#4036]
There is an error in https://docs.kanboard.org/en/1.2.5/plugins/hooks.html#template-hooks (template with callable section).

Shows an `attach` call with a callable, but only accepts an array. There is another function in HookHelper that is called `attachCallable`, but there is no information in docs. Also, would be nice to explain a bit how events can be attached and which values are available. E.g:

Listen show call in Tasks controller:
`controller:task:show`: The name of the element you want to listen (controller, model, ...), the name of the model from which you want to listen (task, project, user...) and the event (open, close, create, delete, beforeInsert...). It's kinda hard to do a plugin without that event information.

**Comment by fguillot** [comment]
Doc updated: https://docs.kanboard.org/en/latest/plugins/hooks.html#template-hooks
