### ISSUE TITLE
Change color when due date expired

### ISSUE THREAD

**Issue by VincentEclancher** [kanboard/kanboard#4038]
Hello,

### Actual behaviour

I try to run the automatic action which allows to change the color of a task if the due date expired.
But when the due date expired, nothing happens.

### Expected behaviour

The color has to change once the due date expired.

### Steps to reproduce

1. Add an automatic action to change the color if the due date expired 

2. Wait until the due date expired.

### Configuration

- Kanboard version: 1.2.5
- Database type and version: postgres 9.6.10
- PHP version: 7.0.30-0+deb9u1
- OS: Linux 4.9.0-8-amd64
- Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

Thank's in advance for your help.

**Comment by dmorlitz** [comment]
I have noticed the same problem.  By any chance - does your project have multiple swimlanes?  I believe that this action is only affecting the first swimlane on my board - rather than all swimlanes.

**Comment by komochek32** [comment]
Is cronjob running? https://docs.kanboard.org/en/latest/admin_guide/cronjob.html
I have the same problem and this instruction solved it.

**Comment by VincentEclancher** [comment]
Thank's for your answer, it works !
