### ISSUE TITLE
Tooltips not working after drag & drop

### ISSUE THREAD

**Issue by DaGLiMiOuX** [kanboard/kanboard#4039]
### Actual behaviour

When you see the task list page for a project, you can see the tooltips on icons when hovering them and access to links when you upload files, for example. After drag and drop, and not refreshing the page, tooltips stop working.

### Expected behaviour

When you drag and drop tasks between columns, keep the tooltips working when hovering on them.

### Steps to reproduce

1 - Create a project.
2 - Create a task.
3 - Attach a file, add a subtask or w/e element that shows an icon with a tooltip.
4 - Go to task list and hover the icon with the tooltip in the created task.
5 - Move the task to another column.
6 - Without refreshing the page, try to hover again the tooltip button.

### Screenshots

When you hover it after loading the page.

![image](https://user-images.githubusercontent.com/1701519/46792552-e9929200-cd43-11e8-8ade-3a9751128153.png)

When you hover it after the task was moved, without refreshing the page.

![image](https://user-images.githubusercontent.com/1701519/46792900-aa187580-cd44-11e8-976d-04057b01cc33.png)

### Logs

None relevant

### Configuration

- Kanboard version: 1.2.5
- Database type and version: SQLite
- PHP version: 5.7
- OS: Windows 10
- Browser:  69.0.3497.100

---

It could be because tooltip initialization. The tooltip [has these lines](https://github.com/kanboard/kanboard/blob/master/assets/js/core/tooltip.js#L81-L84) at the end of the JS. There should be an event listener in the document and check if the hovered target is a tooltip, instead of attaching to current shown tooltip elements. When hovering is triggered in the element matching the selector, it will run the function. More like when you attach an event listener in jQuery and you specify a second param as a selector to find a child element for the element with the attached listener (the whole document in this case).

**Comment by creecros** [comment]
Disable your css plug in and try again. Likely culprit.

**Comment by DaGLiMiOuX** [comment]
> Disable your css plug in and try again. Likely culprit.

I do not think that the problem is the CSS plugin, as it is still not working when disabled.

**Comment by creecros** [comment]
worth a shot. I cannot reproduce though.

**Comment by DaGLiMiOuX** [comment]
I will try to check ASAP if it is not working because of a plugin or maybe a browser problem (Chrome 70 right now). Btw, I'm currently working in another project and I don't have too much time to check it out. If it works for you, maybe a plugin is interfering as you said. I will close it for now and reopen it if needed later.

Thanks for your time.
