### ISSUE TITLE
Denial of Service in controller=AvatarFileController

### ISSUE THREAD

**Issue by tjharman** [kanboard/kanboard#4041]
### Actual behaviour

The size parameter on the Avatar image isn't checked against the image size.

https://kanboard.site/?controller=AvatarFileController&action=image&user_id=1&size=20

If I change size=20 to size=20000 I can cause php to chew up massive amounts of memory and basically render my machine unusable.

**You do not need to be logged in for this to be used.  You can find any kanboard site and twiddle with the URL it seems.**

### Expected behaviour

the size= parameter should check the size of the image and not allow it to be greater than the image is.

I would also have thought that the  memory_limit = 128M in my php.ini would have caught this, but it appears not to.

### Steps to reproduce

Upload a small avatar to your website and set it.
Right click on the Avatar in the upper right hand corner and save the image URL.

Paste the image url into a new browser window, but adjust the size= parameter to be 20000.
Attempt to load the image while watching "top" on your unix box.
Notice that the php process grows rapidly and eventually a massive image is generated (at least I get one)

### Logs
KiB Swap:  2094076 total,  1893884 free,   200192 used.   102268 avail Mem

```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 3574 www-data  20   0 2018780 1.428g  45428 R  99.7 73.7   0:42.87 php-fpm7.0
 5096 www-data  20   0  441588  56900  44912 S   3.3  2.8   2:36.39 php-fpm7.0

```

If I increase the size to be larger than 20000 I get the following in my Apache error.log

`[Fri Oct 12 10:15:25.011690 2018] [proxy_fcgi:error] [pid 9837:tid 3627542316800] [client 10.1.1.2:22985] AH01071: Got error 'PHP message: PHP Warning:  imagecreatetruecolor(): product of memory allocation multiplication would exceed INT_MAX, failing operation gracefully\n in /var/www/kanboard/app/Core/Thumbnail.php on line 124\nPHP message: PHP Warning:  imagecopyresampled() expects parameter 1 to be resource, boolean given in /var/www/kanboard/app/Core/Thumbnail.php on line 127\nPHP message: PHP Warning:  imagejpeg() expects parameter 1 to be resource, boolean given in /var/www/kanboard/app/Core/Thumbnail.php on line 169\nPHP message: PHP Warning:  imagedestroy() expects parameter 1 to be resource, boolean given in /var/www/kanboard/app/Core/Thumbnail.php on line 170\n'`

### Configuration

- Application version: 1.2.6
- PHP version: 7.0.30-0+deb9u1
- PHP SAPI: fpm-fcgi
- OS version: Linux 4.17.19-grsec
- Database driver: mysql
- Database version: 10.1.26-MariaDB-0+deb9u1
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
- Chrome/69.0.3497.100 Safari/537.36

**Comment by creecros** [comment]
20000 is the magic number? Always wondered.

**Comment by tjharman** [comment]
20000 might not be the exact number sorry, I just experimented with various numbers and if I added a 0 to this I got the error.
