### ISSUE TITLE
Add "Minor edit" in Activity / Notification

### ISSUE THREAD

**Issue by oliviermaridat** [kanboard/kanboard#4042]
As stated several times (for example [here about RocketChat plugin](https://github.com/kanboard/plugin-rocketchat/pull/6)), the activity and notification mechanisms of Kanboard could be enhanced (more details, notify by groups of activities instead of one by one, colors, ...).

I have not the full solution (yet ^^), but one idea that may help: add the notion of "Minor edit" from Mediawiki to Kanboard activities. One example: a user edits a task description (typo) on Kanboard, if it checks the "Minor edit" checkbox added under the textarea, this edition will not be notified by email / tchat / ... A such checkbox could be added almost everywhere (subtask, link, comment, ...).
Technically, this probably implies to add a field "minorEdit" to "activity.

What do you think?

I may work on this, but I am available for validation only if someone has some time to implement this.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
