### ISSUE TITLE
Allow empty Start Date and Due Date

### ISSUE THREAD

**Issue by coreygans** [kanboard/kanboard#4050]
### Use case
I have tasks which I have scheduled and leverage the Gantt chart to visualize, but there are also tasks which are either lower priority or won't be scheduled until the next planning, but still want it in the backlog. Right now Start Date and Due Date are required so then the Gantt chart gets messy.

### Desired outcome
Be able to have tickets in the backlog that are separated out on the Gantt chart page as not being scheduled. 

![screen shot 2018-10-16 at 1 31 07 pm](https://user-images.githubusercontent.com/5404391/47039329-51344d00-d149-11e8-907f-8e3335501585.png)

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
