### ISSUE TITLE
Can't send mail via smtp

### ISSUE THREAD

**Issue by t812206236** [kanboard/kanboard#4051]
Already changed config.default.php to config.php
Also changed all of the following
```shell
Define('MAIL_FROM', 'xxx@yyy.com');
Define('MAIL_TRANSPORT', 'smtp');
Define('MAIL_SMTP_HOSTNAME', 'smtp.yyy.com');
Define('MAIL_SMTP_PORT', 25);
Define('MAIL_SMTP_USERNAME', 'aaa');
Define('MAIL_SMTP_PASSWORD', 'bbb');
Define('MAIL_SMTP_ENCRYPTION', 'tls');
```
**This configuration is valid on another arch platform!**

Look at /var/log/mail.log or /var/log/mail.err,
```shell
Oct 22 13:00:02 cloud sm-msp-queue[2557]: My unqualified host name (cloud) unknown; sleeping for retry
Oct 22 13:01:02 cloud sm-msp-queue[2557]: unable to qualify my own domain name (cloud) -- using short name
```
Cloud is the name of my vps operator, but I am very confused that I obviously use the smtp server of other websites. 
Why is my local domain name used when sending emails? 
Is the parameter I configured in config.php invalid? 
Do I need to configure sendmail or mailx in linux or something else in the environment?

**Comment by yzaguirre** [comment]
What's left to try? It works on Arch.

Does the email provider set up port **587** with STARTTLS? I've used that port along with your configuration, it works.

**Comment by t812206236** [comment]
> 
> 
> What's left to try? It works on Arch.
> 
> Does the email provider set up port **587** with STARTTLS? I've used that port along with your configuration, it works.

I am directly copying the configuration of the arch platform, so it is impossible to be a problem with the smtp port.

**Comment by t812206236** [comment]
The latest php version that can be pulled under ubuntu 14.04 is 5.59, and kanboard relies on php version at least 5.6, so I have to compile 5.6.30 myself. I suspect that there is a problem configuring the compilation parameters or I am missing php. Some of the plugins (these are all running under php5.5.9), this is a never-ending process, so I gave up. Is there any way to reduce the kanboard requirements for the php version?

**Comment by bugwatcher** [comment]
Please, use the new forum for questions or installation issues: https://kanboard.discourse.group/
