### ISSUE TITLE
Always show horizontal scroll bar on screen, even with higher columns

### ISSUE THREAD

**Issue by bkroll** [kanboard/kanboard#4056]
### Actual behaviour
When columns are higher than the window, the user first needs to scroll down in order to reach the horizontal scroll bar. 

### Expected behaviour
No matter how high the columns are, the horizontal scroll bar should always be visible on screen.

### Steps to reproduce
1) have more columns on the board than fit into the window width
2) have more issues in at least one column than fit into the window height

### Screenshots
![bottomscrollbar](https://user-images.githubusercontent.com/10960255/47551021-50e24180-d901-11e8-8356-7928d45ed6d0.png)
There should be a horizontal scrollbar, but it is only visible once the user has scrolled down vertically.
![bottomscrollbaronlyatbottom](https://user-images.githubusercontent.com/10960255/47551607-f0ec9a80-d902-11e8-8bbe-5c88affbbad0.PNG)
This is inconvenient if the user wants to horizontally scroll through the board top (i.e. to see the total numbers of cards per column), but needs to scroll down, then sideways and then up again.

### Configuration

- Kanboard version: 1.2.5
- Database type and version: SQlite
- PHP version: 7.0.7
- OS: SLES 12 SP 3
- Browser: Chrome 71dev, Chrome 70.0, Firefox ESR 60.3

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) for open discussions, suggestions and feature requests. **This bug tracker is reserved only for bugs**.

**Comment by bkroll** [comment]
This kind of problem accessing the scroll bars in the board view appeared to be a bug, since the board view is a main feature of this software. Sorry to disturb here, we will solve the problem locally or try something else.
