### ISSUE TITLE
beanstalkd / smtp / worker in Docker image

### ISSUE THREAD

**Issue by arocholl** [kanboard/kanboard#4065]
Thanks for the nice Kanboard tool. We are using it with the Docker image and would love to have it available with the suggested beanstalkd daemon correctly setup for delegated smtp non-blocking configuration.

We tried our best with limited knowledge of the Alpine linux version available in the official docker image, but unfortunately could not correctly setup all details so is working only manually, we do not know how to safely include it in cron using s6-supervise (assumed to be the supervisor to use in Alpine) and also do not know how to confirm the email are actually being processed by the worker.

So if this nice suggested setup could be made available in docker image will help us (and probably others) tremendously. Thanks for your help.!

**Comment by creecros** [comment]
https://github.com/woahbase/alpine-kanboard

Maybe that helps

**Comment by bugwatcher** [comment]
You could run beanstalkd in a separate container and use something like Docker Compose. You should not need to modify the Docker image.

Please, use the new forum for questions: https://kanboard.discourse.group/
