### ISSUE TITLE
Emails are sent every time the cronjob is executed

### ISSUE THREAD

**Issue by frederikmoellers** [kanboard/kanboard#4066]
This issue is:

- [X] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour

Notifications (including emails) for overdue tasks are sent everytime the cronjob is executed.

### Expected behaviour

Notifications are sent only once or in configurable intervals (e.g. at most once every day).

### Steps to reproduce

1. Configure the cronjob to run every 15min.
1. Create a task and let it run beyond the due date
1. Receive an email every 15min

### Configuration

- Kanboard version: 1.2.6
- Database type and version: MySQL 10.1.26-MariaDB-0+deb9u1
- PHP version:  7.0.30-0+deb9u1
- OS: Debian 9.5 (stretch)
- Browser: irrelevant

### Additional Notes

I would like to keep the cronjob configured to run every 15min because I want to be notified within 15min if a task is overdue. However, getting an email every 15min floods my mailbox, often before I am able to log into KanBoard and change the date / mark the task as completed.

**Comment by creecros** [comment]
better explanation:
 
Turn off email notifications:
![image](https://user-images.githubusercontent.com/26339368/48018711-8952fe00-e0ff-11e8-9e7d-396f7eef7f6d.png)

run this every 15 mins `./cli notification:overdue-tasks`

setup auto action to send email of impending due date ([this is a plugin](https://github.com/creecros/SendEmailCreator)):
![image](https://user-images.githubusercontent.com/26339368/48018849-f6ff2a00-e0ff-11e8-820b-c6ed085e0e2d.png)

run task related crons every day, i think its `./cli trigger:tasks` i could be wrong

**Comment by frederikmoellers** [comment]
Agreed, it's arguably a bug. I was unsure whether to call it a bug or a feature request, I guess it's somewhere in between.

My problem with the first proposed solution (run the cronjob for email notifications once a day) is that emails are then only sent once a day. I'd still like to be notified *the moment* a task is due (or at most 15min after). However, I don't want to be notified *every 15 min* (or even every day, for that matter). Also, it still generates one web notification every 15 minutes, which I find weird.

If actions were supported for individual tasks, I could imagine creating an action "send email" and another one "push due date" when the due date hits. However, I can only do that for a whole project, not an individual task (or subtask). That's the problem with the second solution. It only works for whole projects, if I understand correctly.

My preferred solution would be this: You have a configurable value "Send due date notifications at most every ..." (maybe for each project individually, maybe for the whole installation). Then the due date checker sends the first notifications and saves the time of the notification. Whenever it's run again, it checks whether a new *notification* is due and if yes, sends that one and updates the saved timestamp.

However, I can imagine not many people feel a need for this feature. If that's the case I'll search for some workaround (maybe being notified once a day is enough if we set due dates a day earlier) and implement the feature myself when I find the time.

**Comment by creecros** [comment]
I don't believe it would be too difficult to add what you want to my plugin...just not sure I'd want to make the effort. I don't need it, and doesn't look like you even use it.

How I would implement:
I'd record each time an email is sent for each task, to each tasks metadata
I'd add a compare before attempting to send an email, comparing the date in meta and current time, if less than 86400 seconds, its not gonna send the email. 
Re-record the date when it jumps over 86400 seconds. 
now, no matter how many times your running cron a day, emails for each task will only send daily, but checking how ever often as you like.

**Comment by creecros** [comment]
the other key difference is that it will notify of "Impending" due date.

I can put it on my todo list, but I am actively working on a few other projects. If you use it, though, you should ⭐️ it, better chance that I do it 😛 , not like anyone is paying me for this, and stars make me feel special.

**Comment by creecros** [comment]
also, make the feature request on the plugin issue board. I need reminders.

**Comment by creecros** [comment]
test this branch, let me know if that works. I don't have a test server set up properly to test it at the moment...so you can be the guinea pig
https://github.com/creecros/SendEmailCreator/tree/creecros-test

**Comment by creecros** [comment]
Never mind, I tested, works perfectly. Was easier that I thought it was going to be. I did not add the functionality to subtasks, because there is no subtask metadata and you didn't actually ask for that...if someone requests it, I might be obliged. you should still star the repo, If you use it, ⭐️ it.

**Comment by frederikmoellers** [comment]
I just tested the new plugin and it seems to work fine :blush: 
I got 2 emails at the same time for the same task that passed its due date, but no additional mail afterwards (for a day). I'll try to see if I can find out why this happened, but so far I'm reall happy with the feature.
Thank you so much for implementing it!

**Comment by creecros** [comment]
It emails both the assignee and creator...that's why you got two emails
