### ISSUE TITLE
$this->configModel->remove()

### ISSUE THREAD

**Issue by creecros** [kanboard/kanboard#4071]
@fguillot I noticed that there is no `remove()` for Settings/Config `$this->configModel` in SettingsModel or ConfigModel, per https://docs.kanboard.org/en/latest/plugins/metadata.html. Not sure if this is intentional or not, and I could see how it could be intentional, so I'm hesitant to suggest via a pull request.

**Comment by fguillot** [comment]
Because until now, nobody had the need to remove application settings. If you need that for a plugin you can send a PR.
