### ISSUE TITLE
Movement of subtask not possible in Chrome

### ISSUE THREAD

**Issue by Kloppi313** [kanboard/kanboard#4072]
### Actual behaviour

It is not possible to move a subtask within Google Chrome 70.0.3538.102 32Bit; Windows 10 Pro

### Expected behaviour

When clicking on "Change position of subtask" (might be likely, because I use it in another language), the subtask should be movable.

### Steps to reproduce
Have Chrome 70, a task with at least two subtasks and try to change their position.

### Configuration

- Kanboard version: 1.2.6
- Database type and version: 10.1.34-MariaDB-0ubuntu0.18.04.1
- PHP version: 7.2.10-0ubuntu0.18.04.1
- OS: Windows 10 Pro
- Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

**Comment by Snajper88** [comment]
Dude, its Drag'n'Drop.
But there is one issue - if you've just created one or edited one subtask, it isnt moveable until you refresh the site.

**Comment by Kloppi313** [comment]
I know it's drag and drop.
But you are right, after reloading the page it is moveable.
I thought it has to do with the browser, because after experiencing the issue I tested in IE and it worked as intented.

**Comment by fguillot** [comment]
Just tried with Chrome and this is working fine for me. Do you have any plugin installed or browser extensions that may cause problem? any errors in the browser console?

**Comment by Kloppi313** [comment]
It only appered once for me and I'm not able to reproduce it. So I close this issue.
