### ISSUE TITLE
Display every LDAP groups

### ISSUE THREAD

**Issue by vincowl** [kanboard/kanboard#4074]
LDAP groups are not automatically displayed on Group page. A member user shall connect to Kanboard so that LDAP group is added to Group board. It would be better to display every found groups including DB and LDAP ones even if no member has logged to Kanban since group declaration

**Comment by battosai30** [comment]
Maybe it's not the same problem but it's pretty closed : I use an Active directory to manage login on my kanboard. All users are in the same group. But : 
1) Group is not showed directly in the group list. 
2) If the user log in, his account is created but not the group. I have to first create a fake project, and had a permission to the group (I start typing the name, and effectively the complete group name is suggested) to get the group created. Now, if another member of this group log in for the first time in kanboard, he's created and he's attributed to the group on kanboard.

**Comment by towo** [comment]
Yeah, there should be some option to slurp (as well as *purge*) users and groups from LDAP; `synchronize()` only gets called on a login, for that user, as far as I saw that with a quick glance.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
