### ISSUE TITLE
Display groups membership in a user's summary page

### ISSUE THREAD

**Issue by vincowl** [kanboard/kanboard#4075]
Groups membership in a user's summary page are not displayed. It would be useful to show this in order to have a quick view. Indeed, there is no easy way to get this info since groups members are only shown in the group's details and not in the "all groups" page.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
