### ISSUE TITLE
Add default filter per user per project

### ISSUE THREAD

**Issue by martinmildner** [kanboard/kanboard#4076]
Hi,

The "default filter for users" is perfect. In case someone has a lot of projects, the default filter per user does not make sense in all projects. The ability to set a default filter per user per project would solve this.

Thanks for the great work @fguillot !

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
