### ISSUE TITLE
Where do I configure Task Templates?

### ISSUE THREAD

**Issue by frakman1** [kanboard/kanboard#4078]
There appears to be the facility to chose a Task Template when I try to create tasks in bulk

![image](https://user-images.githubusercontent.com/5826484/48954081-0828a300-ef16-11e8-9036-ae32a24a93d0.png)

![image](https://user-images.githubusercontent.com/5826484/48954068-fe06a480-ef15-11e8-86b5-db0aeb66807b.png)

However, I was unable to find anywhere in Kanboard where I can set this Task Template. Can anyone help? What am I missing?

Also, what exactly does "Enter one task by line" mean? At first I thought it meant enter each task on its own line but that didn't make sense. Does it mean, restrict the task description to one line?

**Comment by creecros** [comment]
It's in the project config, under "Predefined Content"

![image](https://user-images.githubusercontent.com/26339368/49031963-60abaa80-f179-11e8-9a6f-c0389815a0e3.png)

**Comment by frakman1** [comment]
That was it. Thank you!
