### ISSUE TITLE
URL Rewrite does not rewrite everything

### ISSUE THREAD

**Issue by benrubson** [kanboard/kanboard#4079]
Hi,

I've activated URL rewriting, it works, for example "Project Management" goes to `/projects`.
Perfect.

However, some Kanboard parts are not rewritten.
For example, "My activity stream" is still `/?controller=ActivityController&action=user`
"My calendar" is `/?controller=CalendarController&action=user&plugin=Calendar`
"Project Gantt chart" is `/?controller=ProjectGanttController&action=show&plugin=Gantt`

Any reason why ?

Thank you very much 👍

Ben

**Comment by p4kl0nc4t** [comment]
Any update on this one?

**Comment by aljawaid** [comment]
There is the URL Cleaner plugin available for this too

**Comment by p4kl0nc4t** [comment]
> There is the URL Cleaner plugin available for this too

Tried but did not work (I guess).

When I click on a task, the URL changed from

`/board/5` to `/?controller=TaskViewController&action=show&task_id=36&project_id=5`
