### ISSUE TITLE
Some search field miss-aligned

### ISSUE THREAD

**Issue by benrubson** [kanboard/kanboard#4080]
Hi,

On a new Kanboard installation, I just found this miss-aligned search field :
Project management / Users overview :

![sc](https://user-images.githubusercontent.com/6764151/49046058-2b33ab00-f1d3-11e8-9538-ef713c6dd643.png)

Thank you 👍

**Comment by rafacamargo123** [comment]
Apparently this bug was introduced by #4005

Removing the width: 300px from .select-dropdown-input-container selector gets the expected behaviour...

![image](https://user-images.githubusercontent.com/12586009/49838383-95327f80-fd91-11e8-869f-2b354c89397e.png)

**Comment by SladeP** [comment]
@benrubson this fix was merged into master, so this issue should be good to close!

**Comment by benrubson** [comment]
Good news @SladeP, thank you very much 👍
