### ISSUE TITLE
Minimize sidebar

### ISSUE THREAD

**Issue by ksciana** [kanboard/kanboard#4081]
This issue is:

- [ ] Bug report
- [x] Feature request
- [ ] Improvement

### Actual behaviour
Sidebar is visible with icons and action titles

### Expected behaviour
Option to minimize sidebar, when is minimalize, then only task number and action icons are visible, otherwise like now.

### Screenshots
![image](https://user-images.githubusercontent.com/1391147/49110177-0865cd00-f28d-11e8-97a7-ad849723b6d0.png)

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
