### ISSUE TITLE
Plugins upgrade with Plugin Manager display wrong infos

### ISSUE THREAD

**Issue by vincowl** [kanboard/kanboard#4084]
While upgrading Customizer plugin with the Kanboard Plugin Manager, it is still displayed as an old version in the "Installed Plugins" page while files have been properly installed and new version is running. This causes the UpdateNotifier plugin to display an erroneous "new upgrade available" message. Don't know if it's related to Customizer plugin or to internal Kanboard plugin management

### Actual behaviour

In the Plugin Manager, a new upgrade available is displayed. After applying it with a success message, the plugin's version is not updated and the new upgrade available is still displayed. Plugin's files have been correctly installed and upgraded plugin is running. This bug leads to the display of a message from UpdateNotifier plugin.

### Expected behaviour

After a plugin upgrade, its version shall be updated to be correctly displayed in the installed plugin list.

### Steps to reproduce
This append with Customizer plugin (the same issue has been opened on their repo). Did not try with other plugins. 

### Configuration

- Kanboard version: 1.2.6 (using docker image)
- Database type and version: sqlite 3.24.0
- PHP version: 7.2.10 fpm-fcgi
- OS: Mac OSX 10.14.1
- Browser: Safari 12.0.1

**Comment by vincowl** [comment]
Seems that installed plugins list is right, whereas plugin's status list (Install, Up to date, Upgrade) is wrong. Could not already find a common specificity to the plugins which status is erroneous

**Comment by creecros** [comment]
![image](https://user-images.githubusercontent.com/26339368/49226418-8375d300-f3b4-11e8-83bb-d4d5eccd2adc.png)

I see you're using Docker.

System Services for Docker, require you to restart your container.

**Comment by vincowl** [comment]
I just tried to remove the docker container and recreate it since plugins are persisted in mapped volumes. Indeed, the problem seems to be solved, at least with Customizer. Other plugins are still wrongly marked as not installed (Broadcast Message for instance)... Strange....

**Comment by creecros** [comment]
Other plugins may actually not be setup properly, the release files have to be:
- zipped properly
- correctly setup in Plugin.php
- Title and Name in plugin.php and json must match.
- Few other variables.

I could find the previous issues related to this, but, needless to say, it actually takes work to make sure the update function works as intended. I would say, it should be documented better for developers.

As far as Docker goes, I simple "Restart" to the container is all thats required, you don't need to recreate the container.

**Comment by petski** [comment]
I think I've found the answer for this bug in https://github.com/moby/moby/issues/15793. 

I see two improvements:

- Set `sendfile` to `off` in nginx.conf (currently, it's `on`)
- Improve plugin upgrade procedure to use `rsync` instead.
