### ISSUE TITLE
Why Does Bugwatcher LOCK comments?

### ISSUE THREAD

**Issue by aljawaid** [kanboard/kanboard#4091]
I understand issue/request controlling through bots, but as the majority of us cannot be collaborators here, why is the bugwatcher bot locking the issue to the level that we cannot even add a comment to the conversation?

Comments in github allow users to communicate and sometimes some solutions are found or solved through the comments, regardless of how old the issue is.  Even if it got closed, we should have the option to comment, just like other repositories on Github.

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
