### ISSUE TITLE
Email links "view the task on Kanboard" and "view the board on Kanboard" broken

### ISSUE THREAD

**Issue by vgf89** [kanboard/kanboard#4095]
### Actual behaviour

When a notification email is sent, there are two links at the bottom: "view the task on Kanboard" and "view the board on Kanboard". In Thunderbird, the link doesn't work; it shows up as an underlined blue link,and hovering it changes the cursor to the hand, but there's no link preview and clicking it does nothing. In Zimbra (a self-hosted webmail client), the link instead points to "https://mail.mydomain.com/kanban.mydomain.com/..."
Here's the source for the footer with the links:
`Kanboard - <a
href="kanban.mydomain.com/?controller=TaskViewController&amp;action=show&amp;task_id=61&amp;project_id=4"
        class="" title="" target="_blank" moz-do-not-send="true">view
        the task on Kanboard</a> - <a
href="kanban.mydomain.com/?controller=BoardViewController&amp;action=show&amp;project_id=4"
        class="" title="" target="_blank" moz-do-not-send="true">view
        the board on Kanboard</a>`

### Expected behaviour

The link should work (pointing to, say, https://www.kanban.mydomain.com/...). What I think is happening is that the link is just missing the `https://www.` which apparently breaks the link in Thunderbird and makes the link appear relative rather than absolute in Zimbra/webmail on a browser.

### Steps to reproduce

Setup email notifications for a user.

Trigger a notification.

Open the user's email in Thunderbird, try to click the link, and check the source ([More]->View Source)

### Configuration

- Kanboard version: 1.2.6
- Database type and version: sqlite 3.22.0
- PHP version: 7.2.10-0ubuntu0.18.04.1
- OS: Linux 4.15.0-29-generic  (Ubuntu 18.04)
- Browser: Chrome 70 (but I don't think this matters for the problem at hand)

**Comment by creecros** [comment]
is your application URL setup correctly with the `https://`

![image](https://user-images.githubusercontent.com/26339368/49671339-8a948500-fa35-11e8-9bd3-aeed77730487.png)

**Comment by vgf89** [comment]
That very well could be the issue. I'll check on Monday. Thanks!

**Comment by vgf89** [comment]
That fixed it, thanks again!
