### ISSUE TITLE
Closed tasks should be displayed by default in boards and dashboard

### ISSUE THREAD

**Issue by vincowl** [kanboard/kanboard#4100]
### Actual behaviour

- In a project's board, only opened tasks are displayed by default
- In a project's board, default filter resets filters to open tasks 
- In a project's board, 'My tasks' shows only open tasks
- In the dashboard, closed tasks are not counted.

### Expected behaviour
- In a project's board, opened and closed tasks should be displayed by default in order to have a complete view. Pre-existing filters are already defined to filter open or closed tasks
- In a project's board, default filter should resets filters to open and closed tasks to be compliant to the above statement.
- In a project's board, 'My tasks' should show open and closed tasks. This leads the previous statement too. It is due to the fact that I use several columns ("New", "To be processed", "In progress", "Done"). The "Done" column should contain closed tasks.
- In the dashboard, closed tasks should be added to open ones (especially in the previous "Done" column)

### Configuration

- Kanboard version: 1.2.6
- Database type and version: sqlite 3.24.0
- PHP version: 7.2.10
- OS: MacOS Mojave (10.14.1) 
- Browser: Safari 12.0.1

**Comment by creecros** [comment]
Personally, I would disagree with this.

**Comment by vincowl** [comment]
So, why not adding a "status:all" default filter and an option in kanboard's setup to choose a default filter to apply instead of forcing the actual behavior ? Several issues seems to have a close need as this one : #4076, #3694, #3581, #3413, #3225
Maybe a bit more explanation on this point of view ?

**Comment by creecros** [comment]
Sorry, not meaning offense, just a point of view. 

My point of view: Closed tasks are closed, so they should be hidden, by default.

**Comment by creecros** [comment]
I agree with choice. Just not as a default. I could go through a lot of reason as to why that would suck, "for me", but better to just say it would pose an issue.

**Comment by rafacamargo123** [comment]
I thing this should be configurable, then. We use one project per team and we're currently running for over 2 years. We have exactly 2648 closed tasks and showing all tasks takes several seconds. Maybe putting this setting as a constant in config.php would be easier to implement and will solve your issue without messing with everyone's kanboard

**Comment by creecros** [comment]
probably simpler to just use the configModel.

**Comment by loonies** [comment]
Why are you closing task if you want them to remain visible i.e. open? Doesn't make sense.

**Comment by vincowl** [comment]
@loonies Where is it stated as a universal rule that visible task closely means being open ????? THAT is a non sense... Github is a public area where different opinions may be expressed. Being condescendant does not help at all to make things go further... Kanban is just a method that can fit various workflows or way of conceiving work traceability, not a set of fixed rules that fit one point of view. I understand and can conceive that this is not a common use... Ok, fine ! You disagree... Fine too ! I just don't understand how this comment helps...

**Comment by vincowl** [comment]
I think this issue may be closed since solutions are foreseen in the related PR.

**Comment by loonies** [comment]
I was only wondering why are you closing tasks if you want them on the board. Simply keep them open.

For example, our workflow is to close tasks in the Done column after predefined time frame using an automated task. This serves as a grace period if we need to follow up on a card for whatever reason. If there are no followups we don't want to clutter the board with unnecessary information. In case much later down the road we need to refer back to some information or follow up it's easy to pull a card via `status:closed search term` filter.
