### ISSUE TITLE
Can't connect to Kanboard self hosted with Android apps

### ISSUE THREAD

**Issue by jkdtoby** [kanboard/kanboard#4109]
Hi,
I'm trying 3 android apps to connect kanboard.
When I try to connect my Kanboard apps on Android :
- KanBoard
- KanboardMobile
- Kandroid
nothing happens

Connect with app Kanboard, I have an "error" message.
When I'm using KanboardMobile the screen is white and at the top of the header I see the KB logo.
The connection with the kandroid brings no result, no error nothing.

 Configuration of the hosting and Kanboard self hosted
    Kanboard version: 1.2.7
    Database type and version: sqlite 3.20.1
    PHP version: 7.2.13
    OS: Linux 3.16.0-uiabi1-infong-amd64

And I use Android 8.0 Samsung Galaxy S7egde

Can you help me please?

**Comment by Cyboulette** [comment]
Hello,

The "KanboardMobile" application try to connect only in HTTPS, please check if your web application is on HTTPS.
If you don't see any projects/boards when you are logged, please check that you have assigned projects on the web application. On this mobile application it's impossible to create new projects.

**Comment by jkdtoby** [comment]
Hi,

yes I have projects and HTTPS is on.

and in htaccess:
<IfModule mod_setenvif.c>
    SetEnvIf Authorization .+ HTTPS_AUTHORIZATION=$0
</IfModule>

and in config.default.php
// Set to false to allow self-signed certificates
define('HTTP_VERIFY_SSL_CERTIFICATE', true);

**Comment by jkdtoby** [comment]
Hello,

what settings(htaccess; config.default.php) need to be made to make it work?
For 
- KanBoard
- KanboardMobile
- Kandroid

Can you help me please?

**Comment by Cyboulette** [comment]
Hello,

First : your config file need to be named "config.php" in order to be enabled.

If you don't have a valid SSL cert
// Set to false to allow self-signed certificates
define('HTTP_VERIFY_SSL_CERTIFICATE', true);

It's hosted online ?

**Comment by jkdtoby** [comment]
Hello,

after renaming the config file, came the error on my website.
Internal Error: SQLSTATE[HY000] [1044] Access denied for user 'dbo123456'@'%' to database 'dbo123456'

And I changed SSL cert
// Set to false to allow self-signed certificates
define('HTTP_VERIFY_SSL_CERTIFICATE', false);

The same situation like before.
Yes, is hosted online.

The response(error) from application KanBoard(android) is to fast.

Can you tell me, which all settings in relevant files are necessary to be made to make it work?
 - which URL in mobile application is useful?
          - with https:// ..... jsonrpc.php
          - or with the same from web application?

**Comment by Cyboulette** [comment]
KanboardMobile use the https /jsonrpc.php file.

If you can send the link I can try to Connect with debug.

Check in php/apache logs in order to know more about the sql error.

**Comment by jkdtoby** [comment]
Hello,

because of the SQL error, it was my mistake. Wrong settings. With config file on my website it works.

The same situation like before.

http://tartatschny.de/kanboard/?controller

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
