### ISSUE TITLE
Incorrect link markdown causes task to hang

### ISSUE THREAD

**Issue by NYSAG-GS** [kanboard/kanboard#4120]
### Actual behaviour

When I use the incorrect link markdown e.g. (My link title)[https://kanboard.org/] in a task's description or comment, opening the task hangs.

### Expected behaviour

Literal rendering of the incorrect markdown (My link title)[https://kanboard.org/]

### Steps to reproduce
1. Add a new task
2. Add (My link title)[https://kanboard.org/] in the task description
3. Save
4. Clicking on the task now hangs

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by rafacamargo123** [comment]
What version of kanboard are you using? I tried and could not reproduce your issue...
If I hover the description preview:
![image](https://user-images.githubusercontent.com/12586009/50945609-9f24cc80-147c-11e9-8773-873f597ead3c.png)
If I click on the task:
![captura de tela 2019-01-10 as 02 10 06](https://user-images.githubusercontent.com/12586009/50945803-94b70280-147d-11e9-8c5a-eea71fa997b2.png)
If I click on the task's edit button:
![captura de tela 2019-01-10 as 02 11 26](https://user-images.githubusercontent.com/12586009/50945791-88cb4080-147d-11e9-8182-6efe859842bf.png)

**Comment by NYSAG-GS** [comment]
Thanks for taking a look @rafacamargo123. Version shows up as:

Application version: master.efd64d842d82404612baef58d9debe1af7515a66
Docker kanboard:latest, up for 5 months.

**Comment by fguillot** [comment]
Please, update your Kanboard instance to version 1.2.8
