### ISSUE TITLE
Add HTTP_PROXY_EXCEPTION

### ISSUE THREAD

**Issue by mildis** [kanboard/kanboard#4125]
### Actual behavior
HTTP_PROXY is set for Slack plugin to connect to Slack servers.
However Oauth plugin should not use the proxy for its outbound connection thus failing to connect to the OIDC server.

This is due to the lack of setting allowing to exclude domains for proxy connections
Adding a setting like HTTP_PROXY_EXCEPTION accepting values like "internal.org" which should exclude proxy settings for all connections to *.internal.org.

### Configuration

- Kanboard version: 1.2.7
- PHP version: 7.0.33
- OS: Debian 9

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) (https://kanboard.discourse.group) for discussions and feature requests, the bug tracker is reserved only for bugs.
