### ISSUE TITLE
URL for a board

### ISSUE THREAD

**Issue by plyaskin** [kanboard/kanboard#4128]
Hi guys!

Could you let me know how I can show my board without header, footer etc? Which the URL I need to use?

**Comment by rafacamargo123** [comment]
You can do so enabling public access:

Configure this project > Public access > enable public access

A "Public link" will be generated. This is a read only view to your board, anyone with this link can view it. At this read only view there are no headers and other stuff, only the board and the tasks. But it will be read only. 

If you have any further questions you can ask questions on the [Forum](https://kanboard.discourse.group/)
