### ISSUE TITLE
Non-existent "doc" folder listed in Security guide

### ISSUE THREAD

**Issue by johnwoltman** [kanboard/kanboard#4136]
### Actual behaviour

When following the security guide (https://docs.kanboard.org/en/latest/admin_guide/security.html) so that I can install kanboard into ``/opt/kanboard`` and symlink it into document root, creating a symlink to ``/opt/kanboard/doc`` fails because the ``doc`` folder does not exist.

### Need to update docs

I can remove the reference to the ``doc`` folder from the security guide and submit a pull request if needed.

- Kanboard version: 1.2.7
- Database type and version: sqlite
- PHP version: 7.2.14
- OS: CentOS 7
- Browser: n/a

**Comment by fguillot** [comment]
The doc has been updated. Thanks
