### ISSUE TITLE
Improve Date Emphasis and Due Alerting

### ISSUE THREAD

**Issue by sammdu** [kanboard/kanboard#4142]
This issue is:
- Feature request
- Improvement

Hi,

I have read the [FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-are-you-not-developing-my-feature-request) and understand the efforts developers to put in to maintaining this project, and I do **not** assume my feature/improvement request will be included. My suggestion is in hopes to improve the usability of this software.

### 1. Emphasis on Due Dates
I propose the ability to enlarge the font size and otherwise emphasize the `Due Date` of tasks (through an option in the settings maybe).
A Kanban's porpose is to help increase productivity of an individual or a team; and with any project the due dates are often one of the most important factors. The current design has the due date in one small corner that's a bit difficult to pay attention to.
![image](https://user-images.githubusercontent.com/10665890/52927328-ed44af80-3307-11e9-939c-cddd29be53b1.png)
I did a quick mockup in GIMP of what I think is a better option: increase the contrast of the **Due Date** text, and enlarge it.
![image](https://user-images.githubusercontent.com/10665890/52927379-2e3cc400-3308-11e9-99c5-8205cf910300.png)
I have also increased the size of the title, for the same reason; but that's more trivial.
And please excuse the crudeness of this mockup, but it's just a demonstration of an idea.

### 2. Flash Task Near Due Date
I also think it's a good idea to have a task be flashing/blinking when it's near the due date, to capture maximum attention, in order to assist with meeting deadlines. It might also help to have the task turn red at the same time. I got this idea from peeking into a McDonald's counter and seeing the order queue screen in action. Orders that have (seemingly) been waiting for a long time start to blink to capture the staff's attention.
If flashing/blinking the whole task card is too obnoxious, maybe have a red dot appear at one corner and start blinking that red dot. Of course make this an option that people can turn on and off based on their taste.
![image](https://user-images.githubusercontent.com/10665890/52927697-ca1aff80-3309-11e9-899f-6b287b40a3ec.png)
* * *
Lastly I want to say, I really enjoy this project, it has helped with my productivity a lot and continue to help me organize tasks. I proposed these ideas in hopes of making this project even better.

Thanks!

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) for open discussions, suggestions and feature requests. **This bug tracker is reserved only for bugs**.

**Comment by sammdu** [comment]
Thank you for the advice, I will close the issue.
