### ISSUE TITLE
Mention HSTS header usage in installation

### ISSUE THREAD

**Issue by slavkoja** [kanboard/kanboard#4144]
I install kanboard on my localhost to see it in real. After i access it, all works. But HSTS header forces all my other custom/development webapps (accessible only from localhost, but via hostname) to use HTTPS, which some of them have not configured. They becomes unavailable from browser and it took some time, until i noticed why they stops to work. 

Another possible problem, which i can see, is when someone install kanban on site with not trusted certificate (i heavy use own CAs). Not trusted certificates, while fully valid, are required to confirm, but HSTS unconditionally requires trusted certificate (at least with Firefox), then confirmation is not possible.

In #278 there was discussion about HSTS header from PHP. I don't want to discuss it again, because it is easy to remove/change it (at least from nginx). But i think, that users/admins have to be warned about this and that HSTS generation have to be mentioned somewhere in installation/requirements section, because while this security header can be very useful in public Internet, it can break existing setup in some cases.

regards

**Comment by fguillot** [comment]
Feel free to update the docs: https://github.com/kanboard/documentation

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.13/developer_guide/faq.html).
