### ISSUE TITLE
Problem when try attach a pdf.

### ISSUE THREAD

**Issue by JAugusto42** [kanboard/kanboard#4145]
### Actual behaviour
SyntaxError: JSON.parse: Unexpect character at line 1 column 1 of the JSON data when try a upload a pdf file.

### Expected behaviour
Upload a pdf file.

### Steps to reproduce
try a upload a pdf file on a task

### Configuration

- Kanboard version: 1.2.6
- Database type and version: posgres 9.4.12
- PHP version: 5.6.30
- OS: Debian 8 linux 3.16.0-4-amd64
- Browser: firefox

**Comment by fguillot** [comment]
I'm not able to reproduce your issue. You should provide more details (screenshots, logs, and installed plugins).

**Comment by JAugusto42** [comment]
![console](https://user-images.githubusercontent.com/29546825/53173085-b1d70900-35c5-11e9-9aed-b161ed938ef3.PNG)
![upload-pdf-txt](https://user-images.githubusercontent.com/29546825/53173086-b26f9f80-35c5-11e9-87c5-7d5b9d9d3ed9.PNG)

**Comment by fguillot** [comment]
Can you take a look to the network tab? What are the response status code and the response body when you try to upload the files?

**Comment by JAugusto42** [comment]
We solved the problem, we had an Apache (where we did the limit change) and had a nginx (load balance) where we did not make the change, so the error... Thanks for the help and support.
