### ISSUE TITLE
Adding images to tasks comments

### ISSUE THREAD

**Issue by AXeL-dev** [kanboard/kanboard#4146]
This issue is:

- [ ] Bug report
- [x] Feature request
- [ ] Improvement

### Actual behaviour
In tasks view, if i want to link an image to a comment, the only way to add the image is to add it to attachments then take note of the image name in my comment.
The "likely issue" here is if i upload many images in the attachments section it's hard to find the image by its name & know which image is related to which comment.

### Suggestion 1
An easy solution could be to add a `copy link to clipboard` in attachment options:

![screenshot 2019-02-21 20-23-33](https://user-images.githubusercontent.com/30635693/53195776-4feec180-360e-11e9-9654-4965911479f9.png)

Then use the `![image](url)` markdown to include the image in the comment, as below:

![screenshot 2019-02-21 20-03-26](https://user-images.githubusercontent.com/30635693/53194502-65aeb780-360b-11e9-96fa-0d87651d64b3.png)

### Suggestion 2
A better way could be to add an image upload feature near to markdown editor:

![screenshot 2019-02-21 20-29-23](https://user-images.githubusercontent.com/30635693/53196083-0488e300-360f-11e9-9575-975161529505.png)

Then upload the image using ajax & automatically add it to attachments after comment save.

### Thanks
I really liked the way kanboard is coded, the source code is so clean & well designed :+1: .

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) for open discussions, suggestions and feature requests. **This bug tracker is reserved only for bugs**.
