### ISSUE TITLE
Webhooks sends an empty request

### ISSUE THREAD

**Issue by jiu4ep** [kanboard/kanboard#4149]
Hello!
I ran into a problem, when specifying a webhook-url and trying to write a POST request with change of the board, I receive an empty POST request. 

Here is a handler that tries to write the entire request.
Maybe I'm doing something wrong?

`<?php
$data = var_dump($_POST);
file_put_contents('test.txt', $data, FILE_APPEND);
?>`

**Comment by fguillot** [comment]
```php
file_put_contents('/tmp/webhook.json', file_get_contents('php://input'));
```

Please, use the forum instead.
