### ISSUE TITLE
[enhancement] permanently or temporarily highlight permalinked comments

### ISSUE THREAD

**Issue by lathan** [kanboard/kanboard#415]
When a comment in a task is linked ([like this](http://demo.kanboard.net/?controller=task&action=show&task_id=1#comment-3)), highlight it (like on mouse hover) so it is obvious which comment was linked, even if the page isn't large enough to display the linked comment at the top.

The "temporary" highlight could look like [stackoverflow's](http://stackoverflow.com/questions/1812926/i-am-looking-for-tips-for-learning-vim-or-emacs-the-smart-way/1815372#1815372). I personally prefer the permanent highlight.

**Comment by fguillot** [comment]
This is now available in the development branch. (Yes, after all this time, finally!)

**Comment by fguillot** [comment]
Available in v1.0.39
