### ISSUE TITLE
Since Kanboard v1.2.8, the plugin directory is disabled by default for security reasons.

### ISSUE THREAD

**Issue by gerroon** [kanboard/kanboard#4150]
HI

It is cool that this is disabled but I do not understand what the document is talkign about. Is it saying that one can never install plugins anymore or is it saying that it is disabled but can be enabled somehow?

I have enabled this and still cant install plugins.
`config.default.php:define('PLUGIN_INSTALLER', true);`

I have been using this for a while without any issues. This just popped up in 1.2.8

thanks

**Comment by fguillot** [comment]
The answers to your questions are available on this page: https://docs.kanboard.org/en/1.2.8/admin_guide/plugins.html

If you have further questions, please use the forum: https://kanboard.discourse.group/.

**Comment by gerroon** [comment]
Thanks but actually not. That page is not clear about it, it just says it is disabled. In any case feel free to make it more concise for layman like me, or not.

thanks
