### ISSUE TITLE
Letters stop being sent every time after running crontab

### ISSUE THREAD

**Issue by 0anion0** [kanboard/kanboard#4152]
### Actual behaviour
I am using the Docker version of Kanboard on Synology NAS, use worker and beanstalk.
At night, after starting the task **"crond[15]: USER nginx pid 213 cmd cd /var/www/app && ./cli cronjob >/dev/null 2>&1"**, the letters cease to be sent.

After restarting the container everything is restored.
What could be the problem?

### Logs
>2019-02-27T03:00:00.708295228Z  crond[15]: USER nginx pid 213 cmd cd /var/www/app && ./cli cronjob >/dev/null 2>&1
>2019-02-27T03:00:00.708688663Z  crond[15]: USER root pid 214 cmd run-parts /etc/periodic/15min
>2019-02-27T03:00:00.708743260Z  crond[15]: USER root pid 215 cmd run-parts /etc/periodic/hourly
>2019-02-27T03:00:04.962695473Z  [27-Feb-2019 08:00:04 Asia/Yekaterinburg] PHP Warning:  Error while sending QUERY packet. PID=14 in /var/www/app/libs/picodb/lib/PicoDb/StatementHandler.php on line 240
>2019-02-27T03:00:04.963094636Z  [27-Feb-2019 08:00:04 Asia/Yekaterinburg] [error] Kanboard\Core\Queue\JobHandler::executeJob: Error during job execution: SQL Error: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
>2019-02-27T03:00:04.963196686Z  [27-Feb-2019 08:00:04 Asia/Yekaterinburg] [error] Kanboard\Core\Queue\JobHandler::executeJob => {"class":"Kanboard\\Job\\EmailJob","params":["hiddenmail","hiddentext"]}
>2019-02-27T03:00:05.039934215Z  [27-Feb-2019 08:00:05 Asia/Yekaterinburg] [error] Kanboard\Core\Queue\JobHandler::executeJob: Error during job execution: SQL Error: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
>2019-02-27T03:00:05.040056460Z  [27-Feb-2019 08:00:05 Asia/Yekaterinburg] [error] Kanboard\Core\Queue\JobHandler::executeJob => {"class":"Kanboard\\Job\\EmailJob","params":["hiddenmail","hiddentext"]}

### Configuration
- Docker: kanboard/kanboard:master
- Kanboard version: 1.2.7
- Database type and version: 10.3.7-MariaDB
- PHP version: 7.2.13
- OS: Alpine Linux 3.8
- Browser: Chrome/72.0.3626.

**Comment by fguillot** [comment]
There is more details about the error `SQLSTATE[HY000]: General error: 2006 MySQL server has gone away` in the MySQL documention: https://dev.mysql.com/doc/refman/8.0/en/gone-away.html

**Comment by fguillot** [comment]
This feature is no longer supported.

**Comment by rautamiekka** [comment]
Why no longer supported ?
