### ISSUE TITLE
PHP Notice:  Undefined variable: user

### ISSUE THREAD

**Issue by fredl99** [kanboard/kanboard#4159]
Hi,

At first I thought it's an issue of the `signal-cli` plugin because the error message was referring to it. I couldn't find any issue like that over there and signal-cli itself works fine. (i.e. can register devices, send&receive, etc.)

Then I saw the same message in conjunction with `Nebula`. So my conclusion is that the cause _could_ be somewhere in kanboard as their common parent. Does anybody know how to track the the loss of that variable?

These message(s) are repeated over and over:
```
PHP Notice:  Undefined variable: user in 
/var/www/virtual/c5c53fb0/sites/kanboard/plugins/Nebula/Template/layout/header/creation_dropdown.php on line 39
PHP Notice:  Undefined variable: user in /var/www/virtual/c5c53fb0/sites/kanboard/plugins/Signal/Notification/Signal.php on line 80
```
Nebula looks fine, but signal-cli doesn't send out anything.

I installed kanboard as well as all plugins via git, if that matters. The "About" page says:

> Version: master.unknown_revision
> PHP Version: 5.6.6 ###-> also tried PHP Version 7.1.27 but it didn't help
> PHP SAPI: cgi-fcgi
> OS Version: Linux 2.6.32-696.18.7.el6.x86_64
> Datenbanktreiber: sqlite
> Datenbank Version: 3.8.7.2

Any ideas where I should look at?
Many thanks in advance!

**Comment by fguillot** [comment]
This is most likely issues in these plugins.

For example, in the Signal plugin the variable `$user` is used but not declared anywhere, see https://github.com/stratmaster/kanboard-plugin-signal/blob/master/Notification/Signal.php#L79-L86

Probably a similar issue for Nebula plugin. `$user` is not passed to the template: https://github.com/kanboard/kanboard/blob/master/app/Template/header.php#L8-L12 and https://github.com/kenlog/Nebula/blob/master/Template/layout/header/creation_dropdown.php#L39

You should report these issues to the plugin authors.

**Comment by fredl99** [comment]
Many thanks for your reply!
In fact I really had doubts that the problem is coming from kanboard. That's why I wrote "could be" in italic letters. You're right, I will report it there.
