### ISSUE TITLE
Calendar drag and drop not always working 

### ISSUE THREAD

**Issue by prema770** [kanboard/kanboard#4160]
### Actual behaviour
I'm a new happy user.  The calendar feature is very useful. Can't drag some tasks 
### Expected behaviour

Expect to be able to drag any task to a new date 

### Steps to reproduce

Dashboard -> Calendar

### Configuration

- Kanboard version:1.2.8
- Database type and version: mysql5x
- PHP version: 5x

- Browser: - OS: Latest Chrome, Linux Mint 

Happy to do any tests and supply any information / screenshots needed 
Thanks for an amazing tool :-)

**Comment by prema770** [comment]
Updated information 

Tags management
Link labels
Currency rates
Integrations
Webhooks
API
Customizer
Calendar settings
About
Official website: https://kanboard.org/
Author: Frédéric Guillot (contributors)
License: MIT
Configuration
Application version: 1.2.8
PHP version: 7.1.27
PHP SAPI: litespeed
OS version: Linux 3.10.0-714.10.2.lve1.5.17.el7.x86_64
Database driver: mysql
Database version: 5.7.25-cll-lve
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

**Comment by fguillot** [comment]
The bug tracker for the calendar is there: https://github.com/kanboard/plugin-calendar/issues
