### ISSUE TITLE
Warning: htmlspecialchars() expects parameter 1 to be string, array given in [...]\htdocs\kanboard\app\Helper\TextHelper.php on line 24

### ISSUE THREAD

**Issue by PhineasClick** [kanboard/kanboard#4161]
When using Tags, for each tag the Error Message is shown in the opened Task:

Warning: htmlspecialchars() expects parameter 1 to be string, array given in [...]\htdocs\kanboard\app\Helper\TextHelper.php on line 24

![grafik](https://user-images.githubusercontent.com/10465238/54598538-fcb73580-4a38-11e9-8671-71a0aeb7355e.png)

    Application version: 1.2.8
    PHP version: 5.6.24
    PHP SAPI: apache2handler
    OS version: Windows NT 6.2
    Database driver: sqlite
    Database version: 3.8.10.2
    Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

**Comment by fguillot** [comment]
What plugins are installed?

**Comment by PhineasClick** [comment]
Blueboard 0.0.1
Calendar 1.1.0
Gantt 1.0.2
Group Assign 0.0.1
Relationgraph 0.1.3
TimeTrackingEditor 1.0.21
Wiki 0.2.5

**Comment by PhineasClick** [comment]
Updating the Plugins Gantt, Group Assign and Wiki fixed the Probelm. I'm not sure which one caused the Problem in the first place.

Thanks for the quick response.
