### ISSUE TITLE
Prevent user from change their role and losing admin access to the project

### ISSUE THREAD

**Issue by wiltonsr** [kanboard/kanboard#4162]
### Actual behaviour
When a user is the only Project Manager and he change his role, this project can no longer be edited by anyone other than an administrator.

### Expected behaviour

Prevent the user to change his role when it's the only Project Manager.

### Steps to reproduce
- Create a project
- Go to Configure this project
- Permissions
- Change user's role to Member or Viewer
- Press F5

### Screenshots

![image](https://user-images.githubusercontent.com/5395065/54771648-7c353800-4be4-11e9-8fe5-3050030446c9.png)

### Configuration

- Kanboard version: any
- Database type and version: any
- PHP version: any
- OS: any
- Browser: any

**Comment by aalmir** [comment]
I had the same Problem.

**Comment by fguillot** [comment]
It should be fixed in recent version.
