### ISSUE TITLE
Problem when creating a project with jsonrpc API user

### ISSUE THREAD

**Issue by wiltonsr** [kanboard/kanboard#4170]
### Actual behaviour

I'm using api python client and when I create an project to another user with API using the jsonrpc user the row is inserted in `projects` table correctly, but I noticed that the `project_has_users` table doesnt change. Because of this the user passed on creation can't access the project.

### Expected behaviour

All tables are updated correctly and the user has access to the project

### Steps to reproduce

- Run this on python
```python
from kanboard import Kanboard
# Use your own token api
kb = Kanboard("http://localhost/jsonrpc.php", "jsonrpc", "api-token")
# Use a different user from admin
kb.create_project(owner_id=2, name='New Project')
```
### Screenshots
- The project will be correctly created and user assigned to it
![image](https://user-images.githubusercontent.com/5395065/55640720-948b8200-57a2-11e9-93fc-ebeb0cdc792e.png)
- But the User can't access the project
![image](https://user-images.githubusercontent.com/5395065/55640823-c8ff3e00-57a2-11e9-9193-722bcd2fb652.png)

### Configuration

- Application version: 1.2.8
- PHP version: 7.2.14
- PHP SAPI: fpm-fcgi
- OS version: Linux 5.0.4-arch1-1-ARCH
- Database driver: sqlite
- Database version: 3.26.0
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by fguillot** [comment]
You need to add the permission for the user if you use the system user "jsonrpc":

```python
kb.add_project_user(project_id=5, user_id=2, role='project-manager');
```

**Comment by wiltonsr** [comment]
Thanks to reply @fguillot 

It would be nice to add a note about this need in the API documentation, as this is not necessary once you create a project using the user's own API token.

**Comment by fguillot** [comment]
The documentation has been updated https://docs.kanboard.org/en/latest/api/examples.html#example-with-python

Contributions are accepted: https://github.com/kanboard/documentation
