### ISSUE TITLE
[Question] Regex Validator

### ISSUE THREAD

**Issue by btd1337** [kanboard/kanboard#4173]
I created a validator to Username in the signup using:

`<?= $this->form->text('username', $values, $errors, array('autofocus', 'required', 'minlength="4"', 'maxlength="191"', 'pattern="^[a-zA-Z][a-zA-Z0-9-_\.]{3,191}$"')) ?>`

My question is: How create a validator with a custom message to this regex pattern?

Thanks in advance!

Reference: https://github.com/btd1337/kanboard/commit/91bad80ba4e9425a031931cba9ae363f4cac7e65

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) for open discussions, suggestions and feature requests. **This bug tracker is reserved only for bugs**.
