### ISSUE TITLE
`exec format error` on ARM

### ISSUE THREAD

**Issue by ModischFabrications** [kanboard/kanboard#4175]
### Actual behaviour

Running Kanboard as a docker image on Raspberry Pi 3 (ARMv71) crashes while starting up with `standard_init_linux.go:190: exec user process caused "exec format error"`

### Expected behaviour

A running instance (started from a multiarchitecture build on docker).

### Steps to reproduce

Run `docker run --name kanboard -p 9020:80 -t kanboard/kanboard` on a Raspberry Pi 3.

### Screenshots

--

### Logs
```
pi@modischpi:~ $ docker run --name kanboard -p 9020:80 -t kanboard/kanboard
standard_init_linux.go:190: exec user process caused "exec format error"
```

Architecture:
```
pi@modischpi:~ $ uname -a
Linux modischpi 4.19.32-v7+ #1210 SMP Tue Apr 2 14:07:04 BST 2019 armv7l GNU/Linux
```

### Configuration

- Kanboard version:  `kanboard/kanboard:latest`
- Database type and version: --
- PHP version: --
- OS: --
- Browser: --

**Comment by ModischFabrications** [comment]
This is likely due to a x86 only image on Docker Hub. Look for `multi-arch` as a keyword, this is an official blogpost for it: https://blog.docker.com/2017/11/multi-arch-all-the-things/

**Comment by fguillot** [comment]
There is no official Docker images for ARM architectures. Contributions are welcome. If you want to give a shot, the Dockerfile is there: https://github.com/kanboard/kanboard/blob/master/Dockerfile
