### ISSUE TITLE
Downloaded attachment seems in bad encoding

### ISSUE THREAD

**Issue by percyboy** [kanboard/kanboard#4179]
### Actual behaviour

I uploaded a file (eg. docx/zip) as attachment and then downloaded it from kanboard. When I tried to open it, I found it seemed in broken format. 

(If it is docx file, MS Word will tell you the file is broken and may recover and display it, though. )

I've checked the uploaded file in the data folder on server and it was the same as the one I uploaded and, of cource, can be opened without any error nor warning. So the bug should be in the downloading process, I guess.

I've also compared the original file and the downloaded one. They seemed in difference encodings (aka. charsets?). I guess the downloading action gave a bad encoding/charset for the file stream.

### Steps to reproduce

1. upload a file (eg. docx/zip) as attachment.
2. download it.
3. try to open it.

### Configuration

- Kanboard version: I'm using the most recent docker version of kanboard.
- Database type and version:
- PHP version:
- OS:
- Browser: chrome

**Comment by rgamec** [comment]
I've just tried to replicate this (using Firefox and Kanboard 1.2.6 running under IIS on Windows Server 2012), but haven't been able to.

Can you compare the downloaded file based on its md5 file checksum, with the file that was uploaded? This will show if the files are a byte-for-byte match or if somehow there was some corruption. Do you see the same issue with other browsers?

I will try and replicate the issue again later using Chrome and the Docker image.

**Comment by percyboy** [comment]
thanks for reply!

I compared the two files by WinMD5Fee and got two different MD5 checksum values.

I've just noticed the sizes of the two files are slightly different: the downloaded one has 3 bytes more than the original one. So I guess this is related to the UTF8 BOM header.

I tried to open the downloaded file and removed the first 3 bytes of it, and then the MD5 became the same! So it is confirmed that the downloaded file was wrongly added UTF8 BOM header.

**Comment by rafacamargo123** [comment]
Are you still experiencing this issue? I’ve checked every file from git repository on the last 300 commits from master (from **96dd20c0** - Mon May 13 23:12:19 2019 -0700 to **f6b1ac83** - Wed Nov 29 10:40:29 2017 -0800) and the only file that had a UTF8 BOM header was                                           ./doc/cs_CZ/index.markdown, but only until commit ac11220a, being removed on 0b306fa6.

If you are still experiencing this, can you attach to your container’s bash or sh (`docker exec -it <CONTAINER_ID> /bin/sh`) and run a `grep -rl $'\xEF\xBB\xBF'` on the kanboard dir? (Probably `/var/www/app`)
You may exclude the `data` dir from grep but I think it’s important to search on plugins aswell to find out if it is a plugin issue.

**Comment by percyboy** [comment]
It works! After running `grep -rl $'\xEF\xBB\xBF' . ` , I finally found the file with UTF8 BOM. It's the `config.php`, which was created by myself. Maybe adding a configuration tip to the setup document will be helpful for others.

Thank you very much!
