### ISSUE TITLE
Failed opening required 'vendor/autoload.php' after update

### ISSUE THREAD

**Issue by gurify** [kanboard/kanboard#418]
Just updated to the latest version from master, error 500 is thrown.
Switched display_errors = On in php.ini and this is the message:

Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /var/zpanel/hostdata/zadmin/public_html/XXXXXXXXXXXX/app/common.php on line 3 Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/zpanel/hostdata/zadmin/public_html/XXXXXXXXXX/app/common.php on line 3

**Comment by LawanyaD** [comment]
I'm not able to find "composer install" file

**Comment by stinnux** [comment]
You need to install composer from www.getcomposer.org

**Comment by LawanyaD** [comment]
Yes I installed then next What I do

**Comment by stinnux** [comment]
After installation you should have a composer.phar file. You can either rename it or simply run it by using ``` php composer.phar install```

**Comment by LawanyaD** [comment]
I don't know about  php composer.phar install
Is  "php composer.phar install" is a tool????

*Regards,*

Lavanya D
Cogzidel Technologies Private Limited,
www.cogzidel.com

**CONFIDENTIAL NOTICE**

This e-mail and any files transmitted with it may contain PRIVILEGED or
CONFIDENTIAL information and may be read or used only by the intended
recipient. If you are not the intended recipient of the e-mail or any of
its attachments, please be advised that you have received this e-mail in
error and that any use, dissemination, distribution, forwarding, printing,
or copying of this e-mail or any attached files is strictly prohibited. If
you have received this e-mail in error, please immediately purge it and all
attachments and notify the sender by reply e-mail.

**Comment by stinnux** [comment]
you just execute that on the command line, in the directory where you checked out kanboard.
