### ISSUE TITLE
Undefined index: category_color_id

### ISSUE THREAD

**Issue by Skyrid3r** [kanboard/kanboard#4189]
As of recently, the error `Undefined index: category_color_id` popped up in the error logs quite often on NGINX (both PHP 7.1 FPM and PHP 7.2 FPM) on Ubuntu 18.04, using the latest update 1.2.9. It was working just fine several weeks ago, but blank pages started showing up whenever you want to add/edit existing tasks, the (dropdown) menu's barely works on chrome but randomly works on firefox.  

Oddly enough, a logout/login fixes it for the time being, but I'd like to know where the issue itself is coming from.. Any idea?

![image](https://user-images.githubusercontent.com/6794064/57659529-ed8cd800-75e2-11e9-8f47-110822e64928.png)

The exact error is:

> PHP message: PHP Notice:  Undefined index: category_color_id in /var/www/xx/xx/xx.xx.xx/app/Template/task_list/task_details.php on line 7" while reading response header from upstream, client: xxxxx, server: xxxxx.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm-sock:", host: "xxxx.com"

**Comment by rafacamargo123** [comment]
I've tried many times and could not reproduce the error. Tried every page that calls this template task_list/task_details, but still could not reproduce.
Can you post a print/copy paste of your configuration page, like this:


Also, if you can easily reproduce this error, please enable debugging, reproduce the error, then disable the debug (to prevent log file to grow too much) then attach here?

To enable debug, on config.php, set the following settings:

```php
// Enable/Disable debug
define('DEBUG',  true);

// Available log drivers: syslog, stderr, stdout, system or file
define('LOG_DRIVER', 'file');

// Log filename if the log driver is "file"
define('LOG_FILE', DATA_DIR.DIRECTORY_SEPARATOR.'debug.log');
```

**Comment by creecros** [comment]
Have you installed any plug-ins recently?

**Comment by creecros** [comment]
Well I see group assign is installed, is it up to date? If not, it overrides the taskfinder, and an old Tasker finder won't have category color id, so it would definitely brain far somewhere.

**Comment by Skyrid3r** [comment]
@creecros Thank you!

Apparently I was using Group assignments 0.0.1, just updated it to the latest version! ^_^, can't thank you enough! :D
