### ISSUE TITLE
Feature Request: automatic action due date change colum

### ISSUE THREAD

**Issue by colttt** [kanboard/kanboard#4193]
Hello,

it would be really nice if you add an action like 

> Assign automatically a the column when due date is expired

**Comment by rafacamargo123** [comment]
There is a plugin available for that on kanboard plugin directory:

Move cards to specific columns when due date passed

https://github.com/dmorlitz/kanboard-TaskMoveOnDueDate

**Comment by fguillot** [comment]
For feature requests, please use the forum: https://kanboard.discourse.group/
