### ISSUE TITLE
SQL error upgrading from 1.0.47 to 1.2.9

### ISSUE THREAD

**Issue by jbaubree** [kanboard/kanboard#4195]
Hi,

### Actual behaviour

I have just upgraded kanboard to the last version. When i did it following doc,
i had an error like : 

Internal Error: Unable to run SQL migrations: Running migration column 'color_id' already exists in ALTER TABLE in function version_132.

### Expected behaviour

to fix issue, maybe use 'IF NOT EXISTS' in ADD COLUMN queries like:
function version_132(PDO $pdo)
{
$pdo->exec('ALTER TABLE `project_has_categories` ADD COLUMN `color_id` VARCHAR(50) DEFAULT NULL');
}

I have actually solved the issue by commenting error function to end my upgrade.

### Configuration

- Kanboard version: 1.0.47
- Database type and version: MySQL 5.5.62
- PHP version: 5.6.39
- OS: Ubuntu 14.04.1
- Browser: Chrome

**Comment by fguillot** [comment]
For installation issues, please use the forum: https://kanboard.discourse.group/
