### ISSUE TITLE
Time spent on sub tasks should not be measured in tenths of an hour

### ISSUE THREAD

**Issue by ChangePlaces** [kanboard/kanboard#4200]
### Actual behaviour
The timer for subtasks measures time in tenths of an hour e.g. "1.66h spent".

### Expected behaviour
Time to be measured on base 60 if measuring in hours
e.g. 1h 40m

### Steps to reproduce
Start a sub task timer and let it run for more than 15 mins

- Kanboard version: 1.29

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests, improvements or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html

**Comment by ChangePlaces** [comment]
It is a bug report. Measuring time in a base 10 system is a incorrect, thus a bug.

**Comment by BlueTeck** [comment]
Decimal time is possible and widely used. https://en.wikipedia.org/wiki/Decimal_time
