### ISSUE TITLE
Filters not working kanborad 

### ISSUE THREAD

**Issue by alvaradojao** [kanboard/kanboard#4202]
### Actual behaviour

in project view , the filter by owner not working

### Expected behaviour

At apply filter by owner should show only my tasks.

### Steps to reproduce
1- open a project with multiple owner taks
2- filter for a specific user tasks
3- still showing all tasks 

### Logs
No error in logs

### Configuration

- Kanboard version:1.2.9
- Database type and version:Mysql 5.7.26
- PHP version: 7.2.17
- OS: Ubutu 18.04
- Browser: Safari 12.1.1

**Comment by rafacamargo123** [comment]
can you please provide a screenshot? youre filtering manually (typing on search field) or using the user selector?

**Comment by alvaradojao** [comment]
Sure, this is before filtering (using the user selector):

![image](https://user-images.githubusercontent.com/41443328/58484472-5b76ea80-811f-11e9-92ee-456b51d2d67f.png)

And this after filter:

![image](https://user-images.githubusercontent.com/41443328/58484587-9416c400-811f-11e9-8132-7044e4af062c.png)


After filter, it still showing many tasks unassigned to the user I filter. There is no difference if a type it on search field.

I downgraded to Kanboard 1.2.5  where filters are working well. I hope this information can help.

**Comment by rafacamargo123** [comment]
I see you are using the group assignment plugin. Is it up to date? 
It overrides the TaskFinderModel and you have to make sure it is updated every time you update kanboard.

**Comment by alvaradojao** [comment]
Yes it is up to date. Your are right, when I remove that plugin, the filter start working again.

![image](https://user-images.githubusercontent.com/41443328/58559056-7dd03d00-81df-11e9-9336-a17724edb007.png)

**Comment by Cyboulette** [comment]
![gassign](https://user-images.githubusercontent.com/1302000/58582977-37b4c100-8253-11e9-90fb-d2f34fd2c856.png)

It's a feature of the Group Assign plugin. When you use `assigne:your_username`, it will display the tasks if you are member of the group assigned.

**Comment by alvaradojao** [comment]
This is the behavior of the same plugin (different version) in the same project with the same filter but in Kanboard 1.2.5:

before username filter:

![image](https://user-images.githubusercontent.com/41443328/58585513-29947f80-8216-11e9-8f50-fdff20f3264e.png)

After filter (only show tasks assigned to the user filtered):

![image](https://user-images.githubusercontent.com/41443328/58585572-52b51000-8216-11e9-9b4e-8583009ff30c.png)

![image](https://user-images.githubusercontent.com/41443328/58585647-82641800-8216-11e9-89bd-8e85cbeac51e.png)

I am no sin the filter assignee:me, I am using the filter: allassignees:Name 

![image](https://user-images.githubusercontent.com/41443328/58585867-01f1e700-8217-11e9-8169-4d2ad7407dbc.png)

**Comment by Cyboulette** [comment]
Yes because it was fixed on the v1.1.0 of the plugin :

https://github.com/creecros/Group_assign/releases?after=1.1.1
![gassign](https://user-images.githubusercontent.com/1302000/58586566-a85fdb80-825b-11e9-90b8-a72ab59dcdf6.png)

If you have issues with the plugin (but here is not an issue but a feature of the plugin) you can post directly on the plugin : https://github.com/creecros/Group_assign/issues

**Comment by rafacamargo123** [comment]
This issue may be closed because an issue was opened on Group_assign project and it is already closed: https://github.com/creecros/Group_assign/issues/37
