### ISSUE TITLE
Set Application URL in config.php

### ISSUE THREAD

**Issue by boredland** [kanboard/kanboard#4203]
### Actual behaviour

Currently it is neither documented, nor does it seem possible to set the APPLICATION URL with a config variable. 

### Expected behaviour

I'd like to see all "standard" variables to be configurable from the config.php.

- Kanboard version: 1.2.9
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by creecros** [comment]
Pretty sure it's stored in the configModel. Pretty sure changing that would cause a lot of people to go..."wth happened", not that I'm advocating aginst the idea.

**Comment by fguillot** [comment]
All configuration options are documented on this page: https://docs.kanboard.org/en/1.2.9/admin_guide/config_file.html or in the sample file: https://github.com/kanboard/kanboard/blob/master/config.default.php

The application URL value is stored in the database.

For feature requests, please use the forum: https://kanboard.discourse.group/
