### ISSUE TITLE
Admin password breaks login

### ISSUE THREAD

**Issue by jpretori** [kanboard/kanboard#4205]
### Actual behaviour

1. Installed Kanboard using Softaculous script on my web host.
2. Told Softaculous script to use `hK'}</!\"7F:2)^g` as the admin password (this password was generated by KeepassXC)
3. Tried to login, got failures
4. Used Softaculous to change admin password to something that only contains letters and numbers
5. Admin login now works

### Expected behaviour

Specific characters in password should not change how password is processed.  In fact this raises a concern about security (can I inject SQL this way?  I haven't tried.)

### Configuration

    Application version: 1.2.9
    PHP version: 7.2.18
    PHP SAPI: cgi-fcgi
    OS version: Linux 3.10.0-862.14.4.el7.x86_64
    Database driver: mysql
    Database version: 10.1.40-MariaDB
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by wladneto** [comment]
I have the same problem

**Comment by rafacamargo123** [comment]
I believe this is a softaculous issue, since kanboard does not have a function to set de initial admin password.
If you set your password to the one generated by keepass using the change password feature on your profile page, does this problem still occurs?

**Comment by fguillot** [comment]
This is a Softaculous issue. In normal Kanboard installation, the default password is hardcoded to "admin".

Please, use the forum for installation issues: https://kanboard.discourse.group/

**Comment by jpretori** [comment]
OK, closing this down then.  I haven't encountered any similar issues, despite continuing to use my password generator for Kanboard passwords.
