### ISSUE TITLE
sync webcal/caldav tasks feed with authentication into kanboard project

### ISSUE THREAD

**Issue by aliceinwire** [kanboard/kanboard#4216]
I know there are some closed bug about this.
But I would like to add more interest on having this feature.

**Comment by aliceinwire** [comment]
maybe using something like this https://github.com/subutux/sogosync

**Comment by aliceinwire** [comment]
this is the only thing that is keeping me to move to kanboard

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
