### ISSUE TITLE
Unable to Upload Files

### ISSUE THREAD

**Issue by Ryonez** [kanboard/kanboard#4223]
### Actual behaviour

Try to upload a attachment, either on a task or to the Customizer plugin. It's show the file name and upload progress bar, but will never upload it.

### Expected behaviour

The files to upload.

### Steps to reproduce
Try to upload a attachment, either on a task or to the Customizer plugin.

### Screenshots

Customizer (With file that's within limits)
![image](https://user-images.githubusercontent.com/16157130/60053722-b99dea00-972c-11e9-94d8-a009c9d5dd82.png)
Attaching to a task:
![image](https://user-images.githubusercontent.com/16157130/60053799-e18d4d80-972c-11e9-8134-fe2510bfc3f5.png)

### Logs
Browser Console:
```
09:14:27.504 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“default-src”).
09:14:27.505 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).
```
No docker logs for this issue.

### Configuration

- Kanboard version:  v1.2.10 
- Database type and version: postgres  11.4 (Debian 11.4-1.pgdg90+1)
- PHP version: 7.3.6
- OS: unRAID
- Browser: Firefox/67.0

This is using the kanboard docker from [here](https://hub.docker.com/r/kanboard/kanboard/).

### Notes

The permissions should be fine, I've uploaded a avatar. However the docker also doesn't have a way to set the user and group used, so that might cause issues?

**Comment by Ryonez** [comment]
So, turns out the percentage to the right of the file/s is *not* indicative of the file being uploaded. You have to click the upload button to actually trigger it.

This issue is resolved but I'll leave this open for a dev to look into still as I have a suggestion to prevent someone from making this mistake like me.

Don't show a progress percentage unless file transfer is in progress. Because it shows when the files is "added", it appears to be processing. Not showing this would make people think they have to do something to trigger it to go.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.13/developer_guide/faq.html).
