### ISSUE TITLE
Your Kanboard instance is not configured to install plugins from the user interface

### ISSUE THREAD

**Issue by dt1018614769** [kanboard/kanboard#4233]
Help! Help! Help

How do I set it up?

**Comment by dt1018614769** [comment]
![2](https://user-images.githubusercontent.com/28726343/60791645-aceeac80-a196-11e9-99f9-654e3a039bb9.png)

**Comment by sambar-fgfs** [comment]
1:Rename&Check $(Kanboarddir)/config.default.php to config.php,  and set parameter PLUGIN_INSTALLER to true
2:Check Permission $(kanboarddir)/plugins dir (need allow write www-user)
3:Need php-zip extension

read more:https://docs.kanboard.org/en/latest/admin_guide/plugins.html
