### ISSUE TITLE
User Mentions (@user) -  the list of users is not in the right place

### ISSUE THREAD

**Issue by kuerme** [kanboard/kanboard#4239]
### Screenshots

![image](https://user-images.githubusercontent.com/2811986/61274507-87892080-a7de-11e9-8839-9906bd5c109d.png)

### Configuration

- Kanboard version: 1.2.10
- Database type and version: Default Sqlite
- PHP version: 7.3
- OS: windows 10
- Browser: Chromium 70.0.3538.25

**Comment by rafacamargo123** [comment]
Are you using any plugin? can you try to reproduce this issue by disabling any plugin that changes kanboard UI?
I've tested the latest kanboard version on chrome 75 and it did not reproduce.
![image](https://user-images.githubusercontent.com/12586009/61676687-4b205d80-acd3-11e9-979e-b5867e12b7c4.png)

**Comment by kuerme** [comment]
I found the reason, it was really my own theme plugin `Spectre Theme` caused the problem. It has now been fixed and a new version update has been submitted to the `plugins.json` of kanboard/website; thanks a lot;

**Comment by kuerme** [comment]
> Are you using any plugin? can you try to reproduce this issue by disabling any plugin that changes kanboard UI?
> I've tested the latest kanboard version on chrome 75 and it did not reproduce.
> ![image](https://user-images.githubusercontent.com/12586009/61676687-4b205d80-acd3-11e9-979e-b5867e12b7c4.png)

I found the reason, it was really my own theme plugin Spectre Theme caused the problem. It has now been fixed and a new version update has been submitted to the plugins.json of kanboard/website; thanks a lot;

**Comment by kuerme** [comment]
I found the reason, it was really my own theme plugin Spectre Theme caused the problem. It has now been fixed and a new version update has been submitted to the plugins.json of kanboard/website; thanks a lot;
