### ISSUE TITLE
Roadmap feature

### ISSUE THREAD

**Issue by oliviermaridat** [kanboard/kanboard#424]
To manage properly the planning of a project, it could be very useful to have a roadmap management on Kanboard. Especially when it is hard to select a due date for each tasks, but when the finale due date is well-known.

I don't know how to handle this in Kanboard, but here is what I think may be useful:
- A roadmap view listing milestones (i.e. releases, versions, whatever you would like to call them)
- The possibility to assign/link/attach a task (or a list of task) to one milestone
- Eventually an automatic "milestone report" computed from all the closed tasks assigned to the milestone

And here are some ideas about how to implement it:
- Technically, a milestone can be a task with a specific category (e.g. "Milestone"). It may be easier than creating an other element. A milestone has a title and a description like tasks, and it is useful to sort them in columns like tasks. 
- The other tasks may be assigned to a milestone by adding a "milestone id" in the task table. Or even better, in a more generic way, by implementing the "Support linking of tasks together" feature (#92): a task is linked to a milestone with label "in milestone #idOfTheMilestone".
- Then a roadmap view can list all milestones (and their due date) and their linked tasks
  - A button "Report" near each milestone may display the list of titles of the closed tasks in the milestone

It is a bit of a draft sorry. But what do you think?

**Comment by abouquet** [comment]
Hi,

+1 for this feature. I'm using kanboard in a scrum way and need to sort different sprint inside a same project.

**Comment by oliviermaridat** [comment]
I have created a "Milestone plugin": https://github.com/oliviermaridat/kanboard-milestone-plugin

I made some test with a "Roadmap view" displaying all the Milestones of a project. I am wondering if this is relevant since the board is actually quite clear (especially with a filter "link:"is a milestone of").
