### ISSUE TITLE
Impossible to edit colomns and add tasks

### ISSUE THREAD

**Issue by tutle** [kanboard/kanboard#4244]
### Actual behaviour

unable to edit or delete column in project
many option (+task button) don't respond

### Expected behaviour

kanboard almost not usable
### Configuration

- Kanboard version:1.2.10
- Database type and version: sqlite 3.6.20
- PHP version: 7.1.30
- OS:  Linux 2.6.32-896.16.1.lve1.4.54.el6.x86_64
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by KN4CK3R** [comment]
Do you have JavaScript disabled?

**Comment by fguillot** [comment]
Remove all plugins. Test each plugin one by one to see if they are compatible with this version of Kanboard.

**Comment by rafacamargo123** [comment]
Open your browsers development console (f12), reload the page, click on the buttons that does not work and post a print screen of the "console" tab

**Comment by tutle** [comment]
Le 23/07/2019 à 00:08, Rafael de Camargo a écrit :

**Comment by rafacamargo123** [comment]
@tutle, your comment is empty. I think the reply via email didn’t work. Try to add the picture on the github website.

**Comment by tutle** [comment]
here is capture
![bug kanboard](https://user-images.githubusercontent.com/23037149/62034021-88ae4a80-b1ed-11e9-98c6-4246ea2dcd55.JPG)
![bug kanboard2](https://user-images.githubusercontent.com/23037149/62034022-88ae4a80-b1ed-11e9-8e2f-bee38961ea7a.JPG)

**Comment by rafacamargo123** [comment]
If I had to guess I would say this 406 erros are from some configuration of your web server.
Are you using apache? It may be the mod_security.
Check your apache errors and mod_security logs to find out which rule is being triggered so you can disable only this rule.
You can also disable mod_security entirely, if you don't care. 
If you need any further help, can you post to the [forum](https://kanboard.discourse.group)?

**Comment by tutle** [comment]
You are right, that's it !!! server mod-security bug
Thanks a lot
Yvan

Le 29/07/2019 à 14:40, Rafael de Camargo a écrit :
