### ISSUE TITLE
Reference Hook Error

### ISSUE THREAD

**Issue by tincboy** [kanboard/kanboard#4247]
### Actual behaviour
Error on simple reference plugin code

### Steps to reproduce
Just put this code in Plugins folder which is prety much similar to code in Kanboard's documentation, but it results in exception.
```
<?php


namespace Kanboard\Plugin\OneBigProject;

use Kanboard\Core\Plugin\Base;

class Plugin extends Base
{
    public function initialize()
    {
            $this->hook->on('formatter:board:query', function (\PicoDb\Table &$query) {
                    $userID = session_get('user')['id'];
                    $query->eq('owner_id',$userID);
            });
    }

    public function getCompatibleVersion()
    {
        // Examples:
        // >=1.0.37
        // <1.0.37
        // <=1.0.37
        return '>=1.2.10';
    }
}
```

### Logs
PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on boolean in /var/www/html/kanboard/libs/picodb/lib/PicoDb/Table.php:283
Stack trace:
#0 /var/www/html/kanboard/app/Formatter/BoardFormatter.php(58): PicoDb\\Table->findAll()
#1 /var/www/html/kanboard/app/Core/Filter/QueryBuilder.php(83): Kanboard\\Formatter\\BoardFormatter->format()
#2 /var/www/html/kanboard/app/Controller/BoardViewController.php(70): Kanboard\\Core\\Filter\\QueryBuilder->format(Object(Kanboard\\Formatter\\BoardFormatter))
#3 /var/www/html/kanboard/app/Core/Controller/Runner.php(77): Kanboard\\Controller\\BoardViewController->show()
#4 /var/www/html/kanboard/app/Core/Controller/Runner.php(31): Kanboard\\Core\\Controller\\Runner->executeController()
#5 /var/www/html/kanboard/index.php(9): Kanboard\\Core\\Controller\\Runner->execute()
#6 {main}
  thrown in /var/www/html/kanboard/libs/picodb/lib/PicoDb/Table.php on line 283

### Configuration

- Kanboard version: 1.2.10
- Database type and version:   MariaDB 10
- PHP version: 7.0
- OS: Linux/Debian
- Browser: Any

**Comment by rafacamargo123** [comment]
This is not an issue. I've tried your code and got a SQL exception:

`Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1 ambiguous column name: owner_id`

You have to prepend the table names. You can do that by using `Kanboard\Model\TaskModel` and then referring to `TaskModel::TABLE`, like that:

```
<?php
namespace Kanboard\Plugin\Test;

use Kanboard\Core\Plugin\Base;
use Kanboard\Model\TaskModel;

class Plugin extends Base
{
    public function initialize()
    {
            $this->hook->on('formatter:board:query', function (\PicoDb\Table &$query) {
                    $userID = session_get('user')['id'];
                    $query->eq(TaskModel::TABLE.'.owner_id',$userID);
            });
    }
}
```

If you have any further questions about plugin development, please use the [forum](https://kanboard.discourse.group)
