### ISSUE TITLE
I am trying to delete a column but it isn't empty but query of column:"Sprint Complete" doesn't show any tasks.

### ISSUE THREAD

**Issue by jack1729** [kanboard/kanboard#4251]
Originally it was 1.1.0 but upgrade to 1.2.10 and still present.

seems like some tasks are still in column but I can't get them to display?

**Comment by fguillot** [comment]
Make sure to display both closed and opened tasks. Closed tasks are hidden by default.

**Comment by jack1729** [comment]
I did, query: Status:closed column:"Sprint Complete"

Sent from BlueMail<http://www.bluemail.me/r?b=15431>
On Jul 24, 2019, at 2:46 PM, "Frédéric Guillot" <notifications@github.com<mailto:notifications@github.com>> wrote:

Make sure to display both closed and opened tasks. Closed tasks are hidden by default.

**Comment by jack1729** [comment]
if I edit project and look at columns selection on left - it lists each column and number of tasks in each column and it shows 4 open tasks

**Comment by jack1729** [comment]
Any other ideas.  I am going to try to look at it in a SQLite editor / tool.

**Comment by jack1729** [comment]
Can you give me SQLite sql to delete 4 records given the task_id?

**Comment by rafacamargo123** [comment]
```
PRAGMA FOREIGN_KEYS = ON;
BEGIN TRANSACTION;
DELETE FROM task_has_files WHERE task_id IN (1111,2222,3333,4444);
DELETE FROM tasks WHERE id IN (1111,2222,3333,4444);
COMMIT;
```
Change 1111,2222,3333,4444 with the task ids you want to delete. 
The first command (pragma foreign_keys = ON) is very important for the child rows (comments, actions, etc.) to get automatically deleted too. 
If anything goes wrong, instead of commit, type `ROLLBACK;`

**Comment by creecros** [comment]
In your dashboard, search `column:ColumnName`. That should find them. Then close them.
