### ISSUE TITLE
Problems when adding a new task in IE 11.829 

### ISSUE THREAD

**Issue by VitaMark** [kanboard/kanboard#4254]
### **Actual behaviour**
When adding a new task in any swimlane, the window “New task” pops up and you can make your settings. When you press “Save” the window normally closes and the Swimlane refreshes with your new task.

This all works fine on Chrome and Edge. However in our company most people use the IE 11.829.17134.0 (newest IE) for several reasons and here the “New task” window does not close and it looks like it keeps saving (grey animated button). If you hit F5 to refresh, it will look like it should. The created task is there.

### **Expected behaviour**
The "New task" window should close and the swimlane shlould refresh so you can see the new task.

### **Steps to reproduce**
- Use IE 11.829.17134.0
- Go to any project
- Press any "+" on top of the swimlane
- Type in some title and markdown in the "New task" window
- Save
>> Now It "hangs"

### **Configuration**
◾Version: 1.2.10 
◾PHP Version: 7.3.1 
◾PHP SAPI: cgi-fcgi 
◾HTTP Client: cURL 
◾OS Version: Windows NT 6.3 
◾Datenbanktreiber: sqlite 
◾Datenbank Version: 3.24.0 
◾Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko 

Thx for your help!

**Comment by rafacamargo123** [comment]
Can you provide the browser's console logs, please? 
It’s the IE, not the edge? 
Thank you!

**Comment by VitaMark** [comment]
Hi!

I guess its the first one: German unknown error.....

SCRIPT16389: Unbekannter Fehler.
kanboard.vita.com (1,1)

HTML1300: Navigation wurde ausgeführt.
kanboard.vita.com

**Comment by VitaMark** [comment]
OK, if I use F12 and then Console I see nothing unusual when doing this procedure. Just a bunch of:

HTML1300: Navigation wurde ausgeführt.
kanboard.vita.com

**Comment by VitaMark** [comment]
One thing I just saw. This does not happen when I edit an existing task. Here it works correctly. This problem just comes up when I create a new task.

**Comment by VitaMark** [comment]
I meanwhile also found out that this does not happen when I use the IP of server instead of the subdomain we set on the IP. Is there any setting I am missing?

**Comment by VitaMark** [comment]
Thanks for your help. I have found the problem. It was a proxy setting we use in our company.
