### ISSUE TITLE
[Enchancement] General board for all projects/tasks

### ISSUE THREAD

**Issue by ArkantosX** [kanboard/kanboard#426]
Availability to have a general Kanban board(board id=0 or similar) that showcases all taks on all projects at same time.

Then we can have it as a read-only board (just showcasing all tasks),
or if update functions are needed and viable, to update task within same Project even if in general board.

Greets.

**Comment by lostsol95** [comment]
Did anyone find a way to see all tasks of all projects on a single calendar no matter who the task is assigned to?  I would think if you were the admin and/or the project manager of that project, then you would be able to see all of the tasks that every project has in your one calendar.
Maybe I'm trying to use the application the wrong way, but this feature makes a lot of sense to me.  I want my employee to log in and create a project and tasks within the project, but I want these tasks to also appear on my calendar.
Any advice would be greatly appreciated, because besides this limitation, I think the app is awesome.

**Comment by BlueTeck** [comment]
@lostsol95 there is already a feature request -> #547

**Comment by jbarotin** [comment]
Hi, any news about this feature ?

**Comment by ttjarloev** [comment]
I needed this feature to have an overview of all my projects, so I've created a plugin, which manage to suit some of my requirements. It's mostly copy and paste of the original code with some small modifications to variables.
The plugin is available here: https://gitlab.com/ThomasTJ/Fullboardview
Please note the comments in the readme.

**Comment by ArmReu** [comment]
Any progress on this project? It's really a feature I'd like to see! 👍

**Comment by erpnedir** [comment]
It would be nice if we can map the columns between the actual boards and the global boards (can be also named as reporting boards.) For example, it can be used to create a global board for all Work In Progress columns from multiple boards.

**Comment by ThomasTJdev** [comment]
While waiting on Stinnux pull [#2676](https://github.com/kanboard/kanboard/pull/2676) to come through, I have two temporary solutions where I just print all the task in a grid for overview. Both solutions is read-only with no user interaction.

**Solution 1** is with webix (please note that this costs $$): [AllBoardView with JS](https://gitlab.com/ThomasTJ/AllBoardView)

**Solution 2** is just HTML and CSS. For now it is predefined to 4 columns, but you can easily loop through your data and add columns dynamic. See the README.md for how to change the columns: [AllBoardViewHTML](https://gitlab.com/ThomasTJ/AllBoardViewHTML)

**Comment by smacz42** [comment]
I can view all tasks in _any_ project in any one column that is the same between them all, grouped by swimlane name with the search function. The URL bookmark I use (running in a docker container) is:

```
http://localhost:8001/?controller=search&action=index&search=column:"Work+in+progress"&page=1&order=tasks.swimlane_id&direction=ASC
```

This is by simply using the search engine to search for the name of the column.

**Comment by juekbr** [comment]
Hi, 
We are searching for a way to manage our ressources, is there an update to this? 
Highly appreciated :)

**Comment by jmccorm** [comment]
I just installed Kanboard, created projects, and created new tasks between them. I also installed the Coverimage plugin, which is a solid help for my visually oriented users. I went to go look "at the big picture", and I'm surprised that this feature isn't here. I expected to find a screen where I could view all the projects in the Board View format. It... it doesn't exist?

If merging the output on-screen the issue, I'd be satisfied with all projects one after the other. I just want a place where I can go to see everything that is in flight, and I really enjoy the Board View presentation to do it. Actually, I want it to be the default view for myself and for my users. It solves a lot of issues with user acceptance and education.

If you were to prioritize this feature, it would be greatly appreciated, and I think it would substantially enhance the user interface.

Thank you for your time,
Josh McCormick

**Comment by fguillot** [comment]
The software is not really made for that initially. That will occurs too many change. I prefer to keep the software very simple.

Thank you for your understanding.

**Comment by compumatter** [comment]
I second this request.  Really need the ability to look at my 'Todays Tasks' or 'All Tasks' so I can make some decisions on what's a priority.  Otherwise I have to open each project one at a time to see what's due that day.

**Comment by compumatter** [comment]
I know you've closed this.  However the lack of just being able to see all tasks in one location is just enough for me to have to use a separate software (https://kanboard.net/) instead of using your plugin.  I wish you would reconsider.  I am happy to put $50.00 towards this bounty if it is on the near to complete list.
