### ISSUE TITLE
not able to to assign position of view-switcher hook

### ISSUE THREAD

**Issue by dreamcoder8** [kanboard/kanboard#4260]
I am using "view-switcher" hook and I want to place new menu to be displayed before overview menu but don't see any option to do so.

$this->template->hook->attach('template:project-header:view-switcher', '{plugin-name}:project_header/views');

Appreciate the help.

Regards
Hitesh

**Comment by rafacamargo123** [comment]
Your view is rendered where the hook is placed on the original view, which is after all other options 

https://github.com/kanboard/kanboard/blob/master/app/Template/project_header/views.php

That’s why it is being displayed at the end. 

You can either edit kanboard code adding a new hook at the beginning of the list and submit a pull request or edit your own instance and move the hook to the beginning of the list. 
Fell free to contribute.

**Comment by dreamcoder8** [comment]
Hello, Thanks for clarification. Will try to contribute.

**Comment by dreamcoder8** [comment]
Hello, Made the contribution and opened pull request. Thanks for the suggestion.
