### ISSUE TITLE
Cronjob not included in Docker

### ISSUE THREAD

**Issue by rolandu** [kanboard/kanboard#4263]
### Actual behaviour

Running Kanboard using provided Dockerfile + Docker-Compose does not execute the daily cronjob.

### Expected behaviour

Dockerfile + Docker-Compose contain the whole configuration required to run Kanboard. This includes a daily Cronjob. 

One might argue whether cron is part of configuration. I think it should be. If you don't think so then at least this is an issue with the documentation and there should be a remark on https://docs.kanboard.org/en/latest/admin_guide/docker.html that cron has to be set up as well.

### Steps to reproduce

* docker-compose up
* wait 24h

### Configuration

* Application version: v1.2.10
* PHP version: 7.3.6
* PHP SAPI: fpm-fcgi
* HTTP Client: cURL
* OS version: Linux 4.9.0-9-amd64
* Database driver: sqlite
* Database version: 3.28.0

**Comment by fguillot** [comment]
The cronjob is included in the Docker image.

You can verify the execution by increasing the debug level in this file: https://github.com/kanboard/kanboard/blob/master/docker/etc/services.d/cron/run, for example `crond -f -d 8`.

If you don't want to wait 24 hours, you can increase the frequency in this file: https://github.com/kanboard/kanboard/blob/master/docker/etc/crontabs/nginx

Then you will see the cronjob execution in Docker logs, for example:

```
crond: USER nginx pid  18 cmd cd /var/www/app && ./cli cronjob >/dev/null 2>&1
crond: USER nginx pid  25 cmd cd /var/www/app && ./cli cronjob >/dev/null 2>&1
crond: USER root pid  26 cmd run-parts /etc/periodic/15min
crond: USER root pid  27 cmd run-parts /etc/periodic/hourly
```

**Comment by creecros** [comment]
I concur, cronjob runs just fine with docker.

**Comment by Kolossi** [comment]
@rolandu - you report docker-compose "contains the whole configuration ... including cronjob".  This isn't the case in the stock docker-compose.yml in this repo.

I use a customer docker-compose myself, and if docker-compose is being used to mount a crontab file, note that the ACTUAL filename needed for the crontab is /var/spool/crontabs/nginx.  You can verify this by entering the container with

`docker exec -it kanboard /bin/bash`

then doing

`crontab -u nginx -e`

and checking the filename presented for editing.

However note that /var/spool/crontabs is a softlink to /etc/crontabs in the kanboard docker image.

Perhaps some of this has got mangled with mounts/volumes in the custom docker-compose ?  Try removing any such crontab mounts/volumes in docker-compose, restarting the container, and see if the daily cronjob returns?

**Comment by rolandu** [comment]
Sorry, it was all my mistake! I configured my rule wrong and blamed it on cron because I did not understand your Dockerfile. Of course everything is there. Retest successful. Thanks for the support!
