### ISSUE TITLE
Disable IP address storage

### ISSUE THREAD

**Issue by Perflyst** [kanboard/kanboard#4267]
Currently any IP address is storage in plain(!) for any login an user does. This is not optimal for privacy.

I did not found any way to disable it. I would like to have an option to disable it.

For the meanwhile, is there a workaround to achive this?

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
