### ISSUE TITLE
Kandroid API authentication error with v.1.2.9

### ISSUE THREAD

**Issue by smacz42** [kanboard/kanboard#4268]
**I am aware that Kandroid is not an officially-supported app. However, I would simply appreciate any suggestions as to what may have changed that might cause this type of behavior.**

### Actual behaviour

[Kandroid](https://github.com/andresth/Kandroid) can no longer authenticate a new user after upgrading to version 1.2.9. Logins work as expected on version 1.2.8. Log excerpt below shows an API authentication error.

### Expected behaviour

Login succeeds.

### Steps to reproduce

Install Kanboard version 1.2.9 on a VM and try to log in with the Kandroid software.

#### NOTE: I am accessing this resource behind a reverse proxy using NGINX. Configuration below:

```
location /kanboard/ {
    proxy_headers_hash_max_size 512;
    proxy_headers_hash_bucket_size 64;
    proxy_set_headers X-Forwarded-Proto $scheme;
    proxy_set_headers X-Real-IP $remote_addr;
    proxy_set_headers X-Forwarded-For $proxy_add_x_forwarded_for;
    add_header Front-End-Https on;
    proxy_pass http://kanboard
}
```

### Logs

```
Aug 19 00:19:03 ubuntu-s-4vcpu-8gb-nyc3-01 6152c4db2ffc[14502]: PHP message: Kanboard: user Unknown authentication failure"
Aug 19 00:19:03 ubuntu-s-4vcpu-8gb-nyc3-01 6152c4db2ffc[14502]: PHP message: [error] API authentication failure for "
2019/08/19 00:19:03 [error] 15#15: *25 FastCGI sent in stderr: "PHP message: Kanboard: user Unknown authentication failurePHP message: [error] API authentication failure for" while reading response header from upstream, client: 172.18.0.2, server: localhost, request: "POST /kanboard/jsonrpc.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "kbtest.example.com"
```

### Configuration

- Kanboard version: 1.2.9
- Database type and version: MySQL
- PHP version: 7
- OS: Alpine
- Browser: Kandroid

**Comment by fguillot** [comment]
The username doesn't seems to be passed to Kanboard via the HTTP headers.

You should check your installation independently of the mobile application by calling the API with curl. See: https://docs.kanboard.org/en/latest/api/examples.html

If that works the problem is coming from the mobile app otherwise it's coming from your setup.

Please, use the forum next time: https://kanboard.discourse.group/
