### ISSUE TITLE
[Bug] in Action TaskUpdateStartDateOnMoveColumn

### ISSUE THREAD

**Issue by BlueTeck** [kanboard/kanboard#4277]
### Actual behaviour

Action just checks, if the column is different from the defined column, not if the previous column is the defined column.

### Expected behaviour

> Automatically update the start date when task move away from certain column

### Steps to reproduce

Try action and move tasks in different columns, the start date is set anyway

### History

Bug introduced by https://github.com/kanboard/kanboard/commit/d3d55224329681722b52a84b31f141bf78aaa134 @renothing 

### Sourcecode

https://github.com/kanboard/kanboard/blob/master/app/Action/TaskUpdateStartDateOnMoveColumn.php#L94

```php  
public function hasRequiredCondition(array $data)
    {
        return empty($data['task']['date_started']) && $data['task']['column_id'] != $this->getParam('column_id');
    }
```

**Comment by BlueTeck** [comment]
see also https://kanboard.discourse.group/t/new-action-to-update-the-start-date-when-a-task-move-away-from-a-column

**Comment by renothing** [comment]
@BlueTeck  to my original iead, it's not a bug. but the discription is not cleaner.
I use it for "any task not in special column should start automatically if it's unstarted."

**Comment by BlueTeck** [comment]
@rafacamargo123 thanks

@renothing ah ok

**Comment by rafacamargo123** [comment]
@renothing but this behavior does not match the Action description. The description says “when move away from certain column”. 
That automatic action was considering the destination column, so it should be like “always set the task start date except when moved to a specific column”
