### ISSUE TITLE
Authentification process hits LDAP before trying API

### ISSUE THREAD

**Issue by Lenormju** [kanboard/kanboard#4279]
### Actual behaviour

I develop scripts that speak to the API endpoint.  
I launch them frequently, which causes them to authenticate frequently.  
The Kanboard server also has the LDAP authentification method enabled.  
I frequently get tempban on the LDAP server.  
I suspect it is because of failed attempts from Kanboard to verify my API authentification from the LDAP server.

### Expected behaviour

It could try to authentificate by API before trying with LDAP.

### Steps to reproduce

1. Have a login + API token generated
2. authentificate to the API endpoint

### Screenshots

N/A

### Logs

I don't have access to any of the servers, so I can't provide logs.

### Configuration

- Kanboard version: (unknown)
- Database type and version: (unknown)
- PHP version: (unknown)
- OS: (unknown)
- Browser: N/A

**Comment by Lenormju** [comment]
The API authentification method [fetches the database](https://github.com/kanboard/kanboard/blob/8cee04101d351fb5321f225963d589883761d214/app/Auth/ApiAccessTokenAuth.php#L59) while the LDAP authentification method [connects to another server ](https://github.com/kanboard/kanboard/blob/8cee04101d351fb5321f225963d589883761d214/app/Auth/LdapAuth.php#L61)).  
These are called by [`passwordAuthentication`](https://github.com/kanboard/kanboard/blob/233fd1a8a1e4da808ce34f91194a423522e5c478/app/Core/Security/AuthenticationManager.php#L117) in the order they are registered in [the provider](https://github.com/kanboard/kanboard/blob/233fd1a8a1e4da808ce34f91194a423522e5c478/app/ServiceProvider/AuthenticationProvider.php#L48), which is **LDAP** before **API**.

Would it be judicious to swap them ?

**Comment by fguillot** [comment]
Moving API auth before LDAP auth should work. You can send a PR if you would like.

**Comment by mogoa** [comment]
I have the same problem for me. The behavior is exactly the same. And after a few attempts with the API, my credentials are blocked.

I have one more question : 

I would like to authenticate to kanboard with ldap credentials through SSO.

For example : some users connect to a frontend web app with some forms very simply and on submit, the webapp creates item in a specific board by using the API.

But I need to get the authentication token of the user to use the API and automatically fill the creator_id field of the item.

If you have any advice !

**Comment by Lenormju** [comment]
@mogoa The creator_id is just an `user_id`, which can be obtained from a [GetMe request](https://docs.kanboard.org/en/latest/api/me_procedures.html#getme) (which requires API auth : login+token) or you could create, like I did, a static mapping from corporate users to user_ids (I built a local JSON file that contains associations `corporate_id`->`kanboard_id`for all the users, i.e. `{"3": "LENORMJU", ...},`)
