### ISSUE TITLE
Drag and Drop Not Working

### ISSUE THREAD

**Issue by bufedwards** [kanboard/kanboard#4280]
I installed Kanboard on REHL with MariaDB and the install was smooth, but I am unable to **drag and drop tasks** from one column to the next.  I have read through the documentation and cannot find anything in the bug tracker or the forums that addresses this.  Therefore I am submitting as a bug report, but this could very well be a misconfiguration on my part.  Moving the tasks via the menu options work fine, I am just unable to drag and drop.  I have attempted to drag and drop in Chrome, Firefox, Edge, and Safari all with the same result.

**Comment by rafacamargo123** [comment]
Did you create any custom roles? Are you by any chance viewing the public board? What is the role of the user you are using? Is it admin?

Also, open the element inspector or developer console, go to Console tab, refresh the page and try to move the tasks. Attach a screenshot of the console messages, please.

**Comment by bufedwards** [comment]
I actually figured this out yesterday afternoon.  The problem was related to the due date sorting plugin.  Once I uninstalled this plugin it worked just as expected, so the issue is not related to kanboard but rather the plugin.  Thank you for your prompt response though!
