### ISSUE TITLE
Chrome recognizes Dutch on German project page

### ISSUE THREAD

**Issue by josch87** [kanboard/kanboard#4289]
### Actual behaviour
Chrome asks if I want to translate dutch on a the German "projects" page (projects management). 

### Expected behaviour
The page is German. Browsers should recognize that it is German.

### Steps to reproduce
- Change language of user interface to German (or any other language)
- Go to projects management
- Chrome want to translate the page. 

It would be great if any page would have `<html` `lang="de">` in head. 

### Screenshots
![image](https://user-images.githubusercontent.com/33511915/64470473-c33bc900-d143-11e9-9008-7345742408e0.png)

### Configuration

Version: 1.2.11
PHP Version: 7.1.31
PHP SAPI: apache2handler
HTTP-Client: cURL
OS Version: Linux 3.16.0-7-amd64
Datenbanktreiber: mysql
Datenbank Version: 5.7.24
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by SladeP** [comment]
@josch87 this fix was merged into master, so this issue should be good to close!

**Comment by josch87** [comment]
I can confirm that issue is fixed on master.
