### ISSUE TITLE
Dropdown in project managers view covers heading

### ISSUE THREAD

**Issue by peterk** [kanboard/kanboard#4299]
### Actual behaviour
In the view /projects/managers the dropdown is too wide in the default theme (and som other themes I tested as well). It covers the headline even if drop down content doesn't require it.

### Expected behaviour

Drop down width matches the sidebar.

### Steps to reproduce

Go to  /projects/managers

### Screenshots

![image](https://user-images.githubusercontent.com/19284/65045933-f8c08d80-d95f-11e9-88a1-a4b51c369b9e.png)

### Configuration

- Kanboard version: 12.11
- Database type and version: 
- PHP version: 7.3.8
- OS: OSX
- Browser: Brave

**Comment by SladeP** [comment]
@peterk this fix was merged into master, so this issue should be good to close!
