### ISSUE TITLE
Dynamic cronjob calls

### ISSUE THREAD

**Issue by davidtessier** [kanboard/kanboard#4307]
Is it at all possible to choose what tasks are run in the cronjob and what ones aren't? 

For example:
- I'd like to run a **_daily_** cron job to see a list of tasks that are overdue. 
- I'd like to run a **_hourly_** cron job to call this automated task: Close a task in a specific column  when not moved during a given period

This would ideally be two different crontab entries. One for the daily, one for the hourly. 

From what I see on this documentation, it doesn't look to be possible. https://docs.kanboard.org/en/latest/admin_guide/cronjob.html If it isn't, can this become a feature request?

Thank you!

**Comment by fguillot** [comment]
You can run them separately:

```
./cli cronjob
```

Is equivalent to:

```
./cli trigger:tasks
./cli projects:daily-stats
./cli notification:overdue-tasks
```

**Comment by davidtessier** [comment]
Thank you! That is exactly what I was hoping for!
