### ISSUE TITLE
No privacy from admins

### ISSUE THREAD

**Issue by JavierYuste** [kanboard/kanboard#4313]
Why are administrators able to see everything? That makes no sense from a privacy point of view. Private projects are not really private then.

**Comment by BlueTeck** [comment]
I stumbled on it too.

**Comment by pcadeot** [comment]
+1
This point is becoming quite problematic in my company, is there any plan to enable some options in general config to enforce privacy for so called private projects ?

**Comment by BlueTeck** [comment]
I've created PR #4317

**Comment by JavierYuste** [comment]
Thanks a lot for the PR @BlueTeck !

**Comment by pcadeot** [comment]
Very nice ! Thanks ! @BlueTeck

**Comment by fguillot** [comment]
Private projects have been renamed personal projects. They are not "private".
