### ISSUE TITLE
Two factor authentication QR code incorrect

### ISSUE THREAD

**Issue by diagonal-III** [kanboard/kanboard#4321]
### Actual behaviour

Enabling 2FA creates a secret and a QR barcode.
The QR barcode does not work - it does not scan.
The generated secret, however, will work when manually entered into OTP software such as Step Two, OTP Auth et al.

### Expected behaviour

QR code generated does indeed contain secret, account ID and boardname as set in the TOTP name variable in config.php.

### Steps to reproduce

1 - Install latest kanboard (I did an install from git because I couldn't get the kanboard-master.zip to work, I'll review that later once I finished testing)
2 - Try to set up 2FA for a user
3 - copy the secret somewhere useful (note: would be good if a user could still see their own 2FA secret and QR code at a later stage).

4 - try to scan QR Code with various 2FA apps.  This fails, which appears to suggest the QR code generated is incorrect.

5 - manually add preserved secret in step (3) to 2FA app
6 - enter code from 2FA app in kanboard to verify
7 - 2FA verified, now enabled.

### Configuration

- Kanboard version: 1.12.1
- Database type and version: sqlite 3.28.0
- PHP version: 7.3.9
- OS: FreeBSD 11.3-RELEASE-p1
- Browser: Used both Safari and Firefox (on MacOS 10.15.1 beta 1)

**Comment by rafacamargo123** [comment]
Tested with an IPhone using [OTP Auth](https://apps.apple.com/br/app/otp-auth/id659877384) and it worked just fine.
Tried iPhone's camera which correctly suggested the OTP. Auth application.

Can you generate a QR code and post it here?

Users are not able to see their secrets again for a security matter. Imagine you forgot your account logged in somewhere. Anyone could pair with your secret.
