### ISSUE TITLE
Board column titles saved for language used during creation of the project

### ISSUE THREAD

**Issue by klxdr** [kanboard/kanboard#4330]
### Actual behaviour
Titles of board columns are not changing when you change the language in user settings. They are in the language that was selected during the creation of the project.

### Expected behaviour
Titles in the language selected in user profile settings.

### Steps to reproduce
* set english language in your user profile settings 
* create project "first_project"
* change language to russian
* create another one project "secong_project"

now when switching to "first_project" columns titles would be "Backlog", "Ready" etc
whe switching to second  "Ожидающие", "Согласованные", etc 

### Configuration

- Kanboard version: 1.2.11
- Database type and version: postgresql (ver. 11.3)
- PHP version: 7.3.11
- OS:3.10.0-327.28.3.el7.x86_6
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Comment by fguillot** [comment]
This is the expected behaviour.

Columns are configurable in the project settings after the project creation. Column names used during the project creation are default labels that can be changed in global settings.

**Comment by klxdr** [comment]
pardon. have not noticed that.
