### ISSUE TITLE
Kanboard v.1.2.12 and Firefox 70

### ISSUE THREAD

**Issue by rajo** [kanboard/kanboard#4331]
### Actual behaviour
After updating Kanboard to 1.2.12 and Firefox to v. 70 multiple things stop working, e.g.
- drag and drop of tasks doesn't work
- drop down menus don't work

FF 70 console throws an error (see below)

Chrome and Firefox 69 work fine with 1.2.12. 

### Expected behaviour
FF 70 should work.

### Steps to reproduce
Upgrade to KB 1.2.12 and FF 70

### Screenshots
![error](https://user-images.githubusercontent.com/758592/67663832-a1eaa280-f966-11e9-921a-e71330ad8d05.png)

### Logs
`UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. app.min.js:287
    render https://kanboard.sr.sr-intra.de/kanboard/assets/js/app.min.js?1572141165:287
    each https://kanboard.sr.sr-intra.de/kanboard/assets/js/vendor.min.js?1572141165:2
    each https://kanboard.sr.sr-intra.de/kanboard/assets/js/vendor.min.js?1572141165:2
    render https://kanboard.sr.sr-intra.de/kanboard/assets/js/app.min.js?1572141165:287
    execute https://kanboard.sr.sr-intra.de/kanboard/assets/js/app.min.js?1572141165:287
    execute https://kanboard.sr.sr-intra.de/kanboard/assets/js/app.min.js?1572141165:282
    <anonym> https://kanboard.sr.sr-intra.de/kanboard/assets/js/app.min.js?1572141165:297
    e https://kanboard.sr.sr-intra.de/kanboard/assets/js/vendor.min.js?1572141165:2
    t https://kanboard.sr.sr-intra.de/kanboard/assets/js/vendor.min.js?1572141165:2`

### Configuration

- Kanboard version: 1.2.12
- Database type and version: mysql 5.5.62-0+deb8u1
- PHP version: 5.6.40-0+deb8u1
- OS: Windows 7 (yes...)
- Browser: Firefox 70.0 (64bit)

**Comment by fguillot** [comment]
I'm also using Firefox 70 and I do not have this issue. Did you try in incognito mode? Do you have any plugins installed? If yes, uninstall them to see if that improve the situation.

**Comment by rajo** [comment]
I have plugins installed in kanboard and removed them. I have extensions installed in FF and removed them. Both did not resolve the issue. Interestingly, using incognito mode resolves the issue. So... maybe some profile issue?

**Comment by rajo** [comment]
Okay, I‘ve cleaned my profile and the issue is resolved. Concidally both updates just happened after each other so it looked as if it is related, but as it seems, there was just a profile quirk. Nevermind :)
