### ISSUE TITLE
The vulnerability

### ISSUE THREAD

**Issue by plyaskin** [kanboard/kanboard#4334]
https://pulsesecurity.co.nz/advisories/Kanboard
The vulnerability was closed?

**Comment by eSkiSo** [comment]
According to the end of the page, it seems so.

**Comment by peterkelm** [comment]
Per the [changelog](https://github.com/kanboard/kanboard/blob/master/ChangeLog) these issues were resolved already in Feb with version 1.2.8. This is also reflected in the pulsesecurity report.
