### ISSUE TITLE
FeatureRequest - Date format select Y-m-d (seperator "-")

### ISSUE THREAD

**Issue by dreiggy** [kanboard/kanboard#4341]
Hi,
for our needs is needed to display date format with seperator "-". Why it is not added to select window?

At this moment we have added this type to DateParser.php - $userFormats
```
        $userFormats = array(
            'm/d/Y',
            'd/m/Y',
            'Y/m/d',
            'd.m.Y',
            'Y-m-d',
        );
```

Can it be included by default to new versions?

**Comment by SladeP** [comment]
@dreiggy this got merged into master so it should be good to close

**Comment by dreiggy** [comment]
Thank you so much!
