### ISSUE TITLE
feature request: add Project/Task Limit per User

### ISSUE THREAD

**Issue by colttt** [kanboard/kanboard#4360]
Hello,

it would be very nice if you add something like a task/project limit per user. So no user will be overloaded. 
If I want to add a user to a Project I will see the actual task/project count (in brackets?)

**Comment by BlueTeck** [comment]
belongs to #1584 and #125

**Comment by danieleteti** [comment]
This is a show-stopper for me. The limit for user (not "user in column", just "user") is a standard Kanban feature... it is not an unuseful complexity, it is just a requirement IMHO. 
All the "Kanban simulations" uses avatars to explain the concept of "User WIP limit".

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
