### ISSUE TITLE
Frequent database locked error after upgrade from 1.2.11 to 1.2.12

### ISSUE THREAD

**Issue by AmritasyaPutra** [kanboard/kanboard#4362]
After upgrade I am seeing the following error frequently, they are okay in concept. But do you think these have increased due to any recent design change?

I had never seen this error earlier. After upgrade, my logs are getting flooded with this. 2 such log every time I look at my dashboard.

[Mon Dec 02 11:16:06.412510 2019] [lsapi:error] [pid 20054] [client 172.68.144.191:55980] [host kanboard.ekvastra.in] Backend fatal error: PHP Fatal error:  Uncaught PicoDb\\SQLException: SQL Error: SQLSTATE[HY000]: General error: 5 database is locked in /home/ekvastra/kanboard.ekvastra.in/libs/picodb/lib/PicoDb/StatementHandler.php:351\nStack trace:\n#0 /home/ekvastra/kanboard.ekvastra.in/libs/picodb/lib/PicoDb/StatementHandler.php(245): PicoDb\\StatementHandler->handleSqlError(Object(PDOException))\n#1 /home/ekvastra/kanboard.ekvastra.in/libs/picodb/lib/PicoDb/Database.php(257): PicoDb\\StatementHandler->execute()\n#2 /home/ekvastra/kanboard.ekvastra.in/libs/picodb/lib/PicoDb/Table.php(218): PicoDb\\Database->execute('UPDATE "session...', Array)\n#3 /home/ekvastra/kanboard.ekvastra.in/app/Core/Session/SessionHandler.php(62): PicoDb\\Table->update(Array)\n#4 [internal function]: Kanboard\\Core\\Session\\SessionHandler->write('ffea3141a342ff2...', 'user|a:23:{s:2:...')\n#5 [internal function]: session_write_close()\n#6 {main}\n  thrown in /home/ekvastra/kanboard.ekvastra.in/libs/picodb/lib/PicoDb/StatementHandler.php on line 351\n

    Application version: 1.2.12
    PHP version: 7.3.11
    PHP SAPI: litespeed
    HTTP Client: cURL
    OS version: Linux 3.10.0-962.3.2.lve1.5.26.5.el7.x86_64
    Database driver: sqlite
    Database version: 3.26.0
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0

The IP and file path in the log are mine and I am okay with sharing it publicly. It is a dynamic IP that will change on every reboot, very frequently. The file path is virtual, it doesn't exist on file system.

**Comment by fguillot** [comment]
Please, use the forum for installation issues. Avoid using Sqlite: https://docs.kanboard.org/en/latest/admin_guide/requirements.html#compatible-databases
