### ISSUE TITLE
Getting Blank Screen on ``Categories`` page - Kanboard version: 1.2.13

### ISSUE THREAD

**Issue by GaneshKandu** [kanboard/kanboard#4375]
### Actual behavior

Getting Blank Screen on ``Categories`` page

### Expected behavior

Not a blank screen  expected

### Steps to reproduce

Create new project and add new Category

### Logs

```
Array
(
    [type] => 4
    [message] => syntax error, unexpected '?'
    [file] => /home/soft/public_html/manual/kanboard1213/app/Template/category/index.php
    [line] => 38
)
```

### Configuration

- Kanboard version: 1.2.13
- Database type and version: mysql , 5.6.45
- PHP version:  5.6.38
- OS: Linux
- Browser: FireFox

----------------------

you used ``Null Coalescing`` Operator in ``app/Template/category/index.php`` file at line no. 38

```php
                <?= $this->text->e($category['name']) ?>

                <?php if (! empty($category['description'])): ?>
                    <?= $this->app->tooltipMarkdown($category['description']) ?>
                <?php endif ?>
            </td>
            <td><?= $this->text->e($colors[$category['color_id']] ?? '') ?></td>
        </tr>
        <?php endforeach ?>
    </table>
<?php endif ?>
```
``Null Coalescing`` operator  introduced in PHP 7
[PHP: rfc:null_coalesce_equal_operator](https://wiki.php.net/rfc/null_coalesce_equal_operator)

Minimum Required PHP version for kanboard is [php-versions 5.6](https://docs.kanboard.org/en/latest/admin_guide/requirements.html#php-versions)

**Comment by BlueTeck** [comment]
I think Kanboard should drop support for old PHP versions (5.6 isn't maintained since 1 year already https://www.php.net/supported-versions.php) in favor for new functions and overall security concerns.

**Comment by GaneshKandu** [comment]
@BlueTeck PHP 7.2 is Minimum Version for Kanboard
