### ISSUE TITLE
Corrupt Captcha image

### ISSUE THREAD

**Issue by missytake** [kanboard/kanboard#4377]
### Actual behaviour

Instead of showing the Captcha after failed logins or when you want to reset the password, it just shows the alt-text. If you want to see the captcha, and right click to "view image", it just says "The image "https://todo.0x90.space/?controller=CaptchaController&action=image" cannot be displayed because it contains errors."

When you replay the request with curl, it returns the following file, which seems to be a corrupted jpeg file, generated by gd:

https://oc2.links-tech.org/s/g20GTYwYpHC1Q5Q

No idea what kind of file that is. GIMP gives the most verbose error message when opening it: `Not a JPEG file: starts with 0x0a 0xff`

I looked at it with `hexdump -C`, and it seems to contain the string `CREATOR: : gd-jpeg v1.0 (using IJG JPEG v80), quality = 90` in the beginning; so it seems to be some bug with gd.

### Expected behaviour

A Captcha is displayed.

### Steps to reproduce

1. Open https://todo.0x90.space/forgot-password
2. See that instead of a captcha image, only the alt-text "Captcha" appears
3. Look at the image in the browser: https://todo.0x90.space/?controller=CaptchaController&action=image
4. download it with curl for further debugging: `curl 'https://todo.0x90.space/?controller=CaptchaController&action=image' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cookie: KB_SID=f5mv3qo3g62g22t4em77lbpg3n' -H 'Upgrade-Insecure-Requests: 1' -H 'Cache-Control: max-age=0' -H 'TE: Trailers' --output captcha.jpeg`

### Configuration

- Kanboard version: kanboard/kanboard:v1.2.13 docker container
- Database type and version: docker setup with sqlite
- PHP version: 7.3.11
- OS: alpine I guess.
- Browser: Firefox 71.0

**Comment by fguillot** [comment]
I'm not able to reproduce the issue on my side. I have tested with the same docker image, HTTP and HTTPS.

The only difference I see using your link, is the Content-Type is defined (`content-length: 2784`) were on my side the Transfer-Encoding is Chunked `Transfer-Encoding: chunked`.

- Do you use a reverse-proxy?
- Do you use a different architecture than x86_64? arm?

**Comment by missytake** [comment]
Ah, yes, I use traefik as a reverse proxy. It changes the content type?
or it screws with the chunking? Because with other applications (I also
use it with ownCloud), Traefik gets the chunking right.

**Comment by fguillot** [comment]
I have tested with Traefik v2.1.1 and the captcha is displayed correctly on my side. I have no clue what is going on.
