### ISSUE TITLE
Nginx reverse proxy with Docker

### ISSUE THREAD

**Issue by vinanrra** [kanboard/kanboard#4394]
Hi,

Thanks for this amazing project, but i would like to do a reverse proxy to a subdomain like this:

kanboard.domian.xx

But i am a not very familiar with reverse proxy could anyone help me to do it or give me some info to do it myself?

Im using this docker container to do all my reverse proxy:

https://hub.docker.com/r/linuxserver/letsencrypt/

With this:

https://github.com/linuxserver/reverse-proxy-confs

And if possible i will pull the config to the repository.

Thanks.

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
