### ISSUE TITLE
Disable Tags

### ISSUE THREAD

**Issue by CBEskilstuna** [kanboard/kanboard#4406]
It would be nice if was possible to deactive/disable tags. Not just edit och delete.
A disabled tag would not be seen in the new task dialog.
This way a disabled tag would exist on old task.

**Comment by BlueTeck** [comment]
You could write a plugin, which modifies the task edit dialog.

**Comment by CBEskilstuna** [comment]
That's an option but i'm just a user/admin so i cannot do it by myself

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) for open discussions, suggestions and feature requests. **This bug tracker is reserved only for bugs**.
