### ISSUE TITLE
Converting subtask to tasks creates wrong internal link direction

### ISSUE THREAD

**Issue by double-p** [kanboard/kanboard#4409]
### Actual behaviour
New task is a "parent of"

### Expected behaviour
New task is a "child of".

I think attributing a former subtask as "parent" is upside down from my POV.

### Steps to reproduce
Convert a subtask to a task, check internal links.

### Reference
#2908 added the idea, implementation likely in
Model/SubtaskTaskConversionModel.php 

### Configuration

Application version: 1.2.13
PHP version: 7.3.14
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 3.10.0-1062.4.1.el7.x86_64
Database driver: mysql
Database version: 5.7.24

**Comment by fguillot** [comment]
Tested with version 1.2.19. The relationship seems correct to me.

Main task:

![image](https://user-images.githubusercontent.com/323546/120911928-eb6d9a00-c63f-11eb-89d3-0e864ce5ba4c.png)

Subtask converted to task:

![image](https://user-images.githubusercontent.com/323546/120911933-f1fc1180-c63f-11eb-8220-7325394e67ca.png)

**Comment by davouch** [comment]
I am also having trouble with the same behavior as @double-p and cannot replicate the correct behavior @fguillot presents bellow. (v1.2.20 here)

A subchild converted from a main task gains an internal link status of a parent, and the main task gets to be a child of the converted subtask.
![image](https://user-images.githubusercontent.com/1025752/134486446-2e7d66d7-bf41-4c1e-91df-c2e0d5f3cb05.png)

![image](https://user-images.githubusercontent.com/1025752/134486761-1f42eadb-3875-4dc0-b575-e730aa17c3ca.png)

**Comment by davouch** [comment]
And I believe I could have found the source of the problem in the link labels:
![image](https://user-images.githubusercontent.com/1025752/134487303-d982dde2-5ed8-4447-813f-eb80029eaacd.png)

Not sure if this helps, but I am using:
![image](https://user-images.githubusercontent.com/1025752/134487394-bd32d89e-7807-4a5b-923d-2e691bf70148.png)
