### ISSUE TITLE
Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1 no such table: voting

### ISSUE THREAD

**Issue by chwilley** [kanboard/kanboard#4410]
### Actual behaviour
There was a minor problem with the installed Kanboard: a task cannot be created under the project.
An error appears: InternalError: SqlError: SQLSTATE [HY000]: GeneraError: 1NosuchTable: Voting.

### Expected behaviour
To create a task under the Project.

### Steps to reproduce
1. Log in to the KanBoard system.
2. In the main page after login, Click the Project Name.
3. There are four kanban boards. Click the plus icon "+"on any board to enter the task editing page.
4. After entering any content, click "Save" and the above error will appear:
Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1 no such table: voting
Above.

### Configuration

- Kanboard version:  1.2.13
- Database type and version: sqlite  3.7.17
- PHP version:  7.2.19
- OS:  Linux 3.10.0-514.el7.x86_64
- Browser: Chrome/80.0.3987.106

Any idea how to fix this? I'm using the latest version of KanBoard.
Thanks a lot!

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) for installation issues or questions.
