### ISSUE TITLE
I try to install on Ionos (1und1) web space 

### ISSUE THREAD

**Issue by witzker** [kanboard/kanboard#4418]
This could be a step by step guide for absolute beginners
I hope for support doing this

1)Download zip & Extract it
2) copy files to web space subdomain folder projecs.domain
Q: Must there be a subfolder kanboard or can files be copied directly in projects.domain
3) point the sub domain: projecs.domain to the webspace folder: projecs.domain
4) create mySQL Database in the Ionos controlcenter

followed this link:
https://docs.kanboard.org/en/latest/admin_guide/mysql.html#create-a-config-file

I have now created a file named config.php

And put in my data of database.
! the name is not kanban I got a number instead!
And saved it to projects.domain folder

then I put the domain in the Browser:

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

What’s wrong?

**Comment by BlueTeck** [comment]
cross post https://kanboard.discourse.group/t/install-on-ionos-1und1-webspace/1012/11

**Comment by bugwatcher** [comment]
Please, use the [forum](https://kanboard.discourse.group) for installation issues or questions.
