### ISSUE TITLE
Hide the "group management" tab for users who have the role manager and user

### ISSUE THREAD

**Issue by Richard76000** [kanboard/kanboard#4433]
Hi,

It's is possible to Hide the "group management" tab for users who have the role "manager" and "user" ?

Thanks.

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
