### ISSUE TITLE
Show the color in the combo in Automatic actions

### ISSUE THREAD

**Issue by ngosang** [kanboard/kanboard#4443]
Show the color in the combo in Automatic actions

# Steps to reproduce
Configure project => Automatic actions => Add new action.

### Screenshots
![image](https://user-images.githubusercontent.com/10577978/77212269-c65a3d80-6b06-11ea-8c54-1486f6c52d23.png)

Should be
![image](https://user-images.githubusercontent.com/10577978/77212370-22bd5d00-6b07-11ea-97e1-53806a6af077.png)

### Configuration
    Application version: master.unknown_revision
    PHP version: 7.2.24-0ubuntu0.18.04.3
    PHP SAPI: fpm-fcgi
    HTTP Client: cURL
    OS version: Linux 3.16.81-49
    Database driver: mysql
    Database version: 10.1.44-MariaDB-0ubuntu0.18.04.1
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0

**Comment by SladeP** [comment]
Hi @ngosang, this should now be committed to master and come out with the next release!

**Comment by ngosang** [comment]
Nice! I will test it
