### ISSUE TITLE
Dutch translation of columns could be better IMO

### ISSUE THREAD

**Issue by Ronaldvr** [kanboard/kanboard#4444]
Dutch translation of columns is inadequate

Currently the following is translated:
   'Ready' => 'Klaar',
    'Backlog' => 'Het wachten',
    'Work in progress' => 'In behandeling',
    'Done' => 'Afgewerkt',

Better would be IMO:

    'Ready' => 'Startklaar',
    'Backlog' => 'Achterstallig',
    'Work in progress' => 'Bezig',
    'Done' => 'Afgerond',

**Comment by Ronaldvr** [comment]
Actually even better would probably be:

'Backlog' => 'In afwachting',
'Ready' => 'Startklaar',
'Work in progress' => 'Bezig',
'Done' => 'Afgerond'

(The literal translation of 'Backlog' is indeed 'achterstallig' however within the context this is not what is meant)

**Comment by BlueTeck** [comment]
You could make a PR to change the translation.
