### ISSUE TITLE
failed to start kanboard

### ISSUE THREAD

**Issue by Mechtilde** [kanboard/kanboard#4451]
I installed kanboard on a fresh installation of Debian 10. I get the followig error:

dispatch(); $runner = new Runner($container); $runner->execute(); } catch (Exception $e) { echo 'Internal Error: '.$e->getMessage(); } 

I did the installation with the last release version 1.2.13 and also with git clone of the master branch. Both gaves the same error.

Database is MariaDB 10.3.22
PHP: 7.3.14
Browser: Firefox-ESR 68.6

**Comment by Mechtilde** [comment]
Hello,

I did an installation under Ubuntu 18.04 too. there it works.

Ubuntu 18.04 comes with PHP 7.2 instead of PHP 7.3 which is in Debian 10

So it will not be possible to do an update to the next LTS version of Ubuntu (20.04)

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests, installation issues or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
