### ISSUE TITLE
Issue with DateHelper->duration/lead time & cycle time

### ISSUE THREAD

**Issue by Cyboulette** [kanboard/kanboard#4464]
### Actual behaviour

On task analytics, the cycle time and lead time are wrong.
Example of task :
Due date: 31/05/2020 00:00
Started: 01/01/2020 00:00
Created: 20/01/2020 00:00
We assume that the date of completion is : 08/04/2020

Lead time: 20 days, 10 hours, 31 minutes, 28 seconds
Cycle time: 8 days, 10 hours, 31 minutes, 28 seconds

### Expected behaviour

Lead time: 79 days, 10 hours, 31 minutes, 44 seconds -> 20/01/2020 - 08/04/2020 = 79 days
Cycle time: 98 days, 10 hours, 31 minutes, 44 seconds -> 01/01/2020 - 08/04/2020 = 98 days

### Steps to reproduce

Create a task which has creation date not in the current month.

### Screenshots

Current:
![image](https://user-images.githubusercontent.com/1302000/78769026-0d608380-798d-11ea-8c18-5688052b28f7.png)

Expected:
![image](https://user-images.githubusercontent.com/1302000/78769247-5dd7e100-798d-11ea-877a-f2eabfd74f16.png)

### Potential fix ?
Replace `%%d` by `%%a` in DateHelper.php duration function.
I'm not an expert with PHP dates and i'm not sure if it's the good fix. If someone could confirm the issue and the fix ?

### Logs

N/A

### Configuration

- Kanboard version: 1.2.13
- Database type and version: MariaDB
- PHP version: PHP 7.2
- OS: Centos7
- Browser: Google Chrome

**Comment by liedekef** [comment]
Based on https://www.php.net/manual/en/dateinterval.format.php, I agree.
