### ISSUE TITLE
Bug at Tags management link

### ISSUE THREAD

**Issue by oalexandrino** [kanboard/kanboard#4467]
### Actual behaviour

Tags management procudes error

### Steps to reproduce

Go to Settings > About and after that just click on Tags management. 

Tags management page should be displayed

### Screenshots

Parse error: syntax error, unexpected '?' in /var/www/html/kanboard-1.2.13/app/Template/tag/index.php on line 22

### Logs

Parse error: syntax error, unexpected '?' in /var/www/html/kanboard-1.2.13/app/Template/tag/index.php on line 22

### Configuration

Application version: 1.2.13
PHP version: 5.6.40-26+ubuntu18.04.1+deb.sury.org+1
PHP SAPI: apache2handler
HTTP Client: socket
OS version: Linux 4.15.0-96-generic
Database driver: sqlite
Database version: 3.22.0
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36

**Comment by BlueTeck** [comment]
> PHP version: 5.6.40

This PHP version isn't supported anymore and should be updated as soon as possible.

https://www.php.net/supported-versions.php

**Comment by oalexandrino** [comment]
Nice! I was using on a local server that deals with legacy systems. I have created a new virtualhost to newest PHP version and it works. thanks!

Application version: 1.2.13
PHP version: 7.4.4
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 4.15.0-96-generic
Database driver: sqlite
Database version: 3.22.0
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36
