### ISSUE TITLE
Contributing to kanboard

### ISSUE THREAD

**Issue by objecttothis** [kanboard/kanboard#4472]
### Actual behaviour

I am a dev an was looking for a replacement KanBan opensource project for my team when I came across Kanboard.  I noticed in the requirements page (https://docs.kanboard.org/en/latest/admin_guide/requirements.html) though that Kanboard and Apache mod_security don't play well together.  I found bug reports #3308 and #3263 here but both were shut down with the response that it is not compatible.  Neither gives any indication that there is intention to deal with the problem.

I'm willing to try to contribute to the project to see if I can either come up with a PR to resolve the issue or contribute to the documentation on how to configure mod_security so that it does not block Kanboard from operating properly.

To do so, I could use whatever is already known about the issue... that is what is known about why mod_security complains, and then I can get to work.

### Expected behaviour

Kanboard to work properly with mod_security enabled.

### Steps to reproduce

see #3308

### Configuration

- Kanboard version: Latest
- Database type and version: MySQL 5.7.29_1
- PHP version: 7.7.4
- OS: FreeBSD 11.2-RELEASE-r6
- Browser: Firefox Developer Edition 76.0b4

**Comment by fguillot** [comment]
`mod_security` doesn't seems to like URLs with a query string. This problem could be solved by using "nice" URLs instead. Some routes might be missing in this file: https://github.com/kanboard/kanboard/blob/master/app/ServiceProvider/RouteProvider.php

**Comment by objecttothis** [comment]
Thanks, I'll investigate and submit a PR.
