### ISSUE TITLE
enabling debug disables comment editing

### ISSUE THREAD

**Issue by Chaosmeister** [kanboard/kanboard#4475]
### Actual behaviour

As soon as I enable debug mode
`#define('DEBUG', true);`
noone can edit their comments anywhere.

The Edit-button does not bring up the modal box

Creating new comments and deleting comments works.

### Expected behaviour

Debugmode should not tamper comment editing

### Steps to reproduce

1. Enable Debugmode.
2. Try to edit comments.

### Screenshots

![image](https://user-images.githubusercontent.com/13346344/79451398-cc98e800-7fe6-11ea-916b-0babb8b9a66c.png)

### Configuration

Version: 1.2.14
PHP Version: 7.2.30
PHP SAPI: apache2handler
HTTP-Client: cURL
OS Version: Linux 3.10.0-1062.18.1.el7.x86_64
Datenbanktreiber: mysql
Datenbank Version: 5.5.64-MariaDB
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

### Plugins

![image](https://user-images.githubusercontent.com/13346344/79451610-17b2fb00-7fe7-11ea-867a-dceede9b2937.png)

**Comment by fguillot** [comment]
Try to uninstall the plugins to see if there a compatibility issue.

**Comment by Chaosmeister** [comment]
Heyo,

yes it's an issue of MarkdownPlus. I'll move over there!
