### ISSUE TITLE
Upgrade to 1.2.14 fails with "Required MYSQL version greater than equal to 10.0.0 AND found version is : 5.6.40"

### ISSUE THREAD

**Issue by krheinwald** [kanboard/kanboard#4478]
Trying to update from 1.2.3 to 1.2.4 with Plesk/Softaculous.

Upgrade is aborted with error "Required MYSQL version greater than equal to 10.0.0 AND found version is : 5.6.40"

- Kanboard version: 1.2.3 -> 1.2.4
- Database type and version: mySQL 5.6.40
- PHP version: 7.4.4
- OS: Linux

**Comment by fguillot** [comment]
Your issue is probably related to Plesk/Softaculous.

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for installation issues.

**Comment by krheinwald** [comment]
Upgrade to 1.2.18 worked through Softaculous.
