### ISSUE TITLE
Content Security Policy issue

### ISSUE THREAD

**Issue by liedekef** [kanboard/kanboard#4482]
### Actual behaviour

This appears in my console on every page load:
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). sandbox eval code:17:35

### Configuration

- Kanboard version: latest dev
- Database type and version: mariadb (but not relevant)
- PHP version: php 7.2
- OS: Ubuntu 18.04 LTS
- Browser: firefox 75.0

**Comment by liedekef** [comment]
Btw, this seems to be due to the csprules defined in app/ServiceProvider/ClassProvider.php:
```
        $container['cspRules'] = array(
            'default-src' => "'self'",
            'style-src' => "'self' 'unsafe-inline'",
            'img-src' => '* data:',
        );
```
together with jquery and eval-usage. This is a discussion on that part and offers a jquery solution too:
https://statuscode.ch/2017/03/CSP-unsafe-eval-and-jquery
I'm leaving this up to you guys to consider this.

**Comment by fguillot** [comment]
Did you install any plugins? If yes, try to uninstall them to see if one of them is using inline Javascript.

Kanboard is blocking inline Javascript for Security reasons.

**Comment by liedekef** [comment]
I most humbly apologize ...
At first I disabled all plugins but still had the issue. Then I looked further and it is some firefox plugin that causes this. So not related to kanboard at all.
