### ISSUE TITLE
Popups on hover not working after moving a task between columns

### ISSUE THREAD

**Issue by liedekef** [kanboard/kanboard#4483]
### Actual behaviour

When you have a task with subtasks, you can hover over the icon to see the subtasks in the kanboard view. However, after moving a task, this hover no longer pops up the subtasks (for the move task or any other task). Refreshing the window is needed to make that work again.

### Expected behaviour

Hovering should always show the expected popup.

### Logs

Unfortunately no logs, not even in the browser console. So I assume some javascript is blocking it based on a security policy after moving a task.

### Configuration

- Kanboard version: latest dev version
- Database type and version: mariadb
- PHP version: 7.2
- OS: Ubuntu 18.04 LTS
- Browser: Firefox 75.0

**Comment by liedekef** [comment]
To the dev's: this seems to be because the move is an ajax call and the page gets replaced dynamically, but this causes the javascript events mouseenter and mouseleave to no longer be bound, see core/tooltip.js . The usage of jquery "on" syntax would solve this imho, something like this:

`$(".tooltip").on("mouseenter", ...);`

This also avoids the need of looping through al tooltips:
```
var elements = document.querySelectorAll(".tooltip");
for (var i = 0; i < elements.length; i++) {
...
}
```
so it would simplify the page a lot. But since I don't have a combined js-file that is not minified, it is very hard to test.

**Comment by liedekef** [comment]
I've managed to fix this, using jquery 'on' way of things. But I saw this old code change:
https://github.com/kanboard/kanboard/commit/5996a8abcf12336586cee345180203dd1500c92f#diff-5d3f61a6b3766bb76bb68b9a3af2a392 (where it says "tooltip rewritten without jquery), so I'm wondering if you'll accept a fix for this in jquery style?

**Comment by SladeP** [comment]
I'm not able to replicate the bug behavior you describe. I created a task and a subtask for it and am using the board view and moving tasks around.

You also should be able to generate a minified js file with your changes for testing by following instructions here: https://docs.kanboard.org/en/latest/developer_guide/assets.html

**Comment by liedekef** [comment]
I can move the tasks just fine, it is the tooltip hover that is no longer working after moving tasks around. And I confirmed it with the latest kanboard here.

**Comment by SladeP** [comment]
Glad you figured out the minified js. So you are able to get your fix tested on your local? Strange because using the tooltip hover works fine for me even after moving tasks around on the most recent kanboard version.

**Comment by liedekef** [comment]
Well,I delved further into the code and KB.tooltip function gets called after drag and drop, so it should be working.
So I went back to testing and it seems Bigboard is causing the problem. Although my fix seems to working even when Bigboard is installed :-)

**Comment by SladeP** [comment]
Oh interesting, so it's a Bigboard bug, that makes more sense.

**Comment by liedekef** [comment]
Well, my pull request should be ok for all in fact, and solves the bigboard issue in one go too.
Although, using my fix, the creation of the event listeners could even go outside of KB.Tooltip and save more cycles. Anyway I leave that up to you guys and I also created an issue on the bigboard github page for this.

**Comment by SladeP** [comment]
I leave the decision up to the project maintainer, I just interjected because I couldn't replicate. Thanks for your time and contribution!
