### ISSUE TITLE
docs.kanboard.org partially down

### ISSUE THREAD

**Issue by SladeP** [kanboard/kanboard#4490]
Certain pages give an error of "too many redirects", while other pages work fine.

Pages with Redirect Errors
- https://docs.kanboard.org/en/latest/
- https://docs.kanboard.org/en/latest/user_guide/index.html

Pages That Work
- https://docs.kanboard.org/en/latest/admin_guide/docker.html

Trying to contribute and can't see the documentation I need. I wasn't sure where else to report this, so sorry if it doesn't belong in the actual repo!

**Comment by fguillot** [comment]
It should work now. Thanks.

**Comment by SladeP** [comment]
Fantastic, thank you!
