### ISSUE TITLE
plugin-gitlab-auth

### ISSUE THREAD

**Issue by xwinie** [kanboard/kanboard#4494]
plugin-gitlab-auth
这个项目已归档，新版本gitlab用什么插件？

**Comment by liedekef** [comment]
I think you can use the plugin plugin-oauth2 to connect to gitlab.

**Comment by xwinie** [comment]
@liedekef  不一样哈，plugin-oauth2需要用户知类的，gitlab只是纯的 和gitlab 服务的东西。我从文档里面未能看出其他操作。

**Comment by liedekef** [comment]
Sorry, but then I can't help here :-)

**Comment by fguillot** [comment]
Please, write in English even if you don't speak English. And, use the forum for questions: https://kanboard.discourse.group/

https://docs.kanboard.org/en/1.2.14/developer_guide/faq.html#how-to-make-a-bug-report
