### ISSUE TITLE
There is no plugin available. reported when trying to install more plugins

### ISSUE THREAD

**Issue by cjohnsonuk** [kanboard/kanboard#4501]
Previously covered in https://github.com/kanboard/kanboard/issues/3347 but this issue is locked for further comments so opening again here as that is also 3 years old..

**Actual behaviour**
Log in as admin, go to plugins, Plugin directory (https://dev.welfarecall.com/projects/?controller=PluginController&action=directory) and it shows: 

There is no plugin available.

I tried curl -v https://kanboard.net/plugins.json
and it comes back with 

`> CONNECT kanboard.net:443 HTTP/1.1
> Host: kanboard.net:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=kanboard.net
*       start date: Apr 04 06:46:41 2020 GMT
*       expire date: Jul 03 06:46:41 2020 GMT
*       common name: kanboard.net
*       issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
> GET /plugins.json HTTP/1.1
> User-Agent: curl/7.29.0
> Host: kanboard.net
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Length: 162
< Content-Type: text/html
< Date: Tue, 05 May 2020 15:25:55 GMT
< Location: https://kanboard.org/plugins.json
< Server: nginx
<
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
`
so its making a connection and most likely not a firewall issue
I tried 
`wget https://kanboard.net/plugins.json`

This works and brings back the json file

**Expected behaviour**
Shows a list of plugins to install

**Configuration**
Application version: 1.2.14
PHP version: 7.2.30
PHP SAPI: apache2handler
HTTP Client: cURL
OS version: Linux 3.10.0-1062.9.1.el7.x86_64
Database driver: mysql
Database version: 10.1.44-MariaDB
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

**Recent Changes**
Upgraded to latest version 1.2.14 from 1.2.13 where it worked fine.  No other changes I'm aware of although I do keep the server up to date and don't always check the plugins work after every server update

**Comment by fguillot** [comment]
Does your installation meets all these requirements? https://docs.kanboard.org/en/1.2.14/admin_guide/plugins.html

> 
    The plugin directory must be writeable by the web server user
    The Zip extension must be available on your server
    The config parameter PLUGIN_INSTALLER must be set to true

**Comment by cjohnsonuk** [comment]
Thanks for getting back so quickly.

> The plugin directory must be writable by the web server user

plugin folder permissions
`drwxrwxr-x. 26 apache apache  4096 May  6 10:37 plugins`
All files in the directory are also owned by apache.

> The Zip extension must be available on your server

Zip | enabled
-- | --
Zip version | 1.18.2
Libzip headers version | 1.6.1
Libzip library version | 1.6.1

> The config parameter PLUGIN_INSTALLER must be set to true

`// Plugins directory
define('PLUGINS_DIR', 'plugins');

// Plugins directory URL
define('PLUGIN_API_URL', 'http://kanboard.org/plugins.json');

// Enable/Disable plugin installer
define('PLUGIN_INSTALLER', true);
`

I've rerun the centos installation instructions from https://docs.kanboard.org/en/1.2.14/admin_guide/rhel_installation.html

but the issue is still present.

**Comment by fguillot** [comment]
Note that the actual URL is https://kanboard.org/plugins.json (this avoid a redirection).

**Comment by liedekef** [comment]
Maybe check that the json and curl extensions are loaded in your php installation, and that no firewall is blocking the request from your webserver to https://kanboard.org/plugins.json

**Comment by lokkelvin2** [comment]
I also faced this issue, and initially thought it was a http vs https typo in my config.php file. Turns out all I needed to do was to restart my apache server a couple of times and the 301 error went away. 

Hope this helps anyone facing the same problem.
