### ISSUE TITLE
Add comment -> Send by e-mail does not include any links to the task

### ISSUE THREAD

**Issue by psy-q** [kanboard/kanboard#4504]
### Actual behaviour

When adding comments and selecting "send by e-mail", the recipient will only receive the raw comment text. No links to Kanboard or the task, not even any indication that it was Kanboard that sent the e-mail.

### Expected behaviour

Comments sent in this way contain the same information as with e.g. "Send task by e-mail" or when using @-mentions.

At least a link to the task and an explanation that the message was sent via Kanboard should be there, otherwise this is confusing for users since they receive strings of text without any context.

### Steps to reproduce

  1. Click on a task
  2. Select "Add comment"
  3. Select "send by e-mail" in the comment form
  4. Select a recipient and enter a comment
  5. As the recipient, receive the message
  6. Observe that the message contains only the raw comment string, making it nonsense unless the user gives complete context in the comment itself (which would be redundant)

### Screenshots

![kanboard_comment](https://user-images.githubusercontent.com/87557/81530881-06e57300-9362-11ea-8b0e-9660b2e87572.png)

### Configuration

- Kanboard version: 1.2.14

**Comment by fguillot** [comment]
Fixed in version 1.2.16
