### ISSUE TITLE
Plugin development technologies

### ISSUE THREAD

**Issue by rooooose** [kanboard/kanboard#4508]
Hi,
I’m a student who tries to develop a plugin on Kanboard, and I was wondering what technologies are used :

- Symfony ?
- Doctrine ?
- others ?

Could you give me some hints to help me start my plugin development (other than what’s written on Kanboard’s Official Documentation)?
I have already created the base of my plugin with CookieCutter.

Thanks very much for your help

**Comment by BlueTeck** [comment]
I would suggest to take a look at other plugins.

For database queries, this might help: https://github.com/kanboard/kanboard/blob/master/libs/picodb/README.md

The other dependencies could be found here: https://github.com/kanboard/kanboard/blob/master/composer.json

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
