### ISSUE TITLE
Internal Error: This software requires PHP 7.2.0 minimum

### ISSUE THREAD

**Issue by larmien** [kanboard/kanboard#4512]
After I install Kanboard 1.2.14, I receive the following error "Internal Error: This software requires PHP 7.2.0 minimum". The hosting server has PHP 7.2

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by jack1729** [comment]
Not sure of your hosting environment, but it may need to be told which version of PHP to use (your site could be configured to use a different version of PHP if you have multiple versions available)

**Comment by larmien** [comment]
Thanks @jack1729 the Lowest Hosting CPanel > Softaculous installation for Kanboard was updated to 1.2.15 and it appears to see the properly assigned version of PHP. Everything is working now.
