### ISSUE TITLE
Some missing features

### ISSUE THREAD

**Issue by HumanG33k** [kanboard/kanboard#4558]
Hello,

At the [April](https://www.april.org/) we [setup](https://www.chapril.org/) for the chatons (kittens) initiative  a [kanboard instance](https://kanban.chapril.org).
It s a "public" one. But in order to respect the [GRPD](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) users should delete and export their data.
By order of priority : 
- user should be able to delete their account (as admin can do for all)
- an export function should exist to export project in one or other open format. do not have a clue about the one can fit.

thx a lot for your great work.

**Comment by HumanG33k** [comment]
@fguillot what do you think about it ?

**Comment by HumanG33k** [comment]
back here. @fguillot 

I also want to add version on login page maybe throught an option : 
In config.php
```php
// Show/hide version and software name on the login page.
define('SHOW_VERSION', false);


```  
And something like that in 
app/Template/auth/index.php
```php
    <a href="https://kanboard.org/" target="_blank" rel="noopener noreferrer">https://kanboard.org/</a>
    | <strong><?= APP_VERSION ?></strong>

```

It's not the final version. I want advice about it. If i make a push request do you accept it ? Maybe i want add some text but i dont know if i only have to had the tag and the the translation in files (in locales) ?

Also do you think there is a way to set the new users to manager by default ?

**Comment by HumanG33k** [comment]
I really want a feedback on this if possible.

**Comment by fguillot** [comment]
Send a PR if you need new features.
