### ISSUE TITLE
hide columns not permanent

### ISSUE THREAD

**Issue by proserver1** [kanboard/kanboard#4570]
### Actual behaviour

hiding columns not permanent. when moving cards or changing project, hidden columns are shown again

### Expected behaviour

"hide column" is a permanent setting (as it was until shortly)

### Steps to reproduce

just switch project and back, colums are shown

### Configuration

    Version: 1.2.15
    PHP Version: 7.3.19-1~deb10u1
    PHP SAPI: fpm-fcgi
    HTTP-Client: cURL
    OS Version: Linux 4.19.0-8-amd64
    Datenbanktreiber: mysql
    Datenbank Version: 10.3.22-MariaDB-0+deb10u1
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

reproducable with chrome (latest) and therefore other login/session too
deleting coolies / site data and fresh login doesnt change behaviour

**Comment by SladeP** [comment]
Hello, I am unable to replicate this bug. Looks like the hidden columns are stored in local storage, so when you switch browsers or use incognito mode, that would unhide the columns. Are you staying with the same browser window and then changing projects?

**Comment by vvzh** [comment]
I can reproduce it. No incognito mode, same browser (Firefox 80). There is even easier case for me:
- Hide a column
- Hit Refresh / F5 (column is hidden as expected)
- Hit Refresh / F5 once more (column is visible again)

The problem started after upgrade from 1.2.13 to 1.2.15.

**Comment by proserver1** [comment]
I stay within one browser tab (other tabs open, other browser open): 

- hide columns in project A
- switch to project B
- switch back to A
= columns are unhidden/shown

same behavior in firefox and chrome (on Linux Ubuntu)

just checked: android 9 ghost and chrome reproducable

**Comment by proserver1** [comment]
like vvzh said, hitting refresh twice does the same (here)

**Comment by proserver1** [comment]
seems fixed with chrome and firefox (linux): Application version: 1.2.16
