### ISSUE TITLE
In Firefox, the vertical bars separating columns are missing, background color wrong

### ISSUE THREAD

**Issue by psy-q** [kanboard/kanboard#4573]
When using the default theme, the board looks wrong in Firefox (78.0.1), the background is grey instead of white and the lines separating columns are misisng:

![firefox](https://user-images.githubusercontent.com/87557/89393785-8c7f8180-d70b-11ea-8648-3937fbf17a79.png)

Whereas in Chromium-based browsers, it looks like this:

![chromium](https://user-images.githubusercontent.com/87557/89393809-94d7bc80-d70b-11ea-9e08-1fb25fe65230.png)

**Comment by fguillot** [comment]
Do you have any plugins installed?

Here is what I see with Firefox 79.0:

![image](https://user-images.githubusercontent.com/323546/89975609-07203380-dc1b-11ea-8256-4029bf759aba.png)

**Comment by psy-q** [comment]
Unfortunately, it also looks wrong with all plugins disabled (and on Firefox 79 as well) :(  There is no custom CSS. I can't seem to figure out why this is happening.
