### ISSUE TITLE
Public link: Sub tasks are not shown on tasks

### ISSUE THREAD

**Issue by k00ni** [kanboard/kanboard#4576]
### Actual behaviour

When opening a board using the public link, sub tasks are not shown on a task.

### Expected behaviour

When opening a board using the public link, sub tasks are shown on a task.

### Steps to reproduce

1. Create a task
2. Create a sub task in that task
3. Open the board's public link
4. Click on the task
5. No sub tasks shown

### Screenshots

**Backend view (list of sub tasks):**

![Bildschirmfoto von 2020-08-11 15-17-46](https://user-images.githubusercontent.com/381727/89902117-57c96980-dbe6-11ea-93c4-65f5c1760218.png)

**Public link: after opening the related task**:

![Bildschirmfoto von 2020-08-11 15-18-52](https://user-images.githubusercontent.com/381727/89902330-9bbc6e80-dbe6-11ea-84fd-01af5a7b7bee.png)

### Configuration

- Kanboard version: 1.2.15
- Database type and version: 5.7.x
- PHP version: 7.3
- OS: Ubuntu
- Browser: Chromium

**Comment by fguillot** [comment]
Do you have any plugins installed? Are they compatible with this version of KB?

I can see the subtasks in the public view:

![image](https://user-images.githubusercontent.com/323546/89975442-9e38bb80-dc1a-11ea-9134-a35065eb6192.png)

**Comment by k00ni** [comment]
You are right, the problem was the plugin "Time Tracking Editor": https://github.com/stinnux/kanboard-Timetrackingeditor

Thank you for the feedback. Will open an issue there.
