### ISSUE TITLE
PHP Version Issue

### ISSUE THREAD

**Issue by Minds-Collide** [kanboard/kanboard#4577]
Have installed Kanboard Version 1.2.15 (June 19, 2020) in a hosted environment using Softaculous App installer in the folder pm on the hosting. Attached are the details

![Hosting Details](https://user-images.githubusercontent.com/28528423/89997294-66c32100-dca5-11ea-8d4c-ee7694e5b523.png)

On trying to open the url http://minds-collide.com/pm/ it gives the below error
Internal Error: This software requires PHP 7.2.0 minimum

Please guide what needs to be done

**Comment by meskobalazs** [comment]
This is the code in `check_setup.php`:
```
// PHP 7.2.0 minimum
if (version_compare(PHP_VERSION, '7.2.0', '<')) {
    throw new Exception('This software s PHP 7.2.0 minimum');
}
```
I would echo the value of `PHP_VERSION` with the exception:
```
throw new Exception('This software s PHP 7.2.0 minimum (current version: ' . PHP_VERSION . ')');
```
and see what it says.

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for installation issues, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
