### ISSUE TITLE
[ux] Wrong error message on avatar upload

### ISSUE THREAD

**Issue by tborychowski** [kanboard/kanboard#4584]
### Actual behaviour
Error message is: "Unable to upload files, check the permissions of your data folder."

### Expected behaviour
Error message should be: "No file selected." (or similar)

### Steps to reproduce
1. Go to: My Profile/Avatar
2. Without selecting a file, click on the button "Upload my avatar image"

### Screenshots
<img width="720" alt="Screenshot 2020-08-28 at 13 14 00" src="https://user-images.githubusercontent.com/392513/91559630-590dcc80-e930-11ea-883f-2bcc8d2ea3e2.png">

### Logs
irrelevant

### Configuration
- Application version: v1.2.15
- PHP version: 7.3.19
- PHP SAPI: fpm-fcgi
- HTTP Client: cURL
- OS version: Linux 5.4.0-42-generic
- Database driver: sqlite
- Database version: 3.32.1
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:81.0) Gecko/20100101 Firefox/81.0

Running on docker.

**Comment by HumanG33k** [comment]
We have the same error on the previous version. 
It's a real right issues or a miss configuration ?

**Comment by tborychowski** [comment]
In my case it's an issue. I tried changing permissions to the folder (even with 777) and didn't make any difference.

**Comment by HumanG33k** [comment]
We have the same issue here. But always have to check perm when we have this kind of issues. I have to take time to investigate furthermore but i'm really busy for several weeks.

**Comment by Trylam** [comment]
Hi, 
I have the same problem and I solve it : in your config.php there is : 
`define('UPLOAD_TMP_DIR', __DIR__.DIRECTORY_SEPARATOR.'upload_tmp_dir');`
I create the folder "upload_tmp_dir" and I give it the good right and it works for me.
I hope this helps you.

**Comment by orkutmuratyilmaz** [comment]
> `define('UPLOAD_TMP_DIR', __DIR__.DIRECTORY_SEPARATOR.'upload_tmp_dir');`

I've been trying this one with different variations, but it doesn't work. My data directory belongs to web server and chmod 755 is done.
