### ISSUE TITLE
External link bug

### ISSUE THREAD

**Issue by Mystico-htb** [kanboard/kanboard#4591]
Dear developers, i am a security researcher and found a potential bug in your software. I observed that when creating a external link i can access internal ports. With this it is possible for attackers to do a port scan and see which ports are open that should not be visible to outsiders. 

*** REPRODUCE STEPS***

1) Log in
2) Create New project with whatever name
3) Go to Overview in the Dashboard and click in the project name
4) Click in one of the + signs and create a new task
5) Click in the task, and go to Add external link
6) Add a link pointing to a localhost resource, such as http://127.0.0.1:8000

Looking forward to your response

**Comment by fguillot** [comment]
It's not a bug. http://127.0.0.1:8000 is a valid URL. Nothing wrong about running a web server locally.
