### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by avijc** [kanboard/kanboard#4595]
I recently updated the lighttpd on my Kanboard server to a version that supports HTTP/2.

When I try to log in I get the usual login form. I fill in my username and password and press the Sign in button. After that I get the same login form again, with texts "The username is required" and "The password is required" in red.

Disabling the HTTP/2 protocol from lighttpd lets me log in normally.

I have not tested, but I think this would also happen on other HTTP/2-capable servers such as recent versions of Apache httpd and nginx. I see various constructs in the source code that seem to work only with HTTP/1.x.

Could Kanboard be fixed to support HTTP/2?

- Kanboard version: 1.2.15
- Database type and version: sqlite
- PHP version: 7.2.24
- OS: CentOS 8.2.2004
- Browser: Chrome 85.0.4183.83
- lighttpd 1.4.56 (pre-release)

**Comment by avijc** [comment]
The login issue was apparently related to cookie handling on the server side, which has now been fixed and I can log in now.

Regardless, the following parts of code may need amending for proper HTTP/2 support:

```
$ grep -r HTTP/1
app/Core/Http/Client.php:            if (strpos($line, 'HTTP/1') === 0) {
libs/jsonrpc/src/JsonRPC/HttpClient.php:                if (strpos($header, 'HTTP/1.0 '.$code) !== false || strpos($header, 'HTTP/1.1 '.$code) !== false) {
libs/jsonrpc/src/JsonRPC/Response/ResponseBuilder.php:            $this->status = 'HTTP/1.0 401 Unauthorized';
libs/jsonrpc/src/JsonRPC/Response/ResponseBuilder.php:            $this->status = 'HTTP/1.0 403 Forbidden';
vendor/symfony/contracts/HttpClient/Test/Fixtures/web/index.php:        header('HTTP/1.1 103 Early Hints');
vendor/symfony/contracts/HttpClient/Test/Fixtures/web/index.php:        echo "HTTP/1.1 200 OK\r\n";
vendor/symfony/contracts/HttpClient/Test/HttpClientTestCase.php:        $this->assertSame('HTTP/1.1 200 OK', $info['response_headers'][0]);
vendor/symfony/contracts/HttpClient/Test/HttpClientTestCase.php:        $this->assertSame('HTTP/1.1', $body['SERVER_PROTOCOL']);
vendor/symfony/contracts/HttpClient/Test/HttpClientTestCase.php:        $this->assertSame('HTTP/1.1 200 OK', $info['response_headers'][0]);
vendor/symfony/contracts/HttpClient/Test/HttpClientTestCase.php:        $this->assertSame('HTTP/1.0 200 OK', $response->getInfo('response_headers')[0]);
vendor/symfony/contracts/HttpClient/Test/HttpClientTestCase.php:        $this->assertSame('HTTP/1.0', $body['SERVER_PROTOCOL']);
vendor/symfony/contracts/HttpClient/Test/HttpClientTestCase.php:            'HTTP/1.1 301 Moved Permanently',
vendor/symfony/contracts/HttpClient/Test/HttpClientTestCase.php:            'HTTP/1.1 302 Found',
vendor/symfony/contracts/HttpClient/Test/HttpClientTestCase.php:            'HTTP/1.1 200 OK',
vendor/symfony/contracts/HttpClient/Test/HttpClientTestCase.php:            'HTTP/1.1 301 Moved Permanently',
vendor/symfony/contracts/HttpClient/Test/HttpClientTestCase.php:            'HTTP/1.1 302 Found',
vendor/symfony/contracts/HttpClient/Test/HttpClientTestCase.php:            $this->assertSame('HTTP/1.1', $body['SERVER_PROTOCOL']);
```

**Comment by fguillot** [comment]
HTTP/2 works fine. I'm using it everyday with Nginx or Traefik. The code above is not relevant for this context because the application is always behind a reverse-proxy.

The issue you are facing is most likely a configuration issue on your side. Using the forum for installation issues is the way to go.
