### ISSUE TITLE
Attaching a jpg file bigger than 950KB is not possible while there is no problem with other file types!

### ISSUE THREAD

**Issue by erpnedir** [kanboard/kanboard#4599]
### Actual behaviour

I cannot upload a jpg bigger than 1MB, while I can upload other file types (pdf, mp3) bigger than 2MB.

### Expected behaviour
If there is a size limit it must be the same to all file types. 
There is something wrong with image uploading.

### Steps to reproduce
Open the board on mobile browser
Click on task dropdown menu
Select Attach a Document menu item
Select an image file bigger than 1MB
Click on Upload Files button
--- The progress bar fills up to %100 percent but the rounding icon on the button never stops.
### Screenshots

![upload Problem](https://user-images.githubusercontent.com/16351692/92937812-75dbf100-f454-11ea-8e4a-ac8d8362784c.png)

### Configuration

- Kanboard version: 1.2.15
- Database type and version: mysql 5.6.47
- PHP version:7.2.32
- Web Server: Litespeed 5.4.7
- OS: Linux 3.10.0-427.36.1.lve1.4.47.el7.x86_64
- Browser: Chrome on Adroid

**Comment by erpnedir** [comment]
The problem seems about jpg files. I could add png files bigger than 1MB, while any jpg bigger than 500K cannot load. It is interesting that small jpg around 100K can be loaded!

**Comment by unibravo** [comment]
Working at PHP 7.4.

**Comment by erpnedir** [comment]
Thank you very much. I upgraded PHP and now it works without any problem.
