### ISSUE TITLE
Support webhook for discord ?

### ISSUE THREAD

**Issue by DaFray31** [kanboard/kanboard#4609]
Hi,
Trying to put the webhook link for Discord integration does not return anything. 
Have I done something wrong ?
If this is not possible, is it possible to make a discordant integration ? 
Regards,
DaFray31

**Comment by fguillot** [comment]
The Kanboard webhook is not meant to work with Discord. Look at the docs: https://docs.kanboard.org/en/latest/developer_guide/webhooks.html
