### ISSUE TITLE
Time Tracking Reports

### ISSUE THREAD

**Issue by ameeriqbal** [kanboard/kanboard#462]
Hi

I think its good if we can identify what a developer is doing on each day and what is the happenings on each project. Please find the following link: https://ehour.nl/demo.phtml. It will be great if we can implement similar feature before next stable release.

**Comment by gmdesousa** [comment]
It would be nice to have a graph saying how many time the tickets are spending on each column

**Comment by crabnky** [comment]
Hi
Any news on this? It would be super if I have ability to export hours worked by user on specified project or/and specified time frame. I assume this would require a multiple time entry per task - now I'm able to enter to the task the total time spent, or add subtasks.
Thanks!

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
