### ISSUE TITLE
Occasionally not loading CSS

### ISSUE THREAD

**Issue by francis-io** [kanboard/kanboard#4649]
### Actual behaviour
When clicking `+` to add a new tasks on a column, sometimes I get sent to a page without any styling. The URL is like `https://<domain>/?controller=TaskCreationController&action=show&project_id=5&column_id=20&swimlane_id=5` instead of loading the task creation forms on the same page.

This is intermittent, but seems to happen at the same time. E.G. it wont happen for a while, but every so often, each new task will load a page like this. 

I have ran chrome without extensions via `google-chrome --disable-extensions` and I still get this issue.

### Expected behaviour

The new task window always should load, with style.

### Steps to reproduce
I can't reproduce this consistently. 

### Screenshots
![Selection_019](https://user-images.githubusercontent.com/10199020/97082696-8959aa80-1603-11eb-9212-97336ed24888.png)

### Logs
Nothing appears when I tail the logs of the kanboard container.

### Configuration

- Kanboard version: Docker latest amd64
kanboard/kanboard:sha256:0c4c9f979bb38e5ad30076df620ada33e03654197835c5274758066707d2ed78
- Database type and version: Docker postgres:9-alpine latest
- PHP version: What ever is installed in the official latest docker container.
- OS: Ubuntu 20.04.1 LTS - 5.4.0-51-generic
- Browser: Google Chrome 86.0.4240.75

**Comment by fguillot** [comment]
You should take a look at the logs to see where the problem is coming from:

- Look at the web server logs (for example Apache / Nginx)
- Look at PHP-FPM logs if you use it
- Look at the web browser console errors
- Look at Kanboard logs
- etc.

**Comment by francis-io** [comment]
It looks like the way to recreate this is to try to add a new task before the page is fully loaded. This seems to recreate the issue every time.
