### ISSUE TITLE
Default profile for LDAP users

### ISSUE THREAD

**Issue by andersonprante** [kanboard/kanboard#4654]
### Actual behaviour
I know how i can define manager users in specific AD group, but...

### Expected behaviour
How cai i set all users ldap as managers?

- Kanboard version: 1.2.16
- Database type and version: mysql
- PHP version: 7.3
- OS: centos 7
- Browser: Chrome / Firefox

**Comment by eSkiSo** [comment]
A quick and dirty way to do it is just change the **users** table default value for column **role** from **app-user** to **app-manager**

**Comment by fguillot** [comment]
If you bother to read the docs, you will see there is an option for that:

- https://docs.kanboard.org/en/latest/admin_guide/config_file.html#ldap-settings
- https://github.com/kanboard/kanboard/blob/master/config.default.php#L165
