### ISSUE TITLE
Bigger project titles and project details under project titles

### ISSUE THREAD

**Issue by makayjozsef** [kanboard/kanboard#4659]
Change request on kanboard/app/Template/dashboard/...
- overview.php 
- projects.php  
- tasks.php

Make the titles of the projects and tasks bigger and/or bolder. It would be much better during the work.

Change request on kanboard/app/Template/dashboard/...
- overview.php 
- projects.php  

Show the colored project's tags under the project titles. We could see the important projects between the normals.

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
