### ISSUE TITLE
Kanboard think i reject the cookies

### ISSUE THREAD

**Issue by stemy2** [kanboard/kanboard#4661]
### Actual behaviour
I have this error when i'm trying to login, even if cookies are actually enabled.
```
The page is not correctly redirected

An error occured during the connection to kanboard.stemy.me.

The cause of this problem may be the disabling or the reject of the cookies.

```
### Expected behaviour

Successful login.

### Steps to reproduce

1. Install the app
2. Try to login

### Configuration

- Kanboard version: 1.2.16
- Database type and version: don't know
- PHP version: 7.3
- OS: yunohost (based on debian)
- Browser: Firefox ESR

**Comment by fguillot** [comment]
This message is not coming from Kanboard.

Please, use the forum https://kanboard.discourse.group/ for installation issues.
