### ISSUE TITLE
broken link in user invitation mail

### ISSUE THREAD

**Issue by agreif** [kanboard/kanboard#4664]
### Actual behaviour

in thunderbird 68.5.0
the email "Kanboard Invitation" 
1) contains a a-href "Click here to join your team" that changes the curson on hover but
- clicking on the Link ... nothing happens
- Copying the link location from the context menu ... copies nothing
2) the generated link url doese not contain the url protocol. 

### Expected behaviour

1) clicking in the link should open a browser window with the defined URL
2) the 'href' attribut of the link should contain the protocol prefix 'https://' or 'http://' depending on the browser context where the invitation was initiated.

### Steps to reproduce

1. invite a user via emailadress
2. open the mail in thunderbird 68.5.0
3. klick on the links

### Configuration

    Application version: 1.2.16
    PHP version: 7.4.12
    PHP SAPI: fpm-fcgi
    HTTP Client: cURL
    OS version: Linux 3.10.0-1127.19.1.el7.x86_64
    Database driver: sqlite
    Database version: 3.7.17
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0

**Comment by fguillot** [comment]
I can't reproduce. I see the url scheme in the email and the link works.

Make sure the application URL is defined correctly.
