### ISSUE TITLE
Notifiacition every 5 minutes

### ISSUE THREAD

**Issue by nykroy** [kanboard/kanboard#4665]
### **This issue is:**

- [x]  Bug report
- [ ] Feature request
- [ ]  Improvement

### **Actual behaviour**

Telegams notifications are sent everytime the cronjob is executed.

### **Expected behaviour**

Notifications are sent only once or in configurable intervals (e.g. at most once every day).

### **Steps to reproduce**
    Configure the cronjob to run every 5min.
    Create a task and let it run beyond the due date
    Receive an email/telegram every 5min

### **Configuration**
    Versión de la aplicación: 1.2.16
    Versión de PHP: 7.3.16
    PHP SAPI: fpm-fcgi
    Cliente HTTP: cURL
    Versión del sistema operativo: Linux 3.10.105
    Driver de la base de datos mysql
    Versión de base de datos: 10.3.21-MariaDB
    Navegador: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0

**Comment by BlueTeck** [comment]
Maybe #4066 could help.

**Comment by nykroy** [comment]
but this issue is about email not about telegram notifications

**Comment by BlueTeck** [comment]
There are different cronjobs, you could run the overdue task just once a day and the other tasks every 5 minutes.

You should open a ticket on the Telegram plugin repository, not in this core Kanboard repo.

**Comment by nykroy** [comment]
I open the issue on telegram repository but this was his answer:
 @manuvarkey manuvarkey commented 12 days ago

Generation of notifications are handled by Kanboard directly. The Telegram plugin only delivers the notification once they are generated. Please raise this issue upstream in the kanboard project.

**Comment by creecros** [comment]
I dont see any reason #4066 solve wouldn't work.

**Comment by fguillot** [comment]
If you configure the cronjob to run every 5 minutes, then it's expected.

Look at the source code: https://github.com/kanboard/kanboard/blob/master/app/Console/CronjobCommand.php#L14

The cronjob is supposed to be configured only once a day.
