### ISSUE TITLE
Can't reach kanboard site

### ISSUE THREAD

**Issue by BarboraPiatkova** [kanboard/kanboard#4666]
I run my server through Apache and have installed php7, I added downloaded kanboard directory into httpd directory, but when I try to reach localserver/kanboard I only see the folders, what might be the problem?
![image](https://user-images.githubusercontent.com/73938804/98570439-bcfb2c80-22b3-11eb-8f54-ddd7aa3d5c54.png)

**Comment by BlueTeck** [comment]
open the index.php file -> localhost:8080/kanboard/index.php

**Comment by BarboraPiatkova** [comment]
The one inside the kanboard directory?

Dňa po 9. 11. 2020, 18:37 Timo <notifications@github.com> napísal(a):

**Comment by BlueTeck** [comment]
Yes, in your case.

But this is not a bug, please use the forum https://kanboard.discourse.group/ for general setup questions.

**Comment by BarboraPiatkova** [comment]
That's what my index.php looks like... where should I put
localhost:8080/kanboard/index.php?

po 9. 11. 2020 o 18:46 Timo <notifications@github.com> napísal(a):

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for installation issues.
