### ISSUE TITLE
Extension Permissions

### ISSUE THREAD

**Issue by hmiledUB** [kanboard/kanboard#4678]
### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by hmiledUB** [comment]
Bonjour, 
Je voudrai ouvrir les projets publics par défaut pour le profil utilisateur dans KanBoard.
Est ce qu'il y a déjà eu une mise à jour contenant cette extension?
Sinon, est ce que c'est possible de la rajouter dans les paramètres?
Est ce que ça demanderai un long développement à réaliser?

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
