### ISSUE TITLE
Upgraded to latest version and application version shows "master"

### ISSUE THREAD

**Issue by Benoit1980** [kanboard/kanboard#4680]
Hello,

I have just upgraded to the latest version from version 1.2.13 and now the "Application version" shows as below:

master.a77ce0cff47595241d35e10281294397d2d2cd76

Any idea why please?

Application version: master.a77ce0cff47595241d35e10281294397d2d2cd76
PHP version: 7.3.25
PHP SAPI: litespeed
HTTP Client: cURL
OS version: Linux 4.18.0-193.19.1.el8_2.x86_64
Database driver: sqlite
Database version: 3.26.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by fguillot** [comment]
You have to download the archive from the releases page.

For example:

- https://github.com/kanboard/kanboard/releases/tag/v1.2.17
- https://github.com/kanboard/kanboard/archive/v1.2.17.tar.gz

**Comment by Benoit1980** [comment]
Thanks.
