### ISSUE TITLE
Unable to add an attachment when creating a task

### ISSUE THREAD

**Issue by Benoit1980** [kanboard/kanboard#4681]
Hello,

I looked everywhere in the settings, I cannot work it out.
I need to upload an attachment each time I create a task, at the moment it is a big annoying, I need to create the task, then find it and upload the attachment after.
Why there is not a button for uploading an attachment upon task creation, please?

Thank you.

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
