### ISSUE TITLE
Add files to gitignore

### ISSUE THREAD

**Issue by ngosang** [kanboard/kanboard#4686]
I'm installing Kanboard 1.2.17 from source code with the following commands:
```
git pull
composer update --no-dev
```
The installation finish good as expected but there are some files changed in the Git working tree.
```
git status

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   vendor/composer/ClassLoader.php
	modified:   vendor/composer/LICENSE
	modified:   vendor/composer/installed.json
	modified:   vendor/pimple/pimple/.travis.yml
	modified:   vendor/pimple/pimple/README.rst
	modified:   vendor/pimple/pimple/composer.json
	modified:   vendor/pimple/pimple/src/Pimple/Container.php

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	vendor/pimple/pimple/.php_cs.dist

no changes added to commit (use "git add" and/or "git commit -a")
```
Please, add those files to .gitignore. Now I have to discard or remove those files before running `git pull`

**Comment by ngosang** [comment]
@fguillot Thank you, but I can't run composer after this change. I'm running the same version of composer, same system.... I just did "git pull" and composer is not working with Kanboard.

```
composer update --no-dev

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Warning from https://packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies
Killed
```

**Comment by ngosang** [comment]
@fguillot It's a memory issue. I'm running Kanboard in a VPS with 1GB of RAM. When I run composer update it uses more than 500 MB of ram to resolve the dependencies. Some users said that you can reduce the memory usage if you set more specific versions of the packages. => https://stackoverflow.com/a/53807543

**Comment by ngosang** [comment]
I removed the composer cache, the composer.lock and the vendor folder and I get the same error.

**Comment by fguillot** [comment]
You don't need to run composer on your server. Dependencies are already included in the Git repo.

**Comment by ngosang** [comment]
You are right. I was using a really old script for update that is not required anymore.
Following the instructions works as expected => https://docs.kanboard.org/en/latest/admin_guide/installation.html
Thank you!
