### ISSUE TITLE
Data loss after upgrade to 1.2.17 (Sqlite)

### ISSUE THREAD

**Issue by rolandu** [kanboard/kanboard#4687]
### Actual behaviour

After upgrading to 1.2.17 (through Docker down, pull, up), all task tags are gone from tasks.

I looked up the situation in the database and it seems that the "task_has_tags" table was emptied during the upgrade.

### Expected behaviour

Tags should not be gone.

### Steps to reproduce

- Start a fresh Docker container of Kanboard 1.2.16
- Upload database backup of 1.2.16
- Confirm tags are there... (confirmed, they are there)
- Stop docker-container
- Start Docker container of Kanboard 1.2.17
- Confirm tags are gone... (confirmed, they are gone)

Example docker compose file to reproduce (just swapped the version numbers):
```
version: '2'
services:
  kanboard:
    image: kanboard/kanboard:v1.2.17
    ports:
     - "4444:80"
    restart: always
```

### Logs

```
$ sudo docker-compose up
Pulling kanboard (kanboard/kanboard:v1.2.17)...
v1.2.17: Pulling from kanboard/kanboard
801bfaa63ef2: Pull complete
4f27d7072dd2: Pull complete
6a1239c45e99: Pull complete
d5c204387882: Pull complete
b0e919b19e5d: Pull complete
Digest: sha256:fc7450eca4417c1c4263d981fc007a4ab48449dd416e4f1bd2b170e6c13e560b
Status: Downloaded newer image for kanboard/kanboard:v1.2.17
Recreating 2_kanboard_1 ... done
Attaching to 2_kanboard_1
```

### Configuration

- Kanboard version: 1.2.16 -> 1.2.17
- Database type and version: sqlite
- PHP version: default of Docker image
- OS: default of Docker image
- Browser: Firefox 84.0.1

---------

Edit: At first I though only the tags were gone, upon closer inspection of the database I found that also other tables have been emptied:

- comments
- project_activities
- subtasks
- subtask_time_tracking
- task_has_external_links
- task_has_files
- task_has_links
- (I am not sure about task_has_metadata, this was empty even before the upgrade for me)
- task_has_tags
- transitions

fyi, this code I found [elsewhere](https://stackoverflow.com/questions/58298886/find-the-number-of-rows-in-each-table-in-a-large-sqlite-database) dumps the rows per table for the whole db which allowed me to compare:

```
echo "SELECT 'SELECT count(*), \"' || name || '\" FROM ' || name || ';'  FROM sqlite_master WHERE type = 'table';" | sqlite3 -readonly "db.sqlite" | sqlite3 -readonly "db.sqlite
```

**Comment by slavkoja** [comment]
I do not use docker, but own debian package. The tags was gone too, with sqlite...

**Comment by fguillot** [comment]
The only Sqlite change for v1.2.17 release was this pull-request https://github.com/kanboard/kanboard/pull/4642. Let me try to reproduce on my side.

**Comment by fguillot** [comment]
This PR should fix the problem: https://github.com/kanboard/kanboard/pull/4689

**Comment by fguillot** [comment]
Version 1.2.18 contains the fix.

1. Restore your Sqlite database from a backup (see https://docs.kanboard.org/en/1.2.18/admin_guide/upgrade.html#important-things-to-do-before-updating)
2. Upgrade directly to v1.2.18 and skip v1.2.17

**Comment by slavkoja** [comment]
I will not bother with DB restore from backup, as i have only few tasks (a restored tags manually). But  upgrade from 1.2.17 to 1.2.18 is without problems with tags.

**Comment by rolandu** [comment]
I upgraded from 1.2.16 to 1.2.18 (latest) using Docker without problems. Thank you for the quick fix!
