### ISSUE TITLE
Unable to run SQL migrations v1.2.16 to v1.2.17 (sqlite)

### ISSUE THREAD

**Issue by Floyer007** [kanboard/kanboard#4691]
### Actual behaviour

I'm running kanboard in a docker-container.
With the newest/latest container my installation doesn't migrate the sqlite-database automatically or manual and shows the following error-message only:

`Internal Error: Unable to run SQL migrations: Running migration \Schema\version_125, SQLSTATE[HY000]: General error: 1 table tasks_new has 32 columns but 34 values were supplied (You may have to fix it manually)`

A manual start of the migration via the docker-console with `bash-5.0# ./cli db:migrate` doesn't work as well and shows the same message.

I couldn't find "tasks_new" while opening the sqlite-db manually with a DB-Browser.

### Expected behaviour

I expect, that the migration finishes and I can use kanboard as usual.

### Steps to reproduce

Change the docker-compose.yml image from image _kanboard/kanboard:v1.2.16_ to _image: kanboard/kanboard:latest_
and run "docker-compose pull" and "docker-compose up".

### Logs

None. Only the usual docker-update log without errors.

### Configuration (before the upgrade, because the new one doesn't work)

- Kanboard version: v1.2.16
- Database type and version: sqlite, 3.32.1 
- PHP version: 7.3.23
- OS: Linux 5.4.35
- Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0

**Comment by fguillot** [comment]
Did you installed any plugins that add more columns to the `tasks` table? The `tasks` table is supposed to have 32 columns, not 34, so it must be a plugin.

Can you open the Sqlite database and execute the `.schema` command. For example:

```bash
$ sqlite3 data/db.sqlite
SQLite version 3.32.3 2020-06-18 14:16:19
Enter ".help" for usage hints.
sqlite> .schema
[... shows db schema ...]
```

**Comment by Floyer007** [comment]
I'm using the following plugins:
- group_assign https://github.com/creecros/group_assign
- Customizer https://github.com/creecros/Customizer

Here's the schema:

SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> .schema
CREATE TABLE users (
            id INTEGER PRIMARY KEY,
            username TEXT NOT NULL,
            password TEXT,
            is_admin INTEGER DEFAULT 0
        , is_ldap_user INTEGER DEFAULT 0, name TEXT, email TEXT, google_id TEXT, github_id TEXT, notifications_enabled INTEGER DEFAULT '0', timezone TEXT, language TEXT, disable_login_form INTEGER DEFAULT 0, twofactor_activated INTEGER DEFAULT 0, twofactor_secret TEXT, token TEXT DEFAULT '', notifications_filter INTEGER DEFAULT 4, nb_failed_login INTEGER DEFAULT 0, lock_expiration_date INTEGER DEFAULT 0, is_project_admin INTEGER DEFAULT 0, gitlab_id INTEGER, role TEXT NOT NULL DEFAULT 'app-user', is_active INTEGER DEFAULT 1, avatar_path TEXT, api_access_token VARCHAR(255) DEFAULT NULL, filter TEXT);
CREATE TABLE projects (
            id INTEGER PRIMARY KEY,
            name TEXT NOCASE NOT NULL,
            is_active INTEGER DEFAULT 1
        , token TEXT, last_modified INTEGER DEFAULT 0, is_public INTEGER DEFAULT "0", is_private INTEGER DEFAULT "0", is_everybody_allowed INTEGER DEFAULT "0", default_swimlane TEXT DEFAULT 'Default swimlane', show_default_swimlane INTEGER DEFAULT 1, description TEXT, identifier TEXT DEFAULT '', start_date TEXT DEFAULT '', end_date TEXT DEFAULT '', owner_id INTEGER DEFAULT 0, priority_default INTEGER DEFAULT 0, priority_start INTEGER DEFAULT 0, priority_end INTEGER DEFAULT 3, email TEXT, predefined_email_subjects TEXT, per_swimlane_task_limits INTEGER DEFAULT 0 NOT NULL, task_limit INTEGER DEFAULT 0, enable_global_tags INTEGER DEFAULT 1 NOT NULL);
CREATE TABLE columns (
            id INTEGER PRIMARY KEY,
            title TEXT NOT NULL,
            position INTEGER,
            project_id INTEGER NOT NULL, task_limit INTEGER DEFAULT '0', description TEXT, hide_in_dashboard INTEGER DEFAULT 0 NOT NULL,
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            UNIQUE (title, project_id)
        );
CREATE TABLE tasks (
            id INTEGER PRIMARY KEY,
            title TEXT NOCASE NOT NULL,
            description TEXT,
            date_creation INTEGER,
            color_id TEXT,
            project_id INTEGER,
            column_id INTEGER,
            owner_id INTEGER DEFAULT '0',
            position INTEGER,
            is_active INTEGER DEFAULT 1, date_completed INTEGER, score INTEGER, date_due INTEGER, category_id INTEGER DEFAULT 0, creator_id INTEGER DEFAULT '0', date_modification INTEGER DEFAULT '0', reference TEXT DEFAULT '', date_started INTEGER, time_spent NUMERIC DEFAULT 0, time_estimated NUMERIC DEFAULT 0, swimlane_id INTEGER DEFAULT 0, date_moved INTEGER DEFAULT 0, recurrence_status INTEGER NOT NULL DEFAULT 0, recurrence_trigger INTEGER NOT NULL DEFAULT 0, recurrence_factor INTEGER NOT NULL DEFAULT 0, recurrence_timeframe INTEGER NOT NULL DEFAULT 0, recurrence_basedate INTEGER NOT NULL DEFAULT 0, recurrence_parent INTEGER, recurrence_child INTEGER, priority INTEGER DEFAULT 0, external_provider TEXT, external_uri TEXT, owner_gp INTEGER DEFAULT '0', owner_ms INTEGER DEFAULT '0',
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            FOREIGN KEY(column_id) REFERENCES columns(id) ON DELETE CASCADE
        );
CREATE TABLE project_has_users (
            project_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL, is_owner INTEGER DEFAULT "0", role TEXT NOT NULL DEFAULT 'project-viewer',
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
            UNIQUE(project_id, user_id)
        );
CREATE TABLE actions (
            id INTEGER PRIMARY KEY,
            project_id INTEGER NOT NULL,
            event_name TEXT NOT NULL,
            action_name TEXT NOT NULL,
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
        );
CREATE TABLE action_has_params (
            id INTEGER PRIMARY KEY,
            action_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            value TEXT NOT NULL,
            FOREIGN KEY(action_id) REFERENCES actions(id) ON DELETE CASCADE
        );
CREATE TABLE remember_me (
            id INTEGER PRIMARY KEY,
            user_id INTEGER NOT NULL,
            ip TEXT,
            user_agent TEXT,
            token TEXT,
            sequence TEXT,
            expiration INTEGER,
            date_creation INTEGER,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        );
CREATE TABLE last_logins (
            id INTEGER PRIMARY KEY,
            auth_type TEXT,
            user_id INTEGER NOT NULL,
            ip TEXT,
            user_agent TEXT,
            date_creation INTEGER,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        );
CREATE TABLE project_has_categories (
            id INTEGER PRIMARY KEY,
            name TEXT COLLATE NOCASE NOT NULL,
            project_id INTEGER NOT NULL, description TEXT, color_id TEXT DEFAULT NULL,
            UNIQUE (project_id, name),
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
        );
CREATE TABLE IF NOT EXISTS "task_has_files" (
            id INTEGER PRIMARY KEY,
            name TEXT COLLATE NOCASE NOT NULL,
            path TEXT,
            is_image INTEGER DEFAULT 0,
            task_id INTEGER NOT NULL, "date" INTEGER NOT NULL DEFAULT 0, "user_id" INTEGER NOT NULL DEFAULT 0, "size" INTEGER NOT NULL DEFAULT 0,
            FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE
        );
CREATE TABLE IF NOT EXISTS "subtasks" (
            id INTEGER PRIMARY KEY,
            title TEXT COLLATE NOCASE NOT NULL,
            status INTEGER DEFAULT 0,
            time_estimated NUMERIC DEFAULT 0,
            time_spent NUMERIC DEFAULT 0,
            task_id INTEGER NOT NULL,
            user_id INTEGER, position INTEGER DEFAULT 1,
            FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE
        );
CREATE TABLE user_has_notifications (
            user_id INTEGER NOT NULL,
            project_id INTEGER NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            UNIQUE(project_id, user_id)
        );
CREATE TABLE settings (
            option TEXT PRIMARY KEY,
            value TEXT DEFAULT ''
        , changed_by INTEGER DEFAULT 0 NOT NULL, changed_on INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS "project_daily_column_stats" (
            id INTEGER PRIMARY KEY,
            day TEXT NOT NULL,
            project_id INTEGER NOT NULL,
            column_id INTEGER NOT NULL,
            total INTEGER NOT NULL DEFAULT 0, score INTEGER NOT NULL DEFAULT 0,
            FOREIGN KEY(column_id) REFERENCES columns(id) ON DELETE CASCADE,
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
        );
CREATE TABLE swimlanes (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            position INTEGER DEFAULT 1,
            is_active INTEGER DEFAULT 1,
            project_id INTEGER NOT NULL, description TEXT, task_limit INTEGER DEFAULT 0,
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            UNIQUE (name, project_id)
        );
CREATE TABLE subtask_time_tracking (
            id INTEGER PRIMARY KEY,
            user_id INTEGER NOT NULL,
            subtask_id INTEGER NOT NULL,
            start INTEGER DEFAULT 0,
            end INTEGER DEFAULT 0, time_spent REAL DEFAULT 0,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY(subtask_id) REFERENCES "subtasks"(id) ON DELETE CASCADE
        );
CREATE TABLE links (
        id INTEGER PRIMARY KEY,
        label TEXT NOT NULL,
        opposite_id INTEGER DEFAULT 0,
        UNIQUE(label)
    );
CREATE TABLE task_has_links (
        id INTEGER PRIMARY KEY,
        link_id INTEGER NOT NULL,
        task_id INTEGER NOT NULL,
        opposite_task_id INTEGER NOT NULL,
        FOREIGN KEY(link_id) REFERENCES links(id) ON DELETE CASCADE,
        FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
        FOREIGN KEY(opposite_task_id) REFERENCES tasks(id) ON DELETE CASCADE
    );
CREATE TABLE transitions (
        "id" INTEGER PRIMARY KEY,
        "user_id" INTEGER NOT NULL,
        "project_id" INTEGER NOT NULL,
        "task_id" INTEGER NOT NULL,
        "src_column_id" INTEGER NOT NULL,
        "dst_column_id" INTEGER NOT NULL,
        "date" INTEGER NOT NULL,
        "time_spent" INTEGER DEFAULT 0,
        FOREIGN KEY(src_column_id) REFERENCES columns(id) ON DELETE CASCADE,
        FOREIGN KEY(dst_column_id) REFERENCES columns(id) ON DELETE CASCADE,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
        FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE
    );
CREATE TABLE currencies ("currency" TEXT NOT NULL UNIQUE, "rate" REAL DEFAULT 0);
CREATE TABLE comments (
            id INTEGER PRIMARY KEY,
            task_id INTEGER NOT NULL,
            user_id INTEGER DEFAULT 0,
            date_creation INTEGER NOT NULL,
            comment TEXT NOT NULL,
            reference VARCHAR(50), date_modification INTEGER,
            FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE
        );
CREATE TABLE project_daily_stats (
            id INTEGER PRIMARY KEY,
            day TEXT NOT NULL,
            project_id INTEGER NOT NULL,
            avg_lead_time INTEGER NOT NULL DEFAULT 0,
            avg_cycle_time INTEGER NOT NULL DEFAULT 0,
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
        );
CREATE TABLE plugin_schema_versions (
            plugin TEXT NOT NULL PRIMARY KEY,
            version INTEGER NOT NULL DEFAULT 0
        );
CREATE TABLE custom_filters (
            id INTEGER PRIMARY KEY,
            filter TEXT NOT NULL,
            project_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            is_shared INTEGER DEFAULT 0
        , append INTEGER DEFAULT 0);
CREATE TABLE user_has_unread_notifications (
            id INTEGER PRIMARY KEY,
            user_id INTEGER NOT NULL,
            date_creation INTEGER NOT NULL,
            event_name TEXT NOT NULL,
            event_data TEXT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        );
CREATE TABLE user_has_notification_types (
            id INTEGER PRIMARY KEY,
            user_id INTEGER NOT NULL,
            notification_type TEXT,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        );
CREATE TABLE project_has_notification_types (
            id INTEGER PRIMARY KEY,
            project_id INTEGER NOT NULL,
            notification_type TEXT NOT NULL,
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            UNIQUE(project_id, notification_type)
        );
CREATE TABLE user_has_metadata (
            user_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            value TEXT DEFAULT '', changed_by INTEGER DEFAULT 0 NOT NULL, changed_on INTEGER DEFAULT 0 NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
            UNIQUE(user_id, name)
        );
CREATE TABLE project_has_metadata (
            project_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            value TEXT DEFAULT '', changed_by INTEGER DEFAULT 0 NOT NULL, changed_on INTEGER DEFAULT 0 NOT NULL,
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            UNIQUE(project_id, name)
        );
CREATE TABLE task_has_metadata (
            task_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            value TEXT DEFAULT '', changed_by INTEGER DEFAULT 0 NOT NULL, changed_on INTEGER DEFAULT 0 NOT NULL,
            FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
            UNIQUE(task_id, name)
        );
CREATE TABLE groups (
            id INTEGER PRIMARY KEY,
            external_id TEXT DEFAULT '',
            name TEXT NOCASE NOT NULL UNIQUE
        );
CREATE TABLE group_has_users (
            group_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE CASCADE,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
            UNIQUE(group_id, user_id)
        );
CREATE TABLE project_has_groups (
            group_id INTEGER NOT NULL,
            project_id INTEGER NOT NULL,
            role TEXT NOT NULL,
            FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE CASCADE,
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            UNIQUE(group_id, project_id)
        );
CREATE TABLE password_reset (
            token TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL,
            date_expiration INTEGER NOT NULL,
            date_creation INTEGER NOT NULL,
            ip TEXT NOT NULL,
            user_agent TEXT NOT NULL,
            is_active INTEGER NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        );
CREATE TABLE task_has_external_links (
            id INTEGER PRIMARY KEY,
            link_type TEXT NOT NULL,
            dependency TEXT NOT NULL,
            title TEXT NOT NULL,
            url TEXT NOT NULL,
            date_creation INTEGER NOT NULL,
            date_modification INTEGER NOT NULL,
            task_id INTEGER NOT NULL,
            creator_id INTEGER DEFAULT 0,
            FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE
        );
CREATE TABLE project_has_files (
            id INTEGER PRIMARY KEY,
            project_id INTEGER NOT NULL,
            name TEXT COLLATE NOCASE NOT NULL,
            path TEXT NOT NULL,
            is_image INTEGER DEFAULT 0,
            size INTEGER DEFAULT 0 NOT NULL,
            user_id INTEGER DEFAULT 0 NOT NULL,
            date INTEGER DEFAULT 0 NOT NULL,
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
        );
CREATE TABLE tags (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            project_id INTEGER NOT NULL, color_id TEXT DEFAULT NULL,
            UNIQUE(project_id, name)
        );
CREATE TABLE task_has_tags (
            task_id INTEGER NOT NULL,
            tag_id INTEGER NOT NULL,
            FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
            FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE,
            UNIQUE(tag_id, task_id)
        );
CREATE TABLE project_has_roles (
            role_id INTEGER PRIMARY KEY,
            role TEXT NOT NULL,
            project_id INTEGER NOT NULL,
            UNIQUE(project_id, role),
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
        );
CREATE TABLE column_has_move_restrictions (
            restriction_id INTEGER PRIMARY KEY,
            project_id INTEGER NOT NULL,
            role_id INTEGER NOT NULL,
            src_column_id INTEGER NOT NULL,
            dst_column_id INTEGER NOT NULL, only_assigned INTEGER DEFAULT 0,
            UNIQUE(role_id, src_column_id, dst_column_id),
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            FOREIGN KEY(role_id) REFERENCES project_has_roles(role_id) ON DELETE CASCADE,
            FOREIGN KEY(src_column_id) REFERENCES columns(id) ON DELETE CASCADE,
            FOREIGN KEY(dst_column_id) REFERENCES columns(id) ON DELETE CASCADE
        );
CREATE TABLE project_role_has_restrictions (
            restriction_id INTEGER PRIMARY KEY,
            project_id INTEGER NOT NULL,
            role_id INTEGER NOT NULL,
            rule VARCHAR(255) NOT NULL,
            UNIQUE(role_id, rule),
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            FOREIGN KEY(role_id) REFERENCES project_has_roles(role_id) ON DELETE CASCADE
        );
CREATE TABLE column_has_restrictions (
            restriction_id INTEGER PRIMARY KEY,
            project_id INTEGER NOT NULL,
            role_id INTEGER NOT NULL,
            column_id INTEGER NOT NULL,
            rule VARCHAR(255) NOT NULL,
            UNIQUE(role_id, column_id, rule),
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            FOREIGN KEY(role_id) REFERENCES project_has_roles(role_id) ON DELETE CASCADE,
            FOREIGN KEY(column_id) REFERENCES columns(id) ON DELETE CASCADE
        );
CREATE TABLE invites (
            email TEXT NOT NULL,
            project_id INTEGER NOT NULL,
            token TEXT NOT NULL,
            PRIMARY KEY(email, token)
        );
CREATE TABLE project_activities (
          id INTEGER PRIMARY KEY,
          date_creation INTEGER NOT NULL,
          event_name TEXT NOT NULL,
          creator_id INTEGER NOT NULL,
          project_id INTEGER NOT NULL,
          task_id INTEGER NOT NULL,
          data TEXT,
          FOREIGN KEY(creator_id) REFERENCES users(id) ON DELETE CASCADE,
          FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
          FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE
      );
CREATE TABLE predefined_task_descriptions (
        id INTEGER PRIMARY KEY,
        project_id INTEGER NOT NULL,
        title TEXT NOT NULL,
        description TEXT NOT NULL,
        FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
    );
CREATE TABLE sessions (
        id TEXT PRIMARY KEY,
        expire_at INTEGER NOT NULL,
        data TEXT DEFAULT ''
    );
CREATE TABLE multiselect (
            id INTEGER PRIMARY KEY,
            external_id TEXT DEFAULT ''
        );
CREATE TABLE multiselect_has_users (
            group_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            FOREIGN KEY(group_id) REFERENCES multiselect(id) ON DELETE CASCADE,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
            UNIQUE(group_id, user_id)
        );
CREATE TABLE customizer_files (
            id INTEGER PRIMARY KEY,
            custom_id INTEGER NOT NULL,
            name TEXT COLLATE NOCASE NOT NULL,
            path TEXT NOT NULL,
            is_image INTEGER DEFAULT 0,
            size INTEGER DEFAULT 0 NOT NULL,
            user_id INTEGER DEFAULT 0 NOT NULL,
            date INTEGER DEFAULT 0 NOT NULL
        );
CREATE INDEX last_logins_user_idx ON last_logins(user_id);
CREATE INDEX tasks_reference_idx ON tasks(reference);
CREATE INDEX users_admin_idx ON users(is_admin);
CREATE INDEX columns_project_idx ON columns(project_id);
CREATE INDEX tasks_project_idx ON tasks(project_id);
CREATE INDEX swimlanes_project_idx ON swimlanes(project_id);
CREATE INDEX categories_project_idx ON project_has_categories(project_id);
CREATE INDEX subtasks_task_idx ON "subtasks"(task_id);
CREATE INDEX files_task_idx ON "task_has_files"(task_id);
CREATE INDEX task_has_links_task_index ON task_has_links(task_id);
CREATE INDEX transitions_task_index ON transitions(task_id);
CREATE INDEX transitions_project_index ON transitions(project_id);
CREATE INDEX transitions_user_index ON transitions(user_id);
CREATE UNIQUE INDEX users_username_idx ON users(username);
CREATE UNIQUE INDEX project_daily_column_stats_idx ON "project_daily_column_stats"(day, project_id, column_id);
CREATE UNIQUE INDEX task_has_links_unique ON task_has_links(link_id, task_id, opposite_task_id);
CREATE UNIQUE INDEX project_daily_stats_idx ON project_daily_stats(day, project_id);
CREATE UNIQUE INDEX user_has_notification_types_user_idx ON user_has_notification_types(user_id, notification_type);

**Comment by fguillot** [comment]
The plugin "Group_Assign" adds 2 extra columns `owner_ms` and `owner_gp`: https://github.com/creecros/Group_assign/blob/master/Schema/Sqlite.php

If you want to keep this plugin, you will have to change the migration manually on your installation to add these 2 columns: https://github.com/kanboard/kanboard/blob/master/app/Schema/Sqlite.php#L13-L56

You can also choose to skip the migration 125. The only change here is to add a foreign key for `swimlane_id`. If that your choice, then update the field `version` in table `schema_version` to the value `125`.

**Comment by mariohommel** [comment]
I've the same problem updating from 1.2.16 to 1.2.18.
I modified Sqlite-php to add the missing columns and migration worked then. But tasks are loosing all already assigned groups.

**Comment by fguillot** [comment]
Ok, I'm assuming the issue is solved now according to your last update.

If you still have a problem, reach out the author of this plugin: https://github.com/creecros/Group_assign/issues

**Comment by sebw** [comment]
I'm facing the error but only have the Telegram plugin enabled.

I used to try some other plugins, though.

Thie is the schema:

```
CREATE TABLE tasks (
            id INTEGER PRIMARY KEY,
            title TEXT NOCASE NOT NULL,
            description TEXT,
            date_creation INTEGER,
            color_id TEXT,
            project_id INTEGER,
            column_id INTEGER,
            owner_id INTEGER DEFAULT '0',
            position INTEGER,
            is_active INTEGER DEFAULT 1, date_completed INTEGER, score INTEGER, date_due INTEGER, category_id INTEGER DEFAULT 0, creator_id INTEGER DEFAULT '0', date_modification INTEGER DEFAULT '0', reference TEXT DEFAULT '', date_started INTEGER, time_spent NUMERIC DEFAULT 0, time_estimated NUMERIC DEFAULT 0, swimlane_id INTEGER DEFAULT 0, date_moved INTEGER DEFAULT 0, recurrence_status INTEGER NOT NULL DEFAULT 0, recurrence_trigger INTEGER NOT NULL DEFAULT 0, recurrence_factor INTEGER NOT NULL DEFAULT 0, recurrence_timeframe INTEGER NOT NULL DEFAULT 0, recurrence_basedate INTEGER NOT NULL DEFAULT 0, recurrence_parent INTEGER, recurrence_child INTEGER, priority INTEGER DEFAULT 0, external_provider TEXT, external_uri TEXT, owner_gp INTEGER DEFAULT '0', owner_ms INTEGER DEFAULT '0',
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            FOREIGN KEY(column_id) REFERENCES columns(id) ON DELETE CASCADE
        );
```

I have `owner_gp` and `owner_ms` entries in there, as @mariohommel 

I tried to drop the columns but it seems Sqlite doesn't support `ALTER TABLE DROP COLUMN`.

Can anyone comfortable with Sqlite help on the syntax?

Thanks!

**Comment by gerroon** [comment]
Hi I do not have group or telegram and I still have this issue. I would appreciate any pointers.

**Comment by benji1000** [comment]
> 
> 
> The plugin "Group_Assign" adds 2 extra columns `owner_ms` and `owner_gp`: https://github.com/creecros/Group_assign/blob/master/Schema/Sqlite.php
> 
> If you want to keep this plugin, you will have to change the migration manually on your installation to add these 2 columns: https://github.com/kanboard/kanboard/blob/master/app/Schema/Sqlite.php#L13-L56
> 
> You can also choose to skip the migration 125. The only change here is to add a foreign key for `swimlane_id`. If that your choice, then update the field `version` in table `schema_version` to the value `125`.
> 
> Note that v1.2.18 has been released to fix a different Sqlite issue. See https://github.com/kanboard/kanboard/releases/tag/v1.2.18

I can confirm that it works great and allowed us to upgrade our 1.2.16 instance to version 1.2.18 by manually editing the `app/Schema/Sqlite.php` as described. To be even more explicit, we edited the following lines (L49-L50) of the file, from this:

```
            external_uri         TEXT
        )
```

To this:

```
            external_uri         TEXT,
            owner_gp             INTEGER DEFAULT 0,
            owner_ms             INTEGER DEFAULT 0
        )
```

The upgrade succeeded, no error message, no data or functionalities lost. Thank you for your help!

Maybe this process could be described in a documentation, or at least in the Release message on Github? Like "If you use plugins that edit tables (e.g. Group_Assign), you have to manually apply the database changes to the `Sqlite.php` file"?

**Comment by gerroon** [comment]
Hi,

Sorry to bug you again but I do not get what I am supposed to be doing to get the migration done. I am not a dev and have no idea about sqlite magic I am just a user tyring to get this running again.

thanks

**Comment by sebw** [comment]
@gerroon I used DBeaver Community to fix my sqlite DB as I only know MySQL. I was able to get rid of the conflicting columns with a few clicks. Feel free to share your DB with me, I can try to have a look at what is wrong in it.

**Comment by benji1000** [comment]
@sebw Well, you should be careful about "getting rid" of columns, they may contain useful data created by the plugins that you may lose if you just delete them. Or maybe I misunderstood what you said.

@gerroon If you go with sebw's solution, you should make a backup of your database file so that you can revert to it if anything goes wrong. One solution can be to go to your Kanboard's plugin page, and for each plugin you have installed, go to their respective Github repository, and ask the developer if their plugin adds columns to the database. That way, you would be able to correct the `app/Schema/Sqlite.php` appropriately. But I understand that it's a delicate process if you're not tech-savvy.

Ideally, this particularity should be taken care of by Kanboard's upgrade process, or at least documented...

**Comment by gerroon** [comment]
@benji1000  I am using sqlite and I installed many plugins in the past :(

How do I know what column is exactly  conflicting?

**Comment by benji1000** [comment]
Well, you first have to know which tables were altered when you installed your plugins, and how (which columns were added and what type of data do the columns contain). There are two ways of doing that.

First solution, you compare the `app/Schema/Sqlite.php` file of Kanboard ([here](https://github.com/kanboard/kanboard/blob/master/app/Schema/Sqlite.php)) with the current schema of your database. You can open your database with DBeaver Community or with DB Browser for SQLite. In my case for instance, when I open my SQLite database and I go to the `tasks` table, I can see that there are two columns that do no appear in the `app/Schema/Sqlite.php` file of Kanboard: `owner_gp` and `owner_ms`. I'm lucky: only the `tasks` table as altered by my plugins.

Second solution, you go to the Github page of all of your plugins, you locate the file which contain the SQLite database modifications, and identify the requests that have the `ALTER` keyword in it. Using the Group_Assign module example, here is [the file](https://github.com/creecros/Group_assign/blob/master/Schema/Sqlite.php#L33), and you can see on line 33 that it does a request to alter the `tasks` table to add a `owner_gp` column. In my case, the `owner_ms` I mentioned earlier must have come from another plugin. That's why you should do this for each of your plugins.

Either way, once you know which tables were edited, the name of the columns that were added and their type, you should edit the `app/Schema/Sqlite.php` of the new release of Kanboard to add these two columns, just like I explained on my message from January 20th. Then replace all the files in the Kanboard folder on your server with the files from the new release, including the `app/Schema/Sqlite.php` file that you edited, and run the upgrade. Don't forget to backup your DB file though.

Who performed your Kanboard install, and could they not help you with that?

**Comment by sebw** [comment]
@benji1000 obviously when I'm talking about conflicting columns, those are orphans from old plugin installation that I no longer use.

**Comment by gerroon** [comment]
@benji1000  thanks for the detailed answer but I am sorry to say that that is ana impossible upgrade for  regular person. I probbaly installed and used over 30 plugins in the past, and trying to figure out who modified what retrospectively is a job for titans.

I am wondering why this was never an issue in 1.2.15 but it has become an issue afterwards. Becasue 1.2.15 works if I revert it.

**Comment by Hardey1774** [comment]
Please I have this issue when I try to view the outcome of my db on a browser: 
Internal Error: Unable to run SQL migrations: Running migration \Schema\version_129, SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'name' used in key specification without a key length (You may have to fix it manually)

Note: I am running vagrant, VirtualMachine, MariaDB and kanboard:
The outcome I expect is as attached:
![WhatsApp Image 2023-08-12 at 15 51 50](https://github.com/kanboard/kanboard/assets/111874994/9195a14a-9e70-4d15-a479-44762d3a3f21)
