### ISSUE TITLE
Internal Error: Unable to run SQL migrations: Running migration \Schema\version_125, SQLSTATE[HY000]: General error: 1 table tasks_new has 32 columns but 34 values were supplied (You may have to fix it manually)

### ISSUE THREAD

**Issue by sebw** [kanboard/kanboard#4697]
### Actual behaviour

Kanboard docker pointing to latest image tag.

After the upgrade I get the following error message instead of the web login form:

Internal Error: Unable to run SQL migrations: Running migration \Schema\version_125, SQLSTATE[HY000]: General error: 1 table tasks_new has 32 columns but 34 values were supplied (You may have to fix it manually)

### Expected behaviour

Smooth upgrade

### Steps to reproduce

Update to latest image

### Workaround

Last known working tag is `v1.2.16`.

Rolling back to v1.2.16 works without noticeable regression.

### Configuration

Application version: v1.2.16
PHP version: 7.3.23
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 5.1.20-200.fc29.x86_64
Database driver: sqlite
Database version: 3.32.1

**Comment by fguillot** [comment]
Duplicate with #4691
