### ISSUE TITLE
How to save New Project?

### ISSUE THREAD

**Issue by fu4dfauzi** [kanboard/kanboard#4703]
I installed Kanboard on CPanel server.

I wonder, how to save the project? The blue Save button is not showing. Here is the screenshot. Please help ASAP!

![image](https://user-images.githubusercontent.com/11000913/104294503-d9a12400-54f1-11eb-9c79-a03d45a6c335.png)

**Comment by fu4dfauzi** [comment]
Then I found this in DevTools

How to solve this?

![image](https://user-images.githubusercontent.com/11000913/104295530-26d1c580-54f3-11eb-8f86-222fb2012684.png)

**Comment by fguillot** [comment]
Disable Clouflare JavaScript optimizations
