### ISSUE TITLE
Installing plugin throws warning

### ISSUE THREAD

**Issue by DigiLive** [kanboard/kanboard#4704]
### Actual behaviour

When installing a plugin from the plugin directory, using the frontend, the plugin will install, but a warning is thrown while the installer tries to unlink the archive.

`Warning: unlink(***\kb_9C98.tmp): Resource temporarily unavailable in ***\kanboard\app\Core\Plugin\Installer.php on line 136`

### Expected behaviour

Installation of plugin without any errors or warnings thrown.

### Steps to reproduce
Click...
profile at top right,
Plugins,
Plugin Directory,
Install @ a plugin (Task2pdf in my case).

### Configuration

- Kanboard version: 1.2.26
- Database type and version: 10.1.37-MariaDB
- PHP version: 7.2.12
- OS: W10
- Browser: Firefox

### Research
I think `app/Core/Plugin/Installer.php` still has an active file-handle when trying to cleanup the archive @ line 136.
Method `Installer::cleanupArchive()` tries to unlink before closing the filehandle.
Line 136 and 137 should be switched?

https://github.com/kanboard/kanboard/blob/8a77a7851ca8552816d52b42897adb4b3807d416/app/Core/Plugin/Installer.php#L134-L138

**Comment by fguillot** [comment]
You are probably right.
