### ISSUE TITLE
Add Avatar to calendar Plugin

### ISSUE THREAD

**Issue by kwetnico** [kanboard/kanboard#4712]
Hello,
Is it possible to add the photo of the person assigned to the task (right next to the task number) on the plugin?

Thank you

- Kanboard version: 1.2.18
- Database type and version: 10.3.17-MariaDB
- PHP version: 7.2.24 
- OS: Linux CentOs 8
- Browser: Chrome, Firefox

**Comment by fguillot** [comment]
No. The calendar plugin is now here: https://gitlab.com/smacz/kanboard-plugin-calendar (ask the maintainer).
