### ISSUE TITLE
Texteditor doesn't show content

### ISSUE THREAD

**Issue by elaubmey** [kanboard/kanboard#4713]
### Actual behaviour

All over kanboard the text-editors doesn't pick up the former content I saw. In the script-tag I find the content. But the system doesn't paste it into the text-editor-textarea.

### Expected behaviour

If I open an edit window, I expect, that the former content will appear in the text-editor

### Steps to reproduce

Edit a descitption in a task.

- Kanboard version: master.40304082bd34255bf244ea9cba78001dfdc5e20e || v1.2.18
- Database type and version:  mysql, 5.6.42-log 
- PHP version: 7.2.34
- OS:  Linux localhost 3.10.0-1127.10.1.el7.x86_64 #1 SMP Linux localhost 3.10.0-1127.10.1.el7.x86_64 #1 SMP
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0

**Comment by fguillot** [comment]
Look at the browser console for errors.

**Comment by elaubmey** [comment]
I looked:

All Get-questions are not answered. I don't know which problem is it. Browser, Anti-Virus or Server. Can you help?

GET https://www.elaubmeyer.de/kanboard/assets/js/app.min.js?1611203272
GET https://www.elaubmeyer.de/kanboard/plugins/Backlog/Assets/backlog.js?1570208718
GET https://www.elaubmeyer.de/kanboard/plugins/Chat/Assets/chat.js?1570208747
GET https://www.elaubmeyer.de/kanboard/plugins/Gantt/Assets/chart.js?1598177482
GET https://www.elaubmeyer.de/kanboard/plugins/Customizer/Assets/js/customizer.js?1607558140
GET https://www.elaubmeyer.de/kanboard/plugins/Customizer/Assets/rgbaColorPicker/rgbaColorPicker.js?1607558140
GET https://www.elaubmeyer.de/kanboard/plugins/HighlightCodeSyntax/Assets/js/prism.js?1598177506
GET https://www.elaubmeyer.de/kanboard/plugins/HighlightCodeSyntax/Assets/js/clipboard.min.js?1598177506

**Comment by elaubmey** [comment]
At Chrome I have the same behavior.

I quit the Anti-Virus nothing happens.

Do you need further information or can you give me a hint?

**Comment by fguillot** [comment]
Cross-posting is a bad idea: https://kanboard.discourse.group/t/texteditor-doesnt-show-content/1651/6
