### ISSUE TITLE
Add quick switch task assignee ?

### ISSUE THREAD

**Issue by kwetnico** [kanboard/kanboard#4714]
Hello,

I do not have this option that interests me. To right click and quickly assign a task to a person.
How do you activate it?

"Add quick switch task assignee feature (kanboard#3251) (kanboard#3177)"
[https://github.com/on-jz/kanboard/commit/1f7a4b64b5385cea5cbd031f79d4a92c2522b8dd](url)
Thank you

Kanboard version: 1.2.18
Database type and version: 10.3.17-MariaDB
PHP version: 7.2.24
OS: Linux CentOs 8
Browser: Chrome, Firefox

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
