### ISSUE TITLE
Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1 no such table: main.task_has_subtasks

### ISSUE THREAD

**Issue by codemaster259** [kanboard/kanboard#4736]
### Actual behaviour

Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1 no such table: main.task_has_subtasks

### Expected behaviour

Mark subtask as "Done" (checkbox checked)

### Steps to reproduce

Create project
Create Task
Add Subtask
Try to mark subtask as "Done" (checkbox)

### Configuration

- Kanboard version: 1.2.18
- Database type and version: sqlite
- PHP version: 7.2.13
- OS: Windows 7 64 bits
- Browser:Google Chrome - 88.0.4324.146 (Build oficial) (64 bits)

**Comment by BlueTeck** [comment]
Please take a look at #1698

**Comment by fguillot** [comment]
Please, keep the discussion on the forum: https://kanboard.discourse.group/t/error-no-such-table-main-task-has-subtasks/1664

Do not post the same message everywhere.

**Comment by TheTrueBumba** [comment]
@fguillot , had the same problem and found the solution and the issue. The problem only occurs with a fresh install of 1.12.18 version. I installed the 1.12.16, logged in one time, upgraded to 1.12.18 and the problem didnt happened.
I saw your code and you check every version to make the changes in the sqlite database. Maybe a issue with fresh install only with 1.12.18.
If you need more help, please reply me. I am skilled only in C#, but I can find the problem and make a pull request.
To be clear: few people are complaing because the issue happens only with a fresh install of 1.12.18. Was my case.

**Comment by Keex0r** [comment]
I think the problem is a foreign key constraint on the subtask_time_tracking table, that reference the task_has_subtasks table. If I change the foreign key definition to "FOREIGN KEY("subtask_id") REFERENCES "subtasks"("id") ON DELETE CASCADE", it works fine. It is probably an oversight in the database migration.

**Comment by TheTrueBumba** [comment]
> 
> 
> I think the problem is a foreign key constraint on the subtask_time_tracking table, that reference the task_has_subtasks table. If I change the foreign key definition to "FOREIGN KEY("subtask_id") REFERENCES "subtasks"("id") ON DELETE CASCADE", it works fine. It is probably an oversight in the database migration.

But only in fresh installs. I am a developer and its normal create a upgrade schema system. In fresh install you create the database and upgrade the schema until the latest version. I think that em .18 version we have a issue with fresh install. I just installed .16 version, logged in once and upgraded to .18 and its working like a charm.
So its a issue only in fresh installs. I will check the code to identify whats happening.

**Comment by Keex0r** [comment]
> > I think the problem is a foreign key constraint on the subtask_time_tracking table, that reference the task_has_subtasks table. If I change the foreign key definition to "FOREIGN KEY("subtask_id") REFERENCES "subtasks"("id") ON DELETE CASCADE", it works fine. It is probably an oversight in the database migration.
> 
> But only in fresh installs. I am a developer and its normal create a upgrade schema system. In fresh install you create the database and upgrade the schema until the latest version. I think that em .18 version we have a issue with fresh install. I just installed .16 version, logged in once and upgraded to .18 and its working like a charm.
> So its a issue only in fresh installs. I will check the code to identify whats happening.

That is well possible. I only started using Kanboard lately so started with a fresh installation of the newest version. 

I'm not familiar with the way the databases are created, e.g. if the whole migration process is ran to arrive at the latest version, so can't really comment more at this point. I changed the foreign key manually and confirmed that clicking a subtask worked. That's as far as I went.

**Comment by TheTrueBumba** [comment]
> 
> 
> > > I think the problem is a foreign key constraint on the subtask_time_tracking table, that reference the task_has_subtasks table. If I change the foreign key definition to "FOREIGN KEY("subtask_id") REFERENCES "subtasks"("id") ON DELETE CASCADE", it works fine. It is probably an oversight in the database migration.
> > 
> > 
> > But only in fresh installs. I am a developer and its normal create a upgrade schema system. In fresh install you create the database and upgrade the schema until the latest version. I think that em .18 version we have a issue with fresh install. I just installed .16 version, logged in once and upgraded to .18 and its working like a charm.
> > So its a issue only in fresh installs. I will check the code to identify whats happening.
> 
> That is well possible. I only started using Kanboard lately so started with a fresh installation of the newest version.
> 
> I'm not familiar with the way the databases are created, e.g. if the whole migration process is ran to arrive at the latest version, so can't really comment more at this point. I changed the foreign key manually and confirmed that clicking a subtask worked. That's as far as I went.

Yes. Works. But the version has a issue with fresh install. I am out of time right now, but I will check the code and contact the developer. Until now I recomend install a previous version, login one time and upgrade to the latest version.
