### ISSUE TITLE
No more access with Firefox 86

### ISSUE THREAD

**Issue by GuillaumeSorel** [kanboard/kanboard#4756]
### Actual behaviour

I can't access anymore our Kanboard with Firefox when it works fine with Chromium (on MacOS).
https://kanboard.domain.com/login brings to a blocked connection.

### Expected behaviour

I should be able to log into our Kanboard

### Steps to reproduce

Try with Firefox 86
// Enable or disable "Strict-Transport-Security" HTTP header
define('ENABLE_HSTS', false);

True or False dosen't change anything.

### Logs
Connexion bloquée : problème de sécurité potentiel

Firefox a détecté une menace potentielle de sécurité et a interrompu le chargement de kanboard.all-in-group.fr, car ce site web nécessite une connexion sécurisée.

Que pouvez-vous faire ?

kanboard.all-in-group.fr a recours à une stratégie de sécurité HTTP Strict Transport Security (HSTS), une connexion sécurisée est obligatoire pour y accéder. Vous ne pouvez pas ajouter d’exception pour visiter ce site.

Le problème vient probablement du site web, vous ne pouvez donc pas y remédier. Vous pouvez le signaler aux personnes qui administrent le site.

### Configuration

- Kanboard version: 1.2.18
- Database type and version: SQLite
- PHP version: 7.3
- OS:
- Browser: Firefox 86

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for installation issues.
