### ISSUE TITLE
Idea for how to improve sqlite performance

### ISSUE THREAD

**Issue by mvalley21** [kanboard/kanboard#4757]
- [ ] I have read this document: https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-are-you-not-developing-my-feature-request

Hi,
Just a suggestion for improving the sqlite performance based on what I've done on my installation:
modify ./libs/picodb/lib/PicoDb/Driver/Sqlite.php

add "$this->pdo->exec('pragma synchronous = off;');"

after the "        $this->pdo = new PDO('sqlite:'.$settings['filename'], null, null, $options);"

It dramactically improves the responsiveness when sqlite gets above 3000 tasks.

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests or questions, **this issue tracker is only for bug reports**.

---

https://www.sqlite.org/pragma.html#pragma_synchronous

> With synchronous OFF (0), SQLite continues without syncing as soon as it has handed data off to the operating system. If the application running SQLite crashes, the data will be safe, but the database might become corrupted if the operating system crashes or the computer loses power before that data has been written to the disk surface. On the other hand, commits can be orders of magnitude faster with synchronous OFF.

https://www.sqlite.org/howtocorrupt.html#cfgerr

> Setting PRAGMA synchronous=OFF can cause the database to go corrupt if there is an operating-system crash or power failure, though this setting is safe from damage due to application crashes.
