### ISSUE TITLE
No results when searching for term with plus/+ sign

### ISSUE THREAD

**Issue by rmmayer** [kanboard/kanboard#4758]
### Actual behaviour
When searching for a term with the "+" sign in it, the + gets removed and no results are shown.

### Expected behaviour

Shouldn't it be possible to search for those strings?
I know that +2days is possible but this should only be needed whith for example due:+2days

Is it possible to escape the "+"-sign? 
Tried "\\+" but the + still gets removed.
Also quoting with double or single quotes did not work.

### Steps to reproduce

1. Create task with "+" in title
2. Search for exact title
3. No results found

### Configuration

- Kanboard version: 1.2.13
- Database type and version: PostgreSQL
- PHP version: 7.3
- OS: Debian 10
- Browser: Firefox 86

**Comment by rafacamargo123** [comment]
This is still an issue, but while it's not fixed, you can work around it by using `%2b` instead of `+` (only works once, it is changed to an `+` after the page is loaded, and if you want to search again or refresh the page you must change it to %2b again)
