### ISSUE TITLE
Query results depends on order of the filters

### ISSUE THREAD

**Issue by clementduveau** [kanboard/kanboard#4760]
### Actual behaviour
I am filtering my project to extract some simple stats.
I am looking for all taks with a specific tag, and due after the first of this year.
I used the following query:
`due:>"01/01/2021" tag:"my tag"`
Tasks seem to be well filtered but I got no filtering based on the tag (all tags and tasks without tag were showed).
I then used:
`tag:"my tag" due:>"01/01/2021"`
And I got the expected results

### Expected behaviour

Since the operator is suppose to be AND between families ( tag AND date AND column ) and OR inside families ( tag OR tag OR tag ) then, in this case, it supposes to be an AND operator, there is no reason for the order to impact the results

### Steps to reproduce
Try the previous queries

### Screenshots
Faulty query:
![image](https://user-images.githubusercontent.com/17810852/112131212-9afea880-8bc9-11eb-9668-578b03eaa1f6.png)

Good query:
![image](https://user-images.githubusercontent.com/17810852/112131420-d4371880-8bc9-11eb-9bd2-4e7e34391d5f.png)

### Logs
I can have access to logs upon request only.

### Configuration
- Kanboard version: Definitely not up to date. Upgrade planned this year
- Database type and version: MySQL (not up to date)
- PHP version: Unknown
- OS: Debian 8
- Browser: Edge and Chrome on Windows 10 (latest for both)

Our configuration is not up to date but since I didn't find any related issue, I open it, and will close it if an upgrade solve the issue.

**Comment by clementduveau** [comment]
> Tasks seem to be well filtered but I got no filtering based on the tag (all tags and tasks without tag were showed).
Well filtered by date*

**Comment by clementduveau** [comment]
I got the information that we are running a fork of the v1.2.15

**Comment by BlueTeck** [comment]
I can confirm this bug.

no result: `status:open tag:"Workflow" due:<="next sunday"`

correct result: `status:open tag:"Workflow" due:<="next sunday"`

**Comment by cshyam1892** [comment]
From the docs, shouldn't it be due:>2023-02-07 tag:"today", instead of due:>"2023-02-07" tag:"today".
It works fine for me when I try due:>2023-02-07 tag:"today".

**Comment by clementduveau** [comment]
Maybe, but this bug is not related to that as

> no result: status:open due:<="next sunday" tag:"Workflow"
> correct result: status:open tag:"Workflow" due:<="next sunday"

clearly shows that the order matter, whatever is the type of date filters used. Plus, I am pretty sure that it doesn't matter if dates are inside quotation marks or not.

I no longer work at this company, so I can't help investigate

**Comment by cshyam1892** [comment]
Is this still considered a bug? 
I tried the newest version of Kanboard with PHP 8.2.5 on Firefox 112.0.2 and Chromium 112.0.5615.49 and everything appears to be alright.

Attached a short video:

https://user-images.githubusercontent.com/52228374/235077606-48b8a396-8556-4959-be11-109c2ef8df7e.mp4

**Comment by clementduveau** [comment]
Seeing your video, it seems not. Code must have been corrected somehow somewhere along the way.

I close this issue.
