### ISSUE TITLE
Export Project as Markdown

### ISSUE THREAD

**Issue by leeand00** [kanboard/kanboard#4764]
- [x] I have read this document: https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-are-you-not-developing-my-feature-request

Please develop a way of exporting the Projects as markdown so that they can be easily exported to a webpage or email.

Just like [taskell ](https://github.com/smallhadroncollider/taskell) does.

**Comment by fguillot** [comment]
Please, use the forum https://kanboard.discourse.group/ for feature requests or questions, **this issue tracker is only for bug reports**.

For more information, see https://docs.kanboard.org/en/latest/developer_guide/faq.html
