### ISSUE TITLE
Group Filter

### ISSUE THREAD

**Issue by korlikiangel** [kanboard/kanboard#4804]
### Actual behaviour

After selecting group filter in board view this error shows up:

`Internal Error: SQL Error: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type integer: "" LINE 1: ...group_has_users WHERE group_has_users.user_id IN ('')) OR ta... ^`

When this error is up you cant see board again, there in no way to reset it, you must enter to the board with specific url with changed filter in link

### Screenshots

![image](https://user-images.githubusercontent.com/68482509/116914739-6d3a6400-ac4b-11eb-9124-2504d3b3008b.png)

- Kanboard version: 1.2.19
- Database type and version: 12.6 (Debian 12.6-1.pgdg100+1)
- PHP version: 7.4.15
- OS: Linux 4.14.218
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

**Comment by fguillot** [comment]
Please, report this issue to the plugin author. Kanboard doesn't have the concept of groups.

See https://github.com/creecros/Group_assign/issues/57
