### ISSUE TITLE
Error messages in public view: sub tasks

### ISSUE THREAD

**Issue by 3avxxx** [kanboard/kanboard#4807]
I am using Kanboard 1.2.19 without any themes.
When I share my project publicly and people click on a task with sub-tasks, under sub tasks, it says:

Fatal error: Uncaught Error: Call to undefined method Kanboard\Helper\SubtaskHelper::getTitle() in /homepages/39/d647535442/htdocs/XXX/kanboard/plugins/Timetrackingeditor/Template/subtask/table.php:25 Stack trace: #0 /homepages/39/d647535442/htdocs/XXX/kanboard/app/Core/Template.php(83): include() #1 /homepages/39/d647535442/htdocs/XXX/kanboard/app/Template/subtask/show.php(7): Kanboard\Core\Template->render('subtask/table', Array) #2 /homepages/39/d647535442/htdocs/XXX/kanboard/app/Core/Template.php(83): include('/homepages/39/d...') #3 /homepages/39/d647535442/htdocs/XXX/kanboard/app/Template/task/public.php(16): Kanboard\Core\Template->render('subtask/show', Array) #4 /homepages/39/d647535442/htdocs/XXX/kanboard/app/Core/Template.php(83): include('/homepages/39/d...') #5 /homepages/39/d647535442/htdocs/XXX/kanboard/app/Helper/LayoutHelper.php(188): Kanboard\Core\Template->render('task/public', Array) #6 /homepages/39/d647535442/htdocs/XXX/kanboard/app/Helper/Layou in /homepages/39/d647535442/htdocs/XXX/kanboard/plugins/Timetrackingeditor/Template/subtask/table.php on line 25

**Comment by fguillot** [comment]
Please, report the issue directly to the plugin author: https://github.com/stinnux/kanboard-Timetrackingeditor/issues
