### ISSUE TITLE
Cannot filter for "+" sign in search field it returns everything and deletes the + sign from filter field

### ISSUE THREAD

**Issue by oszem** [kanboard/kanboard#4826]
### Actual behaviour

If filtering for "+" sign in filtering field it returns nothing and delete + sign.

### Expected behaviour

It should display results as filtering for other characters.

### Steps to reproduce
create a task with + sign. Search for + sign.

### Screenshots

![image](https://user-images.githubusercontent.com/5314882/120800505-520b8e80-c540-11eb-9e6e-11b2e7104c5c.png)
![image](https://user-images.githubusercontent.com/5314882/120800555-5df75080-c540-11eb-83f9-d6b9c7e40e39.png)
![image](https://user-images.githubusercontent.com/5314882/120800566-63ed3180-c540-11eb-8324-bf46513bdfc4.png)

### Configuration

- Kanboard version:  Version 1.2.16 (October 9, 2020)
- Database type and version: 
- PHP version: 7.3.26
- OS: Windows 10
- Browser: Firefox 88.0.1 64bit

**Comment by oszem** [comment]
Let me answer myself. + sign has a semantic meaning use _%2B_ instead
https://stackoverflow.com/questions/6855624/plus-sign-in-query-string

**Comment by rautamiekka** [comment]
Still, sounds like a bug to me.
