### ISSUE TITLE
Start Date after Due Date

### ISSUE THREAD

**Issue by rolandu** [kanboard/kanboard#4842]
This is minor, I am not sure if it's a bug, it feels like a bug to me.

Maybe I am not understanding the logic of start date and due date correctly. In my mind due date is a plan, not something that has to happen in reality. The start date on the other hand is an actual start date - the date I started working. So if something was due on Monday, it is very possible that in reality I start working on it on Tuesday. Kanboard doesn't allow that currently.

Why is this a problem for me? Because I use the due-date to filter things that are overdue and the start date for tracking purposes. I have an automatic action that sets the start date when I move the ticket to the "in progress" column... the automatic setting of the start date works, but I can never manually update the item again unless I change either of them.

### Actual behaviour

I get an error message: "The start date is greater than the end date"

### Expected behaviour

No such error message

### Steps to reproduce

Set start date after due date

### Configuration

- Kanboard version: v1.2.20
- Database type and version: sqlite 3.34.1
- PHP version: 7.4.19
- OS: Linux 4.19.0-17-amd64
- Browser:  Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by garrettboone** [comment]
@rolandu If you manually attempt to set the start date to after the due date while in the task edit window, this error will show there as well, and will prevent saving the edit. Expecting the error to not be displayed seems to be an usual expectation, but in your scenario it might be an equivalent to expect it to reject the movement to the in-progress column because of the failed auto-task, or maybe deny the auto-task of setting the start date while also throwing the error. What do you think about this?

**Comment by rolandu** [comment]
@garrettboone : I gave it some thought. 

Currently there are:

- Start date
- Due date

The current start date is a bit ambiguous whether it means planned or actual. I think the way it is implemented is "planned start", "planned due". However, I would like to use "actual start" ("planned start" might also be useful sometimes), "planned due".

I think it would be an improvement if instead we had:

- Planned start date
- Actual start date
- Due date
- Actual completed date (closed date? I am not sure if there is an invisible closed date already...)

While I think this would be an improvement, I don't see it as very important.

**Comment by garrettboone** [comment]
In the Task Transitions section: https://docs.kanboard.org/en/latest/user_guide/tasks.html, I think the action of moving betweens columns is the built-in approach to what you are describing additional date fields could also accomplish. When something is meant to be started, but not actually started, moving it to a Backlog column, for example, shows it's not started. Then, when actually started it gets noted. Maybe there is a different way to do what you are ultimately trying to accomplish. Another way to filter what you are looking for, based on a time-in-column approach, or something like that.

**Comment by rolandu** [comment]
Okay, I agree that makes sense. I will use the the start date as a plan and the columns as actual dates.
