### ISSUE TITLE
Use of long passwords

### ISSUE THREAD

**Issue by carlosnewmusic** [kanboard/kanboard#4878]
### Checklist

- [x] I verified that Kanboard is correctly installed
- [x] I checked that the problem does not come from a plugin
- [x] I checked that the problem is not already reported

### Actual behaviour
it says wrong password.

### Expected behaviour
To give a warning of what is the maximum value for the password and not to let put more than that value.

### Steps to reproduce
When changing the password to a 2048 digit password and logging out, 
it won't let me log in, 

### Screenshots
![imagen](https://user-images.githubusercontent.com/19379457/131581982-020ef2dd-0d17-478a-af54-cbad5c5d8e83.png)

### Configuration

- Kanboard version: 1.2.20
- Database type and version: sqlite
- PHP version: 8.0
- OS: Windows NT 10
- Browser: Firefox

**Comment by garrettboone** [comment]
@carlosnewmusic I'm not sure there is a maximum for sqlite. Are you possibly copy/pasting a space on the end of the password or something like that? You could paste in your password, then go into the browser console and change the password field from `type="password"` to `type="text"` and copy back out what you pasted, to compare.

**Comment by rautamiekka** [comment]
https://www.sqlite.org/datatype3.html#affinity_name_examples -> https://www.sqlite.org/limits.html#max_length says the current SQLite string implementation limit is `(2^31)-1` bytes => ~2.14GB. 2KB wouldn't even begin to scratch that.

**Comment by fguillot** [comment]
It works fine for me. I generated a password with 2048 characters on this [website](https://passwords-generator.org/).

I can login and logout without problem. The password length should not be a problem. Tested with Sqlite.
