### ISSUE TITLE
max_file_size logic in php.ini not compatibile with Kanboard logic

### ISSUE THREAD

**Issue by bbushong** [kanboard/kanboard#4896]
### Checklist

- [x] I verified that Kanboard is correctly installed
- [x] I checked that the problem does not come from a plugin
- [x] I checked that the problem is not already reported

### Actual behaviour

When uploading a document, we received an error: "The maximum allowed file size is 0B."

### Expected behaviour

Expected to match php.ini logic. Upon receiving this error, looked at Task FileController response and noticed this line:

<div class="js-file-upload" data-params='{"csrf":"removed",**"maxSize":0,**"url":"\/?controller=TaskFileController&action=save&task_id=537&project_id=14","labelDropzone":"Drag and drop your files here","labelOr":"or","labelChooseFiles":"choose files","labelOversize":"The maximum allowed file size is 0B.","labelSuccess":"All files have been uploaded successfully.","labelCloseSuccess":"Close this window","labelUploadError":"Unable to upload this file."}'></div>

Upon looking at the code, the logic where to get maxSize seems to be here:
app/functions: return min(ini_get('upload_max_filesize'), ini_get('post_max_size'));

In my case, the post_max_size was set to zero. This is based on php documentation:
```
 Maximum size of POST data that PHP will accept.
 Its value may be 0 to disable the limit. It is ignored if POST data reading
 is disabled through enable_post_data_reading.
 http://php.net/post-max-size
```
Instead, kanboard took that upload max size should be 0. I was able to adjust my ini file and problem was resolved for me.

### Steps to reproduce
Set you php.ini max_file_size to 0, and try to upload document.

### Screenshots

N/A

### Configuration

- Kanboard version: 1.2.19
- Database type and version:  sqlite, 3.22.0
- PHP version: 7.2.24-0ubuntu0.18.04.8
- OS: Linux 5.4.0-1054-aws
- Browser:  Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0

**Comment by garrettboone** [comment]
However, `post_max_size` can also be set to 0 for unlimited as well, which then causes a problem. I think the logic will need to address a potential zero setting on either php.ini values, but I'm not clear on what the desired handling should be. And while I was looking into it, should [`phpToBytes()`](https://github.com/kanboard/kanboard/blob/53dfd287309c2b48f1f6c249232b8f1a85c02a05/app/Helper/TextHelper.php#L80) actually have different multipliers for g, m, and k?

**Comment by garrettboone** [comment]
I'm still getting the same bug with the error showing `The maximum allowed file size is 5B.` 

PHP settting is:  `upload_max_filesize => 5M`

I have verified from `functions.php` that the `get_upload_max_size()` function is returning `5242880` as I manually run the function from within the file. But for some reason when the function is run within the app, it returns `5` instead. 

At the bottom of `functions.php` I added `echo 'get_upload_max_size(): ' . get_upload_max_size();` and this is what shows when I go to Add a Document:
![image](https://github.com/kanboard/kanboard/assets/47018474/73443cd0-bd9d-44cc-a46e-a9fa1d8b71a1)

I'm still working on why it would return different values when running manually versus running from the app.

**Comment by rautamiekka** [comment]
Are you running the PHP CLI in 1 of the tests ? The CLI and the PHP run by the Web Server are separate.

**Comment by garrettboone** [comment]
@rautamiekka Yes, one with CLI and one with php-fpm. I just checked settings were the same BUT I must not have restarted the service after changing one - it works ok after restart. False alarm!

![image](https://github.com/kanboard/kanboard/assets/47018474/7361c21a-04ec-4e4f-8ad7-368756b948e7)
