### ISSUE TITLE
Requirements are not actual

### ISSUE THREAD

**Issue by slavkoja** [kanboard/kanboard#4955]
### Checklist

- [x ] I verified that Kanboard is correctly installed
- [ ] I verified that the problem does not come from a plugin -- i do not know
- [x ] I verified that the problem is not already reported
- [x ] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour

I upgraded my kanboard to latest version 1.2.22 on my debian oldstable (buster) server with PHP 7.3, before it i check requirements, which tells >= 7.2, but after install i got only this in browser:
```
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". 
```
I not found any other information about this, in logs there are only 500 responses.

### Expected behaviour

perhaps updating requirements is needed?

### Configuration

- Kanboard version: 1.2.22
- Database type and version: sqlite3, 3.27.2
- PHP version: 7.3.31
- OS: Debian buster

**Comment by madiko** [comment]
I encountered the same issue (unfortunately didn't saw this beforehand). 
My current webversion is 7.3.10.

**Comment by vedranmiletic** [comment]
See #4954

**Comment by mikeperalta1** [comment]
Same on my RockyLinux

```
PHP 7.2.24 (cli) (built: Oct 22 2019 08:28:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by madiko** [comment]
Hello everyone, luckily I found a solution so that I now can upgrade my php-version. So I fixed my problem. Thank you.
Frederic @fguillot, as far as I understood Slavko @slavkoja it would be advicible to at least set the minimum requirements to php 7.4 -- as you said yourself. So nobody is surprised by the error. Best regards and many thanks for your great work, Franziska
