### ISSUE TITLE
Signal plugin: old version of Signal plugin in plugins.json 

### ISSUE THREAD

**Issue by mdino-gh** [kanboard/kanboard#4961]
### Checklist

- [ x] I verified that Kanboard is correctly installed
- [ x] I verified that the problem does not come from a plugin
- [ x] I verified that the problem is not already reported
- [ x] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour

In the plugin administration an old version 1.0.1 of the Signal plugin is linked. Version 1.0.2 has been released in April 2021. Version 1.0.1 contains a bug that prevents sending notifications from a project (Fix: Use of correct variable ($project['id']) in function notifyProject()).) The bug causes the error message "Undefined variable: user in .../kanboard/plugins/Signal/Notification/Signal.php on line ..." to appear as reported in https://github.com/kanboard/kanboard/issues/4159.

### Expected behaviour

Version 1.0.2 of Signal plugin is offered for installation.

### Steps to reproduce

- go to plugin administration
- check version that is offered for installation

### Screenshots

Configuration from https://kanboard.org/plugins.json 

    "signal": {
        "title": "Signal",
        "version": "1.0.1",
        "author": "Benedikt Hopmann",
        "license": "MIT",
        "description": "Receive Kanboard notifications on Signal (via signal-cli).",
        "homepage": "https://github.com/stratmaster/kanboard-plugin-signal",
        "readme": "https://raw.githubusercontent.com/stratmaster/kanboard-plugin-signal/master/README.md",
        "download": "https://github.com/stratmaster/kanboard-plugin-signal/releases/download/v1.0.1/Signal-1.0.1.zip",
        "remote_install": true,
        "compatible_version": ">=1.0.37"

### Configuration

- Kanboard version: 1.2.22 and latest dev version pulled from git on 21.02.2022
- Database type and version:  10.5.12-MariaDB-0+deb11u1
- PHP version: 7.4.28
- OS: Linux 5.10.87-v7l+
- Browser: Firefox 97.0

**Comment by fguillot** [comment]
Ask the plugin author to update the version in `plugin.json` (or send a pull-request). See https://github.com/kanboard/website/blob/master/README.md

**Comment by mdino-gh** [comment]
The issue can be closed. I created a pull request https://github.com/kanboard/website/pull/306

Thanks!
