### ISSUE TITLE
Import does not work on Exported Files (Nothing has been imported error)

### ISSUE THREAD

**Issue by srinathganesh** [kanboard/kanboard#4966]
### Checklist

- [x] I verified that Kanboard is correctly installed
- [x] I verified that the problem does not come from a plugin
- [x] I verified that the problem is not already reported
  - [x] CSV uses " and , (All issue have data mismatch which I dont have)

### Expected behaviour

1. Perform Export to get a file
2. Perform Import to restore the exported Tasks

### Steps to reproduce
1. Perform Export to get a file
2. Perform Import to attempt to restore it

### Screenshots
![image](https://user-images.githubusercontent.com/43715636/155919710-d8247107-6994-43d0-8ee8-2b4cfe5bd730.png)

File: [Tasks (5).csv](https://github.com/kanboard/kanboard/files/8150424/Tasks.5.csv)

### Logs
NA

### Configuration
Application version:
PHP version: 7.4.28
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 4.15.0-144-generic
Database driver: sqlite
Database version: 3.36.0
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36

**Comment by fguillot** [comment]
The columns for import and export are not the same. This is a source of confusion, and it has been reported in the past several times (see #3639 and #3107).

**Comment by srinathganesh** [comment]
> The columns for import and export are not the same. This is a source of confusion, and it has been reported in the past several times (see #3639 and #3107).

Ok thanks, I only found about issues regarding seperator mismatch. Will check out these posts

**Comment by fguillot** [comment]
Ideally, the import and export formats should be the same to avoid confusion.

**Comment by srinathganesh** [comment]
> The columns for import and export are not the same. This is a source of confusion, and it has been reported in the past several times (see #3639 and #3107).

Thanks after re-ordering the columns now import seems to work.

I cannot comment on these two closed posts,
Is Description part of the export? Because my export is missing Description column.
