### ISSUE TITLE
Attach A Document (File Upload) Stays at 0%

### ISSUE THREAD

**Issue by arumand** [kanboard/kanboard#4976]
### Checklist

- [X] I verified that Kanboard is correctly installed
- [X] I verified that the problem does not come from a plugin
- [X] I verified that the problem is not already reported
- [X] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour

I am trying to Attach a document to a task. Any filetype that i try to attach, the GUI always give 0% on the progress bar.

Nothing happen. I've tried to debug it. But i don't get any [error] tag.

File upload with Apache and PHP works fine on other apps.

### Expected behaviour

Can attach a document.

### Steps to reproduce

Upload any file via "Attach a document" link.

### Configuration

- Kanboard version: 1.2.22.
- Database type and version: 10.5.12 MariaDB.
- PHP version: 7.4.28.
- OS: Debian 11.
- Browser: Firefox 98. Opera 84.0.4316.31.

**Comment by zlance88** [comment]
have you checked the data folder access on server?
such as:
sudo chown -R www-data:www-data /var/www/yourwebsite/kanboard-$version/data

**Comment by fguillot** [comment]
The user interface can be confusing. The upload doesn't start until you click on the "Upload Files" button.

![image](https://user-images.githubusercontent.com/323546/158506210-e799570e-1724-48aa-8319-ab1fb87e1c4e.png)

Make sure to watch the logs for potential errors when you click on this button.

**Comment by arumand** [comment]
> The user interface can be confusing. The upload doesn't start until you click on the "Upload Files" button.
> 
> ![image](https://user-images.githubusercontent.com/323546/158506210-e799570e-1724-48aa-8319-ab1fb87e1c4e.png)
> 
> Make sure to watch the logs for potential errors when you click on this button.

Yes. You're right. It works correctly. Sorry for this trival matter.
