### ISSUE TITLE
No delete user button

### ISSUE THREAD

**Issue by peterVoisin** [kanboard/kanboard#4985]
I don't see a delete user button.
Where should he be?

**Comment by aqeeliz** [comment]
AFAIK you can't delete user, you can only deactivate it.

**Comment by fguillot** [comment]
You can delete local users. Go to the list of users and open the contextual menu.

![image](https://user-images.githubusercontent.com/323546/160509510-53dcd965-5b4a-44e9-beb0-58080ce5c128.png)

**Comment by peterVoisin** [comment]
Oh thanks !
Yet I searched, but I was not there
