### ISSUE TITLE
User's avatar link was broken

### ISSUE THREAD

**Issue by zitter7** [kanboard/kanboard#5093]
### Checklist

- [x] I verified that Kanboard is correctly installed
- [x] I verified that the problem does not come from a plugin
- [x] I verified that the problem is not already reported
- [x] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour
![](https://i.imgur.com/kN7Ef4s.png)

### Expected behaviour
![](https://i.imgur.com/XO45h6A.png)

### Steps to reproduce

It works on v1.2.22(docker version), but higher version not.

### Logs

PHP message: PHP Deprecated:  Implicit conversion from float -4.5 to int loses precision in /var/www/app/app/Core/Thumbnail.php on line 130"
PHP message: PHP Deprecated:  Implicit conversion from float -1.5 to int loses precision in /var/www/app/app/Core/Thumbnail.php on line 130"
2022/11/13 04:35:08 [error] 15#15: *5 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Implicit conversion from float -1.5 to int loses precision in /var/www/app/app/Core/Thumbnail.php on line 130" while reading response header from upstream, client: 192.168.1.xxx, server: localhost, request: "GET /?controller=AvatarFileController&action=image&user_id=2&hash=a16304d8d23a41b57&size=20 HTTP/1.1"

### Configuration

- Kanboard version: v1.2.24 (Docker version)
- Database type and version: Postgres 14.5
- PHP version: 8.1
- OS: Manjaro
- Browser: Vivaldi

**Comment by zitter7** [comment]
Changing size can help, but when I created a new container without plugin, avatar was incorrectly again.

And finally, I found that if I upload a image with size 96x96, it works, and 96x97 not.

**Comment by p4kl0nc4t** [comment]
Any update on this one? I can confirm this one on mine with same version (run with Docker).
