### ISSUE TITLE
Attachments can't be seen or downloaded in Public view

### ISSUE THREAD

**Issue by RainerBielefeld** [kanboard/kanboard#5103]
### Checklist

- [X] I verified that Kanboard is correctly installed
- [ ] I verified that the problem does not come from a plugin
- [X] I verified that the problem is not already reported
- [X] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behavior
Attachments can't be seen or downloaded in Public view. Also Hyperlinks in Task or Comment to uploaded KANBOARD-Attachments do not work

### Expected behaviour
Links do work in Public view, Attachments listed

## My Configuration
* KANBOARD Application version: 1.2.24 on all-inkl.com
* PHP version: 7.4.28
* PHP SAPI: fpm-fcgi
* HTTP Client: cURL
* OS version: Linux  5.4.0-131-generic
* Database driver: mysql
* Database version:  10.5.16-MariaDB-1:10.5.16+maria~focal-log
* Profile Language: German
* [Plugins](https://kanboard.org/plugins.html):
   * [AddMermaid](https://github.com/euneuber/AddMermaid) 0.1.0
   * [AgileIndicators](https://github.com/aljawaid/AgileIndicators) 1.0.0
   * [AutomaticActionUX](https://github.com/aljawaid/AutomaticActionUX) 1.6.0
   * [Broadcast](https://github.com/kanboard/plugin-broadcast) 1.0.1
   * [Chat](https://github.com/kanboard/plugin-chat) 1.0.3
   * [Customizer](https://github.com/creecros/Customizer)  1.14.0
   * [Group assignment for tasks](https://github.com/creecros/Group_assign) 1.7.12
   *  [KanboardSearch](https://github.com/ipunkt/KanboardSearch)  	1.1.0
   * [KanboardEmailHistory](https://github.com/aljawaid/KanboardEmailHistory)  1.2.0
   * [KanboardSupport](https://github.com/aljawaid/KanboardSupport) 1.5.0
   * [MarkdownPlus](https://github.com/creecros/MarkdownPlus)  1.1.0
   *  [Paste image to markdown](https://github.com/Chaosmeister/PITM) 1.0.3
   * [Plugin Registration v1.0.8](https://github.com/kanboard/plugin-registration/) 
   * [ProjectInvitation](https://github.com/ipunkt/KanboardProjectInvitation)   1.0.0
   * [Self-Registration](https://github.com/kanboard/plugin-registration)  1.0.8
   * <s>TaskProgressBar</s>
   * [SubtaskDescription](https://github.com/shaun-fong/Subtaskdescription) 1.1.1
   * [Task2Pdf](https://github.com/creecros/Task2pdf)  1.5.0
   * [Wiki](https://github.com/funktechno/kanboard-plugin-wiki)  0.3.0
* Browser: **SeaMonkey** 2.53.14 Beta pre, Build-Identifikator: 20220801210005  (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0)

**Comment by Kolossi** [comment]
> And that is an opinion ...

>And that is an opinion ...

@RainerBielefeld : nope!

Does the program do something different than what it stated it would do?

As stated by the author, it's a feature request and with the software frozen as you read before submitting, it's unlikely.  And even less so now I'd imagine :-)

**Comment by ulrischa** [comment]
I think it is very important to see the attachments in the public view.
