### ISSUE TITLE
Add "no color" oder "white" as possible selection in the task creation / edit dialog

### ISSUE THREAD

**Issue by JustFxDev** [kanboard/kanboard#5109]
Hi there,

first of all: thanks for all the great work. I use Kanboard for a few weeks and i like the smal and convienent development, administration and installation design of the whole system. Not forgeting to mention the functionalty. 

The design features maybe could be nicer and fresher, but this is only CSS :-)

I wonder if it is possible to have a small adjustment to the color selection in the task create / edit dialog. I would like to have "white" or "no color" as background color in that dropdown as first choice / default. 

Maybe i'am able to provide a branch on my own for that, but 'am not a php guy. I would need some guidiance where to find the neccessary code to change and what to keep in mind when doing so.

Thanks!

Cheers, fx

**Comment by JustFxDev** [comment]
![file](https://user-images.githubusercontent.com/82320201/208049355-b519edb3-6064-4af4-ae3a-952f0ffbcca8.jpg)

**Comment by creecros** [comment]
@fguillot 
<html>
<body>


model:color:get-list | Alter default_colors values
-- | --



</body>
</html>

if you can give an example for how this hook would allow us to alter the color list, it would greatly help.

**Comment by JustFxDev** [comment]
With the latest version of the [ColorManager ](https://github.com/aljawaid/ColorManager) plugin from @aljawaid, you can work with additional colors far beyond that.

This means that it is no longer necessary to make changes to the core.
