### ISSUE TITLE
Wrong column name refered as id - schema version 90

### ISSUE THREAD

**Issue by almmos** [kanboard/kanboard#5164]
### Checklist

- [x ] I verified that Kanboard is correctly installed
- [x ] I verified that the problem does not come from a plugin
- [x ] I verified that the problem is not already reported
- [x ] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour
**Trying to manually install and run Kanboard, when accessing the service for the first time - the login page - I receive the following output:**
Internal Error: Unable to run SQL migrations: Running migration \Schema\version_1, Running migration \Schema\version_2, Running migration \Schema\version_3, Running migration \Schema\version_4, Running migration \Schema\version_5, Running migration \Schema\version_6, Running migration \Schema\version_7, Running migration \Schema\version_8, Running migration \Schema\version_9, Running migration \Schema\version_10, Running migration \Schema\version_11, Running migration \Schema\version_12, Running migration \Schema\version_13, Running migration \Schema\version_14, Running migration \Schema\version_15, Running migration \Schema\version_16, Running migration \Schema\version_17, Running migration \Schema\version_18, Running migration \Schema\version_19, Running migration \Schema\version_20, Running migration \Schema\version_21, Running migration \Schema\version_22, Running migration \Schema\version_23, Running migration \Schema\version_24, Running migration \Schema\version_25, Running migration \Schema\version_26, Running migration \Schema\version_27, Running migration \Schema\version_28, Running migration \Schema\version_29, Running migration \Schema\version_30, Running migration \Schema\version_31, Running migration \Schema\version_32, Running migration \Schema\version_33, Running migration \Schema\version_34, Running migration \Schema\version_35, Running migration \Schema\version_36, Running migration \Schema\version_37, Running migration \Schema\version_38, Running migration \Schema\version_39, Running migration \Schema\version_40, Running migration \Schema\version_41, Running migration \Schema\version_42, Running migration \Schema\version_43, Running migration \Schema\version_44, Running migration \Schema\version_45, Running migration \Schema\version_46, Running migration \Schema\version_47, Running migration \Schema\version_48, Running migration \Schema\version_52, Running migration \Schema\version_53, Running migration \Schema\version_54, Running migration \Schema\version_55, Running migration \Schema\version_56, Running migration \Schema\version_57, Running migration \Schema\version_58, Running migration \Schema\version_59, Running migration \Schema\version_60, Running migration \Schema\version_61, Running migration \Schema\version_62, Running migration \Schema\version_63, Running migration \Schema\version_64, Running migration \Schema\version_65, Running migration \Schema\version_66, Running migration \Schema\version_67, Running migration \Schema\version_68, Running migration \Schema\version_69, Running migration \Schema\version_70, Running migration \Schema\version_71, Running migration \Schema\version_72, Running migration \Schema\version_73, Running migration \Schema\version_74, Running migration \Schema\version_75, Running migration \Schema\version_76, Running migration \Schema\version_77, Running migration \Schema\version_78, Running migration \Schema\version_79, Running migration \Schema\version_80, Running migration \Schema\version_81, Running migration \Schema\version_82, Running migration \Schema\version_83, Running migration \Schema\version_84, Running migration \Schema\version_85, Running migration \Schema\version_86, Running migration \Schema\version_87, Running migration \Schema\version_88, Running migration \Schema\version_89, Running migration \Schema\version_90, SQLSTATE[HY000]: General error: 1 no such column: id (You may have to fix it manually)

**On a subsequent reload of the page the error returned is limited to:**
Internal Error: Unable to run SQL migrations: Running migration \Schema\version_90, SQLSTATE[HY000]: General error: 1 no such column: id (You may have to fix it manually)

**Possible FIX**
The migration script return an error in [**php function**](https://github.com/kanboard/kanboard/blob/main/app/Schema/Sqlite.php#L447-L474) "version_90" related to adding a new '**role**' column in '**project_has_users**' table.
The script is trying to update existing records with some value for the new column and on [**line 466**](https://github.com/kanboard/kanboard/blob/main/app/Schema/Sqlite.php#L466) is preparing the required SQL statement using '**id**' name in WHERE clause referring a non existing column in '**project_has_users**' table.
I suppose the correct column to be referred to is '**user_id**'.
Same error is encountered few lines down, on [**line 471**](https://github.com/kanboard/kanboard/blob/main/app/Schema/Sqlite.php#L471): '$row['id'],'. Here the reference is again to the same non existing column 'id' and I think this also must be change to '**user_id**'.

Applying the already mentioned modification, allow me to access Kanboard login page without any more problems.

**Important questions I don't have answer for:**
Why this error is revealed long time after the version 90 of the schema is in place?
Is this related to a new or reviewed way on catching exception and handling them?
### Expected behaviour
To access the Kanboard login page without any problems

### Configuration

- Kanboard version: 
v1.2.22 from FreeBSD packages system
v1.2.27 from github
- Database type and version: Sqlite 3.41.0
- PHP version: 8.0.28
- OS: FreeBSD 13.1-RELEASE-p6
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0

**Comment by atomicbeecz** [comment]
Hi @drewgoodin , finally got some time and seems that @almmos was right:
edit file in app/Schema/Sqlite.php 
and replace the whole part of "function version_90(PDO $pdo)" with:
`function version_90(PDO $pdo)
{
    $pdo->exec("
        CREATE TABLE project_has_groups (
            group_id INTEGER NOT NULL,
            project_id INTEGER NOT NULL,
            role TEXT NOT NULL,
            FOREIGN KEY(group_id) REFERENCES groups(user_id) ON DELETE CASCADE,
            FOREIGN KEY(project_id) REFERENCES projects(user_id) ON DELETE CASCADE,
            UNIQUE(group_id, project_id)
        )
    ");

    $pdo->exec("ALTER TABLE project_has_users ADD COLUMN role TEXT NOT NULL DEFAULT '".Role::PROJECT_VIEWER."'");

    $rq = $pdo->prepare('SELECT * FROM project_has_users');
    $rq->execute();
    $rows = $rq->fetchAll(PDO::FETCH_ASSOC) ?: array();

    $rq = $pdo->prepare('UPDATE project_has_users SET "role"=? WHERE "user_id"=?');

    foreach ($rows as $row) {
        $rq->execute(array(
            $row['is_owner'] == 1 ? Role::PROJECT_MANAGER : Role::PROJECT_MEMBER,
            $row['user_id'],
        ));
    }
}`

**Comment by kimminss0** [comment]
Hi, @atomicbeecz, there's one mistake on your solution. 😉

You should use
```
            FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE CASCADE,
```
instead of
```
            FOREIGN KEY(group_id) REFERENCES groups(user_id) ON DELETE CASCADE,
```
