### ISSUE TITLE
Column Grouping / Split columns

### ISSUE THREAD

**Issue by elnicko** [kanboard/kanboard#530]
Is there a plan to implement grouping of columns? 

This would be a great visual aid for implementing a well defined "task-pull" strategy, e. g. in software projects. Basically, it should look like this - the columns are grouped on the board so that columns of the same group are displayed next to each other, and the name of the group is displayed over the names of the column.

This is best illustrated by the following example, where there are two columns (Doing, Done) in each of the groups (Development, Test, Release etc). Currently, I create two columns for each aspect (Development, Test Release) and add _Doing_ or _Done_ at the end of the name. It works, however it doesn't look optimal, as the name gets too long and moves to a second line or flows over to the column next to it. A good example of this usage of a kanban board is given in this slideshare: http://image.slidesharecdn.com/kanbanboards-100328050846-phpapp02/95/kanbanboards-26-728.jpg

In terms of the data flow in the model, I don't expect it to change anything in the way kanboard works (except maybe the unique constraint on the column names), it would simply add a _visual aid_, so that project managers are able to add more structure to the board and streamline processes.

**Comment by TabDambrine** [comment]
We have a project with a similar structure and we use swimlanes to represent that, hence we have 4 columns (waiting,doing,validating,deploying) and some swimlanes (which could represent your groups of columns) : development,server,database,documentation,...

Could this solution works for your need, despite the fact that those informations would be displayed in an horizontal way ?

**Comment by elnicko** [comment]
An interesting idea, but after more consideration, it wouldn't quite work, because it would leave us without prioritization tool (swimlanes). Our target setup is as follows:

The columns are called only Doing and Done, but there are (in your case) 4 pairs of them, each called differently: waiting, doing, validating, deploying (again, in your case). Hence, the groups represent the activities, and the columns represent the progress. We use categories to implement task categorization (in your case development, server, database, documentation), and swimmlanes to implement priorities.

Currently it works great with 8 columns by simply creating two columns and appending (Doing or Done) at the end of the name, However it is not a clean solution, hence the feature request. I hope it is valid and wished upon also by others and I offer my services as a tester at any time.

Cheers,
el.nicko

**Comment by TabDambrine** [comment]
I see what you mean,

I can not figure out a way to handle this with the current kanboard functionalities (eventually the tasks colors, you did not mention them but maybe they are already in use in your setup), so i can only agree with the FR.

The main drawback i can see is the one you pointed out in your original post about the column names, and maybe the consequences on the "analytics" functionality which uses column names.

**Comment by fguillot** [comment]
Sub columns are not yet available.

The only way to simulate that is to add a column for each sub column: "Analyze Doing" and "Analyze Done" by example. But you are already doing that...

**Comment by RainerW** [comment]
Would love this Feature, especially when the WIP limits still would be applied on the 'master' column.

**Comment by AndyCoach** [comment]
Another vote to implement this feature.

**Comment by arougthopher** [comment]
+1 here too
Would be nice to have the column groups have their own WIP limits as well
Our kanboard is like this:
Breakdown:Active
Breakdown:Done
Implementation:Active
Implementation:Review
Implementation:Tracking (does not affect WIP limits)
Implementation:Done
Validate:Active
Validate:Done (this is done/done and has not WIP either)


For all of Implementation (minus tracking, as those are where items go when they get blocked), we have a calculated WIP limit based on team size.  Breakdown has a WIP limit for the Active , but not Done, as the Breakdown:Done is the broken down tasks from Breakdown:Active that are ready to be worked on.  

Our board is based on the recommendations of Eric Brechner's [book]( http://www.amazon.com/Project-Management-Kanban-Developer-Practices/dp/0735698953/ref=sr_1_4?s=books&ie=UTF8&qid=1446070760&sr=1-4&keywords=kanban).

**Comment by bproffitt** [comment]
Chiming in, this is definitely a feature my organization would love to see, since a single-column "triage" area for tasks would be great. From there, tasks can be pulled into team-based swim lanes.

**Comment by nekopa** [comment]
:+1:  Here too.
I am trying to implement a personal kanban using the methods in the book Personal Kanban by Jim Benson, and being able to split a column horizontally as well as vertically would be fantastic. Leankit's Kanban has this feature if you want to see it in action. 

I have the current version of Kanboard up and running on my development machine, so I will try to take a stab at it myself, but it has been years since I have worked in PHP, so it will take me a while :)

**Comment by tvriend** [comment]
+1 from my side as well.
We use a WIP limit for "In progress" and a WIP for "Ready & In progress" combined.
Would love to see the addition of parent groups with a WIP limit and a column within the group with a WIP limit

|||        SPRINT (10)          |||
||| Ready || In progress (6) |||

**Comment by LordTimber** [comment]
:+1: Vote!
Yes, please implement this feature.
WIP limits from the group master column must inherited to the sub-column.

**Comment by SchmilK** [comment]
I was just looking at a similar image this morning while researching best practices for kanban.  This would be a great addition.

**Comment by LordTimber** [comment]
@fguillot 
We wait much on this. Will be this feature soon?

It would be great when it comes and we would love it.

**Comment by gusthoff** [comment]
@fguillot: I've just created a plug-in that might be interesting for this issue:

https://github.com/gusthoff/kanboard-plugin-column-group

Please let me know if you want to discuss enhancements and/or further steps.

**Comment by Busfreak** [comment]
Really cool! I will test it and comment on your github site!

**Comment by arougthopher** [comment]
@gusthoff 
Finally had a chance to test this! Looks good for an initial implementation.  Some things to add/modify:
- Column Group WIP limits, for specific columns specified in the group
- UI cleanup (which you mentioned) - group name should be above column headers, not below

**Comment by FortuneFishDavid** [comment]
VOTE! Would love to see splitting of columns and also horizontal splits within columns (see pic)
![kanban-boards-step-by-step-154-638](https://cloud.githubusercontent.com/assets/12561772/22417512/8dfa0cc0-e6cc-11e6-876d-eee3fa7afe18.jpg)

**Comment by 2Belette** [comment]
@arougthopher 
When you installedi it, had you had any issue when you ticked the *+* button close to the column name to create a task ? 
on mine it breaks the task creation when I installed the plugin..

**Comment by arougthopher** [comment]
I haven't used it much, and not sure if it is even running still.  If I get a chance, I can test that for you.

**Comment by 2Belette** [comment]
@arougthopher cool thanks don't hesitate to share your findings
I had to remove the plugin as I was unable to create tasks with the plugin activated..

**Comment by pufface** [comment]
Vote. This feature is really missing :(

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. If you still need this feature, you should consider contributing to this open-source project. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
