### ISSUE TITLE
Actions sur les colonnes

### ISSUE THREAD

**Issue by essembeh** [kanboard/kanboard#55]
Pour completer les actions automatiques sur les colonnes, ce serait pratique pour effectuer une action sur toutes les tâches d'une colonne.

Par exemple "Déplacer toutes les tâches vers une colonne", "Réinitialiser les statuts des taches"...

Cas d'utilisation: Si j'utilise un kanban pour gérer un plan de test, une fois le plan fini, c'est utile de pouvoir déplacer et reinitialiser XXX taches en une fois pour une prochaine campagne.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
