### ISSUE TITLE
Issues with Comments After Upgrading from v1.2.35 to Higher Versions

### ISSUE THREAD

**Issue by xnardo** [kanboard/kanboard#5568]
### Checklist

- [x] I verified that Kanboard is correctly installed
- [x] I verified that the problem does not come from a plugin
- [x] I verified that the problem is not already reported
- [x] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour

When I upgrade from v1.2.35 to any higher version, all tasks with comments display an error in the visual format. There's also an error when adding a new comment in the newer versions. I've attached an image below.

### Steps to reproduce

 Issues After Upgrading from Kanboard v1.2.35 to Any Higher Version

### Screenshots and Video Recording

![kanboard-error](https://github.com/user-attachments/assets/e311452f-a514-4222-96f0-7be901199bda)

### Configuration

- kanboard/kanboard:v1.2.35
- Database type and version: mariadb:10.9.2

**Comment by dev-rfd** [comment]
<img width="565" alt="kb-empty-html-head" src="https://github.com/user-attachments/assets/42248baa-e644-4708-8dd1-121685bb9d28">

**Comment by xnardo** [comment]
Thank you so much!

I’ve solved it. It was the `MarkdownPlus extension`. I uninstalled it, then updated to 1.2.40, and then reinstalled `MarkdownPlus`, and it worked. Big hug!
