### ISSUE TITLE
View multiple table in the same page

### ISSUE THREAD

**Issue by Squale76** [kanboard/kanboard#6]
could you add the possibility to view multiple projects in the same page with "include".
The top, have the possibility to drag and drop a task between two projects.

**Comment by stinnux** [comment]
I have created a bigboard plugin, maybe you want to try it out. However, it is currently not possbile to drag-and-drop tasks between different projects.

https://github.com/stinnux/kanboard-bigboard

**Comment by dhornford** [comment]
You might want to update the front page that says it still depends upon PR2474
Or, change the 0.9.9 release which says no changes are required.


Dave Hornford
Conexiam. Straightforward answers to complex problems.
www.conexiam.com | 403.818.4303

**Comment by fguillot** [comment]
The software is not really made for that initially. That will occurs too many change. I prefer to keep the software very simple.

Thank you for your understanding.
