### ISSUE TITLE
Swimlanes automatic actions

### ISSUE THREAD

**Issue by oparoz** [kanboard/kanboard#633]
Now that we have swimlanes, it would be nice to be able to use them in automatic actions.

External label A -> Swimlane A
Category B -> Swimlane B
User C -> Swimlane C
etc.

In case of conflicts, I guess it would be nice to be able to re-arrange automatic actions instead of having to start from scratch.

**Comment by AlgyTaylor** [comment]
:+1:  for this, I was just thinking this yesterday :)

**Comment by Chaosmeister** [comment]
:+1:

**Comment by Biniou180** [comment]
Maybe it could be possible to do the other way too?
For example: When a task is dropped into a swimlane, it triggers an action (assign to user A).

**Comment by ukanalyst** [comment]
I just created a pull request that allows the use of swimlane change as a trigger also includes two new actions: set colour on swimlane change and set priority on swimlane change. You can view my pull request here: https://github.com/kanboard/kanboard/pull/2587

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
