### ISSUE TITLE
Multiple events for one action

### ISSUE THREAD

**Issue by LiaraAlis** [kanboard/kanboard#650]
It would be nice, if it were possible, to select more than one event for a action.
Example: A color has to be assigned to a user but not only on creation of a task, even if the responsibility is changed.

**Comment by fguillot** [comment]
You can also create multiple actions to assign a color to user.

**Comment by LiaraAlis** [comment]
Hi fguillot,
you're right. But in my opinion it is very confusing, because you need to select the same user and the same color more than once.

**Comment by fguillot** [comment]
The software is not really made for that initially. That will occurs too many change. I prefer to keep the software very simple.

Thank you for your understanding.
