### ISSUE TITLE
E-mail features

### ISSUE THREAD

**Issue by spacilly** [kanboard/kanboard#73]
It would be nice to send emails to users of the project.
Ex: send an e-mail when the task is completed, when the task status changes, when comment is added or updated ...

Users who receive e-mail will be selected using checkbox like Basecamp does.

**Comment by Guybrush333** [comment]
Thanks for all the hard work! I know this is probably not high on the priority list, but in my opinion there are too many emails sent out. It'd be desireable to be able to choose which events trigger E-Mails for me. Keep it coming! =D

**Comment by klaw1** [comment]
Or if email has the option of sending only to the assigned person.

**Comment by mpscy** [comment]
Sehr geehrte Damen und Herren,

Sie erreichen mich wieder ab dem 26. Mai. Ihre E-Mail beantworte ich anschließend umgehend.

Für Anfragen im Bereich Medical Consulting steht Ihnen bis dahin Herr Robert Woywod unter consulting@heartbeat-med.de zur Verfügung.

Für Anfragen im Bereich Medical Solutions und heartbeat ONE können Sie sich an Herrn Marc Tiedemann unter tiedemann@heartbeat-med.de wenden.

In dringenden Fällen stehen Ihnen unsere Berliner und Kölner Büros auch gerne telefonisch zur Verfügung.

Mit freundlichen Grüßen
Yannik Schreckenberger
