### ISSUE TITLE
Request zone de saisie de titre multi ligne

### ISSUE THREAD

**Issue by ArnaudAtlog** [kanboard/kanboard#774]
Bonjour,

Nous sommes une petite équipe de 10 développeurs répartie dans toute la France, et nous apprécions énormément votre produit.

Je ne sais pas si cela pourra être possible un jour, mais j'ai une demande qui m'a été proposée plusieurs fois : 

Serait t'il possible lors de la création/édition d'une fiche (post-it /task) que la zone de saisie du titre accepte le multi-ligne? à l'affichage dans le Kanboard le titre apparaît bien sur plusieurs lignes si il est très long  mais pas à la saisie du coup lorsque nous devons saisir des titres assez longs on ne voit pas ce qu'on écrit.

Merci pour ce produit.
Très bonne journée
Arnaud

**Comment by GrCOTE7** [comment]
Bonjour, Arnaud,

A travers votre requête, j'entends surtout que vous êtes une team francophone de dev axé sur KB...

J'apprécie au plus haut point cet outil que je n'ai ma foi pourtant découvert que trop récemment.

Adorant le dev, je serais heureux de rejoindre votre team afin d'y apporter ma contribution peut-être.

Est-ce envisageable ?

@++

**Comment by fguillot** [comment]
@GrCOTE7 C'est un projet open source, tout le monde peut contribuer, il faut seulement respecter la philosophie du logiciel (rester simple). Un point de départ serait peut-être de jeter un coup d'oeil à la doc pour les contributeurs: http://kanboard.net/documentation/contributing

**Comment by GrCOTE7** [comment]
Oki, super...

Et, au fait 'fguillot', ça fait qqes jours que je me disais qu'il faudrait bien que je vous fasse signe, pour au moins vous féliciter pour cet excellent outil dont vous faite activement la mise au point (y) !

BRAVOS !

++ :-)

**Comment by fguillot** [comment]
@ArnaudAtlog Malheureusement, le logiciel à pour vocation de rester simple et le nombre de fonctionnalités est volontairement limité. Il reste la toujours le champ de description pour y mettre plus de détails.
