### ISSUE TITLE
Budget discussion and propositions

### ISSUE THREAD

**Issue by oliviermaridat** [kanboard/kanboard#791]
The new budget feature seems very useful for time and budget tracking. I don't know yet how to use that in my projects, but I have the feeling that it may be useful.
I understand that this feature is a work in progress, and I am willing to discuss it if it may help to improve it. Here are my questions...

Why all computations are only done on subtasks? Having a task without subtasks does not seem to be a bad practice. A task by itself is time and budget consuming.

I like the idea of computing automatically the time spent on a subtask. However, sometimes it may cause issues for 2 reasons:
- someone can forget to change the status of the subtask, and that will break all computation. 
- even if there is timetable per user, it is common to leave work before or after the schedule, or to be interrupt by someone during a task. Yes, it is possible to add overtime or timeoff, or to click on "Terminate" (to pause the subtask) and reclick on "in progress", but it is really time consuming.

Therefore, I am wondering, if the "Time spent" can't be used in place of the computed time spent. Something like:
- If a manual "Time spent" is filled: use it
- Otherwise, use the computed "Time spent".

**Comment by fguillot** [comment]
The budget feature and the subtask time tracking have been developed for a specific company to fit their workflow. They pay for that and they accepted to give the source code of this feature to the community.

However, it can be improved like you said.

- Having a start/stop button to record the time spent (mentioned in another ticket)
- Override the calculated time spent with the value entered in the form

**Comment by oliviermaridat** [comment]
Eh, that's great.

**Comment by kasunf** [comment]
timeoff doesn't work for me.. Is something wrong with my installation or else?
