### ISSUE TITLE
Calendar Time Slot

### ISSUE THREAD

**Issue by Rogieee** [kanboard/kanboard#794]
Calendar Time slot allocation doesn't  seem to save.
Any deadline on when the time slot allocation can be saved.
see video below for example.
http://web-disk.co.uk/files/issue.mp4

**Comment by sebelk** [comment]
:+1:  It has to do with #662 and as fguillot stated "Note: The due date doesn't contain the time, only the date." It could be nice that this feature be added

**Comment by fguillot** [comment]
Currently, when you move a task in the calendar that change the due date and this date doesn't contains any time information. Before it was containing the time, but people complained so I changed that.

**Comment by sebelk** [comment]
:ok:  Thanks fguillot, but so what is the sense of having a calendar view with times if we could not use it at all? IMHO I think that this feature could be optional, and if someone likes he could enable it

**Comment by Rogieee** [comment]
I too would like the ability to save the time slot from the calendar view.

If it has been available in previous code what version should I look for or what code do I need to change.

Many thanks.

Steve.

**Comment by sebelk** [comment]
In fact I've started to use kanboard (before of that used taskboard) because has a calendar :worried:

**Comment by fguillot** [comment]
At the moment, you can also display subtasks time tracking information and subtasks estimates in the calendar (options in settings).

In the future, I plan to display more stuff in the calendar. By example, the tasks based on the start and close date or the tasks based on the estimate. Maybe add also a task time tracking...

It's a work in progress...

**Comment by hicter00** [comment]
+1 for time - sometimes tasks, deliverables and milestones are due at a specific time.  People don't have to use the time if they don't want - but a good option for those that need it.

**Comment by Rogieee** [comment]
I will keep a look out for your update fguillot.
I am going to put the current version into a beta test environment of 10 Users next week.
Fingers crossed they don't want the time function. :+1:

**Comment by Rogieee** [comment]
Just an update .
I have kanboard running in a full test production environment and its is working without fail..
The staff (3) have made it there own.
Just need the calendar time slot function to save the data and we could call it a live production system with (10) plus staff using it.

**Comment by Rogieee** [comment]
Any news on this.
Users are pushing for this to work.
I am loathed to back them out and go with anything else as this fits there needs perfectly!
fguillot please would you consider spending a little time on this for us.
I'm sure they would arrange a contribution to a worthy cause of your choosing if needs be.
I don't want to put a value on your work as it is priceless but I am getting a little desperate.

Many thanks.

Rogie

**Comment by Rogieee** [comment]
OK Guys sorry I love this work but I need this time slot function.
Is their an ETA on when this might happen?

I'm getting hassled about it now.

If not can anyone suggest anything else that we can try?

**Comment by PeGa** [comment]
+1 to this. It is a killer feature when using a client which combines several calendars.

**Comment by fguillot** [comment]
Tickets related to the calendar should be posted to the calendar plugin bug tracker: https://github.com/kanboard/plugin-calendar/issues

Thank you
