### ISSUE TITLE
Collapse / Expand individual tasks in board view

### ISSUE THREAD

**Issue by JohnnyGW** [kanboard/kanboard#810]
It would be nice if you could collapse / expand tasks individually by clicking an icon (triangle , plus/minus sign,...). I've found that many times In boards with a big number of tasks I want to expand only one or a small group of tasks. Expanding all tasks moves the focus of my explorer window and I have to scroll down to find the task every time.

**Comment by 2Belette** [comment]
+1

**Comment by grivalta** [comment]
+1

**Comment by bugwatcher** [comment]
This feature request has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project. [Read the FAQ](https://docs.kanboard.org/en/latest/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
