### ISSUE TITLE
Question: Setting for Default sorting order of "My Tasks" in Dashboard

### ISSUE THREAD

**Issue by tekuton** [kanboard/kanboard#830]
Is it possible to have a setting on the dashboard for "My Tasks" to change the default?
I would like the dashboard to be sorted with my default for "My tasks" sorted per "Due Date" and showing the tasks per date in ascending order.
thx

**Comment by jbarotin** [comment]
Hi, 
Any news, I'm interested by this feature too.

**Comment by jbarotin** [comment]
In fact, it should be a setting (not necessarily default). Or better, the user filtering parameters of the dashboard should be stored into a cookie.

**Comment by fguillot** [comment]
I prefer the cookie method because I can make that generic for all tables with sorting. Basically, the last column sorting order used can be stored independently for each table. So each time you display a table your preferred sorting option is used.

**Comment by jbarotin** [comment]
Yes, I think it should a great feature.

**Comment by dopegaar** [comment]
Hi, all!
No news about this?
I'm interested on it! (sort by complexity...).
TIA

**Comment by sbanks15** [comment]
Hi, 

I was wondering if there was any movement on this feature?

Thanks,

Stuart

**Comment by mkromka** [comment]
Hi I would like to sort by priority or sort according to position on the board.
I need to see important things on top without using deadline or due date

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
