### ISSUE TITLE
Hide / show swimlanes user-based

### ISSUE THREAD

**Issue by FilipHens** [kanboard/kanboard#836]
Hello, could it be possible to show or hide swimlanes based on the preferences of a user?
So that not every user of the project sees every swimlane, but only those that are important for him (can be set-up via an admin, checkboxes in usermanagement in the project?)
Would be a great feature for projects with many users, many tasks en multiple swimlanes to maintain a better overview for users.

**Comment by Phryxe** [comment]
I guess my request concerns the same feature. When filtering on a user I only want to see the swimlanes opened where there is assigned tasks to this user.

**Comment by fguillot** [comment]
I do not plan to add such feature. If you really need that, the best way is to contribute.
