### ISSUE TITLE
Account payment fee should be tied to projet, not account

### ISSUE THREAD

**Issue by erixtekila** [kanboard/kanboard#848]
While it's a nice feature to tracks and budget a project, it'd be nice to be able to configure an amount based on each projet for each account.
I don't sell my services at the same price.

Meanwhile, it should be possible to define multiple hour amount, because one person could have multiple type of task in a project, not requiring the same value.

**Comment by fguillot** [comment]
Feature requests for budget plugins are here: https://github.com/kanboard/plugin-budget/issues
