### ISSUE TITLE
Predefined subtasks lists

### ISSUE THREAD

**Issue by freekoder** [kanboard/kanboard#850]
It would be nice to have predefined templates of subtasks. It would allow to create task with set of subtasks instead of manual creation of subtasks. Predefined subtasks lists should be associated with project and have a possibility to choose one at task creation.

**Comment by arielist** [comment]
I was just thinking about this. Often I break down huge tasks into smaller batches to improve my workflow, and I like to create tasks like "content development batch" with several related subtasks that represent the chunk I want to accomplish. It would be great to either have the option to make template tasks that know they will have 3 subtasks, or even better a way to easily add subtasks from the main task creation screen.

Thanks for a great product.

**Comment by AlgyTaylor** [comment]
This would be very handy for me too ... it'd be nice to automatically add something like 'write documentation' and 'do testing' for any new software development task I have, so that it doesn't get sidelined at any point

**Comment by raidlman** [comment]
I would like to see that feature too.

**Comment by wiLLow86** [comment]
Yeah, good idea :-) :+1:

**Comment by DoumeDuSud** [comment]
you can already done it by creat a task and his subtask, let it on the side of you project (or in a dedicate project name for exemple "template")
then you just duplicate teh task each time you need.

I use it very often and it's work great

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
