### ISSUE TITLE
Documentation questions : Manual user time tracking and tasks status

### ISSUE THREAD

**Issue by erixtekila** [kanboard/kanboard#852]
The docs should IMHO be a little more explicit about subtasks time tracking in relation with budget evaluation. 
As I understand it, the status of a task is tracked in order to compute its time, then cost.
The status seems to be represented by the column, am I right ?

"todo", "progress" and "done" are reserved column names.
When translated, do they correspond to (FR) "Prêt", "En cours" and "Terminé" ?

The system tracks the transition from one column (status) to another.
Cost is determined from these changes. There are no user actions.

BTW, if I'd like to manage an already begun project, with budgets.
How could I affect costs on tasks that have already been done ?
Could, for example, the project manager role, be able to add some manually ?
It could be done one a task with status put to 'done' at first glance.

Another question : these status are set by default.
Users that organise columns in another way could not get subtasks time tracking, then ?

To finish, it would be interesting to document the different status a task could have :
- what is the meaning of a closed task : not taken into account or finished
- the difference of a task in the done column and a closed one
- the way time tracking behave in regard to closed tasks

**Comment by fguillot** [comment]
The budget is based on the user hourly rate and the time spent on tasks, not status.
