### ISSUE TITLE
[FR] Email Notifications for Tasks with Due Dates  

### ISSUE THREAD

**Issue by levlaz** [kanboard/kanboard#858]
It would be nice to have email notifications when a task is approaching its due date. 

Ideally there would be a global setting to enable notifications when a task is assigned to a user and has a due date. Perhaps there could be configurable times for the notifications to go out (1 day, 1 week, etc..)

**Comment by fguillot** [comment]
It's already possible, see https://github.com/fguillot/kanboard/blob/master/docs/cli.markdown#send-notifications-for-overdue-tasks

The only missing part is the configurable time.

**Comment by sha-marsig** [comment]
The Link above is not working. Where I can find the documentation to setup the notification on due date? Currently I don't receive any notifications on time settings.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
