### ISSUE TITLE
Download all attachments

### ISSUE THREAD

**Issue by freekoder** [kanboard/kanboard#866]
Hi again. In my projects I have tasks with many attachments and it hard to get them one by one.
It would be usefull to have download link for all attachments as single archive

**Comment by DoumeDuSud** [comment]
+1 for this feature
and also if it's possible to download the screen captures

**Comment by tencrocs** [comment]
+1 for this feature as well
Database + attachments backup would be great

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
