### ISSUE TITLE
Easy way to change Due Date

### ISSUE THREAD

**Issue by oazabir** [kanboard/kanboard#888]
It would be very handy to be able to click on the calendar icon on a card and have a popup date picker to change the due date. We change due dates quite frequently and it takes quite some steps to go to Edit Task -> Change date -> Save -> Back to board.

**Comment by oliviermaridat** [comment]
On the board, if you click on a task number, you will see a dropdown list allowing you to edit the task (and its due date) on the fly. Good enough?

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
