### ISSUE TITLE
Background updates / Auto-update

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/kanboard#894]
Do you think it'd be possible to do a background update, or maybe a one-click, browser-side update for Kanboard. It'd be similar to the one you see in Wordpress ... I think that'd help users keep up to date with the latest and greatest version of Kanboard, which IMO would be a good thing.

**Comment by shimza** [comment]
Agreed.

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature, mostly for security reasons. Only files stored in the data folder should be writeable by the web server user.
