### ISSUE TITLE
Quick task edit button in column view

### ISSUE THREAD

**Issue by raphaelbastide** [kanboard/kanboard#900]
Editing an existing task from the column view always require 2 clicks, I suggest to add or change a link to direct edit the task. I am personally more interested in the Edit Task screen than the Show task screen. What about the other users?

**Comment by raphaelbastide** [comment]
I just discovered the edition drowpdown menu by clicking on the tag ID. Handy! But a bit hidden an it still requires two clicks.

**Comment by raphaelbastide** [comment]
Just a suggestion:

![capture d ecran_2015-07-05_15-04-19](https://cloud.githubusercontent.com/assets/193122/8511862/5a145686-2328-11e5-82e5-be11c207f86b.png)


A quick edit icon is at the bottom left corner of each box.

**Comment by DoumeDuSud** [comment]
thanks @raphaelbastide I just discover this menu :-)

**Comment by krustymars** [comment]
+1 on this request, it would be really a nice improvement for usability

**Comment by fguillot** [comment]
PR #3344 which implement this feature has been merged.
