### ISSUE TITLE
epic board 

### ISSUE THREAD

**Issue by kwijk** [kanboard/kanboard#901]
As a software developer I am involved in working out epic stories into user stories. User stories are split up into tasks. Currently in kanboard one can create a subtask. but I want something more visual so that:
- work breakdowns (from epic, via user story to tasks is) can be created during discussions with product owner, e.g. in order to get requirements clear.
- project progress can be evaluated at different levels (by different roles: end user want epic level progress, product owner want user story progress, developer, project manager may want task level progress etc).

See for an example: http://his-scrum-masters-voice.blogspot.nl/2012/10/expanded-epic-boards-framework-to.html

**Comment by mekhanique** [comment]
This would be very interesting as a plugin type module that could interface with kanboard, overlay it and generate projects/tasks/subtasks from the data, link to those tasks and provide the analytics around the project back up the chain.

**Comment by kwijk** [comment]
If that can be done through a plugin thats perfect for me. 

Kanboard already allows to assign child parent relations e.g. through the 'Add a link' feature.

What I think would be great is to have a tree view of all items on a board (or all items in a single swimlane etc) that visually shows these links. Much like a tree view in your filebrowser that shows a directory tree.  

Some ideas:
1. Maybe through a plugin it is possible to get all task in a swimlane, figure out their parent/child relations and display the items as a tree of items.   
2. In the same view a user could create a new child item for a specific tasks. This would create a new task and in addition automatically adds the child - parent links (similar to what is already possible via 'Add a link'.  
3. The cost/progress of each parent item can be defined as the cumulative cost/progress of all the child items and the parent itself.
4. For the default projects columns (Backlog, Ready, Work in progress, Done) the tree - view could  replace the backlog column: any item in the tree view has a corresponding item in one of the ther columns. That is, while all items move from Ready, via WIP to Done, the tree view shows item progress go from 0 to 100%.

**Comment by xavividal** [comment]
Look at #1165, I'm implementing a graph page to see all the task dependencies. Feel free to test and to comment.

**Comment by iPublicis** [comment]
As a PO I feel this need to create Epics and then slash then in more workable user stories. This would be great. I usually use Atlassian Jira and I do this often :)

**Comment by xavividal** [comment]
As a suggestion, you can create two boards: the kanban one with tasks and another one with epics.

In the Epics board you can represent tasks as epics and relate the childs tasks placed in the kanban board. As a plus, with my plugin Relationgraph you can check the dependencies.

In the Epic board you can move the "epic/task" through the columns to visualize the status of each epic.

It works for me !

**Comment by fguillot** [comment]
I'm closing this ticket. I let the community develop such feature as plugin.
