### ISSUE TITLE
Add a Field From

### ISSUE THREAD

**Issue by bdrayer** [kanboard/kanboard#908]
Hi,

It would be great to add a field "from", with the same users as assignee, to allow tracking of who asked for it when you use your wonderful product for ticket management. I actually put it on the title but it will be best to have it on a separate field and allow to make a search on it.

Thanks in advance if you do it. I wish I can do it myself but my knowledge in PHP are weak.

**Comment by bdrayer** [comment]
Hi,

It would also be great if an admin can post comment or files as a different user to better allow to follow the discussion if the user make a phone for example (and not a post on kanboard directly)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
