### ISSUE TITLE
Provide documentation in other formats

### ISSUE THREAD

**Issue by jniggemann** [kanboard/kanboard#909]
Currently, the documentation is available online at http://kanboard.net/documentation.
While the documentation itself is great, it'd be useful to have it in other formats, too.
Please also create downloadable PDFs, ebook-formats could be useful, too.

IMHO pandoc would be a good choice for this.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
