### ISSUE TITLE
Due date editing on task summary screen

### ISSUE THREAD

**Issue by oazabir** [kanboard/kanboard#916]
After getting task due notification, we click on task, go to summary screen. But there we cannot change due date. We have to go to edit task. It would save one step if the due date is available on task summary screen. 

Another very useful option would be to produce a link that takes to the board, but also pops up the task in editing mode. As if it has automatically clicked the task number -> Edit task link.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
