### ISSUE TITLE
prevent deleting last user / manager from 'List of authorized users'

### ISSUE THREAD

**Issue by Busfreak** [kanboard/kanboard#932]
It is possible to delete every, even the last user and the projectmanager (yourself) from the 'List of authorized users' as projectmanager. Better prevent the deletion of manager and / or last user.

THX, Martin

**Comment by levlaz** [comment]
Even if you remove every user (which is not a valid use case, so it would have to be by mistake), the project owner can still see every project under `?controller=ProjectListController&action=show` which would allow them to correct this error.

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
