### ISSUE TITLE
Task concurrent edition "locking" system?

### ISSUE THREAD

**Issue by nekohayo** [kanboard/kanboard#944]
I'm not sure how complicated live collaborative task edition would be (my guess is: "very"), so I'm proposing a more primitive safety system: a lock.

I can't trust my users/colleagues to not simultaneously try to edit the same task, so I'm thinking there should be some sort of locking system like some wikis (ex: moinmoin) have, where a task is "locked" for edition by others while someone is currently editing something in it, perhaps with a timeout in case the browser does not touch it for an hour. Other users trying to edit the task would be prevented from doing so (or at least notified with a big huge warning needing a confirmation to break the lock?)

**Comment by salomonderossi** [comment]
+1 I do have this case from time to time. Then the edits of one user are gone...

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
