### ISSUE TITLE
[Feature] Show Task Description Contents on Hover Over on Public Board Link

### ISSUE THREAD

**Issue by testarea1** [kanboard/kanboard#946]
Possible to have the option to show Task Description contents on hover on the Public board link document image `?controller=board&action=readonly` like it does on the `?controller=board&action=show` board page?

**Comment by testarea1** [comment]
Actually, it looks like the Public board has the description link the same as the logged in board but it's not pulling the description (only says "Description" on hover on the Public link). They both have the following for example:

`<span title="Description" class="task-board-tooltip" data-href="?controller=board&amp;action=description&amp;task_id=6&amp;project_id=1">`

Not sure why the Public link it's pulling the description.

**Comment by mrfyx** [comment]
I think it is a bug, no ? Because it is possible to access to the description when you click on the task anyway.

**Comment by fguillot** [comment]
It's not a bug, it's the expected behavior, Javascript code is not loaded in the public view. You can always read the description by clicking on the task title.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after 2 years. If you still need this feature, you should consider contributing to this open-source project.
