### ISSUE TITLE
Tasks w/future dated StartDate iCal export incorrectly.

### ISSUE THREAD

**Issue by neurocis** [kanboard/kanboard#968]
It looks like an assumption was made that all task start dates would be in the past as the iCal export seems to always have the date range being startdate<-->now. I would think it would always be startdate<->duedate with observation of the assignee's timetable (not book entire day).

Ideally it would be nice to have it only plot out hours to the total estimated time at the task level, where subtasks represent actual time?

Cheers.

**Comment by fguillot** [comment]
The iCal feed contains tasks in the range -2 months to +6 months. See https://github.com/kanboard/kanboard/blob/master/app/Controller/ICalendarController.php#L92-L93
