### ISSUE TITLE
[FR] Record progess for subtasks for accumulative tickets

### ISSUE THREAD

**Issue by raidlman** [kanboard/kanboard#977]
We would like to create accumulative tickets (same subtasks for a number of parts) where you can monitor the progress of the subtasks for each of the parts. The subtasks do not necessarily depend on each other.

Something like:
### Subtasks:

|  | dev1 | dev2 | dev3 | dev4 | dev5 |
| --- | --- | --- | --- | --- | --- |
| prepare case |  | done | in progress |  | done |
| prepare electronics | done | in progress | done | done | done |
| test electronics | in progress |  |  | done | done |
| assamble parts |  |  |  |  | in progress |

It would be nice to have the same checkboxes like in regular subtasks (changing the status by clicking on them).

**Comment by oliviermaridat** [comment]
Just a question: who / what are the parts in your example? Is it "dev1", ... ? These are the name of the developers?

**Comment by raidlman** [comment]
Sorry for the confusion:
dev1 --> device 1
dev2 --> device 2
etc.

Basically, my idea is to make the time tracking column expandable (with n times the same subtask) and to keep all other columns (Title, Assignee, Actions).

**Comment by fguillot** [comment]
Unfortunately, I do not plan to add such feature into Kanboard. I prefer to keep the software simple, the number of features is voluntary limited. The best approach is probably to write a custom plugin.

Thank you for your understanding
