### ISSUE TITLE
Substasks time tracking should be tied to substasks time settings 

### ISSUE THREAD

**Issue by erixtekila** [kanboard/kanboard#979]
While it's nice to be able to define time for each subtask, i wonder why modifying time spent from the subtask doesn't affect the subtask time tracked one.

**Comment by fguillot** [comment]
Can you give an example?

**Comment by erixtekila** [comment]
Sure !
If you modifiy afterward the time spent on a subtask, it won't be affected to the budget.
Budget should be tied to substask, even when you set a different time spent on it.

**Comment by fguillot** [comment]
Ok, I understand now, you didn't mention it was for the budget the first time.

The budget is based on the "subtask timer" table at the moment, this why it's not affected but that can be improved.

**Comment by erixtekila** [comment]
Greatly appreciated !

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity after more than 1 year. If you still need this feature, you should consider contributing to this open-source project.
