### ISSUE TITLE
Cost per Task instead of Cost per Hour

### ISSUE THREAD

**Issue by Sorasma** [kanboard/kanboard#989]
I , and think that many users, have projects where we have tasks that have fixed price, a pay per completed task price, and as I see now in kanboard we can't add expense with cost per completed task, only cost per hour/time spent. And bad news is that we can't manualy add say more hours so that we can make the expense be the real one.
Is it possible to also add that feature?

**Comment by Alexvander** [comment]
Yes, this is indeed a feature that we are missing. Sometimes when we have cost per action (cost per task/subtask) we don't use the "budget" analytics anymore because the calculations are wrong there.

So, I'd like to have this feature too

**Comment by choney3** [comment]
+1 for this feature. Without the pay per task cost the budget analytics is worthless, it's just giving out wrong data.

@fguillot can you add this option too?

**Comment by richyboy4** [comment]
I'm also missing this feature. All tools with budget calculation should have this one. Hope to have this option soon.

**Comment by antonioseric** [comment]
+1, this will be cool to have

**Comment by shimza** [comment]
Yes, would be a great feature.

**Comment by 8bit-hero** [comment]
This would be very useful

**Comment by fguillot** [comment]
Feature requests for the budget plugin is there: https://github.com/kanboard/plugin-budget/issues
