### ISSUE TITLE
integration into taskd

### ISSUE THREAD

**Issue by jasonsmith0** [kanboard/kanboard#990]
Would be nice to have some support to integrate into task warrior.
This would allow the famous task cli program (and related tools http://taskwarrior.org/tools/)
 to work with kanboard.

API http://taskwarrior.org/docs/hooks2.html

**Comment by fguillot** [comment]
Closing this ticket due to inactivity and lack of interest by the community.

**Comment by DaBlitzStein** [comment]
Please open again. This is a must-have.

**Comment by snth** [comment]
+1 I'd also like this.

**Comment by MartyLake** [comment]
+1 !!!!

**Comment by FiSHYsolutions** [comment]
+1

**Comment by jslot** [comment]
yes
